{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Delay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kDistortionParam_Delay@kDistortionParam_Delay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kDistortionParam_Delay"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kDistortionParam_Delay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kDistortionParam_Delay"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kDistortionParam_Delay"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_CubicTerm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_CubicTerm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_CubicTerm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_CubicTerm"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_CubicTerm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_cubicterm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Decay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_Decay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Decay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_Decay"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_Decay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_decay"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Decimation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_Decimation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Decimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_Decimation"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_Decimation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_decimation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_DecimationMix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_DecimationMix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_DecimationMix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_DecimationMix"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_DecimationMix",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_decimationmix"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Delay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_Delay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Delay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_Delay"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_Delay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_delay"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_DelayMix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_DelayMix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_DelayMix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_DelayMix"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_DelayMix",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_delaymix"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_FinalMix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_FinalMix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_FinalMix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_FinalMix"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_FinalMix",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_finalmix"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_LinearTerm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_LinearTerm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_LinearTerm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_LinearTerm"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_LinearTerm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_linearterm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_PolynomialMix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_PolynomialMix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_PolynomialMix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_PolynomialMix"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_PolynomialMix",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_polynomialmix"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModBalance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_RingModBalance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModBalance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_RingModBalance"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_RingModBalance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_ringmodbalance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModFreq1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_RingModFreq1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModFreq1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_RingModFreq1"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_RingModFreq1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_ringmodfreq1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModFreq2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_RingModFreq2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModFreq2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_RingModFreq2"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_RingModFreq2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_ringmodfreq2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModMix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_RingModMix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModMix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_RingModMix"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_RingModMix",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_ringmodmix"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Rounding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_Rounding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Rounding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_Rounding"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_Rounding",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_rounding"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_SoftClipGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_SoftClipGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_SoftClipGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_SoftClipGain"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_SoftClipGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_softclipgain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_SquaredTerm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDistortionParam_SquaredTerm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_SquaredTerm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDistortionParam_SquaredTerm"
        }
      ],
      "role": "symbol",
      "title": "kDistortionParam_SquaredTerm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdistortionparam_squaredterm"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_CubicTerm",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Decay",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Decimation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_DecimationMix",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_DelayMix",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_FinalMix",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_LinearTerm",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_PolynomialMix",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModBalance",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModFreq1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModFreq2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModMix",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Rounding",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_SoftClipGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_SquaredTerm"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kDistortionParam_Delay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_Delay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_CubicTerm",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Decay",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Decimation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_DecimationMix",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_DelayMix",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_FinalMix",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_LinearTerm",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_PolynomialMix",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModBalance",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModFreq1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModFreq2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_RingModMix",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_Rounding",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_SoftClipGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDistortionParam_SquaredTerm"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kDistortionParam_Delay"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_DelayMix/title",
          "value": "kDistortionParam_DelayMix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_DelayMix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_DelayMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_LinearTerm/title",
          "value": "kDistortionParam_LinearTerm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_LinearTerm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_LinearTerm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_Decay/title",
          "value": "kDistortionParam_Decay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_Decay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_Decay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_Decimation/title",
          "value": "kDistortionParam_Decimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_Decimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_Decimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_Rounding/title",
          "value": "kDistortionParam_Rounding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_Rounding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_Rounding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_DecimationMix/title",
          "value": "kDistortionParam_DecimationMix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_DecimationMix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_DecimationMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_PolynomialMix/title",
          "value": "kDistortionParam_PolynomialMix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_PolynomialMix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_PolynomialMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_CubicTerm/title",
          "value": "kDistortionParam_CubicTerm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_CubicTerm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_CubicTerm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_FinalMix/title",
          "value": "kDistortionParam_FinalMix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_FinalMix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_FinalMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_RingModBalance/title",
          "value": "kDistortionParam_RingModBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_RingModBalance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_RingModBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_RingModFreq1/title",
          "value": "kDistortionParam_RingModFreq1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_RingModFreq1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_RingModFreq1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_Delay/title",
          "value": "kDistortionParam_Delay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_Delay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_Delay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_SoftClipGain/title",
          "value": "kDistortionParam_SoftClipGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_SoftClipGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_SoftClipGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_RingModFreq2/title",
          "value": "kDistortionParam_RingModFreq2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_RingModFreq2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_RingModFreq2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_RingModMix/title",
          "value": "kDistortionParam_RingModMix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_RingModMix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_RingModMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_SquaredTerm/title",
          "value": "kDistortionParam_SquaredTerm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDistortionParam_SquaredTerm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDistortionParam_SquaredTerm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kdistortionparam_delay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kdistortionparam_delay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
