{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_AttackTime"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kDynamicsProcessorParam_Threshold@kDynamicsProcessorParam_AttackTime",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kDynamicsProcessorParam_AttackTime"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kDynamicsProcessorParam_AttackTime"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kDynamicsProcessorParam_AttackTime"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_AttackTime"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_AttackTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_AttackTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_AttackTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_AttackTime"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_AttackTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_attacktime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_CompressionAmount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_CompressionAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_CompressionAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_CompressionAmount"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_CompressionAmount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_compressionamount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionRatio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ExpansionRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ExpansionRatio"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_ExpansionRatio",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_expansionratio"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ExpansionThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ExpansionThreshold"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_ExpansionThreshold",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_expansionthreshold"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_HeadRoom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_HeadRoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_HeadRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_HeadRoom"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_HeadRoom",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_headroom"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_InputAmplitude": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_InputAmplitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_InputAmplitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_InputAmplitude"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_InputAmplitude",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_inputamplitude"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_MasterGain": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_MasterGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_MasterGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_MasterGain"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_MasterGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_mastergain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OutputAmplitude": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_OutputAmplitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OutputAmplitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_OutputAmplitude"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_OutputAmplitude",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_outputamplitude"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OverallGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_OverallGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OverallGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_OverallGain"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_OverallGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_overallgain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ReleaseTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ReleaseTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ReleaseTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_ReleaseTime"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_ReleaseTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_releasetime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_Threshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_Threshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_Threshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDynamicsProcessorParam_Threshold"
        }
      ],
      "role": "symbol",
      "title": "kDynamicsProcessorParam_Threshold",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kdynamicsprocessorparam_threshold"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_CompressionAmount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionRatio",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionThreshold",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_HeadRoom",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_InputAmplitude",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_MasterGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OutputAmplitude",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ReleaseTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_Threshold",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OverallGain"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kDynamicsProcessorParam_AttackTime"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_AttackTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_CompressionAmount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionRatio",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ExpansionThreshold",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_HeadRoom",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_InputAmplitude",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_MasterGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OutputAmplitude",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_ReleaseTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_Threshold",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kDynamicsProcessorParam_OverallGain"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kDynamicsProcessorParam_AttackTime"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_OverallGain/title",
          "value": "kDynamicsProcessorParam_OverallGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_OverallGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_OverallGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ExpansionRatio/title",
          "value": "kDynamicsProcessorParam_ExpansionRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ExpansionRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_ExpansionRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_MasterGain/title",
          "value": "kDynamicsProcessorParam_MasterGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_MasterGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_MasterGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ReleaseTime/title",
          "value": "kDynamicsProcessorParam_ReleaseTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ReleaseTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_ReleaseTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_HeadRoom/title",
          "value": "kDynamicsProcessorParam_HeadRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_HeadRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_HeadRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ExpansionThreshold/title",
          "value": "kDynamicsProcessorParam_ExpansionThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_ExpansionThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_ExpansionThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_CompressionAmount/title",
          "value": "kDynamicsProcessorParam_CompressionAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_CompressionAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_CompressionAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_Threshold/title",
          "value": "kDynamicsProcessorParam_Threshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_Threshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_Threshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_AttackTime/title",
          "value": "kDynamicsProcessorParam_AttackTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_AttackTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_AttackTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_OutputAmplitude/title",
          "value": "kDynamicsProcessorParam_OutputAmplitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_OutputAmplitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_OutputAmplitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_InputAmplitude/title",
          "value": "kDynamicsProcessorParam_InputAmplitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kDynamicsProcessorParam_InputAmplitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDynamicsProcessorParam_InputAmplitude"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kdynamicsprocessorparam_attacktime"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kdynamicsprocessorparam_attacktime"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
