{
  "abstract": [
    {
      "text": "The audio channel layout for your application.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientChannelLayout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kExtAudioFileProperty_FileDataFormat@kExtAudioFileProperty_ClientChannelLayout",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kExtAudioFileProperty_ClientChannelLayout"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
        "text": "ExtAudioFilePropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kExtAudioFileProperty_ClientChannelLayout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kExtAudioFileProperty_ClientChannelLayout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_ClientChannelLayout"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFilePropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
              "text": "ExtAudioFilePropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The audio channel layout for your application. Value is a read/write ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/AudioChannelLayout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " struct.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property’s value specifies the channel layout of the buffers in an ",
              "type": "text"
            },
            {
              "code": "AudioBufferList",
              "type": "codeVoice"
            },
            {
              "text": " list that you pass to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileRead(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions. This layout may be different from the file’s channel layout, in which case the extended audio file object’s underlying audio converter performs remapping. This property must be set after setting the ",
              "type": "text"
            },
            {
              "code": "kExtAudioFileProperty_ClientDataFormat",
              "type": "codeVoice"
            },
            {
              "text": " property, and the number of channels in the two layouts must match.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFilePropertyID": {
      "abstract": [
        {
          "text": "An audio file object property identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFilePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "role": "symbol",
      "title": "ExtAudioFilePropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extaudiofilepropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileRead(_:_:_:)": {
      "abstract": [
        {
          "text": "Performs a synchronous, sequential read operation on an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtAudioFileRead"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFileRef",
          "text": "ExtAudioFileRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioBufferList",
          "text": "AudioBufferList"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileRead(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtAudioFileRead"
        }
      ],
      "role": "symbol",
      "title": "ExtAudioFileRead(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extaudiofileread(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)": {
      "abstract": [
        {
          "text": "Performs a synchronous, sequential write operation on an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtAudioFileWrite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFileRef",
          "text": "ExtAudioFileRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioBufferList",
          "text": "AudioBufferList"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtAudioFileWrite"
        }
      ],
      "role": "symbol",
      "title": "ExtAudioFileWrite(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extaudiofilewrite(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioConverter": {
      "abstract": [
        {
          "text": "The audio converter object associated with the extended audio file object, if a converter is associated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_AudioConverter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioConverter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_AudioConverter"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_AudioConverter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_audioconverter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioFile": {
      "abstract": [
        {
          "text": "The audio file object associated with the extended audio file object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_AudioFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_AudioFile"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_AudioFile",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_audiofile"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientChannelLayout": {
      "abstract": [
        {
          "text": "The audio channel layout for your application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_ClientChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_clientchannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientDataFormat": {
      "abstract": [
        {
          "text": "The audio stream format for your application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientDataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientDataFormat"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_ClientDataFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_clientdataformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientMaxPacketSize": {
      "abstract": [
        {
          "text": "Your application audio data format’s maximum packet size, in bytes. Value is a read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientMaxPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientMaxPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientMaxPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_ClientMaxPacketSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_clientmaxpacketsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_CodecManufacturer": {
      "abstract": [
        {
          "text": "The manufacturer of the codec to be used by the extended audio file object. Value is a read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_CodecManufacturer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_CodecManufacturer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_CodecManufacturer"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_CodecManufacturer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_codecmanufacturer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ConverterConfig": {
      "abstract": [
        {
          "text": "The configuration of the extended audio file object’s associated audio converter, as specified by the ",
          "type": "text"
        },
        {
          "code": "kAudioConverterPropertySettings",
          "type": "codeVoice"
        },
        {
          "text": " property. Value is a read/write ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ConverterConfig"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ConverterConfig",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ConverterConfig"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_ConverterConfig",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_converterconfig"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileChannelLayout": {
      "abstract": [
        {
          "text": "A file’s channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_FileChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_filechannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileDataFormat": {
      "abstract": [
        {
          "text": "A file’s data format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileDataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileDataFormat"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_FileDataFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_filedataformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileLengthFrames": {
      "abstract": [
        {
          "text": "The associated audio file’s length in sample frames. Value is an ",
          "type": "text"
        },
        {
          "code": "SInt64",
          "type": "codeVoice"
        },
        {
          "text": ". For a PCM file, the value is read/write. For a non-PCM file, the value is read-only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileLengthFrames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileLengthFrames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileLengthFrames"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_FileLengthFrames",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_filelengthframes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileMaxPacketSize": {
      "abstract": [
        {
          "text": "The file data format’s maximum packet size, in bytes. Value is a read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileMaxPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileMaxPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileMaxPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_FileMaxPacketSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_filemaxpacketsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBuffer": {
      "abstract": [
        {
          "text": "An audio data buffer. Value is a read/write ",
          "type": "text"
        },
        {
          "code": "void*",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_IOBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_IOBuffer"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_IOBuffer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_iobuffer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBufferSizeBytes": {
      "abstract": [
        {
          "text": "The size of the buffer that the extended audio file object’s associated audio converter uses to read or write the associated audio file. Value is a read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_IOBufferSizeBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBufferSizeBytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_IOBufferSizeBytes"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_IOBufferSizeBytes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_iobuffersizebytes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_PacketTable": {
      "abstract": [
        {
          "text": "This property can be used to override the priming and remainder information in an audio file, and also to retrieve the current priming and remainder frames information for an extended audio file object. If the underlying file type does not provide packet table information, attempting to get the value of this property returns an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_PacketTable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_PacketTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_PacketTable"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_PacketTable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_packettable"
    },
    "doc://com.apple.documentation/documentation/CoreAudioTypes/AudioChannelLayout": {
      "abstract": [
        {
          "text": "A structure that specifies a channel layout in a file or in hardware.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLayout"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/AudioChannelLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioChannelLayout",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioChannelLayout"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileDataFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientDataFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_CodecManufacturer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioConverter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioFile",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileMaxPacketSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientMaxPacketSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileLengthFrames",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ConverterConfig",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBufferSizeBytes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBuffer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_PacketTable"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kExtAudioFileProperty_ClientChannelLayout"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_ClientChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileDataFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientDataFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_CodecManufacturer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioConverter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioFile",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileMaxPacketSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientMaxPacketSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileLengthFrames",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ConverterConfig",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBufferSizeBytes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBuffer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_PacketTable"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kExtAudioFileProperty_ClientChannelLayout"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientChannelLayout/title",
          "value": "kExtAudioFileProperty_ClientChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_ClientChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ConverterConfig/title",
          "value": "kExtAudioFileProperty_ConverterConfig"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ConverterConfig/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_ConverterConfig"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_IOBufferSizeBytes/title",
          "value": "kExtAudioFileProperty_IOBufferSizeBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_IOBufferSizeBytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_IOBufferSizeBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileMaxPacketSize/title",
          "value": "kExtAudioFileProperty_FileMaxPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileMaxPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_FileMaxPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_AudioFile/title",
          "value": "kExtAudioFileProperty_AudioFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_AudioFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_AudioFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileWrite(_:_:_:)/title",
          "value": "ExtAudioFileWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileWrite(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFileWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioTypes~1AudioChannelLayout/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioChannelLayout"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_AudioConverter/title",
          "value": "kExtAudioFileProperty_AudioConverter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_AudioConverter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_AudioConverter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileChannelLayout/title",
          "value": "kExtAudioFileProperty_FileChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_FileChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_PacketTable/title",
          "value": "kExtAudioFileProperty_PacketTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_PacketTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_PacketTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileLengthFrames/title",
          "value": "kExtAudioFileProperty_FileLengthFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileLengthFrames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_FileLengthFrames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFilePropertyID/title",
          "value": "ExtAudioFilePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFilePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFilePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_CodecManufacturer/title",
          "value": "kExtAudioFileProperty_CodecManufacturer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_CodecManufacturer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_CodecManufacturer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileDataFormat/title",
          "value": "kExtAudioFileProperty_FileDataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileDataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_FileDataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientDataFormat/title",
          "value": "kExtAudioFileProperty_ClientDataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientDataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_ClientDataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileRead(_:_:_:)/title",
          "value": "ExtAudioFileRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileRead(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFileRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_IOBuffer/title",
          "value": "kExtAudioFileProperty_IOBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_IOBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_IOBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientMaxPacketSize/title",
          "value": "kExtAudioFileProperty_ClientMaxPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientMaxPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_ClientMaxPacketSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kextaudiofileproperty_clientchannellayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kextaudiofileproperty_clientchannellayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
