{
  "abstract": [
    {
      "text": "This property can be used to override the priming and remainder information in an audio file, and also to retrieve the current priming and remainder frames information for an extended audio file object. If the underlying file type does not provide packet table information, attempting to get the value of this property returns an error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_PacketTable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kExtAudioFileProperty_FileDataFormat@kExtAudioFileProperty_PacketTable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kExtAudioFileProperty_PacketTable"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
        "text": "ExtAudioFilePropertyID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kExtAudioFileProperty_PacketTable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kExtAudioFileProperty_PacketTable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_PacketTable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFilePropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
              "text": "ExtAudioFilePropertyID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By setting this property with a nonnegative number (which may be the value ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": "), you override the corresponding settings for the values contained in the file. If you use a value of ",
              "type": "text"
            },
            {
              "code": "-1",
              "type": "codeVoice"
            },
            {
              "text": " for either the priming or remainder frames, the extended audio file object uses the corresponding value stored in the file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Retrieving the value of this property always retrieves the value the extended audio file object is using, whether derived from the file or from your override.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To determine the value in the file, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyPacketTableInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the property is set, only the remaining and priming values are used. Set the ",
              "type": "text"
            },
            {
              "code": "mNumberValidFrames",
              "type": "codeVoice"
            },
            {
              "text": " field of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePacketTableInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " struct to zero. For example, a file encoded using AAC may have 2112 samples of priming at the start of the file and a remainder of 823 samples at the end. When an extended audio file object returns decoded samples to you, it trims off the ",
              "type": "text"
            },
            {
              "text": " at the start of the file, and trims off the ",
              "type": "text"
            },
            {
              "text": " at the end. It gets these numbers initially from the file. A common use case for overriding this would be to set the priming and remainder samples to ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ". In this example, you would retrieve an additional 2112 samples of silence from the start of the file and 823 samples of silence at the end of the file (silence, because the encoders use silence to pad out these priming and remainder samples).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePacketTableInfo": {
      "abstract": [
        {
          "text": "Contains information about the number of valid frames in a file and where they begin and end.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFilePacketTableInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePacketTableInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFilePacketTableInfo"
        }
      ],
      "role": "symbol",
      "title": "AudioFilePacketTableInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilepackettableinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFilePropertyID": {
      "abstract": [
        {
          "text": "An audio file object property identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFilePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "role": "symbol",
      "title": "ExtAudioFilePropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extaudiofilepropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services": {
      "abstract": [
        {
          "text": "Read or write a variety of audio data to or from disk or a memory buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyPacketTableInfo": {
      "abstract": [
        {
          "text": "Gets or sets an audio file packet table information structure for its supporting file types. When setting the structure, the sum of the values of the ",
          "type": "text"
        },
        {
          "code": "mNumberValidFrames",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "mPrimingFrames",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "mRemainderFrames",
          "type": "codeVoice"
        },
        {
          "text": " fields must be the same as the total number of frames in all packets. If not, a ",
          "type": "text"
        },
        {
          "code": "paramErr",
          "type": "codeVoice"
        },
        {
          "text": " is returned. To ensure this result, get the value of the property and make sure the sum of the three values you set has the same sum as the three values you got.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyPacketTableInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFilePropertyID",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioFilePropertyPacketTableInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFilePropertyPacketTableInfo"
        }
      ],
      "role": "symbol",
      "title": "kAudioFilePropertyPacketTableInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiofilepropertypackettableinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioConverter": {
      "abstract": [
        {
          "text": "The audio converter object associated with the extended audio file object, if a converter is associated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_AudioConverter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioConverter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_AudioConverter"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_AudioConverter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_audioconverter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioFile": {
      "abstract": [
        {
          "text": "The audio file object associated with the extended audio file object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_AudioFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_AudioFile"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_AudioFile",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_audiofile"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientChannelLayout": {
      "abstract": [
        {
          "text": "The audio channel layout for your application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_ClientChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_clientchannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientDataFormat": {
      "abstract": [
        {
          "text": "The audio stream format for your application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientDataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientDataFormat"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_ClientDataFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_clientdataformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientMaxPacketSize": {
      "abstract": [
        {
          "text": "Your application audio data format’s maximum packet size, in bytes. Value is a read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientMaxPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientMaxPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ClientMaxPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_ClientMaxPacketSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_clientmaxpacketsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_CodecManufacturer": {
      "abstract": [
        {
          "text": "The manufacturer of the codec to be used by the extended audio file object. Value is a read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_CodecManufacturer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_CodecManufacturer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_CodecManufacturer"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_CodecManufacturer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_codecmanufacturer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ConverterConfig": {
      "abstract": [
        {
          "text": "The configuration of the extended audio file object’s associated audio converter, as specified by the ",
          "type": "text"
        },
        {
          "code": "kAudioConverterPropertySettings",
          "type": "codeVoice"
        },
        {
          "text": " property. Value is a read/write ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ConverterConfig"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ConverterConfig",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_ConverterConfig"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_ConverterConfig",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_converterconfig"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileChannelLayout": {
      "abstract": [
        {
          "text": "A file’s channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_FileChannelLayout",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_filechannellayout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileDataFormat": {
      "abstract": [
        {
          "text": "A file’s data format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileDataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileDataFormat"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_FileDataFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_filedataformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileLengthFrames": {
      "abstract": [
        {
          "text": "The associated audio file’s length in sample frames. Value is an ",
          "type": "text"
        },
        {
          "code": "SInt64",
          "type": "codeVoice"
        },
        {
          "text": ". For a PCM file, the value is read/write. For a non-PCM file, the value is read-only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileLengthFrames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileLengthFrames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileLengthFrames"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_FileLengthFrames",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_filelengthframes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileMaxPacketSize": {
      "abstract": [
        {
          "text": "The file data format’s maximum packet size, in bytes. Value is a read-only ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileMaxPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileMaxPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_FileMaxPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_FileMaxPacketSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_filemaxpacketsize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBuffer": {
      "abstract": [
        {
          "text": "An audio data buffer. Value is a read/write ",
          "type": "text"
        },
        {
          "code": "void*",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_IOBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_IOBuffer"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_IOBuffer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_iobuffer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBufferSizeBytes": {
      "abstract": [
        {
          "text": "The size of the buffer that the extended audio file object’s associated audio converter uses to read or write the associated audio file. Value is a read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_IOBufferSizeBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBufferSizeBytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_IOBufferSizeBytes"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_IOBufferSizeBytes",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_iobuffersizebytes"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_PacketTable": {
      "abstract": [
        {
          "text": "This property can be used to override the priming and remainder information in an audio file, and also to retrieve the current priming and remainder frames information for an extended audio file object. If the underlying file type does not provide packet table information, attempting to get the value of this property returns an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_PacketTable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFilePropertyID",
          "text": "ExtAudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_PacketTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileProperty_PacketTable"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileProperty_PacketTable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileproperty_packettable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileDataFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientDataFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientChannelLayout",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_CodecManufacturer",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioConverter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioFile",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileMaxPacketSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientMaxPacketSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileLengthFrames",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ConverterConfig",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBufferSizeBytes",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBuffer"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kExtAudioFileProperty_PacketTable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_PacketTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileDataFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientDataFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientChannelLayout",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_CodecManufacturer",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioConverter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_AudioFile",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileMaxPacketSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ClientMaxPacketSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_FileLengthFrames",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_ConverterConfig",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBufferSizeBytes",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileProperty_IOBuffer"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kExtAudioFileProperty_PacketTable"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileLengthFrames/title",
          "value": "kExtAudioFileProperty_FileLengthFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileLengthFrames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_FileLengthFrames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePacketTableInfo/title",
          "value": "AudioFilePacketTableInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePacketTableInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePacketTableInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePacketTableInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePacketTableInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_PacketTable/title",
          "value": "kExtAudioFileProperty_PacketTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_PacketTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_PacketTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFilePropertyID/title",
          "value": "ExtAudioFilePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFilePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFilePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileDataFormat/title",
          "value": "kExtAudioFileProperty_FileDataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileDataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_FileDataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileMaxPacketSize/title",
          "value": "kExtAudioFileProperty_FileMaxPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileMaxPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_FileMaxPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_IOBuffer/title",
          "value": "kExtAudioFileProperty_IOBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_IOBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_IOBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_AudioFile/title",
          "value": "kExtAudioFileProperty_AudioFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_AudioFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_AudioFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyPacketTableInfo/title",
          "value": "kAudioFilePropertyPacketTableInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioFilePropertyPacketTableInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFilePropertyPacketTableInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ConverterConfig/title",
          "value": "kExtAudioFileProperty_ConverterConfig"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ConverterConfig/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_ConverterConfig"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_IOBufferSizeBytes/title",
          "value": "kExtAudioFileProperty_IOBufferSizeBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_IOBufferSizeBytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_IOBufferSizeBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientChannelLayout/title",
          "value": "kExtAudioFileProperty_ClientChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_ClientChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_CodecManufacturer/title",
          "value": "kExtAudioFileProperty_CodecManufacturer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_CodecManufacturer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_CodecManufacturer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_AudioConverter/title",
          "value": "kExtAudioFileProperty_AudioConverter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_AudioConverter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_AudioConverter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientDataFormat/title",
          "value": "kExtAudioFileProperty_ClientDataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientDataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_ClientDataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileChannelLayout/title",
          "value": "kExtAudioFileProperty_FileChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_FileChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_FileChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientMaxPacketSize/title",
          "value": "kExtAudioFileProperty_ClientMaxPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileProperty_ClientMaxPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileProperty_ClientMaxPacketSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kextaudiofileproperty_packettable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kextaudiofileproperty_packettable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
