{
  "abstract": [
    {
      "text": "The ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " function was interrupted and the last buffer that you provided was successfully written to disk.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputConsumed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kExtAudioFileError_CodecUnavailableInputConsumed@kExtAudioFileError_CodecUnavailableInputConsumed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kExtAudioFileError_CodecUnavailableInputConsumed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kExtAudioFileError_CodecUnavailableInputConsumed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kExtAudioFileError_CodecUnavailableInputConsumed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_CodecUnavailableInputConsumed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For additional information, refer to ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioGuidelinesByAppType/AudioGuidelinesByAppType.html#//apple_ref/doc/uid/TP40007875-CH11",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40007875",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)": {
      "abstract": [
        {
          "text": "Performs a synchronous, sequential write operation on an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtAudioFileWrite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ExtAudioFileRef",
          "text": "ExtAudioFileRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioBufferList",
          "text": "AudioBufferList"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtAudioFileWrite"
        }
      ],
      "role": "symbol",
      "title": "ExtAudioFileWrite(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extaudiofilewrite(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteBufferOverflow": {
      "abstract": [
        {
          "text": "An asynchronous write operation could not be completed in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_AsyncWriteBufferOverflow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteBufferOverflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_AsyncWriteBufferOverflow"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_AsyncWriteBufferOverflow",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_asyncwritebufferoverflow"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteTooLarge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_AsyncWriteTooLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteTooLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_AsyncWriteTooLarge"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_AsyncWriteTooLarge",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_asyncwritetoolarge"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputConsumed": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function was interrupted and the last buffer that you provided was successfully written to disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_CodecUnavailableInputConsumed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputConsumed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_CodecUnavailableInputConsumed"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_CodecUnavailableInputConsumed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_codecunavailableinputconsumed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputNotConsumed": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtAudioFileWrite(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function was interrupted and the last buffer that you provided was ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "not",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " successfully written to disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_CodecUnavailableInputNotConsumed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputNotConsumed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_CodecUnavailableInputNotConsumed"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_CodecUnavailableInputNotConsumed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_codecunavailableinputnotconsumed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidChannelMap": {
      "abstract": [
        {
          "text": "The number of channels does not match the specified format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidChannelMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidChannelMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidChannelMap"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidChannelMap",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invalidchannelmap"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidDataFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidDataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidDataFormat"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidDataFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invaliddataformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidOperationOrder": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidOperationOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidOperationOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidOperationOrder"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidOperationOrder",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invalidoperationorder"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidProperty"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidProperty",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invalidproperty"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidPropertySize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidPropertySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidPropertySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidPropertySize"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidPropertySize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invalidpropertysize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidSeek": {
      "abstract": [
        {
          "text": "An attempt to write, or an offset, is out of bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidSeek"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidSeek",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_InvalidSeek"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_InvalidSeek",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_invalidseek"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_MaxPacketSizeUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_MaxPacketSizeUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_MaxPacketSizeUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_MaxPacketSizeUnknown"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_MaxPacketSizeUnknown",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_maxpacketsizeunknown"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_NonPCMClientFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_NonPCMClientFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_NonPCMClientFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kExtAudioFileError_NonPCMClientFormat"
        }
      ],
      "role": "symbol",
      "title": "kExtAudioFileError_NonPCMClientFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kextaudiofileerror_nonpcmclientformat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioGuidelinesByAppType/AudioGuidelinesByAppType.html#//apple_ref/doc/uid/TP40007875-CH11": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioGuidelinesByAppType/AudioGuidelinesByAppType.html#//apple_ref/doc/uid/TP40007875-CH11",
      "title": "Audio Guidelines By App Type",
      "titleInlineContent": [
        {
          "text": "Audio Guidelines By App Type",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioGuidelinesByAppType/AudioGuidelinesByAppType.html#//apple_ref/doc/uid/TP40007875-CH11"
    },
    "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40007875": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40007875",
      "title": "Audio Session Programming Guide",
      "titleInlineContent": [
        {
          "text": "Audio Session Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40007875"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Result-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputNotConsumed",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidProperty",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidPropertySize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_NonPCMClientFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidChannelMap",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidOperationOrder",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidDataFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_MaxPacketSizeUnknown",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidSeek",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteTooLarge",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteBufferOverflow"
      ],
      "title": "Result Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kExtAudioFileError_CodecUnavailableInputConsumed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_CodecUnavailableInputConsumed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Result-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_CodecUnavailableInputNotConsumed",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidProperty",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidPropertySize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_NonPCMClientFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidChannelMap",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidOperationOrder",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidDataFormat",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_MaxPacketSizeUnknown",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_InvalidSeek",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteTooLarge",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kExtAudioFileError_AsyncWriteBufferOverflow"
              ],
              "title": "Result Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kExtAudioFileError_CodecUnavailableInputConsumed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_NonPCMClientFormat/title",
          "value": "kExtAudioFileError_NonPCMClientFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_NonPCMClientFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_NonPCMClientFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidPropertySize/title",
          "value": "kExtAudioFileError_InvalidPropertySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidPropertySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidPropertySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_CodecUnavailableInputConsumed/title",
          "value": "kExtAudioFileError_CodecUnavailableInputConsumed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_CodecUnavailableInputConsumed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_CodecUnavailableInputConsumed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidOperationOrder/title",
          "value": "kExtAudioFileError_InvalidOperationOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidOperationOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidOperationOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileWrite(_:_:_:)/title",
          "value": "ExtAudioFileWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtAudioFileWrite(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtAudioFileWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidDataFormat/title",
          "value": "kExtAudioFileError_InvalidDataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidDataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidDataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_AsyncWriteTooLarge/title",
          "value": "kExtAudioFileError_AsyncWriteTooLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_AsyncWriteTooLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_AsyncWriteTooLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidSeek/title",
          "value": "kExtAudioFileError_InvalidSeek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidSeek/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidSeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_AsyncWriteBufferOverflow/title",
          "value": "kExtAudioFileError_AsyncWriteBufferOverflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_AsyncWriteBufferOverflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_AsyncWriteBufferOverflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidChannelMap/title",
          "value": "kExtAudioFileError_InvalidChannelMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidChannelMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidChannelMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidProperty/title",
          "value": "kExtAudioFileError_InvalidProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_InvalidProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_InvalidProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_CodecUnavailableInputNotConsumed/title",
          "value": "kExtAudioFileError_CodecUnavailableInputNotConsumed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_CodecUnavailableInputNotConsumed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_CodecUnavailableInputNotConsumed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_MaxPacketSizeUnknown/title",
          "value": "kExtAudioFileError_MaxPacketSizeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kExtAudioFileError_MaxPacketSizeUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kExtAudioFileError_MaxPacketSizeUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kextaudiofileerror_codecunavailableinputconsumed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kextaudiofileerror_codecunavailableinputconsumed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
