{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePower"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kMatrixMixerParam_Volume@kMatrixMixerParam_PreAveragePower",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kMatrixMixerParam_PreAveragePower"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMatrixMixerParam_PreAveragePower"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kMatrixMixerParam_PreAveragePower"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PreAveragePower"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Enable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_Enable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Enable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_Enable"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_Enable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_enable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostAveragePower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostAveragePower"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PostAveragePower",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_postaveragepower"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePowerLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostAveragePowerLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePowerLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostAveragePowerLinear"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PostAveragePowerLinear",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_postaveragepowerlinear"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostPeakHoldLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostPeakHoldLevel"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PostPeakHoldLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_postpeakholdlevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevelLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostPeakHoldLevelLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevelLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PostPeakHoldLevelLinear"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PostPeakHoldLevelLinear",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_postpeakholdlevellinear"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PreAveragePower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PreAveragePower"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PreAveragePower",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_preaveragepower"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePowerLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PreAveragePowerLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePowerLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PreAveragePowerLinear"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PreAveragePowerLinear",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_preaveragepowerlinear"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PrePeakHoldLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PrePeakHoldLevel"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PrePeakHoldLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_prepeakholdlevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevelLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PrePeakHoldLevelLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevelLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_PrePeakHoldLevelLinear"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_PrePeakHoldLevelLinear",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_prepeakholdlevellinear"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Volume": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_Volume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Volume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMatrixMixerParam_Volume"
        }
      ],
      "role": "symbol",
      "title": "kMatrixMixerParam_Volume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmatrixmixerparam_volume"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Enable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePower",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePowerLinear",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevelLinear",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePowerLinear",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevelLinear",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Volume"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMatrixMixerParam_PreAveragePower"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PreAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Enable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePower",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostAveragePowerLinear",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PostPeakHoldLevelLinear",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PreAveragePowerLinear",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_PrePeakHoldLevelLinear",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMatrixMixerParam_Volume"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMatrixMixerParam_PreAveragePower"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PreAveragePower/title",
          "value": "kMatrixMixerParam_PreAveragePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PreAveragePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PreAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_Volume/title",
          "value": "kMatrixMixerParam_Volume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_Volume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_Volume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostPeakHoldLevelLinear/title",
          "value": "kMatrixMixerParam_PostPeakHoldLevelLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostPeakHoldLevelLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PostPeakHoldLevelLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PreAveragePowerLinear/title",
          "value": "kMatrixMixerParam_PreAveragePowerLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PreAveragePowerLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PreAveragePowerLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PrePeakHoldLevelLinear/title",
          "value": "kMatrixMixerParam_PrePeakHoldLevelLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PrePeakHoldLevelLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PrePeakHoldLevelLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostAveragePowerLinear/title",
          "value": "kMatrixMixerParam_PostAveragePowerLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostAveragePowerLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PostAveragePowerLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_Enable/title",
          "value": "kMatrixMixerParam_Enable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_Enable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_Enable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostPeakHoldLevel/title",
          "value": "kMatrixMixerParam_PostPeakHoldLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostPeakHoldLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PostPeakHoldLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostAveragePower/title",
          "value": "kMatrixMixerParam_PostAveragePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PostAveragePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PostAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PrePeakHoldLevel/title",
          "value": "kMatrixMixerParam_PrePeakHoldLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMatrixMixerParam_PrePeakHoldLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMatrixMixerParam_PrePeakHoldLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kmatrixmixerparam_preaveragepower"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kmatrixmixerparam_preaveragepower"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
