{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kMultibandCompressorParam_Pregain@kMultibandCompressorParam_Headroom2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kMultibandCompressorParam_Headroom2"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMultibandCompressorParam_Headroom2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kMultibandCompressorParam_Headroom2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Headroom2"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_AttackTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_AttackTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_AttackTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_AttackTime"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_AttackTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_attacktime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_CompressionAmount1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_compressionamount1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_CompressionAmount2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_compressionamount2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_CompressionAmount3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_compressionamount3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_CompressionAmount4"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_CompressionAmount4",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_compressionamount4"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Crossover1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_crossover1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Crossover2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_crossover2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Crossover3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Crossover3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_crossover3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_EQ1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_eq1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_EQ2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_eq2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_EQ3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_eq3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_EQ4"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_EQ4",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_eq4"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Headroom1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_headroom1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Headroom2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_headroom2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Headroom3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_headroom3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandCompressorParam_Headroom4"
        }
      ],
      "role": "symbol",
      "title": "kMultibandCompressorParam_Headroom4",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandcompressorparam_headroom4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_AttackTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount4",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ4",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom4"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMultibandCompressorParam_Headroom2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Headroom2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_AttackTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_CompressionAmount4",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Crossover3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_EQ4",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandCompressorParam_Headroom4"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMultibandCompressorParam_Headroom2"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ3/title",
          "value": "kMultibandCompressorParam_EQ3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_EQ3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount4/title",
          "value": "kMultibandCompressorParam_CompressionAmount4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_CompressionAmount4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom4/title",
          "value": "kMultibandCompressorParam_Headroom4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Headroom4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom2/title",
          "value": "kMultibandCompressorParam_Headroom2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Headroom2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover2/title",
          "value": "kMultibandCompressorParam_Crossover2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Crossover2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_AttackTime/title",
          "value": "kMultibandCompressorParam_AttackTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_AttackTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_AttackTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover1/title",
          "value": "kMultibandCompressorParam_Crossover1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Crossover1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount3/title",
          "value": "kMultibandCompressorParam_CompressionAmount3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_CompressionAmount3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ1/title",
          "value": "kMultibandCompressorParam_EQ1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_EQ1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover3/title",
          "value": "kMultibandCompressorParam_Crossover3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Crossover3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Crossover3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom1/title",
          "value": "kMultibandCompressorParam_Headroom1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Headroom1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ2/title",
          "value": "kMultibandCompressorParam_EQ2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_EQ2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ4/title",
          "value": "kMultibandCompressorParam_EQ4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_EQ4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_EQ4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount2/title",
          "value": "kMultibandCompressorParam_CompressionAmount2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_CompressionAmount2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom3/title",
          "value": "kMultibandCompressorParam_Headroom3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_Headroom3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_Headroom3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount1/title",
          "value": "kMultibandCompressorParam_CompressionAmount1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandCompressorParam_CompressionAmount1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandCompressorParam_CompressionAmount1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kmultibandcompressorparam_headroom2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kmultibandcompressorparam_headroom2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
