{
  "abstract": [
    {
      "text": "The average power level of the channel, after the mixer, in decibels.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PostAveragePower"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kMultiChannelMixerParam_Volume@kMultiChannelMixerParam_PostAveragePower",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kMultiChannelMixerParam_PostAveragePower"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMultiChannelMixerParam_PostAveragePower"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kMultiChannelMixerParam_PostAveragePower"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kMultiChannelMixerParam_PostAveragePower"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Input and output scope. This is a read-only property. Use the value of this constant to read the left channel and its value+1 to read the right channel.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Enable": {
      "abstract": [
        {
          "text": "Enables a channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_Enable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Enable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_Enable"
        }
      ],
      "role": "symbol",
      "title": "kMultiChannelMixerParam_Enable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultichannelmixerparam_enable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Pan": {
      "abstract": [
        {
          "text": "The panning value for the mixer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_Pan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Pan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_Pan"
        }
      ],
      "role": "symbol",
      "title": "kMultiChannelMixerParam_Pan",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultichannelmixerparam_pan"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PostAveragePower": {
      "abstract": [
        {
          "text": "The average power level of the channel, after the mixer, in decibels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_PostAveragePower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PostAveragePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_PostAveragePower"
        }
      ],
      "role": "symbol",
      "title": "kMultiChannelMixerParam_PostAveragePower",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultichannelmixerparam_postaveragepower"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PostPeakHoldLevel": {
      "abstract": [
        {
          "text": "The peak hold level of the channel, after the mixer, in decibels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_PostPeakHoldLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PostPeakHoldLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_PostPeakHoldLevel"
        }
      ],
      "role": "symbol",
      "title": "kMultiChannelMixerParam_PostPeakHoldLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultichannelmixerparam_postpeakholdlevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PreAveragePower": {
      "abstract": [
        {
          "text": "The average power level of the channel, prior to the mixer, in decibels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_PreAveragePower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PreAveragePower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_PreAveragePower"
        }
      ],
      "role": "symbol",
      "title": "kMultiChannelMixerParam_PreAveragePower",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultichannelmixerparam_preaveragepower"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PrePeakHoldLevel": {
      "abstract": [
        {
          "text": "The peak hold level of the channel, prior to the mixer, in decibels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_PrePeakHoldLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PrePeakHoldLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_PrePeakHoldLevel"
        }
      ],
      "role": "symbol",
      "title": "kMultiChannelMixerParam_PrePeakHoldLevel",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultichannelmixerparam_prepeakholdlevel"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Volume": {
      "abstract": [
        {
          "text": "The linear gain of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_Volume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Volume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultiChannelMixerParam_Volume"
        }
      ],
      "role": "symbol",
      "title": "kMultiChannelMixerParam_Volume",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultichannelmixerparam_volume"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Enable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Pan",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PostPeakHoldLevel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PreAveragePower",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PrePeakHoldLevel",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Volume"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMultiChannelMixerParam_PostAveragePower"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultiChannelMixerParam_PostAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Enable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Pan",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PostPeakHoldLevel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PreAveragePower",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_PrePeakHoldLevel",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultiChannelMixerParam_Volume"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMultiChannelMixerParam_PostAveragePower"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_PrePeakHoldLevel/title",
          "value": "kMultiChannelMixerParam_PrePeakHoldLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_PrePeakHoldLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultiChannelMixerParam_PrePeakHoldLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_PostAveragePower/title",
          "value": "kMultiChannelMixerParam_PostAveragePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_PostAveragePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultiChannelMixerParam_PostAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_PostPeakHoldLevel/title",
          "value": "kMultiChannelMixerParam_PostPeakHoldLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_PostPeakHoldLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultiChannelMixerParam_PostPeakHoldLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_Enable/title",
          "value": "kMultiChannelMixerParam_Enable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_Enable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultiChannelMixerParam_Enable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_Pan/title",
          "value": "kMultiChannelMixerParam_Pan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_Pan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultiChannelMixerParam_Pan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_PreAveragePower/title",
          "value": "kMultiChannelMixerParam_PreAveragePower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_PreAveragePower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultiChannelMixerParam_PreAveragePower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_Volume/title",
          "value": "kMultiChannelMixerParam_Volume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultiChannelMixerParam_Volume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultiChannelMixerParam_Volume"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kmultichannelmixerparam_postaveragepower"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kmultichannelmixerparam_postaveragepower"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
