{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_LowFrequency"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kMultibandFilter_LowFilterType@kMultibandFilter_LowFrequency",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kMultibandFilter_LowFrequency"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMultibandFilter_LowFrequency"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kMultibandFilter_LowFrequency"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kMultibandFilter_LowFrequency"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_Bandwidth1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_Bandwidth1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_Bandwidth1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_bandwidth1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_Bandwidth2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_Bandwidth2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_Bandwidth2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_bandwidth2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_Bandwidth3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_Bandwidth3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_Bandwidth3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_bandwidth3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterFreq1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterFreq1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_CenterFreq1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_centerfreq1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterFreq2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterFreq2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_CenterFreq2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_centerfreq2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterFreq3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterFreq3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_CenterFreq3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_centerfreq3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterGain1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterGain1"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_CenterGain1",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_centergain1"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterGain2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterGain2"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_CenterGain2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_centergain2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterGain3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_CenterGain3"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_CenterGain3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_centergain3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighFilterType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_HighFilterType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighFilterType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_HighFilterType"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_HighFilterType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_highfiltertype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighFrequency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_HighFrequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_HighFrequency"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_HighFrequency",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_highfrequency"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_HighGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_HighGain"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_HighGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_highgain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_LowFilterType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_LowFilterType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_LowFilterType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_LowFilterType"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_LowFilterType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_lowfiltertype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_LowFrequency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_LowFrequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_LowFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_LowFrequency"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_LowFrequency",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_lowfrequency"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_LowGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMultibandFilter_LowGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_LowGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMultibandFilter_LowGain"
        }
      ],
      "role": "symbol",
      "title": "kMultibandFilter_LowGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmultibandfilter_lowgain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain1",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighFilterType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighFrequency",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_LowFilterType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_LowGain"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMultibandFilter_LowFrequency"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_LowFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_Bandwidth3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterFreq3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain1",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_CenterGain3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighFilterType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighFrequency",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_HighGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_LowFilterType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMultibandFilter_LowGain"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMultibandFilter_LowFrequency"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterGain3/title",
          "value": "kMultibandFilter_CenterGain3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterGain3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_CenterGain3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterFreq2/title",
          "value": "kMultibandFilter_CenterFreq2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterFreq2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_CenterFreq2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_HighGain/title",
          "value": "kMultibandFilter_HighGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_HighGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_HighGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterFreq1/title",
          "value": "kMultibandFilter_CenterFreq1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterFreq1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_CenterFreq1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_HighFilterType/title",
          "value": "kMultibandFilter_HighFilterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_HighFilterType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_HighFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_Bandwidth1/title",
          "value": "kMultibandFilter_Bandwidth1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_Bandwidth1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_Bandwidth1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterFreq3/title",
          "value": "kMultibandFilter_CenterFreq3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterFreq3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_CenterFreq3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_Bandwidth2/title",
          "value": "kMultibandFilter_Bandwidth2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_Bandwidth2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_Bandwidth2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_LowFrequency/title",
          "value": "kMultibandFilter_LowFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_LowFrequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_LowFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_HighFrequency/title",
          "value": "kMultibandFilter_HighFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_HighFrequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_HighFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterGain1/title",
          "value": "kMultibandFilter_CenterGain1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterGain1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_CenterGain1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_LowFilterType/title",
          "value": "kMultibandFilter_LowFilterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_LowFilterType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_LowFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_Bandwidth3/title",
          "value": "kMultibandFilter_Bandwidth3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_Bandwidth3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_Bandwidth3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterGain2/title",
          "value": "kMultibandFilter_CenterGain2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_CenterGain2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_CenterGain2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_LowGain/title",
          "value": "kMultibandFilter_LowGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMultibandFilter_LowGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMultibandFilter_LowGain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kmultibandfilter_lowfrequency"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kmultibandfilter_lowfrequency"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
