{
  "abstract": [
    {
      "text": "User-defined data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_User"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kMusicEventType_NULL@kMusicEventType_User",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kMusicEventType_User"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMusicEventType_User"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kMusicEventType_User"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kMusicEventType_User"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_AUPreset": {
      "abstract": [
        {
          "text": "An event containing an audio unit user preset dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_AUPreset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_AUPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_AUPreset"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_AUPreset",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_aupreset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedNote": {
      "abstract": [
        {
          "text": "A non-MIDI music event with variable number of parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_ExtendedNote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedNote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_ExtendedNote"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_ExtendedNote",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_extendednote"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedTempo": {
      "abstract": [
        {
          "text": "An event that signals a change in tempo, in beats-per-minute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_ExtendedTempo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedTempo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_ExtendedTempo"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_ExtendedTempo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_extendedtempo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIChannelMessage": {
      "abstract": [
        {
          "text": "A MIDI channel message, other than note control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDIChannelMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIChannelMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDIChannelMessage"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_MIDIChannelMessage",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_midichannelmessage"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDINoteMessage": {
      "abstract": [
        {
          "text": "A MIDI note-on message, including duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDINoteMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDINoteMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDINoteMessage"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_MIDINoteMessage",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_midinotemessage"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIRawData": {
      "abstract": [
        {
          "text": "MIDI system-exclusive data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDIRawData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIRawData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_MIDIRawData"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_MIDIRawData",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_midirawdata"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Meta": {
      "abstract": [
        {
          "text": "A standard MIDI file metaevent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_Meta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Meta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_Meta"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_Meta",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_meta"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_NULL": {
      "abstract": [
        {
          "text": "A null music event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_NULL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_NULL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_NULL"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_NULL",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_null"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Parameter": {
      "abstract": [
        {
          "text": "An audio unit parameter event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_Parameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Parameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_Parameter"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_Parameter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_parameter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_User": {
      "abstract": [
        {
          "text": "User-defined data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicEventType_User"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_User",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicEventType_User"
        }
      ],
      "role": "symbol",
      "title": "kMusicEventType_User",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusiceventtype_user"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_AUPreset",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedNote",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedTempo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIChannelMessage",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDINoteMessage",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIRawData",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Meta",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_NULL",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Parameter"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMusicEventType_User"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_User"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_AUPreset",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedNote",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_ExtendedTempo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIChannelMessage",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDINoteMessage",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_MIDIRawData",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Meta",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_NULL",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicEventType_Parameter"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMusicEventType_User"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDINoteMessage/title",
          "value": "kMusicEventType_MIDINoteMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDINoteMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_MIDINoteMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_Meta/title",
          "value": "kMusicEventType_Meta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_Meta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_Meta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_ExtendedTempo/title",
          "value": "kMusicEventType_ExtendedTempo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_ExtendedTempo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_ExtendedTempo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_Parameter/title",
          "value": "kMusicEventType_Parameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_Parameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_Parameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDIRawData/title",
          "value": "kMusicEventType_MIDIRawData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDIRawData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_MIDIRawData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_AUPreset/title",
          "value": "kMusicEventType_AUPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_AUPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_AUPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_NULL/title",
          "value": "kMusicEventType_NULL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_NULL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_NULL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDIChannelMessage/title",
          "value": "kMusicEventType_MIDIChannelMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_MIDIChannelMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_MIDIChannelMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_User/title",
          "value": "kMusicEventType_User"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_User/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_User"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_ExtendedNote/title",
          "value": "kMusicEventType_ExtendedNote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicEventType_ExtendedNote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicEventType_ExtendedNote"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kmusiceventtype_user"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kmusiceventtype_user"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
