{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceMIDIEventSelect"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kMusicDeviceRange@kMusicDeviceMIDIEventSelect",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kMusicDeviceMIDIEventSelect"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMusicDeviceMIDIEventSelect"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kMusicDeviceMIDIEventSelect"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kMusicDeviceMIDIEventSelect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceMIDIEventListSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicDeviceMIDIEventListSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceMIDIEventListSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicDeviceMIDIEventListSelect"
        }
      ],
      "role": "symbol",
      "title": "kMusicDeviceMIDIEventListSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusicdevicemidieventlistselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceMIDIEventSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicDeviceMIDIEventSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceMIDIEventSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicDeviceMIDIEventSelect"
        }
      ],
      "role": "symbol",
      "title": "kMusicDeviceMIDIEventSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusicdevicemidieventselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDevicePrepareInstrumentSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicDevicePrepareInstrumentSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDevicePrepareInstrumentSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicDevicePrepareInstrumentSelect"
        }
      ],
      "role": "symbol",
      "title": "kMusicDevicePrepareInstrumentSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusicdeviceprepareinstrumentselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicDeviceRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicDeviceRange"
        }
      ],
      "role": "symbol",
      "title": "kMusicDeviceRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusicdevicerange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceReleaseInstrumentSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicDeviceReleaseInstrumentSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceReleaseInstrumentSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicDeviceReleaseInstrumentSelect"
        }
      ],
      "role": "symbol",
      "title": "kMusicDeviceReleaseInstrumentSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusicdevicereleaseinstrumentselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceStartNoteSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicDeviceStartNoteSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceStartNoteSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicDeviceStartNoteSelect"
        }
      ],
      "role": "symbol",
      "title": "kMusicDeviceStartNoteSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusicdevicestartnoteselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceStopNoteSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicDeviceStopNoteSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceStopNoteSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicDeviceStopNoteSelect"
        }
      ],
      "role": "symbol",
      "title": "kMusicDeviceStopNoteSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusicdevicestopnoteselect"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceSysExSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMusicDeviceSysExSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceSysExSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMusicDeviceSysExSelect"
        }
      ],
      "role": "symbol",
      "title": "kMusicDeviceSysExSelect",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kmusicdevicesysexselect"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDevicePrepareInstrumentSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceReleaseInstrumentSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceStartNoteSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceStopNoteSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceSysExSelect",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceMIDIEventListSelect"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMusicDeviceMIDIEventSelect"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicDeviceMIDIEventSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDevicePrepareInstrumentSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceReleaseInstrumentSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceStartNoteSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceStopNoteSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceSysExSelect",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kMusicDeviceMIDIEventListSelect"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMusicDeviceMIDIEventSelect"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceStartNoteSelect/title",
          "value": "kMusicDeviceStartNoteSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceStartNoteSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicDeviceStartNoteSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceSysExSelect/title",
          "value": "kMusicDeviceSysExSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceSysExSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicDeviceSysExSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceRange/title",
          "value": "kMusicDeviceRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicDeviceRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceMIDIEventSelect/title",
          "value": "kMusicDeviceMIDIEventSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceMIDIEventSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicDeviceMIDIEventSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceStopNoteSelect/title",
          "value": "kMusicDeviceStopNoteSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceStopNoteSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicDeviceStopNoteSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceReleaseInstrumentSelect/title",
          "value": "kMusicDeviceReleaseInstrumentSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceReleaseInstrumentSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicDeviceReleaseInstrumentSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceMIDIEventListSelect/title",
          "value": "kMusicDeviceMIDIEventListSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDeviceMIDIEventListSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicDeviceMIDIEventListSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDevicePrepareInstrumentSelect/title",
          "value": "kMusicDevicePrepareInstrumentSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kMusicDevicePrepareInstrumentSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMusicDevicePrepareInstrumentSelect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kmusicdevicemidieventselect"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kmusicdevicemidieventselect"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
