{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallDensity"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kReverbParam_DryWetMix@kReverbParam_SmallDensity",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kReverbParam_SmallDensity"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kReverbParam_SmallDensity"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kReverbParam_SmallDensity"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kReverbParam_SmallDensity"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_DryWetMix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_DryWetMix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_DryWetMix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_DryWetMix"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_DryWetMix",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_drywetmix"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeBrightness": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_LargeBrightness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeBrightness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_LargeBrightness"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_LargeBrightness",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_largebrightness"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDelay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_LargeDelay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDelay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_LargeDelay"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_LargeDelay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_largedelay"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDelayRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_LargeDelayRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDelayRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_LargeDelayRange"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_LargeDelayRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_largedelayrange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDensity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_LargeDensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDensity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_LargeDensity"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_LargeDensity",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_largedensity"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_LargeSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_LargeSize"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_LargeSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_largesize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_ModulationDepth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_ModulationDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_ModulationDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_ModulationDepth"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_ModulationDepth",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_modulationdepth"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_ModulationRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_ModulationRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_ModulationRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_ModulationRate"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_ModulationRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_modulationrate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_PreDelay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_PreDelay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_PreDelay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_PreDelay"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_PreDelay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_predelay"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallBrightness": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_SmallBrightness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallBrightness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_SmallBrightness"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_SmallBrightness",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_smallbrightness"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallDelayRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_SmallDelayRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallDelayRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_SmallDelayRange"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_SmallDelayRange",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_smalldelayrange"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallDensity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_SmallDensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallDensity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_SmallDensity"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_SmallDensity",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_smalldensity"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallLargeMix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_SmallLargeMix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallLargeMix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_SmallLargeMix"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_SmallLargeMix",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_smalllargemix"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReverbParam_SmallSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbParam_SmallSize"
        }
      ],
      "role": "symbol",
      "title": "kReverbParam_SmallSize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kreverbparam_smallsize"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_DryWetMix",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeBrightness",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDelay",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDelayRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDensity",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeSize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_ModulationDepth",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_ModulationRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_PreDelay",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallBrightness",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallDelayRange",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallLargeMix",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallSize"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kReverbParam_SmallDensity"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_SmallDensity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_DryWetMix",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeBrightness",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDelay",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDelayRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeDensity",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_LargeSize",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_ModulationDepth",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_ModulationRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_PreDelay",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallBrightness",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallDelayRange",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallLargeMix",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kReverbParam_SmallSize"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kReverbParam_SmallDensity"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_ModulationRate/title",
          "value": "kReverbParam_ModulationRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_ModulationRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_ModulationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_LargeDensity/title",
          "value": "kReverbParam_LargeDensity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_LargeDensity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_LargeDensity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_SmallLargeMix/title",
          "value": "kReverbParam_SmallLargeMix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_SmallLargeMix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_SmallLargeMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_SmallBrightness/title",
          "value": "kReverbParam_SmallBrightness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_SmallBrightness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_SmallBrightness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_SmallDensity/title",
          "value": "kReverbParam_SmallDensity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_SmallDensity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_SmallDensity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_LargeDelayRange/title",
          "value": "kReverbParam_LargeDelayRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_LargeDelayRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_LargeDelayRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_DryWetMix/title",
          "value": "kReverbParam_DryWetMix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_DryWetMix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_DryWetMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_LargeBrightness/title",
          "value": "kReverbParam_LargeBrightness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_LargeBrightness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_LargeBrightness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_LargeDelay/title",
          "value": "kReverbParam_LargeDelay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_LargeDelay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_LargeDelay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_SmallDelayRange/title",
          "value": "kReverbParam_SmallDelayRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_SmallDelayRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_SmallDelayRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_PreDelay/title",
          "value": "kReverbParam_PreDelay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_PreDelay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_PreDelay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_SmallSize/title",
          "value": "kReverbParam_SmallSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_SmallSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_SmallSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_ModulationDepth/title",
          "value": "kReverbParam_ModulationDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_ModulationDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_ModulationDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_LargeSize/title",
          "value": "kReverbParam_LargeSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kReverbParam_LargeSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbParam_LargeSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kreverbparam_smalldensity"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kreverbparam_smalldensity"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
