{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThresholdTime"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kRogerBeepParam_InGateThreshold@kRogerBeepParam_OutGateThresholdTime",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kRogerBeepParam_OutGateThresholdTime"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kRogerBeepParam_OutGateThresholdTime"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kRogerBeepParam_OutGateThresholdTime"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_OutGateThresholdTime"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_InGateThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_InGateThreshold"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_InGateThreshold",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_ingatethreshold"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThresholdTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_InGateThresholdTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThresholdTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_InGateThresholdTime"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_InGateThresholdTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_ingatethresholdtime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThreshold": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_OutGateThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_OutGateThreshold"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_OutGateThreshold",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_outgatethreshold"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThresholdTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_OutGateThresholdTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThresholdTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_OutGateThresholdTime"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_OutGateThresholdTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_outgatethresholdtime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_RogerGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_RogerGain"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_RogerGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_rogergain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_RogerType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_RogerType"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_RogerType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_rogertype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_Sensitivity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_Sensitivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_Sensitivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRogerBeepParam_Sensitivity"
        }
      ],
      "role": "symbol",
      "title": "kRogerBeepParam_Sensitivity",
      "type": "topic",
      "url": "/documentation/audiotoolbox/krogerbeepparam_sensitivity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThreshold",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThresholdTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThreshold",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_Sensitivity"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kRogerBeepParam_OutGateThresholdTime"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_OutGateThresholdTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThreshold",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_InGateThresholdTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_OutGateThreshold",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_RogerType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRogerBeepParam_Sensitivity"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kRogerBeepParam_OutGateThresholdTime"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_OutGateThreshold/title",
          "value": "kRogerBeepParam_OutGateThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_OutGateThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_OutGateThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_RogerType/title",
          "value": "kRogerBeepParam_RogerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_RogerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_RogerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_InGateThreshold/title",
          "value": "kRogerBeepParam_InGateThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_InGateThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_InGateThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_InGateThresholdTime/title",
          "value": "kRogerBeepParam_InGateThresholdTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_InGateThresholdTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_InGateThresholdTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_Sensitivity/title",
          "value": "kRogerBeepParam_Sensitivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_Sensitivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_Sensitivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_RogerGain/title",
          "value": "kRogerBeepParam_RogerGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_RogerGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_RogerGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_OutGateThresholdTime/title",
          "value": "kRogerBeepParam_OutGateThresholdTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRogerBeepParam_OutGateThresholdTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRogerBeepParam_OutGateThresholdTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/krogerbeepparam_outgatethresholdtime"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/krogerbeepparam_outgatethresholdtime"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
