{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_EncodingStrategy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kRoundTripAACParam_Format@kRoundTripAACParam_EncodingStrategy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kRoundTripAACParam_EncodingStrategy"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kRoundTripAACParam_EncodingStrategy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kRoundTripAACParam_EncodingStrategy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_EncodingStrategy"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_BitRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_BitRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_BitRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_BitRate"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_BitRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_bitrate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_CompressedFormatSampleRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_CompressedFormatSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_CompressedFormatSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_CompressedFormatSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_CompressedFormatSampleRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_compressedformatsamplerate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_EncodingStrategy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_EncodingStrategy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_EncodingStrategy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_EncodingStrategy"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_EncodingStrategy",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_encodingstrategy"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Format": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_Format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_Format"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_Format",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_format"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Quality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_Quality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Quality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_Quality"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_Quality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_quality"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_RateOrQuality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_RateOrQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_RateOrQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRoundTripAACParam_RateOrQuality"
        }
      ],
      "role": "symbol",
      "title": "kRoundTripAACParam_RateOrQuality",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kroundtripaacparam_rateorquality"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_BitRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_CompressedFormatSampleRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Format",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Quality",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_RateOrQuality"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kRoundTripAACParam_EncodingStrategy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_EncodingStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_BitRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_CompressedFormatSampleRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Format",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_Quality",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kRoundTripAACParam_RateOrQuality"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kRoundTripAACParam_EncodingStrategy"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_Quality/title",
          "value": "kRoundTripAACParam_Quality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_Quality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_Quality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_RateOrQuality/title",
          "value": "kRoundTripAACParam_RateOrQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_RateOrQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_RateOrQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_Format/title",
          "value": "kRoundTripAACParam_Format"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_Format/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_Format"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_CompressedFormatSampleRate/title",
          "value": "kRoundTripAACParam_CompressedFormatSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_CompressedFormatSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_CompressedFormatSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_EncodingStrategy/title",
          "value": "kRoundTripAACParam_EncodingStrategy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_EncodingStrategy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_EncodingStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_BitRate/title",
          "value": "kRoundTripAACParam_BitRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kRoundTripAACParam_BitRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRoundTripAACParam_BitRate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kroundtripaacparam_encodingstrategy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kroundtripaacparam_encodingstrategy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
