{
  "abstract": [
    {
      "text": "The time resolution for a sequence of music events. For example, this value can indicate the time resolution that was specified by the MIDI file used to construct a sequence.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_TimeResolution"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kSequenceTrackProperty_LoopInfo@kSequenceTrackProperty_TimeResolution",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSequenceTrackProperty_TimeResolution"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSequenceTrackProperty_TimeResolution"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSequenceTrackProperty_TimeResolution"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSequenceTrackProperty_TimeResolution"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To use a specific time resolution when writing a new file, retrieve this value and then specify it when calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This value does not directly determine playback rate for a music track, but rather it",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "kSequenceTrackProperty_TimeResolution",
              "type": "codeVoice"
            },
            {
              "text": " is set in two possible ways:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you create a music sequence programmatically, the value is set to 480.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you create a music sequence from a MIDI file, the value is set to the time resolution specified in the MIDI file.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "A read-only ",
              "type": "text"
            },
            {
              "code": "SInt16",
              "type": "codeVoice"
            },
            {
              "text": " value that is valid only for a tempo track.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a MIDI file from the events in a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
          "text": "MusicSequenceFileFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreate"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileCreate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefilecreate(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_AutomatedParameters": {
      "abstract": [
        {
          "text": "Indicates whether or not a music track’s purpose is audio unit parameter automation. If this property’s value is other than 0, music events in the track can only indicate points in an automation curve. A read/write ",
          "type": "text"
        },
        {
          "code": "UInt32",
          "type": "codeVoice"
        },
        {
          "text": " value, where a value other than 0 indicates that the track is for parameter automation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_AutomatedParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_AutomatedParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_AutomatedParameters"
        }
      ],
      "role": "symbol",
      "title": "kSequenceTrackProperty_AutomatedParameters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/ksequencetrackproperty_automatedparameters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_LoopInfo": {
      "abstract": [
        {
          "text": "Looping information for a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_LoopInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_LoopInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_LoopInfo"
        }
      ],
      "role": "symbol",
      "title": "kSequenceTrackProperty_LoopInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/ksequencetrackproperty_loopinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_MuteStatus": {
      "abstract": [
        {
          "text": "The mute/unmute state of a music track. By default this value is ",
          "type": "text"
        },
        {
          "code": "false",
          "type": "codeVoice"
        },
        {
          "text": " (not muted). A read/write Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_MuteStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_MuteStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_MuteStatus"
        }
      ],
      "role": "symbol",
      "title": "kSequenceTrackProperty_MuteStatus",
      "type": "topic",
      "url": "/documentation/audiotoolbox/ksequencetrackproperty_mutestatus"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_OffsetTime": {
      "abstract": [
        {
          "text": "A music track’s start time in terms of beat number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_OffsetTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_OffsetTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_OffsetTime"
        }
      ],
      "role": "symbol",
      "title": "kSequenceTrackProperty_OffsetTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/ksequencetrackproperty_offsettime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_SoloStatus": {
      "abstract": [
        {
          "text": "The solo/unsolo state of a music track. By default this value is ",
          "type": "text"
        },
        {
          "code": "false",
          "type": "codeVoice"
        },
        {
          "text": " (not soloed). A read/write Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_SoloStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_SoloStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_SoloStatus"
        }
      ],
      "role": "symbol",
      "title": "kSequenceTrackProperty_SoloStatus",
      "type": "topic",
      "url": "/documentation/audiotoolbox/ksequencetrackproperty_solostatus"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_TimeResolution": {
      "abstract": [
        {
          "text": "The time resolution for a sequence of music events. For example, this value can indicate the time resolution that was specified by the MIDI file used to construct a sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_TimeResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_TimeResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_TimeResolution"
        }
      ],
      "role": "symbol",
      "title": "kSequenceTrackProperty_TimeResolution",
      "type": "topic",
      "url": "/documentation/audiotoolbox/ksequencetrackproperty_timeresolution"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_TrackLength": {
      "abstract": [
        {
          "text": "The time of the last music event in a music track, plus time required for note fade-outs and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_TrackLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_TrackLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_TrackLength"
        }
      ],
      "role": "symbol",
      "title": "kSequenceTrackProperty_TrackLength",
      "type": "topic",
      "url": "/documentation/audiotoolbox/ksequencetrackproperty_tracklength"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_LoopInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_OffsetTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_MuteStatus",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_SoloStatus",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_AutomatedParameters",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_TrackLength"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSequenceTrackProperty_TimeResolution"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSequenceTrackProperty_TimeResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_LoopInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_OffsetTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_MuteStatus",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_SoloStatus",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_AutomatedParameters",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_TrackLength"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kSequenceTrackProperty_TimeResolution"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_SoloStatus/title",
          "value": "kSequenceTrackProperty_SoloStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_SoloStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSequenceTrackProperty_SoloStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_OffsetTime/title",
          "value": "kSequenceTrackProperty_OffsetTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_OffsetTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSequenceTrackProperty_OffsetTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_TrackLength/title",
          "value": "kSequenceTrackProperty_TrackLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_TrackLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSequenceTrackProperty_TrackLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/title",
          "value": "MusicSequenceFileCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_MuteStatus/title",
          "value": "kSequenceTrackProperty_MuteStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_MuteStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSequenceTrackProperty_MuteStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_AutomatedParameters/title",
          "value": "kSequenceTrackProperty_AutomatedParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_AutomatedParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSequenceTrackProperty_AutomatedParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_LoopInfo/title",
          "value": "kSequenceTrackProperty_LoopInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_LoopInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSequenceTrackProperty_LoopInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_TimeResolution/title",
          "value": "kSequenceTrackProperty_TimeResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_TimeResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSequenceTrackProperty_TimeResolution"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/ksequencetrackproperty_timeresolution"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/ksequencetrackproperty_timeresolution"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
