{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_MaxGain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kSpatialMixerParam_Azimuth@kSpatialMixerParam_MaxGain",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSpatialMixerParam_MaxGain"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSpatialMixerParam_MaxGain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSpatialMixerParam_MaxGain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_MaxGain"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Azimuth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_Azimuth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Azimuth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_Azimuth"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_Azimuth",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_azimuth"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Distance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_Distance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Distance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_Distance"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_Distance",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_distance"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Elevation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_Elevation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Elevation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_Elevation"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_Elevation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_elevation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Enable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_Enable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Enable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_Enable"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_Enable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_enable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Gain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_Gain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Gain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_Gain"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_Gain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_gain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_GlobalReverbGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_GlobalReverbGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_GlobalReverbGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_GlobalReverbGain"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_GlobalReverbGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_globalreverbgain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadPitch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_HeadPitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadPitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_HeadPitch"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_HeadPitch",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_headpitch"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadRoll": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_HeadRoll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadRoll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_HeadRoll"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_HeadRoll",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_headroll"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadYaw": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_HeadYaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadYaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_HeadYaw"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_HeadYaw",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_headyaw"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_MaxGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_MaxGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_MaxGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_MaxGain"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_MaxGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_maxgain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_MinGain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_MinGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_MinGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_MinGain"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_MinGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_mingain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_ObstructionAttenuation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_ObstructionAttenuation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_ObstructionAttenuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_ObstructionAttenuation"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_ObstructionAttenuation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_obstructionattenuation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_OcclusionAttenuation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_OcclusionAttenuation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_OcclusionAttenuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_OcclusionAttenuation"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_OcclusionAttenuation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_occlusionattenuation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_PlaybackRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_PlaybackRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_PlaybackRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_PlaybackRate"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_PlaybackRate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_playbackrate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_ReverbBlend": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_ReverbBlend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_ReverbBlend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatialMixerParam_ReverbBlend"
        }
      ],
      "role": "symbol",
      "title": "kSpatialMixerParam_ReverbBlend",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kspatialmixerparam_reverbblend"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Azimuth",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Distance",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Elevation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Enable",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Gain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_GlobalReverbGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_MinGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_ObstructionAttenuation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_OcclusionAttenuation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_PlaybackRate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_ReverbBlend",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadPitch",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadRoll",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadYaw"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSpatialMixerParam_MaxGain"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_MaxGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Azimuth",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Distance",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Elevation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Enable",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_Gain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_GlobalReverbGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_MinGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_ObstructionAttenuation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_OcclusionAttenuation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_PlaybackRate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_ReverbBlend",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadPitch",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadRoll",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSpatialMixerParam_HeadYaw"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kSpatialMixerParam_MaxGain"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_ObstructionAttenuation/title",
          "value": "kSpatialMixerParam_ObstructionAttenuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_ObstructionAttenuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_ObstructionAttenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_MinGain/title",
          "value": "kSpatialMixerParam_MinGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_MinGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_MinGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_HeadRoll/title",
          "value": "kSpatialMixerParam_HeadRoll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_HeadRoll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_HeadRoll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_GlobalReverbGain/title",
          "value": "kSpatialMixerParam_GlobalReverbGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_GlobalReverbGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_GlobalReverbGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_Gain/title",
          "value": "kSpatialMixerParam_Gain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_Gain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_Gain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_OcclusionAttenuation/title",
          "value": "kSpatialMixerParam_OcclusionAttenuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_OcclusionAttenuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_OcclusionAttenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_Elevation/title",
          "value": "kSpatialMixerParam_Elevation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_Elevation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_Elevation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_PlaybackRate/title",
          "value": "kSpatialMixerParam_PlaybackRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_PlaybackRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_PlaybackRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_Azimuth/title",
          "value": "kSpatialMixerParam_Azimuth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_Azimuth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_Azimuth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_Distance/title",
          "value": "kSpatialMixerParam_Distance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_Distance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_Distance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_HeadYaw/title",
          "value": "kSpatialMixerParam_HeadYaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_HeadYaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_HeadYaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_MaxGain/title",
          "value": "kSpatialMixerParam_MaxGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_MaxGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_MaxGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_HeadPitch/title",
          "value": "kSpatialMixerParam_HeadPitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_HeadPitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_HeadPitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_ReverbBlend/title",
          "value": "kSpatialMixerParam_ReverbBlend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_ReverbBlend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_ReverbBlend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_Enable/title",
          "value": "kSpatialMixerParam_Enable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSpatialMixerParam_Enable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatialMixerParam_Enable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/kspatialmixerparam_maxgain"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/kspatialmixerparam_maxgain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
