{"abstract":[{"text":"Removes a specified range of music track events, and shifts later events toward the start of the track to fill in the gap.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/audiotoolbox/musictrackcut(_:_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/audiotoolbox/musictrackcut(_:_:_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCut(_:_:_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTrackCut","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"inTrack","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrack","preciseIdentifier":"c:@T@MusicTrack","text":"MusicTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"inStartTime","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp","preciseIdentifier":"c:@T@MusicTimeStamp","text":"MusicTimeStamp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"inEndTime","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp","preciseIdentifier":"c:@T@MusicTimeStamp","text":"MusicTimeStamp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]},{"kind":"parameters","parameters":[{"name":"inTrack","content":[{"inlineContent":[{"text":"The music track that you want to cut events from.","type":"text"}],"type":"paragraph"}]},{"name":"inStartTime","content":[{"inlineContent":[{"text":"The start time, in beats, for the range of music track events that you want to cut.","type":"text"}],"type":"paragraph"}]},{"name":"inEndTime","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The end time, in beats, for the range of music track events that you want to cut."}]}]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A result code."}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"text":"The ","type":"text"},{"code":"inStartTime","type":"codeVoice"},{"text":" value must be less than the ","type":"text"},{"code":"inEndTime","type":"codeVoice"},{"text":" value.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","seeAlsoSections":[{"anchor":"Managing-Music-Tracks","title":"Managing Music Tracks","generated":true,"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackClear(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCopyInsert(_:_:_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestMIDIEndpoint(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestNode(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetProperty(_:_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetSequence(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMerge(_:_:_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMoveEvents(_:_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewAUPresetEvent(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedNoteEvent(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedTempoEvent(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIChannelEvent(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDINoteEvent(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIRawDataEvent(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMetaEvent(_:_:_:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MusicTrackCut"}],"role":"symbol","modules":[{"name":"Audio Toolbox"}],"title":"MusicTrackCut(_:_:_:)","platforms":[{"unavailable":false,"introducedAt":"5.0","name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"5.0","name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"10.0","name":"macOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"9.0","name":"tvOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","deprecated":false,"beta":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicTrackCut"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MusicTrack","preciseIdentifier":"c:@T@MusicTrack"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTimeStamp","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTimeStamp","text":"MusicTimeStamp"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"}],"roleHeading":"Function","symbolKind":"func","externalID":"c:@F@MusicTrackCut"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"references":{"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMetaEvent(_:_:_:)":{"role":"symbol","url":"/documentation/audiotoolbox/musictracknewmetaevent(_:_:_:)","abstract":[{"type":"text","text":"Adds an event of type "},{"code":"MIDIMetaEvent","type":"codeVoice"},{"text":" to a music track.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MusicTrackNewMetaEvent"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTrackNewMetaEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicTrack","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTrack"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@MIDIMetaEvent","kind":"typeIdentifier","text":"MIDIMetaEvent"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"type":"topic","title":"MusicTrackNewMetaEvent(_:_:_:)","kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMetaEvent(_:_:_:)"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMerge(_:_:_:_:_:)":{"type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMerge(_:_:_:_:_:)","abstract":[{"type":"text","text":"Copies a range of events from one music track and merges them into another music track."}],"kind":"symbol","url":"/documentation/audiotoolbox/musictrackmerge(_:_:_:_:_:)","role":"symbol","navigatorTitle":[{"text":"MusicTrackMerge","kind":"identifier"}],"title":"MusicTrackMerge(_:_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTrackMerge","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@MusicTrack","text":"MusicTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"MusicTimeStamp","preciseIdentifier":"c:@T@MusicTimeStamp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"MusicTimeStamp","preciseIdentifier":"c:@T@MusicTimeStamp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"MusicTrack","preciseIdentifier":"c:@T@MusicTrack"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@MusicTimeStamp","text":"MusicTimeStamp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDINoteEvent(_:_:_:)":{"title":"MusicTrackNewMIDINoteEvent(_:_:_:)","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDINoteEvent(_:_:_:)","url":"/documentation/audiotoolbox/musictracknewmidinoteevent(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"MusicTrackNewMIDINoteEvent"}],"abstract":[{"type":"text","text":"Adds an event of type "},{"type":"codeVoice","code":"MIDINoteMessage"},{"type":"text","text":" to a music track."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTrackNewMIDINoteEvent","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@MusicTrack","kind":"typeIdentifier","text":"MusicTrack"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MIDINoteMessage","preciseIdentifier":"c:@S@MIDINoteMessage"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}],"kind":"symbol","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCopyInsert(_:_:_:_:_:)":{"title":"MusicTrackCopyInsert(_:_:_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"MusicTrackCopyInsert"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCopyInsert(_:_:_:_:_:)","abstract":[{"text":"Copies a range of events from one music track and inserts them into another music track.","type":"text"}],"role":"symbol","kind":"symbol","url":"/documentation/audiotoolbox/musictrackcopyinsert(_:_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTrackCopyInsert","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicTrack","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTrack"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"MusicTrack","preciseIdentifier":"c:@T@MusicTrack"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"MusicTimeStamp","preciseIdentifier":"c:@T@MusicTimeStamp"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}],"type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetProperty(_:_:_:_:)":{"url":"/documentation/audiotoolbox/musictrackgetproperty(_:_:_:_:)","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetProperty(_:_:_:_:)","title":"MusicTrackGetProperty(_:_:_:_:)","abstract":[{"type":"text","text":"Gets a music track property value."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"MusicTrackGetProperty","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicTrack","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTrack"},{"text":", ","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":", ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"navigatorTitle":[{"kind":"identifier","text":"MusicTrackGetProperty"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicTrackFrom":{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicTrackFrom","url":"/documentation/audiotoolbox/newmusictrackfrom","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"NewMusicTrackFrom","kind":"identifier"}],"title":"NewMusicTrackFrom","abstract":[]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedTempoEvent(_:_:_:)":{"title":"MusicTrackNewExtendedTempoEvent(_:_:_:)","type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedTempoEvent(_:_:_:)","url":"/documentation/audiotoolbox/musictracknewextendedtempoevent(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"MusicTrackNewExtendedTempoEvent"}],"abstract":[{"type":"text","text":"Adds a tempo to a music track."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTrackNewExtendedTempoEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicTrack","preciseIdentifier":"c:@T@MusicTrack","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"MusicTimeStamp","preciseIdentifier":"c:@T@MusicTimeStamp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Float64","preciseIdentifier":"s:s7Float64a"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"kind":"symbol","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestNode(_:_:)":{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestNode(_:_:)","url":"/documentation/audiotoolbox/musictrackgetdestnode(_:_:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTrackGetDestNode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicTrack","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTrack"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@T@AUNode","kind":"typeIdentifier","text":"AUNode"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"navigatorTitle":[{"kind":"identifier","text":"MusicTrackGetDestNode"}],"title":"MusicTrackGetDestNode(_:_:)","abstract":[{"text":"Gets the audio unit node that is the event target for a music track.","type":"text"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedNoteEvent(_:_:_:)":{"abstract":[{"type":"text","text":"Adds an event of type "},{"type":"codeVoice","code":"ExtendedNoteOnEvent"},{"text":" to a music track.","type":"text"}],"url":"/documentation/audiotoolbox/musictracknewextendednoteevent(_:_:_:)","role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedNoteEvent(_:_:_:)","navigatorTitle":[{"text":"MusicTrackNewExtendedNoteEvent","kind":"identifier"}],"title":"MusicTrackNewExtendedNoteEvent(_:_:_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MusicTrackNewExtendedNoteEvent"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@MusicTrack","kind":"typeIdentifier","text":"MusicTrack"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@ExtendedNoteOnEvent","text":"ExtendedNoteOnEvent","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIRawDataEvent(_:_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTrackNewMIDIRawDataEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicTrack","preciseIdentifier":"c:@T@MusicTrack","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"MusicTimeStamp","preciseIdentifier":"c:@T@MusicTimeStamp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@MIDIRawData","kind":"typeIdentifier","text":"MIDIRawData"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"abstract":[{"type":"text","text":"Adds an event of type "},{"type":"codeVoice","code":"MIDIRawData"},{"text":" to a music track.","type":"text"}],"title":"MusicTrackNewMIDIRawDataEvent(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"MusicTrackNewMIDIRawDataEvent"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIRawDataEvent(_:_:_:)","url":"/documentation/audiotoolbox/musictracknewmidirawdataevent(_:_:_:)"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIChannelEvent(_:_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTrackNewMIDIChannelEvent","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@MusicTrack","kind":"typeIdentifier","text":"MusicTrack"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@MIDIChannelMessage","kind":"typeIdentifier","text":"MIDIChannelMessage"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"role":"symbol","kind":"symbol","title":"MusicTrackNewMIDIChannelEvent(_:_:_:)","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIChannelEvent(_:_:_:)","abstract":[{"type":"text","text":"Adds an event of type "},{"type":"codeVoice","code":"MIDIChannelMessage"},{"type":"text","text":" to a music track."}],"type":"topic","url":"/documentation/audiotoolbox/musictracknewmidichannelevent(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"MusicTrackNewMIDIChannelEvent"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestMIDIEndpoint(_:_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicTrackGetDestMIDIEndpoint"},{"text":"(","kind":"text"},{"text":"MusicTrack","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTrack"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@T@MIDIEndpointRef","kind":"typeIdentifier","text":"MIDIEndpointRef"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"url":"/documentation/audiotoolbox/musictrackgetdestmidiendpoint(_:_:)","title":"MusicTrackGetDestMIDIEndpoint(_:_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MusicTrackGetDestMIDIEndpoint"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestMIDIEndpoint(_:_:)","abstract":[{"type":"text","text":"Gets the MIDI endpoint that is the event target for a music track."}],"kind":"symbol","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMoveEvents(_:_:_:_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MusicTrackMoveEvents","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicTrack","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTrack"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"abstract":[{"type":"text","text":"Shifts music track events forward or backward in time, in terms of beats."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MusicTrackMoveEvents"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMoveEvents(_:_:_:_:)","url":"/documentation/audiotoolbox/musictrackmoveevents(_:_:_:_:)","title":"MusicTrackMoveEvents(_:_:_:_:)"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetSequence(_:_:)":{"title":"MusicTrackGetSequence(_:_:)","url":"/documentation/audiotoolbox/musictrackgetsequence(_:_:)","kind":"symbol","navigatorTitle":[{"text":"MusicTrackGetSequence","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicTrackGetSequence"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@MusicTrack","kind":"typeIdentifier","text":"MusicTrack"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@T@MusicSequence","kind":"typeIdentifier","text":"MusicSequence"},{"kind":"text","text":"?>) -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"type":"topic","role":"symbol","abstract":[{"text":"Gets the music sequence that the music track is a member of.","type":"text"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetSequence(_:_:)"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrack":{"type":"topic","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrack","url":"/documentation/audiotoolbox/musictrack","abstract":[{"type":"text","text":"A music track consists of a series of music events, each timestamped using units of beats."}],"role":"symbol","title":"MusicTrack","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicTrack"}],"navigatorTitle":[{"kind":"identifier","text":"MusicTrack"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp":{"kind":"symbol","url":"/documentation/audiotoolbox/musictimestamp","navigatorTitle":[{"text":"MusicTimeStamp","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTimeStamp","kind":"identifier"}],"role":"symbol","type":"topic","title":"MusicTimeStamp","abstract":[{"text":"A timestamp for use by a music sequence.","type":"text"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCut(_:_:_:)":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCut(_:_:_:)","abstract":[{"type":"text","text":"Removes a specified range of music track events, and shifts later events toward the start of the track to fill in the gap."}],"navigatorTitle":[{"kind":"identifier","text":"MusicTrackCut"}],"url":"/documentation/audiotoolbox/musictrackcut(_:_:_:)","title":"MusicTrackCut(_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTrackCut","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@MusicTrack","kind":"typeIdentifier","text":"MusicTrack"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"MusicTimeStamp","preciseIdentifier":"c:@T@MusicTimeStamp"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewAUPresetEvent(_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"MusicTrackNewAUPresetEvent"}],"kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewAUPresetEvent(_:_:_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTrackNewAUPresetEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicTrack","preciseIdentifier":"c:@T@MusicTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AUPresetEvent","preciseIdentifier":"c:@S@AUPresetEvent"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}],"title":"MusicTrackNewAUPresetEvent(_:_:_:)","role":"symbol","url":"/documentation/audiotoolbox/musictracknewaupresetevent(_:_:_:)","abstract":[{"text":"Adds an event of type ","type":"text"},{"code":"AUPresetEvent","type":"codeVoice"},{"text":" to a music track.","type":"text"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackClear(_:_:_:)":{"title":"MusicTrackClear(_:_:_:)","url":"/documentation/audiotoolbox/musictrackclear(_:_:_:)","kind":"symbol","navigatorTitle":[{"text":"MusicTrackClear","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicTrackClear"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@MusicTrack","kind":"typeIdentifier","text":"MusicTrack"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@MusicTimeStamp","kind":"typeIdentifier","text":"MusicTimeStamp"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"type":"topic","role":"symbol","abstract":[{"text":"Removes a specified range of music track events.","type":"text"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackClear(_:_:_:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"5.0","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"introducedAt":"5.0","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"introducedAt":"13.1","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"10.0","unavailable":false,"deprecated":false,"beta":false,"name":"macOS"},{"name":"tvOS","beta":false,"introducedAt":"9.0","deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"introducedAt":"1.0","deprecated":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Function","op":"replace","path":"/metadata/roleHeading"},{"value":"MusicTrackCut","op":"replace","path":"/metadata/title"},{"value":"func","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"MusicTrackCut"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Managing Music Tracks","identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicTrackFrom","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackClear(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCopyInsert(_:_:_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestMIDIEndpoint(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestNode(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetProperty(_:_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetSequence(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMerge(_:_:_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMoveEvents(_:_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewAUPresetEvent(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedNoteEvent(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedTempoEvent(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIChannelEvent(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDINoteEvent(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIRawDataEvent(_:_:_:)"],"generated":true,"anchor":"Managing-Music-Tracks"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicTrackCut"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@MusicTrack","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrack","kind":"typeIdentifier","text":"MusicTrack"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inTrack"},{"kind":"text","text":", "},{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTimeStamp","text":"MusicTimeStamp"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inStartTime"},{"kind":"text","text":", "},{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTimeStamp","text":"MusicTimeStamp"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inEndTime"},{"kind":"text","text":");"}],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The music track that you want to cut events from.","type":"text"}]}],"name":"inTrack"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The start time, in beats, for the range of music track events that you want to cut.","type":"text"}]}],"name":"inStartTime"},{"content":[{"inlineContent":[{"type":"text","text":"The end time, in beats, for the range of music track events that you want to cut."}],"type":"paragraph"}],"name":"inEndTime"}],"kind":"parameters"}},{"value":{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A result code."}]}],"kind":"content"},"op":"replace","path":"/primaryContentSections/2"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMetaEvent(_:_:_:)/title","value":"MusicTrackNewMetaEvent"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMetaEvent(_:_:_:)/fragments","value":[{"text":"MusicTrackNewMetaEvent","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackMerge(_:_:_:_:_:)/title","value":"MusicTrackMerge"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackMerge(_:_:_:_:_:)/fragments","value":[{"text":"MusicTrackMerge","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDINoteEvent(_:_:_:)/title","value":"MusicTrackNewMIDINoteEvent"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDINoteEvent(_:_:_:)/fragments","value":[{"text":"MusicTrackNewMIDINoteEvent","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackCopyInsert(_:_:_:_:_:)/title","value":"MusicTrackCopyInsert"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackCopyInsert(_:_:_:_:_:)/fragments","value":[{"text":"MusicTrackCopyInsert","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetProperty(_:_:_:_:)/title","value":"MusicTrackGetProperty"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetProperty(_:_:_:_:)/fragments","value":[{"text":"MusicTrackGetProperty","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewExtendedTempoEvent(_:_:_:)/title","value":"MusicTrackNewExtendedTempoEvent"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewExtendedTempoEvent(_:_:_:)/fragments","value":[{"kind":"identifier","text":"MusicTrackNewExtendedTempoEvent"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetDestNode(_:_:)/title","value":"MusicTrackGetDestNode"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetDestNode(_:_:)/fragments","value":[{"kind":"identifier","text":"MusicTrackGetDestNode"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewExtendedNoteEvent(_:_:_:)/title","value":"MusicTrackNewExtendedNoteEvent"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewExtendedNoteEvent(_:_:_:)/fragments","value":[{"kind":"identifier","text":"MusicTrackNewExtendedNoteEvent"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDIRawDataEvent(_:_:_:)/title","value":"MusicTrackNewMIDIRawDataEvent"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDIRawDataEvent(_:_:_:)/fragments","value":[{"kind":"identifier","text":"MusicTrackNewMIDIRawDataEvent"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDIChannelEvent(_:_:_:)/title","value":"MusicTrackNewMIDIChannelEvent"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDIChannelEvent(_:_:_:)/fragments","value":[{"text":"MusicTrackNewMIDIChannelEvent","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetDestMIDIEndpoint(_:_:)/title","value":"MusicTrackGetDestMIDIEndpoint"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetDestMIDIEndpoint(_:_:)/fragments","value":[{"kind":"identifier","text":"MusicTrackGetDestMIDIEndpoint"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackMoveEvents(_:_:_:_:)/title","value":"MusicTrackMoveEvents"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackMoveEvents(_:_:_:_:)/fragments","value":[{"text":"MusicTrackMoveEvents","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetSequence(_:_:)/title","value":"MusicTrackGetSequence"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetSequence(_:_:)/fragments","value":[{"kind":"identifier","text":"MusicTrackGetSequence"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrack/title","value":"MusicTrack"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrack/fragments","value":[{"kind":"identifier","text":"MusicTrack"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrack/navigatorTitle","value":[{"kind":"identifier","text":"MusicTrack"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/title","value":"MusicTimeStamp"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/fragments","value":[{"kind":"identifier","text":"MusicTimeStamp"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/navigatorTitle","value":[{"kind":"identifier","text":"MusicTimeStamp"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackCut(_:_:_:)/title","value":"MusicTrackCut"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackCut(_:_:_:)/fragments","value":[{"kind":"identifier","text":"MusicTrackCut"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewAUPresetEvent(_:_:_:)/title","value":"MusicTrackNewAUPresetEvent"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewAUPresetEvent(_:_:_:)/fragments","value":[{"text":"MusicTrackNewAUPresetEvent","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackClear(_:_:_:)/title","value":"MusicTrackClear"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackClear(_:_:_:)/fragments","value":[{"text":"MusicTrackClear","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}