{
  "abstract": [
    {
      "text": "Calculates the number of beats that correspond to a number of seconds.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetBeatsForSeconds(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@MusicSequenceGetBeatsForSeconds",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MusicSequenceGetBeatsForSeconds"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MusicSequence",
        "text": "MusicSequence"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s7Float64a",
        "text": "Float64"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MusicTimeStamp",
        "text": "MusicTimeStamp"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MusicSequenceGetBeatsForSeconds"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "MusicSequenceGetBeatsForSeconds(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MusicSequenceGetBeatsForSeconds"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inSequence"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequence",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MusicSequence",
              "text": "MusicSequence"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inSeconds"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s7Float64a",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s7Float64a",
              "text": "Float64"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "outBeats"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MusicTimeStamp",
              "text": "MusicTimeStamp"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The sequence that you want to get a count of beats for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inSequence"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of seconds that you want the corresponding number of beats for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inSeconds"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On output, the number of beats that corresponds to the number of seconds in the ",
                  "type": "text"
                },
                {
                  "code": "inSeconds",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outBeats"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function makes use of the music sequence’s tempo track.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicSequence(_:)": {
      "abstract": [
        {
          "text": "Disposes of a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisposeMusicSequence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicSequence(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisposeMusicSequence"
        }
      ],
      "role": "symbol",
      "title": "DisposeMusicSequence(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/disposemusicsequence(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequence": {
      "abstract": [
        {
          "text": "A music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequence"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequence"
        }
      ],
      "role": "symbol",
      "title": "MusicSequence",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequence"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBarBeatTimeToBeats(_:_:_:)": {
      "abstract": [
        {
          "text": "Formats a music sequence’s bar-beat time to its beat time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceBarBeatTimeToBeats"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CABarBeatTime",
          "text": "CABarBeatTime"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBarBeatTimeToBeats(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceBarBeatTimeToBeats"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceBarBeatTimeToBeats(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencebarbeattimetobeats(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBeatsToBarBeatTime(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Formats a music sequence’s beat time to its bar-beat time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceBeatsToBarBeatTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CABarBeatTime",
          "text": "CABarBeatTime"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBeatsToBarBeatTime(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceBeatsToBarBeatTime"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceBeatsToBarBeatTime(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencebeatstobarbeattime(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceDisposeTrack(_:_:)": {
      "abstract": [
        {
          "text": "Removes a music track from a music sequence, and disposes of the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceDisposeTrack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceDisposeTrack(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceDisposeTrack"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceDisposeTrack(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencedisposetrack(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a MIDI file from the events in a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
          "text": "MusicSequenceFileFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreate"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileCreate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefilecreate(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a data object containing the events from a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreateData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
          "text": "MusicSequenceFileFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreateData"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileCreateData(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefilecreatedata(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Loads data into a music sequence from a URL reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoad"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceLoadFlags",
          "text": "MusicSequenceLoadFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoad"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileLoad(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefileload(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Load data into a music sequence from a data reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoadData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceLoadFlags",
          "text": "MusicSequenceLoadFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoadData"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileLoadData(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefileloaddata(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetAUGraph(_:_:)": {
      "abstract": [
        {
          "text": "Gets the audio processing graph associated with a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetAUGraph"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetAUGraph(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetAUGraph"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetAUGraph(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetaugraph(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetBeatsForSeconds(_:_:_:)": {
      "abstract": [
        {
          "text": "Calculates the number of beats that correspond to a number of seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetBeatsForSeconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetBeatsForSeconds(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetBeatsForSeconds"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetBeatsForSeconds(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetbeatsforseconds(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetIndTrack(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the music track at the specified track index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetIndTrack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetIndTrack(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetIndTrack"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetIndTrack(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetindtrack(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetInfoDictionary(_:)": {
      "abstract": [
        {
          "text": "Returns a dictionary containing music sequence information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetInfoDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetInfoDictionary(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetInfoDictionary"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetInfoDictionary(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetinfodictionary(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSMPTEResolution(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSMPTEResolution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSMPTEResolution(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSMPTEResolution"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetSMPTEResolution(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetsmpteresolution(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSecondsForBeats(_:_:_:)": {
      "abstract": [
        {
          "text": "Calculates the number of seconds that correspond to a number of beats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSecondsForBeats"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSecondsForBeats(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSecondsForBeats"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetSecondsForBeats(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetsecondsforbeats(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSequenceType(_:_:)": {
      "abstract": [
        {
          "text": "Gets the sequence type for a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSequenceType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceType",
          "text": "MusicSequenceType"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSequenceType(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSequenceType"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetSequenceType(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetsequencetype(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp": {
      "abstract": [
        {
          "text": "A timestamp for use by a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "MusicTimeStamp",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictimestamp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicSequence(_:)": {
      "abstract": [
        {
          "text": "Creates a new empty music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NewMusicSequence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicSequence(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NewMusicSequence"
        }
      ],
      "role": "symbol",
      "title": "NewMusicSequence(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/newmusicsequence(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s7Float64a": {
      "abstract": [
        {
          "text": "A 64-bit floating point type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7Float64a",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float64",
      "type": "topic",
      "url": "/documentation/Swift/Float64"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Music-Sequences",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicSequence(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicSequence(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBarBeatTimeToBeats(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBeatsToBarBeatTime(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceDisposeTrack(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetAUGraph(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetIndTrack(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetInfoDictionary(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSMPTEResolution(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSecondsForBeats(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSequenceType(_:_:)"
      ],
      "title": "Managing Music Sequences"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MusicSequenceGetBeatsForSeconds"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetBeatsForSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Music-Sequences",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicSequence(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicSequence(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBarBeatTimeToBeats(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBeatsToBarBeatTime(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceDisposeTrack(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetAUGraph(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetIndTrack(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetInfoDictionary(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSMPTEResolution(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSecondsForBeats(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSequenceType(_:_:)"
              ],
              "title": "Managing Music Sequences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MusicSequenceGetBeatsForSeconds"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequence",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MusicSequence",
                    "text": "MusicSequence"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inSequence"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@Float64",
                    "text": "Float64"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inSeconds"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MusicTimeStamp",
                    "text": "MusicTimeStamp"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outBeats"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The sequence that you want to get a count of beats for.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inSequence"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of seconds that you want the corresponding number of beats for.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inSeconds"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On output, the number of beats that corresponds to the number of seconds in the ",
                        "type": "text"
                      },
                      {
                        "code": "inSeconds",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "outBeats"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceBeatsToBarBeatTime(_:_:_:_:)/title",
          "value": "MusicSequenceBeatsToBarBeatTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceBeatsToBarBeatTime(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceBeatsToBarBeatTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1DisposeMusicSequence(_:)/title",
          "value": "DisposeMusicSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1DisposeMusicSequence(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DisposeMusicSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/title",
          "value": "MusicTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetInfoDictionary(_:)/title",
          "value": "MusicSequenceGetInfoDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetInfoDictionary(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetInfoDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetAUGraph(_:_:)/title",
          "value": "MusicSequenceGetAUGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetAUGraph(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetAUGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoadData(_:_:_:_:)/title",
          "value": "MusicSequenceFileLoadData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoadData(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileLoadData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequence/title",
          "value": "MusicSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetBeatsForSeconds(_:_:_:)/title",
          "value": "MusicSequenceGetBeatsForSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetBeatsForSeconds(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetBeatsForSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSequenceType(_:_:)/title",
          "value": "MusicSequenceGetSequenceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSequenceType(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetSequenceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoad(_:_:_:_:)/title",
          "value": "MusicSequenceFileLoad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoad(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileLoad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/title",
          "value": "MusicSequenceFileCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSMPTEResolution(_:_:_:)/title",
          "value": "MusicSequenceGetSMPTEResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSMPTEResolution(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetSMPTEResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetIndTrack(_:_:_:)/title",
          "value": "MusicSequenceGetIndTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetIndTrack(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetIndTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreateData(_:_:_:_:_:)/title",
          "value": "MusicSequenceFileCreateData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreateData(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileCreateData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceDisposeTrack(_:_:)/title",
          "value": "MusicSequenceDisposeTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceDisposeTrack(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceDisposeTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSecondsForBeats(_:_:_:)/title",
          "value": "MusicSequenceGetSecondsForBeats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSecondsForBeats(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetSecondsForBeats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NewMusicSequence(_:)/title",
          "value": "NewMusicSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NewMusicSequence(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NewMusicSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceBarBeatTimeToBeats(_:_:_:)/title",
          "value": "MusicSequenceBarBeatTimeToBeats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceBarBeatTimeToBeats(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceBarBeatTimeToBeats"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/musicsequencegetbeatsforseconds(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/musicsequencegetbeatsforseconds(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
