{
  "abstract": [
    {
      "text": "A music player plays a music sequence (of type ",
      "type": "text"
    },
    {
      "code": "MusicSequence",
      "type": "codeVoice"
    },
    {
      "text": ").",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@MusicPlayer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MusicPlayer"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MusicPlayer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "MusicPlayer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MusicPlayer"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s13OpaquePointerV",
              "text": "OpaquePointer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicPlayer(_:)": {
      "abstract": [
        {
          "text": "Disposes of a music player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisposeMusicPlayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicPlayer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisposeMusicPlayer"
        }
      ],
      "role": "symbol",
      "title": "DisposeMusicPlayer(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/disposemusicplayer(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayer": {
      "abstract": [
        {
          "text": "A music player plays a music sequence (of type ",
          "type": "text"
        },
        {
          "code": "MusicSequence",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayer"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayer"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayer",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayer"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetBeatsForHostTime(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the beat number associated a specified host time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerGetBeatsForHostTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetBeatsForHostTime(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerGetBeatsForHostTime"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerGetBeatsForHostTime(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayergetbeatsforhosttime(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetHostTimeForBeats(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the host time associated with a specified beat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerGetHostTimeForBeats"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetHostTimeForBeats(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerGetHostTimeForBeats"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerGetHostTimeForBeats(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayergethosttimeforbeats(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetPlayRateScalar(_:_:)": {
      "abstract": [
        {
          "text": "Gets the playback rate multiplier for a music player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerGetPlayRateScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetPlayRateScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerGetPlayRateScalar"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerGetPlayRateScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayergetplayratescalar(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetSequence(_:_:)": {
      "abstract": [
        {
          "text": "Gets the music sequence associated with a music player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerGetSequence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetSequence(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerGetSequence"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerGetSequence(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayergetsequence(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetTime(_:_:)": {
      "abstract": [
        {
          "text": "Gets the playback point for a music player, in beats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerGetTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetTime(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerGetTime"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerGetTime(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayergettime(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerIsPlaying(_:_:)": {
      "abstract": [
        {
          "text": "Indicates whether or not a music player is playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerIsPlaying"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerIsPlaying(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerIsPlaying"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerIsPlaying(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayerisplaying(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerPreroll(_:)": {
      "abstract": [
        {
          "text": "Prepares a music player to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerPreroll"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerPreroll(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerPreroll"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerPreroll(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayerpreroll(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetPlayRateScalar(_:_:)": {
      "abstract": [
        {
          "text": "Sets a playback rate multiplier for a music player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerSetPlayRateScalar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetPlayRateScalar(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerSetPlayRateScalar"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerSetPlayRateScalar(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayersetplayratescalar(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetSequence(_:_:)": {
      "abstract": [
        {
          "text": "Sets the music sequence for the music player to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerSetSequence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetSequence(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerSetSequence"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerSetSequence(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayersetsequence(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetTime(_:_:)": {
      "abstract": [
        {
          "text": "Sets the playback point for a music player, in beats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerSetTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetTime(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerSetTime"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerSetTime(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayersettime(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStart(_:)": {
      "abstract": [
        {
          "text": "Starts playback of a music player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerStart"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerStart(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayerstart(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStop(_:)": {
      "abstract": [
        {
          "text": "Stops playback of a music player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicPlayerStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicPlayerStop"
        }
      ],
      "role": "symbol",
      "title": "MusicPlayerStop(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicplayerstop(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp": {
      "abstract": [
        {
          "text": "A timestamp for use by a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "MusicTimeStamp",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictimestamp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicPlayer(_:)": {
      "abstract": [
        {
          "text": "Creates a new music player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NewMusicPlayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicPlayer",
          "text": "MusicPlayer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicPlayer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NewMusicPlayer"
        }
      ],
      "role": "symbol",
      "title": "NewMusicPlayer(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/newmusicplayer(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s13OpaquePointerV": {
      "abstract": [
        {
          "text": "A wrapper around an opaque C pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpaquePointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
      "kind": "symbol",
      "role": "symbol",
      "title": "OpaquePointer",
      "type": "topic",
      "url": "/documentation/Swift/OpaquePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-a-Music-Player",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicPlayer(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicPlayer(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetBeatsForHostTime(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetHostTimeForBeats(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetPlayRateScalar(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetSequence(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetTime(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerIsPlaying(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerPreroll(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetPlayRateScalar(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetSequence(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetTime(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStart(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStop(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp"
      ],
      "title": "Managing a Music Player"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MusicPlayer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-a-Music-Player",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicPlayer(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicPlayer(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetBeatsForHostTime(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetHostTimeForBeats(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetPlayRateScalar(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetSequence(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetTime(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerIsPlaying(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerPreroll(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetPlayRateScalar(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetSequence(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetTime(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStart(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStop(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp"
              ],
              "title": "Managing a Music Player"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@OpaqueMusicPlayer",
                    "text": "OpaqueMusicPlayer"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "MusicPlayer"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/title",
          "value": "MusicTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetHostTimeForBeats(_:_:_:)/title",
          "value": "MusicPlayerGetHostTimeForBeats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetHostTimeForBeats(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerGetHostTimeForBeats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerStop(_:)/title",
          "value": "MusicPlayerStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerStop(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetTime(_:_:)/title",
          "value": "MusicPlayerSetTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetTime(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerSetTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetBeatsForHostTime(_:_:_:)/title",
          "value": "MusicPlayerGetBeatsForHostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetBeatsForHostTime(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerGetBeatsForHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerPreroll(_:)/title",
          "value": "MusicPlayerPreroll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerPreroll(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerPreroll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetSequence(_:_:)/title",
          "value": "MusicPlayerGetSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetSequence(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerGetSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1DisposeMusicPlayer(_:)/title",
          "value": "DisposeMusicPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1DisposeMusicPlayer(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DisposeMusicPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetTime(_:_:)/title",
          "value": "MusicPlayerGetTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetTime(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerGetTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NewMusicPlayer(_:)/title",
          "value": "NewMusicPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NewMusicPlayer(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NewMusicPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerStart(_:)/title",
          "value": "MusicPlayerStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerStart(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetPlayRateScalar(_:_:)/title",
          "value": "MusicPlayerGetPlayRateScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetPlayRateScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerGetPlayRateScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetPlayRateScalar(_:_:)/title",
          "value": "MusicPlayerSetPlayRateScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetPlayRateScalar(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerSetPlayRateScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetSequence(_:_:)/title",
          "value": "MusicPlayerSetSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetSequence(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerSetSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayer/title",
          "value": "MusicPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerIsPlaying(_:_:)/title",
          "value": "MusicPlayerIsPlaying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerIsPlaying(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicPlayerIsPlaying"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/musicplayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/musicplayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
