{
  "abstract": [
    {
      "text": "Creates a MIDI file from the events in a music sequence.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@MusicSequenceFileCreate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MusicSequenceFileCreate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MusicSequence",
        "text": "MusicSequence"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFURLRef",
        "text": "CFURL"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
        "text": "MusicSequenceFileTypeID"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
        "text": "MusicSequenceFileFlags"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int16V",
        "text": "Int16"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MusicSequenceFileCreate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "MusicSequenceFileCreate(_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MusicSequenceFileCreate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inSequence"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequence",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MusicSequence",
              "text": "MusicSequence"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inFileRef"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFURLRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFURLRef",
              "text": "CFURL"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inFileType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
              "text": "MusicSequenceFileTypeID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inFlags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
              "text": "MusicSequenceFileFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inResolution"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int16V",
              "text": "Int16"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The music sequence that you want to create a MIDI file from.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inSequence"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The URL to the MIDI file to be created.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inFileRef"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of file to create.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inFileType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Flags that configure the file creation process.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inFlags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The resolution, which depends on the file type and the music sequence type.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inResolution"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function can be (and is most commonly) used to create a MIDI file from the events in a sequence. Only MIDI based events are used when creating the MIDI file. MIDI files are normally beat based, but can also have a SMPTE (or real-time rather than beat time) representation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The inResolution parameter specifies the relationship between “tick” and quarter note for saving to a standard MIDI file. Pass 0 to this parameter to use the default value; namely, the value that is currently set on the tempo track.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The various sequence types determine the kinds of files that can be created, as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Beats—When saving a MIDI file, it saves a beats (PPQ) based axis.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Seconds—When saving a MIDI file, it will save it as a SMPTE resolution - so you should specify this resolution when creating the MIDI file. If zero is specified, 25 fps and 40 ticks/frame is used (a time scale of a millisecond)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Samples—You cannot save to a MIDI file with this sequence type.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The complete meaning of the 16-bit “division” field in a MIDI File’s MThd chunk. If it is positive, then a tick represents 1/D quarter notes.  If it negative, the following pertains:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Bits 14-8 are a signed 7-bit number representing the SMPTE format: 24, -25, -29 (drop), -30.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Bits 7-0 represents the number of ticks per SMPTE frame. Typical values are 4, 10, 80, 100. You can obtain millisecond resolution by specifying 25 frames/sec and 40 divisions/frame:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "code": [
            "  30 fps with 80 bits (ticks) per frame: 0xE250  ((char)0xE2 == -30)"
          ],
          "syntax": "objc",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicSequence(_:)": {
      "abstract": [
        {
          "text": "Disposes of a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisposeMusicSequence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicSequence(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisposeMusicSequence"
        }
      ],
      "role": "symbol",
      "title": "DisposeMusicSequence(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/disposemusicsequence(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequence": {
      "abstract": [
        {
          "text": "A music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequence"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequence"
        }
      ],
      "role": "symbol",
      "title": "MusicSequence",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequence"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBarBeatTimeToBeats(_:_:_:)": {
      "abstract": [
        {
          "text": "Formats a music sequence’s bar-beat time to its beat time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceBarBeatTimeToBeats"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CABarBeatTime",
          "text": "CABarBeatTime"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBarBeatTimeToBeats(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceBarBeatTimeToBeats"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceBarBeatTimeToBeats(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencebarbeattimetobeats(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBeatsToBarBeatTime(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Formats a music sequence’s beat time to its bar-beat time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceBeatsToBarBeatTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CABarBeatTime",
          "text": "CABarBeatTime"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBeatsToBarBeatTime(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceBeatsToBarBeatTime"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceBeatsToBarBeatTime(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencebeatstobarbeattime(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceDisposeTrack(_:_:)": {
      "abstract": [
        {
          "text": "Removes a music track from a music sequence, and disposes of the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceDisposeTrack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceDisposeTrack(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceDisposeTrack"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceDisposeTrack(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencedisposetrack(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a MIDI file from the events in a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
          "text": "MusicSequenceFileFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreate"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileCreate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefilecreate(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a data object containing the events from a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreateData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
          "text": "MusicSequenceFileFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreateData"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileCreateData(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefilecreatedata(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags": {
      "abstract": [
        {
          "text": "Flags that configure the behavior of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileFlags"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefileflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Loads data into a music sequence from a URL reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoad"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceLoadFlags",
          "text": "MusicSequenceLoadFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoad"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileLoad(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefileload(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Load data into a music sequence from a data reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoadData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceLoadFlags",
          "text": "MusicSequenceLoadFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileLoadData"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileLoadData(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefileloaddata(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID": {
      "abstract": [
        {
          "text": "The various types of files that can be parsed by a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileTypeID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileTypeID"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileTypeID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefiletypeid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetAUGraph(_:_:)": {
      "abstract": [
        {
          "text": "Gets the audio processing graph associated with a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetAUGraph"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUGraph",
          "text": "AUGraph"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetAUGraph(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetAUGraph"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetAUGraph(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetaugraph(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetBeatsForSeconds(_:_:_:)": {
      "abstract": [
        {
          "text": "Calculates the number of beats that correspond to a number of seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetBeatsForSeconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetBeatsForSeconds(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetBeatsForSeconds"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetBeatsForSeconds(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetbeatsforseconds(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetIndTrack(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the music track at the specified track index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetIndTrack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetIndTrack(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetIndTrack"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetIndTrack(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetindtrack(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetInfoDictionary(_:)": {
      "abstract": [
        {
          "text": "Returns a dictionary containing music sequence information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetInfoDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetInfoDictionary(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetInfoDictionary"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetInfoDictionary(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetinfodictionary(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSMPTEResolution(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSMPTEResolution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSMPTEResolution(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSMPTEResolution"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetSMPTEResolution(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetsmpteresolution(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSecondsForBeats(_:_:_:)": {
      "abstract": [
        {
          "text": "Calculates the number of seconds that correspond to a number of beats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSecondsForBeats"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSecondsForBeats(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSecondsForBeats"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetSecondsForBeats(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetsecondsforbeats(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSequenceType(_:_:)": {
      "abstract": [
        {
          "text": "Gets the sequence type for a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSequenceType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceType",
          "text": "MusicSequenceType"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSequenceType(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceGetSequenceType"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceGetSequenceType(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencegetsequencetype(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicSequence(_:)": {
      "abstract": [
        {
          "text": "Creates a new empty music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NewMusicSequence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicSequence(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NewMusicSequence"
        }
      ],
      "role": "symbol",
      "title": "NewMusicSequence(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/newmusicsequence(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFURLRef": {
      "abstract": [
        {
          "text": "A reference to a CFURL object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFURL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFURLRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFURL",
      "type": "topic",
      "url": "/documentation/corefoundation/cfurl"
    },
    "doc://com.externally.resolved.symbol/s:s5Int16V": {
      "abstract": [
        {
          "text": "A 16-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int16",
      "type": "topic",
      "url": "/documentation/Swift/Int16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Music-Sequences",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicSequence(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicSequence(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBarBeatTimeToBeats(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBeatsToBarBeatTime(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceDisposeTrack(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetAUGraph(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetBeatsForSeconds(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetIndTrack(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetInfoDictionary(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSMPTEResolution(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSecondsForBeats(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSequenceType(_:_:)"
      ],
      "title": "Managing Music Sequences"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MusicSequenceFileCreate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Music-Sequences",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicSequence(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicSequence(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBarBeatTimeToBeats(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceBeatsToBarBeatTime(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceDisposeTrack(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoad(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileLoadData(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetAUGraph(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetBeatsForSeconds(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetIndTrack(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetInfoDictionary(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSMPTEResolution(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSecondsForBeats(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceGetSequenceType(_:_:)"
              ],
              "title": "Managing Music Sequences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MusicSequenceFileCreate"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequence",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MusicSequence",
                    "text": "MusicSequence"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inSequence"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFURLRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFURLRef",
                    "text": "CFURLRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inFileRef"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileTypeID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
                    "text": "MusicSequenceFileTypeID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inFileType"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
                    "text": "MusicSequenceFileFlags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inFlags"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SInt16",
                    "text": "SInt16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inResolution"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The music sequence that you want to create a MIDI file from.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inSequence"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The URL to the MIDI file to be created.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inFileRef"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The type of file to create.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inFileType"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Flags that configure the file creation process.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inFlags"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The resolution, which depends on the file type and the music sequence type.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inResolution"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceDisposeTrack(_:_:)/title",
          "value": "MusicSequenceDisposeTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceDisposeTrack(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceDisposeTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileTypeID/title",
          "value": "MusicSequenceFileTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileTypeID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileTypeID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1DisposeMusicSequence(_:)/title",
          "value": "DisposeMusicSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1DisposeMusicSequence(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DisposeMusicSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceBeatsToBarBeatTime(_:_:_:_:)/title",
          "value": "MusicSequenceBeatsToBarBeatTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceBeatsToBarBeatTime(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceBeatsToBarBeatTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreateData(_:_:_:_:_:)/title",
          "value": "MusicSequenceFileCreateData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreateData(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileCreateData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFURLRef/title",
          "value": "CFURLRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetBeatsForSeconds(_:_:_:)/title",
          "value": "MusicSequenceGetBeatsForSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetBeatsForSeconds(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetBeatsForSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceBarBeatTimeToBeats(_:_:_:)/title",
          "value": "MusicSequenceBarBeatTimeToBeats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceBarBeatTimeToBeats(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceBarBeatTimeToBeats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSequenceType(_:_:)/title",
          "value": "MusicSequenceGetSequenceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSequenceType(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetSequenceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NewMusicSequence(_:)/title",
          "value": "NewMusicSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NewMusicSequence(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NewMusicSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSMPTEResolution(_:_:_:)/title",
          "value": "MusicSequenceGetSMPTEResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSMPTEResolution(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetSMPTEResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequence/title",
          "value": "MusicSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetInfoDictionary(_:)/title",
          "value": "MusicSequenceGetInfoDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetInfoDictionary(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetInfoDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSecondsForBeats(_:_:_:)/title",
          "value": "MusicSequenceGetSecondsForBeats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetSecondsForBeats(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetSecondsForBeats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/title",
          "value": "MusicSequenceFileCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoadData(_:_:_:_:)/title",
          "value": "MusicSequenceFileLoadData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoadData(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileLoadData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetIndTrack(_:_:_:)/title",
          "value": "MusicSequenceGetIndTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetIndTrack(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetIndTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/title",
          "value": "MusicSequenceFileFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetAUGraph(_:_:)/title",
          "value": "MusicSequenceGetAUGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceGetAUGraph(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceGetAUGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoad(_:_:_:_:)/title",
          "value": "MusicSequenceFileLoad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileLoad(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileLoad"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/musicsequencefilecreate(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/musicsequencefilecreate(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
