{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@MusicDeviceStdNoteParams",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MusicDeviceStdNoteParams"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MusicDeviceStdNoteParams"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MusicDeviceStdNoteParams"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MusicDeviceStdNoteParams"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicEventIterator(_:)": {
      "abstract": [
        {
          "text": "Disposes of a music event iterator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisposeMusicEventIterator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicEventIterator(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisposeMusicEventIterator"
        }
      ],
      "role": "symbol",
      "title": "DisposeMusicEventIterator(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/disposemusiceventiterator(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedNoteOnEvent": {
      "abstract": [
        {
          "text": "Describes a note-on event with extended parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtendedNoteOnEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedNoteOnEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtendedNoteOnEvent"
        }
      ],
      "role": "symbol",
      "title": "ExtendedNoteOnEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendednoteonevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicDeviceStdNoteParams"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicDeviceStdNoteParams"
        }
      ],
      "role": "symbol",
      "title": "MusicDeviceStdNoteParams",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdevicestdnoteparams"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/argCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/argCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "argCount"
        }
      ],
      "role": "symbol",
      "title": "argCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdevicestdnoteparams/argcount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdevicestdnoteparams/init()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/init(argCount:mPitch:mVelocity:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "argCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mPitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/init(argCount:mPitch:mVelocity:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(argCount:mPitch:mVelocity:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdevicestdnoteparams/init(argcount:mpitch:mvelocity:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/mPitch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mPitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/mPitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mPitch"
        }
      ],
      "role": "symbol",
      "title": "mPitch",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdevicestdnoteparams/mpitch"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/mVelocity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/mVelocity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mVelocity"
        }
      ],
      "role": "symbol",
      "title": "mVelocity",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdevicestdnoteparams/mvelocity"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIterator": {
      "abstract": [
        {
          "text": "A music event iterator sequentially handles events on a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventIterator"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIterator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventIterator"
        }
      ],
      "role": "symbol",
      "title": "MusicEventIterator",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventiterator"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorDeleteEvent(_:)": {
      "abstract": [
        {
          "text": "Deletes the event at a music event iterator’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventIteratorDeleteEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorDeleteEvent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventIteratorDeleteEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicEventIteratorDeleteEvent(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventiteratordeleteevent(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorGetEventInfo(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets information about the event at a music event iterator’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventIteratorGetEventInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventType",
          "text": "MusicEventType"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorGetEventInfo(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventIteratorGetEventInfo"
        }
      ],
      "role": "symbol",
      "title": "MusicEventIteratorGetEventInfo(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventiteratorgeteventinfo(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasCurrentEvent(_:_:)": {
      "abstract": [
        {
          "text": "Indicates whether or not a music track contains an event at the music event iterator’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventIteratorHasCurrentEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasCurrentEvent(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventIteratorHasCurrentEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicEventIteratorHasCurrentEvent(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventiteratorhascurrentevent(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasNextEvent(_:_:)": {
      "abstract": [
        {
          "text": "Indicates whether or not a music track contains an event beyond the music event iterator’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventIteratorHasNextEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasNextEvent(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventIteratorHasNextEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicEventIteratorHasNextEvent(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventiteratorhasnextevent(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasPreviousEvent(_:_:)": {
      "abstract": [
        {
          "text": "Indicates whether or not a music track contains an event before the music event iterator’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventIteratorHasPreviousEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasPreviousEvent(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventIteratorHasPreviousEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicEventIteratorHasPreviousEvent(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventiteratorhaspreviousevent(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorNextEvent(_:)": {
      "abstract": [
        {
          "text": "Positions a music event iterator at the next event on a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventIteratorNextEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorNextEvent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventIteratorNextEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicEventIteratorNextEvent(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventiteratornextevent(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorPreviousEvent(_:)": {
      "abstract": [
        {
          "text": "Positions a music event iterator at the previous event on a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventIteratorPreviousEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorPreviousEvent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventIteratorPreviousEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicEventIteratorPreviousEvent(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventiteratorpreviousevent(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSeek(_:_:)": {
      "abstract": [
        {
          "text": "Positions a music event iterator at a specified timestamp, in beats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventIteratorSeek"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSeek(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventIteratorSeek"
        }
      ],
      "role": "symbol",
      "title": "MusicEventIteratorSeek(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventiteratorseek(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSetEventInfo(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets information for the event at a music event iterator’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventIteratorSetEventInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventType",
          "text": "MusicEventType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSetEventInfo(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventIteratorSetEventInfo"
        }
      ],
      "role": "symbol",
      "title": "MusicEventIteratorSetEventInfo(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventiteratorseteventinfo(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSetEventTime(_:_:)": {
      "abstract": [
        {
          "text": "Sets the timestamp for the event at a music event iterator’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventIteratorSetEventTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSetEventTime(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventIteratorSetEventTime"
        }
      ],
      "role": "symbol",
      "title": "MusicEventIteratorSetEventTime(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventiteratorseteventtime(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventType": {
      "abstract": [
        {
          "text": "MIDI and other music event types, used by music event iterator functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicEventType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicEventType"
        }
      ],
      "role": "symbol",
      "title": "MusicEventType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musiceventtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicEventIterator(_:_:)": {
      "abstract": [
        {
          "text": "Creates a new music event iterator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NewMusicEventIterator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicEventIterator",
          "text": "MusicEventIterator"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicEventIterator(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NewMusicEventIterator"
        }
      ],
      "role": "symbol",
      "title": "NewMusicEventIterator(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/newmusiceventiterator(_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Iterating-Over-Music-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicEventIterator(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicEventIterator(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorNextEvent(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSeek(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorDeleteEvent(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorGetEventInfo(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasCurrentEvent(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasNextEvent(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasPreviousEvent(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorPreviousEvent(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSetEventInfo(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSetEventTime(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIterator",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventType",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedNoteOnEvent"
      ],
      "title": "Iterating Over Music Events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/init()",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/init(argCount:mPitch:mVelocity:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/argCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/mPitch",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/mVelocity"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MusicDeviceStdNoteParams"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceStdNoteParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceStdNoteParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/argCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/mPitch",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceStdNoteParams/mVelocity"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Iterating-Over-Music-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicEventIterator(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicEventIterator(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorNextEvent(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSeek(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorDeleteEvent(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorGetEventInfo(_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasCurrentEvent(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasNextEvent(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorHasPreviousEvent(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorPreviousEvent(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSetEventInfo(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIteratorSetEventTime(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventIterator",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicEventType",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedNoteOnEvent"
              ],
              "title": "Iterating Over Music Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MusicDeviceStdNoteParams"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorHasNextEvent(_:_:)/title",
          "value": "MusicEventIteratorHasNextEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorHasNextEvent(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIteratorHasNextEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventType/title",
          "value": "MusicEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NewMusicEventIterator(_:_:)/title",
          "value": "NewMusicEventIterator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NewMusicEventIterator(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NewMusicEventIterator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceStdNoteParams~1mVelocity/title",
          "value": "mVelocity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceStdNoteParams~1mVelocity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIterator/title",
          "value": "MusicEventIterator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIterator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIterator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIterator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIterator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceStdNoteParams~1argCount/title",
          "value": "argCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceStdNoteParams~1argCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "argCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorHasPreviousEvent(_:_:)/title",
          "value": "MusicEventIteratorHasPreviousEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorHasPreviousEvent(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIteratorHasPreviousEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceStdNoteParams~1mPitch/title",
          "value": "mPitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceStdNoteParams~1mPitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mPitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorHasCurrentEvent(_:_:)/title",
          "value": "MusicEventIteratorHasCurrentEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorHasCurrentEvent(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIteratorHasCurrentEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorSeek(_:_:)/title",
          "value": "MusicEventIteratorSeek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorSeek(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIteratorSeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorSetEventTime(_:_:)/title",
          "value": "MusicEventIteratorSetEventTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorSetEventTime(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIteratorSetEventTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorNextEvent(_:)/title",
          "value": "MusicEventIteratorNextEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorNextEvent(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIteratorNextEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorGetEventInfo(_:_:_:_:_:)/title",
          "value": "MusicEventIteratorGetEventInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorGetEventInfo(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIteratorGetEventInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceStdNoteParams/title",
          "value": "MusicDeviceStdNoteParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceStdNoteParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceStdNoteParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceStdNoteParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceStdNoteParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1DisposeMusicEventIterator(_:)/title",
          "value": "DisposeMusicEventIterator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1DisposeMusicEventIterator(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DisposeMusicEventIterator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedNoteOnEvent/title",
          "value": "ExtendedNoteOnEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedNoteOnEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedNoteOnEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedNoteOnEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedNoteOnEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorPreviousEvent(_:)/title",
          "value": "MusicEventIteratorPreviousEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorPreviousEvent(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIteratorPreviousEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorSetEventInfo(_:_:_:)/title",
          "value": "MusicEventIteratorSetEventInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorSetEventInfo(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIteratorSetEventInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorDeleteEvent(_:)/title",
          "value": "MusicEventIteratorDeleteEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicEventIteratorDeleteEvent(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicEventIteratorDeleteEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/musicdevicestdnoteparams"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/musicdevicestdnoteparams"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
