{
  "abstract": [
    {
      "text": "Supports control of the looping behavior of a music track.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@MusicTrackLoopInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MusicTrackLoopInfo"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MusicTrackLoopInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MusicTrackLoopInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MusicTrackLoopInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This data type is used for the value of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_LoopInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackClear(_:_:_:)": {
      "abstract": [
        {
          "text": "Removes a specified range of music track events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackClear"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackClear(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackClear"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackClear(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackclear(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCopyInsert(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Copies a range of events from one music track and inserts them into another music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackCopyInsert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCopyInsert(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackCopyInsert"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackCopyInsert(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackcopyinsert(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCut(_:_:_:)": {
      "abstract": [
        {
          "text": "Removes a specified range of music track events, and shifts later events toward the start of the track to fill in the gap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackCut"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCut(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackCut"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackCut(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackcut(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestMIDIEndpoint(_:_:)": {
      "abstract": [
        {
          "text": "Gets the MIDI endpoint that is the event target for a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackGetDestMIDIEndpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestMIDIEndpoint(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackGetDestMIDIEndpoint"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackGetDestMIDIEndpoint(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackgetdestmidiendpoint(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestNode(_:_:)": {
      "abstract": [
        {
          "text": "Gets the audio unit node that is the event target for a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackGetDestNode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUNode",
          "text": "AUNode"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestNode(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackGetDestNode"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackGetDestNode(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackgetdestnode(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetProperty(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets a music track property value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackGetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackGetProperty"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackGetProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackgetproperty(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetSequence(_:_:)": {
      "abstract": [
        {
          "text": "Gets the music sequence that the music track is a member of.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackGetSequence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetSequence(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackGetSequence"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackGetSequence(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackgetsequence(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo": {
      "abstract": [
        {
          "text": "Supports control of the looping behavior of a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackLoopInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackLoopInfo"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackLoopInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackloopinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackloopinfo/init()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/init(loopDuration:numberOfLoops:)": {
      "abstract": [
        {
          "text": "Initializes the music track loop information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "loopDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "numberOfLoops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/init(loopDuration:numberOfLoops:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(loopDuration:numberOfLoops:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackloopinfo/init(loopduration:numberofloops:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/loopDuration": {
      "abstract": [
        {
          "text": "The point in a music track, measured in beats from the end of the music track, at which to begin playback during looped playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loopDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/loopDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loopDuration"
        }
      ],
      "role": "symbol",
      "title": "loopDuration",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackloopinfo/loopduration"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/numberOfLoops": {
      "abstract": [
        {
          "text": "The number of times to play the designated portion of the music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfLoops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/numberOfLoops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfLoops"
        }
      ],
      "role": "symbol",
      "title": "numberOfLoops",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackloopinfo/numberofloops"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMerge(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Copies a range of events from one music track and merges them into another music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackMerge"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMerge(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackMerge"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackMerge(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackmerge(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMoveEvents(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Shifts music track events forward or backward in time, in terms of beats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackMoveEvents"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMoveEvents(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackMoveEvents"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackMoveEvents(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictrackmoveevents(_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewAUPresetEvent(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds an event of type ",
          "type": "text"
        },
        {
          "code": "AUPresetEvent",
          "type": "codeVoice"
        },
        {
          "text": " to a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackNewAUPresetEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AUPresetEvent",
          "text": "AUPresetEvent"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewAUPresetEvent(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackNewAUPresetEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackNewAUPresetEvent(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictracknewaupresetevent(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedNoteEvent(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds an event of type ",
          "type": "text"
        },
        {
          "code": "ExtendedNoteOnEvent",
          "type": "codeVoice"
        },
        {
          "text": " to a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackNewExtendedNoteEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@ExtendedNoteOnEvent",
          "text": "ExtendedNoteOnEvent"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedNoteEvent(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackNewExtendedNoteEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackNewExtendedNoteEvent(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictracknewextendednoteevent(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedTempoEvent(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds a tempo to a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackNewExtendedTempoEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedTempoEvent(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackNewExtendedTempoEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackNewExtendedTempoEvent(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictracknewextendedtempoevent(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIChannelEvent(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds an event of type ",
          "type": "text"
        },
        {
          "code": "MIDIChannelMessage",
          "type": "codeVoice"
        },
        {
          "text": " to a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackNewMIDIChannelEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIChannelMessage",
          "text": "MIDIChannelMessage"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIChannelEvent(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackNewMIDIChannelEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackNewMIDIChannelEvent(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictracknewmidichannelevent(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDINoteEvent(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds an event of type ",
          "type": "text"
        },
        {
          "code": "MIDINoteMessage",
          "type": "codeVoice"
        },
        {
          "text": " to a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackNewMIDINoteEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDINoteMessage",
          "text": "MIDINoteMessage"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDINoteEvent(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackNewMIDINoteEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackNewMIDINoteEvent(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictracknewmidinoteevent(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIRawDataEvent(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds an event of type ",
          "type": "text"
        },
        {
          "code": "MIDIRawData",
          "type": "codeVoice"
        },
        {
          "text": " to a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicTrackNewMIDIRawDataEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTrack",
          "text": "MusicTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicTimeStamp",
          "text": "MusicTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIRawData",
          "text": "MIDIRawData"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIRawDataEvent(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicTrackNewMIDIRawDataEvent"
        }
      ],
      "role": "symbol",
      "title": "MusicTrackNewMIDIRawDataEvent(_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictracknewmidirawdataevent(_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicTrackFrom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NewMusicTrackFrom"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicTrackFrom",
      "kind": "symbol",
      "role": "symbol",
      "title": "NewMusicTrackFrom",
      "type": "topic",
      "url": "/documentation/audiotoolbox/newmusictrackfrom"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_LoopInfo": {
      "abstract": [
        {
          "text": "Looping information for a music track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_LoopInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kSequenceTrackProperty_LoopInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSequenceTrackProperty_LoopInfo"
        }
      ],
      "role": "symbol",
      "title": "kSequenceTrackProperty_LoopInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/ksequencetrackproperty_loopinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Music-Tracks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackClear(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCopyInsert(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCut(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestMIDIEndpoint(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestNode(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetProperty(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetSequence(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMerge(_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMoveEvents(_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewAUPresetEvent(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedNoteEvent(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedTempoEvent(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIChannelEvent(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDINoteEvent(_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIRawDataEvent(_:_:_:)"
      ],
      "title": "Managing Music Tracks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/init()",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/init(loopDuration:numberOfLoops:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/loopDuration",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/numberOfLoops"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MusicTrackLoopInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackLoopInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackLoopInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/loopDuration",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackLoopInfo/numberOfLoops"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Music-Tracks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicTrackFrom",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackClear(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCopyInsert(_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackCut(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestMIDIEndpoint(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetDestNode(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetProperty(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackGetSequence(_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMerge(_:_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackMoveEvents(_:_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewAUPresetEvent(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedNoteEvent(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedTempoEvent(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDIChannelEvent(_:_:_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewMIDINoteEvent(_:_:_:)"
              ],
              "title": "Managing Music Tracks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MusicTrackLoopInfo"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "MusicTrackLoopInfo"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDIChannelEvent(_:_:_:)/title",
          "value": "MusicTrackNewMIDIChannelEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDIChannelEvent(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackNewMIDIChannelEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDINoteEvent(_:_:_:)/title",
          "value": "MusicTrackNewMIDINoteEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDINoteEvent(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackNewMIDINoteEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewExtendedNoteEvent(_:_:_:)/title",
          "value": "MusicTrackNewExtendedNoteEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewExtendedNoteEvent(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackNewExtendedNoteEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDIRawDataEvent(_:_:_:)/title",
          "value": "MusicTrackNewMIDIRawDataEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewMIDIRawDataEvent(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackNewMIDIRawDataEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetDestMIDIEndpoint(_:_:)/title",
          "value": "MusicTrackGetDestMIDIEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetDestMIDIEndpoint(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackGetDestMIDIEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewAUPresetEvent(_:_:_:)/title",
          "value": "MusicTrackNewAUPresetEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewAUPresetEvent(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackNewAUPresetEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackLoopInfo/title",
          "value": "MusicTrackLoopInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackLoopInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackLoopInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackLoopInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackLoopInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackClear(_:_:_:)/title",
          "value": "MusicTrackClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackClear(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackCut(_:_:_:)/title",
          "value": "MusicTrackCut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackCut(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackCut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackMerge(_:_:_:_:_:)/title",
          "value": "MusicTrackMerge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackMerge(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackMerge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewExtendedTempoEvent(_:_:_:)/title",
          "value": "MusicTrackNewExtendedTempoEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackNewExtendedTempoEvent(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackNewExtendedTempoEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackLoopInfo~1loopDuration/title",
          "value": "loopDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackLoopInfo~1loopDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "loopDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackCopyInsert(_:_:_:_:_:)/title",
          "value": "MusicTrackCopyInsert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackCopyInsert(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackCopyInsert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetSequence(_:_:)/title",
          "value": "MusicTrackGetSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetSequence(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackGetSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetDestNode(_:_:)/title",
          "value": "MusicTrackGetDestNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetDestNode(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackGetDestNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_LoopInfo/title",
          "value": "kSequenceTrackProperty_LoopInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kSequenceTrackProperty_LoopInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSequenceTrackProperty_LoopInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetProperty(_:_:_:_:)/title",
          "value": "MusicTrackGetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackGetProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackGetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackLoopInfo~1numberOfLoops/title",
          "value": "numberOfLoops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackLoopInfo~1numberOfLoops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfLoops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackMoveEvents(_:_:_:_:)/title",
          "value": "MusicTrackMoveEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTrackMoveEvents(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicTrackMoveEvents"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/musictrackloopinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/musictrackloopinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
