{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceReleaseInstrument"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@MusicDeviceReleaseInstrument",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MusicDeviceReleaseInstrument"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MusicDeviceReleaseInstrument"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.5",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "MusicDeviceReleaseInstrument"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MusicDeviceReleaseInstrument"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceComponent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MusicDeviceComponent",
              "text": "MusicDeviceComponent"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inUnit"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceInstrumentID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MusicDeviceInstrumentID",
              "text": "MusicDeviceInstrumentID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inInstrument"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetIcon(_:_:)": {
      "abstract": [
        {
          "text": "The UIImage of the audio component’s icon.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentGetIcon"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponent",
          "text": "AudioComponent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetIcon(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentGetIcon"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentGetIcon(_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentgeticon(_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetLastActiveTime(_:)": {
      "abstract": [
        {
          "text": "The time at which the application publishing the component was last active.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentGetLastActiveTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponent",
          "text": "AudioComponent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAbsoluteTime",
          "text": "CFAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetLastActiveTime(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentGetLastActiveTime"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentGetLastActiveTime(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentgetlastactivetime(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentCreate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentCreate"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileComponentCreate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentcreate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentDataIsThisFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentDataIsThisFormat"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentDataIsThisFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileComponentDataIsThisFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentdataisthisformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentFileIsThisFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentFileIsThisFormat"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentFileIsThisFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileComponentFileIsThisFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentfileisthisformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitialize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileComponentInitialize"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitialize",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileComponentInitialize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecomponentinitialize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileCreate": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileCreate"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileCreate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilecreate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileInitialize": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileInitialize"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileInitialize",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileInitialize",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofileinitialize"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileOpen": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileOpen"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileOpen",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileOpen",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofileopen"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileReadPackets(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Reads a fixed duration of audio data from an audio file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFileReadPackets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFileID",
          "text": "AudioFileID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileReadPackets(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFileReadPackets"
        }
      ],
      "role": "symbol",
      "title": "AudioFileReadPackets(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilereadpackets(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceComponent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicDeviceComponent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicDeviceComponent"
        }
      ],
      "role": "symbol",
      "title": "MusicDeviceComponent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdevicecomponent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceInstrumentID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicDeviceInstrumentID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceInstrumentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicDeviceInstrumentID"
        }
      ],
      "role": "symbol",
      "title": "MusicDeviceInstrumentID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdeviceinstrumentid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceReleaseInstrument": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MusicDeviceReleaseInstrument"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicDeviceReleaseInstrument",
      "kind": "symbol",
      "role": "symbol",
      "title": "MusicDeviceReleaseInstrument",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicdevicereleaseinstrument"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFDataWithFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MusicSequenceLoadSMFDataWithFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFDataWithFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "MusicSequenceLoadSMFDataWithFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequenceloadsmfdatawithflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFWithFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MusicSequenceLoadSMFWithFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFWithFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "MusicSequenceLoadSMFWithFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequenceloadsmfwithflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveMIDIFile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MusicSequenceSaveMIDIFile"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveMIDIFile",
      "kind": "symbol",
      "role": "symbol",
      "title": "MusicSequenceSaveMIDIFile",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencesavemidifile"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveSMFData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MusicSequenceSaveSMFData"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveSMFData",
      "kind": "symbol",
      "role": "symbol",
      "title": "MusicSequenceSaveSMFData",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencesavesmfdata"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedControlEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MusicTrackNewExtendedControlEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedControlEvent",
      "kind": "symbol",
      "role": "symbol",
      "title": "MusicTrackNewExtendedControlEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musictracknewextendedcontrolevent"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileCreate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileInitialize",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileOpen",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileReadPackets(_:_:_:_:_:_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFDataWithFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceLoadSMFWithFlags",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveMIDIFile",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceSaveSMFData",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTrackNewExtendedControlEvent",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetIcon(_:_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentGetLastActiveTime(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentCreate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentDataIsThisFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentFileIsThisFormat",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileComponentInitialize"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceInstrumentID/title",
          "value": "MusicDeviceInstrumentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceInstrumentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceInstrumentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceInstrumentID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceInstrumentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentGetLastActiveTime(_:)/title",
          "value": "AudioComponentGetLastActiveTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentGetLastActiveTime(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentGetLastActiveTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceComponent/title",
          "value": "MusicDeviceComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicDeviceComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicDeviceComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileReadPackets(_:_:_:_:_:_:_:)/title",
          "value": "AudioFileReadPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFileReadPackets(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFileReadPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentGetIcon(_:_:)/title",
          "value": "AudioComponentGetIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentGetIcon(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentGetIcon"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/musicdevicereleaseinstrument"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
