{"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicPlayerIsPlaying","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"inPlayer","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayer","text":"MusicPlayer","preciseIdentifier":"c:@T@MusicPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"outIsPlaying","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sp","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DarwinBoolean","preciseIdentifier":"s:6Darwin0A7BooleanV","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}]}],"kind":"declarations"},{"parameters":[{"name":"inPlayer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The music player to query."}]}]},{"name":"outIsPlaying","content":[{"inlineContent":[{"text":"On output ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" (nonzero) if playing, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" (zero) if not playing.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A result code","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"If a music player has started playing and has not been explicitly stopped, the ","type":"text"},{"code":"outIsPlaying","type":"codeVoice"},{"text":" value is ","type":"text"},{"code":"true","type":"codeVoice"},{"text":". Specifically, if the player’s music sequence has completed—so there is no more audible output—but the player has not been explicitly stopped, the ","type":"text"},{"code":"outIsPlaying","type":"codeVoice"},{"text":" value is ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" and the music player’s time value continues to increase.","type":"text"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"seeAlsoSections":[{"title":"Managing a Music Player","anchor":"Managing-a-Music-Player","generated":true,"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicPlayer(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicPlayer(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetBeatsForHostTime(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetHostTimeForBeats(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetPlayRateScalar(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetSequence(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetTime(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerPreroll(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetPlayRateScalar(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetSequence(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetTime(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStart(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStop(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayer","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp"]}],"variants":[{"paths":["/documentation/audiotoolbox/musicplayerisplaying(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/audiotoolbox/musicplayerisplaying(_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Indicates whether or not a music player is playing."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerIsPlaying(_:_:)"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MusicPlayerIsPlaying"}],"roleHeading":"Function","externalID":"c:@F@MusicPlayerIsPlaying","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicPlayerIsPlaying"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer","text":"MusicPlayer"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:6Darwin0A7BooleanV","text":"DarwinBoolean"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"platforms":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"5.0","deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"5.0","deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","deprecated":false},{"unavailable":false,"name":"macOS","beta":false,"introducedAt":"10.2","deprecated":false},{"unavailable":false,"name":"tvOS","beta":false,"introducedAt":"9.0","deprecated":false},{"unavailable":false,"name":"visionOS","beta":false,"introducedAt":"1.0","deprecated":false}],"symbolKind":"func","title":"MusicPlayerIsPlaying(_:_:)","modules":[{"name":"Audio Toolbox"}]},"kind":"symbol","references":{"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStop(_:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Stops playback of a music player."}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStop(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicPlayerStop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":") -> ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"url":"/documentation/audiotoolbox/musicplayerstop(_:)","title":"MusicPlayerStop(_:)","role":"symbol","navigatorTitle":[{"text":"MusicPlayerStop","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Sp":{"url":"/documentation/Swift/UnsafeMutablePointer","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Pointee","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}],"type":"topic","title":"UnsafeMutablePointer","identifier":"doc://com.externally.resolved.symbol/s:Sp","abstract":[{"text":"A pointer for accessing and manipulating data of a specific type.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetHostTimeForBeats(_:_:_:)":{"title":"MusicPlayerGetHostTimeForBeats(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"MusicPlayerGetHostTimeForBeats","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":", ","kind":"text"},{"text":"MusicTimeStamp","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTimeStamp"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"Gets the host time associated with a specified beat."}],"navigatorTitle":[{"text":"MusicPlayerGetHostTimeForBeats","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetHostTimeForBeats(_:_:_:)","url":"/documentation/audiotoolbox/musicplayergethosttimeforbeats(_:_:_:)","kind":"symbol","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetBeatsForHostTime(_:_:_:)":{"type":"topic","title":"MusicPlayerGetBeatsForHostTime(_:_:_:)","url":"/documentation/audiotoolbox/musicplayergetbeatsforhosttime(_:_:_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicPlayerGetBeatsForHostTime"},{"kind":"text","text":"("},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":", ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@MusicTimeStamp","text":"MusicTimeStamp","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"MusicPlayerGetBeatsForHostTime","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetBeatsForHostTime(_:_:_:)","abstract":[{"type":"text","text":"Gets the beat number associated a specified host time."}],"role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetSequence(_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicPlayerGetSequence","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@MusicSequence","text":"MusicSequence","kind":"typeIdentifier"},{"text":"?>) -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"title":"MusicPlayerGetSequence(_:_:)","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetSequence(_:_:)","url":"/documentation/audiotoolbox/musicplayergetsequence(_:_:)","navigatorTitle":[{"text":"MusicPlayerGetSequence","kind":"identifier"}],"abstract":[{"type":"text","text":"Gets the music sequence associated with a music player."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicPlayer(_:)":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates a new music player."}],"url":"/documentation/audiotoolbox/newmusicplayer(_:)","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicPlayer(_:)","navigatorTitle":[{"text":"NewMusicPlayer","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewMusicPlayer"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":"?>) -> ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"title":"NewMusicPlayer(_:)"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerIsPlaying(_:_:)":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Indicates whether or not a music player is playing."}],"url":"/documentation/audiotoolbox/musicplayerisplaying(_:_:)","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerIsPlaying(_:_:)","navigatorTitle":[{"text":"MusicPlayerIsPlaying","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicPlayerIsPlaying","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:6Darwin0A7BooleanV","text":"DarwinBoolean","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"title":"MusicPlayerIsPlaying(_:_:)"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp":{"kind":"symbol","url":"/documentation/audiotoolbox/musictimestamp","navigatorTitle":[{"text":"MusicTimeStamp","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicTimeStamp","kind":"identifier"}],"role":"symbol","type":"topic","title":"MusicTimeStamp","abstract":[{"text":"A timestamp for use by a music sequence.","type":"text"}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayer":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A music player plays a music sequence (of type "},{"type":"codeVoice","code":"MusicSequence"},{"type":"text","text":")."}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayer","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicPlayer","kind":"identifier"}],"url":"/documentation/audiotoolbox/musicplayer","title":"MusicPlayer","role":"symbol","navigatorTitle":[{"text":"MusicPlayer","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetPlayRateScalar(_:_:)":{"title":"MusicPlayerGetPlayRateScalar(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicPlayerGetPlayRateScalar"},{"text":"(","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s7Float64a","text":"Float64","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"Gets the playback rate multiplier for a music player."}],"navigatorTitle":[{"text":"MusicPlayerGetPlayRateScalar","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetPlayRateScalar(_:_:)","url":"/documentation/audiotoolbox/musicplayergetplayratescalar(_:_:)","kind":"symbol","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetTime(_:_:)":{"title":"MusicPlayerSetTime(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicPlayerSetTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":", ","kind":"text"},{"text":"MusicTimeStamp","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicTimeStamp"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Sets the playback point for a music player, in beats.","type":"text"}],"navigatorTitle":[{"text":"MusicPlayerSetTime","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetTime(_:_:)","url":"/documentation/audiotoolbox/musicplayersettime(_:_:)","kind":"symbol","role":"symbol"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetTime(_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicPlayerGetTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@MusicTimeStamp","text":"MusicTimeStamp","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"title":"MusicPlayerGetTime(_:_:)","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetTime(_:_:)","url":"/documentation/audiotoolbox/musicplayergettime(_:_:)","navigatorTitle":[{"text":"MusicPlayerGetTime","kind":"identifier"}],"abstract":[{"type":"text","text":"Gets the playback point for a music player, in beats."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicPlayer(_:)":{"role":"symbol","type":"topic","abstract":[{"text":"Disposes of a music player.","type":"text"}],"url":"/documentation/audiotoolbox/disposemusicplayer(_:)","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicPlayer(_:)","navigatorTitle":[{"text":"DisposeMusicPlayer","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisposeMusicPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MusicPlayer","preciseIdentifier":"c:@T@MusicPlayer"},{"text":") -> ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"title":"DisposeMusicPlayer(_:)"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetPlayRateScalar(_:_:)":{"kind":"symbol","url":"/documentation/audiotoolbox/musicplayersetplayratescalar(_:_:)","navigatorTitle":[{"text":"MusicPlayerSetPlayRateScalar","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetPlayRateScalar(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicPlayerSetPlayRateScalar","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":", ","kind":"text"},{"text":"Float64","kind":"typeIdentifier","preciseIdentifier":"s:s7Float64a"},{"text":") -> ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"role":"symbol","type":"topic","title":"MusicPlayerSetPlayRateScalar(_:_:)","abstract":[{"type":"text","text":"Sets a playback rate multiplier for a music player."}]},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetSequence(_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicPlayerSetSequence","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":", ","kind":"text"},{"text":"MusicSequence","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicSequence"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"title":"MusicPlayerSetSequence(_:_:)","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetSequence(_:_:)","url":"/documentation/audiotoolbox/musicplayersetsequence(_:_:)","navigatorTitle":[{"text":"MusicPlayerSetSequence","kind":"identifier"}],"abstract":[{"type":"text","text":"Sets the music sequence for the music player to play."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerPreroll(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MusicPlayerPreroll"},{"text":"(","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"title":"MusicPlayerPreroll(_:)","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerPreroll(_:)","url":"/documentation/audiotoolbox/musicplayerpreroll(_:)","navigatorTitle":[{"text":"MusicPlayerPreroll","kind":"identifier"}],"abstract":[{"type":"text","text":"Prepares a music player to play."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStart(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MusicPlayerStart","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@T@MusicPlayer"},{"text":") -> ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"navigatorTitle":[{"text":"MusicPlayerStart","kind":"identifier"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStart(_:)","abstract":[{"text":"Starts playback of a music player.","type":"text"}],"kind":"symbol","type":"topic","title":"MusicPlayerStart(_:)","url":"/documentation/audiotoolbox/musicplayerstart(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"5.0","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"5.0","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false},{"beta":false,"deprecated":false,"name":"macOS","introducedAt":"10.2","unavailable":false},{"beta":false,"deprecated":false,"name":"tvOS","introducedAt":"9.0","unavailable":false},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Function","path":"/metadata/roleHeading","op":"replace"},{"value":"MusicPlayerIsPlaying","path":"/metadata/title","op":"replace"},{"value":"func","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"MusicPlayerIsPlaying","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"identifiers":["doc://com.apple.audiotoolbox/documentation/AudioToolbox/NewMusicPlayer(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/DisposeMusicPlayer(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetBeatsForHostTime(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetHostTimeForBeats(_:_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetPlayRateScalar(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetSequence(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerGetTime(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerPreroll(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetPlayRateScalar(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetSequence(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerSetTime(_:_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStart(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayerStop(_:)","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayer","doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicTimeStamp"],"title":"Managing a Music Player","anchor":"Managing-a-Music-Player"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"},{"kind":"text","text":" "},{"text":"MusicPlayerIsPlaying","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MusicPlayer","preciseIdentifier":"c:@T@MusicPlayer","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicPlayer","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"inPlayer","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"Boolean","preciseIdentifier":"c:@T@Boolean","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"outIsPlaying","kind":"internalParam"},{"text":");","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The music player to query."}]}],"name":"inPlayer"},{"content":[{"inlineContent":[{"type":"text","text":"On output "},{"type":"codeVoice","code":"true"},{"type":"text","text":" (nonzero) if playing, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" (zero) if not playing."}],"type":"paragraph"}],"name":"outIsPlaying"}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A result code"}]}]},"path":"/primaryContentSections/2","op":"replace"},{"op":"replace","value":"MusicPlayerStop","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerStop(_:)/title"},{"op":"replace","value":[{"text":"MusicPlayerStop","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerStop(_:)/fragments"},{"op":"replace","value":"MusicPlayerGetHostTimeForBeats","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetHostTimeForBeats(_:_:_:)/title"},{"op":"replace","value":[{"text":"MusicPlayerGetHostTimeForBeats","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetHostTimeForBeats(_:_:_:)/fragments"},{"op":"replace","value":"MusicPlayerGetBeatsForHostTime","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetBeatsForHostTime(_:_:_:)/title"},{"op":"replace","value":[{"text":"MusicPlayerGetBeatsForHostTime","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetBeatsForHostTime(_:_:_:)/fragments"},{"op":"replace","value":"MusicPlayerGetSequence","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetSequence(_:_:)/title"},{"op":"replace","value":[{"text":"MusicPlayerGetSequence","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetSequence(_:_:)/fragments"},{"value":"NewMusicPlayer","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NewMusicPlayer(_:)/title"},{"value":[{"kind":"identifier","text":"NewMusicPlayer"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NewMusicPlayer(_:)/fragments"},{"value":"MusicPlayerIsPlaying","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerIsPlaying(_:_:)/title"},{"value":[{"text":"MusicPlayerIsPlaying","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerIsPlaying(_:_:)/fragments"},{"value":"MusicTimeStamp","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/title"},{"value":[{"kind":"identifier","text":"MusicTimeStamp"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/fragments"},{"value":[{"kind":"identifier","text":"MusicTimeStamp"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicTimeStamp/navigatorTitle"},{"value":"MusicPlayer","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayer/title"},{"value":[{"text":"MusicPlayer","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayer/fragments"},{"value":[{"kind":"identifier","text":"MusicPlayer"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayer/navigatorTitle"},{"value":"MusicPlayerGetPlayRateScalar","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetPlayRateScalar(_:_:)/title"},{"value":[{"text":"MusicPlayerGetPlayRateScalar","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetPlayRateScalar(_:_:)/fragments"},{"value":"MusicPlayerSetTime","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetTime(_:_:)/title"},{"value":[{"text":"MusicPlayerSetTime","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetTime(_:_:)/fragments"},{"value":"MusicPlayerGetTime","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetTime(_:_:)/title"},{"value":[{"kind":"identifier","text":"MusicPlayerGetTime"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerGetTime(_:_:)/fragments"},{"value":"DisposeMusicPlayer","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1DisposeMusicPlayer(_:)/title"},{"value":[{"text":"DisposeMusicPlayer","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1DisposeMusicPlayer(_:)/fragments"},{"value":"MusicPlayerSetPlayRateScalar","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetPlayRateScalar(_:_:)/title"},{"value":[{"text":"MusicPlayerSetPlayRateScalar","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetPlayRateScalar(_:_:)/fragments"},{"value":"MusicPlayerSetSequence","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetSequence(_:_:)/title"},{"value":[{"text":"MusicPlayerSetSequence","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerSetSequence(_:_:)/fragments"},{"value":"MusicPlayerPreroll","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerPreroll(_:)/title"},{"value":[{"kind":"identifier","text":"MusicPlayerPreroll"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerPreroll(_:)/fragments"},{"value":"MusicPlayerStart","op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerStart(_:)/title"},{"value":[{"text":"MusicPlayerStart","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicPlayerStart(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}