{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@ScheduledAudioFileRegion",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ScheduledAudioFileRegion"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ScheduledAudioFileRegion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "ScheduledAudioFileRegion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegion"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount": {
      "abstract": [
        {
          "text": "A number of audio channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioChannelCount"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioChannelCount"
        }
      ],
      "role": "symbol",
      "title": "AUAudioChannelCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiochannelcount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount": {
      "abstract": [
        {
          "text": "A number of audio sample frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioFrameCount"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioFrameCount"
        }
      ],
      "role": "symbol",
      "title": "AUAudioFrameCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudioframecount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioObjectID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioObjectID"
        }
      ],
      "role": "symbol",
      "title": "AUAudioObjectID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudioobjectid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus": {
      "abstract": [
        {
          "text": "A result code returned from an audio unit’s render function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitStatus"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitStatus",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounitstatus"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUEventListenerProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUEventListenerProc"
        }
      ],
      "role": "symbol",
      "title": "AUEventListenerProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aueventlistenerproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUEventListenerRef"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUEventListenerRef"
        }
      ],
      "role": "symbol",
      "title": "AUEventListenerRef",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aueventlistenerref"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime": {
      "abstract": [
        {
          "text": "Expresses time as a sample count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUEventSampleTime"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUEventSampleTime"
        }
      ],
      "role": "symbol",
      "title": "AUEventSampleTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aueventsampletime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver": {
      "abstract": [
        {
          "text": "A block called to notify the audio unit implementation of changes to a parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUImplementorValueObserver"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUImplementorValueObserver"
        }
      ],
      "role": "symbol",
      "title": "AUImplementorValueObserver",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auimplementorvalueobserver"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider": {
      "abstract": [
        {
          "text": "A block called to fetch a parameter’s current value from the audio unit implementation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUImplementorValueProvider"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUImplementorValueProvider"
        }
      ],
      "role": "symbol",
      "title": "AUImplementorValueProvider",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auimplementorvalueprovider"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUInputHandler": {
      "abstract": [
        {
          "text": "A block to notify the host of an I/O unit that an input is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUInputHandler"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUInputHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUInputHandler"
        }
      ],
      "role": "symbol",
      "title": "AUInputHandler",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auinputhandler"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUMIDICIProfileChangedBlock"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUMIDICIProfileChangedBlock"
        }
      ],
      "role": "symbol",
      "title": "AUMIDICIProfileChangedBlock",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aumidiciprofilechangedblock"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber": {
      "abstract": [
        {
          "text": "MIDI Channel, 0~15 (channels 1 through 16, respectively).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIChannelNumber"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIChannelNumber"
        }
      ],
      "role": "symbol",
      "title": "MIDIChannelNumber",
      "type": "topic",
      "url": "/documentation/audiotoolbox/midichannelnumber"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegion"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegion"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioFileRegion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/init(mTimeStamp:mCompletionProc:mCompletionProcUserData:mAudioFile:mLoopCount:mStartFrame:mFramesToPlay:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mCompletionProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ScheduledAudioFileRegionCompletionProc",
          "text": "ScheduledAudioFileRegionCompletionProc"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "mCompletionProcUserData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "mAudioFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mLoopCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mStartFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mFramesToPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/init(mTimeStamp:mCompletionProc:mCompletionProcUserData:mAudioFile:mLoopCount:mStartFrame:mFramesToPlay:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mTimeStamp:mCompletionProc:mCompletionProcUserData:mAudioFile:mLoopCount:mStartFrame:mFramesToPlay:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregion/init(mtimestamp:mcompletionproc:mcompletionprocuserdata:maudiofile:mloopcount:mstartframe:mframestoplay:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mAudioFile": {
      "abstract": [
        {
          "text": "Must be a valid and already-open audio file object (of type ",
          "type": "text"
        },
        {
          "code": "AudioFileID",
          "type": "codeVoice"
        },
        {
          "text": "), as declared in ",
          "type": "text"
        },
        {
          "code": "AudioToolbox/AudioFile.h",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mAudioFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mAudioFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mAudioFile"
        }
      ],
      "role": "symbol",
      "title": "mAudioFile",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregion/maudiofile"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mCompletionProc": {
      "abstract": [
        {
          "text": "may be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mCompletionProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ScheduledAudioFileRegionCompletionProc",
          "text": "ScheduledAudioFileRegionCompletionProc"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mCompletionProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mCompletionProc"
        }
      ],
      "role": "symbol",
      "title": "mCompletionProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregion/mcompletionproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mCompletionProcUserData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mCompletionProcUserData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mCompletionProcUserData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mCompletionProcUserData"
        }
      ],
      "role": "symbol",
      "title": "mCompletionProcUserData",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregion/mcompletionprocuserdata"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mFramesToPlay": {
      "abstract": [
        {
          "text": "The number of frames to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mFramesToPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mFramesToPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mFramesToPlay"
        }
      ],
      "role": "symbol",
      "title": "mFramesToPlay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregion/mframestoplay"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mLoopCount": {
      "abstract": [
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " = do not loop",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mLoopCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mLoopCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mLoopCount"
        }
      ],
      "role": "symbol",
      "title": "mLoopCount",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregion/mloopcount"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mStartFrame": {
      "abstract": [
        {
          "text": "The frame offset into the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mStartFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mStartFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mStartFrame"
        }
      ],
      "role": "symbol",
      "title": "mStartFrame",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregion/mstartframe"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mTimeStamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "mTimeStamp",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregion/mtimestamp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegionCompletionProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioFileRegionCompletionProc"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioFileRegionCompletionProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudiofileregioncompletionproc"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioSlice"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioSlice"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioSlice",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudioslice"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScheduledAudioSliceCompletionProc"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScheduledAudioSliceCompletionProc"
        }
      ],
      "role": "symbol",
      "title": "ScheduledAudioSliceCompletionProc",
      "type": "topic",
      "url": "/documentation/audiotoolbox/scheduledaudioslicecompletionproc"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Unit-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUInputHandler"
      ],
      "title": "Audio Unit Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/init(mTimeStamp:mCompletionProc:mCompletionProcUserData:mAudioFile:mLoopCount:mStartFrame:mFramesToPlay:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mAudioFile",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mCompletionProc",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mCompletionProcUserData",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mFramesToPlay",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mLoopCount",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mStartFrame",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mTimeStamp"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ScheduledAudioFileRegion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mAudioFile",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mCompletionProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mCompletionProcUserData",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mFramesToPlay",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mLoopCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mStartFrame",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegion/mTimeStamp"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Unit-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSlice",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioFileRegionCompletionProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ScheduledAudioSliceCompletionProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MIDIChannelNumber",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioObjectID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUMIDICIProfileChangedBlock",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioChannelCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioFrameCount",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnitStatus",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerProc",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventListenerRef",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUEventSampleTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueObserver",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUImplementorValueProvider",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUInputHandler"
              ],
              "title": "Audio Unit Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ScheduledAudioFileRegion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mLoopCount/title",
          "value": "mLoopCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mLoopCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mLoopCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mCompletionProcUserData/title",
          "value": "mCompletionProcUserData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mCompletionProcUserData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mCompletionProcUserData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/title",
          "value": "MIDIChannelNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIChannelNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MIDIChannelNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIChannelNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mCompletionProc/title",
          "value": "mCompletionProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mCompletionProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mFramesToPlay/title",
          "value": "mFramesToPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mFramesToPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mFramesToPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mAudioFile/title",
          "value": "mAudioFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mAudioFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mAudioFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/title",
          "value": "AUAudioObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/title",
          "value": "ScheduledAudioFileRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/title",
          "value": "ScheduledAudioFileRegionCompletionProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegionCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegionCompletionProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioFileRegionCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/title",
          "value": "AUAudioFrameCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioFrameCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUInputHandler/title",
          "value": "AUInputHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUInputHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUInputHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUInputHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUInputHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/title",
          "value": "AUMIDICIProfileChangedBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUMIDICIProfileChangedBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUMIDICIProfileChangedBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUMIDICIProfileChangedBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/title",
          "value": "AUAudioChannelCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioChannelCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioChannelCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioChannelCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/title",
          "value": "AUImplementorValueProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/title",
          "value": "AUImplementorValueObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUImplementorValueObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUImplementorValueObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/title",
          "value": "AUEventListenerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/title",
          "value": "ScheduledAudioSliceCompletionProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSliceCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSliceCompletionProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSliceCompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/title",
          "value": "ScheduledAudioSlice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSlice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioSlice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScheduledAudioSlice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/title",
          "value": "AUEventListenerProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventListenerProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mStartFrame/title",
          "value": "mStartFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mStartFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mStartFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/title",
          "value": "AUAudioUnitStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnitStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/title",
          "value": "AUEventSampleTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventSampleTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUEventSampleTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUEventSampleTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mTimeStamp/title",
          "value": "mTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ScheduledAudioFileRegion~1mTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mTimeStamp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/scheduledaudiofileregion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/scheduledaudiofileregion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
