{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetPropertyFDF"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@SetPropertyFDF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SetPropertyFDF"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SetPropertyFDF"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "SetPropertyFDF"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SetPropertyFDF"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioFilePropertyID",
              "text": "AudioFilePropertyID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SV",
              "text": "UnsafeRawPointer"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID": {
      "abstract": [
        {
          "text": "An audio file property identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFilePropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFilePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFilePropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioFilePropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilepropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionPropertyID": {
      "abstract": [
        {
          "text": "The data type for an audio session property identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioSessionPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioSessionPropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioSessionPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiosessionpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedControlEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExtendedControlEvent"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedControlEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExtendedControlEvent"
        }
      ],
      "role": "symbol",
      "title": "ExtendedControlEvent",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extendedcontrolevent"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MagicCookieInfo": {
      "abstract": [
        {
          "text": "A structure holding magic cookie information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MagicCookieInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MagicCookieInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MagicCookieInfo"
        }
      ],
      "role": "symbol",
      "title": "MagicCookieInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/magiccookieinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NoteInstanceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NoteInstanceID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NoteInstanceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NoteInstanceID"
        }
      ],
      "role": "symbol",
      "title": "NoteInstanceID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/noteinstanceid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadBytesFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReadBytesFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadBytesFDF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReadBytesFDF"
        }
      ],
      "role": "symbol",
      "title": "ReadBytesFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/readbytesfdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadPacketDataFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReadPacketDataFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadPacketDataFDF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReadPacketDataFDF"
        }
      ],
      "role": "symbol",
      "title": "ReadPacketDataFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/readpacketdatafdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadPacketsFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReadPacketsFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadPacketsFDF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReadPacketsFDF"
        }
      ],
      "role": "symbol",
      "title": "ReadPacketsFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/readpacketsfdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetPropertyFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetPropertyFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetPropertyFDF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SetPropertyFDF"
        }
      ],
      "role": "symbol",
      "title": "SetPropertyFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/setpropertyfdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetUserDataFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetUserDataFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetUserDataFDF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SetUserDataFDF"
        }
      ],
      "role": "symbol",
      "title": "SetUserDataFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/setuserdatafdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/WriteBytesFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WriteBytesFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/WriteBytesFDF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WriteBytesFDF"
        }
      ],
      "role": "symbol",
      "title": "WriteBytesFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/writebytesfdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/WritePacketsFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WritePacketsFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/WritePacketsFDF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WritePacketsFDF"
        }
      ],
      "role": "symbol",
      "title": "WritePacketsFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/writepacketsfdf"
    },
    "doc://com.apple.documentation/documentation/CoreMIDI/MIDIEndpointRef": {
      "abstract": [
        {
          "text": "A MIDI source or destination an entity owns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIEndpointRef"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIObjectRef",
          "text": "MIDIObjectRef"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMIDI/MIDIEndpointRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDIEndpointRef",
      "type": "topic",
      "url": "/documentation/CoreMIDI/MIDIEndpointRef"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SV": {
      "abstract": [
        {
          "text": "A raw pointer for accessing untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SV",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedControlEvent",
        "doc://com.apple.documentation/documentation/CoreMIDI/MIDIEndpointRef",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MagicCookieInfo",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NoteInstanceID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadBytesFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadPacketDataFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadPacketsFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetUserDataFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/WriteBytesFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/WritePacketsFDF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionPropertyID"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SetPropertyFDF"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SetPropertyFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SetPropertyFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ExtendedControlEvent",
                "doc://com.apple.documentation/documentation/CoreMIDI/MIDIEndpointRef",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MagicCookieInfo",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/NoteInstanceID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadBytesFDF",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadPacketDataFDF",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadPacketsFDF",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/SetUserDataFDF",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/WriteBytesFDF",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/WritePacketsFDF",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioSessionPropertyID"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*FI(#*v#i#i#*1v)",
                    "text": "int (*)(void *, unsigned int, unsigned int, const void *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SetPropertyFDF"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionPropertyID/title",
          "value": "AudioSessionPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioSessionPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioSessionPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1WritePacketsFDF/title",
          "value": "WritePacketsFDF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1WritePacketsFDF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WritePacketsFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1WritePacketsFDF/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WritePacketsFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1WriteBytesFDF/title",
          "value": "WriteBytesFDF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1WriteBytesFDF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WriteBytesFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1WriteBytesFDF/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WriteBytesFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetUserDataFDF/title",
          "value": "SetUserDataFDF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetUserDataFDF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SetUserDataFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetUserDataFDF/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SetUserDataFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadPacketDataFDF/title",
          "value": "ReadPacketDataFDF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadPacketDataFDF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ReadPacketDataFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadPacketDataFDF/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ReadPacketDataFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadBytesFDF/title",
          "value": "ReadBytesFDF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadBytesFDF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ReadBytesFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadBytesFDF/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ReadBytesFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetPropertyFDF/title",
          "value": "SetPropertyFDF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetPropertyFDF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SetPropertyFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1SetPropertyFDF/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SetPropertyFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedControlEvent/title",
          "value": "ExtendedControlEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedControlEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedControlEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ExtendedControlEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ExtendedControlEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMIDI~1MIDIEndpointRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MIDIObjectRef",
              "text": "MIDIObjectRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDIEndpointRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NoteInstanceID/title",
          "value": "NoteInstanceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NoteInstanceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NoteInstanceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1NoteInstanceID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NoteInstanceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/title",
          "value": "AudioFilePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioFilePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFilePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MagicCookieInfo/title",
          "value": "MagicCookieInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MagicCookieInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MagicCookieInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MagicCookieInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MagicCookieInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadPacketsFDF/title",
          "value": "ReadPacketsFDF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadPacketsFDF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ReadPacketsFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadPacketsFDF/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ReadPacketsFDF"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/setpropertyfdf"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/setpropertyfdf"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
