{
  "abstract": [
    {
      "text": "Keys for the dictionaries in the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OutputDestinations",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " array.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/usb-accessory-audio-destination-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "USB Accessory Audio Destination Dictionary Keys"
  },
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support": {
      "abstract": [
        {
          "text": "Describe the properties that you associate with audio sessions and audio routes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Support",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-session-support"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputSources": {
      "abstract": [
        {
          "text": "Details on the available audio input sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InputSources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputSources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_InputSources"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_InputSources",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_inputsources"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OutputDestinations": {
      "abstract": [
        {
          "text": "Details on the available audio output destinations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OutputDestinations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_OutputDestinations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSessionProperty_OutputDestinations"
        }
      ],
      "role": "symbol",
      "title": "kAudioSessionProperty_OutputDestinations",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosessionproperty_outputdestinations"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_OutputDestinationKey_Description": {
      "abstract": [
        {
          "text": "The audio output destination.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSession_OutputDestinationKey_Description"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_OutputDestinationKey_Description",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSession_OutputDestinationKey_Description"
        }
      ],
      "role": "symbol",
      "title": "kAudioSession_OutputDestinationKey_Description",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosession_outputdestinationkey_description"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_OutputDestinationKey_ID": {
      "abstract": [
        {
          "text": "The output destination.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSession_OutputDestinationKey_ID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_OutputDestinationKey_ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSession_OutputDestinationKey_ID"
        }
      ],
      "role": "symbol",
      "title": "kAudioSession_OutputDestinationKey_ID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiosession_outputdestinationkey_id"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/usb-accessory-audio-source-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys for the dictionaries in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSessionProperty_InputSources",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " array.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/usb-accessory-audio-source-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "USB Accessory Audio Source Dictionary Keys",
      "type": "topic",
      "url": "/documentation/audiotoolbox/usb-accessory-audio-source-dictionary-keys"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "USB-Accessories",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/usb-accessory-audio-source-dictionary-keys"
      ],
      "title": "USB Accessories"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_OutputDestinationKey_ID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_OutputDestinationKey_Description"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_OutputDestinationKey_ID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioSession_OutputDestinationKey_Description"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "USB-Accessories",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/usb-accessory-audio-source-dictionary-keys"
              ],
              "title": "USB Accessories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_OutputDestinationKey_Description/title",
          "value": "kAudioSession_OutputDestinationKey_Description"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_OutputDestinationKey_Description/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSession_OutputDestinationKey_Description"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InputSources/title",
          "value": "kAudioSessionProperty_InputSources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_InputSources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_InputSources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OutputDestinations/title",
          "value": "kAudioSessionProperty_OutputDestinations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSessionProperty_OutputDestinations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSessionProperty_OutputDestinations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_OutputDestinationKey_ID/title",
          "value": "kAudioSession_OutputDestinationKey_ID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioSession_OutputDestinationKey_ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSession_OutputDestinationKey_ID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/usb-accessory-audio-destination-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/usb-accessory-audio-destination-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
