{
  "abstract": [
    {
      "text": "A value that indicates the return type is an array of object IDs that corresponds to the inserted rows.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType/objectIDs"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSBatchInsertRequestResultType@NSBatchInsertRequestResultTypeObjectIDs",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "objectIDs"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSBatchInsertRequestResultTypeObjectIDs"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSBatchInsertRequestResultType.objectIDs"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "objectIDs"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType": {
      "abstract": [
        {
          "text": "Result types for a batch-insertion request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBatchInsertRequestResultType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchInsertRequestResultType"
        }
      ],
      "role": "symbol",
      "title": "NSBatchInsertRequestResultType",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequestresulttype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType/count": {
      "abstract": [
        {
          "text": "A value that indicates that the return type is the number of inserted rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType/count",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchInsertRequestResultTypeCount"
        }
      ],
      "role": "symbol",
      "title": "NSBatchInsertRequestResultType.count",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequestresulttype/count"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType/objectIDs": {
      "abstract": [
        {
          "text": "A value that indicates the return type is an array of object IDs that corresponds to the inserted rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType/objectIDs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchInsertRequestResultTypeObjectIDs"
        }
      ],
      "role": "symbol",
      "title": "NSBatchInsertRequestResultType.objectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequestresulttype/objectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType/statusOnly": {
      "abstract": [
        {
          "text": "A value that indicates that the return type is a Boolean value representing whether the batch-insertion request succeeded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusOnly"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType/statusOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchInsertRequestResultTypeStatusOnly"
        }
      ],
      "role": "symbol",
      "title": "NSBatchInsertRequestResultType.statusOnly",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequestresulttype/statusonly"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Request-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType/statusOnly",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType/count"
      ],
      "title": "Request Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSBatchInsertRequestResultTypeObjectIDs"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertRequestResultTypeObjectIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Request-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType/statusOnly",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequestResultType/count"
              ],
              "title": "Request Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSBatchInsertRequestResultTypeObjectIDs"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequestResultType~1count/title",
          "value": "NSBatchInsertRequestResultTypeCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequestResultType~1count/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertRequestResultTypeCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequestResultType/title",
          "value": "NSBatchInsertRequestResultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequestResultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertRequestResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequestResultType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertRequestResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequestResultType~1statusOnly/title",
          "value": "NSBatchInsertRequestResultTypeStatusOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequestResultType~1statusOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertRequestResultTypeStatusOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequestResultType~1objectIDs/title",
          "value": "NSBatchInsertRequestResultTypeObjectIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequestResultType~1objectIDs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertRequestResultTypeObjectIDs"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsbatchinsertrequestresulttype/objectids"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsbatchinsertrequestresulttype/objectids"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
