{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-3k9gq"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-1csf0": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-1csf0",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/corevideo/anonymous-1csf0"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-jbs3": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-jbs3",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/corevideo/anonymous-jbs3"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Enumerations",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-enumerations"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_32BGRA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_32BGRA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_32BGRA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_32BGRA"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_Lossless_32BGRA",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_lossless_32bgra"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_lossless_420ypcbcr10packedbiplanarvideorange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_lossless_420ypcbcr8biplanarfullrange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_lossless_420ypcbcr8biplanarvideorange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_lossless_422ypcbcr10packedbiplanarvideorange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-jbs3",
        "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-1csf0"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_32BGRA",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange/title",
          "value": "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange/title",
          "value": "kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange/title",
          "value": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange/title",
          "value": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_32BGRA/title",
          "value": "kCVPixelFormatType_Lossless_32BGRA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_32BGRA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_Lossless_32BGRA"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/anonymous-3k9gq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
