{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-jbs3"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-1csf0": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-1csf0",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/corevideo/anonymous-1csf0"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-3k9gq": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-3k9gq",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/corevideo/anonymous-3k9gq"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Enumerations",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-enumerations"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_BGGR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVVersatileBayer_BayerPattern_BGGR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_BGGR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVVersatileBayer_BayerPattern_BGGR"
        }
      ],
      "role": "symbol",
      "title": "kCVVersatileBayer_BayerPattern_BGGR",
      "type": "topic",
      "url": "/documentation/corevideo/kcvversatilebayer_bayerpattern_bggr"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_GBRG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVVersatileBayer_BayerPattern_GBRG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_GBRG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVVersatileBayer_BayerPattern_GBRG"
        }
      ],
      "role": "symbol",
      "title": "kCVVersatileBayer_BayerPattern_GBRG",
      "type": "topic",
      "url": "/documentation/corevideo/kcvversatilebayer_bayerpattern_gbrg"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_GRBG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVVersatileBayer_BayerPattern_GRBG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_GRBG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVVersatileBayer_BayerPattern_GRBG"
        }
      ],
      "role": "symbol",
      "title": "kCVVersatileBayer_BayerPattern_GRBG",
      "type": "topic",
      "url": "/documentation/corevideo/kcvversatilebayer_bayerpattern_grbg"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_RGGB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVVersatileBayer_BayerPattern_RGGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_RGGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVVersatileBayer_BayerPattern_RGGB"
        }
      ],
      "role": "symbol",
      "title": "kCVVersatileBayer_BayerPattern_RGGB",
      "type": "topic",
      "url": "/documentation/corevideo/kcvversatilebayer_bayerpattern_rggb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-3k9gq",
        "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-1csf0"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_BGGR",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_GBRG",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_GRBG",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVVersatileBayer_BayerPattern_RGGB"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVVersatileBayer_BayerPattern_GBRG/title",
          "value": "kCVVersatileBayer_BayerPattern_GBRG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVVersatileBayer_BayerPattern_GBRG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVVersatileBayer_BayerPattern_GBRG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVVersatileBayer_BayerPattern_RGGB/title",
          "value": "kCVVersatileBayer_BayerPattern_RGGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVVersatileBayer_BayerPattern_RGGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVVersatileBayer_BayerPattern_RGGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVVersatileBayer_BayerPattern_BGGR/title",
          "value": "kCVVersatileBayer_BayerPattern_BGGR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVVersatileBayer_BayerPattern_BGGR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVVersatileBayer_BayerPattern_BGGR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVVersatileBayer_BayerPattern_GRBG/title",
          "value": "kCVVersatileBayer_BayerPattern_GRBG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVVersatileBayer_BayerPattern_GRBG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVVersatileBayer_BayerPattern_GRBG"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/anonymous-jbs3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
