{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Video Functions"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetIntegerCodePointForString(_:)": {
      "abstract": [
        {
          "text": "Returns the standard integer code point corresponding to the Core Video color primaries constant string that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVColorPrimariesGetIntegerCodePointForString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetIntegerCodePointForString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVColorPrimariesGetIntegerCodePointForString"
        }
      ],
      "role": "symbol",
      "title": "CVColorPrimariesGetIntegerCodePointForString(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvcolorprimariesgetintegercodepointforstring(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetStringForIntegerCodePoint(_:)": {
      "abstract": [
        {
          "text": "Returns the Core Video color primaries string corresponding to the standard integer code point that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVColorPrimariesGetStringForIntegerCodePoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetStringForIntegerCodePoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVColorPrimariesGetStringForIntegerCodePoint"
        }
      ],
      "role": "symbol",
      "title": "CVColorPrimariesGetStringForIntegerCodePoint(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvcolorprimariesgetstringforintegercodepoint(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVIsCompressedPixelFormatAvailable(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVIsCompressedPixelFormatAvailable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVIsCompressedPixelFormatAvailable(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVIsCompressedPixelFormatAvailable"
        }
      ],
      "role": "symbol",
      "title": "CVIsCompressedPixelFormatAvailable(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cviscompressedpixelformatavailable(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCopyCreationAttributes(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferCopyCreationAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCopyCreationAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferCopyCreationAttributes"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferCopyCreationAttributes(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffercopycreationattributes(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetIntegerCodePointForString(_:)": {
      "abstract": [
        {
          "text": "Returns the standard integer code point corresponding to the Core Video transfer function string that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTransferFunctionGetIntegerCodePointForString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetIntegerCodePointForString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTransferFunctionGetIntegerCodePointForString"
        }
      ],
      "role": "symbol",
      "title": "CVTransferFunctionGetIntegerCodePointForString(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvtransferfunctiongetintegercodepointforstring(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetStringForIntegerCodePoint(_:)": {
      "abstract": [
        {
          "text": "Returns the Core Video transfer function string corresponding to the standard integer code point that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTransferFunctionGetStringForIntegerCodePoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetStringForIntegerCodePoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTransferFunctionGetStringForIntegerCodePoint"
        }
      ],
      "role": "symbol",
      "title": "CVTransferFunctionGetStringForIntegerCodePoint(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvtransferfunctiongetstringforintegercodepoint(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetIntegerCodePointForString(_:)": {
      "abstract": [
        {
          "text": "Returns the standard integer code point corresponding to the Core Video YCbCr matrix string that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVYCbCrMatrixGetIntegerCodePointForString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetIntegerCodePointForString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVYCbCrMatrixGetIntegerCodePointForString"
        }
      ],
      "role": "symbol",
      "title": "CVYCbCrMatrixGetIntegerCodePointForString(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvycbcrmatrixgetintegercodepointforstring(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetStringForIntegerCodePoint(_:)": {
      "abstract": [
        {
          "text": "Returns the Core Video YCbCr matrix string corresponding to the standard integer code point that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVYCbCrMatrixGetStringForIntegerCodePoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetStringForIntegerCodePoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVYCbCrMatrixGetStringForIntegerCodePoint"
        }
      ],
      "role": "symbol",
      "title": "CVYCbCrMatrixGetStringForIntegerCodePoint(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvycbcrmatrixgetstringforintegercodepoint(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Constants",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Enumerations",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-enumerations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations",
        "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Converting-between-strings-and-integer-code-points",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetIntegerCodePointForString(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetStringForIntegerCodePoint(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetIntegerCodePointForString(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetStringForIntegerCodePoint(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetIntegerCodePointForString(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetStringForIntegerCodePoint(_:)"
      ],
      "title": "Converting between strings and integer code points"
    },
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVIsCompressedPixelFormatAvailable(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCopyCreationAttributes(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Converting-between-strings-and-integer-code-points",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetIntegerCodePointForString(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetStringForIntegerCodePoint(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetIntegerCodePointForString(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetStringForIntegerCodePoint(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetIntegerCodePointForString(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetStringForIntegerCodePoint(_:)"
              ],
              "title": "Converting between strings and integer code points"
            },
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVIsCompressedPixelFormatAvailable(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCopyCreationAttributes(_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations",
                "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVColorPrimariesGetIntegerCodePointForString(_:)/title",
          "value": "CVColorPrimariesGetIntegerCodePointForString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVColorPrimariesGetIntegerCodePointForString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVColorPrimariesGetIntegerCodePointForString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVIsCompressedPixelFormatAvailable(_:)/title",
          "value": "CVIsCompressedPixelFormatAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVIsCompressedPixelFormatAvailable(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVIsCompressedPixelFormatAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVYCbCrMatrixGetStringForIntegerCodePoint(_:)/title",
          "value": "CVYCbCrMatrixGetStringForIntegerCodePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVYCbCrMatrixGetStringForIntegerCodePoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVYCbCrMatrixGetStringForIntegerCodePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTransferFunctionGetIntegerCodePointForString(_:)/title",
          "value": "CVTransferFunctionGetIntegerCodePointForString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTransferFunctionGetIntegerCodePointForString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTransferFunctionGetIntegerCodePointForString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCopyCreationAttributes(_:)/title",
          "value": "CVPixelBufferCopyCreationAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCopyCreationAttributes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferCopyCreationAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTransferFunctionGetStringForIntegerCodePoint(_:)/title",
          "value": "CVTransferFunctionGetStringForIntegerCodePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTransferFunctionGetStringForIntegerCodePoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTransferFunctionGetStringForIntegerCodePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVColorPrimariesGetStringForIntegerCodePoint(_:)/title",
          "value": "CVColorPrimariesGetStringForIntegerCodePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVColorPrimariesGetStringForIntegerCodePoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVColorPrimariesGetStringForIntegerCodePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVYCbCrMatrixGetIntegerCodePointForString(_:)/title",
          "value": "CVYCbCrMatrixGetIntegerCodePointForString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVYCbCrMatrixGetIntegerCodePointForString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVYCbCrMatrixGetIntegerCodePointForString"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/core-video-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/core-video-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
