{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Video Constants"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_DECLARE_NULLABILITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_DECLARE_NULLABILITY"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_DECLARE_NULLABILITY",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_declare_nullability"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_FALSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_FALSE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_FALSE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_false"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_GL_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_GL_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_GL_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "COREVIDEO_GL_DEPRECATED",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_gl_deprecated"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_included_iosurface_header_file"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_COLORSPACE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_COLORSPACE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_COLORSPACE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_colorspace"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DIRECT3D"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DIRECT3D"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_DIRECT3D",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_direct3d"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DISPLAYLINK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DISPLAYLINK"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_DISPLAYLINK",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_displaylink"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_gles_tex_image_iosurface"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_IOSURFACE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_iosurface"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_iosurface_prefetch"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_METAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_METAL"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_METAL",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_metal"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGL"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_OPENGL",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_opengl"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGLES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGLES"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_OPENGLES",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_opengles"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_permanent_allocator"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PREFETCH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PREFETCH"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_PREFETCH",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_prefetch"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_TRUE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_TRUE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_TRUE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_true"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_use_derived_enums_for_constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_use_eaglcontext_class_in_api"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_IOSURFACEREF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_USE_IOSURFACEREF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_IOSURFACEREF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_USE_IOSURFACEREF"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_USE_IOSURFACEREF",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_use_iosurfaceref"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3D": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVDIRECT3D"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3D",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVDIRECT3D",
      "type": "topic",
      "url": "/documentation/corevideo/cvdirect3d"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3DDEVICE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVDIRECT3DDEVICE"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3DDEVICE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVDIRECT3DDEVICE",
      "type": "topic",
      "url": "/documentation/corevideo/cvdirect3ddevice"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3DSURFACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVDIRECT3DSURFACE"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3DSURFACE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVDIRECT3DSURFACE",
      "type": "topic",
      "url": "/documentation/corevideo/cvdirect3dsurface"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3DTEXTURE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVDIRECT3DTEXTURE"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3DTEXTURE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVDIRECT3DTEXTURE",
      "type": "topic",
      "url": "/documentation/corevideo/cvdirect3dtexture"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CV_BRIDGED_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CV_BRIDGED_TYPE"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CV_BRIDGED_TYPE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CV_BRIDGED_TYPE",
      "type": "topic",
      "url": "/documentation/corevideo/cv_bridged_type"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CV_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CV_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CV_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "CV_EXPORT",
      "type": "topic",
      "url": "/documentation/corevideo/cv_export"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CV_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CV_INLINE"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CV_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CV_INLINE",
      "type": "topic",
      "url": "/documentation/corevideo/cv_inline"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CV_INTERNAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CV_INTERNAL"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CV_INTERNAL",
      "kind": "symbol",
      "role": "symbol",
      "title": "CV_INTERNAL",
      "type": "topic",
      "url": "/documentation/corevideo/cv_internal"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CV_NONNULL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CV_NONNULL"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CV_NONNULL",
      "kind": "symbol",
      "role": "symbol",
      "title": "CV_NONNULL",
      "type": "topic",
      "url": "/documentation/corevideo/cv_nonnull"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CV_NULLABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CV_NULLABLE"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CV_NULLABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CV_NULLABLE",
      "type": "topic",
      "url": "/documentation/corevideo/cv_nullable"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CV_RELEASES_ARGUMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CV_RELEASES_ARGUMENT"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CV_RELEASES_ARGUMENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "CV_RELEASES_ARGUMENT",
      "type": "topic",
      "url": "/documentation/corevideo/cv_releases_argument"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CV_RETURNS_RETAINED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CV_RETURNS_RETAINED"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CV_RETURNS_RETAINED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CV_RETURNS_RETAINED",
      "type": "topic",
      "url": "/documentation/corevideo/cv_returns_retained"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CV_RETURNS_RETAINED_PARAMETER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CV_RETURNS_RETAINED_PARAMETER"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CV_RETURNS_RETAINED_PARAMETER",
      "kind": "symbol",
      "role": "symbol",
      "title": "CV_RETURNS_RETAINED_PARAMETER",
      "type": "topic",
      "url": "/documentation/corevideo/cv_returns_retained_parameter"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Enumerations",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-enumerations"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Functions",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-functions"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelModeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferAlphaChannelModeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelModeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferAlphaChannelModeKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferAlphaChannelModeKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferalphachannelmodekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelMode_PremultipliedAlpha": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferAlphaChannelMode_PremultipliedAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelMode_PremultipliedAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferAlphaChannelMode_PremultipliedAlpha"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferAlphaChannelMode_PremultipliedAlpha",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferalphachannelmode_premultipliedalpha"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelMode_StraightAlpha": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferAlphaChannelMode_StraightAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelMode_StraightAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferAlphaChannelMode_StraightAlpha"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferAlphaChannelMode_StraightAlpha",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferalphachannelmode_straightalpha"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAmbientViewingEnvironmentKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferAmbientViewingEnvironmentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAmbientViewingEnvironmentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferAmbientViewingEnvironmentKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferAmbientViewingEnvironmentKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferambientviewingenvironmentkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferLogTransferFunctionKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferLogTransferFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferLogTransferFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferLogTransferFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferLogTransferFunctionKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferlogtransferfunctionkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferLogTransferFunction_AppleLog": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferLogTransferFunction_AppleLog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferLogTransferFunction_AppleLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferLogTransferFunction_AppleLog"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferLogTransferFunction_AppleLog",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferlogtransferfunction_applelog"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferRegionOfInterestKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferRegionOfInterestKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferRegionOfInterestKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferRegionOfInterestKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferRegionOfInterestKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferregionofinterestkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_Linear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_Linear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_Linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_Linear"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_Linear",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_linear"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVMetalTextureStorageMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVMetalTextureStorageMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVMetalTextureStorageMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVMetalTextureStorageMode"
        }
      ],
      "role": "symbol",
      "title": "kCVMetalTextureStorageMode",
      "type": "topic",
      "url": "/documentation/corevideo/kcvmetaltexturestoragemode"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_BlackLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_BlackLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_BlackLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_BlackLevel"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferProResRAWKey_BlackLevel",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferproresrawkey_blacklevel"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_ColorMatrix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_ColorMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_ColorMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_ColorMatrix"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferProResRAWKey_ColorMatrix",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferproresrawkey_colormatrix"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_GainFactor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_GainFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_GainFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_GainFactor"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferProResRAWKey_GainFactor",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferproresrawkey_gainfactor"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_MetadataExtension": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_MetadataExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_MetadataExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_MetadataExtension"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferProResRAWKey_MetadataExtension",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferproresrawkey_metadataextension"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_RecommendedCrop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_RecommendedCrop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_RecommendedCrop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_RecommendedCrop"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferProResRAWKey_RecommendedCrop",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferproresrawkey_recommendedcrop"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_SenselSitingOffsets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_SenselSitingOffsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_SenselSitingOffsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_SenselSitingOffsets"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferProResRAWKey_SenselSitingOffsets",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferproresrawkey_senselsitingoffsets"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferproresrawkey_whitebalancebluefactor"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceCCT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_WhiteBalanceCCT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceCCT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_WhiteBalanceCCT"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferProResRAWKey_WhiteBalanceCCT",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferproresrawkey_whitebalancecct"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferproresrawkey_whitebalanceredfactor"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_WhiteLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferProResRAWKey_WhiteLevel"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferProResRAWKey_WhiteLevel",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferproresrawkey_whitelevel"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferVersatileBayerKey_BayerPattern": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferVersatileBayerKey_BayerPattern"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferVersatileBayerKey_BayerPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferVersatileBayerKey_BayerPattern"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferVersatileBayerKey_BayerPattern",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferversatilebayerkey_bayerpattern"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsGrayscale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsGrayscale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsGrayscale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsGrayscale"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatContainsGrayscale",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcontainsgrayscale"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsSenselArray": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsSenselArray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsSenselArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsSenselArray"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatContainsSenselArray",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcontainssenselarray"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations",
        "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_IOSURFACEREF",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelModeKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelMode_PremultipliedAlpha",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelMode_StraightAlpha",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAmbientViewingEnvironmentKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferLogTransferFunctionKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferLogTransferFunction_AppleLog",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferRegionOfInterestKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_Linear",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVMetalTextureStorageMode",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_BlackLevel",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_ColorMatrix",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_GainFactor",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_MetadataExtension",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_RecommendedCrop",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_SenselSitingOffsets",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceCCT",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteLevel",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferVersatileBayerKey_BayerPattern",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsGrayscale",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsSenselArray"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_IOSURFACEREF",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelModeKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelMode_PremultipliedAlpha",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelMode_StraightAlpha",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAmbientViewingEnvironmentKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferLogTransferFunctionKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferLogTransferFunction_AppleLog",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferRegionOfInterestKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_Linear",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVMetalTextureStorageMode",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_BlackLevel",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_ColorMatrix",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_GainFactor",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_MetadataExtension",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_RecommendedCrop",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_SenselSitingOffsets",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceCCT",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferProResRAWKey_WhiteLevel",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferVersatileBayerKey_BayerPattern",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsGrayscale",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsSenselArray"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_GL_DEPRECATED",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3D",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3DDEVICE",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3DSURFACE",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVDIRECT3DTEXTURE",
                "doc://com.apple.corevideo/documentation/CoreVideo/CV_BRIDGED_TYPE",
                "doc://com.apple.corevideo/documentation/CoreVideo/CV_EXPORT",
                "doc://com.apple.corevideo/documentation/CoreVideo/CV_INLINE",
                "doc://com.apple.corevideo/documentation/CoreVideo/CV_INTERNAL",
                "doc://com.apple.corevideo/documentation/CoreVideo/CV_NONNULL",
                "doc://com.apple.corevideo/documentation/CoreVideo/CV_NULLABLE",
                "doc://com.apple.corevideo/documentation/CoreVideo/CV_RELEASES_ARGUMENT",
                "doc://com.apple.corevideo/documentation/CoreVideo/CV_RETURNS_RETAINED",
                "doc://com.apple.corevideo/documentation/CoreVideo/CV_RETURNS_RETAINED_PARAMETER"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations",
                "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE/title",
          "value": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DIRECT3D/title",
          "value": "COREVIDEO_SUPPORTS_DIRECT3D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DIRECT3D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_DIRECT3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAlphaChannelMode_PremultipliedAlpha/title",
          "value": "kCVImageBufferAlphaChannelMode_PremultipliedAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAlphaChannelMode_PremultipliedAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferAlphaChannelMode_PremultipliedAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_ColorMatrix/title",
          "value": "kCVPixelBufferProResRAWKey_ColorMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_ColorMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferProResRAWKey_ColorMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_Linear/title",
          "value": "kCVImageBufferTransferFunction_Linear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_Linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_Linear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAlphaChannelMode_StraightAlpha/title",
          "value": "kCVImageBufferAlphaChannelMode_StraightAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAlphaChannelMode_StraightAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferAlphaChannelMode_StraightAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_USE_IOSURFACEREF/title",
          "value": "COREVIDEO_USE_IOSURFACEREF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_USE_IOSURFACEREF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_USE_IOSURFACEREF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_GainFactor/title",
          "value": "kCVPixelBufferProResRAWKey_GainFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_GainFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferProResRAWKey_GainFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_DECLARE_NULLABILITY/title",
          "value": "COREVIDEO_DECLARE_NULLABILITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_DECLARE_NULLABILITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_DECLARE_NULLABILITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsSenselArray/title",
          "value": "kCVPixelFormatContainsSenselArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsSenselArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatContainsSenselArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferRegionOfInterestKey/title",
          "value": "kCVImageBufferRegionOfInterestKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferRegionOfInterestKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferRegionOfInterestKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH/title",
          "value": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferLogTransferFunctionKey/title",
          "value": "kCVImageBufferLogTransferFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferLogTransferFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferLogTransferFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS/title",
          "value": "COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsGrayscale/title",
          "value": "kCVPixelFormatContainsGrayscale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsGrayscale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatContainsGrayscale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAlphaChannelModeKey/title",
          "value": "kCVImageBufferAlphaChannelModeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAlphaChannelModeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferAlphaChannelModeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVMetalTextureStorageMode/title",
          "value": "kCVMetalTextureStorageMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVMetalTextureStorageMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVMetalTextureStorageMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_MetadataExtension/title",
          "value": "kCVPixelBufferProResRAWKey_MetadataExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_MetadataExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferProResRAWKey_MetadataExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAmbientViewingEnvironmentKey/title",
          "value": "kCVImageBufferAmbientViewingEnvironmentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAmbientViewingEnvironmentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferAmbientViewingEnvironmentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PREFETCH/title",
          "value": "COREVIDEO_SUPPORTS_PREFETCH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PREFETCH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_PREFETCH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_FALSE/title",
          "value": "COREVIDEO_FALSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_FALSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_FALSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_TRUE/title",
          "value": "COREVIDEO_TRUE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_TRUE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_TRUE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_RecommendedCrop/title",
          "value": "kCVPixelBufferProResRAWKey_RecommendedCrop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_RecommendedCrop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferProResRAWKey_RecommendedCrop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE/title",
          "value": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR/title",
          "value": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE/title",
          "value": "COREVIDEO_SUPPORTS_IOSURFACE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_IOSURFACE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor/title",
          "value": "kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferProResRAWKey_WhiteBalanceBlueFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_SenselSitingOffsets/title",
          "value": "kCVPixelBufferProResRAWKey_SenselSitingOffsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_SenselSitingOffsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferProResRAWKey_SenselSitingOffsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_WhiteBalanceCCT/title",
          "value": "kCVPixelBufferProResRAWKey_WhiteBalanceCCT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_WhiteBalanceCCT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferProResRAWKey_WhiteBalanceCCT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_WhiteLevel/title",
          "value": "kCVPixelBufferProResRAWKey_WhiteLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_WhiteLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferProResRAWKey_WhiteLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DISPLAYLINK/title",
          "value": "COREVIDEO_SUPPORTS_DISPLAYLINK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DISPLAYLINK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_DISPLAYLINK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API/title",
          "value": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_BlackLevel/title",
          "value": "kCVPixelBufferProResRAWKey_BlackLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_BlackLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferProResRAWKey_BlackLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferVersatileBayerKey_BayerPattern/title",
          "value": "kCVPixelBufferVersatileBayerKey_BayerPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferVersatileBayerKey_BayerPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferVersatileBayerKey_BayerPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_COLORSPACE/title",
          "value": "COREVIDEO_SUPPORTS_COLORSPACE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_COLORSPACE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_COLORSPACE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor/title",
          "value": "kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferProResRAWKey_WhiteBalanceRedFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_METAL/title",
          "value": "COREVIDEO_SUPPORTS_METAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_METAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_METAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGLES/title",
          "value": "COREVIDEO_SUPPORTS_OPENGLES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGLES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_OPENGLES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferLogTransferFunction_AppleLog/title",
          "value": "kCVImageBufferLogTransferFunction_AppleLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferLogTransferFunction_AppleLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferLogTransferFunction_AppleLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGL/title",
          "value": "COREVIDEO_SUPPORTS_OPENGL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_OPENGL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/core-video-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/core-video-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
