{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_DECLARE_NULLABILITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_DECLARE_NULLABILITY"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_DECLARE_NULLABILITY",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_declare_nullability"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_FALSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_FALSE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_FALSE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_false"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_included_iosurface_header_file"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_COLORSPACE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_COLORSPACE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_COLORSPACE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_colorspace"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DIRECT3D"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DIRECT3D"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_DIRECT3D",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_direct3d"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DISPLAYLINK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DISPLAYLINK"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_DISPLAYLINK",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_displaylink"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_gles_tex_image_iosurface"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_IOSURFACE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_iosurface"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_iosurface_prefetch"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_METAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_METAL"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_METAL",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_metal"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGL"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_OPENGL",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_opengl"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGLES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGLES"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_OPENGLES",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_opengles"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_permanent_allocator"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PREFETCH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PREFETCH"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_PREFETCH",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_prefetch"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_TRUE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_TRUE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_TRUE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_true"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_use_eaglcontext_class_in_api"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR/title",
          "value": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PREFETCH/title",
          "value": "COREVIDEO_SUPPORTS_PREFETCH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PREFETCH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_PREFETCH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DIRECT3D/title",
          "value": "COREVIDEO_SUPPORTS_DIRECT3D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DIRECT3D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_DIRECT3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DISPLAYLINK/title",
          "value": "COREVIDEO_SUPPORTS_DISPLAYLINK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DISPLAYLINK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_DISPLAYLINK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_COLORSPACE/title",
          "value": "COREVIDEO_SUPPORTS_COLORSPACE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_COLORSPACE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_COLORSPACE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE/title",
          "value": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_DECLARE_NULLABILITY/title",
          "value": "COREVIDEO_DECLARE_NULLABILITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_DECLARE_NULLABILITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_DECLARE_NULLABILITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_TRUE/title",
          "value": "COREVIDEO_TRUE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_TRUE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_TRUE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_FALSE/title",
          "value": "COREVIDEO_FALSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_FALSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_FALSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGLES/title",
          "value": "COREVIDEO_SUPPORTS_OPENGLES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGLES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_OPENGLES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE/title",
          "value": "COREVIDEO_SUPPORTS_IOSURFACE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_IOSURFACE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGL/title",
          "value": "COREVIDEO_SUPPORTS_OPENGL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_OPENGL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH/title",
          "value": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE/title",
          "value": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_METAL/title",
          "value": "COREVIDEO_SUPPORTS_METAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_METAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_METAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API/title",
          "value": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_USE_EAGLCONTEXT_CLASS_IN_API"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/corevideo_use_eaglcontext_class_in_api"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/corevideo_use_eaglcontext_class_in_api"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
