{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "title": "Core Video Enumerations"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-1csf0": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-1csf0",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/corevideo/anonymous-1csf0"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-3k9gq": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-3k9gq",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/corevideo/anonymous-3k9gq"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-jbs3": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-jbs3",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/corevideo/anonymous-jbs3"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Constants",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Functions",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-functions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-jbs3",
        "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-3k9gq",
        "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-1csf0"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-jbs3",
                "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-3k9gq",
                "doc://com.apple.corevideo/documentation/CoreVideo/anonymous-1csf0"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/core-video-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/core-video-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
