{
  "abstract": [
    {
      "text": "The attachment types for a Core Video buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attachment-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVBuffer Attachment Keys"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attribute-keys": {
      "abstract": [
        {
          "text": "The attributes associated with Core Video buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attribute-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVBuffer Attribute Keys",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer-attribute-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm": {
      "abstract": [
        {
          "text": "An abstract base class that defines how to interact with data buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer-nfm"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferMovieTimeKey": {
      "abstract": [
        {
          "text": "The movie time associated with the buffer. Generally only available for frames emitted by QuickTime (type ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": " containing the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferTimeValueKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferTimeScaleKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " keys).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVBufferMovieTimeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferMovieTimeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVBufferMovieTimeKey"
        }
      ],
      "role": "symbol",
      "title": "kCVBufferMovieTimeKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvbuffermovietimekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferTimeScaleKey": {
      "abstract": [
        {
          "text": "The time scale associated with the movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVBufferTimeScaleKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferTimeScaleKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVBufferTimeScaleKey"
        }
      ],
      "role": "symbol",
      "title": "kCVBufferTimeScaleKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvbuffertimescalekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferTimeValueKey": {
      "abstract": [
        {
          "text": "The time value associated with the movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVBufferTimeValueKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferTimeValueKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVBufferTimeValueKey"
        }
      ],
      "role": "symbol",
      "title": "kCVBufferTimeValueKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvbuffertimevaluekey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attribute-keys"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferMovieTimeKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferTimeValueKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferTimeScaleKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferMovieTimeKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferTimeValueKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferTimeScaleKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attribute-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVBufferMovieTimeKey/title",
          "value": "kCVBufferMovieTimeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVBufferMovieTimeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVBufferMovieTimeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVBufferTimeValueKey/title",
          "value": "kCVBufferTimeValueKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVBufferTimeValueKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVBufferTimeValueKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVBufferTimeScaleKey/title",
          "value": "kCVBufferTimeScaleKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVBufferTimeScaleKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVBufferTimeScaleKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvbuffer-attachment-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvbuffer-attachment-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
