{
  "abstract": [
    {
      "text": "Releases a Core Video buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRelease"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CVBufferRelease",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CVBufferRelease"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CVBufferRelease"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CVBufferRelease"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVBufferRelease"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVBufferRef",
              "text": "CVBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "buffer"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Core Video buffer that you want to release.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "buffer"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", this function decrements the retain count of a Core Video buffer. However, unlike ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", this function is ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " safe. If the retain count becomes zero, the system deallocates the object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer": {
      "abstract": [
        {
          "text": "A reference to a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBuffer"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRelease": {
      "abstract": [
        {
          "text": "Releases a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVBufferRelease"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVBufferRelease",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferrelease"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRetain": {
      "abstract": [
        {
          "text": "Retains a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVBufferRetain"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRetain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVBufferRetain",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferretain"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retaining-and-releasing-buffers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRetain"
      ],
      "title": "Retaining and releasing buffers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/title",
          "value": "CVBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvbufferrelease"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
