{
  "abstract": [
    {
      "text": "Retrieves all attachments of a Core Video buffer.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CVBufferGetAttachments",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CVBufferGetAttachments"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CVBufferRef",
        "text": "CVBuffer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CVAttachmentMode",
        "text": "CVAttachmentMode"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFDictionaryRef",
        "text": "CFDictionary"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CVBufferGetAttachments"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "4.0",
        "name": "iOS",
        "renamed": "CVBufferCopyAttachments(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "4.0",
        "name": "iPadOS",
        "renamed": "CVBufferCopyAttachments(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "renamed": "CVBufferCopyAttachments(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.4",
        "name": "macOS",
        "renamed": "CVBufferCopyAttachments(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "9.0",
        "name": "tvOS",
        "renamed": "CVBufferCopyAttachments(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "CVBufferCopyAttachments(_:_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "4.0",
        "name": "watchOS",
        "renamed": "CVBufferCopyAttachments(_:_:)",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CVBufferGetAttachments(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVBufferGetAttachments"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "buffer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVBufferRef",
              "text": "CVBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attachmentMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CVAttachmentMode",
              "text": "CVAttachmentMode"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The buffer whose attachments you want to retrieve.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "buffer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The mode of the attachments you want to retrieve. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for possible values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "attachmentMode"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Core Foundation dictionary with all attachments identified by keys, or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nil-2gl",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the attachment mode is invalid. The dictionary is empty if the buffer has no attachments.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode": {
      "abstract": [
        {
          "text": "The propagation modes of a Core Video buffer attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVAttachmentMode"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVAttachmentMode"
        }
      ],
      "role": "symbol",
      "title": "CVAttachmentMode",
      "type": "topic",
      "url": "/documentation/corevideo/cvattachmentmode"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer": {
      "abstract": [
        {
          "text": "A reference to a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBuffer"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a copy of an attachment from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferCopyAttachment(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffercopyattachment(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)": {
      "abstract": [
        {
          "text": "Returns a copy of all attachments from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferCopyAttachments(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffercopyattachments(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a specific attachment of a Core Video buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferGetAttachment(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffergetattachment(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves all attachments of a Core Video buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferGetAttachments(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffergetattachments(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a Core Video buffer contains a specified attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferHasAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferHasAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferHasAttachment(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferhasattachment(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)": {
      "abstract": [
        {
          "text": "Copies all attachments that Core Video can propagate from one buffer to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferPropagateAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferPropagateAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferPropagateAttachments(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferpropagateattachments(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)": {
      "abstract": [
        {
          "text": "Removes all attachments from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAllAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAllAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferRemoveAllAttachments(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferremoveallattachments(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)": {
      "abstract": [
        {
          "text": "Removes the attachment you specify from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferRemoveAttachment(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferremoveattachment(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets or adds an attachment to a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferSetAttachment(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffersetattachment(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a dictionary of attachments on a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferSetAttachments(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffersetattachments(_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/objectivec/nil-2gl": {
      "abstract": [
        {
          "text": "Defines the `id` of a null instance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nil-2gl",
      "kind": "symbol",
      "role": "symbol",
      "title": "nil",
      "type": "topic",
      "url": "/documentation/objectivec/nil-2gl"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-attachments",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)"
      ],
      "title": "Working with attachments"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CVBufferGetAttachments"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferGetAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-attachments",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)"
              ],
              "title": "Working with attachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFDictionaryRef",
                    "text": "CFDictionaryRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CVBufferGetAttachments"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CVBufferRef",
                    "text": "CVBufferRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "buffer"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CVAttachmentMode",
                    "text": "CVAttachmentMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "attachmentMode"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The buffer whose attachments you want to retrieve.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "buffer"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The mode of the attachments you want to retrieve. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for possible values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "attachmentMode"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A Core Foundation dictionary with all attachments identified by keys, or ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/objectivec/nil-2gl",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the attachment mode is invalid. The dictionary is empty if the buffer has no attachments.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachments(_:_:)/title",
          "value": "CVBufferGetAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachments(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferGetAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachments(_:_:)/title",
          "value": "CVBufferCopyAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachments(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferCopyAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVAttachmentMode/title",
          "value": "CVAttachmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVAttachmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVAttachmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVAttachmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVAttachmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachments(_:_:_:)/title",
          "value": "CVBufferSetAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachments(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferSetAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachment(_:_:_:_:)/title",
          "value": "CVBufferSetAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachment(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferSetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAttachment(_:_:)/title",
          "value": "CVBufferRemoveAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAttachment(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRemoveAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferHasAttachment(_:_:)/title",
          "value": "CVBufferHasAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferHasAttachment(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferHasAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachment(_:_:_:)/title",
          "value": "CVBufferGetAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachment(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferGetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAllAttachments(_:)/title",
          "value": "CVBufferRemoveAllAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAllAttachments(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRemoveAllAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferPropagateAttachments(_:_:)/title",
          "value": "CVBufferPropagateAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferPropagateAttachments(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferPropagateAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/title",
          "value": "CVBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachment(_:_:_:)/title",
          "value": "CVBufferCopyAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachment(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferCopyAttachment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvbuffergetattachments(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvbuffergetattachments(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
