{
  "abstract": [
    {
      "text": "Sets or adds an attachment to a Core Video buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CVBufferSetAttachment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CVBufferSetAttachment"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CVBufferRef",
        "text": "CVBuffer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFTypeRef",
        "text": "CFTypeRef"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CVAttachmentMode",
        "text": "CVAttachmentMode"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CVBufferSetAttachment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CVBufferSetAttachment(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVBufferSetAttachment"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "buffer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVBufferRef",
              "text": "CVBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attachmentMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CVAttachmentMode",
              "text": "CVAttachmentMode"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The buffer on which to add or set an attachment.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "buffer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A string that identifies the attachment, which can be of any ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/cftype",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attachment-keys",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for predefined values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "key"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The attachment in the form of a Core Foundation object. If this parameter is ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", the function returns an error.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The attachment mode for this attachment. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for possible values. Any given attachment key may exist in only one mode at a time.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "attachmentMode"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can attach any Core Foundation object to a Core Video buffer to store additional information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If it doesn’t exist for the buffer object, the system adds a new attachment. If the key does exist, the system replaces the existing attachment. In both cases, the system increases the retain count of the attachment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can also set attachments when creating a buffer by specifying them in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferPropagatedAttachmentsKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferNonPropagatedAttachmentsKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " attributes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To retrieve attachments, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode": {
      "abstract": [
        {
          "text": "The propagation modes of a Core Video buffer attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVAttachmentMode"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVAttachmentMode"
        }
      ],
      "role": "symbol",
      "title": "CVAttachmentMode",
      "type": "topic",
      "url": "/documentation/corevideo/cvattachmentmode"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer": {
      "abstract": [
        {
          "text": "A reference to a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBuffer"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a copy of an attachment from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferCopyAttachment(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffercopyattachment(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)": {
      "abstract": [
        {
          "text": "Returns a copy of all attachments from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferCopyAttachments(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffercopyattachments(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a specific attachment of a Core Video buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferGetAttachment(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffergetattachment(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves all attachments of a Core Video buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferGetAttachments(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffergetattachments(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a Core Video buffer contains a specified attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferHasAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferHasAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferHasAttachment(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferhasattachment(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)": {
      "abstract": [
        {
          "text": "Copies all attachments that Core Video can propagate from one buffer to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferPropagateAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferPropagateAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferPropagateAttachments(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferpropagateattachments(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)": {
      "abstract": [
        {
          "text": "Removes all attachments from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAllAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAllAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferRemoveAllAttachments(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferremoveallattachments(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)": {
      "abstract": [
        {
          "text": "Removes the attachment you specify from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferRemoveAttachment(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferremoveattachment(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets or adds an attachment to a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferSetAttachment(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffersetattachment(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a dictionary of attachments on a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferSetAttachments(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffersetattachments(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attachment-keys": {
      "abstract": [
        {
          "text": "The attachment types for a Core Video buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attachment-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVBuffer Attachment Keys",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer-attachment-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys": {
      "abstract": [
        {
          "text": "Keys that describe the attachment types associated with image buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Attachment Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-attachment-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferNonPropagatedAttachmentsKey": {
      "abstract": [
        {
          "text": "Attachments that should not be copied when using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function (type ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": ", containing a list of attachments as key-value pairs).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVBufferNonPropagatedAttachmentsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferNonPropagatedAttachmentsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVBufferNonPropagatedAttachmentsKey"
        }
      ],
      "role": "symbol",
      "title": "kCVBufferNonPropagatedAttachmentsKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvbuffernonpropagatedattachmentskey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferPropagatedAttachmentsKey": {
      "abstract": [
        {
          "text": "Attachments that should be copied when using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function (type ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": ", containing a list of attachments as key-value pairs).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVBufferPropagatedAttachmentsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVBufferPropagatedAttachmentsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVBufferPropagatedAttachmentsKey"
        }
      ],
      "role": "symbol",
      "title": "kCVBufferPropagatedAttachmentsKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvbufferpropagatedattachmentskey"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cftype": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cftype",
      "kind": "article",
      "role": "article",
      "title": "CFType",
      "type": "topic",
      "url": "/documentation/corefoundation/cftype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFTypeRef": {
      "abstract": [
        {
          "text": "An untyped \"generic\" reference to any Core Foundation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTypeRef",
      "type": "topic",
      "url": "/documentation/corefoundation/cftyperef"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-attachments",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)"
      ],
      "title": "Working with attachments"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CVBufferSetAttachment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferSetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-attachments",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)"
              ],
              "title": "Working with attachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CVBufferSetAttachment"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CVBufferRef",
                    "text": "CVBufferRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "buffer"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "key"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFTypeRef",
                    "text": "CFTypeRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CVAttachmentMode",
                    "text": "CVAttachmentMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "attachmentMode"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The buffer on which to add or set an attachment.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "buffer"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that identifies the attachment, which can be of any ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/corefoundation/cftype",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attachment-keys",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for predefined values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "key"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The attachment in the form of a Core Foundation object. If this parameter is ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", the function returns an error.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "value"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The attachment mode for this attachment. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for possible values. Any given attachment key may exist in only one mode at a time.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "attachmentMode"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAttachment(_:_:)/title",
          "value": "CVBufferRemoveAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAttachment(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRemoveAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachment(_:_:_:_:)/title",
          "value": "CVBufferSetAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachment(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferSetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVBufferPropagatedAttachmentsKey/title",
          "value": "kCVBufferPropagatedAttachmentsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVBufferPropagatedAttachmentsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVBufferPropagatedAttachmentsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVAttachmentMode/title",
          "value": "CVAttachmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVAttachmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVAttachmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVAttachmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVAttachmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferHasAttachment(_:_:)/title",
          "value": "CVBufferHasAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferHasAttachment(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferHasAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachments(_:_:_:)/title",
          "value": "CVBufferSetAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachments(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferSetAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachment(_:_:_:)/title",
          "value": "CVBufferCopyAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachment(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferCopyAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachments(_:_:)/title",
          "value": "CVBufferCopyAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachments(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferCopyAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachments(_:_:)/title",
          "value": "CVBufferGetAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachments(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferGetAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferPropagateAttachments(_:_:)/title",
          "value": "CVBufferPropagateAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferPropagateAttachments(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferPropagateAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/title",
          "value": "CVBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachment(_:_:_:)/title",
          "value": "CVBufferGetAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachment(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferGetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVBufferNonPropagatedAttachmentsKey/title",
          "value": "kCVBufferNonPropagatedAttachmentsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVBufferNonPropagatedAttachmentsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVBufferNonPropagatedAttachmentsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAllAttachments(_:)/title",
          "value": "CVBufferRemoveAllAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAllAttachments(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRemoveAllAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvbuffersetattachment(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvbuffersetattachment(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
