{
  "abstract": [
    {
      "text": "An abstract base class that defines how to interact with data buffers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVBuffer"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " serves as an abstract base class that defines how to interact with buffers of data. A buffer object can hold video, audio, or possibly other types of data. All the other buffer types within the Core Video framework, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", derive from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " programming interface on any Core Video buffer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode": {
      "abstract": [
        {
          "text": "The propagation modes of a Core Video buffer attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVAttachmentMode"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVAttachmentMode"
        }
      ],
      "role": "symbol",
      "title": "CVAttachmentMode",
      "type": "topic",
      "url": "/documentation/corevideo/cvattachmentmode"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer": {
      "abstract": [
        {
          "text": "A reference to a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBuffer"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a copy of an attachment from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferCopyAttachment(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffercopyattachment(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)": {
      "abstract": [
        {
          "text": "Returns a copy of all attachments from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferCopyAttachments(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffercopyattachments(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a specific attachment of a Core Video buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferGetAttachment(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffergetattachment(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves all attachments of a Core Video buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferGetAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferGetAttachments(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffergetattachments(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a Core Video buffer contains a specified attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferHasAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferHasAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferHasAttachment(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferhasattachment(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)": {
      "abstract": [
        {
          "text": "Copies all attachments that Core Video can propagate from one buffer to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferPropagateAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferPropagateAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferPropagateAttachments(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferpropagateattachments(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRelease": {
      "abstract": [
        {
          "text": "Releases a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVBufferRelease"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVBufferRelease",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferrelease"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)": {
      "abstract": [
        {
          "text": "Removes all attachments from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAllAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAllAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferRemoveAllAttachments(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferremoveallattachments(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)": {
      "abstract": [
        {
          "text": "Removes the attachment you specify from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferRemoveAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferRemoveAttachment(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferremoveattachment(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRetain": {
      "abstract": [
        {
          "text": "Retains a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVBufferRetain"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRetain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVBufferRetain",
      "type": "topic",
      "url": "/documentation/corevideo/cvbufferretain"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets or adds an attachment to a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferSetAttachment(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffersetattachment(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a dictionary of attachments on a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVBufferSetAttachments(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffersetattachments(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o": {
      "abstract": [
        {
          "text": "A utility object for managing a recyclable set of pixel buffer objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpool-77o"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attachment-keys": {
      "abstract": [
        {
          "text": "The attachment types for a Core Video buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attachment-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVBuffer Attachment Keys",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer-attachment-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attribute-keys": {
      "abstract": [
        {
          "text": "The attributes associated with Core Video buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attribute-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVBuffer Attribute Keys",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer-attribute-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40": {
      "abstract": [
        {
          "text": "An interface for managing different types of image data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer-q40"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e": {
      "abstract": [
        {
          "text": "An image buffer that holds pixels in main memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffer-q2e"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription": {
      "abstract": [
        {
          "text": "An API that provides functions and types for defining custom pixel formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelFormatDescription",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelformatdescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536",
      "title": "Core Video Programming Guide",
      "titleInlineContent": [
        {
          "text": "Core Video Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Data-Processing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
      ],
      "title": "Data Processing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Working-with-attachments",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)"
      ],
      "title": "Working with attachments"
    },
    {
      "anchor": "Data-types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode"
      ],
      "title": "Data types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attribute-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attachment-keys"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Working-with-attachments",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferHasAttachment(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachments(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachments(_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferPropagateAttachments(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAttachment(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRemoveAllAttachments(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachment(_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferGetAttachments(_:_:)"
              ],
              "title": "Working with attachments"
            },
            {
              "anchor": "Retaining-and-releasing-buffers",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRetain",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferRelease"
              ],
              "title": "Retaining and releasing buffers"
            },
            {
              "anchor": "Data-types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVAttachmentMode"
              ],
              "title": "Data types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attribute-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-attachment-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Data-Processing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
              ],
              "title": "Data Processing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachment(_:_:_:)/title",
          "value": "CVBufferGetAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachment(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferGetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachments(_:_:)/title",
          "value": "CVBufferGetAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferGetAttachments(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferGetAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVAttachmentMode/title",
          "value": "CVAttachmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVAttachmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVAttachmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVAttachmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVAttachmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachments(_:_:_:)/title",
          "value": "CVBufferSetAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachments(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferSetAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferPropagateAttachments(_:_:)/title",
          "value": "CVBufferPropagateAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferPropagateAttachments(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferPropagateAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachment(_:_:_:_:)/title",
          "value": "CVBufferSetAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachment(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferSetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachment(_:_:_:)/title",
          "value": "CVBufferCopyAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachment(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferCopyAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferHasAttachment(_:_:)/title",
          "value": "CVBufferHasAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferHasAttachment(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferHasAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachments(_:_:)/title",
          "value": "CVBufferCopyAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachments(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferCopyAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/title",
          "value": "CVBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAttachment(_:_:)/title",
          "value": "CVBufferRemoveAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAttachment(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRemoveAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAllAttachments(_:)/title",
          "value": "CVBufferRemoveAllAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferRemoveAllAttachments(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRemoveAllAttachments"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvbuffer-nfm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvbuffer-nfm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
