{
  "abstract": [
    {
      "text": "Translates the time in the display link’s time base from one representation to another.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "use NSView.displayLink(target:selector:), NSWindow.displayLink(target:selector:), or NSScreen.displayLink(target:selector:) ",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkTranslateTime(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CVDisplayLinkTranslateTime",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CVDisplayLinkTranslateTime"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CVDisplayLinkRef",
        "text": "CVDisplayLink"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CVTimeStamp",
        "text": "CVTimeStamp"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CVTimeStamp",
        "text": "CVTimeStamp"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CVReturn",
        "text": "CVReturn"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CVDisplayLinkTranslateTime"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "message": "use NSView.displayLink(target:selector:), NSWindow.displayLink(target:selector:), or NSScreen.displayLink(target:selector:) ",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.4",
        "message": "use NSView.displayLink(target:selector:), NSWindow.displayLink(target:selector:), or NSScreen.displayLink(target:selector:) ",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CVDisplayLinkTranslateTime(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVDisplayLinkTranslateTime"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "displayLink"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLink",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVDisplayLinkRef",
              "text": "CVDisplayLink"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inTime"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CVTimeStamp",
              "text": "CVTimeStamp"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "outTime"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CVTimeStamp",
              "text": "CVTimeStamp"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVReturn",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVReturn",
              "text": "CVReturn"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The display link whose time base should be used to do the translation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "displayLink"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a ",
                  "type": "text"
                },
                {
                  "code": "CVTimeStamp",
                  "type": "codeVoice"
                },
                {
                  "text": " structure containing the source time to translate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inTime"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a ",
                  "type": "text"
                },
                {
                  "code": "CVTimeStamp",
                  "type": "codeVoice"
                },
                {
                  "text": " structure into which the target time is written. Before calling, you must set the version field (currently ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ") to indicate which version of the structure you want. You should also set the ",
                  "type": "text"
                },
                {
                  "code": "flags",
                  "type": "codeVoice"
                },
                {
                  "text": " field to specify which representations to translate to.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outTime"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Core Video result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for possible values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Note that the display link has to be running for this call to succeed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLink": {
      "abstract": [
        {
          "text": "A reference to a display link object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLink"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLink"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLink",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylink"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetActualOutputVideoRefreshPeriod(_:)": {
      "abstract": [
        {
          "text": "Retrieves the actual output refresh period of a display as measured by the system time.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetActualOutputVideoRefreshPeriod"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVDisplayLinkRef",
          "text": "CVDisplayLink"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetActualOutputVideoRefreshPeriod(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetActualOutputVideoRefreshPeriod"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkGetActualOutputVideoRefreshPeriod(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkgetactualoutputvideorefreshperiod(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetCurrentCGDisplay(_:)": {
      "abstract": [
        {
          "text": "Gets the current display associated with a display link.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetCurrentCGDisplay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVDisplayLinkRef",
          "text": "CVDisplayLink"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGDirectDisplayID",
          "text": "CGDirectDisplayID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetCurrentCGDisplay(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetCurrentCGDisplay"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkGetCurrentCGDisplay(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkgetcurrentcgdisplay(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetCurrentTime(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the current (“now”) time of a given display link.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetCurrentTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVDisplayLinkRef",
          "text": "CVDisplayLink"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTimeStamp",
          "text": "CVTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetCurrentTime(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetCurrentTime"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkGetCurrentTime(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkgetcurrenttime(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)": {
      "abstract": [
        {
          "text": "Retrieves the nominal refresh period of a display link.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVDisplayLinkRef",
          "text": "CVDisplayLink"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTime",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkgetnominaloutputvideorefreshperiod(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetOutputVideoLatency(_:)": {
      "abstract": [
        {
          "text": "Retrieves the nominal latency of a display link.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetOutputVideoLatency"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVDisplayLinkRef",
          "text": "CVDisplayLink"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTime",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetOutputVideoLatency(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetOutputVideoLatency"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkGetOutputVideoLatency(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkgetoutputvideolatency(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetTypeID()": {
      "abstract": [
        {
          "text": "Obtains the Core Foundation ID for the display link data type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkgettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkIsRunning(_:)": {
      "abstract": [
        {
          "text": "Indicates whether a given display link is running.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkIsRunning"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVDisplayLinkRef",
          "text": "CVDisplayLink"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkIsRunning(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkIsRunning"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkIsRunning(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkisrunning(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkTranslateTime(_:_:_:)": {
      "abstract": [
        {
          "text": "Translates the time in the display link’s time base from one representation to another.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkTranslateTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVDisplayLinkRef",
          "text": "CVDisplayLink"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTimeStamp",
          "text": "CVTimeStamp"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTimeStamp",
          "text": "CVTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkTranslateTime(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkTranslateTime"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkTranslateTime(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinktranslatetime(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVReturn": {
      "abstract": [
        {
          "text": "A Core Video error type return value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVReturn"
        }
      ],
      "role": "symbol",
      "title": "CVReturn",
      "type": "topic",
      "url": "/documentation/corevideo/cvreturn"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp": {
      "abstract": [
        {
          "text": "A structure for defining a display timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "CVTimeStamp",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Constants",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Display-Links",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetCurrentCGDisplay(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetCurrentTime(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetActualOutputVideoRefreshPeriod(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetOutputVideoLatency(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkIsRunning(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetTypeID()"
      ],
      "title": "Inspecting Display Links"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CVDisplayLinkTranslateTime"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkTranslateTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-Display-Links",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetCurrentCGDisplay(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetCurrentTime(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetActualOutputVideoRefreshPeriod(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetOutputVideoLatency(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkIsRunning(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetTypeID()"
              ],
              "title": "Inspecting Display Links"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVReturn",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CVReturn",
                    "text": "CVReturn"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CVDisplayLinkTranslateTime"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLink",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CVDisplayLinkRef",
                    "text": "CVDisplayLinkRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "displayLink"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CVTimeStamp",
                    "text": "CVTimeStamp"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inTime"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CVTimeStamp",
                    "text": "CVTimeStamp"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outTime"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The display link whose time base should be used to do the translation.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "displayLink"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to a ",
                        "type": "text"
                      },
                      {
                        "code": "CVTimeStamp",
                        "type": "codeVoice"
                      },
                      {
                        "text": " structure containing the source time to translate.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inTime"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to a ",
                        "type": "text"
                      },
                      {
                        "code": "CVTimeStamp",
                        "type": "codeVoice"
                      },
                      {
                        "text": " structure into which the target time is written. Before calling, you must set the version field (currently ",
                        "type": "text"
                      },
                      {
                        "code": "0",
                        "type": "codeVoice"
                      },
                      {
                        "text": ") to indicate which version of the structure you want. You should also set the ",
                        "type": "text"
                      },
                      {
                        "code": "flags",
                        "type": "codeVoice"
                      },
                      {
                        "text": " field to specify which representations to translate to.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "outTime"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A Core Video result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " for possible values.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "use NSView.displayLink(target:selector:), NSWindow.displayLink(target:selector:), or NSScreen.displayLink(target:selector:) ",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVReturn/title",
          "value": "CVReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVReturn/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetCurrentCGDisplay(_:)/title",
          "value": "CVDisplayLinkGetCurrentCGDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetCurrentCGDisplay(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkGetCurrentCGDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetActualOutputVideoRefreshPeriod(_:)/title",
          "value": "CVDisplayLinkGetActualOutputVideoRefreshPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetActualOutputVideoRefreshPeriod(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkGetActualOutputVideoRefreshPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp/title",
          "value": "CVTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)/title",
          "value": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLink/title",
          "value": "CVDisplayLinkRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetOutputVideoLatency(_:)/title",
          "value": "CVDisplayLinkGetOutputVideoLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetOutputVideoLatency(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkGetOutputVideoLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetTypeID()/title",
          "value": "CVDisplayLinkGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkTranslateTime(_:_:_:)/title",
          "value": "CVDisplayLinkTranslateTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkTranslateTime(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkTranslateTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetCurrentTime(_:_:)/title",
          "value": "CVDisplayLinkGetCurrentTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetCurrentTime(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkGetCurrentTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkIsRunning(_:)/title",
          "value": "CVDisplayLinkIsRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkIsRunning(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkIsRunning"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvdisplaylinktranslatetime(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvdisplaylinktranslatetime(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
