{
  "abstract": [
    {
      "text": "Retains a display link.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkRetain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CVDisplayLinkRetain",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CVDisplayLinkRetain"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CVDisplayLinkRetain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CVDisplayLinkRetain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLink",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVDisplayLinkRef",
              "text": "CVDisplayLinkRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVDisplayLinkRetain"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLink",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVDisplayLinkRef",
              "text": "CVDisplayLinkRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "displayLink"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The display link to be retained. This function is ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": "-safe.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "displayLink"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For convenience, this function returns the retained display link if successful.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLink": {
      "abstract": [
        {
          "text": "A reference to a display link object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLink"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLink"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLink",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylink"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkRelease": {
      "abstract": [
        {
          "text": "Releases a display link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkRelease"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkRelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVDisplayLinkRelease",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkrelease"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkRetain": {
      "abstract": [
        {
          "text": "Retains a display link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkRetain"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkRetain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVDisplayLinkRetain",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkretain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retaining-and-Releasing-Display-Links",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkRelease"
      ],
      "title": "Retaining and Releasing Display Links"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLink/title",
          "value": "CVDisplayLinkRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvdisplaylinkretain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
