{
  "abstract": [
    {
      "text": "A structure for holding information that describes a custom extended pixel fill algorithm.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@CVFillExtendedPixelsCallBackData",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CVFillExtendedPixelsCallBackData"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CVFillExtendedPixelsCallBackData"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CVFillExtendedPixelsCallBackData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBackData"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You must fill out this structure and store it as part of your pixel format description Core Foundation dictionary (key: ",
              "type": "text"
            },
            {
              "code": "kCVPixelFormatFillExtendedPixelsCallback",
              "type": "codeVoice"
            },
            {
              "text": ", type: ",
              "type": "text"
            },
            {
              "code": "CFData",
              "type": "codeVoice"
            },
            {
              "text": "). However, if your custom pixel format never needs the functionality of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferFillExtendedPixels(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you don’t need to add this key or implement the associated callback.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about defining a custom pixel format, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-description-keys",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData": {
      "abstract": [
        {
          "text": "A structure for holding information that describes a custom extended pixel fill algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVFillExtendedPixelsCallBackData"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVFillExtendedPixelsCallBackData"
        }
      ],
      "role": "symbol",
      "title": "CVFillExtendedPixelsCallBackData",
      "type": "topic",
      "url": "/documentation/corevideo/cvfillextendedpixelscallbackdata"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/fillCallBack": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fillCallBack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVFillExtendedPixelsCallBack",
          "text": "CVFillExtendedPixelsCallBack"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/fillCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fillCallBack"
        }
      ],
      "role": "symbol",
      "title": "fillCallBack",
      "type": "topic",
      "url": "/documentation/corevideo/cvfillextendedpixelscallbackdata/fillcallback"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/corevideo/cvfillextendedpixelscallbackdata/init()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/init(version:fillCallBack:refCon:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fillCallBack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVFillExtendedPixelsCallBack",
          "text": "CVFillExtendedPixelsCallBack"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "refCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/init(version:fillCallBack:refCon:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(version:fillCallBack:refCon:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvfillextendedpixelscallbackdata/init(version:fillcallback:refcon:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/refCon": {
      "abstract": [
        {
          "text": "A pointer to application-defined data that is passed to your custom pixel fill function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/refCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "refCon"
        }
      ],
      "role": "symbol",
      "title": "refCon",
      "type": "topic",
      "url": "/documentation/corevideo/cvfillextendedpixelscallbackdata/refcon"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/version": {
      "abstract": [
        {
          "text": "The version of this fill algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/corevideo/cvfillextendedpixelscallbackdata/version"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferFillExtendedPixels(_:)": {
      "abstract": [
        {
          "text": "Fills the extended pixels of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferFillExtendedPixels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferFillExtendedPixels(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferFillExtendedPixels"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferFillExtendedPixels(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferfillextendedpixels(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-description-keys": {
      "abstract": [
        {
          "text": "The attributes of a pixel format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-description-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Format Description Keys",
      "type": "topic",
      "url": "/documentation/corevideo/pixel-format-description-keys"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/init()",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/init(version:fillCallBack:refCon:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/fillCallBack",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/refCon",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/version"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CVFillExtendedPixelsCallBackData"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBackData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBackData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Properties",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/fillCallBack",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/refCon",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData/version"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "CVFillExtendedPixelsCallBackData"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferFillExtendedPixels(_:)/title",
          "value": "CVPixelBufferFillExtendedPixels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferFillExtendedPixels(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferFillExtendedPixels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData~1refCon/title",
          "value": "refCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData~1refCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "refCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData/title",
          "value": "CVFillExtendedPixelsCallBackData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBackData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBackData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData~1fillCallBack/title",
          "value": "fillCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData~1fillCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fillCallBack"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvfillextendedpixelscallbackdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvfillextendedpixelscallbackdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
