{
  "abstract": [
    {
      "text": "Returns the frequency of updates to the system time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockFrequency()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CVGetHostClockFrequency",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CVGetHostClockFrequency"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CVGetHostClockFrequency"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CVGetHostClockFrequency()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVGetHostClockFrequency"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The current host frequency.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS, the host time bases for Core Video and CoreAudio are identical—both are based on the ",
              "type": "text"
            },
            {
              "code": "mach_absolute_time",
              "type": "codeVoice"
            },
            {
              "text": " function—so the values returned from either API can be used interchangeably.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVGetCurrentHostTime()": {
      "abstract": [
        {
          "text": "Returns the current system time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVGetCurrentHostTime"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVGetCurrentHostTime()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVGetCurrentHostTime"
        }
      ],
      "role": "symbol",
      "title": "CVGetCurrentHostTime()",
      "type": "topic",
      "url": "/documentation/corevideo/cvgetcurrenthosttime()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockFrequency()": {
      "abstract": [
        {
          "text": "Returns the frequency of updates to the system time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVGetHostClockFrequency"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockFrequency()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVGetHostClockFrequency"
        }
      ],
      "role": "symbol",
      "title": "CVGetHostClockFrequency()",
      "type": "topic",
      "url": "/documentation/corevideo/cvgethostclockfrequency()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockMinimumTimeDelta()": {
      "abstract": [
        {
          "text": "Returns the smallest possible increment in the system time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVGetHostClockMinimumTimeDelta"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockMinimumTimeDelta()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVGetHostClockMinimumTimeDelta"
        }
      ],
      "role": "symbol",
      "title": "CVGetHostClockMinimumTimeDelta()",
      "type": "topic",
      "url": "/documentation/corevideo/cvgethostclockminimumtimedelta()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-the-Host-Clock",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVGetCurrentHostTime()",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockMinimumTimeDelta()"
      ],
      "title": "Inspecting the Host Clock"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CVGetHostClockFrequency"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVGetHostClockFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-the-Host-Clock",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVGetCurrentHostTime()",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockMinimumTimeDelta()"
              ],
              "title": "Inspecting the Host Clock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CVGetHostClockFrequency"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The current host frequency.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetHostClockFrequency()/title",
          "value": "CVGetHostClockFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetHostClockFrequency()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVGetHostClockFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetCurrentHostTime()/title",
          "value": "CVGetCurrentHostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetCurrentHostTime()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVGetCurrentHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetHostClockMinimumTimeDelta()/title",
          "value": "CVGetHostClockMinimumTimeDelta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetHostClockMinimumTimeDelta()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVGetHostClockMinimumTimeDelta"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvgethostclockfrequency()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvgethostclockfrequency()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
