{
  "abstract": [
    {
      "text": "An interface for managing different types of image data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVImageBuffer"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Video image buffers provides a convenient interface for managing different types of image data. Pixel buffers and Core Video OpenGL buffers derive from the Core Video image buffer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetIntegerCodePointForString(_:)": {
      "abstract": [
        {
          "text": "Returns the standard integer code point corresponding to the Core Video color primaries constant string that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVColorPrimariesGetIntegerCodePointForString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetIntegerCodePointForString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVColorPrimariesGetIntegerCodePointForString"
        }
      ],
      "role": "symbol",
      "title": "CVColorPrimariesGetIntegerCodePointForString(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvcolorprimariesgetintegercodepointforstring(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetStringForIntegerCodePoint(_:)": {
      "abstract": [
        {
          "text": "Returns the Core Video color primaries string corresponding to the standard integer code point that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVColorPrimariesGetStringForIntegerCodePoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetStringForIntegerCodePoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVColorPrimariesGetStringForIntegerCodePoint"
        }
      ],
      "role": "symbol",
      "title": "CVColorPrimariesGetStringForIntegerCodePoint(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvcolorprimariesgetstringforintegercodepoint(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBuffer": {
      "abstract": [
        {
          "text": "A reference to a Core Video image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVImageBuffer"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVImageBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferCreateColorSpaceFromAttachments(_:)": {
      "abstract": [
        {
          "text": "Attempts to create a Core Graphics color space from the image buffer’s attachments that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVImageBufferCreateColorSpaceFromAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferCreateColorSpaceFromAttachments(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVImageBufferCreateColorSpaceFromAttachments"
        }
      ],
      "role": "symbol",
      "title": "CVImageBufferCreateColorSpaceFromAttachments(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffercreatecolorspacefromattachments(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetCleanRect(_:)": {
      "abstract": [
        {
          "text": "Returns the source rectangle of a Core Video image buffer that represents the clean aperture of the buffer in encoded pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVImageBufferGetCleanRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetCleanRect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVImageBufferGetCleanRect"
        }
      ],
      "role": "symbol",
      "title": "CVImageBufferGetCleanRect(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffergetcleanrect(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetColorSpace(_:)": {
      "abstract": [
        {
          "text": "Returns the color space of a Core Video image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVImageBufferGetColorSpace"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetColorSpace(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVImageBufferGetColorSpace"
        }
      ],
      "role": "symbol",
      "title": "CVImageBufferGetColorSpace(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffergetcolorspace(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetDisplaySize(_:)": {
      "abstract": [
        {
          "text": "Returns the nominal output display size, in square pixels, of a Core Video image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVImageBufferGetDisplaySize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetDisplaySize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVImageBufferGetDisplaySize"
        }
      ],
      "role": "symbol",
      "title": "CVImageBufferGetDisplaySize(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffergetdisplaysize(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetEncodedSize(_:)": {
      "abstract": [
        {
          "text": "Returns the full encoded dimensions of a Core Video image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVImageBufferGetEncodedSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetEncodedSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVImageBufferGetEncodedSize"
        }
      ],
      "role": "symbol",
      "title": "CVImageBufferGetEncodedSize(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffergetencodedsize(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferIsFlipped(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the image is vertically flipped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVImageBufferIsFlipped"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferIsFlipped(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVImageBufferIsFlipped"
        }
      ],
      "role": "symbol",
      "title": "CVImageBufferIsFlipped(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebufferisflipped(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o": {
      "abstract": [
        {
          "text": "A utility object for managing a recyclable set of pixel buffer objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpool-77o"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetIntegerCodePointForString(_:)": {
      "abstract": [
        {
          "text": "Returns the standard integer code point corresponding to the Core Video transfer function string that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTransferFunctionGetIntegerCodePointForString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetIntegerCodePointForString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTransferFunctionGetIntegerCodePointForString"
        }
      ],
      "role": "symbol",
      "title": "CVTransferFunctionGetIntegerCodePointForString(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvtransferfunctiongetintegercodepointforstring(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetStringForIntegerCodePoint(_:)": {
      "abstract": [
        {
          "text": "Returns the Core Video transfer function string corresponding to the standard integer code point that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTransferFunctionGetStringForIntegerCodePoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetStringForIntegerCodePoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTransferFunctionGetStringForIntegerCodePoint"
        }
      ],
      "role": "symbol",
      "title": "CVTransferFunctionGetStringForIntegerCodePoint(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvtransferfunctiongetstringforintegercodepoint(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetIntegerCodePointForString(_:)": {
      "abstract": [
        {
          "text": "Returns the standard integer code point corresponding to the Core Video YCbCr matrix string that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVYCbCrMatrixGetIntegerCodePointForString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetIntegerCodePointForString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVYCbCrMatrixGetIntegerCodePointForString"
        }
      ],
      "role": "symbol",
      "title": "CVYCbCrMatrixGetIntegerCodePointForString(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvycbcrmatrixgetintegercodepointforstring(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetStringForIntegerCodePoint(_:)": {
      "abstract": [
        {
          "text": "Returns the Core Video YCbCr matrix string corresponding to the standard integer code point that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVYCbCrMatrixGetStringForIntegerCodePoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetStringForIntegerCodePoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVYCbCrMatrixGetStringForIntegerCodePoint"
        }
      ],
      "role": "symbol",
      "title": "CVYCbCrMatrixGetStringForIntegerCodePoint(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvycbcrmatrixgetstringforintegercodepoint(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm": {
      "abstract": [
        {
          "text": "An abstract base class that defines how to interact with data buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer-nfm"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e": {
      "abstract": [
        {
          "text": "An image buffer that holds pixels in main memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffer-q2e"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription": {
      "abstract": [
        {
          "text": "An API that provides functions and types for defining custom pixel formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelFormatDescription",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelformatdescription"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys": {
      "abstract": [
        {
          "text": "Keys that describe the attachment types associated with image buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Attachment Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-attachment-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants": {
      "abstract": [
        {
          "text": "Constants that indicate locations for chroma samples in the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Chroma Location Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-chroma-location-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the original format of subsampled data in the image buffer before conversion to 422/2vuy format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Chroma Subsampling Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-chroma-subsampling-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys": {
      "abstract": [
        {
          "text": "Keys that describe the clean aperture of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Clean Aperture Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-clean-aperture-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the color primaries gamut for the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Color Primaries Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-color-primaries-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys": {
      "abstract": [
        {
          "text": "Keys that describe the display dimensions of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Display Dimensions Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-display-dimensions-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the field order of interlaced video in an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Field Detail Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-field-detail-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys": {
      "abstract": [
        {
          "text": "Keys that describe the pixel aspect ratio of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Pixel Aspect Ratio Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-pixel-aspect-ratio-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the transfer function for the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Transfer Function Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-transfer-function-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the type of conversion matrix Core Video uses when it converts image buffer data from the YCbCr color space to the RGB color space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer YCbCr Matrix Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-ycbcr-matrix-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536",
      "title": "Core Video Programming Guide",
      "titleInlineContent": [
        {
          "text": "Core Video Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Data-Processing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
      ],
      "title": "Data Processing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-image-buffers",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetCleanRect(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetColorSpace(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetDisplaySize(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetEncodedSize(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferIsFlipped(_:)"
      ],
      "title": "Inspecting image buffers"
    },
    {
      "anchor": "Creating-color-spaces",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferCreateColorSpaceFromAttachments(_:)"
      ],
      "title": "Creating color spaces"
    },
    {
      "anchor": "Data-types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBuffer"
      ],
      "title": "Data types"
    },
    {
      "anchor": "Converting-between-strings-and-integer-code-points",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetIntegerCodePointForString(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetStringForIntegerCodePoint(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetIntegerCodePointForString(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetStringForIntegerCodePoint(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetIntegerCodePointForString(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetStringForIntegerCodePoint(_:)"
      ],
      "title": "Converting between strings and integer code points"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-image-buffers",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetCleanRect(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetColorSpace(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetDisplaySize(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferGetEncodedSize(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferIsFlipped(_:)"
              ],
              "title": "Inspecting image buffers"
            },
            {
              "anchor": "Creating-color-spaces",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBufferCreateColorSpaceFromAttachments(_:)"
              ],
              "title": "Creating color spaces"
            },
            {
              "anchor": "Data-types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBuffer"
              ],
              "title": "Data types"
            },
            {
              "anchor": "Converting-between-strings-and-integer-code-points",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetIntegerCodePointForString(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVColorPrimariesGetStringForIntegerCodePoint(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetIntegerCodePointForString(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTransferFunctionGetStringForIntegerCodePoint(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetIntegerCodePointForString(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVYCbCrMatrixGetStringForIntegerCodePoint(_:)"
              ],
              "title": "Converting between strings and integer code points"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Data-Processing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
              ],
              "title": "Data Processing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTransferFunctionGetStringForIntegerCodePoint(_:)/title",
          "value": "CVTransferFunctionGetStringForIntegerCodePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTransferFunctionGetStringForIntegerCodePoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTransferFunctionGetStringForIntegerCodePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVYCbCrMatrixGetIntegerCodePointForString(_:)/title",
          "value": "CVYCbCrMatrixGetIntegerCodePointForString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVYCbCrMatrixGetIntegerCodePointForString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVYCbCrMatrixGetIntegerCodePointForString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferGetEncodedSize(_:)/title",
          "value": "CVImageBufferGetEncodedSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferGetEncodedSize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVImageBufferGetEncodedSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferIsFlipped(_:)/title",
          "value": "CVImageBufferIsFlipped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferIsFlipped(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVImageBufferIsFlipped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVColorPrimariesGetIntegerCodePointForString(_:)/title",
          "value": "CVColorPrimariesGetIntegerCodePointForString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVColorPrimariesGetIntegerCodePointForString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVColorPrimariesGetIntegerCodePointForString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferGetDisplaySize(_:)/title",
          "value": "CVImageBufferGetDisplaySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferGetDisplaySize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVImageBufferGetDisplaySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTransferFunctionGetIntegerCodePointForString(_:)/title",
          "value": "CVTransferFunctionGetIntegerCodePointForString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTransferFunctionGetIntegerCodePointForString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTransferFunctionGetIntegerCodePointForString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferGetCleanRect(_:)/title",
          "value": "CVImageBufferGetCleanRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferGetCleanRect(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVImageBufferGetCleanRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferGetColorSpace(_:)/title",
          "value": "CVImageBufferGetColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferGetColorSpace(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVImageBufferGetColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVColorPrimariesGetStringForIntegerCodePoint(_:)/title",
          "value": "CVColorPrimariesGetStringForIntegerCodePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVColorPrimariesGetStringForIntegerCodePoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVColorPrimariesGetStringForIntegerCodePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVYCbCrMatrixGetStringForIntegerCodePoint(_:)/title",
          "value": "CVYCbCrMatrixGetStringForIntegerCodePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVYCbCrMatrixGetStringForIntegerCodePoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVYCbCrMatrixGetStringForIntegerCodePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferCreateColorSpaceFromAttachments(_:)/title",
          "value": "CVImageBufferCreateColorSpaceFromAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBufferCreateColorSpaceFromAttachments(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVImageBufferCreateColorSpaceFromAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBuffer/title",
          "value": "CVImageBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVImageBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVImageBufferRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvimagebuffer-q40"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvimagebuffer-q40"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
