{
  "abstract": [
    {
      "text": "A cache used to create and manage Metal texture objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVMetalTextureCache"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Core Video Metal texture cache creates and manages ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTexture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " textures. You use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to directly read from or write to GPU-based Core Video image buffers in rendering, or for sharing data with Metal kernels. For example, you can use a Metal texture cache to present live output from a device’s camera in a 3D scene rendered with Metal.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTexture": {
      "abstract": [
        {
          "text": "A reference to a CoreVideo Metal texture-based image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalTexture"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalTexture"
        }
      ],
      "role": "symbol",
      "title": "CVMetalTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexture"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCache": {
      "abstract": [
        {
          "text": "A reference to a Core Video Metal texture cache.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalTextureCache"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalTextureCache"
        }
      ],
      "role": "symbol",
      "title": "CVMetalTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturecache"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCache-cache-attributes": {
      "abstract": [
        {
          "text": "Attributes specifying texture cache behavior, used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheCreate(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCache-cache-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cache Attributes",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturecache-cache-attributes"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheCreate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new texture cache.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalTextureCacheCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalTextureCacheRef",
          "text": "CVMetalTextureCache"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheCreate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalTextureCacheCreate"
        }
      ],
      "role": "symbol",
      "title": "CVMetalTextureCacheCreate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturecachecreate(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a Core Video Metal texture buffer from an existing image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalTextureCacheCreateTextureFromImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalTextureCacheRef",
          "text": "CVMetalTextureCache"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalTextureRef",
          "text": "CVMetalTexture"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalTextureCacheCreateTextureFromImage"
        }
      ],
      "role": "symbol",
      "title": "CVMetalTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturecachecreatetexturefromimage(_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheFlush(_:_:)": {
      "abstract": [
        {
          "text": "Manually flushes the contents of the provided texture cache.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalTextureCacheFlush"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalTextureCacheRef",
          "text": "CVMetalTextureCache"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOptionFlags",
          "text": "CVOptionFlags"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheFlush(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalTextureCacheFlush"
        }
      ],
      "role": "symbol",
      "title": "CVMetalTextureCacheFlush(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturecacheflush(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier for a Core Video Metal texture cache.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalTextureCacheGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalTextureCacheGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVMetalTextureCacheGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturecachegettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexture-q3g": {
      "abstract": [
        {
          "text": "A texture-based image buffer that supplies source image data for use with the Metal framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexture-q3g",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVMetalTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexture-q3g"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j": {
      "abstract": [
        {
          "text": "A cache used to create and manage Metal texture objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVMetalTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturecache-q3j"
    },
    "doc://com.apple.documentation/documentation/Metal/setting-up-a-command-structure": {
      "abstract": [
        {
          "text": "Discover how Metal executes commands on a GPU.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/setting-up-a-command-structure",
      "kind": "article",
      "role": "article",
      "title": "Setting Up a Command Structure",
      "type": "topic",
      "url": "/documentation/Metal/setting-up-a-command-structure"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metal",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexture-q3g"
      ],
      "title": "Metal"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheCreate(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheFlush(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheGetTypeID()"
      ],
      "title": "Functions"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCache"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCache-cache-attributes"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Metal/setting-up-a-command-structure"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheCreate(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheFlush(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCacheGetTypeID()"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCache"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureCache-cache-attributes"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Metal/setting-up-a-command-structure"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metal",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexture-q3g"
              ],
              "title": "Metal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureCacheGetTypeID()/title",
          "value": "CVMetalTextureCacheGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureCacheGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureCacheGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureCacheFlush(_:_:)/title",
          "value": "CVMetalTextureCacheFlush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureCacheFlush(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureCacheFlush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureCache/title",
          "value": "CVMetalTextureCacheRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureCacheRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureCache/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureCacheRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureCacheCreate(_:_:_:_:_:)/title",
          "value": "CVMetalTextureCacheCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureCacheCreate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureCacheCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:)/title",
          "value": "CVMetalTextureCacheCreateTextureFromImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureCacheCreateTextureFromImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTexture/title",
          "value": "CVMetalTextureRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvmetaltexturecache-q3j"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvmetaltexturecache-q3j"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
