{
  "abstract": [
    {
      "text": "A texture-based image buffer that supplies source image data for use with the Metal framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexture-q3g"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVMetalTexture"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Core Video Metal Texture is a texture-based image buffer that supplies source image data for use with the Metal framework.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTexture": {
      "abstract": [
        {
          "text": "A reference to a CoreVideo Metal texture-based image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalTexture"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalTexture"
        }
      ],
      "role": "symbol",
      "title": "CVMetalTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexture"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetCleanTexCoords(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns convenient normalized texture coordinates for the part of the image that should be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalTextureGetCleanTexCoords"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalTextureRef",
          "text": "CVMetalTexture"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetCleanTexCoords(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalTextureGetCleanTexCoords"
        }
      ],
      "role": "symbol",
      "title": "CVMetalTextureGetCleanTexCoords(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturegetcleantexcoords(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetTexture(_:)": {
      "abstract": [
        {
          "text": "Returns the Metal texture object for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalTextureGetTexture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalTextureRef",
          "text": "CVMetalTexture"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetTexture(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalTextureGetTexture"
        }
      ],
      "role": "symbol",
      "title": "CVMetalTextureGetTexture(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturegettexture(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier for a CoreVideo Metal texture-based image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalTextureGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalTextureGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVMetalTextureGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturegettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureIsFlipped(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the texture image is vertically flipped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalTextureIsFlipped"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalTextureRef",
          "text": "CVMetalTexture"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureIsFlipped(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalTextureIsFlipped"
        }
      ],
      "role": "symbol",
      "title": "CVMetalTextureIsFlipped(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltextureisflipped(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j": {
      "abstract": [
        {
          "text": "A cache used to create and manage Metal texture objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVMetalTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturecache-q3j"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metal",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j"
      ],
      "title": "Metal"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-Textures",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetTexture(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetCleanTexCoords(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureIsFlipped(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetTypeID()"
      ],
      "title": "Inspecting Textures"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTexture"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-Textures",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetTexture(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetCleanTexCoords(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureIsFlipped(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTextureGetTypeID()"
              ],
              "title": "Inspecting Textures"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalTexture"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metal",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j"
              ],
              "title": "Metal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTexture/title",
          "value": "CVMetalTextureRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureIsFlipped(_:)/title",
          "value": "CVMetalTextureIsFlipped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureIsFlipped(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureIsFlipped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureGetTypeID()/title",
          "value": "CVMetalTextureGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureGetCleanTexCoords(_:_:_:_:_:)/title",
          "value": "CVMetalTextureGetCleanTexCoords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureGetCleanTexCoords(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureGetCleanTexCoords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureGetTexture(_:)/title",
          "value": "CVMetalTextureGetTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalTextureGetTexture(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalTextureGetTexture"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvmetaltexture-q3g"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvmetaltexture-q3g"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
