{
  "abstract": [
    {
      "text": "Dictionary keys and values for use with the cacheAttributes parameter of ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)",
      "isActive": true,
      "type": "reference"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCache-cache-attributes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Cache Attributes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In some cases, a texture cache can do higher quality chroma upsampling on GPUs that support ",
              "type": "text"
            },
            {
              "code": "ARB_fragment_program",
              "type": "codeVoice"
            },
            {
              "text": ". By default, it will be enabled automatically if the texture cache determines that the GPU has the needed support and the image size is something reasonable for the GPU being used. The default behavior can be overridden using the values defined below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Setting the chroma sampling mode to ",
                  "type": "text"
                },
                {
                  "code": "kCVOpenGLTextureCacheChromaSamplingModeHighQuality",
                  "type": "codeVoice"
                },
                {
                  "text": " is only a request. GPUs that don’t support ",
                  "type": "text"
                },
                {
                  "code": "ARB_fragment_program",
                  "type": "codeVoice"
                },
                {
                  "text": " will still resort back to the native hardware support for YCbCr textures.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new texture cache.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGLContextObj",
          "text": "CGLContextObj"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGLPixelFormatObj",
          "text": "CGLPixelFormatObj"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLTextureCacheRef",
          "text": "CVOpenGLTextureCache"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheCreate"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecachecreate(_:_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780": {
      "abstract": [
        {
          "text": "A cache used to create and manage OpenGL texture objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecache-780"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeAutomatic": {
      "abstract": [
        {
          "text": "The default mode if not otherwise specified.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVOpenGLTextureCacheChromaSamplingModeAutomatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeAutomatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVOpenGLTextureCacheChromaSamplingModeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "kCVOpenGLTextureCacheChromaSamplingModeAutomatic",
      "type": "topic",
      "url": "/documentation/corevideo/kcvopengltexturecachechromasamplingmodeautomatic"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeBestPerformance": {
      "abstract": [
        {
          "text": "Set the chroma sample mode to use the most performant way possible.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVOpenGLTextureCacheChromaSamplingModeBestPerformance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeBestPerformance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVOpenGLTextureCacheChromaSamplingModeBestPerformance"
        }
      ],
      "role": "symbol",
      "title": "kCVOpenGLTextureCacheChromaSamplingModeBestPerformance",
      "type": "topic",
      "url": "/documentation/corevideo/kcvopengltexturecachechromasamplingmodebestperformance"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeHighestQuality": {
      "abstract": [
        {
          "text": "Forces the highest quality regardless of performance impact.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVOpenGLTextureCacheChromaSamplingModeHighestQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeHighestQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVOpenGLTextureCacheChromaSamplingModeHighestQuality"
        }
      ],
      "role": "symbol",
      "title": "kCVOpenGLTextureCacheChromaSamplingModeHighestQuality",
      "type": "topic",
      "url": "/documentation/corevideo/kcvopengltexturecachechromasamplingmodehighestquality"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeKey": {
      "abstract": [
        {
          "text": "The key used to define the cache’s requested chroma sampling mode.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVOpenGLTextureCacheChromaSamplingModeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVOpenGLTextureCacheChromaSamplingModeKey"
        }
      ],
      "role": "symbol",
      "title": "kCVOpenGLTextureCacheChromaSamplingModeKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvopengltexturecachechromasamplingmodekey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Key",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeKey"
      ],
      "title": "Key"
    },
    {
      "anchor": "Values",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeAutomatic",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeHighestQuality",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeBestPerformance"
      ],
      "title": "Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Key",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeKey"
              ],
              "title": "Key"
            },
            {
              "anchor": "Values",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeAutomatic",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeHighestQuality",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLTextureCacheChromaSamplingModeBestPerformance"
              ],
              "title": "Values"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLTextureCacheChromaSamplingModeAutomatic/title",
          "value": "kCVOpenGLTextureCacheChromaSamplingModeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLTextureCacheChromaSamplingModeAutomatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVOpenGLTextureCacheChromaSamplingModeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLTextureCacheChromaSamplingModeKey/title",
          "value": "kCVOpenGLTextureCacheChromaSamplingModeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLTextureCacheChromaSamplingModeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVOpenGLTextureCacheChromaSamplingModeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)/title",
          "value": "CVOpenGLTextureCacheCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureCacheCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLTextureCacheChromaSamplingModeBestPerformance/title",
          "value": "kCVOpenGLTextureCacheChromaSamplingModeBestPerformance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLTextureCacheChromaSamplingModeBestPerformance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVOpenGLTextureCacheChromaSamplingModeBestPerformance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLTextureCacheChromaSamplingModeHighestQuality/title",
          "value": "kCVOpenGLTextureCacheChromaSamplingModeHighestQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLTextureCacheChromaSamplingModeHighestQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVOpenGLTextureCacheChromaSamplingModeHighestQuality"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvopengltexturecache-cache-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvopengltexturecache-cache-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
