{
  "abstract": [
    {
      "text": "An image buffer used to store image data in video memory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVOpenGLBuffer"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBuffer": {
      "abstract": [
        {
          "text": "A reference to a Core Video OpenGL buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBuffer"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbuffer"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferAttach(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Attaches an OpenGL context to a Core Video OpenGL buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferAttach"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLBufferRef",
          "text": "CVOpenGLBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGLContextObj",
          "text": "CGLContextObj"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLenum",
          "text": "GLenum"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferAttach(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferAttach"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferAttach(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferattach(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferCreate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new Core Video OpenGL buffer that can be used for OpenGL rendering purposes",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLBufferRef",
          "text": "CVOpenGLBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferCreate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferCreate"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferCreate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbuffercreate(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetAttributes(_:)": {
      "abstract": [
        {
          "text": "Obtains the attributes of a Core Video OpenGL buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferGetAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLBufferRef",
          "text": "CVOpenGLBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferGetAttributes"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferGetAttributes(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbuffergetattributes(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetTypeID()": {
      "abstract": [
        {
          "text": "Obtains the Core Foundation type ID for the OpenGL buffer type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbuffergettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRelease": {
      "abstract": [
        {
          "text": "Releases a Core Video OpenGL buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferRelease"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVOpenGLBufferRelease",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferrelease"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRetain": {
      "abstract": [
        {
          "text": "Retains a Core Video OpenGL buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferRetain"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRetain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVOpenGLBufferRetain",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferretain"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j": {
      "abstract": [
        {
          "text": "A utility object for managing a set of recyclable OpenGL buffer objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpool-77j"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782": {
      "abstract": [
        {
          "text": "A texture-based image buffer that supplies source image data to OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexture-782"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780": {
      "abstract": [
        {
          "text": "A cache used to create and manage OpenGL texture objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecache-780"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferHeight": {
      "abstract": [
        {
          "text": "The height of the buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferHeight"
        }
      ],
      "role": "symbol",
      "title": "kCVOpenGLBufferHeight",
      "type": "topic",
      "url": "/documentation/corevideo/kcvopenglbufferheight"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferInternalFormat": {
      "abstract": [
        {
          "text": "The OpenGL internal format of this buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferInternalFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferInternalFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferInternalFormat"
        }
      ],
      "role": "symbol",
      "title": "kCVOpenGLBufferInternalFormat",
      "type": "topic",
      "url": "/documentation/corevideo/kcvopenglbufferinternalformat"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferMaximumMipmapLevel": {
      "abstract": [
        {
          "text": "The maximum mipmap level for this buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferMaximumMipmapLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferMaximumMipmapLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferMaximumMipmapLevel"
        }
      ],
      "role": "symbol",
      "title": "kCVOpenGLBufferMaximumMipmapLevel",
      "type": "topic",
      "url": "/documentation/corevideo/kcvopenglbuffermaximummipmaplevel"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferTarget": {
      "abstract": [
        {
          "text": "The OpenGL target for this buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferTarget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferTarget"
        }
      ],
      "role": "symbol",
      "title": "kCVOpenGLBufferTarget",
      "type": "topic",
      "url": "/documentation/corevideo/kcvopenglbuffertarget"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferWidth": {
      "abstract": [
        {
          "text": "The width of the buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferWidth"
        }
      ],
      "role": "symbol",
      "title": "kCVOpenGLBufferWidth",
      "type": "topic",
      "url": "/documentation/corevideo/kcvopenglbufferwidth"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "OpenGL",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j"
      ],
      "title": "OpenGL"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferCreate(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferAttach(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetAttributes(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetTypeID()"
      ],
      "title": "Functions"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBuffer"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferHeight",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferInternalFormat",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferMaximumMipmapLevel",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferTarget",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferWidth"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferCreate(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferAttach(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetAttributes(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetTypeID()",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRetain",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRelease"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBuffer"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferHeight",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferInternalFormat",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferMaximumMipmapLevel",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferTarget",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferWidth"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "OpenGL",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j"
              ],
              "title": "OpenGL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferTarget/title",
          "value": "kCVOpenGLBufferTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVOpenGLBufferTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferAttach(_:_:_:_:_:)/title",
          "value": "CVOpenGLBufferAttach"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferAttach(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferAttach"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferWidth/title",
          "value": "kCVOpenGLBufferWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVOpenGLBufferWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferHeight/title",
          "value": "kCVOpenGLBufferHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVOpenGLBufferHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferCreate(_:_:_:_:_:)/title",
          "value": "CVOpenGLBufferCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferCreate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferGetTypeID()/title",
          "value": "CVOpenGLBufferGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferMaximumMipmapLevel/title",
          "value": "kCVOpenGLBufferMaximumMipmapLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferMaximumMipmapLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVOpenGLBufferMaximumMipmapLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferInternalFormat/title",
          "value": "kCVOpenGLBufferInternalFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferInternalFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVOpenGLBufferInternalFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferGetAttributes(_:)/title",
          "value": "CVOpenGLBufferGetAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferGetAttributes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferGetAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBuffer/title",
          "value": "CVOpenGLBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvopenglbuffer-77s"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvopenglbuffer-77s"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
