{
  "abstract": [
    {
      "text": "A texture-based image buffer that supplies source image data to OpenGL ES.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglestexture-q2s"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVOpenGLESTexture"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Video OpenGL ES textures are texture-based image buffers the system uses to supply source image data to OpenGL.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTexture": {
      "abstract": [
        {
          "text": "A reference to a Core Video texture-based image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTexture"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTexture"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexture"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-q2r": {
      "abstract": [
        {
          "text": "A cache used to create and manage OpenGL ES texture objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-q2r",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLESTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturecache-q2r"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetCleanTexCoords(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns convenient normalized texture coordinates for the part of the image that should be displayed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureGetCleanTexCoords"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLESTextureRef",
          "text": "CVOpenGLESTexture"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLfloat",
          "text": "GLfloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLfloat",
          "text": "GLfloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLfloat",
          "text": "GLfloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLfloat",
          "text": "GLfloat"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetCleanTexCoords(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureGetCleanTexCoords"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTextureGetCleanTexCoords(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturegetcleantexcoords(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetName(_:)": {
      "abstract": [
        {
          "text": "Returns the texture target name for a ",
          "type": "text"
        },
        {
          "code": "CVOpenGLESTextureRef",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureGetName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLESTextureRef",
          "text": "CVOpenGLESTexture"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLuint",
          "text": "GLuint"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureGetName"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTextureGetName(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturegetname(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetTarget(_:)": {
      "abstract": [
        {
          "text": "Returns the texture target for a ",
          "type": "text"
        },
        {
          "code": "CVOpenGLESTextureRef",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureGetTarget"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLESTextureRef",
          "text": "CVOpenGLESTexture"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLenum",
          "text": "GLenum"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetTarget(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureGetTarget"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTextureGetTarget(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturegettarget(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier for a Core Video texture-based image buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTextureGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturegettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureIsFlipped(_:)": {
      "abstract": [
        {
          "text": "Returns whether the image is flipped vertically or not.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureIsFlipped"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLESTextureRef",
          "text": "CVOpenGLESTexture"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureIsFlipped(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureIsFlipped"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTextureIsFlipped(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestextureisflipped(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "OpenGL-ES",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-q2r"
      ],
      "title": "OpenGL ES"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "The functions in this section operate on Core Video texture-based image buffers derived from the ",
          "type": "text"
        },
        {
          "code": "CVOpenGLESTextureRef",
          "type": "codeVoice"
        },
        {
          "text": " type.",
          "type": "text"
        }
      ],
      "anchor": "Inspecting-Textures",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetTarget(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetName(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetCleanTexCoords(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureIsFlipped(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetTypeID()"
      ],
      "title": "Inspecting Textures"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTexture"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "The functions in this section operate on Core Video texture-based image buffers derived from the ",
                  "type": "text"
                },
                {
                  "code": "CVOpenGLESTextureRef",
                  "type": "codeVoice"
                },
                {
                  "text": " type.",
                  "type": "text"
                }
              ],
              "anchor": "Inspecting-Textures",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetTarget(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetName(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetCleanTexCoords(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureIsFlipped(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureGetTypeID()"
              ],
              "title": "Inspecting Textures"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTexture"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "OpenGL-ES",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-q2r"
              ],
              "title": "OpenGL ES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureGetCleanTexCoords(_:_:_:_:_:)/title",
          "value": "CVOpenGLESTextureGetCleanTexCoords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureGetCleanTexCoords(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureGetCleanTexCoords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureGetTypeID()/title",
          "value": "CVOpenGLESTextureGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTexture/title",
          "value": "CVOpenGLESTextureRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureGetTarget(_:)/title",
          "value": "CVOpenGLESTextureGetTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureGetTarget(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureGetTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureIsFlipped(_:)/title",
          "value": "CVOpenGLESTextureIsFlipped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureIsFlipped(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureIsFlipped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureGetName(_:)/title",
          "value": "CVOpenGLESTextureGetName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureGetName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureGetName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvopenglestexture-q2s"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvopenglestexture-q2s"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
