{
  "abstract": [
    {
      "text": "Obtains the Core Foundation type ID for the OpenGL buffer type.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "OpenGL/OpenGLES is no longer supported. Use Metal APIs instead. (Define COREVIDEO_SILENCE_GL_DEPRECATION to silence these warnings)",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetTypeID()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CVOpenGLBufferGetTypeID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CVOpenGLBufferGetTypeID"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFTypeID",
        "text": "CFTypeID"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CVOpenGLBufferGetTypeID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.4",
        "message": "OpenGL/OpenGLES is no longer supported. Use Metal APIs instead. (Define COREVIDEO_SILENCE_GL_DEPRECATION to silence these warnings)",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CVOpenGLBufferGetTypeID()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferGetTypeID"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeID",
              "text": "CFTypeID"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Core Foundation ID for this data type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferAttach(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Attaches an OpenGL context to a Core Video OpenGL buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferAttach"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLBufferRef",
          "text": "CVOpenGLBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGLContextObj",
          "text": "CGLContextObj"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLenum",
          "text": "GLenum"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferAttach(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferAttach"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferAttach(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferattach(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferCreate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new Core Video OpenGL buffer that can be used for OpenGL rendering purposes",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLBufferRef",
          "text": "CVOpenGLBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferCreate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferCreate"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferCreate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbuffercreate(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetAttributes(_:)": {
      "abstract": [
        {
          "text": "Obtains the attributes of a Core Video OpenGL buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferGetAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLBufferRef",
          "text": "CVOpenGLBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferGetAttributes"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferGetAttributes(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbuffergetattributes(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetTypeID()": {
      "abstract": [
        {
          "text": "Obtains the Core Foundation type ID for the OpenGL buffer type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbuffergettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRelease": {
      "abstract": [
        {
          "text": "Releases a Core Video OpenGL buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferRelease"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVOpenGLBufferRelease",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferrelease"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRetain": {
      "abstract": [
        {
          "text": "Retains a Core Video OpenGL buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferRetain"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRetain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVOpenGLBufferRetain",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferretain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFTypeID": {
      "abstract": [
        {
          "text": "A type for unique, constant integer values that identify particular Core Foundation opaque types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTypeID",
      "type": "topic",
      "url": "/documentation/corefoundation/cftypeid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferCreate(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferAttach(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetAttributes(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CVOpenGLBufferGetTypeID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferCreate(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferAttach(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferGetAttributes(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRetain",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferRelease"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFTypeID",
                    "text": "CFTypeID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CVOpenGLBufferGetTypeID"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The Core Foundation ID for this data type.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "OpenGL/OpenGLES is no longer supported. Use Metal APIs instead. (Define COREVIDEO_SILENCE_GL_DEPRECATION to silence these warnings)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferCreate(_:_:_:_:_:)/title",
          "value": "CVOpenGLBufferCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferCreate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferGetAttributes(_:)/title",
          "value": "CVOpenGLBufferGetAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferGetAttributes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferGetAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferGetTypeID()/title",
          "value": "CVOpenGLBufferGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferAttach(_:_:_:_:_:)/title",
          "value": "CVOpenGLBufferAttach"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferAttach(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferAttach"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvopenglbuffergettypeid()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvopenglbuffergettypeid()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
