{
  "abstract": [
    {
      "text": "A cache used to create and manage OpenGL texture objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVOpenGLTextureCache"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCache"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCache"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecache"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCache-cache-attributes": {
      "abstract": [
        {
          "text": "Dictionary keys and values for use with the cacheAttributes parameter of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCache-cache-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cache Attributes",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecache-cache-attributes"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new texture cache.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGLContextObj",
          "text": "CGLContextObj"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGLPixelFormatObj",
          "text": "CGLPixelFormatObj"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLTextureCacheRef",
          "text": "CVOpenGLTextureCache"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheCreate"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecachecreate(_:_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreateTextureFromImage(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a CVOpenGLTexture object from an existing ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheCreateTextureFromImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLTextureCacheRef",
          "text": "CVOpenGLTextureCache"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLTextureRef",
          "text": "CVOpenGLTexture"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreateTextureFromImage(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheCreateTextureFromImage"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTextureCacheCreateTextureFromImage(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecachecreatetexturefromimage(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheFlush(_:_:)": {
      "abstract": [
        {
          "text": "Performs internal housekeeping/recycling operations on the cache.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheFlush"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLTextureCacheRef",
          "text": "CVOpenGLTextureCache"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOptionFlags",
          "text": "CVOptionFlags"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheFlush(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheFlush"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTextureCacheFlush(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecacheflush(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier for a the texture cache.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTextureCacheGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecachegettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheRelease": {
      "abstract": [
        {
          "text": "Releases a texture cache object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheRelease"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheRelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVOpenGLTextureCacheRelease",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecacherelease"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheRetain": {
      "abstract": [
        {
          "text": "Retains a texture cache object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureCacheRetain"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheRetain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVOpenGLTextureCacheRetain",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecacheretain"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40": {
      "abstract": [
        {
          "text": "An interface for managing different types of image data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer-q40"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s": {
      "abstract": [
        {
          "text": "An image buffer used to store image data in video memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbuffer-77s"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j": {
      "abstract": [
        {
          "text": "A utility object for managing a set of recyclable OpenGL buffer objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpool-77j"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782": {
      "abstract": [
        {
          "text": "A texture-based image buffer that supplies source image data to OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexture-782"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "OpenGL",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j"
      ],
      "title": "OpenGL"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreateTextureFromImage(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheFlush(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheGetTypeID()"
      ],
      "title": "Functions"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCache"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCache-cache-attributes"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheCreateTextureFromImage(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheFlush(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheRetain",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheRelease",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCacheGetTypeID()"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCache"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureCache-cache-attributes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "OpenGL",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j"
              ],
              "title": "OpenGL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)/title",
          "value": "CVOpenGLTextureCacheCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCacheCreate(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureCacheCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCacheGetTypeID()/title",
          "value": "CVOpenGLTextureCacheGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCacheGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureCacheGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCache/title",
          "value": "CVOpenGLTextureCacheRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureCacheRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCache/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureCacheRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCacheCreateTextureFromImage(_:_:_:_:_:)/title",
          "value": "CVOpenGLTextureCacheCreateTextureFromImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCacheCreateTextureFromImage(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureCacheCreateTextureFromImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCacheFlush(_:_:)/title",
          "value": "CVOpenGLTextureCacheFlush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureCacheFlush(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureCacheFlush"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvopengltexturecache-780"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvopengltexturecache-780"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
