{
  "abstract": [
    {
      "text": "A texture-based image buffer that supplies source image data to OpenGL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVOpenGLTexture"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Video OpenGL textures are texture-based image buffers used for supplying source image data to OpenGL.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTexture": {
      "abstract": [
        {
          "text": "A reference to an OpenGL texture-based image buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTexture"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTexture"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexture"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetCleanTexCoords(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the texture coordinates for the part of the image that should be displayed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureGetCleanTexCoords"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLTextureRef",
          "text": "CVOpenGLTexture"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLfloat",
          "text": "GLfloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLfloat",
          "text": "GLfloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLfloat",
          "text": "GLfloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLfloat",
          "text": "GLfloat"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetCleanTexCoords(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureGetCleanTexCoords"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTextureGetCleanTexCoords(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturegetcleantexcoords(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetName(_:)": {
      "abstract": [
        {
          "text": "Returns the texture target name of a CoreVideo OpenGL texture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureGetName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLTextureRef",
          "text": "CVOpenGLTexture"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLuint",
          "text": "GLuint"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureGetName"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTextureGetName(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturegetname(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetTarget(_:)": {
      "abstract": [
        {
          "text": "Returns the texture target (for example, ",
          "type": "text"
        },
        {
          "code": "GL_TEXTURE_2D",
          "type": "codeVoice"
        },
        {
          "text": ") of an OpenGL texture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureGetTarget"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLTextureRef",
          "text": "CVOpenGLTexture"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLenum",
          "text": "GLenum"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetTarget(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureGetTarget"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTextureGetTarget(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturegettarget(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetTypeID()": {
      "abstract": [
        {
          "text": "Obtains the Core Foundation ID for the Core Video OpenGL texture type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTextureGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturegettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureIsFlipped(_:)": {
      "abstract": [
        {
          "text": "Determines whether an OpenGL texture is flipped vertically.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureIsFlipped"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLTextureRef",
          "text": "CVOpenGLTexture"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureIsFlipped(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureIsFlipped"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLTextureIsFlipped(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltextureisflipped(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureRelease": {
      "abstract": [
        {
          "text": "Releases a Core Video OpenGL texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureRelease"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureRelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVOpenGLTextureRelease",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturerelease"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureRetain": {
      "abstract": [
        {
          "text": "Retains a Core Video OpenGL texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVOpenGLTextureRetain"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureRetain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVOpenGLTextureRetain",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltextureretain"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s": {
      "abstract": [
        {
          "text": "An image buffer used to store image data in video memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbuffer-77s"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j": {
      "abstract": [
        {
          "text": "A utility object for managing a set of recyclable OpenGL buffer objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpool-77j"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780": {
      "abstract": [
        {
          "text": "A cache used to create and manage OpenGL texture objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecache-780"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "OpenGL",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j"
      ],
      "title": "OpenGL"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-Textures",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetName(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetTarget(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetCleanTexCoords(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureIsFlipped(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetTypeID()"
      ],
      "title": "Inspecting Textures"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTexture"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-Textures",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetName(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetTarget(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetCleanTexCoords(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureIsFlipped(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureGetTypeID()"
              ],
              "title": "Inspecting Textures"
            },
            {
              "anchor": "Retaining-and-Releasing-Textures",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureRetain",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTextureRelease"
              ],
              "title": "Retaining and Releasing Textures"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLTexture"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "OpenGL",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j"
              ],
              "title": "OpenGL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureIsFlipped(_:)/title",
          "value": "CVOpenGLTextureIsFlipped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureIsFlipped(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureIsFlipped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureGetTypeID()/title",
          "value": "CVOpenGLTextureGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTexture/title",
          "value": "CVOpenGLTextureRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureGetName(_:)/title",
          "value": "CVOpenGLTextureGetName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureGetName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureGetName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureGetCleanTexCoords(_:_:_:_:_:)/title",
          "value": "CVOpenGLTextureGetCleanTexCoords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureGetCleanTexCoords(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureGetCleanTexCoords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureGetTarget(_:)/title",
          "value": "CVOpenGLTextureGetTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLTextureGetTarget(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLTextureGetTarget"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvopengltexture-782"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvopengltexture-782"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
