{
  "abstract": [
    {
      "text": "A utility object for managing a set of recyclable OpenGL buffer objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVOpenGLBufferPool"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPool": {
      "abstract": [
        {
          "text": "A reference to an OpenGL buffer pool object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPool"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpool"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolCreate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new OpenGL buffer pool.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLBufferPoolRef",
          "text": "CVOpenGLBufferPool"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolCreate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolCreate"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferPoolCreate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpoolcreate(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolCreateOpenGLBuffer(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new OpenGL buffer from an OpenGL buffer pool.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolCreateOpenGLBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLBufferPoolRef",
          "text": "CVOpenGLBufferPool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLBufferRef",
          "text": "CVOpenGLBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolCreateOpenGLBuffer(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolCreateOpenGLBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferPoolCreateOpenGLBuffer(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpoolcreateopenglbuffer(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetAttributes(_:)": {
      "abstract": [
        {
          "text": "Returns the pool attributes dictionary for an Open GL buffer pool.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolGetAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLBufferPoolRef",
          "text": "CVOpenGLBufferPool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolGetAttributes"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferPoolGetAttributes(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpoolgetattributes(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetOpenGLBufferAttributes(_:)": {
      "abstract": [
        {
          "text": "Returns the attributes of OpenGL buffers that will be created from a buffer pool.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolGetOpenGLBufferAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLBufferPoolRef",
          "text": "CVOpenGLBufferPool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetOpenGLBufferAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolGetOpenGLBufferAttributes"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferPoolGetOpenGLBufferAttributes(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpoolgetopenglbufferattributes(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetTypeID()": {
      "abstract": [
        {
          "text": "Obtains the Core Foundation ID for the OpenGL buffer pool type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLBufferPoolGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpoolgettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolRelease": {
      "abstract": [
        {
          "text": "Releases an OpenGL buffer pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolRelease"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolRelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVOpenGLBufferPoolRelease",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpoolrelease"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolRetain": {
      "abstract": [
        {
          "text": "Retains an OpenGL buffer pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVOpenGLBufferPoolRetain"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolRetain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVOpenGLBufferPoolRetain",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpoolretain"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s": {
      "abstract": [
        {
          "text": "An image buffer used to store image data in video memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbuffer-77s"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782": {
      "abstract": [
        {
          "text": "A texture-based image buffer that supplies source image data to OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexture-782"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780": {
      "abstract": [
        {
          "text": "A cache used to create and manage OpenGL texture objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecache-780"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferPoolMaximumBufferAgeKey": {
      "abstract": [
        {
          "text": "The maximum time that unused buffers should be kept before they are deallocated (type ",
          "type": "text"
        },
        {
          "code": "CFAbsoluteTime",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferPoolMaximumBufferAgeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferPoolMaximumBufferAgeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferPoolMaximumBufferAgeKey"
        }
      ],
      "role": "symbol",
      "title": "kCVOpenGLBufferPoolMaximumBufferAgeKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvopenglbufferpoolmaximumbufferagekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferPoolMinimumBufferCountKey": {
      "abstract": [
        {
          "text": "The minimum number of buffers to be kept in the pool (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferPoolMinimumBufferCountKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferPoolMinimumBufferCountKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVOpenGLBufferPoolMinimumBufferCountKey"
        }
      ],
      "role": "symbol",
      "title": "kCVOpenGLBufferPoolMinimumBufferCountKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvopenglbufferpoolminimumbuffercountkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536",
      "title": "Core Video Programming Guide",
      "titleInlineContent": [
        {
          "text": "Core Video Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "OpenGL",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s"
      ],
      "title": "OpenGL"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolCreate(_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolCreateOpenGLBuffer(_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetAttributes(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetOpenGLBufferAttributes(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetTypeID()"
      ],
      "title": "Functions"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPool"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferPoolMaximumBufferAgeKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferPoolMinimumBufferCountKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolCreate(_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolCreateOpenGLBuffer(_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetAttributes(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetOpenGLBufferAttributes(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolGetTypeID()",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolRetain",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPoolRelease"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLBufferPool"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferPoolMaximumBufferAgeKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVOpenGLBufferPoolMinimumBufferCountKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "OpenGL",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s"
              ],
              "title": "OpenGL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferPoolMinimumBufferCountKey/title",
          "value": "kCVOpenGLBufferPoolMinimumBufferCountKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferPoolMinimumBufferCountKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVOpenGLBufferPoolMinimumBufferCountKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPoolGetAttributes(_:)/title",
          "value": "CVOpenGLBufferPoolGetAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPoolGetAttributes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferPoolGetAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPoolCreate(_:_:_:_:)/title",
          "value": "CVOpenGLBufferPoolCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPoolCreate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferPoolCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPoolGetOpenGLBufferAttributes(_:)/title",
          "value": "CVOpenGLBufferPoolGetOpenGLBufferAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPoolGetOpenGLBufferAttributes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferPoolGetOpenGLBufferAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPoolCreateOpenGLBuffer(_:_:_:)/title",
          "value": "CVOpenGLBufferPoolCreateOpenGLBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPoolCreateOpenGLBuffer(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferPoolCreateOpenGLBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPool/title",
          "value": "CVOpenGLBufferPoolRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferPoolRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPool/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferPoolRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferPoolMaximumBufferAgeKey/title",
          "value": "kCVOpenGLBufferPoolMaximumBufferAgeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVOpenGLBufferPoolMaximumBufferAgeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVOpenGLBufferPoolMaximumBufferAgeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPoolGetTypeID()/title",
          "value": "CVOpenGLBufferPoolGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLBufferPoolGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLBufferPoolGetTypeID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvopenglbufferpool-77j"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvopenglbufferpool-77j"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
