{
  "abstract": [
    {
      "text": "A cache used to create and manage OpenGL ES texture objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-q2r"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVOpenGLESTextureCache"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Video uses OpenGL ES texture caches to cache and manage ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTexture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " textures. These texture caches provide you with a way to directly read and write buffers with various pixel formats, such as 420v or BGRA, from GL ES.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVEAGLContext": {
      "abstract": [
        {
          "text": "A type that resolves to an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/OpenGLES/EAGLContext",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " pointer when appropriate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVEAGLContext"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVEAGLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVEAGLContext"
        }
      ],
      "role": "symbol",
      "title": "CVEAGLContext",
      "type": "topic",
      "url": "/documentation/corevideo/cveaglcontext"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBuffer": {
      "abstract": [
        {
          "text": "A reference to a Core Video image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVImageBuffer"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVImageBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTexture": {
      "abstract": [
        {
          "text": "A reference to a Core Video texture-based image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTexture"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTexture"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexture"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureCache"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureCache"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturecache"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-cache-attributes": {
      "abstract": [
        {
          "text": "Attributes for the texture cache.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-cache-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cache Attributes",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturecache-cache-attributes"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheCreate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new Core Video texture cache.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureCacheCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVEAGLContext",
          "text": "CVEAGLContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLESTextureCacheRef",
          "text": "CVOpenGLESTextureCache"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheCreate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureCacheCreate"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTextureCacheCreate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturecachecreate(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTexture",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object from an existing ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVImageBuffer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureCacheCreateTextureFromImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLESTextureCacheRef",
          "text": "CVOpenGLESTextureCache"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLenum",
          "text": "GLenum"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLsizei",
          "text": "GLsizei"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLsizei",
          "text": "GLsizei"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLenum",
          "text": "GLenum"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLenum",
          "text": "GLenum"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLESTextureRef",
          "text": "CVOpenGLESTexture"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureCacheCreateTextureFromImage"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturecachecreatetexturefromimage(_:_:_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheFlush(_:_:)": {
      "abstract": [
        {
          "text": "Performs internal housekeeping/recycling operations on a texture cache.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureCacheFlush"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOpenGLESTextureCacheRef",
          "text": "CVOpenGLESTextureCache"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOptionFlags",
          "text": "CVOptionFlags"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheFlush(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureCacheFlush"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTextureCacheFlush(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturecacheflush(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier for a Core Video texture cache.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureCacheGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVOpenGLESTextureCacheGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVOpenGLESTextureCacheGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturecachegettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglestexture-q2s": {
      "abstract": [
        {
          "text": "A texture-based image buffer that supplies source image data to OpenGL ES.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglestexture-q2s",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLESTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexture-q2s"
    },
    "doc://com.apple.documentation/documentation/OpenGLES/EAGLContext": {
      "abstract": [
        {
          "text": "An [`EAGLContext`](doc://com.apple.opengles/documentation/OpenGLES/EAGLContext) object manages an OpenGL ES *rendering context*—the state information, commands, and resources needed to draw using OpenGL ES. To execute OpenGL ES commands, you need a current rendering context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAGLContext"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/OpenGLES/EAGLContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "EAGLContext",
      "type": "topic",
      "url": "/documentation/OpenGLES/EAGLContext"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "OpenGL-ES",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglestexture-q2s"
      ],
      "title": "OpenGL ES"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "The functions in this section operate on Core Video texture caches derived from the ",
          "type": "text"
        },
        {
          "code": "CVOpenGLESTextureCacheRef",
          "type": "codeVoice"
        },
        {
          "text": " type.",
          "type": "text"
        }
      ],
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheCreate(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheFlush(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheGetTypeID()"
      ],
      "title": "Functions"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVEAGLContext"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-cache-attributes"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "The functions in this section operate on Core Video texture caches derived from the ",
                  "type": "text"
                },
                {
                  "code": "CVOpenGLESTextureCacheRef",
                  "type": "codeVoice"
                },
                {
                  "text": " type.",
                  "type": "text"
                }
              ],
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheCreate(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheFlush(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCacheGetTypeID()"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVEAGLContext"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-cache-attributes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "OpenGL-ES",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglestexture-q2s"
              ],
              "title": "OpenGL ES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBuffer/title",
          "value": "CVImageBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVImageBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVImageBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVImageBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureCacheFlush(_:_:)/title",
          "value": "CVOpenGLESTextureCacheFlush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureCacheFlush(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureCacheFlush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureCacheCreate(_:_:_:_:_:)/title",
          "value": "CVOpenGLESTextureCacheCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureCacheCreate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureCacheCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:_:_:_:)/title",
          "value": "CVOpenGLESTextureCacheCreateTextureFromImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureCacheCreateTextureFromImage(_:_:_:_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureCacheCreateTextureFromImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureCache/title",
          "value": "CVOpenGLESTextureCacheRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureCacheRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureCache/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureCacheRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1OpenGLES~1EAGLContext/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EAGLContext"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureCacheGetTypeID()/title",
          "value": "CVOpenGLESTextureCacheGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTextureCacheGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureCacheGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTexture/title",
          "value": "CVOpenGLESTextureRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVOpenGLESTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVOpenGLESTextureRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVEAGLContext/title",
          "value": "CVEAGLContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVEAGLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVEAGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVEAGLContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVEAGLContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvopenglestexturecache-q2r"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvopenglestexturecache-q2r"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
