{
  "abstract": [
    {
      "text": "An image buffer that holds pixels in main memory.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVPixelBuffer"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Core Video pixel buffer is an image buffer that holds pixels in main memory. Applications generating frames, compressing or decompressing video, or using Core Image can all make use of Core Video pixel buffers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBuffer": {
      "abstract": [
        {
          "text": "A reference to a Core Video pixel buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBuffer"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffer"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreate(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a single pixel buffer for a given size and pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreate(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreate"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferCreate(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffercreate(_:_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)": {
      "abstract": [
        {
          "text": "Resolves an array of ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": " objects describing various pixel buffer attributes into a single dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateResolvedAttributesDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateResolvedAttributesDictionary"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffercreateresolvedattributesdictionary(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithBytes(_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a pixel buffer for a given size and pixel format containing data specified by a memory location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateWithBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferReleaseBytesCallback",
          "text": "CVPixelBufferReleaseBytesCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithBytes(_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateWithBytes"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferCreateWithBytes(_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffercreatewithbytes(_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithIOSurface(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a single pixel buffer for the IO surface that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateWithIOSurface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithIOSurface(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateWithIOSurface"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferCreateWithIOSurface(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffercreatewithiosurface(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithPlanarBytes(_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a single pixel buffer in planar format for a given size and pixel format containing data specified by a memory location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateWithPlanarBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferReleasePlanarBytesCallback",
          "text": "CVPixelBufferReleasePlanarBytesCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithPlanarBytes(_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateWithPlanarBytes"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferCreateWithPlanarBytes(_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffercreatewithplanarbytes(_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferFillExtendedPixels(_:)": {
      "abstract": [
        {
          "text": "Fills the extended pixels of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferFillExtendedPixels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferFillExtendedPixels(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferFillExtendedPixels"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferFillExtendedPixels(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferfillextendedpixels(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddress(_:)": {
      "abstract": [
        {
          "text": "Returns the base address of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBaseAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddress(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBaseAddress"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetBaseAddress(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetbaseaddress(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddressOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the base address of the plane at the specified plane index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBaseAddressOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddressOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBaseAddressOfPlane"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetBaseAddressOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetbaseaddressofplane(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRow(_:)": {
      "abstract": [
        {
          "text": "Returns the number of bytes per row of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBytesPerRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBytesPerRow"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetBytesPerRow(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetbytesperrow(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRowOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the number of bytes per row for a plane at the specified index in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBytesPerRowOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRowOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBytesPerRowOfPlane"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetBytesPerRowOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetbytesperrowofplane(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetDataSize(_:)": {
      "abstract": [
        {
          "text": "Returns the data size for contiguous planes of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetDataSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetDataSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetDataSize"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetDataSize(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetdatasize(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetExtendedPixels(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the amount of extended pixel padding in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetExtendedPixels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetExtendedPixels(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetExtendedPixels"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetExtendedPixels(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetextendedpixels(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeight(_:)": {
      "abstract": [
        {
          "text": "Returns the height of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetHeight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeight(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetHeight"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetHeight(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetheight(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeightOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the height of the plane at planeIndex in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetHeightOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeightOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetHeightOfPlane"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetHeightOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetheightofplane(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetIOSurface(_:)": {
      "abstract": [
        {
          "text": "Returns the IOSurface backing the pixel buffer, or ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": " if it is not backed by an IOSurface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetIOSurface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetIOSurface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetIOSurface"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetIOSurface(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetiosurface(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPixelFormatType(_:)": {
      "abstract": [
        {
          "text": "Returns the pixel format type of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetPixelFormatType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPixelFormatType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetPixelFormatType"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetPixelFormatType(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetpixelformattype(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPlaneCount(_:)": {
      "abstract": [
        {
          "text": "Returns number of planes of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetPlaneCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPlaneCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetPlaneCount"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetPlaneCount(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetplanecount(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier of the pixel buffer type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidth(_:)": {
      "abstract": [
        {
          "text": "Returns the width of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetWidth"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidth(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetWidth"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetWidth(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetwidth(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidthOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the width of the plane at a given index in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetWidthOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidthOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetWidthOfPlane"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetWidthOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetwidthofplane(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferIsPlanar(_:)": {
      "abstract": [
        {
          "text": "Determines whether the pixel buffer is planar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferIsPlanar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferIsPlanar(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferIsPlanar"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferIsPlanar(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferisplanar(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferLockBaseAddress(_:_:)": {
      "abstract": [
        {
          "text": "Locks the base address of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferLockBaseAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVPixelBufferLockFlags",
          "text": "CVPixelBufferLockFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferLockBaseAddress(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferLockBaseAddress"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferLockBaseAddress(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferlockbaseaddress(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferLockFlags": {
      "abstract": [
        {
          "text": "The flags to pass to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferLockBaseAddress(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferUnlockBaseAddress(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferLockFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferLockFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferLockFlags"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferLockFlags",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferlockflags"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o": {
      "abstract": [
        {
          "text": "A utility object for managing a recyclable set of pixel buffer objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpool-77o"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferRelease": {
      "abstract": [
        {
          "text": "Releases a pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferRelease"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferRelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVPixelBufferRelease",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferrelease"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferReleaseBytesCallback": {
      "abstract": [
        {
          "text": "A type that defines a release callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferReleaseBytesCallback"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferReleaseBytesCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferReleaseBytesCallback"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferReleaseBytesCallback",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferreleasebytescallback"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferReleasePlanarBytesCallback": {
      "abstract": [
        {
          "text": "Defines a pointer to a pixel buffer release callback function, which is called when a pixel buffer created by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithPlanarBytes(_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is released.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferReleasePlanarBytesCallback"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferReleasePlanarBytesCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferReleasePlanarBytesCallback"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferReleasePlanarBytesCallback",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferreleaseplanarbytescallback"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferRetain": {
      "abstract": [
        {
          "text": "Retains a pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferRetain"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferRetain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVPixelBufferRetain",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferretain"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferUnlockBaseAddress(_:_:)": {
      "abstract": [
        {
          "text": "Unlocks the base address of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferUnlockBaseAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVPixelBufferLockFlags",
          "text": "CVPixelBufferLockFlags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferUnlockBaseAddress(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferUnlockBaseAddress"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferUnlockBaseAddress(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferunlockbaseaddress(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo": {
      "abstract": [
        {
          "text": "A structure for describing planar components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPlanarComponentInfo"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPlanarComponentInfo"
        }
      ],
      "role": "symbol",
      "title": "CVPlanarComponentInfo",
      "type": "topic",
      "url": "/documentation/corevideo/cvplanarcomponentinfo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo": {
      "abstract": [
        {
          "text": "A structure for describing planar buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPlanarPixelBufferInfo"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPlanarPixelBufferInfo"
        }
      ],
      "role": "symbol",
      "title": "CVPlanarPixelBufferInfo",
      "type": "topic",
      "url": "/documentation/corevideo/cvplanarpixelbufferinfo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrBiPlanar": {
      "abstract": [
        {
          "text": "A structure for describing YCbCr biplanar buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPlanarPixelBufferInfo_YCbCrBiPlanar"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrBiPlanar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPlanarPixelBufferInfo_YCbCrBiPlanar"
        }
      ],
      "role": "symbol",
      "title": "CVPlanarPixelBufferInfo_YCbCrBiPlanar",
      "type": "topic",
      "url": "/documentation/corevideo/cvplanarpixelbufferinfo_ycbcrbiplanar"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar": {
      "abstract": [
        {
          "text": "A structure for describing YCbCr planar buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPlanarPixelBufferInfo_YCbCrPlanar"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPlanarPixelBufferInfo_YCbCrPlanar"
        }
      ],
      "role": "symbol",
      "title": "CVPlanarPixelBufferInfo_YCbCrPlanar",
      "type": "topic",
      "url": "/documentation/corevideo/cvplanarpixelbufferinfo_ycbcrplanar"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm": {
      "abstract": [
        {
          "text": "An abstract base class that defines how to interact with data buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer-nfm"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40": {
      "abstract": [
        {
          "text": "An interface for managing different types of image data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer-q40"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription": {
      "abstract": [
        {
          "text": "An API that provides functions and types for defining custom pixel formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelFormatDescription",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelformatdescription"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/pixel-buffer-attribute-keys": {
      "abstract": [
        {
          "text": "The attributes associated with a pixel buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/pixel-buffer-attribute-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Buffer Attribute Keys",
      "type": "topic",
      "url": "/documentation/corevideo/pixel-buffer-attribute-keys"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536",
      "title": "Core Video Programming Guide",
      "titleInlineContent": [
        {
          "text": "Core Video Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Data-Processing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
      ],
      "title": "Data Processing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-pixel-buffers",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreate(_:_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithBytes(_:_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithPlanarBytes(_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithIOSurface(_:_:_:_:)"
      ],
      "title": "Creating pixel buffers"
    },
    {
      "anchor": "Inspecting-Pixel-Buffers",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddress(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddressOfPlane(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRow(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRowOfPlane(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeight(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeightOfPlane(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidth(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidthOfPlane(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferIsPlanar(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPlaneCount(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetDataSize(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPixelFormatType(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetExtendedPixels(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetIOSurface(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetTypeID()"
      ],
      "title": "Inspecting Pixel Buffers"
    },
    {
      "anchor": "Modifying-Pixel-Buffers",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferFillExtendedPixels(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferLockBaseAddress(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferUnlockBaseAddress(_:_:)"
      ],
      "title": "Modifying Pixel Buffers"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBuffer",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferLockFlags",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrBiPlanar"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Callbacks",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferReleaseBytesCallback",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferReleasePlanarBytesCallback"
      ],
      "title": "Callbacks"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/pixel-buffer-attribute-keys"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-pixel-buffers",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreate(_:_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithBytes(_:_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithPlanarBytes(_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateWithIOSurface(_:_:_:_:)"
              ],
              "title": "Creating pixel buffers"
            },
            {
              "anchor": "Inspecting-Pixel-Buffers",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddress(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddressOfPlane(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRow(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRowOfPlane(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeight(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeightOfPlane(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidth(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidthOfPlane(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferIsPlanar(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPlaneCount(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetDataSize(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPixelFormatType(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetExtendedPixels(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetIOSurface(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetTypeID()"
              ],
              "title": "Inspecting Pixel Buffers"
            },
            {
              "anchor": "Modifying-Pixel-Buffers",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferFillExtendedPixels(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferLockBaseAddress(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferUnlockBaseAddress(_:_:)"
              ],
              "title": "Modifying Pixel Buffers"
            },
            {
              "anchor": "Retaining-and-Releasing-Pixel-Buffers",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferRetain",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferRelease"
              ],
              "title": "Retaining and Releasing Pixel Buffers"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBuffer",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferLockFlags",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrBiPlanar"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Callbacks",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferReleaseBytesCallback",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferReleasePlanarBytesCallback"
              ],
              "title": "Callbacks"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/pixel-buffer-attribute-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Data-Processing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
              ],
              "title": "Data Processing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetWidthOfPlane(_:_:)/title",
          "value": "CVPixelBufferGetWidthOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetWidthOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetWidthOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrBiPlanar/title",
          "value": "CVPlanarPixelBufferInfo_YCbCrBiPlanar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrBiPlanar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarPixelBufferInfo_YCbCrBiPlanar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrBiPlanar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarPixelBufferInfo_YCbCrBiPlanar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetIOSurface(_:)/title",
          "value": "CVPixelBufferGetIOSurface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetIOSurface(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetIOSurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetHeightOfPlane(_:_:)/title",
          "value": "CVPixelBufferGetHeightOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetHeightOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetHeightOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferUnlockBaseAddress(_:_:)/title",
          "value": "CVPixelBufferUnlockBaseAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferUnlockBaseAddress(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferUnlockBaseAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBytesPerRowOfPlane(_:_:)/title",
          "value": "CVPixelBufferGetBytesPerRowOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBytesPerRowOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetBytesPerRowOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBaseAddressOfPlane(_:_:)/title",
          "value": "CVPixelBufferGetBaseAddressOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBaseAddressOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetBaseAddressOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetHeight(_:)/title",
          "value": "CVPixelBufferGetHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetHeight(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBaseAddress(_:)/title",
          "value": "CVPixelBufferGetBaseAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBaseAddress(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetBaseAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetWidth(_:)/title",
          "value": "CVPixelBufferGetWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetWidth(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetExtendedPixels(_:_:_:_:_:)/title",
          "value": "CVPixelBufferGetExtendedPixels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetExtendedPixels(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetExtendedPixels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferFillExtendedPixels(_:)/title",
          "value": "CVPixelBufferFillExtendedPixels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferFillExtendedPixels(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferFillExtendedPixels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateWithBytes(_:_:_:_:_:_:_:_:_:_:)/title",
          "value": "CVPixelBufferCreateWithBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateWithBytes(_:_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferCreateWithBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar/title",
          "value": "CVPlanarPixelBufferInfo_YCbCrPlanar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarPixelBufferInfo_YCbCrPlanar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarPixelBufferInfo_YCbCrPlanar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateWithPlanarBytes(_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:)/title",
          "value": "CVPixelBufferCreateWithPlanarBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateWithPlanarBytes(_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferCreateWithPlanarBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferLockFlags/title",
          "value": "CVPixelBufferLockFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferLockFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferLockFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferLockFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferLockFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferReleaseBytesCallback/title",
          "value": "CVPixelBufferReleaseBytesCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferReleaseBytesCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferReleaseBytesCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferReleaseBytesCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferReleaseBytesCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBuffer/title",
          "value": "CVPixelBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferLockBaseAddress(_:_:)/title",
          "value": "CVPixelBufferLockBaseAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferLockBaseAddress(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferLockBaseAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferIsPlanar(_:)/title",
          "value": "CVPixelBufferIsPlanar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferIsPlanar(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferIsPlanar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferReleasePlanarBytesCallback/title",
          "value": "CVPixelBufferReleasePlanarBytesCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferReleasePlanarBytesCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferReleasePlanarBytesCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferReleasePlanarBytesCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferReleasePlanarBytesCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBytesPerRow(_:)/title",
          "value": "CVPixelBufferGetBytesPerRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBytesPerRow(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetBytesPerRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreate(_:_:_:_:_:_:)/title",
          "value": "CVPixelBufferCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreate(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetPlaneCount(_:)/title",
          "value": "CVPixelBufferGetPlaneCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetPlaneCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetPlaneCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo/title",
          "value": "CVPlanarPixelBufferInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarPixelBufferInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarPixelBufferInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateWithIOSurface(_:_:_:_:)/title",
          "value": "CVPixelBufferCreateWithIOSurface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateWithIOSurface(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferCreateWithIOSurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarComponentInfo/title",
          "value": "CVPlanarComponentInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarComponentInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarComponentInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarComponentInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarComponentInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)/title",
          "value": "CVPixelBufferCreateResolvedAttributesDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferCreateResolvedAttributesDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetDataSize(_:)/title",
          "value": "CVPixelBufferGetDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetDataSize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetTypeID()/title",
          "value": "CVPixelBufferGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetPixelFormatType(_:)/title",
          "value": "CVPixelBufferGetPixelFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetPixelFormatType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetPixelFormatType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvpixelbuffer-q2e"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvpixelbuffer-q2e"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
