{
  "abstract": [
    {
      "text": "A utility object for managing a recyclable set of pixel buffer objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVPixelBufferPool"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool": {
      "abstract": [
        {
          "text": "A reference to a pixel buffer pool object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPool"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpool"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a pixel buffer pool using the allocator and attributes that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferPoolRef",
          "text": "CVPixelBufferPool"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreate"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPoolCreate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolcreate(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBuffer(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a pixel buffer from a pixel buffer pool, using the allocator that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreatePixelBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferPoolRef",
          "text": "CVPixelBufferPool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBuffer(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreatePixelBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPoolCreatePixelBuffer(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolcreatepixelbuffer(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new pixel buffer with auxiliary attributes from the pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferPoolRef",
          "text": "CVPixelBufferPool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolcreatepixelbufferwithauxattributes(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolFlush(_:_:)": {
      "abstract": [
        {
          "text": "Frees pixel buffers from the pool based on the options that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolFlush"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferPoolRef",
          "text": "CVPixelBufferPool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVPixelBufferPoolFlushFlags",
          "text": "CVPixelBufferPoolFlushFlags"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolFlush(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolFlush"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPoolFlush(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolflush(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolFlushFlags": {
      "abstract": [
        {
          "text": "The flags to pass to flush the pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolFlushFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolFlushFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolFlushFlags"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPoolFlushFlags",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolflushflags"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetAttributes(_:)": {
      "abstract": [
        {
          "text": "The pool attributes dictionary for a pixel buffer pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolGetAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferPoolRef",
          "text": "CVPixelBufferPool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolGetAttributes"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPoolGetAttributes(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolgetattributes(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetPixelBufferAttributes(_:)": {
      "abstract": [
        {
          "text": "The attributes of pixel buffers which the system creates using the pool you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolGetPixelBufferAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferPoolRef",
          "text": "CVPixelBufferPool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetPixelBufferAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolGetPixelBufferAttributes"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPoolGetPixelBufferAttributes(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolgetpixelbufferattributes(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier of the pixel buffer pool type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPoolGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolgettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRelease": {
      "abstract": [
        {
          "text": "Releases a pixel buffer pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolRelease"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVPixelBufferPoolRelease",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolrelease"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRetain": {
      "abstract": [
        {
          "text": "Retains the pixel buffer pool that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolRetain"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRetain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVPixelBufferPoolRetain",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolretain"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm": {
      "abstract": [
        {
          "text": "An abstract base class that defines how to interact with data buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer-nfm"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40": {
      "abstract": [
        {
          "text": "An interface for managing different types of image data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer-q40"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e": {
      "abstract": [
        {
          "text": "An image buffer that holds pixels in main memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffer-q2e"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription": {
      "abstract": [
        {
          "text": "An API that provides functions and types for defining custom pixel formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelFormatDescription",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelformatdescription"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolAllocationThresholdKey": {
      "abstract": [
        {
          "text": "The key you use to set the auxiliary attributes dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolAllocationThresholdKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolAllocationThresholdKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolAllocationThresholdKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPoolAllocationThresholdKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferpoolallocationthresholdkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolFreeBufferNotification": {
      "abstract": [
        {
          "text": "A notification that the system posts if a buffer becomes available after it fails to create a pixel buffer with auxiliary attributes because it exceeded the threshold you specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolFreeBufferNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolFreeBufferNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolFreeBufferNotification"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPoolFreeBufferNotification",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferpoolfreebuffernotification"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMaximumBufferAgeKey": {
      "abstract": [
        {
          "text": "The key you use to set the maximum allowable age for a buffer in the pixel buffer pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolMaximumBufferAgeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMaximumBufferAgeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolMaximumBufferAgeKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPoolMaximumBufferAgeKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferpoolmaximumbufferagekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMinimumBufferCountKey": {
      "abstract": [
        {
          "text": "The minimum number of buffers allowed in the pixel buffer pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolMinimumBufferCountKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMinimumBufferCountKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolMinimumBufferCountKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPoolMinimumBufferCountKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferpoolminimumbuffercountkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536",
      "title": "Core Video Programming Guide",
      "titleInlineContent": [
        {
          "text": "Core Video Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Data-Processing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
      ],
      "title": "Data Processing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-pools",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreate(_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBuffer(_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)"
      ],
      "title": "Creating pools"
    },
    {
      "anchor": "Flushing-pools",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolFlush(_:_:)"
      ],
      "title": "Flushing pools"
    },
    {
      "anchor": "Inspecting-pools",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetAttributes(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetPixelBufferAttributes(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetTypeID()"
      ],
      "title": "Inspecting pools"
    },
    {
      "anchor": "Data-types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolFlushFlags"
      ],
      "title": "Data types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMinimumBufferCountKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMaximumBufferAgeKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolAllocationThresholdKey"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Notifications",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolFreeBufferNotification"
      ],
      "title": "Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-pools",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreate(_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBuffer(_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)"
              ],
              "title": "Creating pools"
            },
            {
              "anchor": "Flushing-pools",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolFlush(_:_:)"
              ],
              "title": "Flushing pools"
            },
            {
              "anchor": "Inspecting-pools",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetAttributes(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetPixelBufferAttributes(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolGetTypeID()"
              ],
              "title": "Inspecting pools"
            },
            {
              "anchor": "Retaining-and-releasing-pools",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRetain",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRelease"
              ],
              "title": "Retaining and releasing pools"
            },
            {
              "anchor": "Data-types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolFlushFlags"
              ],
              "title": "Data types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMinimumBufferCountKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMaximumBufferAgeKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolAllocationThresholdKey"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Notifications",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolFreeBufferNotification"
              ],
              "title": "Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Data-Processing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
              ],
              "title": "Data Processing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPool/title",
          "value": "CVPixelBufferPoolRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPool/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolGetTypeID()/title",
          "value": "CVPixelBufferPoolGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolAllocationThresholdKey/title",
          "value": "kCVPixelBufferPoolAllocationThresholdKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolAllocationThresholdKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPoolAllocationThresholdKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolMinimumBufferCountKey/title",
          "value": "kCVPixelBufferPoolMinimumBufferCountKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolMinimumBufferCountKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPoolMinimumBufferCountKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)/title",
          "value": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolFlushFlags/title",
          "value": "CVPixelBufferPoolFlushFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolFlushFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolFlushFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolFlushFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolFlushFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolFlush(_:_:)/title",
          "value": "CVPixelBufferPoolFlush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolFlush(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolFlush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolGetAttributes(_:)/title",
          "value": "CVPixelBufferPoolGetAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolGetAttributes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolGetAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolGetPixelBufferAttributes(_:)/title",
          "value": "CVPixelBufferPoolGetPixelBufferAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolGetPixelBufferAttributes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolGetPixelBufferAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolMaximumBufferAgeKey/title",
          "value": "kCVPixelBufferPoolMaximumBufferAgeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolMaximumBufferAgeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPoolMaximumBufferAgeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreate(_:_:_:_:)/title",
          "value": "CVPixelBufferPoolCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreatePixelBuffer(_:_:_:)/title",
          "value": "CVPixelBufferPoolCreatePixelBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreatePixelBuffer(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolCreatePixelBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolFreeBufferNotification/title",
          "value": "kCVPixelBufferPoolFreeBufferNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolFreeBufferNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPoolFreeBufferNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvpixelbufferpool-77o"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvpixelbufferpool-77o"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
