{
  "abstract": [
    {
      "text": "Resolves an array of ",
      "type": "text"
    },
    {
      "code": "CFDictionary",
      "type": "codeVoice"
    },
    {
      "text": " objects describing various pixel buffer attributes into a single dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CVPixelBufferCreateResolvedAttributesDictionary",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CVPixelBufferCreateResolvedAttributesDictionary"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFAllocatorRef",
        "text": "CFAllocator"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFDictionaryRef",
        "text": "CFDictionary"
      },
      {
        "kind": "text",
        "text": "?>) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CVReturn",
        "text": "CVReturn"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CVPixelBufferCreateResolvedAttributesDictionary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVPixelBufferCreateResolvedAttributesDictionary"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "allocator"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocator"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attributes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "resolvedDictionaryOut"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": "?>) -> "
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVReturn",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVReturn",
              "text": "CVReturn"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The allocator to use to create the pixel buffer. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to specify the default allocator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allocator"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of Core Foundation dictionaries containing pixel buffer attribute key-value pairs.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "attributes"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On output, the consolidated dictionary. Ownership follows the ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "resolvedDictionaryOut"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Core Video result code. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for possible values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This call is useful when you need to resolve requirements between several potential clients of a buffer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If two or more dictionaries contain the same key but different values, this function adjusts values where possible so that the output dictionary contains a mutually compatible set of values. For example, if the ",
              "type": "text"
            },
            {
              "code": "attributes",
              "type": "codeVoice"
            },
            {
              "text": " parameter contains dictionaries whose bytes-per-row attributes differ, the ",
              "type": "text"
            },
            {
              "code": "rowBytes",
              "type": "codeVoice"
            },
            {
              "text": " value in the output dictionary is the least common multiple of the input values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Some mismatched attributes cannot be resolved. Calling this function results in an error if the widths, heights, pixel format allocators, or callbacks in the input dictionaries do not match.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)": {
      "abstract": [
        {
          "text": "Resolves an array of ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": " objects describing various pixel buffer attributes into a single dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateResolvedAttributesDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateResolvedAttributesDictionary"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffercreateresolvedattributesdictionary(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddress(_:)": {
      "abstract": [
        {
          "text": "Returns the base address of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBaseAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddress(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBaseAddress"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetBaseAddress(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetbaseaddress(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddressOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the base address of the plane at the specified plane index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBaseAddressOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddressOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBaseAddressOfPlane"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetBaseAddressOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetbaseaddressofplane(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRow(_:)": {
      "abstract": [
        {
          "text": "Returns the number of bytes per row of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBytesPerRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBytesPerRow"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetBytesPerRow(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetbytesperrow(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRowOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the number of bytes per row for a plane at the specified index in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBytesPerRowOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRowOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetBytesPerRowOfPlane"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetBytesPerRowOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetbytesperrowofplane(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetDataSize(_:)": {
      "abstract": [
        {
          "text": "Returns the data size for contiguous planes of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetDataSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetDataSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetDataSize"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetDataSize(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetdatasize(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetExtendedPixels(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the amount of extended pixel padding in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetExtendedPixels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetExtendedPixels(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetExtendedPixels"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetExtendedPixels(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetextendedpixels(_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeight(_:)": {
      "abstract": [
        {
          "text": "Returns the height of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetHeight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeight(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetHeight"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetHeight(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetheight(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeightOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the height of the plane at planeIndex in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetHeightOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeightOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetHeightOfPlane"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetHeightOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetheightofplane(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetIOSurface(_:)": {
      "abstract": [
        {
          "text": "Returns the IOSurface backing the pixel buffer, or ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": " if it is not backed by an IOSurface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetIOSurface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetIOSurface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetIOSurface"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetIOSurface(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetiosurface(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPixelFormatType(_:)": {
      "abstract": [
        {
          "text": "Returns the pixel format type of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetPixelFormatType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPixelFormatType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetPixelFormatType"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetPixelFormatType(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetpixelformattype(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPlaneCount(_:)": {
      "abstract": [
        {
          "text": "Returns number of planes of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetPlaneCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPlaneCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetPlaneCount"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetPlaneCount(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetplanecount(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier of the pixel buffer type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidth(_:)": {
      "abstract": [
        {
          "text": "Returns the width of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetWidth"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidth(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetWidth"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetWidth(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetwidth(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidthOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the width of the plane at a given index in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetWidthOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidthOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferGetWidthOfPlane"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferGetWidthOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffergetwidthofplane(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferIsPlanar(_:)": {
      "abstract": [
        {
          "text": "Determines whether the pixel buffer is planar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferIsPlanar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferIsPlanar(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferIsPlanar"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferIsPlanar(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferisplanar(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVReturn": {
      "abstract": [
        {
          "text": "A Core Video error type return value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVReturn"
        }
      ],
      "role": "symbol",
      "title": "CVReturn",
      "type": "topic",
      "url": "/documentation/corevideo/cvreturn"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Constants",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029": {
      "identifier": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029",
      "title": "The Create Rule",
      "titleInlineContent": [
        {
          "text": "The Create Rule",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Pixel-Buffers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddress(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddressOfPlane(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRow(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRowOfPlane(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeight(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeightOfPlane(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidth(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidthOfPlane(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferIsPlanar(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPlaneCount(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetDataSize(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPixelFormatType(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetExtendedPixels(_:_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetIOSurface(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetTypeID()"
      ],
      "title": "Inspecting Pixel Buffers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CVPixelBufferCreateResolvedAttributesDictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferCreateResolvedAttributesDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-Pixel-Buffers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddress(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBaseAddressOfPlane(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRow(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetBytesPerRowOfPlane(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeight(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetHeightOfPlane(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidth(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetWidthOfPlane(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferIsPlanar(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPlaneCount(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetDataSize(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetPixelFormatType(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetExtendedPixels(_:_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetIOSurface(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferGetTypeID()"
              ],
              "title": "Inspecting Pixel Buffers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVReturn",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CVReturn",
                    "text": "CVReturn"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CVPixelBufferCreateResolvedAttributesDictionary"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFAllocatorRef",
                    "text": "CFAllocatorRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "allocator"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "attributes"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFDictionaryRef",
                    "text": "CFDictionaryRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "resolvedDictionaryOut"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The allocator to use to create the pixel buffer. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to specify the default allocator.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "allocator"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of Core Foundation dictionaries containing pixel buffer attribute key-value pairs.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "attributes"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On output, the consolidated dictionary. Ownership follows the ",
                        "type": "text"
                      },
                      {
                        "identifier": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "resolvedDictionaryOut"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A Core Video result code. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " for possible values.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetHeight(_:)/title",
          "value": "CVPixelBufferGetHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetHeight(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetDataSize(_:)/title",
          "value": "CVPixelBufferGetDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetDataSize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetExtendedPixels(_:_:_:_:_:)/title",
          "value": "CVPixelBufferGetExtendedPixels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetExtendedPixels(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetExtendedPixels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferIsPlanar(_:)/title",
          "value": "CVPixelBufferIsPlanar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferIsPlanar(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferIsPlanar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBytesPerRow(_:)/title",
          "value": "CVPixelBufferGetBytesPerRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBytesPerRow(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetBytesPerRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetTypeID()/title",
          "value": "CVPixelBufferGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetPixelFormatType(_:)/title",
          "value": "CVPixelBufferGetPixelFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetPixelFormatType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetPixelFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetWidth(_:)/title",
          "value": "CVPixelBufferGetWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetWidth(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetIOSurface(_:)/title",
          "value": "CVPixelBufferGetIOSurface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetIOSurface(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetIOSurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBytesPerRowOfPlane(_:_:)/title",
          "value": "CVPixelBufferGetBytesPerRowOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBytesPerRowOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetBytesPerRowOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVReturn/title",
          "value": "CVReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVReturn/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)/title",
          "value": "CVPixelBufferCreateResolvedAttributesDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferCreateResolvedAttributesDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetPlaneCount(_:)/title",
          "value": "CVPixelBufferGetPlaneCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetPlaneCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetPlaneCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBaseAddressOfPlane(_:_:)/title",
          "value": "CVPixelBufferGetBaseAddressOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBaseAddressOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetBaseAddressOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBaseAddress(_:)/title",
          "value": "CVPixelBufferGetBaseAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetBaseAddress(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetBaseAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetHeightOfPlane(_:_:)/title",
          "value": "CVPixelBufferGetHeightOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetHeightOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetHeightOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetWidthOfPlane(_:_:)/title",
          "value": "CVPixelBufferGetWidthOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferGetWidthOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferGetWidthOfPlane"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvpixelbuffercreateresolvedattributesdictionary(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvpixelbuffercreateresolvedattributesdictionary(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
