{
  "abstract": [
    {
      "text": "Retains the pixel buffer pool that you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRetain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CVPixelBufferPoolRetain",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CVPixelBufferPoolRetain"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CVPixelBufferPoolRetain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CVPixelBufferPoolRetain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVPixelBufferPoolRef",
              "text": "CVPixelBufferPoolRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolRetain"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVPixelBufferPoolRef",
              "text": "CVPixelBufferPoolRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pixelBufferPool"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The same pixel buffer pool that you specified.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is equivalent to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521269-cfretain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", except it’s ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " safe.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool": {
      "abstract": [
        {
          "text": "A reference to a pixel buffer pool object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPool"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpool"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRelease": {
      "abstract": [
        {
          "text": "Releases a pixel buffer pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolRelease"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVPixelBufferPoolRelease",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolrelease"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRetain": {
      "abstract": [
        {
          "text": "Retains the pixel buffer pool that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolRetain"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRetain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVPixelBufferPoolRetain",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolretain"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1521269-cfretain": {
      "abstract": [
        {
          "text": "Retains a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521269-cfretain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRetain",
      "type": "topic",
      "url": "/documentation/corefoundation/1521269-cfretain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retaining-and-releasing-pools",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolRelease"
      ],
      "title": "Retaining and releasing pools"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPool/title",
          "value": "CVPixelBufferPoolRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPool/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvpixelbufferpoolretain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
