{
  "abstract": [
    {
      "text": "An API that provides functions and types for defining custom pixel formats.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVPixelFormatDescription"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Core Video pixel format description API defines functions and types for defining custom pixel formats. You should only use pixel format descriptions if you need to define a custom pixel format.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBack": {
      "abstract": [
        {
          "text": "Defines a pointer to a custom extended pixel-fill function, which is called whenever the system needs to pad a buffer holding your custom pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVFillExtendedPixelsCallBack"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVFillExtendedPixelsCallBack"
        }
      ],
      "role": "symbol",
      "title": "CVFillExtendedPixelsCallBack",
      "type": "topic",
      "url": "/documentation/corevideo/cvfillextendedpixelscallback"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData": {
      "abstract": [
        {
          "text": "A structure for holding information that describes a custom extended pixel fill algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVFillExtendedPixelsCallBackData"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVFillExtendedPixelsCallBackData"
        }
      ],
      "role": "symbol",
      "title": "CVFillExtendedPixelsCallBackData",
      "type": "topic",
      "url": "/documentation/corevideo/cvfillextendedpixelscallbackdata"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o": {
      "abstract": [
        {
          "text": "A utility object for managing a recyclable set of pixel buffer objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpool-77o"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes(_:)": {
      "abstract": [
        {
          "text": "Returns all the pixel format descriptions known to Core Video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes"
        }
      ],
      "role": "symbol",
      "title": "CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelformatdescriptionarraycreatewithallpixelformattypes(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionCreateWithPixelFormatType(_:_:)": {
      "abstract": [
        {
          "text": "Creates a pixel format description from a given ",
          "type": "text"
        },
        {
          "code": "OSType",
          "type": "codeVoice"
        },
        {
          "text": " identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelFormatDescriptionCreateWithPixelFormatType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionCreateWithPixelFormatType(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelFormatDescriptionCreateWithPixelFormatType"
        }
      ],
      "role": "symbol",
      "title": "CVPixelFormatDescriptionCreateWithPixelFormatType(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelformatdescriptioncreatewithpixelformattype(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType(_:_:)": {
      "abstract": [
        {
          "text": "Registers a pixel format description with Core Video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType"
        }
      ],
      "role": "symbol",
      "title": "CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelformatdescriptionregisterdescriptionwithpixelformattype(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm": {
      "abstract": [
        {
          "text": "An abstract base class that defines how to interact with data buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer-nfm"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40": {
      "abstract": [
        {
          "text": "An interface for managing different types of image data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer-q40"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e": {
      "abstract": [
        {
          "text": "An image buffer that holds pixels in main memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffer-q2e"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-description-keys": {
      "abstract": [
        {
          "text": "The attributes of a pixel format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-description-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Format Description Keys",
      "type": "topic",
      "url": "/documentation/corevideo/pixel-format-description-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-identifiers": {
      "abstract": [
        {
          "text": "Core Video does not provide support for all of these formats; this list defines only their names.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Format Identifiers",
      "type": "topic",
      "url": "/documentation/corevideo/pixel-format-identifiers"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Processing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o"
      ],
      "title": "Data Processing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Format-Descriptions",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionCreateWithPixelFormatType(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType(_:_:)"
      ],
      "title": "Creating Format Descriptions"
    },
    {
      "anchor": "Retrieving-Format-Descriptions",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes(_:)"
      ],
      "title": "Retrieving Format Descriptions"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Callbacks",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBack"
      ],
      "title": "Callbacks"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-description-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-identifiers"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Format-Descriptions",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionCreateWithPixelFormatType(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType(_:_:)"
              ],
              "title": "Creating Format Descriptions"
            },
            {
              "anchor": "Retrieving-Format-Descriptions",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes(_:)"
              ],
              "title": "Retrieving Format Descriptions"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Callbacks",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBack"
              ],
              "title": "Callbacks"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-description-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Processing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o"
              ],
              "title": "Data Processing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType(_:_:)/title",
          "value": "CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelFormatDescriptionRegisterDescriptionWithPixelFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelFormatDescriptionCreateWithPixelFormatType(_:_:)/title",
          "value": "CVPixelFormatDescriptionCreateWithPixelFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelFormatDescriptionCreateWithPixelFormatType(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelFormatDescriptionCreateWithPixelFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBack/title",
          "value": "CVFillExtendedPixelsCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes(_:)/title",
          "value": "CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelFormatDescriptionArrayCreateWithAllPixelFormatTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData/title",
          "value": "CVFillExtendedPixelsCallBackData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBackData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBackData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvpixelformatdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvpixelformatdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
