{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CVTimeStampFlags",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CVTimeStampFlags"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CVTimeStampFlags"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CVTimeStampFlags"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVTimeStampFlags"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVSMPTETimeFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVSMPTETimeFlags"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeFlags",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimeflags"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVSMPTETimeType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVSMPTETimeType"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeType",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimetype"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTimeFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTimeFlags"
        }
      ],
      "role": "symbol",
      "title": "CVTimeFlags",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimeflags"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTimeStampFlags"
        }
      ],
      "role": "symbol",
      "title": "CVTimeStampFlags",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/bottomField": {
      "abstract": [
        {
          "text": "The timestamp represents the bottom lines of an interlaced image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomField"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVTimeStampFlags",
          "text": "CVTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/bottomField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVTimeStampBottomField"
        }
      ],
      "role": "symbol",
      "title": "bottomField",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags/bottomfield"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/hostTimeValid": {
      "abstract": [
        {
          "text": "The value in the host time field is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostTimeValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVTimeStampFlags",
          "text": "CVTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/hostTimeValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVTimeStampHostTimeValid"
        }
      ],
      "role": "symbol",
      "title": "hostTimeValid",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags/hosttimevalid"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags/init(rawvalue:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/isInterlaced": {
      "abstract": [
        {
          "text": "A convenience constant indicating that the timestamp is for an interlaced image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInterlaced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVTimeStampFlags",
          "text": "CVTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/isInterlaced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVTimeStampIsInterlaced"
        }
      ],
      "role": "symbol",
      "title": "isInterlaced",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags/isinterlaced"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/rateScalarValid": {
      "abstract": [
        {
          "text": "The value in the rate scalar field is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rateScalarValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVTimeStampFlags",
          "text": "CVTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/rateScalarValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVTimeStampRateScalarValid"
        }
      ],
      "role": "symbol",
      "title": "rateScalarValid",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags/ratescalarvalid"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/smpteTimeValid": {
      "abstract": [
        {
          "text": "The value in the SMPTE time field is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smpteTimeValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVTimeStampFlags",
          "text": "CVTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/smpteTimeValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVTimeStampSMPTETimeValid"
        }
      ],
      "role": "symbol",
      "title": "smpteTimeValid",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags/smptetimevalid"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/topField": {
      "abstract": [
        {
          "text": "The timestamp represents the top lines of an interlaced image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topField"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVTimeStampFlags",
          "text": "CVTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/topField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVTimeStampTopField"
        }
      ],
      "role": "symbol",
      "title": "topField",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags/topfield"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoHostTimeValid": {
      "abstract": [
        {
          "text": "A convenience constant indicating that both the video time and host time fields are valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoHostTimeValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVTimeStampFlags",
          "text": "CVTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoHostTimeValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVTimeStampVideoHostTimeValid"
        }
      ],
      "role": "symbol",
      "title": "videoHostTimeValid",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags/videohosttimevalid"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoRefreshPeriodValid": {
      "abstract": [
        {
          "text": "The value in the video refresh period field is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoRefreshPeriodValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVTimeStampFlags",
          "text": "CVTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoRefreshPeriodValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVTimeStampVideoRefreshPeriodValid"
        }
      ],
      "role": "symbol",
      "title": "videoRefreshPeriodValid",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags/videorefreshperiodvalid"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoTimeValid": {
      "abstract": [
        {
          "text": "The value in the video time field is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoTimeValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVTimeStampFlags",
          "text": "CVTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoTimeValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVTimeStampVideoTimeValid"
        }
      ],
      "role": "symbol",
      "title": "videoTimeValid",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags/videotimevalid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeFlags",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeFlags"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/bottomField",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/hostTimeValid",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/isInterlaced",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/rateScalarValid",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/smpteTimeValid",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/topField",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoHostTimeValid",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoRefreshPeriodValid",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoTimeValid"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CVTimeStampFlags"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStampFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStampFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/bottomField",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/hostTimeValid",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/isInterlaced",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/rateScalarValid",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/smpteTimeValid",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/topField",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoHostTimeValid",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoRefreshPeriodValid",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags/videoTimeValid"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeFlags",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeFlags"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CVTimeStampFlags"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint64_t",
                    "text": "uint64_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType/title",
          "value": "CVSMPTETimeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETimeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETimeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1isInterlaced/title",
          "value": "kCVTimeStampIsInterlaced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1isInterlaced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVTimeStampIsInterlaced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1topField/title",
          "value": "kCVTimeStampTopField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1topField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVTimeStampTopField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1rateScalarValid/title",
          "value": "kCVTimeStampRateScalarValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1rateScalarValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVTimeStampRateScalarValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1videoHostTimeValid/title",
          "value": "kCVTimeStampVideoHostTimeValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1videoHostTimeValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVTimeStampVideoHostTimeValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1videoRefreshPeriodValid/title",
          "value": "kCVTimeStampVideoRefreshPeriodValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1videoRefreshPeriodValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVTimeStampVideoRefreshPeriodValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1bottomField/title",
          "value": "kCVTimeStampBottomField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1bottomField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVTimeStampBottomField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1hostTimeValid/title",
          "value": "kCVTimeStampHostTimeValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1hostTimeValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVTimeStampHostTimeValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeFlags/title",
          "value": "CVSMPTETimeFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETimeFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETimeFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeFlags/title",
          "value": "CVTimeFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1videoTimeValid/title",
          "value": "kCVTimeStampVideoTimeValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1videoTimeValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVTimeStampVideoTimeValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags/title",
          "value": "CVTimeStampFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStampFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStampFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1smpteTimeValid/title",
          "value": "kCVTimeStampSMPTETimeValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags~1smpteTimeValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVTimeStampSMPTETimeValid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvtimestampflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvtimestampflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
