{
  "abstract": [
    {
      "text": "A structure used for storing Core Video time values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-q1e"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVTime"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core video uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTime",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structures for storing Core Video time values. You use them to interact with the Core Video display link.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVGetCurrentHostTime()": {
      "abstract": [
        {
          "text": "Returns the current system time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVGetCurrentHostTime"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVGetCurrentHostTime()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVGetCurrentHostTime"
        }
      ],
      "role": "symbol",
      "title": "CVGetCurrentHostTime()",
      "type": "topic",
      "url": "/documentation/corevideo/cvgetcurrenthosttime()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockFrequency()": {
      "abstract": [
        {
          "text": "Returns the frequency of updates to the system time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVGetHostClockFrequency"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockFrequency()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVGetHostClockFrequency"
        }
      ],
      "role": "symbol",
      "title": "CVGetHostClockFrequency()",
      "type": "topic",
      "url": "/documentation/corevideo/cvgethostclockfrequency()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockMinimumTimeDelta()": {
      "abstract": [
        {
          "text": "Returns the smallest possible increment in the system time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVGetHostClockMinimumTimeDelta"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockMinimumTimeDelta()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVGetHostClockMinimumTimeDelta"
        }
      ],
      "role": "symbol",
      "title": "CVGetHostClockMinimumTimeDelta()",
      "type": "topic",
      "url": "/documentation/corevideo/cvgethostclockminimumtimedelta()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETime": {
      "abstract": [
        {
          "text": "A structure for holding an SMPTE time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVSMPTETime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVSMPTETime"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETime",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetime"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVSMPTETimeFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVSMPTETimeFlags"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeFlags",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimeflags"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVSMPTETimeType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVSMPTETimeType"
        }
      ],
      "role": "symbol",
      "title": "CVSMPTETimeType",
      "type": "topic",
      "url": "/documentation/corevideo/cvsmptetimetype"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTime": {
      "abstract": [
        {
          "text": "A structure for reporting Core Video time values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTime"
        }
      ],
      "role": "symbol",
      "title": "CVTime",
      "type": "topic",
      "url": "/documentation/corevideo/cvtime"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTimeFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTimeFlags"
        }
      ],
      "role": "symbol",
      "title": "CVTimeFlags",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimeflags"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp": {
      "abstract": [
        {
          "text": "A structure for defining a display timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "CVTimeStamp",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTimeStampFlags"
        }
      ],
      "role": "symbol",
      "title": "CVTimeStampFlags",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestampflags"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k": {
      "abstract": [
        {
          "text": "A high-priority thread that notifies your app when a given display will need each frame.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVDisplayLink",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylink-k0k"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-values": {
      "abstract": [
        {
          "text": "Keys that represent Core Video time values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVTime Values",
      "type": "topic",
      "url": "/documentation/corevideo/cvtime-values"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvtimestamp-api": {
      "abstract": [
        {
          "text": "A structure for representing a display timestamp.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvtimestamp-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVTimeStamp",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp-api"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536",
      "title": "Core Video Programming Guide",
      "titleInlineContent": [
        {
          "text": "Core Video Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Time-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k"
      ],
      "title": "Time Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-the-Host-Clock",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVGetCurrentHostTime()",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockFrequency()",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockMinimumTimeDelta()"
      ],
      "title": "Inspecting the Host Clock"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTime",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvtimestamp-api",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETime"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-values"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeFlags",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeFlags",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-the-Host-Clock",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVGetCurrentHostTime()",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockFrequency()",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVGetHostClockMinimumTimeDelta()"
              ],
              "title": "Inspecting the Host Clock"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTime",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvtimestamp-api",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETime"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-values"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeType",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVSMPTETimeFlags",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeFlags",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStampFlags"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreVideo/CVProg_Intro/CVProg_Intro.html#//apple_ref/doc/uid/TP40001536"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Time-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k"
              ],
              "title": "Time Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetCurrentHostTime()/title",
          "value": "CVGetCurrentHostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetCurrentHostTime()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVGetCurrentHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags/title",
          "value": "CVTimeStampFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStampFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStampFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStampFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetHostClockFrequency()/title",
          "value": "CVGetHostClockFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetHostClockFrequency()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVGetHostClockFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp/title",
          "value": "CVTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTime/title",
          "value": "CVTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeFlags/title",
          "value": "CVTimeFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETime/title",
          "value": "CVSMPTETime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType/title",
          "value": "CVSMPTETimeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETimeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETimeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetHostClockMinimumTimeDelta()/title",
          "value": "CVGetHostClockMinimumTimeDelta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVGetHostClockMinimumTimeDelta()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVGetHostClockMinimumTimeDelta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeFlags/title",
          "value": "CVSMPTETimeFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETimeFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVSMPTETimeFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVSMPTETimeFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvtime-q1e"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvtime-q1e"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
