{
  "abstract": [
    {
      "text": "Keys that represent Core Video time values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-q1e"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CVTime Values"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)": {
      "abstract": [
        {
          "text": "Retrieves the nominal refresh period of a display link.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVDisplayLinkRef",
          "text": "CVDisplayLink"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTime",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkgetnominaloutputvideorefreshperiod(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetOutputVideoLatency(_:)": {
      "abstract": [
        {
          "text": "Retrieves the nominal latency of a display link.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetOutputVideoLatency"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVDisplayLinkRef",
          "text": "CVDisplayLink"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTime",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetOutputVideoLatency(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetOutputVideoLatency"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkGetOutputVideoLatency(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkgetoutputvideolatency(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-q1e": {
      "abstract": [
        {
          "text": "A structure used for storing Core Video time values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-q1e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVTime",
      "type": "topic",
      "url": "/documentation/corevideo/cvtime-q1e"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVIndefiniteTime": {
      "abstract": [
        {
          "text": "An unknown or indefinite time. For example, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " returns ",
          "type": "text"
        },
        {
          "code": "kCVIndefiniteTime",
          "type": "codeVoice"
        },
        {
          "text": " if the display link specified is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVIndefiniteTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTime",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVIndefiniteTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVIndefiniteTime"
        }
      ],
      "role": "symbol",
      "title": "kCVIndefiniteTime",
      "type": "topic",
      "url": "/documentation/corevideo/kcvindefinitetime"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVZeroTime": {
      "abstract": [
        {
          "text": "Zero time or duration. For example, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetOutputVideoLatency(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " returns ",
          "type": "text"
        },
        {
          "code": "kCVZeroTime",
          "type": "codeVoice"
        },
        {
          "text": " for zero video latency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVZeroTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTime",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVZeroTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVZeroTime"
        }
      ],
      "role": "symbol",
      "title": "kCVZeroTime",
      "type": "topic",
      "url": "/documentation/corevideo/kcvzerotime"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVZeroTime",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVIndefiniteTime"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVZeroTime",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVIndefiniteTime"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetOutputVideoLatency(_:)/title",
          "value": "CVDisplayLinkGetOutputVideoLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetOutputVideoLatency(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkGetOutputVideoLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVIndefiniteTime/title",
          "value": "kCVIndefiniteTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVIndefiniteTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVIndefiniteTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVZeroTime/title",
          "value": "kCVZeroTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVZeroTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVZeroTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)/title",
          "value": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvtime-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvtime-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
