{
  "abstract": [
    {
      "text": "Keys that describe the attachment types associated with image buffers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Image Buffer Attachment Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An image buffer associates its attachment keys in a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdictionary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance. To read and write these image buffer attachments, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions or other ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions. See the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " topic group for additional information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer": {
      "abstract": [
        {
          "text": "A reference to a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBuffer"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a copy of an attachment from a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferCopyAttachment(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferCopyAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferCopyAttachment(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffercopyattachment(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets or adds an attachment to a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CVAttachmentMode",
          "text": "CVAttachmentMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVBufferSetAttachment(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVBufferSetAttachment"
        }
      ],
      "role": "symbol",
      "title": "CVBufferSetAttachment(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffersetattachment(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm": {
      "abstract": [
        {
          "text": "An abstract base class that defines how to interact with data buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer-nfm"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40": {
      "abstract": [
        {
          "text": "An interface for managing different types of image data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer-q40"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants": {
      "abstract": [
        {
          "text": "Constants that indicate locations for chroma samples in the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Chroma Location Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-chroma-location-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the original format of subsampled data in the image buffer before conversion to 422/2vuy format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Chroma Subsampling Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-chroma-subsampling-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys": {
      "abstract": [
        {
          "text": "Keys that describe the clean aperture of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Clean Aperture Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-clean-aperture-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the color primaries gamut for the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Color Primaries Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-color-primaries-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys": {
      "abstract": [
        {
          "text": "Keys that describe the display dimensions of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Display Dimensions Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-display-dimensions-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the field order of interlaced video in an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Field Detail Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-field-detail-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys": {
      "abstract": [
        {
          "text": "Keys that describe the pixel aspect ratio of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Pixel Aspect Ratio Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-pixel-aspect-ratio-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the transfer function for the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Transfer Function Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-transfer-function-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the type of conversion matrix Core Video uses when it converts image buffer data from the YCbCr color space to the RGB color space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer YCbCr Matrix Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-ycbcr-matrix-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelIsOpaque": {
      "abstract": [
        {
          "text": "A key to indicate whether the alpha channel is fully opaque.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferAlphaChannelIsOpaque"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelIsOpaque",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferAlphaChannelIsOpaque"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferAlphaChannelIsOpaque",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferalphachannelisopaque"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCGColorSpaceKey": {
      "abstract": [
        {
          "text": "A key to the color space of the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferCGColorSpaceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCGColorSpaceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferCGColorSpaceKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferCGColorSpaceKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercgcolorspacekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationBottomFieldKey": {
      "abstract": [
        {
          "text": "A key to the location of chroma bottom field information in the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaLocationBottomFieldKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationBottomFieldKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaLocationBottomFieldKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferChromaLocationBottomFieldKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferchromalocationbottomfieldkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationTopFieldKey": {
      "abstract": [
        {
          "text": "A key to the location of chroma top field information in the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaLocationTopFieldKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationTopFieldKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaLocationTopFieldKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferChromaLocationTopFieldKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferchromalocationtopfieldkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaSubsamplingKey": {
      "abstract": [
        {
          "text": "A key to the original format of subsampled data in the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaSubsamplingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaSubsamplingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaSubsamplingKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferChromaSubsamplingKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferchromasubsamplingkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCleanApertureKey": {
      "abstract": [
        {
          "text": "A key to the dictionary describing the clean aperture for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferCleanApertureKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCleanApertureKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferCleanApertureKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferCleanApertureKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercleanaperturekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimariesKey": {
      "abstract": [
        {
          "text": "A key to the color primaries gamut for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimariesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimariesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimariesKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferColorPrimariesKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercolorprimarieskey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferContentLightLevelInfoKey": {
      "abstract": [
        {
          "text": "A key to the content light level information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferContentLightLevelInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferContentLightLevelInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferContentLightLevelInfoKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferContentLightLevelInfoKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercontentlightlevelinfokey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferDisplayDimensionsKey": {
      "abstract": [
        {
          "text": "A key to the dictionary describing the display dimensions for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferDisplayDimensionsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferDisplayDimensionsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferDisplayDimensionsKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferDisplayDimensionsKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferdisplaydimensionskey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldCountKey": {
      "abstract": [
        {
          "text": "A key to the field count for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferFieldCountKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldCountKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferFieldCountKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferFieldCountKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferfieldcountkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldDetailKey": {
      "abstract": [
        {
          "text": "A key to the field detail for an image buffer that indicates the order of interlaced video data in the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferFieldDetailKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldDetailKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferFieldDetailKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferFieldDetailKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferfielddetailkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferGammaLevelKey": {
      "abstract": [
        {
          "text": "A key to the gamma level for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferGammaLevelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferGammaLevelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferGammaLevelKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferGammaLevelKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffergammalevelkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferICCProfileKey": {
      "abstract": [
        {
          "text": "A key to the ICC color profile for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferICCProfileKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferICCProfileKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferICCProfileKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferICCProfileKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffericcprofilekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferMasteringDisplayColorVolumeKey": {
      "abstract": [
        {
          "text": "A key to the mastering display color volume.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferMasteringDisplayColorVolumeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferMasteringDisplayColorVolumeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferMasteringDisplayColorVolumeKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferMasteringDisplayColorVolumeKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffermasteringdisplaycolorvolumekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPixelAspectRatioKey": {
      "abstract": [
        {
          "text": "A key to the dictionary describing the pixel aspect ratio for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferPixelAspectRatioKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPixelAspectRatioKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferPixelAspectRatioKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferPixelAspectRatioKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferpixelaspectratiokey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPreferredCleanApertureKey": {
      "abstract": [
        {
          "text": "A key to the dictionary describing the preferred clean aperture for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferPreferredCleanApertureKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPreferredCleanApertureKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferPreferredCleanApertureKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferPreferredCleanApertureKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferpreferredcleanaperturekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunctionKey": {
      "abstract": [
        {
          "text": "A key to the transfer function for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunctionKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunctionkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrixKey": {
      "abstract": [
        {
          "text": "A key to the YCbCr to RGB color conversion matrix for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrixKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrixKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrixKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrixKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrixkey"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfdictionary": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCGColorSpaceKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCleanApertureKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPreferredCleanApertureKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldCountKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldDetailKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPixelAspectRatioKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferDisplayDimensionsKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferGammaLevelKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferICCProfileKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrixKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimariesKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunctionKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationTopFieldKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationBottomFieldKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaSubsamplingKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelIsOpaque",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferContentLightLevelInfoKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferMasteringDisplayColorVolumeKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCGColorSpaceKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCleanApertureKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPreferredCleanApertureKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldCountKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldDetailKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPixelAspectRatioKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferDisplayDimensionsKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferGammaLevelKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferICCProfileKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrixKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimariesKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunctionKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationTopFieldKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationBottomFieldKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaSubsamplingKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelIsOpaque",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferContentLightLevelInfoKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferMasteringDisplayColorVolumeKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfdictionary/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferCGColorSpaceKey/title",
          "value": "kCVImageBufferCGColorSpaceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferCGColorSpaceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferCGColorSpaceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferDisplayDimensionsKey/title",
          "value": "kCVImageBufferDisplayDimensionsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferDisplayDimensionsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferDisplayDimensionsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunctionKey/title",
          "value": "kCVImageBufferTransferFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferContentLightLevelInfoKey/title",
          "value": "kCVImageBufferContentLightLevelInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferContentLightLevelInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferContentLightLevelInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferGammaLevelKey/title",
          "value": "kCVImageBufferGammaLevelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferGammaLevelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferGammaLevelKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaSubsamplingKey/title",
          "value": "kCVImageBufferChromaSubsamplingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaSubsamplingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferChromaSubsamplingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachment(_:_:_:)/title",
          "value": "CVBufferCopyAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferCopyAttachment(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferCopyAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPreferredCleanApertureKey/title",
          "value": "kCVImageBufferPreferredCleanApertureKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPreferredCleanApertureKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferPreferredCleanApertureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPixelAspectRatioKey/title",
          "value": "kCVImageBufferPixelAspectRatioKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPixelAspectRatioKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferPixelAspectRatioKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaLocationTopFieldKey/title",
          "value": "kCVImageBufferChromaLocationTopFieldKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaLocationTopFieldKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferChromaLocationTopFieldKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferICCProfileKey/title",
          "value": "kCVImageBufferICCProfileKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferICCProfileKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferICCProfileKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachment(_:_:_:_:)/title",
          "value": "CVBufferSetAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBufferSetAttachment(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferSetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferMasteringDisplayColorVolumeKey/title",
          "value": "kCVImageBufferMasteringDisplayColorVolumeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferMasteringDisplayColorVolumeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferMasteringDisplayColorVolumeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/title",
          "value": "CVBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAlphaChannelIsOpaque/title",
          "value": "kCVImageBufferAlphaChannelIsOpaque"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAlphaChannelIsOpaque/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferAlphaChannelIsOpaque"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrixKey/title",
          "value": "kCVImageBufferYCbCrMatrixKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrixKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrixKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferFieldDetailKey/title",
          "value": "kCVImageBufferFieldDetailKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferFieldDetailKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferFieldDetailKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaLocationBottomFieldKey/title",
          "value": "kCVImageBufferChromaLocationBottomFieldKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaLocationBottomFieldKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferChromaLocationBottomFieldKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferCleanApertureKey/title",
          "value": "kCVImageBufferCleanApertureKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferCleanApertureKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferCleanApertureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimariesKey/title",
          "value": "kCVImageBufferColorPrimariesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimariesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferColorPrimariesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferFieldCountKey/title",
          "value": "kCVImageBufferFieldCountKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferFieldCountKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferFieldCountKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/image-buffer-attachment-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/image-buffer-attachment-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
