{
  "abstract": [
    {
      "text": "Constants that indicate the type of conversion matrix Core Video uses when it converts image buffer data from the YCbCr color space to the RGB color space.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Image Buffer YCbCr Matrix Constants"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrixKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key to attach one of these values to the image buffer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40": {
      "abstract": [
        {
          "text": "An interface for managing different types of image data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer-q40"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys": {
      "abstract": [
        {
          "text": "Keys that describe the attachment types associated with image buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Attachment Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-attachment-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants": {
      "abstract": [
        {
          "text": "Constants that indicate locations for chroma samples in the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Chroma Location Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-chroma-location-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the original format of subsampled data in the image buffer before conversion to 422/2vuy format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Chroma Subsampling Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-chroma-subsampling-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys": {
      "abstract": [
        {
          "text": "Keys that describe the clean aperture of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Clean Aperture Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-clean-aperture-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the color primaries gamut for the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Color Primaries Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-color-primaries-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys": {
      "abstract": [
        {
          "text": "Keys that describe the display dimensions of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Display Dimensions Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-display-dimensions-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the field order of interlaced video in an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Field Detail Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-field-detail-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys": {
      "abstract": [
        {
          "text": "Keys that describe the pixel aspect ratio of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Pixel Aspect Ratio Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-pixel-aspect-ratio-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the transfer function for the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Transfer Function Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-transfer-function-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrixKey": {
      "abstract": [
        {
          "text": "A key to the YCbCr to RGB color conversion matrix for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrixKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrixKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrixKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrixKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrixkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_DCI_P3": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_DCI_P3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_DCI_P3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_DCI_P3"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_DCI_P3",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_dci_p3"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_2020": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_2020"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_2020",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_2020"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_ITU_R_2020",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_itu_r_2020"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_601_4": {
      "abstract": [
        {
          "text": "A key to the conversion matrix for standard digital television images, that follows the ITU R 601 standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_601_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_601_4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_601_4"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_ITU_R_601_4",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_itu_r_601_4"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_709_2": {
      "abstract": [
        {
          "text": "A key to the conversion matrix for HDTV digital television images, that follows the ITU R 709 standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_709_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_709_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_709_2"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_itu_r_709_2"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_P3_D65": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_P3_D65"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_P3_D65",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_P3_D65"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_P3_D65",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_p3_d65"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_SMPTE_240M_1995": {
      "abstract": [
        {
          "text": "A key to the conversion matrix for 1920 x 1135 HDTV images, that follows the SMPTE 240M 1995 standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_SMPTE_240M_1995"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_SMPTE_240M_1995",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_SMPTE_240M_1995"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_SMPTE_240M_1995",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_smpte_240m_1995"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_2020",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_P3_D65",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_709_2",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_601_4",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_SMPTE_240M_1995",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_DCI_P3"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_2020",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_P3_D65",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_709_2",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_601_4",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_SMPTE_240M_1995",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_DCI_P3"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrixKey/title",
          "value": "kCVImageBufferYCbCrMatrixKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrixKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrixKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_2020/title",
          "value": "kCVImageBufferYCbCrMatrix_ITU_R_2020"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_2020/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_ITU_R_2020"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_SMPTE_240M_1995/title",
          "value": "kCVImageBufferYCbCrMatrix_SMPTE_240M_1995"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_SMPTE_240M_1995/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_SMPTE_240M_1995"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_DCI_P3/title",
          "value": "kCVImageBufferYCbCrMatrix_DCI_P3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_DCI_P3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_DCI_P3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_709_2/title",
          "value": "kCVImageBufferYCbCrMatrix_ITU_R_709_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_709_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_ITU_R_709_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_601_4/title",
          "value": "kCVImageBufferYCbCrMatrix_ITU_R_601_4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_601_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_ITU_R_601_4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_P3_D65/title",
          "value": "kCVImageBufferYCbCrMatrix_P3_D65"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_P3_D65/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_P3_D65"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/image-buffer-ycbcr-matrix-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/image-buffer-ycbcr-matrix-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
