{
  "abstract": [
    {
      "text": "Constants that indicate the transfer function for the image buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Image Buffer Transfer Function Constants"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunctionKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key to attach one of these values to the image buffer. The transfer function describes the tonality of an image for use in color matching operations, along with a color primaries gamut (See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.). Most apps should specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_709_2",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " transfer function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40": {
      "abstract": [
        {
          "text": "An interface for managing different types of image data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer-q40"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys": {
      "abstract": [
        {
          "text": "Keys that describe the attachment types associated with image buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Attachment Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-attachment-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants": {
      "abstract": [
        {
          "text": "Constants that indicate locations for chroma samples in the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Chroma Location Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-chroma-location-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the original format of subsampled data in the image buffer before conversion to 422/2vuy format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Chroma Subsampling Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-chroma-subsampling-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys": {
      "abstract": [
        {
          "text": "Keys that describe the clean aperture of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Clean Aperture Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-clean-aperture-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the color primaries gamut for the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Color Primaries Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-color-primaries-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys": {
      "abstract": [
        {
          "text": "Keys that describe the display dimensions of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Display Dimensions Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-display-dimensions-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the field order of interlaced video in an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Field Detail Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-field-detail-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys": {
      "abstract": [
        {
          "text": "Keys that describe the pixel aspect ratio of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Pixel Aspect Ratio Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-pixel-aspect-ratio-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the type of conversion matrix Core Video uses when it converts image buffer data from the YCbCr color space to the RGB color space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer YCbCr Matrix Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-ycbcr-matrix-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunctionKey": {
      "abstract": [
        {
          "text": "A key to the transfer function for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunctionKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunctionkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_EBU_3213": {
      "abstract": [
        {
          "text": "A key to the transfer function that follows the EBU 3213 standard.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_EBU_3213"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_EBU_3213",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_EBU_3213",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_ebu_3213"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2020": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_2020"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2020",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_2020"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_ITU_R_2020",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_itu_r_2020"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2100_HLG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_2100_HLG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2100_HLG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_2100_HLG"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_ITU_R_2100_HLG",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_itu_r_2100_hlg"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_709_2": {
      "abstract": [
        {
          "text": "A key to the transfer function for high-definition and standard-definition video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_709_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_709_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_709_2"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_itu_r_709_2"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_240M_1995": {
      "abstract": [
        {
          "text": "A key to the transfer function for HDTV interim video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_240M_1995"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_240M_1995",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_240M_1995"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_SMPTE_240M_1995",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_smpte_240m_1995"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_C": {
      "abstract": [
        {
          "text": "A key to the transfer function for standard-definition video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_C"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_C",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_SMPTE_C",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_smpte_c"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_smpte_st_2084_pq"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_428_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_428_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_SMPTE_ST_428_1",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_smpte_st_428_1"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_UseGamma": {
      "abstract": [
        {
          "text": "A key to the transfer function that’s defined by the gamma level value of the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_UseGamma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_UseGamma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_UseGamma"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_UseGamma",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_usegamma"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_sRGB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_sRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_sRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_sRGB"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_sRGB",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_srgb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_709_2",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_240M_1995",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_UseGamma",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_sRGB",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2020",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_428_1",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2100_HLG",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_709_2",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_240M_1995",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_UseGamma",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_sRGB",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2020",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_428_1",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2100_HLG",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_EBU_3213",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_C"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_709_2/title",
          "value": "kCVImageBufferTransferFunction_ITU_R_709_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_709_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_ITU_R_709_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ/title",
          "value": "kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_2020/title",
          "value": "kCVImageBufferTransferFunction_ITU_R_2020"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_2020/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_ITU_R_2020"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_ST_428_1/title",
          "value": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_ST_428_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_sRGB/title",
          "value": "kCVImageBufferTransferFunction_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_sRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunctionKey/title",
          "value": "kCVImageBufferTransferFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_UseGamma/title",
          "value": "kCVImageBufferTransferFunction_UseGamma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_UseGamma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_UseGamma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_2100_HLG/title",
          "value": "kCVImageBufferTransferFunction_ITU_R_2100_HLG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_2100_HLG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_ITU_R_2100_HLG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_240M_1995/title",
          "value": "kCVImageBufferTransferFunction_SMPTE_240M_1995"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_240M_1995/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_SMPTE_240M_1995"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/image-buffer-transfer-function-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/image-buffer-transfer-function-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
