{
  "abstract": [
    {
      "text": "Constants that indicate the color primaries gamut for the image buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-color-primaries-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Image Buffer Color Primaries Constants"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimariesKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key to attach one of these values to the image buffer. The color primaries gamut describes the rendering intent of an image, for use in color matching operations, along with a transfer function (See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40": {
      "abstract": [
        {
          "text": "An interface for managing different types of image data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer-q40"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys": {
      "abstract": [
        {
          "text": "Keys that describe the attachment types associated with image buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Attachment Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-attachment-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants": {
      "abstract": [
        {
          "text": "Constants that indicate locations for chroma samples in the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Chroma Location Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-chroma-location-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the original format of subsampled data in the image buffer before conversion to 422/2vuy format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Chroma Subsampling Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-chroma-subsampling-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys": {
      "abstract": [
        {
          "text": "Keys that describe the clean aperture of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Clean Aperture Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-clean-aperture-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys": {
      "abstract": [
        {
          "text": "Keys that describe the display dimensions of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Display Dimensions Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-display-dimensions-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the field order of interlaced video in an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Field Detail Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-field-detail-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys": {
      "abstract": [
        {
          "text": "Keys that describe the pixel aspect ratio of an image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Pixel Aspect Ratio Keys",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-pixel-aspect-ratio-keys"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the transfer function for the image buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer Transfer Function Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-transfer-function-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants": {
      "abstract": [
        {
          "text": "Constants that indicate the type of conversion matrix Core Video uses when it converts image buffer data from the YCbCr color space to the RGB color space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Buffer YCbCr Matrix Constants",
      "type": "topic",
      "url": "/documentation/corevideo/image-buffer-ycbcr-matrix-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimariesKey": {
      "abstract": [
        {
          "text": "A key to the color primaries gamut for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimariesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimariesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimariesKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferColorPrimariesKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercolorprimarieskey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_DCI_P3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_DCI_P3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_DCI_P3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_DCI_P3"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferColorPrimaries_DCI_P3",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercolorprimaries_dci_p3"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_EBU_3213": {
      "abstract": [
        {
          "text": "A key to the color primaries gamut for PAL video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_EBU_3213"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_EBU_3213",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_EBU_3213"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferColorPrimaries_EBU_3213",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercolorprimaries_ebu_3213"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_ITU_R_2020": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_ITU_R_2020"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_ITU_R_2020",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_ITU_R_2020"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferColorPrimaries_ITU_R_2020",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercolorprimaries_itu_r_2020"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_ITU_R_709_2": {
      "abstract": [
        {
          "text": "A key to the color primaries gamut for HD video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_ITU_R_709_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_ITU_R_709_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_ITU_R_709_2"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferColorPrimaries_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercolorprimaries_itu_r_709_2"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_P22": {
      "abstract": [
        {
          "text": "A key to the color primaries gamut for sRGB video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_P22"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_P22",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_P22"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferColorPrimaries_P22",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercolorprimaries_p22"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_P3_D65": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_P3_D65"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_P3_D65",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_P3_D65"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferColorPrimaries_P3_D65",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercolorprimaries_p3_d65"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_SMPTE_C": {
      "abstract": [
        {
          "text": "A key to the color primaries gamut for standard-definition video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_SMPTE_C"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_SMPTE_C",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimaries_SMPTE_C"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferColorPrimaries_SMPTE_C",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercolorprimaries_smpte_c"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_ITU_R_709_2",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_EBU_3213",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_SMPTE_C",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_DCI_P3",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_ITU_R_2020",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_P3_D65",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_P22"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_ITU_R_709_2",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_EBU_3213",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_SMPTE_C",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_DCI_P3",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_ITU_R_2020",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_P3_D65",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimaries_P22"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-attachment-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-clean-aperture-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-pixel-aspect-ratio-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-display-dimensions-keys",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-field-detail-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-ycbcr-matrix-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-transfer-function-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-location-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/image-buffer-chroma-subsampling-constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_DCI_P3/title",
          "value": "kCVImageBufferColorPrimaries_DCI_P3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_DCI_P3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferColorPrimaries_DCI_P3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_ITU_R_709_2/title",
          "value": "kCVImageBufferColorPrimaries_ITU_R_709_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_ITU_R_709_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferColorPrimaries_ITU_R_709_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_ITU_R_2020/title",
          "value": "kCVImageBufferColorPrimaries_ITU_R_2020"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_ITU_R_2020/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferColorPrimaries_ITU_R_2020"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_SMPTE_C/title",
          "value": "kCVImageBufferColorPrimaries_SMPTE_C"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_SMPTE_C/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferColorPrimaries_SMPTE_C"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_P22/title",
          "value": "kCVImageBufferColorPrimaries_P22"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_P22/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferColorPrimaries_P22"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_EBU_3213/title",
          "value": "kCVImageBufferColorPrimaries_EBU_3213"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_EBU_3213/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferColorPrimaries_EBU_3213"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimariesKey/title",
          "value": "kCVImageBufferColorPrimariesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimariesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferColorPrimariesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_P3_D65/title",
          "value": "kCVImageBufferColorPrimaries_P3_D65"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimaries_P3_D65/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferColorPrimaries_P3_D65"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/image-buffer-color-primaries-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/image-buffer-color-primaries-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
