{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This value is no longer supported.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_P3_D65"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCVImageBufferYCbCrMatrix_P3_D65",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCVImageBufferYCbCrMatrix_P3_D65"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCVImageBufferYCbCrMatrix_P3_D65"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "9.0",
        "message": "kCVImageBufferYCbCrMatrix_P3_D65 no longer supported.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "9.0",
        "message": "kCVImageBufferYCbCrMatrix_P3_D65 no longer supported.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.1",
        "message": "kCVImageBufferYCbCrMatrix_P3_D65 no longer supported.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.11",
        "message": "kCVImageBufferYCbCrMatrix_P3_D65 no longer supported.",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "9.0",
        "message": "kCVImageBufferYCbCrMatrix_P3_D65 no longer supported.",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "kCVImageBufferYCbCrMatrix_P3_D65 no longer supported.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "7.0",
        "introducedAt": "2.0",
        "message": "kCVImageBufferYCbCrMatrix_P3_D65 no longer supported.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCVImageBufferYCbCrMatrix_P3_D65"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_P3_D65"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_DCI_P3": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_DCI_P3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_DCI_P3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_DCI_P3"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_DCI_P3",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_dci_p3"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_2020": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_2020"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_2020",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_2020"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_ITU_R_2020",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_itu_r_2020"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_601_4": {
      "abstract": [
        {
          "text": "A key to the conversion matrix for standard digital television images, that follows the ITU R 601 standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_601_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_601_4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_601_4"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_ITU_R_601_4",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_itu_r_601_4"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_709_2": {
      "abstract": [
        {
          "text": "A key to the conversion matrix for HDTV digital television images, that follows the ITU R 709 standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_709_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_709_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_ITU_R_709_2"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_itu_r_709_2"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_P3_D65": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_P3_D65"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_P3_D65",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_P3_D65"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_P3_D65",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_p3_d65"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_SMPTE_240M_1995": {
      "abstract": [
        {
          "text": "A key to the conversion matrix for 1920 x 1135 HDTV images, that follows the SMPTE 240M 1995 standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_SMPTE_240M_1995"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_SMPTE_240M_1995",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrix_SMPTE_240M_1995"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrix_SMPTE_240M_1995",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrix_smpte_240m_1995"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_2020",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_709_2",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_601_4",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_SMPTE_240M_1995",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_DCI_P3"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCVImageBufferYCbCrMatrix_P3_D65"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_P3_D65"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_2020",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_709_2",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_ITU_R_601_4",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_SMPTE_240M_1995",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrix_DCI_P3"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCVImageBufferYCbCrMatrix_P3_D65"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This value is no longer supported.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_P3_D65/title",
          "value": "kCVImageBufferYCbCrMatrix_P3_D65"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_P3_D65/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_P3_D65"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_DCI_P3/title",
          "value": "kCVImageBufferYCbCrMatrix_DCI_P3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_DCI_P3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_DCI_P3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_2020/title",
          "value": "kCVImageBufferYCbCrMatrix_ITU_R_2020"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_2020/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_ITU_R_2020"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_SMPTE_240M_1995/title",
          "value": "kCVImageBufferYCbCrMatrix_SMPTE_240M_1995"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_SMPTE_240M_1995/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_SMPTE_240M_1995"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_601_4/title",
          "value": "kCVImageBufferYCbCrMatrix_ITU_R_601_4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_601_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_ITU_R_601_4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_709_2/title",
          "value": "kCVImageBufferYCbCrMatrix_ITU_R_709_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrix_ITU_R_709_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrix_ITU_R_709_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/kcvimagebufferycbcrmatrix_p3_d65"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/kcvimagebufferycbcrmatrix_p3_d65"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
