{
  "abstract": [
    {
      "text": "A key to the color space of the image buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCGColorSpaceKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCVImageBufferCGColorSpaceKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCVImageBufferCGColorSpaceKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCVImageBufferCGColorSpaceKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCVImageBufferCGColorSpaceKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCVImageBufferCGColorSpaceKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The color space value is of type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcolorspace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelIsOpaque": {
      "abstract": [
        {
          "text": "A key to indicate whether the alpha channel is fully opaque.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferAlphaChannelIsOpaque"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelIsOpaque",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferAlphaChannelIsOpaque"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferAlphaChannelIsOpaque",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferalphachannelisopaque"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCGColorSpaceKey": {
      "abstract": [
        {
          "text": "A key to the color space of the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferCGColorSpaceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCGColorSpaceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferCGColorSpaceKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferCGColorSpaceKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercgcolorspacekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationBottomFieldKey": {
      "abstract": [
        {
          "text": "A key to the location of chroma bottom field information in the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaLocationBottomFieldKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationBottomFieldKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaLocationBottomFieldKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferChromaLocationBottomFieldKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferchromalocationbottomfieldkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationTopFieldKey": {
      "abstract": [
        {
          "text": "A key to the location of chroma top field information in the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaLocationTopFieldKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationTopFieldKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaLocationTopFieldKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferChromaLocationTopFieldKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferchromalocationtopfieldkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaSubsamplingKey": {
      "abstract": [
        {
          "text": "A key to the original format of subsampled data in the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaSubsamplingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaSubsamplingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferChromaSubsamplingKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferChromaSubsamplingKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferchromasubsamplingkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCleanApertureKey": {
      "abstract": [
        {
          "text": "A key to the dictionary describing the clean aperture for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferCleanApertureKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCleanApertureKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferCleanApertureKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferCleanApertureKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercleanaperturekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimariesKey": {
      "abstract": [
        {
          "text": "A key to the color primaries gamut for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimariesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimariesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferColorPrimariesKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferColorPrimariesKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffercolorprimarieskey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferDisplayDimensionsKey": {
      "abstract": [
        {
          "text": "A key to the dictionary describing the display dimensions for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferDisplayDimensionsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferDisplayDimensionsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferDisplayDimensionsKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferDisplayDimensionsKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferdisplaydimensionskey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldCountKey": {
      "abstract": [
        {
          "text": "A key to the field count for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferFieldCountKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldCountKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferFieldCountKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferFieldCountKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferfieldcountkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldDetailKey": {
      "abstract": [
        {
          "text": "A key to the field detail for an image buffer that indicates the order of interlaced video data in the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferFieldDetailKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldDetailKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferFieldDetailKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferFieldDetailKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferfielddetailkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferGammaLevelKey": {
      "abstract": [
        {
          "text": "A key to the gamma level for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferGammaLevelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferGammaLevelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferGammaLevelKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferGammaLevelKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffergammalevelkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferICCProfileKey": {
      "abstract": [
        {
          "text": "A key to the ICC color profile for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferICCProfileKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferICCProfileKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferICCProfileKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferICCProfileKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffericcprofilekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPixelAspectRatioKey": {
      "abstract": [
        {
          "text": "A key to the dictionary describing the pixel aspect ratio for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferPixelAspectRatioKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPixelAspectRatioKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferPixelAspectRatioKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferPixelAspectRatioKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferpixelaspectratiokey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPreferredCleanApertureKey": {
      "abstract": [
        {
          "text": "A key to the dictionary describing the preferred clean aperture for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferPreferredCleanApertureKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPreferredCleanApertureKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferPreferredCleanApertureKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferPreferredCleanApertureKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferpreferredcleanaperturekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunctionKey": {
      "abstract": [
        {
          "text": "A key to the transfer function for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunctionKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunctionkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrixKey": {
      "abstract": [
        {
          "text": "A key to the YCbCr to RGB color conversion matrix for the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrixKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrixKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferYCbCrMatrixKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferYCbCrMatrixKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferycbcrmatrixkey"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgcolorspace": {
      "abstract": [
        {
          "text": "A profile that specifies how to interpret a color value for display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGColorSpace"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcolorspace",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGColorSpace",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcolorspace"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCleanApertureKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPreferredCleanApertureKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldCountKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldDetailKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPixelAspectRatioKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferDisplayDimensionsKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferGammaLevelKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferICCProfileKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrixKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimariesKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunctionKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationTopFieldKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationBottomFieldKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaSubsamplingKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelIsOpaque"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCVImageBufferCGColorSpaceKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferCGColorSpaceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferCleanApertureKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPreferredCleanApertureKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldCountKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferFieldDetailKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPixelAspectRatioKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferDisplayDimensionsKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferGammaLevelKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferICCProfileKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferYCbCrMatrixKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferColorPrimariesKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunctionKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationTopFieldKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaLocationBottomFieldKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferChromaSubsamplingKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAlphaChannelIsOpaque"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCVImageBufferCGColorSpaceKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimariesKey/title",
          "value": "kCVImageBufferColorPrimariesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferColorPrimariesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferColorPrimariesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgcolorspace/title",
          "value": "CGColorSpaceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaLocationBottomFieldKey/title",
          "value": "kCVImageBufferChromaLocationBottomFieldKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaLocationBottomFieldKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferChromaLocationBottomFieldKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferCleanApertureKey/title",
          "value": "kCVImageBufferCleanApertureKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferCleanApertureKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferCleanApertureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaSubsamplingKey/title",
          "value": "kCVImageBufferChromaSubsamplingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaSubsamplingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferChromaSubsamplingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferFieldDetailKey/title",
          "value": "kCVImageBufferFieldDetailKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferFieldDetailKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferFieldDetailKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPreferredCleanApertureKey/title",
          "value": "kCVImageBufferPreferredCleanApertureKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPreferredCleanApertureKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferPreferredCleanApertureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferDisplayDimensionsKey/title",
          "value": "kCVImageBufferDisplayDimensionsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferDisplayDimensionsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferDisplayDimensionsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferGammaLevelKey/title",
          "value": "kCVImageBufferGammaLevelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferGammaLevelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferGammaLevelKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferCGColorSpaceKey/title",
          "value": "kCVImageBufferCGColorSpaceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferCGColorSpaceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferCGColorSpaceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPixelAspectRatioKey/title",
          "value": "kCVImageBufferPixelAspectRatioKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPixelAspectRatioKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferPixelAspectRatioKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferFieldCountKey/title",
          "value": "kCVImageBufferFieldCountKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferFieldCountKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferFieldCountKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunctionKey/title",
          "value": "kCVImageBufferTransferFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAlphaChannelIsOpaque/title",
          "value": "kCVImageBufferAlphaChannelIsOpaque"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAlphaChannelIsOpaque/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferAlphaChannelIsOpaque"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaLocationTopFieldKey/title",
          "value": "kCVImageBufferChromaLocationTopFieldKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferChromaLocationTopFieldKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferChromaLocationTopFieldKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferICCProfileKey/title",
          "value": "kCVImageBufferICCProfileKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferICCProfileKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferICCProfileKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrixKey/title",
          "value": "kCVImageBufferYCbCrMatrixKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferYCbCrMatrixKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferYCbCrMatrixKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/kcvimagebuffercgcolorspacekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/kcvimagebuffercgcolorspacekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
