{
  "abstract": [
    {
      "text": "An unknown or indefinite time. For example, ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " returns ",
      "type": "text"
    },
    {
      "code": "kCVIndefiniteTime",
      "type": "codeVoice"
    },
    {
      "text": " if the display link specified is not valid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/kCVIndefiniteTime"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCVIndefiniteTime",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCVIndefiniteTime"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CVTime",
        "text": "CVTime"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCVIndefiniteTime"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCVIndefiniteTime"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCVIndefiniteTime"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTime",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CVTime",
              "text": "CVTime"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)": {
      "abstract": [
        {
          "text": "Retrieves the nominal refresh period of a display link.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVDisplayLinkRef",
          "text": "CVDisplayLink"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTime",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkgetnominaloutputvideorefreshperiod(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetOutputVideoLatency(_:)": {
      "abstract": [
        {
          "text": "Retrieves the nominal latency of a display link.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetOutputVideoLatency"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVDisplayLinkRef",
          "text": "CVDisplayLink"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTime",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetOutputVideoLatency(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVDisplayLinkGetOutputVideoLatency"
        }
      ],
      "role": "symbol",
      "title": "CVDisplayLinkGetOutputVideoLatency(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylinkgetoutputvideolatency(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTime": {
      "abstract": [
        {
          "text": "A structure for reporting Core Video time values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTime"
        }
      ],
      "role": "symbol",
      "title": "CVTime",
      "type": "topic",
      "url": "/documentation/corevideo/cvtime"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVIndefiniteTime": {
      "abstract": [
        {
          "text": "An unknown or indefinite time. For example, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " returns ",
          "type": "text"
        },
        {
          "code": "kCVIndefiniteTime",
          "type": "codeVoice"
        },
        {
          "text": " if the display link specified is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVIndefiniteTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTime",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVIndefiniteTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVIndefiniteTime"
        }
      ],
      "role": "symbol",
      "title": "kCVIndefiniteTime",
      "type": "topic",
      "url": "/documentation/corevideo/kcvindefinitetime"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVZeroTime": {
      "abstract": [
        {
          "text": "Zero time or duration. For example, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVDisplayLinkGetOutputVideoLatency(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " returns ",
          "type": "text"
        },
        {
          "code": "kCVZeroTime",
          "type": "codeVoice"
        },
        {
          "text": " for zero video latency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVZeroTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CVTime",
          "text": "CVTime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVZeroTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVZeroTime"
        }
      ],
      "role": "symbol",
      "title": "kCVZeroTime",
      "type": "topic",
      "url": "/documentation/corevideo/kcvzerotime"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVZeroTime"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCVIndefiniteTime"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVIndefiniteTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVZeroTime"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTime",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CVTime",
                    "text": "CVTime"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCVIndefiniteTime"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTime/title",
          "value": "CVTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVZeroTime/title",
          "value": "kCVZeroTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVZeroTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVZeroTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)/title",
          "value": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetNominalOutputVideoRefreshPeriod(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkGetNominalOutputVideoRefreshPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVIndefiniteTime/title",
          "value": "kCVIndefiniteTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVIndefiniteTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVIndefiniteTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetOutputVideoLatency(_:)/title",
          "value": "CVDisplayLinkGetOutputVideoLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVDisplayLinkGetOutputVideoLatency(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVDisplayLinkGetOutputVideoLatency"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/kcvindefinitetime"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/kcvindefinitetime"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
