{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_428_1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCVImageBufferTransferFunction_SMPTE_ST_428_1",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_EBU_3213": {
      "abstract": [
        {
          "text": "A key to the transfer function that follows the EBU 3213 standard.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_EBU_3213"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_EBU_3213",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_EBU_3213",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_ebu_3213"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2020": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_2020"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2020",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_2020"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_ITU_R_2020",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_itu_r_2020"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2100_HLG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_2100_HLG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2100_HLG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_2100_HLG"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_ITU_R_2100_HLG",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_itu_r_2100_hlg"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_709_2": {
      "abstract": [
        {
          "text": "A key to the transfer function for high-definition and standard-definition video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_709_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_709_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_ITU_R_709_2"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_itu_r_709_2"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_240M_1995": {
      "abstract": [
        {
          "text": "A key to the transfer function for HDTV interim video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_240M_1995"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_240M_1995",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_240M_1995"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_SMPTE_240M_1995",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_smpte_240m_1995"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_C": {
      "abstract": [
        {
          "text": "A key to the transfer function for standard-definition video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_C"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_C",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_SMPTE_C",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_smpte_c"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_smpte_st_2084_pq"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_428_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_428_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_SMPTE_ST_428_1",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_smpte_st_428_1"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_UseGamma": {
      "abstract": [
        {
          "text": "A key to the transfer function that’s defined by the gamma level value of the image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_UseGamma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_UseGamma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_UseGamma"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_UseGamma",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_usegamma"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_sRGB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_sRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_sRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferTransferFunction_sRGB"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferTransferFunction_sRGB",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffertransferfunction_srgb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_709_2",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_240M_1995",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_UseGamma",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_sRGB",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2020",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2100_HLG",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_709_2",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_240M_1995",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_UseGamma",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_sRGB",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2020",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_ITU_R_2100_HLG",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_EBU_3213",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferTransferFunction_SMPTE_C"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ/title",
          "value": "kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_2100_HLG/title",
          "value": "kCVImageBufferTransferFunction_ITU_R_2100_HLG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_2100_HLG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_ITU_R_2100_HLG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_sRGB/title",
          "value": "kCVImageBufferTransferFunction_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_sRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_240M_1995/title",
          "value": "kCVImageBufferTransferFunction_SMPTE_240M_1995"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_240M_1995/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_SMPTE_240M_1995"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_2020/title",
          "value": "kCVImageBufferTransferFunction_ITU_R_2020"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_2020/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_ITU_R_2020"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_709_2/title",
          "value": "kCVImageBufferTransferFunction_ITU_R_709_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_ITU_R_709_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_ITU_R_709_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_UseGamma/title",
          "value": "kCVImageBufferTransferFunction_UseGamma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_UseGamma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_UseGamma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_ST_428_1/title",
          "value": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferTransferFunction_SMPTE_ST_428_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferTransferFunction_SMPTE_ST_428_1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/kcvimagebuffertransferfunction_smpte_st_428_1"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/kcvimagebuffertransferfunction_smpte_st_428_1"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
