{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAmbientViewingEnvironmentKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCVImageBufferAmbientViewingEnvironmentKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCVImageBufferAmbientViewingEnvironmentKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCVImageBufferAmbientViewingEnvironmentKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCVImageBufferAmbientViewingEnvironmentKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCVImageBufferAmbientViewingEnvironmentKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_DECLARE_NULLABILITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_DECLARE_NULLABILITY"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_DECLARE_NULLABILITY",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_declare_nullability"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_FALSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_FALSE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_FALSE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_false"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_included_iosurface_header_file"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_COLORSPACE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_COLORSPACE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_COLORSPACE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_colorspace"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DIRECT3D"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DIRECT3D"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_DIRECT3D",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_direct3d"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DISPLAYLINK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_DISPLAYLINK"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_DISPLAYLINK",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_displaylink"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_gles_tex_image_iosurface"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_IOSURFACE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_iosurface"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_iosurface_prefetch"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_METAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_METAL"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_METAL",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_metal"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGL"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_OPENGL",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_opengl"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGLES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_OPENGLES"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_OPENGLES",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_opengles"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_permanent_allocator"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PREFETCH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_SUPPORTS_PREFETCH"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_SUPPORTS_PREFETCH",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_supports_prefetch"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREVIDEO_TRUE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREVIDEO_TRUE"
        }
      ],
      "role": "symbol",
      "title": "COREVIDEO_TRUE",
      "type": "topic",
      "url": "/documentation/corevideo/corevideo_true"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAmbientViewingEnvironmentKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferAmbientViewingEnvironmentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferAmbientViewingEnvironmentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferAmbientViewingEnvironmentKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferAmbientViewingEnvironmentKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferambientviewingenvironmentkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH",
        "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCVImageBufferAmbientViewingEnvironmentKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferAmbientViewingEnvironmentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_DECLARE_NULLABILITY",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_FALSE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_COLORSPACE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DIRECT3D",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_DISPLAYLINK",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_METAL",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGL",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_OPENGLES",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_SUPPORTS_PREFETCH",
                "doc://com.apple.corevideo/documentation/CoreVideo/COREVIDEO_TRUE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCVImageBufferAmbientViewingEnvironmentKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGL/title",
          "value": "COREVIDEO_SUPPORTS_OPENGL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_OPENGL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGLES/title",
          "value": "COREVIDEO_SUPPORTS_OPENGLES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_OPENGLES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_OPENGLES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_DECLARE_NULLABILITY/title",
          "value": "COREVIDEO_DECLARE_NULLABILITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_DECLARE_NULLABILITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_DECLARE_NULLABILITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAmbientViewingEnvironmentKey/title",
          "value": "kCVImageBufferAmbientViewingEnvironmentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferAmbientViewingEnvironmentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferAmbientViewingEnvironmentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_TRUE/title",
          "value": "COREVIDEO_TRUE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_TRUE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_TRUE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR/title",
          "value": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_COLORSPACE/title",
          "value": "COREVIDEO_SUPPORTS_COLORSPACE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_COLORSPACE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_COLORSPACE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE/title",
          "value": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PREFETCH/title",
          "value": "COREVIDEO_SUPPORTS_PREFETCH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_PREFETCH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_PREFETCH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH/title",
          "value": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DIRECT3D/title",
          "value": "COREVIDEO_SUPPORTS_DIRECT3D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DIRECT3D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_DIRECT3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE/title",
          "value": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_METAL/title",
          "value": "COREVIDEO_SUPPORTS_METAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_METAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_METAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DISPLAYLINK/title",
          "value": "COREVIDEO_SUPPORTS_DISPLAYLINK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_DISPLAYLINK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_DISPLAYLINK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE/title",
          "value": "COREVIDEO_SUPPORTS_IOSURFACE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_SUPPORTS_IOSURFACE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_SUPPORTS_IOSURFACE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_FALSE/title",
          "value": "COREVIDEO_FALSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1COREVIDEO_FALSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREVIDEO_FALSE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/kcvimagebufferambientviewingenvironmentkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/kcvimagebufferambientviewingenvironmentkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
