{
  "abstract": [
    {
      "text": "The horizontal alignment requirements of this format (type ",
      "type": "text"
    },
    {
      "code": "CFNumber",
      "type": "codeVoice"
    },
    {
      "text": "). For example,the alignment for v210 would be 8 here for the horizontal case to match the standard v210 row alignment value of 48. Assumed to be 1 if this key is not present.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHorizontalAlignment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCVPixelFormatBlockHorizontalAlignment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCVPixelFormatBlockHorizontalAlignment"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCVPixelFormatBlockHorizontalAlignment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCVPixelFormatBlockHorizontalAlignment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBlockHorizontalAlignment"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBitsPerBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBitsPerBlock"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatBitsPerBlock",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatbitsperblock"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHeight": {
      "abstract": [
        {
          "text": "The height, in pixels, of the smallest byte-addressable group of pixels (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": "). Assumed to be 1 if this key is not present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockHeight"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatBlockHeight",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatblockheight"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHorizontalAlignment": {
      "abstract": [
        {
          "text": "The horizontal alignment requirements of this format (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": "). For example,the alignment for v210 would be 8 here for the horizontal case to match the standard v210 row alignment value of 48. Assumed to be 1 if this key is not present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockHorizontalAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHorizontalAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockHorizontalAlignment"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatBlockHorizontalAlignment",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatblockhorizontalalignment"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockWidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockWidth"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatBlockWidth",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatblockwidth"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCodecType": {
      "abstract": [
        {
          "text": "The codec type (type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": "). For example, ",
          "type": "text"
        },
        {
          "code": "'2vuy'",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "k422YpCbCr8CodecType",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatCodecType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatCodecType"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatCodecType",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcodectype"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatComponentRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcomponentrange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_FullRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_FullRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_FullRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_FullRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatComponentRange_FullRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcomponentrange_fullrange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_VideoRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_VideoRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_VideoRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_VideoRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatComponentRange_VideoRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcomponentrange_videorange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_WideRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_WideRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_WideRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_WideRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatComponentRange_WideRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcomponentrange_widerange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatConstant": {
      "abstract": [
        {
          "text": "The pixel format constant for QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatConstant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatConstant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatConstant"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatConstant",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatconstant"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsAlpha": {
      "abstract": [
        {
          "text": "A Boolean value where ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " indicates that the format contains alpha and some images may be considered transparent; ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " indicates that there is no alpha and images are always opaque.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsAlpha"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatContainsAlpha",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcontainsalpha"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsRGB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsRGB"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatContainsRGB",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcontainsrgb"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsYCbCr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsYCbCr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsYCbCr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsYCbCr"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatContainsYCbCr",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcontainsycbcr"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFourCC": {
      "abstract": [
        {
          "text": "The Microsoft FourCC equivalent code for this pixel format (type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatFourCC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFourCC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatFourCC"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatFourCC",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatfourcc"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatName": {
      "abstract": [
        {
          "text": "The name of the pixel format (type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": "). This should be the same as the codec name you would use in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatName"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatName",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatname"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatPlanes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatPlanes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatPlanes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatPlanes"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatPlanes",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatplanes"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse": {
      "abstract": [
        {
          "text": "Boolean false value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanFalse"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanFalse",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleanfalse"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue": {
      "abstract": [
        {
          "text": "Boolean true value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanTrue"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanTrue",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleantrue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_FullRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_VideoRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_WideRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsRGB",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsYCbCr",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatName",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatConstant",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCodecType",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFourCC",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsAlpha",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatPlanes",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockWidth",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHeight",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerBlock"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCVPixelFormatBlockHorizontalAlignment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBlockHorizontalAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_FullRange",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_VideoRange",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_WideRange",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsRGB",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsYCbCr",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatName",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatConstant",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCodecType",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFourCC",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsAlpha",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatPlanes",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockWidth",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHeight",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerBlock"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCVPixelFormatBlockHorizontalAlignment"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatConstant/title",
          "value": "kCVPixelFormatConstant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatConstant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatConstant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatPlanes/title",
          "value": "kCVPixelFormatPlanes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatPlanes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatPlanes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange/title",
          "value": "kCVPixelFormatComponentRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatComponentRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatCodecType/title",
          "value": "kCVPixelFormatCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBitsPerBlock/title",
          "value": "kCVPixelFormatBitsPerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBitsPerBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBitsPerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockHeight/title",
          "value": "kCVPixelFormatBlockHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBlockHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsRGB/title",
          "value": "kCVPixelFormatContainsRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatContainsRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_WideRange/title",
          "value": "kCVPixelFormatComponentRange_WideRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_WideRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatComponentRange_WideRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_FullRange/title",
          "value": "kCVPixelFormatComponentRange_FullRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_FullRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatComponentRange_FullRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_VideoRange/title",
          "value": "kCVPixelFormatComponentRange_VideoRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_VideoRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatComponentRange_VideoRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatFourCC/title",
          "value": "kCVPixelFormatFourCC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatFourCC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatFourCC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockHorizontalAlignment/title",
          "value": "kCVPixelFormatBlockHorizontalAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockHorizontalAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBlockHorizontalAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsYCbCr/title",
          "value": "kCVPixelFormatContainsYCbCr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsYCbCr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatContainsYCbCr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatName/title",
          "value": "kCVPixelFormatName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockWidth/title",
          "value": "kCVPixelFormatBlockWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBlockWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsAlpha/title",
          "value": "kCVPixelFormatContainsAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatContainsAlpha"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/kcvpixelformatblockhorizontalalignment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/kcvpixelformatblockhorizontalalignment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
