{
  "abstract": [
    {
      "text": "The key you use to set the auxiliary attributes dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolAllocationThresholdKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCVPixelBufferPoolAllocationThresholdKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCVPixelBufferPoolAllocationThresholdKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCVPixelBufferPoolAllocationThresholdKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCVPixelBufferPoolAllocationThresholdKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPoolAllocationThresholdKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this key to set ",
              "type": "text"
            },
            {
              "code": "auxAttributes",
              "type": "codeVoice"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The value for this key specifies that the system shouldn’t allocate a new pixel buffer if the pool already holds at least the specified number of allocated pixel buffers. This key doesn’t prevent the system from recycling allocated buffers. If this key causes ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to fail, it returns the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnWouldExceedAllocationThreshold",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " result code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new pixel buffer with auxiliary attributes from the pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferPoolRef",
          "text": "CVPixelBufferPool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolcreatepixelbufferwithauxattributes(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolAllocationThresholdKey": {
      "abstract": [
        {
          "text": "The key you use to set the auxiliary attributes dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolAllocationThresholdKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolAllocationThresholdKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolAllocationThresholdKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPoolAllocationThresholdKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferpoolallocationthresholdkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMaximumBufferAgeKey": {
      "abstract": [
        {
          "text": "The key you use to set the maximum allowable age for a buffer in the pixel buffer pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolMaximumBufferAgeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMaximumBufferAgeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolMaximumBufferAgeKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPoolMaximumBufferAgeKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferpoolmaximumbufferagekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMinimumBufferCountKey": {
      "abstract": [
        {
          "text": "The minimum number of buffers allowed in the pixel buffer pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolMinimumBufferCountKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMinimumBufferCountKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolMinimumBufferCountKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPoolMinimumBufferCountKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferpoolminimumbuffercountkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnWouldExceedAllocationThreshold": {
      "abstract": [
        {
          "text": "Allocation for a pixel buffer failed because the threshold value set for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolAllocationThresholdKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function would be surpassed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnWouldExceedAllocationThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnWouldExceedAllocationThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnWouldExceedAllocationThreshold"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnWouldExceedAllocationThreshold",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnwouldexceedallocationthreshold"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMinimumBufferCountKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMaximumBufferAgeKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCVPixelBufferPoolAllocationThresholdKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPoolAllocationThresholdKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMinimumBufferCountKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolMaximumBufferAgeKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCVPixelBufferPoolAllocationThresholdKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolMinimumBufferCountKey/title",
          "value": "kCVPixelBufferPoolMinimumBufferCountKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolMinimumBufferCountKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPoolMinimumBufferCountKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnWouldExceedAllocationThreshold/title",
          "value": "kCVReturnWouldExceedAllocationThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnWouldExceedAllocationThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnWouldExceedAllocationThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)/title",
          "value": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolAllocationThresholdKey/title",
          "value": "kCVPixelBufferPoolAllocationThresholdKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolAllocationThresholdKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPoolAllocationThresholdKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolMaximumBufferAgeKey/title",
          "value": "kCVPixelBufferPoolMaximumBufferAgeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolMaximumBufferAgeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPoolMaximumBufferAgeKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/kcvpixelbufferpoolallocationthresholdkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/kcvpixelbufferpoolallocationthresholdkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
