{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_OneComponent10"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCVPixelFormatType_1Monochrome@kCVPixelFormatType_OneComponent10",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCVPixelFormatType_OneComponent10"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSType",
        "text": "OSType"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCVPixelFormatType_OneComponent10"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCVPixelFormatType_OneComponent10"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_OneComponent10"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSType",
              "text": "OSType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16BE555": {
      "abstract": [
        {
          "text": "16-bit BE RGB 555.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_16BE555"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16BE555",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_16BE555"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_16BE555",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_16be555"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16BE565": {
      "abstract": [
        {
          "text": "16-bit BE RGB 565.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_16BE565"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16BE565",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_16BE565"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_16BE565",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_16be565"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE555": {
      "abstract": [
        {
          "text": "16-bit LE RGB 555.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_16LE555"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE555",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_16LE555"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_16LE555",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_16le555"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE5551": {
      "abstract": [
        {
          "text": "16-bit LE RGB 5551.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_16LE5551"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE5551",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_16LE5551"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_16LE5551",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_16le5551"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE565": {
      "abstract": [
        {
          "text": "16-bit LE RGB 565.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_16LE565"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE565",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_16LE565"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_16LE565",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_16le565"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_1IndexedGray_WhiteIsZero": {
      "abstract": [
        {
          "text": "1 bit indexed gray, white is zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_1IndexedGray_WhiteIsZero"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_1IndexedGray_WhiteIsZero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_1IndexedGray_WhiteIsZero"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_1IndexedGray_WhiteIsZero",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_1indexedgray_whiteiszero"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_1Monochrome": {
      "abstract": [
        {
          "text": "1 bit indexed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_1Monochrome"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_1Monochrome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_1Monochrome"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_1Monochrome",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_1monochrome"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_24BGR": {
      "abstract": [
        {
          "text": "24-bit BGR.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_24BGR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_24BGR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_24BGR"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_24BGR",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_24bgr"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_24RGB": {
      "abstract": [
        {
          "text": "24-bit RGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_24RGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_24RGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_24RGB"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_24RGB",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_24rgb"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_2Indexed": {
      "abstract": [
        {
          "text": "2-bit indexed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_2Indexed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_2Indexed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_2Indexed"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_2Indexed",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_2indexed"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_2IndexedGray_WhiteIsZero": {
      "abstract": [
        {
          "text": "2-bit indexed gray, white is zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_2IndexedGray_WhiteIsZero"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_2IndexedGray_WhiteIsZero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_2IndexedGray_WhiteIsZero"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_2IndexedGray_WhiteIsZero",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_2indexedgray_whiteiszero"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_4Indexed": {
      "abstract": [
        {
          "text": "4-bit indexed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_4Indexed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_4Indexed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_4Indexed"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_4Indexed",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_4indexed"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_4IndexedGray_WhiteIsZero": {
      "abstract": [
        {
          "text": "4-bit indexed gray, white is zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_4IndexedGray_WhiteIsZero"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_4IndexedGray_WhiteIsZero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_4IndexedGray_WhiteIsZero"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_4IndexedGray_WhiteIsZero",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_4indexedgray_whiteiszero"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_8Indexed": {
      "abstract": [
        {
          "text": "8-bit indexed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_8Indexed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_8Indexed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_8Indexed"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_8Indexed",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_8indexed"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_8IndexedGray_WhiteIsZero": {
      "abstract": [
        {
          "text": "8-bit indexed gray, white is zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_8IndexedGray_WhiteIsZero"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_8IndexedGray_WhiteIsZero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_8IndexedGray_WhiteIsZero"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_8IndexedGray_WhiteIsZero",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_8indexedgray_whiteiszero"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_OneComponent10": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_OneComponent10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_OneComponent10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_OneComponent10"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_OneComponent10",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_onecomponent10"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_1Monochrome",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_2Indexed",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_4Indexed",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_8Indexed",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_1IndexedGray_WhiteIsZero",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_2IndexedGray_WhiteIsZero",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_4IndexedGray_WhiteIsZero",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_8IndexedGray_WhiteIsZero",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16BE555",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE555",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE5551",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16BE565",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE565",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_24RGB",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_24BGR"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCVPixelFormatType_OneComponent10"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_OneComponent10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_1Monochrome",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_2Indexed",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_4Indexed",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_8Indexed",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_1IndexedGray_WhiteIsZero",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_2IndexedGray_WhiteIsZero",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_4IndexedGray_WhiteIsZero",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_8IndexedGray_WhiteIsZero",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16BE555",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE555",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE5551",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16BE565",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_16LE565",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_24RGB",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_24BGR"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCVPixelFormatType_OneComponent10"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_16LE5551/title",
          "value": "kCVPixelFormatType_16LE5551"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_16LE5551/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_16LE5551"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_16LE555/title",
          "value": "kCVPixelFormatType_16LE555"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_16LE555/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_16LE555"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_16LE565/title",
          "value": "kCVPixelFormatType_16LE565"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_16LE565/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_16LE565"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_16BE555/title",
          "value": "kCVPixelFormatType_16BE555"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_16BE555/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_16BE555"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_16BE565/title",
          "value": "kCVPixelFormatType_16BE565"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_16BE565/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_16BE565"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_4IndexedGray_WhiteIsZero/title",
          "value": "kCVPixelFormatType_4IndexedGray_WhiteIsZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_4IndexedGray_WhiteIsZero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_4IndexedGray_WhiteIsZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_24BGR/title",
          "value": "kCVPixelFormatType_24BGR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_24BGR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_24BGR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_2Indexed/title",
          "value": "kCVPixelFormatType_2Indexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_2Indexed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_2Indexed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_8IndexedGray_WhiteIsZero/title",
          "value": "kCVPixelFormatType_8IndexedGray_WhiteIsZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_8IndexedGray_WhiteIsZero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_8IndexedGray_WhiteIsZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_2IndexedGray_WhiteIsZero/title",
          "value": "kCVPixelFormatType_2IndexedGray_WhiteIsZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_2IndexedGray_WhiteIsZero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_2IndexedGray_WhiteIsZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_8Indexed/title",
          "value": "kCVPixelFormatType_8Indexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_8Indexed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_8Indexed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_OneComponent10/title",
          "value": "kCVPixelFormatType_OneComponent10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_OneComponent10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_OneComponent10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_24RGB/title",
          "value": "kCVPixelFormatType_24RGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_24RGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_24RGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_1IndexedGray_WhiteIsZero/title",
          "value": "kCVPixelFormatType_1IndexedGray_WhiteIsZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_1IndexedGray_WhiteIsZero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_1IndexedGray_WhiteIsZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_4Indexed/title",
          "value": "kCVPixelFormatType_4Indexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_4Indexed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_4Indexed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_1Monochrome/title",
          "value": "kCVPixelFormatType_1Monochrome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_1Monochrome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_1Monochrome"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/kcvpixelformattype_onecomponent10"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/kcvpixelformattype_onecomponent10"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
