{
  "abstract": [
    {
      "text": "A key to the number of pixels padding the bottom of the image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsBottomKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCVPixelBufferExtendedPixelsBottomKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCVPixelBufferExtendedPixelsBottomKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCVPixelBufferExtendedPixelsBottomKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCVPixelBufferExtendedPixelsBottomKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCVPixelBufferExtendedPixelsBottomKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value for this key is of type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferBytesPerRowAlignmentKey": {
      "abstract": [
        {
          "text": "A key to a number that specifies the alignment of number of bytes per row in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferBytesPerRowAlignmentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferBytesPerRowAlignmentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferBytesPerRowAlignmentKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferBytesPerRowAlignmentKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferbytesperrowalignmentkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGBitmapContextCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether the pixel buffer is compatible with Core Graphics bitmap contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferCGBitmapContextCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGBitmapContextCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferCGBitmapContextCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferCGBitmapContextCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbuffercgbitmapcontextcompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGImageCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether the pixel buffer is compatible with Core Graphics bitmap image types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferCGImageCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGImageCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferCGImageCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferCGImageCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbuffercgimagecompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsBottomKey": {
      "abstract": [
        {
          "text": "A key to the number of pixels padding the bottom of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsBottomKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsBottomKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsBottomKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferExtendedPixelsBottomKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferextendedpixelsbottomkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsLeftKey": {
      "abstract": [
        {
          "text": "A key to the number of pixels padding the left of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsLeftKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsLeftKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsLeftKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferExtendedPixelsLeftKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferextendedpixelsleftkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsRightKey": {
      "abstract": [
        {
          "text": "A key to the number of pixels padding the right of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsRightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsRightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsRightKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferExtendedPixelsRightKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferextendedpixelsrightkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsTopKey": {
      "abstract": [
        {
          "text": "A key to the number of pixels padding the top of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsTopKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsTopKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsTopKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferExtendedPixelsTopKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferextendedpixelstopkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferHeightKey": {
      "abstract": [
        {
          "text": "A key to the height of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferHeightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferHeightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferHeightKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferHeightKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferheightkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfacePropertiesKey": {
      "abstract": [
        {
          "text": "A key to the dictionary containing optional properties for the IOSurface framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfacePropertiesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfacePropertiesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfacePropertiesKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferIOSurfacePropertiesKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferiosurfacepropertieskey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMemoryAllocatorKey": {
      "abstract": [
        {
          "text": "A key to the allocator that the system uses to create the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferMemoryAllocatorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMemoryAllocatorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferMemoryAllocatorKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferMemoryAllocatorKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbuffermemoryallocatorkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMetalCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether the pixel buffer is compatible with the Metal framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferMetalCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMetalCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferMetalCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferMetalCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbuffermetalcompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether the pixel buffer is compatible with OpenGL contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferOpenGLCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferopenglcompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether the pixel buffer is compatible with OpenGL ES contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLESCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLESCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferOpenGLESCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferopenglescompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey": {
      "abstract": [
        {
          "text": "A key to one or more pixel buffer format types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPixelFormatTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPixelFormatTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPixelFormatTypeKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferpixelformattypekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPlaneAlignmentKey": {
      "abstract": [
        {
          "text": "A key to a number that specifies the alignment of the planes in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPlaneAlignmentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPlaneAlignmentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPlaneAlignmentKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPlaneAlignmentKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferplanealignmentkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferWidthKey": {
      "abstract": [
        {
          "text": "A key to the width of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferWidthKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferWidthKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferWidthKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferWidthKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferwidthkey"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
      "kind": "article",
      "role": "article",
      "title": "CFNumber",
      "type": "topic",
      "url": "/documentation/corefoundation/cfnumber-rjd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMemoryAllocatorKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferWidthKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferHeightKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsLeftKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsTopKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsRightKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferBytesPerRowAlignmentKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGBitmapContextCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGImageCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPlaneAlignmentKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfacePropertiesKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMetalCompatibilityKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCVPixelBufferExtendedPixelsBottomKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferExtendedPixelsBottomKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMemoryAllocatorKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferWidthKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferHeightKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsLeftKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsTopKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsRightKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferBytesPerRowAlignmentKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGBitmapContextCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGImageCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPlaneAlignmentKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfacePropertiesKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMetalCompatibilityKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCVPixelBufferExtendedPixelsBottomKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferBytesPerRowAlignmentKey/title",
          "value": "kCVPixelBufferBytesPerRowAlignmentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferBytesPerRowAlignmentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferBytesPerRowAlignmentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLESCompatibilityKey/title",
          "value": "kCVPixelBufferOpenGLESCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLESCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferOpenGLESCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsBottomKey/title",
          "value": "kCVPixelBufferExtendedPixelsBottomKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsBottomKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferExtendedPixelsBottomKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferWidthKey/title",
          "value": "kCVPixelBufferWidthKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferWidthKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferWidthKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferCGBitmapContextCompatibilityKey/title",
          "value": "kCVPixelBufferCGBitmapContextCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferCGBitmapContextCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferCGBitmapContextCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferMetalCompatibilityKey/title",
          "value": "kCVPixelBufferMetalCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferMetalCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferMetalCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfacePropertiesKey/title",
          "value": "kCVPixelBufferIOSurfacePropertiesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfacePropertiesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferIOSurfacePropertiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsLeftKey/title",
          "value": "kCVPixelBufferExtendedPixelsLeftKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsLeftKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferExtendedPixelsLeftKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPlaneAlignmentKey/title",
          "value": "kCVPixelBufferPlaneAlignmentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPlaneAlignmentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPlaneAlignmentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferHeightKey/title",
          "value": "kCVPixelBufferHeightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferHeightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferHeightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsTopKey/title",
          "value": "kCVPixelBufferExtendedPixelsTopKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsTopKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferExtendedPixelsTopKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferCGImageCompatibilityKey/title",
          "value": "kCVPixelBufferCGImageCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferCGImageCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferCGImageCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsRightKey/title",
          "value": "kCVPixelBufferExtendedPixelsRightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsRightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferExtendedPixelsRightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferMemoryAllocatorKey/title",
          "value": "kCVPixelBufferMemoryAllocatorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferMemoryAllocatorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferMemoryAllocatorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLCompatibilityKey/title",
          "value": "kCVPixelBufferOpenGLCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferOpenGLCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPixelFormatTypeKey/title",
          "value": "kCVPixelBufferPixelFormatTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPixelFormatTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPixelFormatTypeKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/kcvpixelbufferextendedpixelsbottomkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/kcvpixelbufferextendedpixelsbottomkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
