{
  "abstract": [
    {
      "text": "The attributes associated with a pixel buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/pixel-buffer-attribute-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Pixel Buffer Attribute Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the pixel buffer attribute keys to tell Core Video how to allocate pixel buffers for compatibility with client requirements. A pixel buffer attributes dictionary is a Core Foundation dictionary that contains zero or more key-value pairs. You can pass this dictionary to functions such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreate(_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreate(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To create an attributes dictionary that’s compatible for multiple clients, pass an array of each client’s attributes dictionary to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreate(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a single pixel buffer for a given size and pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreate(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreate"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferCreate(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffercreate(_:_:_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)": {
      "abstract": [
        {
          "text": "Resolves an array of ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": " objects describing various pixel buffer attributes into a single dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateResolvedAttributesDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferCreateResolvedAttributesDictionary"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffercreateresolvedattributesdictionary(_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a pixel buffer pool using the allocator and attributes that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferPoolRef",
          "text": "CVPixelBufferPool"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreate"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPoolCreate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolcreate(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e": {
      "abstract": [
        {
          "text": "An image buffer that holds pixels in main memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffer-q2e"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferBytesPerRowAlignmentKey": {
      "abstract": [
        {
          "text": "A key to a number that specifies the alignment of number of bytes per row in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferBytesPerRowAlignmentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferBytesPerRowAlignmentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferBytesPerRowAlignmentKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferBytesPerRowAlignmentKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferbytesperrowalignmentkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGBitmapContextCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether the pixel buffer is compatible with Core Graphics bitmap contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferCGBitmapContextCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGBitmapContextCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferCGBitmapContextCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferCGBitmapContextCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbuffercgbitmapcontextcompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGImageCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether the pixel buffer is compatible with Core Graphics bitmap image types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferCGImageCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGImageCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferCGImageCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferCGImageCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbuffercgimagecompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsBottomKey": {
      "abstract": [
        {
          "text": "A key to the number of pixels padding the bottom of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsBottomKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsBottomKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsBottomKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferExtendedPixelsBottomKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferextendedpixelsbottomkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsLeftKey": {
      "abstract": [
        {
          "text": "A key to the number of pixels padding the left of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsLeftKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsLeftKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsLeftKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferExtendedPixelsLeftKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferextendedpixelsleftkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsRightKey": {
      "abstract": [
        {
          "text": "A key to the number of pixels padding the right of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsRightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsRightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsRightKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferExtendedPixelsRightKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferextendedpixelsrightkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsTopKey": {
      "abstract": [
        {
          "text": "A key to the number of pixels padding the top of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsTopKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsTopKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferExtendedPixelsTopKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferExtendedPixelsTopKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferextendedpixelstopkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferHeightKey": {
      "abstract": [
        {
          "text": "A key to the height of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferHeightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferHeightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferHeightKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferHeightKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferheightkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether Core Animation can display the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferiosurfacecoreanimationcompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether OpenGL ES can create a valid texture for use as a color buffer attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferiosurfaceopenglesfbocompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether OpenGL ES can create a valid texture object from the IOSurface-backed pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferiosurfaceopenglestexturecompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether OpenGL can create a valid texture for use as a color buffer attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferiosurfaceopenglfbocompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether OpenGL can create a valid texture object from the IOSurface-backed pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferiosurfaceopengltexturecompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfacePropertiesKey": {
      "abstract": [
        {
          "text": "A key to the dictionary containing optional properties for the IOSurface framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfacePropertiesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfacePropertiesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferIOSurfacePropertiesKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferIOSurfacePropertiesKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferiosurfacepropertieskey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMemoryAllocatorKey": {
      "abstract": [
        {
          "text": "A key to the allocator that the system uses to create the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferMemoryAllocatorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMemoryAllocatorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferMemoryAllocatorKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferMemoryAllocatorKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbuffermemoryallocatorkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMetalCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether the pixel buffer is compatible with the Metal framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferMetalCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMetalCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferMetalCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferMetalCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbuffermetalcompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether the pixel buffer is compatible with OpenGL contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferOpenGLCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferopenglcompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether the pixel buffer is compatible with OpenGL ES contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLESCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLESCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferOpenGLESCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferopenglescompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESTextureCacheCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether OpenGL ES performs format conversions of the texture-cache data in a shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLESTextureCacheCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESTextureCacheCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLESTextureCacheCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferOpenGLESTextureCacheCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferopenglestexturecachecompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLTextureCacheCompatibilityKey": {
      "abstract": [
        {
          "text": "A key to a Boolean value that indicates whether OpenGL performs format conversions of the texture-cache data in a shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLTextureCacheCompatibilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLTextureCacheCompatibilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferOpenGLTextureCacheCompatibilityKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferOpenGLTextureCacheCompatibilityKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferopengltexturecachecompatibilitykey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey": {
      "abstract": [
        {
          "text": "A key to one or more pixel buffer format types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPixelFormatTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPixelFormatTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPixelFormatTypeKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferpixelformattypekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPlaneAlignmentKey": {
      "abstract": [
        {
          "text": "A key to a number that specifies the alignment of the planes in the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPlaneAlignmentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPlaneAlignmentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPlaneAlignmentKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPlaneAlignmentKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferplanealignmentkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferWidthKey": {
      "abstract": [
        {
          "text": "A key to the width of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferWidthKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferWidthKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferWidthKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferWidthKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferwidthkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMemoryAllocatorKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferWidthKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferHeightKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsLeftKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsTopKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsRightKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsBottomKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferBytesPerRowAlignmentKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGBitmapContextCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGImageCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPlaneAlignmentKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfacePropertiesKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMetalCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLTextureCacheCompatibilityKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESTextureCacheCompatibilityKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMemoryAllocatorKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferWidthKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferHeightKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsLeftKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsTopKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsRightKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferExtendedPixelsBottomKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferBytesPerRowAlignmentKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGBitmapContextCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferCGImageCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPlaneAlignmentKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfacePropertiesKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferMetalCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLTextureCacheCompatibilityKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferOpenGLESTextureCacheCompatibilityKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLESTextureCacheCompatibilityKey/title",
          "value": "kCVPixelBufferOpenGLESTextureCacheCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLESTextureCacheCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferOpenGLESTextureCacheCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferCGImageCompatibilityKey/title",
          "value": "kCVPixelBufferCGImageCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferCGImageCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferCGImageCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPixelFormatTypeKey/title",
          "value": "kCVPixelBufferPixelFormatTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPixelFormatTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPixelFormatTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsTopKey/title",
          "value": "kCVPixelBufferExtendedPixelsTopKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsTopKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferExtendedPixelsTopKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLTextureCacheCompatibilityKey/title",
          "value": "kCVPixelBufferOpenGLTextureCacheCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLTextureCacheCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferOpenGLTextureCacheCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferWidthKey/title",
          "value": "kCVPixelBufferWidthKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferWidthKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferWidthKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferHeightKey/title",
          "value": "kCVPixelBufferHeightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferHeightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferHeightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLCompatibilityKey/title",
          "value": "kCVPixelBufferOpenGLCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferOpenGLCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey/title",
          "value": "kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPlaneAlignmentKey/title",
          "value": "kCVPixelBufferPlaneAlignmentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPlaneAlignmentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPlaneAlignmentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsLeftKey/title",
          "value": "kCVPixelBufferExtendedPixelsLeftKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsLeftKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferExtendedPixelsLeftKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreate(_:_:_:_:)/title",
          "value": "CVPixelBufferPoolCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)/title",
          "value": "CVPixelBufferCreateResolvedAttributesDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreateResolvedAttributesDictionary(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferCreateResolvedAttributesDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreate(_:_:_:_:_:_:)/title",
          "value": "CVPixelBufferCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferCreate(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey/title",
          "value": "kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferIOSurfaceOpenGLFBOCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsRightKey/title",
          "value": "kCVPixelBufferExtendedPixelsRightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsRightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferExtendedPixelsRightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferMetalCompatibilityKey/title",
          "value": "kCVPixelBufferMetalCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferMetalCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferMetalCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferMemoryAllocatorKey/title",
          "value": "kCVPixelBufferMemoryAllocatorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferMemoryAllocatorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferMemoryAllocatorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfacePropertiesKey/title",
          "value": "kCVPixelBufferIOSurfacePropertiesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfacePropertiesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferIOSurfacePropertiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey/title",
          "value": "kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferIOSurfaceCoreAnimationCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsBottomKey/title",
          "value": "kCVPixelBufferExtendedPixelsBottomKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferExtendedPixelsBottomKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferExtendedPixelsBottomKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey/title",
          "value": "kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferIOSurfaceOpenGLESTextureCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferCGBitmapContextCompatibilityKey/title",
          "value": "kCVPixelBufferCGBitmapContextCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferCGBitmapContextCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferCGBitmapContextCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLESCompatibilityKey/title",
          "value": "kCVPixelBufferOpenGLESCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferOpenGLESCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferOpenGLESCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey/title",
          "value": "kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferIOSurfaceOpenGLESFBOCompatibilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferBytesPerRowAlignmentKey/title",
          "value": "kCVPixelBufferBytesPerRowAlignmentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferBytesPerRowAlignmentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferBytesPerRowAlignmentKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/pixel-buffer-attribute-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/pixel-buffer-attribute-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
