{
  "abstract": [
    {
      "text": "The attributes of a pixel format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-description-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Pixel Format Description Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you need to define a custom pixel format, you must specify these keys in a Core Foundation dictionary. For information about registering your pixel format, see ",
              "type": "text"
            },
            {
              "identifier": "http://developer.apple.com/qa/qa2005/qa1401.html",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In most cases you do not need to specify your own pixel format.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBack": {
      "abstract": [
        {
          "text": "Defines a pointer to a custom extended pixel-fill function, which is called whenever the system needs to pad a buffer holding your custom pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVFillExtendedPixelsCallBack"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVFillExtendedPixelsCallBack"
        }
      ],
      "role": "symbol",
      "title": "CVFillExtendedPixelsCallBack",
      "type": "topic",
      "url": "/documentation/corevideo/cvfillextendedpixelscallback"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData": {
      "abstract": [
        {
          "text": "A structure for holding information that describes a custom extended pixel fill algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVFillExtendedPixelsCallBackData"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVFillExtendedPixelsCallBackData"
        }
      ],
      "role": "symbol",
      "title": "CVFillExtendedPixelsCallBackData",
      "type": "topic",
      "url": "/documentation/corevideo/cvfillextendedpixelscallbackdata"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription": {
      "abstract": [
        {
          "text": "An API that provides functions and types for defining custom pixel formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelFormatDescription",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelformatdescription"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBitsPerBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBitsPerBlock"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatBitsPerBlock",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatbitsperblock"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlackBlock": {
      "abstract": [
        {
          "text": "The bit pattern for a block of black pixels (type ",
          "type": "text"
        },
        {
          "code": "CFData",
          "type": "codeVoice"
        },
        {
          "text": ". If this key is absent, black is assumed to be all zeros. If present, this should be ",
          "type": "text"
        },
        {
          "code": "bitsPerPixel",
          "type": "codeVoice"
        },
        {
          "text": " bits long; if ",
          "type": "text"
        },
        {
          "code": "bitsPerPixel",
          "type": "codeVoice"
        },
        {
          "text": " is less than a byte, repeat the bit pattern for the full byte.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlackBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlackBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlackBlock"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatBlackBlock",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatblackblock"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHeight": {
      "abstract": [
        {
          "text": "The height, in pixels, of the smallest byte-addressable group of pixels (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": "). Assumed to be 1 if this key is not present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockHeight"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatBlockHeight",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatblockheight"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHorizontalAlignment": {
      "abstract": [
        {
          "text": "The horizontal alignment requirements of this format (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": "). For example,the alignment for v210 would be 8 here for the horizontal case to match the standard v210 row alignment value of 48. Assumed to be 1 if this key is not present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockHorizontalAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHorizontalAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockHorizontalAlignment"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatBlockHorizontalAlignment",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatblockhorizontalalignment"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockVerticalAlignment": {
      "abstract": [
        {
          "text": "The vertical alignment requirements of this format (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": "). Assumed to be 1 if this key is not present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockVerticalAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockVerticalAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockVerticalAlignment"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatBlockVerticalAlignment",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatblockverticalalignment"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockWidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBlockWidth"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatBlockWidth",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatblockwidth"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGBitmapContextCompatibility": {
      "abstract": [
        {
          "text": "If true, this format is compatible with Core Graphics bitmap contexts(type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatCGBitmapContextCompatibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGBitmapContextCompatibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatCGBitmapContextCompatibility"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatCGBitmapContextCompatibility",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcgbitmapcontextcompatibility"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGBitmapInfo": {
      "abstract": [
        {
          "text": "The Core Graphics bitmap information for this pixel format (if applicable).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatCGBitmapInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGBitmapInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatCGBitmapInfo"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatCGBitmapInfo",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcgbitmapinfo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGImageCompatibility": {
      "abstract": [
        {
          "text": "If true, this format is compatible with the ",
          "type": "text"
        },
        {
          "code": "CGImage",
          "type": "codeVoice"
        },
        {
          "text": " type (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatCGImageCompatibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGImageCompatibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatCGImageCompatibility"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatCGImageCompatibility",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcgimagecompatibility"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCodecType": {
      "abstract": [
        {
          "text": "The codec type (type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": "). For example, ",
          "type": "text"
        },
        {
          "code": "'2vuy'",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "k422YpCbCr8CodecType",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatCodecType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatCodecType"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatCodecType",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcodectype"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatComponentRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcomponentrange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_FullRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_FullRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_FullRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_FullRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatComponentRange_FullRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcomponentrange_fullrange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_VideoRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_VideoRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_VideoRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_VideoRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatComponentRange_VideoRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcomponentrange_videorange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_WideRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_WideRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_WideRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatComponentRange_WideRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatComponentRange_WideRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcomponentrange_widerange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatConstant": {
      "abstract": [
        {
          "text": "The pixel format constant for QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatConstant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatConstant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatConstant"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatConstant",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatconstant"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsAlpha": {
      "abstract": [
        {
          "text": "A Boolean value where ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " indicates that the format contains alpha and some images may be considered transparent; ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " indicates that there is no alpha and images are always opaque.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsAlpha"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatContainsAlpha",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcontainsalpha"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsRGB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsRGB"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatContainsRGB",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcontainsrgb"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsYCbCr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsYCbCr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsYCbCr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatContainsYCbCr"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatContainsYCbCr",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatcontainsycbcr"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFillExtendedPixelsCallback": {
      "abstract": [
        {
          "text": "A custom extended pixel fill algorithm (type ",
          "type": "text"
        },
        {
          "code": "CFData",
          "type": "codeVoice"
        },
        {
          "text": "). See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBack",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVFillExtendedPixelsCallBackData",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for more information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatFillExtendedPixelsCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFillExtendedPixelsCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatFillExtendedPixelsCallback"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatFillExtendedPixelsCallback",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatfillextendedpixelscallback"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFourCC": {
      "abstract": [
        {
          "text": "The Microsoft FourCC equivalent code for this pixel format (type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatFourCC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFourCC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatFourCC"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatFourCC",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatfourcc"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatHorizontalSubsampling": {
      "abstract": [
        {
          "text": "Horizontal subsampling information for this plane (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": "). Assumed to be 1 if this key is not present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatHorizontalSubsampling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatHorizontalSubsampling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatHorizontalSubsampling"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatHorizontalSubsampling",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformathorizontalsubsampling"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatName": {
      "abstract": [
        {
          "text": "The name of the pixel format (type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": "). This should be the same as the codec name you would use in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatName"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatName",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatname"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLCompatibility": {
      "abstract": [
        {
          "text": "If true, this format is compatible with OpenGL (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatOpenGLCompatibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLCompatibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatOpenGLCompatibility"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatOpenGLCompatibility",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatopenglcompatibility"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLESCompatibility": {
      "abstract": [
        {
          "text": "If true, this format is compatible with OpenGLES (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatOpenGLESCompatibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLESCompatibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatOpenGLESCompatibility"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatOpenGLESCompatibility",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatopenglescompatibility"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLFormat": {
      "abstract": [
        {
          "text": "The OpenGL format used to describe this image plane (if applicable). See the ",
          "type": "text"
        },
        {
          "identifier": "http://www.opengl.org/documentation/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for possible values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatOpenGLFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatOpenGLFormat"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatOpenGLFormat",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatopenglformat"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLInternalFormat": {
      "abstract": [
        {
          "text": "The OpenGL internal format for this pixel format (if applicable). See the ",
          "type": "text"
        },
        {
          "identifier": "http://www.opengl.org/documentation/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for possible values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatOpenGLInternalFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLInternalFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatOpenGLInternalFormat"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatOpenGLInternalFormat",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatopenglinternalformat"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLType": {
      "abstract": [
        {
          "text": "The OpenGL type to describe this image plane (if applicable). See the ",
          "type": "text"
        },
        {
          "identifier": "http://www.opengl.org/documentation/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for possible values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatOpenGLType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatOpenGLType"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatOpenGLType",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatopengltype"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatPlanes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatPlanes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatPlanes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatPlanes"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatPlanes",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatplanes"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatQDCompatibility": {
      "abstract": [
        {
          "text": "If true, this format is compatible with QuickDraw (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatQDCompatibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatQDCompatibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatQDCompatibility"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatQDCompatibility",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatqdcompatibility"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatVerticalSubsampling": {
      "abstract": [
        {
          "text": "Vertical subsampling information for this plane (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": "). Assumed to be 1 if this key is not present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatVerticalSubsampling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatVerticalSubsampling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatVerticalSubsampling"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatVerticalSubsampling",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatverticalsubsampling"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-identifiers": {
      "abstract": [
        {
          "text": "Core Video does not provide support for all of these formats; this list defines only their names.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Format Identifiers",
      "type": "topic",
      "url": "/documentation/corevideo/pixel-format-identifiers"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse": {
      "abstract": [
        {
          "text": "Boolean false value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanFalse"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanFalse",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleanfalse"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue": {
      "abstract": [
        {
          "text": "Boolean true value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanTrue"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanTrue",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleantrue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "http://developer.apple.com/qa/qa2005/qa1401.html": {
      "identifier": "http://developer.apple.com/qa/qa2005/qa1401.html",
      "title": "Technical Q&A 1401: Registering Custom Pixel Formats with QuickTime and Core Video",
      "titleInlineContent": [
        {
          "text": "Technical Q&A 1401: Registering Custom Pixel Formats with QuickTime and Core Video",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://developer.apple.com/qa/qa2005/qa1401.html"
    },
    "http://www.opengl.org/documentation/": {
      "identifier": "http://www.opengl.org/documentation/",
      "title": "OpenGL specification",
      "titleInlineContent": [
        {
          "text": "OpenGL specification",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.opengl.org/documentation/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/pixel-format-identifiers"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_FullRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_VideoRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_WideRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsRGB",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsYCbCr",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatName",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatConstant",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCodecType",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFourCC",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsAlpha",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatPlanes",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockWidth",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHeight",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerBlock",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHorizontalAlignment",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockVerticalAlignment",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlackBlock",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatHorizontalSubsampling",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatVerticalSubsampling",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLFormat",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLType",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLInternalFormat",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGBitmapInfo",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatQDCompatibility",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGBitmapContextCompatibility",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGImageCompatibility",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLCompatibility",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLESCompatibility",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFillExtendedPixelsCallback"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_FullRange",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_VideoRange",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatComponentRange_WideRange",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsRGB",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsYCbCr",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatName",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatConstant",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCodecType",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFourCC",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatContainsAlpha",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatPlanes",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockWidth",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHeight",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerBlock",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockHorizontalAlignment",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlockVerticalAlignment",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBlackBlock",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatHorizontalSubsampling",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatVerticalSubsampling",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLFormat",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLType",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLInternalFormat",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGBitmapInfo",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatQDCompatibility",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGBitmapContextCompatibility",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatCGImageCompatibility",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLCompatibility",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatOpenGLESCompatibility",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatFillExtendedPixelsCallback"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBack/title",
          "value": "CVFillExtendedPixelsCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_FullRange/title",
          "value": "kCVPixelFormatComponentRange_FullRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_FullRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatComponentRange_FullRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatQDCompatibility/title",
          "value": "kCVPixelFormatQDCompatibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatQDCompatibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatQDCompatibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatOpenGLESCompatibility/title",
          "value": "kCVPixelFormatOpenGLESCompatibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatOpenGLESCompatibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatOpenGLESCompatibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBitsPerBlock/title",
          "value": "kCVPixelFormatBitsPerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBitsPerBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBitsPerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatOpenGLInternalFormat/title",
          "value": "kCVPixelFormatOpenGLInternalFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatOpenGLInternalFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatOpenGLInternalFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_WideRange/title",
          "value": "kCVPixelFormatComponentRange_WideRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_WideRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatComponentRange_WideRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockWidth/title",
          "value": "kCVPixelFormatBlockWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBlockWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatFillExtendedPixelsCallback/title",
          "value": "kCVPixelFormatFillExtendedPixelsCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatFillExtendedPixelsCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatFillExtendedPixelsCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_VideoRange/title",
          "value": "kCVPixelFormatComponentRange_VideoRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange_VideoRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatComponentRange_VideoRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatConstant/title",
          "value": "kCVPixelFormatConstant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatConstant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatConstant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlackBlock/title",
          "value": "kCVPixelFormatBlackBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlackBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBlackBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatOpenGLCompatibility/title",
          "value": "kCVPixelFormatOpenGLCompatibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatOpenGLCompatibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatOpenGLCompatibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsRGB/title",
          "value": "kCVPixelFormatContainsRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatContainsRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatCGBitmapInfo/title",
          "value": "kCVPixelFormatCGBitmapInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatCGBitmapInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatCGBitmapInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatCGImageCompatibility/title",
          "value": "kCVPixelFormatCGImageCompatibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatCGImageCompatibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatCGImageCompatibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatCodecType/title",
          "value": "kCVPixelFormatCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatOpenGLFormat/title",
          "value": "kCVPixelFormatOpenGLFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatOpenGLFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatOpenGLFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockVerticalAlignment/title",
          "value": "kCVPixelFormatBlockVerticalAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockVerticalAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBlockVerticalAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsYCbCr/title",
          "value": "kCVPixelFormatContainsYCbCr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsYCbCr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatContainsYCbCr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockHorizontalAlignment/title",
          "value": "kCVPixelFormatBlockHorizontalAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockHorizontalAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBlockHorizontalAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatVerticalSubsampling/title",
          "value": "kCVPixelFormatVerticalSubsampling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatVerticalSubsampling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatVerticalSubsampling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatName/title",
          "value": "kCVPixelFormatName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsAlpha/title",
          "value": "kCVPixelFormatContainsAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatContainsAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatContainsAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatCGBitmapContextCompatibility/title",
          "value": "kCVPixelFormatCGBitmapContextCompatibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatCGBitmapContextCompatibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatCGBitmapContextCompatibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatOpenGLType/title",
          "value": "kCVPixelFormatOpenGLType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatOpenGLType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatOpenGLType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange/title",
          "value": "kCVPixelFormatComponentRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatComponentRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatComponentRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatPlanes/title",
          "value": "kCVPixelFormatPlanes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatPlanes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatPlanes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData/title",
          "value": "CVFillExtendedPixelsCallBackData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBackData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVFillExtendedPixelsCallBackData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVFillExtendedPixelsCallBackData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatFourCC/title",
          "value": "kCVPixelFormatFourCC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatFourCC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatFourCC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockHeight/title",
          "value": "kCVPixelFormatBlockHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBlockHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBlockHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatHorizontalSubsampling/title",
          "value": "kCVPixelFormatHorizontalSubsampling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatHorizontalSubsampling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatHorizontalSubsampling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/pixel-format-description-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/pixel-format-description-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
