{
  "abstract": [
    {
      "text": "Describes the result codes generated by Core Video operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/result-codes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Result Codes"
  },
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o": {
      "abstract": [
        {
          "text": "A utility object for managing a recyclable set of pixel buffer objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpool-77o"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new pixel buffer with auxiliary attributes from the pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferPoolRef",
          "text": "CVPixelBufferPool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
        }
      ],
      "role": "symbol",
      "title": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpoolcreatepixelbufferwithauxattributes(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k": {
      "abstract": [
        {
          "text": "A high-priority thread that notifies your app when a given display will need each frame.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVDisplayLink",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylink-k0k"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e": {
      "abstract": [
        {
          "text": "An image buffer that holds pixels in main memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffer-q2e"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/data-types": {
      "abstract": [
        {
          "text": "Common data types used by the Core Video framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Types",
      "type": "topic",
      "url": "/documentation/corevideo/data-types"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolAllocationThresholdKey": {
      "abstract": [
        {
          "text": "The key you use to set the auxiliary attributes dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolAllocationThresholdKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolAllocationThresholdKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPoolAllocationThresholdKey"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelBufferPoolAllocationThresholdKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelbufferpoolallocationthresholdkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnAllocationFailed": {
      "abstract": [
        {
          "text": "Memory allocation for a buffer or buffer pool failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnAllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnAllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnAllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnAllocationFailed",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnallocationfailed"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkAlreadyRunning": {
      "abstract": [
        {
          "text": "The specified display link is already running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnDisplayLinkAlreadyRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkAlreadyRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnDisplayLinkAlreadyRunning"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnDisplayLinkAlreadyRunning",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturndisplaylinkalreadyrunning"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkCallbacksNotSet": {
      "abstract": [
        {
          "text": "No callback registered for the specified display link. You must set either the output callback or both the render and display callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnDisplayLinkCallbacksNotSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkCallbacksNotSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnDisplayLinkCallbacksNotSet"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnDisplayLinkCallbacksNotSet",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturndisplaylinkcallbacksnotset"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkNotRunning": {
      "abstract": [
        {
          "text": "The specified display link is not running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnDisplayLinkNotRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkNotRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnDisplayLinkNotRunning"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnDisplayLinkNotRunning",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturndisplaylinknotrunning"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnError": {
      "abstract": [
        {
          "text": "An otherwise undefined error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnError"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnError",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnerror"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnFirst": {
      "abstract": [
        {
          "text": "Placeholder to mark the beginning of Core Video result codes (not returned by any functions).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnFirst"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnFirst",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnfirst"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidArgument": {
      "abstract": [
        {
          "text": "Invalid function parameter. For example, out of range or the wrong type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidArgument"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnInvalidArgument",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturninvalidargument"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidDisplay": {
      "abstract": [
        {
          "text": "The display specified when creating a display link is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidDisplay"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnInvalidDisplay",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturninvaliddisplay"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPixelBufferAttributes": {
      "abstract": [
        {
          "text": "A buffer cannot be created with the specified attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidPixelBufferAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPixelBufferAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidPixelBufferAttributes"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnInvalidPixelBufferAttributes",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturninvalidpixelbufferattributes"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPixelFormat": {
      "abstract": [
        {
          "text": "The buffer does not support the specified pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidPixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnInvalidPixelFormat",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturninvalidpixelformat"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPoolAttributes": {
      "abstract": [
        {
          "text": "A buffer pool cannot be created with the specified attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidPoolAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPoolAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidPoolAttributes"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnInvalidPoolAttributes",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturninvalidpoolattributes"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidSize": {
      "abstract": [
        {
          "text": "The buffer cannot support the requested buffer size (usually too big).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnInvalidSize"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnInvalidSize",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturninvalidsize"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnLast": {
      "abstract": [
        {
          "text": "Placeholder to mark the end of Core Video result codes (not returned by any functions).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnLast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnLast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnLast"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnLast",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnlast"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPixelBufferNotMetalCompatible": {
      "abstract": [
        {
          "text": "The pixel buffer is not compatible with Metal due to an unsupported buffer size, pixel format, or attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnPixelBufferNotMetalCompatible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPixelBufferNotMetalCompatible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnPixelBufferNotMetalCompatible"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnPixelBufferNotMetalCompatible",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnpixelbuffernotmetalcompatible"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPixelBufferNotOpenGLCompatible": {
      "abstract": [
        {
          "text": "The pixel buffer is not compatible with OpenGL due to an unsupported buffer size, pixel format, or attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnPixelBufferNotOpenGLCompatible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPixelBufferNotOpenGLCompatible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnPixelBufferNotOpenGLCompatible"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnPixelBufferNotOpenGLCompatible",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnpixelbuffernotopenglcompatible"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPoolAllocationFailed": {
      "abstract": [
        {
          "text": "Allocation for a buffer pool failed, most likely due to a lack of resources. Check to make sure your parameters are in range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnPoolAllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPoolAllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnPoolAllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnPoolAllocationFailed",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnpoolallocationfailed"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnRetry": {
      "abstract": [
        {
          "text": "A scan hasn’t completely traversed the ",
          "type": "text"
        },
        {
          "code": "CVBufferPool",
          "type": "codeVoice"
        },
        {
          "text": " due to a concurrent operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnRetry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnRetry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnRetry"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnRetry",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnretry"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnSuccess": {
      "abstract": [
        {
          "text": "Indicates the operation completed successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnSuccess"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnSuccess",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnsuccess"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnUnsupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnUnsupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnUnsupported"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnUnsupported",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnunsupported"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnWouldExceedAllocationThreshold": {
      "abstract": [
        {
          "text": "Allocation for a pixel buffer failed because the threshold value set for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelBufferPoolAllocationThresholdKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function would be surpassed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVReturnWouldExceedAllocationThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnWouldExceedAllocationThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVReturnWouldExceedAllocationThreshold"
        }
      ],
      "role": "symbol",
      "title": "kCVReturnWouldExceedAllocationThreshold",
      "type": "topic",
      "url": "/documentation/corevideo/kcvreturnwouldexceedallocationthreshold"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Core-Video-Error-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/data-types"
      ],
      "title": "Core Video Error Constants"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Result codes related to a number of Core Video operations.",
          "type": "text"
        }
      ],
      "anchor": "Common",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnAllocationFailed",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnError",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidArgument",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnSuccess",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnUnsupported",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnLast",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnFirst"
      ],
      "title": "Common"
    },
    {
      "abstract": [
        {
          "text": "Result codes related to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " operations.",
          "type": "text"
        }
      ],
      "anchor": "Pixel-Buffer",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPixelBufferAttributes",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPixelFormat",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidSize",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPixelBufferNotMetalCompatible",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPixelBufferNotOpenGLCompatible"
      ],
      "title": "Pixel Buffer"
    },
    {
      "abstract": [
        {
          "text": "Result codes related to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " operations.",
          "type": "text"
        }
      ],
      "anchor": "Buffer-Pool",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnRetry",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPoolAttributes",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPoolAllocationFailed",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnWouldExceedAllocationThreshold"
      ],
      "title": "Buffer Pool"
    },
    {
      "abstract": [
        {
          "text": "Result codes related to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " operations.",
          "type": "text"
        }
      ],
      "anchor": "Display-Link",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidDisplay",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkAlreadyRunning",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkNotRunning",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkCallbacksNotSet"
      ],
      "title": "Display Link"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Result codes related to a number of Core Video operations.",
                  "type": "text"
                }
              ],
              "anchor": "Common",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnAllocationFailed",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnError",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidArgument",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnSuccess",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnUnsupported",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnLast",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnFirst"
              ],
              "title": "Common"
            },
            {
              "abstract": [
                {
                  "text": "Result codes related to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " operations.",
                  "type": "text"
                }
              ],
              "anchor": "Pixel-Buffer",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPixelBufferAttributes",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPixelFormat",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidSize",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPixelBufferNotMetalCompatible",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPixelBufferNotOpenGLCompatible"
              ],
              "title": "Pixel Buffer"
            },
            {
              "abstract": [
                {
                  "text": "Result codes related to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " operations.",
                  "type": "text"
                }
              ],
              "anchor": "Buffer-Pool",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnRetry",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidPoolAttributes",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnPoolAllocationFailed",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnWouldExceedAllocationThreshold"
              ],
              "title": "Buffer Pool"
            },
            {
              "abstract": [
                {
                  "text": "Result codes related to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " operations.",
                  "type": "text"
                }
              ],
              "anchor": "Display-Link",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnInvalidDisplay",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkAlreadyRunning",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkNotRunning",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVReturnDisplayLinkCallbacksNotSet"
              ],
              "title": "Display Link"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Core-Video-Error-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/data-types"
              ],
              "title": "Core Video Error Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnDisplayLinkAlreadyRunning/title",
          "value": "kCVReturnDisplayLinkAlreadyRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnDisplayLinkAlreadyRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnDisplayLinkAlreadyRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidPixelBufferAttributes/title",
          "value": "kCVReturnInvalidPixelBufferAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidPixelBufferAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnInvalidPixelBufferAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnFirst/title",
          "value": "kCVReturnFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnError/title",
          "value": "kCVReturnError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnDisplayLinkCallbacksNotSet/title",
          "value": "kCVReturnDisplayLinkCallbacksNotSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnDisplayLinkCallbacksNotSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnDisplayLinkCallbacksNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidArgument/title",
          "value": "kCVReturnInvalidArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnInvalidArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidDisplay/title",
          "value": "kCVReturnInvalidDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnInvalidDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnAllocationFailed/title",
          "value": "kCVReturnAllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnAllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnAllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)/title",
          "value": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPixelBufferPoolCreatePixelBufferWithAuxAttributes(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPixelBufferPoolCreatePixelBufferWithAuxAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnDisplayLinkNotRunning/title",
          "value": "kCVReturnDisplayLinkNotRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnDisplayLinkNotRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnDisplayLinkNotRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnSuccess/title",
          "value": "kCVReturnSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnPoolAllocationFailed/title",
          "value": "kCVReturnPoolAllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnPoolAllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnPoolAllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnUnsupported/title",
          "value": "kCVReturnUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnLast/title",
          "value": "kCVReturnLast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnLast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnLast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnPixelBufferNotMetalCompatible/title",
          "value": "kCVReturnPixelBufferNotMetalCompatible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnPixelBufferNotMetalCompatible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnPixelBufferNotMetalCompatible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnPixelBufferNotOpenGLCompatible/title",
          "value": "kCVReturnPixelBufferNotOpenGLCompatible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnPixelBufferNotOpenGLCompatible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnPixelBufferNotOpenGLCompatible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidPoolAttributes/title",
          "value": "kCVReturnInvalidPoolAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidPoolAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnInvalidPoolAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidPixelFormat/title",
          "value": "kCVReturnInvalidPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnInvalidPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolAllocationThresholdKey/title",
          "value": "kCVPixelBufferPoolAllocationThresholdKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelBufferPoolAllocationThresholdKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPoolAllocationThresholdKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnRetry/title",
          "value": "kCVReturnRetry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnRetry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnRetry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnWouldExceedAllocationThreshold/title",
          "value": "kCVReturnWouldExceedAllocationThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnWouldExceedAllocationThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnWouldExceedAllocationThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidSize/title",
          "value": "kCVReturnInvalidSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVReturnInvalidSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVReturnInvalidSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/result-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/result-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
