{
  "abstract": [
    {
      "text": "Apple Pay Later is unavailable because one or more ineligible or prohibited items are in the shopping cart, such as gift cards.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Apple Pay Later is deprecated.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability/unavailableItemIneligible"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKApplePayLaterAvailability@PKApplePayLaterUnavailableItemIneligible",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unavailableItemIneligible"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKApplePayLaterUnavailableItemIneligible"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKApplePayLaterAvailability.unavailableItemIneligible"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unavailableItemIneligible"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability": {
      "abstract": [
        {
          "text": "Values you use to enable or disable Apple Pay Later for a specific transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKApplePayLaterAvailability"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKApplePayLaterAvailability"
        }
      ],
      "role": "symbol",
      "title": "PKApplePayLaterAvailability",
      "type": "topic",
      "url": "/documentation/passkit/pkapplepaylateravailability"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability/available": {
      "abstract": [
        {
          "text": "Apple Pay Later is available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "available"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability/available",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKApplePayLaterAvailable"
        }
      ],
      "role": "symbol",
      "title": "PKApplePayLaterAvailability.available",
      "type": "topic",
      "url": "/documentation/passkit/pkapplepaylateravailability/available"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability/unavailableItemIneligible": {
      "abstract": [
        {
          "text": "Apple Pay Later is unavailable because one or more ineligible or prohibited items are in the shopping cart, such as gift cards.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unavailableItemIneligible"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability/unavailableItemIneligible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKApplePayLaterUnavailableItemIneligible"
        }
      ],
      "role": "symbol",
      "title": "PKApplePayLaterAvailability.unavailableItemIneligible",
      "type": "topic",
      "url": "/documentation/passkit/pkapplepaylateravailability/unavailableitemineligible"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability/unavailableRecurringTransaction": {
      "abstract": [
        {
          "text": "Apple Pay Later is unavailable because there’s a recurring payment or subscription in the shopping cart.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unavailableRecurringTransaction"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability/unavailableRecurringTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKApplePayLaterUnavailableRecurringTransaction"
        }
      ],
      "role": "symbol",
      "title": "PKApplePayLaterAvailability.unavailableRecurringTransaction",
      "type": "topic",
      "url": "/documentation/passkit/pkapplepaylateravailability/unavailablerecurringtransaction"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Availability-values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability/available",
        "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability/unavailableRecurringTransaction"
      ],
      "title": "Availability values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKApplePayLaterUnavailableItemIneligible"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKApplePayLaterUnavailableItemIneligible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Availability-values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability/available",
                "doc://com.apple.passkit/documentation/PassKit/PKApplePayLaterAvailability/unavailableRecurringTransaction"
              ],
              "title": "Availability values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKApplePayLaterUnavailableItemIneligible"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Apple Pay Later is deprecated.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKApplePayLaterAvailability~1unavailableRecurringTransaction/title",
          "value": "PKApplePayLaterUnavailableRecurringTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKApplePayLaterAvailability~1unavailableRecurringTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKApplePayLaterUnavailableRecurringTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKApplePayLaterAvailability~1unavailableItemIneligible/title",
          "value": "PKApplePayLaterUnavailableItemIneligible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKApplePayLaterAvailability~1unavailableItemIneligible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKApplePayLaterUnavailableItemIneligible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKApplePayLaterAvailability/title",
          "value": "PKApplePayLaterAvailability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKApplePayLaterAvailability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKApplePayLaterAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKApplePayLaterAvailability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKApplePayLaterAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKApplePayLaterAvailability~1available/title",
          "value": "PKApplePayLaterAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKApplePayLaterAvailability~1available/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKApplePayLaterAvailable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkapplepaylateravailability/unavailableitemineligible"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkapplepaylateravailability/unavailableitemineligible"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
