{
  "abstract": [
    {
      "text": "Indicates that no key modifier should be used.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyModifierFlags/XCUIKeyModifierNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCUIKeyModifierFlags@XCUIKeyModifierNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "XCUIKeyModifierNone"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIKeyModifierNone"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "XCUIKeyModifierNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags": {
      "abstract": [
        {
          "text": "Flags for simulating combination keystrokes with keys, such as Control, Option, Shift, and Command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/KeyModifierFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KeyModifierFlags"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.KeyModifierFlags",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/keymodifierflags"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyModifierFlags/XCUIKeyModifierNone": {
      "abstract": [
        {
          "text": "Indicates that no key modifier should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUIKeyModifierNone"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyModifierFlags/XCUIKeyModifierNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUIKeyModifierNone",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeymodifierflags/xcuikeymodifiernone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags/title",
          "value": "XCUIKeyModifierFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1KeyModifierFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyModifierFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuikeymodifierflags/xcuikeymodifiernone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
