{
  "abstract": [
    {
      "text": "Returns the shared instance representing a target application specified by",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "its process identifier.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge",
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithProcessIdentifier:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SBApplication(cm)applicationWithProcessIdentifier:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "applicationWithProcessIdentifier:"
      }
    ],
    "modules": [
      {
        "name": "Scripting Bridge"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "applicationWithProcessIdentifier:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "applicationWithProcessIdentifier:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SBApplication",
              "text": "SBApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "applicationWithProcessIdentifier:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@pid_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@pid_t",
              "text": "pid_t"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "pid"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The BSD process ID of a OSA-compliant application. Often you can get",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "the process ID of a process using the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nstask/1412022-processidentifier",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "method of ",
                  "type": "text"
                },
                {
                  "code": "NSTask",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pid"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An instance of an ",
              "type": "text"
            },
            {
              "code": "SBApplication",
              "type": "codeVoice"
            },
            {
              "text": " subclass that represents the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "target application whose process identifier is ",
              "type": "text"
            },
            {
              "code": "pid",
              "type": "codeVoice"
            },
            {
              "text": ". Returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if no",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "such application can be found or if the application does not have a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "scripting interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You should avoid using this method unless you know nothing about a target",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "application but its process ID. In most cases, it is better to use",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithBundleIdentifier:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which will dynamically",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "locate the application’s path at runtime, or",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithURL:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which is not dependent on the target",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "application being open at the time the method is called.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge": {
      "abstract": [
        {
          "text": "Automate scriptable apps by sending and receiving Apple events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge",
      "kind": "symbol",
      "role": "collection",
      "title": "Scripting Bridge",
      "type": "topic",
      "url": "/documentation/scriptingbridge"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "SBApplication",
          "type": "codeVoice"
        },
        {
          "text": " class provides a mechanism enabling an Objective-C",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "program to send Apple events to a scriptable application and receive Apple",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "events in response. It thereby makes it possible for that program to control",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the application and exchange data with it. Scripting Bridge works by",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "bridging data types between Apple event descriptors and Cocoa objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SBApplication"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SBApplication"
        }
      ],
      "role": "symbol",
      "title": "SBApplication",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplication"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithBundleIdentifier:": {
      "abstract": [
        {
          "text": "Returns the shared instance representing the target application specified by",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "its bundle identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "applicationWithBundleIdentifier:"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithBundleIdentifier:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationWithBundleIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "applicationWithBundleIdentifier:",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplication/applicationwithbundleidentifier:"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithProcessIdentifier:": {
      "abstract": [
        {
          "text": "Returns the shared instance representing a target application specified by",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "its process identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "applicationWithProcessIdentifier:"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithProcessIdentifier:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationWithProcessIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "applicationWithProcessIdentifier:",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplication/applicationwithprocessidentifier:"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithURL:": {
      "abstract": [
        {
          "text": "Returns the shared instance representing a target application specified by",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "applicationWithURL:"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithURL:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationWithURL:"
        }
      ],
      "role": "symbol",
      "title": "applicationWithURL:",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplication/applicationwithurl:"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(processIdentifier:)": {
      "abstract": [
        {
          "text": "Returns an instance of an ",
          "type": "text"
        },
        {
          "code": "SBApplication",
          "type": "codeVoice"
        },
        {
          "text": " subclass that represents the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "target application identified by the given process identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "processIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(processIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithProcessIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(processIdentifier:)",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplication/init(processidentifier:)"
    },
    "doc://com.apple.documentation/documentation/foundation/nstask/1412022-processidentifier": {
      "abstract": [
        {
          "text": "The receiver’s process identifier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nstask/1412022-processidentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "processIdentifier",
      "type": "topic",
      "url": "/documentation/foundation/nstask/1412022-processidentifier"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@pid_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@pid_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "pid_t",
      "type": "topic",
      "url": "/documentation/kernel/pid_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(processIdentifier:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Getting-a-Scriptable-Application-Instance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithBundleIdentifier:",
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithURL:"
      ],
      "title": "Getting a Scriptable Application Instance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "add",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nstask~11412022-processidentifier/fragments",
          "value": [
            {
              "kind": "text",
              "text": "var "
            },
            {
              "kind": "identifier",
              "text": "processIdentifier"
            },
            {
              "kind": "text",
              "text": ": Int32"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication/title",
          "value": "SBApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SBApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SBApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication~1init(processIdentifier:)/title",
          "value": "initWithProcessIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication~1init(processIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithProcessIdentifier:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scriptingbridge/sbapplication/applicationwithprocessidentifier:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
