{
  "abstract": [
    {
      "text": "Returns an instance of an ",
      "type": "text"
    },
    {
      "code": "SBApplication",
      "type": "codeVoice"
    },
    {
      "text": " subclass that represents the",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "target application identified by the given bundle identifier.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge",
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(bundleIdentifier:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SBApplication(im)initWithBundleIdentifier:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "bundleIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Scripting Bridge"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithBundleIdentifier:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(bundleIdentifier:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "bundleIdentifier"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ident"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A bundle identifier specifying an application that is",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "OSA-compliant.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ident"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An initialized shared instance of an ",
              "type": "text"
            },
            {
              "code": "SBApplication",
              "type": "codeVoice"
            },
            {
              "text": " subclass",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that represents a target application with the bundle identifier of ",
              "type": "text"
            },
            {
              "code": "ident",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if no such application can be found or if the application does",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "not have a scripting interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you must initialize an ",
              "type": "text"
            },
            {
              "code": "SBApplication",
              "type": "codeVoice"
            },
            {
              "text": " object explictly, you should use",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "this initializer if possible; unlike",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(processIdentifier:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(url:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", this method is not dependent on changeable",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "factors such as the target application’s path or process ID. Even so, you",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "should rarely have to initialize an ",
              "type": "text"
            },
            {
              "code": "SBApplication",
              "type": "codeVoice"
            },
            {
              "text": " object yourself;",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instead, you should initialize an application-specific subclass such as",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "iTunesApplication",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Note that this method does not check whether an application with the given",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "bundle identifier actually exists.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge": {
      "abstract": [
        {
          "text": "Automate scriptable apps by sending and receiving Apple events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge",
      "kind": "symbol",
      "role": "collection",
      "title": "Scripting Bridge",
      "type": "topic",
      "url": "/documentation/scriptingbridge"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "SBApplication",
          "type": "codeVoice"
        },
        {
          "text": " class provides a mechanism enabling an Objective-C",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "program to send Apple events to a scriptable application and receive Apple",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "events in response. It thereby makes it possible for that program to control",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the application and exchange data with it. Scripting Bridge works by",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "bridging data types between Apple event descriptors and Cocoa objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SBApplication"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SBApplication"
        }
      ],
      "role": "symbol",
      "title": "SBApplication",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplication"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithBundleIdentifier:": {
      "abstract": [
        {
          "text": "Returns the shared instance representing the target application specified by",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "its bundle identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "applicationWithBundleIdentifier:"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithBundleIdentifier:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationWithBundleIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "applicationWithBundleIdentifier:",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplication/applicationwithbundleidentifier:"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(bundleIdentifier:)": {
      "abstract": [
        {
          "text": "Returns an instance of an ",
          "type": "text"
        },
        {
          "code": "SBApplication",
          "type": "codeVoice"
        },
        {
          "text": " subclass that represents the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "target application identified by the given bundle identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "bundleIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(bundleIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBundleIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(bundleIdentifier:)",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplication/init(bundleidentifier:)"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(processIdentifier:)": {
      "abstract": [
        {
          "text": "Returns an instance of an ",
          "type": "text"
        },
        {
          "code": "SBApplication",
          "type": "codeVoice"
        },
        {
          "text": " subclass that represents the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "target application identified by the given process identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "processIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(processIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithProcessIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(processIdentifier:)",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplication/init(processidentifier:)"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(url:)": {
      "abstract": [
        {
          "text": "Returns an instance of an ",
          "type": "text"
        },
        {
          "code": "SBApplication",
          "type": "codeVoice"
        },
        {
          "text": " subclass that represents the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "target application identified by the given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(url:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithURL:"
        }
      ],
      "role": "symbol",
      "title": "init(url:)",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplication/init(url:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializing-a-Scriptable-Application-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(processIdentifier:)",
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(url:)"
      ],
      "title": "Initializing a Scriptable Application Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithBundleIdentifier:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithBundleIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge",
                "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/applicationWithBundleIdentifier:"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Initializing-a-Scriptable-Application-Object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(processIdentifier:)",
                "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication/init(url:)"
              ],
              "title": "Initializing a Scriptable Application Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplication",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SBApplication",
                    "text": "SBApplication"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithBundleIdentifier:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "ident"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A bundle identifier specifying an application that is",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "OSA-compliant.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "ident"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An initialized shared instance of an ",
                    "type": "text"
                  },
                  {
                    "code": "SBApplication",
                    "type": "codeVoice"
                  },
                  {
                    "text": " subclass",
                    "type": "text"
                  },
                  {
                    "text": " ",
                    "type": "text"
                  },
                  {
                    "text": "that represents a target application with the bundle identifier of ",
                    "type": "text"
                  },
                  {
                    "code": "ident",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  },
                  {
                    "text": " ",
                    "type": "text"
                  },
                  {
                    "text": "Returns ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if no such application can be found or if the application does",
                    "type": "text"
                  },
                  {
                    "text": " ",
                    "type": "text"
                  },
                  {
                    "text": "not have a scripting interface.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication~1init(processIdentifier:)/title",
          "value": "initWithProcessIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication~1init(processIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithProcessIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication/title",
          "value": "SBApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SBApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SBApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication~1init(bundleIdentifier:)/title",
          "value": "initWithBundleIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication~1init(bundleIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithBundleIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication~1init(url:)/title",
          "value": "initWithURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplication~1init(url:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURL:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scriptingbridge/sbapplication/init(bundleidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scriptingbridge/sbapplication/init(bundleidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
