{
  "abstract": [
    {
      "text": "A Boolean value indicating whether to download all sidecar files along with the media file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/sidecarFiles"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ImageCaptureCore",
    "externalID": "c:@ICDownloadSidecarFiles",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sidecarFiles"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ICDownloadOption",
        "text": "ICDownloadOption"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICDownloadSidecarFiles"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "sidecarFiles"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sidecarFiles"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ICDownloadOption",
              "text": "ICDownloadOption"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Specify this value as an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption": {
      "abstract": [
        {
          "text": "An option for downloading a file from the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDownloadOption"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDownloadOption"
        }
      ],
      "role": "symbol",
      "title": "ICDownloadOption",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdownloadoption"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/deleteAfterSuccessfulDownload": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to delete the file from the device after a successful download.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteAfterSuccessfulDownload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDownloadOption",
          "text": "ICDownloadOption"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/deleteAfterSuccessfulDownload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeleteAfterSuccessfulDownload"
        }
      ],
      "role": "symbol",
      "title": "deleteAfterSuccessfulDownload",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdownloadoption/deleteaftersuccessfuldownload"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/downloadsDirectoryURL": {
      "abstract": [
        {
          "text": "A writable directory where the downloaded files should be saved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadsDirectoryURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDownloadOption",
          "text": "ICDownloadOption"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/downloadsDirectoryURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDownloadsDirectoryURL"
        }
      ],
      "role": "symbol",
      "title": "downloadsDirectoryURL",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdownloadoption/downloadsdirectoryurl"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/overwrite": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the downloaded file should overwrite an existing file with the same name and extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overwrite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDownloadOption",
          "text": "ICDownloadOption"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/overwrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICOverwrite"
        }
      ],
      "role": "symbol",
      "title": "overwrite",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdownloadoption/overwrite"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/saveAsFilename": {
      "abstract": [
        {
          "text": "The name to be used for the downloaded file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveAsFilename"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDownloadOption",
          "text": "ICDownloadOption"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/saveAsFilename",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICSaveAsFilename"
        }
      ],
      "role": "symbol",
      "title": "saveAsFilename",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdownloadoption/saveasfilename"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/savedAncillaryFiles": {
      "abstract": [
        {
          "text": "An array of files associated with the file being downloaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "savedAncillaryFiles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDownloadOption",
          "text": "ICDownloadOption"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/savedAncillaryFiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICSavedAncillaryFiles"
        }
      ],
      "role": "symbol",
      "title": "savedAncillaryFiles",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdownloadoption/savedancillaryfiles"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/savedFilename": {
      "abstract": [
        {
          "text": "The actual name of the saved file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "savedFilename"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDownloadOption",
          "text": "ICDownloadOption"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/savedFilename",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICSavedFilename"
        }
      ],
      "role": "symbol",
      "title": "savedFilename",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdownloadoption/savedfilename"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/sidecarFiles": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to download all sidecar files along with the media file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sidecarFiles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDownloadOption",
          "text": "ICDownloadOption"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/sidecarFiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDownloadSidecarFiles"
        }
      ],
      "role": "symbol",
      "title": "sidecarFiles",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdownloadoption/sidecarfiles"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Download-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/downloadsDirectoryURL",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/saveAsFilename",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/savedFilename",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/savedAncillaryFiles",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/overwrite",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/deleteAfterSuccessfulDownload"
      ],
      "title": "Download Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICDownloadSidecarFiles"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDownloadSidecarFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Download-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/downloadsDirectoryURL",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/saveAsFilename",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/savedFilename",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/savedAncillaryFiles",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/overwrite",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption/deleteAfterSuccessfulDownload"
              ],
              "title": "Download Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDownloadOption",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ICDownloadOption",
                    "text": "ICDownloadOption"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICDownloadSidecarFiles"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1deleteAfterSuccessfulDownload/title",
          "value": "ICDeleteAfterSuccessfulDownload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1deleteAfterSuccessfulDownload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeleteAfterSuccessfulDownload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1saveAsFilename/title",
          "value": "ICSaveAsFilename"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1saveAsFilename/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICSaveAsFilename"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1downloadsDirectoryURL/title",
          "value": "ICDownloadsDirectoryURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1downloadsDirectoryURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDownloadsDirectoryURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1savedFilename/title",
          "value": "ICSavedFilename"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1savedFilename/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICSavedFilename"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1overwrite/title",
          "value": "ICOverwrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1overwrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICOverwrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1sidecarFiles/title",
          "value": "ICDownloadSidecarFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1sidecarFiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDownloadSidecarFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption/title",
          "value": "ICDownloadOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDownloadOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDownloadOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1savedAncillaryFiles/title",
          "value": "ICSavedAncillaryFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDownloadOption~1savedAncillaryFiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICSavedAncillaryFiles"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icdownloadoption/sidecarfiles"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icdownloadoption/sidecarfiles"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
