{
  "abstract": [
    {
      "text": "A verdict to drop a packet.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict/drop"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEFilterPacketProviderVerdict@NEFilterPacketProviderVerdictDrop",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "drop"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEFilterPacketProviderVerdictDrop"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEFilterPacketProvider.Verdict.drop"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "drop"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider": {
      "abstract": [
        {
          "text": "A filter provider that evaluates network packets and decides whether to block, allow, or delay the packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterPacketProvider"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterPacketProvider"
        }
      ],
      "role": "symbol",
      "title": "NEFilterPacketProvider",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterpacketprovider"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict": {
      "abstract": [
        {
          "text": "The verdict returned by a packet handler indicating what the framework should do with a packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Verdict"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Verdict"
        }
      ],
      "role": "symbol",
      "title": "NEFilterPacketProvider.Verdict",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterpacketprovider/verdict"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict/allow": {
      "abstract": [
        {
          "text": "A verdict to allow a packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allow"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict/allow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterPacketProviderVerdictAllow"
        }
      ],
      "role": "symbol",
      "title": "NEFilterPacketProvider.Verdict.allow",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterpacketprovider/verdict/allow"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict/delay": {
      "abstract": [
        {
          "text": "A verdict to delay a packet until a future verdict.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delay"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict/delay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterPacketProviderVerdictDelay"
        }
      ],
      "role": "symbol",
      "title": "NEFilterPacketProvider.Verdict.delay",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterpacketprovider/verdict/delay"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict/drop": {
      "abstract": [
        {
          "text": "A verdict to drop a packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drop"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict/drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterPacketProviderVerdictDrop"
        }
      ],
      "role": "symbol",
      "title": "NEFilterPacketProvider.Verdict.drop",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterpacketprovider/verdict/drop"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Verdicts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict/allow",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict/delay"
      ],
      "title": "Verdicts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEFilterPacketProviderVerdictDrop"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterPacketProviderVerdictDrop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Verdicts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict/allow",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterPacketProvider/Verdict/delay"
              ],
              "title": "Verdicts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEFilterPacketProviderVerdictDrop"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider~1Verdict~1drop/title",
          "value": "NEFilterPacketProviderVerdictDrop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider~1Verdict~1drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterPacketProviderVerdictDrop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider/title",
          "value": "NEFilterPacketProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterPacketProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterPacketProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider~1Verdict/title",
          "value": "NEFilterPacketProviderVerdict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider~1Verdict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterPacketProviderVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider~1Verdict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterPacketProviderVerdict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider~1Verdict~1allow/title",
          "value": "NEFilterPacketProviderVerdictAllow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider~1Verdict~1allow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterPacketProviderVerdictAllow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider~1Verdict~1delay/title",
          "value": "NEFilterPacketProviderVerdictDelay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterPacketProvider~1Verdict~1delay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterPacketProviderVerdictDelay"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nefilterpacketprovider/verdict/drop"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nefilterpacketprovider/verdict/drop"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
