{
  "abstract": [
    {
      "text": "The user needs to launch the app to update the user’s affinity for the media.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/failureRequiringAppLaunch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INUpdateMediaAffinityIntentResponseCode@INUpdateMediaAffinityIntentResponseCodeFailureRequiringAppLaunch",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failureRequiringAppLaunch"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INUpdateMediaAffinityIntentResponseCodeFailureRequiringAppLaunch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INUpdateMediaAffinityIntentResponseCode.failureRequiringAppLaunch"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failureRequiringAppLaunch"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this response code when you can’t handle the request with Siri for a reason not covered by any other response code. For example, you might use this code if the user hasn’t set up an account with your app. Don’t use it for general errors or to force the user to launch your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode": {
      "abstract": [
        {
          "text": "Codes returned by an intents handler in response to an update media affinity request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinityintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "The app is unable to update the user’s affinity for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinityintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user needs to launch the app to update the user’s affinity for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinityintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/inProgress": {
      "abstract": [
        {
          "text": "The app is currently trying to process the update affinity request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinityintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "The app is ready.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinityintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/success": {
      "abstract": [
        {
          "text": "The app successfully updated the user’s affinity for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinityintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "An unknown state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUpdateMediaAffinityIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INUpdateMediaAffinityIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/inupdatemediaaffinityintentresponsecode/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Response-Code",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/failure"
      ],
      "title": "Response Code"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INUpdateMediaAffinityIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Response-Code",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INUpdateMediaAffinityIntentResponseCode/failure"
              ],
              "title": "Response Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INUpdateMediaAffinityIntentResponseCodeFailureRequiringAppLaunch"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1inProgress/title",
          "value": "INUpdateMediaAffinityIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode/title",
          "value": "INUpdateMediaAffinityIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1ready/title",
          "value": "INUpdateMediaAffinityIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1unspecified/title",
          "value": "INUpdateMediaAffinityIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INUpdateMediaAffinityIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1success/title",
          "value": "INUpdateMediaAffinityIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1failure/title",
          "value": "INUpdateMediaAffinityIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUpdateMediaAffinityIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUpdateMediaAffinityIntentResponseCodeFailure"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inupdatemediaaffinityintentresponsecode/failurerequiringapplaunch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inupdatemediaaffinityintentresponsecode/failurerequiringapplaunch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
