{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For most view controllers, UIKit maps this style to:"}]},{"items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet","isActive":true},{"type":"text","text":" in iOS 18 and later"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet"},{"type":"text","text":" in versions of iOS earlier than iOS 18"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Some system view controllers may map it to a different style."}]}],"kind":"content"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"UIModalPresentationAutomatic","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"UIKit"}],"externalID":"c:@E@UIModalPresentationStyle@UIModalPresentationAutomatic","platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"13.0","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"13.0","beta":false},{"beta":false,"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"13.0","name":"tvOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS","unavailable":false}],"role":"symbol","title":"UIModalPresentationStyle.automatic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"roleHeading":"Case"},"seeAlsoSections":[{"anchor":"Presentations","title":"Presentations","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overCurrentContext","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen"],"generated":true}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/automatic","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle"]]},"sections":[],"variants":[{"paths":["/documentation/uikit/uimodalpresentationstyle/automatic"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uimodalpresentationstyle/automatic"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The default presentation style chosen by the system.","type":"text"}],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/automatic":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.automatic","navigatorTitle":[{"text":"UIModalPresentationAutomatic","kind":"identifier"}],"url":"/documentation/uikit/uimodalpresentationstyle/automatic","abstract":[{"text":"The default presentation style chosen by the system.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"automatic","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/automatic"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overCurrentContext":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationOverCurrentContext"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"overCurrentContext"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overCurrentContext","url":"/documentation/uikit/uimodalpresentationstyle/overcurrentcontext","type":"topic","kind":"symbol","title":"UIModalPresentationStyle.overCurrentContext","abstract":[{"type":"text","text":"A presentation style where the content is displayed over another view controller’s content."}]},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.pageSheet","navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationPageSheet"}],"url":"/documentation/uikit/uimodalpresentationstyle/pagesheet","abstract":[{"text":"A presentation style that partially covers the underlying content.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSheet"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none":{"navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationNone"}],"type":"topic","title":"UIModalPresentationStyle.none","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none","url":"/documentation/uikit/uimodalpresentationstyle/none","abstract":[{"type":"text","text":"A presentation style that indicates no adaptations should be made."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}]},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.custom","navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationCustom"}],"url":"/documentation/uikit/uimodalpresentationstyle/custom","abstract":[{"text":"A custom view presentation style that is managed by a custom presentation controller and one or more custom animator objects.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationFormSheet"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"formSheet"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet","url":"/documentation/uikit/uimodalpresentationstyle/formsheet","type":"topic","kind":"symbol","title":"UIModalPresentationStyle.formSheet","abstract":[{"type":"text","text":"A presentation style that displays the content centered in the screen."}]},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.overFullScreen","navigatorTitle":[{"text":"UIModalPresentationOverFullScreen","kind":"identifier"}],"url":"/documentation/uikit/uimodalpresentationstyle/overfullscreen","abstract":[{"text":"A view presentation style in which the presented view covers the screen.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"overFullScreen","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A presentation style where the content is displayed in a popover view."}],"navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationPopover"}],"title":"UIModalPresentationStyle.popover","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"popover"}],"url":"/documentation/uikit/uimodalpresentationstyle/popover"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle":{"role":"symbol","title":"UIModalPresentationStyle","abstract":[{"type":"text","text":"Modal presentation styles available when presenting view controllers."}],"navigatorTitle":[{"text":"UIModalPresentationStyle","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIModalPresentationStyle","kind":"identifier"}],"url":"/documentation/uikit/uimodalpresentationstyle","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen":{"navigatorTitle":[{"text":"UIModalPresentationFullScreen","kind":"identifier"}],"type":"topic","title":"UIModalPresentationStyle.fullScreen","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen","url":"/documentation/uikit/uimodalpresentationstyle/fullscreen","abstract":[{"type":"text","text":"A presentation style in which the presented view covers the screen."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fullScreen","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.currentContext","navigatorTitle":[{"text":"UIModalPresentationCurrentContext","kind":"identifier"}],"url":"/documentation/uikit/uimodalpresentationstyle/currentcontext","abstract":[{"text":"A presentation style where the content is displayed over another view controller’s content.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentContext","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.blurOverFullScreen","navigatorTitle":[{"text":"UIModalPresentationBlurOverFullScreen","kind":"identifier"}],"url":"/documentation/uikit/uimodalpresentationstyle/bluroverfullscreen","abstract":[{"text":"A presentation style that blurs the underlying content before displaying new content in a full-screen presentation.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"blurOverFullScreen"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","introducedAt":"13.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"13.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","introducedAt":"13.0","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","introducedAt":"1.0","beta":false,"deprecated":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"UIModalPresentationAutomatic"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"UIModalPresentationAutomatic"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overCurrentContext","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen"],"anchor":"Presentations","title":"Presentations"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"UIModalPresentationAutomatic","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1automatic/title","value":"UIModalPresentationAutomatic"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1automatic/fragments","op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationAutomatic"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overCurrentContext/title","op":"replace","value":"UIModalPresentationOverCurrentContext"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overCurrentContext/fragments","op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationOverCurrentContext"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1pageSheet/title","op":"replace","value":"UIModalPresentationPageSheet"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1pageSheet/fragments","op":"replace","value":[{"text":"UIModalPresentationPageSheet","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1none/title","op":"replace","value":"UIModalPresentationNone"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1none/fragments","op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationNone"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1custom/title","op":"replace","value":"UIModalPresentationCustom"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1custom/fragments","op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationCustom"}]},{"op":"replace","value":"UIModalPresentationFormSheet","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1formSheet/title"},{"op":"replace","value":[{"text":"UIModalPresentationFormSheet","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1formSheet/fragments"},{"op":"replace","value":"UIModalPresentationOverFullScreen","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overFullScreen/title"},{"op":"replace","value":[{"text":"UIModalPresentationOverFullScreen","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overFullScreen/fragments"},{"op":"replace","value":"UIModalPresentationPopover","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1popover/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationPopover"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1popover/fragments"},{"op":"replace","value":"UIModalPresentationStyle","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationStyle"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/fragments"},{"op":"replace","value":[{"text":"UIModalPresentationStyle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/navigatorTitle"},{"op":"replace","value":"UIModalPresentationFullScreen","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1fullScreen/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationFullScreen"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1fullScreen/fragments"},{"op":"replace","value":"UIModalPresentationCurrentContext","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1currentContext/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationCurrentContext"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1currentContext/fragments"},{"op":"replace","value":"UIModalPresentationBlurOverFullScreen","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1blurOverFullScreen/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationBlurOverFullScreen"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1blurOverFullScreen/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}