{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle"]]},"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationOverCurrentContext"}],"title":"UIModalPresentationStyle.overCurrentContext","role":"symbol","symbolKind":"case","platforms":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"8.0"},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"8.0"},{"beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1"},{"beta":false,"deprecated":false,"name":"tvOS","unavailable":false},{"beta":false,"deprecated":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"externalID":"c:@E@UIModalPresentationStyle@UIModalPresentationOverCurrentContext","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"overCurrentContext"}],"modules":[{"name":"UIKit"}]},"kind":"symbol","variants":[{"paths":["/documentation/uikit/uimodalpresentationstyle/overcurrentcontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uimodalpresentationstyle/overcurrentcontext"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A presentation style where the content is displayed over another view controller’s content."}],"sections":[],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overCurrentContext","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overCurrentContext","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"Using this presentation style, the current view controller’s content is displayed over the view controller whose "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController/definesPresentationContext"},{"type":"text","text":" property is "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":". UIKit may walk up the view controller hierarchy to find a view controller that wants to define the presentation context. The views beneath the presented content are not removed from the view hierarchy when the presentation finishes. So if the presented view controller does not fill the screen with opaque content, the underlying content shows through."}],"type":"paragraph"},{"inlineContent":[{"text":"When presenting a view controller in a popover, this presentation style is supported only if the transition style is ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/coverVertical"},{"text":". Attempting to use a different transition style triggers an exception. However, you may use other transition styles (except the partial curl transition) if the parent view controller is not in a popover.","type":"text"}],"type":"paragraph"}]}],"seeAlsoSections":[{"title":"Presentations","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/automatic","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen"],"anchor":"Presentations"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/automatic":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.automatic","navigatorTitle":[{"text":"UIModalPresentationAutomatic","kind":"identifier"}],"url":"/documentation/uikit/uimodalpresentationstyle/automatic","abstract":[{"text":"The default presentation style chosen by the system.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"automatic","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/automatic"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen":{"navigatorTitle":[{"text":"UIModalPresentationFullScreen","kind":"identifier"}],"type":"topic","title":"UIModalPresentationStyle.fullScreen","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen","url":"/documentation/uikit/uimodalpresentationstyle/fullscreen","abstract":[{"type":"text","text":"A presentation style in which the presented view covers the screen."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fullScreen","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.overFullScreen","navigatorTitle":[{"text":"UIModalPresentationOverFullScreen","kind":"identifier"}],"url":"/documentation/uikit/uimodalpresentationstyle/overfullscreen","abstract":[{"text":"A view presentation style in which the presented view covers the screen.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"overFullScreen","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen"},"doc://com.apple.uikit/documentation/UIKit/UIViewController/definesPresentationContext":{"kind":"symbol","title":"definesPresentationContext","abstract":[{"type":"text","text":"A Boolean value that indicates whether this view controller’s view is covered when the view controller or one of its descendants presents a view controller."}],"navigatorTitle":[{"kind":"identifier","text":"definesPresentationContext"}],"url":"/documentation/uikit/uiviewcontroller/definespresentationcontext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"definesPresentationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController/definesPresentationContext","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.currentContext","navigatorTitle":[{"text":"UIModalPresentationCurrentContext","kind":"identifier"}],"url":"/documentation/uikit/uimodalpresentationstyle/currentcontext","abstract":[{"text":"A presentation style where the content is displayed over another view controller’s content.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentContext","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext"},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle":{"role":"symbol","title":"UIModalPresentationStyle","abstract":[{"type":"text","text":"Modal presentation styles available when presenting view controllers."}],"navigatorTitle":[{"text":"UIModalPresentationStyle","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIModalPresentationStyle","kind":"identifier"}],"url":"/documentation/uikit/uimodalpresentationstyle","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A presentation style where the content is displayed in a popover view."}],"navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationPopover"}],"title":"UIModalPresentationStyle.popover","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"popover"}],"url":"/documentation/uikit/uimodalpresentationstyle/popover"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overCurrentContext":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationOverCurrentContext"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"overCurrentContext"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overCurrentContext","url":"/documentation/uikit/uimodalpresentationstyle/overcurrentcontext","type":"topic","kind":"symbol","title":"UIModalPresentationStyle.overCurrentContext","abstract":[{"type":"text","text":"A presentation style where the content is displayed over another view controller’s content."}]},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.blurOverFullScreen","navigatorTitle":[{"text":"UIModalPresentationBlurOverFullScreen","kind":"identifier"}],"url":"/documentation/uikit/uimodalpresentationstyle/bluroverfullscreen","abstract":[{"text":"A presentation style that blurs the underlying content before displaying new content in a full-screen presentation.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"blurOverFullScreen"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen"},"doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/coverVertical":{"kind":"symbol","abstract":[],"role":"symbol","url":"/documentation/uikit/uimodaltransitionstyle/coververtical","type":"topic","title":"UIModalTransitionStyle.coverVertical","navigatorTitle":[{"text":"UIModalTransitionStyleCoverVertical","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coverVertical","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/coverVertical"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.custom","navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationCustom"}],"url":"/documentation/uikit/uimodalpresentationstyle/custom","abstract":[{"text":"A custom view presentation style that is managed by a custom presentation controller and one or more custom animator objects.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet":{"kind":"symbol","type":"topic","role":"symbol","title":"UIModalPresentationStyle.pageSheet","navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationPageSheet"}],"url":"/documentation/uikit/uimodalpresentationstyle/pagesheet","abstract":[{"text":"A presentation style that partially covers the underlying content.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSheet"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationFormSheet"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"formSheet"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet","url":"/documentation/uikit/uimodalpresentationstyle/formsheet","type":"topic","kind":"symbol","title":"UIModalPresentationStyle.formSheet","abstract":[{"type":"text","text":"A presentation style that displays the content centered in the screen."}]},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none":{"navigatorTitle":[{"kind":"identifier","text":"UIModalPresentationNone"}],"type":"topic","title":"UIModalPresentationStyle.none","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none","url":"/documentation/uikit/uimodalpresentationstyle/none","abstract":[{"type":"text","text":"A presentation style that indicates no adaptations should be made."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"8.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"introducedAt":"8.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"introducedAt":"13.1","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","deprecated":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration Case","path":"/metadata/roleHeading","op":"replace"},{"value":"UIModalPresentationOverCurrentContext","path":"/metadata/title","op":"replace"},{"value":"case","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"UIModalPresentationOverCurrentContext","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Presentations","generated":true,"title":"Presentations","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/automatic","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover","doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"UIModalPresentationOverCurrentContext"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"UIModalPresentationAutomatic","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1automatic/title","op":"replace"},{"value":[{"text":"UIModalPresentationAutomatic","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1automatic/fragments","op":"replace"},{"value":"UIModalPresentationFullScreen","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1fullScreen/title","op":"replace"},{"value":[{"text":"UIModalPresentationFullScreen","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1fullScreen/fragments","op":"replace"},{"op":"replace","value":"UIModalPresentationOverFullScreen","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overFullScreen/title"},{"op":"replace","value":[{"text":"UIModalPresentationOverFullScreen","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overFullScreen/fragments"},{"op":"replace","value":"definesPresentationContext","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1definesPresentationContext/title"},{"op":"replace","value":[{"text":"definesPresentationContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1definesPresentationContext/fragments"},{"op":"replace","value":"UIModalPresentationCurrentContext","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1currentContext/title"},{"op":"replace","value":[{"text":"UIModalPresentationCurrentContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1currentContext/fragments"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/title","op":"replace","value":"UIModalPresentationStyle"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/fragments","op":"replace","value":[{"text":"UIModalPresentationStyle","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationStyle"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1popover/title","op":"replace","value":"UIModalPresentationPopover"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1popover/fragments","op":"replace","value":[{"text":"UIModalPresentationPopover","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overCurrentContext/title","op":"replace","value":"UIModalPresentationOverCurrentContext"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overCurrentContext/fragments","op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationOverCurrentContext"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1blurOverFullScreen/title","op":"replace","value":"UIModalPresentationBlurOverFullScreen"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1blurOverFullScreen/fragments","op":"replace","value":[{"text":"UIModalPresentationBlurOverFullScreen","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle~1coverVertical/title","op":"replace","value":"UIModalTransitionStyleCoverVertical"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle~1coverVertical/fragments","op":"replace","value":[{"kind":"identifier","text":"UIModalTransitionStyleCoverVertical"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1custom/title","op":"replace","value":"UIModalPresentationCustom"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1custom/fragments","op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationCustom"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1pageSheet/title","op":"replace","value":"UIModalPresentationPageSheet"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1pageSheet/fragments","op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationPageSheet"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1formSheet/title","op":"replace","value":"UIModalPresentationFormSheet"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1formSheet/fragments","op":"replace","value":[{"kind":"identifier","text":"UIModalPresentationFormSheet"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1none/title","op":"replace","value":"UIModalPresentationNone"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1none/fragments","op":"replace","value":[{"text":"UIModalPresentationNone","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}