{
  "abstract": [
    {
      "text": "A presentation style where the content is displayed in a popover view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIModalPresentationStyle@UIModalPresentationPopover",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "popover"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIModalPresentationPopover"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIModalPresentationStyle.popover"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "popover"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In a horizontally regular environment, this style displays the view controller in a popover view. The background content is dimmed and taps outside the popover cause the popover to be dismissed. If you do not want taps to dismiss the popover, you can assign one or more views to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/passthroughViews",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the associated ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, which you can get from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/popoverPresentationController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 13 and later, for horizontally or vertically compact environments, this option behaves the same as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 12 and earlier:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For horizontally compact environments, this option behaves the same as ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For horizontally regular and vertically compact environments, this option behaves the same as ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about horizontal and vertical size classes, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceSizeClass",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle": {
      "abstract": [
        {
          "text": "Modal presentation styles available when presenting view controllers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIModalPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationStyle"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/automatic": {
      "abstract": [
        {
          "text": "The default presentation style chosen by the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen": {
      "abstract": [
        {
          "text": "A presentation style that blurs the underlying content before displaying new content in a full-screen presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blurOverFullScreen"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationBlurOverFullScreen"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.blurOverFullScreen",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/bluroverfullscreen"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext": {
      "abstract": [
        {
          "text": "A presentation style where the content is displayed over another view controller’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationCurrentContext"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.currentContext",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/currentcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom": {
      "abstract": [
        {
          "text": "A custom view presentation style that is managed by a custom presentation controller and one or more custom animator objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationCustom"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.custom",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/custom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet": {
      "abstract": [
        {
          "text": "A presentation style that displays the content centered in the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formSheet"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationFormSheet"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.formSheet",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/formsheet"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen": {
      "abstract": [
        {
          "text": "A presentation style in which the presented view covers the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreen"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationFullScreen"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.fullScreen",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/fullscreen"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none": {
      "abstract": [
        {
          "text": "A presentation style that indicates no adaptations should be made.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationNone"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.none",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overCurrentContext": {
      "abstract": [
        {
          "text": "A presentation style where the content is displayed over another view controller’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overCurrentContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overCurrentContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationOverCurrentContext"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.overCurrentContext",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/overcurrentcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen": {
      "abstract": [
        {
          "text": "A view presentation style in which the presented view covers the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overFullScreen"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationOverFullScreen"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.overFullScreen",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/overfullscreen"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet": {
      "abstract": [
        {
          "text": "A presentation style that partially covers the underlying content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageSheet"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationPageSheet"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.pageSheet",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/pagesheet"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover": {
      "abstract": [
        {
          "text": "A presentation style where the content is displayed in a popover view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popover"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationPopover"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.popover",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/popover"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController": {
      "abstract": [
        {
          "text": "An object that manages the display of content in a popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverPresentationController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPopoverPresentationController"
        }
      ],
      "role": "symbol",
      "title": "UIPopoverPresentationController",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/passthroughViews": {
      "abstract": [
        {
          "text": "An array of views that the user can interact with while the popover is visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passthroughViews"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/passthroughViews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passthroughViews"
        }
      ],
      "role": "symbol",
      "title": "passthroughViews",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/passthroughviews"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceSizeClass": {
      "abstract": [
        {
          "text": "Constants that indicate the size class of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserInterfaceSizeClass"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceSizeClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceSizeClass"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceSizeClass",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfacesizeclass"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/popoverPresentationController": {
      "abstract": [
        {
          "text": "The nearest popover presentation controller that is managing the current view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverPresentationController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPopoverPresentationController",
          "text": "UIPopoverPresentationController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/popoverPresentationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverPresentationController"
        }
      ],
      "role": "symbol",
      "title": "popoverPresentationController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/popoverpresentationcontroller"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presentations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none",
        "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen",
        "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet",
        "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet",
        "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext",
        "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom",
        "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen",
        "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overCurrentContext",
        "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen"
      ],
      "title": "Presentations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIModalPresentationPopover"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationPopover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presentations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/none",
                "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/fullScreen",
                "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/pageSheet",
                "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/formSheet",
                "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/currentContext",
                "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/custom",
                "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overFullScreen",
                "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/overCurrentContext",
                "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/blurOverFullScreen"
              ],
              "title": "Presentations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIModalPresentationPopover"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1popover/title",
          "value": "UIModalPresentationPopover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1popover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationPopover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1fullScreen/title",
          "value": "UIModalPresentationFullScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1fullScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationFullScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1passthroughViews/title",
          "value": "passthroughViews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1passthroughViews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "passthroughViews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1blurOverFullScreen/title",
          "value": "UIModalPresentationBlurOverFullScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1blurOverFullScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationBlurOverFullScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController/title",
          "value": "UIPopoverPresentationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/title",
          "value": "UIModalPresentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overCurrentContext/title",
          "value": "UIModalPresentationOverCurrentContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overCurrentContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationOverCurrentContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1formSheet/title",
          "value": "UIModalPresentationFormSheet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1formSheet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationFormSheet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1none/title",
          "value": "UIModalPresentationNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceSizeClass/title",
          "value": "UIUserInterfaceSizeClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceSizeClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceSizeClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceSizeClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceSizeClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1automatic/title",
          "value": "UIModalPresentationAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1pageSheet/title",
          "value": "UIModalPresentationPageSheet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1pageSheet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationPageSheet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overFullScreen/title",
          "value": "UIModalPresentationOverFullScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1overFullScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationOverFullScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1custom/title",
          "value": "UIModalPresentationCustom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1custom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationCustom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1popoverPresentationController/title",
          "value": "popoverPresentationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1popoverPresentationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "popoverPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1currentContext/title",
          "value": "UIModalPresentationCurrentContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1currentContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationCurrentContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uimodalpresentationstyle/popover"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uimodalpresentationstyle/popover"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
