{
  "abstract": [
    {
      "text": "A style indicating that the toolbar appears below the window title.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/expanded"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITitlebarToolbarStyle@UITitlebarToolbarStyleExpanded",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "expanded"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITitlebarToolbarStyleExpanded"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UITitlebarToolbarStyle.expanded"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "expanded"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle": {
      "abstract": [
        {
          "text": "Styles that determine the toolbar’s appearance and location related to the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITitlebarToolbarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarToolbarStyle"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarToolbarStyle",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartoolbarstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/automatic": {
      "abstract": [
        {
          "text": "A style indicating that the system determines the toolbar’s appearance and location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarToolbarStyleAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarToolbarStyle.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartoolbarstyle/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/expanded": {
      "abstract": [
        {
          "text": "A style indicating that the toolbar appears below the window title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expanded"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/expanded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarToolbarStyleExpanded"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarToolbarStyle.expanded",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartoolbarstyle/expanded"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/preference": {
      "abstract": [
        {
          "text": "A style indicating that the toolbar appears below the window title with toolbar items centered in the toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preference"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/preference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarToolbarStylePreference"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarToolbarStyle.preference",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartoolbarstyle/preference"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/unified": {
      "abstract": [
        {
          "text": "A style indicating that the toolbar appears inline with the window title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/unified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarToolbarStyleUnified"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarToolbarStyle.unified",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartoolbarstyle/unified"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/unifiedCompact": {
      "abstract": [
        {
          "text": "A style indicating that the toolbar appears inline with the window title and with reduced margins to allow more focus on the window’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unifiedCompact"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/unifiedCompact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarToolbarStyleUnifiedCompact"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarToolbarStyle.unifiedCompact",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartoolbarstyle/unifiedcompact"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/preference",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/unified",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/unifiedCompact"
      ],
      "title": "Styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITitlebarToolbarStyleExpanded"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarToolbarStyleExpanded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/preference",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/unified",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle/unifiedCompact"
              ],
              "title": "Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UITitlebarToolbarStyleExpanded"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle~1unified/title",
          "value": "UITitlebarToolbarStyleUnified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle~1unified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarToolbarStyleUnified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle~1expanded/title",
          "value": "UITitlebarToolbarStyleExpanded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle~1expanded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarToolbarStyleExpanded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle~1unifiedCompact/title",
          "value": "UITitlebarToolbarStyleUnifiedCompact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle~1unifiedCompact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarToolbarStyleUnifiedCompact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle~1automatic/title",
          "value": "UITitlebarToolbarStyleAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarToolbarStyleAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle~1preference/title",
          "value": "UITitlebarToolbarStylePreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle~1preference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarToolbarStylePreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle/title",
          "value": "UITitlebarToolbarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarToolbarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarToolbarStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uititlebartoolbarstyle/expanded"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uititlebartoolbarstyle/expanded"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
