{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"inlineContent":[{"text":"QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)","type":"text"}],"type":"paragraph"}],"seeAlsoSections":[{"title":"Managing Rendering","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/startRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/isRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/autostartsRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/setAutostartsRendering(_:)","doc://com.apple.quartz/documentation/Quartz/QCView/stopRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/pauseRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/resumeRendering()"],"generated":true,"anchor":"Managing-Rendering"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPausedRendering"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"text":" if the rendering is paused; otherwise ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":".","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartz/documentation/Quartz","doc://com.apple.quartz/documentation/Quartz/QCView"]]},"abstract":[{"type":"text","text":"Returns whether or not the rendering in the view is paused."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.quartz/documentation/Quartz/QCView/isPausedRendering()"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/quartz/qcview/ispausedrendering()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/quartz/qcview/ispausedrendering()"]}],"metadata":{"role":"symbol","platforms":[{"deprecated":false,"beta":false,"message":"QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)","deprecatedAt":"10.15","unavailable":false,"name":"macOS","introducedAt":"10.4"}],"modules":[{"name":"Quartz"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"isPausedRendering"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPausedRendering"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"symbolKind":"method","externalID":"c:objc(cs)QCView(im)isPausedRendering","title":"isPausedRendering()"},"references":{"doc://com.apple.quartz/documentation/Quartz/QCView/isRendering()":{"url":"/documentation/quartz/qcview/isrendering()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRendering","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/isRendering()","type":"topic","role":"symbol","title":"isRendering()","abstract":[{"type":"text","text":"Checks whether a composition is rendering in the view."}],"navigatorTitle":[{"text":"isRendering","kind":"identifier"}],"deprecated":true},"doc://com.apple.documentation/documentation/swift/false":{"abstract":[{"type":"text","text":"A false value."}],"identifier":"doc://com.apple.documentation/documentation/swift/false","title":"false","type":"topic","url":"/documentation/swift/false","role":"symbol","kind":"symbol"},"doc://com.apple.quartz/documentation/Quartz/QCView/startRendering()":{"abstract":[{"text":"Starts rendering the composition that is in the view.","type":"text"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/startRendering()","title":"startRendering()","type":"topic","url":"/documentation/quartz/qcview/startrendering()","role":"symbol","kind":"symbol","deprecated":true,"navigatorTitle":[{"text":"startRendering","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRendering","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.apple.quartz/documentation/Quartz/QCView/isPausedRendering()":{"url":"/documentation/quartz/qcview/ispausedrendering()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPausedRendering"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/isPausedRendering()","type":"topic","role":"symbol","title":"isPausedRendering()","abstract":[{"type":"text","text":"Returns whether or not the rendering in the view is paused."}],"navigatorTitle":[{"kind":"identifier","text":"isPausedRendering"}],"deprecated":true},"doc://com.apple.quartz/documentation/Quartz/QCView/autostartsRendering()":{"url":"/documentation/quartz/qcview/autostartsrendering()","role":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"autostartsRendering"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","abstract":[{"type":"text","text":"Checks whether the view is set to start rendering automatically."}],"type":"topic","title":"autostartsRendering()","identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/autostartsRendering()","navigatorTitle":[{"kind":"identifier","text":"autostartsRendering"}]},"doc://com.apple.quartz/documentation/Quartz":{"identifier":"doc://com.apple.quartz/documentation/Quartz","kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Allow users to browse, edit, and save images, using slideshows and Core Image filters."}],"title":"Quartz","url":"/documentation/quartz"},"doc://com.apple.quartz/documentation/Quartz/QCView/setAutostartsRendering(_:)":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/setAutostartsRendering(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAutostartsRendering"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAutostartsRendering:"}],"deprecated":true,"title":"setAutostartsRendering(_:)","kind":"symbol","abstract":[{"text":"Sets whether the composition that is in the view starts rendering automatically when the view is put on the screen.","type":"text"}],"url":"/documentation/quartz/qcview/setautostartsrendering(_:)","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"url":"/documentation/Swift/MainActor"},"doc://com.externally.resolved.symbol/s:Sb":{"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"Bool","type":"topic","url":"/documentation/Swift/Bool"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic"},"doc://com.apple.quartz/documentation/Quartz/QCView":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"QCView"},{"type":"text","text":" class is a custom "},{"type":"codeVoice","code":"NSView"},{"type":"text","text":" class that loads, plays, and controls Quartz Composer compositions. It is an autonomous view that is driven by an internal timer running on the main thread."}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QCView"}],"navigatorTitle":[{"kind":"identifier","text":"QCView"}],"role":"symbol","kind":"symbol","title":"QCView","deprecated":true,"type":"topic","url":"/documentation/quartz/qcview"},"doc://com.apple.quartz/documentation/Quartz/QCView/pauseRendering()":{"abstract":[{"type":"text","text":"Pauses rendering in the view."}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/pauseRendering()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseRendering"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"pauseRendering"}],"role":"symbol","kind":"symbol","title":"pauseRendering()","deprecated":true,"type":"topic","url":"/documentation/quartz/qcview/pauserendering()"},"doc://com.apple.quartz/documentation/Quartz/QCView/resumeRendering()":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/resumeRendering()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resumeRendering","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"resumeRendering","kind":"identifier"}],"deprecated":true,"title":"resumeRendering()","kind":"symbol","abstract":[{"text":"Resumes rendering a paused composition.","type":"text"}],"url":"/documentation/quartz/qcview/resumerendering()","role":"symbol"},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/swift/true","title":"true","type":"topic","url":"/documentation/swift/true","role":"symbol","kind":"symbol"},"doc://com.apple.quartz/documentation/Quartz/QCView/stopRendering()":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/stopRendering()","title":"stopRendering()","url":"/documentation/quartz/qcview/stoprendering()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopRendering"},{"kind":"text","text":"()"}],"deprecated":true,"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopRendering"}],"type":"topic","abstract":[{"type":"text","text":"Stops rendering the composition that is in the view."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false,"deprecatedAt":"10.15","introducedAt":"10.4"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"path":"/metadata/title","op":"replace","value":"isPausedRendering"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPausedRendering"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartz/documentation/Quartz","doc://com.apple.quartz/documentation/Quartz/QCView"]]}},{"path":"/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Managing-Rendering","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/startRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/isRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/autostartsRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/setAutostartsRendering(_:)","doc://com.apple.quartz/documentation/Quartz/QCView/stopRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/pauseRendering()","doc://com.apple.quartz/documentation/Quartz/QCView/resumeRendering()"],"title":"Managing Rendering","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isPausedRendering"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true,"type":"reference"},{"text":" if the rendering is paused; otherwise ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]},"path":"/primaryContentSections/1"},{"value":[{"inlineContent":[{"text":"QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)","type":"text"}],"type":"paragraph"}],"op":"replace","path":"/deprecationSummary"},{"value":"isRendering","op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1isRendering()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isRendering"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1isRendering()/fragments"},{"value":"startRendering","op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1startRendering()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"startRendering","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1startRendering()/fragments"},{"value":"isPausedRendering","op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1isPausedRendering()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isPausedRendering","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1isPausedRendering()/fragments"},{"value":"autostartsRendering","op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1autostartsRendering()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"autostartsRendering"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1autostartsRendering()/fragments"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setAutostartsRendering(_:)/title","value":"setAutostartsRendering:","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setAutostartsRendering(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAutostartsRendering:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/title","value":"QCView","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/fragments","value":[{"text":"QCView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/navigatorTitle","value":[{"text":"QCView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1pauseRendering()/title","value":"pauseRendering","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1pauseRendering()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pauseRendering"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1resumeRendering()/title","value":"resumeRendering","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1resumeRendering()/fragments","value":[{"text":"- ","kind":"text"},{"text":"resumeRendering","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1stopRendering()/title","value":"stopRendering","op":"replace"},{"path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1stopRendering()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopRendering"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}