{
  "abstract": [
    {
      "text": "Sets the mask used to filter which types of events are forwarded from the view to the composition during rendering.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/QCView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/QCView/setEventForwardingMask(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)QCView(im)setEventForwardingMask:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setEventForwardingMask"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setEventForwardingMask:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.4",
        "message": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setEventForwardingMask(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setEventForwardingMask"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "mask"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An event filtering mask. The mask can be a combination of any of the mask constants listed below, or the constant ",
                  "type": "text"
                },
                {
                  "code": "NSAnyEventMask",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "header": "row",
              "rows": [
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "Event",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "Description",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSLeftMouseDownMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user pressed the left button.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSLeftMouseDraggedMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user moved the mouse with the left button down.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSLeftMouseUpMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user released the left button.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSRightMouseDownMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user pressed the right button.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSRightMouseDraggedMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user moved the mouse with the right button down.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSRightMouseUpMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user released the right button.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSOtherMouseDownMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user pressed the middle button, or some button other than the left or right button.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSOtherMouseDraggedMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user moved the mouse with the middle button down, or some button other than the left or right button.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSOtherMouseUpMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user released the middle button, or some button other than the left or right button.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSMouseMovedMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user moved the mouse without holding down a mouse button.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSScrollWheelMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user moved the mouse scroll wheel.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSKeyDownMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user generated a character or characters by pressing a key.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSKeyUpMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user released a key.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "code": "NSFlagsChangedMask",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The user pressed or released a modifier key, or toggled the Caps Lock key.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ]
              ],
              "type": "table"
            }
          ],
          "name": "mask"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCView": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "QCView",
          "type": "codeVoice"
        },
        {
          "text": " class is a custom ",
          "type": "text"
        },
        {
          "code": "NSView",
          "type": "codeVoice"
        },
        {
          "text": " class that loads, plays, and controls Quartz Composer compositions. It is an autonomous view that is driven by an internal timer running on the main thread.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCView"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QCView"
        }
      ],
      "role": "symbol",
      "title": "QCView",
      "type": "topic",
      "url": "/documentation/quartz/qcview"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCView/eventForwardingMask()": {
      "abstract": [
        {
          "text": "Retrieves the mask used to filter which types of events are forwarded from the view to the composition during rendering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventForwardingMask"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCView/eventForwardingMask()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eventForwardingMask"
        }
      ],
      "role": "symbol",
      "title": "eventForwardingMask()",
      "type": "topic",
      "url": "/documentation/quartz/qcview/eventforwardingmask()"
    },
    "doc://com.apple.quartz/documentation/Quartz/QCView/setEventForwardingMask(_:)": {
      "abstract": [
        {
          "text": "Sets the mask used to filter which types of events are forwarded from the view to the composition during rendering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setEventForwardingMask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/QCView/setEventForwardingMask(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setEventForwardingMask:"
        }
      ],
      "role": "symbol",
      "title": "setEventForwardingMask(_:)",
      "type": "topic",
      "url": "/documentation/quartz/qcview/seteventforwardingmask(_:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-and-Getting-Event-Masks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/QCView/eventForwardingMask()"
      ],
      "title": "Setting and Getting Event Masks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setEventForwardingMask:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setEventForwardingMask:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartz/documentation/Quartz",
                "doc://com.apple.quartz/documentation/Quartz/QCView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-and-Getting-Event-Masks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/QCView/eventForwardingMask()"
              ],
              "title": "Setting and Getting Event Masks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setEventForwardingMask:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "mask"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An event filtering mask. The mask can be a combination of any of the mask constants listed below, or the constant ",
                        "type": "text"
                      },
                      {
                        "code": "NSAnyEventMask",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "header": "row",
                    "rows": [
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "Event",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "Description",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSLeftMouseDownMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user pressed the left button.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSLeftMouseDraggedMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user moved the mouse with the left button down.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSLeftMouseUpMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user released the left button.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSRightMouseDownMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user pressed the right button.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSRightMouseDraggedMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user moved the mouse with the right button down.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSRightMouseUpMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user released the right button.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSOtherMouseDownMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user pressed the middle button, or some button other than the left or right button.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSOtherMouseDraggedMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user moved the mouse with the middle button down, or some button other than the left or right button.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSOtherMouseUpMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user released the middle button, or some button other than the left or right button.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSMouseMovedMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user moved the mouse without holding down a mouse button.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSScrollWheelMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user moved the mouse scroll wheel.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSKeyDownMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user generated a character or characters by pressing a key.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSKeyUpMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user released a key.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "code": "NSFlagsChangedMask",
                                "type": "codeVoice"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The user pressed or released a modifier key, or toggled the Caps Lock key.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ]
                    ],
                    "type": "table"
                  }
                ],
                "name": "mask"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/title",
          "value": "QCView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QCView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QCView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1eventForwardingMask()/title",
          "value": "eventForwardingMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1eventForwardingMask()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "eventForwardingMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setEventForwardingMask(_:)/title",
          "value": "setEventForwardingMask:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1setEventForwardingMask(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setEventForwardingMask:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/qcview/seteventforwardingmask(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/qcview/seteventforwardingmask(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
