{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartz/documentation/Quartz","doc://com.apple.quartz/documentation/Quartz/QCView"]]},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)"}],"type":"paragraph"}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"snapshotImage"}],"externalID":"c:objc(cs)QCView(im)snapshotImage","modules":[{"name":"Quartz"}],"platforms":[{"introducedAt":"10.4","unavailable":false,"name":"macOS","message":"QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)","deprecated":false,"beta":false,"deprecatedAt":"10.15"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"snapshotImage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSImage","preciseIdentifier":"c:objc(cs)NSImage"},{"kind":"text","text":"!"}],"roleHeading":"Instance Method","title":"snapshotImage()","symbolKind":"method"},"variants":[{"paths":["/documentation/quartz/qcview/snapshotimage()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/quartz/qcview/snapshotimage()"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"anchor":"Taking-Snapshot-Images","title":"Taking Snapshot Images","identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/createSnapshotImage(ofType:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"snapshotImage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSImage","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSImage","preciseIdentifier":"c:objc(cs)NSImage"},{"kind":"text","text":"!"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"The snapshot image.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Returns an ","type":"text"},{"code":"NSImage","type":"codeVoice"},{"text":" object of the current image in the view.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.quartz/documentation/Quartz/QCView/snapshotImage()"},"references":{"doc://com.externally.resolved.symbol/s:ScM":{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"url":"/documentation/Swift/MainActor"},"doc://com.externally.resolved.symbol/c:objc(cs)NSImage":{"url":"/documentation/AppKit/NSImage","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSImage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NSImage","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A high-level interface for manipulating image data."}],"title":"NSImage","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic"},"doc://com.apple.quartz/documentation/Quartz/QCView/createSnapshotImage(ofType:)":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/createSnapshotImage(ofType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createSnapshotImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ofType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"createSnapshotImageOfType:"}],"type":"topic","url":"/documentation/quartz/qcview/createsnapshotimage(oftype:)","deprecated":true,"title":"createSnapshotImage(ofType:)","kind":"symbol","abstract":[{"type":"text","text":"Returns the current image in the view as an image object of the provided image type."}],"role":"symbol"},"doc://com.apple.quartz/documentation/Quartz":{"identifier":"doc://com.apple.quartz/documentation/Quartz","kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Allow users to browse, edit, and save images, using slideshows and Core Image filters."}],"title":"Quartz","url":"/documentation/quartz"},"doc://com.apple.quartz/documentation/Quartz/QCView":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"QCView"},{"type":"text","text":" class is a custom "},{"type":"codeVoice","code":"NSView"},{"type":"text","text":" class that loads, plays, and controls Quartz Composer compositions. It is an autonomous view that is driven by an internal timer running on the main thread."}],"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QCView"}],"navigatorTitle":[{"kind":"identifier","text":"QCView"}],"role":"symbol","kind":"symbol","title":"QCView","deprecated":true,"type":"topic","url":"/documentation/quartz/qcview"},"doc://com.apple.quartz/documentation/Quartz/QCView/snapshotImage()":{"identifier":"doc://com.apple.quartz/documentation/Quartz/QCView/snapshotImage()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"snapshotImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"snapshotImage","kind":"identifier"}],"type":"topic","url":"/documentation/quartz/qcview/snapshotimage()","deprecated":true,"title":"snapshotImage()","kind":"symbol","abstract":[{"type":"text","text":"Returns an "},{"code":"NSImage","type":"codeVoice"},{"type":"text","text":" object of the current image in the view."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"10.4","unavailable":false,"deprecatedAt":"10.15","beta":false,"deprecated":false,"name":"macOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"snapshotImage","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"snapshotImage","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartz/documentation/Quartz","doc://com.apple.quartz/documentation/Quartz/QCView"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.quartz/documentation/Quartz/QCView/createSnapshotImage(ofType:)"],"anchor":"Taking-Snapshot-Images","generated":true,"title":"Taking Snapshot Images"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage","text":"NSImage","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"snapshotImage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The snapshot image.","type":"text"}]}]},"path":"/primaryContentSections/1","op":"replace"},{"value":[{"type":"paragraph","inlineContent":[{"text":"QuartzComposer API deprecated. (Define QC_SILENCE_DEPRECATION to silence these warnings)","type":"text"}]}],"op":"replace","path":"/deprecationSummary"},{"value":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"NSImage","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSImage/fragments"},{"value":"createSnapshotImageOfType:","op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1createSnapshotImage(ofType:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"createSnapshotImageOfType:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1createSnapshotImage(ofType:)/fragments"},{"value":"QCView","op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/title"},{"value":[{"kind":"identifier","text":"QCView"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/fragments"},{"value":[{"kind":"identifier","text":"QCView"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView/navigatorTitle"},{"value":"snapshotImage","op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1snapshotImage()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"snapshotImage"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1QCView~1snapshotImage()/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}