{
  "abstract": [
    {
      "text": "These constants identify record types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/1614747-record-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Record Types"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecordType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types": {
      "abstract": [
        {
          "text": "These constants identify record property types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Property Types",
      "type": "topic",
      "url": "/documentation/addressbook/1614731-record-property-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1619730-sort-order": {
      "abstract": [
        {
          "text": "These constants identify sort order for person lists.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1619730-sort-order",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sort Order",
      "type": "topic",
      "url": "/documentation/addressbook/1619730-sort-order"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1619815-composite-name-format": {
      "abstract": [
        {
          "text": "These constants identify the format to use for a person’s composite name order for person records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1619815-composite-name-format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Composite Name Format",
      "type": "topic",
      "url": "/documentation/addressbook/1619815-composite-name-format"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types": {
      "abstract": [
        {
          "text": "These constants identify the type of a source.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Source Types",
      "type": "topic",
      "url": "/documentation/addressbook/1619878-source-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecordType": {
      "abstract": [
        {
          "text": "Integer that identifies a record type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecordType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecordType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecordType"
        }
      ],
      "role": "symbol",
      "title": "ABRecordType",
      "type": "topic",
      "url": "/documentation/addressbook/abrecordtype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations": {
      "abstract": [
        {
          "text": "Get the enumerations you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Enumerations",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-enumerations"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABGroupType": {
      "abstract": [
        {
          "text": "Group record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABGroupType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABGroupType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABGroupType"
        }
      ],
      "role": "symbol",
      "title": "kABGroupType",
      "type": "topic",
      "url": "/documentation/addressbook/kabgrouptype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonType": {
      "abstract": [
        {
          "text": "Person record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonType"
        }
      ],
      "role": "symbol",
      "title": "kABPersonType",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersontype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSourceType": {
      "abstract": [
        {
          "text": "Source record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSourceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSourceType"
        }
      ],
      "role": "symbol",
      "title": "kABSourceType",
      "type": "topic",
      "url": "/documentation/addressbook/kabsourcetype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/1619815-composite-name-format",
        "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types",
        "doc://com.apple.addressbook/documentation/AddressBook/1619730-sort-order",
        "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types"
      ],
      "title": "Miscellaneous"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonType",
        "doc://com.apple.addressbook/documentation/AddressBook/kABGroupType",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSourceType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonType",
                "doc://com.apple.addressbook/documentation/AddressBook/kABGroupType",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSourceType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordType/title",
          "value": "ABRecordType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABGroupType/title",
          "value": "kABGroupType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABGroupType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABGroupType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceType/title",
          "value": "kABSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonType/title",
          "value": "kABPersonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/1614747-record-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/1614747-record-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
