{
  "abstract": [
    {
      "text": "These constants identify sort order for person lists.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/1619730-sort-order"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sort Order"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types": {
      "abstract": [
        {
          "text": "These constants identify record property types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Property Types",
      "type": "topic",
      "url": "/documentation/addressbook/1614731-record-property-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1614747-record-types": {
      "abstract": [
        {
          "text": "These constants identify record types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1614747-record-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Types",
      "type": "topic",
      "url": "/documentation/addressbook/1614747-record-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1619815-composite-name-format": {
      "abstract": [
        {
          "text": "These constants identify the format to use for a person’s composite name order for person records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1619815-composite-name-format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Composite Name Format",
      "type": "topic",
      "url": "/documentation/addressbook/1619815-composite-name-format"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types": {
      "abstract": [
        {
          "text": "These constants identify the type of a source.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Source Types",
      "type": "topic",
      "url": "/documentation/addressbook/1619878-source-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations": {
      "abstract": [
        {
          "text": "Get the enumerations you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Enumerations",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-enumerations"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonSortByFirstName": {
      "abstract": [
        {
          "text": "Order by first name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonSortByFirstName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonSortByFirstName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonSortByFirstName"
        }
      ],
      "role": "symbol",
      "title": "kABPersonSortByFirstName",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonsortbyfirstname"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonSortByLastName": {
      "abstract": [
        {
          "text": "Order by last name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonSortByLastName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonSortByLastName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonSortByLastName"
        }
      ],
      "role": "symbol",
      "title": "kABPersonSortByLastName",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonsortbylastname"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/1619815-composite-name-format",
        "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types",
        "doc://com.apple.addressbook/documentation/AddressBook/1614747-record-types",
        "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types"
      ],
      "title": "Miscellaneous"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonSortByFirstName",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonSortByLastName"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonSortByFirstName",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonSortByLastName"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonSortByFirstName/title",
          "value": "kABPersonSortByFirstName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonSortByFirstName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonSortByFirstName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonSortByLastName/title",
          "value": "kABPersonSortByLastName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonSortByLastName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonSortByLastName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/1619730-sort-order"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/1619730-sort-order"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
