{
  "abstract": [
    {
      "text": "These constants identify the format to use for a person’s composite name order for person records.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/1619815-composite-name-format"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Composite Name Format"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCompositeNameFormat",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecordCopyCompositeName(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types": {
      "abstract": [
        {
          "text": "These constants identify record property types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Property Types",
      "type": "topic",
      "url": "/documentation/addressbook/1614731-record-property-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1614747-record-types": {
      "abstract": [
        {
          "text": "These constants identify record types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1614747-record-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Types",
      "type": "topic",
      "url": "/documentation/addressbook/1614747-record-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1619730-sort-order": {
      "abstract": [
        {
          "text": "These constants identify sort order for person lists.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1619730-sort-order",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sort Order",
      "type": "topic",
      "url": "/documentation/addressbook/1619730-sort-order"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types": {
      "abstract": [
        {
          "text": "These constants identify the type of a source.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Source Types",
      "type": "topic",
      "url": "/documentation/addressbook/1619878-source-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCompositeNameFormat": {
      "abstract": [
        {
          "text": "Indicates a person-name display format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCompositeNameFormat"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCompositeNameFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCompositeNameFormat"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCompositeNameFormat",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncompositenameformat"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecordCopyCompositeName(_:)": {
      "abstract": [
        {
          "text": "Returns an appropriate, human-friendly name for the record.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecordCopyCompositeName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecordCopyCompositeName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecordCopyCompositeName"
        }
      ],
      "role": "symbol",
      "title": "ABRecordCopyCompositeName(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abrecordcopycompositename(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations": {
      "abstract": [
        {
          "text": "Get the enumerations you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Enumerations",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-enumerations"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatFirstNameFirst": {
      "abstract": [
        {
          "text": "First name first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonCompositeNameFormatFirstNameFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatFirstNameFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonCompositeNameFormatFirstNameFirst"
        }
      ],
      "role": "symbol",
      "title": "kABPersonCompositeNameFormatFirstNameFirst",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersoncompositenameformatfirstnamefirst"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatLastNameFirst": {
      "abstract": [
        {
          "text": "Last name first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonCompositeNameFormatLastNameFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatLastNameFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonCompositeNameFormatLastNameFirst"
        }
      ],
      "role": "symbol",
      "title": "kABPersonCompositeNameFormatLastNameFirst",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersoncompositenameformatlastnamefirst"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types",
        "doc://com.apple.addressbook/documentation/AddressBook/1614747-record-types",
        "doc://com.apple.addressbook/documentation/AddressBook/1619730-sort-order",
        "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types"
      ],
      "title": "Miscellaneous"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatFirstNameFirst",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatLastNameFirst"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatFirstNameFirst",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatLastNameFirst"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCompositeNameFormat/title",
          "value": "ABPersonCompositeNameFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCompositeNameFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCompositeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCompositeNameFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCompositeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonCompositeNameFormatFirstNameFirst/title",
          "value": "kABPersonCompositeNameFormatFirstNameFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonCompositeNameFormatFirstNameFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonCompositeNameFormatFirstNameFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonCompositeNameFormatLastNameFirst/title",
          "value": "kABPersonCompositeNameFormatLastNameFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonCompositeNameFormatLastNameFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonCompositeNameFormatLastNameFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordCopyCompositeName(_:)/title",
          "value": "ABRecordCopyCompositeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordCopyCompositeName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordCopyCompositeName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/1619815-composite-name-format"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/1619815-composite-name-format"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
