{
  "abstract": [
    {
      "text": "Return ",
      "type": "text"
    },
    {
      "code": "true",
      "type": "codeVoice"
    },
    {
      "text": " ifthe action menu item should be enabled, ",
      "type": "text"
    },
    {
      "code": "false",
      "type": "codeVoice"
    },
    {
      "text": " otherwise.If the property returned by ",
      "type": "text"
    },
    {
      "code": "ABActionGetPropertyCallback",
      "type": "codeVoice"
    },
    {
      "text": " isa multi-value property, ",
      "type": "text"
    },
    {
      "code": "identifier",
      "type": "codeVoice"
    },
    {
      "text": " contains theunique identifier of the value selected.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABActionEnabledCallback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@ABActionEnabledCallback",
    "fragments": [
      {
        "kind": "identifier",
        "text": "ABActionEnabledCallback"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABActionEnabledCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "ABActionEnabledCallback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:*Fc(#*$@S@__ABPerson#*1$@S@__CFString)",
              "text": "unsigned char (*)(struct __ABPerson *, const struct __CFString *)"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABActionEnabledCallback"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionCopyTitleCallback": {
      "abstract": [
        {
          "text": "The title of the menu item for the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionCopyTitleCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionCopyTitleCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionCopyTitleCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactioncopytitlecallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionEnabledCallback": {
      "abstract": [
        {
          "text": "Return ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": " ifthe action menu item should be enabled, ",
          "type": "text"
        },
        {
          "code": "false",
          "type": "codeVoice"
        },
        {
          "text": " otherwise.If the property returned by ",
          "type": "text"
        },
        {
          "code": "ABActionGetPropertyCallback",
          "type": "codeVoice"
        },
        {
          "text": " isa multi-value property, ",
          "type": "text"
        },
        {
          "code": "identifier",
          "type": "codeVoice"
        },
        {
          "text": " contains theunique identifier of the value selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionEnabledCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionEnabledCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionEnabledCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactionenabledcallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback": {
      "abstract": [
        {
          "text": "Return the property the action applies to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionGetPropertyCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionGetPropertyCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactiongetpropertycallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionSelectedCallback": {
      "abstract": [
        {
          "text": "Execute the action. If the property returnedby ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " isa multi-value property, ",
          "type": "text"
        },
        {
          "code": "identifier",
          "type": "codeVoice"
        },
        {
          "text": " containsthe unique identifier of the value selected; otherwise, identifieris ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionSelectedCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionSelectedCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionSelectedCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactionselectedcallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABImageClientCallback": {
      "abstract": [
        {
          "text": "Prototype of a callback function used to notify an application when an asynchronous image fetch is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABImageClientCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABImageClientCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABImageClientCallback"
        }
      ],
      "role": "symbol",
      "title": "ABImageClientCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abimageclientcallback"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Callbacks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABImageClientCallback",
        "doc://com.apple.addressbook/documentation/AddressBook/ABActionCopyTitleCallback",
        "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback",
        "doc://com.apple.addressbook/documentation/AddressBook/ABActionSelectedCallback"
      ],
      "title": "Callbacks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClientCallback/title",
          "value": "ABImageClientCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClientCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClientCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClientCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClientCallback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abactionenabledcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
