{
  "abstract": [
    {
      "text": "The main object you use to access the Address Book database.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ABAddressBook",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ABAddressBook"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABAddressBook"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ABAddressBook"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABAddressBook"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "ABAddressBook",
              "type": "codeVoice"
            },
            {
              "text": " class provides a programming interface to the Address Book—a centralized database used by multiple applications to store contact and other personal information about people. The Address Book database also supports the notion of a “group” containing one or more persons. People may belong to multiple groups, and groups may also belong to other groups with some restrictions (for example, no circular references are allowed).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "ABAddressBook",
              "type": "codeVoice"
            },
            {
              "text": " class is “toll-free bridged” with its procedural C opaque-type counterpart. This means that the ",
              "type": "text"
            },
            {
              "code": "ABAddressBookRef",
              "type": "codeVoice"
            },
            {
              "text": " type is interchangeable in function or method calls with instances of the ",
              "type": "text"
            },
            {
              "code": "ABAddressBook",
              "type": "codeVoice"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1529225-errors": {
      "abstract": [
        {
          "text": "Errors codes returned by the Address Book Framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1529225-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Errors",
      "type": "topic",
      "url": "/documentation/addressbook/1529225-errors"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook": {
      "abstract": [
        {
          "text": "The main object you use to access the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBook",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/add(_:)": {
      "abstract": [
        {
          "text": "Adds an ",
          "type": "text"
        },
        {
          "code": "ABPerson",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "ABGroup",
          "type": "codeVoice"
        },
        {
          "text": " record to the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABRecord",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/add(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addRecord:"
        }
      ],
      "role": "symbol",
      "title": "add(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/add(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/add(_:error:)": {
      "abstract": [
        {
          "text": "Adds an ",
          "type": "text"
        },
        {
          "code": "ABPerson",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "ABGroup",
          "type": "codeVoice"
        },
        {
          "text": " record to the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABRecord",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": ()) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/add(_:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addRecord:error:"
        }
      ],
      "role": "symbol",
      "title": "add(_:error:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/add(_:error:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/addressBook": {
      "abstract": [
        {
          "text": "Returns a new instance of ",
          "type": "text"
        },
        {
          "code": "ABAddressBook",
          "type": "codeVoice"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if the Address Book database can’t be initialized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "addressBook"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/addressBook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addressBook"
        }
      ],
      "role": "symbol",
      "title": "addressBook",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/defaultCountryCode()": {
      "abstract": [
        {
          "text": "Returns the default country code for records with unspecified country codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultCountryCode"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/defaultCountryCode()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultCountryCode"
        }
      ],
      "role": "symbol",
      "title": "defaultCountryCode()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/defaultcountrycode()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/defaultNameOrdering()": {
      "abstract": [
        {
          "text": "Returns the default name ordering defined by the user in the Address Book application’s preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultNameOrdering"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/defaultNameOrdering()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultNameOrdering"
        }
      ],
      "role": "symbol",
      "title": "defaultNameOrdering()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/defaultnameordering()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/formattedAddress(from:)": {
      "abstract": [
        {
          "text": "Returns an attributed string containing the formatted address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formattedAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/formattedAddress(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "formattedAddressFromDictionary:"
        }
      ],
      "role": "symbol",
      "title": "formattedAddress(from:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/formattedaddress(from:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/groups()": {
      "abstract": [
        {
          "text": "Returns an array of all the groups in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groups"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/groups()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "groups"
        }
      ],
      "role": "symbol",
      "title": "groups()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/groups()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/hasUnsavedChanges()": {
      "abstract": [
        {
          "text": "Indicates whether an address book has changes that have not been saved to the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasUnsavedChanges"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/hasUnsavedChanges()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasUnsavedChanges"
        }
      ],
      "role": "symbol",
      "title": "hasUnsavedChanges()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/hasunsavedchanges()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/me()": {
      "abstract": [
        {
          "text": "Returns the ",
          "type": "text"
        },
        {
          "code": "ABPerson",
          "type": "codeVoice"
        },
        {
          "text": " record that represents the logged-in user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "me"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPerson",
          "text": "ABPerson"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/me()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "me"
        }
      ],
      "role": "symbol",
      "title": "me()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/me()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/people()": {
      "abstract": [
        {
          "text": "Returns an array of all the people in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "people"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/people()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "people"
        }
      ],
      "role": "symbol",
      "title": "people()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/people()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/record(forUniqueId:)": {
      "abstract": [
        {
          "text": "Returns the person or group record that matches the given unique ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forUniqueId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABRecord",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/record(forUniqueId:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordForUniqueId:"
        }
      ],
      "role": "symbol",
      "title": "record(forUniqueId:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/record(foruniqueid:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/recordClass(fromUniqueId:)": {
      "abstract": [
        {
          "text": "Returns the class name of the record that matches the given unique ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordClass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromUniqueId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/recordClass(fromUniqueId:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordClassFromUniqueId:"
        }
      ],
      "role": "symbol",
      "title": "recordClass(fromUniqueId:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/recordclass(fromuniqueid:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/records(matching:)": {
      "abstract": [
        {
          "text": "Returns an array of records that match the given search element, or returns an empty array if no records match the search element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "records"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABSearchElement",
          "text": "ABSearchElement"
        },
        {
          "kind": "text",
          "text": "!) -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/records(matching:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordsMatchingSearchElement:"
        }
      ],
      "role": "symbol",
      "title": "records(matching:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/records(matching:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/remove(_:)": {
      "abstract": [
        {
          "text": "Removes an ",
          "type": "text"
        },
        {
          "code": "ABPerson",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "ABGroup",
          "type": "codeVoice"
        },
        {
          "text": " record from the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABRecord",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/remove(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeRecord:"
        }
      ],
      "role": "symbol",
      "title": "remove(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/remove(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/remove(_:error:)": {
      "abstract": [
        {
          "text": "Removes an ",
          "type": "text"
        },
        {
          "code": "ABPerson",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "ABGroup",
          "type": "codeVoice"
        },
        {
          "text": " record from the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABRecord",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": ()) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/remove(_:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeRecord:error:"
        }
      ],
      "role": "symbol",
      "title": "remove(_:error:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/remove(_:error:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/save()": {
      "abstract": [
        {
          "text": "Saves all the changes made since the last save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/save()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "save"
        }
      ],
      "role": "symbol",
      "title": "save()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/save()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/saveAndReturnError()": {
      "abstract": [
        {
          "text": "Saves all the changes made since the last save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveAndReturnError"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/saveAndReturnError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveAndReturnError:"
        }
      ],
      "role": "symbol",
      "title": "saveAndReturnError()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/saveandreturnerror()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/setMe(_:)": {
      "abstract": [
        {
          "text": "Sets the record that represents the logged-in user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setMe"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPerson",
          "text": "ABPerson"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/setMe(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMe:"
        }
      ],
      "role": "symbol",
      "title": "setMe(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/setme(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/shared()": {
      "abstract": [
        {
          "text": "Returns the unique shared instance of ",
          "type": "text"
        },
        {
          "code": "ABAddressBook",
          "type": "codeVoice"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if the Address Book database can’t be initialized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABAddressBook",
          "text": "ABAddressBook"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/shared()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedAddressBook"
        }
      ],
      "role": "symbol",
      "title": "shared()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/shared()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/database-change-notification-keys": {
      "abstract": [
        {
          "text": "Keys contained by the user-info dictionary of the notifications posted by the Address Book framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/database-change-notification-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Database change notification keys",
      "type": "topic",
      "url": "/documentation/addressbook/database-change-notification-keys"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedExternallyNotification": {
      "abstract": [
        {
          "text": "Posted when a process other than the current one has changed the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABDatabaseChangedExternallyNotification"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedExternallyNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDatabaseChangedExternallyNotification",
      "type": "topic",
      "url": "/documentation/addressbook/kabdatabasechangedexternallynotification"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedNotification": {
      "abstract": [
        {
          "text": "Posted when this process has changed the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABDatabaseChangedNotification"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDatabaseChangedNotification",
      "type": "topic",
      "url": "/documentation/addressbook/kabdatabasechangednotification"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458497-abdatabasechanged": {
      "abstract": [
        {
          "text": "Posted when this process has changed the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "abDatabaseChanged"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458497-abdatabasechanged",
      "kind": "symbol",
      "role": "symbol",
      "title": "abDatabaseChanged",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1458497-abdatabasechanged"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458671-abdatabasechangedexternally": {
      "abstract": [
        {
          "text": "Posted when a process other than the current one has changed the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "abDatabaseChangedExternally"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458671-abdatabasechangedexternally",
      "kind": "symbol",
      "role": "symbol",
      "title": "abDatabaseChangedExternally",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1458671-abdatabasechangedexternally"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-and-Initializing-an-Address-Book",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/shared()"
      ],
      "title": "Creating and Initializing an Address Book"
    },
    {
      "anchor": "Retrieving-Groups-and-People",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/groups()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/people()"
      ],
      "title": "Retrieving Groups and People"
    },
    {
      "anchor": "Setting-and-Retrieving-the-Logged-in-Users-Record",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/me()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/setMe(_:)"
      ],
      "title": "Setting and Retrieving the Logged-in User’s Record"
    },
    {
      "anchor": "Retrieving-a-Specific-Record",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/record(forUniqueId:)"
      ],
      "title": "Retrieving a Specific Record"
    },
    {
      "anchor": "Retrieving-the-Class-of-a-Record",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/recordClass(fromUniqueId:)"
      ],
      "title": "Retrieving the Class of a Record"
    },
    {
      "anchor": "Retrieving-a-Formatted-Address",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/formattedAddress(from:)"
      ],
      "title": "Retrieving a Formatted Address"
    },
    {
      "anchor": "Retrieving-Default-Values",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/defaultCountryCode()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/defaultNameOrdering()"
      ],
      "title": "Retrieving Default Values"
    },
    {
      "anchor": "Adding-and-Removing-Records",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/add(_:error:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/add(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/remove(_:error:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/remove(_:)"
      ],
      "title": "Adding and Removing Records"
    },
    {
      "anchor": "Searching",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/records(matching:)"
      ],
      "title": "Searching"
    },
    {
      "anchor": "Saving-and-Detecting-Changes",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/hasUnsavedChanges()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/save()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/saveAndReturnError()"
      ],
      "title": "Saving and Detecting Changes"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/database-change-notification-keys",
        "doc://com.apple.addressbook/documentation/AddressBook/1529225-errors"
      ],
      "title": "Constants"
    },
    {
      "abstract": [
        {
          "text": "These notifications are sent when something changes in the Address Book database. These are not sent until the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/shared()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class method has been invoked.",
          "type": "text"
        }
      ],
      "anchor": "Notifications",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458497-abdatabasechanged",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458671-abdatabasechangedexternally"
      ],
      "title": "Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ABAddressBook"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-and-Initializing-an-Address-Book",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/shared()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/addressBook"
              ],
              "title": "Creating and Initializing an Address Book"
            },
            {
              "anchor": "Retrieving-Groups-and-People",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/groups()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/people()"
              ],
              "title": "Retrieving Groups and People"
            },
            {
              "anchor": "Setting-and-Retrieving-the-Logged-in-Users-Record",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/me()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/setMe(_:)"
              ],
              "title": "Setting and Retrieving the Logged-in User’s Record"
            },
            {
              "anchor": "Retrieving-a-Specific-Record",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/record(forUniqueId:)"
              ],
              "title": "Retrieving a Specific Record"
            },
            {
              "anchor": "Retrieving-the-Class-of-a-Record",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/recordClass(fromUniqueId:)"
              ],
              "title": "Retrieving the Class of a Record"
            },
            {
              "anchor": "Retrieving-a-Formatted-Address",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/formattedAddress(from:)"
              ],
              "title": "Retrieving a Formatted Address"
            },
            {
              "anchor": "Retrieving-Default-Values",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/defaultCountryCode()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/defaultNameOrdering()"
              ],
              "title": "Retrieving Default Values"
            },
            {
              "anchor": "Adding-and-Removing-Records",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/add(_:error:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/add(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/remove(_:error:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/remove(_:)"
              ],
              "title": "Adding and Removing Records"
            },
            {
              "anchor": "Searching",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/records(matching:)"
              ],
              "title": "Searching"
            },
            {
              "anchor": "Saving-and-Detecting-Changes",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/hasUnsavedChanges()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/save()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/saveAndReturnError()"
              ],
              "title": "Saving and Detecting Changes"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/database-change-notification-keys",
                "doc://com.apple.addressbook/documentation/AddressBook/1529225-errors"
              ],
              "title": "Constants"
            },
            {
              "abstract": [
                {
                  "text": "These notifications are sent when something changes in the Address Book database. These are not sent until the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/shared()",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " class method has been invoked.",
                  "type": "text"
                }
              ],
              "anchor": "Notifications",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedNotification",
                "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedExternallyNotification"
              ],
              "title": "Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ABAddressBook"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1remove(_:)/title",
          "value": "removeRecord:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1remove(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeRecord:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1records(matching:)/title",
          "value": "recordsMatchingSearchElement:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1records(matching:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordsMatchingSearchElement:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1shared()/title",
          "value": "sharedAddressBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1shared()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedAddressBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1hasUnsavedChanges()/title",
          "value": "hasUnsavedChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1hasUnsavedChanges()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hasUnsavedChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1me()/title",
          "value": "me"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1me()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "me"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1remove(_:error:)/title",
          "value": "removeRecord:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1remove(_:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeRecord:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1defaultNameOrdering()/title",
          "value": "defaultNameOrdering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1defaultNameOrdering()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "defaultNameOrdering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1record(forUniqueId:)/title",
          "value": "recordForUniqueId:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1record(forUniqueId:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordForUniqueId:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1people()/title",
          "value": "people"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1people()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "people"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1setMe(_:)/title",
          "value": "setMe:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1setMe(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setMe:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1formattedAddress(from:)/title",
          "value": "formattedAddressFromDictionary:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1formattedAddress(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "formattedAddressFromDictionary:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1add(_:error:)/title",
          "value": "addRecord:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1add(_:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addRecord:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1save()/title",
          "value": "save"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1save()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "save"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1saveAndReturnError()/title",
          "value": "saveAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1saveAndReturnError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1defaultCountryCode()/title",
          "value": "defaultCountryCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1defaultCountryCode()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "defaultCountryCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1add(_:)/title",
          "value": "addRecord:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1add(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addRecord:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1groups()/title",
          "value": "groups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1groups()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "groups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook/title",
          "value": "ABAddressBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1recordClass(fromUniqueId:)/title",
          "value": "recordClassFromUniqueId:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1recordClass(fromUniqueId:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordClassFromUniqueId:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abaddressbook"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abaddressbook"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
