{
  "abstract": [
    {
      "text": "Returns an array of records that match the given search element, or an empty array if no records match the search element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfMatchingRecords(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@ABCopyArrayOfMatchingRecords",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ABCopyArrayOfMatchingRecords"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABAddressBookRef",
        "text": "ABAddressBookRef"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABSearchElementRef",
        "text": "ABSearchElementRef"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": ">!"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABCopyArrayOfMatchingRecords"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "ABCopyArrayOfMatchingRecords(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABCopyArrayOfMatchingRecords"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "addressBook"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABAddressBookRef",
              "text": "ABAddressBookRef"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "search"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABSearchElementRef",
              "text": "ABSearchElementRef"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": ">!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The address book for the logged-in user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "addressBook"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The search element that specifies the query. If ",
                  "type": "text"
                },
                {
                  "code": "search",
                  "type": "codeVoice"
                },
                {
                  "text": " is ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", this function raises an exception. Create an ABSearchElement object using the record specific functions: ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreateSearchElement(_:_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateSearchElement(_:_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". See ",
                  "type": "text"
                },
                {
                  "code": "ABSearchElement C",
                  "type": "codeVoice"
                },
                {
                  "text": " for more functions that create compound queries.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "search"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new array containing ABRecord objects representing all the records that match ",
              "type": "text"
            },
            {
              "code": "search",
              "type": "codeVoice"
            },
            {
              "text": ". If no records match ",
              "type": "text"
            },
            {
              "code": "search",
              "type": "codeVoice"
            },
            {
              "text": ", this function returns an empty array. You are responsible for releasing this object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef": {
      "abstract": [
        {
          "text": "A reference to an ABAddressBook object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBook",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfMatchingRecords(_:_:)": {
      "abstract": [
        {
          "text": "Returns an array of records that match the given search element, or an empty array if no records match the search element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABCopyArrayOfMatchingRecords"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBookRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchElementRef",
          "text": "ABSearchElementRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfMatchingRecords(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABCopyArrayOfMatchingRecords"
        }
      ],
      "role": "symbol",
      "title": "ABCopyArrayOfMatchingRecords(_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abcopyarrayofmatchingrecords(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreateSearchElement(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an ABSearchElement object that specifies a queryfor ABGroup records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupCreateSearchElement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchComparison",
          "text": "ABSearchComparison"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchElementRef",
          "text": "ABSearchElementRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreateSearchElement(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupCreateSearchElement"
        }
      ],
      "role": "symbol",
      "title": "ABGroupCreateSearchElement(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupcreatesearchelement(_:_:_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateSearchElement(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a search element object that specifies a query for records of this type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCreateSearchElement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchComparison",
          "text": "ABSearchComparison"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchElementRef",
          "text": "ABSearchElementRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateSearchElement(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCreateSearchElement"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCreateSearchElement(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncreatesearchelement(_:_:_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementCreateWithConjunction(_:_:)": {
      "abstract": [
        {
          "text": "Returns a compound search element created by combiningthe search elements in an array with the given conjunction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSearchElementCreateWithConjunction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchConjunction",
          "text": "ABSearchConjunction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchElementRef",
          "text": "ABSearchElementRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementCreateWithConjunction(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSearchElementCreateWithConjunction"
        }
      ],
      "role": "symbol",
      "title": "ABSearchElementCreateWithConjunction(_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/absearchelementcreatewithconjunction(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementMatchesRecord(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether or not a record matches a search element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSearchElementMatchesRecord"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchElementRef",
          "text": "ABSearchElementRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecordRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementMatchesRecord(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSearchElementMatchesRecord"
        }
      ],
      "role": "symbol",
      "title": "ABSearchElementMatchesRecord(_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/absearchelementmatchesrecord(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementRef": {
      "abstract": [
        {
          "text": "A reference to an ABSearchElement object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSearchElementRef"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSearchElementRef"
        }
      ],
      "role": "symbol",
      "title": "ABSearchElementRef",
      "type": "topic",
      "url": "/documentation/addressbook/absearchelementref"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Search-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementCreateWithConjunction(_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementMatchesRecord(_:_:)"
      ],
      "title": "Search Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ABCopyArrayOfMatchingRecords"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABCopyArrayOfMatchingRecords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Search-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementCreateWithConjunction(_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementMatchesRecord(_:_:)"
              ],
              "title": "Search Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ABCopyArrayOfMatchingRecords"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABAddressBookRef",
                    "text": "ABAddressBookRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "addressBook"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABSearchElementRef",
                    "text": "ABSearchElementRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "search"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The address book for the logged-in user.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "addressBook"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The search element that specifies the query. If ",
                        "type": "text"
                      },
                      {
                        "code": "search",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", this function raises an exception. Create an ABSearchElement object using the record specific functions: ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreateSearchElement(_:_:_:_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateSearchElement(_:_:_:_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". See ",
                        "type": "text"
                      },
                      {
                        "code": "ABSearchElement C",
                        "type": "codeVoice"
                      },
                      {
                        "text": " for more functions that create compound queries.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "search"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new array containing ABRecord objects representing all the records that match ",
                    "type": "text"
                  },
                  {
                    "code": "search",
                    "type": "codeVoice"
                  },
                  {
                    "text": ". If no records match ",
                    "type": "text"
                  },
                  {
                    "code": "search",
                    "type": "codeVoice"
                  },
                  {
                    "text": ", this function returns an empty array. You are responsible for releasing this object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElementMatchesRecord(_:_:)/title",
          "value": "ABSearchElementMatchesRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElementMatchesRecord(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchElementMatchesRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreateSearchElement(_:_:_:_:_:)/title",
          "value": "ABPersonCreateSearchElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreateSearchElement(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCreateSearchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/title",
          "value": "ABAddressBookRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElementCreateWithConjunction(_:_:)/title",
          "value": "ABSearchElementCreateWithConjunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElementCreateWithConjunction(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchElementCreateWithConjunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyArrayOfMatchingRecords(_:_:)/title",
          "value": "ABCopyArrayOfMatchingRecords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyArrayOfMatchingRecords(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABCopyArrayOfMatchingRecords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElementRef/title",
          "value": "ABSearchElementRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElementRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchElementRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElementRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchElementRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCreateSearchElement(_:_:_:_:_:)/title",
          "value": "ABGroupCreateSearchElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCreateSearchElement(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupCreateSearchElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abcopyarrayofmatchingrecords(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abcopyarrayofmatchingrecords(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
