{
  "abstract": [
    {
      "text": "Prototype for a function callback invoked on an address book when the Address Book database is modified by another address book instance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABExternalChangeCallback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@ABExternalChangeCallback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ABExternalChangeCallback"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABExternalChangeCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "ABExternalChangeCallback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABExternalChangeCallback"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABAddressBookRef",
              "text": "ABAddressBook"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An address book used to interact with the Address Book database.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "addressBook"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Always ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "info"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The object to pass to the callback function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you name your callback function ",
              "type": "text"
            },
            {
              "code": "MyAddressBookExternalChangeCallback",
              "type": "codeVoice"
            },
            {
              "text": ", you declare it like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Discussion",
          "level": 3,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRegisterExternalChangeCallback(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to register and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookUnregisterExternalChangeCallback(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to unregister the callback function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can register for a callback with different contexts or callback functions. The run loop on the thread that registered the callback invokes the callback.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "addressBook",
              "type": "codeVoice"
            },
            {
              "text": " object does not take any action to flush or synchronize cached state with the Address Book database. If you want to ensure that ",
              "type": "text"
            },
            {
              "code": "addressBook",
              "type": "codeVoice"
            },
            {
              "text": " doesn’t contain stale values, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRevert(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef": {
      "abstract": [
        {
          "text": "A reference to an ABAddressBook object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBook",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRegisterExternalChangeCallback(_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback to receive notifications when the Address Book database is modified.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBookRegisterExternalChangeCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBook"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABExternalChangeCallback",
          "text": "ABExternalChangeCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRegisterExternalChangeCallback(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBookRegisterExternalChangeCallback"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBookRegisterExternalChangeCallback(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookregisterexternalchangecallback(_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRequestAccessCompletionHandler": {
      "abstract": [
        {
          "text": "Definition for a block callback invoked when an access request has completed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBookRequestAccessCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRequestAccessCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBookRequestAccessCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBookRequestAccessCompletionHandler",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookrequestaccesscompletionhandler"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRevert(_:)": {
      "abstract": [
        {
          "text": "Discards unsaved changes in an address book.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBookRevert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBook"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRevert(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBookRevert"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBookRevert(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookrevert(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookUnregisterExternalChangeCallback(_:_:_:)": {
      "abstract": [
        {
          "text": "Unregisters a callback.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBookUnregisterExternalChangeCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBook"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABExternalChangeCallback",
          "text": "ABExternalChangeCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookUnregisterExternalChangeCallback(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBookUnregisterExternalChangeCallback"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBookUnregisterExternalChangeCallback(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookunregisterexternalchangecallback(_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABExternalChangeCallback": {
      "abstract": [
        {
          "text": "Prototype for a function callback invoked on an address book when the Address Book database is modified by another address book instance.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABExternalChangeCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABExternalChangeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABExternalChangeCallback"
        }
      ],
      "role": "symbol",
      "title": "ABExternalChangeCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abexternalchangecallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifier": {
      "abstract": [
        {
          "text": "Identifies multivalue properties.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultiValueIdentifier"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMultiValueIdentifier"
        }
      ],
      "role": "symbol",
      "title": "ABMultiValueIdentifier",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalueidentifier"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCompositeNameFormat": {
      "abstract": [
        {
          "text": "Indicates a person-name display format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCompositeNameFormat"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCompositeNameFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCompositeNameFormat"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCompositeNameFormat",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncompositenameformat"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSortOrdering": {
      "abstract": [
        {
          "text": "Indicates a person sort ordering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonSortOrdering"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSortOrdering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonSortOrdering"
        }
      ],
      "role": "symbol",
      "title": "ABPersonSortOrdering",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonsortordering"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyID": {
      "abstract": [
        {
          "text": "Integer that identifies a record property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPropertyID"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPropertyID"
        }
      ],
      "role": "symbol",
      "title": "ABPropertyID",
      "type": "topic",
      "url": "/documentation/addressbook/abpropertyid"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias": {
      "abstract": [
        {
          "text": "A reference to an ABRecord object or any of its derivedopaque types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "role": "symbol",
      "title": "ABRecord",
      "type": "topic",
      "url": "/documentation/addressbook/abrecord-swift.typealias"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecordID": {
      "abstract": [
        {
          "text": "Integer that identifies a record.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecordID"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecordID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecordID"
        }
      ],
      "role": "symbol",
      "title": "ABRecordID",
      "type": "topic",
      "url": "/documentation/addressbook/abrecordid"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecordType": {
      "abstract": [
        {
          "text": "Integer that identifies a record type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecordType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecordType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecordType"
        }
      ],
      "role": "symbol",
      "title": "ABRecordType",
      "type": "topic",
      "url": "/documentation/addressbook/abrecordtype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSourceType": {
      "abstract": [
        {
          "text": "Indicates a source type. See ",
          "type": "text"
        },
        {
          "code": "Source Properties",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSourceType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSourceType"
        }
      ],
      "role": "symbol",
      "title": "ABSourceType",
      "type": "topic",
      "url": "/documentation/addressbook/absourcetype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRequestAccessCompletionHandler",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifier",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCompositeNameFormat",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSortOrdering",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyID",
        "doc://com.apple.addressbook/documentation/AddressBook/ABRecordID",
        "doc://com.apple.addressbook/documentation/AddressBook/ABRecordType",
        "doc://com.apple.addressbook/documentation/AddressBook/ABSourceType"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ABExternalChangeCallback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABExternalChangeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABExternalChangeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRequestAccessCompletionHandler",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifier",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCompositeNameFormat",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSortOrdering",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyID",
                "doc://com.apple.addressbook/documentation/AddressBook/ABRecordID",
                "doc://com.apple.addressbook/documentation/AddressBook/ABRecordType",
                "doc://com.apple.addressbook/documentation/AddressBook/ABSourceType"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*Fv(#*1v#*1$@S@__CFDictionary#*v)",
                    "text": "void (*)(const void *, const struct __CFDictionary *, void *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ABExternalChangeCallback"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCompositeNameFormat/title",
          "value": "ABPersonCompositeNameFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCompositeNameFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCompositeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCompositeNameFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCompositeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRequestAccessCompletionHandler/title",
          "value": "ABAddressBookRequestAccessCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRequestAccessCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRequestAccessCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRequestAccessCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRequestAccessCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueIdentifier/title",
          "value": "ABMultiValueIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABExternalChangeCallback/title",
          "value": "ABExternalChangeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABExternalChangeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABExternalChangeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABExternalChangeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABExternalChangeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/title",
          "value": "ABAddressBookRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSourceType/title",
          "value": "ABSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookUnregisterExternalChangeCallback(_:_:_:)/title",
          "value": "ABAddressBookUnregisterExternalChangeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookUnregisterExternalChangeCallback(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookUnregisterExternalChangeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.typealias/title",
          "value": "ABRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonSortOrdering/title",
          "value": "ABPersonSortOrdering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonSortOrdering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonSortOrdering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonSortOrdering/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonSortOrdering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordType/title",
          "value": "ABRecordType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordID/title",
          "value": "ABRecordID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyID/title",
          "value": "ABPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRevert(_:)/title",
          "value": "ABAddressBookRevert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRevert(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRevert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRegisterExternalChangeCallback(_:_:_:)/title",
          "value": "ABAddressBookRegisterExternalChangeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRegisterExternalChangeCallback(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRegisterExternalChangeCallback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abexternalchangecallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abexternalchangecallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
