{
  "abstract": [
    {
      "text": "Returns an array containing a group’s subgroups.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyArrayOfAllSubgroups(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@ABGroupCopyArrayOfAllSubgroups",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ABGroupCopyArrayOfAllSubgroups"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABGroupRef",
        "text": "ABGroupRef"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": ">!"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABGroupCopyArrayOfAllSubgroups"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "ABGroupCopyArrayOfAllSubgroups(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABGroupCopyArrayOfAllSubgroups"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "group"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABGroupRef",
              "text": "ABGroupRef"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": ">!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ABGroup object whose subgroups you wish to obtain.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "group"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An array of ABGroupobjects representing the subgroups of ",
              "type": "text"
            },
            {
              "code": "group",
              "type": "codeVoice"
            },
            {
              "text": ".If ",
              "type": "text"
            },
            {
              "code": "group",
              "type": "codeVoice"
            },
            {
              "text": " doesn’t contain any groups,this function returns an empty array. You are responsible for releasingthis object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfAllGroups(_:)": {
      "abstract": [
        {
          "text": "Returns an array of all the groups in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABCopyArrayOfAllGroups"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBookRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfAllGroups(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABCopyArrayOfAllGroups"
        }
      ],
      "role": "symbol",
      "title": "ABCopyArrayOfAllGroups(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abcopyarrayofallgroups(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddGroup(_:_:)": {
      "abstract": [
        {
          "text": "Adds a subgroup to another group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupAddGroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABGroupRef",
          "text": "ABGroupRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABGroupRef",
          "text": "ABGroupRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddGroup(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupAddGroup"
        }
      ],
      "role": "symbol",
      "title": "ABGroupAddGroup(_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupaddgroup(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddMember(_:_:)": {
      "abstract": [
        {
          "text": "Adds a person to a group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupAddMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddMember(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupAddMember"
        }
      ],
      "role": "symbol",
      "title": "ABGroupAddMember(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupaddmember(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyArrayOfAllMembers(_:)": {
      "abstract": [
        {
          "text": "Returns an array of persons in a group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupCopyArrayOfAllMembers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyArrayOfAllMembers(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupCopyArrayOfAllMembers"
        }
      ],
      "role": "symbol",
      "title": "ABGroupCopyArrayOfAllMembers(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupcopyarrayofallmembers(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyArrayOfAllSubgroups(_:)": {
      "abstract": [
        {
          "text": "Returns an array containing a group’s subgroups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupCopyArrayOfAllSubgroups"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABGroupRef",
          "text": "ABGroupRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyArrayOfAllSubgroups(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupCopyArrayOfAllSubgroups"
        }
      ],
      "role": "symbol",
      "title": "ABGroupCopyArrayOfAllSubgroups(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupcopyarrayofallsubgroups(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyDistributionIdentifier(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the distribution identifier for the given propertyand person.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupCopyDistributionIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABGroupRef",
          "text": "ABGroupRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPersonRef",
          "text": "ABPersonRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyDistributionIdentifier(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupCopyDistributionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "ABGroupCopyDistributionIdentifier(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupcopydistributionidentifier(_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyParentGroups(_:)": {
      "abstract": [
        {
          "text": "Returns an array containing a group’s parents—thegroups that a group belongs to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupCopyParentGroups"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABGroupRef",
          "text": "ABGroupRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyParentGroups(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupCopyParentGroups"
        }
      ],
      "role": "symbol",
      "title": "ABGroupCopyParentGroups(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupcopyparentgroups(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreate()": {
      "abstract": [
        {
          "text": "Returns a new ABGroup object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupCreate"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupCreate"
        }
      ],
      "role": "symbol",
      "title": "ABGroupCreate()",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupcreate()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreateSearchElement(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an ABSearchElement object that specifies a queryfor ABGroup records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupCreateSearchElement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchComparison",
          "text": "ABSearchComparison"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchElementRef",
          "text": "ABSearchElementRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreateSearchElement(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupCreateSearchElement"
        }
      ],
      "role": "symbol",
      "title": "ABGroupCreateSearchElement(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupcreatesearchelement(_:_:_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRef": {
      "abstract": [
        {
          "text": "A reference to an ABGroup object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupRef"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupRef"
        }
      ],
      "role": "symbol",
      "title": "ABGroupRef",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveGroup(_:_:)": {
      "abstract": [
        {
          "text": "Removes a subgroup from a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupRemoveGroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABGroupRef",
          "text": "ABGroupRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABGroupRef",
          "text": "ABGroupRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveGroup(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupRemoveGroup"
        }
      ],
      "role": "symbol",
      "title": "ABGroupRemoveGroup(_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupremovegroup(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveMember(_:_:)": {
      "abstract": [
        {
          "text": "Removes a person from a group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupRemoveMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveMember(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupRemoveMember"
        }
      ],
      "role": "symbol",
      "title": "ABGroupRemoveMember(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupremovemember(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupSetDistributionIdentifier(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Assigning a specific distribution identifier for a person’smulti-value list property so that the group can be used as a distributionlist (mailing list, in the case of an email property).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupSetDistributionIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABGroupRef",
          "text": "ABGroupRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPersonRef",
          "text": "ABPersonRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupSetDistributionIdentifier(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupSetDistributionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "ABGroupSetDistributionIdentifier(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupsetdistributionidentifier(_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Groups",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfAllGroups(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddGroup(_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddMember(_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyArrayOfAllMembers(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyDistributionIdentifier(_:_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyParentGroups(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreate()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreateSearchElement(_:_:_:_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveGroup(_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveMember(_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupSetDistributionIdentifier(_:_:_:_:)"
      ],
      "title": "Groups"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ABGroupCopyArrayOfAllSubgroups"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupCopyArrayOfAllSubgroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Groups",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfAllGroups(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddGroup(_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddMember(_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyArrayOfAllMembers(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyDistributionIdentifier(_:_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCopyParentGroups(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreate()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreateSearchElement(_:_:_:_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveGroup(_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveMember(_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupSetDistributionIdentifier(_:_:_:_:)"
              ],
              "title": "Groups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ABGroupCopyArrayOfAllSubgroups"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABGroupRef",
                    "text": "ABGroupRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "group"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ABGroup object whose subgroups you wish to obtain.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "group"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An array of ABGroupobjects representing the subgroups of ",
                    "type": "text"
                  },
                  {
                    "code": "group",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".If ",
                    "type": "text"
                  },
                  {
                    "code": "group",
                    "type": "codeVoice"
                  },
                  {
                    "text": " doesn’t contain any groups,this function returns an empty array. You are responsible for releasingthis object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupAddMember(_:_:)/title",
          "value": "ABGroupAddMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupAddMember(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupAddMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupSetDistributionIdentifier(_:_:_:_:)/title",
          "value": "ABGroupSetDistributionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupSetDistributionIdentifier(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupSetDistributionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRef/title",
          "value": "ABGroupRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyArrayOfAllGroups(_:)/title",
          "value": "ABCopyArrayOfAllGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyArrayOfAllGroups(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABCopyArrayOfAllGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupAddGroup(_:_:)/title",
          "value": "ABGroupAddGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupAddGroup(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupAddGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCopyArrayOfAllMembers(_:)/title",
          "value": "ABGroupCopyArrayOfAllMembers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCopyArrayOfAllMembers(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupCopyArrayOfAllMembers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCopyDistributionIdentifier(_:_:_:)/title",
          "value": "ABGroupCopyDistributionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCopyDistributionIdentifier(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupCopyDistributionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCreate()/title",
          "value": "ABGroupCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCreate()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCreateSearchElement(_:_:_:_:_:)/title",
          "value": "ABGroupCreateSearchElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCreateSearchElement(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupCreateSearchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRemoveGroup(_:_:)/title",
          "value": "ABGroupRemoveGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRemoveGroup(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupRemoveGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCopyArrayOfAllSubgroups(_:)/title",
          "value": "ABGroupCopyArrayOfAllSubgroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCopyArrayOfAllSubgroups(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupCopyArrayOfAllSubgroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCopyParentGroups(_:)/title",
          "value": "ABGroupCopyParentGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCopyParentGroups(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupCopyParentGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRemoveMember(_:_:)/title",
          "value": "ABGroupRemoveMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRemoveMember(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupRemoveMember"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abgroupcopyarrayofallsubgroups(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abgroupcopyarrayofallsubgroups(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
