{
  "abstract": [
    {
      "text": "Prototype of a callback function used to notify an application when an asynchronous image fetch is complete.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABImageClientCallback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@ABImageClientCallback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ABImageClientCallback"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABImageClientCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "ABImageClientCallback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABImageClientCallback"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDataRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDataRef",
              "text": "CFData"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFIndex",
              "text": "CFIndex"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The image data in Quicktime compatible format that was loaded from an asynchronous fetch. ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if the fetch failed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "imageData"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tracking number for this fetch that should have been obtained from a previous call to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABBeginLoadingImageDataForClient(_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tag"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An untyped pointer to program-defined data that was passed to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABBeginLoadingImageDataForClient(_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "info"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABBeginLoadingImageDataForClient(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to begin an asynchronous fetch, and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABCancelLoadingImageDataForTag(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to cancel an asynchronous fetch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionCopyTitleCallback": {
      "abstract": [
        {
          "text": "The title of the menu item for the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionCopyTitleCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionCopyTitleCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionCopyTitleCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactioncopytitlecallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionEnabledCallback": {
      "abstract": [
        {
          "text": "Return ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": " ifthe action menu item should be enabled, ",
          "type": "text"
        },
        {
          "code": "false",
          "type": "codeVoice"
        },
        {
          "text": " otherwise.If the property returned by ",
          "type": "text"
        },
        {
          "code": "ABActionGetPropertyCallback",
          "type": "codeVoice"
        },
        {
          "text": " isa multi-value property, ",
          "type": "text"
        },
        {
          "code": "identifier",
          "type": "codeVoice"
        },
        {
          "text": " contains theunique identifier of the value selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionEnabledCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionEnabledCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionEnabledCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactionenabledcallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback": {
      "abstract": [
        {
          "text": "Return the property the action applies to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionGetPropertyCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionGetPropertyCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactiongetpropertycallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionSelectedCallback": {
      "abstract": [
        {
          "text": "Execute the action. If the property returnedby ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " isa multi-value property, ",
          "type": "text"
        },
        {
          "code": "identifier",
          "type": "codeVoice"
        },
        {
          "text": " containsthe unique identifier of the value selected; otherwise, identifieris ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionSelectedCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionSelectedCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionSelectedCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactionselectedcallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABBeginLoadingImageDataForClient(_:_:_:)": {
      "abstract": [
        {
          "text": "Starts an asynchronous fetch for image data in all locations, and returns a non-zero tag for tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABBeginLoadingImageDataForClient"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPersonRef",
          "text": "ABPersonRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABImageClientCallback",
          "text": "ABImageClientCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABBeginLoadingImageDataForClient(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABBeginLoadingImageDataForClient"
        }
      ],
      "role": "symbol",
      "title": "ABBeginLoadingImageDataForClient(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abbeginloadingimagedataforclient(_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABCancelLoadingImageDataForTag(_:)": {
      "abstract": [
        {
          "text": "Cancels an asynchronous fetch of an image for the given tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABCancelLoadingImageDataForTag"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABCancelLoadingImageDataForTag(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABCancelLoadingImageDataForTag"
        }
      ],
      "role": "symbol",
      "title": "ABCancelLoadingImageDataForTag(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abcancelloadingimagedatafortag(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABImageClientCallback": {
      "abstract": [
        {
          "text": "Prototype of a callback function used to notify an application when an asynchronous image fetch is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABImageClientCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABImageClientCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABImageClientCallback"
        }
      ],
      "role": "symbol",
      "title": "ABImageClientCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abimageclientcallback"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDataRef": {
      "abstract": [
        {
          "text": "A reference to an immutable CFData object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFData"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDataRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFData",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdata"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFIndex": {
      "abstract": [
        {
          "text": "Priority values used for kAXPriorityKey",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFIndex",
      "type": "topic",
      "url": "/documentation/corefoundation/cfindex"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ABImageClientCallback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClientCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClientCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Callbacks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABActionCopyTitleCallback",
                "doc://com.apple.addressbook/documentation/AddressBook/ABActionEnabledCallback",
                "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback",
                "doc://com.apple.addressbook/documentation/AddressBook/ABActionSelectedCallback"
              ],
              "title": "Callbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*Fv(#*1$@S@__CFData#L#*v)",
                    "text": "void (*)(const struct __CFData *, long, void *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ABImageClientCallback"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClientCallback/title",
          "value": "ABImageClientCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClientCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClientCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClientCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClientCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABBeginLoadingImageDataForClient(_:_:_:)/title",
          "value": "ABBeginLoadingImageDataForClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABBeginLoadingImageDataForClient(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABBeginLoadingImageDataForClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDataRef/title",
          "value": "CFDataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCancelLoadingImageDataForTag(_:)/title",
          "value": "ABCancelLoadingImageDataForTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCancelLoadingImageDataForTag(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABCancelLoadingImageDataForTag"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abimageclientcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abimageclientcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
