{
  "abstract": [
    {
      "text": "An immutable representation of a property that might have multiple values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ABMultiValue",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ABMultiValue"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABMultiValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ABMultiValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABMultiValue"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each value in a multivalue list must be of the same type, and must have an associated predefined or user-defined label, and unique identifier. The labels, however, need not be unique. For example, you can have multiple Home phone numbers. Each multivalue object may have a primary identifier—used as a default value when a label is not provided. For example, a person record may have multiple addresses with the labels Home and Work, where Work is designated as the primary value. Instances of this class are immutable, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for methods that manipulate the content of a multivalue list.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "ABMultiValue",
              "type": "codeVoice"
            },
            {
              "text": " class is “toll-free bridged” with its procedural C opaque-type counterpart. This means that the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type is interchangeable in function or method calls with instances of the ",
              "type": "text"
            },
            {
              "code": "ABMultiValue",
              "type": "codeVoice"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroup": {
      "abstract": [
        {
          "text": "An object that represents a group of records in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroup"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroup"
        }
      ],
      "role": "symbol",
      "title": "ABGroup",
      "type": "topic",
      "url": "/documentation/addressbook/abgroup"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABImageClient": {
      "abstract": [
        {
          "text": "Methods for responding to a request to load images associated with a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABImageClient"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABImageClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABImageClient"
        }
      ],
      "role": "symbol",
      "title": "ABImageClient",
      "type": "topic",
      "url": "/documentation/addressbook/abimageclient"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue": {
      "abstract": [
        {
          "text": "An immutable representation of a property that might have multiple values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultiValue"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMultiValue"
        }
      ],
      "role": "symbol",
      "title": "ABMultiValue",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalue"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/count()": {
      "abstract": [
        {
          "text": "Returns the number of entries in a multivalue list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/count()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "role": "symbol",
      "title": "count()",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalue/count()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/identifier(at:)": {
      "abstract": [
        {
          "text": "Returns the identifier for the given index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/identifier(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifierAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "identifier(at:)",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalue/identifier(at:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/index(forIdentifier:)": {
      "abstract": [
        {
          "text": "Returns the index for the given identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/index(forIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexForIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "index(forIdentifier:)",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalue/index(foridentifier:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/label(at:)": {
      "abstract": [
        {
          "text": "Returns the label for the given index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/label(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "labelAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "label(at:)",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalue/label(at:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/label(forIdentifier:)": {
      "abstract": [
        {
          "text": "Returns the label for the given identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/label(forIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "labelForIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "label(forIdentifier:)",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalue/label(foridentifier:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/primaryIdentifier()": {
      "abstract": [
        {
          "text": "Returns the identifier for the primary value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryIdentifier"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/primaryIdentifier()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryIdentifier"
        }
      ],
      "role": "symbol",
      "title": "primaryIdentifier()",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalue/primaryidentifier()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/propertyType()": {
      "abstract": [
        {
          "text": "Returns the type for the values in a multivalue list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertyType"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyType",
          "text": "ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/propertyType()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertyType"
        }
      ],
      "role": "symbol",
      "title": "propertyType()",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalue/propertytype()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/value(at:)": {
      "abstract": [
        {
          "text": "Returns the value for the given index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/value(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "value(at:)",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalue/value(at:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/value(forIdentifier:)": {
      "abstract": [
        {
          "text": "Returns the value for the given identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/value(forIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "value(forIdentifier:)",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalue/value(foridentifier:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef": {
      "abstract": [
        {
          "text": "A reference to an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "ABMutableMultiValueobject",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultiValue"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMultiValue"
        }
      ],
      "role": "symbol",
      "title": "ABMultiValue",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalueref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValue": {
      "abstract": [
        {
          "text": "A mutable representation of a property that might have multiple values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMutableMultiValue"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMutableMultiValue"
        }
      ],
      "role": "symbol",
      "title": "ABMutableMultiValue",
      "type": "topic",
      "url": "/documentation/addressbook/abmutablemultivalue"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPerson": {
      "abstract": [
        {
          "text": "An object that encapsulates all information about a person in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPerson"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPerson"
        }
      ],
      "role": "symbol",
      "title": "ABPerson",
      "type": "topic",
      "url": "/documentation/addressbook/abperson"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class": {
      "abstract": [
        {
          "text": "An abstract class that defines the common properties for all Address Book records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "role": "symbol",
      "title": "ABRecord",
      "type": "topic",
      "url": "/documentation/addressbook/abrecord-swift.class"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to support fast enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSFastEnumeration"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFastEnumeration",
      "type": "topic",
      "url": "/documentation/foundation/nsfastenumeration"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying": {
      "abstract": [
        {
          "text": "A protocol that mutable objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSMutableCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableCopying",
      "type": "topic",
      "url": "/documentation/foundation/nsmutablecopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValue"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPerson",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroup",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValue",
        "doc://com.apple.addressbook/documentation/AddressBook/ABImageClient",
        "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-primary-identifier",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/primaryIdentifier()"
      ],
      "title": "Accessing the primary identifier"
    },
    {
      "anchor": "Accessing-identifiers",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/identifier(at:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/index(forIdentifier:)"
      ],
      "title": "Accessing identifiers"
    },
    {
      "anchor": "Accessing-entries",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/label(at:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/value(at:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/value(forIdentifier:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/label(forIdentifier:)"
      ],
      "title": "Accessing entries"
    },
    {
      "anchor": "Querying-the-list",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/count()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/propertyType()"
      ],
      "title": "Querying the list"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ABMultiValue"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-primary-identifier",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/primaryIdentifier()"
              ],
              "title": "Accessing the primary identifier"
            },
            {
              "anchor": "Accessing-identifiers",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/identifier(at:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/index(forIdentifier:)"
              ],
              "title": "Accessing identifiers"
            },
            {
              "anchor": "Accessing-entries",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/label(at:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/value(at:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/value(forIdentifier:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/label(forIdentifier:)"
              ],
              "title": "Accessing entries"
            },
            {
              "anchor": "Querying-the-list",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/count()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValue/propertyType()"
              ],
              "title": "Querying the list"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValue"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABPerson",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroup",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValue",
                "doc://com.apple.addressbook/documentation/AddressBook/ABImageClient",
                "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ABMultiValue"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1value(forIdentifier:)/title",
          "value": "valueForIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1value(forIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valueForIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1count()/title",
          "value": "count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1count()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMutableMultiValue/title",
          "value": "ABMutableMultiValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMutableMultiValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMutableMultiValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMutableMultiValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMutableMultiValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1primaryIdentifier()/title",
          "value": "primaryIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1primaryIdentifier()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "primaryIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1value(at:)/title",
          "value": "valueAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1value(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valueAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.class/title",
          "value": "ABRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1label(at:)/title",
          "value": "labelAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1label(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "labelAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1index(forIdentifier:)/title",
          "value": "indexForIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1index(forIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexForIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroup/title",
          "value": "ABGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/title",
          "value": "ABMultiValueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue/title",
          "value": "ABMultiValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClient/title",
          "value": "ABImageClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1identifier(at:)/title",
          "value": "identifierAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1identifier(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "identifierAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1propertyType()/title",
          "value": "propertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1propertyType()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "propertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson/title",
          "value": "ABPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1label(forIdentifier:)/title",
          "value": "labelForIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValue~1label(forIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "labelForIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abmultivalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abmultivalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
