{
  "abstract": [
    {
      "text": "Returns a search element object that specifies a query for records of this type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateSearchElement(_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@ABPersonCreateSearchElement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ABPersonCreateSearchElement"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFTypeRef",
        "text": "CFTypeRef"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABSearchComparison",
        "text": "ABSearchComparison"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABSearchElementRef",
        "text": "ABSearchElementRef"
      },
      {
        "kind": "text",
        "text": ">!"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABPersonCreateSearchElement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "ABPersonCreateSearchElement(_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABPersonCreateSearchElement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "property"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "label"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "comparison"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABSearchComparison",
              "text": "ABSearchComparison"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABSearchElementRef",
              "text": "ABSearchElementRef"
            },
            {
              "kind": "text",
              "text": ">!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the property to search on. It cannot be ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ". For a full list of the properties, see ",
                  "type": "text"
                },
                {
                  "code": "Person Properties",
                  "type": "codeVoice"
                },
                {
                  "text": " and Common Properties in ABRecord.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "property"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The label name for a multi-value list. If ",
                  "type": "text"
                },
                {
                  "code": "property",
                  "type": "codeVoice"
                },
                {
                  "text": " does not have multiple values, pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ". If ",
                  "type": "text"
                },
                {
                  "code": "property",
                  "type": "codeVoice"
                },
                {
                  "text": " does have multiple values, pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to search all the values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "label"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The key name for a dictionary. If ",
                  "type": "text"
                },
                {
                  "code": "property",
                  "type": "codeVoice"
                },
                {
                  "text": " is not a dictionary, pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ". If ",
                  "type": "text"
                },
                {
                  "code": "property",
                  "type": "codeVoice"
                },
                {
                  "text": " is a dictionary, pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to search all keys.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "key"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The value you are searching for. It cannot be ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Specifies the type of comparison to perform, such as ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEqual",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPrefixMatchCaseInsensitive",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". For a full list, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "comparison"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A search element object that specifies a query according to the above parameters. You are responsible for releasing this object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ABAddressBook ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfMatchingRecords(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to actually perform the query. Also, see ",
              "type": "text"
            },
            {
              "code": "ABSearchElement C",
              "type": "codeVoice"
            },
            {
              "text": " for more functions that create compound queries.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfAllPeople(_:)": {
      "abstract": [
        {
          "text": "Returns an array of all the people in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABCopyArrayOfAllPeople"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBookRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfAllPeople(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABCopyArrayOfAllPeople"
        }
      ],
      "role": "symbol",
      "title": "ABCopyArrayOfAllPeople(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abcopyarrayofallpeople(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfMatchingRecords(_:_:)": {
      "abstract": [
        {
          "text": "Returns an array of records that match the given search element, or an empty array if no records match the search element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABCopyArrayOfMatchingRecords"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBookRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchElementRef",
          "text": "ABSearchElementRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfMatchingRecords(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABCopyArrayOfMatchingRecords"
        }
      ],
      "role": "symbol",
      "title": "ABCopyArrayOfMatchingRecords(_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abcopyarrayofmatchingrecords(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGetMe(_:)": {
      "abstract": [
        {
          "text": "Returns the ABPerson object for the logged-in user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGetMe"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBookRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPersonRef",
          "text": "ABPersonRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGetMe(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGetMe"
        }
      ],
      "role": "symbol",
      "title": "ABGetMe(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgetme(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyImageData(_:)": {
      "abstract": [
        {
          "text": "Returns data that contains a picture of a person.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCopyImageData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyImageData(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCopyImageData"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCopyImageData(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncopyimagedata(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyParentGroups(_:)": {
      "abstract": [
        {
          "text": "Returns an array of groups that a person belongs to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCopyParentGroups"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPersonRef",
          "text": "ABPersonRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyParentGroups(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCopyParentGroups"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCopyParentGroups(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncopyparentgroups(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyVCardRepresentation(_:)": {
      "abstract": [
        {
          "text": "Returns the vCard representation of the person as a data object in vCard format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCopyVCardRepresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPersonRef",
          "text": "ABPersonRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyVCardRepresentation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCopyVCardRepresentation"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCopyVCardRepresentation(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncopyvcardrepresentation(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreate()": {
      "abstract": [
        {
          "text": "Returns a newly created person object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCreate"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCreate"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCreate()",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncreate()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateSearchElement(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a search element object that specifies a query for records of this type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCreateSearchElement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchComparison",
          "text": "ABSearchComparison"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchElementRef",
          "text": "ABSearchElementRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateSearchElement(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCreateSearchElement"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCreateSearchElement(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncreatesearchelement(_:_:_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateWithVCardRepresentation(_:)": {
      "abstract": [
        {
          "text": "Returns a new ABPerson object initialized with the given data in vCard format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCreateWithVCardRepresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPersonRef",
          "text": "ABPersonRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateWithVCardRepresentation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCreateWithVCardRepresentation"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCreateWithVCardRepresentation(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncreatewithvcardrepresentation(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSetImageData(_:_:)": {
      "abstract": [
        {
          "text": "Sets the image for this person to the given data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonSetImageData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSetImageData(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonSetImageData"
        }
      ],
      "role": "symbol",
      "title": "ABPersonSetImageData(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonsetimagedata(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison": {
      "abstract": [
        {
          "text": "Constants used to specify the type of comparison beingmade.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSearchComparison"
        }
      ],
      "role": "symbol",
      "title": "ABSearchComparison",
      "type": "topic",
      "url": "/documentation/addressbook/absearchcomparison"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementRef": {
      "abstract": [
        {
          "text": "A reference to an ABSearchElement object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSearchElementRef"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSearchElementRef"
        }
      ],
      "role": "symbol",
      "title": "ABSearchElementRef",
      "type": "topic",
      "url": "/documentation/addressbook/absearchelementref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSetMe(_:_:)": {
      "abstract": [
        {
          "text": "Sets the record that represents the logged-in user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSetMe"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBookRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPersonRef",
          "text": "ABPersonRef"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSetMe(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSetMe"
        }
      ],
      "role": "symbol",
      "title": "ABSetMe(_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/absetme(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEqual": {
      "abstract": [
        {
          "text": "Search for elements that are equal to the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEqual",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABEqual",
      "type": "topic",
      "url": "/documentation/addressbook/kabequal"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPrefixMatchCaseInsensitive": {
      "abstract": [
        {
          "text": "Search for elements that begin with the value, ignoring case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPrefixMatchCaseInsensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPrefixMatchCaseInsensitive",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABPrefixMatchCaseInsensitive",
      "type": "topic",
      "url": "/documentation/addressbook/kabprefixmatchcaseinsensitive"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFTypeRef": {
      "abstract": [
        {
          "text": "An untyped \"generic\" reference to any Core Foundation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTypeRef",
      "type": "topic",
      "url": "/documentation/corefoundation/cftyperef"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "People",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfAllPeople(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGetMe(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyImageData(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyParentGroups(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyVCardRepresentation(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreate()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateWithVCardRepresentation(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSetImageData(_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABSetMe(_:_:)"
      ],
      "title": "People"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ABPersonCreateSearchElement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCreateSearchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "People",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfAllPeople(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGetMe(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyImageData(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyParentGroups(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCopyVCardRepresentation(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreate()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateWithVCardRepresentation(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSetImageData(_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABSetMe(_:_:)"
              ],
              "title": "People"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElementRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABSearchElementRef",
                    "text": "ABSearchElementRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ABPersonCreateSearchElement"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "property"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "label"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "key"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFTypeRef",
                    "text": "CFTypeRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABSearchComparison",
                    "text": "ABSearchComparison"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "comparison"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The name of the property to search on. It cannot be ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". For a full list of the properties, see ",
                        "type": "text"
                      },
                      {
                        "code": "Person Properties",
                        "type": "codeVoice"
                      },
                      {
                        "text": " and Common Properties in ABRecord.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "property"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The label name for a multi-value list. If ",
                        "type": "text"
                      },
                      {
                        "code": "property",
                        "type": "codeVoice"
                      },
                      {
                        "text": " does not have multiple values, pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". If ",
                        "type": "text"
                      },
                      {
                        "code": "property",
                        "type": "codeVoice"
                      },
                      {
                        "text": " does have multiple values, pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to search all the values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "label"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The key name for a dictionary. If ",
                        "type": "text"
                      },
                      {
                        "code": "property",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is not a dictionary, pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". If ",
                        "type": "text"
                      },
                      {
                        "code": "property",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is a dictionary, pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to search all keys.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "key"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The value you are searching for. It cannot be ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "value"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Specifies the type of comparison to perform, such as ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEqual",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPrefixMatchCaseInsensitive",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". For a full list, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "comparison"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A search element object that specifies a query according to the above parameters. You are responsible for releasing this object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCopyParentGroups(_:)/title",
          "value": "ABPersonCopyParentGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCopyParentGroups(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCopyParentGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCopyVCardRepresentation(_:)/title",
          "value": "ABPersonCopyVCardRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCopyVCardRepresentation(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCopyVCardRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreate()/title",
          "value": "ABPersonCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreate()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyArrayOfMatchingRecords(_:_:)/title",
          "value": "ABCopyArrayOfMatchingRecords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyArrayOfMatchingRecords(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABCopyArrayOfMatchingRecords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSetMe(_:_:)/title",
          "value": "ABSetMe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSetMe(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSetMe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonSetImageData(_:_:)/title",
          "value": "ABPersonSetImageData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonSetImageData(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonSetImageData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCopyImageData(_:)/title",
          "value": "ABPersonCopyImageData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCopyImageData(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCopyImageData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreateSearchElement(_:_:_:_:_:)/title",
          "value": "ABPersonCreateSearchElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreateSearchElement(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCreateSearchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchComparison/title",
          "value": "ABSearchComparison"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchComparison/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchComparison"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchComparison/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchComparison"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyArrayOfAllPeople(_:)/title",
          "value": "ABCopyArrayOfAllPeople"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyArrayOfAllPeople(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABCopyArrayOfAllPeople"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreateWithVCardRepresentation(_:)/title",
          "value": "ABPersonCreateWithVCardRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreateWithVCardRepresentation(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCreateWithVCardRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElementRef/title",
          "value": "ABSearchElementRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElementRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchElementRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElementRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchElementRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGetMe(_:)/title",
          "value": "ABGetMe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGetMe(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGetMe"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abpersoncreatesearchelement(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abpersoncreatesearchelement(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
