{
  "abstract": [
    {
      "text": "A picker object that you display when you want the user to select contacts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ABPersonPicker",
    "fragments": [
      {
        "kind": "identifier",
        "text": "ABPersonPicker"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABPersonPicker"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ABPersonPicker"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABPersonPicker"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView": {
      "abstract": [
        {
          "text": "An object you use to customize the behavior of people-picker views in an app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPeoplePickerView"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerView"
        }
      ],
      "role": "symbol",
      "title": "ABPeoplePickerView",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerview"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker": {
      "abstract": [
        {
          "text": "A picker object that you display when you want the user to select contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPersonPicker"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPersonPicker",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonpicker"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/close": {
      "abstract": [
        {
          "text": "Closes the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "close"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/close",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "close"
        }
      ],
      "role": "symbol",
      "title": "close",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonpicker/close"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/delegate": {
      "abstract": [
        {
          "text": "An object the system notifies as the user interacts with the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/delegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonpicker/delegate"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/properties": {
      "abstract": [
        {
          "text": "An array of properties to display in the picker when the user selects a person.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "properties"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/properties",
      "kind": "symbol",
      "role": "symbol",
      "title": "properties",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonpicker/properties"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/showRelativeToRect:ofView:preferredEdge:": {
      "abstract": [
        {
          "text": "Shows the picker in a popover relative to a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "showRelativeToRect:ofView:preferredEdge:"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/showRelativeToRect:ofView:preferredEdge:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showRelativeToRect:ofView:preferredEdge:"
        }
      ],
      "role": "symbol",
      "title": "showRelativeToRect:ofView:preferredEdge:",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonpicker/showrelativetorect:ofview:preferrededge:"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPickerDelegate": {
      "abstract": [
        {
          "text": "Methods you use to respond to user selections in a person picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPersonPickerDelegate"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPickerDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPersonPickerDelegate",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonpickerdelegate"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonView": {
      "abstract": [
        {
          "text": "An object that provides a view for displaying and editing contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonView"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonView"
        }
      ],
      "role": "symbol",
      "title": "ABPersonView",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonview"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Pickers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerView",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonView"
      ],
      "title": "Pickers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-the-Picker-Interface",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/delegate",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPickerDelegate"
      ],
      "title": "Managing the Picker Interface"
    },
    {
      "anchor": "Showing-and-Closing-the-Picker",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/showRelativeToRect:ofView:preferredEdge:",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/close"
      ],
      "title": "Showing and Closing the Picker"
    },
    {
      "anchor": "Specifying-Picker-Properties",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonPicker/properties"
      ],
      "title": "Specifying Picker Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonView/title",
          "value": "ABPersonView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView/title",
          "value": "ABPeoplePickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abpersonpicker"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
