{
  "abstract": [
    {
      "text": "Selects a value or a set of values in a multi-value property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerSelectIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@ABPickerSelectIdentifier",
    "fragments": [
      {
        "kind": "identifier",
        "text": "ABPickerSelectIdentifier"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABPickerSelectIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "ABPickerSelectIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABPickerSelectIdentifier"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABPickerRef",
              "text": "ABPickerRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inPicker"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABPersonRef",
              "text": "ABPersonRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inPerson"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inIdentifier"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:b",
              "text": "bool"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inExtendSelection"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The people-picker window to manipulate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inPicker"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The person with the multi-value property with the value to select.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inPerson"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identifier of the value to select in the multi-value property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inIdentifier"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "code": "true",
                  "type": "codeVoice"
                },
                {
                  "text": " if you want to add the value to the list of selected values in the multi-value property of the desired person; ",
                  "type": "text"
                },
                {
                  "code": "false",
                  "type": "codeVoice"
                },
                {
                  "text": " if you want the value to be the only value selected in the list.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inExtendSelection"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonRef": {
      "abstract": [
        {
          "text": "A reference to an ABPerson object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonRef"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonRef"
        }
      ],
      "role": "symbol",
      "title": "ABPersonRef",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAddProperty": {
      "abstract": [
        {
          "text": "Adds a property to the group of properties available in the record list. Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerRemoveProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to remove a property from the list and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopyProperties",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to obtain the list of properties available in the list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerAddProperty"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAddProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerAddProperty",
      "type": "topic",
      "url": "/documentation/addressbook/abpickeraddproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerChangeAttributes": {
      "abstract": [
        {
          "text": "Specifies the selection behaviors for a people-picker window. Use ",
          "type": "text"
        },
        {
          "code": "ABPickerGetAttributes",
          "type": "codeVoice"
        },
        {
          "text": " to obtain the selection behaviors specified for the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerChangeAttributes"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerChangeAttributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerChangeAttributes",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerchangeattributes"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerClearSearchField": {
      "abstract": [
        {
          "text": "Clears the search field and resets the list of displayed records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerClearSearchField"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerClearSearchField",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerClearSearchField",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerclearsearchfield"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopyColumnTitle": {
      "abstract": [
        {
          "text": "Obtains the title of a custom property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerCopyColumnTitle"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopyColumnTitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerCopyColumnTitle",
      "type": "topic",
      "url": "/documentation/addressbook/abpickercopycolumntitle"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopyDisplayedProperty": {
      "abstract": [
        {
          "text": "Returns the name of the property currently displayed in the record list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerCopyDisplayedProperty"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopyDisplayedProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerCopyDisplayedProperty",
      "type": "topic",
      "url": "/documentation/addressbook/abpickercopydisplayedproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopyProperties": {
      "abstract": [
        {
          "text": "Obtains the list of properties available in the record list. Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAddProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to add a property to the record list and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerRemoveProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to remove a property from the list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerCopyProperties"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopyProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerCopyProperties",
      "type": "topic",
      "url": "/documentation/addressbook/abpickercopyproperties"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedGroups": {
      "abstract": [
        {
          "text": "Returns the groups selected in the group list as an array of ",
          "type": "text"
        },
        {
          "code": "ABRecord C",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerCopySelectedGroups"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedGroups",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerCopySelectedGroups",
      "type": "topic",
      "url": "/documentation/addressbook/abpickercopyselectedgroups"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedIdentifiers": {
      "abstract": [
        {
          "text": "Returns the identifiers of the selected values in a multi-value property or an empty array if the property displayed is a single-value property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerCopySelectedIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedIdentifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerCopySelectedIdentifiers",
      "type": "topic",
      "url": "/documentation/addressbook/abpickercopyselectedidentifiers"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedRecords": {
      "abstract": [
        {
          "text": "Returns the selection in the record list as an array of ABGroup or ",
          "type": "text"
        },
        {
          "code": "ABPerson C",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerCopySelectedRecords"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedRecords",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerCopySelectedRecords",
      "type": "topic",
      "url": "/documentation/addressbook/abpickercopyselectedrecords"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedValues": {
      "abstract": [
        {
          "text": "Returns the selected values in a multi-value property or an empty array if no values are selected or the property displayedis a single-value property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerCopySelectedValues"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedValues",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerCopySelectedValues",
      "type": "topic",
      "url": "/documentation/addressbook/abpickercopyselectedvalues"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCreate": {
      "abstract": [
        {
          "text": "Creates an ABPickerRef. The corresponding window is hidden. Invoke ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerSetVisibility",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to show it. Release with ",
          "type": "text"
        },
        {
          "code": "CFRelease",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerCreate"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerCreate",
      "type": "topic",
      "url": "/documentation/addressbook/abpickercreate"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectAll": {
      "abstract": [
        {
          "text": "Deselects all selected groups, records, and values in multi-value properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerDeselectAll"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectAll",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerDeselectAll",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerdeselectall"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectGroup": {
      "abstract": [
        {
          "text": "Deselects a group in the group list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerDeselectGroup"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerDeselectGroup",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerdeselectgroup"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectIdentifier": {
      "abstract": [
        {
          "text": "Deselects a value in multi-value property currently displayed in the record list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerDeselectIdentifier"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerDeselectIdentifier",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerdeselectidentifier"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectRecord": {
      "abstract": [
        {
          "text": "Deselects a group in the record list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerDeselectRecord"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectRecord",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerDeselectRecord",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerdeselectrecord"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerRef": {
      "abstract": [
        {
          "text": "A reference to an ABPicker object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerRef"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerRef",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerRemoveProperty": {
      "abstract": [
        {
          "text": "Removes a property from the group of properties whose values are shown in the record list. Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAddProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to add a property to the record list and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopyProperties",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to obtain the list of properties shown in the record list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerRemoveProperty"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerRemoveProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerRemoveProperty",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerremoveproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerSelectIdentifier": {
      "abstract": [
        {
          "text": "Selects a value or a set of values in a multi-value property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerSelectIdentifier"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerSelectIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerSelectIdentifier",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerselectidentifier"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerSetVisibility": {
      "abstract": [
        {
          "text": "Shows or hides a people-picker window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerSetVisibility"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerSetVisibility",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerSetVisibility",
      "type": "topic",
      "url": "/documentation/addressbook/abpickersetvisibility"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAddProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerChangeAttributes",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerClearSearchField",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopyColumnTitle",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopyDisplayedProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopyProperties",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedGroups",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedIdentifiers",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedRecords",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCopySelectedValues",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerCreate",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectAll",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectGroup",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectIdentifier",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPickerDeselectRecord"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonRef/title",
          "value": "ABPersonRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abpickerselectidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
