{
  "abstract": [
    {
      "text": "Constants used to specify the type of comparison beingmade.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@ABSearchComparison",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ABSearchComparison"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABSearchComparison"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "ABSearchComparison"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABSearchComparison"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFIndex",
              "text": "CFIndex"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants are used in a call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreateSearchElement(_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateSearchElement(_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functionto specify the type of comparison being made.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreateSearchElement(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an ABSearchElement object that specifies a queryfor ABGroup records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupCreateSearchElement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchComparison",
          "text": "ABSearchComparison"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchElementRef",
          "text": "ABSearchElementRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreateSearchElement(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupCreateSearchElement"
        }
      ],
      "role": "symbol",
      "title": "ABGroupCreateSearchElement(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupcreatesearchelement(_:_:_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateSearchElement(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a search element object that specifies a query for records of this type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCreateSearchElement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchComparison",
          "text": "ABSearchComparison"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABSearchElementRef",
          "text": "ABSearchElementRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreateSearchElement(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCreateSearchElement"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCreateSearchElement(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncreatesearchelement(_:_:_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison": {
      "abstract": [
        {
          "text": "Constants used to specify the type of comparison beingmade.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSearchComparison"
        }
      ],
      "role": "symbol",
      "title": "ABSearchComparison",
      "type": "topic",
      "url": "/documentation/addressbook/absearchcomparison"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSearchConjunction": {
      "abstract": [
        {
          "text": "Constants used to create compound search elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSearchConjunction"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchConjunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSearchConjunction"
        }
      ],
      "role": "symbol",
      "title": "ABSearchConjunction",
      "type": "topic",
      "url": "/documentation/addressbook/absearchconjunction"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABBitsInBitFieldMatch": {
      "abstract": [
        {
          "text": "Search for elements that match the bits in ABPersonFlags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABBitsInBitFieldMatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABBitsInBitFieldMatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABBitsInBitFieldMatch",
      "type": "topic",
      "url": "/documentation/addressbook/kabbitsinbitfieldmatch"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubString": {
      "abstract": [
        {
          "text": "Search for elements that contain the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABContainsSubString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubString",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABContainsSubString",
      "type": "topic",
      "url": "/documentation/addressbook/kabcontainssubstring"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubStringCaseInsensitive": {
      "abstract": [
        {
          "text": "Search for elements that contain the value,ignoring case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABContainsSubStringCaseInsensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubStringCaseInsensitive",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABContainsSubStringCaseInsensitive",
      "type": "topic",
      "url": "/documentation/addressbook/kabcontainssubstringcaseinsensitive"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubString": {
      "abstract": [
        {
          "text": "Search for elements that do not contain the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDoesNotContainSubString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubString",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDoesNotContainSubString",
      "type": "topic",
      "url": "/documentation/addressbook/kabdoesnotcontainsubstring"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubStringCaseInsensitive": {
      "abstract": [
        {
          "text": "Search for elements that do not contain the value, ignoring case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDoesNotContainSubStringCaseInsensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubStringCaseInsensitive",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDoesNotContainSubStringCaseInsensitive",
      "type": "topic",
      "url": "/documentation/addressbook/kabdoesnotcontainsubstringcaseinsensitive"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEqual": {
      "abstract": [
        {
          "text": "Search for elements that are equal to the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEqual",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABEqual",
      "type": "topic",
      "url": "/documentation/addressbook/kabequal"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEqualCaseInsensitive": {
      "abstract": [
        {
          "text": "Search for elements that are equal to the value,ignoring case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEqualCaseInsensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEqualCaseInsensitive",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABEqualCaseInsensitive",
      "type": "topic",
      "url": "/documentation/addressbook/kabequalcaseinsensitive"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABGreaterThan": {
      "abstract": [
        {
          "text": "Search for elements that are greater than thevalue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABGreaterThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABGreaterThan",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABGreaterThan",
      "type": "topic",
      "url": "/documentation/addressbook/kabgreaterthan"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABGreaterThanOrEqual": {
      "abstract": [
        {
          "text": "Search for elements that are greater than orequal to the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABGreaterThanOrEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABGreaterThanOrEqual",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABGreaterThanOrEqual",
      "type": "topic",
      "url": "/documentation/addressbook/kabgreaterthanorequal"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABLessThan": {
      "abstract": [
        {
          "text": "Search for elements that are less than thevalue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABLessThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABLessThan",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABLessThan",
      "type": "topic",
      "url": "/documentation/addressbook/kablessthan"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABLessThanOrEqual": {
      "abstract": [
        {
          "text": "Search for elements that are less than or equalto the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABLessThanOrEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABLessThanOrEqual",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABLessThanOrEqual",
      "type": "topic",
      "url": "/documentation/addressbook/kablessthanorequal"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABNotEqual": {
      "abstract": [
        {
          "text": "Search for elements that are not equal to thevalue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABNotEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABNotEqual",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABNotEqual",
      "type": "topic",
      "url": "/documentation/addressbook/kabnotequal"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABNotEqualCaseInsensitive": {
      "abstract": [
        {
          "text": "Search for elements that are not equal to the value, ignoring case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABNotEqualCaseInsensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABNotEqualCaseInsensitive",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABNotEqualCaseInsensitive",
      "type": "topic",
      "url": "/documentation/addressbook/kabnotequalcaseinsensitive"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalAroundToday": {
      "abstract": [
        {
          "text": "Search for elements that are ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "not",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " within a time interval (in seconds) forward or backward from today.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABNotWithinIntervalAroundToday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalAroundToday",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABNotWithinIntervalAroundToday",
      "type": "topic",
      "url": "/documentation/addressbook/kabnotwithinintervalaroundtoday"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalAroundTodayYearless": {
      "abstract": [
        {
          "text": "Search for elements that are ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "not",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " within a time interval (in seconds) forward or backward from this day in any year.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABNotWithinIntervalAroundTodayYearless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalAroundTodayYearless",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABNotWithinIntervalAroundTodayYearless",
      "type": "topic",
      "url": "/documentation/addressbook/kabnotwithinintervalaroundtodayyearless"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalFromToday": {
      "abstract": [
        {
          "text": "Search for elements that are ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "not",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " within a time interval (in seconds) forward from today.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABNotWithinIntervalFromToday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalFromToday",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABNotWithinIntervalFromToday",
      "type": "topic",
      "url": "/documentation/addressbook/kabnotwithinintervalfromtoday"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalFromTodayYearless": {
      "abstract": [
        {
          "text": "Search for elements that are ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "not",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " within a time interval (in seconds) forward from this day in any year.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABNotWithinIntervalFromTodayYearless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalFromTodayYearless",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABNotWithinIntervalFromTodayYearless",
      "type": "topic",
      "url": "/documentation/addressbook/kabnotwithinintervalfromtodayyearless"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPrefixMatch": {
      "abstract": [
        {
          "text": "Search for elements that begin with the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPrefixMatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPrefixMatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABPrefixMatch",
      "type": "topic",
      "url": "/documentation/addressbook/kabprefixmatch"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPrefixMatchCaseInsensitive": {
      "abstract": [
        {
          "text": "Search for elements that begin with the value, ignoring case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPrefixMatchCaseInsensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPrefixMatchCaseInsensitive",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABPrefixMatchCaseInsensitive",
      "type": "topic",
      "url": "/documentation/addressbook/kabprefixmatchcaseinsensitive"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSuffixMatch": {
      "abstract": [
        {
          "text": "Search for elements that end with the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSuffixMatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSuffixMatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABSuffixMatch",
      "type": "topic",
      "url": "/documentation/addressbook/kabsuffixmatch"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSuffixMatchCaseInsensitive": {
      "abstract": [
        {
          "text": "Search for elements that end with the value, ignoring case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSuffixMatchCaseInsensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSuffixMatchCaseInsensitive",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABSuffixMatchCaseInsensitive",
      "type": "topic",
      "url": "/documentation/addressbook/kabsuffixmatchcaseinsensitive"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalAroundToday": {
      "abstract": [
        {
          "text": "Search for elements that are within a time interval (in seconds) forward or backward from today.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABWithinIntervalAroundToday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalAroundToday",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABWithinIntervalAroundToday",
      "type": "topic",
      "url": "/documentation/addressbook/kabwithinintervalaroundtoday"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalAroundTodayYearless": {
      "abstract": [
        {
          "text": "Search for elements that are within a time interval (in seconds) forward or backward from this day in any year.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABWithinIntervalAroundTodayYearless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalAroundTodayYearless",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABWithinIntervalAroundTodayYearless",
      "type": "topic",
      "url": "/documentation/addressbook/kabwithinintervalaroundtodayyearless"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalFromToday": {
      "abstract": [
        {
          "text": "Search for elements that are within a time interval (in seconds) forward from today.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABWithinIntervalFromToday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalFromToday",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABWithinIntervalFromToday",
      "type": "topic",
      "url": "/documentation/addressbook/kabwithinintervalfromtoday"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalFromTodayYearless": {
      "abstract": [
        {
          "text": "Search for elements that are within a time interval (in seconds) forward from this day in any year.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABWithinIntervalFromTodayYearless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalFromTodayYearless",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABWithinIntervalFromTodayYearless",
      "type": "topic",
      "url": "/documentation/addressbook/kabwithinintervalfromtodayyearless"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFIndex": {
      "abstract": [
        {
          "text": "Priority values used for kAXPriorityKey",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFIndex",
      "type": "topic",
      "url": "/documentation/corefoundation/cfindex"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABSearchConjunction"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABEqual",
        "doc://com.apple.addressbook/documentation/AddressBook/kABNotEqual",
        "doc://com.apple.addressbook/documentation/AddressBook/kABNotEqualCaseInsensitive",
        "doc://com.apple.addressbook/documentation/AddressBook/kABLessThan",
        "doc://com.apple.addressbook/documentation/AddressBook/kABLessThanOrEqual",
        "doc://com.apple.addressbook/documentation/AddressBook/kABGreaterThan",
        "doc://com.apple.addressbook/documentation/AddressBook/kABGreaterThanOrEqual",
        "doc://com.apple.addressbook/documentation/AddressBook/kABEqualCaseInsensitive",
        "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubString",
        "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubStringCaseInsensitive",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPrefixMatch",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPrefixMatchCaseInsensitive",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSuffixMatch",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSuffixMatchCaseInsensitive",
        "doc://com.apple.addressbook/documentation/AddressBook/kABBitsInBitFieldMatch",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubString",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubStringCaseInsensitive",
        "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalAroundToday",
        "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalAroundTodayYearless",
        "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalAroundToday",
        "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalAroundTodayYearless",
        "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalFromToday",
        "doc://com.apple.addressbook/documentation/AddressBook/kABWithinIntervalFromTodayYearless",
        "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalFromToday",
        "doc://com.apple.addressbook/documentation/AddressBook/kABNotWithinIntervalFromTodayYearless"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ABSearchComparison"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchComparison"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchComparison"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABSearchConjunction"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFIndex",
                    "text": "CFIndex"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ABSearchComparison"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreateSearchElement(_:_:_:_:_:)/title",
          "value": "ABPersonCreateSearchElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreateSearchElement(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCreateSearchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchConjunction/title",
          "value": "ABSearchConjunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchConjunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchConjunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchConjunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchConjunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCreateSearchElement(_:_:_:_:_:)/title",
          "value": "ABGroupCreateSearchElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCreateSearchElement(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupCreateSearchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchComparison/title",
          "value": "ABSearchComparison"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchComparison/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchComparison"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchComparison/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchComparison"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/absearchcomparison"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/absearchcomparison"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
