{
  "abstract": [
    {
      "text": "Returns the type of a given property for a given record.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABTypeOfProperty(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@ABTypeOfProperty",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ABTypeOfProperty"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABAddressBookRef",
        "text": "ABAddressBookRef"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABPropertyType",
        "text": "ABPropertyType"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABTypeOfProperty"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "ABTypeOfProperty(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABTypeOfProperty"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "addressBook"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABAddressBookRef",
              "text": "ABAddressBookRef"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "recordType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "property"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABPropertyType",
              "text": "ABPropertyType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The address book for the logged-in user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "addressBook"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The record type that contains ",
                  "type": "text"
                },
                {
                  "code": "property",
                  "type": "codeVoice"
                },
                {
                  "text": ": kABGroupRecordType or kABPersonRecordType.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "recordType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The property whose type you wish to obtain.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "property"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The type of ",
              "type": "text"
            },
            {
              "code": "property",
              "type": "codeVoice"
            },
            {
              "text": " as defined in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If ",
              "type": "text"
            },
            {
              "code": "property",
              "type": "codeVoice"
            },
            {
              "text": " does not exist in ",
              "type": "text"
            },
            {
              "code": "recordType",
              "type": "codeVoice"
            },
            {
              "text": ", this function returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABErrorInProperty",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddPropertiesAndTypes(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds the given properties to all the records of the specified type in the Address Book database, and returns the number of properties successfully added.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddPropertiesAndTypes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBookRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddPropertiesAndTypes(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddPropertiesAndTypes"
        }
      ],
      "role": "symbol",
      "title": "ABAddPropertiesAndTypes(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abaddpropertiesandtypes(_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef": {
      "abstract": [
        {
          "text": "A reference to an ABAddressBook object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBook",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfPropertiesForRecordType(_:_:)": {
      "abstract": [
        {
          "text": "Returns an array containing the names of all the properties for the specified record type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABCopyArrayOfPropertiesForRecordType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBookRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfPropertiesForRecordType(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABCopyArrayOfPropertiesForRecordType"
        }
      ],
      "role": "symbol",
      "title": "ABCopyArrayOfPropertiesForRecordType(_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abcopyarrayofpropertiesforrecordtype(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABCopyLocalizedPropertyOrLabel(_:)": {
      "abstract": [
        {
          "text": "Returns the localized version of a built in property,label, or key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABCopyLocalizedPropertyOrLabel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABCopyLocalizedPropertyOrLabel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABCopyLocalizedPropertyOrLabel"
        }
      ],
      "role": "symbol",
      "title": "ABCopyLocalizedPropertyOrLabel(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abcopylocalizedpropertyorlabel(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABLocalizedPropertyOrLabel(_:)": {
      "abstract": [
        {
          "text": "Returns the localized version of a built in property, label, or key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABLocalizedPropertyOrLabel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABLocalizedPropertyOrLabel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABLocalizedPropertyOrLabel"
        }
      ],
      "role": "symbol",
      "title": "ABLocalizedPropertyOrLabel(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/ablocalizedpropertyorlabel(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType": {
      "abstract": [
        {
          "text": "These are the possible types of ABRecord properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPropertyType"
        }
      ],
      "role": "symbol",
      "title": "ABPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/abpropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRemoveProperties(_:_:_:)": {
      "abstract": [
        {
          "text": "Removes the given properties from all the records of this type in the Address Book database, and returns the number of properties successfully removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRemoveProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBookRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRemoveProperties(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRemoveProperties"
        }
      ],
      "role": "symbol",
      "title": "ABRemoveProperties(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abremoveproperties(_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABTypeOfProperty(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the type of a given property for a given record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABTypeOfProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBookRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyType",
          "text": "ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABTypeOfProperty(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABTypeOfProperty"
        }
      ],
      "role": "symbol",
      "title": "ABTypeOfProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abtypeofproperty(_:_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABErrorInProperty": {
      "abstract": [
        {
          "text": "An invalid property was used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABErrorInProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABErrorInProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABErrorInProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kaberrorinproperty"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddPropertiesAndTypes(_:_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfPropertiesForRecordType(_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABCopyLocalizedPropertyOrLabel(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABLocalizedPropertyOrLabel(_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABRemoveProperties(_:_:_:)"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ABTypeOfProperty"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABTypeOfProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddPropertiesAndTypes(_:_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABCopyArrayOfPropertiesForRecordType(_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABCopyLocalizedPropertyOrLabel(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABLocalizedPropertyOrLabel(_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABRemoveProperties(_:_:_:)"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABPropertyType",
                    "text": "ABPropertyType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ABTypeOfProperty"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABAddressBookRef",
                    "text": "ABAddressBookRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "addressBook"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "recordType"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "property"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The address book for the logged-in user.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "addressBook"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The record type that contains ",
                        "type": "text"
                      },
                      {
                        "code": "property",
                        "type": "codeVoice"
                      },
                      {
                        "text": ": kABGroupRecordType or kABPersonRecordType.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "recordType"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The property whose type you wish to obtain.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "property"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The type of ",
                    "type": "text"
                  },
                  {
                    "code": "property",
                    "type": "codeVoice"
                  },
                  {
                    "text": " as defined in ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ". If ",
                    "type": "text"
                  },
                  {
                    "code": "property",
                    "type": "codeVoice"
                  },
                  {
                    "text": " does not exist in ",
                    "type": "text"
                  },
                  {
                    "code": "recordType",
                    "type": "codeVoice"
                  },
                  {
                    "text": ", this function returns ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABErrorInProperty",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/title",
          "value": "ABAddressBookRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRemoveProperties(_:_:_:)/title",
          "value": "ABRemoveProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRemoveProperties(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRemoveProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddPropertiesAndTypes(_:_:_:)/title",
          "value": "ABAddPropertiesAndTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddPropertiesAndTypes(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddPropertiesAndTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyLocalizedPropertyOrLabel(_:)/title",
          "value": "ABCopyLocalizedPropertyOrLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyLocalizedPropertyOrLabel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABCopyLocalizedPropertyOrLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/title",
          "value": "ABPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABTypeOfProperty(_:_:_:)/title",
          "value": "ABTypeOfProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABTypeOfProperty(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABTypeOfProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABLocalizedPropertyOrLabel(_:)/title",
          "value": "ABLocalizedPropertyOrLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABLocalizedPropertyOrLabel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABLocalizedPropertyOrLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyArrayOfPropertiesForRecordType(_:_:)/title",
          "value": "ABCopyArrayOfPropertiesForRecordType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABCopyArrayOfPropertiesForRecordType(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABCopyArrayOfPropertiesForRecordType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abtypeofproperty(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abtypeofproperty(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
