{
  "abstract": [
    {
      "text": "Get the enumerations you use to specify Address Book information.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AddressBook Enumerations"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1529225-errors": {
      "abstract": [
        {
          "text": "Errors codes returned by the Address Book Framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1529225-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Errors",
      "type": "topic",
      "url": "/documentation/addressbook/1529225-errors"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types": {
      "abstract": [
        {
          "text": "These constants identify record property types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Property Types",
      "type": "topic",
      "url": "/documentation/addressbook/1614731-record-property-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1614747-record-types": {
      "abstract": [
        {
          "text": "These constants identify record types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1614747-record-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Types",
      "type": "topic",
      "url": "/documentation/addressbook/1614747-record-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1619730-sort-order": {
      "abstract": [
        {
          "text": "These constants identify sort order for person lists.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1619730-sort-order",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sort Order",
      "type": "topic",
      "url": "/documentation/addressbook/1619730-sort-order"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1619815-composite-name-format": {
      "abstract": [
        {
          "text": "These constants identify the format to use for a person’s composite name order for person records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1619815-composite-name-format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Composite Name Format",
      "type": "topic",
      "url": "/documentation/addressbook/1619815-composite-name-format"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types": {
      "abstract": [
        {
          "text": "These constants identify the type of a source.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Source Types",
      "type": "topic",
      "url": "/documentation/addressbook/1619878-source-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus": {
      "abstract": [
        {
          "text": "Different possible values for the authorization status of an app with respect to address book data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ABAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/addressbook/abauthorizationstatus"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerSelectionBehavior": {
      "abstract": [
        {
          "text": "Constants indicating the possible value selection behaviors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPeoplePickerSelectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerSelectionBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerSelectionBehavior"
        }
      ],
      "role": "symbol",
      "title": "ABPeoplePickerSelectionBehavior",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerselectionbehavior"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonImageFormat": {
      "abstract": [
        {
          "text": "Indicates an image format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonImageFormat"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonImageFormat"
        }
      ],
      "role": "symbol",
      "title": "ABPersonImageFormat",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonimageformat"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAttributes": {
      "abstract": [
        {
          "text": "A bitfield used to specify the selection behavior for the values of multi-value properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerAttributes"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAttributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerAttributes",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerattributes"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants": {
      "abstract": [
        {
          "text": "Get the constants you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Book Constants",
      "type": "topic",
      "url": "/documentation/addressbook/address-book-constants"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-book-errors": {
      "abstract": [
        {
          "text": "Errors that can be raised under the Address Book error domain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-book-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Book Errors",
      "type": "topic",
      "url": "/documentation/addressbook/address-book-errors"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-data-types": {
      "abstract": [
        {
          "text": "Get the data types you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Data Types",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-data-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions": {
      "abstract": [
        {
          "text": "Find the C functions and function-like macros you use to manipulate Address Book data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Functions",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-functions"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/c-types": {
      "abstract": [
        {
          "text": "Identify the C types that correspond to Address Book objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/c-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "C Types",
      "type": "topic",
      "url": "/documentation/addressbook/c-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/composite-name-format": {
      "abstract": [
        {
          "text": "These constants identify the format to use for a person’s composite name order for person records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/composite-name-format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Composite Name Format",
      "type": "topic",
      "url": "/documentation/addressbook/composite-name-format"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-class": {
      "abstract": [
        {
          "text": "This is the People Picker event class.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-class",
      "kind": "article",
      "role": "collectionGroup",
      "title": "People-Picker Event Class",
      "type": "topic",
      "url": "/documentation/addressbook/people-picker-event-class"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-kinds": {
      "abstract": [
        {
          "text": "Constants used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAttributes",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to specify People Picker event types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-kinds",
      "kind": "article",
      "role": "collectionGroup",
      "title": "People-Picker Event Kinds",
      "type": "topic",
      "url": "/documentation/addressbook/people-picker-event-kinds"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-parameter-name": {
      "abstract": [
        {
          "text": "Use this constant to obtain the ABPicker object from aPeople Picker event.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-parameter-name",
      "kind": "article",
      "role": "collectionGroup",
      "title": "People-Picker Event Parameter Name",
      "type": "topic",
      "url": "/documentation/addressbook/people-picker-event-parameter-name"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/people-picker-selection-behavior": {
      "abstract": [
        {
          "text": "Constants to specify the selection behavior for the values of multi-value properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/people-picker-selection-behavior",
      "kind": "article",
      "role": "collectionGroup",
      "title": "People-Picker Selection Behavior",
      "type": "topic",
      "url": "/documentation/addressbook/people-picker-selection-behavior"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/record-property-types": {
      "abstract": [
        {
          "text": "These constants identify record property types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/record-property-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Property Types",
      "type": "topic",
      "url": "/documentation/addressbook/record-property-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/record-types": {
      "abstract": [
        {
          "text": "These constants identify record types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/record-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Types",
      "type": "topic",
      "url": "/documentation/addressbook/record-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/sort-order": {
      "abstract": [
        {
          "text": "These constants identify sort order for person lists.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/sort-order",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sort Order",
      "type": "topic",
      "url": "/documentation/addressbook/sort-order"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/source-types": {
      "abstract": [
        {
          "text": "These constants identify the type of a source.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/source-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Source Types",
      "type": "topic",
      "url": "/documentation/addressbook/source-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "C-Interfaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/c-types",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions",
        "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-data-types"
      ],
      "title": "C Interfaces"
    }
  ],
  "topicSections": [
    {
      "anchor": "Picker",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerSelectionBehavior",
        "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-class",
        "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-kinds",
        "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-parameter-name",
        "doc://com.apple.addressbook/documentation/AddressBook/people-picker-selection-behavior"
      ],
      "title": "Picker"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/address-book-errors",
        "doc://com.apple.addressbook/documentation/AddressBook/1529225-errors"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Miscellaneous",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/1619815-composite-name-format",
        "doc://com.apple.addressbook/documentation/AddressBook/1614731-record-property-types",
        "doc://com.apple.addressbook/documentation/AddressBook/1614747-record-types",
        "doc://com.apple.addressbook/documentation/AddressBook/1619730-sort-order",
        "doc://com.apple.addressbook/documentation/AddressBook/1619878-source-types"
      ],
      "title": "Miscellaneous"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonImageFormat"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Picker",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerSelectionBehavior",
                "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-class",
                "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-kinds",
                "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-parameter-name",
                "doc://com.apple.addressbook/documentation/AddressBook/people-picker-selection-behavior"
              ],
              "title": "Picker"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/address-book-errors",
                "doc://com.apple.addressbook/documentation/AddressBook/1529225-errors"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Miscellaneous",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/composite-name-format",
                "doc://com.apple.addressbook/documentation/AddressBook/record-property-types",
                "doc://com.apple.addressbook/documentation/AddressBook/record-types",
                "doc://com.apple.addressbook/documentation/AddressBook/sort-order",
                "doc://com.apple.addressbook/documentation/AddressBook/source-types"
              ],
              "title": "Miscellaneous"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonImageFormat"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "C-Interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/c-types",
                "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions",
                "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
                "doc://com.apple.addressbook/documentation/AddressBook/addressbook-data-types"
              ],
              "title": "C Interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonImageFormat/title",
          "value": "ABPersonImageFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonImageFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonImageFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonImageFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus/title",
          "value": "ABAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerSelectionBehavior/title",
          "value": "ABPeoplePickerSelectionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerSelectionBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerSelectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerSelectionBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerSelectionBehavior"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/addressbook-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/addressbook-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
