{
  "abstract": [
    {
      "text": "Get the data types you use to specify Address Book information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AddressBook Data Types"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionCopyTitleCallback": {
      "abstract": [
        {
          "text": "The title of the menu item for the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionCopyTitleCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionCopyTitleCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionCopyTitleCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactioncopytitlecallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionEnabledCallback": {
      "abstract": [
        {
          "text": "Return ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": " ifthe action menu item should be enabled, ",
          "type": "text"
        },
        {
          "code": "false",
          "type": "codeVoice"
        },
        {
          "text": " otherwise.If the property returned by ",
          "type": "text"
        },
        {
          "code": "ABActionGetPropertyCallback",
          "type": "codeVoice"
        },
        {
          "text": " isa multi-value property, ",
          "type": "text"
        },
        {
          "code": "identifier",
          "type": "codeVoice"
        },
        {
          "text": " contains theunique identifier of the value selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionEnabledCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionEnabledCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionEnabledCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactionenabledcallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback": {
      "abstract": [
        {
          "text": "Return the property the action applies to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionGetPropertyCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionGetPropertyCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactiongetpropertycallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionSelectedCallback": {
      "abstract": [
        {
          "text": "Execute the action. If the property returnedby ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " isa multi-value property, ",
          "type": "text"
        },
        {
          "code": "identifier",
          "type": "codeVoice"
        },
        {
          "text": " containsthe unique identifier of the value selected; otherwise, identifieris ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionSelectedCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionSelectedCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionSelectedCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abactionselectedcallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRequestAccessCompletionHandler": {
      "abstract": [
        {
          "text": "Definition for a block callback invoked when an access request has completed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBookRequestAccessCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRequestAccessCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBookRequestAccessCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBookRequestAccessCompletionHandler",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookrequestaccesscompletionhandler"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABExternalChangeCallback": {
      "abstract": [
        {
          "text": "Prototype for a function callback invoked on an address book when the Address Book database is modified by another address book instance.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABExternalChangeCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABExternalChangeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABExternalChangeCallback"
        }
      ],
      "role": "symbol",
      "title": "ABExternalChangeCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abexternalchangecallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABImageClientCallback": {
      "abstract": [
        {
          "text": "Prototype of a callback function used to notify an application when an asynchronous image fetch is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABImageClientCallback"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABImageClientCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABImageClientCallback"
        }
      ],
      "role": "symbol",
      "title": "ABImageClientCallback",
      "type": "topic",
      "url": "/documentation/addressbook/abimageclientcallback"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifier": {
      "abstract": [
        {
          "text": "Identifies multivalue properties.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultiValueIdentifier"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMultiValueIdentifier"
        }
      ],
      "role": "symbol",
      "title": "ABMultiValueIdentifier",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalueidentifier"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCompositeNameFormat": {
      "abstract": [
        {
          "text": "Indicates a person-name display format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCompositeNameFormat"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCompositeNameFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCompositeNameFormat"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCompositeNameFormat",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncompositenameformat"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSortOrdering": {
      "abstract": [
        {
          "text": "Indicates a person sort ordering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonSortOrdering"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSortOrdering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonSortOrdering"
        }
      ],
      "role": "symbol",
      "title": "ABPersonSortOrdering",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonsortordering"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAttributes": {
      "abstract": [
        {
          "text": "A bitfield used to specify the selection behavior for the values of multi-value properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerAttributes"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAttributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerAttributes",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerattributes"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyID": {
      "abstract": [
        {
          "text": "Integer that identifies a record property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPropertyID"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPropertyID"
        }
      ],
      "role": "symbol",
      "title": "ABPropertyID",
      "type": "topic",
      "url": "/documentation/addressbook/abpropertyid"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType": {
      "abstract": [
        {
          "text": "These are the possible types of ABRecord properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPropertyType"
        }
      ],
      "role": "symbol",
      "title": "ABPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/abpropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias": {
      "abstract": [
        {
          "text": "A reference to an ABRecord object or any of its derivedopaque types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "role": "symbol",
      "title": "ABRecord",
      "type": "topic",
      "url": "/documentation/addressbook/abrecord-swift.typealias"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecordID": {
      "abstract": [
        {
          "text": "Integer that identifies a record.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecordID"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecordID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecordID"
        }
      ],
      "role": "symbol",
      "title": "ABRecordID",
      "type": "topic",
      "url": "/documentation/addressbook/abrecordid"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecordType": {
      "abstract": [
        {
          "text": "Integer that identifies a record type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecordType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecordType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecordType"
        }
      ],
      "role": "symbol",
      "title": "ABRecordType",
      "type": "topic",
      "url": "/documentation/addressbook/abrecordtype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison": {
      "abstract": [
        {
          "text": "Constants used to specify the type of comparison beingmade.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSearchComparison"
        }
      ],
      "role": "symbol",
      "title": "ABSearchComparison",
      "type": "topic",
      "url": "/documentation/addressbook/absearchcomparison"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSearchConjunction": {
      "abstract": [
        {
          "text": "Constants used to create compound search elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSearchConjunction"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchConjunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSearchConjunction"
        }
      ],
      "role": "symbol",
      "title": "ABSearchConjunction",
      "type": "topic",
      "url": "/documentation/addressbook/absearchconjunction"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSourceType": {
      "abstract": [
        {
          "text": "Indicates a source type. See ",
          "type": "text"
        },
        {
          "code": "Source Properties",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSourceType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSourceType"
        }
      ],
      "role": "symbol",
      "title": "ABSourceType",
      "type": "topic",
      "url": "/documentation/addressbook/absourcetype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants": {
      "abstract": [
        {
          "text": "Get the constants you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Book Constants",
      "type": "topic",
      "url": "/documentation/addressbook/address-book-constants"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations": {
      "abstract": [
        {
          "text": "Get the enumerations you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Enumerations",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-enumerations"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions": {
      "abstract": [
        {
          "text": "Find the C functions and function-like macros you use to manipulate Address Book data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Functions",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-functions"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/c-types": {
      "abstract": [
        {
          "text": "Identify the C types that correspond to Address Book objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/c-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "C Types",
      "type": "topic",
      "url": "/documentation/addressbook/c-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "C-Interfaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/c-types",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions",
        "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations"
      ],
      "title": "C Interfaces"
    }
  ],
  "topicSections": [
    {
      "anchor": "Callbacks",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABImageClientCallback"
      ],
      "title": "Callbacks"
    },
    {
      "anchor": "Miscellaneous",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
        "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison",
        "doc://com.apple.addressbook/documentation/AddressBook/ABSearchConjunction"
      ],
      "title": "Miscellaneous"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRequestAccessCompletionHandler",
        "doc://com.apple.addressbook/documentation/AddressBook/ABExternalChangeCallback",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifier",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCompositeNameFormat",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSortOrdering",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyID",
        "doc://com.apple.addressbook/documentation/AddressBook/ABRecordID",
        "doc://com.apple.addressbook/documentation/AddressBook/ABRecordType",
        "doc://com.apple.addressbook/documentation/AddressBook/ABSourceType"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Callbacks",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABImageClientCallback",
                "doc://com.apple.addressbook/documentation/AddressBook/ABActionCopyTitleCallback",
                "doc://com.apple.addressbook/documentation/AddressBook/ABActionEnabledCallback",
                "doc://com.apple.addressbook/documentation/AddressBook/ABActionGetPropertyCallback",
                "doc://com.apple.addressbook/documentation/AddressBook/ABActionSelectedCallback"
              ],
              "title": "Callbacks"
            },
            {
              "anchor": "Miscellaneous",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAttributes",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
                "doc://com.apple.addressbook/documentation/AddressBook/ABSearchComparison",
                "doc://com.apple.addressbook/documentation/AddressBook/ABSearchConjunction"
              ],
              "title": "Miscellaneous"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRequestAccessCompletionHandler",
                "doc://com.apple.addressbook/documentation/AddressBook/ABExternalChangeCallback",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifier",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCompositeNameFormat",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSortOrdering",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyID",
                "doc://com.apple.addressbook/documentation/AddressBook/ABRecordID",
                "doc://com.apple.addressbook/documentation/AddressBook/ABRecordType",
                "doc://com.apple.addressbook/documentation/AddressBook/ABSourceType"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "C-Interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/c-types",
                "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions",
                "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
                "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations"
              ],
              "title": "C Interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonSortOrdering/title",
          "value": "ABPersonSortOrdering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonSortOrdering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonSortOrdering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonSortOrdering/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonSortOrdering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueIdentifier/title",
          "value": "ABMultiValueIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchConjunction/title",
          "value": "ABSearchConjunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchConjunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchConjunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchConjunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchConjunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRequestAccessCompletionHandler/title",
          "value": "ABAddressBookRequestAccessCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRequestAccessCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRequestAccessCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRequestAccessCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRequestAccessCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/title",
          "value": "ABPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordID/title",
          "value": "ABRecordID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchComparison/title",
          "value": "ABSearchComparison"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchComparison/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchComparison"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchComparison/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchComparison"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordType/title",
          "value": "ABRecordType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClientCallback/title",
          "value": "ABImageClientCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClientCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClientCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABImageClientCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABImageClientCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyID/title",
          "value": "ABPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.typealias/title",
          "value": "ABRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABExternalChangeCallback/title",
          "value": "ABExternalChangeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABExternalChangeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABExternalChangeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABExternalChangeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABExternalChangeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCompositeNameFormat/title",
          "value": "ABPersonCompositeNameFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCompositeNameFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCompositeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCompositeNameFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCompositeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSourceType/title",
          "value": "ABSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSourceType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/addressbook-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/addressbook-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
