{
  "abstract": [
    {
      "text": "Identify the C types that correspond to Address Book objects.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/c-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "C Types"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABActionCallbacks": {
      "abstract": [
        {
          "text": "This is the structure that the ",
          "type": "text"
        },
        {
          "code": "ABActionRegisterCallbacks",
          "type": "codeVoice"
        },
        {
          "text": " returns to tell Address Book about the action the plug-in implements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABActionCallbacks"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABActionCallbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABActionCallbacks",
      "type": "topic",
      "url": "/documentation/addressbook/abactioncallbacks"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef": {
      "abstract": [
        {
          "text": "A reference to an ABAddressBook object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBook",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRef": {
      "abstract": [
        {
          "text": "A reference to an ABGroup object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupRef"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupRef"
        }
      ],
      "role": "symbol",
      "title": "ABGroupRef",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef": {
      "abstract": [
        {
          "text": "A reference to an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "ABMutableMultiValueobject",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultiValue"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMultiValue"
        }
      ],
      "role": "symbol",
      "title": "ABMultiValue",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalueref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValueRef": {
      "abstract": [
        {
          "text": "A reference to an ABMutableMultiValue object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMutableMultiValue"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValueRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMutableMultiValue"
        }
      ],
      "role": "symbol",
      "title": "ABMutableMultiValue",
      "type": "topic",
      "url": "/documentation/addressbook/abmutablemultivalueref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonImageFormat": {
      "abstract": [
        {
          "text": "Indicates an image format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonImageFormat"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonImageFormat"
        }
      ],
      "role": "symbol",
      "title": "ABPersonImageFormat",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonimageformat"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonRef": {
      "abstract": [
        {
          "text": "A reference to an ABPerson object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonRef"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonRef"
        }
      ],
      "role": "symbol",
      "title": "ABPersonRef",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerRef": {
      "abstract": [
        {
          "text": "A reference to an ABPicker object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerRef"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerRef",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants": {
      "abstract": [
        {
          "text": "Get the constants you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Book Constants",
      "type": "topic",
      "url": "/documentation/addressbook/address-book-constants"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-data-types": {
      "abstract": [
        {
          "text": "Get the data types you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Data Types",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-data-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations": {
      "abstract": [
        {
          "text": "Get the enumerations you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Enumerations",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-enumerations"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions": {
      "abstract": [
        {
          "text": "Find the C functions and function-like macros you use to manipulate Address Book data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Functions",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-functions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "C-Interfaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions",
        "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-data-types"
      ],
      "title": "C Interfaces"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonRef",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRef",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValueRef"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonImageFormat"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonRef",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRef",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValueRef"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Pickers",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABPickerRef"
              ],
              "title": "Pickers"
            },
            {
              "anchor": "Action-Plug-In",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABActionCallbacks"
              ],
              "title": "Action Plug-In"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonImageFormat"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "C-Interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/addressbook-functions",
                "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
                "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations",
                "doc://com.apple.addressbook/documentation/AddressBook/addressbook-data-types"
              ],
              "title": "C Interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/title",
          "value": "ABMultiValueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRef/title",
          "value": "ABGroupRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMutableMultiValueRef/title",
          "value": "ABMutableMultiValueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMutableMultiValueRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMutableMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMutableMultiValueRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMutableMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonRef/title",
          "value": "ABPersonRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/title",
          "value": "ABAddressBookRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonImageFormat/title",
          "value": "ABPersonImageFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonImageFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonImageFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonImageFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/c-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/c-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
