{
  "abstract": [
    {
      "text": "These constants identify the format to use for a person’s composite name order for person records.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/composite-name-format"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Composite Name Format"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations": {
      "abstract": [
        {
          "text": "Get the enumerations you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Enumerations",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-enumerations"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatFirstNameFirst": {
      "abstract": [
        {
          "text": "First name first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonCompositeNameFormatFirstNameFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatFirstNameFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonCompositeNameFormatFirstNameFirst"
        }
      ],
      "role": "symbol",
      "title": "kABPersonCompositeNameFormatFirstNameFirst",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersoncompositenameformatfirstnamefirst"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatLastNameFirst": {
      "abstract": [
        {
          "text": "Last name first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonCompositeNameFormatLastNameFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatLastNameFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonCompositeNameFormatLastNameFirst"
        }
      ],
      "role": "symbol",
      "title": "kABPersonCompositeNameFormatLastNameFirst",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersoncompositenameformatlastnamefirst"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/record-property-types": {
      "abstract": [
        {
          "text": "These constants identify record property types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/record-property-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Property Types",
      "type": "topic",
      "url": "/documentation/addressbook/record-property-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/record-types": {
      "abstract": [
        {
          "text": "These constants identify record types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/record-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Types",
      "type": "topic",
      "url": "/documentation/addressbook/record-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/sort-order": {
      "abstract": [
        {
          "text": "These constants identify sort order for person lists.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/sort-order",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sort Order",
      "type": "topic",
      "url": "/documentation/addressbook/sort-order"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/source-types": {
      "abstract": [
        {
          "text": "These constants identify the type of a source.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/source-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Source Types",
      "type": "topic",
      "url": "/documentation/addressbook/source-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatFirstNameFirst",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatLastNameFirst"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatFirstNameFirst",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonCompositeNameFormatLastNameFirst"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/record-property-types",
                "doc://com.apple.addressbook/documentation/AddressBook/record-types",
                "doc://com.apple.addressbook/documentation/AddressBook/sort-order",
                "doc://com.apple.addressbook/documentation/AddressBook/source-types"
              ],
              "title": "Miscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonCompositeNameFormatLastNameFirst/title",
          "value": "kABPersonCompositeNameFormatLastNameFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonCompositeNameFormatLastNameFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonCompositeNameFormatLastNameFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonCompositeNameFormatFirstNameFirst/title",
          "value": "kABPersonCompositeNameFormatFirstNameFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonCompositeNameFormatFirstNameFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonCompositeNameFormatFirstNameFirst"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/composite-name-format"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/composite-name-format"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
