{
  "abstract": [
    {
      "text": "The default labels contained in the Address Book database for specifying different values in a multivalue list. Users can also add their own labels.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/default-multivalue-list-labels"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Default Multivalue List Labels"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroup/addPropertiesAndTypes(_:)": {
      "abstract": [
        {
          "text": "Adds the given properties to all records of this type in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPropertiesAndTypes"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroup/addPropertiesAndTypes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPropertiesAndTypes:"
        }
      ],
      "role": "symbol",
      "title": "addPropertiesAndTypes(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroup/addpropertiesandtypes(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType": {
      "abstract": [
        {
          "text": "These are the possible types of ABRecord properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPropertyType"
        }
      ],
      "role": "symbol",
      "title": "ABPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/abpropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants": {
      "abstract": [
        {
          "text": "Get the constants you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Book Constants",
      "type": "topic",
      "url": "/documentation/addressbook/address-book-constants"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-keys": {
      "abstract": [
        {
          "text": "The keys used to specify the different fields in a ",
          "type": "text"
        },
        {
          "code": "kABAddressProperty",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Keys",
      "type": "topic",
      "url": "/documentation/addressbook/address-keys"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/default-group-properties": {
      "abstract": [
        {
          "text": "The properties that a group record contains by default.  Developers can add their own properties with the ",
          "type": "text"
        },
        {
          "code": "ABGroup",
          "type": "codeVoice"
        },
        {
          "text": " method ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroup/addPropertiesAndTypes(_:)",
          "isActive": true,
          "type": "reference"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/default-group-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Default Group Properties",
      "type": "topic",
      "url": "/documentation/addressbook/default-group-properties"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties": {
      "abstract": [
        {
          "text": "The properties that a person record contains by default.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Default Person Properties",
      "type": "topic",
      "url": "/documentation/addressbook/default-person-properties"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties": {
      "abstract": [
        {
          "text": "Properties common to all types of records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Default Record Properties",
      "type": "topic",
      "url": "/documentation/addressbook/default-record-properties"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels": {
      "abstract": [
        {
          "text": "The generic labels contained in the Address Book database for specifying different values in a multivalue list.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generic Multivalue List Labels",
      "type": "topic",
      "url": "/documentation/addressbook/generic-multivalue-list-labels"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAIMHomeLabel": {
      "abstract": [
        {
          "text": "Home AOL instant messaging ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABAIMHomeLabel"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAIMHomeLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABAIMHomeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabaimhomelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAIMMobileMeLabel": {
      "abstract": [
        {
          "text": "Mobile Me AOL instant messaging ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABAIMMobileMeLabel"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAIMMobileMeLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABAIMMobileMeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabaimmobilemelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAIMWorkLabel": {
      "abstract": [
        {
          "text": "Work AOL instant messaging ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABAIMWorkLabel"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAIMWorkLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABAIMWorkLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabaimworklabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAddressHomeLabel": {
      "abstract": [
        {
          "text": "Home address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABAddressHomeLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAddressHomeLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAddressHomeLabel"
        }
      ],
      "role": "symbol",
      "title": "kABAddressHomeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabaddresshomelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAddressWorkLabel": {
      "abstract": [
        {
          "text": "Work address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABAddressWorkLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAddressWorkLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAddressWorkLabel"
        }
      ],
      "role": "symbol",
      "title": "kABAddressWorkLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabaddressworklabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAnniversaryLabel": {
      "abstract": [
        {
          "text": "Anniversary date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABAnniversaryLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAnniversaryLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAnniversaryLabel"
        }
      ],
      "role": "symbol",
      "title": "kABAnniversaryLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabanniversarylabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAssistantLabel": {
      "abstract": [
        {
          "text": "Assistant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABAssistantLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAssistantLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAssistantLabel"
        }
      ],
      "role": "symbol",
      "title": "kABAssistantLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabassistantlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABBrotherLabel": {
      "abstract": [
        {
          "text": "Brother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABBrotherLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABBrotherLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABBrotherLabel"
        }
      ],
      "role": "symbol",
      "title": "kABBrotherLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabbrotherlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABChildLabel": {
      "abstract": [
        {
          "text": "Child.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABChildLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABChildLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABChildLabel"
        }
      ],
      "role": "symbol",
      "title": "kABChildLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabchildlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEmailHomeLabel": {
      "abstract": [
        {
          "text": "Home email.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEmailHomeLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEmailHomeLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABEmailHomeLabel"
        }
      ],
      "role": "symbol",
      "title": "kABEmailHomeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabemailhomelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEmailMobileMeLabel": {
      "abstract": [
        {
          "text": "Mobile Me email.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEmailMobileMeLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEmailMobileMeLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABEmailMobileMeLabel"
        }
      ],
      "role": "symbol",
      "title": "kABEmailMobileMeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabemailmobilemelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEmailWorkLabel": {
      "abstract": [
        {
          "text": "Work email.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEmailWorkLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEmailWorkLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABEmailWorkLabel"
        }
      ],
      "role": "symbol",
      "title": "kABEmailWorkLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabemailworklabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABFatherLabel": {
      "abstract": [
        {
          "text": "Father.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABFatherLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABFatherLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABFatherLabel"
        }
      ],
      "role": "symbol",
      "title": "kABFatherLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabfatherlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABFriendLabel": {
      "abstract": [
        {
          "text": "Friend.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABFriendLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABFriendLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABFriendLabel"
        }
      ],
      "role": "symbol",
      "title": "kABFriendLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabfriendlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageLabel": {
      "abstract": [
        {
          "text": "Webpage URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABHomePageLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABHomePageLabel"
        }
      ],
      "role": "symbol",
      "title": "kABHomePageLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabhomepagelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABICQHomeLabel": {
      "abstract": [
        {
          "text": "Home ICQ instant messaging ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABICQHomeLabel"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABICQHomeLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABICQHomeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabicqhomelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABICQWorkLabel": {
      "abstract": [
        {
          "text": "Work ICQ instant messaging ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABICQWorkLabel"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABICQWorkLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABICQWorkLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabicqworklabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABJabberHomeLabel": {
      "abstract": [
        {
          "text": "Home Jabber instant messaging ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABJabberHomeLabel"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABJabberHomeLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABJabberHomeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabjabberhomelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABJabberWorkLabel": {
      "abstract": [
        {
          "text": "Work Jabber instant messaging ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABJabberWorkLabel"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABJabberWorkLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABJabberWorkLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabjabberworklabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMSNHomeLabel": {
      "abstract": [
        {
          "text": "Home MSN instant messaging ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABMSNHomeLabel"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMSNHomeLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMSNHomeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabmsnhomelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMSNWorkLabel": {
      "abstract": [
        {
          "text": "Work MSN instant messaging ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABMSNWorkLabel"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMSNWorkLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMSNWorkLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabmsnworklabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABManagerLabel": {
      "abstract": [
        {
          "text": "Manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABManagerLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABManagerLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABManagerLabel"
        }
      ],
      "role": "symbol",
      "title": "kABManagerLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabmanagerlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMotherLabel": {
      "abstract": [
        {
          "text": "Mother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMotherLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMotherLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABMotherLabel"
        }
      ],
      "role": "symbol",
      "title": "kABMotherLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabmotherlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABParentLabel": {
      "abstract": [
        {
          "text": "Parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABParentLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABParentLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABParentLabel"
        }
      ],
      "role": "symbol",
      "title": "kABParentLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabparentlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPartnerLabel": {
      "abstract": [
        {
          "text": "Partner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPartnerLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPartnerLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPartnerLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPartnerLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabpartnerlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneHomeFAXLabel": {
      "abstract": [
        {
          "text": "Home fax number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPhoneHomeFAXLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneHomeFAXLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPhoneHomeFAXLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPhoneHomeFAXLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabphonehomefaxlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneHomeLabel": {
      "abstract": [
        {
          "text": "Home phone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPhoneHomeLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneHomeLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPhoneHomeLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPhoneHomeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabphonehomelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneMainLabel": {
      "abstract": [
        {
          "text": "Main phone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPhoneMainLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneMainLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPhoneMainLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPhoneMainLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabphonemainlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneMobileLabel": {
      "abstract": [
        {
          "text": "Cell phone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPhoneMobileLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneMobileLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPhoneMobileLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPhoneMobileLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabphonemobilelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPhonePagerLabel": {
      "abstract": [
        {
          "text": "Pager number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPhonePagerLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPhonePagerLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPhonePagerLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPhonePagerLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabphonepagerlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneWorkFAXLabel": {
      "abstract": [
        {
          "text": "Work fax number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPhoneWorkFAXLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneWorkFAXLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPhoneWorkFAXLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPhoneWorkFAXLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabphoneworkfaxlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneWorkLabel": {
      "abstract": [
        {
          "text": "Work phone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPhoneWorkLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneWorkLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPhoneWorkLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPhoneWorkLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabphoneworklabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneiPhoneLabel": {
      "abstract": [
        {
          "text": "iPhone phone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPhoneiPhoneLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneiPhoneLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPhoneiPhoneLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPhoneiPhoneLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabphoneiphonelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSisterLabel": {
      "abstract": [
        {
          "text": "Sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSisterLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSisterLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSisterLabel"
        }
      ],
      "role": "symbol",
      "title": "kABSisterLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabsisterlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSpouseLabel": {
      "abstract": [
        {
          "text": "Spouse.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSpouseLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSpouseLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSpouseLabel"
        }
      ],
      "role": "symbol",
      "title": "kABSpouseLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabspouselabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABYahooHomeLabel": {
      "abstract": [
        {
          "text": "Home Yahoo instant messaging ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABYahooHomeLabel"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABYahooHomeLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABYahooHomeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabyahoohomelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABYahooWorkLabel": {
      "abstract": [
        {
          "text": "Work Yahoo instant messaging ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABYahooWorkLabel"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABYahooWorkLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABYahooWorkLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabyahooworklabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property": {
      "abstract": [
        {
          "text": "A multivalue property type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Multivalue Property",
      "type": "topic",
      "url": "/documentation/addressbook/multivalue-property"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/property_types": {
      "abstract": [
        {
          "text": "The possible ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " types for ",
          "type": "text"
        },
        {
          "code": "ABRecord",
          "type": "codeVoice"
        },
        {
          "text": " properties:",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/property_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property Types",
      "type": "topic",
      "url": "/documentation/addressbook/property_types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Type-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/address-keys",
        "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties",
        "doc://com.apple.addressbook/documentation/AddressBook/default-group-properties",
        "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels",
        "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property",
        "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties",
        "doc://com.apple.addressbook/documentation/AddressBook/property_types"
      ],
      "title": "Data Type Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABEmailWorkLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABEmailHomeLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABEmailMobileMeLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABAddressHomeLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABAddressWorkLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABAnniversaryLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABFatherLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMotherLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABParentLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABBrotherLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSisterLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABChildLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABFriendLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSpouseLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPartnerLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABAssistantLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABManagerLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneWorkLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneHomeLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneiPhoneLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneMobileLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneMainLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneHomeFAXLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneWorkFAXLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPhonePagerLabel"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABEmailWorkLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABEmailHomeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABEmailMobileMeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABAddressHomeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABAddressWorkLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABAnniversaryLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABFatherLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABMotherLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABParentLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABBrotherLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSisterLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABChildLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABFriendLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSpouseLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPartnerLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABAssistantLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABManagerLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneWorkLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneHomeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneiPhoneLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneMobileLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneMainLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneHomeFAXLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPhoneWorkFAXLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPhonePagerLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABAIMWorkLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABAIMHomeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABAIMMobileMeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABJabberWorkLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABJabberHomeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABMSNWorkLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABMSNHomeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABYahooWorkLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABYahooHomeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABICQWorkLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABICQHomeLabel"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Type-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/address-keys",
                "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties",
                "doc://com.apple.addressbook/documentation/AddressBook/default-group-properties",
                "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels",
                "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property",
                "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties",
                "doc://com.apple.addressbook/documentation/AddressBook/property_types"
              ],
              "title": "Data Type Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhonePagerLabel/title",
          "value": "kABPhonePagerLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhonePagerLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPhonePagerLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABParentLabel/title",
          "value": "kABParentLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABParentLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABParentLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroup~1addPropertiesAndTypes(_:)/title",
          "value": "addPropertiesAndTypes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroup~1addPropertiesAndTypes(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "addPropertiesAndTypes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneHomeFAXLabel/title",
          "value": "kABPhoneHomeFAXLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneHomeFAXLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPhoneHomeFAXLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABHomePageLabel/title",
          "value": "kABHomePageLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABHomePageLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABHomePageLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneWorkLabel/title",
          "value": "kABPhoneWorkLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneWorkLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPhoneWorkLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailMobileMeLabel/title",
          "value": "kABEmailMobileMeLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailMobileMeLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABEmailMobileMeLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAnniversaryLabel/title",
          "value": "kABAnniversaryLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAnniversaryLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAnniversaryLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABChildLabel/title",
          "value": "kABChildLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABChildLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABChildLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAddressHomeLabel/title",
          "value": "kABAddressHomeLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAddressHomeLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAddressHomeLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSisterLabel/title",
          "value": "kABSisterLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSisterLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSisterLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMotherLabel/title",
          "value": "kABMotherLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMotherLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABMotherLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneMobileLabel/title",
          "value": "kABPhoneMobileLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneMobileLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPhoneMobileLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABBrotherLabel/title",
          "value": "kABBrotherLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABBrotherLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABBrotherLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneiPhoneLabel/title",
          "value": "kABPhoneiPhoneLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneiPhoneLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPhoneiPhoneLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSpouseLabel/title",
          "value": "kABSpouseLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSpouseLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSpouseLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPartnerLabel/title",
          "value": "kABPartnerLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPartnerLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPartnerLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailWorkLabel/title",
          "value": "kABEmailWorkLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailWorkLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABEmailWorkLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/title",
          "value": "ABPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneHomeLabel/title",
          "value": "kABPhoneHomeLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneHomeLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPhoneHomeLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailHomeLabel/title",
          "value": "kABEmailHomeLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailHomeLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABEmailHomeLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneMainLabel/title",
          "value": "kABPhoneMainLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneMainLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPhoneMainLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFatherLabel/title",
          "value": "kABFatherLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFatherLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABFatherLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFriendLabel/title",
          "value": "kABFriendLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFriendLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABFriendLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABManagerLabel/title",
          "value": "kABManagerLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABManagerLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABManagerLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAssistantLabel/title",
          "value": "kABAssistantLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAssistantLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAssistantLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAddressWorkLabel/title",
          "value": "kABAddressWorkLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAddressWorkLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAddressWorkLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneWorkFAXLabel/title",
          "value": "kABPhoneWorkFAXLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPhoneWorkFAXLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPhoneWorkFAXLabel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/default-multivalue-list-labels"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/default-multivalue-list-labels"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
