{
  "abstract": [
    {
      "text": "The properties that a group record contains by default.  Developers can add their own properties with the ",
      "type": "text"
    },
    {
      "code": "ABGroup",
      "type": "codeVoice"
    },
    {
      "text": " method ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroup/addPropertiesAndTypes(_:)",
      "isActive": true,
      "type": "reference"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/default-group-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Default Group Properties"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroup/addPropertiesAndTypes(_:)": {
      "abstract": [
        {
          "text": "Adds the given properties to all records of this type in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPropertiesAndTypes"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroup/addPropertiesAndTypes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPropertiesAndTypes:"
        }
      ],
      "role": "symbol",
      "title": "addPropertiesAndTypes(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroup/addpropertiesandtypes(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType": {
      "abstract": [
        {
          "text": "These are the possible types of ABRecord properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPropertyType"
        }
      ],
      "role": "symbol",
      "title": "ABPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/abpropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants": {
      "abstract": [
        {
          "text": "Get the constants you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Book Constants",
      "type": "topic",
      "url": "/documentation/addressbook/address-book-constants"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-keys": {
      "abstract": [
        {
          "text": "The keys used to specify the different fields in a ",
          "type": "text"
        },
        {
          "code": "kABAddressProperty",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Keys",
      "type": "topic",
      "url": "/documentation/addressbook/address-keys"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/default-multivalue-list-labels": {
      "abstract": [
        {
          "text": "The default labels contained in the Address Book database for specifying different values in a multivalue list. Users can also add their own labels.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/default-multivalue-list-labels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Default Multivalue List Labels",
      "type": "topic",
      "url": "/documentation/addressbook/default-multivalue-list-labels"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties": {
      "abstract": [
        {
          "text": "The properties that a person record contains by default.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Default Person Properties",
      "type": "topic",
      "url": "/documentation/addressbook/default-person-properties"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties": {
      "abstract": [
        {
          "text": "Properties common to all types of records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Default Record Properties",
      "type": "topic",
      "url": "/documentation/addressbook/default-record-properties"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels": {
      "abstract": [
        {
          "text": "The generic labels contained in the Address Book database for specifying different values in a multivalue list.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generic Multivalue List Labels",
      "type": "topic",
      "url": "/documentation/addressbook/generic-multivalue-list-labels"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABGroupNameProperty": {
      "abstract": [
        {
          "text": "Name of the group",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABGroupNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABGroupNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABGroupNameProperty"
        }
      ],
      "role": "symbol",
      "title": "kABGroupNameProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabgroupnameproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property": {
      "abstract": [
        {
          "text": "A multivalue property type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Multivalue Property",
      "type": "topic",
      "url": "/documentation/addressbook/multivalue-property"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/property_types": {
      "abstract": [
        {
          "text": "The possible ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " types for ",
          "type": "text"
        },
        {
          "code": "ABRecord",
          "type": "codeVoice"
        },
        {
          "text": " properties:",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/property_types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property Types",
      "type": "topic",
      "url": "/documentation/addressbook/property_types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Type-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/address-keys",
        "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties",
        "doc://com.apple.addressbook/documentation/AddressBook/default-multivalue-list-labels",
        "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels",
        "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property",
        "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties",
        "doc://com.apple.addressbook/documentation/AddressBook/property_types"
      ],
      "title": "Data Type Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABGroupNameProperty"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABGroupNameProperty"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Type-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/address-keys",
                "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties",
                "doc://com.apple.addressbook/documentation/AddressBook/default-multivalue-list-labels",
                "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels",
                "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property",
                "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties",
                "doc://com.apple.addressbook/documentation/AddressBook/property_types"
              ],
              "title": "Data Type Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/title",
          "value": "ABPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroup~1addPropertiesAndTypes(_:)/title",
          "value": "addPropertiesAndTypes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroup~1addPropertiesAndTypes(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "addPropertiesAndTypes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABGroupNameProperty/title",
          "value": "kABGroupNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABGroupNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABGroupNameProperty"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/default-group-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/default-group-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
