{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated symbols"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef": {
      "abstract": [
        {
          "text": "A reference to an ABAddressBook object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBook",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddMember(_:_:)": {
      "abstract": [
        {
          "text": "Adds a person to a group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupAddMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddMember(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupAddMember"
        }
      ],
      "role": "symbol",
      "title": "ABGroupAddMember(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupaddmember(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveMember(_:_:)": {
      "abstract": [
        {
          "text": "Removes a person from a group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupRemoveMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveMember(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupRemoveMember"
        }
      ],
      "role": "symbol",
      "title": "ABGroupRemoveMember(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupremovemember(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueCreateMutable()": {
      "abstract": [
        {
          "text": "Returns a newly created mutable multi-value list object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultiValueCreateMutable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyType",
          "text": "ABPropertyType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABMutableMultiValueRef",
          "text": "ABMutableMultiValue"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueCreateMutable()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMultiValueCreateMutable"
        }
      ],
      "role": "symbol",
      "title": "ABMultiValueCreateMutable(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivaluecreatemutable()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef": {
      "abstract": [
        {
          "text": "A reference to an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "ABMutableMultiValueobject",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultiValue"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMultiValue"
        }
      ],
      "role": "symbol",
      "title": "ABMultiValue",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalueref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValueRef": {
      "abstract": [
        {
          "text": "A reference to an ABMutableMultiValue object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMutableMultiValue"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValueRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMutableMultiValue"
        }
      ],
      "role": "symbol",
      "title": "ABMutableMultiValue",
      "type": "topic",
      "url": "/documentation/addressbook/abmutablemultivalueref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSetImageData(_:_:)": {
      "abstract": [
        {
          "text": "Sets the image for this person to the given data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonSetImageData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSetImageData(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonSetImageData"
        }
      ],
      "role": "symbol",
      "title": "ABPersonSetImageData(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abpersonsetimagedata(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias": {
      "abstract": [
        {
          "text": "A reference to an ABRecord object or any of its derivedopaque types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "role": "symbol",
      "title": "ABRecord",
      "type": "topic",
      "url": "/documentation/addressbook/abrecord-swift.typealias"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecordRemoveValue(_:_:)": {
      "abstract": [
        {
          "text": "Removes the value of the given property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecordRemoveValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyID",
          "text": "ABPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecordRemoveValue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecordRemoveValue"
        }
      ],
      "role": "symbol",
      "title": "ABRecordRemoveValue(_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abrecordremovevalue(_:_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecordSetValue(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the value of a given property for a record.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecordSetValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyID",
          "text": "ABPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecordSetValue(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecordSetValue"
        }
      ],
      "role": "symbol",
      "title": "ABRecordSetValue(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abrecordsetvalue(_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-classes",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddMember(_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveMember(_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueCreateMutable()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSetImageData(_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABRecordRemoveValue(_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABRecordSetValue(_:_:_:)",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
        "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValueRef",
        "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias"
      ],
      "title": "Deprecated classes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-classes",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupAddMember(_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABGroupRemoveMember(_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueCreateMutable()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPersonSetImageData(_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABRecordRemoveValue(_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABRecordSetValue(_:_:_:)",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookRef",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
                "doc://com.apple.addressbook/documentation/AddressBook/ABMutableMultiValueRef",
                "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.typealias"
              ],
              "title": "Deprecated classes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMutableMultiValueRef/title",
          "value": "ABMutableMultiValueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMutableMultiValueRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMutableMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMutableMultiValueRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMutableMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordRemoveValue(_:_:)/title",
          "value": "ABRecordRemoveValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordRemoveValue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordRemoveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/title",
          "value": "ABAddressBookRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordSetValue(_:_:_:)/title",
          "value": "ABRecordSetValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecordSetValue(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordSetValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRemoveMember(_:_:)/title",
          "value": "ABGroupRemoveMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupRemoveMember(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupRemoveMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.typealias/title",
          "value": "ABRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueCreateMutable()/title",
          "value": "ABMultiValueCreateMutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueCreateMutable()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueCreateMutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonSetImageData(_:_:)/title",
          "value": "ABPersonSetImageData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonSetImageData(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonSetImageData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/title",
          "value": "ABMultiValueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupAddMember(_:_:)/title",
          "value": "ABGroupAddMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupAddMember(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupAddMember"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
