{
  "abstract": [
    {
      "text": "Errors codes used by the Address Book framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/error-codes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error Codes"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddRecordsError": {
      "abstract": [
        {
          "text": "The records could not be added.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddRecordsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddRecordsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddRecordsError"
        }
      ],
      "role": "symbol",
      "title": "ABAddRecordsError",
      "type": "topic",
      "url": "/documentation/addressbook/abaddrecordserror"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookErrorDomain": {
      "abstract": [
        {
          "text": "Error domain returning errors reported by an address book object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBookErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBookErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBookErrorDomain",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookerrordomain"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifiersErrorKey": {
      "abstract": [
        {
          "text": "Key used with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyValueValidationError",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultiValueIdentifiersErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifiersErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMultiValueIdentifiersErrorKey"
        }
      ],
      "role": "symbol",
      "title": "ABMultiValueIdentifiersErrorKey",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalueidentifierserrorkey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyReadOnlyError": {
      "abstract": [
        {
          "text": "The property is read-only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPropertyReadOnlyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyReadOnlyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPropertyReadOnlyError"
        }
      ],
      "role": "symbol",
      "title": "ABPropertyReadOnlyError",
      "type": "topic",
      "url": "/documentation/addressbook/abpropertyreadonlyerror"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyUnsupportedBySourceError": {
      "abstract": [
        {
          "text": "The property is not supported by the source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPropertyUnsupportedBySourceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyUnsupportedBySourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPropertyUnsupportedBySourceError"
        }
      ],
      "role": "symbol",
      "title": "ABPropertyUnsupportedBySourceError",
      "type": "topic",
      "url": "/documentation/addressbook/abpropertyunsupportedbysourceerror"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyValueValidationError": {
      "abstract": [
        {
          "text": "The property value is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPropertyValueValidationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyValueValidationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPropertyValueValidationError"
        }
      ],
      "role": "symbol",
      "title": "ABPropertyValueValidationError",
      "type": "topic",
      "url": "/documentation/addressbook/abpropertyvaluevalidationerror"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRemoveRecordsError": {
      "abstract": [
        {
          "text": "The records could not be removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRemoveRecordsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRemoveRecordsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRemoveRecordsError"
        }
      ],
      "role": "symbol",
      "title": "ABRemoveRecordsError",
      "type": "topic",
      "url": "/documentation/addressbook/abremoverecordserror"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants": {
      "abstract": [
        {
          "text": "Get the constants you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Book Constants",
      "type": "topic",
      "url": "/documentation/addressbook/address-book-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddRecordsError",
        "doc://com.apple.addressbook/documentation/AddressBook/ABRemoveRecordsError",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyValueValidationError",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyUnsupportedBySourceError",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyReadOnlyError"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Dictionary-Keys",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifiersErrorKey"
      ],
      "title": "Dictionary Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddRecordsError",
                "doc://com.apple.addressbook/documentation/AddressBook/ABRemoveRecordsError",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyValueValidationError",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyUnsupportedBySourceError",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyReadOnlyError"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Dictionary-Keys",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueIdentifiersErrorKey"
              ],
              "title": "Dictionary Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRemoveRecordsError/title",
          "value": "ABRemoveRecordsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRemoveRecordsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRemoveRecordsError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyUnsupportedBySourceError/title",
          "value": "ABPropertyUnsupportedBySourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyUnsupportedBySourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyUnsupportedBySourceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookErrorDomain/title",
          "value": "ABAddressBookErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyReadOnlyError/title",
          "value": "ABPropertyReadOnlyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyReadOnlyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyReadOnlyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddRecordsError/title",
          "value": "ABAddRecordsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddRecordsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddRecordsError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueIdentifiersErrorKey/title",
          "value": "ABMultiValueIdentifiersErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueIdentifiersErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueIdentifiersErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyValueValidationError/title",
          "value": "ABPropertyValueValidationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyValueValidationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyValueValidationError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/error-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/error-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
