{
  "abstract": [
    {
      "text": "The keys used to specify the different fields in a ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageProperty",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Instant Messaging Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Neither developers nor users can add more keys.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants": {
      "abstract": [
        {
          "text": "Get the constants you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Book Constants",
      "type": "topic",
      "url": "/documentation/addressbook/address-book-constants"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-services": {
      "abstract": [
        {
          "text": "The predefined constants are used to identify instant messaging services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Instant Messaging Services",
      "type": "topic",
      "url": "/documentation/addressbook/instant-messaging-services"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageProperty": {
      "abstract": [
        {
          "text": "Instant messaging ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageProperty"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceKey": {
      "abstract": [
        {
          "text": "The instant messaging service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceKey"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageServiceKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageservicekey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageUsernameKey": {
      "abstract": [
        {
          "text": "The instant messaging username or handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageUsernameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageUsernameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageUsernameKey"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageUsernameKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageusernamekey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/social-profile-services": {
      "abstract": [
        {
          "text": "The predefined constants are used to identify social networking services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/social-profile-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Social Profile Services",
      "type": "topic",
      "url": "/documentation/addressbook/social-profile-services"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Social-Media-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-services",
        "doc://com.apple.addressbook/documentation/AddressBook/social-profile-services"
      ],
      "title": "Social Media Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageUsernameKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageUsernameKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Social-Media-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-services",
                "doc://com.apple.addressbook/documentation/AddressBook/social-profile-services"
              ],
              "title": "Social Media Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceKey/title",
          "value": "kABInstantMessageServiceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageServiceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageUsernameKey/title",
          "value": "kABInstantMessageUsernameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageUsernameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageUsernameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageProperty/title",
          "value": "kABInstantMessageProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageProperty"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/instant-messaging-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/instant-messaging-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
