{
  "abstract": [
    {
      "text": "The predefined constants are used to identify instant messaging services.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-services"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Instant Messaging Services"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You may use these constants or any other string.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants": {
      "abstract": [
        {
          "text": "Get the constants you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Book Constants",
      "type": "topic",
      "url": "/documentation/addressbook/address-book-constants"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-keys": {
      "abstract": [
        {
          "text": "The keys used to specify the different fields in a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Instant Messaging Keys",
      "type": "topic",
      "url": "/documentation/addressbook/instant-messaging-keys"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageProperty": {
      "abstract": [
        {
          "text": "Instant messaging ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageProperty"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceAIM": {
      "abstract": [
        {
          "text": "AOL Instant Messenger instant message service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceAIM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceAIM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceAIM"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageServiceAIM",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageserviceaim"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceFacebook": {
      "abstract": [
        {
          "text": "Facebook instant message service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceFacebook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceFacebook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceFacebook"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageServiceFacebook",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageservicefacebook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceGaduGadu": {
      "abstract": [
        {
          "text": "Gadu-Gadu instant message service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceGaduGadu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceGaduGadu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceGaduGadu"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageServiceGaduGadu",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageservicegadugadu"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceGoogleTalk": {
      "abstract": [
        {
          "text": "Google Talk instant message service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceGoogleTalk"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceGoogleTalk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceGoogleTalk"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageServiceGoogleTalk",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageservicegoogletalk"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceICQ": {
      "abstract": [
        {
          "text": "ICQ instant message service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceICQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceICQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceICQ"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageServiceICQ",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageserviceicq"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceJabber": {
      "abstract": [
        {
          "text": "Jabber instant message service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceJabber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceJabber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceJabber"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageServiceJabber",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageservicejabber"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceMSN": {
      "abstract": [
        {
          "text": "MSN instant message service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceMSN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceMSN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceMSN"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageServiceMSN",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageservicemsn"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceQQ": {
      "abstract": [
        {
          "text": "QQ instant message service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceQQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceQQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceQQ"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageServiceQQ",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageserviceqq"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceSkype": {
      "abstract": [
        {
          "text": "Skype instant message service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceSkype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceSkype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceSkype"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageServiceSkype",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageserviceskype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceYahoo": {
      "abstract": [
        {
          "text": "Yahoo! instant message service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceYahoo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceYahoo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageServiceYahoo"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageServiceYahoo",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageserviceyahoo"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/social-profile-services": {
      "abstract": [
        {
          "text": "The predefined constants are used to identify social networking services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/social-profile-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Social Profile Services",
      "type": "topic",
      "url": "/documentation/addressbook/social-profile-services"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Social-Media-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-keys",
        "doc://com.apple.addressbook/documentation/AddressBook/social-profile-services"
      ],
      "title": "Social Media Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceAIM",
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceFacebook",
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceGaduGadu",
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceGoogleTalk",
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceICQ",
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceJabber",
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceMSN",
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceQQ",
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceSkype",
        "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceYahoo"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceAIM",
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceFacebook",
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceGaduGadu",
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceGoogleTalk",
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceICQ",
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceJabber",
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceMSN",
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceQQ",
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceSkype",
                "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageServiceYahoo"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Social-Media-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-keys",
                "doc://com.apple.addressbook/documentation/AddressBook/social-profile-services"
              ],
              "title": "Social Media Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceQQ/title",
          "value": "kABInstantMessageServiceQQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceQQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageServiceQQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceICQ/title",
          "value": "kABInstantMessageServiceICQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceICQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageServiceICQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceGoogleTalk/title",
          "value": "kABInstantMessageServiceGoogleTalk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceGoogleTalk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageServiceGoogleTalk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageProperty/title",
          "value": "kABInstantMessageProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceFacebook/title",
          "value": "kABInstantMessageServiceFacebook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceFacebook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageServiceFacebook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceGaduGadu/title",
          "value": "kABInstantMessageServiceGaduGadu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceGaduGadu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageServiceGaduGadu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceMSN/title",
          "value": "kABInstantMessageServiceMSN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceMSN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageServiceMSN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceYahoo/title",
          "value": "kABInstantMessageServiceYahoo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceYahoo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageServiceYahoo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceSkype/title",
          "value": "kABInstantMessageServiceSkype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceSkype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageServiceSkype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceAIM/title",
          "value": "kABInstantMessageServiceAIM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceAIM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageServiceAIM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceJabber/title",
          "value": "kABInstantMessageServiceJabber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageServiceJabber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageServiceJabber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/instant-messaging-services"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/instant-messaging-services"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
