{
  "abstract": [
    {
      "text": "Anniversary date.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/kABAnniversaryLabel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kABAnniversaryLabel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kABAnniversaryLabel"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kABAnniversaryLabel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kABAnniversaryLabel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kABAnniversaryLabel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAddressHomeLabel": {
      "abstract": [
        {
          "text": "Home address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABAddressHomeLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAddressHomeLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAddressHomeLabel"
        }
      ],
      "role": "symbol",
      "title": "kABAddressHomeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabaddresshomelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAddressWorkLabel": {
      "abstract": [
        {
          "text": "Work address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABAddressWorkLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAddressWorkLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAddressWorkLabel"
        }
      ],
      "role": "symbol",
      "title": "kABAddressWorkLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabaddressworklabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAnniversaryLabel": {
      "abstract": [
        {
          "text": "Anniversary date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABAnniversaryLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAnniversaryLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAnniversaryLabel"
        }
      ],
      "role": "symbol",
      "title": "kABAnniversaryLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabanniversarylabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABBrotherLabel": {
      "abstract": [
        {
          "text": "Brother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABBrotherLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABBrotherLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABBrotherLabel"
        }
      ],
      "role": "symbol",
      "title": "kABBrotherLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabbrotherlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABChildLabel": {
      "abstract": [
        {
          "text": "Child.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABChildLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABChildLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABChildLabel"
        }
      ],
      "role": "symbol",
      "title": "kABChildLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabchildlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEmailHomeLabel": {
      "abstract": [
        {
          "text": "Home email.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEmailHomeLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEmailHomeLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABEmailHomeLabel"
        }
      ],
      "role": "symbol",
      "title": "kABEmailHomeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabemailhomelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEmailMobileMeLabel": {
      "abstract": [
        {
          "text": "Mobile Me email.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEmailMobileMeLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEmailMobileMeLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABEmailMobileMeLabel"
        }
      ],
      "role": "symbol",
      "title": "kABEmailMobileMeLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabemailmobilemelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEmailWorkLabel": {
      "abstract": [
        {
          "text": "Work email.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEmailWorkLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEmailWorkLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABEmailWorkLabel"
        }
      ],
      "role": "symbol",
      "title": "kABEmailWorkLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabemailworklabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABFatherLabel": {
      "abstract": [
        {
          "text": "Father.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABFatherLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABFatherLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABFatherLabel"
        }
      ],
      "role": "symbol",
      "title": "kABFatherLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabfatherlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABFriendLabel": {
      "abstract": [
        {
          "text": "Friend.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABFriendLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABFriendLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABFriendLabel"
        }
      ],
      "role": "symbol",
      "title": "kABFriendLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabfriendlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageLabel": {
      "abstract": [
        {
          "text": "Webpage URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABHomePageLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABHomePageLabel"
        }
      ],
      "role": "symbol",
      "title": "kABHomePageLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabhomepagelabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMotherLabel": {
      "abstract": [
        {
          "text": "Mother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMotherLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMotherLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABMotherLabel"
        }
      ],
      "role": "symbol",
      "title": "kABMotherLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabmotherlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABParentLabel": {
      "abstract": [
        {
          "text": "Parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABParentLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABParentLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABParentLabel"
        }
      ],
      "role": "symbol",
      "title": "kABParentLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabparentlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPartnerLabel": {
      "abstract": [
        {
          "text": "Partner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPartnerLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPartnerLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPartnerLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPartnerLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabpartnerlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSisterLabel": {
      "abstract": [
        {
          "text": "Sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSisterLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSisterLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSisterLabel"
        }
      ],
      "role": "symbol",
      "title": "kABSisterLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabsisterlabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSpouseLabel": {
      "abstract": [
        {
          "text": "Spouse.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSpouseLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSpouseLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSpouseLabel"
        }
      ],
      "role": "symbol",
      "title": "kABSpouseLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabspouselabel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABEmailWorkLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABEmailHomeLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABEmailMobileMeLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABAddressHomeLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABAddressWorkLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABFatherLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMotherLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABParentLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABBrotherLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSisterLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABChildLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABFriendLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSpouseLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPartnerLabel"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kABAnniversaryLabel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAnniversaryLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABEmailWorkLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABEmailHomeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABEmailMobileMeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABAddressHomeLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABAddressWorkLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABFatherLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABMotherLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABParentLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABBrotherLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSisterLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABChildLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABFriendLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSpouseLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPartnerLabel"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kABAnniversaryLabel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSisterLabel/title",
          "value": "kABSisterLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSisterLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSisterLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFatherLabel/title",
          "value": "kABFatherLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFatherLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABFatherLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPartnerLabel/title",
          "value": "kABPartnerLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPartnerLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPartnerLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABChildLabel/title",
          "value": "kABChildLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABChildLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABChildLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMotherLabel/title",
          "value": "kABMotherLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMotherLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABMotherLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABParentLabel/title",
          "value": "kABParentLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABParentLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABParentLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAddressHomeLabel/title",
          "value": "kABAddressHomeLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAddressHomeLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAddressHomeLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFriendLabel/title",
          "value": "kABFriendLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFriendLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABFriendLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAnniversaryLabel/title",
          "value": "kABAnniversaryLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAnniversaryLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAnniversaryLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSpouseLabel/title",
          "value": "kABSpouseLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSpouseLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSpouseLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABHomePageLabel/title",
          "value": "kABHomePageLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABHomePageLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABHomePageLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailWorkLabel/title",
          "value": "kABEmailWorkLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailWorkLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABEmailWorkLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAddressWorkLabel/title",
          "value": "kABAddressWorkLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAddressWorkLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAddressWorkLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailMobileMeLabel/title",
          "value": "kABEmailMobileMeLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailMobileMeLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABEmailMobileMeLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABBrotherLabel/title",
          "value": "kABBrotherLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABBrotherLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABBrotherLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailHomeLabel/title",
          "value": "kABEmailHomeLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailHomeLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABEmailHomeLabel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/kabanniversarylabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/kabanniversarylabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
