{
  "abstract": [
    {
      "text": "Dictionary property. Returned as a ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdictionary",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/kABDictionaryPropertyType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kABInvalidPropertyType@kABDictionaryPropertyType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kABDictionaryPropertyType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kABDictionaryPropertyType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kABDictionaryPropertyType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kABDictionaryPropertyType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef": {
      "abstract": [
        {
          "text": "A reference to an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "ABMutableMultiValueobject",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultiValue"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMultiValue"
        }
      ],
      "role": "symbol",
      "title": "ABMultiValue",
      "type": "topic",
      "url": "/documentation/addressbook/abmultivalueref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDateTimePropertyType": {
      "abstract": [
        {
          "text": "Date-time property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDateTimePropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDateTimePropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABDateTimePropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABDateTimePropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabdatetimepropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDictionaryPropertyType": {
      "abstract": [
        {
          "text": "Dictionary property. Returned as a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdictionary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDictionaryPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDictionaryPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABDictionaryPropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABDictionaryPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabdictionarypropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABIntegerPropertyType": {
      "abstract": [
        {
          "text": "Integer property. Returned as a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABIntegerPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABIntegerPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABIntegerPropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABIntegerPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabintegerpropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInvalidPropertyType": {
      "abstract": [
        {
          "text": "Invalid property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInvalidPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInvalidPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInvalidPropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABInvalidPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabinvalidpropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateTimePropertyType": {
      "abstract": [
        {
          "text": "Multi–date-time property. Returned as an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiDateTimePropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateTimePropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABMultiDateTimePropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABMultiDateTimePropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultidatetimepropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDictionaryPropertyType": {
      "abstract": [
        {
          "text": "Multidictionary property. Returned as an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdictionary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiDictionaryPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDictionaryPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABMultiDictionaryPropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABMultiDictionaryPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultidictionarypropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiIntegerPropertyType": {
      "abstract": [
        {
          "text": "Multiinteger property. Returned as an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultiValueRef",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiIntegerPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiIntegerPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABMultiIntegerPropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABMultiIntegerPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultiintegerpropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiRealPropertyType": {
      "abstract": [
        {
          "text": "Multireal property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiRealPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiRealPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABMultiRealPropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABMultiRealPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultirealpropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringPropertyType": {
      "abstract": [
        {
          "text": "Multistring property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiStringPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABMultiStringPropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABMultiStringPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultistringpropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABRealPropertyType": {
      "abstract": [
        {
          "text": "Real property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABRealPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABRealPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABRealPropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABRealPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabrealpropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABStringPropertyType": {
      "abstract": [
        {
          "text": "String property. Returned as a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABStringPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABStringPropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABStringPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabstringpropertytype"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfdate": {
      "abstract": [
        {
          "text": "A reference to an immutable `CFDate` object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDate"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDate",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdate"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfdictionary": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfnumber": {
      "abstract": [
        {
          "text": "A reference to a CFNumber object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFNumber",
      "type": "topic",
      "url": "/documentation/corefoundation/cfnumber"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfstring": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABInvalidPropertyType",
        "doc://com.apple.addressbook/documentation/AddressBook/kABStringPropertyType",
        "doc://com.apple.addressbook/documentation/AddressBook/kABIntegerPropertyType",
        "doc://com.apple.addressbook/documentation/AddressBook/kABRealPropertyType",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDateTimePropertyType",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringPropertyType",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiIntegerPropertyType",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiRealPropertyType",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateTimePropertyType",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDictionaryPropertyType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kABDictionaryPropertyType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABDictionaryPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABInvalidPropertyType",
                "doc://com.apple.addressbook/documentation/AddressBook/kABStringPropertyType",
                "doc://com.apple.addressbook/documentation/AddressBook/kABIntegerPropertyType",
                "doc://com.apple.addressbook/documentation/AddressBook/kABRealPropertyType",
                "doc://com.apple.addressbook/documentation/AddressBook/kABDateTimePropertyType",
                "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringPropertyType",
                "doc://com.apple.addressbook/documentation/AddressBook/kABMultiIntegerPropertyType",
                "doc://com.apple.addressbook/documentation/AddressBook/kABMultiRealPropertyType",
                "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateTimePropertyType",
                "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDictionaryPropertyType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kABDictionaryPropertyType"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMultiRealPropertyType/title",
          "value": "kABMultiRealPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMultiRealPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABMultiRealPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfdictionary/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDictionaryPropertyType/title",
          "value": "kABDictionaryPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDictionaryPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABDictionaryPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABIntegerPropertyType/title",
          "value": "kABIntegerPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABIntegerPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABIntegerPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABRealPropertyType/title",
          "value": "kABRealPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABRealPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABRealPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfnumber/title",
          "value": "CFNumberRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMultiDictionaryPropertyType/title",
          "value": "kABMultiDictionaryPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMultiDictionaryPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABMultiDictionaryPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/title",
          "value": "ABMultiValueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultiValueRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultiValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfdate/title",
          "value": "CFDateRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMultiDateTimePropertyType/title",
          "value": "kABMultiDateTimePropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMultiDateTimePropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABMultiDateTimePropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfstring/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDateTimePropertyType/title",
          "value": "kABDateTimePropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDateTimePropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABDateTimePropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABStringPropertyType/title",
          "value": "kABStringPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABStringPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABStringPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMultiIntegerPropertyType/title",
          "value": "kABMultiIntegerPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMultiIntegerPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABMultiIntegerPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMultiStringPropertyType/title",
          "value": "kABMultiStringPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMultiStringPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABMultiStringPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInvalidPropertyType/title",
          "value": "kABInvalidPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInvalidPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInvalidPropertyType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/kabdictionarypropertytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/kabdictionarypropertytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
