{
  "abstract": [
    {
      "text": "The associated value is a string representing the calendar identifier for a ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendar",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "use NSDateComponents.calendar",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayCalendarIdentifierKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kABPersonAlternateBirthdayCalendarIdentifierKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kABPersonAlternateBirthdayCalendarIdentifierKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kABPersonAlternateBirthdayCalendarIdentifierKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "2.0",
        "message": "use NSDateComponents.calendar",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "2.0",
        "message": "use NSDateComponents.calendar",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "use NSDateComponents.calendar",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kABPersonAlternateBirthdayCalendarIdentifierKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kABPersonAlternateBirthdayCalendarIdentifierKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Corresponds to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsdatecomponents/1415799-calendar",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDictionaryPropertyType": {
      "abstract": [
        {
          "text": "Dictionary property. Returned as a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdictionary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDictionaryPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDictionaryPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABDictionaryPropertyType"
        }
      ],
      "role": "symbol",
      "title": "kABDictionaryPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/kabdictionarypropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCityKey": {
      "abstract": [
        {
          "text": "City.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAddressCityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAddressCityKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAddressCityKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonaddresscitykey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCountryCodeKey": {
      "abstract": [
        {
          "text": "Country code. The value is an ISO country code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAddressCountryCodeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCountryCodeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAddressCountryCodeKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAddressCountryCodeKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonaddresscountrycodekey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCountryKey": {
      "abstract": [
        {
          "text": "Country or region.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAddressCountryKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCountryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAddressCountryKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAddressCountryKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonaddresscountrykey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressProperty": {
      "abstract": [
        {
          "text": "Identifier for the address multivalue property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAddressProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyID",
          "text": "ABPropertyID"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAddressProperty"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAddressProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonaddressproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressStateKey": {
      "abstract": [
        {
          "text": "State.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAddressStateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressStateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAddressStateKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAddressStateKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonaddressstatekey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressStreetKey": {
      "abstract": [
        {
          "text": "Street.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAddressStreetKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressStreetKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAddressStreetKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAddressStreetKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonaddressstreetkey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressZIPKey": {
      "abstract": [
        {
          "text": "Zip code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAddressZIPKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressZIPKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAddressZIPKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAddressZIPKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonaddresszipkey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayCalendarIdentifierKey": {
      "abstract": [
        {
          "text": "The associated value is a string representing the calendar identifier for a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendar",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayCalendarIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayCalendarIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayCalendarIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAlternateBirthdayCalendarIdentifierKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonalternatebirthdaycalendaridentifierkey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayDayKey": {
      "abstract": [
        {
          "text": "The associated value is a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " of type ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumbertype/nsintegertype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " whose value is the day for the birthday.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayDayKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayDayKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayDayKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAlternateBirthdayDayKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonalternatebirthdaydaykey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayEraKey": {
      "abstract": [
        {
          "text": "The associated value is a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " of type ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumbertype/nsintegertype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " whose value is the era for the birthday.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayEraKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayEraKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayEraKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAlternateBirthdayEraKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonalternatebirthdayerakey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayIsLeapMonthKey": {
      "abstract": [
        {
          "text": "The associated value is a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " of type ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumbertype/chartype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayIsLeapMonthKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayIsLeapMonthKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayIsLeapMonthKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAlternateBirthdayIsLeapMonthKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonalternatebirthdayisleapmonthkey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayMonthKey": {
      "abstract": [
        {
          "text": "The associated value is a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " of type ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumbertype/nsintegertype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " whose value is the month for the birthday.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayMonthKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayMonthKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayMonthKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAlternateBirthdayMonthKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonalternatebirthdaymonthkey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayProperty": {
      "abstract": [
        {
          "text": "The associated value is a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDictionaryPropertyType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " with keys specified by the other constants listed here.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyID",
          "text": "ABPropertyID"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayProperty"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAlternateBirthdayProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonalternatebirthdayproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayYearKey": {
      "abstract": [
        {
          "text": "The associated value is a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " of type ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumbertype/nsintegertype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " whose value is the year for the birthday.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayYearKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayYearKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAlternateBirthdayYearKey"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAlternateBirthdayYearKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonalternatebirthdayyearkey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAnniversaryLabel": {
      "abstract": [
        {
          "text": "Birthdate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAnniversaryLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAnniversaryLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAnniversaryLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAnniversaryLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonanniversarylabel"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAssistantLabel": {
      "abstract": [
        {
          "text": "Assistant.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABPersonAssistantLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAssistantLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABPersonAssistantLabel"
        }
      ],
      "role": "symbol",
      "title": "kABPersonAssistantLabel",
      "type": "topic",
      "url": "/documentation/addressbook/kabpersonassistantlabel"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfcalendar": {
      "abstract": [
        {
          "text": "A reference to a CFCalendar object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFCalendar"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfcalendar",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFCalendar",
      "type": "topic",
      "url": "/documentation/corefoundation/cfcalendar"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfnumber": {
      "abstract": [
        {
          "text": "A reference to a CFNumber object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFNumber",
      "type": "topic",
      "url": "/documentation/corefoundation/cfnumber"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfnumbertype/chartype": {
      "abstract": [
        {
          "text": "Basic C `char` type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "case "
        },
        {
          "kind": "identifier",
          "text": "charType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumbertype/chartype",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFNumberType.charType",
      "type": "topic",
      "url": "/documentation/corefoundation/cfnumbertype/chartype"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfnumbertype/nsintegertype": {
      "abstract": [
        {
          "text": "`NSInteger` value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "case "
        },
        {
          "kind": "identifier",
          "text": "nsIntegerType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumbertype/nsintegertype",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFNumberType.nsIntegerType",
      "type": "topic",
      "url": "/documentation/corefoundation/cfnumbertype/nsintegertype"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdatecomponents/1415799-calendar": {
      "abstract": [
        {
          "text": "The calendar used to interpret the date components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "calendar"
        },
        {
          "kind": "text",
          "text": ": Calendar?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdatecomponents/1415799-calendar",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendar",
      "type": "topic",
      "url": "/documentation/foundation/nsdatecomponents/1415799-calendar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCityKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCountryCodeKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCountryKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressStateKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressStreetKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressZIPKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayDayKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayEraKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayIsLeapMonthKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayMonthKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayYearKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAnniversaryLabel",
        "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAssistantLabel"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kABPersonAlternateBirthdayCalendarIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAlternateBirthdayCalendarIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCityKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCountryCodeKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressCountryKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressStateKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressStreetKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAddressZIPKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayDayKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayEraKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayIsLeapMonthKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayMonthKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAlternateBirthdayYearKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAnniversaryLabel",
                "doc://com.apple.addressbook/documentation/AddressBook/kABPersonAssistantLabel"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kABPersonAlternateBirthdayCalendarIdentifierKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "use NSDateComponents.calendar",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressCountryCodeKey/title",
          "value": "kABPersonAddressCountryCodeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressCountryCodeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAddressCountryCodeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayIsLeapMonthKey/title",
          "value": "kABPersonAlternateBirthdayIsLeapMonthKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayIsLeapMonthKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAlternateBirthdayIsLeapMonthKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayYearKey/title",
          "value": "kABPersonAlternateBirthdayYearKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayYearKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAlternateBirthdayYearKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfcalendar/title",
          "value": "CFCalendarRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressProperty/title",
          "value": "kABPersonAddressProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAddressProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAssistantLabel/title",
          "value": "kABPersonAssistantLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAssistantLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAssistantLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayEraKey/title",
          "value": "kABPersonAlternateBirthdayEraKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayEraKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAlternateBirthdayEraKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayCalendarIdentifierKey/title",
          "value": "kABPersonAlternateBirthdayCalendarIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayCalendarIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAlternateBirthdayCalendarIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfnumbertype~1chartype/title",
          "value": "kCFNumberCharType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressCityKey/title",
          "value": "kABPersonAddressCityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressCityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAddressCityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayProperty/title",
          "value": "kABPersonAlternateBirthdayProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAlternateBirthdayProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayDayKey/title",
          "value": "kABPersonAlternateBirthdayDayKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayDayKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAlternateBirthdayDayKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfnumber/title",
          "value": "CFNumberRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressCountryKey/title",
          "value": "kABPersonAddressCountryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressCountryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAddressCountryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayMonthKey/title",
          "value": "kABPersonAlternateBirthdayMonthKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAlternateBirthdayMonthKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAlternateBirthdayMonthKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfnumbertype~1nsintegertype/title",
          "value": "kCFNumberNSIntegerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDictionaryPropertyType/title",
          "value": "kABDictionaryPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDictionaryPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABDictionaryPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAnniversaryLabel/title",
          "value": "kABPersonAnniversaryLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAnniversaryLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAnniversaryLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressZIPKey/title",
          "value": "kABPersonAddressZIPKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressZIPKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAddressZIPKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressStreetKey/title",
          "value": "kABPersonAddressStreetKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressStreetKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAddressStreetKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressStateKey/title",
          "value": "kABPersonAddressStateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABPersonAddressStateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABPersonAddressStateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/kabpersonalternatebirthdaycalendaridentifierkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/kabpersonalternatebirthdaycalendaridentifierkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
