{
  "abstract": [
    {
      "text": "Flickr social profile service.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFlickr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kABSocialProfileServiceFlickr",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kABSocialProfileServiceFlickr"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kABSocialProfileServiceFlickr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kABSocialProfileServiceFlickr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceFlickr"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFacebook": {
      "abstract": [
        {
          "text": "Facebook social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceFacebook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFacebook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceFacebook"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceFacebook",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileservicefacebook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFlickr": {
      "abstract": [
        {
          "text": "Flickr social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceFlickr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFlickr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceFlickr"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceFlickr",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileserviceflickr"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceLinkedIn": {
      "abstract": [
        {
          "text": "LinkedIn social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceLinkedIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceLinkedIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceLinkedIn"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceLinkedIn",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileservicelinkedin"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceMySpace": {
      "abstract": [
        {
          "text": "Myspace social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceMySpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceMySpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceMySpace"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceMySpace",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileservicemyspace"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceSinaWeibo": {
      "abstract": [
        {
          "text": "Sina Weibo social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceSinaWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceSinaWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceSinaWeibo"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceSinaWeibo",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileservicesinaweibo"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceTwitter": {
      "abstract": [
        {
          "text": "Twitter social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceTwitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceTwitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceTwitter"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceTwitter",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileservicetwitter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceTwitter",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFacebook",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceMySpace",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceLinkedIn",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceSinaWeibo"
      ],
      "title": "Services"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kABSocialProfileServiceFlickr"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceFlickr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceTwitter",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFacebook",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceMySpace",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceLinkedIn",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceSinaWeibo"
              ],
              "title": "Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kABSocialProfileServiceFlickr"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceMySpace/title",
          "value": "kABSocialProfileServiceMySpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceMySpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceMySpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceFlickr/title",
          "value": "kABSocialProfileServiceFlickr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceFlickr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceFlickr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceSinaWeibo/title",
          "value": "kABSocialProfileServiceSinaWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceSinaWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceSinaWeibo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceTwitter/title",
          "value": "kABSocialProfileServiceTwitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceTwitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceTwitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceFacebook/title",
          "value": "kABSocialProfileServiceFacebook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceFacebook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceFacebook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceLinkedIn/title",
          "value": "kABSocialProfileServiceLinkedIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceLinkedIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceLinkedIn"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/kabsocialprofileserviceflickr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/kabsocialprofileserviceflickr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
