{
  "abstract": [
    {
      "text": "Used in conjunction with ",
      "type": "text"
    },
    {
      "code": "kABShowAsPerson",
      "type": "codeVoice"
    },
    {
      "text": " and ",
      "type": "text"
    },
    {
      "code": "kABShowAsCompany",
      "type": "codeVoice"
    },
    {
      "text": " to determine record configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kABShowAsMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kABShowAsMask"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kABShowAsMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kABShowAsMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kABShowAsMask"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABMultipleValueSelection": {
      "abstract": [
        {
          "text": "The user can select multiple values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultipleValueSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@ABPeoplePickerSelectionBehavior",
          "text": "ABPeoplePickerSelectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABMultipleValueSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABMultipleValueSelection"
        }
      ],
      "role": "symbol",
      "title": "ABMultipleValueSelection",
      "type": "topic",
      "url": "/documentation/addressbook/abmultiplevalueselection"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABNoValueSelection": {
      "abstract": [
        {
          "text": "The user cannot select individual values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABNoValueSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@ABPeoplePickerSelectionBehavior",
          "text": "ABPeoplePickerSelectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABNoValueSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABNoValueSelection"
        }
      ],
      "role": "symbol",
      "title": "ABNoValueSelection",
      "type": "topic",
      "url": "/documentation/addressbook/abnovalueselection"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerDisplayedPropertyDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the displayed property in the record list is changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerDisplayedPropertyDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerDisplayedPropertyDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPeoplePickerDisplayedPropertyDidChangeNotification",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerdisplayedpropertydidchangenotification"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerGroupSelectionDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the selection in the group list is changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerGroupSelectionDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerGroupSelectionDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPeoplePickerGroupSelectionDidChangeNotification",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickergroupselectiondidchangenotification"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerNameSelectionDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the selection in the name list is changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerNameSelectionDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerNameSelectionDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPeoplePickerNameSelectionDidChangeNotification",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickernameselectiondidchangenotification"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerValueSelectionDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the selection in a multivalue property is changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerValueSelectionDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerValueSelectionDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPeoplePickerValueSelectionDidChangeNotification",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickervalueselectiondidchangenotification"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSingleValueSelection": {
      "abstract": [
        {
          "text": "The user can select a single value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSingleValueSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@ABPeoplePickerSelectionBehavior",
          "text": "ABPeoplePickerSelectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSingleValueSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSingleValueSelection"
        }
      ],
      "role": "symbol",
      "title": "ABSingleValueSelection",
      "type": "topic",
      "url": "/documentation/addressbook/absinglevalueselection"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAlternateBirthdayComponentsProperty": {
      "abstract": [
        {
          "text": "The components that represent a birthday in a non-Gregorian calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABAlternateBirthdayComponentsProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAlternateBirthdayComponentsProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAlternateBirthdayComponentsProperty"
        }
      ],
      "role": "symbol",
      "title": "kABAlternateBirthdayComponentsProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabalternatebirthdaycomponentsproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABBitsInBitFieldMatch": {
      "abstract": [
        {
          "text": "Search for elements that match the bits in ABPersonFlags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABBitsInBitFieldMatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABBitsInBitFieldMatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABBitsInBitFieldMatch",
      "type": "topic",
      "url": "/documentation/addressbook/kabbitsinbitfieldmatch"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubString": {
      "abstract": [
        {
          "text": "Search for elements that contain the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABContainsSubString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubString",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABContainsSubString",
      "type": "topic",
      "url": "/documentation/addressbook/kabcontainssubstring"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubStringCaseInsensitive": {
      "abstract": [
        {
          "text": "Search for elements that contain the value,ignoring case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABContainsSubStringCaseInsensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubStringCaseInsensitive",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABContainsSubStringCaseInsensitive",
      "type": "topic",
      "url": "/documentation/addressbook/kabcontainssubstringcaseinsensitive"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedExternallyNotification": {
      "abstract": [
        {
          "text": "Posted when a process other than the current one has changed the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABDatabaseChangedExternallyNotification"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedExternallyNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDatabaseChangedExternallyNotification",
      "type": "topic",
      "url": "/documentation/addressbook/kabdatabasechangedexternallynotification"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedNotification": {
      "abstract": [
        {
          "text": "Posted when this process has changed the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kABDatabaseChangedNotification"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDatabaseChangedNotification",
      "type": "topic",
      "url": "/documentation/addressbook/kabdatabasechangednotification"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDefaultNameOrdering": {
      "abstract": [
        {
          "text": "Default name ordering (whether a person’s first name or last name is displayed first) in the Address Book application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDefaultNameOrdering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDefaultNameOrdering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABDefaultNameOrdering"
        }
      ],
      "role": "symbol",
      "title": "kABDefaultNameOrdering",
      "type": "topic",
      "url": "/documentation/addressbook/kabdefaultnameordering"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDeletedRecords": {
      "abstract": [
        {
          "text": "Records that have been deleted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDeletedRecords"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDeletedRecords",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABDeletedRecords"
        }
      ],
      "role": "symbol",
      "title": "kABDeletedRecords",
      "type": "topic",
      "url": "/documentation/addressbook/kabdeletedrecords"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubString": {
      "abstract": [
        {
          "text": "Search for elements that do not contain the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDoesNotContainSubString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubString",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDoesNotContainSubString",
      "type": "topic",
      "url": "/documentation/addressbook/kabdoesnotcontainsubstring"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubStringCaseInsensitive": {
      "abstract": [
        {
          "text": "Search for elements that do not contain the value, ignoring case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDoesNotContainSubStringCaseInsensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubStringCaseInsensitive",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDoesNotContainSubStringCaseInsensitive",
      "type": "topic",
      "url": "/documentation/addressbook/kabdoesnotcontainsubstringcaseinsensitive"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEqual": {
      "abstract": [
        {
          "text": "Search for elements that are equal to the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEqual",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABEqual",
      "type": "topic",
      "url": "/documentation/addressbook/kabequal"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEqualCaseInsensitive": {
      "abstract": [
        {
          "text": "Search for elements that are equal to the value,ignoring case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEqualCaseInsensitive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEqualCaseInsensitive",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABEqualCaseInsensitive",
      "type": "topic",
      "url": "/documentation/addressbook/kabequalcaseinsensitive"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameFirst": {
      "abstract": [
        {
          "text": "First name is displayed first in Address Book.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABFirstNameFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABFirstNameFirst"
        }
      ],
      "role": "symbol",
      "title": "kABFirstNameFirst",
      "type": "topic",
      "url": "/documentation/addressbook/kabfirstnamefirst"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABGreaterThan": {
      "abstract": [
        {
          "text": "Search for elements that are greater than thevalue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABGreaterThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABSearchComparison"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABGreaterThan",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABGreaterThan",
      "type": "topic",
      "url": "/documentation/addressbook/kabgreaterthan"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInsertedRecords": {
      "abstract": [
        {
          "text": "Records that have been inserted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInsertedRecords"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInsertedRecords",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInsertedRecords"
        }
      ],
      "role": "symbol",
      "title": "kABInsertedRecords",
      "type": "topic",
      "url": "/documentation/addressbook/kabinsertedrecords"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABLastNameFirst": {
      "abstract": [
        {
          "text": "Last name is displayed first in Address Book.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABLastNameFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABLastNameFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABLastNameFirst"
        }
      ],
      "role": "symbol",
      "title": "kABLastNameFirst",
      "type": "topic",
      "url": "/documentation/addressbook/kablastnamefirst"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsMask": {
      "abstract": [
        {
          "text": "Used in conjunction with ",
          "type": "text"
        },
        {
          "code": "kABShowAsPerson",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "kABShowAsCompany",
          "type": "codeVoice"
        },
        {
          "text": " to determine record configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABShowAsMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABShowAsMask"
        }
      ],
      "role": "symbol",
      "title": "kABShowAsMask",
      "type": "topic",
      "url": "/documentation/addressbook/kabshowasmask"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABMultipleValueSelection",
        "doc://com.apple.addressbook/documentation/AddressBook/ABNoValueSelection",
        "doc://com.apple.addressbook/documentation/AddressBook/ABSingleValueSelection",
        "doc://com.apple.addressbook/documentation/AddressBook/kABAlternateBirthdayComponentsProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABBitsInBitFieldMatch",
        "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubString",
        "doc://com.apple.addressbook/documentation/AddressBook/kABContainsSubStringCaseInsensitive",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDefaultNameOrdering",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDeletedRecords",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubString",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDoesNotContainSubStringCaseInsensitive",
        "doc://com.apple.addressbook/documentation/AddressBook/kABEqual",
        "doc://com.apple.addressbook/documentation/AddressBook/kABEqualCaseInsensitive",
        "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameFirst",
        "doc://com.apple.addressbook/documentation/AddressBook/kABGreaterThan"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kABShowAsMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABShowAsMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABMultipleValueSelection",
                "doc://com.apple.addressbook/documentation/AddressBook/ABNoValueSelection",
                "doc://com.apple.addressbook/documentation/AddressBook/ABSingleValueSelection",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerDisplayedPropertyDidChangeNotification",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerGroupSelectionDidChangeNotification",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerNameSelectionDidChangeNotification",
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerValueSelectionDidChangeNotification",
                "doc://com.apple.addressbook/documentation/AddressBook/kABAlternateBirthdayComponentsProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedExternallyNotification",
                "doc://com.apple.addressbook/documentation/AddressBook/kABDatabaseChangedNotification",
                "doc://com.apple.addressbook/documentation/AddressBook/kABDefaultNameOrdering",
                "doc://com.apple.addressbook/documentation/AddressBook/kABDeletedRecords",
                "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameFirst",
                "doc://com.apple.addressbook/documentation/AddressBook/kABInsertedRecords",
                "doc://com.apple.addressbook/documentation/AddressBook/kABLastNameFirst"
              ],
              "title": "Miscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kABShowAsMask"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABLastNameFirst/title",
          "value": "kABLastNameFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABLastNameFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABLastNameFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInsertedRecords/title",
          "value": "kABInsertedRecords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInsertedRecords/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInsertedRecords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFirstNameFirst/title",
          "value": "kABFirstNameFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFirstNameFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABFirstNameFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDeletedRecords/title",
          "value": "kABDeletedRecords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDeletedRecords/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABDeletedRecords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsMask/title",
          "value": "kABShowAsMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABShowAsMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSingleValueSelection/title",
          "value": "ABSingleValueSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSingleValueSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSingleValueSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABNoValueSelection/title",
          "value": "ABNoValueSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABNoValueSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABNoValueSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultipleValueSelection/title",
          "value": "ABMultipleValueSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABMultipleValueSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABMultipleValueSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAlternateBirthdayComponentsProperty/title",
          "value": "kABAlternateBirthdayComponentsProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAlternateBirthdayComponentsProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAlternateBirthdayComponentsProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDefaultNameOrdering/title",
          "value": "kABDefaultNameOrdering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDefaultNameOrdering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABDefaultNameOrdering"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/kabshowasmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/kabshowasmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
