{
  "abstract": [
    {
      "text": "Web pages. Type: ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringProperty",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/kABURLsProperty"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kABURLsProperty",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kABURLsProperty"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kABURLsProperty"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kABURLsProperty"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kABURLsProperty"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABAddressProperty": {
      "abstract": [
        {
          "text": "Street addresses. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDictionaryProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABAddressProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABAddressProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAddressProperty"
        }
      ],
      "role": "symbol",
      "title": "kABAddressProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabaddressproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABBirthdayComponentsProperty": {
      "abstract": [
        {
          "text": "Birth date as date components. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDateComponentsProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABBirthdayComponentsProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABBirthdayComponentsProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABBirthdayComponentsProperty"
        }
      ],
      "role": "symbol",
      "title": "kABBirthdayComponentsProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabbirthdaycomponentsproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABBirthdayProperty": {
      "abstract": [
        {
          "text": "Birth date. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDateProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABBirthdayProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABBirthdayProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABBirthdayProperty"
        }
      ],
      "role": "symbol",
      "title": "kABBirthdayProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabbirthdayproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABCalendarURIsProperty": {
      "abstract": [
        {
          "text": "Calendar URIs. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABCalendarURIsProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABCalendarURIsProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABCalendarURIsProperty"
        }
      ],
      "role": "symbol",
      "title": "kABCalendarURIsProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabcalendarurisproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDateComponentsProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "NSDateComponents",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDateComponentsProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDateComponentsProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDateComponentsProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabdatecomponentsproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDateProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "NSDate",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDateProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDateProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDateProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabdateproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABEmailProperty": {
      "abstract": [
        {
          "text": "Email addresses. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABEmailProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABEmailProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABEmailProperty"
        }
      ],
      "role": "symbol",
      "title": "kABEmailProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabemailproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNamePhoneticProperty": {
      "abstract": [
        {
          "text": "Phonetic representation of the first name. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABFirstNamePhoneticProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNamePhoneticProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABFirstNamePhoneticProperty"
        }
      ],
      "role": "symbol",
      "title": "kABFirstNamePhoneticProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabfirstnamephoneticproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameProperty": {
      "abstract": [
        {
          "text": "First name. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABFirstNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABFirstNameProperty"
        }
      ],
      "role": "symbol",
      "title": "kABFirstNameProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabfirstnameproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageProperty": {
      "abstract": [
        {
          "text": "Home web page. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABHomePageProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABHomePageProperty"
        }
      ],
      "role": "symbol",
      "title": "kABHomePageProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabhomepageproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABJobTitleProperty": {
      "abstract": [
        {
          "text": "Job title. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABJobTitleProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABJobTitleProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABJobTitleProperty"
        }
      ],
      "role": "symbol",
      "title": "kABJobTitleProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabjobtitleproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABLastNamePhoneticProperty": {
      "abstract": [
        {
          "text": "Phonetic representation of the last name. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABLastNamePhoneticProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABLastNamePhoneticProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABLastNamePhoneticProperty"
        }
      ],
      "role": "symbol",
      "title": "kABLastNamePhoneticProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kablastnamephoneticproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABLastNameProperty": {
      "abstract": [
        {
          "text": "Last name. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABLastNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABLastNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABLastNameProperty"
        }
      ],
      "role": "symbol",
      "title": "kABLastNameProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kablastnameproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMaidenNameProperty": {
      "abstract": [
        {
          "text": "Maiden name. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMaidenNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMaidenNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABMaidenNameProperty"
        }
      ],
      "role": "symbol",
      "title": "kABMaidenNameProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmaidennameproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing ",
          "type": "text"
        },
        {
          "code": "NSDate",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiDateProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMultiDateProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultidateproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDictionaryProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing ",
          "type": "text"
        },
        {
          "code": "NSDictionary",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiDictionaryProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDictionaryProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMultiDictionaryProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultidictionaryproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiStringProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMultiStringProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultistringproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABNicknameProperty": {
      "abstract": [
        {
          "text": "Nickname. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABNicknameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABNicknameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABNicknameProperty"
        }
      ],
      "role": "symbol",
      "title": "kABNicknameProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabnicknameproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABOrganizationProperty": {
      "abstract": [
        {
          "text": "Company name. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABOrganizationProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABOrganizationProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABOrganizationProperty"
        }
      ],
      "role": "symbol",
      "title": "kABOrganizationProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kaborganizationproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABOtherDatesProperty": {
      "abstract": [
        {
          "text": "Dates associated with a person. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABOtherDatesProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABOtherDatesProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABOtherDatesProperty"
        }
      ],
      "role": "symbol",
      "title": "kABOtherDatesProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabotherdatesproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABStringProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABStringProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabstringproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABURLsProperty": {
      "abstract": [
        {
          "text": "Web pages. Type: ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABURLsProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABURLsProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABURLsProperty"
        }
      ],
      "role": "symbol",
      "title": "kABURLsProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kaburlsproperty"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABLastNameProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNamePhoneticProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABLastNamePhoneticProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABNicknameProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMaidenNameProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABBirthdayProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABBirthdayComponentsProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABOrganizationProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABJobTitleProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABCalendarURIsProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABEmailProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABAddressProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABOtherDatesProperty"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kABURLsProperty"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABURLsProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABLastNameProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNamePhoneticProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABLastNamePhoneticProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABNicknameProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABMaidenNameProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABBirthdayProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABBirthdayComponentsProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABOrganizationProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABJobTitleProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABHomePageProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABCalendarURIsProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABEmailProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABAddressProperty",
                "doc://com.apple.addressbook/documentation/AddressBook/kABOtherDatesProperty"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kABURLsProperty"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMaidenNameProperty/title",
          "value": "kABMaidenNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABMaidenNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABMaidenNameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABURLsProperty/title",
          "value": "kABURLsProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABURLsProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABURLsProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAddressProperty/title",
          "value": "kABAddressProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABAddressProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAddressProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABCalendarURIsProperty/title",
          "value": "kABCalendarURIsProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABCalendarURIsProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABCalendarURIsProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABBirthdayComponentsProperty/title",
          "value": "kABBirthdayComponentsProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABBirthdayComponentsProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABBirthdayComponentsProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFirstNameProperty/title",
          "value": "kABFirstNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFirstNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABFirstNameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABNicknameProperty/title",
          "value": "kABNicknameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABNicknameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABNicknameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABJobTitleProperty/title",
          "value": "kABJobTitleProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABJobTitleProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABJobTitleProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABOrganizationProperty/title",
          "value": "kABOrganizationProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABOrganizationProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABOrganizationProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABOtherDatesProperty/title",
          "value": "kABOtherDatesProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABOtherDatesProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABOtherDatesProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABLastNamePhoneticProperty/title",
          "value": "kABLastNamePhoneticProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABLastNamePhoneticProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABLastNamePhoneticProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFirstNamePhoneticProperty/title",
          "value": "kABFirstNamePhoneticProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFirstNamePhoneticProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABFirstNamePhoneticProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailProperty/title",
          "value": "kABEmailProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABEmailProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABEmailProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABHomePageProperty/title",
          "value": "kABHomePageProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABHomePageProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABHomePageProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABBirthdayProperty/title",
          "value": "kABBirthdayProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABBirthdayProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABBirthdayProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABLastNameProperty/title",
          "value": "kABLastNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABLastNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABLastNameProperty"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/kaburlsproperty"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/kaburlsproperty"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
