{
  "abstract": [
    {
      "text": "Use this constant to obtain the ABPicker object from aPeople Picker event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-parameter-name"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "People-Picker Event Parameter Name"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerSelectionBehavior": {
      "abstract": [
        {
          "text": "Constants indicating the possible value selection behaviors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPeoplePickerSelectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerSelectionBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerSelectionBehavior"
        }
      ],
      "role": "symbol",
      "title": "ABPeoplePickerSelectionBehavior",
      "type": "topic",
      "url": "/documentation/addressbook/abpeoplepickerselectionbehavior"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAttributes": {
      "abstract": [
        {
          "text": "A bitfield used to specify the selection behavior for the values of multi-value properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ABPickerAttributes"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAttributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPickerAttributes",
      "type": "topic",
      "url": "/documentation/addressbook/abpickerattributes"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations": {
      "abstract": [
        {
          "text": "Get the enumerations you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Enumerations",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-enumerations"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kEventParamABPickerRef": {
      "abstract": [
        {
          "text": "The parameter name of people-picker events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kEventParamABPickerRef"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kEventParamABPickerRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "kEventParamABPickerRef",
      "type": "topic",
      "url": "/documentation/addressbook/keventparamabpickerref"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-class": {
      "abstract": [
        {
          "text": "This is the People Picker event class.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-class",
      "kind": "article",
      "role": "collectionGroup",
      "title": "People-Picker Event Class",
      "type": "topic",
      "url": "/documentation/addressbook/people-picker-event-class"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-kinds": {
      "abstract": [
        {
          "text": "Constants used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPickerAttributes",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to specify People Picker event types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-kinds",
      "kind": "article",
      "role": "collectionGroup",
      "title": "People-Picker Event Kinds",
      "type": "topic",
      "url": "/documentation/addressbook/people-picker-event-kinds"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/people-picker-selection-behavior": {
      "abstract": [
        {
          "text": "Constants to specify the selection behavior for the values of multi-value properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/people-picker-selection-behavior",
      "kind": "article",
      "role": "collectionGroup",
      "title": "People-Picker Selection Behavior",
      "type": "topic",
      "url": "/documentation/addressbook/people-picker-selection-behavior"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Picker",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerSelectionBehavior",
        "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-class",
        "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-kinds",
        "doc://com.apple.addressbook/documentation/AddressBook/people-picker-selection-behavior"
      ],
      "title": "Picker"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kEventParamABPickerRef"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Picker",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABPeoplePickerSelectionBehavior",
                "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-class",
                "doc://com.apple.addressbook/documentation/AddressBook/people-picker-event-kinds",
                "doc://com.apple.addressbook/documentation/AddressBook/people-picker-selection-behavior"
              ],
              "title": "Picker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerSelectionBehavior/title",
          "value": "ABPeoplePickerSelectionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerSelectionBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerSelectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPeoplePickerSelectionBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerSelectionBehavior"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/people-picker-event-parameter-name"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/people-picker-event-parameter-name"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
