{
  "abstract": [
    {
      "text": "Settings that determine how person records are displayed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/ABPerson"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/person-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Person Flags"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPerson": {
      "abstract": [
        {
          "text": "An object that encapsulates all information about a person in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPerson"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPerson"
        }
      ],
      "role": "symbol",
      "title": "ABPerson",
      "type": "topic",
      "url": "/documentation/addressbook/abperson"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDefaultNameOrdering": {
      "abstract": [
        {
          "text": "Default name ordering (whether a person’s first name or last name is displayed first) in the Address Book application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDefaultNameOrdering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDefaultNameOrdering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABDefaultNameOrdering"
        }
      ],
      "role": "symbol",
      "title": "kABDefaultNameOrdering",
      "type": "topic",
      "url": "/documentation/addressbook/kabdefaultnameordering"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameFirst": {
      "abstract": [
        {
          "text": "First name is displayed first in Address Book.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABFirstNameFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABFirstNameFirst"
        }
      ],
      "role": "symbol",
      "title": "kABFirstNameFirst",
      "type": "topic",
      "url": "/documentation/addressbook/kabfirstnamefirst"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABLastNameFirst": {
      "abstract": [
        {
          "text": "Last name is displayed first in Address Book.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABLastNameFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABLastNameFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABLastNameFirst"
        }
      ],
      "role": "symbol",
      "title": "kABLastNameFirst",
      "type": "topic",
      "url": "/documentation/addressbook/kablastnamefirst"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABNameOrderingMask": {
      "abstract": [
        {
          "text": "Used in conjunction with ",
          "type": "text"
        },
        {
          "code": "kABDefaultNameOrdering",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "kABFirstNameFirst",
          "type": "codeVoice"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "code": "kABLastNameFirst",
          "type": "codeVoice"
        },
        {
          "text": " to determine name ordering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABNameOrderingMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABNameOrderingMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABNameOrderingMask"
        }
      ],
      "role": "symbol",
      "title": "kABNameOrderingMask",
      "type": "topic",
      "url": "/documentation/addressbook/kabnameorderingmask"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsCompany": {
      "abstract": [
        {
          "text": "Record is displayed as a company.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABShowAsCompany"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsCompany",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABShowAsCompany"
        }
      ],
      "role": "symbol",
      "title": "kABShowAsCompany",
      "type": "topic",
      "url": "/documentation/addressbook/kabshowascompany"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsMask": {
      "abstract": [
        {
          "text": "Used in conjunction with ",
          "type": "text"
        },
        {
          "code": "kABShowAsPerson",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "kABShowAsCompany",
          "type": "codeVoice"
        },
        {
          "text": " to determine record configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABShowAsMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABShowAsMask"
        }
      ],
      "role": "symbol",
      "title": "kABShowAsMask",
      "type": "topic",
      "url": "/documentation/addressbook/kabshowasmask"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsPerson": {
      "abstract": [
        {
          "text": "Record is displayed as a person.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABShowAsPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABShowAsPerson"
        }
      ],
      "role": "symbol",
      "title": "kABShowAsPerson",
      "type": "topic",
      "url": "/documentation/addressbook/kabshowasperson"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsResource": {
      "abstract": [
        {
          "text": "Record is displayed as a resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABShowAsResource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABShowAsResource"
        }
      ],
      "role": "symbol",
      "title": "kABShowAsResource",
      "type": "topic",
      "url": "/documentation/addressbook/kabshowasresource"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsRoom": {
      "abstract": [
        {
          "text": "Record is displayed as a room.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABShowAsRoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABShowAsRoom"
        }
      ],
      "role": "symbol",
      "title": "kABShowAsRoom",
      "type": "topic",
      "url": "/documentation/addressbook/kabshowasroom"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsMask",
        "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsPerson",
        "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsCompany",
        "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsResource",
        "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsRoom",
        "doc://com.apple.addressbook/documentation/AddressBook/kABNameOrderingMask",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDefaultNameOrdering",
        "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameFirst",
        "doc://com.apple.addressbook/documentation/AddressBook/kABLastNameFirst"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsMask",
                "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsPerson",
                "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsCompany",
                "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsResource",
                "doc://com.apple.addressbook/documentation/AddressBook/kABShowAsRoom",
                "doc://com.apple.addressbook/documentation/AddressBook/kABNameOrderingMask",
                "doc://com.apple.addressbook/documentation/AddressBook/kABDefaultNameOrdering",
                "doc://com.apple.addressbook/documentation/AddressBook/kABFirstNameFirst",
                "doc://com.apple.addressbook/documentation/AddressBook/kABLastNameFirst"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABLastNameFirst/title",
          "value": "kABLastNameFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABLastNameFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABLastNameFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsCompany/title",
          "value": "kABShowAsCompany"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsCompany/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABShowAsCompany"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsResource/title",
          "value": "kABShowAsResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABShowAsResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDefaultNameOrdering/title",
          "value": "kABDefaultNameOrdering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABDefaultNameOrdering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABDefaultNameOrdering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson/title",
          "value": "ABPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPerson/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABNameOrderingMask/title",
          "value": "kABNameOrderingMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABNameOrderingMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABNameOrderingMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsMask/title",
          "value": "kABShowAsMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABShowAsMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsRoom/title",
          "value": "kABShowAsRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABShowAsRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsPerson/title",
          "value": "kABShowAsPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABShowAsPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABShowAsPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFirstNameFirst/title",
          "value": "kABFirstNameFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABFirstNameFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABFirstNameFirst"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/person-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/person-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
