{
  "abstract": [
    {
      "text": "The possible ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " types for ",
      "type": "text"
    },
    {
      "code": "ABRecord",
      "type": "codeVoice"
    },
    {
      "text": " properties:",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/property_types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Property Types"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroup/addPropertiesAndTypes(_:)": {
      "abstract": [
        {
          "text": "Adds the given properties to all records of this type in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPropertiesAndTypes"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroup/addPropertiesAndTypes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPropertiesAndTypes:"
        }
      ],
      "role": "symbol",
      "title": "addPropertiesAndTypes(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/abgroup/addpropertiesandtypes(_:)"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType": {
      "abstract": [
        {
          "text": "These are the possible types of ABRecord properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPropertyType"
        }
      ],
      "role": "symbol",
      "title": "ABPropertyType",
      "type": "topic",
      "url": "/documentation/addressbook/abpropertytype"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants": {
      "abstract": [
        {
          "text": "Get the constants you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Book Constants",
      "type": "topic",
      "url": "/documentation/addressbook/address-book-constants"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-keys": {
      "abstract": [
        {
          "text": "The keys used to specify the different fields in a ",
          "type": "text"
        },
        {
          "code": "kABAddressProperty",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Keys",
      "type": "topic",
      "url": "/documentation/addressbook/address-keys"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/default-group-properties": {
      "abstract": [
        {
          "text": "The properties that a group record contains by default.  Developers can add their own properties with the ",
          "type": "text"
        },
        {
          "code": "ABGroup",
          "type": "codeVoice"
        },
        {
          "text": " method ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroup/addPropertiesAndTypes(_:)",
          "isActive": true,
          "type": "reference"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/default-group-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Default Group Properties",
      "type": "topic",
      "url": "/documentation/addressbook/default-group-properties"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/default-multivalue-list-labels": {
      "abstract": [
        {
          "text": "The default labels contained in the Address Book database for specifying different values in a multivalue list. Users can also add their own labels.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/default-multivalue-list-labels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Default Multivalue List Labels",
      "type": "topic",
      "url": "/documentation/addressbook/default-multivalue-list-labels"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties": {
      "abstract": [
        {
          "text": "The properties that a person record contains by default.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Default Person Properties",
      "type": "topic",
      "url": "/documentation/addressbook/default-person-properties"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties": {
      "abstract": [
        {
          "text": "Properties common to all types of records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Default Record Properties",
      "type": "topic",
      "url": "/documentation/addressbook/default-record-properties"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels": {
      "abstract": [
        {
          "text": "The generic labels contained in the Address Book database for specifying different values in a multivalue list.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generic Multivalue List Labels",
      "type": "topic",
      "url": "/documentation/addressbook/generic-multivalue-list-labels"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABArrayProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABArrayProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABArrayProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABArrayProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabarrayproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDataProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "NSData",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDataProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDataProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDataProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabdataproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDateComponentsProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "NSDateComponents",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDateComponentsProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDateComponentsProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDateComponentsProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabdatecomponentsproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDateProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "NSDate",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDateProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDateProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDateProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabdateproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABDictionaryProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "NSDictionary",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABDictionaryProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABDictionaryProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABDictionaryProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabdictionaryproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABErrorInProperty": {
      "abstract": [
        {
          "text": "An invalid property was used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABErrorInProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABErrorInProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABErrorInProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kaberrorinproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABIntegerProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object representing an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABIntegerProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABIntegerProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABIntegerProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabintegerproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiArrayProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing ",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiArrayProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiArrayProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMultiArrayProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultiarrayproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDataProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing ",
          "type": "text"
        },
        {
          "code": "NSData",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiDataProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDataProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMultiDataProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultidataproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateComponentsProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing ",
          "type": "text"
        },
        {
          "code": "NSDateComponents",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiDateComponentsProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateComponentsProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMultiDateComponentsProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultidatecomponentsproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing ",
          "type": "text"
        },
        {
          "code": "NSDate",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiDateProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMultiDateProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultidateproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDictionaryProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing ",
          "type": "text"
        },
        {
          "code": "NSDictionary",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiDictionaryProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDictionaryProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMultiDictionaryProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultidictionaryproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiIntegerProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " objects representing integers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiIntegerProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiIntegerProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMultiIntegerProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultiintegerproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiRealProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " objects representing real numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiRealProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiRealProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMultiRealProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultirealproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "ABMultiValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABMultiStringProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABMultiStringProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabmultistringproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABRealProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object representing a real number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABRealProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABRealProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABRealProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabrealproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty": {
      "abstract": [
        {
          "text": "This property is an ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABStringProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "_ABPropertyType"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "kABStringProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabstringproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property": {
      "abstract": [
        {
          "text": "A multivalue property type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Multivalue Property",
      "type": "topic",
      "url": "/documentation/addressbook/multivalue-property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Type-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/address-keys",
        "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties",
        "doc://com.apple.addressbook/documentation/AddressBook/default-group-properties",
        "doc://com.apple.addressbook/documentation/AddressBook/default-multivalue-list-labels",
        "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels",
        "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property",
        "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties"
      ],
      "title": "Data Type Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABErrorInProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABStringProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABIntegerProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABRealProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDateProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABArrayProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDictionaryProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDataProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABDateComponentsProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiStringProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiIntegerProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiRealProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiArrayProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDictionaryProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDataProperty",
        "doc://com.apple.addressbook/documentation/AddressBook/kABMultiDateComponentsProperty"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Type-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/address-keys",
                "doc://com.apple.addressbook/documentation/AddressBook/default-person-properties",
                "doc://com.apple.addressbook/documentation/AddressBook/default-group-properties",
                "doc://com.apple.addressbook/documentation/AddressBook/default-multivalue-list-labels",
                "doc://com.apple.addressbook/documentation/AddressBook/generic-multivalue-list-labels",
                "doc://com.apple.addressbook/documentation/AddressBook/multivalue-property",
                "doc://com.apple.addressbook/documentation/AddressBook/default-record-properties"
              ],
              "title": "Data Type Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroup~1addPropertiesAndTypes(_:)/title",
          "value": "addPropertiesAndTypes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroup~1addPropertiesAndTypes(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "addPropertiesAndTypes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/title",
          "value": "ABPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPropertyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPropertyType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/property_types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/property_types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
