{
  "abstract": [
    {
      "text": "The predefined constants are used to identify social networking services.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/social-profile-services"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Social Profile Services"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You may use these constants or any other string.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The value of these constants is undefined until one of the following functions has been called: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookCreate()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreate()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreate()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Neither developers nor users can add more keys.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookCreate()": {
      "abstract": [
        {
          "text": "Creates a new address book object with data from the Address Book database.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBookCreate"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABAddressBookRef",
          "text": "ABAddressBook"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBookCreate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBookCreate"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBookCreate()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbookcreate()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreate()": {
      "abstract": [
        {
          "text": "Returns a new ABGroup object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABGroupCreate"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABGroupCreate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABGroupCreate"
        }
      ],
      "role": "symbol",
      "title": "ABGroupCreate()",
      "type": "topic",
      "url": "/documentation/addressbook/abgroupcreate()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreate()": {
      "abstract": [
        {
          "text": "Returns a newly created person object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonCreate"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABPersonCreate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonCreate"
        }
      ],
      "role": "symbol",
      "title": "ABPersonCreate()",
      "type": "topic",
      "url": "/documentation/addressbook/abpersoncreate()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants": {
      "abstract": [
        {
          "text": "Get the constants you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/address-book-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Address Book Constants",
      "type": "topic",
      "url": "/documentation/addressbook/address-book-constants"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-keys": {
      "abstract": [
        {
          "text": "The keys used to specify the different fields in a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Instant Messaging Keys",
      "type": "topic",
      "url": "/documentation/addressbook/instant-messaging-keys"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-services": {
      "abstract": [
        {
          "text": "The predefined constants are used to identify instant messaging services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Instant Messaging Services",
      "type": "topic",
      "url": "/documentation/addressbook/instant-messaging-services"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageProperty": {
      "abstract": [
        {
          "text": "Instant messaging ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABInstantMessageProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABInstantMessageProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABInstantMessageProperty"
        }
      ],
      "role": "symbol",
      "title": "kABInstantMessageProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabinstantmessageproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileProperty": {
      "abstract": [
        {
          "text": "Social network profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileProperty"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileProperty",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileproperty"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFacebook": {
      "abstract": [
        {
          "text": "Facebook social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceFacebook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFacebook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceFacebook"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceFacebook",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileservicefacebook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFlickr": {
      "abstract": [
        {
          "text": "Flickr social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceFlickr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFlickr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceFlickr"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceFlickr",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileserviceflickr"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceKey": {
      "abstract": [
        {
          "text": "Social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceKey"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileservicekey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceLinkedIn": {
      "abstract": [
        {
          "text": "LinkedIn social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceLinkedIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceLinkedIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceLinkedIn"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceLinkedIn",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileservicelinkedin"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceMySpace": {
      "abstract": [
        {
          "text": "Myspace social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceMySpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceMySpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceMySpace"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceMySpace",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileservicemyspace"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceSinaWeibo": {
      "abstract": [
        {
          "text": "Sina Weibo social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceSinaWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceSinaWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceSinaWeibo"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceSinaWeibo",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileservicesinaweibo"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceTwitter": {
      "abstract": [
        {
          "text": "Twitter social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceTwitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceTwitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileServiceTwitter"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileServiceTwitter",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileservicetwitter"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileURLKey": {
      "abstract": [
        {
          "text": "Social profile URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileURLKey"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileURLKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileurlkey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileUserIdentifierKey": {
      "abstract": [
        {
          "text": "Social profile user identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileUserIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileUserIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileUserIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileUserIdentifierKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileuseridentifierkey"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileUsernameKey": {
      "abstract": [
        {
          "text": "Social profile username.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSocialProfileUsernameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileUsernameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSocialProfileUsernameKey"
        }
      ],
      "role": "symbol",
      "title": "kABSocialProfileUsernameKey",
      "type": "topic",
      "url": "/documentation/addressbook/kabsocialprofileusernamekey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Social-Media-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-keys",
        "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-services"
      ],
      "title": "Social Media Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Services",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceTwitter",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFacebook",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceMySpace",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceLinkedIn",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFlickr",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceSinaWeibo"
      ],
      "title": "Services"
    },
    {
      "abstract": [
        {
          "text": "The keys used to specify the different fields in a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "anchor": "Keys",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileURLKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileUsernameKey",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileUserIdentifierKey"
      ],
      "title": "Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Services",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceTwitter",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFacebook",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceMySpace",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceLinkedIn",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceFlickr",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceSinaWeibo"
              ],
              "title": "Services"
            },
            {
              "abstract": [
                {
                  "text": "The keys used to specify the different fields in a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileProperty",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property.",
                  "type": "text"
                }
              ],
              "anchor": "Keys",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileURLKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileServiceKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileUsernameKey",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSocialProfileUserIdentifierKey"
              ],
              "title": "Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Social-Media-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-keys",
                "doc://com.apple.addressbook/documentation/AddressBook/instant-messaging-services"
              ],
              "title": "Social Media Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileURLKey/title",
          "value": "kABSocialProfileURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileUsernameKey/title",
          "value": "kABSocialProfileUsernameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileUsernameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileUsernameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceLinkedIn/title",
          "value": "kABSocialProfileServiceLinkedIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceLinkedIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceLinkedIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceTwitter/title",
          "value": "kABSocialProfileServiceTwitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceTwitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceTwitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceFacebook/title",
          "value": "kABSocialProfileServiceFacebook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceFacebook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceFacebook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreate()/title",
          "value": "ABPersonCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABPersonCreate()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileProperty/title",
          "value": "kABSocialProfileProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileUserIdentifierKey/title",
          "value": "kABSocialProfileUserIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileUserIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileUserIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceMySpace/title",
          "value": "kABSocialProfileServiceMySpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceMySpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceMySpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCreate()/title",
          "value": "ABGroupCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABGroupCreate()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABGroupCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageProperty/title",
          "value": "kABInstantMessageProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABInstantMessageProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABInstantMessageProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceSinaWeibo/title",
          "value": "kABSocialProfileServiceSinaWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceSinaWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceSinaWeibo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceFlickr/title",
          "value": "kABSocialProfileServiceFlickr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceFlickr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceFlickr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceKey/title",
          "value": "kABSocialProfileServiceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSocialProfileServiceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSocialProfileServiceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookCreate()/title",
          "value": "ABAddressBookCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBookCreate()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBookCreate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/social-profile-services"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/social-profile-services"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
