{
  "abstract": [
    {
      "text": "These constants identify the type of a source.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/source-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Source Types"
  },
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations": {
      "abstract": [
        {
          "text": "Get the enumerations you use to specify Address Book information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/addressbook-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AddressBook Enumerations",
      "type": "topic",
      "url": "/documentation/addressbook/addressbook-enumerations"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/composite-name-format": {
      "abstract": [
        {
          "text": "These constants identify the format to use for a person’s composite name order for person records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/composite-name-format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Composite Name Format",
      "type": "topic",
      "url": "/documentation/addressbook/composite-name-format"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeCardDAV": {
      "abstract": [
        {
          "text": "CardDAV server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSourceTypeCardDAV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeCardDAV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSourceTypeCardDAV"
        }
      ],
      "role": "symbol",
      "title": "kABSourceTypeCardDAV",
      "type": "topic",
      "url": "/documentation/addressbook/kabsourcetypecarddav"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeCardDAVSearch": {
      "abstract": [
        {
          "text": "Searchable CardDAV server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSourceTypeCardDAVSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeCardDAVSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSourceTypeCardDAVSearch"
        }
      ],
      "role": "symbol",
      "title": "kABSourceTypeCardDAVSearch",
      "type": "topic",
      "url": "/documentation/addressbook/kabsourcetypecarddavsearch"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeExchange": {
      "abstract": [
        {
          "text": "Exchange server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSourceTypeExchange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeExchange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSourceTypeExchange"
        }
      ],
      "role": "symbol",
      "title": "kABSourceTypeExchange",
      "type": "topic",
      "url": "/documentation/addressbook/kabsourcetypeexchange"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeExchangeGAL": {
      "abstract": [
        {
          "text": "Exchange Global Address List.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSourceTypeExchangeGAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeExchangeGAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSourceTypeExchangeGAL"
        }
      ],
      "role": "symbol",
      "title": "kABSourceTypeExchangeGAL",
      "type": "topic",
      "url": "/documentation/addressbook/kabsourcetypeexchangegal"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeLDAP": {
      "abstract": [
        {
          "text": "LDAP server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSourceTypeLDAP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeLDAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSourceTypeLDAP"
        }
      ],
      "role": "symbol",
      "title": "kABSourceTypeLDAP",
      "type": "topic",
      "url": "/documentation/addressbook/kabsourcetypeldap"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeLocal": {
      "abstract": [
        {
          "text": "Local address book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSourceTypeLocal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeLocal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSourceTypeLocal"
        }
      ],
      "role": "symbol",
      "title": "kABSourceTypeLocal",
      "type": "topic",
      "url": "/documentation/addressbook/kabsourcetypelocal"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeMobileMe": {
      "abstract": [
        {
          "text": "MobileMe.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kABSourceTypeMobileMe"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeMobileMe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABSourceTypeMobileMe"
        }
      ],
      "role": "symbol",
      "title": "kABSourceTypeMobileMe",
      "type": "topic",
      "url": "/documentation/addressbook/kabsourcetypemobileme"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/record-property-types": {
      "abstract": [
        {
          "text": "These constants identify record property types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/record-property-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Property Types",
      "type": "topic",
      "url": "/documentation/addressbook/record-property-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/record-types": {
      "abstract": [
        {
          "text": "These constants identify record types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/record-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Types",
      "type": "topic",
      "url": "/documentation/addressbook/record-types"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/sort-order": {
      "abstract": [
        {
          "text": "These constants identify sort order for person lists.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/sort-order",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sort Order",
      "type": "topic",
      "url": "/documentation/addressbook/sort-order"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeLocal",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeExchange",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeExchangeGAL",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeMobileMe",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeLDAP",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeCardDAV",
        "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeCardDAVSearch"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeLocal",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeExchange",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeExchangeGAL",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeMobileMe",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeLDAP",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeCardDAV",
                "doc://com.apple.addressbook/documentation/AddressBook/kABSourceTypeCardDAVSearch"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/composite-name-format",
                "doc://com.apple.addressbook/documentation/AddressBook/record-property-types",
                "doc://com.apple.addressbook/documentation/AddressBook/record-types",
                "doc://com.apple.addressbook/documentation/AddressBook/sort-order"
              ],
              "title": "Miscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeLocal/title",
          "value": "kABSourceTypeLocal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeLocal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSourceTypeLocal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeCardDAVSearch/title",
          "value": "kABSourceTypeCardDAVSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeCardDAVSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSourceTypeCardDAVSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeExchange/title",
          "value": "kABSourceTypeExchange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeExchange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSourceTypeExchange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeCardDAV/title",
          "value": "kABSourceTypeCardDAV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeCardDAV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSourceTypeCardDAV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeExchangeGAL/title",
          "value": "kABSourceTypeExchangeGAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeExchangeGAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSourceTypeExchangeGAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeMobileMe/title",
          "value": "kABSourceTypeMobileMe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeMobileMe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSourceTypeMobileMe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeLDAP/title",
          "value": "kABSourceTypeLDAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1kABSourceTypeLDAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABSourceTypeLDAP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/source-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/source-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
