{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/isEnabled","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItem"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property has no effect unless the menu in which the item will be added or is already a part of has been sent "},{"type":"codeVoice","code":"setAutoenablesItems:NO"},{"type":"text","text":". If a menu item is disabled, its keyboard equivalent is also disabled. See the "},{"type":"codeVoice","code":"NSMenuValidation"},{"type":"text","text":" informal protocol specification for cautions regarding this method."}]}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsmenuitem/isenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsmenuitem/isenabled"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"c:objc(cs)NSMenuItem(py)enabled","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"AppKit"}],"symbolKind":"property","platforms":[{"name":"macOS","beta":false,"deprecated":false,"unavailable":false}],"navigatorTitle":[{"text":"enabled","kind":"identifier"}],"title":"isEnabled"},"abstract":[{"text":"A Boolean value that indicates whether the menu item is enabled.","type":"text"}],"references":{"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/isEnabled":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/isEnabled","navigatorTitle":[{"kind":"identifier","text":"enabled"}],"abstract":[{"text":"A Boolean value that indicates whether the menu item is enabled.","type":"text"}],"title":"isEnabled","type":"topic","url":"/documentation/appkit/nsmenuitem/isenabled","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem","url":"/documentation/appkit/nsmenuitem","navigatorTitle":[{"kind":"identifier","text":"NSMenuItem"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSMenuItem"}],"kind":"symbol","type":"topic","title":"NSMenuItem","role":"symbol","abstract":[{"text":"A command item in an app menu.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"enabled"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"enabled","kind":"identifier"}]},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItem"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"enabled","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1isEnabled/title","op":"replace"},{"value":[{"text":"enabled","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1isEnabled/fragments","op":"replace"},{"value":"NSMenuItem","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/title","op":"replace"},{"value":[{"text":"NSMenuItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/fragments","op":"replace"},{"value":[{"text":"NSMenuItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}