{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSeparatorItem"},{"text":": ","kind":"text"},{"text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"This menu item is disabled. The default separator item is blank space.","type":"text"}]}]}],"seeAlsoSections":[{"anchor":"Managing-the-separator-item","title":"Managing the separator item","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItem/separator()"],"generated":true}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/isSeparatorItem","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsmenuitem/isseparatoritem"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsmenuitem/isseparatoritem"]}],"kind":"symbol","abstract":[{"type":"text","text":"A Boolean value indicating whether the menu item is a separator item."}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"separatorItem","kind":"identifier"}],"modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSMenuItem(py)separatorItem","role":"symbol","title":"isSeparatorItem","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSeparatorItem","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"roleHeading":"Instance Property","platforms":[{"name":"macOS","unavailable":false,"deprecated":false,"beta":false}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItem"]]},"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/isSeparatorItem":{"url":"/documentation/appkit/nsmenuitem/isseparatoritem","navigatorTitle":[{"kind":"identifier","text":"separatorItem"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSeparatorItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/isSeparatorItem","role":"symbol","title":"isSeparatorItem","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value indicating whether the menu item is a separator item."}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem","url":"/documentation/appkit/nsmenuitem","navigatorTitle":[{"kind":"identifier","text":"NSMenuItem"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSMenuItem"}],"kind":"symbol","type":"topic","title":"NSMenuItem","role":"symbol","abstract":[{"text":"A command item in an app menu.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/separator()":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"separator"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSMenuItem","preciseIdentifier":"c:objc(cs)NSMenuItem"}],"kind":"symbol","title":"separator()","url":"/documentation/appkit/nsmenuitem/separator()","navigatorTitle":[{"kind":"identifier","text":"separatorItem"}],"abstract":[{"type":"text","text":"Returns a menu item that is used to separate logical groups of menu commands."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/separator()","role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"separatorItem","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"separatorItem","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItem"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"value":[{"generated":true,"anchor":"Managing-the-separator-item","title":"Managing the separator item","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItem/separator()"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isSeparatorItem","kind":"identifier"},{"text":") ","kind":"text"},{"text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"separatorItem","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1isSeparatorItem/title","value":"separatorItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1isSeparatorItem/fragments","value":[{"kind":"identifier","text":"separatorItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/title","value":"NSMenuItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/fragments","value":[{"kind":"identifier","text":"NSMenuItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/navigatorTitle","value":[{"kind":"identifier","text":"NSMenuItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1separator()/title","value":"separatorItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1separator()/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"separatorItem"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}