{"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItem/tag"]}],"metadata":{"platforms":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}],"title":"representedObject","navigatorTitle":[{"kind":"identifier","text":"representedObject"}],"modules":[{"name":"AppKit"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)NSMenuItem(py)representedObject","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"representedObject"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItem"]]},"abstract":[{"type":"text","text":"The object represented by the menu item."}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/representedObject","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"representedObject"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"By setting a represented object for a menu item, you make an association between the menu item and that object. The represented object functions as a more specific form of tag that allows you to associate any object, not just an arbitrary integer, with the items in a menu."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsmenuitem/representedobject"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsmenuitem/representedobject"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/tag":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/tag","url":"/documentation/appkit/nsmenuitem/tag","navigatorTitle":[{"text":"tag","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic","title":"tag","role":"symbol","abstract":[{"text":"The menu item’s tag.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem","url":"/documentation/appkit/nsmenuitem","navigatorTitle":[{"kind":"identifier","text":"NSMenuItem"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSMenuItem"}],"kind":"symbol","type":"topic","title":"NSMenuItem","role":"symbol","abstract":[{"text":"A command item in an app menu.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/representedObject":{"role":"symbol","url":"/documentation/appkit/nsmenuitem/representedobject","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/representedObject","title":"representedObject","abstract":[{"type":"text","text":"The object represented by the menu item."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"representedObject"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"representedObject"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"representedObject"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"representedObject"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItem"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItem/tag"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id","kind":"keyword"},{"text":" ","kind":"text"},{"text":"representedObject","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1tag/title","op":"replace","value":"tag"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1tag/fragments","op":"replace","value":[{"kind":"identifier","text":"tag"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/title","op":"replace","value":"NSMenuItem"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/fragments","op":"replace","value":[{"kind":"identifier","text":"NSMenuItem"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSMenuItem"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1representedObject/title","op":"replace","value":"representedObject"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1representedObject/fragments","op":"replace","value":[{"kind":"identifier","text":"representedObject"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}