{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setMnemonicLocation:","interfaceLanguage":"occ"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setMnemonicLocation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"location"},{"kind":"text","text":";"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"location","content":[{"type":"paragraph","inlineContent":[{"text":"An integer index into the character array of the title. ","type":"text"},{"type":"codeVoice","code":"location"},{"text":" must be from 0 to 254.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"This character identifies the access key by which users can access the menu item.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItem"]]},"variants":[{"paths":["/documentation/appkit/nsmenuitem/setmnemoniclocation:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonicLocation","doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setTitleWithMnemonic(_:)","doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonic"],"title":"Managing mnemonics","generated":true,"anchor":"Managing-mnemonics"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"This method did nothing useful and there is no replacement."}],"type":"paragraph"}],"abstract":[{"text":"Sets the character of the menu item title at location that is to be underlined.","type":"text"}],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"setMnemonicLocation:","kind":"identifier"}],"navigatorTitle":[{"text":"setMnemonicLocation:","kind":"identifier"}],"title":"setMnemonicLocation:","platforms":[{"unavailable":false,"name":"macOS","deprecatedAt":"10.6","beta":false,"introducedAt":"10.0","deprecated":false}],"modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSMenuItem(im)setMnemonicLocation:","roleHeading":"Instance Method"},"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSMenuItem":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem","url":"/documentation/appkit/nsmenuitem","navigatorTitle":[{"kind":"identifier","text":"NSMenuItem"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSMenuItem"}],"kind":"symbol","type":"topic","title":"NSMenuItem","role":"symbol","abstract":[{"text":"A command item in an app menu.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setMnemonicLocation:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setMnemonicLocation:","title":"setMnemonicLocation:","url":"/documentation/appkit/nsmenuitem/setmnemoniclocation:","role":"symbol","kind":"symbol","abstract":[{"text":"Sets the character of the menu item title at location that is to be underlined.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setMnemonicLocation:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMnemonicLocation:"}],"deprecated":true,"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonicLocation":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonicLocation","title":"mnemonicLocation","url":"/documentation/appkit/nsmenuitem/mnemoniclocation","role":"symbol","kind":"symbol","abstract":[{"text":"Returns the position of the underlined character in the menu item title used as a mnemonic.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mnemonicLocation"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mnemonicLocation"}],"deprecated":true,"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setTitleWithMnemonic(_:)":{"title":"setTitleWithMnemonic(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitleWithMnemonic"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setTitleWithMnemonic:","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"Sets the title of a menu item with a character denoting an access key."}],"type":"topic","url":"/documentation/appkit/nsmenuitem/settitlewithmnemonic(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setTitleWithMnemonic(_:)","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonic":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonic","title":"mnemonic","url":"/documentation/appkit/nsmenuitem/mnemonic","role":"symbol","kind":"symbol","abstract":[{"text":"Returns the character in the menu item title that appears underlined for use as a mnemonic.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mnemonic"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mnemonic"}],"deprecated":true,"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"type":"text","text":"Describes an unsigned integer."}],"url":"/documentation/objectivec/nsuinteger","kind":"symbol","role":"symbol","title":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/title","value":"NSMenuItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/fragments","value":[{"text":"NSMenuItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/navigatorTitle","value":[{"kind":"identifier","text":"NSMenuItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1setTitleWithMnemonic(_:)/title","value":"setTitleWithMnemonic:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1setTitleWithMnemonic(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleWithMnemonic:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}