{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setTitleWithMnemonic(_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItem"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setTitleWithMnemonic:"}],"extendedModule":"AppKit","symbolKind":"method","title":"setTitleWithMnemonic(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitleWithMnemonic"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":[{"deprecatedAt":"10.13","introducedAt":"10.0","name":"macOS","unavailable":false,"deprecated":false,"beta":false}],"modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)NSMenuItem(im)setTitleWithMnemonic:","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsmenuitem/settitlewithmnemonic(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsmenuitem/settitlewithmnemonic(_:)"]}],"abstract":[{"type":"text","text":"Sets the title of a menu item with a character denoting an access key."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTitleWithMnemonic","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"stringWithAmpersand","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:SS","text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use an ampersand character to mark the character (the one following the ampersand) to be designated."}]}],"kind":"content"}],"references":{"doc://com.externally.resolved.symbol/s:SS":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"type":"topic","title":"String","role":"symbol","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonic":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonic","title":"mnemonic","url":"/documentation/appkit/nsmenuitem/mnemonic","role":"symbol","kind":"symbol","abstract":[{"text":"Returns the character in the menu item title that appears underlined for use as a mnemonic.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mnemonic"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mnemonic"}],"deprecated":true,"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem","url":"/documentation/appkit/nsmenuitem","navigatorTitle":[{"kind":"identifier","text":"NSMenuItem"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSMenuItem"}],"kind":"symbol","type":"topic","title":"NSMenuItem","role":"symbol","abstract":[{"text":"A command item in an app menu.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setTitleWithMnemonic(_:)":{"title":"setTitleWithMnemonic(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitleWithMnemonic"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setTitleWithMnemonic:","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"Sets the title of a menu item with a character denoting an access key."}],"type":"topic","url":"/documentation/appkit/nsmenuitem/settitlewithmnemonic(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setTitleWithMnemonic(_:)","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"title":"NSString","kind":"symbol","url":"/documentation/foundation/nsstring","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setMnemonicLocation:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setMnemonicLocation:","title":"setMnemonicLocation:","url":"/documentation/appkit/nsmenuitem/setmnemoniclocation:","role":"symbol","kind":"symbol","abstract":[{"text":"Sets the character of the menu item title at location that is to be underlined.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setMnemonicLocation:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMnemonicLocation:"}],"deprecated":true,"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonicLocation":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonicLocation","title":"mnemonicLocation","url":"/documentation/appkit/nsmenuitem/mnemoniclocation","role":"symbol","kind":"symbol","abstract":[{"text":"Returns the position of the underlined character in the menu item title used as a mnemonic.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mnemonicLocation"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mnemonicLocation"}],"deprecated":true,"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.0","deprecatedAt":"10.13","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"setTitleWithMnemonic:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"setTitleWithMnemonic:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItem"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonic","doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setMnemonicLocation:"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItem/setMnemonicLocation:","doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonicLocation","doc://com.apple.appkit/documentation/AppKit/NSMenuItem/mnemonic"],"title":"Managing mnemonics","generated":true,"anchor":"Managing-mnemonics"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setTitleWithMnemonic:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"stringWithAmpersand","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/title","value":"NSMenuItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/fragments","value":[{"kind":"identifier","text":"NSMenuItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/navigatorTitle","value":[{"text":"NSMenuItem","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1setTitleWithMnemonic(_:)/title","value":"setTitleWithMnemonic:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1setTitleWithMnemonic(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setTitleWithMnemonic:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"type":"text","text":"A static, plain-text Unicode string object."}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}