{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/tag","interfaceLanguage":"swift"},"kind":"symbol","seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItem/representedObject"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tag","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItem"]]},"abstract":[{"type":"text","text":"The menu item’s tag."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsmenuitem/tag"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsmenuitem/tag"]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"tag","modules":[{"name":"AppKit"}],"platforms":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tag"}],"externalID":"c:objc(cs)NSMenuItem(py)tag"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit/NSMenuItem":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem","url":"/documentation/appkit/nsmenuitem","navigatorTitle":[{"kind":"identifier","text":"NSMenuItem"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSMenuItem"}],"kind":"symbol","type":"topic","title":"NSMenuItem","role":"symbol","abstract":[{"text":"A command item in an app menu.","type":"text"}]},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/representedObject":{"role":"symbol","url":"/documentation/appkit/nsmenuitem/representedobject","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/representedObject","title":"representedObject","abstract":[{"type":"text","text":"The object represented by the menu item."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"representedObject"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"representedObject"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/tag":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItem/tag","url":"/documentation/appkit/nsmenuitem/tag","navigatorTitle":[{"text":"tag","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic","title":"tag","role":"symbol","abstract":[{"text":"The menu item’s tag.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"tag","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"tag"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItem"]]},"op":"replace","path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItem/representedObject"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"tag","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":"NSMenuItem","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/title"},{"op":"replace","value":[{"text":"NSMenuItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSMenuItem"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/navigatorTitle"},{"op":"replace","value":"representedObject","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1representedObject/title"},{"op":"replace","value":[{"kind":"identifier","text":"representedObject"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1representedObject/fragments"},{"op":"replace","value":"tag","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1tag/title"},{"op":"replace","value":[{"text":"tag","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem~1tag/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}