{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSContainerStatus",
        "doc://FSKit/documentation/FSKit/FSContainerState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSContainerState/Equatable-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Equatable Implementations"
  },
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSContainerState": {
      "abstract": [
        {
          "text": "An enumeration of container state values.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSContainerState"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSContainerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSContainerState"
        }
      ],
      "role": "symbol",
      "title": "FSContainerState",
      "type": "topic",
      "url": "/documentation/fskit/fscontainerstate"
    },
    "doc://FSKit/documentation/FSKit/FSContainerState/!=(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether two values are not equal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "!="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSContainerState/!=(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "!=(_:_:)",
      "type": "topic",
      "url": "/documentation/fskit/fscontainerstate/!=(_:_:)"
    },
    "doc://FSKit/documentation/FSKit/FSContainerStatus": {
      "abstract": [
        {
          "text": "A type that represents a container’s status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSContainerStatus"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSContainerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSContainerStatus"
        }
      ],
      "role": "symbol",
      "title": "FSContainerStatus",
      "type": "topic",
      "url": "/documentation/fskit/fscontainerstatus"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Operators",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSContainerState/!=(_:_:)"
      ],
      "title": "Operators"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSContainerStatus/title",
          "value": "FSContainerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSContainerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSContainerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSContainerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSContainerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSContainerState/title",
          "value": "FSContainerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSContainerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSContainerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSContainerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSContainerState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fscontainerstate/equatable-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
