{
  "abstract": [
    {
      "text": "Returns a shared keychain settings panel object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.securityinterface/documentation/SecurityInterface",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel/shared()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFKeychainSettingsPanel(cm)sharedKeychainSettingsPanel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "shared"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SFKeychainSettingsPanel",
        "text": "SFKeychainSettingsPanel"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Security Interface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sharedKeychainSettingsPanel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "shared()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shared"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SFKeychainSettingsPanel",
              "text": "SFKeychainSettingsPanel"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the shared object has not already been created, this method allocates and initializes the object first.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface": {
      "abstract": [
        {
          "text": "Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Interface",
      "type": "topic",
      "url": "/documentation/securityinterface"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel": {
      "abstract": [
        {
          "text": "A panel or sheet that allows users to change their keychain settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFKeychainSettingsPanel"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFKeychainSettingsPanel"
        }
      ],
      "role": "symbol",
      "title": "SFKeychainSettingsPanel",
      "type": "topic",
      "url": "/documentation/securityinterface/sfkeychainsettingspanel"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel/shared()": {
      "abstract": [
        {
          "text": "Returns a shared keychain settings panel object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFKeychainSettingsPanel",
          "text": "SFKeychainSettingsPanel"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel/shared()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedKeychainSettingsPanel"
        }
      ],
      "role": "symbol",
      "title": "shared()",
      "type": "topic",
      "url": "/documentation/securityinterface/sfkeychainsettingspanel/shared()"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "https://developer.apple.com/library/archive/documentation/Security/Conceptual/keychainServConcepts/01introduction/introduction.html#//apple_ref/doc/uid/TP30000897": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Security/Conceptual/keychainServConcepts/01introduction/introduction.html#//apple_ref/doc/uid/TP30000897",
      "title": "Keychain Services Programming Guide",
      "titleInlineContent": [
        {
          "text": "Keychain Services Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Security/Conceptual/keychainServConcepts/01introduction/introduction.html#//apple_ref/doc/uid/TP30000897"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Security/Conceptual/keychainServConcepts/01introduction/introduction.html#//apple_ref/doc/uid/TP30000897"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sharedKeychainSettingsPanel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedKeychainSettingsPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.securityinterface/documentation/SecurityInterface",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/Security/Conceptual/keychainServConcepts/01introduction/introduction.html#//apple_ref/doc/uid/TP30000897"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SFKeychainSettingsPanel",
                    "text": "SFKeychainSettingsPanel"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "sharedKeychainSettingsPanel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFKeychainSettingsPanel~1shared()/title",
          "value": "sharedKeychainSettingsPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFKeychainSettingsPanel~1shared()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedKeychainSettingsPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFKeychainSettingsPanel/title",
          "value": "SFKeychainSettingsPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFKeychainSettingsPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFKeychainSettingsPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFKeychainSettingsPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFKeychainSettingsPanel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityinterface/sfkeychainsettingspanel/shared()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/securityinterface/sfkeychainsettingspanel/shared()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
