{
  "abstract": [
    {
      "text": "An error that indicates the parent record doesn’t exist.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts",
        "doc://com.apple.contacts/documentation/Contacts/CNError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/parentRecordDoesNotExist"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CNErrorCode@CNErrorCodeParentRecordDoesNotExist",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "parentRecordDoesNotExist"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNErrorCodeParentRecordDoesNotExist"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CNError.Code.parentRecordDoesNotExist"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "parentRecordDoesNotExist"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError": {
      "abstract": [
        {
          "text": "Error information that may be returned when using the methods of the Contacts framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNError"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNError"
        }
      ],
      "role": "symbol",
      "title": "CNError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code": {
      "abstract": [
        {
          "text": "Error codes that the system may return when you use Contacts framework methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/authorizationDenied": {
      "abstract": [
        {
          "text": "An error that indicates the system denied authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationDenied"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/authorizationDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeAuthorizationDenied"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.authorizationDenied",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/authorizationdenied"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryExpired": {
      "abstract": [
        {
          "text": "An error that indicates the change history expired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryExpired"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeChangeHistoryExpired"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.changeHistoryExpired",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/changehistoryexpired"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidAnchor": {
      "abstract": [
        {
          "text": "An error that indicates a change history anchor is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryInvalidAnchor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeChangeHistoryInvalidAnchor"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.changeHistoryInvalidAnchor",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/changehistoryinvalidanchor"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidFetchRequest": {
      "abstract": [
        {
          "text": "An error that indicates a change history fetch request is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryInvalidFetchRequest"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidFetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeChangeHistoryInvalidFetchRequest"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.changeHistoryInvalidFetchRequest",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/changehistoryinvalidfetchrequest"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierCollision": {
      "abstract": [
        {
          "text": "An error that indicates a client identifier collision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierCollision"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierCollision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeClientIdentifierCollision"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.clientIdentifierCollision",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/clientidentifiercollision"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierDoesNotExist": {
      "abstract": [
        {
          "text": "An error that indicates the client identifier doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierDoesNotExist"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierDoesNotExist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeClientIdentifierDoesNotExist"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.clientIdentifierDoesNotExist",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/clientidentifierdoesnotexist"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierInvalid": {
      "abstract": [
        {
          "text": "An error that indicates the client identifier is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierInvalid"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeClientIdentifierInvalid"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.clientIdentifierInvalid",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/clientidentifierinvalid"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/communicationError": {
      "abstract": [
        {
          "text": "An error that indicates a communication error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationError"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/communicationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeCommunicationError"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.communicationError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/communicationerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentCycle": {
      "abstract": [
        {
          "text": "An error with the containment cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containmentCycle"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentCycle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeContainmentCycle"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.containmentCycle",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/containmentcycle"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentScope": {
      "abstract": [
        {
          "text": "An error with containment scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containmentScope"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeContainmentScope"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.containmentScope",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/containmentscope"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/dataAccessError": {
      "abstract": [
        {
          "text": "An error with data access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataAccessError"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/dataAccessError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeDataAccessError"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.dataAccessError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/dataaccesserror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureDisabledByUser": {
      "abstract": [
        {
          "text": "An error that indicates the user disabled the feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureDisabledByUser"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureDisabledByUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeFeatureDisabledByUser"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.featureDisabledByUser",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/featuredisabledbyuser"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureNotAvailable": {
      "abstract": [
        {
          "text": "An error that indicates the feature isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeFeatureNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.featureNotAvailable",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/featurenotavailable"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/insertedRecordAlreadyExists": {
      "abstract": [
        {
          "text": "An error that indicates the inserted record already exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertedRecordAlreadyExists"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/insertedRecordAlreadyExists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeInsertedRecordAlreadyExists"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.insertedRecordAlreadyExists",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/insertedrecordalreadyexists"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/noAccessableWritableContainers": {
      "abstract": [
        {
          "text": "An error that indicates there are no accessible writable containers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAccessableWritableContainers"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/noAccessableWritableContainers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeNoAccessableWritableContainers"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.noAccessableWritableContainers",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/noaccessablewritablecontainers"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/parentRecordDoesNotExist": {
      "abstract": [
        {
          "text": "An error that indicates the parent record doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentRecordDoesNotExist"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/parentRecordDoesNotExist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeParentRecordDoesNotExist"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.parentRecordDoesNotExist",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/parentrecorddoesnotexist"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/authorizationDenied",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryExpired",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidAnchor",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidFetchRequest",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierCollision",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierInvalid",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierDoesNotExist",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/communicationError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentCycle",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentScope",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/dataAccessError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureDisabledByUser",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureNotAvailable",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/insertedRecordAlreadyExists",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/noAccessableWritableContainers"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNErrorCodeParentRecordDoesNotExist"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeParentRecordDoesNotExist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/authorizationDenied",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryExpired",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidAnchor",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidFetchRequest",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierCollision",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierInvalid",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierDoesNotExist",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/communicationError",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentCycle",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentScope",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/dataAccessError",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureDisabledByUser",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureNotAvailable",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/insertedRecordAlreadyExists",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/noAccessableWritableContainers"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CNErrorCodeParentRecordDoesNotExist"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1insertedRecordAlreadyExists/title",
          "value": "CNErrorCodeInsertedRecordAlreadyExists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1insertedRecordAlreadyExists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeInsertedRecordAlreadyExists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierDoesNotExist/title",
          "value": "CNErrorCodeClientIdentifierDoesNotExist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierDoesNotExist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeClientIdentifierDoesNotExist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierInvalid/title",
          "value": "CNErrorCodeClientIdentifierInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeClientIdentifierInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1containmentScope/title",
          "value": "CNErrorCodeContainmentScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1containmentScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeContainmentScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryInvalidFetchRequest/title",
          "value": "CNErrorCodeChangeHistoryInvalidFetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryInvalidFetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeChangeHistoryInvalidFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierCollision/title",
          "value": "CNErrorCodeClientIdentifierCollision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierCollision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeClientIdentifierCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1featureDisabledByUser/title",
          "value": "CNErrorCodeFeatureDisabledByUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1featureDisabledByUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeFeatureDisabledByUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1featureNotAvailable/title",
          "value": "CNErrorCodeFeatureNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1featureNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeFeatureNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1noAccessableWritableContainers/title",
          "value": "CNErrorCodeNoAccessableWritableContainers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1noAccessableWritableContainers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeNoAccessableWritableContainers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1communicationError/title",
          "value": "CNErrorCodeCommunicationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1communicationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeCommunicationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryExpired/title",
          "value": "CNErrorCodeChangeHistoryExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeChangeHistoryExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1containmentCycle/title",
          "value": "CNErrorCodeContainmentCycle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1containmentCycle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeContainmentCycle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1authorizationDenied/title",
          "value": "CNErrorCodeAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1authorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeAuthorizationDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/title",
          "value": "CNErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1dataAccessError/title",
          "value": "CNErrorCodeDataAccessError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1dataAccessError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeDataAccessError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryInvalidAnchor/title",
          "value": "CNErrorCodeChangeHistoryInvalidAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryInvalidAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeChangeHistoryInvalidAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1parentRecordDoesNotExist/title",
          "value": "CNErrorCodeParentRecordDoesNotExist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1parentRecordDoesNotExist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeParentRecordDoesNotExist"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnerror/code/parentrecorddoesnotexist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnerror/code/parentrecorddoesnotexist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
