{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPPanDirection/CPPanDirectionNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CPPanDirection@CPPanDirectionNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CPPanDirectionNone"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPPanDirectionNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "CPPanDirectionNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "CPPanDirectionNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection": {
      "abstract": [
        {
          "text": "The directions a user can pan (or move) a map displayed on the CarPlay screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PanDirection"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplate.PanDirection",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/down": {
      "abstract": [
        {
          "text": "The user panned the map downward.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPanDirectionDown"
        }
      ],
      "role": "symbol",
      "title": "down",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection/down"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/left": {
      "abstract": [
        {
          "text": "The user panned the map to the left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPanDirectionLeft"
        }
      ],
      "role": "symbol",
      "title": "left",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection/left"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/right": {
      "abstract": [
        {
          "text": "The user panned the map to the right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPanDirectionRight"
        }
      ],
      "role": "symbol",
      "title": "right",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection/right"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/up": {
      "abstract": [
        {
          "text": "The user panned the map upward.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPanDirectionUp"
        }
      ],
      "role": "symbol",
      "title": "up",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection/up"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPPanDirection/CPPanDirectionNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CPPanDirectionNone"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPanDirection/CPPanDirectionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "CPPanDirectionNone",
      "type": "topic",
      "url": "/documentation/carplay/cppandirection/cppandirectionnone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Pan-Directions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/down",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/left",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/right",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection/up"
      ],
      "title": "Pan Directions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/title",
          "value": "CPPanDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1left/title",
          "value": "CPPanDirectionLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirectionLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1up/title",
          "value": "CPPanDirectionUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirectionUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1right/title",
          "value": "CPPanDirectionRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirectionRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1down/title",
          "value": "CPPanDirectionDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirectionDown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cppandirection/cppandirectionnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
