{
  "abstract": [
    {
      "text": "Interface is participating in an infrastructure network as an access point.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/hostAP"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CWInterfaceMode@kCWInterfaceModeHostAP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hostAP"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCWInterfaceModeHostAP"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CWInterfaceMode.hostAP"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hostAP"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode": {
      "abstract": [
        {
          "text": "Wi-Fi interface operating modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWInterfaceMode"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWInterfaceMode"
        }
      ],
      "role": "symbol",
      "title": "CWInterfaceMode",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterfacemode"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/IBSS": {
      "abstract": [
        {
          "text": "Interface is participating in an IBSS network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IBSS"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/IBSS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInterfaceModeIBSS"
        }
      ],
      "role": "symbol",
      "title": "CWInterfaceMode.IBSS",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterfacemode/ibss"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/hostAP": {
      "abstract": [
        {
          "text": "Interface is participating in an infrastructure network as an access point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostAP"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/hostAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInterfaceModeHostAP"
        }
      ],
      "role": "symbol",
      "title": "CWInterfaceMode.hostAP",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterfacemode/hostap"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/none": {
      "abstract": [
        {
          "text": "Interface is not in any mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInterfaceModeNone"
        }
      ],
      "role": "symbol",
      "title": "CWInterfaceMode.none",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterfacemode/none"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/station": {
      "abstract": [
        {
          "text": "Interface is participating in an infrastructure network as a non-AP station.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "station"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/station",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInterfaceModeStation"
        }
      ],
      "role": "symbol",
      "title": "CWInterfaceMode.station",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterfacemode/station"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/none",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/station",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/IBSS"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCWInterfaceModeHostAP"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInterfaceModeHostAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/none",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/station",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterfaceMode/IBSS"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCWInterfaceModeHostAP"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode~1hostAP/title",
          "value": "kCWInterfaceModeHostAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode~1hostAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInterfaceModeHostAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode~1none/title",
          "value": "kCWInterfaceModeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInterfaceModeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode~1IBSS/title",
          "value": "kCWInterfaceModeIBSS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode~1IBSS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInterfaceModeIBSS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/title",
          "value": "CWInterfaceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterfaceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterfaceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode~1station/title",
          "value": "kCWInterfaceModeStation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterfaceMode~1station/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInterfaceModeStation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwinterfacemode/hostap"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwinterfacemode/hostap"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
