{
  "abstract": [
    {
      "text": "Modifies the specified records and delivers the results to a completion hander.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/modifyRecords(saving:deleting:savePolicy:atomically:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CloudKit",
    "externalID": "s:So10CKDatabaseC8CloudKitE13modifyRecords6saving8deleting10savePolicy10atomically17completionHandlerySaySo8CKRecordCG_SaySo0M2IDCGSo0m4SaveI0VSbys6ResultOySDyAnSyAKs5Error_pGG0H7Results_SDyAnSyytsAT_pGG06deleteR0tsAT_pGctF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "modifyRecords"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "saving"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecord",
        "text": "CKRecord"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "deleting"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecord",
        "text": "CKRecord"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecordID",
        "text": "ID"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "savePolicy"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKModifyRecordsOperation",
        "text": "CKModifyRecordsOperation"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CKRecordSavePolicy",
        "text": "RecordSavePolicy"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "atomically"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6ResultO",
        "text": "Result"
      },
      {
        "kind": "text",
        "text": "<(saveResults"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecord",
        "text": "CKRecord"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecordID",
        "text": "ID"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6ResultO",
        "text": "Result"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecord",
        "text": "CKRecord"
      },
      {
        "kind": "text",
        "text": ", any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ">], deleteResults"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecord",
        "text": "CKRecord"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecordID",
        "text": "ID"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6ResultO",
        "text": "Result"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ", any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ">]), any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "modifyRecords(saving:deleting:savePolicy:atomically:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "modifyRecords"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "saving"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "recordsToSave"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecord",
              "text": "CKRecord"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "deleting"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "recordIDsToDelete"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecord",
              "text": "CKRecord"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/ID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecordID",
              "text": "ID"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "savePolicy"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKModifyRecordsOperation",
              "text": "CKModifyRecordsOperation"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CKRecordSavePolicy",
              "text": "RecordSavePolicy"
            },
            {
              "kind": "text",
              "text": " = .ifServerRecordUnchanged, "
            },
            {
              "kind": "externalParam",
              "text": "atomically"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " = true, "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6ResultO",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6ResultO",
              "text": "Result"
            },
            {
              "kind": "text",
              "text": "<(saveResults"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecord",
              "text": "CKRecord"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/ID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecordID",
              "text": "ID"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6ResultO",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6ResultO",
              "text": "Result"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecord",
              "text": "CKRecord"
            },
            {
              "kind": "text",
              "text": ", any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ">], deleteResults"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecord",
              "text": "CKRecord"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/ID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecordID",
              "text": "ID"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6ResultO",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6ResultO",
              "text": "Result"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ", any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ">]), any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The records to save.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "recordsToSave"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identifiers of the records to permanently delete.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "recordIDsToDelete"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The policy to use when modifying existing records. For possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "savePolicy"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", the entire operation fails if CloudKit can’t modify one or more of the specified records; otherwise, CloudKit reports individual failures in the returned tuple. Atomic changes are only applicable in record zones that have the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone/Capabilities-swift.struct/atomic",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " capability.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "atomically"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The closure to execute after CloudKit processes the changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The completion handler takes a single ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/Result",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " parameter that contains either a tuple, or an error if the request fails. For example, when the network is unavailable or the device doesn’t have an active iCloud account, or when ",
              "type": "text"
            },
            {
              "code": "atomically",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and one or more of the specified changes fail.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When present, the tuple contains the following named elements:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A dictionary of saved records. The dictionary uses the identifiers of the records you specify in ",
                        "type": "text"
                      },
                      {
                        "code": "recordsToSave",
                        "type": "codeVoice"
                      },
                      {
                        "text": " as its keys. The value of each key is a ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/Swift/Result",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " that contains either the corresponding modified record (as it appears on the server), or an error that describes why CloudKit can’t modify that record.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "saveResults",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A dictionary of deleted records. The dictionary uses the identifiers you specify in ",
                        "type": "text"
                      },
                      {
                        "code": "recordIDsToDelete",
                        "type": "codeVoice"
                      },
                      {
                        "text": " as its keys. The value of each key is a ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/Swift/Result",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " that contains either ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/Swift/Void",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to indicate a successful deletion, or an error that describes why CloudKit can’t delete that record.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "deleteResults",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Deleting records may cause additional deletions if other records in the database reference the deleted records. CloudKit doesn’t provide the identifiers of any additional records it deletes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information on a more configurable way to modify records, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase": {
      "abstract": [
        {
          "text": "An object that represents a collection of record zones and subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKDatabase"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKDatabase"
        }
      ],
      "role": "symbol",
      "title": "CKDatabase",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/delete(withRecordID:completionHandler:)": {
      "abstract": [
        {
          "text": "Deletes a specific record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delete"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withRecordID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/delete(withRecordID:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteRecordWithID:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "delete(withRecordID:completionHandler:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase/delete(withrecordid:completionhandler:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/modifyRecords(saving:deleting:savePolicy:atomically:)": {
      "abstract": [
        {
          "text": "Modifies the specified records and returns the results to an awaiting caller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modifyRecords"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "saving"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "deleting"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "savePolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKModifyRecordsOperation",
          "text": "CKModifyRecordsOperation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKRecordSavePolicy",
          "text": "RecordSavePolicy"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "atomically"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> (saveResults"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">], deleteResults"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">])"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/modifyRecords(saving:deleting:savePolicy:atomically:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "modifyRecords(saving:deleting:savePolicy:atomically:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase/modifyrecords(saving:deleting:savepolicy:atomically:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/modifyRecords(saving:deleting:savePolicy:atomically:completionHandler:)": {
      "abstract": [
        {
          "text": "Modifies the specified records and delivers the results to a completion hander.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modifyRecords"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "saving"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "deleting"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "savePolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKModifyRecordsOperation",
          "text": "CKModifyRecordsOperation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKRecordSavePolicy",
          "text": "RecordSavePolicy"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "atomically"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<(saveResults"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">], deleteResults"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">]), any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/modifyRecords(saving:deleting:savePolicy:atomically:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "modifyRecords(saving:deleting:savePolicy:atomically:completionHandler:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase/modifyrecords(saving:deleting:savepolicy:atomically:completionhandler:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/save(_:completionHandler:)-3tatz": {
      "abstract": [
        {
          "text": "Saves a specific record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/save(_:completionHandler:)-3tatz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveRecord:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "save(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase/save(_:completionhandler:)-3tatz"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation": {
      "abstract": [
        {
          "text": "An operation that modifies one or more records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKModifyRecordsOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKModifyRecordsOperation"
        }
      ],
      "role": "symbol",
      "title": "CKModifyRecordsOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy": {
      "abstract": [
        {
          "text": "Constants that indicate which policy to apply when saving records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RecordSavePolicy"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RecordSavePolicy"
        }
      ],
      "role": "symbol",
      "title": "CKModifyRecordsOperation.RecordSavePolicy",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation/recordsavepolicy"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord": {
      "abstract": [
        {
          "text": "A collection of key-value pairs that store your app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecord"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecord"
        }
      ],
      "role": "symbol",
      "title": "CKRecord",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/ID": {
      "abstract": [
        {
          "text": "An object that uniquely identifies a record in a database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "role": "symbol",
      "title": "CKRecord.ID",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/id"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone/Capabilities-swift.struct/atomic": {
      "abstract": [
        {
          "text": "A capability that allows atomic changes of multiple records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atomic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordZone",
          "text": "CKRecordZone"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKRecordZoneCapabilities",
          "text": "Capabilities"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone/Capabilities-swift.struct/atomic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordZoneCapabilityAtomic"
        }
      ],
      "role": "symbol",
      "title": "atomic",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordzone/capabilities-swift.struct/atomic"
    },
    "doc://com.apple.documentation/documentation/Swift/Result": {
      "abstract": [
        {
          "text": "A value that represents either a success or a failure, including an associated value in each case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Success"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Failure"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Failure"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Success"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Result",
      "kind": "symbol",
      "role": "symbol",
      "title": "Result",
      "type": "topic",
      "url": "/documentation/Swift/Result"
    },
    "doc://com.apple.documentation/documentation/Swift/Void": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Void",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s6ResultO": {
      "abstract": [
        {
          "text": "A value that represents either a success or a failure, including an associated value in each case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Success"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Failure"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Failure"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Success"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6ResultO",
      "kind": "symbol",
      "role": "symbol",
      "title": "Result",
      "type": "topic",
      "url": "/documentation/Swift/Result"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Modifying-Records",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/modifyRecords(saving:deleting:savePolicy:atomically:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/save(_:completionHandler:)-3tatz",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/delete(withRecordID:completionHandler:)"
      ],
      "title": "Modifying Records"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1ID/title",
          "value": "CKRecordID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1ID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy/title",
          "value": "CKRecordSavePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordSavePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordSavePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation/title",
          "value": "CKModifyRecordsOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKModifyRecordsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKModifyRecordsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase/title",
          "value": "CKDatabase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase~1delete(withRecordID:completionHandler:)/title",
          "value": "deleteRecordWithID:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase~1delete(withRecordID:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deleteRecordWithID:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase~1save(_:completionHandler:)-3tatz/title",
          "value": "saveRecord:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase~1save(_:completionHandler:)-3tatz/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveRecord:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/title",
          "value": "CKRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZone~1Capabilities-swift.struct~1atomic/title",
          "value": "CKRecordZoneCapabilityAtomic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZone~1Capabilities-swift.struct~1atomic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordZoneCapabilityAtomic"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckdatabase/modifyrecords(saving:deleting:savepolicy:atomically:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
