{
  "abstract": [
    {
      "text": "A mode in which a person can only select one option in the control at a time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum/selectOne"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSPickerTouchBarItemSelectionMode@NSPickerTouchBarItemSelectionModeSelectOne",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "selectOne"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPickerTouchBarItemSelectionModeSelectOne"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSPickerTouchBarItem.SelectionMode.selectOne"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "selectOne"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a picker control with multiple options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify selection modes for picker bar items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SelectionMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SelectionMode"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.SelectionMode",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/selectionmode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum/momentary": {
      "abstract": [
        {
          "text": "A mode in which an option is only selected while a person is interacting within the bounds of that option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentary"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum/momentary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItemSelectionModeMomentary"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.SelectionMode.momentary",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/selectionmode-swift.enum/momentary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum/selectAny": {
      "abstract": [
        {
          "text": "A mode in which a person can select one or more options in the control at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectAny"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum/selectAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItemSelectionModeSelectAny"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.SelectionMode.selectAny",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/selectionmode-swift.enum/selectany"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum/selectOne": {
      "abstract": [
        {
          "text": "A mode in which a person can only select one option in the control at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectOne"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum/selectOne",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItemSelectionModeSelectOne"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.SelectionMode.selectOne",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/selectionmode-swift.enum/selectone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selection-modes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum/selectAny",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum/momentary"
      ],
      "title": "Selection modes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPickerTouchBarItemSelectionModeSelectOne"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemSelectionModeSelectOne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selection-modes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum/selectAny",
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum/momentary"
              ],
              "title": "Selection modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSPickerTouchBarItemSelectionModeSelectOne"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum~1selectOne/title",
          "value": "NSPickerTouchBarItemSelectionModeSelectOne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum~1selectOne/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemSelectionModeSelectOne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum~1momentary/title",
          "value": "NSPickerTouchBarItemSelectionModeMomentary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum~1momentary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemSelectionModeMomentary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum~1selectAny/title",
          "value": "NSPickerTouchBarItemSelectionModeSelectAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum~1selectAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemSelectionModeSelectAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum/title",
          "value": "NSPickerTouchBarItemSelectionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemSelectionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemSelectionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/title",
          "value": "NSPickerTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspickertouchbaritem/selectionmode-swift.enum/selectone"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nspickertouchbaritem/selectionmode-swift.enum/selectone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
