{
  "abstract": [
    {
      "text": "The common name for the counter set that contains hardware utilization measurements from various render stages.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/stageUtilization"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Metal",
    "externalID": "c:@MTLCommonCounterSetStageUtilization",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "stageUtilization"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MTLCommonCounterSet",
        "text": "MTLCommonCounterSet"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLCommonCounterSetStageUtilization"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "stageUtilization"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "stageUtilization"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MTLCommonCounterSet",
              "text": "MTLCommonCounterSet"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/converting-a-gpus-counter-data-into-a-readable-format"
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The stage utilization counter set contains the following counters:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/totalCycles",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/vertexCycles",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentCycles",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/tessellationCycles",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/postTessellationVertexCycles",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/renderTargetWriteCycles",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Use this name to check whether a GPU device supports the corresponding counter set (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/confirming-which-counters-and-counter-sets-a-gpu-supports",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of cycles the GPU uses to run fragment shaders during a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fragmentCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterFragmentCycles"
        }
      ],
      "role": "symbol",
      "title": "fragmentCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/fragmentcycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/postTessellationVertexCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of cycles the GPU uses to run post-tessellation vertex shaders during a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postTessellationVertexCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/postTessellationVertexCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterPostTessellationVertexCycles"
        }
      ],
      "role": "symbol",
      "title": "postTessellationVertexCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/posttessellationvertexcycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/renderTargetWriteCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of cycles the GPU uses to write data to render targets during a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderTargetWriteCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/renderTargetWriteCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterRenderTargetWriteCycles"
        }
      ],
      "role": "symbol",
      "title": "renderTargetWriteCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/rendertargetwritecycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/tessellationCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of cycles the GPU uses to run the tessellation stage during a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/tessellationCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterTessellationCycles"
        }
      ],
      "role": "symbol",
      "title": "tessellationCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/tessellationcycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/totalCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the total number of cycles the GPU uses to run a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/totalCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterTotalCycles"
        }
      ],
      "role": "symbol",
      "title": "totalCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/totalcycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/vertexCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of cycles the GPU uses to run vertex shaders during a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/vertexCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterVertexCycles"
        }
      ],
      "role": "symbol",
      "title": "vertexCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/vertexcycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet": {
      "abstract": [
        {
          "text": "The name of a specific counter set that a GPU device can support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommonCounterSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterSet"
        }
      ],
      "role": "symbol",
      "title": "MTLCommonCounterSet",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounterset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/stageUtilization": {
      "abstract": [
        {
          "text": "The common name for the counter set that contains hardware utilization measurements from various render stages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stageUtilization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounterSet",
          "text": "MTLCommonCounterSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/stageUtilization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterSetStageUtilization"
        }
      ],
      "role": "symbol",
      "title": "stageUtilization",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounterset/stageutilization"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/statistic": {
      "abstract": [
        {
          "text": "The common name for the counter set that contains GPU workload statistics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statistic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounterSet",
          "text": "MTLCommonCounterSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/statistic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterSetStatistic"
        }
      ],
      "role": "symbol",
      "title": "statistic",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounterset/statistic"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/timestamp": {
      "abstract": [
        {
          "text": "The common name for the counter set that contains the timestamp counter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounterSet",
          "text": "MTLCommonCounterSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/timestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterSetTimestamp"
        }
      ],
      "role": "symbol",
      "title": "timestamp",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounterset/timestamp"
    },
    "doc://com.apple.metal/documentation/Metal/confirming-which-counters-and-counter-sets-a-gpu-supports": {
      "abstract": [
        {
          "text": "Check whether a GPU produces the runtime performance data you want to sample.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/confirming-which-counters-and-counter-sets-a-gpu-supports",
      "kind": "article",
      "role": "article",
      "title": "Confirming which Counters and Counter Sets a GPU Supports",
      "type": "topic",
      "url": "/documentation/metal/confirming-which-counters-and-counter-sets-a-gpu-supports"
    },
    "doc://com.apple.metal/documentation/Metal/converting-a-gpus-counter-data-into-a-readable-format": {
      "abstract": [
        {
          "text": "Inspect and use the data within a GPU’s counter sample buffer by resolving it into a standard format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/converting-a-gpus-counter-data-into-a-readable-format",
      "kind": "article",
      "role": "article",
      "title": "Converting a GPU’s Counter Data into a Readable Format",
      "type": "topic",
      "url": "/documentation/metal/converting-a-gpus-counter-data-into-a-readable-format"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common-Counter-Set-Names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/timestamp",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/statistic"
      ],
      "title": "Common Counter Set Names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLCommonCounterSetStageUtilization"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterSetStageUtilization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common-Counter-Set-Names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/timestamp",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/statistic"
              ],
              "title": "Common Counter Set Names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MTLCommonCounterSet",
                    "text": "MTLCommonCounterSet"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLCommonCounterSetStageUtilization"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1renderTargetWriteCycles/title",
          "value": "MTLCommonCounterRenderTargetWriteCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1renderTargetWriteCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterRenderTargetWriteCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1tessellationCycles/title",
          "value": "MTLCommonCounterTessellationCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1tessellationCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterTessellationCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounterSet~1statistic/title",
          "value": "MTLCommonCounterSetStatistic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounterSet~1statistic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterSetStatistic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounterSet/title",
          "value": "MTLCommonCounterSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounterSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounterSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1postTessellationVertexCycles/title",
          "value": "MTLCommonCounterPostTessellationVertexCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1postTessellationVertexCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterPostTessellationVertexCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1fragmentCycles/title",
          "value": "MTLCommonCounterFragmentCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1fragmentCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterFragmentCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1totalCycles/title",
          "value": "MTLCommonCounterTotalCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1totalCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterTotalCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounterSet~1stageUtilization/title",
          "value": "MTLCommonCounterSetStageUtilization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounterSet~1stageUtilization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterSetStageUtilization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounterSet~1timestamp/title",
          "value": "MTLCommonCounterSetTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounterSet~1timestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterSetTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1vertexCycles/title",
          "value": "MTLCommonCounterVertexCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1vertexCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterVertexCycles"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcommoncounterset/stageutilization"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcommoncounterset/stageutilization"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
