{
  "abstract": [
    {
      "text": "Instantiates a new session object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession/session"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKExtendedRuntimeSession(cm)session",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "session"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "session"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "session"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKExtendedRuntimeSession",
              "text": "WKExtendedRuntimeSession"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system sets the session’s type based on the Session Type setting in your WatchKit Extension’s Background Modes capability. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/using-extended-runtime-sessions#Set-Up-the-Session",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession": {
      "abstract": [
        {
          "text": "A session that continues to run your app after the user has stopped interacting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSession"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSession"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSession",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesession"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession/delegate": {
      "abstract": [
        {
          "text": "A delegate object for monitoring the session and responding to state changes and errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKExtendedRuntimeSessionDelegate",
          "text": "WKExtendedRuntimeSessionDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesession/delegate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession/session": {
      "abstract": [
        {
          "text": "Instantiates a new session object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "session"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession/session",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session"
        }
      ],
      "role": "symbol",
      "title": "session",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesession/session"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods for monitoring an extended runtime session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionDelegate"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionDelegate",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessiondelegate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/using-extended-runtime-sessions#Set-Up-the-Session": {
      "abstract": [],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/using-extended-runtime-sessions#Set-Up-the-Session",
      "kind": "section",
      "title": "Set Up the Session",
      "type": "topic",
      "url": "/documentation/watchkit/using-extended-runtime-sessions#Set-Up-the-Session"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Session",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession/delegate",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionDelegate"
      ],
      "title": "Creating a Session"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSession~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSession~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSession/title",
          "value": "WKExtendedRuntimeSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionDelegate/title",
          "value": "WKExtendedRuntimeSessionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkextendedruntimesession/session"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
