{
  "abstract": [
    {
      "text": "Incorporates the dropped data into your data structures and updates the table.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDropDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropDelegate/tableView(_:performDropWith:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITableViewDropDelegate(im)tableView:performDropWithCoordinator:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tableView"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UITableView",
        "text": "UITableView"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "performDropWith"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)UITableViewDropCoordinator",
        "text": "UITableViewDropCoordinator"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "tableView:performDropWithCoordinator:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "tableView(_:performDropWith:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tableView"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tableView"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITableView",
              "text": "UITableView"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "performDropWith"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "coordinator"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UITableViewDropCoordinator",
              "text": "UITableViewDropCoordinator"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The table view that received the drop.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tableView"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The coordinator object to use when handling the drop. Use this object to coordinate your custom behavior with the default behavior of the table view.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "coordinator"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-table-views"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to integrate the dropped content into your table view. In your implementation, iterate over the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator/items",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the ",
              "type": "text"
            },
            {
              "code": "coordinator",
              "type": "codeVoice"
            },
            {
              "text": " object to retrieve the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects associated with the drag operation. Use the data in those objects to update your table view’s data source and the table view itself.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "How you update the table view depends on the source of the dragged items and whether you need to load the data asynchronously.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Insert placeholder rows for any data that you must load asynchronously.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Use the ",
                      "type": "text"
                    },
                    {
                      "code": "drop(_:toPlaceholderInsertedAt:withReuseIdentifier:rowHeight:cellUpdateHandler:)",
                      "type": "codeVoice"
                    },
                    {
                      "text": " method to insert a placeholder cell into the table while you wait for the data to load.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Use the existing table view methods to rearrange rows within the table.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " When the drag source contains rows from the same table, use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/moveRow(at:to:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method to rearrange the rows.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Insert local data directly into the table.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " When the drag item’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragItem/localObject",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property contains a value, use that value to update the table view directly. Specifically, update your data source object and insert any needed rows into the table.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When updating your table directly, use the coordinator object to animate the dropping of the items. For example, you might use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator/drop(_:toRowAt:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to animate the insertion of the dropped item at the specified location. The insertion of placeholders automatically creates appropriate animations. For more information about the types of animations that you can perform, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragItem": {
      "abstract": [
        {
          "text": "A representation of an underlying data item as a person drags it from one location to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDragItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDragItem"
        }
      ],
      "role": "symbol",
      "title": "UIDragItem",
      "type": "topic",
      "url": "/documentation/uikit/uidragitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragItem/localObject": {
      "abstract": [
        {
          "text": "A custom object associated with the drag item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragItem/localObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localObject"
        }
      ],
      "role": "symbol",
      "title": "localObject",
      "type": "topic",
      "url": "/documentation/uikit/uidragitem/localobject"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView": {
      "abstract": [
        {
          "text": "A view that presents data using rows in a single column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "role": "symbol",
      "title": "UITableView",
      "type": "topic",
      "url": "/documentation/uikit/uitableview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/moveRow(at:to:)": {
      "abstract": [
        {
          "text": "Moves the row at a specified location to a destination location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/moveRow(at:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveRowAtIndexPath:toIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "moveRow(at:to:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/moverow(at:to:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator": {
      "abstract": [
        {
          "text": "An interface for coordinating your custom drop-related actions with the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewDropCoordinator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewDropCoordinator"
        }
      ],
      "role": "symbol",
      "title": "UITableViewDropCoordinator",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropcoordinator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator/drop(_:toRowAt:)": {
      "abstract": [
        {
          "text": "Animates the item to the specified index path in the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toRowAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragAnimating",
          "text": "UIDragAnimating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator/drop(_:toRowAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropItem:toRowAtIndexPath:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "drop(_:toRowAt:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropcoordinator/drop(_:torowat:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator/items": {
      "abstract": [
        {
          "text": "The items being dragged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "items"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITableViewDropItem",
          "text": "UITableViewDropItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator/items",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "items"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "items",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropcoordinator/items"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropDelegate": {
      "abstract": [
        {
          "text": "The interface for handling drops in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewDropDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewDropDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITableViewDropDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropDelegate/tableView(_:performDropWith:)": {
      "abstract": [
        {
          "text": "Incorporates the dropped data into your data structures and updates the table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableView",
          "text": "UITableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "performDropWith"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITableViewDropCoordinator",
          "text": "UITableViewDropCoordinator"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropDelegate/tableView(_:performDropWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:performDropWithCoordinator:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "tableView(_:performDropWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropdelegate/tableview(_:performdropwith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-table-views": {
      "abstract": [
        {
          "text": "Initiate drags and handle drops from a table view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-table-views",
      "kind": "article",
      "role": "article",
      "title": "Supporting drag and drop in table views",
      "type": "topic",
      "url": "/documentation/uikit/supporting-drag-and-drop-in-table-views"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "tableView:performDropWithCoordinator:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:performDropWithCoordinator:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDropDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "tableView:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UITableView",
                    "text": "UITableView"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "tableView"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "performDropWithCoordinator:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)UITableViewDropCoordinator",
                    "text": "id<UITableViewDropCoordinator>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "coordinator"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The table view that received the drop.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "tableView"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The coordinator object to use when handling the drop. Use this object to coordinate your custom behavior with the default behavior of the table view.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "coordinator"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1moveRow(at:to:)/title",
          "value": "moveRowAtIndexPath:toIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1moveRow(at:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "moveRowAtIndexPath:toIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropDelegate~1tableView(_:performDropWith:)/title",
          "value": "tableView:performDropWithCoordinator:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropDelegate~1tableView(_:performDropWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:performDropWithCoordinator:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropDelegate/title",
          "value": "UITableViewDropDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator/title",
          "value": "UITableViewDropCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/title",
          "value": "UITableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem~1localObject/title",
          "value": "localObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem~1localObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem/title",
          "value": "UIDragItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator~1items/title",
          "value": "items"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator~1items/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator~1drop(_:toRowAt:)/title",
          "value": "dropItem:toRowAtIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator~1drop(_:toRowAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropItem:toRowAtIndexPath:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitableviewdropdelegate/tableview(_:performdropwith:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitableviewdropdelegate/tableview(_:performdropwith:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
