{
  "abstract": [
    {
      "text": "An error that indicates the photo library isn’t available because the file system volume that stores it isn’t mounted.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/libraryVolumeOffline"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHPhotosError@PHPhotosErrorLibraryVolumeOffline",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "libraryVolumeOffline"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHPhotosErrorLibraryVolumeOffline"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHPhotosError.Code.libraryVolumeOffline"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "libraryVolumeOffline"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPhotosError"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosError"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for framework operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/accessRestricted": {
      "abstract": [
        {
          "text": "An error that indicates the system configuration restricts access to the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessRestricted"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/accessRestricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorAccessRestricted"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.accessRestricted",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/accessrestricted"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/accessUserDenied": {
      "abstract": [
        {
          "text": "An error that indicates the user denies access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessUserDenied"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/accessUserDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorAccessUserDenied"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.accessUserDenied",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/accessuserdenied"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/changeNotSupported": {
      "abstract": [
        {
          "text": "An error that indicates the system doesn’t support the change request configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeNotSupported"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/changeNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorChangeNotSupported"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.changeNotSupported",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/changenotsupported"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/identifierNotFound": {
      "abstract": [
        {
          "text": "An error that indicates an identifier doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifierNotFound"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/identifierNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorIdentifierNotFound"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.identifierNotFound",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/identifiernotfound"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/internalError": {
      "abstract": [
        {
          "text": "An error that indicates an internal error occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorInternalError"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.internalError",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/internalerror"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/invalidResource": {
      "abstract": [
        {
          "text": "An error that indicates the asset resource validation fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidResource"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/invalidResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorInvalidResource"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.invalidResource",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/invalidresource"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/libraryInFileProviderSyncRoot": {
      "abstract": [
        {
          "text": "An error that indicates the Photos library bundle is in a file provider sync directory, and the framework doesn’t support it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "libraryInFileProviderSyncRoot"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/libraryInFileProviderSyncRoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorLibraryInFileProviderSyncRoot"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.libraryInFileProviderSyncRoot",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/libraryinfileprovidersyncroot"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/libraryVolumeOffline": {
      "abstract": [
        {
          "text": "An error that indicates the photo library isn’t available because the file system volume that stores it isn’t mounted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "libraryVolumeOffline"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/libraryVolumeOffline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorLibraryVolumeOffline"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.libraryVolumeOffline",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/libraryvolumeoffline"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/missingResource": {
      "abstract": [
        {
          "text": "An error that indicates a missing asset resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingResource"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/missingResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorMissingResource"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.missingResource",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/missingresource"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/multipleIdentifiersFound": {
      "abstract": [
        {
          "text": "An error that indicates that more than one identifier exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multipleIdentifiersFound"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/multipleIdentifiersFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorMultipleIdentifiersFound"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.multipleIdentifiersFound",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/multipleidentifiersfound"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/networkAccessRequired": {
      "abstract": [
        {
          "text": "An error that indicates the request for an asset resource fails because it requires network access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkAccessRequired"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/networkAccessRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorNetworkAccessRequired"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.networkAccessRequired",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/networkaccessrequired"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/networkError": {
      "abstract": [
        {
          "text": "An error that indicates the request for an asset resource fails because of a network connection error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkError"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/networkError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorNetworkError"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.networkError",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/networkerror"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/notEnoughSpace": {
      "abstract": [
        {
          "text": "An error that indicates there’s not enough space to perform the requested change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEnoughSpace"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/notEnoughSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorNotEnoughSpace"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.notEnoughSpace",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/notenoughspace"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/operationInterrupted": {
      "abstract": [
        {
          "text": "An error that indicates an interruption occurs and the operation can’t complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationInterrupted"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/operationInterrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorOperationInterrupted"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.operationInterrupted",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/operationinterrupted"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/persistentChangeDetailsUnavailable": {
      "abstract": [
        {
          "text": "An error that indicates the change details aren’t available for the persistent change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistentChangeDetailsUnavailable"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/persistentChangeDetailsUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorPersistentChangeDetailsUnavailable"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.persistentChangeDetailsUnavailable",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/persistentchangedetailsunavailable"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/persistentChangeTokenExpired": {
      "abstract": [
        {
          "text": "An error that indicates the library state is older than the available history of persistent changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistentChangeTokenExpired"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/persistentChangeTokenExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorPersistentChangeTokenExpired"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code.persistentChangeTokenExpired",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code/persistentchangetokenexpired"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/accessRestricted",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/accessUserDenied",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/changeNotSupported",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/identifierNotFound",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/internalError",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/invalidResource",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/libraryInFileProviderSyncRoot",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/missingResource",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/multipleIdentifiersFound",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/networkAccessRequired",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/networkError",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/notEnoughSpace",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/operationInterrupted",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/persistentChangeDetailsUnavailable",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/persistentChangeTokenExpired"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHPhotosErrorLibraryVolumeOffline"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorLibraryVolumeOffline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/accessRestricted",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/accessUserDenied",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/changeNotSupported",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/identifierNotFound",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/internalError",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/invalidResource",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/libraryInFileProviderSyncRoot",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/missingResource",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/multipleIdentifiersFound",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/networkAccessRequired",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/networkError",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/notEnoughSpace",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/operationInterrupted",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/persistentChangeDetailsUnavailable",
                "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code/persistentChangeTokenExpired"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHPhotosErrorLibraryVolumeOffline"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1multipleIdentifiersFound/title",
          "value": "PHPhotosErrorMultipleIdentifiersFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1multipleIdentifiersFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorMultipleIdentifiersFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1libraryInFileProviderSyncRoot/title",
          "value": "PHPhotosErrorLibraryInFileProviderSyncRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1libraryInFileProviderSyncRoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorLibraryInFileProviderSyncRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1networkAccessRequired/title",
          "value": "PHPhotosErrorNetworkAccessRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1networkAccessRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorNetworkAccessRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1accessRestricted/title",
          "value": "PHPhotosErrorAccessRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1accessRestricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorAccessRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1changeNotSupported/title",
          "value": "PHPhotosErrorChangeNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1changeNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorChangeNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1persistentChangeTokenExpired/title",
          "value": "PHPhotosErrorPersistentChangeTokenExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1persistentChangeTokenExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorPersistentChangeTokenExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1libraryVolumeOffline/title",
          "value": "PHPhotosErrorLibraryVolumeOffline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1libraryVolumeOffline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorLibraryVolumeOffline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1networkError/title",
          "value": "PHPhotosErrorNetworkError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1networkError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorNetworkError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1operationInterrupted/title",
          "value": "PHPhotosErrorOperationInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1operationInterrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorOperationInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1internalError/title",
          "value": "PHPhotosErrorInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1notEnoughSpace/title",
          "value": "PHPhotosErrorNotEnoughSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1notEnoughSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorNotEnoughSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1missingResource/title",
          "value": "PHPhotosErrorMissingResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1missingResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorMissingResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1accessUserDenied/title",
          "value": "PHPhotosErrorAccessUserDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1accessUserDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorAccessUserDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1identifierNotFound/title",
          "value": "PHPhotosErrorIdentifierNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1identifierNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorIdentifierNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1persistentChangeDetailsUnavailable/title",
          "value": "PHPhotosErrorPersistentChangeDetailsUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1persistentChangeDetailsUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorPersistentChangeDetailsUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1invalidResource/title",
          "value": "PHPhotosErrorInvalidResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code~1invalidResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorInvalidResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code/title",
          "value": "PHPhotosError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phphotoserror-swift.struct/code/libraryvolumeoffline"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phphotoserror-swift.struct/code/libraryvolumeoffline"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
