{
  "abstract": [
    {
      "text": "The size of your messages view, given the provided maximum size.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messages/documentation/Messages",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation/contentSizeThatFits(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MSMessagesAppTranscriptPresentation(im)contentSizeThatFits:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "contentSizeThatFits"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGSize",
        "text": "CGSize"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGSize",
        "text": "CGSize"
      }
    ],
    "modules": [
      {
        "name": "Messages"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "contentSizeThatFits:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "contentSizeThatFits(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "contentSizeThatFits"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "size"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGSize",
              "text": "CGSize"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGSize",
              "text": "CGSize"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The maximum available size, in points.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "size"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system calls this method only when the Messages app needs to update the view’s size and the view controller is presenting a live view in the transcript or input field (the view controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/presentationStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is set to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle/transcript",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value). Typically, the view’s size needs updating when the live message is added to the transcript, when the transcript’s width changes, or when the locale or dynamic type size changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class’s default implementation of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation/contentSizeThatFits(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method simply returns the ",
              "type": "text"
            },
            {
              "code": "size",
              "type": "codeVoice"
            },
            {
              "text": " parameter. Override this method to return an appropriate size for your live message view that fits within the provided size. The returned value must be equal to or smaller than the ",
              "type": "text"
            },
            {
              "code": "size",
              "type": "codeVoice"
            },
            {
              "text": " parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messages/documentation/Messages": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/messages"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle/transcript": {
      "abstract": [
        {
          "text": "The iMessage app is displayed in the Messages app’s transcript or input field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transcript"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle/transcript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationStyleTranscript"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppPresentationStyle.transcript",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapppresentationstyle/transcript"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation": {
      "abstract": [
        {
          "text": "A protocol that provides support for displaying live messages in the transcript of the Messages app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesAppTranscriptPresentation"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppTranscriptPresentation"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppTranscriptPresentation",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapptranscriptpresentation"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation/contentSizeThatFits(_:)": {
      "abstract": [
        {
          "text": "The size of your messages view, given the provided maximum size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentSizeThatFits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation/contentSizeThatFits(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentSizeThatFits:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "contentSizeThatFits(_:)",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapptranscriptpresentation/contentsizethatfits(_:)"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController": {
      "abstract": [
        {
          "text": "The principal view controller for iMessage apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesAppViewController"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppViewController"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppViewController",
      "type": "topic",
      "url": "/documentation/messages/msmessagesappviewcontroller"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/presentationStyle": {
      "abstract": [
        {
          "text": "The extension’s current presentation style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MSMessagesAppPresentationStyle",
          "text": "MSMessagesAppPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController/presentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationStyle"
        }
      ],
      "role": "symbol",
      "title": "presentationStyle",
      "type": "topic",
      "url": "/documentation/messages/msmessagesappviewcontroller/presentationstyle"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGSize": {
      "abstract": [
        {
          "text": "A structure that contains width and height values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGSize",
      "type": "topic",
      "url": "/documentation/corefoundation/cgsize"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "contentSizeThatFits:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentSizeThatFits:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.messages/documentation/Messages",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGSize",
                    "text": "CGSize"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "contentSizeThatFits:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGSize",
                    "text": "CGSize"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "size"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The maximum available size, in points.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "size"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation~1contentSizeThatFits(_:)/title",
          "value": "contentSizeThatFits:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation~1contentSizeThatFits(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentSizeThatFits:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1presentationStyle/title",
          "value": "presentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController~1presentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation/title",
          "value": "MSMessagesAppTranscriptPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppTranscriptPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppTranscriptPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/title",
          "value": "MSMessagesAppViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle~1transcript/title",
          "value": "MSMessagesAppPresentationStyleTranscript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle~1transcript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationStyleTranscript"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messages/msmessagesapptranscriptpresentation/contentsizethatfits(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messages/msmessagesapptranscriptpresentation/contentsizethatfits(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
