{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/corenfc-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CoreNFC Enumerations"
  },
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaEncryptionId": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaEncryptionId"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaEncryptionId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaEncryptionId"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaEncryptionId",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicaencryptionid"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingRequestCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingRequestCode"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaPollingRequestCode",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicapollingrequestcode"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingTimeSlot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingTimeSlot"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingTimeSlot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingTimeSlot"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaPollingTimeSlot",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicapollingtimeslot"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693RequestFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO15693RequestFlag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693RequestFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO15693RequestFlag"
        }
      ],
      "role": "symbol",
      "title": "NFCISO15693RequestFlag",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693requestflag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ResponseFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO15693ResponseFlag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ResponseFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO15693ResponseFlag"
        }
      ],
      "role": "symbol",
      "title": "NFCISO15693ResponseFlag",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693responseflag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Mode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Mode"
        }
      ],
      "role": "symbol",
      "title": "NFCVASCommandConfiguration.Mode",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvascommandconfiguration/mode-swift.enum"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse.ErrorCode",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaEncryptionId",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingTimeSlot",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693RequestFlag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ResponseFlag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaEncryptionId",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingTimeSlot",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693RequestFlag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ResponseFlag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693ResponseFlag/title",
          "value": "NFCISO15693ResponseFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693ResponseFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693ResponseFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693ResponseFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693ResponseFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode/title",
          "value": "NFCFeliCaPollingRequestCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaPollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaPollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/title",
          "value": "NFCVASMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode/title",
          "value": "NFCVASErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693RequestFlag/title",
          "value": "NFCISO15693RequestFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693RequestFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693RequestFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693RequestFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693RequestFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaEncryptionId/title",
          "value": "NFCFeliCaEncryptionId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaEncryptionId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaEncryptionId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaEncryptionId/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaEncryptionId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingTimeSlot/title",
          "value": "NFCFeliCaPollingTimeSlot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingTimeSlot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaPollingTimeSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingTimeSlot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaPollingTimeSlot"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/corenfc-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/corenfc-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
