{
  "abstract": [
    {
      "text": "An interface for interacting with a FeliCa™ tag.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NFCFeliCaTag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NFCFeliCaTag"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCFeliCaTag"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NFCFeliCaTag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NFCFeliCaTag"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NFCNDEFTag",
              "text": "NFCNDEFTag"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "text": "__NFCTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "FeliCa is a trademark of Sony Corporation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/EncryptionId": {
      "abstract": [
        {
          "text": "Encryption identifiers indicating the type of encryption algorithm used in the response of a Request Service V2 command.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EncryptionId"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/EncryptionId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EncryptionId"
        }
      ],
      "role": "symbol",
      "title": "EncryptionId",
      "type": "topic",
      "url": "/documentation/corenfc/encryptionid"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag": {
      "abstract": [
        {
          "text": "An interface for interacting with a FeliCa™ tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaTag"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/currentIDm": {
      "abstract": [
        {
          "text": "The manufacturer identifier for the system currently selected by the reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentIDm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/currentIDm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentIDm"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "currentIDm",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/currentidm"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/currentSystemCode": {
      "abstract": [
        {
          "text": "The system code most recently selected by the reader session during a polling sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSystemCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/currentSystemCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSystemCode"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "currentSystemCode",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/currentsystemcode"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/polling(systemCode:requestCode:timeSlot:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the Polling command as defined by FeliCa card specification to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "polling"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "systemCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "requestCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCFeliCaPollingRequestCode",
          "text": "NFCFeliCaPollingRequestCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeSlot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCFeliCaPollingTimeSlot",
          "text": "NFCFeliCaPollingTimeSlot"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/polling(systemCode:requestCode:timeSlot:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pollingWithSystemCode:requestCode:timeSlot:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "polling(systemCode:requestCode:timeSlot:completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/polling(systemcode:requestcode:timeslot:completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/polling(systemCode:requestCode:timeSlot:resultHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "polling"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "systemCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "requestCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCFeliCaPollingRequestCode",
          "text": "NFCFeliCaPollingRequestCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeSlot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCFeliCaPollingTimeSlot",
          "text": "NFCFeliCaPollingTimeSlot"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7CoreNFC24NFCFeliCaPollingResponseV",
          "text": "NFCFeliCaPollingResponse"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/polling(systemCode:requestCode:timeSlot:resultHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "polling(systemCode:requestCode:timeSlot:resultHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/polling(systemcode:requestcode:timeslot:resulthandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/readWithoutEncryption(serviceCodeList:blockList:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the Read Without Encryption command, as defined by the FeliCa card specification, to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readWithoutEncryption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "serviceCodeList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "blockList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/readWithoutEncryption(serviceCodeList:blockList:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readWithoutEncryptionWithServiceCodeList:blockList:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "readWithoutEncryption(serviceCodeList:blockList:completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/readwithoutencryption(servicecodelist:blocklist:completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/readWithoutEncryption(serviceCodeList:blockList:resultHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readWithoutEncryption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "serviceCodeList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "blockList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7CoreNFC19NFCFeliCaStatusFlagV",
          "text": "NFCFeliCaStatusFlag"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "]), any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/readWithoutEncryption(serviceCodeList:blockList:resultHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "readWithoutEncryption(serviceCodeList:blockList:resultHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/readwithoutencryption(servicecodelist:blocklist:resulthandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestResponse(completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the Request Response command, as defined by the FeliCa card specification, to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestResponse"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestResponse(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestResponseWithCompletionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "requestResponse(completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/requestresponse(completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestResponse(resultHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestResponse"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestResponse(resultHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestResponse(resultHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/requestresponse(resulthandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestService(nodeCodeList:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the Request Service command, as defined by the FeliCa card specification, to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestService"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "nodeCodeList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestService(nodeCodeList:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestServiceWithNodeCodeList:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "requestService(nodeCodeList:completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/requestservice(nodecodelist:completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestService(nodeCodeList:resultHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestService"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "nodeCodeList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestService(nodeCodeList:resultHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestService(nodeCodeList:resultHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/requestservice(nodecodelist:resulthandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestServiceV2(nodeCodeList:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the Request Service V2 command, as defined by the FeliCa card specification, to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestServiceV2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "nodeCodeList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCFeliCaEncryptionId",
          "text": "NFCFeliCaEncryptionId"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestServiceV2(nodeCodeList:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestServiceV2WithNodeCodeList:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "requestServiceV2(nodeCodeList:completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/requestservicev2(nodecodelist:completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestServiceV2(nodeCodeList:resultHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestServiceV2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "nodeCodeList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7CoreNFC33NFCFeliCaRequsetServiceV2ResponseV",
          "text": "NFCFeliCaRequsetServiceV2Response"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestServiceV2(nodeCodeList:resultHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestServiceV2(nodeCodeList:resultHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/requestservicev2(nodecodelist:resulthandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSpecificationVersion(completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the Request Specification Version command, as defined by the FeliCa card specification, to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestSpecificationVersion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSpecificationVersion(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestSpecificationVersionWithCompletionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "requestSpecificationVersion(completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/requestspecificationversion(completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSpecificationVersion(resultHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestSpecificationVersion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7CoreNFC44NFCFeliCaRequestSpecificationVersionResponseV",
          "text": "NFCFeliCaRequestSpecificationVersionResponse"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSpecificationVersion(resultHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestSpecificationVersion(resultHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/requestspecificationversion(resulthandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSystemCode(completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the Request System Code command, as defined by the FeliCa card specification, to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestSystemCode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSystemCode(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestSystemCodeWithCompletionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "requestSystemCode(completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/requestsystemcode(completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSystemCode(resultHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestSystemCode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSystemCode(resultHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestSystemCode(resultHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/requestsystemcode(resulthandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/resetMode(completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the Reset Mode command, as defined by the FeliCa card specification, to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/resetMode(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resetModeWithCompletionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "resetMode(completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/resetmode(completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/resetMode(resultHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7CoreNFC19NFCFeliCaStatusFlagV",
          "text": "NFCFeliCaStatusFlag"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/resetMode(resultHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "resetMode(resultHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/resetmode(resulthandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/sendFeliCaCommand(commandPacket:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the FeliCa command packet data to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendFeliCaCommand"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "commandPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/sendFeliCaCommand(commandPacket:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendFeliCaCommandPacket:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sendFeliCaCommand(commandPacket:completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/sendfelicacommand(commandpacket:completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/sendFeliCaCommand(commandPacket:resultHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendFeliCaCommand"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "commandPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/sendFeliCaCommand(commandPacket:resultHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "sendFeliCaCommand(commandPacket:resultHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/sendfelicacommand(commandpacket:resulthandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/writeWithoutEncryption(serviceCodeList:blockList:blockData:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the Write Without Encryption command, as defined by the FeliCa card specification, to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeWithoutEncryption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "serviceCodeList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "blockList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "blockData"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/writeWithoutEncryption(serviceCodeList:blockList:blockData:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeWithoutEncryptionWithServiceCodeList:blockList:blockData:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "writeWithoutEncryption(serviceCodeList:blockList:blockData:completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/writewithoutencryption(servicecodelist:blocklist:blockdata:completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/writeWithoutEncryption(serviceCodeList:blockList:blockData:resultHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeWithoutEncryption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "serviceCodeList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "blockList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "blockData"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7CoreNFC19NFCFeliCaStatusFlagV",
          "text": "NFCFeliCaStatusFlag"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/writeWithoutEncryption(serviceCodeList:blockList:blockData:resultHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "writeWithoutEncryption(serviceCodeList:blockList:blockData:resultHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/writewithoutencryption(servicecodelist:blocklist:blockdata:resulthandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693Tag": {
      "abstract": [
        {
          "text": "An interface for interacting with an ISO 15693 tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO15693Tag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693Tag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO15693Tag"
        }
      ],
      "role": "symbol",
      "title": "NFCISO15693Tag",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693tag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag": {
      "abstract": [
        {
          "text": "An interface for interacting with an ISO 7816 tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO7816Tag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO7816Tag"
        }
      ],
      "role": "symbol",
      "title": "NFCISO7816Tag",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso7816tag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCMiFareTag": {
      "abstract": [
        {
          "text": "An interface for interacting with a MIFARE® tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCMiFareTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCMiFareTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCMiFareTag"
        }
      ],
      "role": "symbol",
      "title": "NFCMiFareTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfcmifaretag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag": {
      "abstract": [
        {
          "text": "An interface for interacting with an NDEF tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFTag"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndeftag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-c.protocol": {
      "abstract": [
        {
          "text": "An interface for interacting with an NFC or RFID tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NFCTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfctag-c.protocol"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum": {
      "abstract": [
        {
          "text": "An object that represents an NFC tag object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTag"
        }
      ],
      "role": "symbol",
      "title": "NFCTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfctag-swift.enum"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagCommandConfiguration": {
      "abstract": [
        {
          "text": "A set of parameters you use to define the configuration of an NFC tag command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTagCommandConfiguration"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagCommandConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTagCommandConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NFCTagCommandConfiguration",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagcommandconfiguration"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/PollingRequestCode": {
      "abstract": [
        {
          "text": "Codes that specify the type of the data to request when polling.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PollingRequestCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/PollingRequestCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PollingRequestCode"
        }
      ],
      "role": "symbol",
      "title": "PollingRequestCode",
      "type": "topic",
      "url": "/documentation/corenfc/pollingrequestcode"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/PollingTimeSlot": {
      "abstract": [
        {
          "text": "Constants that specify the maximum number of time slots.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PollingTimeSlot"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/PollingTimeSlot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PollingTimeSlot"
        }
      ],
      "role": "symbol",
      "title": "PollingTimeSlot",
      "type": "topic",
      "url": "/documentation/corenfc/pollingtimeslot"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/creating-nfc-tags-from-your-iphone": {
      "abstract": [
        {
          "text": "Save data to tags, and interact with them using native tag protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/creating-nfc-tags-from-your-iphone",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating NFC Tags from Your iPhone",
      "type": "topic",
      "url": "/documentation/corenfc/creating-nfc-tags-from-your-iphone"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/com.apple.developer.nfc.readersession.felica.systemcodes": {
      "abstract": [
        {
          "text": "A list of FeliCa system codes that the app supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/com.apple.developer.nfc.readersession.felica.systemcodes",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.nfc.readersession.felica.systemcodes",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/com.apple.developer.nfc.readersession.felica.systemcodes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Tag-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/creating-nfc-tags-from-your-iphone",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693Tag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCMiFareTag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagCommandConfiguration"
      ],
      "title": "Tag types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-System-Codes",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/com.apple.developer.nfc.readersession.felica.systemcodes"
      ],
      "title": "Specifying System Codes"
    },
    {
      "anchor": "Getting-Current-Information",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/currentSystemCode",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/currentIDm"
      ],
      "title": "Getting Current Information"
    },
    {
      "anchor": "Polling",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/polling(systemCode:requestCode:timeSlot:completionHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/PollingRequestCode",
        "doc://com.apple.corenfc/documentation/CoreNFC/PollingTimeSlot"
      ],
      "title": "Polling"
    },
    {
      "anchor": "Requesting-Services",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestService(nodeCodeList:completionHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestServiceV2(nodeCodeList:completionHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/EncryptionId"
      ],
      "title": "Requesting Services"
    },
    {
      "anchor": "Requesting-Responses",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestResponse(completionHandler:)"
      ],
      "title": "Requesting Responses"
    },
    {
      "anchor": "Requesting-Specification-Versions",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSpecificationVersion(completionHandler:)"
      ],
      "title": "Requesting Specification Versions"
    },
    {
      "anchor": "Requesting-System-Codes",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSystemCode(completionHandler:)"
      ],
      "title": "Requesting System Codes"
    },
    {
      "anchor": "Resetting-Modes",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/resetMode(completionHandler:)"
      ],
      "title": "Resetting Modes"
    },
    {
      "anchor": "Reading-and-Writing-Without-Encryption",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/readWithoutEncryption(serviceCodeList:blockList:completionHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/writeWithoutEncryption(serviceCodeList:blockList:blockData:completionHandler:)"
      ],
      "title": "Reading and Writing Without Encryption"
    },
    {
      "anchor": "Sending-FeliCa-Commands",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/sendFeliCaCommand(commandPacket:completionHandler:)"
      ],
      "title": "Sending FeliCa Commands"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/polling(systemCode:requestCode:timeSlot:resultHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/readWithoutEncryption(serviceCodeList:blockList:resultHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestResponse(resultHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestService(nodeCodeList:resultHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestServiceV2(nodeCodeList:resultHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSpecificationVersion(resultHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSystemCode(resultHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/resetMode(resultHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/sendFeliCaCommand(commandPacket:resultHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/writeWithoutEncryption(serviceCodeList:blockList:blockData:resultHandler:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCFeliCaTag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-System-Codes",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/com.apple.developer.nfc.readersession.felica.systemcodes"
              ],
              "title": "Specifying System Codes"
            },
            {
              "anchor": "Getting-Current-Information",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/currentSystemCode",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/currentIDm"
              ],
              "title": "Getting Current Information"
            },
            {
              "anchor": "Polling",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/polling(systemCode:requestCode:timeSlot:completionHandler:)",
                "doc://com.apple.corenfc/documentation/CoreNFC/PollingRequestCode",
                "doc://com.apple.corenfc/documentation/CoreNFC/PollingTimeSlot"
              ],
              "title": "Polling"
            },
            {
              "anchor": "Requesting-Services",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestService(nodeCodeList:completionHandler:)",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestServiceV2(nodeCodeList:completionHandler:)",
                "doc://com.apple.corenfc/documentation/CoreNFC/EncryptionId"
              ],
              "title": "Requesting Services"
            },
            {
              "anchor": "Requesting-Responses",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestResponse(completionHandler:)"
              ],
              "title": "Requesting Responses"
            },
            {
              "anchor": "Requesting-Specification-Versions",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSpecificationVersion(completionHandler:)"
              ],
              "title": "Requesting Specification Versions"
            },
            {
              "anchor": "Requesting-System-Codes",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/requestSystemCode(completionHandler:)"
              ],
              "title": "Requesting System Codes"
            },
            {
              "anchor": "Resetting-Modes",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/resetMode(completionHandler:)"
              ],
              "title": "Resetting Modes"
            },
            {
              "anchor": "Reading-and-Writing-Without-Encryption",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/readWithoutEncryption(serviceCodeList:blockList:completionHandler:)",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/writeWithoutEncryption(serviceCodeList:blockList:blockData:completionHandler:)"
              ],
              "title": "Reading and Writing Without Encryption"
            },
            {
              "anchor": "Sending-FeliCa-Commands",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/sendFeliCaCommand(commandPacket:completionHandler:)"
              ],
              "title": "Sending FeliCa Commands"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-c.protocol"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Tag-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/creating-nfc-tags-from-your-iphone",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693Tag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCMiFareTag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-c.protocol",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagCommandConfiguration"
              ],
              "title": "Tag types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NFCFeliCaTag"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-c.protocol",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NFCTag",
                    "text": "NFCTag"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NFCNDEFTag",
                    "text": "NFCNDEFTag"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1requestSystemCode(completionHandler:)/title",
          "value": "requestSystemCodeWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1requestSystemCode(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestSystemCodeWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1requestSpecificationVersion(completionHandler:)/title",
          "value": "requestSpecificationVersionWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1requestSpecificationVersion(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestSpecificationVersionWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1EncryptionId/title",
          "value": "EncryptionId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1EncryptionId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EncryptionId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1EncryptionId/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EncryptionId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1requestResponse(completionHandler:)/title",
          "value": "requestResponseWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1requestResponse(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestResponseWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1writeWithoutEncryption(serviceCodeList:blockList:blockData:completionHandler:)/title",
          "value": "writeWithoutEncryptionWithServiceCodeList:blockList:blockData:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1writeWithoutEncryption(serviceCodeList:blockList:blockData:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeWithoutEncryptionWithServiceCodeList:blockList:blockData:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1readWithoutEncryption(serviceCodeList:blockList:completionHandler:)/title",
          "value": "readWithoutEncryptionWithServiceCodeList:blockList:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1readWithoutEncryption(serviceCodeList:blockList:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readWithoutEncryptionWithServiceCodeList:blockList:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO7816Tag/title",
          "value": "NFCISO7816Tag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO7816Tag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO7816Tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO7816Tag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO7816Tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1currentIDm/title",
          "value": "currentIDm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1currentIDm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentIDm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag/title",
          "value": "NFCFeliCaTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagCommandConfiguration/title",
          "value": "NFCTagCommandConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagCommandConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagCommandConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagCommandConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagCommandConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingTimeSlot/title",
          "value": "PollingTimeSlot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingTimeSlot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingTimeSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingTimeSlot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingTimeSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1currentSystemCode/title",
          "value": "currentSystemCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1currentSystemCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSystemCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1sendFeliCaCommand(commandPacket:completionHandler:)/title",
          "value": "sendFeliCaCommandPacket:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1sendFeliCaCommand(commandPacket:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendFeliCaCommandPacket:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1requestServiceV2(nodeCodeList:completionHandler:)/title",
          "value": "requestServiceV2WithNodeCodeList:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1requestServiceV2(nodeCodeList:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestServiceV2WithNodeCodeList:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1requestService(nodeCodeList:completionHandler:)/title",
          "value": "requestServiceWithNodeCodeList:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1requestService(nodeCodeList:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestServiceWithNodeCodeList:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCMiFareTag/title",
          "value": "NFCMiFareTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCMiFareTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCMiFareTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCMiFareTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCMiFareTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag/title",
          "value": "NFCNDEFTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingRequestCode/title",
          "value": "PollingRequestCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingRequestCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingRequestCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1resetMode(completionHandler:)/title",
          "value": "resetModeWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1resetMode(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resetModeWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1polling(systemCode:requestCode:timeSlot:completionHandler:)/title",
          "value": "pollingWithSystemCode:requestCode:timeSlot:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1polling(systemCode:requestCode:timeSlot:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pollingWithSystemCode:requestCode:timeSlot:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693Tag/title",
          "value": "NFCISO15693Tag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693Tag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693Tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693Tag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693Tag"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcfelicatag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfcfelicatag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
