{
  "abstract": [
    {
      "text": "An object containing the response from the tag.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:7CoreNFC22NFCISO7816ResponseAPDUV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NFCISO7816ResponseAPDU"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCISO7816ResponseAPDU"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NFCISO7816ResponseAPDU"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NFCISO7816ResponseAPDU"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816APDU": {
      "abstract": [
        {
          "text": "An object representing an ISO 7816 application protocol data unit (APDU).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO7816APDU"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816APDU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO7816APDU"
        }
      ],
      "role": "symbol",
      "title": "NFCISO7816APDU",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso7816apdu"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU": {
      "abstract": [
        {
          "text": "An object containing the response from the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO7816ResponseAPDU"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO7816ResponseAPDU"
        }
      ],
      "role": "symbol",
      "title": "NFCISO7816ResponseAPDU",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso7816responseapdu"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU/payload": {
      "abstract": [
        {
          "text": "A data object that contains the response data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU/payload",
      "kind": "symbol",
      "role": "symbol",
      "title": "payload",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso7816responseapdu/payload"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU/statusWord1": {
      "abstract": [
        {
          "text": "The SW1 command-processing status byte.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusWord1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU/statusWord1",
      "kind": "symbol",
      "role": "symbol",
      "title": "statusWord1",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso7816responseapdu/statusword1"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU/statusWord2": {
      "abstract": [
        {
          "text": "The SW2 command-processing status byte.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusWord2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU/statusWord2",
      "kind": "symbol",
      "role": "symbol",
      "title": "statusWord2",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso7816responseapdu/statusword2"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag/sendCommand(apdu:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends an application protocol data unit (APDU) to the tag and receives a response APDU.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendCommand"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "apdu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCISO7816APDU",
          "text": "NFCISO7816APDU"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag/sendCommand(apdu:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendCommandAPDU:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sendCommand(apdu:completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso7816tag/sendcommand(apdu:completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag/sendCommand(apdu:resultHandler:)": {
      "abstract": [
        {
          "text": "Sends an application protocol data unit (APDU) to the tag and receives a response APDU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendCommand"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "apdu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCISO7816APDU",
          "text": "NFCISO7816APDU"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7CoreNFC22NFCISO7816ResponseAPDUV",
          "text": "NFCISO7816ResponseAPDU"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag/sendCommand(apdu:resultHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "sendCommand(apdu:resultHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso7816tag/sendcommand(apdu:resulthandler:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sending-a-Command",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag/sendCommand(apdu:resultHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag/sendCommand(apdu:completionHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816APDU"
      ],
      "title": "Sending a Command"
    }
  ],
  "topicSections": [
    {
      "anchor": "Response-Data",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU/payload",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU/statusWord1",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816ResponseAPDU/statusWord2"
      ],
      "title": "Response Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO7816Tag~1sendCommand(apdu:completionHandler:)/title",
          "value": "sendCommandAPDU:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO7816Tag~1sendCommand(apdu:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendCommandAPDU:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO7816APDU/title",
          "value": "NFCISO7816APDU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO7816APDU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO7816APDU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO7816APDU/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO7816APDU"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfciso7816responseapdu"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
