{
  "abstract": [
    {
      "text": "A payload record in an NFC NDEF message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NFCNDEFPayload",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NFCNDEFPayload"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCNDEFPayload"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NFCNDEFPayload"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NFCNDEFPayload"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.corenfc/documentation/CoreNFC/adding-support-for-background-tag-reading"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An NDEF message payload consists of the Type Name Format field (as defined by the NDEF specification), type, identifier, and data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage": {
      "abstract": [
        {
          "text": "An NFC NDEF message consisting of an array of payload records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFMessage"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFMessage"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFMessage",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefmessage"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload": {
      "abstract": [
        {
          "text": "A payload record in an NFC NDEF message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFPayload"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFPayload"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFPayload",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/identifier": {
      "abstract": [
        {
          "text": "The identifier of the payload, as defined by the NDEF specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/identifier"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/init(format:type:identifier:payload:)": {
      "abstract": [
        {
          "text": "Creates a payload record with the specified format, type, identifier, and payload data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCTypeNameFormat",
          "text": "NFCTypeNameFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "payload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/init(format:type:identifier:payload:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFormat:type:identifier:payload:"
        }
      ],
      "role": "symbol",
      "title": "init(format:type:identifier:payload:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/init(format:type:identifier:payload:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/init(format:type:identifier:payload:chunkSize:)": {
      "abstract": [
        {
          "text": "Creates a payload record with the specified format, type, identifier, payload data, and data chunk size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCTypeNameFormat",
          "text": "NFCTypeNameFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "payload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "chunkSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/init(format:type:identifier:payload:chunkSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFormat:type:identifier:payload:chunkSize:"
        }
      ],
      "role": "symbol",
      "title": "init(format:type:identifier:payload:chunkSize:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/init(format:type:identifier:payload:chunksize:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/payload": {
      "abstract": [
        {
          "text": "The payload, as defined by the NDEF specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/payload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "payload"
        }
      ],
      "role": "symbol",
      "title": "payload",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/payload"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/type": {
      "abstract": [
        {
          "text": "The type of the payload, as defined by the NDEF specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/type"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/typeNameFormat": {
      "abstract": [
        {
          "text": "The Type Name Format field of the payload, as defined by the NDEF specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeNameFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCTypeNameFormat",
          "text": "NFCTypeNameFormat"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/typeNameFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeNameFormat"
        }
      ],
      "role": "symbol",
      "title": "typeNameFormat",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/typenameformat"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnowTypeTextPayload(string:locale:)": {
      "abstract": [
        {
          "text": "Creates a payload record with text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wellKnowTypeTextPayload"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "locale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnowTypeTextPayload(string:locale:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wellKnowTypeTextPayloadWithString:locale:"
        }
      ],
      "role": "symbol",
      "title": "wellKnowTypeTextPayload(string:locale:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/wellknowtypetextpayload(string:locale:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeTextPayload()": {
      "abstract": [
        {
          "text": "Returns the text and locale of a valid Well Known Type Text payload.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wellKnownTypeTextPayload"
        },
        {
          "kind": "text",
          "text": "() -> ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeTextPayload()",
      "kind": "symbol",
      "role": "symbol",
      "title": "wellKnownTypeTextPayload()",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/wellknowntypetextpayload()"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeTextPayload(string:locale:)": {
      "abstract": [
        {
          "text": "Creates a payload record with text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wellKnownTypeTextPayload"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "locale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeTextPayload(string:locale:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wellKnownTypeTextPayloadWithString:locale:"
        }
      ],
      "role": "symbol",
      "title": "wellKnownTypeTextPayload(string:locale:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/wellknowntypetextpayload(string:locale:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeTextPayloadWithLocale:": {
      "abstract": [
        {
          "text": "Returns the text of a valid Well Known Type Text payload.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "wellKnownTypeTextPayloadWithLocale:"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeTextPayloadWithLocale:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wellKnownTypeTextPayloadWithLocale:"
        }
      ],
      "role": "symbol",
      "title": "wellKnownTypeTextPayloadWithLocale:",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/wellknowntypetextpayloadwithlocale:"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload()": {
      "abstract": [
        {
          "text": "Returns the URL of a valid Well Known Type URI payload.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wellKnownTypeURIPayload"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wellKnownTypeURIPayload"
        }
      ],
      "role": "symbol",
      "title": "wellKnownTypeURIPayload()",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/wellknowntypeuripayload()"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload(string:)": {
      "abstract": [
        {
          "text": "Creates a payload record with a URI specified as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wellKnownTypeURIPayload"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload(string:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wellKnownTypeURIPayloadWithString:"
        }
      ],
      "role": "symbol",
      "title": "wellKnownTypeURIPayload(string:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/wellknowntypeuripayload(string:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload(url:)": {
      "abstract": [
        {
          "text": "Creates a payload record with a URI specified as a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wellKnownTypeURIPayload"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload(url:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wellKnownTypeURIPayloadWithURL:"
        }
      ],
      "role": "symbol",
      "title": "wellKnownTypeURIPayload(url:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/wellknowntypeuripayload(url:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat": {
      "abstract": [
        {
          "text": "The Type Name Format values that specify the content type for the payload data in an NFC NDEF message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormat"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormat"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/adding-support-for-background-tag-reading": {
      "abstract": [
        {
          "text": "Allow users to scan NFC tags without an app using background tag reading.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/adding-support-for-background-tag-reading",
      "kind": "article",
      "role": "article",
      "title": "Adding Support for Background Tag Reading",
      "type": "topic",
      "url": "/documentation/corenfc/adding-support-for-background-tag-reading"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "NDEF-messages-and-payloads",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage"
      ],
      "title": "NDEF messages and payloads"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Payload-Record",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload(url:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload(string:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeTextPayload(string:locale:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/init(format:type:identifier:payload:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/init(format:type:identifier:payload:chunkSize:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnowTypeTextPayload(string:locale:)"
      ],
      "title": "Creating a Payload Record"
    },
    {
      "anchor": "Getting-Information-About-a-Payload-Record",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/identifier",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/payload",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/type",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/typeNameFormat",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat"
      ],
      "title": "Getting Information About a Payload Record"
    },
    {
      "anchor": "Getting-the-URI-from-a-Payload-Record",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload()"
      ],
      "title": "Getting the URI from a Payload Record"
    },
    {
      "anchor": "Getting-Text-from-a-Payload-Record",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeTextPayload()"
      ],
      "title": "Getting Text from a Payload Record"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCNDEFPayload"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Payload-Record",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload(url:)",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload(string:)",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeTextPayload(string:locale:)",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/init(format:type:identifier:payload:)",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/init(format:type:identifier:payload:chunkSize:)",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnowTypeTextPayload(string:locale:)"
              ],
              "title": "Creating a Payload Record"
            },
            {
              "anchor": "Getting-Information-About-a-Payload-Record",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/identifier",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/payload",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/type",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/typeNameFormat",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat"
              ],
              "title": "Getting Information About a Payload Record"
            },
            {
              "anchor": "Getting-the-URI-from-a-Payload-Record",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeURIPayload()"
              ],
              "title": "Getting the URI from a Payload Record"
            },
            {
              "anchor": "Getting-Text-from-a-Payload-Record",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/wellKnownTypeTextPayloadWithLocale:"
              ],
              "title": "Getting Text from a Payload Record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "NDEF-messages-and-payloads",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage"
              ],
              "title": "NDEF messages and payloads"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NFCNDEFPayload"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1wellKnownTypeURIPayload(string:)/title",
          "value": "wellKnownTypeURIPayloadWithString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1wellKnownTypeURIPayload(string:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "wellKnownTypeURIPayloadWithString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat/title",
          "value": "NFCTypeNameFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1wellKnownTypeURIPayload()/title",
          "value": "wellKnownTypeURIPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1wellKnownTypeURIPayload()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "wellKnownTypeURIPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1wellKnownTypeTextPayload(string:locale:)/title",
          "value": "wellKnownTypeTextPayloadWithString:locale:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1wellKnownTypeTextPayload(string:locale:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "wellKnownTypeTextPayloadWithString:locale:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload/title",
          "value": "NFCNDEFPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1payload/title",
          "value": "payload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1payload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "payload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1init(format:type:identifier:payload:chunkSize:)/title",
          "value": "initWithFormat:type:identifier:payload:chunkSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1init(format:type:identifier:payload:chunkSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFormat:type:identifier:payload:chunkSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1init(format:type:identifier:payload:)/title",
          "value": "initWithFormat:type:identifier:payload:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1init(format:type:identifier:payload:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFormat:type:identifier:payload:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1typeNameFormat/title",
          "value": "typeNameFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1typeNameFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1wellKnownTypeURIPayload(url:)/title",
          "value": "wellKnownTypeURIPayloadWithURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1wellKnownTypeURIPayload(url:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "wellKnownTypeURIPayloadWithURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1wellKnowTypeTextPayload(string:locale:)/title",
          "value": "wellKnowTypeTextPayloadWithString:locale:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1wellKnowTypeTextPayload(string:locale:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "wellKnowTypeTextPayloadWithString:locale:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFMessage/title",
          "value": "NFCNDEFMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFMessage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcndefpayload"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfcndefpayload"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
