{
  "abstract": [
    {
      "text": "A collection of callbacks that provide information about the status of an NFC reader session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NFCReaderSessionDelegate",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NFCReaderSessionDelegate"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCReaderSessionDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NFCReaderSessionDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NFCReaderSessionDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession": {
      "abstract": [
        {
          "text": "A reader session for detecting NFC Data Exchange Format (NDEF) tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefreadersession"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class": {
      "abstract": [
        {
          "text": "The abstract base class that represents a reader session for detecting NFC tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersession-swift.class"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate": {
      "abstract": [
        {
          "text": "A collection of callbacks that provide information about the status of an NFC reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCReaderSessionDelegate",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersessiondelegate"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate/readerSession:didDetectTags:": {
      "abstract": [
        {
          "text": "Provides an array of tags detected by the reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "readerSession:didDetectTags:"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate/readerSession:didDetectTags:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readerSession:didDetectTags:"
        }
      ],
      "role": "symbol",
      "title": "readerSession:didDetectTags:",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersessiondelegate/readersession:diddetecttags:"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate/readerSession:didInvalidateWithError:": {
      "abstract": [
        {
          "text": "Provides information about the error that invalidated the reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "readerSession:didInvalidateWithError:"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate/readerSession:didInvalidateWithError:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readerSession:didInvalidateWithError:"
        }
      ],
      "role": "symbol",
      "title": "readerSession:didInvalidateWithError:",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersessiondelegate/readersession:didinvalidatewitherror:"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate/readerSessionDidBecomeActive:": {
      "abstract": [
        {
          "text": "Tells you when radio-frequency polling is enabled and the reader session has become active and is scanning for tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "readerSessionDidBecomeActive:"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate/readerSessionDidBecomeActive:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readerSessionDidBecomeActive:"
        }
      ],
      "role": "symbol",
      "title": "readerSessionDidBecomeActive:",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersessiondelegate/readersessiondidbecomeactive:"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol": {
      "abstract": [
        {
          "text": "A general interface for interacting with a reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderSessionProtocol"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionProtocol"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderSessionProtocol",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersessionprotocol"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession": {
      "abstract": [
        {
          "text": "A reader session for detecting ISO7816, ISO15693, FeliCa, and MIFARE tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTagReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTagReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCTagReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagreadersession"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession": {
      "abstract": [
        {
          "text": "A reader session for processing Value Added Service (VAS) tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCVASReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCVASReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasreadersession"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats": {
      "abstract": [
        {
          "text": "The Near Field Communication data formats an app can read.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats",
      "kind": "symbol",
      "role": "symbol",
      "title": "Near Field Communication Tag Reader Session Formats Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reader-sessions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats"
      ],
      "title": "Reader sessions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Status-of-a-Reader-Session",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate/readerSession:didDetectTags:",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate/readerSession:didInvalidateWithError:",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate/readerSessionDidBecomeActive:"
      ],
      "title": "Getting the Status of a Reader Session"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSessionProtocol/title",
          "value": "NFCReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSessionProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSessionProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class/title",
          "value": "NFCReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/title",
          "value": "NFCNDEFReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession/title",
          "value": "NFCTagReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASReaderSession/title",
          "value": "NFCVASReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASReaderSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASReaderSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcreadersessiondelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
