{
  "abstract": [
    {
      "text": "An error type that indicates problems with reader sessions or tags.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC14NFCReaderErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NFCReaderError"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCReaderError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NFCReaderError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain": {
      "abstract": [
        {
          "text": "The domain for errors associated with Core NFC APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "NFCErrorDomain",
      "type": "topic",
      "url": "/documentation/corenfc/nfcerrordomain"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct": {
      "abstract": [
        {
          "text": "An error type that indicates problems with reader sessions or tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Reader session and tag error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/errordomain"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorTagNotWritable": {
      "abstract": [
        {
          "text": "The NDEF tag isn’t writable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorTagNotWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorTagNotWritable",
      "kind": "symbol",
      "role": "symbol",
      "title": "ndefReaderSessionErrorTagNotWritable",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/ndefreadersessionerrortagnotwritable"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorTagSizeTooSmall": {
      "abstract": [
        {
          "text": "The NDEF tag memory size is too small to store the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorTagSizeTooSmall"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorTagSizeTooSmall",
      "kind": "symbol",
      "role": "symbol",
      "title": "ndefReaderSessionErrorTagSizeTooSmall",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/ndefreadersessionerrortagsizetoosmall"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorTagUpdateFailure": {
      "abstract": [
        {
          "text": "The reader session failed to update the NDEF tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorTagUpdateFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorTagUpdateFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "ndefReaderSessionErrorTagUpdateFailure",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/ndefreadersessionerrortagupdatefailure"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorZeroLengthMessage": {
      "abstract": [
        {
          "text": "The NDEF tag doesn’t contain an NDEF message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ndefReaderSessionErrorZeroLengthMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorZeroLengthMessage",
      "kind": "symbol",
      "role": "symbol",
      "title": "ndefReaderSessionErrorZeroLengthMessage",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/ndefreadersessionerrorzerolengthmessage"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorInvalidParameter": {
      "abstract": [
        {
          "text": "An input parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorInvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorInvalidParameter",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerErrorInvalidParameter",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readererrorinvalidparameter"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorInvalidParameterLength": {
      "abstract": [
        {
          "text": "The length of an input parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorInvalidParameterLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorInvalidParameterLength",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerErrorInvalidParameterLength",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readererrorinvalidparameterlength"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorParameterOutOfBound": {
      "abstract": [
        {
          "text": "A parameter value is outside of the acceptable boundary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorParameterOutOfBound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorParameterOutOfBound",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerErrorParameterOutOfBound",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readererrorparameteroutofbound"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorRadioDisabled": {
      "abstract": [
        {
          "text": "The NFC wireless radio on the device is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorRadioDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorRadioDisabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerErrorRadioDisabled",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readererrorradiodisabled"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorSecurityViolation": {
      "abstract": [
        {
          "text": "A security violation associated with the reader session has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorSecurityViolation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorSecurityViolation",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerErrorSecurityViolation",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readererrorsecurityviolation"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorUnsupportedFeature": {
      "abstract": [
        {
          "text": "The reader session does not support this feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerErrorUnsupportedFeature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorUnsupportedFeature",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerErrorUnsupportedFeature",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readererrorunsupportedfeature"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorFirstNDEFTagRead": {
      "abstract": [
        {
          "text": "The first NDEF tag read by this session is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorFirstNDEFTagRead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorFirstNDEFTagRead",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerSessionInvalidationErrorFirstNDEFTagRead",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readersessioninvalidationerrorfirstndeftagread"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorSessionTerminatedUnexpectedly": {
      "abstract": [
        {
          "text": "The reader session terminated unexpectedly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorSessionTerminatedUnexpectedly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readersessioninvalidationerrorsessionterminatedunexpectedly"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorSessionTimeout": {
      "abstract": [
        {
          "text": "The reader session timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorSessionTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorSessionTimeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerSessionInvalidationErrorSessionTimeout",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readersessioninvalidationerrorsessiontimeout"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorSystemIsBusy": {
      "abstract": [
        {
          "text": "The reader session failed because the system is busy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorSystemIsBusy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorSystemIsBusy",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerSessionInvalidationErrorSystemIsBusy",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readersessioninvalidationerrorsystemisbusy"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorUserCanceled": {
      "abstract": [
        {
          "text": "The user canceled the reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerSessionInvalidationErrorUserCanceled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorUserCanceled",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerSessionInvalidationErrorUserCanceled",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readersessioninvalidationerrorusercanceled"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorPacketTooLong": {
      "abstract": [
        {
          "text": "The packet length exceeds the limit supported by the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorPacketTooLong"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorPacketTooLong",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerTransceiveErrorPacketTooLong",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readertransceiveerrorpackettoolong"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorRetryExceeded": {
      "abstract": [
        {
          "text": "Too many retries have occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorRetryExceeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorRetryExceeded",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerTransceiveErrorRetryExceeded",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readertransceiveerrorretryexceeded"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorSessionInvalidated": {
      "abstract": [
        {
          "text": "The reader session is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorSessionInvalidated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorSessionInvalidated",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerTransceiveErrorSessionInvalidated",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readertransceiveerrorsessioninvalidated"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorTagConnectionLost": {
      "abstract": [
        {
          "text": "The reader lost the connection to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorTagConnectionLost"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorTagConnectionLost",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerTransceiveErrorTagConnectionLost",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readertransceiveerrortagconnectionlost"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorTagNotConnected": {
      "abstract": [
        {
          "text": "The tag isn’t in the connected state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorTagNotConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorTagNotConnected",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerTransceiveErrorTagNotConnected",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readertransceiveerrortagnotconnected"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorTagResponseError": {
      "abstract": [
        {
          "text": "The tag has responded with an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerTransceiveErrorTagResponseError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorTagResponseError",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerTransceiveErrorTagResponseError",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/readertransceiveerrortagresponseerror"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/tagCommandConfigurationErrorInvalidParameters": {
      "abstract": [
        {
          "text": "The tag has been configured with invalid parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tagCommandConfigurationErrorInvalidParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14NFCReaderErrorLeV",
          "text": "NFCReaderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCReaderError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/tagCommandConfigurationErrorInvalidParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "tagCommandConfigurationErrorInvalidParameters",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/tagcommandconfigurationerrorinvalidparameters"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagResponseUnexpectedLengthErrorKey": {
      "abstract": [
        {
          "text": "A user-information dictionary key that indicates an invalid received response packet length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTagResponseUnexpectedLengthErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagResponseUnexpectedLengthErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTagResponseUnexpectedLengthErrorKey"
        }
      ],
      "role": "symbol",
      "title": "NFCTagResponseUnexpectedLengthErrorKey",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagresponseunexpectedlengtherrorkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagResponseUnexpectedLengthErrorKey"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Session-Errors",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorFirstNDEFTagRead",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorSessionTerminatedUnexpectedly",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorSessionTimeout",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorSystemIsBusy",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerSessionInvalidationErrorUserCanceled"
      ],
      "title": "Session Errors"
    },
    {
      "anchor": "NDEF-Tag-Errors",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorTagNotWritable",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorTagSizeTooSmall",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorTagUpdateFailure",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/ndefReaderSessionErrorZeroLengthMessage"
      ],
      "title": "NDEF Tag Errors"
    },
    {
      "anchor": "Transceive-Errors",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorRetryExceeded",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorTagConnectionLost",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorTagNotConnected",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorTagResponseError",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorSessionInvalidated",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerTransceiveErrorPacketTooLong"
      ],
      "title": "Transceive Errors"
    },
    {
      "anchor": "Tag-Command-Configuration-Error",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/tagCommandConfigurationErrorInvalidParameters"
      ],
      "title": "Tag Command Configuration Error"
    },
    {
      "anchor": "Other-Errors",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorUnsupportedFeature",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorInvalidParameter",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorInvalidParameterLength",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorParameterOutOfBound",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorRadioDisabled",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/readerErrorSecurityViolation"
      ],
      "title": "Other Errors"
    },
    {
      "anchor": "Error-Domain",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain"
      ],
      "title": "Error Domain"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagResponseUnexpectedLengthErrorKey/title",
          "value": "NFCTagResponseUnexpectedLengthErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagResponseUnexpectedLengthErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagResponseUnexpectedLengthErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/title",
          "value": "NFCReaderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCErrorDomain/title",
          "value": "NFCErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcreadererror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
