{
  "abstract": [
    {
      "text": "The abstract base class that represents a reader session for detecting NFC tags.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NFCReaderSession",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NFCReaderSession"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCReaderSession"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NFCReaderSession"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You do not create instances of this class. Instead, you create and use an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Only one reader session of any type can be active in the system at a time. The system puts additional sessions in a queue and processes them in FIFO order.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ReaderSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NFCISO15693ReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ReaderSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCISO15693ReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693readersession"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession": {
      "abstract": [
        {
          "text": "A reader session for detecting NFC Data Exchange Format (NDEF) tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefreadersession"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class": {
      "abstract": [
        {
          "text": "The abstract base class that represents a reader session for detecting NFC tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersession-swift.class"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/delegate": {
      "abstract": [
        {
          "text": "The delegate of the reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": AnyObject?"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersession-swift.class/delegate"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/readingAvailable": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the device supports NFC tag reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readingAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/readingAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readingAvailable"
        }
      ],
      "role": "symbol",
      "title": "readingAvailable",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersession-swift.class/readingavailable"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/sessionQueue": {
      "abstract": [
        {
          "text": "The queue on which the reader session delegate callbacks and completion block handlers are dispatched.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/sessionQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sessionQueue"
        }
      ],
      "role": "symbol",
      "title": "sessionQueue",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersession-swift.class/sessionqueue"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate": {
      "abstract": [
        {
          "text": "A collection of callbacks that provide information about the status of an NFC reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCReaderSessionDelegate",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersessiondelegate"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol": {
      "abstract": [
        {
          "text": "A general interface for interacting with a reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderSessionProtocol"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionProtocol"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderSessionProtocol",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersessionprotocol"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession": {
      "abstract": [
        {
          "text": "A reader session for detecting ISO7816, ISO15693, FeliCa, and MIFARE tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTagReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTagReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCTagReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagreadersession"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession": {
      "abstract": [
        {
          "text": "A reader session for processing Value Added Service (VAS) tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCVASReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCVASReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasreadersession"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats": {
      "abstract": [
        {
          "text": "The Near Field Communication data formats an app can read.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats",
      "kind": "symbol",
      "role": "symbol",
      "title": "Near Field Communication Tag Reader Session Formats Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reader-sessions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats"
      ],
      "title": "Reader sessions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-Tag-Reading-Capability",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/readingAvailable"
      ],
      "title": "Determining Tag Reading Capability"
    },
    {
      "anchor": "Working-with-a-Session",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/delegate",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/sessionQueue"
      ],
      "title": "Working with a Session"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCReaderSession"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-Tag-Reading-Capability",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/readingAvailable"
              ],
              "title": "Determining Tag Reading Capability"
            },
            {
              "anchor": "Working-with-a-Session",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/delegate",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/sessionQueue"
              ],
              "title": "Working with a Session"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ReaderSession",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reader-sessions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats"
              ],
              "title": "Reader sessions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NFCReaderSession"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class/title",
          "value": "NFCReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASReaderSession/title",
          "value": "NFCVASReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASReaderSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASReaderSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSessionProtocol/title",
          "value": "NFCReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSessionProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSessionProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession/title",
          "value": "NFCTagReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class~1readingAvailable/title",
          "value": "readingAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class~1readingAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "readingAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/title",
          "value": "NFCNDEFReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class~1sessionQueue/title",
          "value": "sessionQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class~1sessionQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sessionQueue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcreadersession-swift.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfcreadersession-swift.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
