{
  "abstract": [
    {
      "text": "The Type Name Format values that specify the content type for the payload data in an NFC NDEF message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NFCTypeNameFormat",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NFCTypeNameFormat"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCTypeNameFormat"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NFCTypeNameFormat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormat"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/identifier": {
      "abstract": [
        {
          "text": "The identifier of the payload, as defined by the NDEF specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/identifier"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/payload": {
      "abstract": [
        {
          "text": "The payload, as defined by the NDEF specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/payload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "payload"
        }
      ],
      "role": "symbol",
      "title": "payload",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/payload"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/type": {
      "abstract": [
        {
          "text": "The type of the payload, as defined by the NDEF specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/type"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/typeNameFormat": {
      "abstract": [
        {
          "text": "The Type Name Format field of the payload, as defined by the NDEF specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeNameFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCTypeNameFormat",
          "text": "NFCTypeNameFormat"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/typeNameFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeNameFormat"
        }
      ],
      "role": "symbol",
      "title": "typeNameFormat",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload/typenameformat"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat": {
      "abstract": [
        {
          "text": "The Type Name Format values that specify the content type for the payload data in an NFC NDEF message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormat"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormat"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/absoluteURI": {
      "abstract": [
        {
          "text": "A type indicating that the payload contains a uniform resource identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "absoluteURI"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/absoluteURI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatAbsoluteURI"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.absoluteURI",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/absoluteuri"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/empty": {
      "abstract": [
        {
          "text": "A type indicating that the payload contains no data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "empty"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/empty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatEmpty"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.empty",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/empty"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/init(rawvalue:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/media": {
      "abstract": [
        {
          "text": "A type indicating that the payload contains media data as defined by RFC 2046.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "media"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/media",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatMedia"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.media",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/media"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcExternal": {
      "abstract": [
        {
          "text": "A type indicating that the payload contains NFC external type data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nfcExternal"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcExternal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatNFCExternal"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.nfcExternal",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/nfcexternal"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcWellKnown": {
      "abstract": [
        {
          "text": "A type indicating that the payload contains well-known NFC record type data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nfcWellKnown"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcWellKnown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatNFCWellKnown"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.nfcWellKnown",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/nfcwellknown"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unchanged": {
      "abstract": [
        {
          "text": "A type indicating that the payload is part of a series of records containing chunked data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unchanged"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unchanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatUnchanged"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.unchanged",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/unchanged"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unknown": {
      "abstract": [
        {
          "text": "A type indicating that the payload data type is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTypeNameFormatUnknown"
        }
      ],
      "role": "symbol",
      "title": "NFCTypeNameFormat.unknown",
      "type": "topic",
      "url": "/documentation/corenfc/nfctypenameformat/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Information-About-a-Payload-Record",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/identifier",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/payload",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/type",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/typeNameFormat"
      ],
      "title": "Getting Information About a Payload Record"
    }
  ],
  "topicSections": [
    {
      "anchor": "Content-Types",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/absoluteURI",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/empty",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/media",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcExternal",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcWellKnown",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unchanged",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unknown"
      ],
      "title": "Content Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCTypeNameFormat"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Content-Types",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/absoluteURI",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/empty",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/media",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcExternal",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/nfcWellKnown",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unchanged",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTypeNameFormat/unknown"
              ],
              "title": "Content Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Information-About-a-Payload-Record",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/identifier",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/payload",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/type",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload/typeNameFormat"
              ],
              "title": "Getting Information About a Payload Record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NFCTypeNameFormat"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1absoluteURI/title",
          "value": "NFCTypeNameFormatAbsoluteURI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1absoluteURI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatAbsoluteURI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat/title",
          "value": "NFCTypeNameFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1unchanged/title",
          "value": "NFCTypeNameFormatUnchanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1unchanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatUnchanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1payload/title",
          "value": "payload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1payload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "payload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1nfcExternal/title",
          "value": "NFCTypeNameFormatNFCExternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1nfcExternal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatNFCExternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1media/title",
          "value": "NFCTypeNameFormatMedia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1media/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatMedia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1empty/title",
          "value": "NFCTypeNameFormatEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1empty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1nfcWellKnown/title",
          "value": "NFCTypeNameFormatNFCWellKnown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1nfcWellKnown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatNFCWellKnown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1typeNameFormat/title",
          "value": "typeNameFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload~1typeNameFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typeNameFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1unknown/title",
          "value": "NFCTypeNameFormatUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTypeNameFormat~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTypeNameFormatUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfctypenameformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfctypenameformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
