{
  "abstract": [
    {
      "text": "A protocol that an object implements to receive callbacks sent from an NFC tag reader session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NFCTagReaderSessionDelegate",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NFCTagReaderSessionDelegate"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NFCTagReaderSessionDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NFCTagReaderSessionDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NFCTagReaderSessionDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession/PollingOption": {
      "abstract": [
        {
          "text": "Options that determine the type of tags that a reader session should detect during a polling sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PollingOption"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession/PollingOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PollingOption"
        }
      ],
      "role": "symbol",
      "title": "NFCTagReaderSession.PollingOption",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagreadersession/pollingoption"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession/initWithPollingOption:delegate:queue:": {
      "abstract": [
        {
          "text": "Intializes an NFC tag reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithPollingOption:delegate:queue:"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession/initWithPollingOption:delegate:queue:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPollingOption:delegate:queue:"
        }
      ],
      "role": "symbol",
      "title": "initWithPollingOption:delegate:queue:",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagreadersession/initwithpollingoption:delegate:queue:"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw": {
      "abstract": [
        {
          "text": "A protocol that an object implements to receive callbacks sent from an NFC tag reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NFCTagReaderSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCTagReaderSessionDelegate",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagreadersessiondelegate-5gxiw"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw/tagReaderSession:didDetectTags:": {
      "abstract": [
        {
          "text": "Tells the delegate that the session detected NFC tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "tagReaderSession:didDetectTags:"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw/tagReaderSession:didDetectTags:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tagReaderSession:didDetectTags:"
        }
      ],
      "role": "symbol",
      "title": "tagReaderSession:didDetectTags:",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagreadersessiondelegate-5gxiw/tagreadersession:diddetecttags:"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw/tagReaderSession:didInvalidateWithError:": {
      "abstract": [
        {
          "text": "Tells the delegate the reason for invalidating a reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "tagReaderSession:didInvalidateWithError:"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw/tagReaderSession:didInvalidateWithError:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tagReaderSession:didInvalidateWithError:"
        }
      ],
      "role": "symbol",
      "title": "tagReaderSession:didInvalidateWithError:",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagreadersessiondelegate-5gxiw/tagreadersession:didinvalidatewitherror:"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw/tagReaderSessionDidBecomeActive:": {
      "abstract": [
        {
          "text": "Tells the delegate that the reader session is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "tagReaderSessionDidBecomeActive:"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw/tagReaderSessionDidBecomeActive:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tagReaderSessionDidBecomeActive:"
        }
      ],
      "role": "symbol",
      "title": "tagReaderSessionDidBecomeActive:",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagreadersessiondelegate-5gxiw/tagreadersessiondidbecomeactive:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Tag-Reader-Session",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession/initWithPollingOption:delegate:queue:",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession/PollingOption"
      ],
      "title": "Creating a Tag Reader Session"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-Session-Activation",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw/tagReaderSessionDidBecomeActive:"
      ],
      "title": "Handling Session Activation"
    },
    {
      "anchor": "Finding-NFC-Tags",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw/tagReaderSession:didDetectTags:"
      ],
      "title": "Finding NFC Tags"
    },
    {
      "anchor": "Handling-an-Invalidated-Session",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSessionDelegate-5gxiw/tagReaderSession:didInvalidateWithError:"
      ],
      "title": "Handling an Invalidated Session"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession~1PollingOption/title",
          "value": "NFCPollingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession~1PollingOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCPollingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession~1PollingOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCPollingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfctagreadersessiondelegate-5gxiw"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
