{
  "abstract": [
    {
      "text": "Codes that specify the type of the data to request when polling.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/PollingRequestCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@PollingRequestCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PollingRequestCode"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PollingRequestCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.0",
        "name": "iOS",
        "renamed": "NFCFeliCaPollingRequestCode",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.0",
        "name": "iPadOS",
        "renamed": "NFCFeliCaPollingRequestCode",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "renamed": "NFCFeliCaPollingRequestCode",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "PollingRequestCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PollingRequestCode"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NFCFeliCaPollingRequestCode",
              "text": "NFCFeliCaPollingRequestCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingRequestCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingRequestCode"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaPollingRequestCode",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicapollingrequestcode"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeCommunicationPerformance": {
      "abstract": [
        {
          "text": "A code that indicates a communication performance request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PollingRequestCodeCommunicationPerformance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCFeliCaPollingRequestCode",
          "text": "NFCFeliCaPollingRequestCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeCommunicationPerformance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PollingRequestCodeCommunicationPerformance"
        }
      ],
      "role": "symbol",
      "title": "PollingRequestCodeCommunicationPerformance",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicapollingrequestcode/pollingrequestcodecommunicationperformance"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeNoRequest": {
      "abstract": [
        {
          "text": "A code that indicates no request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PollingRequestCodeNoRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCFeliCaPollingRequestCode",
          "text": "NFCFeliCaPollingRequestCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeNoRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PollingRequestCodeNoRequest"
        }
      ],
      "role": "symbol",
      "title": "PollingRequestCodeNoRequest",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicapollingrequestcode/pollingrequestcodenorequest"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeSystemCode": {
      "abstract": [
        {
          "text": "A code that indicates a system code request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PollingRequestCodeSystemCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCFeliCaPollingRequestCode",
          "text": "NFCFeliCaPollingRequestCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeSystemCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PollingRequestCodeSystemCode"
        }
      ],
      "role": "symbol",
      "title": "PollingRequestCodeSystemCode",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicapollingrequestcode/pollingrequestcodesystemcode"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/polling(systemCode:requestCode:timeSlot:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the Polling command as defined by FeliCa card specification to the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "polling"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "systemCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "requestCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCFeliCaPollingRequestCode",
          "text": "NFCFeliCaPollingRequestCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeSlot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCFeliCaPollingTimeSlot",
          "text": "NFCFeliCaPollingTimeSlot"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/polling(systemCode:requestCode:timeSlot:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pollingWithSystemCode:requestCode:timeSlot:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "polling(systemCode:requestCode:timeSlot:completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag/polling(systemcode:requestcode:timeslot:completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/PollingRequestCode": {
      "abstract": [
        {
          "text": "Codes that specify the type of the data to request when polling.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PollingRequestCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/PollingRequestCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PollingRequestCode"
        }
      ],
      "role": "symbol",
      "title": "PollingRequestCode",
      "type": "topic",
      "url": "/documentation/corenfc/pollingrequestcode"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/PollingTimeSlot": {
      "abstract": [
        {
          "text": "Constants that specify the maximum number of time slots.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PollingTimeSlot"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/PollingTimeSlot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PollingTimeSlot"
        }
      ],
      "role": "symbol",
      "title": "PollingTimeSlot",
      "type": "topic",
      "url": "/documentation/corenfc/pollingtimeslot"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Polling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/polling(systemCode:requestCode:timeSlot:completionHandler:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/PollingTimeSlot"
      ],
      "title": "Polling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Request-Codes",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeNoRequest",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeSystemCode",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeCommunicationPerformance"
      ],
      "title": "Request Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PollingRequestCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Request-Codes",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeNoRequest",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeSystemCode",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode/PollingRequestCodeCommunicationPerformance"
              ],
              "title": "Request Codes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Polling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag/polling(systemCode:requestCode:timeSlot:completionHandler:)",
                "doc://com.apple.corenfc/documentation/CoreNFC/PollingTimeSlot"
              ],
              "title": "Polling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NFCFeliCaPollingRequestCode",
                    "text": "NFCFeliCaPollingRequestCode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PollingRequestCode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1polling(systemCode:requestCode:timeSlot:completionHandler:)/title",
          "value": "pollingWithSystemCode:requestCode:timeSlot:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag~1polling(systemCode:requestCode:timeSlot:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pollingWithSystemCode:requestCode:timeSlot:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingRequestCode/title",
          "value": "PollingRequestCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingRequestCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingRequestCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingTimeSlot/title",
          "value": "PollingTimeSlot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingTimeSlot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingTimeSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1PollingTimeSlot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingTimeSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode~1PollingRequestCodeCommunicationPerformance/title",
          "value": "PollingRequestCodeCommunicationPerformance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode~1PollingRequestCodeCommunicationPerformance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingRequestCodeCommunicationPerformance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode~1PollingRequestCodeSystemCode/title",
          "value": "PollingRequestCodeSystemCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode~1PollingRequestCodeSystemCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingRequestCodeSystemCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode/title",
          "value": "NFCFeliCaPollingRequestCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaPollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaPollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode~1PollingRequestCodeNoRequest/title",
          "value": "PollingRequestCodeNoRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode~1PollingRequestCodeNoRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PollingRequestCodeNoRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/pollingrequestcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/pollingrequestcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
