{
  "abstract": [
    {
      "text": "Constants representing APDU status codes for a VAS response.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/VASErrorCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@VASErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VASErrorCode"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VASErrorCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.0",
        "name": "iOS",
        "renamed": "NFCVASErrorCode",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.0",
        "name": "iPadOS",
        "renamed": "NFCVASErrorCode",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "renamed": "NFCVASErrorCode",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "VASErrorCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VASErrorCode"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NFCVASResponse",
              "text": "NFCVASResponse"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NFCVASErrorCode",
              "text": "ErrorCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse": {
      "abstract": [
        {
          "text": "An object representing the response from a single ",
          "type": "text"
        },
        {
          "code": "GET VAS DATA",
          "type": "codeVoice"
        },
        {
          "text": " command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCVASResponse"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASResponse"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse.ErrorCode",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotActivated": {
      "abstract": [
        {
          "text": "A constant indicating that the data isn’t activated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeDataNotActivated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotActivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeDataNotActivated"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeDataNotActivated",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodedatanotactivated"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotFound": {
      "abstract": [
        {
          "text": "A constant indicating that data wasn’t found.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeDataNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeDataNotFound"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeDataNotFound",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodedatanotfound"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeIncorrectData": {
      "abstract": [
        {
          "text": "A constant indicating that the data is incorrect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeIncorrectData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeIncorrectData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeIncorrectData"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeIncorrectData",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodeincorrectdata"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeSuccess": {
      "abstract": [
        {
          "text": "A constant indicating that the ",
          "type": "text"
        },
        {
          "code": "GET VAS DATA",
          "type": "codeVoice"
        },
        {
          "text": " command was successful.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeSuccess",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodesuccess"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUnsupportedApplicationVersion": {
      "abstract": [
        {
          "text": "A constant indicating an unsupported application version.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeUnsupportedApplicationVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUnsupportedApplicationVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeUnsupportedApplicationVersion"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeUnsupportedApplicationVersion",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodeunsupportedapplicationversion"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUserIntervention": {
      "abstract": [
        {
          "text": "A constant indicating that the tag requires user intervention.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeUserIntervention"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUserIntervention",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeUserIntervention"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeUserIntervention",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodeuserintervention"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongLCField": {
      "abstract": [
        {
          "text": "A constant indicating that the value in the Length Count field is wrong.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeWrongLCField"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongLCField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeWrongLCField"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeWrongLCField",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodewronglcfield"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongParameters": {
      "abstract": [
        {
          "text": "A constant indicating that VAS command parameters are wrong.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeWrongParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeWrongParameters"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeWrongParameters",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodewrongparameters"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/status": {
      "abstract": [
        {
          "text": "A response APDU status code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/status"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/VASErrorCode": {
      "abstract": [
        {
          "text": "Constants representing APDU status codes for a VAS response.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/VASErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCode"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCode",
      "type": "topic",
      "url": "/documentation/corenfc/vaserrorcode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Response-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/status"
      ],
      "title": "Getting the Response Status"
    }
  ],
  "topicSections": [
    {
      "anchor": "Status-Codes",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeSuccess",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUserIntervention"
      ],
      "title": "Status Codes"
    },
    {
      "anchor": "Data-Codes",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotActivated",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotFound",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeIncorrectData"
      ],
      "title": "Data Codes"
    },
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUnsupportedApplicationVersion",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongLCField",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongParameters"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VASErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Status-Codes",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeSuccess",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUserIntervention"
              ],
              "title": "Status Codes"
            },
            {
              "anchor": "Data-Codes",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotActivated",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotFound",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeIncorrectData"
              ],
              "title": "Data Codes"
            },
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUnsupportedApplicationVersion",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongLCField",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongParameters"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Response-Status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/status"
              ],
              "title": "Getting the Response Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NFCVASErrorCode",
                    "text": "NFCVASErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VASErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1VASErrorCode/title",
          "value": "VASErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1VASErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1VASErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeDataNotActivated/title",
          "value": "VASErrorCodeDataNotActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeDataNotActivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeDataNotActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeDataNotFound/title",
          "value": "VASErrorCodeDataNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeDataNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeDataNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeWrongLCField/title",
          "value": "VASErrorCodeWrongLCField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeWrongLCField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeWrongLCField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeIncorrectData/title",
          "value": "VASErrorCodeIncorrectData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeIncorrectData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeIncorrectData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode/title",
          "value": "NFCVASErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1status/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeUserIntervention/title",
          "value": "VASErrorCodeUserIntervention"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeUserIntervention/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeUserIntervention"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeSuccess/title",
          "value": "VASErrorCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse/title",
          "value": "NFCVASResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeUnsupportedApplicationVersion/title",
          "value": "VASErrorCodeUnsupportedApplicationVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeUnsupportedApplicationVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeUnsupportedApplicationVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeWrongParameters/title",
          "value": "VASErrorCodeWrongParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeWrongParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeWrongParameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/vaserrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/vaserrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
