{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"VASMode"},{"kind":"text","text":" = "},{"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NFCVASCommandConfiguration","text":"NFCVASCommandConfiguration"},{"kind":"text","text":"."},{"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum","kind":"typeIdentifier","preciseIdentifier":"c:@E@NFCVASMode","text":"Mode"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"variants":[{"paths":["/documentation/corenfc/vasmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/corenfc/vasmode"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum/VASModeNormal"],"title":"Modes","anchor":"Modes"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"VASMode"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"VASMode"}],"modules":[{"name":"Core NFC"}],"roleHeading":"Type Alias","symbolKind":"typealias","role":"symbol","title":"VASMode","platforms":[{"name":"iOS","introducedAt":"13.0","deprecatedAt":"14.0","renamed":"NFCVASMode","unavailable":false,"deprecated":false,"beta":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"13.0","deprecatedAt":"14.0","renamed":"NFCVASMode","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecatedAt":"14.0","renamed":"NFCVASMode","deprecated":false}],"externalID":"c:@T@VASMode"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corenfc/documentation/CoreNFC"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/mode-swift.property","doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/passTypeIdentifier","doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/url"],"title":"Setting Configuration Items","anchor":"Setting-Configuration-Items","generated":true}],"sections":[],"abstract":[{"type":"text","text":"Constants that indicate the VAS protocol mode."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.corenfc/documentation/CoreNFC/VASMode"},"references":{"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NFCVASCommandConfiguration"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration","url":"/documentation/corenfc/nfcvascommandconfiguration","role":"symbol","title":"NFCVASCommandConfiguration","kind":"symbol","type":"topic","abstract":[{"text":"An object providing the configuration for a GET VAS DATA command.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NFCVASCommandConfiguration"}]},"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum/VASModeNormal":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"VASModeNormal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NFCVASCommandConfiguration","preciseIdentifier":"c:objc(cs)NFCVASCommandConfiguration"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"c:@E@NFCVASMode"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum/VASModeNormal","url":"/documentation/corenfc/nfcvascommandconfiguration/mode-swift.enum/vasmodenormal","role":"symbol","deprecated":true,"title":"VASModeNormal","kind":"symbol","type":"topic","abstract":[{"text":"A constant that indicates the Full VAS Protocol mode.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"VASModeNormal"}]},"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/mode-swift.property":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NFCVASCommandConfiguration","preciseIdentifier":"c:objc(cs)NFCVASCommandConfiguration","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Mode","preciseIdentifier":"c:@E@NFCVASMode","kind":"typeIdentifier"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/mode-swift.property","url":"/documentation/corenfc/nfcvascommandconfiguration/mode-swift.property","role":"symbol","title":"mode","kind":"symbol","type":"topic","abstract":[{"text":"A VAS protocol mode.","type":"text"}],"navigatorTitle":[{"text":"mode","kind":"identifier"}]},"doc://com.apple.corenfc/documentation/CoreNFC/VASMode":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VASMode","kind":"identifier"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/VASMode","url":"/documentation/corenfc/vasmode","role":"symbol","deprecated":true,"title":"VASMode","kind":"symbol","type":"topic","abstract":[{"text":"Constants that indicate the VAS protocol mode.","type":"text"}],"navigatorTitle":[{"text":"VASMode","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","title":"Technologies","kind":"technologies","abstract":[{"type":"text","text":""}],"role":"overview","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/passTypeIdentifier":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passTypeIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/passTypeIdentifier","url":"/documentation/corenfc/nfcvascommandconfiguration/passtypeidentifier","role":"symbol","title":"passTypeIdentifier","kind":"symbol","type":"topic","abstract":[{"text":"A type identifier for the Wallet Pass.","type":"text"}],"navigatorTitle":[{"text":"passTypeIdentifier","kind":"identifier"}]},"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/url":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/url","url":"/documentation/corenfc/nfcvascommandconfiguration/url","role":"symbol","title":"url","kind":"symbol","type":"topic","abstract":[{"text":"A merchant URL.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"url"}]},"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mode"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum","url":"/documentation/corenfc/nfcvascommandconfiguration/mode-swift.enum","role":"symbol","title":"NFCVASCommandConfiguration.Mode","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Mode"}]},"doc://com.apple.corenfc/documentation/CoreNFC":{"abstract":[{"type":"text","text":"Detect NFC tags, read messages that contain NDEF data, and save data to writable tags."}],"title":"Core NFC","identifier":"doc://com.apple.corenfc/documentation/CoreNFC","type":"topic","kind":"symbol","url":"/documentation/corenfc","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecatedAt":"14.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"13.0"},{"deprecatedAt":"14.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"13.0"},{"deprecatedAt":"14.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1"}],"op":"replace","path":"/metadata/platforms"},{"value":"Type Alias","op":"replace","path":"/metadata/roleHeading"},{"value":"VASMode","op":"replace","path":"/metadata/title"},{"value":"typealias","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"VASMode","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"kind":"identifier","text":"VASMode"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corenfc/documentation/CoreNFC"]]},"op":"replace","path":"/hierarchy"},{"value":[{"identifiers":["doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum/VASModeNormal"],"anchor":"Modes","title":"Modes"}],"op":"replace","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/mode-swift.property","doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/passTypeIdentifier","doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/url"],"title":"Setting Configuration Items","anchor":"Setting-Configuration-Items","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum","text":"NFCVASMode","preciseIdentifier":"c:@E@NFCVASMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"VASMode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration/title","value":"NFCVASCommandConfiguration"},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration/fragments","value":[{"text":"NFCVASCommandConfiguration","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration/navigatorTitle","value":[{"text":"NFCVASCommandConfiguration","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum~1VASModeNormal/title","value":"VASModeNormal"},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum~1VASModeNormal/fragments","value":[{"text":"VASModeNormal","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1mode-swift.property/title","value":"mode"},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1mode-swift.property/fragments","value":[{"kind":"identifier","text":"mode"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1VASMode/title","value":"VASMode"},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1VASMode/fragments","value":[{"kind":"identifier","text":"VASMode"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1VASMode/navigatorTitle","value":[{"text":"VASMode","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1passTypeIdentifier/title","value":"passTypeIdentifier"},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1passTypeIdentifier/fragments","value":[{"text":"passTypeIdentifier","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1url/title","value":"url"},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1url/fragments","value":[{"kind":"identifier","text":"url"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/title","value":"NFCVASMode"},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/fragments","value":[{"text":"NFCVASMode","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/navigatorTitle","value":[{"kind":"identifier","text":"NFCVASMode"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}