{
  "abstract": [
    {
      "text": "Tells the delegate that the user is authorizing the payment request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewControllerWillAuthorizePayment(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PKPaymentAuthorizationViewControllerDelegate(im)paymentAuthorizationViewControllerWillAuthorizePayment:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "paymentAuthorizationViewControllerWillAuthorizePayment"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationViewController",
        "text": "PKPaymentAuthorizationViewController"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "paymentAuthorizationViewControllerWillAuthorizePayment:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "paymentAuthorizationViewControllerWillAuthorizePayment(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationViewControllerWillAuthorizePayment"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationViewController",
              "text": "PKPaymentAuthorizationViewController"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The payment authorization view controller.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "controller"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called before the payment request is authorized but after the user has authenticated by using either a passcode, Touch ID, or Face ID.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController": {
      "abstract": [
        {
          "text": "An object that presents a sheet that prompts the user to authorize a payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationViewController"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate": {
      "abstract": [
        {
          "text": "Methods that let you respond to user interactions with your payment authorization view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didAuthorizePayment:completion:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user authorized the payment request, and asks for a result.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationViewController",
          "text": "PKPaymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAuthorizePayment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPayment",
          "text": "PKPayment"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentAuthorizationStatus",
          "text": "PKPaymentAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didAuthorizePayment:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewController:didAuthorizePayment:completion:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationViewController(_:didAuthorizePayment:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate/paymentauthorizationviewcontroller(_:didauthorizepayment:completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didAuthorizePayment:handler:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user authorized the payment request, and asks for a result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationViewController",
          "text": "PKPaymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAuthorizePayment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPayment",
          "text": "PKPayment"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationResult",
          "text": "PKPaymentAuthorizationResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didAuthorizePayment:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewController:didAuthorizePayment:handler:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationViewController(_:didAuthorizePayment:handler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate/paymentauthorizationviewcontroller(_:didauthorizepayment:handler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didRequestMerchantSessionUpdate:)": {
      "abstract": [
        {
          "text": "Requests an object that validates the identity of a merchant for a payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationViewController",
          "text": "PKPaymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRequestMerchantSessionUpdate"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentRequestMerchantSessionUpdate",
          "text": "PKPaymentRequestMerchantSessionUpdate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didRequestMerchantSessionUpdate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewController:didRequestMerchantSessionUpdate:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationViewController(_:didRequestMerchantSessionUpdate:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate/paymentauthorizationviewcontroller(_:didrequestmerchantsessionupdate:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didSelect:completion:)-30s85": {
      "abstract": [
        {
          "text": "Tells the delegate that the user changed the payment method, and asks for an updated payment request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationViewController",
          "text": "PKPaymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentMethod",
          "text": "PKPaymentMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentSummaryItem",
          "text": "PKPaymentSummaryItem"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didSelect:completion:)-30s85",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewController:didSelectPaymentMethod:completion:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationViewController(_:didSelect:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate/paymentauthorizationviewcontroller(_:didselect:completion:)-30s85"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didSelect:handler:)-3bex6": {
      "abstract": [
        {
          "text": "Tells the delegate that the user changed the payment method, and asks for an updated payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationViewController",
          "text": "PKPaymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentMethod",
          "text": "PKPaymentMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentRequestPaymentMethodUpdate",
          "text": "PKPaymentRequestPaymentMethodUpdate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didSelect:handler:)-3bex6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewController:didSelectPaymentMethod:handler:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationViewController(_:didSelect:handler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate/paymentauthorizationviewcontroller(_:didselect:handler:)-3bex6"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewControllerDidFinish(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that payment authorization finished.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewControllerDidFinish"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationViewController",
          "text": "PKPaymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewControllerDidFinish(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewControllerDidFinish:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "paymentAuthorizationViewControllerDidFinish(_:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate/paymentauthorizationviewcontrollerdidfinish(_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewControllerWillAuthorizePayment(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user is authorizing the payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewControllerWillAuthorizePayment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationViewController",
          "text": "PKPaymentAuthorizationViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewControllerWillAuthorizePayment(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentAuthorizationViewControllerWillAuthorizePayment:"
        }
      ],
      "role": "symbol",
      "title": "paymentAuthorizationViewControllerWillAuthorizePayment(_:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate/paymentauthorizationviewcontrollerwillauthorizepayment(_:)"
    },
    "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/index.html#//apple_ref/doc/uid/TP40012195": {
      "identifier": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/index.html#//apple_ref/doc/uid/TP40012195",
      "title": "Wallet Developer Guide",
      "titleInlineContent": [
        {
          "text": "Wallet Developer Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/index.html#//apple_ref/doc/uid/TP40012195"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/index.html#//apple_ref/doc/uid/TP40012195"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Handling-users-payment-authorization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didRequestMerchantSessionUpdate:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didAuthorizePayment:handler:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didAuthorizePayment:completion:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewControllerDidFinish(_:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didSelect:handler:)-3bex6",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didSelect:completion:)-30s85"
      ],
      "title": "Handling user’s payment authorization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "paymentAuthorizationViewControllerWillAuthorizePayment:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationViewControllerWillAuthorizePayment:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/index.html#//apple_ref/doc/uid/TP40012195"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Handling-users-payment-authorization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didRequestMerchantSessionUpdate:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didAuthorizePayment:handler:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didAuthorizePayment:completion:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewControllerDidFinish(_:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didSelect:handler:)-3bex6",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewControllerDelegate/paymentAuthorizationViewController(_:didSelect:completion:)-30s85"
              ],
              "title": "Handling user’s payment authorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "paymentAuthorizationViewControllerWillAuthorizePayment:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PKPaymentAuthorizationViewController",
                    "text": "PKPaymentAuthorizationViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "controller"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The payment authorization view controller.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "controller"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewController(_:didSelect:completion:)-30s85/title",
          "value": "paymentAuthorizationViewController:didSelectPaymentMethod:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewController(_:didSelect:completion:)-30s85/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationViewController:didSelectPaymentMethod:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewControllerDidFinish(_:)/title",
          "value": "paymentAuthorizationViewControllerDidFinish:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewControllerDidFinish(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationViewControllerDidFinish:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewController(_:didSelect:handler:)-3bex6/title",
          "value": "paymentAuthorizationViewController:didSelectPaymentMethod:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewController(_:didSelect:handler:)-3bex6/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationViewController:didSelectPaymentMethod:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewController(_:didRequestMerchantSessionUpdate:)/title",
          "value": "paymentAuthorizationViewController:didRequestMerchantSessionUpdate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewController(_:didRequestMerchantSessionUpdate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationViewController:didRequestMerchantSessionUpdate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate/title",
          "value": "PKPaymentAuthorizationViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewController/title",
          "value": "PKPaymentAuthorizationViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewController(_:didAuthorizePayment:completion:)/title",
          "value": "paymentAuthorizationViewController:didAuthorizePayment:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewController(_:didAuthorizePayment:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationViewController:didAuthorizePayment:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewControllerWillAuthorizePayment(_:)/title",
          "value": "paymentAuthorizationViewControllerWillAuthorizePayment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewControllerWillAuthorizePayment(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationViewControllerWillAuthorizePayment:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewController(_:didAuthorizePayment:handler:)/title",
          "value": "paymentAuthorizationViewController:didAuthorizePayment:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewControllerDelegate~1paymentAuthorizationViewController(_:didAuthorizePayment:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "paymentAuthorizationViewController:didAuthorizePayment:handler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate/paymentauthorizationviewcontrollerwillauthorizepayment(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate/paymentauthorizationviewcontrollerwillauthorizepayment(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
