{
  "abstract": [
    {
      "text": "The view does not include tabs and has no border.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTabView",
        "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/noTabsNoBorder"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTabViewType@NSNoTabsNoBorder",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "noTabsNoBorder"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSNoTabsNoBorder"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTabView.TabType.noTabsNoBorder"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "noTabsNoBorder"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView": {
      "abstract": [
        {
          "text": "A multipage interface that displays one page at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTabView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTabView"
        }
      ],
      "role": "symbol",
      "title": "NSTabView",
      "type": "topic",
      "url": "/documentation/appkit/nstabview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType": {
      "abstract": [
        {
          "text": "These constants specify the tab view’s type as used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/tabViewType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TabType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TabType"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabType",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/bottomTabsBezelBorder": {
      "abstract": [
        {
          "text": "Tabs are on the bottom of the view with a bezeled border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomTabsBezelBorder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/bottomTabsBezelBorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBottomTabsBezelBorder"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabType.bottomTabsBezelBorder",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabtype/bottomtabsbezelborder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/leftTabsBezelBorder": {
      "abstract": [
        {
          "text": "Tabs are on the left of the view with a bezeled border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftTabsBezelBorder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/leftTabsBezelBorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLeftTabsBezelBorder"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabType.leftTabsBezelBorder",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabtype/lefttabsbezelborder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/noTabsBezelBorder": {
      "abstract": [
        {
          "text": "The view does not include tabs and has a bezeled border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noTabsBezelBorder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/noTabsBezelBorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNoTabsBezelBorder"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabType.noTabsBezelBorder",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabtype/notabsbezelborder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/noTabsLineBorder": {
      "abstract": [
        {
          "text": "The view does not include tabs and has a lined border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noTabsLineBorder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/noTabsLineBorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNoTabsLineBorder"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabType.noTabsLineBorder",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabtype/notabslineborder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/noTabsNoBorder": {
      "abstract": [
        {
          "text": "The view does not include tabs and has no border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noTabsNoBorder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/noTabsNoBorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNoTabsNoBorder"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabType.noTabsNoBorder",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabtype/notabsnoborder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/rightTabsBezelBorder": {
      "abstract": [
        {
          "text": "Tabs are on the right of the view with a bezeled border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightTabsBezelBorder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/rightTabsBezelBorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRightTabsBezelBorder"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabType.rightTabsBezelBorder",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabtype/righttabsbezelborder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/topTabsBezelBorder": {
      "abstract": [
        {
          "text": "The view includes tabs on the top of the view and has a bezeled border (the default).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topTabsBezelBorder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/topTabsBezelBorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTopTabsBezelBorder"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabType.topTabsBezelBorder",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabtype/toptabsbezelborder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/tabViewType": {
      "abstract": [
        {
          "text": "The tab type to display the tabs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabViewType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTabView",
          "text": "NSTabView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTabViewType",
          "text": "TabType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/tabViewType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabViewType"
        }
      ],
      "role": "symbol",
      "title": "tabViewType",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabviewtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/topTabsBezelBorder",
        "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/noTabsBezelBorder",
        "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/noTabsLineBorder",
        "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/bottomTabsBezelBorder",
        "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/leftTabsBezelBorder",
        "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/rightTabsBezelBorder"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSNoTabsNoBorder"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoTabsNoBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/topTabsBezelBorder",
                "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/noTabsBezelBorder",
                "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/noTabsLineBorder",
                "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/bottomTabsBezelBorder",
                "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/leftTabsBezelBorder",
                "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabType/rightTabsBezelBorder"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSNoTabsNoBorder"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1noTabsBezelBorder/title",
          "value": "NSNoTabsBezelBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1noTabsBezelBorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoTabsBezelBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1noTabsNoBorder/title",
          "value": "NSNoTabsNoBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1noTabsNoBorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoTabsNoBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1topTabsBezelBorder/title",
          "value": "NSTopTabsBezelBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1topTabsBezelBorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTopTabsBezelBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView/title",
          "value": "NSTabView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1bottomTabsBezelBorder/title",
          "value": "NSBottomTabsBezelBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1bottomTabsBezelBorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBottomTabsBezelBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1leftTabsBezelBorder/title",
          "value": "NSLeftTabsBezelBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1leftTabsBezelBorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLeftTabsBezelBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1noTabsLineBorder/title",
          "value": "NSNoTabsLineBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1noTabsLineBorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoTabsLineBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType/title",
          "value": "NSTabViewType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabViewType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabViewType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1tabViewType/title",
          "value": "tabViewType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1tabViewType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabViewType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1rightTabsBezelBorder/title",
          "value": "NSRightTabsBezelBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabType~1rightTabsBezelBorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRightTabsBezelBorder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstabview/tabtype/notabsnoborder"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstabview/tabtype/notabsnoborder"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
