{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"edges","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSDirectionalRectEdge","text":"NSDirectionalRectEdge","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDirectionalRectEdge"},{"text":", ","kind":"text"},{"text":"fractionalOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor"]]},"metadata":{"title":"init(edges:fractionalOffset:)","role":"symbol","platforms":[{"name":"macOS","introducedAt":"10.15","unavailable":false,"beta":false,"deprecated":false}],"modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"edges"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSDirectionalRectEdge","kind":"typeIdentifier","text":"NSDirectionalRectEdge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fractionalOffset"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint"},{"kind":"text","text":")"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"layoutAnchorWithEdges:fractionalOffset:"}],"symbolKind":"init","externalID":"c:objc(cs)NSCollectionLayoutAnchor(cm)layoutAnchorWithEdges:fractionalOffset:"},"abstract":[{"type":"text","text":"Creates an anchor with the specified edges to attach to, offset by the provided fractional value."}],"seeAlsoSections":[{"title":"Creating an anchor","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:absoluteOffset:)"],"anchor":"Creating-an-anchor"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscollectionlayoutanchor/init(edges:fractionaloffset:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscollectionlayoutanchor/init(edges:fractionaloffset:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:fractionalOffset:)"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:fractionalOffset:)":{"title":"init(edges:fractionalOffset:)","abstract":[{"type":"text","text":"Creates an anchor with the specified edges to attach to, offset by the provided fractional value."}],"role":"symbol","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"edges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalRectEdge","preciseIdentifier":"c:@E@NSDirectionalRectEdge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fractionalOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/appkit/nscollectionlayoutanchor/init(edges:fractionaloffset:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:fractionalOffset:)","navigatorTitle":[{"kind":"identifier","text":"layoutAnchorWithEdges:fractionalOffset:"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@NSPoint":{"abstract":[{"text":"A point in a Cartesian coordinate system.","type":"text"}],"url":"/documentation/foundation/nspoint","kind":"symbol","role":"symbol","title":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","type":"topic","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSPoint","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:absoluteOffset:)":{"role":"symbol","title":"init(edges:absoluteOffset:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates an anchor with the specified edges to attach to, offset by the provided absolute value."}],"url":"/documentation/appkit/nscollectionlayoutanchor/init(edges:absoluteoffset:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:absoluteOffset:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"edges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalRectEdge","preciseIdentifier":"c:@E@NSDirectionalRectEdge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"absoluteOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"layoutAnchorWithEdges:absoluteOffset:"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDirectionalRectEdge":{"role":"symbol","type":"topic","title":"NSDirectionalRectEdge","url":"/documentation/appkit/nsdirectionalrectedge","navigatorTitle":[{"kind":"identifier","text":"NSDirectionalRectEdge"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDirectionalRectEdge","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDirectionalRectEdge"}],"abstract":[]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor":{"url":"/documentation/appkit/nscollectionlayoutanchor","kind":"symbol","navigatorTitle":[{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSCollectionLayoutAnchor","abstract":[{"type":"text","text":"An object that defines how to attach a supplementary item to an item in a collection view."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:)":{"title":"init(edges:)","abstract":[{"type":"text","text":"Creates an anchor with the specified edges to attach to."}],"role":"symbol","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"edges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalRectEdge","preciseIdentifier":"c:@E@NSDirectionalRectEdge"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/appkit/nscollectionlayoutanchor/init(edges:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:)","navigatorTitle":[{"kind":"identifier","text":"layoutAnchorWithEdges:"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"introducedAt":"10.15","name":"macOS","unavailable":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Type Method"},{"op":"replace","path":"/metadata/title","value":"layoutAnchorWithEdges:fractionalOffset:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"+ ","kind":"text"},{"text":"layoutAnchorWithEdges:fractionalOffset:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:absoluteOffset:)"],"anchor":"Creating-an-anchor","title":"Creating an anchor"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"layoutAnchorWithEdges:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDirectionalRectEdge","kind":"typeIdentifier","text":"NSDirectionalRectEdge","preciseIdentifier":"c:@E@NSDirectionalRectEdge"},{"kind":"text","text":") "},{"kind":"internalParam","text":"edges"},{"text":" ","kind":"text"},{"text":"fractionalOffset:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":") ","kind":"text"},{"text":"fractionalOffset","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:fractionalOffset:)/title","value":"layoutAnchorWithEdges:fractionalOffset:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:fractionalOffset:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"layoutAnchorWithEdges:fractionalOffset:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:absoluteOffset:)/title","value":"layoutAnchorWithEdges:absoluteOffset:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:absoluteOffset:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"layoutAnchorWithEdges:absoluteOffset:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalRectEdge/title","value":"NSDirectionalRectEdge","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalRectEdge/fragments","value":[{"text":"NSDirectionalRectEdge","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalRectEdge/navigatorTitle","value":[{"text":"NSDirectionalRectEdge","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor/title","value":"NSCollectionLayoutAnchor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor/fragments","value":[{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor/navigatorTitle","value":[{"kind":"identifier","text":"NSCollectionLayoutAnchor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:)/title","value":"layoutAnchorWithEdges:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"layoutAnchorWithEdges:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}