{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor"]]},"kind":"symbol","seeAlsoSections":[{"title":"Getting the offset","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isAbsoluteOffset","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isFractionalOffset"],"anchor":"Getting-the-offset","generated":true}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/offset","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The floating-point value of the anchor’s offset from the item it’s attached to."}],"metadata":{"externalID":"c:objc(cs)NSCollectionLayoutAnchor(py)offset","navigatorTitle":[{"kind":"identifier","text":"offset"}],"platforms":[{"unavailable":false,"introducedAt":"10.15","name":"macOS","beta":false,"deprecated":false}],"title":"offset","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offset","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"AppKit"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/appkit/nscollectionlayoutanchor/offset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscollectionlayoutanchor/offset"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isAbsoluteOffset":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isAbsoluteOffset","url":"/documentation/appkit/nscollectionlayoutanchor/isabsoluteoffset","title":"isAbsoluteOffset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isAbsoluteOffset"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the anchor’s offset is expressed as an absolute value."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAbsoluteOffset"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/offset":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/offset","url":"/documentation/appkit/nscollectionlayoutanchor/offset","title":"offset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"offset"}],"abstract":[{"type":"text","text":"The floating-point value of the anchor’s offset from the item it’s attached to."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"offset"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isFractionalOffset":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isFractionalOffset","url":"/documentation/appkit/nscollectionlayoutanchor/isfractionaloffset","title":"isFractionalOffset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFractionalOffset"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the anchor’s offset is expressed as a fraction of its supplementary item’s dimension."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFractionalOffset"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor":{"url":"/documentation/appkit/nscollectionlayoutanchor","kind":"symbol","navigatorTitle":[{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSCollectionLayoutAnchor","abstract":[{"type":"text","text":"An object that defines how to attach a supplementary item to an item in a collection view."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor"},"doc://com.externally.resolved.symbol/c:@T@NSPoint":{"abstract":[{"text":"A point in a Cartesian coordinate system.","type":"text"}],"url":"/documentation/foundation/nspoint","kind":"symbol","role":"symbol","title":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","type":"topic","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSPoint","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"10.15"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"offset","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"offset"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor"]]},"path":"/hierarchy","op":"replace"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Getting the offset","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isAbsoluteOffset","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isFractionalOffset"],"anchor":"Getting-the-offset","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"offset"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"isAbsoluteOffset","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1isAbsoluteOffset/title","op":"replace"},{"value":[{"text":"isAbsoluteOffset","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1isAbsoluteOffset/fragments","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1offset/title","op":"replace","value":"offset"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1offset/fragments","op":"replace","value":[{"kind":"identifier","text":"offset"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1isFractionalOffset/title","op":"replace","value":"isFractionalOffset"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1isFractionalOffset/fragments","op":"replace","value":[{"kind":"identifier","text":"isFractionalOffset"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor/title","op":"replace","value":"NSCollectionLayoutAnchor"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor/fragments","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutAnchor"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutAnchor"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}