{
  "abstract": [
    {
      "text": "Specifies that the printed content consists of mixed text, graphics, and images. The default paper is Letter, A4, or similar locale-specific designation. Output is normal quality, duplex.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/general"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIPrintInfoOutputType@UIPrintInfoOutputGeneral",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "general"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPrintInfoOutputGeneral"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIPrintInfo.OutputType.general"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "general"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo": {
      "abstract": [
        {
          "text": "Information about a print job that the system uses when it prints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the output type, which is an indication of the type of content the app is drawing or providing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OutputType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OutputType"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.OutputType",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/general": {
      "abstract": [
        {
          "text": "Specifies that the printed content consists of mixed text, graphics, and images. The default paper is Letter, A4, or similar locale-specific designation. Output is normal quality, duplex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "general"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/general",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInfoOutputGeneral"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.OutputType.general",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.enum/general"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/grayscale": {
      "abstract": [
        {
          "text": "Specifies that the printed content is grayscale. Set the output type to this value when your printable content contains no color—for example, it’s black text only. The default paper is Letter/A4. Output is grayscale quality, duplex. This content type can produce a performance improvement in some cases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "grayscale"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/grayscale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInfoOutputGrayscale"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.OutputType.grayscale",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.enum/grayscale"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photo": {
      "abstract": [
        {
          "text": "Specifies that the printed content consists of black-and-white or color images. The default paper is 4x6, A6, or similar locale-specific designation. Output is high quality, simplex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInfoOutputPhoto"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.OutputType.photo",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.enum/photo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photoGrayscale": {
      "abstract": [
        {
          "text": "Specifies that the printed content is a grayscale image. Set the output type to this value when your printable content contains no color—for example, it’s black text only. The default paper is Letter/A4. Output is high quality grayscale, duplex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoGrayscale"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photoGrayscale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInfoOutputPhotoGrayscale"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo.OutputType.photoGrayscale",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo/outputtype-swift.enum/photograyscale"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photo",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/grayscale",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photoGrayscale"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPrintInfoOutputGeneral"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputGeneral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photo",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/grayscale",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo/OutputType-swift.enum/photoGrayscale"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIPrintInfoOutputGeneral"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo/title",
          "value": "UIPrintInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1photoGrayscale/title",
          "value": "UIPrintInfoOutputPhotoGrayscale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1photoGrayscale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputPhotoGrayscale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1photo/title",
          "value": "UIPrintInfoOutputPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1photo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum/title",
          "value": "UIPrintInfoOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1grayscale/title",
          "value": "UIPrintInfoOutputGrayscale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1grayscale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputGrayscale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1general/title",
          "value": "UIPrintInfoOutputGeneral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo~1OutputType-swift.enum~1general/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfoOutputGeneral"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiprintinfo/outputtype-swift.enum/general"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiprintinfo/outputtype-swift.enum/general"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
