{
  "abstract": [
    {
      "text": "An alert sheet with side-by-side buttons.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle/sideBySideButtonsAlert"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKAlertControllerStyle@WKAlertControllerStyleSideBySideButtonsAlert",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sideBySideButtonsAlert"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKAlertControllerStyleSideBySideButtonsAlert"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKAlertControllerStyle.sideBySideButtonsAlert"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sideBySideButtonsAlert"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle": {
      "abstract": [
        {
          "text": "Constants indicating the styles for standard system alerts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAlertControllerStyle"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAlertControllerStyle"
        }
      ],
      "role": "symbol",
      "title": "WKAlertControllerStyle",
      "type": "topic",
      "url": "/documentation/watchkit/wkalertcontrollerstyle"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle/actionSheet": {
      "abstract": [
        {
          "text": "An action sheet style. Action sheets are modal sheets that can be dismissed using the Cancel button in the top-left corner of the sheet. You can also add one or two custom buttons to perform related tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionSheet"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle/actionSheet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAlertControllerStyleActionSheet"
        }
      ],
      "role": "symbol",
      "title": "WKAlertControllerStyle.actionSheet",
      "type": "topic",
      "url": "/documentation/watchkit/wkalertcontrollerstyle/actionsheet"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle/alert": {
      "abstract": [
        {
          "text": "An alert sheet with stacked buttons. The alert sheet includes a default Cancel button at the bottom of the sheet. You can add other buttons, which are placed above the Cancel button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alert"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle/alert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAlertControllerStyleAlert"
        }
      ],
      "role": "symbol",
      "title": "WKAlertControllerStyle.alert",
      "type": "topic",
      "url": "/documentation/watchkit/wkalertcontrollerstyle/alert"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle/sideBySideButtonsAlert": {
      "abstract": [
        {
          "text": "An alert sheet with side-by-side buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sideBySideButtonsAlert"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle/sideBySideButtonsAlert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAlertControllerStyleSideBySideButtonsAlert"
        }
      ],
      "role": "symbol",
      "title": "WKAlertControllerStyle.sideBySideButtonsAlert",
      "type": "topic",
      "url": "/documentation/watchkit/wkalertcontrollerstyle/sidebysidebuttonsalert"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle/alert",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle/actionSheet"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKAlertControllerStyleSideBySideButtonsAlert"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAlertControllerStyleSideBySideButtonsAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle/alert",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAlertControllerStyle/actionSheet"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKAlertControllerStyleSideBySideButtonsAlert"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertControllerStyle~1sideBySideButtonsAlert/title",
          "value": "WKAlertControllerStyleSideBySideButtonsAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertControllerStyle~1sideBySideButtonsAlert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAlertControllerStyleSideBySideButtonsAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertControllerStyle~1actionSheet/title",
          "value": "WKAlertControllerStyleActionSheet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertControllerStyle~1actionSheet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAlertControllerStyleActionSheet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertControllerStyle~1alert/title",
          "value": "WKAlertControllerStyleAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertControllerStyle~1alert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAlertControllerStyleAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertControllerStyle/title",
          "value": "WKAlertControllerStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertControllerStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAlertControllerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAlertControllerStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAlertControllerStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkalertcontrollerstyle/sidebysidebuttonsalert"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkalertcontrollerstyle/sidebysidebuttonsalert"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
