{
  "abstract": [
    {
      "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "Accelerate",
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.3",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Accelerate"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Accelerate provides high-performance, energy-efficient computation on the CPU by leveraging its vector-processing capability. The following Accelerate libraries abstract that capability so that code written for them executes appropriate instructions for the processor available at runtime:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Subroutines for constructing and running neural networks for both training and inference.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns-library",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A wide range of image-processing functions, including Core Graphics and Core Video interoperation, format conversion, and image manipulation.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Digital signal processing functions, including 1D and 2D fast Fourier transforms, biquadratic filtering, vector and matrix arithmetic, convolution, and type conversion.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vdsp-library",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Functions for performing arithmetic and transcendental functions on vectors.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vforce-library",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Libraries for performing linear algebra on sparse and dense matrices.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ", ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/blas-library",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ", and LAPACK",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Although not part of the Accelerate framework, the following libraries are closely related:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A framework for performing multithreaded lossless compression of directories, files, and data.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/AppleArchive",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Algorithms for lossless data compression that support LZFSE, LZ4, LZMA, and ZLIB algorithms.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/Compression",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A module for performing computations on small vectors and matrices.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Spatial is a lightweight 3D mathematical library that provides a simple API for working with 3D primitives.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/spatial",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetShapeBounding(_:)": {
      "abstract": [
        {
          "text": "Returns true if the use of shape bounding is enabled, or false otherwise.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetShapeBounding"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetShapeBounding(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetShapeBounding"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsGetShapeBounding(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionsgetshapebounding(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetShapeBounding(_:_:)": {
      "abstract": [
        {
          "text": "Enables use of bounding logic in shapes (may inhibit aliasing optimizations)",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetShapeBounding"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetShapeBounding(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetShapeBounding"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetShapeBounding(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssetshapebounding(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/InitializableFromCGImage": {
      "abstract": [
        {
          "text": "A pixel format that supports initialization from a Core Graphics image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InitializableFromCGImage"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/InitializableFromCGImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InitializableFromCGImage"
        }
      ],
      "role": "symbol",
      "title": "InitializableFromCGImage",
      "type": "topic",
      "url": "/documentation/accelerate/initializablefromcgimage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/MultiplePlanePixelFormat": {
      "abstract": [
        {
          "text": "A pixel format that contains multiple homogeneous planes represented by multiple underlying vImage buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MultiplePlanePixelFormat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/MultiplePlanePixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MultiplePlanePixelFormat"
        }
      ],
      "role": "symbol",
      "title": "MultiplePlanePixelFormat",
      "type": "topic",
      "url": "/documentation/accelerate/multipleplanepixelformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/PixelFormat": {
      "abstract": [
        {
          "text": "A pixel buffer pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PixelFormat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/PixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PixelFormat"
        }
      ],
      "role": "symbol",
      "title": "PixelFormat",
      "type": "topic",
      "url": "/documentation/accelerate/pixelformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SinglePlanePixelFormat": {
      "abstract": [
        {
          "text": "A pixel format that contains a single underlying vImage buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SinglePlanePixelFormat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SinglePlanePixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SinglePlanePixelFormat"
        }
      ],
      "role": "symbol",
      "title": "SinglePlanePixelFormat",
      "type": "topic",
      "url": "/documentation/accelerate/singleplanepixelformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/StaticPixelFormat": {
      "abstract": [
        {
          "text": "A pixel format that’s known at compile time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StaticPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/StaticPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StaticPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "StaticPixelFormat",
      "type": "topic",
      "url": "/documentation/accelerate/staticpixelformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/adding-a-bokeh-effect-to-images": {
      "abstract": [
        {
          "text": "Simulate a bokeh effect by applying dilation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/adding-a-bokeh-effect-to-images",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adding a bokeh effect to images",
      "type": "topic",
      "url": "/documentation/accelerate/adding-a-bokeh-effect-to-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/adjusting-saturation-and-applying-tone-mapping": {
      "abstract": [
        {
          "text": "Convert an RGB image to discrete luminance and chrominance channels, and apply color and contrast treatments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/adjusting-saturation-and-applying-tone-mapping",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adjusting saturation and applying tone mapping",
      "type": "topic",
      "url": "/documentation/accelerate/adjusting-saturation-and-applying-tone-mapping"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-brightness-and-contrast-of-an-image": {
      "abstract": [
        {
          "text": "Use a gamma function to apply a linear or exponential curve.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-brightness-and-contrast-of-an-image",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adjusting the brightness and contrast of an image",
      "type": "topic",
      "url": "/documentation/accelerate/adjusting-the-brightness-and-contrast-of-an-image"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-hue-of-an-image": {
      "abstract": [
        {
          "text": "Convert an image to L*a*b* color space and apply hue adjustment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-hue-of-an-image",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adjusting the hue of an image",
      "type": "topic",
      "url": "/documentation/accelerate/adjusting-the-hue-of-an-image"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-biquadratic-filters-to-a-music-loop": {
      "abstract": [
        {
          "text": "Change the frequency response of an audio signal using a cascaded biquadratic filter.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-biquadratic-filters-to-a-music-loop",
      "kind": "article",
      "role": "sampleCode",
      "title": "Applying biquadratic filters to a music loop",
      "type": "topic",
      "url": "/documentation/accelerate/applying-biquadratic-filters-to-a-music-loop"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-color-transforms-to-images-with-a-multidimensional-lookup-table": {
      "abstract": [
        {
          "text": "Precompute translation values to optimize color space conversion and other pointwise operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-color-transforms-to-images-with-a-multidimensional-lookup-table",
      "kind": "article",
      "role": "article",
      "title": "Applying color transforms to images with a multidimensional lookup table",
      "type": "topic",
      "url": "/documentation/accelerate/applying-color-transforms-to-images-with-a-multidimensional-lookup-table"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-geometric-transforms-to-images": {
      "abstract": [
        {
          "text": "Reflect, shear, rotate, and scale image buffers using vImage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-geometric-transforms-to-images",
      "kind": "article",
      "role": "article",
      "title": "Applying geometric transforms to images",
      "type": "topic",
      "url": "/documentation/accelerate/applying-geometric-transforms-to-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images": {
      "abstract": [
        {
          "text": "Use the vImage library’s polynomial transform to apply tone curve adjustments to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images",
      "kind": "article",
      "role": "sampleCode",
      "title": "Applying tone curve adjustments to images",
      "type": "topic",
      "url": "/documentation/accelerate/applying-tone-curve-adjustments-to-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-vimage-operations-to-regions-of-interest": {
      "abstract": [
        {
          "text": "Limit the effect of vImage operations to rectangular regions of interest.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-vimage-operations-to-regions-of-interest",
      "kind": "article",
      "role": "article",
      "title": "Applying vImage operations to regions of interest",
      "type": "topic",
      "url": "/documentation/accelerate/applying-vimage-operations-to-regions-of-interest"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-vimage-operations-to-video-sample-buffers": {
      "abstract": [
        {
          "text": "Use the vImage convert-any-to-any functionality to perform real-time image processing of video frames streamed from your device’s camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-vimage-operations-to-video-sample-buffers",
      "kind": "article",
      "role": "sampleCode",
      "title": "Applying vImage operations to video sample buffers",
      "type": "topic",
      "url": "/documentation/accelerate/applying-vimage-operations-to-video-sample-buffers"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/biquadratic-iir-filters": {
      "abstract": [
        {
          "text": "Apply biquadratic filters to single-channel and multichannel data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/biquadratic-iir-filters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Biquadratic IIR filters",
      "type": "topic",
      "url": "/documentation/accelerate/biquadratic-iir-filters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/blas-library": {
      "abstract": [
        {
          "text": "Perform common linear algebra operations with Apple’s implementation of the Basic Linear Algebra Subprograms (BLAS).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/blas-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "BLAS",
      "type": "topic",
      "url": "/documentation/accelerate/blas-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/blurring-an-image": {
      "abstract": [
        {
          "text": "Filter an image by convolving it with custom and high-speed kernels.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/blurring-an-image",
      "kind": "article",
      "role": "sampleCode",
      "title": "Blurring an image",
      "type": "topic",
      "url": "/documentation/accelerate/blurring-an-image"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns-library": {
      "abstract": [
        {
          "text": "Implement and run neural networks for training and inference.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "BNNS",
      "type": "topic",
      "url": "/documentation/accelerate/bnns-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow": {
      "abstract": [
        {
          "text": "Learn the fundamentals of the convert-any-to-any function by converting a CMYK image to an RGB image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow",
      "kind": "article",
      "role": "article",
      "title": "Building a basic image conversion workflow",
      "type": "topic",
      "url": "/documentation/accelerate/building-a-basic-image-conversion-workflow"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-processing-workflow": {
      "abstract": [
        {
          "text": "Resize an image with vImage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-processing-workflow",
      "kind": "article",
      "role": "article",
      "title": "Building a Basic Image-Processing Workflow",
      "type": "topic",
      "url": "/documentation/accelerate/building-a-basic-image-processing-workflow"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending": {
      "abstract": [
        {
          "text": "Combine two images by using alpha blending to create a single output.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending",
      "kind": "article",
      "role": "article",
      "title": "Compositing images with alpha blending",
      "type": "topic",
      "url": "/documentation/accelerate/compositing-images-with-alpha-blending"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-vimage-blend-modes": {
      "abstract": [
        {
          "text": "Combine two images by using blend modes to create a single output.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-vimage-blend-modes",
      "kind": "article",
      "role": "article",
      "title": "Compositing images with vImage blend modes",
      "type": "topic",
      "url": "/documentation/accelerate/compositing-images-with-vimage-blend-modes"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/compressing-an-image-using-linear-algebra": {
      "abstract": [
        {
          "text": "Reduce the storage size of an image using singular value decomposition (SVD).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/compressing-an-image-using-linear-algebra",
      "kind": "article",
      "role": "sampleCode",
      "title": "Compressing an image using linear algebra",
      "type": "topic",
      "url": "/documentation/accelerate/compressing-an-image-using-linear-algebra"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-data-with-buffer-compression": {
      "abstract": [
        {
          "text": "Compress a string, write it to the file system, and decompress the same file using buffer compression.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-data-with-buffer-compression",
      "kind": "article",
      "role": "article",
      "title": "Compressing and decompressing data with buffer compression",
      "type": "topic",
      "url": "/documentation/accelerate/compressing-and-decompressing-data-with-buffer-compression"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-data-with-input-and-output-filters": {
      "abstract": [
        {
          "text": "Compress and decompress streamed or from-memory data, using input and output filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-data-with-input-and-output-filters",
      "kind": "article",
      "role": "article",
      "title": "Compressing and decompressing data with input and output filters",
      "type": "topic",
      "url": "/documentation/accelerate/compressing-and-decompressing-data-with-input-and-output-filters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-files-with-stream-compression": {
      "abstract": [
        {
          "text": "Perform compression or the appropriate kind of decompression to a file based on its path extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-files-with-stream-compression",
      "kind": "article",
      "role": "sampleCode",
      "title": "Compressing and Decompressing Files with Stream Compression",
      "type": "topic",
      "url": "/documentation/accelerate/compressing-and-decompressing-files-with-stream-compression"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-saving-a-string-to-the-file-system": {
      "abstract": [
        {
          "text": "Compress the contents of a Unicode string and store the result on the file system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-saving-a-string-to-the-file-system",
      "kind": "article",
      "role": "article",
      "title": "Compressing and saving a string to the file system",
      "type": "topic",
      "url": "/documentation/accelerate/compressing-and-saving-a-string-to-the-file-system"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/compressing-file-system-directories": {
      "abstract": [
        {
          "text": "Compress the contents of an entire directory and store the result on the file system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/compressing-file-system-directories",
      "kind": "article",
      "role": "article",
      "title": "Compressing file system directories",
      "type": "topic",
      "url": "/documentation/accelerate/compressing-file-system-directories"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/compressing-single-files": {
      "abstract": [
        {
          "text": "Compress a single file and store the result on the file system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/compressing-single-files",
      "kind": "article",
      "role": "article",
      "title": "Compressing single files",
      "type": "topic",
      "url": "/documentation/accelerate/compressing-single-files"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/controlling-vdsp-operations-with-stride": {
      "abstract": [
        {
          "text": "Operate selectively on the elements of a vector at regular intervals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/controlling-vdsp-operations-with-stride",
      "kind": "article",
      "role": "article",
      "title": "Controlling vDSP operations with stride",
      "type": "topic",
      "url": "/documentation/accelerate/controlling-vdsp-operations-with-stride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/conversion": {
      "abstract": [
        {
          "text": "Convert an image to a different format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/conversion",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Conversion",
      "type": "topic",
      "url": "/documentation/accelerate/conversion"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/converting-bitmap-data-between-core-graphics-images-and-vimage-buffers": {
      "abstract": [
        {
          "text": "Pass image data between Core Graphics and vImage to create and manipulate images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/converting-bitmap-data-between-core-graphics-images-and-vimage-buffers",
      "kind": "article",
      "role": "article",
      "title": "Converting bitmap data between Core Graphics images and vImage buffers",
      "type": "topic",
      "url": "/documentation/accelerate/converting-bitmap-data-between-core-graphics-images-and-vimage-buffers"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/converting-color-images-to-grayscale": {
      "abstract": [
        {
          "text": "Convert an RGB image to grayscale using matrix multiplication.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/converting-color-images-to-grayscale",
      "kind": "article",
      "role": "sampleCode",
      "title": "Converting color images to grayscale",
      "type": "topic",
      "url": "/documentation/accelerate/converting-color-images-to-grayscale"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/converting-luminance-and-chrominance-planes-to-an-argb-image": {
      "abstract": [
        {
          "text": "Create a displayable ARGB image using the luminance and chrominance information from your device’s camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/converting-luminance-and-chrominance-planes-to-an-argb-image",
      "kind": "article",
      "role": "sampleCode",
      "title": "Converting luminance and chrominance planes to an ARGB image",
      "type": "topic",
      "url": "/documentation/accelerate/converting-luminance-and-chrominance-planes-to-an-argb-image"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/convolution": {
      "abstract": [
        {
          "text": "Apply a convolution kernel to an image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/convolution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Convolution",
      "type": "topic",
      "url": "/documentation/accelerate/convolution"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/core-video-interoperability": {
      "abstract": [
        {
          "text": "Pass image data between Core Video and vImage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/core-video-interoperability",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video interoperability",
      "type": "topic",
      "url": "/documentation/accelerate/core-video-interoperability"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/creating-a-core-graphics-image-from-a-vimage-buffer": {
      "abstract": [
        {
          "text": "Create displayable representations of vImage buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/creating-a-core-graphics-image-from-a-vimage-buffer",
      "kind": "article",
      "role": "article",
      "title": "Creating a Core Graphics Image from a vImage Buffer",
      "type": "topic",
      "url": "/documentation/accelerate/creating-a-core-graphics-image-from-a-vimage-buffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/creating-a-sparse-matrix-from-coordinate-format-arrays": {
      "abstract": [
        {
          "text": "Use separate coordinate format arrays to create sparse matrices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/creating-a-sparse-matrix-from-coordinate-format-arrays",
      "kind": "article",
      "role": "article",
      "title": "Creating a sparse matrix from coordinate format arrays",
      "type": "topic",
      "url": "/documentation/accelerate/creating-a-sparse-matrix-from-coordinate-format-arrays"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/creating-and-populating-buffers-from-core-graphics-images": {
      "abstract": [
        {
          "text": "Initialize vImage buffers from Core Graphics images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/creating-and-populating-buffers-from-core-graphics-images",
      "kind": "article",
      "role": "article",
      "title": "Creating and Populating Buffers from Core Graphics Images",
      "type": "topic",
      "url": "/documentation/accelerate/creating-and-populating-buffers-from-core-graphics-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/creating-sparse-matrices": {
      "abstract": [
        {
          "text": "Create sparse matrices for factorization and solving systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/creating-sparse-matrices",
      "kind": "article",
      "role": "article",
      "title": "Creating sparse matrices",
      "type": "topic",
      "url": "/documentation/accelerate/creating-sparse-matrices"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/decompressing-and-extracting-an-archived-directory": {
      "abstract": [
        {
          "text": "Recreate an entire file system directory from an archive file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/decompressing-and-extracting-an-archived-directory",
      "kind": "article",
      "role": "article",
      "title": "Decompressing and extracting an archived directory",
      "type": "topic",
      "url": "/documentation/accelerate/decompressing-and-extracting-an-archived-directory"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/decompressing-and-parsing-an-archived-string": {
      "abstract": [
        {
          "text": "Recreate a string from an archive file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/decompressing-and-parsing-an-archived-string",
      "kind": "article",
      "role": "article",
      "title": "Decompressing and Parsing an Archived String",
      "type": "topic",
      "url": "/documentation/accelerate/decompressing-and-parsing-an-archived-string"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/decompressing-single-files": {
      "abstract": [
        {
          "text": "Recreate a single file from a compressed file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/decompressing-single-files",
      "kind": "article",
      "role": "article",
      "title": "Decompressing single files",
      "type": "topic",
      "url": "/documentation/accelerate/decompressing-single-files"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/discrete-cosine-transforms": {
      "abstract": [
        {
          "text": "Transform vectors of temporal and spatial domain real values to the frequency domain, and vice versa.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/discrete-cosine-transforms",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Discrete Cosine transforms",
      "type": "topic",
      "url": "/documentation/accelerate/discrete-cosine-transforms"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/discrete-fourier-transforms": {
      "abstract": [
        {
          "text": "Transform vectors of temporal and spatial domain complex values to the frequency domain, and vice versa.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/discrete-fourier-transforms",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Discrete Fourier transforms",
      "type": "topic",
      "url": "/documentation/accelerate/discrete-fourier-transforms"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/enhancing-image-contrast-with-histogram-manipulation": {
      "abstract": [
        {
          "text": "Enhance and adjust the contrast of an image with histogram equalization and contrast stretching.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/enhancing-image-contrast-with-histogram-manipulation",
      "kind": "article",
      "role": "article",
      "title": "Enhancing image contrast with histogram manipulation",
      "type": "topic",
      "url": "/documentation/accelerate/enhancing-image-contrast-with-histogram-manipulation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/equalizing-audio-with-discrete-cosine-transforms-dcts": {
      "abstract": [
        {
          "text": "Change the frequency response of an audio signal by manipulating frequency-domain data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/equalizing-audio-with-discrete-cosine-transforms-dcts",
      "kind": "article",
      "role": "sampleCode",
      "title": "Equalizing audio with discrete cosine transforms (DCTs)",
      "type": "topic",
      "url": "/documentation/accelerate/equalizing-audio-with-discrete-cosine-transforms-dcts"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/fast-fourier-transforms": {
      "abstract": [
        {
          "text": "Transform vectors and matrices of temporal and spatial domain complex values to the frequency domain, and vice versa.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/fast-fourier-transforms",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Fast Fourier transforms",
      "type": "topic",
      "url": "/documentation/accelerate/fast-fourier-transforms"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/finding-an-interpolating-polynomial-using-the-vandermonde-method": {
      "abstract": [
        {
          "text": "Use LAPACK to solve a linear system and find an interpolating polynomial to construct new points between a series of known data points.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/finding-an-interpolating-polynomial-using-the-vandermonde-method",
      "kind": "article",
      "role": "article",
      "title": "Finding an interpolating polynomial using the Vandermonde method",
      "type": "topic",
      "url": "/documentation/accelerate/finding-an-interpolating-polynomial-using-the-vandermonde-method"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/finding-the-component-frequencies-in-a-composite-sine-wave": {
      "abstract": [
        {
          "text": "Use 1D fast Fourier transform to compute the frequency components of a signal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/finding-the-component-frequencies-in-a-composite-sine-wave",
      "kind": "article",
      "role": "article",
      "title": "Finding the component frequencies in a composite sine wave",
      "type": "topic",
      "url": "/documentation/accelerate/finding-the-component-frequencies-in-a-composite-sine-wave"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/finding-the-sharpest-image-in-a-sequence-of-captured-images": {
      "abstract": [
        {
          "text": "Share image data between vDSP and vImage to compute the sharpest image from a bracketed photo sequence.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/finding-the-sharpest-image-in-a-sequence-of-captured-images",
      "kind": "article",
      "role": "sampleCode",
      "title": "Finding the sharpest image in a sequence of captured images",
      "type": "topic",
      "url": "/documentation/accelerate/finding-the-sharpest-image-in-a-sequence-of-captured-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/halftone-descreening-with-2d-fast-fourier-transform": {
      "abstract": [
        {
          "text": "Reduce or remove periodic artifacts from images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/halftone-descreening-with-2d-fast-fourier-transform",
      "kind": "article",
      "role": "sampleCode",
      "title": "Halftone descreening with 2D fast Fourier transform",
      "type": "topic",
      "url": "/documentation/accelerate/halftone-descreening-with-2d-fast-fourier-transform"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/histogram": {
      "abstract": [
        {
          "text": "Calculate or manipulate an image’s histogram.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/histogram",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Histogram",
      "type": "topic",
      "url": "/documentation/accelerate/histogram"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/image-shearing": {
      "abstract": [
        {
          "text": "Shear images horizontally and vertically.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/image-shearing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image shearing",
      "type": "topic",
      "url": "/documentation/accelerate/image-shearing"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/improving-the-quality-of-quantized-images-with-dithering": {
      "abstract": [
        {
          "text": "Apply dithering to simulate colors that are unavailable in reduced bit depths.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/improving-the-quality-of-quantized-images-with-dithering",
      "kind": "article",
      "role": "sampleCode",
      "title": "Improving the quality of quantized images with dithering",
      "type": "topic",
      "url": "/documentation/accelerate/improving-the-quality-of-quantized-images-with-dithering"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/integrating-vimage-pixel-buffers-into-a-core-image-workflow": {
      "abstract": [
        {
          "text": "Share image data between Core Video pixel buffers and vImage buffers to integrate vImage operations into a Core Image workflow.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/integrating-vimage-pixel-buffers-into-a-core-image-workflow",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating vImage pixel buffers into a Core Image workflow",
      "type": "topic",
      "url": "/documentation/accelerate/integrating-vimage-pixel-buffers-into-a-core-image-workflow"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/macros": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/accelerate/macros"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/morphology": {
      "abstract": [
        {
          "text": "Dilate and erode images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/morphology",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Morphology",
      "type": "topic",
      "url": "/documentation/accelerate/morphology"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/optimizing-image-processing-performance": {
      "abstract": [
        {
          "text": "Improve your app’s performance by converting image buffer formats from interleaved to planar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/optimizing-image-processing-performance",
      "kind": "article",
      "role": "article",
      "title": "Optimizing image-processing performance",
      "type": "topic",
      "url": "/documentation/accelerate/optimizing-image-processing-performance"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/performing-fourier-transforms-on-interleaved-complex-data": {
      "abstract": [
        {
          "text": "Optimize discrete Fourier transform (DFT) performance with the vDSP interleaved DFT routines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/performing-fourier-transforms-on-interleaved-complex-data",
      "kind": "article",
      "role": "article",
      "title": "Performing Fourier transforms on interleaved-complex data",
      "type": "topic",
      "url": "/documentation/accelerate/performing-fourier-transforms-on-interleaved-complex-data"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/performing-fourier-transforms-on-multiple-signals": {
      "abstract": [
        {
          "text": "Use Accelerate’s multiple-signal fast Fourier transform (FFT) functions to transform multiple signals with a single function call.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/performing-fourier-transforms-on-multiple-signals",
      "kind": "article",
      "role": "article",
      "title": "Performing Fourier Transforms on Multiple Signals",
      "type": "topic",
      "url": "/documentation/accelerate/performing-fourier-transforms-on-multiple-signals"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/quadrature": {
      "abstract": [
        {
          "text": "Approximate the definite integral of a function over a finite or infinite interval.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/quadrature",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quadrature",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/reducing-artifacts-with-custom-resampling-filters": {
      "abstract": [
        {
          "text": "Implement custom linear interpolation to prevent the ringing effects associated with scaling an image with the default Lanczos algorithm.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/reducing-artifacts-with-custom-resampling-filters",
      "kind": "article",
      "role": "sampleCode",
      "title": "Reducing artifacts with custom resampling filters",
      "type": "topic",
      "url": "/documentation/accelerate/reducing-artifacts-with-custom-resampling-filters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/reducing-spectral-leakage-with-windowing": {
      "abstract": [
        {
          "text": "Multiply signal data by window sequence values when performing transforms with noninteger period signals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/reducing-spectral-leakage-with-windowing",
      "kind": "article",
      "role": "article",
      "title": "Reducing spectral leakage with windowing",
      "type": "topic",
      "url": "/documentation/accelerate/reducing-spectral-leakage-with-windowing"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/resampling-a-signal-with-decimation": {
      "abstract": [
        {
          "text": "Reduce the sample rate of a signal by specifying a decimation factor and applying a custom antialiasing filter.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/resampling-a-signal-with-decimation",
      "kind": "article",
      "role": "article",
      "title": "Resampling a signal with decimation",
      "type": "topic",
      "url": "/documentation/accelerate/resampling-a-signal-with-decimation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage": {
      "abstract": [
        {
          "text": "Learn how vImage resamples image data during geometric operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage",
      "kind": "article",
      "role": "article",
      "title": "Resampling in vImage",
      "type": "topic",
      "url": "/documentation/accelerate/resampling-in-vimage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/rotating-a-cube-by-transforming-its-vertices": {
      "abstract": [
        {
          "text": "Rotate a cube through a series of keyframes using quaternion interpolation to transition between them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/rotating-a-cube-by-transforming-its-vertices",
      "kind": "article",
      "role": "sampleCode",
      "title": "Rotating a cube by transforming its vertices",
      "type": "topic",
      "url": "/documentation/accelerate/rotating-a-cube-by-transforming-its-vertices"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/signal-extraction-from-noise": {
      "abstract": [
        {
          "text": "Use Accelerate’s discrete cosine transform to remove noise from a signal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/signal-extraction-from-noise",
      "kind": "article",
      "role": "sampleCode",
      "title": "Signal extraction from noise",
      "type": "topic",
      "url": "/documentation/accelerate/signal-extraction-from-noise"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/simd-library": {
      "abstract": [
        {
          "text": "Perform computations on small vectors and matrices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/accelerate/simd-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-of-linear-equations-with-lapack": {
      "abstract": [
        {
          "text": "Select the optimal LAPACK routine to solve a system of linear equations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-of-linear-equations-with-lapack",
      "kind": "article",
      "role": "sampleCode",
      "title": "Solving systems of linear equations with LAPACK",
      "type": "topic",
      "url": "/documentation/accelerate/solving-systems-of-linear-equations-with-lapack"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods": {
      "abstract": [
        {
          "text": "Use direct methods to solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods",
      "kind": "article",
      "role": "article",
      "title": "Solving systems using direct methods",
      "type": "topic",
      "url": "/documentation/accelerate/solving-systems-using-direct-methods"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-iterative-methods": {
      "abstract": [
        {
          "text": "Use iterative methods to solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-iterative-methods",
      "kind": "article",
      "role": "article",
      "title": "Solving systems using iterative methods",
      "type": "topic",
      "url": "/documentation/accelerate/solving-systems-using-iterative-methods"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library": {
      "abstract": [
        {
          "text": "Solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Solvers",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-solvers-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/specifying-histograms-with-vimage": {
      "abstract": [
        {
          "text": "Calculate the histogram of one image, and apply it to a second image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/specifying-histograms-with-vimage",
      "kind": "article",
      "role": "sampleCode",
      "title": "Specifying histograms with vImage",
      "type": "topic",
      "url": "/documentation/accelerate/specifying-histograms-with-vimage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/training-a-neural-network-to-recognize-digits": {
      "abstract": [
        {
          "text": "Build a simple neural network and train it to recognize randomly generated numbers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/training-a-neural-network-to-recognize-digits",
      "kind": "article",
      "role": "sampleCode",
      "title": "Training a neural network to recognize digits",
      "type": "topic",
      "url": "/documentation/accelerate/training-a-neural-network-to-recognize-digits"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/understanding-data-packing-for-fourier-transforms": {
      "abstract": [
        {
          "text": "Format source data for the vDSP Fourier functions, and interpret the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/understanding-data-packing-for-fourier-transforms",
      "kind": "article",
      "role": "article",
      "title": "Understanding data packing for Fourier transforms",
      "type": "topic",
      "url": "/documentation/accelerate/understanding-data-packing-for-fourier-transforms"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/using-linear-interpolation-to-construct-new-data-points": {
      "abstract": [
        {
          "text": "Fill the gaps in arrays of numerical data using linear interpolation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/using-linear-interpolation-to-construct-new-data-points",
      "kind": "article",
      "role": "article",
      "title": "Using linear interpolation to construct new data points",
      "type": "topic",
      "url": "/documentation/accelerate/using-linear-interpolation-to-construct-new-data-points"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/using-vdsp-for-vector-based-arithmetic": {
      "abstract": [
        {
          "text": "Increase the performance of common mathematical tasks with vDSP vector-vector and vector-scalar operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/using-vdsp-for-vector-based-arithmetic",
      "kind": "article",
      "role": "article",
      "title": "Using vDSP for vector-based arithmetic",
      "type": "topic",
      "url": "/documentation/accelerate/using-vdsp-for-vector-based-arithmetic"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/using-vimage-pixel-buffers-to-generate-video-effects": {
      "abstract": [
        {
          "text": "Render real-time video effects with the vImage Pixel Buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/using-vimage-pixel-buffers-to-generate-video-effects",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using vImage pixel buffers to generate video effects",
      "type": "topic",
      "url": "/documentation/accelerate/using-vimage-pixel-buffers-to-generate-video-effects"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vdsp-library": {
      "abstract": [
        {
          "text": "Perform basic arithmetic operations and common digital signal processing (DSP) routines on large vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vdsp-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vDSP",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/veclib": {
      "abstract": [
        {
          "text": "Perform computations on large vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/veclib",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vecLib",
      "type": "topic",
      "url": "/documentation/accelerate/veclib"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vforce-library": {
      "abstract": [
        {
          "text": "Perform transcendental and trigonometric functions on vectors of any length.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vforce-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vForce",
      "type": "topic",
      "url": "/documentation/accelerate/vforce-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPU’s vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/visualizing-sound-as-an-audio-spectrogram": {
      "abstract": [
        {
          "text": "Share image data between vDSP and vImage to visualize audio that a device microphone captures.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/visualizing-sound-as-an-audio-spectrogram",
      "kind": "article",
      "role": "sampleCode",
      "title": "Visualizing sound as an audio spectrogram",
      "type": "topic",
      "url": "/documentation/accelerate/visualizing-sound-as-an-audio-spectrogram"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/working-with-matrices": {
      "abstract": [
        {
          "text": "Solve simultaneous equations and transform points in space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/working-with-matrices",
      "kind": "article",
      "role": "article",
      "title": "Working with Matrices",
      "type": "topic",
      "url": "/documentation/accelerate/working-with-matrices"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/working-with-quaternions": {
      "abstract": [
        {
          "text": "Rotate points around the surface of a sphere, and interpolate between them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/working-with-quaternions",
      "kind": "article",
      "role": "article",
      "title": "Working with Quaternions",
      "type": "topic",
      "url": "/documentation/accelerate/working-with-quaternions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/working-with-vectors": {
      "abstract": [
        {
          "text": "Use vectors to calculate geometric values, calculate dot products and cross products, and interpolate between values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/working-with-vectors",
      "kind": "article",
      "role": "article",
      "title": "Working with Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/working-with-vectors"
    },
    "doc://com.apple.documentation/documentation/AppleArchive": {
      "abstract": [
        {
          "text": "Perform multithreaded lossless compression of directories, files, and data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppleArchive",
      "kind": "symbol",
      "role": "collection",
      "title": "Apple Archive",
      "type": "topic",
      "url": "/documentation/AppleArchive"
    },
    "doc://com.apple.documentation/documentation/Compression": {
      "abstract": [
        {
          "text": "Leverage common compression algorithms for lossless data compression.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Compression",
      "kind": "symbol",
      "role": "collection",
      "title": "Compression",
      "type": "topic",
      "url": "/documentation/Compression"
    },
    "doc://com.apple.documentation/documentation/spatial": {
      "abstract": [
        {
          "text": "Create and manipulate 3D mathematical primitives.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/spatial",
      "kind": "symbol",
      "role": "collection",
      "title": "Spatial",
      "type": "topic",
      "url": "/documentation/spatial"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Neural-Networks",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/training-a-neural-network-to-recognize-digits",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns-library"
      ],
      "title": "Neural Networks"
    },
    {
      "anchor": "Directories-Files-and-Data-Archives",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/compressing-single-files",
        "doc://com.apple.accelerate/documentation/Accelerate/decompressing-single-files",
        "doc://com.apple.accelerate/documentation/Accelerate/compressing-file-system-directories",
        "doc://com.apple.accelerate/documentation/Accelerate/decompressing-and-extracting-an-archived-directory",
        "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-saving-a-string-to-the-file-system",
        "doc://com.apple.accelerate/documentation/Accelerate/decompressing-and-parsing-an-archived-string"
      ],
      "title": "Directories, Files, and Data Archives"
    },
    {
      "anchor": "Compression",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-files-with-stream-compression",
        "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-data-with-buffer-compression",
        "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-data-with-input-and-output-filters"
      ],
      "title": "Compression"
    },
    {
      "anchor": "Image-Processing-Essentials",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/converting-bitmap-data-between-core-graphics-images-and-vimage-buffers",
        "doc://com.apple.accelerate/documentation/Accelerate/creating-and-populating-buffers-from-core-graphics-images",
        "doc://com.apple.accelerate/documentation/Accelerate/creating-a-core-graphics-image-from-a-vimage-buffer",
        "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-processing-workflow",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-geometric-transforms-to-images",
        "doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending",
        "doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-vimage-blend-modes",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-vimage-operations-to-regions-of-interest",
        "doc://com.apple.accelerate/documentation/Accelerate/optimizing-image-processing-performance",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library"
      ],
      "title": "Image Processing Essentials"
    },
    {
      "anchor": "Signal-Processing-Essentials",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/controlling-vdsp-operations-with-stride",
        "doc://com.apple.accelerate/documentation/Accelerate/using-linear-interpolation-to-construct-new-data-points",
        "doc://com.apple.accelerate/documentation/Accelerate/using-vdsp-for-vector-based-arithmetic",
        "doc://com.apple.accelerate/documentation/Accelerate/resampling-a-signal-with-decimation",
        "doc://com.apple.accelerate/documentation/Accelerate/vdsp-library"
      ],
      "title": "Signal Processing Essentials"
    },
    {
      "anchor": "Fourier-and-Cosine-Transforms",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/understanding-data-packing-for-fourier-transforms",
        "doc://com.apple.accelerate/documentation/Accelerate/finding-the-component-frequencies-in-a-composite-sine-wave",
        "doc://com.apple.accelerate/documentation/Accelerate/performing-fourier-transforms-on-interleaved-complex-data",
        "doc://com.apple.accelerate/documentation/Accelerate/reducing-spectral-leakage-with-windowing",
        "doc://com.apple.accelerate/documentation/Accelerate/signal-extraction-from-noise",
        "doc://com.apple.accelerate/documentation/Accelerate/performing-fourier-transforms-on-multiple-signals",
        "doc://com.apple.accelerate/documentation/Accelerate/halftone-descreening-with-2d-fast-fourier-transform",
        "doc://com.apple.accelerate/documentation/Accelerate/fast-fourier-transforms",
        "doc://com.apple.accelerate/documentation/Accelerate/discrete-fourier-transforms",
        "doc://com.apple.accelerate/documentation/Accelerate/discrete-cosine-transforms"
      ],
      "title": "Fourier and Cosine Transforms"
    },
    {
      "anchor": "Core-Video-Interoperation",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/using-vimage-pixel-buffers-to-generate-video-effects",
        "doc://com.apple.accelerate/documentation/Accelerate/integrating-vimage-pixel-buffers-into-a-core-image-workflow",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-vimage-operations-to-video-sample-buffers",
        "doc://com.apple.accelerate/documentation/Accelerate/improving-the-quality-of-quantized-images-with-dithering",
        "doc://com.apple.accelerate/documentation/Accelerate/core-video-interoperability"
      ],
      "title": "Core Video Interoperation"
    },
    {
      "anchor": "Vectors-Matrices-and-Quaternions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/working-with-vectors",
        "doc://com.apple.accelerate/documentation/Accelerate/working-with-matrices",
        "doc://com.apple.accelerate/documentation/Accelerate/working-with-quaternions",
        "doc://com.apple.accelerate/documentation/Accelerate/rotating-a-cube-by-transforming-its-vertices",
        "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
        "doc://com.apple.accelerate/documentation/Accelerate/vforce-library"
      ],
      "title": "Vectors, Matrices, and Quaternions"
    },
    {
      "anchor": "Audio-Processing",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/visualizing-sound-as-an-audio-spectrogram",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-biquadratic-filters-to-a-music-loop",
        "doc://com.apple.accelerate/documentation/Accelerate/equalizing-audio-with-discrete-cosine-transforms-dcts",
        "doc://com.apple.accelerate/documentation/Accelerate/biquadratic-iir-filters",
        "doc://com.apple.accelerate/documentation/Accelerate/discrete-cosine-transforms"
      ],
      "title": "Audio Processing"
    },
    {
      "anchor": "Conversion-Between-Image-Formats",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow",
        "doc://com.apple.accelerate/documentation/Accelerate/converting-color-images-to-grayscale",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-color-transforms-to-images-with-a-multidimensional-lookup-table",
        "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow",
        "doc://com.apple.accelerate/documentation/Accelerate/converting-luminance-and-chrominance-planes-to-an-argb-image",
        "doc://com.apple.accelerate/documentation/Accelerate/conversion"
      ],
      "title": "Conversion Between Image Formats"
    },
    {
      "anchor": "Image-Resampling",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage",
        "doc://com.apple.accelerate/documentation/Accelerate/reducing-artifacts-with-custom-resampling-filters",
        "doc://com.apple.accelerate/documentation/Accelerate/image-shearing"
      ],
      "title": "Image Resampling"
    },
    {
      "anchor": "Convolution-and-Morphology",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/blurring-an-image",
        "doc://com.apple.accelerate/documentation/Accelerate/adding-a-bokeh-effect-to-images",
        "doc://com.apple.accelerate/documentation/Accelerate/convolution",
        "doc://com.apple.accelerate/documentation/Accelerate/morphology"
      ],
      "title": "Convolution and Morphology"
    },
    {
      "anchor": "Color-and-Tone-Adjustment",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-brightness-and-contrast-of-an-image",
        "doc://com.apple.accelerate/documentation/Accelerate/adjusting-saturation-and-applying-tone-mapping",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images",
        "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-hue-of-an-image",
        "doc://com.apple.accelerate/documentation/Accelerate/specifying-histograms-with-vimage",
        "doc://com.apple.accelerate/documentation/Accelerate/enhancing-image-contrast-with-histogram-manipulation",
        "doc://com.apple.accelerate/documentation/Accelerate/histogram"
      ],
      "title": "Color and Tone Adjustment"
    },
    {
      "anchor": "vImage--vDSP-Interoperability",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/finding-the-sharpest-image-in-a-sequence-of-captured-images",
        "doc://com.apple.accelerate/documentation/Accelerate/visualizing-sound-as-an-audio-spectrogram"
      ],
      "title": "vImage / vDSP Interoperability"
    },
    {
      "anchor": "Sparse-Matrices",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/creating-sparse-matrices",
        "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods",
        "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-iterative-methods",
        "doc://com.apple.accelerate/documentation/Accelerate/creating-a-sparse-matrix-from-coordinate-format-arrays",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library"
      ],
      "title": "Sparse Matrices"
    },
    {
      "anchor": "Arithmetic-and-Transcendental-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/veclib"
      ],
      "title": "Arithmetic and Transcendental Functions"
    },
    {
      "anchor": "Linear-Algebra",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-of-linear-equations-with-lapack",
        "doc://com.apple.accelerate/documentation/Accelerate/finding-an-interpolating-polynomial-using-the-vandermonde-method",
        "doc://com.apple.accelerate/documentation/Accelerate/compressing-an-image-using-linear-algebra",
        "doc://com.apple.accelerate/documentation/Accelerate/blas-library"
      ],
      "title": "Linear Algebra"
    },
    {
      "anchor": "Definite-Integration",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/quadrature"
      ],
      "title": "Definite Integration"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/macros"
      ],
      "title": "Macros"
    },
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/InitializableFromCGImage",
        "doc://com.apple.accelerate/documentation/Accelerate/MultiplePlanePixelFormat",
        "doc://com.apple.accelerate/documentation/Accelerate/PixelFormat",
        "doc://com.apple.accelerate/documentation/Accelerate/SinglePlanePixelFormat",
        "doc://com.apple.accelerate/documentation/Accelerate/StaticPixelFormat"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetShapeBounding(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetShapeBounding(_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Neural-Networks",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/training-a-neural-network-to-recognize-digits",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns-library"
              ],
              "title": "Neural Networks"
            },
            {
              "anchor": "Directories-Files-and-Data-Archives",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/compressing-single-files",
                "doc://com.apple.accelerate/documentation/Accelerate/decompressing-single-files",
                "doc://com.apple.accelerate/documentation/Accelerate/compressing-file-system-directories",
                "doc://com.apple.accelerate/documentation/Accelerate/decompressing-and-extracting-an-archived-directory",
                "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-saving-a-string-to-the-file-system",
                "doc://com.apple.accelerate/documentation/Accelerate/decompressing-and-parsing-an-archived-string"
              ],
              "title": "Directories, Files, and Data Archives"
            },
            {
              "anchor": "Compression",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-files-with-stream-compression",
                "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-data-with-buffer-compression",
                "doc://com.apple.accelerate/documentation/Accelerate/compressing-and-decompressing-data-with-input-and-output-filters"
              ],
              "title": "Compression"
            },
            {
              "anchor": "Image-Processing-Essentials",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/converting-bitmap-data-between-core-graphics-images-and-vimage-buffers",
                "doc://com.apple.accelerate/documentation/Accelerate/creating-and-populating-buffers-from-core-graphics-images",
                "doc://com.apple.accelerate/documentation/Accelerate/creating-a-core-graphics-image-from-a-vimage-buffer",
                "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-processing-workflow",
                "doc://com.apple.accelerate/documentation/Accelerate/applying-geometric-transforms-to-images",
                "doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending",
                "doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-vimage-blend-modes",
                "doc://com.apple.accelerate/documentation/Accelerate/applying-vimage-operations-to-regions-of-interest",
                "doc://com.apple.accelerate/documentation/Accelerate/optimizing-image-processing-performance",
                "doc://com.apple.accelerate/documentation/Accelerate/vimage-library"
              ],
              "title": "Image Processing Essentials"
            },
            {
              "anchor": "Signal-Processing-Essentials",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/controlling-vdsp-operations-with-stride",
                "doc://com.apple.accelerate/documentation/Accelerate/using-linear-interpolation-to-construct-new-data-points",
                "doc://com.apple.accelerate/documentation/Accelerate/using-vdsp-for-vector-based-arithmetic",
                "doc://com.apple.accelerate/documentation/Accelerate/resampling-a-signal-with-decimation",
                "doc://com.apple.accelerate/documentation/Accelerate/vdsp-library"
              ],
              "title": "Signal Processing Essentials"
            },
            {
              "anchor": "Fourier-and-Cosine-Transforms",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/understanding-data-packing-for-fourier-transforms",
                "doc://com.apple.accelerate/documentation/Accelerate/finding-the-component-frequencies-in-a-composite-sine-wave",
                "doc://com.apple.accelerate/documentation/Accelerate/performing-fourier-transforms-on-interleaved-complex-data",
                "doc://com.apple.accelerate/documentation/Accelerate/reducing-spectral-leakage-with-windowing",
                "doc://com.apple.accelerate/documentation/Accelerate/signal-extraction-from-noise",
                "doc://com.apple.accelerate/documentation/Accelerate/performing-fourier-transforms-on-multiple-signals",
                "doc://com.apple.accelerate/documentation/Accelerate/halftone-descreening-with-2d-fast-fourier-transform",
                "doc://com.apple.accelerate/documentation/Accelerate/fast-fourier-transforms",
                "doc://com.apple.accelerate/documentation/Accelerate/discrete-fourier-transforms",
                "doc://com.apple.accelerate/documentation/Accelerate/discrete-cosine-transforms"
              ],
              "title": "Fourier and Cosine Transforms"
            },
            {
              "anchor": "Core-Video-Interoperation",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/using-vimage-pixel-buffers-to-generate-video-effects",
                "doc://com.apple.accelerate/documentation/Accelerate/integrating-vimage-pixel-buffers-into-a-core-image-workflow",
                "doc://com.apple.accelerate/documentation/Accelerate/applying-vimage-operations-to-video-sample-buffers",
                "doc://com.apple.accelerate/documentation/Accelerate/improving-the-quality-of-quantized-images-with-dithering",
                "doc://com.apple.accelerate/documentation/Accelerate/core-video-interoperability"
              ],
              "title": "Core Video Interoperation"
            },
            {
              "anchor": "Vectors-Matrices-and-Quaternions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/working-with-vectors",
                "doc://com.apple.accelerate/documentation/Accelerate/working-with-matrices",
                "doc://com.apple.accelerate/documentation/Accelerate/working-with-quaternions",
                "doc://com.apple.accelerate/documentation/Accelerate/rotating-a-cube-by-transforming-its-vertices",
                "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
                "doc://com.apple.accelerate/documentation/Accelerate/vforce-library"
              ],
              "title": "Vectors, Matrices, and Quaternions"
            },
            {
              "anchor": "Audio-Processing",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/visualizing-sound-as-an-audio-spectrogram",
                "doc://com.apple.accelerate/documentation/Accelerate/applying-biquadratic-filters-to-a-music-loop",
                "doc://com.apple.accelerate/documentation/Accelerate/equalizing-audio-with-discrete-cosine-transforms-dcts",
                "doc://com.apple.accelerate/documentation/Accelerate/biquadratic-iir-filters",
                "doc://com.apple.accelerate/documentation/Accelerate/discrete-cosine-transforms"
              ],
              "title": "Audio Processing"
            },
            {
              "anchor": "Conversion-Between-Image-Formats",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow",
                "doc://com.apple.accelerate/documentation/Accelerate/converting-color-images-to-grayscale",
                "doc://com.apple.accelerate/documentation/Accelerate/applying-color-transforms-to-images-with-a-multidimensional-lookup-table",
                "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow",
                "doc://com.apple.accelerate/documentation/Accelerate/converting-luminance-and-chrominance-planes-to-an-argb-image",
                "doc://com.apple.accelerate/documentation/Accelerate/conversion"
              ],
              "title": "Conversion Between Image Formats"
            },
            {
              "anchor": "Image-Resampling",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage",
                "doc://com.apple.accelerate/documentation/Accelerate/reducing-artifacts-with-custom-resampling-filters",
                "doc://com.apple.accelerate/documentation/Accelerate/image-shearing"
              ],
              "title": "Image Resampling"
            },
            {
              "anchor": "Convolution-and-Morphology",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/blurring-an-image",
                "doc://com.apple.accelerate/documentation/Accelerate/adding-a-bokeh-effect-to-images",
                "doc://com.apple.accelerate/documentation/Accelerate/convolution",
                "doc://com.apple.accelerate/documentation/Accelerate/morphology"
              ],
              "title": "Convolution and Morphology"
            },
            {
              "anchor": "Color-and-Tone-Adjustment",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-brightness-and-contrast-of-an-image",
                "doc://com.apple.accelerate/documentation/Accelerate/adjusting-saturation-and-applying-tone-mapping",
                "doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images",
                "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-hue-of-an-image",
                "doc://com.apple.accelerate/documentation/Accelerate/specifying-histograms-with-vimage",
                "doc://com.apple.accelerate/documentation/Accelerate/enhancing-image-contrast-with-histogram-manipulation",
                "doc://com.apple.accelerate/documentation/Accelerate/histogram"
              ],
              "title": "Color and Tone Adjustment"
            },
            {
              "anchor": "vImage--vDSP-Interoperability",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/finding-the-sharpest-image-in-a-sequence-of-captured-images",
                "doc://com.apple.accelerate/documentation/Accelerate/visualizing-sound-as-an-audio-spectrogram"
              ],
              "title": "vImage / vDSP Interoperability"
            },
            {
              "anchor": "Sparse-Matrices",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/creating-sparse-matrices",
                "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods",
                "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-iterative-methods",
                "doc://com.apple.accelerate/documentation/Accelerate/creating-a-sparse-matrix-from-coordinate-format-arrays",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library"
              ],
              "title": "Sparse Matrices"
            },
            {
              "anchor": "Arithmetic-and-Transcendental-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/veclib"
              ],
              "title": "Arithmetic and Transcendental Functions"
            },
            {
              "anchor": "Linear-Algebra",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-of-linear-equations-with-lapack",
                "doc://com.apple.accelerate/documentation/Accelerate/finding-an-interpolating-polynomial-using-the-vandermonde-method",
                "doc://com.apple.accelerate/documentation/Accelerate/compressing-an-image-using-linear-algebra",
                "doc://com.apple.accelerate/documentation/Accelerate/blas-library"
              ],
              "title": "Linear Algebra"
            },
            {
              "anchor": "Definite-Integration",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/quadrature"
              ],
              "title": "Definite Integration"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/macros"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetShapeBounding(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetShapeBounding(_:_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetShapeBounding(_:)/title",
          "value": "BNNSGraphCompileOptionsGetShapeBounding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetShapeBounding(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsGetShapeBounding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetShapeBounding(_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetShapeBounding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetShapeBounding(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetShapeBounding"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
