{
  "abstract": [
    {
      "text": "Make your apps accessible to everyone who uses Apple devices.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "customMetadata": {
      "show-on-this-page": "true"
    },
    "externalID": "Accessibility",
    "images": [
      {
        "identifier": "Accessibility-PageImage-card.png",
        "type": "card"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "7.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Accessibility"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Accessibility features help a wide range of people interact with their devices.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "By creating your app with accessibility in mind, you make it possible for everyone",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to enjoy your app.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Whether you’re developing a new app, or updating an existing one, consider the needs",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of all the people who might use your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For many, accessibility is a necessity.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For others, it’s a practicality.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, closed captions can be necessary for someone who is deaf or hard of hearing,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "but also useful for someone watching a video in a noisy environment.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Learn more about how to support different types of accessibility needs in your app using Apple’s wide range of accessibility APIs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            "doc://com.apple.Accessibility/documentation/Accessibility/vision",
            "doc://com.apple.Accessibility/documentation/Accessibility/speech",
            "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
            "doc://com.apple.Accessibility/documentation/Accessibility/cognitive",
            "doc://com.apple.Accessibility/documentation/Accessibility/hearing"
          ],
          "style": "detailedGrid",
          "type": "links"
        },
        {
          "anchor": "Dive-into-featured-sample-apps",
          "level": 3,
          "text": "Dive into featured sample apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Explore how sample apps leverage accessible design principles and accessibility APIs to create a great user experience for everyone.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            "doc://com.apple.documentation/documentation/visionOS/destination-video",
            "doc://com.apple.documentation/documentation/visionOS/happybeam"
          ],
          "style": "compactGrid",
          "type": "links"
        },
        {
          "anchor": "Explore-assistive-technologies",
          "level": 3,
          "text": "Explore assistive technologies",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "People can personalize their devices by choosing the accessibility features and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "assistive technologies that give them the best user experience.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Make sure your app provides a great experience for people who use assistive technologies by testing your app with them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
            "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
            "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
            "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
          ],
          "style": "detailedGrid",
          "type": "links"
        },
        {
          "anchor": "Related-videos",
          "level": 3,
          "text": "Related videos",
          "type": "heading"
        },
        {
          "items": [
            "doc://com.apple.documentation/videos/play/wwdc2023/10034",
            "doc://com.apple.documentation/videos/play/wwdc2023/10036",
            "doc://com.apple.documentation/videos/play/wwdc2023/10032",
            "doc://com.apple.documentation/videos/play/wwdc2023/10078",
            "doc://com.apple.documentation/videos/play/wwdc2023/10035",
            "doc://com.apple.documentation/videos/play/wwdc2023/10033"
          ],
          "style": "compactGrid",
          "type": "links"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "0C1B59D8-1271-4A4D-BBD5-401BCFA4D855": {
      "alt": null,
      "identifier": "0C1B59D8-1271-4A4D-BBD5-401BCFA4D855",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/0C1B59D8-1271-4A4D-BBD5-401BCFA4D855/8063_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/0C1B59D8-1271-4A4D-BBD5-401BCFA4D855/8063_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/0C1B59D8-1271-4A4D-BBD5-401BCFA4D855/8063_wide_250x141_3x.jpg"
        }
      ]
    },
    "2C47B638-090D-4CBB-9E9E-EBE8114536D9": {
      "alt": null,
      "identifier": "2C47B638-090D-4CBB-9E9E-EBE8114536D9",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/2C47B638-090D-4CBB-9E9E-EBE8114536D9/8132_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/2C47B638-090D-4CBB-9E9E-EBE8114536D9/8132_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/2C47B638-090D-4CBB-9E9E-EBE8114536D9/8132_wide_250x141_3x.jpg"
        }
      ]
    },
    "3BF48B60-4462-4461-BAB8-7E4A6224A2F5": {
      "alt": null,
      "identifier": "3BF48B60-4462-4461-BAB8-7E4A6224A2F5",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/3BF48B60-4462-4461-BAB8-7E4A6224A2F5/8060_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/3BF48B60-4462-4461-BAB8-7E4A6224A2F5/8060_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/3BF48B60-4462-4461-BAB8-7E4A6224A2F5/8060_wide_250x141_3x.jpg"
        }
      ]
    },
    "A93805E1-686D-4936-82A4-32403D14E4AE": {
      "alt": null,
      "identifier": "A93805E1-686D-4936-82A4-32403D14E4AE",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/A93805E1-686D-4936-82A4-32403D14E4AE/8061_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/A93805E1-686D-4936-82A4-32403D14E4AE/8061_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/A93805E1-686D-4936-82A4-32403D14E4AE/8061_wide_250x141_3x.jpg"
        }
      ]
    },
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "D0CC0FAC-069A-45B5-873F-55365CE0EB21": {
      "alt": null,
      "identifier": "D0CC0FAC-069A-45B5-873F-55365CE0EB21",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/D0CC0FAC-069A-45B5-873F-55365CE0EB21/8064_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/D0CC0FAC-069A-45B5-873F-55365CE0EB21/8064_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/D0CC0FAC-069A-45B5-873F-55365CE0EB21/8064_wide_250x141_3x.jpg"
        }
      ]
    },
    "D1866B0D-617B-4A78-A645-915F82BC0B78": {
      "alt": null,
      "identifier": "D1866B0D-617B-4A78-A645-915F82BC0B78",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/D1866B0D-617B-4A78-A645-915F82BC0B78/8062_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/D1866B0D-617B-4A78-A645-915F82BC0B78/8062_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/D1866B0D-617B-4A78-A645-915F82BC0B78/8062_wide_250x141_3x.jpg"
        }
      ]
    },
    "Destination-Video-intro.png": {
      "alt": null,
      "identifier": "Destination-Video-intro.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/648c665254129674ce04bbc64dbeeb2d/Destination-Video-intro@2x.png"
        }
      ]
    },
    "Happy-Beam-intro.png": {
      "alt": null,
      "identifier": "Happy-Beam-intro.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/52b497b6d705af322726d7371dee6ddd/Happy-Beam-intro@2x.png"
        }
      ]
    },
    "Performing-Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Performing-Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e051f9ccd83bfe36b3b3f6d9f40cbdb7/Performing-Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/aa888b2429f4c432b6746549abb24c55/Performing-Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-card-cognitive.png": {
      "alt": "An illustration that shows a person standing and looking at an Apple Watch on their left wrist.",
      "identifier": "accessibility-card-cognitive.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e160ce0d82939c6b6866af282cc4bc9c/accessibility-card-cognitive@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3d882a73b0819d3d605fb78bda492908/accessibility-card-cognitive~dark@2x.png"
        }
      ]
    },
    "accessibility-card-hearing.png": {
      "alt": "An illustration that shows a person wearing a hearing aid and a camping backpack. The person is walking and using an iPhone.",
      "identifier": "accessibility-card-hearing.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/08122f4b2e9f57caf30f8e244ccd3dfe/accessibility-card-hearing@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/db59daa0db79629fb85282bf8a9e4908/accessibility-card-hearing~dark@2x.png"
        }
      ]
    },
    "accessibility-card-mobility.png": {
      "alt": "An illustration that shows a person in a wheelchair using a MacBook in their lap.",
      "identifier": "accessibility-card-mobility.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c55383b0bf084116e82d7e4aba87c3cc/accessibility-card-mobility@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d0ce2da05b4c6805e5c3f5862222b099/accessibility-card-mobility~dark@2x.png"
        }
      ]
    },
    "accessibility-card-speech.png": {
      "alt": "An illustration that shows a person in an electric wheelchair sitting at a desk and using speech synthesis features on a Mac.",
      "identifier": "accessibility-card-speech.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c1f425b12f45643f5a126e3852ab9d76/accessibility-card-speech@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5655a5854b8b46288245fde1cd517f97/accessibility-card-speech~dark@2x.png"
        }
      ]
    },
    "accessibility-card-vision.png": {
      "alt": "An illustration that shows a person with low vision walking with the assistance of a guide dog while using an iPhone and AirPods.",
      "identifier": "accessibility-card-vision.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/11631c0b01fa73cc082557dc6067840e/accessibility-card-vision@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/624a8a2e8a195d6785905c00a619d3ac/accessibility-card-vision~dark@2x.png"
        }
      ]
    },
    "accessibility.svg": {
      "alt": null,
      "identifier": "accessibility.svg",
      "type": "image",
      "variants": [
        {
          "svgID": "accessibility",
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/83c941607786e0ba1f582082f4e94361/accessibility.svg"
        }
      ]
    },
    "assistive-access-card.png": {
      "alt": "",
      "identifier": "assistive-access-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6a2ce2f33aac08a5727273235f9f0bb6/assistive-access-card@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession": {
      "abstract": [
        {
          "text": "A token object that represents an override session held by your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSession"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSession"
        }
      ],
      "role": "symbol",
      "title": "AXFeatureOverrideSession",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesession"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options": {
      "abstract": [
        {
          "text": "Options indicating which Accessibility features will be turned on or off when an override session is held by your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "AXFeatureOverrideSession.Options",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesession/options"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSessionError"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSessionError"
        }
      ],
      "role": "symbol",
      "title": "AXFeatureOverrideSessionError",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesessionerror-swift.struct"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionError-swift.struct/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AXFeatureOverrideSessionError.Code",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesessionerror-swift.struct/code"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionErrorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSessionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSessionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "AXFeatureOverrideSessionErrorDomain",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesessionerrordomain"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionManager": {
      "abstract": [
        {
          "text": "A manager class to begin and end accessibility feature override sessions. Multiple override sessions are reconciled by combining the requests, preferring feature enablement. Ending all sessions restores the prior state of Accessibility feature enablement. Your app must be entitled with com.apple.developer.accessibility.merchant-api-control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSessionManager"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXFeatureOverrideSessionManager"
        }
      ],
      "role": "symbol",
      "title": "AXFeatureOverrideSessionManager",
      "type": "topic",
      "url": "/documentation/accessibility/axfeatureoverridesessionmanager"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpression": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpression"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpression"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpression",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpression"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFenced": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionFenced"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFenced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionFenced"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionFenced",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionfenced"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFraction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionFraction"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionFraction"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionFraction",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionfraction"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionIdentifier"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionIdentifier",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionidentifier"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionMultiscript": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionMultiscript"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionMultiscript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionMultiscript"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionMultiscript",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionmultiscript"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionNumber"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionNumber"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionNumber",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionnumber"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionOperator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionOperator"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionOperator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionOperator"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionOperator",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionoperator"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionProvider": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionProvider"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionProvider"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionProvider",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionprovider"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRoot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionRoot"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionRoot"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionRoot",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionroot"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionRow"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionRow"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionRow",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionrow"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionSubSuperscript": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionSubSuperscript"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionSubSuperscript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionSubSuperscript"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionSubSuperscript",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionsubsuperscript"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionTable"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionTable"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionTable",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressiontable"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableCell": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionTableCell"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionTableCell"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionTableCell",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressiontablecell"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableRow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionTableRow"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionTableRow"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionTableRow",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressiontablerow"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionText": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionText"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionText"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionText",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressiontext"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionUnderOver": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionUnderOver"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionUnderOver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionUnderOver"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionUnderOver",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionunderover"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-api": {
      "abstract": [
        {
          "text": "Browse API in the Accessibility framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility API",
      "type": "topic",
      "url": "/documentation/accessibility/accessibility-api"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-for-visionos": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses visionOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-for-visionos",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility for visionOS",
      "type": "topic",
      "url": "/documentation/accessibility/accessibility-for-visionos"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-inspector": {
      "abstract": [
        {
          "text": "Reveal how your app represents itself to people using accessibility features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-inspector",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility Inspector",
      "type": "topic",
      "url": "/documentation/accessibility/accessibility-inspector"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/accessibility_design_for_mac_catalyst": {
      "abstract": [
        {
          "text": "Improve navigation in your app by using keyboard shortcuts and accessibility containers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility_design_for_mac_catalyst",
      "kind": "article",
      "role": "sampleCode",
      "title": "Accessibility design for Mac Catalyst",
      "type": "topic",
      "url": "/documentation/accessibility/accessibility_design_for_mac_catalyst"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access": {
      "abstract": [
        {
          "text": "A mode that tailors the iOS and iPadOS experience for people with cognitive disabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access",
      "images": [
        {
          "identifier": "assistive-access-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive Access",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-access"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies": {
      "abstract": [
        {
          "text": "Make sure your app provides a great experience for people who use assistive technologies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive technologies",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-technologies"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/cognitive": {
      "abstract": [
        {
          "text": "A person may have difficulty remembering a sequence of steps, or they",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "may find an overly complex user interface difficult to process and manage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/cognitive",
      "images": [
        {
          "identifier": "accessibility-card-cognitive.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cognitive",
      "type": "topic",
      "url": "/documentation/accessibility/cognitive"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/delivering_an_exceptional_accessibility_experience": {
      "abstract": [
        {
          "text": "Make improvements to your app’s interaction model to support assistive technologies such as VoiceOver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/delivering_an_exceptional_accessibility_experience",
      "kind": "article",
      "role": "sampleCode",
      "title": "Delivering an exceptional accessibility experience",
      "type": "topic",
      "url": "/documentation/accessibility/delivering_an_exceptional_accessibility_experience"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/enhancing-the-accessibility-of-your-swiftui-app": {
      "abstract": [
        {
          "text": "Support advancements in SwiftUI accessibility to make your app accessible to everyone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/enhancing-the-accessibility-of-your-swiftui-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Enhancing the accessibility of your SwiftUI app",
      "type": "topic",
      "url": "/documentation/accessibility/enhancing-the-accessibility-of-your-swiftui-app"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/hearing": {
      "abstract": [
        {
          "text": "A person may be deaf, have partial hearing loss, or have difficulty hearing",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "sounds within a certain range.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/hearing",
      "images": [
        {
          "identifier": "accessibility-card-hearing.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hearing",
      "type": "topic",
      "url": "/documentation/accessibility/hearing"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/integrating_accessibility_into_your_app": {
      "abstract": [
        {
          "text": "Make your app more accessible to users with disabilities by adding accessibility features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/integrating_accessibility_into_your_app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating accessibility into your app",
      "type": "topic",
      "url": "/documentation/accessibility/integrating_accessibility_into_your_app"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/mobility": {
      "abstract": [
        {
          "text": "A person with reduced mobility may have difficulty holding a device",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "or tapping the interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
      "images": [
        {
          "identifier": "accessibility-card-mobility.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mobility",
      "type": "topic",
      "url": "/documentation/accessibility/mobility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app": {
      "abstract": [
        {
          "text": "Test your app with accessibility settings and assistive technologies to discover and address accessibility issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app",
      "images": [
        {
          "identifier": "Performing-Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Performing accessibility testing for your app",
      "type": "topic",
      "url": "/documentation/accessibility/performing-accessibility-testing-for-your-app"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/speech": {
      "abstract": [
        {
          "text": "A person may have a speech disability or prefer to connect without using their voice.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/speech",
      "images": [
        {
          "identifier": "accessibility-card-speech.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/accessibility/speech"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/switch-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device with a variety of adaptive switch hardware, wireless game controllers, or sounds such as a click or a pop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
      "images": [
        {
          "identifier": "switch-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Switch Control",
      "type": "topic",
      "url": "/documentation/accessibility/switch-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/vision": {
      "abstract": [
        {
          "text": "A person may be blind or color blind, or have a vision challenge that",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "makes focusing difficult.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/vision",
      "images": [
        {
          "identifier": "accessibility-card-vision.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/accessibility/vision"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voice-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device using voice commands to tap, swipe, type, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
      "images": [
        {
          "identifier": "voice-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Voice Control",
      "type": "topic",
      "url": "/documentation/accessibility/voice-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voiceover": {
      "abstract": [
        {
          "text": "A gesture-based screen reader that provides an auditory description of the content onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
      "images": [
        {
          "identifier": "voiceover-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "VoiceOver",
      "type": "topic",
      "url": "/documentation/accessibility/voiceover"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_large_text_challenge": {
      "abstract": [
        {
          "text": "Design for large text sizes by modifying the user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_large_text_challenge",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC21 Challenge: Large Text Challenge",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc21_challenge_large_text_challenge"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_speech_synthesizer_simulator": {
      "abstract": [
        {
          "text": "Simulate a conversation using speech synthesis.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_speech_synthesizer_simulator",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC21 Challenge: Speech Synthesizer Simulator",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc21_challenge_speech_synthesizer_simulator"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze": {
      "abstract": [
        {
          "text": "Navigate to the end of a dark maze using VoiceOver as your guide.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC21 Challenge: VoiceOver Maze",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc21_challenge_voiceover_maze"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming": {
      "abstract": [
        {
          "text": "Play a card-matching game using Switch Control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC22 Challenge: Learn Switch Control through gaming",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc22_challenge_learn_switch_control_through_gaming"
    },
    "doc://com.apple.documentation/design/Human-Interface-Guidelines/accessibility": {
      "abstract": [
        {
          "text": "Accessible user interfaces empower everyone to have a great experience with your app or game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/design/Human-Interface-Guidelines/accessibility",
      "images": [
        {
          "identifier": "accessibility.svg",
          "type": "icon"
        },
        {
          "identifier": "foundations-accessibility-thumbnail.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Accessibility",
      "type": "topic",
      "url": "/design/Human-Interface-Guidelines/accessibility"
    },
    "doc://com.apple.documentation/documentation/AppKit/accessibility-for-appkit": {
      "abstract": [
        {
          "text": "Make your AppKit apps accessible to everyone who uses macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/accessibility-for-appkit",
      "kind": "article",
      "role": "article",
      "title": "Accessibility for AppKit",
      "type": "topic",
      "url": "/documentation/AppKit/accessibility-for-appkit"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Accessibility-fundamentals": {
      "abstract": [
        {
          "text": "Make your SwiftUI apps accessible to everyone, including people with disabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Accessibility-fundamentals",
      "kind": "article",
      "role": "article",
      "title": "Accessibility fundamentals",
      "type": "topic",
      "url": "/documentation/SwiftUI/Accessibility-fundamentals"
    },
    "doc://com.apple.documentation/documentation/UIKit/accessibility-for-uikit": {
      "abstract": [
        {
          "text": "Make your UIKit apps accessible to everyone who uses iOS and tvOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/accessibility-for-uikit",
      "kind": "article",
      "role": "article",
      "title": "Accessibility for UIKit",
      "type": "topic",
      "url": "/documentation/UIKit/accessibility-for-uikit"
    },
    "doc://com.apple.documentation/documentation/Updates/Accessibility": {
      "abstract": [
        {
          "text": "Learn about important changes to Accessibility.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/Accessibility",
      "kind": "article",
      "role": "article",
      "title": "Accessibility updates",
      "type": "topic",
      "url": "/documentation/Updates/Accessibility"
    },
    "doc://com.apple.documentation/documentation/swiftui/creating_accessible_views": {
      "abstract": [
        {
          "text": "Make your app accessible to everyone by applying accessibility modifiers to your SwiftUI views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swiftui/creating_accessible_views",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating Accessible Views",
      "type": "topic",
      "url": "/documentation/swiftui/creating_accessible_views"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/visionOS/destination-video": {
      "abstract": [
        {
          "text": "Leverage SwiftUI to build an immersive media experience in a multiplatform app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/destination-video",
      "images": [
        {
          "identifier": "Destination-Video-intro.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "sampleCode",
      "title": "Destination Video",
      "type": "topic",
      "url": "/documentation/visionOS/destination-video"
    },
    "doc://com.apple.documentation/documentation/visionOS/happybeam": {
      "abstract": [
        {
          "text": "Leverage a Full Space to create a fun game using ARKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/happybeam",
      "images": [
        {
          "identifier": "Happy-Beam-intro.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "sampleCode",
      "title": "Happy Beam",
      "type": "topic",
      "url": "/documentation/visionOS/happybeam"
    },
    "doc://com.apple.documentation/videos/play/wwdc2023/10032": {
      "abstract": [
        {
          "text": "Learn how Assistive Access can help people with cognitive disabilities more easily use iPhone and iPad. Discover the design principles that guide Assistive Access and find out how the system experience adapts to lighten cognitive load. We’ll show you how Assistive Access works and what you can do to support this experience in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2023/10032",
      "images": [
        {
          "identifier": "3BF48B60-4462-4461-BAB8-7E4A6224A2F5",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Meet Assistive Access",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10032"
    },
    "doc://com.apple.documentation/videos/play/wwdc2023/10033": {
      "abstract": [
        {
          "text": "Bring the latest advancements in Speech Synthesis to your apps. Learn how you can integrate your custom speech synthesizer and voices into iOS and macOS. We’ll show you how SSML is used to generate expressive speech synthesis, and explore how Personal Voice can enable your augmentative and assistive communication app to speak on a person’s behalf in an authentic way.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2023/10033",
      "images": [
        {
          "identifier": "A93805E1-686D-4936-82A4-32403D14E4AE",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Extend Speech Synthesis with personal and custom voices",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10033"
    },
    "doc://com.apple.documentation/videos/play/wwdc2023/10034": {
      "abstract": [
        {
          "text": "Learn how you can make spatial computing apps that work well for everyone. Like all Apple platforms, visionOS is designed for accessibility: We’ll share how we’ve reimagined assistive technologies like VoiceOver and Pointer Control and designed features like Dwell Control to help people interact in the way that works best for them. Learn best practices for vision, motor, cognitive, and hearing accessibility and help everyone enjoy immersive experiences for visionOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2023/10034",
      "images": [
        {
          "identifier": "D1866B0D-617B-4A78-A645-915F82BC0B78",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Create accessible spatial experiences",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10034"
    },
    "doc://com.apple.documentation/videos/play/wwdc2023/10035": {
      "abstract": [
        {
          "text": "Discover how you can test your app for accessibility with every build. Learn how to perform automated audits for accessibility using XCTest and find out how to interpret the results. We’ll also share enhancements to the accessibility API that can help you improve UI test coverage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2023/10035",
      "images": [
        {
          "identifier": "0C1B59D8-1271-4A4D-BBD5-401BCFA4D855",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Perform accessibility audits for your app",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10035"
    },
    "doc://com.apple.documentation/videos/play/wwdc2023/10036": {
      "abstract": [
        {
          "text": "Discover how advancements in UI frameworks make it easier to build rich, accessible experiences. Find out how technologies like VoiceOver can better interact with your app’s interface through accessibility traits and actions. We’ll share the latest updates to SwiftUI that help you refine your accessibility experience and show you how to keep accessibility information up-to-date in your UIKit apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2023/10036",
      "images": [
        {
          "identifier": "D0CC0FAC-069A-45B5-873F-55365CE0EB21",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Build accessible apps with SwiftUI and UIKit",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10036"
    },
    "doc://com.apple.documentation/videos/play/wwdc2023/10078": {
      "abstract": [
        {
          "text": "Learn how to design engaging immersive experiences for visionOS that respect the limitations of human vision and motion perception. We’ll show you how you can use depth cues, contrast, focus, and motion to keep people comfortable as they enjoy your apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2023/10078",
      "images": [
        {
          "identifier": "2C47B638-090D-4CBB-9E9E-EBE8114536D9",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Design considerations for vision and motion",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10078"
    },
    "foundations-accessibility-thumbnail.png": {
      "alt": null,
      "identifier": "foundations-accessibility-thumbnail.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8b7b11d06dd958f4e9449f0a5acdadbd/foundations-accessibility-thumbnail@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/fea544b1ff706c10ba3a1d06f528da46/foundations-accessibility-thumbnail~dark@2x.png"
        }
      ]
    },
    "switch-control-card.png": {
      "alt": "",
      "identifier": "switch-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4b37322483b5831fc6a7e44fb9dc05b4/switch-control-card@2x.png"
        }
      ]
    },
    "voice-control-card.png": {
      "alt": "",
      "identifier": "voice-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9b9495b7277bc069208a522c435b7fc7/voice-control-card@2x.png"
        }
      ]
    },
    "voiceover-card.png": {
      "alt": "",
      "identifier": "voiceover-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6d02ab927e1e3865da0472d09dc3aae4/voiceover-card@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Updates/Accessibility",
        "doc://com.apple.documentation/design/Human-Interface-Guidelines/accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Sample-code",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/enhancing-the-accessibility-of-your-swiftui-app",
        "doc://com.apple.documentation/documentation/swiftui/creating_accessible_views",
        "doc://com.apple.Accessibility/documentation/Accessibility/delivering_an_exceptional_accessibility_experience",
        "doc://com.apple.Accessibility/documentation/Accessibility/integrating_accessibility_into_your_app",
        "doc://com.apple.Accessibility/documentation/Accessibility/accessibility_design_for_mac_catalyst"
      ],
      "title": "Sample code"
    },
    {
      "anchor": "Domains",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/vision",
        "doc://com.apple.Accessibility/documentation/Accessibility/speech",
        "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
        "doc://com.apple.Accessibility/documentation/Accessibility/cognitive",
        "doc://com.apple.Accessibility/documentation/Accessibility/hearing"
      ],
      "title": "Domains"
    },
    {
      "anchor": "Developer-tools",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-inspector"
      ],
      "title": "Developer tools"
    },
    {
      "anchor": "Assistive-technologies",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies"
      ],
      "title": "Assistive technologies"
    },
    {
      "anchor": "Accessibility-framework",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-api"
      ],
      "title": "Accessibility framework"
    },
    {
      "anchor": "Platforms",
      "identifiers": [
        "doc://com.apple.documentation/documentation/SwiftUI/Accessibility-fundamentals",
        "doc://com.apple.documentation/documentation/UIKit/accessibility-for-uikit",
        "doc://com.apple.documentation/documentation/AppKit/accessibility-for-appkit",
        "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-for-visionos"
      ],
      "title": "Platforms"
    },
    {
      "anchor": "WWDC-Challenges",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming",
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_large_text_challenge",
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_speech_synthesizer_simulator",
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze"
      ],
      "title": "WWDC Challenges"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionManager",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpression",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFenced",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFraction",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionIdentifier",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionMultiscript",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionNumber",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionOperator",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRoot",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRow",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionSubSuperscript",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTable",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableCell",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableRow",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionText",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionUnderOver"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionProvider"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionError-swift.struct"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionErrorDomain"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Updates/Accessibility",
                "doc://com.apple.documentation/design/Human-Interface-Guidelines/accessibility",
                "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Sample-code",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/enhancing-the-accessibility-of-your-swiftui-app",
                "doc://com.apple.documentation/documentation/swiftui/creating_accessible_views",
                "doc://com.apple.Accessibility/documentation/Accessibility/delivering_an_exceptional_accessibility_experience",
                "doc://com.apple.Accessibility/documentation/Accessibility/integrating_accessibility_into_your_app",
                "doc://com.apple.Accessibility/documentation/Accessibility/accessibility_design_for_mac_catalyst"
              ],
              "title": "Sample code"
            },
            {
              "anchor": "Domains",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/vision",
                "doc://com.apple.Accessibility/documentation/Accessibility/speech",
                "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
                "doc://com.apple.Accessibility/documentation/Accessibility/cognitive",
                "doc://com.apple.Accessibility/documentation/Accessibility/hearing"
              ],
              "title": "Domains"
            },
            {
              "anchor": "Developer-tools",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-inspector"
              ],
              "title": "Developer tools"
            },
            {
              "anchor": "Assistive-technologies",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies"
              ],
              "title": "Assistive technologies"
            },
            {
              "anchor": "Accessibility-framework",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-api"
              ],
              "title": "Accessibility framework"
            },
            {
              "anchor": "Platforms",
              "identifiers": [
                "doc://com.apple.documentation/documentation/SwiftUI/Accessibility-fundamentals",
                "doc://com.apple.documentation/documentation/UIKit/accessibility-for-uikit",
                "doc://com.apple.documentation/documentation/AppKit/accessibility-for-appkit",
                "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-for-visionos"
              ],
              "title": "Platforms"
            },
            {
              "anchor": "WWDC-Challenges",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming",
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_large_text_challenge",
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_speech_synthesizer_simulator",
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze"
              ],
              "title": "WWDC Challenges"
            },
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionManager",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpression",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFenced",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFraction",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionIdentifier",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionMultiscript",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionNumber",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionOperator",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRoot",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRow",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionSubSuperscript",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTable",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableCell",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableRow",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionText",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionUnderOver"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionProvider"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionErrorDomain"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSession/Options",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXFeatureOverrideSessionError-swift.struct/Code"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpression/title",
          "value": "AXMathExpression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpression/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSessionError-swift.struct~1Code/title",
          "value": "AXFeatureOverrideSessionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSessionError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSessionError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSessionErrorDomain/title",
          "value": "AXFeatureOverrideSessionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSessionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options/title",
          "value": "AXFeatureOverrideSessionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession~1Options/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionText/title",
          "value": "AXMathExpressionText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession/title",
          "value": "AXFeatureOverrideSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRow/title",
          "value": "AXMathExpressionRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionSubSuperscript/title",
          "value": "AXMathExpressionSubSuperscript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionSubSuperscript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionSubSuperscript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionSubSuperscript/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionSubSuperscript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionMultiscript/title",
          "value": "AXMathExpressionMultiscript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionMultiscript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionMultiscript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionMultiscript/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionMultiscript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRoot/title",
          "value": "AXMathExpressionRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRoot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionOperator/title",
          "value": "AXMathExpressionOperator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionOperator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionOperator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFenced/title",
          "value": "AXMathExpressionFenced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFenced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionFenced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFenced/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionFenced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionIdentifier/title",
          "value": "AXMathExpressionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionProvider/title",
          "value": "AXMathExpressionProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableCell/title",
          "value": "AXMathExpressionTableCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTableCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTableCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFraction/title",
          "value": "AXMathExpressionFraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionFraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionFraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableRow/title",
          "value": "AXMathExpressionTableRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTableRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableRow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTableRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTable/title",
          "value": "AXMathExpressionTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSessionManager/title",
          "value": "AXFeatureOverrideSessionManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSessionManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXFeatureOverrideSessionManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXFeatureOverrideSessionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionUnderOver/title",
          "value": "AXMathExpressionUnderOver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionUnderOver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionUnderOver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionUnderOver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionUnderOver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionNumber/title",
          "value": "AXMathExpressionNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionNumber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
