{
  "abstract": [
    {
      "text": "Help users access and manage their external accounts from within your app, without requiring them to enter login credentials.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "The Accounts framework is deprecated. For new apps, instead of using Accounts, contact the provider of the service you integrate with, to get access to their SDK or documentation about managing accounts with their service.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accounts/documentation/Accounts"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "Accounts",
    "modules": [
      {
        "name": "Accounts"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "5.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "5.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.8",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Accounts"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Accounts framework provides access to user accounts stored in the Accounts database, which is managed by the system. An account stores the login credentials of a particular service, such as LinkedIn, and you use those credentials to authenticate with the service. When you integrate the Accounts framework into your app, you don’t need to store account logins yourself. Instead, the user grants your app access to use their account login credentials, bypassing the need to type their username and password. If no account for a particular service exists in the user’s Accounts database, you can let them create and save an account from within your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accounts/documentation/Accounts": {
      "abstract": [
        {
          "text": "Help users access and manage their external accounts from within your app, without requiring them to enter login credentials.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.accounts/documentation/Accounts",
      "kind": "symbol",
      "role": "collection",
      "title": "Accounts",
      "type": "topic",
      "url": "/documentation/accounts"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccount": {
      "abstract": [
        {
          "text": "The information associated with one of the user’s accounts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccount"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccount"
        }
      ],
      "role": "symbol",
      "title": "ACAccount",
      "type": "topic",
      "url": "/documentation/accounts/acaccount"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountCredential": {
      "abstract": [
        {
          "text": "A credential object that encapsulates the information needed to authenticate a user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountCredential"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountCredential"
        }
      ],
      "role": "symbol",
      "title": "ACAccountCredential",
      "type": "topic",
      "url": "/documentation/accounts/acaccountcredential"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore": {
      "abstract": [
        {
          "text": "The object you use to request, manage, and store the user’s account information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountStore"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountStore"
        }
      ],
      "role": "symbol",
      "title": "ACAccountStore",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountType": {
      "abstract": [
        {
          "text": "An object that encapsulates information about all accounts of a particular type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountType"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountType"
        }
      ],
      "role": "symbol",
      "title": "ACAccountType",
      "type": "topic",
      "url": "/documentation/accounts/acaccounttype"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACCOUNTS_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ACCOUNTS_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACCOUNTS_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "ACCOUNTS_EXTERN",
      "type": "topic",
      "url": "/documentation/accounts/accounts_extern"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorCode": {
      "abstract": [
        {
          "text": "Codes for errors that may occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorCode"
        }
      ],
      "role": "symbol",
      "title": "ACErrorCode",
      "type": "topic",
      "url": "/documentation/accounts/acerrorcode"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for the Accounts framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ACErrorDomain",
      "type": "topic",
      "url": "/documentation/accounts/acerrordomain"
    },
    "doc://com.apple.accounts/documentation/Accounts/deprecated-symbols": {
      "abstract": [
        {
          "text": "Avoid using deprecated symbols in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/accounts/deprecated-symbols"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Account-Management",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore",
        "doc://com.apple.accounts/documentation/Accounts/ACAccount",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountCredential"
      ],
      "title": "Account Management"
    },
    {
      "anchor": "Account-Types",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountType"
      ],
      "title": "Account Types"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACErrorCode",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorDomain"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/deprecated-symbols"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Account-Management",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore",
                "doc://com.apple.accounts/documentation/Accounts/ACAccount",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountCredential"
              ],
              "title": "Account Management"
            },
            {
              "anchor": "Account-Types",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountType"
              ],
              "title": "Account Types"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACErrorCode",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorDomain"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/deprecated-symbols"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACCOUNTS_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "The Accounts framework is deprecated. For new apps, instead of using Accounts, contact the provider of the service you integrate with, to get access to their SDK or documentation about managing accounts with their service.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorDomain/title",
          "value": "ACErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccount/title",
          "value": "ACAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredential/title",
          "value": "ACAccountCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredential/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCode/title",
          "value": "ACErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountType/title",
          "value": "ACAccountType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/title",
          "value": "ACAccountStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accounts"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accounts"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
