{
  "abstract": [
    {
      "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.agl/documentation/AGL"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "AGL",
    "modules": [
      {
        "name": "AGL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "AGL"
  },
  "references": {
    "doc://com.apple.agl/documentation/AGL": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL",
      "kind": "symbol",
      "role": "collection",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl"
    },
    "doc://com.apple.agl/documentation/AGL/AGL-collection": {
      "abstract": [
        {
          "text": "Create and manage OpenGL rendering contexts for use in macOS, and perform operations on drawable objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.agl/documentation/AGL/AGL-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL",
      "type": "topic",
      "url": "/documentation/agl/agl-collection"
    },
    "doc://com.apple.agl/documentation/AGL/agl-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.agl/documentation/AGL/agl-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL Constants",
      "type": "topic",
      "url": "/documentation/agl/agl-constants"
    },
    "doc://com.apple.agl/documentation/AGL/agl-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.agl/documentation/AGL/agl-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL Data Types",
      "type": "topic",
      "url": "/documentation/agl/agl-data-types"
    },
    "doc://com.apple.agl/documentation/AGL/agl-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.agl/documentation/AGL/agl-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AGL Functions",
      "type": "topic",
      "url": "/documentation/agl/agl-functions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.agl/documentation/AGL/AGL-collection",
        "doc://com.apple.agl/documentation/AGL/agl-constants",
        "doc://com.apple.agl/documentation/AGL/agl-functions",
        "doc://com.apple.agl/documentation/AGL/agl-data-types"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.agl/documentation/AGL/AGL-collection",
                "doc://com.apple.agl/documentation/AGL/agl-constants",
                "doc://com.apple.agl/documentation/AGL/agl-functions",
                "doc://com.apple.agl/documentation/AGL/agl-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/agl"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/agl"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
