{
  "abstract": [
    {
      "text": "Provide people a shortcut to selected content and features of your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appclip/documentation/AppClip"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "AppClip",
    "modules": [
      {
        "name": "App Clips"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "App Clips"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "App Clip",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is a lightweight version of your app that offers people access to some of the app’s functionality. A coffee shop app downloaded and installed from the App Store, for example, might provide people the ability to order a drink, save favorites, collect rewards, get special offers, and so on. The coffee shop App Clip only offers the functionality to order a drink.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4301753",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "People find an App Clip by performing an ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "invocation,",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " for example, by tapping a location-based suggestion from Siri Suggestions or by scanning an App Clip Code. After a person confirms the invocation, the App Clip launches instantly, helps a person perform an everyday task as quickly as possible, and only stays on their device for as long as they need it. When a person installs the corresponding full app for your App Clip, the full app replaces the App Clip. From this moment on, confirming an invocation launches the full app instead of the App Clip, and a person gets the functionality of the App Clip within the full app. If they don’t install the full app, the system automatically removes the App Clip after a period of inactivity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Again, consider the coffee shop’s App Clip: When a person walks past the coffee shop, the system displays a location-based suggestion from Siri Suggestions on their device. They tap the suggestion, confirm the launch of the App Clip on the system-provided ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "App Clip card",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", and instantly use the App Clip to order a drink. After a person completes the order, the App Clip recommends its corresponding app to them, and they download the app. The next time they tap the location-based suggestion, they launch the full app instead of the App Clip. If they don’t install the app, tapping the suggestion and confirming the invocation continues launching the App Clip.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Session 10178: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc23/10178",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " (WWDC23)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Session 10097: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc22/10097",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " (WWDC22)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Session 10013: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc21/10013",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " (WWDC21)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Session 10012:  ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc21/10012",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " (WWDC21)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Related sessions from WWDC21, WWDC22, and WWDC23",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Offer-a-great-user-experience",
          "level": 3,
          "text": "Offer a great user experience",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "App Clips provide a polished user experience that helps users solve a real-world task as quickly as possible. Additionally, App Clips don’t appear on the Home screen, and users don’t manage them the way they manage full apps. Instead, the system removes an App Clip from a device after a period of inactivity, emphasizing the importance of a polished user experience.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/app-clips/overview/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Review-App-Clip-creation",
          "level": 3,
          "text": "Review App Clip creation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Limit the function of an App Clip to ensure a fast launch experience, protect user privacy, and preserve resources. Before you create an App Clip, first review the technology available to App Clips and identify which of your app’s functionalities would make a great App Clip. When you create an App Clip, plan to spend time with:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Making changes to your app’s Xcode project and your code, for example, adding an App Clip target or sharing code between your App Clip and full app",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Planning the launch experience for your App Clip, identifying invocations to support, and adding code to respond to them",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Associating your App Clip with your website to support additional invocations and advanced App Clip experiences (optional)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Creating App Clip experiences in App Store Connect",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Creating App Clip Codes that offer the best experience for people to discover and launch your App Clip (optional)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appclip/documentation/AppClip": {
      "abstract": [
        {
          "text": "Provide people a shortcut to selected content and features of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip",
      "kind": "symbol",
      "role": "collection",
      "title": "App Clips",
      "type": "topic",
      "url": "/documentation/appclip"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayload": {
      "abstract": [
        {
          "text": "Information that’s passed to an App Clip on launch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "APActivationPayload"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APActivationPayload"
        }
      ],
      "role": "symbol",
      "title": "APActivationPayload",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayload"
    },
    "doc://com.apple.appclip/documentation/AppClip/AP_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AP_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/AP_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "AP_EXTERN",
      "type": "topic",
      "url": "/documentation/appclip/ap_extern"
    },
    "doc://com.apple.appclip/documentation/AppClip/associating-your-app-clip-with-your-website": {
      "abstract": [
        {
          "text": "Enable the system to verify your App Clip to support invocations in iOS 16.3 or earlier and from your website.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/associating-your-app-clip-with-your-website",
      "kind": "article",
      "role": "article",
      "title": "Associating your App Clip with your website",
      "type": "topic",
      "url": "/documentation/appclip/associating-your-app-clip-with-your-website"
    },
    "doc://com.apple.appclip/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip": {
      "abstract": [
        {
          "text": "Review frameworks available to App Clips and identify functionality that makes a great App Clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip",
      "kind": "article",
      "role": "article",
      "title": "Choosing the right functionality for your App Clip",
      "type": "topic",
      "url": "/documentation/appclip/choosing-the-right-functionality-for-your-app-clip"
    },
    "doc://com.apple.appclip/documentation/AppClip/configuring-the-launch-experience-of-your-app-clip": {
      "abstract": [
        {
          "text": "Review how people launch your App Clip, identify invocation URLs, make use of default App Clip links, and configure experiences in App Store Connect.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/configuring-the-launch-experience-of-your-app-clip",
      "kind": "article",
      "role": "article",
      "title": "Configuring the launch experience of your App Clip",
      "type": "topic",
      "url": "/documentation/appclip/configuring-the-launch-experience-of-your-app-clip"
    },
    "doc://com.apple.appclip/documentation/AppClip/confirming-a-person-s-physical-location": {
      "abstract": [
        {
          "text": "Add code to quickly confirm a person’s physical location while respecting their privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/confirming-a-person-s-physical-location",
      "kind": "article",
      "role": "article",
      "title": "Confirming a person’s physical location",
      "type": "topic",
      "url": "/documentation/appclip/confirming-a-person-s-physical-location"
    },
    "doc://com.apple.appclip/documentation/AppClip/creating-an-app-clip-with-xcode": {
      "abstract": [
        {
          "text": "Add an App Clip target to your Xcode project and share code between the App Clip and its corresponding full app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/creating-an-app-clip-with-xcode",
      "kind": "article",
      "role": "article",
      "title": "Creating an App Clip with Xcode",
      "type": "topic",
      "url": "/documentation/appclip/creating-an-app-clip-with-xcode"
    },
    "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes": {
      "abstract": [
        {
          "text": "Help users discover your App Clip by using an NFC-integrated or scan-only App Clip Code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes",
      "kind": "article",
      "role": "article",
      "title": "Creating App Clip Codes",
      "type": "topic",
      "url": "/documentation/appclip/creating-app-clip-codes"
    },
    "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes-with-app-store-connect": {
      "abstract": [
        {
          "text": "Select one or more advanced App Clip experiences in App Store Connect and create App Clip Codes for users to scan to launch your App Clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes-with-app-store-connect",
      "kind": "article",
      "role": "article",
      "title": "Creating App Clip Codes with App Store Connect",
      "type": "topic",
      "url": "/documentation/appclip/creating-app-clip-codes-with-app-store-connect"
    },
    "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes-with-the-app-clip-code-generator": {
      "abstract": [
        {
          "text": "Use the App Clip Code Generator command-line tool to verify your code’s colors, get color suggestions, and create App Clip Codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes-with-the-app-clip-code-generator",
      "kind": "article",
      "role": "article",
      "title": "Creating App Clip Codes with the App Clip Code Generator",
      "type": "topic",
      "url": "/documentation/appclip/creating-app-clip-codes-with-the-app-clip-code-generator"
    },
    "doc://com.apple.appclip/documentation/AppClip/distributing-your-app-clip": {
      "abstract": [
        {
          "text": "Archive the full app for your App Clip, upload it to App Store Connect, and distribute it to testers or publish it on the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/distributing-your-app-clip",
      "kind": "article",
      "role": "article",
      "title": "Distributing your App Clip",
      "type": "topic",
      "url": "/documentation/appclip/distributing-your-app-clip"
    },
    "doc://com.apple.appclip/documentation/AppClip/enabling-notifications-in-app-clips": {
      "abstract": [
        {
          "text": "Enable your App Clip to schedule and receive notifications for a short or extended time period.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/enabling-notifications-in-app-clips",
      "kind": "article",
      "role": "article",
      "title": "Enabling notifications in App Clips",
      "type": "topic",
      "url": "/documentation/appclip/enabling-notifications-in-app-clips"
    },
    "doc://com.apple.appclip/documentation/AppClip/encoding-a-url-in-an-app-clip-code": {
      "abstract": [
        {
          "text": "Choose an invocation URL for your App Clip Code that you can encode efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/encoding-a-url-in-an-app-clip-code",
      "kind": "article",
      "role": "article",
      "title": "Encoding a URL in an App Clip Code",
      "type": "topic",
      "url": "/documentation/appclip/encoding-a-url-in-an-app-clip-code"
    },
    "doc://com.apple.appclip/documentation/AppClip/interacting-with-app-clip-codes-in-ar": {
      "abstract": [
        {
          "text": "Display content and provide services in an AR experience with App Clip Codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/interacting-with-app-clip-codes-in-ar",
      "kind": "article",
      "role": "sampleCode",
      "title": "Interacting with App Clip Codes in AR",
      "type": "topic",
      "url": "/documentation/appclip/interacting-with-app-clip-codes-in-ar"
    },
    "doc://com.apple.appclip/documentation/AppClip/launching-another-app-s-app-clip-from-your-app": {
      "abstract": [
        {
          "text": "Enable people to launch another app’s App Clip from your app with App Clip links and offer a rich preview of it with the Link Presentation framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/launching-another-app-s-app-clip-from-your-app",
      "kind": "article",
      "role": "article",
      "title": "Launching another app’s App Clip from your app",
      "type": "topic",
      "url": "/documentation/appclip/launching-another-app-s-app-clip-from-your-app"
    },
    "doc://com.apple.appclip/documentation/AppClip/offering-live-activities-with-your-app-clip": {
      "abstract": [
        {
          "text": "Add a widget extension to your App Clip target and use ActivityKit to display Live Activities on the Lock Screen and in the Dynamic Island.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/offering-live-activities-with-your-app-clip",
      "kind": "article",
      "role": "article",
      "title": "Offering Live Activities with your App Clip",
      "type": "topic",
      "url": "/documentation/appclip/offering-live-activities-with-your-app-clip"
    },
    "doc://com.apple.appclip/documentation/AppClip/preparing-multiple-app-clip-codes-for-production": {
      "abstract": [
        {
          "text": "Prepare your App Clip Codes to send to a professional printing service.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/preparing-multiple-app-clip-codes-for-production",
      "kind": "article",
      "role": "article",
      "title": "Preparing multiple App Clip Codes for production",
      "type": "topic",
      "url": "/documentation/appclip/preparing-multiple-app-clip-codes-for-production"
    },
    "doc://com.apple.appclip/documentation/AppClip/recommending-your-app-to-app-clip-users": {
      "abstract": [
        {
          "text": "Display an overlay in your App Clip to recommend your app to users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/recommending-your-app-to-app-clip-users",
      "kind": "article",
      "role": "article",
      "title": "Recommending your app to App Clip users",
      "type": "topic",
      "url": "/documentation/appclip/recommending-your-app-to-app-clip-users"
    },
    "doc://com.apple.appclip/documentation/AppClip/responding-to-invocations": {
      "abstract": [
        {
          "text": "Add code to respond to invocations and offer a focused launch experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/responding-to-invocations",
      "kind": "article",
      "role": "article",
      "title": "Responding to invocations",
      "type": "topic",
      "url": "/documentation/appclip/responding-to-invocations"
    },
    "doc://com.apple.appclip/documentation/AppClip/sharing-data-between-your-app-clip-and-your-full-app": {
      "abstract": [
        {
          "text": "Use CloudKit, Sign in with Apple, shared user defaults or containers, and the keychain to offer a smooth transition from your App Clip to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/sharing-data-between-your-app-clip-and-your-full-app",
      "kind": "article",
      "role": "article",
      "title": "Sharing data between your App Clip and your full app",
      "type": "topic",
      "url": "/documentation/appclip/sharing-data-between-your-app-clip-and-your-full-app"
    },
    "doc://com.apple.appclip/documentation/AppClip/supporting-invocations-from-your-website-and-the-messages-app": {
      "abstract": [
        {
          "text": "Display a Smart App Banner and the App Clip card on your website that people tap to launch your App Clip, and add support for invocations from the Messages app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/supporting-invocations-from-your-website-and-the-messages-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting invocations from your website and the Messages app",
      "type": "topic",
      "url": "/documentation/appclip/supporting-invocations-from-your-website-and-the-messages-app"
    },
    "doc://com.apple.appclip/documentation/AppClip/testing-the-launch-experience-of-your-app-clip": {
      "abstract": [
        {
          "text": "Debug App Clip invocations, test the launch experience, and verify the configuration of your released App Clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/testing-the-launch-experience-of-your-app-clip",
      "kind": "article",
      "role": "article",
      "title": "Testing the launch experience of your App Clip",
      "type": "topic",
      "url": "/documentation/appclip/testing-the-launch-experience-of-your-app-clip"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.associated-appclip-app-identifiers": {
      "abstract": [
        {
          "text": "A list of App Clip identifiers for an app with exactly one entry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.associated-appclip-app-identifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.associated-appclip-app-identifiers",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.associated-appclip-app-identifiers"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.on-demand-install-capable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a bundle represents an App Clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.on-demand-install-capable",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.on-demand-install-capable",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.on-demand-install-capable"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.parent-application-identifiers": {
      "abstract": [
        {
          "text": "A list of parent application identifiers for an App Clip with exactly one entry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.parent-application-identifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "Parent Application Identifiers Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.parent-application-identifiers"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppClip": {
      "abstract": [
        {
          "text": "A collection of keys that an App Clip uses to get additional capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppClip",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppClip",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSAppClip"
    },
    "doc://com.apple.documentation/documentation/appclip/fruta_building_a_feature-rich_app_with_swiftui": {
      "abstract": [
        {
          "text": "Create a shared codebase to build a multiplatform app that offers widgets and an App Clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appclip/fruta_building_a_feature-rich_app_with_swiftui",
      "kind": "article",
      "role": "sampleCode",
      "title": "Fruta: Building a Feature-Rich App with SwiftUI",
      "type": "topic",
      "url": "/documentation/appclip/fruta_building_a_feature-rich_app_with_swiftui"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/design/human-interface-guidelines/app-clips/overview/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/app-clips/overview/",
      "title": "Human Interface Guidelines > App Clips",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > App Clips",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/app-clips/overview/"
    },
    "https://developer.apple.com/wwdc21/10012": {
      "identifier": "https://developer.apple.com/wwdc21/10012",
      "title": "What’s new in App Clips",
      "titleInlineContent": [
        {
          "text": "What’s new in App Clips",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10012"
    },
    "https://developer.apple.com/wwdc21/10013": {
      "identifier": "https://developer.apple.com/wwdc21/10013",
      "title": "Build light and fast App Clips",
      "titleInlineContent": [
        {
          "text": "Build light and fast App Clips",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10013"
    },
    "https://developer.apple.com/wwdc22/10097": {
      "identifier": "https://developer.apple.com/wwdc22/10097",
      "title": "What’s new in App Clips",
      "titleInlineContent": [
        {
          "text": "What’s new in App Clips",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc22/10097"
    },
    "https://developer.apple.com/wwdc23/10178": {
      "identifier": "https://developer.apple.com/wwdc23/10178",
      "title": "What’s new in App Clips",
      "titleInlineContent": [
        {
          "text": "What’s new in App Clips",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc23/10178"
    },
    "media-4301753": {
      "alt": "A flowchart illustrating the flow for an App Clip. From left to right, the images shows an App Clip Code as an invocation, an App Clip card for a donut shop, the App Clip of the donut shop, and a donut.",
      "identifier": "media-4301753",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1fa269ccc94c2866e6b1c27d127a4cb5/media-4301753@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8ae03b1de889eefa91bb309ad8d53b8a/media-4301753~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Creation",
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/creating-an-app-clip-with-xcode",
        "doc://com.apple.documentation/documentation/appclip/fruta_building_a_feature-rich_app_with_swiftui",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.parent-application-identifiers",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.associated-appclip-app-identifiers",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.on-demand-install-capable"
      ],
      "title": "Creation"
    },
    {
      "anchor": "Launch",
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/configuring-the-launch-experience-of-your-app-clip",
        "doc://com.apple.appclip/documentation/AppClip/associating-your-app-clip-with-your-website",
        "doc://com.apple.appclip/documentation/AppClip/supporting-invocations-from-your-website-and-the-messages-app",
        "doc://com.apple.appclip/documentation/AppClip/responding-to-invocations",
        "doc://com.apple.appclip/documentation/AppClip/confirming-a-person-s-physical-location",
        "doc://com.apple.appclip/documentation/AppClip/launching-another-app-s-app-clip-from-your-app",
        "doc://com.apple.appclip/documentation/AppClip/APActivationPayload",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppClip"
      ],
      "title": "Launch"
    },
    {
      "anchor": "App-Clip-Codes",
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes",
        "doc://com.apple.appclip/documentation/AppClip/preparing-multiple-app-clip-codes-for-production",
        "doc://com.apple.appclip/documentation/AppClip/interacting-with-app-clip-codes-in-ar"
      ],
      "title": "App Clip Codes"
    },
    {
      "anchor": "App-Clip-to-full-app-transition",
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/recommending-your-app-to-app-clip-users",
        "doc://com.apple.appclip/documentation/AppClip/sharing-data-between-your-app-clip-and-your-full-app"
      ],
      "title": "App Clip to full app transition"
    },
    {
      "anchor": "Notifications",
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/enabling-notifications-in-app-clips"
      ],
      "title": "Notifications"
    },
    {
      "anchor": "Live-Activities",
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/offering-live-activities-with-your-app-clip"
      ],
      "title": "Live Activities"
    },
    {
      "anchor": "Testing",
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/testing-the-launch-experience-of-your-app-clip"
      ],
      "title": "Testing"
    },
    {
      "anchor": "Distribution",
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/distributing-your-app-clip"
      ],
      "title": "Distribution"
    },
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes-with-app-store-connect",
        "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes-with-the-app-clip-code-generator",
        "doc://com.apple.appclip/documentation/AppClip/encoding-a-url-in-an-app-clip-code"
      ],
      "title": "Articles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Creation",
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/creating-an-app-clip-with-xcode",
                "doc://com.apple.documentation/documentation/appclip/fruta_building_a_feature-rich_app_with_swiftui",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.parent-application-identifiers",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.associated-appclip-app-identifiers",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.on-demand-install-capable"
              ],
              "title": "Creation"
            },
            {
              "anchor": "Launch",
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/configuring-the-launch-experience-of-your-app-clip",
                "doc://com.apple.appclip/documentation/AppClip/associating-your-app-clip-with-your-website",
                "doc://com.apple.appclip/documentation/AppClip/supporting-invocations-from-your-website-and-the-messages-app",
                "doc://com.apple.appclip/documentation/AppClip/responding-to-invocations",
                "doc://com.apple.appclip/documentation/AppClip/confirming-a-person-s-physical-location",
                "doc://com.apple.appclip/documentation/AppClip/launching-another-app-s-app-clip-from-your-app",
                "doc://com.apple.appclip/documentation/AppClip/APActivationPayload",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSAppClip"
              ],
              "title": "Launch"
            },
            {
              "anchor": "App-Clip-Codes",
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes",
                "doc://com.apple.appclip/documentation/AppClip/preparing-multiple-app-clip-codes-for-production",
                "doc://com.apple.appclip/documentation/AppClip/interacting-with-app-clip-codes-in-ar"
              ],
              "title": "App Clip Codes"
            },
            {
              "anchor": "App-Clip-to-full-app-transition",
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/recommending-your-app-to-app-clip-users",
                "doc://com.apple.appclip/documentation/AppClip/sharing-data-between-your-app-clip-and-your-full-app"
              ],
              "title": "App Clip to full app transition"
            },
            {
              "anchor": "Notifications",
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/enabling-notifications-in-app-clips"
              ],
              "title": "Notifications"
            },
            {
              "anchor": "Live-Activities",
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/offering-live-activities-with-your-app-clip"
              ],
              "title": "Live Activities"
            },
            {
              "anchor": "Testing",
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/testing-the-launch-experience-of-your-app-clip"
              ],
              "title": "Testing"
            },
            {
              "anchor": "Distribution",
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/distributing-your-app-clip"
              ],
              "title": "Distribution"
            },
            {
              "anchor": "Articles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes-with-app-store-connect",
                "doc://com.apple.appclip/documentation/AppClip/creating-app-clip-codes-with-the-app-clip-code-generator",
                "doc://com.apple.appclip/documentation/AppClip/encoding-a-url-in-an-app-clip-code"
              ],
              "title": "Articles"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appclip/documentation/AppClip/AP_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayload/title",
          "value": "APActivationPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "APActivationPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APActivationPayload"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appclip"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appclip"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
