{
  "abstract": [
    {
      "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "AppKit",
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "AppKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "AppKit contains the objects you need to build the user interface for a macOS app. In addition to drawing windows, buttons, panels, and text fields, it handles all the event management and interaction between your app, people, and macOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4209947",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Aside from drawing and managing interactions, AppKit handles printing, animating, as well as creating documents with large amounts of data efficiently. The framework also contains built-in support for localization and accessibility to ensure that your app reaches as many people as possible.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "AppKit also works with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", so you can implement parts of your AppKit app in SwiftUI or mix interface elements between the two frameworks. For example, you can place AppKit views and view controllers inside SwiftUI views, and vice versa.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "For information about bringing your iPad app to Mac, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/mac-catalyst",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". To build an iOS app, you can use SwiftUI to create an app that works across all of Apple’s platforms, or use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to create an app for iOS only.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "SwiftUI-PageImage-card.png": {
      "alt": "A black Swift logo on a swirly blue and purple background.",
      "identifier": "SwiftUI-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1450d0b30a6b024e10c148e3f31dafe9/SwiftUI-PageImage-card~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b1de0de086f81a5d0eac3839a0af6e6f/SwiftUI-PageImage-card@2x.png"
        }
      ]
    },
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/IBSegueAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IBSegueAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/IBSegueAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "IBSegueAction",
      "type": "topic",
      "url": "/documentation/appkit/ibsegueaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplicationProtectedDataDidBecomeAvailableNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSApplicationProtectedDataDidBecomeAvailableNotification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationProtectedDataDidBecomeAvailableNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationProtectedDataDidBecomeAvailableNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsapplicationprotecteddatadidbecomeavailablenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplicationProtectedDataWillBecomeUnavailableNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSApplicationProtectedDataWillBecomeUnavailableNotification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationProtectedDataWillBecomeUnavailableNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationProtectedDataWillBecomeUnavailableNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsapplicationprotecteddatawillbecomeunavailablenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNoUnderlineStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSNoUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNoUnderlineStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNoUnderlineStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsnounderlinestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/AccessBehavior-swift.enum": {
      "abstract": [
        {
          "text": "A value indicating pasteboard access behavior.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/AccessBehavior-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard.AccessBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/accessbehavior-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardCommunicationError": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboardCommunicationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardCommunicationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardCommunicationError"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboardCommunicationError",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboardcommunicationerror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardContentsNotAvailableError": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboardContentsNotAvailableError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardContentsNotAvailableError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardContentsNotAvailableError"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboardContentsNotAvailableError",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboardcontentsnotavailableerror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPattern": {
      "abstract": [
        {
          "text": "A pattern to detect on the pasteboard, such as a URL, text, or a number.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPattern"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPattern",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPattern",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpattern"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternCalendarEvent": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains a calendar event.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPatternCalendarEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternCalendarEvent",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPatternCalendarEvent",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpatterncalendarevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternEmailAddress": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains an email address.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPatternEmailAddress"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternEmailAddress",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPatternEmailAddress",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpatternemailaddress"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternFlightNumber": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains a flight number.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPatternFlightNumber"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternFlightNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPatternFlightNumber",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpatternflightnumber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternLink": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains a URL.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPatternLink"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternLink",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPatternLink",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpatternlink"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternMoneyAmount": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains an amount of money.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPatternMoneyAmount"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternMoneyAmount",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPatternMoneyAmount",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpatternmoneyamount"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternNumber": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that consists of a numeric value.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPatternNumber"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPatternNumber",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpatternnumber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternPhoneNumber": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains a phone number.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPatternPhoneNumber"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternPhoneNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPatternPhoneNumber",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpatternphonenumber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternPostalAddress": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains a postal address.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPatternPostalAddress"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternPostalAddress",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPatternPostalAddress",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpatternpostaladdress"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternProbableWebSearch": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string suitable for use as a web search term.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPatternProbableWebSearch"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternProbableWebSearch",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPatternProbableWebSearch",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpatternprobablewebsearch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternProbableWebURL": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that consists of a web URL.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPatternProbableWebURL"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternProbableWebURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPatternProbableWebURL",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpatternprobableweburl"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternShipmentTrackingNumber": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains a parcel tracking number and carrier.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardDetectionPatternShipmentTrackingNumber"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternShipmentTrackingNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardDetectionPatternShipmentTrackingNumber",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarddetectionpatternshipmenttrackingnumber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardErrorMaximum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboardErrorMaximum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardErrorMaximum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardErrorMaximum"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboardErrorMaximum",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarderrormaximum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardErrorMinimum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboardErrorMinimum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardErrorMinimum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardErrorMinimum"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboardErrorMinimum",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarderrorminimum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardInvalidArgumentError": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboardInvalidArgumentError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardInvalidArgumentError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardInvalidArgumentError"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboardInvalidArgumentError",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboardinvalidargumenterror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardMetadataType": {
      "abstract": [
        {
          "text": "A metadata type to detect on the pasteboard.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardMetadataType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardMetadataType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardMetadataType",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboardmetadatatype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardMetadataTypeContentType": {
      "abstract": [
        {
          "text": "A metadata type that returns the content type if the pasteboard detects a reference to a file.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPasteboardMetadataTypeContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardMetadataTypeContentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPasteboardMetadataTypeContentType",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboardmetadatatypecontenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardMiscellaneousError": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboardMiscellaneousError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardMiscellaneousError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardMiscellaneousError"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboardMiscellaneousError",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboardmiscellaneouserror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSingleUnderlineStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSingleUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSingleUnderlineStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSingleUnderlineStyle",
      "type": "topic",
      "url": "/documentation/appkit/nssingleunderlinestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSuggestionItem": {
      "abstract": [
        {
          "text": "The items that appear in suggestion menus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSuggestionItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSuggestionItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSuggestionItem"
        }
      ],
      "role": "symbol",
      "title": "NSSuggestionItem",
      "type": "topic",
      "url": "/documentation/appkit/nssuggestionitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSuggestionItemResponse": {
      "abstract": [
        {
          "text": "Describes the result of a batch of suggestion items from a search",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSuggestionItemResponse"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSuggestionItemResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSuggestionItemResponse"
        }
      ],
      "role": "symbol",
      "title": "NSSuggestionItemResponse",
      "type": "topic",
      "url": "/documentation/appkit/nssuggestionitemresponse"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSuggestionItemSection": {
      "abstract": [
        {
          "text": "Describes a section of suggestions items in a suggestions menu",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSuggestionItemSection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSuggestionItemSection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSuggestionItemSection"
        }
      ],
      "role": "symbol",
      "title": "NSSuggestionItemSection",
      "type": "topic",
      "url": "/documentation/appkit/nssuggestionitemsection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSuggestionsDelegate": {
      "abstract": [
        {
          "text": "A protocol for suggestion delegates of text fields to conform to in order to provide text suggestions in response to the user typing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextSuggestionsDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSuggestionsDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSuggestionsDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSTextSuggestionsDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nstextsuggestionsdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/Identifier/writingToolsItemIdentifier": {
      "abstract": [
        {
          "text": "A standard item that is configured to send -showWritingTools: to the firstResponder when invoked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writingToolsItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSToolbarItem",
          "text": "NSToolbarItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSToolbarItemIdentifier",
          "text": "Identifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/Identifier/writingToolsItemIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSToolbarWritingToolsItemIdentifier"
        }
      ],
      "role": "symbol",
      "title": "writingToolsItemIdentifier",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritem/identifier/writingtoolsitemidentifier"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewContentSelectionInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewContentSelectionInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewContentSelectionInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewContentSelectionInfo"
        }
      ],
      "role": "symbol",
      "title": "NSViewContentSelectionInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsviewcontentselectioninfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsExclusionAttributeName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsExclusionAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsExclusionAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWritingToolsExclusionAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsexclusionattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/Preview(_:traits:body:)-55ljx": {
      "abstract": [
        {
          "text": "Preview an NSViewController.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "macro"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "traits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport12PreviewTraitV",
          "text": "PreviewTrait"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV10ViewTraitsO",
          "text": "ViewTraits"
        },
        {
          "kind": "text",
          "text": ">..., "
        },
        {
          "kind": "externalParam",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSViewController",
          "text": "NSViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/Preview(_:traits:body:)-55ljx",
      "kind": "symbol",
      "role": "symbol",
      "title": "Preview(_:traits:body:)",
      "type": "topic",
      "url": "/documentation/appkit/preview(_:traits:body:)-55ljx"
    },
    "doc://com.apple.appkit/documentation/AppKit/Preview(_:traits:body:)-7pfjp": {
      "abstract": [
        {
          "text": "Preview an NSView.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "macro"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "traits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport12PreviewTraitV",
          "text": "PreviewTrait"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV10ViewTraitsO",
          "text": "ViewTraits"
        },
        {
          "kind": "text",
          "text": ">..., "
        },
        {
          "kind": "externalParam",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/Preview(_:traits:body:)-7pfjp",
      "kind": "symbol",
      "role": "symbol",
      "title": "Preview(_:traits:body:)",
      "type": "topic",
      "url": "/documentation/appkit/preview(_:traits:body:)-7pfjp"
    },
    "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit": {
      "abstract": [
        {
          "text": "Make your AppKit apps accessible to everyone who uses macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility for AppKit",
      "type": "topic",
      "url": "/documentation/appkit/accessibility-for-appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/animation": {
      "abstract": [
        {
          "text": "Animate your views and other content to create a more engaging experience for users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/animation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation",
      "type": "topic",
      "url": "/documentation/appkit/animation"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-and-environment": {
      "abstract": [
        {
          "text": "Learn about the objects that you use to interact with the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and Environment",
      "type": "topic",
      "url": "/documentation/appkit/app-and-environment"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-extensions": {
      "abstract": [
        {
          "text": "Extend your app’s basic functionality to other parts of the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App Extensions",
      "type": "topic",
      "url": "/documentation/appkit/app-extensions"
    },
    "doc://com.apple.appkit/documentation/AppKit/appearance-customization": {
      "abstract": [
        {
          "text": "Add Dark Mode support to your app, and use appearance proxies to modify your UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/appearance-customization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Appearance Customization",
      "type": "topic",
      "url": "/documentation/appkit/appearance-customization"
    },
    "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings": {
      "abstract": [
        {
          "text": "Automatically synchronize your data model with your app’s interface using Cocoa Bindings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cocoa Bindings",
      "type": "topic",
      "url": "/documentation/appkit/cocoa-bindings"
    },
    "doc://com.apple.appkit/documentation/AppKit/color": {
      "abstract": [
        {
          "text": "Represent colors using built-in or custom formats, and give users options for selecting and applying colors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/color",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color",
      "type": "topic",
      "url": "/documentation/appkit/color"
    },
    "doc://com.apple.appkit/documentation/AppKit/constants": {
      "abstract": [
        {
          "text": "Constants for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Constants",
      "type": "topic",
      "url": "/documentation/appkit/constants"
    },
    "doc://com.apple.appkit/documentation/AppKit/data-types": {
      "abstract": [
        {
          "text": "Data types for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Types",
      "type": "topic",
      "url": "/documentation/appkit/data-types"
    },
    "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review symbols that are no longer supported, and find the replacements to use instead.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/appkit/deprecated-symbols"
    },
    "doc://com.apple.appkit/documentation/AppKit/documents-data-and-pasteboard": {
      "abstract": [
        {
          "text": "Organize your app’s data and preferences, and share that data on the pasteboard or in iCloud.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/documents-data-and-pasteboard",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Documents, Data, and Pasteboard",
      "type": "topic",
      "url": "/documentation/appkit/documents-data-and-pasteboard"
    },
    "doc://com.apple.appkit/documentation/AppKit/drag-and-drop": {
      "abstract": [
        {
          "text": "Support the direct manipulation of your app’s content using drag and drop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drag and Drop",
      "type": "topic",
      "url": "/documentation/appkit/drag-and-drop"
    },
    "doc://com.apple.appkit/documentation/AppKit/drawing": {
      "abstract": [
        {
          "text": "Draw shapes, images, and other content on the screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/drawing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drawing",
      "type": "topic",
      "url": "/documentation/appkit/drawing"
    },
    "doc://com.apple.appkit/documentation/AppKit/enumerations": {
      "abstract": [
        {
          "text": "Enumerations for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Enumerations",
      "type": "topic",
      "url": "/documentation/appkit/enumerations"
    },
    "doc://com.apple.appkit/documentation/AppKit/fonts": {
      "abstract": [
        {
          "text": "Manage the fonts used to display text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/fonts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Fonts",
      "type": "topic",
      "url": "/documentation/appkit/fonts"
    },
    "doc://com.apple.appkit/documentation/AppKit/gestures": {
      "abstract": [
        {
          "text": "Encapsulate your app’s event-handling logic in gesture recognizers so that you can reuse that code throughout your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/gestures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Gestures",
      "type": "topic",
      "url": "/documentation/appkit/gestures"
    },
    "doc://com.apple.appkit/documentation/AppKit/images-and-pdf": {
      "abstract": [
        {
          "text": "Create and manage images, in bitmap, PDF, and other formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/images-and-pdf",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Images and PDF",
      "type": "topic",
      "url": "/documentation/appkit/images-and-pdf"
    },
    "doc://com.apple.appkit/documentation/AppKit/macros": {
      "abstract": [
        {
          "text": "Macros for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/appkit/macros"
    },
    "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock": {
      "abstract": [
        {
          "text": "Implement menus and cursors to facilitate interactions with your app, and use your app’s Dock tile to convey updated information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Menus, Cursors, and the Dock",
      "type": "topic",
      "url": "/documentation/appkit/menus-cursors-and-the-dock"
    },
    "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad": {
      "abstract": [
        {
          "text": "Handle events related to mouse, keyboard, and trackpad input.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mouse, Keyboard, and Trackpad",
      "type": "topic",
      "url": "/documentation/appkit/mouse-keyboard-and-trackpad"
    },
    "doc://com.apple.appkit/documentation/AppKit/printing": {
      "abstract": [
        {
          "text": "Display the system print panels and manage the printing process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/printing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Printing",
      "type": "topic",
      "url": "/documentation/appkit/printing"
    },
    "doc://com.apple.appkit/documentation/AppKit/resource-management": {
      "abstract": [
        {
          "text": "Manage the storyboards and nib files containing your app’s user interface, and learn how to load data that is stored in resource files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/resource-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resource Management",
      "type": "topic",
      "url": "/documentation/appkit/resource-management"
    },
    "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics": {
      "abstract": [
        {
          "text": "Play sounds and haptic feedback, and incorporate speech recognition and synthesis into your interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sound, Speech, and Haptics",
      "type": "topic",
      "url": "/documentation/appkit/sound-speech-and-haptics"
    },
    "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app": {
      "abstract": [
        {
          "text": "Incorporate scanned documents and pictures from a user’s iPhone, iPad, or iPod touch into your Mac app using Continuity Camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting Continuity Camera in Your Mac App",
      "type": "topic",
      "url": "/documentation/appkit/supporting-continuity-camera-in-your-mac-app"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-display": {
      "abstract": [
        {
          "text": "Display text and check spelling.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-display",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Display",
      "type": "topic",
      "url": "/documentation/appkit/text-display"
    },
    "doc://com.apple.appkit/documentation/AppKit/textkit": {
      "abstract": [
        {
          "text": "Manage text storage and perform custom layout of text-based content in your app’s views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/textkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit",
      "type": "topic",
      "url": "/documentation/appkit/textkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/touch-bar": {
      "abstract": [
        {
          "text": "Display interactive content and controls in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/touch-bar",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Touch Bar",
      "type": "topic",
      "url": "/documentation/appkit/touch-bar"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-layout": {
      "abstract": [
        {
          "text": "Position and size views using a stack view or Auto Layout constraints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-layout",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Layout",
      "type": "topic",
      "url": "/documentation/appkit/view-layout"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-management": {
      "abstract": [
        {
          "text": "Manage your user interface, including the size and position of views in a window.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Management",
      "type": "topic",
      "url": "/documentation/appkit/view-management"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens": {
      "abstract": [
        {
          "text": "Organize your view hierarchies and facilitate their display onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Windows, Panels, and Screens",
      "type": "topic",
      "url": "/documentation/appkit/windows-panels-and-screens"
    },
    "doc://com.apple.appkit/documentation/AppKit/writing-tools": {
      "abstract": [
        {
          "text": "Add support for Writing Tools to your app’s text views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/writing-tools",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Writing Tools",
      "type": "topic",
      "url": "/documentation/appkit/writing-tools"
    },
    "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-macos-apps-to-apple-silicon": {
      "abstract": [
        {
          "text": "Create a version of your macOS app that runs on both Apple silicon and Intel-based Mac computers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-macos-apps-to-apple-silicon",
      "kind": "article",
      "role": "article",
      "title": "Porting Your macOS Apps to Apple Silicon",
      "type": "topic",
      "url": "/documentation/Apple-Silicon/porting-your-macos-apps-to-apple-silicon"
    },
    "doc://com.apple.documentation/documentation/SwiftUI": {
      "abstract": [
        {
          "text": "Declare the user interface and behavior for your app on every platform.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI",
      "images": [
        {
          "identifier": "SwiftUI-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "SwiftUI",
      "type": "topic",
      "url": "/documentation/SwiftUI"
    },
    "doc://com.apple.documentation/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/UIKit"
    },
    "doc://com.apple.documentation/documentation/UIKit/mac-catalyst": {
      "abstract": [
        {
          "text": "Create a version of your iPad app that users can run on a Mac device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/mac-catalyst",
      "kind": "article",
      "role": "article",
      "title": "Mac Catalyst",
      "type": "topic",
      "url": "/documentation/UIKit/mac-catalyst"
    },
    "doc://com.apple.documentation/documentation/UIKit/protecting-the-user-s-privacy": {
      "abstract": [
        {
          "text": "Secure personal data, and respect user preferences for how data is used.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/protecting-the-user-s-privacy",
      "kind": "article",
      "role": "article",
      "title": "Protecting the User’s Privacy",
      "type": "topic",
      "url": "/documentation/UIKit/protecting-the-user-s-privacy"
    },
    "doc://com.apple.documentation/documentation/Updates/AppKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/AppKit",
      "kind": "article",
      "role": "article",
      "title": "AppKit updates",
      "type": "topic",
      "url": "/documentation/Updates/AppKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-4209947": {
      "alt": "An image of a MacBook Pro showing Calendar, Maps, and the Dock on the screen.",
      "identifier": "media-4209947",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5dd2fc2d7bcc09ecaf739c3d145f92cd/media-4209947@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c5da81508b831927287fd429b508c05c/media-4209947~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Updates/AppKit",
        "doc://com.apple.documentation/documentation/UIKit/protecting-the-user-s-privacy",
        "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-macos-apps-to-apple-silicon"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "App-Structure",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
        "doc://com.apple.appkit/documentation/AppKit/documents-data-and-pasteboard",
        "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings",
        "doc://com.apple.appkit/documentation/AppKit/resource-management",
        "doc://com.apple.appkit/documentation/AppKit/app-extensions"
      ],
      "title": "App Structure"
    },
    {
      "abstract": [
        {
          "text": "Your app’s user interface provides visual, audible, and tactile feedback to the user about what your app is doing.",
          "type": "text"
        }
      ],
      "anchor": "User-Interface",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
        "doc://com.apple.appkit/documentation/AppKit/view-management",
        "doc://com.apple.appkit/documentation/AppKit/view-layout",
        "doc://com.apple.appkit/documentation/AppKit/appearance-customization",
        "doc://com.apple.appkit/documentation/AppKit/animation",
        "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
        "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics",
        "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app"
      ],
      "title": "User Interface"
    },
    {
      "anchor": "User-Interactions",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
        "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock",
        "doc://com.apple.appkit/documentation/AppKit/gestures",
        "doc://com.apple.appkit/documentation/AppKit/touch-bar",
        "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
        "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit"
      ],
      "title": "User Interactions"
    },
    {
      "anchor": "Graphics-Drawing-Color-and-Printing",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/images-and-pdf",
        "doc://com.apple.appkit/documentation/AppKit/drawing",
        "doc://com.apple.appkit/documentation/AppKit/color",
        "doc://com.apple.appkit/documentation/AppKit/printing"
      ],
      "title": "Graphics, Drawing, Color, and Printing"
    },
    {
      "anchor": "Text",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/text-display",
        "doc://com.apple.appkit/documentation/AppKit/textkit",
        "doc://com.apple.appkit/documentation/AppKit/fonts",
        "doc://com.apple.appkit/documentation/AppKit/writing-tools"
      ],
      "title": "Text"
    },
    {
      "abstract": [
        {
          "text": "Avoid using deprecated classes and protocols in your apps.",
          "type": "text"
        }
      ],
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/enumerations",
        "doc://com.apple.appkit/documentation/AppKit/constants",
        "doc://com.apple.appkit/documentation/AppKit/data-types",
        "doc://com.apple.appkit/documentation/AppKit/macros"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextSuggestionsDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSViewContentSelectionInfo"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSuggestionItem",
        "doc://com.apple.appkit/documentation/AppKit/NSSuggestionItemResponse",
        "doc://com.apple.appkit/documentation/AppKit/NSSuggestionItemSection"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboardCommunicationError",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboardContentsNotAvailableError",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboardErrorMaximum",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboardErrorMinimum",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboardInvalidArgumentError",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboardMiscellaneousError"
      ],
      "title": "Variables"
    },
    {
      "anchor": "Macros",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/Preview(_:traits:body:)-55ljx",
        "doc://com.apple.appkit/documentation/AppKit/Preview(_:traits:body:)-7pfjp"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Updates/AppKit",
                "doc://com.apple.documentation/documentation/UIKit/protecting-the-user-s-privacy",
                "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-macos-apps-to-apple-silicon"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "App-Structure",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
                "doc://com.apple.appkit/documentation/AppKit/documents-data-and-pasteboard",
                "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings",
                "doc://com.apple.appkit/documentation/AppKit/resource-management",
                "doc://com.apple.appkit/documentation/AppKit/app-extensions"
              ],
              "title": "App Structure"
            },
            {
              "abstract": [
                {
                  "text": "Your app’s user interface provides visual, audible, and tactile feedback to the user about what your app is doing.",
                  "type": "text"
                }
              ],
              "anchor": "User-Interface",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
                "doc://com.apple.appkit/documentation/AppKit/view-management",
                "doc://com.apple.appkit/documentation/AppKit/view-layout",
                "doc://com.apple.appkit/documentation/AppKit/appearance-customization",
                "doc://com.apple.appkit/documentation/AppKit/animation",
                "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
                "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics",
                "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app"
              ],
              "title": "User Interface"
            },
            {
              "anchor": "User-Interactions",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
                "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock",
                "doc://com.apple.appkit/documentation/AppKit/gestures",
                "doc://com.apple.appkit/documentation/AppKit/touch-bar",
                "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
                "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit"
              ],
              "title": "User Interactions"
            },
            {
              "anchor": "Graphics-Drawing-Color-and-Printing",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/images-and-pdf",
                "doc://com.apple.appkit/documentation/AppKit/drawing",
                "doc://com.apple.appkit/documentation/AppKit/color",
                "doc://com.apple.appkit/documentation/AppKit/printing"
              ],
              "title": "Graphics, Drawing, Color, and Printing"
            },
            {
              "anchor": "Text",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/text-display",
                "doc://com.apple.appkit/documentation/AppKit/textkit",
                "doc://com.apple.appkit/documentation/AppKit/fonts",
                "doc://com.apple.appkit/documentation/AppKit/writing-tools"
              ],
              "title": "Text"
            },
            {
              "abstract": [
                {
                  "text": "Avoid using deprecated classes and protocols in your apps.",
                  "type": "text"
                }
              ],
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/enumerations",
                "doc://com.apple.appkit/documentation/AppKit/constants",
                "doc://com.apple.appkit/documentation/AppKit/data-types",
                "doc://com.apple.appkit/documentation/AppKit/macros"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSViewContentSelectionInfo"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplicationProtectedDataDidBecomeAvailableNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSApplicationProtectedDataWillBecomeUnavailableNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternCalendarEvent",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternEmailAddress",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternFlightNumber",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternLink",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternMoneyAmount",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternNumber",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternPhoneNumber",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternPostalAddress",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternProbableWebSearch",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternProbableWebURL",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPatternShipmentTrackingNumber",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardMetadataTypeContentType",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/Identifier/writingToolsItemIdentifier",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsExclusionAttributeName"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/IBSegueAction"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSNoUnderlineStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardCommunicationError",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardContentsNotAvailableError",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardErrorMaximum",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardErrorMinimum",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardInvalidArgumentError",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardMiscellaneousError",
                "doc://com.apple.appkit/documentation/AppKit/NSSingleUnderlineStyle"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Type-Aliases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardDetectionPattern",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboardMetadataType"
              ],
              "title": "Type Aliases"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/AccessBehavior-swift.enum"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1Identifier~1writingToolsItemIdentifier/title",
          "value": "NSToolbarWritingToolsItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1Identifier~1writingToolsItemIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarWritingToolsItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardErrorMinimum/title",
          "value": "NSPasteboardErrorMinimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardErrorMinimum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardErrorMinimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1AccessBehavior-swift.enum/title",
          "value": "NSPasteboardAccessBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1AccessBehavior-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardAccessBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1AccessBehavior-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardAccessBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardInvalidArgumentError/title",
          "value": "NSPasteboardInvalidArgumentError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardInvalidArgumentError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardInvalidArgumentError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewContentSelectionInfo/title",
          "value": "NSViewContentSelectionInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewContentSelectionInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewContentSelectionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewContentSelectionInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewContentSelectionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardMiscellaneousError/title",
          "value": "NSPasteboardMiscellaneousError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardMiscellaneousError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardMiscellaneousError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardCommunicationError/title",
          "value": "NSPasteboardCommunicationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardCommunicationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardCommunicationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardContentsNotAvailableError/title",
          "value": "NSPasteboardContentsNotAvailableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardContentsNotAvailableError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardContentsNotAvailableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardErrorMaximum/title",
          "value": "NSPasteboardErrorMaximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardErrorMaximum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardErrorMaximum"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
