{
  "abstract": [
    {
      "text": "Perform multithreaded lossless compression of directories, files, and data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.applearchive/documentation/AppleArchive"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "AppleArchive",
    "modules": [
      {
        "name": "Apple Archive"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "7.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Apple Archive"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apple Archive provides fast compression that includes file attributes, such as, ownership, permissions, flags, times, extended attributes, and error correction. Apple Archive offers these features:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Multithreaded processing that uses all cores, is energy efficient, and yields faster results",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An ability to transport files and their attributes and use Apple File System (APFS) features when they’re available, for example, filesystem compression, full clones, and sparse files",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Flexible encoding formats, so you can use archives, for example, for error correction, digests, manifests, and external data storage",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "API support for in-memory archive processing, streaming access, random access, and back-to-back archive and extraction",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.applearchive/documentation/AppleArchive": {
      "abstract": [
        {
          "text": "Perform multithreaded lossless compression of directories, files, and data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive",
      "kind": "symbol",
      "role": "collection",
      "title": "Apple Archive",
      "type": "topic",
      "url": "/documentation/applearchive"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/APPLE_ARCHIVE_API_VERSION": {
      "abstract": [
        {
          "text": "The version of the framework at compile time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "APPLE_ARCHIVE_API_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/APPLE_ARCHIVE_API_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APPLE_ARCHIVE_API_VERSION"
        }
      ],
      "role": "symbol",
      "title": "APPLE_ARCHIVE_API_VERSION",
      "type": "topic",
      "url": "/documentation/applearchive/apple_archive_api_version"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveByteStream": {
      "abstract": [
        {
          "text": "An archive stream that reads from and writes to buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArchiveByteStream"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveByteStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArchiveByteStream"
        }
      ],
      "role": "symbol",
      "title": "ArchiveByteStream",
      "type": "topic",
      "url": "/documentation/applearchive/archivebytestream"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveByteStreamProtocol": {
      "abstract": [
        {
          "text": "A set of methods that defines the interface for using an archive stream that reads from and writes to buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArchiveByteStreamProtocol"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveByteStreamProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArchiveByteStreamProtocol"
        }
      ],
      "role": "symbol",
      "title": "ArchiveByteStreamProtocol",
      "type": "topic",
      "url": "/documentation/applearchive/archivebytestreamprotocol"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveEncryptionContext": {
      "abstract": [
        {
          "text": "An object that encapsulates all parameters, keys, and data necessary to open an encrypted archive for both encryption and decryption streams.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArchiveEncryptionContext"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveEncryptionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArchiveEncryptionContext"
        }
      ],
      "role": "symbol",
      "title": "ArchiveEncryptionContext",
      "type": "topic",
      "url": "/documentation/applearchive/archiveencryptioncontext"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveError": {
      "abstract": [
        {
          "text": "Error codes for AppleArchive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArchiveError"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArchiveError"
        }
      ],
      "role": "symbol",
      "title": "ArchiveError",
      "type": "topic",
      "url": "/documentation/applearchive/archiveerror"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveHeader": {
      "abstract": [
        {
          "text": "An AppleArchive entry header.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArchiveHeader"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArchiveHeader"
        }
      ],
      "role": "symbol",
      "title": "ArchiveHeader",
      "type": "topic",
      "url": "/documentation/applearchive/archiveheader"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveStream": {
      "abstract": [
        {
          "text": "An archive stream that reads from and writes to data blobs",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArchiveStream"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArchiveStream"
        }
      ],
      "role": "symbol",
      "title": "ArchiveStream",
      "type": "topic",
      "url": "/documentation/applearchive/archivestream"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveStreamProtocol": {
      "abstract": [
        {
          "text": "A set of methods that defines the interface for using an archive stream that reads from and writes to data blobs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArchiveStreamProtocol"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveStreamProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArchiveStreamProtocol"
        }
      ],
      "role": "symbol",
      "title": "ArchiveStreamProtocol",
      "type": "topic",
      "url": "/documentation/applearchive/archivestreamprotocol"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Apple Archive data types",
      "type": "topic",
      "url": "/documentation/applearchive/apple-archive-data-types"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Apple Archive functions",
      "type": "topic",
      "url": "/documentation/applearchive/apple-archive-functions"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Apple Archive macros",
      "type": "topic",
      "url": "/documentation/applearchive/apple-archive-macros"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Apple Archive structures",
      "type": "topic",
      "url": "/documentation/applearchive/apple-archive-structures"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-single-file": {
      "abstract": [
        {
          "text": "Encrypt a single file and save the result to the file system, then decrypt and recreate the original file from the archive file using Apple Encrypted Archive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-single-file",
      "kind": "article",
      "role": "sampleCode",
      "title": "Encrypting and Decrypting a Single File",
      "type": "topic",
      "url": "/documentation/applearchive/encrypting-and-decrypting-a-single-file"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-string": {
      "abstract": [
        {
          "text": "Encrypt the contents of a string and save the result to the file system, then decrypt and recreate the string from the archive file using Apple Encrypted Archive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-string",
      "kind": "article",
      "role": "sampleCode",
      "title": "Encrypting and Decrypting a String",
      "type": "topic",
      "url": "/documentation/applearchive/encrypting-and-decrypting-a-string"
    },
    "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-directories": {
      "abstract": [
        {
          "text": "Compress and encrypt the contents of an entire directory or decompress and decrypt an archived directory  using Apple Encrypted Archive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-directories",
      "kind": "article",
      "role": "sampleCode",
      "title": "Encrypting and Decrypting Directories",
      "type": "topic",
      "url": "/documentation/applearchive/encrypting-and-decrypting-directories"
    },
    "doc://com.apple.documentation/documentation/Accelerate/compressing-and-saving-a-string-to-the-file-system": {
      "abstract": [
        {
          "text": "Compress the contents of a Unicode string and store the result on the file system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/compressing-and-saving-a-string-to-the-file-system",
      "kind": "article",
      "role": "article",
      "title": "Compressing and saving a string to the file system",
      "type": "topic",
      "url": "/documentation/Accelerate/compressing-and-saving-a-string-to-the-file-system"
    },
    "doc://com.apple.documentation/documentation/Accelerate/compressing-file-system-directories": {
      "abstract": [
        {
          "text": "Compress the contents of an entire directory and store the result on the file system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/compressing-file-system-directories",
      "kind": "article",
      "role": "article",
      "title": "Compressing file system directories",
      "type": "topic",
      "url": "/documentation/Accelerate/compressing-file-system-directories"
    },
    "doc://com.apple.documentation/documentation/Accelerate/compressing-single-files": {
      "abstract": [
        {
          "text": "Compress a single file and store the result on the file system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/compressing-single-files",
      "kind": "article",
      "role": "article",
      "title": "Compressing single files",
      "type": "topic",
      "url": "/documentation/Accelerate/compressing-single-files"
    },
    "doc://com.apple.documentation/documentation/Accelerate/decompressing-and-extracting-an-archived-directory": {
      "abstract": [
        {
          "text": "Recreate an entire file system directory from an archive file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/decompressing-and-extracting-an-archived-directory",
      "kind": "article",
      "role": "article",
      "title": "Decompressing and extracting an archived directory",
      "type": "topic",
      "url": "/documentation/Accelerate/decompressing-and-extracting-an-archived-directory"
    },
    "doc://com.apple.documentation/documentation/Accelerate/decompressing-and-parsing-an-archived-string": {
      "abstract": [
        {
          "text": "Recreate a string from an archive file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/decompressing-and-parsing-an-archived-string",
      "kind": "article",
      "role": "article",
      "title": "Decompressing and Parsing an Archived String",
      "type": "topic",
      "url": "/documentation/Accelerate/decompressing-and-parsing-an-archived-string"
    },
    "doc://com.apple.documentation/documentation/Accelerate/decompressing-single-files": {
      "abstract": [
        {
          "text": "Recreate a single file from a compressed file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/decompressing-single-files",
      "kind": "article",
      "role": "article",
      "title": "Decompressing single files",
      "type": "topic",
      "url": "/documentation/Accelerate/decompressing-single-files"
    },
    "doc://com.apple.documentation/documentation/foundation/file_system/about_apple_file_system": {
      "abstract": [
        {
          "text": "Use high-level APIs to get the most out of Apple File System.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/file_system/about_apple_file_system",
      "kind": "article",
      "role": "article",
      "title": "About Apple File System",
      "type": "topic",
      "url": "/documentation/foundation/file_system/about_apple_file_system"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/file_system/about_apple_file_system"
      ],
      "title": "Related Documentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Apple-Archive-essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Accelerate/compressing-single-files",
        "doc://com.apple.documentation/documentation/Accelerate/decompressing-single-files",
        "doc://com.apple.documentation/documentation/Accelerate/compressing-file-system-directories",
        "doc://com.apple.documentation/documentation/Accelerate/decompressing-and-extracting-an-archived-directory",
        "doc://com.apple.documentation/documentation/Accelerate/compressing-and-saving-a-string-to-the-file-system",
        "doc://com.apple.documentation/documentation/Accelerate/decompressing-and-parsing-an-archived-string"
      ],
      "title": "Apple Archive essentials"
    },
    {
      "anchor": "Apple-Encrypted-Archive-essentials",
      "identifiers": [
        "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-string",
        "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-single-file",
        "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-directories",
        "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveEncryptionContext"
      ],
      "title": "Apple Encrypted Archive essentials"
    },
    {
      "anchor": "Apple-Archive-headers",
      "identifiers": [
        "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveHeader"
      ],
      "title": "Apple Archive headers"
    },
    {
      "anchor": "Apple-Archive-streams",
      "identifiers": [
        "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveStreamProtocol",
        "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveStream",
        "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveByteStreamProtocol",
        "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveByteStream"
      ],
      "title": "Apple Archive streams"
    },
    {
      "anchor": "Apple-Archive-errors",
      "identifiers": [
        "doc://com.apple.applearchive/documentation/AppleArchive/ArchiveError"
      ],
      "title": "Apple Archive errors"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.applearchive/documentation/AppleArchive/APPLE_ARCHIVE_API_VERSION"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-structures"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Apple-Archive-essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Accelerate/compressing-single-files",
                "doc://com.apple.documentation/documentation/Accelerate/decompressing-single-files",
                "doc://com.apple.documentation/documentation/Accelerate/compressing-file-system-directories",
                "doc://com.apple.documentation/documentation/Accelerate/decompressing-and-extracting-an-archived-directory",
                "doc://com.apple.documentation/documentation/Accelerate/compressing-and-saving-a-string-to-the-file-system",
                "doc://com.apple.documentation/documentation/Accelerate/decompressing-and-parsing-an-archived-string"
              ],
              "title": "Apple Archive essentials"
            },
            {
              "anchor": "Apple-Encrypted-Archive-essentials",
              "identifiers": [
                "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-string",
                "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-a-single-file",
                "doc://com.apple.applearchive/documentation/AppleArchive/encrypting-and-decrypting-directories"
              ],
              "title": "Apple Encrypted Archive essentials"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.applearchive/documentation/AppleArchive/APPLE_ARCHIVE_API_VERSION"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-structures",
                "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-data-types",
                "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-functions",
                "doc://com.apple.applearchive/documentation/AppleArchive/apple-archive-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/foundation/file_system/about_apple_file_system"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.applearchive~1documentation~1AppleArchive~1APPLE_ARCHIVE_API_VERSION/title",
          "value": "APPLE_ARCHIVE_API_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.applearchive~1documentation~1AppleArchive~1APPLE_ARCHIVE_API_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "APPLE_ARCHIVE_API_VERSION"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/applearchive"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/applearchive"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
