{
  "abstract": [
    {
      "text": "Request user authorization to access app-related data for tracking the user or the",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "AppTrackingTransparency",
    "modules": [
      {
        "name": "App Tracking Transparency"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "App Tracking Transparency"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You must use the AppTrackingTransparency framework if your app collects data about",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "end users and shares it with other companies for purposes of tracking across apps",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and web sites. The AppTrackingTransparency framework presents an app-tracking authorization",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "request to the user and provides the tracking authorization status.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To use the AppTrackingTransparency framework:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set up a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to display a system-permission alert request for your app installed on end-user devices.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/requestTrackingAuthorization(completionHandler:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to present the app-tracking authorization request to the end user.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/trackingAuthorizationStatus",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to determine the app-tracking permission status. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "for status enums.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about app tracking and privacy, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/app-store/user-privacy-and-data-use/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/app-store/app-privacy-details/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency": {
      "abstract": [
        {
          "text": "Request user authorization to access app-related data for tracking the user or the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency",
      "kind": "symbol",
      "role": "collection",
      "title": "App Tracking Transparency",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager": {
      "abstract": [
        {
          "text": "A class that provides a tracking authorization request and the tracking",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "authorization status of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ATTrackingManager"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATTrackingManager"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus": {
      "abstract": [
        {
          "text": "The status values for app tracking authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/AuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ATTrackingManager.AuthorizationStatus",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/requestTrackingAuthorization(completionHandler:)": {
      "abstract": [
        {
          "text": "The request for user authorization to access app-related data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestTrackingAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ATTrackingManager",
          "text": "ATTrackingManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ATTrackingManagerAuthorizationStatus",
          "text": "AuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/requestTrackingAuthorization(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestTrackingAuthorizationWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestTrackingAuthorization(completionHandler:)",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/requesttrackingauthorization(completionhandler:)"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/trackingAuthorizationStatus": {
      "abstract": [
        {
          "text": "The authorization status that is current for the calling application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ATTrackingManager",
          "text": "ATTrackingManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ATTrackingManagerAuthorizationStatus",
          "text": "AuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager/trackingAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackingAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "trackingAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/attrackingmanager/trackingauthorizationstatus"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/AppTrackingTransparencyVersionNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AppTrackingTransparencyVersionNumber"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/AppTrackingTransparencyVersionNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "AppTrackingTransparencyVersionNumber",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/apptrackingtransparencyversionnumber"
    },
    "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/AppTrackingTransparencyVersionString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AppTrackingTransparencyVersionString"
        }
      ],
      "identifier": "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/AppTrackingTransparencyVersionString",
      "kind": "symbol",
      "role": "symbol",
      "title": "AppTrackingTransparencyVersionString",
      "type": "topic",
      "url": "/documentation/apptrackingtransparency/apptrackingtransparencyversionstring"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription": {
      "abstract": [
        {
          "text": "A message that informs the user why an app is requesting permission to use data for tracking the user or the device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserTrackingUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/app-store/app-privacy-details/": {
      "identifier": "https://developer.apple.com/app-store/app-privacy-details/",
      "title": "App Privacy Details",
      "titleInlineContent": [
        {
          "text": "App Privacy Details",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/app-store/app-privacy-details/"
    },
    "https://developer.apple.com/app-store/user-privacy-and-data-use/": {
      "identifier": "https://developer.apple.com/app-store/user-privacy-and-data-use/",
      "title": "User Privacy and Data Use",
      "titleInlineContent": [
        {
          "text": "User Privacy and Data Use",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/app-store/user-privacy-and-data-use/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Class-and-Components",
      "identifiers": [
        "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager"
      ],
      "title": "Class and Components"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Class-and-Components",
              "identifiers": [
                "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/ATTrackingManager"
              ],
              "title": "Class and Components"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/AppTrackingTransparencyVersionNumber",
                "doc://com.apple.App-Tracking-Transparency/documentation/AppTrackingTransparency/AppTrackingTransparencyVersionString"
              ],
              "title": "Variables"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/title",
          "value": "ATTrackingManagerAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1AuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManagerAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/title",
          "value": "ATTrackingManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ATTrackingManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1requestTrackingAuthorization(completionHandler:)/title",
          "value": "requestTrackingAuthorizationWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1requestTrackingAuthorization(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestTrackingAuthorizationWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1trackingAuthorizationStatus/title",
          "value": "trackingAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.App-Tracking-Transparency~1documentation~1AppTrackingTransparency~1ATTrackingManager~1trackingAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackingAuthorizationStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/apptrackingtransparency"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/apptrackingtransparency"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
