{
  "abstract": [
    {
      "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ARKit",
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "ARKit"
  },
  "primaryContentSections": [
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.arkit/documentation/ARKit/validating-a-model-for-motion-capture",
        "doc://com.apple.arkit/documentation/ARKit/recording-and-replaying-ar-session-data"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Augmented reality",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " (AR) describes user experiences that add 2D or 3D elements to the live view from a device’s sensors in a way that makes those elements appear to inhabit the real world. ARKit combines device motion tracking, world tracking, scene understanding, and display conveniences to simplify building an AR experience.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "arkit-hero",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "arkit-hero": {
      "alt": "An illustration showing a robot and a futuristic greenhouse.",
      "identifier": "arkit-hero",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/df5a8c154f2399688d3746e9d42fd9db/arkit-hero.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a5209042ade8072b9689305fab0840a9/arkit-hero@2x.png"
        },
        {
          "traits": [
            "1x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6fa57bb20631c58f8730299f3b74bead/arkit-hero~dark.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/11dba2960ea31e7164c941323ff77443/arkit-hero~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARAnchor": {
      "abstract": [
        {
          "text": "An object that specifies the position and orientation of an item in the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARAnchor",
      "type": "topic",
      "url": "/documentation/arkit/aranchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARKitSession": {
      "abstract": [
        {
          "text": "The main entry point for receiving data from ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARKitSession"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARKitSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARKitSession"
        }
      ],
      "role": "symbol",
      "title": "ARKitSession",
      "type": "topic",
      "url": "/documentation/arkit/arkitsession"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSession": {
      "abstract": [
        {
          "text": "The object that manages the major tasks associated with every AR experience, such as motion tracking, camera passthrough, and image analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "role": "symbol",
      "title": "ARSession",
      "type": "topic",
      "url": "/documentation/arkit/arsession"
    },
    "doc://com.apple.arkit/documentation/ARKit/Anchor": {
      "abstract": [
        {
          "text": "The identity, location, and orientation of an object in world space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Anchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/Anchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Anchor"
        }
      ],
      "role": "symbol",
      "title": "Anchor",
      "type": "topic",
      "url": "/documentation/arkit/anchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/DataProvider": {
      "abstract": [
        {
          "text": "A source of live data from ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/DataProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataProvider"
        }
      ],
      "role": "symbol",
      "title": "DataProvider",
      "type": "topic",
      "url": "/documentation/arkit/dataprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_stereo_properties_configuration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_stereo_properties_configuration"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_stereo_properties_configuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_stereo_properties_configuration"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_stereo_properties_configuration",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_stereo_properties_configuration"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_stereo_properties_provider": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_stereo_properties_provider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_stereo_properties_provider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_stereo_properties_provider"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_stereo_properties_provider",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_stereo_properties_provider"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_viewpoint_properties": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_viewpoint_properties"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_viewpoint_properties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_viewpoint_properties"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_viewpoint_properties",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_viewpoint_properties"
    },
    "doc://com.apple.arkit/documentation/ARKit/StereoPropertiesProvider": {
      "abstract": [
        {
          "text": "The StereoPropertiesProvider serves the latest viewpoint properties on the device.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StereoPropertiesProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/StereoPropertiesProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StereoPropertiesProvider"
        }
      ],
      "role": "symbol",
      "title": "StereoPropertiesProvider",
      "type": "topic",
      "url": "/documentation/arkit/stereopropertiesprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/ViewpointProperties": {
      "abstract": [
        {
          "text": "The ViewpointProperties is a record of render camera transforms at some particular time.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ViewpointProperties"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ViewpointProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ViewpointProperties"
        }
      ],
      "role": "symbol",
      "title": "ViewpointProperties",
      "type": "topic",
      "url": "/documentation/arkit/viewpointproperties"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_configuration_create": {
      "abstract": [
        {
          "text": "Create a stereo properties configuration object.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_stereo_properties_configuration_create"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_configuration_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_stereo_properties_configuration_create",
      "type": "topic",
      "url": "/documentation/arkit/ar_stereo_properties_configuration_create"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_configuration_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_stereo_properties_configuration_t"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_configuration_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_stereo_properties_configuration_t",
      "type": "topic",
      "url": "/documentation/arkit/ar_stereo_properties_configuration_t"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_create": {
      "abstract": [
        {
          "text": "Create a stereo properties provider.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_stereo_properties_provider_create"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_stereo_properties_provider_create",
      "type": "topic",
      "url": "/documentation/arkit/ar_stereo_properties_provider_create"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_get_required_authorization_type": {
      "abstract": [
        {
          "text": "Get the authorization type required by the stereo properties provider.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_stereo_properties_provider_get_required_authorization_type"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_get_required_authorization_type",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_stereo_properties_provider_get_required_authorization_type",
      "type": "topic",
      "url": "/documentation/arkit/ar_stereo_properties_provider_get_required_authorization_type"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_get_viewpoint_properties": {
      "abstract": [
        {
          "text": "Returns the latest viewpoint properties.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_stereo_properties_provider_get_viewpoint_properties"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_get_viewpoint_properties",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_stereo_properties_provider_get_viewpoint_properties",
      "type": "topic",
      "url": "/documentation/arkit/ar_stereo_properties_provider_get_viewpoint_properties"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_is_supported": {
      "abstract": [
        {
          "text": "Determines whether this device supports the stereo properties provider.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_stereo_properties_provider_is_supported"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_is_supported",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_stereo_properties_provider_is_supported",
      "type": "topic",
      "url": "/documentation/arkit/ar_stereo_properties_provider_is_supported"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_stereo_properties_provider_t"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_stereo_properties_provider_t",
      "type": "topic",
      "url": "/documentation/arkit/ar_stereo_properties_provider_t"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_create": {
      "abstract": [
        {
          "text": "Create an ",
          "type": "text"
        },
        {
          "code": "ar_viewpoint_properties_t",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_viewpoint_properties_create"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_viewpoint_properties_create",
      "type": "topic",
      "url": "/documentation/arkit/ar_viewpoint_properties_create"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_get_device_from_left_viewpoint_transform": {
      "abstract": [
        {
          "text": "Get the transformation matrix that converts from the left viewpoint to the device’s coordinate space.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_viewpoint_properties_get_device_from_left_viewpoint_transform"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_get_device_from_left_viewpoint_transform",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_viewpoint_properties_get_device_from_left_viewpoint_transform",
      "type": "topic",
      "url": "/documentation/arkit/ar_viewpoint_properties_get_device_from_left_viewpoint_transform"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_get_device_from_right_viewpoint_transform": {
      "abstract": [
        {
          "text": "Get the transformation matrix that converts from the right viewpoint to the device’s coordinate space.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_viewpoint_properties_get_device_from_right_viewpoint_transform"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_get_device_from_right_viewpoint_transform",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_viewpoint_properties_get_device_from_right_viewpoint_transform",
      "type": "topic",
      "url": "/documentation/arkit/ar_viewpoint_properties_get_device_from_right_viewpoint_transform"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_viewpoint_properties_t"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_viewpoint_properties_t",
      "type": "topic",
      "url": "/documentation/arkit/ar_viewpoint_properties_t"
    },
    "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios": {
      "abstract": [
        {
          "text": "Integrate iOS device camera and motion features to produce augmented reality experiences in your app or game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ARKit in iOS",
      "type": "topic",
      "url": "/documentation/arkit/arkit-in-ios"
    },
    "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos": {
      "abstract": [
        {
          "text": "Create immersive augmented reality experiences.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ARKit in visionOS",
      "type": "topic",
      "url": "/documentation/arkit/arkit-in-visionos"
    },
    "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos-c-api": {
      "abstract": [
        {
          "text": "Integrate ARKit with low-level libraries and functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos-c-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ARKit in visionOS C API",
      "type": "topic",
      "url": "/documentation/arkit/arkit-in-visionos-c-api"
    },
    "doc://com.apple.arkit/documentation/ARKit/recording-and-replaying-ar-session-data": {
      "abstract": [
        {
          "text": "Record an AR session in Reality Composer and replay it in your ARKit app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/recording-and-replaying-ar-session-data",
      "kind": "article",
      "role": "article",
      "title": "Recording and Replaying AR Session Data",
      "type": "topic",
      "url": "/documentation/arkit/recording-and-replaying-ar-session-data"
    },
    "doc://com.apple.arkit/documentation/ARKit/stereo_properties_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "stereo_properties_h"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/stereo_properties_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "stereo_properties_h",
      "type": "topic",
      "url": "/documentation/arkit/stereo_properties_h"
    },
    "doc://com.apple.arkit/documentation/ARKit/validating-a-model-for-motion-capture": {
      "abstract": [
        {
          "text": "Verify that your character model matches ARKit’s Motion Capture requirements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/validating-a-model-for-motion-capture",
      "kind": "article",
      "role": "article",
      "title": "Validating a Model for Motion Capture",
      "type": "topic",
      "url": "/documentation/arkit/validating-a-model-for-motion-capture"
    },
    "doc://com.apple.arkit/documentation/ARKit/verifying-device-support-and-user-permission": {
      "abstract": [
        {
          "text": "Check whether your app can use ARKit and respect user privacy at runtime.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/verifying-device-support-and-user-permission",
      "kind": "article",
      "role": "article",
      "title": "Verifying Device Support and User Permission",
      "type": "topic",
      "url": "/documentation/arkit/verifying-device-support-and-user-permission"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data": {
      "abstract": [
        {
          "text": "Check whether your app can use ARKit and respect people’s privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data",
      "kind": "article",
      "role": "article",
      "title": "Setting up access to ARKit data",
      "type": "topic",
      "url": "/documentation/visionOS/setting-up-access-to-arkit-data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "visionOS",
      "identifiers": [
        "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data",
        "doc://com.apple.arkit/documentation/ARKit/ARKitSession",
        "doc://com.apple.arkit/documentation/ARKit/DataProvider",
        "doc://com.apple.arkit/documentation/ARKit/Anchor",
        "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos",
        "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos-c-api"
      ],
      "title": "visionOS"
    },
    {
      "anchor": "iOS",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/verifying-device-support-and-user-permission",
        "doc://com.apple.arkit/documentation/ARKit/ARSession",
        "doc://com.apple.arkit/documentation/ARKit/ARAnchor",
        "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios"
      ],
      "title": "iOS"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/StereoPropertiesProvider"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_stereo_properties_configuration",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_stereo_properties_provider",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_viewpoint_properties"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ViewpointProperties"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "visionOS",
              "identifiers": [
                "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data",
                "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos",
                "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos-c-api"
              ],
              "title": "visionOS"
            },
            {
              "anchor": "iOS",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/verifying-device-support-and-user-permission",
                "doc://com.apple.arkit/documentation/ARKit/ARSession",
                "doc://com.apple.arkit/documentation/ARKit/ARAnchor",
                "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios"
              ],
              "title": "iOS"
            },
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_stereo_properties_configuration",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_stereo_properties_provider",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_viewpoint_properties"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_configuration_create",
                "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_create",
                "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_get_required_authorization_type",
                "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_get_viewpoint_properties",
                "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_is_supported",
                "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_create",
                "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_get_device_from_left_viewpoint_transform",
                "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_get_device_from_right_viewpoint_transform"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/stereo_properties_h"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Type-Aliases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_configuration_t",
                "doc://com.apple.arkit/documentation/ARKit/ar_stereo_properties_provider_t",
                "doc://com.apple.arkit/documentation/ARKit/ar_viewpoint_properties_t"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_viewpoint_properties/title",
          "value": "OS_ar_viewpoint_properties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_viewpoint_properties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_viewpoint_properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_viewpoint_properties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_viewpoint_properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_stereo_properties_configuration/title",
          "value": "OS_ar_stereo_properties_configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_stereo_properties_configuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_stereo_properties_configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_stereo_properties_configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_stereo_properties_configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_stereo_properties_provider/title",
          "value": "OS_ar_stereo_properties_provider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_stereo_properties_provider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_stereo_properties_provider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_stereo_properties_provider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_stereo_properties_provider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession/title",
          "value": "ARSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAnchor/title",
          "value": "ARAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAnchor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
