{
  "abstract": [
    {
      "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "AudioToolbox",
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Audio Toolbox"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The AudioToolbox framework provides interfaces for recording, playback, and stream parsing. In iOS, the framework provides additional interfaces for managing audio sessions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Constants",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-constants"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Data Types",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-data-types"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Enumerations",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-enumerations"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Functions",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-functions"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-macros"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AudioToolbox Structures",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox-structures"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUAudioUnit_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AUAudioUnit_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUAudioUnit_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AUAudioUnit_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_auaudiounit_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUParameters_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AUParameters_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUParameters_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AUParameters_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_auparameters_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioUnitProperties_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioToolbox_AudioUnitProperties_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioUnitProperties_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioToolbox_AudioUnitProperties_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiotoolbox_audiounitproperties_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AUComponent_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnit_AUComponent_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AUComponent_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnit_AUComponent_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounit_aucomponent_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioCodec_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnit_AudioCodec_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioCodec_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnit_AudioCodec_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounit_audiocodec_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioComponent_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioUnit_AudioComponent_h"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioComponent_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioUnit_AudioComponent_h",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounit_audiocomponent_h"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/analyzing-audio-performance-with-instruments": {
      "abstract": [
        {
          "text": "Ensure a smooth and immersive audio experience in your apps using Audio System Trace.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/analyzing-audio-performance-with-instruments",
      "kind": "article",
      "role": "article",
      "title": "Analyzing audio performance with Instruments",
      "type": "topic",
      "url": "/documentation/audiotoolbox/analyzing-audio-performance-with-instruments"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-codec": {
      "abstract": [
        {
          "text": "Translate audio data from one format to another.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-codec",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-codec"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components": {
      "abstract": [
        {
          "text": "Find, load, and configure audio components, such as Audio Units and audio codecs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Components",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-components"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services": {
      "abstract": [
        {
          "text": "Convert between linear PCM audio formats, and between linear PCM and compressed formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Converter Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-converter-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components": {
      "abstract": [
        {
          "text": "Get information about audio file formats, and about files containing audio data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Components",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-components"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services": {
      "abstract": [
        {
          "text": "Read or write a variety of audio data to or from disk or a memory buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services": {
      "abstract": [
        {
          "text": "Parse streamed audio files as the data arrives on the user’s computer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio File Stream Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-file-stream-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-format-services": {
      "abstract": [
        {
          "text": "Access information about audio formats and codecs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-format-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-format-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services": {
      "abstract": [
        {
          "text": "Connect to audio hardware and manage the recording or playback process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Queue Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-queue-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-services": {
      "abstract": [
        {
          "text": "Play short sounds or trigger a vibration effect on iOS devices with the appropriate hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support": {
      "abstract": [
        {
          "text": "Describe the properties that you associate with audio sessions and audio routes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Session Support",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-session-support"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-toolbox-debugging": {
      "abstract": [
        {
          "text": "Obtain the internal state of Core Audio objects during the development and debugging of your code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-toolbox-debugging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Toolbox Debugging",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-toolbox-debugging"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties": {
      "abstract": [
        {
          "text": "Obtain information about the built-in mixers, equalizers, filters, effects, and other Audio Unit app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Properties",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-properties"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api": {
      "abstract": [
        {
          "text": "Configure an Audio Unit and prepare it to render audio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v2 (C) API",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v2-c-api"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins": {
      "abstract": [
        {
          "text": "Deliver custom audio effects, instruments, and other audio behaviors using an Audio Unit v3 app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit v3 Plug-Ins",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-v3-plug-ins"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-voice-i-o": {
      "abstract": [
        {
          "text": "Configure system voice processing and respond to speech events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-voice-i-o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Unit Voice I/O",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audio-unit-voice-i-o"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/clock-utilities": {
      "abstract": [
        {
          "text": "Manage time-related information associated with audio playback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/clock-utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clock Utilities",
      "type": "topic",
      "url": "/documentation/audiotoolbox/clock-utilities"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format": {
      "abstract": [
        {
          "text": "Parse the structure of Core Audio files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio File Format",
      "type": "topic",
      "url": "/documentation/audiotoolbox/core-audio-file-format"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/audiotoolbox/deprecated-symbols"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services": {
      "abstract": [
        {
          "text": "Read and write compressed files and linear PCM audio files using a simplified interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended Audio File Services",
      "type": "topic",
      "url": "/documentation/audiotoolbox/extended-audio-file-services"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream": {
      "abstract": [
        {
          "text": "Convert 8-channel audio to 2-channel spatial audio by using a spatial mixer audio unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream",
      "kind": "article",
      "role": "sampleCode",
      "title": "Generating spatial audio from a multichannel audio stream",
      "type": "topic",
      "url": "/documentation/audiotoolbox/generating-spatial-audio-from-a-multichannel-audio-stream"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MultipleVoiceProcessors": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_MultipleVoiceProcessors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MultipleVoiceProcessors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitErr_MultipleVoiceProcessors"
        }
      ],
      "role": "symbol",
      "title": "kAudioUnitErr_MultipleVoiceProcessors",
      "type": "topic",
      "url": "/documentation/audiotoolbox/kaudiouniterr_multiplevoiceprocessors"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/music-player": {
      "abstract": [
        {
          "text": "Create and play a sequence of tracks, and manage aspects of playback in response to standard events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/music-player",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Player",
      "type": "topic",
      "url": "/documentation/audiotoolbox/music-player"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/workgroup-management": {
      "abstract": [
        {
          "text": "Coordinate the activity of custom real-time audio threads with those of the system and other processes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/workgroup-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workgroup Management",
      "type": "topic",
      "url": "/documentation/audiotoolbox/workgroup-management"
    },
    "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-audio-code-to-apple-silicon": {
      "abstract": [
        {
          "text": "Eliminate issues in your audio-specific code when running on Apple silicon Mac computers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-audio-code-to-apple-silicon",
      "kind": "article",
      "role": "article",
      "title": "Porting Your Audio Code to Apple Silicon",
      "type": "topic",
      "url": "/documentation/Apple-Silicon/porting-your-audio-code-to-apple-silicon"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-audio-code-to-apple-silicon"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Audio-Units",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-voice-i-o"
      ],
      "title": "Audio Units"
    },
    {
      "anchor": "Playback-and-Recording",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-services",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/music-player"
      ],
      "title": "Playback and Recording"
    },
    {
      "anchor": "Audio-Files-and-Formats",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-format-services",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format"
      ],
      "title": "Audio Files and Formats"
    },
    {
      "anchor": "Utilities",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/analyzing-audio-performance-with-instruments",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-toolbox-debugging",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/workgroup-management",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-codec",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/clock-utilities"
      ],
      "title": "Utilities"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-structures",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-constants",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-macros"
      ],
      "title": "Macros"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MultipleVoiceProcessors"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-audio-code-to-apple-silicon"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Audio-Units",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/generating-spatial-audio-from-a-multichannel-audio-stream",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v3-plug-ins",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-components",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-v2-c-api",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-properties",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-unit-voice-i-o"
              ],
              "title": "Audio Units"
            },
            {
              "anchor": "Playback-and-Recording",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-queue-services",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-services",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/music-player"
              ],
              "title": "Playback and Recording"
            },
            {
              "anchor": "Audio-Files-and-Formats",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-format-services",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-services",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/extended-audio-file-services",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-stream-services",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-file-components",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/core-audio-file-format"
              ],
              "title": "Audio Files and Formats"
            },
            {
              "anchor": "Utilities",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/analyzing-audio-performance-with-instruments",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-converter-services",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-session-support",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-toolbox-debugging",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/workgroup-management",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/audio-codec",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/clock-utilities"
              ],
              "title": "Utilities"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/deprecated-symbols"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-structures",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-enumerations",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-constants",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-functions",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-data-types"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox-macros",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUAudioUnit_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AUParameters_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioToolbox_AudioUnitProperties_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AUComponent_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioCodec_h",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnit_AudioComponent_h"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/kAudioUnitErr_MultipleVoiceProcessors"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_MultipleVoiceProcessors/title",
          "value": "kAudioUnitErr_MultipleVoiceProcessors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1kAudioUnitErr_MultipleVoiceProcessors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitErr_MultipleVoiceProcessors"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
