{
  "abstract": [
    {
      "text": "Add sophisticated audio manipulation and processing capabilities to your app.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the Audio Unit types in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/AudioToolbox",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiounit/documentation/AudioUnit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "AudioUnit",
    "modules": [
      {
        "name": "Audio Unit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Audio Unit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Audio Unit framework provides interfaces for hosting either version 2 or version 3 audio units and implementing version 3 audio processing plug-ins known as Audio Unit extensions. Developers implementing version 3 audio units should subclass the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Version 3 Audio Unit extensions can be used on iOS, tvOS, and macOS by host apps and distributed via the App Store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To learn more about App Extensions and version 3 Audio Unit extensions, see the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and the WWDC 2015 presentation ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/videos/play/wwdc2015/508/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiounit/documentation/AudioUnit": {
      "abstract": [
        {
          "text": "Add sophisticated audio manipulation and processing capabilities to your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.audiounit/documentation/AudioUnit",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Unit",
      "type": "topic",
      "url": "/documentation/audiounit"
    },
    "doc://com.apple.audiounit/documentation/AudioUnit/AUDIO_UNIT_VERSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUDIO_UNIT_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.audiounit/documentation/AudioUnit/AUDIO_UNIT_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUDIO_UNIT_VERSION"
        }
      ],
      "role": "symbol",
      "title": "AUDIO_UNIT_VERSION",
      "type": "topic",
      "url": "/documentation/audiounit/audio_unit_version"
    },
    "doc://com.apple.audiounit/documentation/AudioUnit/debugging-out-of-process-audio-units-on-apple-silicon": {
      "abstract": [
        {
          "text": "Connect to out-of-process audio units using the Xcode debugger.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiounit/documentation/AudioUnit/debugging-out-of-process-audio-units-on-apple-silicon",
      "kind": "article",
      "role": "article",
      "title": "Debugging Out-of-Process Audio Units on Apple Silicon",
      "type": "topic",
      "url": "/documentation/audiounit/debugging-out-of-process-audio-units-on-apple-silicon"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/AudioToolbox"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit": {
      "abstract": [
        {
          "text": "A class that defines a host’s interface to an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUAudioUnit",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214",
      "title": "App Extension Programming Guide",
      "titleInlineContent": [
        {
          "text": "App Extension Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214"
    },
    "https://developer.apple.com/videos/play/wwdc2015/508/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2015/508/",
      "title": "Audio Unit Extensions",
      "titleInlineContent": [
        {
          "text": "Audio Unit Extensions",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2015/508/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.audiounit/documentation/AudioUnit/debugging-out-of-process-audio-units-on-apple-silicon"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiounit/documentation/AudioUnit/AUDIO_UNIT_VERSION"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.audiounit/documentation/AudioUnit/debugging-out-of-process-audio-units-on-apple-silicon"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiounit/documentation/AudioUnit/AUDIO_UNIT_VERSION"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use the Audio Unit types in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AudioToolbox",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiounit~1documentation~1AudioUnit~1AUDIO_UNIT_VERSION/title",
          "value": "AUDIO_UNIT_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiounit~1documentation~1AudioUnit~1AUDIO_UNIT_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUDIO_UNIT_VERSION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUAudioUnit"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiounit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiounit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
