{
  "abstract": [
    {
      "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "Automator",
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.4",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Automator"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Automator framework supports the development of actions for the Automator app, as well as the ability to run a workflow in developer apps. An ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "action",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is a bundle that, when loaded and run, performs a specific task, such as copying a file or cropping an image. Using Automator, users can construct and execute ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "workflows",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " consisting of a sequence of actions. Developers can also load and execute workflows in their apps. As a workflow executes, the output of one action is typically passed as the input to the next action. Automator loads action bundles from standard locations in the file system: ",
              "type": "text"
            },
            {
              "code": "/System/Library/Automator",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "/Library/Automator",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "~/Library/Automator",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface and general characteristics of Automator actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMAction"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMAction"
        }
      ],
      "role": "symbol",
      "title": "AMAction",
      "type": "topic",
      "url": "/documentation/automator/amaction"
    },
    "doc://com.apple.automator/documentation/Automator/AMActionErrorKey": {
      "abstract": [
        {
          "text": "A key to retrieve the action that caused an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMActionErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMActionErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionErrorKey"
        }
      ],
      "role": "symbol",
      "title": "AMActionErrorKey",
      "type": "topic",
      "url": "/documentation/automator/amactionerrorkey"
    },
    "doc://com.apple.automator/documentation/Automator/AMAppleScriptAction": {
      "abstract": [
        {
          "text": "An object that represents Automator actions whose runtime behavior is driven by an AppleScript script.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMAppleScriptAction"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAppleScriptAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMAppleScriptAction"
        }
      ],
      "role": "symbol",
      "title": "AMAppleScriptAction",
      "type": "topic",
      "url": "/documentation/automator/amapplescriptaction"
    },
    "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the Automator error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMAutomatorErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMAutomatorErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "AMAutomatorErrorDomain",
      "type": "topic",
      "url": "/documentation/automator/amautomatorerrordomain"
    },
    "doc://com.apple.automator/documentation/Automator/AMBundleAction": {
      "abstract": [
        {
          "text": "An object that represents an Automator action that’s a loadable bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMBundleAction"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMBundleAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMBundleAction"
        }
      ],
      "role": "symbol",
      "title": "AMBundleAction",
      "type": "topic",
      "url": "/documentation/automator/ambundleaction"
    },
    "doc://com.apple.automator/documentation/Automator/AMError": {
      "abstract": [
        {
          "text": "An Automator error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "role": "symbol",
      "title": "AMError",
      "type": "topic",
      "url": "/documentation/automator/amerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code": {
      "abstract": [
        {
          "text": "Automator error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code",
      "type": "topic",
      "url": "/documentation/automator/amerror/code"
    },
    "doc://com.apple.automator/documentation/Automator/AMShellScriptAction": {
      "abstract": [
        {
          "text": "An object that represents Automator actions whose runtime behavior is driven by a shell script or by a Perl or Python script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMShellScriptAction"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMShellScriptAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMShellScriptAction"
        }
      ],
      "role": "symbol",
      "title": "AMShellScriptAction",
      "type": "topic",
      "url": "/documentation/automator/amshellscriptaction"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow": {
      "abstract": [
        {
          "text": "An object that lets you use an Automator workflow in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflow"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflow"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflow",
      "type": "topic",
      "url": "/documentation/automator/amworkflow"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowController": {
      "abstract": [
        {
          "text": "An object that lets you manage an Automator workflow in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflowController"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowController"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflowController",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontroller"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowView": {
      "abstract": [
        {
          "text": "An object that lets you view and edit Automator workflows in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflowView"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowView"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflowView",
      "type": "topic",
      "url": "/documentation/automator/amworkflowview"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkspace": {
      "abstract": [
        {
          "text": "A workspace for running an Automator workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkspace"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkspace"
        }
      ],
      "role": "symbol",
      "title": "AMWorkspace",
      "type": "topic",
      "url": "/documentation/automator/amworkspace"
    },
    "doc://com.apple.automator/documentation/Automator/AM_RETURNS_NONRETAINED_FOR_ANALYZER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AM_RETURNS_NONRETAINED_FOR_ANALYZER"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AM_RETURNS_NONRETAINED_FOR_ANALYZER",
      "kind": "symbol",
      "role": "symbol",
      "title": "AM_RETURNS_NONRETAINED_FOR_ANALYZER",
      "type": "topic",
      "url": "/documentation/automator/am_returns_nonretained_for_analyzer"
    },
    "doc://com.apple.automator/documentation/Automator/AM_RETURNS_RETAINED_FOR_ANALYZER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AM_RETURNS_RETAINED_FOR_ANALYZER"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AM_RETURNS_RETAINED_FOR_ANALYZER",
      "kind": "symbol",
      "role": "symbol",
      "title": "AM_RETURNS_RETAINED_FOR_ANALYZER",
      "type": "topic",
      "url": "/documentation/automator/am_returns_retained_for_analyzer"
    },
    "doc://com.apple.automator/documentation/Automator/AM_UNUSED_FOR_ANALYZER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AM_UNUSED_FOR_ANALYZER"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AM_UNUSED_FOR_ANALYZER",
      "kind": "symbol",
      "role": "symbol",
      "title": "AM_UNUSED_FOR_ANALYZER",
      "type": "topic",
      "url": "/documentation/automator/am_unused_for_analyzer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Actions",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMBundleAction",
        "doc://com.apple.automator/documentation/Automator/AMShellScriptAction",
        "doc://com.apple.automator/documentation/Automator/AMAction"
      ],
      "title": "Actions"
    },
    {
      "anchor": "Workflows",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflow",
        "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
        "doc://com.apple.automator/documentation/Automator/AMWorkflowView",
        "doc://com.apple.automator/documentation/Automator/AMWorkspace"
      ],
      "title": "Workflows"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain",
        "doc://com.apple.automator/documentation/Automator/AMActionErrorKey",
        "doc://com.apple.automator/documentation/Automator/AMError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMAppleScriptAction"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Actions",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMBundleAction",
                "doc://com.apple.automator/documentation/Automator/AMShellScriptAction",
                "doc://com.apple.automator/documentation/Automator/AMAction"
              ],
              "title": "Actions"
            },
            {
              "anchor": "Workflows",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflow",
                "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
                "doc://com.apple.automator/documentation/Automator/AMWorkflowView",
                "doc://com.apple.automator/documentation/Automator/AMWorkspace"
              ],
              "title": "Workflows"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain",
                "doc://com.apple.automator/documentation/Automator/AMActionErrorKey",
                "doc://com.apple.automator/documentation/Automator/AMError/Code"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMAppleScriptAction"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AM_RETURNS_NONRETAINED_FOR_ANALYZER",
                "doc://com.apple.automator/documentation/Automator/AM_RETURNS_RETAINED_FOR_ANALYZER",
                "doc://com.apple.automator/documentation/Automator/AM_UNUSED_FOR_ANALYZER"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowView/title",
          "value": "AMWorkflowView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAutomatorErrorDomain/title",
          "value": "AMAutomatorErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAutomatorErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMAutomatorErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMShellScriptAction/title",
          "value": "AMShellScriptAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMShellScriptAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMShellScriptAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMShellScriptAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMShellScriptAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkspace/title",
          "value": "AMWorkspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkspace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAppleScriptAction/title",
          "value": "AMAppleScriptAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAppleScriptAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMAppleScriptAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAppleScriptAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMAppleScriptAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMBundleAction/title",
          "value": "AMBundleAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMBundleAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMBundleAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMBundleAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMBundleAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction/title",
          "value": "AMAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/title",
          "value": "AMWorkflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/title",
          "value": "AMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMActionErrorKey/title",
          "value": "AMActionErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMActionErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/title",
          "value": "AMWorkflowController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/automator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
