{
  "abstract": [
    {
      "text": "Play, record, and process audio; configure your app’s system audio behavior.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 1"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "AVFAudio",
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.5",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.5",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.5",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.3",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "14.5",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "AVFAudio"
  },
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication": {
      "abstract": [
        {
          "text": "An object that manages one or more audio sessions that belong to an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioApplication"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioApplication"
        }
      ],
      "role": "symbol",
      "title": "AVAudioApplication",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverterInputBlock": {
      "abstract": [
        {
          "text": "A block to get input data for conversion, as necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioConverterInputBlock"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverterInputBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioConverterInputBlock"
        }
      ],
      "role": "symbol",
      "title": "AVAudioConverterInputBlock",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioconverterinputblock"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayer": {
      "abstract": [
        {
          "text": "An object that plays audio data from a file or buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioPlayer"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioPlayer"
        }
      ],
      "role": "symbol",
      "title": "AVAudioPlayer",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioplayer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder": {
      "abstract": [
        {
          "text": "An object that records audio data to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioRecorder"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioRecorder"
        }
      ],
      "role": "symbol",
      "title": "AVAudioRecorder",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorder"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRoutingArbiter": {
      "abstract": [
        {
          "text": "An object for configuring macOS apps to participate in AirPods Automatic Switching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioRoutingArbiter"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRoutingArbiter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioRoutingArbiter"
        }
      ],
      "role": "symbol",
      "title": "AVAudioRoutingArbiter",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioroutingarbiter"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionAnchoringStrategy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionAnchoringStrategy"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionAnchoringStrategy",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionAnchoringStrategy",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessionanchoringstrategy"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSetActiveFlags_NotifyOthersOnDeactivation": {
      "abstract": [
        {
          "text": "A flag that indicates that when your audio session deactivates, any audio sessions that your audio session interrupted can reactivate themselves.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSessionSetActiveFlags_NotifyOthersOnDeactivation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSetActiveFlags_NotifyOthersOnDeactivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionSetActiveFlags_NotifyOthersOnDeactivation"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSessionSetActiveFlags_NotifyOthersOnDeactivation",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessionsetactiveflags_notifyothersondeactivation"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperience": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperience",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessionspatialexperience"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOption": {
      "abstract": [
        {
          "text": "A type definition for a spatial experience option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperienceOption"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionSpatialExperienceOption",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessionspatialexperienceoption"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionAnchoringStrategy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperienceOptionAnchoringStrategy"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionAnchoringStrategy",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionSpatialExperienceOptionAnchoringStrategy",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessionspatialexperienceoptionanchoringstrategy"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSceneIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperienceOptionSceneIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSceneIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionSpatialExperienceOptionSceneIdentifier",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessionspatialexperienceoptionsceneidentifier"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSoundStageSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperienceOptionSoundStageSize"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSoundStageSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionSpatialExperienceOptionSoundStageSize",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessionspatialexperienceoptionsoundstagesize"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIPlayer": {
      "abstract": [
        {
          "text": "An object that plays MIDI data through a system sound module.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMIDIPlayer"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIPlayer"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIPlayer",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidiplayer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIPlayerCompletionHandler": {
      "abstract": [
        {
          "text": "A callback the system invokes when MIDI playback completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMIDIPlayerCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIPlayerCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIPlayerCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIPlayerCompletionHandler",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidiplayercompletionhandler"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_Mastering": {
      "abstract": [
        {
          "text": "The mastering encoder bit rate strategy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleRateConverterAlgorithm_Mastering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_Mastering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleRateConverterAlgorithm_Mastering"
        }
      ],
      "role": "symbol",
      "title": "AVSampleRateConverterAlgorithm_Mastering",
      "type": "topic",
      "url": "/documentation/avfaudio/avsamplerateconverteralgorithm_mastering"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_MinimumPhase": {
      "abstract": [
        {
          "text": "The minimum phase encoder bit rate strategy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleRateConverterAlgorithm_MinimumPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_MinimumPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleRateConverterAlgorithm_MinimumPhase"
        }
      ],
      "role": "symbol",
      "title": "AVSampleRateConverterAlgorithm_MinimumPhase",
      "type": "topic",
      "url": "/documentation/avfaudio/avsamplerateconverteralgorithm_minimumphase"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_Normal": {
      "abstract": [
        {
          "text": "The usual encoder bit rate strategy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleRateConverterAlgorithm_Normal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_Normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleRateConverterAlgorithm_Normal"
        }
      ],
      "role": "symbol",
      "title": "AVSampleRateConverterAlgorithm_Normal",
      "type": "topic",
      "url": "/documentation/avfaudio/avsamplerateconverteralgorithm_normal"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/Adding-synthesized-speech-to-calls": {
      "abstract": [
        {
          "text": "Provide a more accessible experience by adding your app’s audio to a call.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/Adding-synthesized-speech-to-calls",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adding synthesized speech to calls",
      "type": "topic",
      "url": "/documentation/avfaudio/adding-synthesized-speech-to-calls"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine": {
      "abstract": [
        {
          "text": "Perform advanced real-time and offline audio processing, implement 3D spatialization, and work with MIDI and samplers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Engine",
      "type": "topic",
      "url": "/documentation/avfaudio/audio-engine"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/capturing-stereo-audio-from-built-in-microphones": {
      "abstract": [
        {
          "text": "Configure an iOS device’s built-in microphones to add stereo recording capabilities to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/capturing-stereo-audio-from-built-in-microphones",
      "kind": "article",
      "role": "sampleCode",
      "title": "Capturing stereo audio from built-In microphones",
      "type": "topic",
      "url": "/documentation/avfaudio/capturing-stereo-audio-from-built-in-microphones"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions": {
      "abstract": [
        {
          "text": "Observe audio session notifications to ensure that your app responds appropriately to interruptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions",
      "kind": "article",
      "role": "article",
      "title": "Handling audio interruptions",
      "type": "topic",
      "url": "/documentation/avfaudio/handling-audio-interruptions"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/macros": {
      "abstract": [],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/avfaudio/macros"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/responding-to-audio-route-changes": {
      "abstract": [
        {
          "text": "Observe audio session notifications to ensure that your app responds appropriately to route changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/responding-to-audio-route-changes",
      "kind": "article",
      "role": "article",
      "title": "Responding to audio route changes",
      "type": "topic",
      "url": "/documentation/avfaudio/responding-to-audio-route-changes"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/speech-synthesis": {
      "abstract": [
        {
          "text": "Configure voices to speak strings of text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/speech-synthesis",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Speech synthesis",
      "type": "topic",
      "url": "/documentation/avfaudio/speech-synthesis"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "System-audio",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions",
        "doc://com.apple.avfaudio/documentation/AVFAudio/responding-to-audio-route-changes",
        "doc://com.apple.avfaudio/documentation/AVFAudio/Adding-synthesized-speech-to-calls",
        "doc://com.apple.avfaudio/documentation/AVFAudio/capturing-stereo-audio-from-built-in-microphones",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRoutingArbiter"
      ],
      "title": "System audio"
    },
    {
      "anchor": "Basic-playback-and-recording",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayer",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIPlayer"
      ],
      "title": "Basic playback and recording"
    },
    {
      "anchor": "Advanced-audio-processing",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine"
      ],
      "title": "Advanced audio processing"
    },
    {
      "anchor": "Speech-synthesis",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/speech-synthesis"
      ],
      "title": "Speech synthesis"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/macros"
      ],
      "title": "Macros"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSetActiveFlags_NotifyOthersOnDeactivation",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_Mastering",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_MinimumPhase",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_Normal"
      ],
      "title": "Variables"
    },
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverterInputBlock",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIPlayerCompletionHandler"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "System-audio",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions",
                "doc://com.apple.avfaudio/documentation/AVFAudio/responding-to-audio-route-changes",
                "doc://com.apple.avfaudio/documentation/AVFAudio/Adding-synthesized-speech-to-calls",
                "doc://com.apple.avfaudio/documentation/AVFAudio/capturing-stereo-audio-from-built-in-microphones",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRoutingArbiter"
              ],
              "title": "System audio"
            },
            {
              "anchor": "Basic-playback-and-recording",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayer",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIPlayer"
              ],
              "title": "Basic playback and recording"
            },
            {
              "anchor": "Advanced-audio-processing",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine"
              ],
              "title": "Advanced audio processing"
            },
            {
              "anchor": "Speech-synthesis",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/speech-synthesis"
              ],
              "title": "Speech synthesis"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/macros"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionAnchoringStrategy",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSceneIdentifier",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSoundStageSize",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_Mastering",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_MinimumPhase",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSampleRateConverterAlgorithm_Normal"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSetActiveFlags_NotifyOthersOnDeactivation"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Type-Aliases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverterInputBlock",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOption",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIPlayerCompletionHandler"
              ],
              "title": "Type Aliases"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionAnchoringStrategy",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperience"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIPlayerCompletionHandler/title",
          "value": "AVMIDIPlayerCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIPlayerCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIPlayerCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIPlayerCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIPlayerCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSampleRateConverterAlgorithm_Mastering/title",
          "value": "AVSampleRateConverterAlgorithm_Mastering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSampleRateConverterAlgorithm_Mastering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleRateConverterAlgorithm_Mastering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionSetActiveFlags_NotifyOthersOnDeactivation/title",
          "value": "AVAudioSessionSetActiveFlags_NotifyOthersOnDeactivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionSetActiveFlags_NotifyOthersOnDeactivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionSetActiveFlags_NotifyOthersOnDeactivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverterInputBlock/title",
          "value": "AVAudioConverterInputBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverterInputBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioConverterInputBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverterInputBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioConverterInputBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSampleRateConverterAlgorithm_Normal/title",
          "value": "AVSampleRateConverterAlgorithm_Normal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSampleRateConverterAlgorithm_Normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleRateConverterAlgorithm_Normal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayer/title",
          "value": "AVAudioPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication/title",
          "value": "AVAudioApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRoutingArbiter/title",
          "value": "AVAudioRoutingArbiter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRoutingArbiter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRoutingArbiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRoutingArbiter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRoutingArbiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSampleRateConverterAlgorithm_MinimumPhase/title",
          "value": "AVSampleRateConverterAlgorithm_MinimumPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSampleRateConverterAlgorithm_MinimumPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleRateConverterAlgorithm_MinimumPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorder/title",
          "value": "AVAudioRecorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIPlayer/title",
          "value": "AVMIDIPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIPlayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
