{
  "abstract": [
    {
      "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 1"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 1"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "AVFoundation",
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.2",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.7",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "AVFoundation"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "AVFoundation combines several major technology areas that together encompass a wide range of tasks for inspecting, playing, capturing, and processing audiovisual media on Apple platforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetChapterMetadataGroupsDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAssetChapterMetadataGroupsDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetChapterMetadataGroupsDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetChapterMetadataGroupsDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetchaptermetadatagroupsdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetContainsFragmentsDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when an asset’s fragments change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAssetContainsFragmentsDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetContainsFragmentsDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetContainsFragmentsDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetcontainsfragmentsdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDurationDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when a fragmented asset minder observes a change to a fragmented asset’s duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAssetDurationDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDurationDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetDurationDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetdurationdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetMediaSelectionGroupsDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAssetMediaSelectionGroupsDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetMediaSelectionGroupsDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetMediaSelectionGroupsDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetmediaselectiongroupsdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackSegmentsDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAssetTrackSegmentsDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackSegmentsDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetTrackSegmentsDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettracksegmentsdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackTimeRangeDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAssetTrackTimeRangeDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackTimeRangeDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetTrackTimeRangeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettracktimerangedidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackTrackAssociationsDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAssetTrackTrackAssociationsDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackTrackAssociationsDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetTrackTrackAssociationsDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettracktrackassociationsdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWasDefragmentedNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when a fragmented asset minder observes that the system defragments the asset on disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAssetWasDefragmentedNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWasDefragmentedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetWasDefragmentedNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetwasdefragmentednotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that defines the errors that framework operations can generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVError"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVError"
        }
      ],
      "role": "symbol",
      "title": "AVError",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code": {
      "abstract": [
        {
          "text": "An enumeration that defines the errors that framework operations can generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFoundation-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFoundation-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/avfoundation/avfoundation-macros"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFoundationErrorDomain": {
      "abstract": [
        {
          "text": "The error domain of AVFoundation errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFoundationErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFoundationErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFoundationErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "AVFoundationErrorDomain",
      "type": "topic",
      "url": "/documentation/avfoundation/avfoundationerrordomain"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieContainsMovieFragmentsDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVFragmentedMovieContainsMovieFragmentsDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieContainsMovieFragmentsDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVFragmentedMovieContainsMovieFragmentsDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedmoviecontainsmoviefragmentsdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieDurationDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVFragmentedMovieDurationDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieDurationDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVFragmentedMovieDurationDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedmoviedurationdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrackSegmentsDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVFragmentedMovieTrackSegmentsDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrackSegmentsDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVFragmentedMovieTrackSegmentsDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedmovietracksegmentsdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrackTimeRangeDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVFragmentedMovieTrackTimeRangeDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrackTimeRangeDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVFragmentedMovieTrackTimeRangeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedmovietracktimerangedidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrackTotalSampleDataLengthDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVFragmentedMovieTrackTotalSampleDataLengthDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrackTotalSampleDataLengthDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVFragmentedMovieTrackTotalSampleDataLengthDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedmovietracktotalsampledatalengthdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieWasDefragmentedNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVFragmentedMovieWasDefragmentedNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieWasDefragmentedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVFragmentedMovieWasDefragmentedNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedmoviewasdefragmentednotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType/auxiliaryPicture": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auxiliaryPicture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaType",
          "text": "AVMediaType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType/auxiliaryPicture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaTypeAuxiliaryPicture"
        }
      ],
      "role": "symbol",
      "title": "auxiliaryPicture",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediatype/auxiliarypicture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAvailableHDRModesDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVPlayerAvailableHDRModesDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAvailableHDRModesDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayerAvailableHDRModesDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeravailablehdrmodesdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAudioRendererOutputConfigurationDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferAudioRendererOutputConfigurationDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAudioRendererOutputConfigurationDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVSampleBufferAudioRendererOutputConfigurationDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferaudiorendereroutputconfigurationdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAudioRendererWasFlushedAutomaticallyNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferAudioRendererWasFlushedAutomaticallyNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAudioRendererWasFlushedAutomaticallyNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVSampleBufferAudioRendererWasFlushedAutomaticallyNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferaudiorendererwasflushedautomaticallynotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayerOutputObscuredDueToInsufficientExternalProtectionDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferDisplayLayerOutputObscuredDueToInsufficientExternalProtectionDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayerOutputObscuredDueToInsufficientExternalProtectionDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVSampleBufferDisplayLayerOutputObscuredDueToInsufficientExternalProtectionDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayeroutputobscuredduetoinsufficientexternalprotectiondidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayerReadyForDisplayDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferDisplayLayerReadyForDisplayDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayerReadyForDisplayDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVSampleBufferDisplayLayerReadyForDisplayDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayerreadyfordisplaydidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayerRequiresFlushToResumeDecodingDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when a sample buffer display layer changes its decoding requirements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferDisplayLayerRequiresFlushToResumeDecodingDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayerRequiresFlushToResumeDecodingDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVSampleBufferDisplayLayerRequiresFlushToResumeDecodingDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayerrequiresflushtoresumedecodingdidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/additional-data-capture": {
      "abstract": [
        {
          "text": "Capture additional data including depth and metadata, and synchronize capture from multiple outputs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/additional-data-capture",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Additional data capture",
      "type": "topic",
      "url": "/documentation/avfoundation/additional-data-capture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/audio-and-video-capture": {
      "abstract": [
        {
          "text": "Capture audio and video directly to media files, or capture streams of media for direct access to media sample buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-and-video-capture",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio and video capture",
      "type": "topic",
      "url": "/documentation/avfoundation/audio-and-video-capture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/audio-mixing": {
      "abstract": [
        {
          "text": "Define how to mix the audio levels from multiple audio tracks over an asset’s duration.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-mixing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio mixing",
      "type": "topic",
      "url": "/documentation/avfoundation/audio-mixing"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/audio-playback-recording-and-processing": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-playback-recording-and-processing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio playback, recording, and processing",
      "type": "topic",
      "url": "/documentation/avfoundation/audio-playback-recording-and-processing"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings": {
      "abstract": [
        {
          "text": "Configure audio processing settings using standard key and value constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio settings",
      "type": "topic",
      "url": "/documentation/avfoundation/audio-settings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup": {
      "abstract": [
        {
          "text": "Configure built-in cameras and microphones, and external capture devices, for media capture.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Capture setup",
      "type": "topic",
      "url": "/documentation/avfoundation/capture-setup"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets": {
      "abstract": [
        {
          "text": "Combine tracks and segments of tracks from multiple assets into a composite asset that you can play or process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Composite assets",
      "type": "topic",
      "url": "/documentation/avfoundation/composite-assets"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets": {
      "abstract": [
        {
          "text": "Load media assets from files and streams to inspect their attributes, tracks, and embedded metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media assets",
      "type": "topic",
      "url": "/documentation/avfoundation/media-assets"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback": {
      "abstract": [
        {
          "text": "Manage the playback of media assets and interstitial content, independent of how you present that content in your interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media playback",
      "type": "topic",
      "url": "/documentation/avfoundation/media-playback"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing": {
      "abstract": [
        {
          "text": "Read images from video, export to alternative formats, and perform sample-level reading and writing of media data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media reading and writing",
      "type": "topic",
      "url": "/documentation/avfoundation/media-reading-and-writing"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities": {
      "abstract": [
        {
          "text": "Identify the types of content and file formats that AVFoundation supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media types and utilities",
      "type": "topic",
      "url": "/documentation/avfoundation/media-types-and-utilities"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/offline-playback-and-storage": {
      "abstract": [
        {
          "text": "Download streamed content to disk to allow offline playback, and define policies to automatically remove downloaded assets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/offline-playback-and-storage",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Offline playback and storage",
      "type": "topic",
      "url": "/documentation/avfoundation/offline-playback-and-storage"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture": {
      "abstract": [
        {
          "text": "Capture high-quality still images, Live Photos, and supporting photo data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Photo capture",
      "type": "topic",
      "url": "/documentation/avfoundation/photo-capture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies": {
      "abstract": [
        {
          "text": "Access the contents of a QuickTime movie file, and perform sample-level edits of its media tracks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QuickTime movies",
      "type": "topic",
      "url": "/documentation/avfoundation/quicktime-movies"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback": {
      "abstract": [
        {
          "text": "Create custom controllers to play and synchronize the timing of sample buffer streams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sample buffer playback",
      "type": "topic",
      "url": "/documentation/avfoundation/sample-buffer-playback"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/speech-synthesis": {
      "abstract": [
        {
          "text": "Configure voices to speak strings of text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/speech-synthesis",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Speech synthesis",
      "type": "topic",
      "url": "/documentation/avfoundation/speech-synthesis"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay": {
      "abstract": [
        {
          "text": "Stream content wirelessly to other devices using AirPlay, and handle requests involving FairPlay-protected assets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Streaming and AirPlay",
      "type": "topic",
      "url": "/documentation/avfoundation/streaming-and-airplay"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects": {
      "abstract": [
        {
          "text": "Define standard video transition effects, synchronize layer animations with media timing, and create custom video compositors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Video effects",
      "type": "topic",
      "url": "/documentation/avfoundation/video-effects"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings": {
      "abstract": [
        {
          "text": "Configure video processing settings using standard key and value constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Video settings",
      "type": "topic",
      "url": "/documentation/avfoundation/video-settings"
    },
    "doc://com.apple.documentation/documentation/Updates/AVFoundation": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFoundation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/AVFoundation",
      "kind": "article",
      "role": "article",
      "title": "AVFoundation updates",
      "type": "topic",
      "url": "/documentation/Updates/AVFoundation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Updates/AVFoundation"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Common",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
        "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings",
        "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings"
      ],
      "title": "Common"
    },
    {
      "anchor": "Playback",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
        "doc://com.apple.avfoundation/documentation/AVFoundation/offline-playback-and-storage",
        "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay",
        "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback"
      ],
      "title": "Playback"
    },
    {
      "anchor": "Capture",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup",
        "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture",
        "doc://com.apple.avfoundation/documentation/AVFoundation/audio-and-video-capture",
        "doc://com.apple.avfoundation/documentation/AVFoundation/additional-data-capture"
      ],
      "title": "Capture"
    },
    {
      "anchor": "Editing",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets",
        "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies",
        "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects",
        "doc://com.apple.avfoundation/documentation/AVFoundation/audio-mixing"
      ],
      "title": "Editing"
    },
    {
      "anchor": "Audio",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/audio-playback-recording-and-processing",
        "doc://com.apple.avfoundation/documentation/AVFoundation/speech-synthesis"
      ],
      "title": "Audio"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFoundationErrorDomain",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFoundation-macros"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Updates/AVFoundation"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Common",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
                "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings",
                "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings"
              ],
              "title": "Common"
            },
            {
              "anchor": "Playback",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
                "doc://com.apple.avfoundation/documentation/AVFoundation/offline-playback-and-storage",
                "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay",
                "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback"
              ],
              "title": "Playback"
            },
            {
              "anchor": "Capture",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup",
                "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture",
                "doc://com.apple.avfoundation/documentation/AVFoundation/audio-and-video-capture",
                "doc://com.apple.avfoundation/documentation/AVFoundation/additional-data-capture"
              ],
              "title": "Capture"
            },
            {
              "anchor": "Editing",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets",
                "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies",
                "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects",
                "doc://com.apple.avfoundation/documentation/AVFoundation/audio-mixing"
              ],
              "title": "Editing"
            },
            {
              "anchor": "Audio",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/audio-playback-recording-and-processing",
                "doc://com.apple.avfoundation/documentation/AVFoundation/speech-synthesis"
              ],
              "title": "Audio"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFoundationErrorDomain",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFoundation-macros"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetChapterMetadataGroupsDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetContainsFragmentsDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDurationDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetMediaSelectionGroupsDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackSegmentsDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackTimeRangeDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackTrackAssociationsDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWasDefragmentedNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieContainsMovieFragmentsDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieDurationDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrackSegmentsDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrackTimeRangeDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrackTotalSampleDataLengthDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieWasDefragmentedNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType/auxiliaryPicture",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAvailableHDRModesDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAudioRendererOutputConfigurationDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAudioRendererWasFlushedAutomaticallyNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayerOutputObscuredDueToInsufficientExternalProtectionDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayerReadyForDisplayDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayerRequiresFlushToResumeDecodingDidChangeNotification"
              ],
              "title": "Variables"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/title",
          "value": "AVError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaType~1auxiliaryPicture/title",
          "value": "AVMediaTypeAuxiliaryPicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaType~1auxiliaryPicture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaTypeAuxiliaryPicture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFoundationErrorDomain/title",
          "value": "AVFoundationErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFoundationErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFoundationErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
