{
  "abstract": [
    {
      "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "AVKit",
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.9",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "AVKit"
  },
  "primaryContentSections": [
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-for-video-calls"
      ]
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection": {
      "abstract": [
        {
          "text": "Constants that indicate the audio route selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteSelection"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionRouteSelection",
      "type": "topic",
      "url": "/documentation/avkit/avaudiosessionrouteselection"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVCaptureEvent": {
      "abstract": [
        {
          "text": "An object that describes a user interaction with a system hardware button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureEvent"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVCaptureEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureEvent"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureEvent",
      "type": "topic",
      "url": "/documentation/avkit/avcaptureevent"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVCaptureEventInteraction": {
      "abstract": [
        {
          "text": "An object that registers handlers to respond to capture events from system hardware buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureEventInteraction"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVCaptureEventInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureEventInteraction"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureEventInteraction",
      "type": "topic",
      "url": "/documentation/avkit/avcaptureeventinteraction"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVCaptureView": {
      "abstract": [
        {
          "text": "A view that displays standard user interface controls for capturing media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureView"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVCaptureView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureView"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureView",
      "type": "topic",
      "url": "/documentation/avkit/avcaptureview"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController": {
      "abstract": [
        {
          "text": "A view controller that proposes content to watch next.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentProposalViewController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentProposalViewController"
        }
      ],
      "role": "symbol",
      "title": "AVContentProposalViewController",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposalviewcontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController": {
      "abstract": [
        {
          "text": "A view controller that provides an interface to a person so they can select and connect a continuity device to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewController"
        }
      ],
      "role": "symbol",
      "title": "AVContinuityDevicePickerViewController",
      "type": "topic",
      "url": "/documentation/avkit/avcontinuitydevicepickerviewcontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate": {
      "abstract": [
        {
          "text": "An interface that responds to events from a continuity device picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVContinuityDevicePickerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager": {
      "abstract": [
        {
          "text": "A tvOS management object that controls whether a TV switches modes to match the video’s native mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDisplayManager"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVDisplayManager"
        }
      ],
      "role": "symbol",
      "title": "AVDisplayManager",
      "type": "topic",
      "url": "/documentation/avkit/avdisplaymanager"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController": {
      "abstract": [
        {
          "text": "An object that controls video experiences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVExperienceController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVExperienceController"
        }
      ],
      "role": "symbol",
      "title": "AVExperienceController",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVGroupExperienceCoordinator": {
      "abstract": [
        {
          "text": "An object that synchronizes viewing environment state across participants in a SharePlay session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVGroupExperienceCoordinator"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVGroupExperienceCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVGroupExperienceCoordinator"
        }
      ],
      "role": "symbol",
      "title": "AVGroupExperienceCoordinator",
      "type": "topic",
      "url": "/documentation/avkit/avgroupexperiencecoordinator"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange": {
      "abstract": [
        {
          "text": "A time range in an audiovisual presentation for content with an interstitial designation, such as advertisements or legal notices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVInterstitialTimeRange"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVInterstitialTimeRange"
        }
      ],
      "role": "symbol",
      "title": "AVInterstitialTimeRange",
      "type": "topic",
      "url": "/documentation/avkit/avinterstitialtimerange"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKit-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKit-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/avkit/avkit-macros"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitError"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitError"
        }
      ],
      "role": "symbol",
      "title": "AVKitError",
      "type": "topic",
      "url": "/documentation/avkit/avkiterror-swift.struct"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Constants that identify framework error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AVKitError.Code",
      "type": "topic",
      "url": "/documentation/avkit/avkiterror-swift.struct/code"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitErrorDomain": {
      "abstract": [
        {
          "text": "The domain of errors the framework generates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "AVKitErrorDomain",
      "type": "topic",
      "url": "/documentation/avkit/avkiterrordomain"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVMultiviewManager": {
      "abstract": [
        {
          "text": "An object that manages viewing multiple videos at once.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMultiviewManager"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVMultiviewManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMultiviewManager"
        }
      ],
      "role": "symbol",
      "title": "AVMultiviewManager",
      "type": "topic",
      "url": "/documentation/avkit/avmultiviewmanager"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup": {
      "abstract": [
        {
          "text": "A set of markers for navigating playback of an audiovisual presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVNavigationMarkersGroup"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVNavigationMarkersGroup"
        }
      ],
      "role": "symbol",
      "title": "AVNavigationMarkersGroup",
      "type": "topic",
      "url": "/documentation/avkit/avnavigationmarkersgroup"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController": {
      "abstract": [
        {
          "text": "A controller that responds to user-initiated Picture in Picture playback of video in a floating, resizable window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPictureInPictureController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPictureInPictureController"
        }
      ],
      "role": "symbol",
      "title": "AVPictureInPictureController",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerView": {
      "abstract": [
        {
          "text": "A view that displays content from a player and presents a native user interface to control playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerView"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerView"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerView",
      "type": "topic",
      "url": "/documentation/avkit/avplayerview"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController": {
      "abstract": [
        {
          "text": "A view controller that displays content from a player and presents a native user interface to control playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerViewController",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to implement to respond to player view controller events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontrollerdelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView": {
      "abstract": [
        {
          "text": "A view that presents a list of nearby media receivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVRoutePickerView"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerView"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview"
    },
    "doc://com.apple.avkit/documentation/AVKit/VideoPlayer": {
      "abstract": [
        {
          "text": "A view that displays content from a player and a native user interface to control playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VideoPlayer"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/VideoPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VideoPlayer"
        }
      ],
      "role": "symbol",
      "title": "VideoPlayer",
      "type": "topic",
      "url": "/documentation/avkit/videoplayer"
    },
    "doc://com.apple.avkit/documentation/AVKit/accessing-the-camera-while-multitasking-on-ipad": {
      "abstract": [
        {
          "text": "Operate the camera in Split View, Slide Over, Picture in Picture, and Stage Manager modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/accessing-the-camera-while-multitasking-on-ipad",
      "kind": "article",
      "role": "article",
      "title": "Accessing the camera while multitasking on iPad",
      "type": "topic",
      "url": "/documentation/avkit/accessing-the-camera-while-multitasking-on-ipad"
    },
    "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-for-video-calls": {
      "abstract": [
        {
          "text": "Add multitasking capability to your video-call apps by using Picture in Picture (PiP).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-for-video-calls",
      "kind": "article",
      "role": "article",
      "title": "Adopting Picture in Picture for video calls",
      "type": "topic",
      "url": "/documentation/avkit/adopting-picture-in-picture-for-video-calls"
    },
    "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-custom-player": {
      "abstract": [
        {
          "text": "Add controls to your custom player user interface to invoke Picture in Picture (PiP) playback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-custom-player",
      "kind": "article",
      "role": "article",
      "title": "Adopting Picture in Picture in a Custom Player",
      "type": "topic",
      "url": "/documentation/avkit/adopting-picture-in-picture-in-a-custom-player"
    },
    "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-standard-player": {
      "abstract": [
        {
          "text": "Add Picture in Picture (PiP) playback to your app using a player view controller.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-standard-player",
      "kind": "article",
      "role": "article",
      "title": "Adopting Picture in Picture in a Standard Player",
      "type": "topic",
      "url": "/documentation/avkit/adopting-picture-in-picture-in-a-standard-player"
    },
    "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-playback-in-tvos": {
      "abstract": [
        {
          "text": "Add advanced multitasking capabilities to your video apps by using Picture in Picture playback in tvOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-playback-in-tvos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adopting Picture in Picture Playback in tvOS",
      "type": "topic",
      "url": "/documentation/avkit/adopting-picture-in-picture-playback-in-tvos"
    },
    "doc://com.apple.avkit/documentation/AVKit/adopting-the-system-player-interface-in-visionos": {
      "abstract": [
        {
          "text": "Provide an optimized viewing experience for watching 3D video content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/adopting-the-system-player-interface-in-visionos",
      "kind": "article",
      "role": "article",
      "title": "Adopting the system player interface in visionOS",
      "type": "topic",
      "url": "/documentation/avkit/adopting-the-system-player-interface-in-visionos"
    },
    "doc://com.apple.avkit/documentation/AVKit/avkit-metadata-identifiers": {
      "abstract": [
        {
          "text": "Additional metadata that an asset contains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/avkit-metadata-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AVKit Metadata Identifiers",
      "type": "topic",
      "url": "/documentation/avkit/avkit-metadata-identifiers"
    },
    "doc://com.apple.avkit/documentation/AVKit/creating-a-multiview-video-playback-experience-in-visionos": {
      "abstract": [
        {
          "text": "Build an interface that plays multiple videos simultaneously and handles transitions to different experience types gracefully.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/creating-a-multiview-video-playback-experience-in-visionos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a multiview video playback experience in visionOS",
      "type": "topic",
      "url": "/documentation/avkit/creating-a-multiview-video-playback-experience-in-visionos"
    },
    "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience": {
      "abstract": [
        {
          "text": "Adopt the latest features of the redesigned tvOS player user interface to provide a more streamlined way to watch your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience",
      "kind": "article",
      "role": "article",
      "title": "Customizing the tvOS Playback Experience",
      "type": "topic",
      "url": "/documentation/avkit/customizing-the-tvos-playback-experience"
    },
    "doc://com.apple.avkit/documentation/AVKit/implementing-trimming-in-a-macos-player": {
      "abstract": [
        {
          "text": "Provide a QuickTime media-trimming experience in your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/implementing-trimming-in-a-macos-player",
      "kind": "article",
      "role": "article",
      "title": "Implementing Trimming in a macOS Player",
      "type": "topic",
      "url": "/documentation/avkit/implementing-trimming-in-a-macos-player"
    },
    "doc://com.apple.avkit/documentation/AVKit/playing-video-content-in-a-standard-user-interface": {
      "abstract": [
        {
          "text": "Play media full screen, embedded inline, or in a floating Picture in Picture (PiP) window using a player view controller.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/playing-video-content-in-a-standard-user-interface",
      "kind": "article",
      "role": "sampleCode",
      "title": "Playing video content in a standard user interface",
      "type": "topic",
      "url": "/documentation/avkit/playing-video-content-in-a-standard-user-interface"
    },
    "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos": {
      "abstract": [
        {
          "text": "Display a preview of an upcoming media item at the conclusion of the currently playing media item.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos",
      "kind": "article",
      "role": "article",
      "title": "Presenting Content Proposals in tvOS",
      "type": "topic",
      "url": "/documentation/avkit/presenting-content-proposals-in-tvos"
    },
    "doc://com.apple.avkit/documentation/AVKit/presenting-navigation-markers": {
      "abstract": [
        {
          "text": "Present navigation markers in the Chapters panel to help users quickly navigate your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/presenting-navigation-markers",
      "kind": "article",
      "role": "article",
      "title": "Presenting Navigation Markers",
      "type": "topic",
      "url": "/documentation/avkit/presenting-navigation-markers"
    },
    "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app": {
      "abstract": [
        {
          "text": "Capture high-quality photos, video, and audio in your Apple TV app by connecting",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "an iPhone or iPad as a continuity device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting Continuity Camera in your tvOS app",
      "type": "topic",
      "url": "/documentation/avkit/supporting-continuity-camera-in-your-tvos-app"
    },
    "doc://com.apple.avkit/documentation/AVKit/trimming-and-exporting-media-in-visionos": {
      "abstract": [
        {
          "text": "Display standard controls in your app to edit the timeline of the currently playing media.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/trimming-and-exporting-media-in-visionos",
      "kind": "article",
      "role": "article",
      "title": "Trimming and exporting media in visionOS",
      "type": "topic",
      "url": "/documentation/avkit/trimming-and-exporting-media-in-visionos"
    },
    "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content": {
      "abstract": [
        {
          "text": "Present additional content alongside your main media presentation using HTTP Live Streaming support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content",
      "kind": "article",
      "role": "article",
      "title": "Working with Interstitial Content",
      "type": "topic",
      "url": "/documentation/avkit/working-with-interstitial-content"
    },
    "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos": {
      "abstract": [
        {
          "text": "Add interactive overlays, parental controls, and livestream channel flipping using a player view controller.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Working with Overlays and Parental Controls in tvOS",
      "type": "topic",
      "url": "/documentation/avkit/working-with-overlays-and-parental-controls-in-tvos"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "iOS-Playback-and-Capture",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/playing-video-content-in-a-standard-user-interface",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
        "doc://com.apple.avkit/documentation/AVKit/AVCaptureEventInteraction",
        "doc://com.apple.avkit/documentation/AVKit/AVCaptureEvent"
      ],
      "title": "iOS Playback and Capture"
    },
    {
      "anchor": "tvOS-Playback-and-Capture",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience",
        "doc://com.apple.avkit/documentation/AVKit/presenting-navigation-markers",
        "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content",
        "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos",
        "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos",
        "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
        "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange",
        "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController",
        "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager",
        "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController",
        "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate"
      ],
      "title": "tvOS Playback and Capture"
    },
    {
      "anchor": "visionOS-Playback",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/creating-a-multiview-video-playback-experience-in-visionos",
        "doc://com.apple.avkit/documentation/AVKit/adopting-the-system-player-interface-in-visionos",
        "doc://com.apple.avkit/documentation/AVKit/trimming-and-exporting-media-in-visionos",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController",
        "doc://com.apple.avkit/documentation/AVKit/AVMultiviewManager",
        "doc://com.apple.avkit/documentation/AVKit/AVGroupExperienceCoordinator"
      ],
      "title": "visionOS Playback"
    },
    {
      "anchor": "macOS-Playback-and-Capture",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/implementing-trimming-in-a-macos-player",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerView",
        "doc://com.apple.avkit/documentation/AVKit/AVCaptureView"
      ],
      "title": "macOS Playback and Capture"
    },
    {
      "anchor": "Multiplatform-Playback-and-Capture",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/VideoPlayer"
      ],
      "title": "Multiplatform Playback and Capture"
    },
    {
      "anchor": "Picture-in-Picture",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-playback-in-tvos",
        "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-standard-player",
        "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-custom-player",
        "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-for-video-calls",
        "doc://com.apple.avkit/documentation/AVKit/accessing-the-camera-while-multitasking-on-ipad",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController"
      ],
      "title": "Picture in Picture"
    },
    {
      "anchor": "Playback-Route-Selection",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView"
      ],
      "title": "Playback Route Selection"
    },
    {
      "anchor": "Metadata",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/avkit-metadata-identifiers"
      ],
      "title": "Metadata"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVKitErrorDomain",
        "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct",
        "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/Code"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVKit-macros"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "iOS-Playback-and-Capture",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/playing-video-content-in-a-standard-user-interface",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
                "doc://com.apple.avkit/documentation/AVKit/AVCaptureEventInteraction",
                "doc://com.apple.avkit/documentation/AVKit/AVCaptureEvent"
              ],
              "title": "iOS Playback and Capture"
            },
            {
              "anchor": "tvOS-Playback-and-Capture",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience",
                "doc://com.apple.avkit/documentation/AVKit/presenting-navigation-markers",
                "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content",
                "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos",
                "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos",
                "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
                "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange",
                "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController",
                "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager",
                "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController",
                "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate"
              ],
              "title": "tvOS Playback and Capture"
            },
            {
              "anchor": "visionOS-Playback",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/creating-a-multiview-video-playback-experience-in-visionos",
                "doc://com.apple.avkit/documentation/AVKit/adopting-the-system-player-interface-in-visionos",
                "doc://com.apple.avkit/documentation/AVKit/trimming-and-exporting-media-in-visionos",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate"
              ],
              "title": "visionOS Playback"
            },
            {
              "anchor": "macOS-Playback-and-Capture",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/implementing-trimming-in-a-macos-player",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerView",
                "doc://com.apple.avkit/documentation/AVKit/AVCaptureView"
              ],
              "title": "macOS Playback and Capture"
            },
            {
              "anchor": "Picture-in-Picture",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-playback-in-tvos",
                "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-standard-player",
                "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-custom-player",
                "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-for-video-calls",
                "doc://com.apple.avkit/documentation/AVKit/accessing-the-camera-while-multitasking-on-ipad",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController"
              ],
              "title": "Picture in Picture"
            },
            {
              "anchor": "Playback-Route-Selection",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView",
                "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection"
              ],
              "title": "Playback Route Selection"
            },
            {
              "anchor": "Metadata",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/avkit-metadata-identifiers"
              ],
              "title": "Metadata"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVKitErrorDomain",
                "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/Code"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection"
              ],
              "title": "Enumerations"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVKit-macros"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVCaptureView/title",
          "value": "AVCaptureView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVCaptureView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVCaptureView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/title",
          "value": "AVContinuityDevicePickerViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/title",
          "value": "AVRoutePickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVCaptureEventInteraction/title",
          "value": "AVCaptureEventInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVCaptureEventInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureEventInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVCaptureEventInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureEventInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController/title",
          "value": "AVPictureInPictureController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVNavigationMarkersGroup/title",
          "value": "AVNavigationMarkersGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVNavigationMarkersGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVNavigationMarkersGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVNavigationMarkersGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVNavigationMarkersGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVInterstitialTimeRange/title",
          "value": "AVInterstitialTimeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVInterstitialTimeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVInterstitialTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVInterstitialTimeRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVInterstitialTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/title",
          "value": "AVPlayerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitError-swift.struct~1Code/title",
          "value": "AVKitError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVCaptureEvent/title",
          "value": "AVCaptureEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVCaptureEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVCaptureEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController/title",
          "value": "AVContentProposalViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposalViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposalViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVDisplayManager/title",
          "value": "AVDisplayManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVDisplayManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDisplayManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVDisplayManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDisplayManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/title",
          "value": "AVPlayerViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitErrorDomain/title",
          "value": "AVKitErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/title",
          "value": "AVContinuityDevicePickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerView/title",
          "value": "AVPlayerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
