{
  "abstract": [
    {
      "text": "Request the system to launch your app in the background to run tasks.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "BackgroundTasks",
    "modules": [
      {
        "name": "Background Tasks"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Background Tasks"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the BackgroundTasks framework to keep your app content up to date and run tasks requiring minutes to complete while your app is in the background. Longer tasks can optionally require external power and network connectivity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Register launch handlers for tasks when the app launches and schedule them as required. The system launches your app in the background and executes the tasks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks": {
      "abstract": [
        {
          "text": "Request the system to launch your app in the background to run tasks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks",
      "kind": "symbol",
      "role": "collection",
      "title": "Background Tasks",
      "type": "topic",
      "url": "/documentation/backgroundtasks"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGAppRefreshTask": {
      "abstract": [
        {
          "text": "An object representing a short task typically used to refresh content that’s run while the app is in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BGAppRefreshTask"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGAppRefreshTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGAppRefreshTask"
        }
      ],
      "role": "symbol",
      "title": "BGAppRefreshTask",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgapprefreshtask"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGAppRefreshTaskRequest": {
      "abstract": [
        {
          "text": "A request to launch your app in the background to execute a short refresh task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BGAppRefreshTaskRequest"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGAppRefreshTaskRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGAppRefreshTaskRequest"
        }
      ],
      "role": "symbol",
      "title": "BGAppRefreshTaskRequest",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgapprefreshtaskrequest"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGHealthResearchTask": {
      "abstract": [
        {
          "text": "A time-consuming, necessary processing task that runs while the app is in the background to prepare data essential to a health research study.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BGHealthResearchTask"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGHealthResearchTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGHealthResearchTask"
        }
      ],
      "role": "symbol",
      "title": "BGHealthResearchTask",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bghealthresearchtask"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGHealthResearchTaskRequest": {
      "abstract": [
        {
          "text": "A request to launch your app in the background to execute processing for a health research study in which a user participates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BGHealthResearchTaskRequest"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGHealthResearchTaskRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGHealthResearchTaskRequest"
        }
      ],
      "role": "symbol",
      "title": "BGHealthResearchTaskRequest",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bghealthresearchtaskrequest"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGProcessingTask": {
      "abstract": [
        {
          "text": "A time-consuming processing task that runs while the app is in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BGProcessingTask"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGProcessingTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGProcessingTask"
        }
      ],
      "role": "symbol",
      "title": "BGProcessingTask",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgprocessingtask"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGProcessingTaskRequest": {
      "abstract": [
        {
          "text": "A request to launch your app in the background to execute a processing task that can take minutes to complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BGProcessingTaskRequest"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGProcessingTaskRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGProcessingTaskRequest"
        }
      ],
      "role": "symbol",
      "title": "BGProcessingTaskRequest",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgprocessingtaskrequest"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTask": {
      "abstract": [
        {
          "text": "An abstract class representing a task that’s run while the app is in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BGTask"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGTask"
        }
      ],
      "role": "symbol",
      "title": "BGTask",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgtask"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskRequest": {
      "abstract": [
        {
          "text": "An abstract class for representing task requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BGTaskRequest"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGTaskRequest"
        }
      ],
      "role": "symbol",
      "title": "BGTaskRequest",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgtaskrequest"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler": {
      "abstract": [
        {
          "text": "A class for scheduling task requests that launch your app in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BGTaskScheduler"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGTaskScheduler"
        }
      ],
      "role": "symbol",
      "title": "BGTaskScheduler",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgtaskscheduler"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BG_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BG_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BG_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "BG_EXTERN",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bg_extern"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/choosing-background-strategies-for-your-app": {
      "abstract": [
        {
          "text": "Select the best method of scheduling background runtime for your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/choosing-background-strategies-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Choosing Background Strategies for Your App",
      "type": "topic",
      "url": "/documentation/backgroundtasks/choosing-background-strategies-for-your-app"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/refreshing-and-maintaining-your-app-using-background-tasks": {
      "abstract": [
        {
          "text": "Use scheduled background tasks for refreshing your app content and for performing maintenance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/refreshing-and-maintaining-your-app-using-background-tasks",
      "kind": "article",
      "role": "sampleCode",
      "title": "Refreshing and Maintaining Your App Using Background Tasks",
      "type": "topic",
      "url": "/documentation/backgroundtasks/refreshing-and-maintaining-your-app-using-background-tasks"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/starting-and-terminating-tasks-during-development": {
      "abstract": [
        {
          "text": "Use the debugger during development to start tasks and to terminate them before completion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/starting-and-terminating-tasks-during-development",
      "kind": "article",
      "role": "article",
      "title": "Starting and Terminating Tasks During Development",
      "type": "topic",
      "url": "/documentation/backgroundtasks/starting-and-terminating-tasks-during-development"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/starting-and-terminating-tasks-during-development",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/refreshing-and-maintaining-your-app-using-background-tasks",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/choosing-background-strategies-for-your-app"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Requests",
      "identifiers": [
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGProcessingTaskRequest",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGAppRefreshTaskRequest",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskRequest",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGHealthResearchTaskRequest"
      ],
      "title": "Requests"
    },
    {
      "anchor": "Task-management",
      "identifiers": [
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGProcessingTask",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGAppRefreshTask",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTask",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGHealthResearchTask"
      ],
      "title": "Task management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler",
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/starting-and-terminating-tasks-during-development",
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/refreshing-and-maintaining-your-app-using-background-tasks",
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/choosing-background-strategies-for-your-app"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Requests",
              "identifiers": [
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGProcessingTaskRequest",
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGAppRefreshTaskRequest",
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskRequest",
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGHealthResearchTaskRequest"
              ],
              "title": "Requests"
            },
            {
              "anchor": "Task-management",
              "identifiers": [
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGProcessingTask",
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGAppRefreshTask",
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTask",
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGHealthResearchTask"
              ],
              "title": "Task management"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BG_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGProcessingTaskRequest/title",
          "value": "BGProcessingTaskRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGProcessingTaskRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BGProcessingTaskRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGProcessingTaskRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGProcessingTaskRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGHealthResearchTask/title",
          "value": "BGHealthResearchTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGHealthResearchTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BGHealthResearchTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGHealthResearchTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGHealthResearchTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGAppRefreshTask/title",
          "value": "BGAppRefreshTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGAppRefreshTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BGAppRefreshTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGAppRefreshTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGAppRefreshTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskRequest/title",
          "value": "BGTaskRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTaskRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTaskRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGProcessingTask/title",
          "value": "BGProcessingTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGProcessingTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BGProcessingTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGProcessingTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGProcessingTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGHealthResearchTaskRequest/title",
          "value": "BGHealthResearchTaskRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGHealthResearchTaskRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BGHealthResearchTaskRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGHealthResearchTaskRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGHealthResearchTaskRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskScheduler/title",
          "value": "BGTaskScheduler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskScheduler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTaskScheduler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskScheduler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTaskScheduler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTask/title",
          "value": "BGTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGAppRefreshTaskRequest/title",
          "value": "BGAppRefreshTaskRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGAppRefreshTaskRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BGAppRefreshTaskRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGAppRefreshTaskRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGAppRefreshTaskRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/backgroundtasks"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/backgroundtasks"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
