{
  "abstract": [
    {
      "text": "Integrate an alternative browser engine into your web browser app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "BrowserEngineCore",
    "modules": [
      {
        "name": "BrowserEngineCore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "17.4",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "18.0",
        "name": "iPadOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "BrowserEngineCore"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "code": "BrowserEngineCore",
              "type": "codeVoice"
            },
            {
              "text": " framework to support low-level functions for your alternative browser engine that renders its UI using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BrowserEngineKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For more information on developing web browser apps, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BrowserEngineKit/designing-your-browser-architecture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore": {
      "abstract": [
        {
          "text": "Integrate an alternative browser engine into your web browser app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineCore",
      "type": "topic",
      "url": "/documentation/browserenginecore"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG": {
      "abstract": [
        {
          "text": "A discriminator value the system uses to generate pointer authentication codes for just-in-time compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BE_JIT_WRITE_PROTECT_TAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BE_JIT_WRITE_PROTECT_TAG"
        }
      ],
      "role": "symbol",
      "title": "BE_JIT_WRITE_PROTECT_TAG",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_jit_write_protect_tag"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS": {
      "abstract": [
        {
          "text": "Indicates that no flags are set in a request to receive kernel events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BE_KEVENT_NO_FLAGS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BE_KEVENT_NO_FLAGS"
        }
      ],
      "role": "symbol",
      "title": "BE_KEVENT_NO_FLAGS",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent_no_flags"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY": {
      "abstract": [
        {
          "text": "Indicates that a request to receive kernel events needs to return without waiting for events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BE_KEVENT_RETURN_IMMEDIATELY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BE_KEVENT_RETURN_IMMEDIATELY"
        }
      ],
      "role": "symbol",
      "title": "BE_KEVENT_RETURN_IMMEDIATELY",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent_return_immediately"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_ACCESSIBILITY_AVAILABILITY": {
      "abstract": [
        {
          "text": "A macro the framework uses to indicate which SDK versions provide the accessibility APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BROWSERENGINE_ACCESSIBILITY_AVAILABILITY"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_ACCESSIBILITY_AVAILABILITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "BROWSERENGINE_ACCESSIBILITY_AVAILABILITY",
      "type": "topic",
      "url": "/documentation/browserenginecore/browserengine_accessibility_availability"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_ACCESSIBILITY_MARKER_AVAILABILITY": {
      "abstract": [
        {
          "text": "A macro the framework uses to indicate which SDK versions provide the accessibility marker APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BROWSERENGINE_ACCESSIBILITY_MARKER_AVAILABILITY"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_ACCESSIBILITY_MARKER_AVAILABILITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "BROWSERENGINE_ACCESSIBILITY_MARKER_AVAILABILITY",
      "type": "topic",
      "url": "/documentation/browserenginecore/browserengine_accessibility_marker_availability"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_EXPORT": {
      "abstract": [
        {
          "text": "A macro the framework uses to make API available for use in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BROWSERENGINE_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "BROWSERENGINE_EXPORT",
      "type": "topic",
      "url": "/documentation/browserenginecore/browserengine_export"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_EXTERN": {
      "abstract": [
        {
          "text": "A macro the framework uses to indicate that a symbol is defined in a different file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BROWSERENGINE_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "BROWSERENGINE_EXTERN",
      "type": "topic",
      "url": "/documentation/browserenginecore/browserengine_extern"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_FINAL": {
      "abstract": [
        {
          "text": "A macro the framework uses to indicate that an Objective-C class isn’t available for subclassing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BROWSERENGINE_FINAL"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_FINAL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BROWSERENGINE_FINAL",
      "type": "topic",
      "url": "/documentation/browserenginecore/browserengine_final"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_IMPORT": {
      "abstract": [
        {
          "text": "A macro the framework uses to import APIs from other frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BROWSERENGINE_IMPORT"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_IMPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "BROWSERENGINE_IMPORT",
      "type": "topic",
      "url": "/documentation/browserenginecore/browserengine_import"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_TEXTINPUT_AVAILABILITY": {
      "abstract": [
        {
          "text": "A macro the framework uses to indicate which SDK versions provide the text input APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BROWSERENGINE_TEXTINPUT_AVAILABILITY"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_TEXTINPUT_AVAILABILITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "BROWSERENGINE_TEXTINPUT_AVAILABILITY",
      "type": "topic",
      "url": "/documentation/browserenginecore/browserengine_textinput_availability"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers for kernel events on the specified queue, and returns events that are pending on the queue, using 32-bit data types.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "be_kevent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent",
          "text": "kevent"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent",
          "text": "kevent"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "be_kevent"
        }
      ],
      "role": "symbol",
      "title": "be_kevent(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent(_:_:_:_:_:_:)"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers for kernel events on the specified queue, and returns events that are pending on the queue, using 64-bit data types.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "be_kevent64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent64_s",
          "text": "kevent64_s"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent64_s",
          "text": "kevent64_s"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "be_kevent64"
        }
      ],
      "role": "symbol",
      "title": "be_kevent64(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent64(_:_:_:_:_:_:)"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness": {
      "abstract": [
        {
          "text": "Makes a region of memory writable for use in just-in-time (JIT) compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "be_memory_inline_jit_restrict_rwx_to_rw_with_witness"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness",
      "kind": "symbol",
      "role": "symbol",
      "title": "be_memory_inline_jit_restrict_rwx_to_rw_with_witness",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness_impl": {
      "abstract": [
        {
          "text": "Makes a region of memory writable for use in just-in-time (JIT) compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "be_memory_inline_jit_restrict_rwx_to_rw_with_witness_impl"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness_impl",
      "kind": "symbol",
      "role": "symbol",
      "title": "be_memory_inline_jit_restrict_rwx_to_rw_with_witness_impl",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness_impl"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness": {
      "abstract": [
        {
          "text": "Makes a region of memory executable for use in just-in-time (JIT) compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "be_memory_inline_jit_restrict_rwx_to_rx_with_witness"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness",
      "kind": "symbol",
      "role": "symbol",
      "title": "be_memory_inline_jit_restrict_rwx_to_rx_with_witness",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness_impl": {
      "abstract": [
        {
          "text": "Makes a region of memory executable for use in just-in-time (JIT) compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "be_memory_inline_jit_restrict_rwx_to_rx_with_witness_impl"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness_impl",
      "kind": "symbol",
      "role": "symbol",
      "title": "be_memory_inline_jit_restrict_rwx_to_rx_with_witness_impl",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness_impl"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_with_witness_supported": {
      "abstract": [
        {
          "text": "Reports whether write protection for just-in-time (JIT) compilation is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "be_memory_inline_jit_restrict_with_witness_supported"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_with_witness_supported",
      "kind": "symbol",
      "role": "symbol",
      "title": "be_memory_inline_jit_restrict_with_witness_supported",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_memory_inline_jit_restrict_with_witness_supported"
    },
    "doc://com.apple.documentation/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/BrowserEngineKit"
    },
    "doc://com.apple.documentation/documentation/BrowserEngineKit/designing-your-browser-architecture": {
      "abstract": [
        {
          "text": "Isolate privileged access to operating system resources and private data from untrusted code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BrowserEngineKit/designing-your-browser-architecture",
      "kind": "article",
      "role": "article",
      "title": "Designing your browser architecture",
      "type": "topic",
      "url": "/documentation/BrowserEngineKit/designing-your-browser-architecture"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Kernel-events",
      "identifiers": [
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)",
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)",
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS",
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY"
      ],
      "title": "Kernel events"
    },
    {
      "anchor": "JIT-compilation",
      "identifiers": [
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG"
      ],
      "title": "JIT compilation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Kernel-events",
              "identifiers": [
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY"
              ],
              "title": "Kernel events"
            },
            {
              "anchor": "JIT-compilation",
              "identifiers": [
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_with_witness_supported",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG"
              ],
              "title": "JIT compilation"
            },
            {
              "anchor": "Memory-protection-implementation",
              "identifiers": [
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness_impl",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness_impl"
              ],
              "title": "Memory-protection implementation"
            },
            {
              "anchor": "API-availability",
              "identifiers": [
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_ACCESSIBILITY_AVAILABILITY",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_ACCESSIBILITY_MARKER_AVAILABILITY",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_TEXTINPUT_AVAILABILITY",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_EXPORT",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_EXTERN",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_FINAL",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BROWSERENGINE_IMPORT"
              ],
              "title": "API availability"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent(_:_:_:_:_:_:)/title",
          "value": "be_kevent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "be_kevent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_JIT_WRITE_PROTECT_TAG/title",
          "value": "BE_JIT_WRITE_PROTECT_TAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_JIT_WRITE_PROTECT_TAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BE_JIT_WRITE_PROTECT_TAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent64(_:_:_:_:_:_:)/title",
          "value": "be_kevent64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent64(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "be_kevent64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_NO_FLAGS/title",
          "value": "BE_KEVENT_NO_FLAGS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_NO_FLAGS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BE_KEVENT_NO_FLAGS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_RETURN_IMMEDIATELY/title",
          "value": "BE_KEVENT_RETURN_IMMEDIATELY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_RETURN_IMMEDIATELY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BE_KEVENT_RETURN_IMMEDIATELY"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginecore"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginecore"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
