{
  "abstract": [
    {
      "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cinematic/documentation/Cinematic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "Cinematic",
    "modules": [
      {
        "name": "Cinematic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "tvOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Cinematic"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Cinematic framework enables you to add professional-level editing and playback features to movies, recorded with the Camera app’s Cinematic mode, to your apps. These are the same features used in applications such as Final Cut Pro, Photos, and iMovie. For example, this enables your apps to change focus distance and aperture in movies, creating a bokeh effect, even after recording.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cinematic/documentation/Cinematic": {
      "abstract": [
        {
          "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic",
      "kind": "symbol",
      "role": "collection",
      "title": "Cinematic",
      "type": "topic",
      "url": "/documentation/cinematic"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNAssetInfo-2ata2": {
      "abstract": [
        {
          "text": "An object that provides Cinematic-specific information about an asset, including its tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNAssetInfo"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNAssetInfo-2ata2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNAssetInfo"
        }
      ],
      "role": "symbol",
      "title": "CNAssetInfo",
      "type": "topic",
      "url": "/documentation/cinematic/cnassetinfo-2ata2"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNAssetInfo-8ja4t": {
      "abstract": [
        {
          "text": "An object that provides Cinematic-specific information about an asset, including its tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNAssetInfo"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNAssetInfo-8ja4t",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNAssetInfo",
      "type": "topic",
      "url": "/documentation/cinematic/cnassetinfo-8ja4t"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNBoundsPrediction-c.class": {
      "abstract": [
        {
          "text": "An object representing the bounds of the predicted subject.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNBoundsPrediction"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNBoundsPrediction-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNBoundsPrediction",
      "type": "topic",
      "url": "/documentation/cinematic/cnboundsprediction-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNBoundsPrediction-swift.struct": {
      "abstract": [
        {
          "text": "A structure representing the bounds of the predicted subject.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNBoundsPrediction"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNBoundsPrediction-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNBoundsPrediction"
        }
      ],
      "role": "symbol",
      "title": "CNBoundsPrediction",
      "type": "topic",
      "url": "/documentation/cinematic/cnboundsprediction-swift.struct"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCinematicError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNCinematicError"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCinematicError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNCinematicError"
        }
      ],
      "role": "symbol",
      "title": "CNCinematicError",
      "type": "topic",
      "url": "/documentation/cinematic/cncinematicerror"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCompositionInfo-7eunn": {
      "abstract": [
        {
          "text": "An object that enables you to add the appropriate number of tracks for a Cinematic asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNCompositionInfo"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCompositionInfo-7eunn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNCompositionInfo"
        }
      ],
      "role": "symbol",
      "title": "CNCompositionInfo",
      "type": "topic",
      "url": "/documentation/cinematic/cncompositioninfo-7eunn"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCompositionInfo-vzoh": {
      "abstract": [
        {
          "text": "An object that enables you to add the appropriate number of tracks for a Cinematic asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNCompositionInfo"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCompositionInfo-vzoh",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNCompositionInfo",
      "type": "topic",
      "url": "/documentation/cinematic/cncompositioninfo-vzoh"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc": {
      "abstract": [
        {
          "text": "An object representing a discrete detection track composed of individual detections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNCustomDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNCustomDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cncustomdetectiontrack-891hc"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-9a2zo": {
      "abstract": [
        {
          "text": "An object representing a discrete detection track composed of individual detections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNCustomDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-9a2zo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNCustomDetectionTrack"
        }
      ],
      "role": "symbol",
      "title": "CNCustomDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cncustomdetectiontrack-9a2zo"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class": {
      "abstract": [
        {
          "text": "An object that represents a decision to focus on a particular detection, or group of detections, at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDecision"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDecision",
      "type": "topic",
      "url": "/documentation/cinematic/cndecision-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-swift.struct": {
      "abstract": [
        {
          "text": "An object that represents a decision to focus on a particular detection, or group of detections, at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDecision"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDecision"
        }
      ],
      "role": "symbol",
      "title": "CNDecision",
      "type": "topic",
      "url": "/documentation/cinematic/cndecision-swift.struct"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class": {
      "abstract": [
        {
          "text": "A structure that represents a detected subject, face, torso or pet at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDetection",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a detected subject, face, torso or pet at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "role": "symbol",
      "title": "CNDetection",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-swift.struct"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-2bxtd": {
      "abstract": [
        {
          "text": "An object representing a series of detections of the same subject over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-2bxtd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionTrack"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-2bxtd"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g": {
      "abstract": [
        {
          "text": "An object representing a series of detections of the same subject over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontrack-61x7g"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType": {
      "abstract": [
        {
          "text": "The type of object detected, such as face, torso, cat, dog and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2": {
      "abstract": [
        {
          "text": "An object representing the fixed detection track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNFixedDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNFixedDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-5aei2"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw": {
      "abstract": [
        {
          "text": "An object representing the fixed detection track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNFixedDetectionTrack"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNFixedDetectionTrack"
        }
      ],
      "role": "symbol",
      "title": "CNFixedDetectionTrack",
      "type": "topic",
      "url": "/documentation/cinematic/cnfixeddetectiontrack-93rrw"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNObjectTracker-1n598": {
      "abstract": [
        {
          "text": "An object that converts a normalized point or rectangle into a detection track that tracks an object over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNObjectTracker"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNObjectTracker-1n598",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNObjectTracker"
        }
      ],
      "role": "symbol",
      "title": "CNObjectTracker",
      "type": "topic",
      "url": "/documentation/cinematic/cnobjecttracker-1n598"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNObjectTracker-7aliq": {
      "abstract": [
        {
          "text": "An object that converts a normalized point or rectangle into a detection track that tracks an object over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNObjectTracker"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNObjectTracker-7aliq",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNObjectTracker",
      "type": "topic",
      "url": "/documentation/cinematic/cnobjecttracker-7aliq"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-1hzh8": {
      "abstract": [
        {
          "text": "An object representing the context in which rendering occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNRenderingSession"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-1hzh8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNRenderingSession"
        }
      ],
      "role": "symbol",
      "title": "CNRenderingSession",
      "type": "topic",
      "url": "/documentation/cinematic/cnrenderingsession-1hzh8"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-8yghc": {
      "abstract": [
        {
          "text": "An object representing the context in which rendering occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNRenderingSession"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-8yghc",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNRenderingSession",
      "type": "topic",
      "url": "/documentation/cinematic/cnrenderingsession-8yghc"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSessionAttributes": {
      "abstract": [
        {
          "text": "A structure for movie-wide attributes required for proper rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNRenderingSessionAttributes"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSessionAttributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNRenderingSessionAttributes",
      "type": "topic",
      "url": "/documentation/cinematic/cnrenderingsessionattributes"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSessionFrameAttributes": {
      "abstract": [
        {
          "text": "Creates an object with the per frame attributes that control the appearance of a single frame of the Cinematic movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNRenderingSessionFrameAttributes"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSessionFrameAttributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNRenderingSessionFrameAttributes",
      "type": "topic",
      "url": "/documentation/cinematic/cnrenderingsessionframeattributes"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNScript-1ispe": {
      "abstract": [
        {
          "text": "A collection of focus decisions, focus transitions, detections, and detection tracks associated with a movie captured in Cinematic mode and methods to change them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNScript"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNScript-1ispe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNScript"
        }
      ],
      "role": "symbol",
      "title": "CNScript",
      "type": "topic",
      "url": "/documentation/cinematic/cnscript-1ispe"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNScript-9e1zn": {
      "abstract": [
        {
          "text": "A collection of focus decisions, focus transitions, detections, and detection tracks associated with a movie captured in Cinematic mode and methods to change them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNScript"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNScript-9e1zn",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNScript",
      "type": "topic",
      "url": "/documentation/cinematic/cnscript-9e1zn"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNScriptChanges": {
      "abstract": [
        {
          "text": "An object that represents a snapshot of the changes made to a movie script, including the added user decisions and detection tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNScriptChanges"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNScriptChanges",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNScriptChanges",
      "type": "topic",
      "url": "/documentation/cinematic/cnscriptchanges"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNScriptFrame": {
      "abstract": [
        {
          "text": "An object that represents what to focus on, and where to focus, in a given movie frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNScriptFrame"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNScriptFrame",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNScriptFrame",
      "type": "topic",
      "url": "/documentation/cinematic/cnscriptframe"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CN_CINEMATIC_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CN_CINEMATIC_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CN_CINEMATIC_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CN_CINEMATIC_EXTERN",
      "type": "topic",
      "url": "/documentation/cinematic/cn_cinematic_extern"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cinematic Constants",
      "type": "topic",
      "url": "/documentation/cinematic/cinematic-constants"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cinematic Data Types",
      "type": "topic",
      "url": "/documentation/cinematic/cinematic-data-types"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cinematic Enumerations",
      "type": "topic",
      "url": "/documentation/cinematic/cinematic-enumerations"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/playing-and-editing-cinematic-mode-video": {
      "abstract": [
        {
          "text": "Play and edit Cinematic mode video with an adjustable depth of field and focus points.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/playing-and-editing-cinematic-mode-video",
      "kind": "article",
      "role": "sampleCode",
      "title": "Playing and editing Cinematic mode video",
      "type": "topic",
      "url": "/documentation/cinematic/playing-and-editing-cinematic-mode-video"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/playing-and-editing-cinematic-mode-video",
        "doc://com.apple.cinematic/documentation/Cinematic/CNScript-1ispe"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Reading-and-rendering",
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNAssetInfo-2ata2",
        "doc://com.apple.cinematic/documentation/Cinematic/CNCompositionInfo-7eunn",
        "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-1hzh8"
      ],
      "title": "Reading and rendering"
    },
    {
      "anchor": "Editing",
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-swift.struct",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-swift.struct",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-2bxtd",
        "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-93rrw",
        "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-9a2zo",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType"
      ],
      "title": "Editing"
    },
    {
      "anchor": "Custom-Object-Tracking",
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNBoundsPrediction-swift.struct",
        "doc://com.apple.cinematic/documentation/Cinematic/CNObjectTracker-1n598"
      ],
      "title": "Custom Object Tracking"
    },
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/CNCinematicError"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-enumerations",
        "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-constants",
        "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-data-types"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.cinematic/documentation/Cinematic/playing-and-editing-cinematic-mode-video",
                "doc://com.apple.cinematic/documentation/Cinematic/CNScript-9e1zn",
                "doc://com.apple.cinematic/documentation/Cinematic/CNScriptChanges",
                "doc://com.apple.cinematic/documentation/Cinematic/CNScriptFrame"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Reading-and-rendering",
              "identifiers": [
                "doc://com.apple.cinematic/documentation/Cinematic/CNAssetInfo-8ja4t",
                "doc://com.apple.cinematic/documentation/Cinematic/CNCompositionInfo-vzoh",
                "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-8yghc",
                "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSessionAttributes",
                "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSessionFrameAttributes"
              ],
              "title": "Reading and rendering"
            },
            {
              "anchor": "Editing",
              "identifiers": [
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDecision-c.class",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionTrack-61x7g",
                "doc://com.apple.cinematic/documentation/Cinematic/CNFixedDetectionTrack-5aei2",
                "doc://com.apple.cinematic/documentation/Cinematic/CNCustomDetectionTrack-891hc",
                "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType"
              ],
              "title": "Editing"
            },
            {
              "anchor": "Custom-Object-Tracking",
              "identifiers": [
                "doc://com.apple.cinematic/documentation/Cinematic/CNObjectTracker-7aliq",
                "doc://com.apple.cinematic/documentation/Cinematic/CNBoundsPrediction-c.class"
              ],
              "title": "Custom Object Tracking"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-enumerations",
                "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-constants",
                "doc://com.apple.cinematic/documentation/Cinematic/Cinematic-data-types"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cinematic/documentation/Cinematic/CN_CINEMATIC_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/title",
          "value": "CNDetectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cinematic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cinematic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
