{
  "abstract": [
    {
      "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ClassKit",
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "11.4",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "11.4",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "ClassKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Educational apps provide access to resources like books and videos while reinforcing learning through interactive visualizations, games, and assessments. ClassKit lets you organize educational material so that teachers can assign activities to students and see their progress.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ClassKit environment consists of a teacher’s device (or devices) and many student devices communicating through iCloud. Each device runs your app (plus other educational apps) along with Apple’s Schoolwork app, with ClassKit acting as a hub on the device. Using Schoolwork, teachers can see what assignable content your app exposes to ClassKit. They can then create assignments based on that content, and monitor progress of all their students. Meanwhile, students use Schoolwork to receive assignments that link directly to content in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2961556",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "ClassKit doesn’t replace any existing logic or storage mechanisms in your app, and you don’t use it to generate any new user interfaces. Instead, you use ClassKit to publicize the structure you already have, so that teachers can use Apple’s Schoolwork app to create assignments based on your app’s content and measure their students’ progress through those assignments.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "ClassKit is designed for educational organizations that use ",
                  "type": "text"
                },
                {
                  "identifier": "https://www.apple.com/education/it/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Consider adopting ClassKit if education is your intended market.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSActivity": {
      "abstract": [
        {
          "text": "A representation of user interaction with a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSActivity"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSActivity"
        }
      ],
      "role": "symbol",
      "title": "CLSActivity",
      "type": "topic",
      "url": "/documentation/classkit/clsactivity"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSActivityItem": {
      "abstract": [
        {
          "text": "An abstract base class for gathering information about an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSActivityItem"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSActivityItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSActivityItem"
        }
      ],
      "role": "symbol",
      "title": "CLSActivityItem",
      "type": "topic",
      "url": "/documentation/classkit/clsactivityitem"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryItem": {
      "abstract": [
        {
          "text": "Activity information that is true or false, pass or fail, yes or no.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSBinaryItem"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSBinaryItem"
        }
      ],
      "role": "symbol",
      "title": "CLSBinaryItem",
      "type": "topic",
      "url": "/documentation/classkit/clsbinaryitem"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContext": {
      "abstract": [
        {
          "text": "An area of your app that represents an assignable task, like a quiz or a chapter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContext"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContext"
        }
      ],
      "role": "symbol",
      "title": "CLSContext",
      "type": "topic",
      "url": "/documentation/classkit/clscontext"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider": {
      "abstract": [
        {
          "text": "An interface used to tell your ClassKit context provider app extension to update contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSContextProvider"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSContextProvider"
        }
      ],
      "role": "symbol",
      "title": "CLSContextProvider",
      "type": "topic",
      "url": "/documentation/classkit/clscontextprovider"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore": {
      "abstract": [
        {
          "text": "A container for all the ClassKit data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSDataStore"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSDataStore"
        }
      ],
      "role": "symbol",
      "title": "CLSDataStore",
      "type": "topic",
      "url": "/documentation/classkit/clsdatastore"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError": {
      "abstract": [
        {
          "text": "Errors issued by ClassKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSError"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSError"
        }
      ],
      "role": "symbol",
      "title": "CLSError",
      "type": "topic",
      "url": "/documentation/classkit/clserror"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code": {
      "abstract": [
        {
          "text": "Error codes that ClassKit issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSErrorCodeDomain": {
      "abstract": [
        {
          "text": "The error domain that ClassKit uses when issuing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSErrorCodeDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSErrorCodeDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeDomain"
        }
      ],
      "role": "symbol",
      "title": "CLSErrorCodeDomain",
      "type": "topic",
      "url": "/documentation/classkit/clserrorcodedomain"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSErrorUserInfoKey": {
      "abstract": [
        {
          "text": "Keys that appear in the user info dictionary in errors that ClassKit creates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSErrorUserInfoKey"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSErrorUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "CLSErrorUserInfoKey",
      "type": "topic",
      "url": "/documentation/classkit/clserroruserinfokey"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSQuantityItem": {
      "abstract": [
        {
          "text": "Activity information that signifies a quantity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSQuantityItem"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSQuantityItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSQuantityItem"
        }
      ],
      "role": "symbol",
      "title": "CLSQuantityItem",
      "type": "topic",
      "url": "/documentation/classkit/clsquantityitem"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSScoreItem": {
      "abstract": [
        {
          "text": "Activity information that signifies a score out of a possible maximum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSScoreItem"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSScoreItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSScoreItem"
        }
      ],
      "role": "symbol",
      "title": "CLSScoreItem",
      "type": "topic",
      "url": "/documentation/classkit/clsscoreitem"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLS_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLS_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLS_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLS_EXTERN",
      "type": "topic",
      "url": "/documentation/classkit/cls_extern"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLS_EXTERN_HIDDEN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLS_EXTERN_HIDDEN"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLS_EXTERN_HIDDEN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLS_EXTERN_HIDDEN",
      "type": "topic",
      "url": "/documentation/classkit/cls_extern_hidden"
    },
    "doc://com.apple.classkit/documentation/ClassKit/advertising-your-app-s-assignable-content": {
      "abstract": [
        {
          "text": "Assemble a hierarchy of contexts and declare your app’s assignable content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/advertising-your-app-s-assignable-content",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Advertising your app’s assignable content",
      "type": "topic",
      "url": "/documentation/classkit/advertising-your-app-s-assignable-content"
    },
    "doc://com.apple.classkit/documentation/ClassKit/enabling-classkit-in-your-app": {
      "abstract": [
        {
          "text": "Prepare your app and your development environment to adopt ClassKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/enabling-classkit-in-your-app",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Enabling ClassKit in your app",
      "type": "topic",
      "url": "/documentation/classkit/enabling-classkit-in-your-app"
    },
    "doc://com.apple.classkit/documentation/ClassKit/incorporating-classkit-into-an-educational-app": {
      "abstract": [
        {
          "text": "Walk through the process of setting up assignments and recording student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/incorporating-classkit-into-an-educational-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Incorporating ClassKit into an Educational App",
      "type": "topic",
      "url": "/documentation/classkit/incorporating-classkit-into-an-educational-app"
    },
    "doc://com.apple.classkit/documentation/ClassKit/recording-additional-metrics-about-a-completed-task": {
      "abstract": [
        {
          "text": "Add an activity item to an activity to record additional information about a student’s attempt to complete a task.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/recording-additional-metrics-about-a-completed-task",
      "kind": "article",
      "role": "article",
      "title": "Recording additional metrics about a completed task",
      "type": "topic",
      "url": "/documentation/classkit/recording-additional-metrics-about-a-completed-task"
    },
    "doc://com.apple.classkit/documentation/ClassKit/recording-student-progress": {
      "abstract": [
        {
          "text": "Create an activity to record student progress through an assignment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/recording-student-progress",
      "kind": "article",
      "role": "article",
      "title": "Recording student progress",
      "type": "topic",
      "url": "/documentation/classkit/recording-student-progress"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment": {
      "abstract": [
        {
          "text": "The ClassKit development or production environment for an education app that works with the Schoolwork app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
      "kind": "symbol",
      "role": "symbol",
      "title": "ClassKit Environment Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://www.apple.com/education/it/": {
      "identifier": "https://www.apple.com/education/it/",
      "title": "Apple School Manager and Managed Apple IDs",
      "titleInlineContent": [
        {
          "text": "Apple School Manager and Managed Apple IDs",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.apple.com/education/it/"
    },
    "media-2961556": {
      "alt": "Diagram showing how your app connects to the other parts of the virtual classroom.",
      "identifier": "media-2961556",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7d0f59a3ec04672ed3eca0956e814025/media-2961556.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e2acdb865501008f2e8a12d23b500bdd/media-2961556@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/enabling-classkit-in-your-app",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
        "doc://com.apple.classkit/documentation/ClassKit/incorporating-classkit-into-an-educational-app",
        "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Contexts",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/advertising-your-app-s-assignable-content",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContext",
        "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider"
      ],
      "title": "Contexts"
    },
    {
      "anchor": "Activities",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/recording-student-progress",
        "doc://com.apple.classkit/documentation/ClassKit/CLSActivity"
      ],
      "title": "Activities"
    },
    {
      "anchor": "Activity-items",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/recording-additional-metrics-about-a-completed-task",
        "doc://com.apple.classkit/documentation/ClassKit/CLSScoreItem",
        "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryItem",
        "doc://com.apple.classkit/documentation/ClassKit/CLSQuantityItem",
        "doc://com.apple.classkit/documentation/ClassKit/CLSActivityItem"
      ],
      "title": "Activity items"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSError",
        "doc://com.apple.classkit/documentation/ClassKit/CLSErrorCodeDomain",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code",
        "doc://com.apple.classkit/documentation/ClassKit/CLSErrorUserInfoKey"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/enabling-classkit-in-your-app",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
                "doc://com.apple.classkit/documentation/ClassKit/incorporating-classkit-into-an-educational-app",
                "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Contexts",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/advertising-your-app-s-assignable-content",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContext",
                "doc://com.apple.classkit/documentation/ClassKit/CLSContextProvider"
              ],
              "title": "Contexts"
            },
            {
              "anchor": "Activities",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/recording-student-progress",
                "doc://com.apple.classkit/documentation/ClassKit/CLSActivity"
              ],
              "title": "Activities"
            },
            {
              "anchor": "Activity-items",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/recording-additional-metrics-about-a-completed-task",
                "doc://com.apple.classkit/documentation/ClassKit/CLSScoreItem",
                "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryItem",
                "doc://com.apple.classkit/documentation/ClassKit/CLSQuantityItem",
                "doc://com.apple.classkit/documentation/ClassKit/CLSActivityItem"
              ],
              "title": "Activity items"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSErrorCodeDomain",
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code",
                "doc://com.apple.classkit/documentation/ClassKit/CLSErrorUserInfoKey"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLS_EXTERN",
                "doc://com.apple.classkit/documentation/ClassKit/CLS_EXTERN_HIDDEN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext/title",
          "value": "CLSContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSQuantityItem/title",
          "value": "CLSQuantityItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSQuantityItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSQuantityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSQuantityItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSQuantityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSScoreItem/title",
          "value": "CLSScoreItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSScoreItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSScoreItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSScoreItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSScoreItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivityItem/title",
          "value": "CLSActivityItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivityItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSActivityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivityItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSActivityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSErrorCodeDomain/title",
          "value": "CLSErrorCodeDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSErrorCodeDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSErrorUserInfoKey/title",
          "value": "CLSErrorUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSErrorUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSErrorUserInfoKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryItem/title",
          "value": "CLSBinaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity/title",
          "value": "CLSActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextProvider/title",
          "value": "CLSContextProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSContextProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSContextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code/title",
          "value": "CLSErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/title",
          "value": "CLSDataStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
