{
  "abstract": [
    {
      "text": "Find and access identities, that is, users and groups. Display the Identity Picker, which lets users create and select identities.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.collaboration/documentation/Collaboration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "Collaboration",
    "modules": [
      {
        "name": "Collaboration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.5",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Collaboration"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Collaboration framework allows developers to monitor identities and their attributes. Identities reside in an identity authority, which can be either local to a user’s system, or on a network directory. The Collaboration framework also manages a sheet, known as the identity picker, to allow applications to select identities.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Collaboration framework works closely with the Core Services Identity APIs to form the Identity Services technology. If you need the ability to create and manipulate identities read ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Networking/Reference/IdentityServices_Ref/index.html#//apple_ref/doc/uid/TP40004673",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.collaboration/documentation/Collaboration": {
      "abstract": [
        {
          "text": "Find and access identities, that is, users and groups. Display the Identity Picker, which lets users create and select identities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration",
      "kind": "symbol",
      "role": "collection",
      "title": "Collaboration",
      "type": "topic",
      "url": "/documentation/collaboration"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity": {
      "abstract": [
        {
          "text": "An object of the ",
          "type": "text"
        },
        {
          "code": "CBGroupIdentity",
          "type": "codeVoice"
        },
        {
          "text": " class represents a group identity and is used for viewing the attributes of group identities from an identity authority. The principal attributes of a ",
          "type": "text"
        },
        {
          "code": "CBGroupIdentity",
          "type": "codeVoice"
        },
        {
          "text": " object are a POSIX group identifier (GID) and a list of members.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBGroupIdentity"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBGroupIdentity"
        }
      ],
      "role": "symbol",
      "title": "CBGroupIdentity",
      "type": "topic",
      "url": "/documentation/collaboration/cbgroupidentity"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "CBIdentity",
          "type": "codeVoice"
        },
        {
          "text": " object is used for accessing the attributes of an identity stored in an identity authority. You can use an identity object for finding identities, and storing them in an access control list (ACL). If you need to edit these attributes, take advantage of the ",
          "type": "text"
        },
        {
          "code": "CSIdentity",
          "type": "codeVoice"
        },
        {
          "text": " class in Core Services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBIdentity"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBIdentity"
        }
      ],
      "role": "symbol",
      "title": "CBIdentity",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentity"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority": {
      "abstract": [
        {
          "text": "An identity authority is a database that stores information about identities. The ",
          "type": "text"
        },
        {
          "code": "CBIdentityAuthority",
          "type": "codeVoice"
        },
        {
          "text": " class defines one or more identity authorities. You can search this database for identities in conjunction with the ",
          "type": "text"
        },
        {
          "code": "CBIdentity",
          "type": "codeVoice"
        },
        {
          "text": " class factory methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBIdentityAuthority"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBIdentityAuthority"
        }
      ],
      "role": "symbol",
      "title": "CBIdentityAuthority",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "CBIdentityPicker",
          "type": "codeVoice"
        },
        {
          "text": " object allows a user to select identities—for example, user or group objects—that it wants one or more services or shared resources to have access to. An identity picker can be displayed either as an application-modal dialog or as a sheet attached to a document window. An identity picker returns the selected records to be added to access control lists using Collaboration. If a selected record is not a user or group identity, then an identity picker prompts the user for additional information—such as a password—to promote that record to a sharing account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBIdentityPicker"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBIdentityPicker"
        }
      ],
      "role": "symbol",
      "title": "CBIdentityPicker",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentitypicker"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity": {
      "abstract": [
        {
          "text": "An object of the ",
          "type": "text"
        },
        {
          "code": "CBUserIdentity",
          "type": "codeVoice"
        },
        {
          "text": " class represents a user identity and is used for accessing the attributes of a user identity from an identity authority. The principal attributes of ",
          "type": "text"
        },
        {
          "code": "CBUserIdentity",
          "type": "codeVoice"
        },
        {
          "text": " are a POSIX user identifier (UID), password, and certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUserIdentity"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUserIdentity"
        }
      ],
      "role": "symbol",
      "title": "CBUserIdentity",
      "type": "topic",
      "url": "/documentation/collaboration/cbuseridentity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490",
      "title": "Identity Services Programming Guide",
      "titleInlineContent": [
        {
          "text": "Identity Services Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490"
    },
    "https://developer.apple.com/library/archive/documentation/Networking/Reference/IdentityServices_Ref/index.html#//apple_ref/doc/uid/TP40004673": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Networking/Reference/IdentityServices_Ref/index.html#//apple_ref/doc/uid/TP40004673",
      "title": "Core Services Identity Reference",
      "titleInlineContent": [
        {
          "text": "Core Services Identity Reference",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Networking/Reference/IdentityServices_Ref/index.html#//apple_ref/doc/uid/TP40004673"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Networking/Reference/IdentityServices_Ref/index.html#//apple_ref/doc/uid/TP40004673",
        "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490"
      ],
      "title": "Related Documentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker",
        "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity"
      ],
      "title": "Classes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity",
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentity",
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority",
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker",
                "doc://com.apple.collaboration/documentation/Collaboration/CBUserIdentity"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/Networking/Reference/IdentityServices_Ref/index.html#//apple_ref/doc/uid/TP40004673",
                "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBGroupIdentity/title",
          "value": "CBGroupIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBGroupIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBGroupIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBGroupIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBGroupIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity/title",
          "value": "CBIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker/title",
          "value": "CBIdentityPicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/title",
          "value": "CBIdentityAuthority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity/title",
          "value": "CBUserIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUserIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBUserIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUserIdentity"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/collaboration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/collaboration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
