{
  "abstract": [
    {
      "text": "Reproduce colors accurately across a range of input, output, and display devices.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.colorsync/documentation/ColorSync"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ColorSync",
    "modules": [
      {
        "name": "ColorSync"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.13",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "ColorSync"
  },
  "references": {
    "doc://com.apple.colorsync/documentation/ColorSync": {
      "abstract": [
        {
          "text": "Reproduce colors accurately across a range of input, output, and display devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync",
      "kind": "symbol",
      "role": "collection",
      "title": "ColorSync",
      "type": "topic",
      "url": "/documentation/colorsync"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CMMApplyTransformProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMApplyTransformProc"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CMMApplyTransformProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMApplyTransformProc"
        }
      ],
      "role": "symbol",
      "title": "CMMApplyTransformProc",
      "type": "topic",
      "url": "/documentation/colorsync/cmmapplytransformproc"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CMMCreateTransformPropertyProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMCreateTransformPropertyProc"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CMMCreateTransformPropertyProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMCreateTransformPropertyProc"
        }
      ],
      "role": "symbol",
      "title": "CMMCreateTransformPropertyProc",
      "type": "topic",
      "url": "/documentation/colorsync/cmmcreatetransformpropertyproc"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CMMInitializeLinkProfileProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMInitializeLinkProfileProc"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CMMInitializeLinkProfileProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMInitializeLinkProfileProc"
        }
      ],
      "role": "symbol",
      "title": "CMMInitializeLinkProfileProc",
      "type": "topic",
      "url": "/documentation/colorsync/cmminitializelinkprofileproc"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CMMInitializeTransformProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMInitializeTransformProc"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CMMInitializeTransformProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMInitializeTransformProc"
        }
      ],
      "role": "symbol",
      "title": "CMMInitializeTransformProc",
      "type": "topic",
      "url": "/documentation/colorsync/cmminitializetransformproc"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncAlphaInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncAlphaInfo"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncAlphaInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncAlphaInfo"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncAlphaInfo",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncalphainfo"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncCMM"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncCMM"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncCMM",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynccmm"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMIterateCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncCMMIterateCallback"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMIterateCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncCMMIterateCallback"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncCMMIterateCallback",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynccmmiteratecallback"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDataDepth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDataDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncDataDepth"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncDataDepth",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncdatadepth"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDataLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncDataLayout"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDataLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncDataLayout"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncDataLayout",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncdatalayout"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceProfileIterateCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncDeviceProfileIterateCallback"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceProfileIterateCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncDeviceProfileIterateCallback"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncDeviceProfileIterateCallback",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncdeviceprofileiteratecallback"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncMD5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncMD5"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncMD5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncMD5"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncMD5",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncmd5"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncMutableProfile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncMutableProfile"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncMutableProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncMutableProfile"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncMutableProfile",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncmutableprofile"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncProfile"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncProfile"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncProfile",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncprofile"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIterateCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncProfileIterateCallback"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIterateCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncProfileIterateCallback"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncProfileIterateCallback",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncprofileiteratecallback"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncTransform": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncTransform"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncTransform"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncTransform",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynctransform"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/colorsync-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/colorsync-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ColorSync Constants",
      "type": "topic",
      "url": "/documentation/colorsync/colorsync-constants"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/colorsync-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/colorsync-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ColorSync Functions",
      "type": "topic",
      "url": "/documentation/colorsync/colorsync-functions"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncAlphaNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncAlphaInfo",
          "text": "ColorSyncAlphaInfo"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncAlphaNone"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncAlphaNone",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncalphanone"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformUseITU709OETF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncTransformUseITU709OETF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformUseITU709OETF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncTransformUseITU709OETF"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncTransformUseITU709OETF",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsynctransformuseitu709oetf"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.colorsync/documentation/ColorSync/colorsync-constants",
        "doc://com.apple.colorsync/documentation/ColorSync/colorsync-functions"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMM",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncMutableProfile",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfile",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncTransform"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncAlphaInfo",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDataDepth",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncMD5"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaNone",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformUseITU709OETF"
      ],
      "title": "Variables"
    },
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.colorsync/documentation/ColorSync/CMMApplyTransformProc",
        "doc://com.apple.colorsync/documentation/ColorSync/CMMCreateTransformPropertyProc",
        "doc://com.apple.colorsync/documentation/ColorSync/CMMInitializeLinkProfileProc",
        "doc://com.apple.colorsync/documentation/ColorSync/CMMInitializeTransformProc",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMIterateCallback",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDataLayout",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceProfileIterateCallback",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIterateCallback"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.colorsync/documentation/ColorSync/colorsync-constants",
                "doc://com.apple.colorsync/documentation/ColorSync/colorsync-functions"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncMD5"
              ],
              "title": "Structures"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformUseITU709OETF"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Type-Aliases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.colorsync/documentation/ColorSync/CMMApplyTransformProc",
                "doc://com.apple.colorsync/documentation/ColorSync/CMMCreateTransformPropertyProc",
                "doc://com.apple.colorsync/documentation/ColorSync/CMMInitializeLinkProfileProc",
                "doc://com.apple.colorsync/documentation/ColorSync/CMMInitializeTransformProc",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMM",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMIterateCallback",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDataLayout",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceProfileIterateCallback",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncMutableProfile",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfile",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIterateCallback",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncTransform"
              ],
              "title": "Type Aliases"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncAlphaInfo",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDataDepth"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDeviceProfileIterateCallback/title",
          "value": "ColorSyncDeviceProfileIterateCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDeviceProfileIterateCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncDeviceProfileIterateCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDeviceProfileIterateCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncDeviceProfileIterateCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMIterateCallback/title",
          "value": "ColorSyncCMMIterateCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMIterateCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMIterateCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMIterateCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMIterateCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMCreateTransformPropertyProc/title",
          "value": "CMMCreateTransformPropertyProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMCreateTransformPropertyProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMCreateTransformPropertyProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMCreateTransformPropertyProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMCreateTransformPropertyProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileIterateCallback/title",
          "value": "ColorSyncProfileIterateCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileIterateCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileIterateCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileIterateCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileIterateCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncMD5/title",
          "value": "ColorSyncMD5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncMD5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncMD5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncMD5/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncMD5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncTransform/title",
          "value": "ColorSyncTransformRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncTransformRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncTransformRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDataDepth/title",
          "value": "ColorSyncDataDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDataDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncDataDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDataDepth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncDataDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncMutableProfile/title",
          "value": "ColorSyncMutableProfileRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncMutableProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncMutableProfileRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncMutableProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncMutableProfileRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncTransformUseITU709OETF/title",
          "value": "kColorSyncTransformUseITU709OETF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncTransformUseITU709OETF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncTransformUseITU709OETF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncAlphaInfo/title",
          "value": "ColorSyncAlphaInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncAlphaInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncAlphaInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncAlphaInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncAlphaInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDataLayout/title",
          "value": "ColorSyncDataLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDataLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncDataLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDataLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncDataLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfile/title",
          "value": "ColorSyncProfileRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMInitializeLinkProfileProc/title",
          "value": "CMMInitializeLinkProfileProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMInitializeLinkProfileProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMInitializeLinkProfileProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMInitializeLinkProfileProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMInitializeLinkProfileProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMInitializeTransformProc/title",
          "value": "CMMInitializeTransformProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMInitializeTransformProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMInitializeTransformProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMInitializeTransformProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMInitializeTransformProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMApplyTransformProc/title",
          "value": "CMMApplyTransformProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMApplyTransformProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMApplyTransformProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CMMApplyTransformProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMApplyTransformProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncAlphaNone/title",
          "value": "kColorSyncAlphaNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncAlphaNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncAlphaNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMM/title",
          "value": "ColorSyncCMMRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMM/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/colorsync"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/colorsync"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
