{
  "abstract": [
    {
      "text": "Take control of the drawing environment and render your own content using Metal.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CompositorServices",
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Compositor Services"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Compositor Services lets you draw directly to the device’s displays using Metal and your own rendering engine.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Use this framework to create a fully immersive scene in your app that doesn’t require integration with the person’s surroundings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you present an immersive space with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " content from your app,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you receive a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with the information you need to set up your Metal drawing environment.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Use the layer to start your rendering loop and deliver successive frames of content.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The layer provides the timing information you need to deliver frames at the refresh rate of the display.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "It also provides the Metal textures and other information that you need to draw content on the device displays.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about how to draw your app’s content using Metal,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_EXPORT",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_export"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_EXTERN",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_extern"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXTERN_C_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_EXTERN_C_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXTERN_C_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_EXTERN_C_BEGIN",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_extern_c_begin"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXTERN_C_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_EXTERN_C_END"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXTERN_C_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_EXTERN_C_END",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_extern_c_end"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_FINAL_CLASS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_FINAL_CLASS"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_FINAL_CLASS",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_FINAL_CLASS",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_final_class"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_NONNULL_EXTERN_C_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_NONNULL_EXTERN_C_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_NONNULL_EXTERN_C_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_NONNULL_EXTERN_C_BEGIN",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_nonnull_extern_c_begin"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_NONNULL_EXTERN_C_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_NONNULL_EXTERN_C_END"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_NONNULL_EXTERN_C_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_NONNULL_EXTERN_C_END",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_nonnull_extern_c_end"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_NULLABLE_STRUCT_REF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_NULLABLE_STRUCT_REF"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_NULLABLE_STRUCT_REF",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_NULLABLE_STRUCT_REF",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_nullable_struct_ref"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_OBJECT_DECL"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_OBJECT_DECL",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_object_decl"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_OBJECT_DECL_"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_OBJECT_DECL_",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_object_decl_"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_OBJECT_DECL_1"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_OBJECT_DECL_1",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_object_decl_1"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_OBJECT_DECL_2"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_2",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_OBJECT_DECL_2",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_object_decl_2"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_BASE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_OBJECT_DECL_BASE"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_BASE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_OBJECT_DECL_BASE",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_object_decl_base"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_NAME": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_OBJECT_NAME"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_OBJECT_NAME",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_object_name"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_STRUCT_REF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_STRUCT_REF"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_STRUCT_REF",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_STRUCT_REF",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_struct_ref"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_STRUCT_REF_BASE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_STRUCT_REF_BASE"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_STRUCT_REF_BASE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_STRUCT_REF_BASE",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_struct_ref_base"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CP_WARN_UNUSED_RESULT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CP_WARN_UNUSED_RESULT"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CP_WARN_UNUSED_RESULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "CP_WARN_UNUSED_RESULT",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_warn_unused_result"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer": {
      "abstract": [
        {
          "text": "A type that you use with an immersive space to display fully immersive content using Metal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompositorLayer"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompositorLayer"
        }
      ],
      "role": "symbol",
      "title": "CompositorLayer",
      "type": "topic",
      "url": "/documentation/compositorservices/compositorlayer"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration": {
      "abstract": [
        {
          "text": "An interface for specifying the texture configurations and rendering behaviors to use with your Metal rendering engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompositorLayerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompositorLayerConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CompositorLayerConfiguration",
      "type": "topic",
      "url": "/documentation/compositorservices/compositorlayerconfiguration"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/DefaultCompositorLayerConfiguration": {
      "abstract": [
        {
          "text": "A type that configures the layer with the default texture configurations and rendering behaviors for the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DefaultCompositorLayerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/DefaultCompositorLayerConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DefaultCompositorLayerConfiguration"
        }
      ],
      "role": "symbol",
      "title": "DefaultCompositorLayerConfiguration",
      "type": "topic",
      "url": "/documentation/compositorservices/defaultcompositorlayerconfiguration"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer": {
      "abstract": [
        {
          "text": "A type that provides the Metal types and timing information you need to draw your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable": {
      "abstract": [
        {
          "text": "A type that provides the textures and information you need to draw a frame of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Drawable"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Drawable"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Drawable",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View": {
      "abstract": [
        {
          "text": "A type that provides information on how to render content into the frame’s textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Drawable.View",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable/view"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Frame": {
      "abstract": [
        {
          "text": "A type that provides access to the timing information and data types you need to render a single frame of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Frame"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Frame"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Frame",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/frame"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRendererConfigurationError": {
      "abstract": [
        {
          "text": "Errors that can occur during layer configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerRendererConfigurationError"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRendererConfigurationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerRendererConfigurationError"
        }
      ],
      "role": "symbol",
      "title": "LayerRendererConfigurationError",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrendererconfigurationerror"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology": {
      "abstract": [
        {
          "text": "A type that specifies the organization of one of the drawable’s textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextureTopology"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextureTopology"
        }
      ],
      "role": "symbol",
      "title": "TextureTopology",
      "type": "topic",
      "url": "/documentation/compositorservices/texturetopology"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/compositorservices-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/compositorservices-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CompositorServices Functions",
      "type": "topic",
      "url": "/documentation/compositorservices/compositorservices-functions"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_compute_projection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_drawable_compute_projection"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_compute_projection",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_drawable_compute_projection",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_drawable_compute_projection"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_binocular_frustum_matrix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_frame_binocular_frustum_matrix"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_binocular_frustum_matrix",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_frame_binocular_frustum_matrix",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_frame_binocular_frustum_matrix"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_monocular_frustum_matrix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_frame_monocular_frustum_matrix"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_monocular_frustum_matrix",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_frame_monocular_frustum_matrix",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_frame_monocular_frustum_matrix"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_timing_get_trackable_anchor_time": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_frame_timing_get_trackable_anchor_time"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_timing_get_trackable_anchor_time",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_frame_timing_get_trackable_anchor_time",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_frame_timing_get_trackable_anchor_time"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_error_code": {
      "abstract": [
        {
          "text": "Errors that can occur during layer configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_configuration_error_code"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_error_code",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_configuration_error_code",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_configuration_error_code"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_error_domain": {
      "abstract": [
        {
          "text": "The domain for errors that occur during layer configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_layer_renderer_configuration_error_domain"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_error_domain",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_layer_renderer_configuration_error_domain",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_layer_renderer_configuration_error_domain"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time": {
      "abstract": [
        {
          "text": "A Mach absolute time clock value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_time"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_time",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_time"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/drawable": {
      "abstract": [
        {
          "text": "A type that provides information on how to render content into the frame’s textures.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/drawable",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drawable",
      "type": "topic",
      "url": "/documentation/compositorservices/drawable"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal": {
      "abstract": [
        {
          "text": "Create a fully immersive experience in visionOS using a custom Metal-based rendering engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal",
      "kind": "article",
      "role": "article",
      "title": "Drawing fully immersive content using Metal",
      "type": "topic",
      "url": "/documentation/compositorservices/drawing-fully-immersive-content-using-metal"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/frames": {
      "abstract": [
        {
          "text": "A type that represents a single frame of content, manages the pace of animations,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and provides access to the drawable environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/frames",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Frames",
      "type": "topic",
      "url": "/documentation/compositorservices/frames"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/interacting-with-virtual-content-blended-with-passthrough": {
      "abstract": [
        {
          "text": "Present a mixed immersion style space to draw content in a person’s surroundings,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and choose how upper limbs appear with respect to rendered content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/interacting-with-virtual-content-blended-with-passthrough",
      "kind": "article",
      "role": "sampleCode",
      "title": "Interacting with virtual content blended with passthrough",
      "type": "topic",
      "url": "/documentation/compositorservices/interacting-with-virtual-content-blended-with-passthrough"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/layer-renderer": {
      "abstract": [
        {
          "text": "A type that provides the Metal types and timing information you need to draw your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/layer-renderer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layer renderer",
      "type": "topic",
      "url": "/documentation/compositorservices/layer-renderer"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/utilities": {
      "abstract": [
        {
          "text": "Common types and utilities to manage your app’s rendering process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Utilities",
      "type": "topic",
      "url": "/documentation/compositorservices/utilities"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/view": {
      "abstract": [
        {
          "text": "A type that manages the viewport and texture details for each portion of your frame’s content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/view",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View",
      "type": "topic",
      "url": "/documentation/compositorservices/view"
    },
    "doc://com.apple.documentation/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/Metal"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "App-integration",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal",
        "doc://com.apple.compositorservices/documentation/CompositorServices/interacting-with-virtual-content-blended-with-passthrough",
        "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayer",
        "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorLayerConfiguration",
        "doc://com.apple.compositorservices/documentation/CompositorServices/DefaultCompositorLayerConfiguration"
      ],
      "title": "App integration"
    },
    {
      "anchor": "Render-loop-setup",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Frame"
      ],
      "title": "Render-loop setup"
    },
    {
      "anchor": "Drawing-environment",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/View"
      ],
      "title": "Drawing environment"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRendererConfigurationError"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/compositorservices-functions"
      ],
      "title": "Articles"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/TextureTopology"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "App-integration",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/drawing-fully-immersive-content-using-metal",
                "doc://com.apple.compositorservices/documentation/CompositorServices/interacting-with-virtual-content-blended-with-passthrough"
              ],
              "title": "App integration"
            },
            {
              "anchor": "Render-loop-setup",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/layer-renderer",
                "doc://com.apple.compositorservices/documentation/CompositorServices/frames",
                "doc://com.apple.compositorservices/documentation/CompositorServices/utilities"
              ],
              "title": "Render-loop setup"
            },
            {
              "anchor": "Drawing-environment",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/drawable",
                "doc://com.apple.compositorservices/documentation/CompositorServices/view"
              ],
              "title": "Drawing environment"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_error_domain",
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_layer_renderer_configuration_error_code"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Articles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/compositorservices-functions"
              ],
              "title": "Articles"
            },
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_time"
              ],
              "title": "Structures"
            },
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_compute_projection",
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_binocular_frustum_matrix",
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_monocular_frustum_matrix",
                "doc://com.apple.compositorservices/documentation/CompositorServices/cp_frame_timing_get_trackable_anchor_time"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXPORT",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXTERN",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXTERN_C_BEGIN",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_EXTERN_C_END",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_FINAL_CLASS",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_NONNULL_EXTERN_C_BEGIN",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_NONNULL_EXTERN_C_END",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_NULLABLE_STRUCT_REF",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_1",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_2",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_DECL_BASE",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_OBJECT_NAME",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_STRUCT_REF",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_STRUCT_REF_BASE",
                "doc://com.apple.compositorservices/documentation/CompositorServices/CP_WARN_UNUSED_RESULT"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/title",
          "value": "CP_OBJECT_cp_layer_renderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compositorservices"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
