{
  "abstract": [
    {
      "text": "Provide an interface that allows people to display information about their",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "contacts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Contacts-UI/documentation/ContactsUI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ContactsUI",
    "modules": [
      {
        "name": "Contacts UI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.11",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Contacts UI"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Contacts UI framework contains user interface objects that provide access",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to a person’s contacts in your app. Depending on your app’s authorization",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "level for using contacts (as indicated by",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Contacts/CNContactStore/authorizationStatus(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "),",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app may be able to display, edit, select, and create contacts. When the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "authorization level is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Contacts/CNAuthorizationStatus/limited",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you can display a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/ContactAccessButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to request access to contacts beyond",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the limited set a person has currently granted your app access to.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Contacts-UI/documentation/ContactsUI": {
      "abstract": [
        {
          "text": "Provide an interface that allows people to display information about their",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts UI",
      "type": "topic",
      "url": "/documentation/contactsui"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker": {
      "abstract": [
        {
          "text": "A popover-based interface for selecting a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPicker"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPicker"
        }
      ],
      "role": "symbol",
      "title": "CNContactPicker",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactpicker"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that displays an interface for picking contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "CNContactPickerViewController",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactpickerviewcontroller"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController": {
      "abstract": [
        {
          "text": "A view controller that displays a new, unknown, or existing contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactViewController"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactViewController"
        }
      ],
      "role": "symbol",
      "title": "CNContactViewController",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactviewcontroller"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/ContactAccessButton": {
      "abstract": [
        {
          "text": "A SwiftUI button that you use to add to the set of contacts someone shares with",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ContactAccessButton"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/ContactAccessButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ContactAccessButton"
        }
      ],
      "role": "symbol",
      "title": "ContactAccessButton",
      "type": "topic",
      "url": "/documentation/contactsui/contactaccessbutton"
    },
    "doc://com.apple.documentation/documentation/Contacts/CNAuthorizationStatus/limited": {
      "abstract": [
        {
          "text": "The app has access to a limited subset of contacts, chosen by the person using the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limited"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Contacts/CNAuthorizationStatus/limited",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNAuthorizationStatus.limited",
      "type": "topic",
      "url": "/documentation/Contacts/CNAuthorizationStatus/limited"
    },
    "doc://com.apple.documentation/documentation/Contacts/CNContactStore/authorizationStatus(for:)": {
      "abstract": [
        {
          "text": "Returns the current authorization status to access the contact data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "entityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNEntityType",
          "text": "CNEntityType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNAuthorizationStatus",
          "text": "CNAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Contacts/CNContactStore/authorizationStatus(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "authorizationStatus(for:)",
      "type": "topic",
      "url": "/documentation/Contacts/CNContactStore/authorizationStatus(for:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Contact-viewer",
      "identifiers": [
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController"
      ],
      "title": "Contact viewer"
    },
    {
      "anchor": "Contact-pickers",
      "identifiers": [
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController",
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker"
      ],
      "title": "Contact pickers"
    },
    {
      "anchor": "Contact-access",
      "identifiers": [
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/ContactAccessButton"
      ],
      "title": "Contact access"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Contact-viewer",
              "identifiers": [
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController"
              ],
              "title": "Contact viewer"
            },
            {
              "anchor": "Contact-pickers",
              "identifiers": [
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController",
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker"
              ],
              "title": "Contact pickers"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Contacts~1CNAuthorizationStatus~1limited/title",
          "value": "CNAuthorizationStatusLimited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Contacts~1CNAuthorizationStatus~1limited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNAuthorizationStatusLimited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/title",
          "value": "CNContactViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Contacts~1CNContactStore~1authorizationStatus(for:)/title",
          "value": "authorizationStatusForEntityType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Contacts~1CNContactStore~1authorizationStatus(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CNAuthorizationStatus",
              "text": "CNAuthorizationStatus"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatusForEntityType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CNEntityType",
              "text": "CNEntityType"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "entityType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/title",
          "value": "CNContactPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPicker/title",
          "value": "CNContactPicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPicker"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contactsui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contactsui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
