{
  "abstract": [
    {
      "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CoreMIDI",
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.2",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "4.2",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Core MIDI"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Core MIDI framework provides APIs to communicate with MIDI (Musical Instrument Digital Interface) devices, including hardware keyboards and synthesizers. Connect from an iOS device using the dock connector or a network. For more information about using the dock connector, see the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/programs/mfi/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Macros",
      "type": "topic",
      "url": "/documentation/coremidi/coremidi-macros"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2DeviceInfo"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2DeviceInfo"
        }
      ],
      "role": "symbol",
      "title": "MIDI2DeviceInfo",
      "type": "topic",
      "url": "/documentation/coremidi/midi2deviceinfo"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIDevice"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIDevice"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDevice",
      "type": "topic",
      "url": "/documentation/coremidi/midicidevice"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIDeviceManager"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIDeviceManager"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDeviceManager",
      "type": "topic",
      "url": "/documentation/coremidi/midicidevicemanager"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveredNode": {
      "abstract": [
        {
          "text": "A discovered MIDI-CI node that represents a MIDI source and destination that respond to capability inquiries.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIDiscoveredNode"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveredNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIDiscoveredNode"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDiscoveredNode",
      "type": "topic",
      "url": "/documentation/coremidi/midicidiscoverednode"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIProfile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPCIProfile"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPCIProfile"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPCIProfile",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpciprofile"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPEndpoint"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPEndpoint"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPEndpoint",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpendpoint"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPEndpointManager"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPEndpointManager"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPEndpointManager",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpendpointmanager"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlock"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlock"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPFunctionBlock",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpfunctionblock"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableEndpoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPMutableEndpoint"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPMutableEndpoint"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPMutableEndpoint",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpmutableendpoint"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableFunctionBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPMutableFunctionBlock"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableFunctionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPMutableFunctionBlock"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPMutableFunctionBlock",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpmutablefunctionblock"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Constants",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-constants"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Data Types",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-data-types"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Enumerations",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-enumerations"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Functions",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-functions"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Structures",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-structures"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributeManufacturerSpecific": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDINoteAttributeManufacturerSpecific"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributeManufacturerSpecific",
      "kind": "symbol",
      "role": "symbol",
      "title": "kMIDINoteAttributeManufacturerSpecific",
      "type": "topic",
      "url": "/documentation/coremidi/kmidinoteattributemanufacturerspecific"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributeNone": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDINoteAttributeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "kMIDINoteAttributeNone",
      "type": "topic",
      "url": "/documentation/coremidi/kmidinoteattributenone"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributePitch": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDINoteAttributePitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributePitch",
      "kind": "symbol",
      "role": "symbol",
      "title": "kMIDINoteAttributePitch",
      "type": "topic",
      "url": "/documentation/coremidi/kmidinoteattributepitch"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributeProfileSpecific": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDINoteAttributeProfileSpecific"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributeProfileSpecific",
      "kind": "symbol",
      "role": "symbol",
      "title": "kMIDINoteAttributeProfileSpecific",
      "type": "topic",
      "url": "/documentation/coremidi/kmidinoteattributeprofilespecific"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kmidiobjecttype_externalmask": {
      "abstract": [
        {
          "text": "A bit mask indicating that a device is external.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kmidiobjecttype_externalmask",
      "kind": "article",
      "role": "article",
      "title": "kMIDIObjectType_ExternalMask",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiobjecttype_externalmask"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth": {
      "abstract": [
        {
          "text": "Connect to Bluetooth Low Energy MIDI peripherals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Bluetooth",
      "type": "topic",
      "url": "/documentation/coremidi/midi-bluetooth"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry": {
      "abstract": [
        {
          "text": "Provide support for bidirectional discovery and configuration of devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Capability Inquiry",
      "type": "topic",
      "url": "/documentation/coremidi/midi-capability-inquiry"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers": {
      "abstract": [
        {
          "text": "Create driver plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Drivers",
      "type": "topic",
      "url": "/documentation/coremidi/midi-drivers"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages": {
      "abstract": [
        {
          "text": "Create and configure messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Messages",
      "type": "topic",
      "url": "/documentation/coremidi/midi-messages"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking": {
      "abstract": [
        {
          "text": "Create and manage devices connected over a local network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Networking",
      "type": "topic",
      "url": "/documentation/coremidi/midi-networking"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services": {
      "abstract": [
        {
          "text": "Communicate with hardware using Universal MIDI Packets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Services",
      "type": "topic",
      "url": "/documentation/coremidi/midi-services"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup": {
      "abstract": [
        {
          "text": "Configure the global MIDI system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI System Setup",
      "type": "topic",
      "url": "/documentation/coremidi/midi-system-setup"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection": {
      "abstract": [
        {
          "text": "Create play-through connections between sources and destinations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Thru Connection",
      "type": "topic",
      "url": "/documentation/coremidi/midi-thru-connection"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi_system_setup-deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi_system_setup-deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/coremidi/midi_system_setup-deprecated-symbols"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/programs/mfi/": {
      "identifier": "https://developer.apple.com/programs/mfi/",
      "title": "MFi Program",
      "titleInlineContent": [
        {
          "text": "MFi Program",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/programs/mfi/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Services",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry"
      ],
      "title": "Services"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
        "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/kmidiobjecttype_externalmask",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi_system_setup-deprecated-symbols"
      ],
      "title": "Articles"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceInfo",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDevice",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceManager",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveredNode",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIProfile",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpoint",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlock",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableEndpoint",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableFunctionBlock"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributeManufacturerSpecific",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributeNone",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributePitch",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoteAttributeProfileSpecific"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Services",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry"
              ],
              "title": "Services"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
                "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Articles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/kmidiobjecttype_externalmask",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi_system_setup-deprecated-symbols"
              ],
              "title": "Articles"
            },
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceInfo",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDevice",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceManager",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveredNode",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIProfile",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpoint",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlock",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableEndpoint",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableFunctionBlock"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlock/title",
          "value": "MIDIUMPFunctionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPMutableFunctionBlock/title",
          "value": "MIDIUMPMutableFunctionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPMutableFunctionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPMutableFunctionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPMutableFunctionBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPMutableFunctionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpointManager/title",
          "value": "MIDIUMPEndpointManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpointManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPEndpointManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpointManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPEndpointManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDevice/title",
          "value": "MIDICIDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceInfo/title",
          "value": "MIDI2DeviceInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2DeviceInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2DeviceInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpoint/title",
          "value": "MIDIUMPEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveredNode/title",
          "value": "MIDICIDiscoveredNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveredNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDiscoveredNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveredNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDiscoveredNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPMutableEndpoint/title",
          "value": "MIDIUMPMutableEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPMutableEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPMutableEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPMutableEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPMutableEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPCIProfile/title",
          "value": "MIDIUMPCIProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPCIProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPCIProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPCIProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPCIProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceManager/title",
          "value": "MIDICIDeviceManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
