{
  "abstract": [
    {
      "text": "Securely support custom camera devices in macOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CoreMediaIO",
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.7",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Core Media I/O"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the Core Media I/O framework to enable support for custom camera devices in macOS. Starting in macOS 12.3, the framework builds on ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SystemExtensions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to enable you to support custom devices while maintaining system privacy and security protections. The system prevents apps from loading extension code into their process to ensure that they can’t bypass macOS privacy protections or mask their identity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Apple recommends replacing legacy Device Abstraction Layer (DAL) plug-ins with Core Media I/O extensions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionClient": {
      "abstract": [
        {
          "text": "An object that represents a client of the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionClient"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionClient"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionClient",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionclient"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice": {
      "abstract": [
        {
          "text": "An object that represents a physical or virtual device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionDevice"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionDevice"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionDevice",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevice"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties": {
      "abstract": [
        {
          "text": "An object that defines the properties of a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionDeviceProperties"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionDeviceProperties"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionDeviceProperties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondeviceproperties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceSource": {
      "abstract": [
        {
          "text": "A protocol for objects that act as device sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionDeviceSource"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionDeviceSource"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionDeviceSource",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensiondevicesource"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionInfoDictionaryKey": {
      "abstract": [
        {
          "text": "A key that specifies the extension information dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionInfoDictionaryKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionInfoDictionaryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionInfoDictionaryKey"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionInfoDictionaryKey",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensioninfodictionarykey"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionMachServiceNameKey": {
      "abstract": [
        {
          "text": "A key that specifies the mach service name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionMachServiceNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionMachServiceNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionMachServiceNameKey"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionMachServiceNameKey",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionmachservicenamekey"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty": {
      "abstract": [
        {
          "text": "A structure that defines the properties that providers, devices, and streams support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionProperty"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionProperty",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproperty"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyAttributes": {
      "abstract": [
        {
          "text": "An object that describes the attributes of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyAttributes"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyAttributes"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionPropertyAttributes",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionpropertyattributes"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState": {
      "abstract": [
        {
          "text": "An object that describes the state of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyState"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyState"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionPropertyState",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionpropertystate"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProvider": {
      "abstract": [
        {
          "text": "An object that manages device connections for a provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionProvider"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionProvider"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionProvider",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionprovider"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderProperties": {
      "abstract": [
        {
          "text": "An object that manages the properties of an extension provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionProviderProperties"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionProviderProperties"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionProviderProperties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproviderproperties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource": {
      "abstract": [
        {
          "text": "A protocol for objects that act as provider sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionProviderSource"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionProviderSource"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionProviderSource",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionprovidersource"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream": {
      "abstract": [
        {
          "text": "An object that represents a stream of media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionStream"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionStream"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionStream",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionstream"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties": {
      "abstract": [
        {
          "text": "An object that describes the properties of an extension stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionStreamProperties"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionStreamProperties"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionStreamProperties",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionstreamproperties"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource": {
      "abstract": [
        {
          "text": "A protocol for objects that act as stream sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionStreamSource"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionStreamSource"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionStreamSource",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionstreamsource"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/creating-a-camera-extension-with-core-media-i-o": {
      "abstract": [
        {
          "text": "Build high-performance camera drivers that are secure and simple to deploy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/creating-a-camera-extension-with-core-media-i-o",
      "kind": "article",
      "role": "article",
      "title": "Creating a camera extension with Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio/creating-a-camera-extension-with-core-media-i-o"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins": {
      "abstract": [
        {
          "text": "API reference for legacy DAL plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Abstraction Layer (DAL) Plug-Ins",
      "type": "topic",
      "url": "/documentation/coremediaio/device-abstraction-layer-dal-plug-ins"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_BufferOverrun": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_BufferOverrun"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_BufferOverrun",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_BufferOverrun",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_bufferoverrun"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_ClientSyncDiscontinuity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_ClientSyncDiscontinuity"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_ClientSyncDiscontinuity",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_ClientSyncDiscontinuity",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_clientsyncdiscontinuity"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_CodecSettingsChanged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_CodecSettingsChanged"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_CodecSettingsChanged",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_CodecSettingsChanged",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_codecsettingschanged"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DataFormatChanged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_DataFormatChanged"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DataFormatChanged",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_DataFormatChanged",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_dataformatchanged"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DataWasDropped": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_DataWasDropped"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DataWasDropped",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_DataWasDropped",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_datawasdropped"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DataWasFlushed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_DataWasFlushed"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DataWasFlushed",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_DataWasFlushed",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_datawasflushed"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DiscontinuityInDTS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_DiscontinuityInDTS"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DiscontinuityInDTS",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_DiscontinuityInDTS",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_discontinuityindts"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DurationWasExtended": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_DurationWasExtended"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DurationWasExtended",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_DurationWasExtended",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_durationwasextended"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_MalformedData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_MalformedData"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_MalformedData",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_MalformedData",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_malformeddata"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_NoDataMarker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_NoDataMarker"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_NoDataMarker",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_NoDataMarker",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_nodatamarker"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_PacketError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_PacketError"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_PacketError",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_PacketError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_packeterror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_RelatedToDiscontinuity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_RelatedToDiscontinuity"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_RelatedToDiscontinuity",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_RelatedToDiscontinuity",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_relatedtodiscontinuity"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_SleepWakeCycle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_SleepWakeCycle"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_SleepWakeCycle",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_SleepWakeCycle",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_sleepwakecycle"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_StreamDiscontinuity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_StreamDiscontinuity"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_StreamDiscontinuity",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_StreamDiscontinuity",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_streamdiscontinuity"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_TimecodeDiscontinuity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_TimecodeDiscontinuity"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_TimecodeDiscontinuity",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_TimecodeDiscontinuity",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_timecodediscontinuity"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_TimingReferenceJumped": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_TimingReferenceJumped"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_TimingReferenceJumped",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_TimingReferenceJumped",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_timingreferencejumped"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_TrickPlay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_TrickPlay"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_TrickPlay",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_TrickPlay",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_trickplay"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_UnknownDiscontinuity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferDiscontinuityFlag_UnknownDiscontinuity"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_UnknownDiscontinuity",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferDiscontinuityFlag_UnknownDiscontinuity",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebufferdiscontinuityflag_unknowndiscontinuity"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_DeviceDidNotSync": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferNoDataEvent_DeviceDidNotSync"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_DeviceDidNotSync",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferNoDataEvent_DeviceDidNotSync",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebuffernodataevent_devicedidnotsync"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_DeviceInWrongMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferNoDataEvent_DeviceInWrongMode"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_DeviceInWrongMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferNoDataEvent_DeviceInWrongMode",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebuffernodataevent_deviceinwrongmode"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_NoMedia": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferNoDataEvent_NoMedia"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_NoMedia",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferNoDataEvent_NoMedia",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebuffernodataevent_nomedia"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_ProcessingError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferNoDataEvent_ProcessingError"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_ProcessingError",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferNoDataEvent_ProcessingError",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebuffernodataevent_processingerror"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_SleepWakeCycle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferNoDataEvent_SleepWakeCycle"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_SleepWakeCycle",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferNoDataEvent_SleepWakeCycle",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebuffernodataevent_sleepwakecycle"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_Unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferNoDataEvent_Unknown"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_Unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferNoDataEvent_Unknown",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebuffernodataevent_unknown"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDiscontinuities": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMIOSampleBufferNoDiscontinuities"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDiscontinuities",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMIOSampleBufferNoDiscontinuities",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiosamplebuffernodiscontinuities"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/overriding-the-default-usb-video-class-extension": {
      "abstract": [
        {
          "text": "Create a simple DriverKit extension to override the default driver-matching behavior for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/overriding-the-default-usb-video-class-extension",
      "kind": "article",
      "role": "article",
      "title": "Overriding the default USB video class extension",
      "type": "topic",
      "url": "/documentation/coremediaio/overriding-the-default-usb-video-class-extension"
    },
    "doc://com.apple.documentation/documentation/SystemExtensions": {
      "abstract": [
        {
          "text": "Install and manage user space code that extends the capabilities of macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SystemExtensions",
      "kind": "symbol",
      "role": "collection",
      "title": "System Extensions",
      "type": "topic",
      "url": "/documentation/SystemExtensions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Providers",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/creating-a-camera-extension-with-core-media-i-o",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/overriding-the-default-usb-video-class-extension",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProvider",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderProperties"
      ],
      "title": "Providers"
    },
    {
      "anchor": "Devices",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceSource",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties"
      ],
      "title": "Devices"
    },
    {
      "anchor": "Streams",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionClient"
      ],
      "title": "Streams"
    },
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyAttributes",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionInfoDictionaryKey",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionMachServiceNameKey"
      ],
      "title": "Properties"
    },
    {
      "anchor": "DAL-Plug-Ins",
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins"
      ],
      "title": "DAL Plug-Ins"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providers",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/creating-a-camera-extension-with-core-media-i-o",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/overriding-the-default-usb-video-class-extension",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProvider",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderSource",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProviderProperties"
              ],
              "title": "Providers"
            },
            {
              "anchor": "Devices",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDevice",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceSource",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionDeviceProperties"
              ],
              "title": "Devices"
            },
            {
              "anchor": "Streams",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamSource",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStreamProperties",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionClient"
              ],
              "title": "Streams"
            },
            {
              "anchor": "Properties",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyAttributes",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionInfoDictionaryKey",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionMachServiceNameKey"
              ],
              "title": "Properties"
            },
            {
              "anchor": "DAL-Plug-Ins",
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/device-abstraction-layer-dal-plug-ins"
              ],
              "title": "DAL Plug-Ins"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_BufferOverrun",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_ClientSyncDiscontinuity",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_CodecSettingsChanged",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DataFormatChanged",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DataWasDropped",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DataWasFlushed",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DiscontinuityInDTS",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_DurationWasExtended",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_MalformedData",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_NoDataMarker",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_PacketError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_RelatedToDiscontinuity",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_SleepWakeCycle",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_StreamDiscontinuity",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_TimecodeDiscontinuity",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_TimingReferenceJumped",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_TrickPlay",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferDiscontinuityFlag_UnknownDiscontinuity",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_DeviceDidNotSync",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_DeviceInWrongMode",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_NoMedia",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_ProcessingError",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_SleepWakeCycle",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDataEvent_Unknown",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOSampleBufferNoDiscontinuities"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource/title",
          "value": "CMIOExtensionStreamSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStreamSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStreamSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty/title",
          "value": "CMIOExtensionProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState/title",
          "value": "CMIOExtensionPropertyState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProvider/title",
          "value": "CMIOExtensionProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties/title",
          "value": "CMIOExtensionDeviceProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDeviceProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDeviceProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceSource/title",
          "value": "CMIOExtensionDeviceSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDeviceSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDeviceSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDeviceSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionMachServiceNameKey/title",
          "value": "CMIOExtensionMachServiceNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionMachServiceNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionMachServiceNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionClient/title",
          "value": "CMIOExtensionClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyAttributes/title",
          "value": "CMIOExtensionPropertyAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderProperties/title",
          "value": "CMIOExtensionProviderProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProviderProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProviderProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionInfoDictionaryKey/title",
          "value": "CMIOExtensionInfoDictionaryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionInfoDictionaryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionInfoDictionaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream/title",
          "value": "CMIOExtensionStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource/title",
          "value": "CMIOExtensionProviderSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProviderSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProviderSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProviderSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice/title",
          "value": "CMIOExtensionDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties/title",
          "value": "CMIOExtensionStreamProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStreamProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStreamProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStreamProperties"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
