{
  "abstract": [
    {
      "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CoreTelephony",
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.10",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Core Telephony"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the Core Telephony framework to obtain information about a user’s home cellular service provider. Carriers can use this information to write apps that provide services only for their own subscribers. You can also use this framework to obtain information about current cellular calls.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object gives you information about the user’s cellular service provider, such as whether it allows use of VoIP (Voice over Internet Protocol) on its network. A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCall",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object gives you information about a current call, including a unique identifier and state information such as dialing, incoming, connected, or disconnected.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "VoIP and cellular services through Core Telephony are unavailable for compatible iPad and iPhone apps running in visionOS. You can still use the APIs of this framework, but services don’t return carrier information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCall": {
      "abstract": [
        {
          "text": "An object used to identify a cellular call and determine its state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCall"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCall"
        }
      ],
      "role": "symbol",
      "title": "CTCall",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcall"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter": {
      "abstract": [
        {
          "text": "An object that provides a list of current cellular calls, and provides the ability to respond to state changes for calls.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCallCenter"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCallCenter"
        }
      ],
      "role": "symbol",
      "title": "CTCallCenter",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcallcenter"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier": {
      "abstract": [
        {
          "text": "Information about the user’s cellular service provider, such as its unique identifier and whether it allows VoIP calls on its network.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCarrier"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCarrier"
        }
      ],
      "role": "symbol",
      "title": "CTCarrier",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcarrier"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularData": {
      "abstract": [
        {
          "text": "An object indicating whether the app can access cellular data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCellularData"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularData"
        }
      ],
      "role": "symbol",
      "title": "CTCellularData",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellulardata"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning": {
      "abstract": [
        {
          "text": "An object you use to download and install a carrier eSIM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioning"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioning"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioning",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioning"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest": {
      "abstract": [
        {
          "text": "A request specifying an eSIM to download and install.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningRequest"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningRequest"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioningRequest",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioningrequest"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTError": {
      "abstract": [
        {
          "text": "A type representing a Core Telephony error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTError"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTError"
        }
      ],
      "role": "symbol",
      "title": "CTError",
      "type": "topic",
      "url": "/documentation/coretelephony/cterror"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriber": {
      "abstract": [
        {
          "text": "A cellular network subscriber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTSubscriber"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTSubscriber"
        }
      ],
      "role": "symbol",
      "title": "CTSubscriber",
      "type": "topic",
      "url": "/documentation/coretelephony/ctsubscriber"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberDelegate": {
      "abstract": [
        {
          "text": "A protocol to handle changes to subscriber information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTSubscriberDelegate"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTSubscriberDelegate"
        }
      ],
      "role": "symbol",
      "title": "CTSubscriberDelegate",
      "type": "topic",
      "url": "/documentation/coretelephony/ctsubscriberdelegate"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberInfo": {
      "abstract": [
        {
          "text": "An object that provides an array of cellular network subscribers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTSubscriberInfo"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTSubscriberInfo"
        }
      ],
      "role": "symbol",
      "title": "CTSubscriberInfo",
      "type": "topic",
      "url": "/documentation/coretelephony/ctsubscriberinfo"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo": {
      "abstract": [
        {
          "text": "An object that provides notifications of changes to the user’s cellular service provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTelephonyNetworkInfo"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTelephonyNetworkInfo"
        }
      ],
      "role": "symbol",
      "title": "CTTelephonyNetworkInfo",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/coretelephony-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/coretelephony-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Telephony Macros",
      "type": "topic",
      "url": "/documentation/coretelephony/coretelephony-macros"
    },
    "doc://com.apple.documentation/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/CallKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Service-Information",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo"
      ],
      "title": "Service Information"
    },
    {
      "abstract": [
        {
          "text": "Carrier apps use the classes in this group to provision cellular plan eSIMs on supported devices.",
          "type": "text"
        }
      ],
      "anchor": "eSIM",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest"
      ],
      "title": "eSIM"
    },
    {
      "anchor": "Subscriber-Information",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriber",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberDelegate",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberInfo"
      ],
      "title": "Subscriber Information"
    },
    {
      "anchor": "Cellular-Data-Access",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularData"
      ],
      "title": "Cellular Data Access"
    },
    {
      "abstract": [
        {
          "text": "Getting call information in Core Telephony is no longer supported. Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/CallKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "anchor": "Call-Information",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCall",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter"
      ],
      "title": "Call Information"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTError"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Service-Information",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo"
              ],
              "title": "Service Information"
            },
            {
              "abstract": [
                {
                  "text": "Carrier apps use the classes in this group to provision cellular plan eSIMs on supported devices.",
                  "type": "text"
                }
              ],
              "anchor": "eSIM",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest"
              ],
              "title": "eSIM"
            },
            {
              "anchor": "Subscriber-Information",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriber",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberDelegate",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberInfo"
              ],
              "title": "Subscriber Information"
            },
            {
              "anchor": "Cellular-Data-Access",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularData"
              ],
              "title": "Cellular Data Access"
            },
            {
              "abstract": [
                {
                  "text": "Getting call information in Core Telephony is no longer supported. Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CallKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "anchor": "Call-Information",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCall",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallCenter"
              ],
              "title": "Call Information"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTError"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/coretelephony-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/title",
          "value": "CTTelephonyNetworkInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCall/title",
          "value": "CTCall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCall/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCarrier/title",
          "value": "CTCarrier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCarrier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCarrier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCarrier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCarrier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning/title",
          "value": "CTCellularPlanProvisioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallCenter/title",
          "value": "CTCallCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCallCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCallCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTError/title",
          "value": "CTError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberDelegate/title",
          "value": "CTSubscriberDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularData/title",
          "value": "CTCellularData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningRequest/title",
          "value": "CTCellularPlanProvisioningRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberInfo/title",
          "value": "CTSubscriberInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriberInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriberInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriber/title",
          "value": "CTSubscriber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
