{
  "abstract": [
    {
      "text": "Represent time-based audio-visual assets with essential data types.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CoreMedia",
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.7",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "6.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Core Media"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Core Media framework defines the media pipeline used by AVFoundation and other high-level media frameworks found on Apple platforms. Use Core Media’s low-level data types and interfaces to efficiently process media samples and manage queues of media data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType": {
      "abstract": [
        {
          "text": "The type of packing within each video frame, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "role": "symbol",
      "title": "CMPackingType",
      "type": "topic",
      "url": "/documentation/coremedia/cmpackingtype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType": {
      "abstract": [
        {
          "text": "Constants describing the projection surface information in a 3D video buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "role": "symbol",
      "title": "CMProjectionType",
      "type": "topic",
      "url": "/documentation/coremedia/cmprojectiontype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents": {
      "abstract": [
        {
          "text": "Constants describing the stereo views contained within a buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewComponents",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewcomponents"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions": {
      "abstract": [
        {
          "text": "Create a set of stereo view interpretation options from a constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewInterpretationOptions",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewinterpretationoptions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer": {
      "abstract": [
        {
          "text": "An instance of a media buffer containing metadata tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTaggedBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTaggedBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMTaggedBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers, with an associated Swift type for its value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "role": "symbol",
      "title": "CMTypedTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtypedtag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_INLINE"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_INLINE",
      "type": "topic",
      "url": "/documentation/coremedia/cm_inline"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_SWIFT_NONSENDABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_SWIFT_NONSENDABLE"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_SWIFT_NONSENDABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_SWIFT_NONSENDABLE",
      "type": "topic",
      "url": "/documentation/coremedia/cm_swift_nonsendable"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_SWIFT_SENDABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_SWIFT_SENDABLE"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_SWIFT_SENDABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_SWIFT_SENDABLE",
      "type": "topic",
      "url": "/documentation/coremedia/cm_swift_sendable"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmattachment-api": {
      "abstract": [
        {
          "text": "Add supporting metadata to sample buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmattachment-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMAttachment APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmattachment-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmaudioclock-api": {
      "abstract": [
        {
          "text": "A specialized reference clock that synchronizes with audio sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmaudioclock-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMAudioClock APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudioclock-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api": {
      "abstract": [
        {
          "text": "An object the system uses to move blocks of memory through a processing system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMBlockBuffer APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffer-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmbufferqueue-api": {
      "abstract": [
        {
          "text": "A queue of timed buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmbufferqueue-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMBufferQueue APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-api": {
      "abstract": [
        {
          "text": "A reference clock you use to synchronize applications and devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMClock APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmclock-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmemorypool-api": {
      "abstract": [
        {
          "text": "An object that optimizes memory allocation when working with large blocks of memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmemorypool-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMemoryPool APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmemorypool-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api": {
      "abstract": [
        {
          "text": "An object that contains zero or more media samples of a uniform media type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSampleBuffer APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsimplequeue-api": {
      "abstract": [
        {
          "text": "A simple, lockless FIFO queue of elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsimplequeue-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSimpleQueue APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmsimplequeue-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api": {
      "abstract": [
        {
          "text": "Types and interfaces for working with Core Media tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTag APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection": {
      "abstract": [
        {
          "text": "Objective-C types and interfaces for working with Core Media tag collections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTagCollection APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtaggedbuffergroup": {
      "abstract": [
        {
          "text": "Objective-C types and interfaces for working with Core Media tagged buffer groups.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtaggedbuffergroup",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTaggedBufferGroup APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroup"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtextmarkup": {
      "abstract": [
        {
          "text": "Attributes that specify text markup in legible media.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtextmarkup",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTextMarkup",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextmarkup"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api": {
      "abstract": [
        {
          "text": "A structure that represents time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTime APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-api": {
      "abstract": [
        {
          "text": "A model of a timeline under application control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTimebase APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtimemapping-api": {
      "abstract": [
        {
          "text": "A structure that maps a segment of a source time range to a target time range.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtimemapping-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTimeMapping APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemapping-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-api": {
      "abstract": [
        {
          "text": "A structure that represents a range of time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTimeRange APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Constants",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Functions",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-functions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Macros",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-macros"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Type Aliases",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-type-aliases"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_Equirectangular": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionProjectionKind_Equirectangular"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_Equirectangular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionProjectionKind_Equirectangular"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionProjectionKind_Equirectangular",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionprojectionkind_equirectangular"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_HalfEquirectangular": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionProjectionKind_HalfEquirectangular"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_HalfEquirectangular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionProjectionKind_HalfEquirectangular"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionProjectionKind_HalfEquirectangular",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionprojectionkind_halfequirectangular"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Sample-Processing",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtaggedbuffergroup",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmattachment-api"
      ],
      "title": "Sample Processing"
    },
    {
      "anchor": "Time-Representation",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtimemapping-api"
      ],
      "title": "Time Representation"
    },
    {
      "anchor": "Media-Synchronization",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmaudioclock-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-api"
      ],
      "title": "Media Synchronization"
    },
    {
      "anchor": "Text-Markup",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtextmarkup"
      ],
      "title": "Text Markup"
    },
    {
      "anchor": "Metadata",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
      ],
      "title": "Metadata"
    },
    {
      "anchor": "Queues",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsimplequeue-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmbufferqueue-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmemorypool-api"
      ],
      "title": "Queues"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions",
        "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_Equirectangular",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_HalfEquirectangular"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Sample-Processing",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtaggedbuffergroup",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmattachment-api"
              ],
              "title": "Sample Processing"
            },
            {
              "anchor": "Time-Representation",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtimemapping-api"
              ],
              "title": "Time Representation"
            },
            {
              "anchor": "Media-Synchronization",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmaudioclock-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-api"
              ],
              "title": "Media Synchronization"
            },
            {
              "anchor": "Text-Markup",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtextmarkup"
              ],
              "title": "Text Markup"
            },
            {
              "anchor": "Metadata",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
              ],
              "title": "Metadata"
            },
            {
              "anchor": "Queues",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmsimplequeue-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmbufferqueue-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmmemorypool-api"
              ],
              "title": "Queues"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions",
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases",
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_Equirectangular",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_HalfEquirectangular"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_INLINE",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_SWIFT_NONSENDABLE",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_SWIFT_SENDABLE"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/title",
          "value": "CMProjectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionProjectionKind_Equirectangular/title",
          "value": "kCMFormatDescriptionProjectionKind_Equirectangular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionProjectionKind_Equirectangular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionProjectionKind_Equirectangular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionProjectionKind_HalfEquirectangular/title",
          "value": "kCMFormatDescriptionProjectionKind_HalfEquirectangular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionProjectionKind_HalfEquirectangular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionProjectionKind_HalfEquirectangular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/title",
          "value": "CMPackingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/title",
          "value": "CMStereoViewComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/title",
          "value": "CMStereoViewInterpretationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
