{
  "abstract": [
    {
      "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CoreVideo",
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.4",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Core Video"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Video provides a pipeline model for digital video. It simplifies working with video by partitioning the process into discrete steps. This makes it easier for developers to access and manipulate individual frames without having to worry about translating between data types or display synchronization issues. Apps that don’t need to manipulate individual video frames don’t need to use Core Video directly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBuffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalBuffer"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVMetalBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetalbuffer"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalBufferCache"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalBufferCache"
        }
      ],
      "role": "symbol",
      "title": "CVMetalBufferCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetalbuffercache"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheCreate(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalBufferCacheCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalBufferCacheRef",
          "text": "CVMetalBufferCache"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheCreate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalBufferCacheCreate"
        }
      ],
      "role": "symbol",
      "title": "CVMetalBufferCacheCreate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetalbuffercachecreate(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheCreateBufferFromImage(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalBufferCacheCreateBufferFromImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalBufferCacheRef",
          "text": "CVMetalBufferCache"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalBufferRef",
          "text": "CVMetalBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVReturn",
          "text": "CVReturn"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheCreateBufferFromImage(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalBufferCacheCreateBufferFromImage"
        }
      ],
      "role": "symbol",
      "title": "CVMetalBufferCacheCreateBufferFromImage(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetalbuffercachecreatebufferfromimage(_:_:_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheFlush(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalBufferCacheFlush"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalBufferCacheRef",
          "text": "CVMetalBufferCache"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVOptionFlags",
          "text": "CVOptionFlags"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheFlush(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalBufferCacheFlush"
        }
      ],
      "role": "symbol",
      "title": "CVMetalBufferCacheFlush(_:_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetalbuffercacheflush(_:_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheGetTypeID()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalBufferCacheGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalBufferCacheGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVMetalBufferCacheGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetalbuffercachegettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferGetBuffer(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalBufferGetBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVMetalBufferRef",
          "text": "CVMetalBuffer"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferGetBuffer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalBufferGetBuffer"
        }
      ],
      "role": "symbol",
      "title": "CVMetalBufferGetBuffer(_:)",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetalbuffergetbuffer(_:)"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferGetTypeID()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVMetalBufferGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVMetalBufferGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CVMetalBufferGetTypeID()",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetalbuffergettypeid()"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-q2r": {
      "abstract": [
        {
          "text": "A cache used to create and manage OpenGL ES texture objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-q2r",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLESTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexturecache-q2r"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o": {
      "abstract": [
        {
          "text": "A utility object for managing a recyclable set of pixel buffer objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbufferpool-77o"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CV_SWIFT_NONSENDABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CV_SWIFT_NONSENDABLE"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CV_SWIFT_NONSENDABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CV_SWIFT_NONSENDABLE",
      "type": "topic",
      "url": "/documentation/corevideo/cv_swift_nonsendable"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CV_SWIFT_SENDABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CV_SWIFT_SENDABLE"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CV_SWIFT_SENDABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CV_SWIFT_SENDABLE",
      "type": "topic",
      "url": "/documentation/corevideo/cv_swift_sendable"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Constants",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-constants"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Enumerations",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-enumerations"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Functions",
      "type": "topic",
      "url": "/documentation/corevideo/core-video-functions"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm": {
      "abstract": [
        {
          "text": "An abstract base class that defines how to interact with data buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvbuffer-nfm"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k": {
      "abstract": [
        {
          "text": "A high-priority thread that notifies your app when a given display will need each frame.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVDisplayLink",
      "type": "topic",
      "url": "/documentation/corevideo/cvdisplaylink-k0k"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40": {
      "abstract": [
        {
          "text": "An interface for managing different types of image data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvimagebuffer-q40"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexture-q3g": {
      "abstract": [
        {
          "text": "A texture-based image buffer that supplies source image data for use with the Metal framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexture-q3g",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVMetalTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexture-q3g"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j": {
      "abstract": [
        {
          "text": "A cache used to create and manage Metal texture objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVMetalTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvmetaltexturecache-q3j"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s": {
      "abstract": [
        {
          "text": "An image buffer used to store image data in video memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbuffer-77s"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j": {
      "abstract": [
        {
          "text": "A utility object for managing a set of recyclable OpenGL buffer objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLBufferPool",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglbufferpool-77j"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglestexture-q2s": {
      "abstract": [
        {
          "text": "A texture-based image buffer that supplies source image data to OpenGL ES.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglestexture-q2s",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLESTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvopenglestexture-q2s"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782": {
      "abstract": [
        {
          "text": "A texture-based image buffer that supplies source image data to OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLTexture",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexture-782"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780": {
      "abstract": [
        {
          "text": "A cache used to create and manage OpenGL texture objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVOpenGLTextureCache",
      "type": "topic",
      "url": "/documentation/corevideo/cvopengltexturecache-780"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e": {
      "abstract": [
        {
          "text": "An image buffer that holds pixels in main memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelBuffer",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelbuffer-q2e"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription": {
      "abstract": [
        {
          "text": "An API that provides functions and types for defining custom pixel formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVPixelFormatDescription",
      "type": "topic",
      "url": "/documentation/corevideo/cvpixelformatdescription"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-q1e": {
      "abstract": [
        {
          "text": "A structure used for storing Core Video time values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-q1e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CVTime",
      "type": "topic",
      "url": "/documentation/corevideo/cvtime-q1e"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/data-types": {
      "abstract": [
        {
          "text": "Common data types used by the Core Video framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Types",
      "type": "topic",
      "url": "/documentation/corevideo/data-types"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPostDecodeProcessingFrameMetadataKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferPostDecodeProcessingFrameMetadataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPostDecodeProcessingFrameMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferPostDecodeProcessingFrameMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferPostDecodeProcessingFrameMetadataKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferpostdecodeprocessingframemetadatakey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPostDecodeProcessingSequenceMetadataKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferPostDecodeProcessingSequenceMetadataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPostDecodeProcessingSequenceMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferPostDecodeProcessingSequenceMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferPostDecodeProcessingSequenceMetadataKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebufferpostdecodeprocessingsequencemetadatakey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferSceneIlluminationKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVImageBufferSceneIlluminationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferSceneIlluminationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVImageBufferSceneIlluminationKey"
        }
      ],
      "role": "symbol",
      "title": "kCVImageBufferSceneIlluminationKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvimagebuffersceneilluminationkey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVMetalBufferCacheMaximumBufferAgeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVMetalBufferCacheMaximumBufferAgeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVMetalBufferCacheMaximumBufferAgeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVMetalBufferCacheMaximumBufferAgeKey"
        }
      ],
      "role": "symbol",
      "title": "kCVMetalBufferCacheMaximumBufferAgeKey",
      "type": "topic",
      "url": "/documentation/corevideo/kcvmetalbuffercachemaximumbufferagekey"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerComponent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBitsPerComponent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatBitsPerComponent"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatBitsPerComponent",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformatbitspercomponent"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_30RGB_r210": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_30RGB_r210"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_30RGB_r210",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_30RGB_r210"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_30RGB_r210",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_30rgb_r210"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_lossless_420ypcbcr10packedbiplanarfullrange"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_64RGBAHalf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_64RGBAHalf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_64RGBAHalf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_Lossless_64RGBAHalf"
        }
      ],
      "role": "symbol",
      "title": "kCVPixelFormatType_Lossless_64RGBAHalf",
      "type": "topic",
      "url": "/documentation/corevideo/kcvpixelformattype_lossless_64rgbahalf"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/result-codes": {
      "abstract": [
        {
          "text": "Describes the result codes generated by Core Video operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/result-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Result Codes",
      "type": "topic",
      "url": "/documentation/corevideo/result-codes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Data-Processing",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
      ],
      "title": "Data Processing"
    },
    {
      "anchor": "Time-Management",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-q1e",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k"
      ],
      "title": "Time Management"
    },
    {
      "anchor": "Metal",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexture-q3g"
      ],
      "title": "Metal"
    },
    {
      "anchor": "OpenGL",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j"
      ],
      "title": "OpenGL"
    },
    {
      "anchor": "OpenGL-ES",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-q2r",
        "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglestexture-q2s"
      ],
      "title": "OpenGL ES"
    },
    {
      "anchor": "Core-Video-Error-Constants",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/result-codes",
        "doc://com.apple.corevideo/documentation/CoreVideo/data-types"
      ],
      "title": "Core Video Error Constants"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations",
        "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
        "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCache"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPostDecodeProcessingFrameMetadataKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPostDecodeProcessingSequenceMetadataKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferSceneIlluminationKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVMetalBufferCacheMaximumBufferAgeKey",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerComponent",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_30RGB_r210",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange",
        "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_64RGBAHalf"
      ],
      "title": "Variables"
    },
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheCreate(_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheCreateBufferFromImage(_:_:_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheFlush(_:_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheGetTypeID()",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferGetBuffer(_:)",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferGetTypeID()"
      ],
      "title": "Functions"
    },
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBuffer"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Processing",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvbuffer-nfm",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvimagebuffer-q40",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelbuffer-q2e",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPixelBufferPool-77o",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvpixelformatdescription"
              ],
              "title": "Data Processing"
            },
            {
              "anchor": "Time-Management",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvtime-q1e",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvdisplaylink-k0k"
              ],
              "title": "Time Management"
            },
            {
              "anchor": "Metal",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexturecache-q3j",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvmetaltexture-q3g"
              ],
              "title": "Metal"
            },
            {
              "anchor": "OpenGL",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexturecache-780",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopengltexture-782",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbuffer-77s",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglbufferpool-77j"
              ],
              "title": "OpenGL"
            },
            {
              "anchor": "OpenGL-ES",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVOpenGLESTextureCache-q2r",
                "doc://com.apple.corevideo/documentation/CoreVideo/cvopenglestexture-q2s"
              ],
              "title": "OpenGL ES"
            },
            {
              "anchor": "Core-Video-Error-Constants",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/result-codes",
                "doc://com.apple.corevideo/documentation/CoreVideo/data-types"
              ],
              "title": "Core Video Error Constants"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/core-video-enumerations",
                "doc://com.apple.corevideo/documentation/CoreVideo/core-video-constants",
                "doc://com.apple.corevideo/documentation/CoreVideo/core-video-functions"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPostDecodeProcessingFrameMetadataKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferPostDecodeProcessingSequenceMetadataKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVImageBufferSceneIlluminationKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVMetalBufferCacheMaximumBufferAgeKey",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatBitsPerComponent"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheCreate(_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheCreateBufferFromImage(_:_:_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheFlush(_:_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCacheGetTypeID()",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferGetBuffer(_:)",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferGetTypeID()"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CV_SWIFT_NONSENDABLE",
                "doc://com.apple.corevideo/documentation/CoreVideo/CV_SWIFT_SENDABLE"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_30RGB_r210",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange",
                "doc://com.apple.corevideo/documentation/CoreVideo/kCVPixelFormatType_Lossless_64RGBAHalf"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Type-Aliases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBuffer",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVMetalBufferCache"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_64RGBAHalf/title",
          "value": "kCVPixelFormatType_Lossless_64RGBAHalf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_64RGBAHalf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_Lossless_64RGBAHalf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBuffer/title",
          "value": "CVMetalBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferGetTypeID()/title",
          "value": "CVMetalBufferGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalBufferGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferCache/title",
          "value": "CVMetalBufferCacheRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalBufferCacheRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferCache/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalBufferCacheRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVMetalBufferCacheMaximumBufferAgeKey/title",
          "value": "kCVMetalBufferCacheMaximumBufferAgeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVMetalBufferCacheMaximumBufferAgeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVMetalBufferCacheMaximumBufferAgeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBitsPerComponent/title",
          "value": "kCVPixelFormatBitsPerComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatBitsPerComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatBitsPerComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_30RGB_r210/title",
          "value": "kCVPixelFormatType_30RGB_r210"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_30RGB_r210/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_30RGB_r210"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferGetBuffer(_:)/title",
          "value": "CVMetalBufferGetBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferGetBuffer(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalBufferGetBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferCacheGetTypeID()/title",
          "value": "CVMetalBufferCacheGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferCacheGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalBufferCacheGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferCacheCreateBufferFromImage(_:_:_:_:)/title",
          "value": "CVMetalBufferCacheCreateBufferFromImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferCacheCreateBufferFromImage(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalBufferCacheCreateBufferFromImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferCacheFlush(_:_:)/title",
          "value": "CVMetalBufferCacheFlush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferCacheFlush(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalBufferCacheFlush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferCacheCreate(_:_:_:_:)/title",
          "value": "CVMetalBufferCacheCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVMetalBufferCacheCreate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVMetalBufferCacheCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPostDecodeProcessingSequenceMetadataKey/title",
          "value": "kCVImageBufferPostDecodeProcessingSequenceMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPostDecodeProcessingSequenceMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferPostDecodeProcessingSequenceMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferSceneIlluminationKey/title",
          "value": "kCVImageBufferSceneIlluminationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferSceneIlluminationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferSceneIlluminationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange/title",
          "value": "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPostDecodeProcessingFrameMetadataKey/title",
          "value": "kCVImageBufferPostDecodeProcessingFrameMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1kCVImageBufferPostDecodeProcessingFrameMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVImageBufferPostDecodeProcessingFrameMetadataKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
