{
  "abstract": [
    {
      "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CoreData",
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.4",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Core Data"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use Core Data to save your application’s permanent data for offline use, to cache temporary data, and to add undo functionality to your app on a single device. To sync data across multiple devices in a single iCloud account, Core Data automatically mirrors your schema to a CloudKit container.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Through Core Data’s Data Model editor, you define your data’s types and relationships, and generate respective class definitions. Core Data can then manage object instances at runtime to provide the following features.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Persistence",
          "level": 3,
          "text": "Persistence",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Data abstracts the details of mapping your objects to a store, making it easy to save data from Swift and Objective-C without administering a database directly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3119932",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Undo-and-redo-of-individual-and-batched-changes",
          "level": 3,
          "text": "Undo and redo of individual and batched changes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Data’s undo manager tracks changes and can roll them back individually, in groups, or all at once, making it easy to add undo and redo support to your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3118362",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Background-data-tasks",
          "level": 3,
          "text": "Background data tasks",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Perform potentially UI-blocking data tasks, like parsing JSON into objects, in the background. You can then cache or store the results to reduce server roundtrips.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3118359",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "View-synchronization",
          "level": 3,
          "text": "View synchronization",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Data also helps keep your views and data synchronized by providing data sources for table and collection views.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Versioning-and-migration",
          "level": 3,
          "text": "Versioning and migration",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Data includes mechanisms for versioning your data model and migrating user data as your app evolves.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/CoreData-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/CoreData-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/coredata/coredata-macros"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAsynchronousFetchRequest": {
      "abstract": [
        {
          "text": "A fetch request that retrieves results asynchronously and supports progress notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAsynchronousFetchRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAsynchronousFetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAsynchronousFetchRequest"
        }
      ],
      "role": "symbol",
      "title": "NSAsynchronousFetchRequest",
      "type": "topic",
      "url": "/documentation/coredata/nsasynchronousfetchrequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAsynchronousFetchResult": {
      "abstract": [
        {
          "text": "A fetch result object that encompasses the response from an executed asynchronous fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAsynchronousFetchResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAsynchronousFetchResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAsynchronousFetchResult"
        }
      ],
      "role": "symbol",
      "title": "NSAsynchronousFetchResult",
      "type": "topic",
      "url": "/documentation/coredata/nsasynchronousfetchresult"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest": {
      "abstract": [
        {
          "text": "A description of search criteria used to retrieve data from a persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFetchRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFetchRequest"
        }
      ],
      "role": "symbol",
      "title": "NSFetchRequest",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchedResultsController": {
      "abstract": [
        {
          "text": "A controller that you use to manage the results of a Core Data fetch request and to display data to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFetchedResultsController"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchedResultsController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFetchedResultsController"
        }
      ],
      "role": "symbol",
      "title": "NSFetchedResultsController",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchedresultscontroller"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer": {
      "abstract": [
        {
          "text": "A container that encapsulates the Core Data stack in your app, and mirrors select persistent stores to a CloudKit private database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainer"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainer"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentCloudKitContainer",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainer"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerOptions": {
      "abstract": [
        {
          "text": "An object that customizes how a store description aligns with a CloudKit database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainerOptions"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainerOptions"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentCloudKitContainerOptions",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontaineroptions"
    },
    "doc://com.apple.coredata/documentation/CoreData/accessing-data-when-the-store-changes": {
      "abstract": [
        {
          "text": "Guarantee that a context won’t see store changes until you tell it to look.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/accessing-data-when-the-store-changes",
      "kind": "article",
      "role": "article",
      "title": "Accessing data when the store changes",
      "type": "topic",
      "url": "/documentation/coredata/accessing-data-when-the-store-changes"
    },
    "doc://com.apple.coredata/documentation/CoreData/adopting-swiftdata-for-a-core-data-app": {
      "abstract": [
        {
          "text": "Persist data in your app intuitively with the Swift native persistence framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/adopting-swiftdata-for-a-core-data-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adopting SwiftData for a Core Data app",
      "type": "topic",
      "url": "/documentation/coredata/adopting-swiftdata-for-a-core-data-app"
    },
    "doc://com.apple.coredata/documentation/CoreData/batch-processing": {
      "abstract": [
        {
          "text": "Use batch processes to manage large data changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/batch-processing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Batch processing",
      "type": "topic",
      "url": "/documentation/coredata/batch-processing"
    },
    "doc://com.apple.coredata/documentation/CoreData/conflict-resolution": {
      "abstract": [
        {
          "text": "Detect and resolve conflicts that occur when data is changed on multiple threads.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/conflict-resolution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Conflict resolution",
      "type": "topic",
      "url": "/documentation/coredata/conflict-resolution"
    },
    "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes": {
      "abstract": [
        {
          "text": "Filter store transactions for changes relevant to the current view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes",
      "kind": "article",
      "role": "article",
      "title": "Consuming relevant store changes",
      "type": "topic",
      "url": "/documentation/coredata/consuming-relevant-store-changes"
    },
    "doc://com.apple.coredata/documentation/CoreData/core-data-constants": {
      "abstract": [
        {
          "text": "Keys to use with persistent stores and notifications from Core Data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/core-data-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Data Constants",
      "type": "topic",
      "url": "/documentation/coredata/core-data-constants"
    },
    "doc://com.apple.coredata/documentation/CoreData/core-data-model": {
      "abstract": [
        {
          "text": "Describe your app’s object structure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/core-data-model",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Data model",
      "type": "topic",
      "url": "/documentation/coredata/core-data-model"
    },
    "doc://com.apple.coredata/documentation/CoreData/core-data-stack": {
      "abstract": [
        {
          "text": "Manage and persist your app’s model layer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Data stack",
      "type": "topic",
      "url": "/documentation/coredata/core-data-stack"
    },
    "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model": {
      "abstract": [
        {
          "text": "Define your app’s object structure with a data model file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model",
      "kind": "article",
      "role": "article",
      "title": "Creating a Core Data model",
      "type": "topic",
      "url": "/documentation/coredata/creating-a-core-data-model"
    },
    "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data": {
      "abstract": [
        {
          "text": "Create, store, and present records for a variety of data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data",
      "kind": "article",
      "role": "sampleCode",
      "title": "Handling Different Data Types in Core Data",
      "type": "topic",
      "url": "/documentation/coredata/handling-different-data-types-in-core-data"
    },
    "doc://com.apple.coredata/documentation/CoreData/linking-data-between-two-core-data-stores": {
      "abstract": [
        {
          "text": "Organize data in two different stores and implement a link between them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/linking-data-between-two-core-data-stores",
      "kind": "article",
      "role": "sampleCode",
      "title": "Linking Data Between Two Core Data Stores",
      "type": "topic",
      "url": "/documentation/coredata/linking-data-between-two-core-data-stores"
    },
    "doc://com.apple.coredata/documentation/CoreData/manual-migrations": {
      "abstract": [
        {
          "text": "Migrate elaborate data models with changes that go beyond the capabilities of both lightweight and staged migrations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/manual-migrations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Manual migrations",
      "type": "topic",
      "url": "/documentation/coredata/manual-migrations"
    },
    "doc://com.apple.coredata/documentation/CoreData/migrating-your-data-model-automatically": {
      "abstract": [
        {
          "text": "Enable lightweight migrations to keep your data model and the underlying data in a consistent state.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/migrating-your-data-model-automatically",
      "kind": "article",
      "role": "article",
      "title": "Migrating your data model automatically",
      "type": "topic",
      "url": "/documentation/coredata/migrating-your-data-model-automatically"
    },
    "doc://com.apple.coredata/documentation/CoreData/mirroring-a-core-data-store-with-cloudkit": {
      "abstract": [
        {
          "text": "Back user interfaces with a local replica of a CloudKit private database.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/mirroring-a-core-data-store-with-cloudkit",
      "kind": "article",
      "role": "article",
      "title": "Mirroring a Core Data store with CloudKit",
      "type": "topic",
      "url": "/documentation/coredata/mirroring-a-core-data-store-with-cloudkit"
    },
    "doc://com.apple.coredata/documentation/CoreData/modeling-data": {
      "abstract": [
        {
          "text": "Configure the data model file to contain your app’s object graph.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/modeling-data",
      "kind": "article",
      "role": "article",
      "title": "Modeling data",
      "type": "topic",
      "url": "/documentation/coredata/modeling-data"
    },
    "doc://com.apple.coredata/documentation/CoreData/persistent-history": {
      "abstract": [
        {
          "text": "Use persistent history tracking to determine what changes have occurred in the store since the enabling of persistent history tracking.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/persistent-history",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Persistent history",
      "type": "topic",
      "url": "/documentation/coredata/persistent-history"
    },
    "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack": {
      "abstract": [
        {
          "text": "Set up the classes that manage and persist your app’s objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack",
      "kind": "article",
      "role": "article",
      "title": "Setting up a Core Data stack",
      "type": "topic",
      "url": "/documentation/coredata/setting-up-a-core-data-stack"
    },
    "doc://com.apple.coredata/documentation/CoreData/sharing-core-data-objects-between-icloud-users": {
      "abstract": [
        {
          "text": "Use Core Data and CloudKit to synchronize data between devices of an iCloud user and share data between different iCloud users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/sharing-core-data-objects-between-icloud-users",
      "kind": "article",
      "role": "sampleCode",
      "title": "Sharing Core Data objects between iCloud users",
      "type": "topic",
      "url": "/documentation/coredata/sharing-core-data-objects-between-icloud-users"
    },
    "doc://com.apple.coredata/documentation/CoreData/staged-migrations": {
      "abstract": [
        {
          "text": "Migrate complex data models containing changes that are incompatible with lightweight migrations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/staged-migrations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Staged migrations",
      "type": "topic",
      "url": "/documentation/coredata/staged-migrations"
    },
    "doc://com.apple.coredata/documentation/CoreData/synchronizing-a-local-store-to-the-cloud": {
      "abstract": [
        {
          "text": "Share data between a user’s devices and other iCloud users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/synchronizing-a-local-store-to-the-cloud",
      "kind": "article",
      "role": "sampleCode",
      "title": "Synchronizing a local store to the cloud",
      "type": "topic",
      "url": "/documentation/coredata/synchronizing-a-local-store-to-the-cloud"
    },
    "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background": {
      "abstract": [
        {
          "text": "Use Core Data in both a single-threaded and multithreaded app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background",
      "kind": "article",
      "role": "article",
      "title": "Using Core Data in the background",
      "type": "topic",
      "url": "/documentation/coredata/using-core-data-in-the-background"
    },
    "doc://com.apple.documentation/documentation/swiftui/loading_and_displaying_a_large_data_feed": {
      "abstract": [
        {
          "text": "Consume data in the background, and lower memory use by batching imports and preventing duplicate records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swiftui/loading_and_displaying_a_large_data_feed",
      "kind": "article",
      "role": "sampleCode",
      "title": "Loading and Displaying a Large Data Feed",
      "type": "topic",
      "url": "/documentation/swiftui/loading_and_displaying_a_large_data_feed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3118359": {
      "alt": "Flow diagram showing data from an endpoint populating objects in the background before updating the UI.",
      "identifier": "media-3118359",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d71b242e7299eb1f75bd78763df7278c/media-3118359@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8dc9a8c28c8e8b60083b52e0baea9457/media-3118359~dark@2x.png"
        }
      ]
    },
    "media-3118362": {
      "alt": "Figure showing a shake to undo gesture causing an element to be removed from a list.",
      "identifier": "media-3118362",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/640964de6db0e195490edb69b0d5aae8/media-3118362@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d1e4583b8e8db606f2858010a8d9089b/media-3118362~dark@2x.png"
        }
      ]
    },
    "media-3119932": {
      "alt": "Flow diagram showing an app saving data to and loading data from a persistent store.",
      "identifier": "media-3119932",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/75428f775be2ff5c6fe139221ff330d4/media-3119932@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/0592134f824c86be48ea930952f993eb/media-3119932~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model",
        "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack",
        "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
        "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data",
        "doc://com.apple.coredata/documentation/CoreData/linking-data-between-two-core-data-stores"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Data-modeling",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/modeling-data",
        "doc://com.apple.coredata/documentation/CoreData/core-data-model"
      ],
      "title": "Data modeling"
    },
    {
      "abstract": [
        {
          "text": "Core Data retrieves persisted data to be used by your app.",
          "type": "text"
        }
      ],
      "anchor": "Fetch-requests",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest",
        "doc://com.apple.coredata/documentation/CoreData/NSAsynchronousFetchRequest",
        "doc://com.apple.coredata/documentation/CoreData/NSAsynchronousFetchResult",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchedResultsController"
      ],
      "title": "Fetch requests"
    },
    {
      "anchor": "SwiftData-migration-and-coexistence",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/adopting-swiftdata-for-a-core-data-app"
      ],
      "title": "SwiftData migration and coexistence"
    },
    {
      "anchor": "CloudKit-mirroring",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/mirroring-a-core-data-store-with-cloudkit",
        "doc://com.apple.coredata/documentation/CoreData/synchronizing-a-local-store-to-the-cloud",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerOptions",
        "doc://com.apple.coredata/documentation/CoreData/sharing-core-data-objects-between-icloud-users"
      ],
      "title": "CloudKit mirroring"
    },
    {
      "anchor": "Change-processing",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/accessing-data-when-the-store-changes",
        "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes",
        "doc://com.apple.coredata/documentation/CoreData/persistent-history"
      ],
      "title": "Change processing"
    },
    {
      "anchor": "Background-tasks",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background",
        "doc://com.apple.documentation/documentation/swiftui/loading_and_displaying_a_large_data_feed",
        "doc://com.apple.coredata/documentation/CoreData/conflict-resolution",
        "doc://com.apple.coredata/documentation/CoreData/batch-processing"
      ],
      "title": "Background tasks"
    },
    {
      "abstract": [
        {
          "text": "Core Data has built-in data migration tools to help synchronize your app’s data with the current data model.",
          "type": "text"
        }
      ],
      "anchor": "Data-model-migration",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/migrating-your-data-model-automatically",
        "doc://com.apple.coredata/documentation/CoreData/staged-migrations",
        "doc://com.apple.coredata/documentation/CoreData/manual-migrations"
      ],
      "title": "Data model migration"
    },
    {
      "anchor": "Related-types",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/core-data-constants"
      ],
      "title": "Related types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model",
                "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack",
                "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
                "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data",
                "doc://com.apple.coredata/documentation/CoreData/linking-data-between-two-core-data-stores"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Data-modeling",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/modeling-data",
                "doc://com.apple.coredata/documentation/CoreData/core-data-model"
              ],
              "title": "Data modeling"
            },
            {
              "abstract": [
                {
                  "text": "Core Data retrieves persisted data to be used by your app.",
                  "type": "text"
                }
              ],
              "anchor": "Fetch-requests",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest",
                "doc://com.apple.coredata/documentation/CoreData/NSAsynchronousFetchRequest",
                "doc://com.apple.coredata/documentation/CoreData/NSAsynchronousFetchResult",
                "doc://com.apple.coredata/documentation/CoreData/NSFetchedResultsController"
              ],
              "title": "Fetch requests"
            },
            {
              "anchor": "SwiftData-migration-and-coexistence",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/adopting-swiftdata-for-a-core-data-app"
              ],
              "title": "SwiftData migration and coexistence"
            },
            {
              "anchor": "CloudKit-mirroring",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/mirroring-a-core-data-store-with-cloudkit",
                "doc://com.apple.coredata/documentation/CoreData/synchronizing-a-local-store-to-the-cloud",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerOptions",
                "doc://com.apple.coredata/documentation/CoreData/sharing-core-data-objects-between-icloud-users"
              ],
              "title": "CloudKit mirroring"
            },
            {
              "anchor": "Change-processing",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/accessing-data-when-the-store-changes",
                "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes",
                "doc://com.apple.coredata/documentation/CoreData/persistent-history"
              ],
              "title": "Change processing"
            },
            {
              "anchor": "Background-tasks",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background",
                "doc://com.apple.documentation/documentation/swiftui/loading_and_displaying_a_large_data_feed",
                "doc://com.apple.coredata/documentation/CoreData/conflict-resolution",
                "doc://com.apple.coredata/documentation/CoreData/batch-processing"
              ],
              "title": "Background tasks"
            },
            {
              "abstract": [
                {
                  "text": "Core Data has built-in data migration tools to help synchronize your app’s data with the current data model.",
                  "type": "text"
                }
              ],
              "anchor": "Data-model-migration",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/migrating-your-data-model-automatically",
                "doc://com.apple.coredata/documentation/CoreData/staged-migrations",
                "doc://com.apple.coredata/documentation/CoreData/manual-migrations"
              ],
              "title": "Data model migration"
            },
            {
              "anchor": "Related-types",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/core-data-constants"
              ],
              "title": "Related types"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/CoreData-macros"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer/title",
          "value": "NSPersistentCloudKitContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAsynchronousFetchRequest/title",
          "value": "NSAsynchronousFetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAsynchronousFetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAsynchronousFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAsynchronousFetchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAsynchronousFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchedResultsController/title",
          "value": "NSFetchedResultsController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchedResultsController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchedResultsController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchedResultsController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchedResultsController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerOptions/title",
          "value": "NSPersistentCloudKitContainerOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest/title",
          "value": "NSFetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAsynchronousFetchResult/title",
          "value": "NSAsynchronousFetchResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAsynchronousFetchResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAsynchronousFetchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAsynchronousFetchResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAsynchronousFetchResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
