{
  "abstract": [
    {
      "text": "Streamline access to users’ location data through a standard, secure UI.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CoreLocationUI",
    "modules": [
      {
        "name": "CoreLocationUI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "CoreLocationUI"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The CoreLocationUI framework contains a standardized UI that interacts securely",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreLocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to request authorization to access location data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "CoreLocationUI provides ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/LocationButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for SwiftUI apps and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for UIKit apps. Add these buttons to your UI when you want someone to grant one-time",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "authorization for your app to fetch their location. The button’s style is consistent",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "with the standard Core Location design language, giving users a sense of familiarity",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and trust when they interact with it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The location button ignores user input on Mac apps built with Mac Catalyst, and on compatible iPad and iPhone apps running in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI": {
      "abstract": [
        {
          "text": "Streamline access to users’ location data through a standard, secure UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI",
      "kind": "symbol",
      "role": "collection",
      "title": "CoreLocationUI",
      "type": "topic",
      "url": "/documentation/corelocationui"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton": {
      "abstract": [
        {
          "text": "A button that grants one-time location authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationButton"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButton"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButton",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbutton"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonIcon": {
      "abstract": [
        {
          "text": "Constants that specify styles for the location arrow icon on the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationButtonIcon"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonIcon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonIcon"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonIcon",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonicon"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel": {
      "abstract": [
        {
          "text": "Constants that specify the text of the button label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabel"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CoreLocationUIVersionNumber": {
      "abstract": [
        {
          "text": "The project version number for CoreLocationUI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CoreLocationUIVersionNumber"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CoreLocationUIVersionNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "CoreLocationUIVersionNumber",
      "type": "topic",
      "url": "/documentation/corelocationui/corelocationuiversionnumber"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CoreLocationUIVersionString": {
      "abstract": [
        {
          "text": "The project version string for CoreLocationUI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CoreLocationUIVersionString"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CoreLocationUIVersionString",
      "kind": "symbol",
      "role": "symbol",
      "title": "CoreLocationUIVersionString",
      "type": "topic",
      "url": "/documentation/corelocationui/corelocationuiversionstring"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/LocationButton": {
      "abstract": [
        {
          "text": "A SwiftUI button that grants one-time location authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocationButton"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/LocationButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocationButton"
        }
      ],
      "role": "symbol",
      "title": "LocationButton",
      "type": "topic",
      "url": "/documentation/corelocationui/locationbutton"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/sharing-your-location-to-find-a-park": {
      "abstract": [
        {
          "text": "Ask for location access using a customizable location button.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/sharing-your-location-to-find-a-park",
      "kind": "article",
      "role": "sampleCode",
      "title": "Sharing Your Location to Find a Park",
      "type": "topic",
      "url": "/documentation/corelocationui/sharing-your-location-to-find-a-park"
    },
    "doc://com.apple.documentation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/CoreLocation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Location-authorization",
      "identifiers": [
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/sharing-your-location-to-find-a-park",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/LocationButton",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton"
      ],
      "title": "Location authorization"
    },
    {
      "anchor": "Button-customization",
      "identifiers": [
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonIcon",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel"
      ],
      "title": "Button customization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Location-authorization",
              "identifiers": [
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/sharing-your-location-to-find-a-park",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButton"
              ],
              "title": "Location authorization"
            },
            {
              "anchor": "Button-customization",
              "identifiers": [
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonIcon",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel"
              ],
              "title": "Button customization"
            },
            {
              "anchor": "Framework-version",
              "identifiers": [
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CoreLocationUIVersionNumber",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CoreLocationUIVersionString"
              ],
              "title": "Framework version"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel/title",
          "value": "CLLocationButtonLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton/title",
          "value": "CLLocationButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonIcon/title",
          "value": "CLLocationButtonIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonIcon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonIcon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonIcon"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocationui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocationui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
