{
  "abstract": [
    {
      "text": "Add user interfaces to audio units.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CoreAudioKit",
    "modules": [
      {
        "name": "CoreAudioKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.4",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "CoreAudioKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Audio Kit provides views and controllers to use when building Audio Unit user interfaces.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit": {
      "abstract": [
        {
          "text": "Add user interfaces to audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CoreAudioKit",
      "type": "topic",
      "url": "/documentation/coreaudiokit"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAppleCustomViewLoader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAppleCustomViewLoader"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAppleCustomViewLoader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAppleCustomViewLoader"
        }
      ],
      "role": "symbol",
      "title": "AUAppleCustomViewLoader",
      "type": "topic",
      "url": "/documentation/coreaudiokit/auapplecustomviewloader"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that describes how to present the audio unit’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitViewConfiguration"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitViewConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitViewConfiguration",
      "type": "topic",
      "url": "/documentation/coreaudiokit/auaudiounitviewconfiguration"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData": {
      "abstract": [
        {
          "text": "A protocol that defines the methods an Audio Unit host calls to manage view data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUCustomViewPersistentData"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUCustomViewPersistentData"
        }
      ],
      "role": "symbol",
      "title": "AUCustomViewPersistentData",
      "type": "topic",
      "url": "/documentation/coreaudiokit/aucustomviewpersistentdata"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView": {
      "abstract": [
        {
          "text": "A view that provides a generic user interface for a Cocoa audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGenericView"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGenericView"
        }
      ],
      "role": "symbol",
      "title": "AUGenericView",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericview"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGenericViewController"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGenericViewController"
        }
      ],
      "role": "symbol",
      "title": "AUGenericViewController",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewcontroller"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags": {
      "abstract": [
        {
          "text": "Flags that describe the display of a generic view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "role": "symbol",
      "title": "AUGenericViewDisplayFlags",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewdisplayflags"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewInternal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGenericViewInternal"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewInternal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGenericViewInternal"
        }
      ],
      "role": "symbol",
      "title": "AUGenericViewInternal",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewinternal"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewInternalBase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGenericViewInternalBase"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewInternalBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGenericViewInternalBase"
        }
      ],
      "role": "symbol",
      "title": "AUGenericViewInternalBase",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewinternalbase"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView": {
      "abstract": [
        {
          "text": "A view that provides a specialized user interface for a Cocoa-based panner audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUPannerView"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUPannerView"
        }
      ],
      "role": "symbol",
      "title": "AUPannerView",
      "type": "topic",
      "url": "/documentation/coreaudiokit/aupannerview"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewController": {
      "abstract": [
        {
          "text": "The base class to extend when creating a custom user interface for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUViewController"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUViewController"
        }
      ],
      "role": "symbol",
      "title": "AUViewController",
      "type": "topic",
      "url": "/documentation/coreaudiokit/auviewcontroller"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewControllerBase": {
      "abstract": [
        {
          "text": "A type definition that indicates the the platform’s Audio Unit view controller base class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AUViewControllerBase"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewControllerBase",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUViewControllerBase",
      "type": "topic",
      "url": "/documentation/coreaudiokit/auviewcontrollerbase"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTLEMIDIWindowController": {
      "abstract": [
        {
          "text": "A window controller that displays nearby Bluetooth-based MIDI peripherals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CABTLEMIDIWindowController"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTLEMIDIWindowController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CABTLEMIDIWindowController"
        }
      ],
      "role": "symbol",
      "title": "CABTLEMIDIWindowController",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cabtlemidiwindowcontroller"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTMIDICentralViewController": {
      "abstract": [
        {
          "text": "A view controller that displays nearby Bluetooth-based MIDI peripherals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CABTMIDICentralViewController"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTMIDICentralViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CABTMIDICentralViewController"
        }
      ],
      "role": "symbol",
      "title": "CABTMIDICentralViewController",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cabtmidicentralviewcontroller"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTMIDILocalPeripheralViewController": {
      "abstract": [
        {
          "text": "A view controller that advertises an iOS device as a Bluetooth-based MIDI peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CABTMIDILocalPeripheralViewController"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTMIDILocalPeripheralViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CABTMIDILocalPeripheralViewController"
        }
      ],
      "role": "symbol",
      "title": "CABTMIDILocalPeripheralViewController",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cabtmidilocalperipheralviewcontroller"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioSwitcherView": {
      "abstract": [
        {
          "text": "A view that provides an audio switcher user interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAInterAppAudioSwitcherView"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioSwitcherView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAInterAppAudioSwitcherView"
        }
      ],
      "role": "symbol",
      "title": "CAInterAppAudioSwitcherView",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudioswitcherview"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView": {
      "abstract": [
        {
          "text": "A view that provides an audio transport user interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAInterAppAudioTransportView"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAInterAppAudioTransportView"
        }
      ],
      "role": "symbol",
      "title": "CAInterAppAudioTransportView",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterappaudiotransportview"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterDeviceAudioViewController": {
      "abstract": [
        {
          "text": "A view controller object that displays iOS devices that support inter-device audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAInterDeviceAudioViewController"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterDeviceAudioViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAInterDeviceAudioViewController"
        }
      ],
      "role": "symbol",
      "title": "CAInterDeviceAudioViewController",
      "type": "topic",
      "url": "/documentation/coreaudiokit/cainterdeviceaudioviewcontroller"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CANetworkBrowserWindowController": {
      "abstract": [
        {
          "text": "A window controller that displays available network audio devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CANetworkBrowserWindowController"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CANetworkBrowserWindowController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CANetworkBrowserWindowController"
        }
      ],
      "role": "symbol",
      "title": "CANetworkBrowserWindowController",
      "type": "topic",
      "url": "/documentation/coreaudiokit/canetworkbrowserwindowcontroller"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/core-audio-kit-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/core-audio-kit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Kit Data Types",
      "type": "topic",
      "url": "/documentation/coreaudiokit/core-audio-kit-data-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Audio-Units",
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewController",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData"
      ],
      "title": "Audio Units"
    },
    {
      "anchor": "Bluetooth-Devices",
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTLEMIDIWindowController",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTMIDICentralViewController",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTMIDILocalPeripheralViewController"
      ],
      "title": "Bluetooth Devices"
    },
    {
      "anchor": "Network-Devices",
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CANetworkBrowserWindowController"
      ],
      "title": "Network Devices"
    },
    {
      "anchor": "Inter-Device-Audio",
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterDeviceAudioViewController"
      ],
      "title": "Inter-Device Audio"
    },
    {
      "abstract": [
        {
          "text": "Inter-App Audio is deprecated in iOS 13 and is unavailable when running iPad apps in macOS.",
          "type": "text"
        }
      ],
      "anchor": "Inter-App-Audio",
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioSwitcherView",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView"
      ],
      "title": "Inter-App Audio"
    },
    {
      "anchor": "Deprecations",
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewInternal",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewInternalBase"
      ],
      "title": "Deprecations"
    },
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAppleCustomViewLoader",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewController"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Audio-Units",
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewController",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewControllerBase",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData"
              ],
              "title": "Audio Units"
            },
            {
              "anchor": "Bluetooth-Devices",
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTLEMIDIWindowController",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTMIDICentralViewController",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CABTMIDILocalPeripheralViewController"
              ],
              "title": "Bluetooth Devices"
            },
            {
              "anchor": "Network-Devices",
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CANetworkBrowserWindowController"
              ],
              "title": "Network Devices"
            },
            {
              "anchor": "Inter-Device-Audio",
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterDeviceAudioViewController"
              ],
              "title": "Inter-Device Audio"
            },
            {
              "abstract": [
                {
                  "text": "Inter-App Audio is deprecated in iOS 13 and is unavailable when running iPad apps in macOS.",
                  "type": "text"
                }
              ],
              "anchor": "Inter-App-Audio",
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioSwitcherView",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/CAInterAppAudioTransportView"
              ],
              "title": "Inter-App Audio"
            },
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewController"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/core-audio-kit-data-types"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CABTMIDILocalPeripheralViewController/title",
          "value": "CABTMIDILocalPeripheralViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CABTMIDILocalPeripheralViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CABTMIDILocalPeripheralViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CABTMIDILocalPeripheralViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CABTMIDILocalPeripheralViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags/title",
          "value": "AUGenericViewDisplayFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericViewDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericViewDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUViewController/title",
          "value": "AUViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterDeviceAudioViewController/title",
          "value": "CAInterDeviceAudioViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterDeviceAudioViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAInterDeviceAudioViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterDeviceAudioViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAInterDeviceAudioViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioSwitcherView/title",
          "value": "CAInterAppAudioSwitcherView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioSwitcherView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAInterAppAudioSwitcherView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioSwitcherView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAInterAppAudioSwitcherView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CABTMIDICentralViewController/title",
          "value": "CABTMIDICentralViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CABTMIDICentralViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CABTMIDICentralViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CABTMIDICentralViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CABTMIDICentralViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUPannerView/title",
          "value": "AUPannerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUPannerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUPannerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUPannerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUPannerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView/title",
          "value": "CAInterAppAudioTransportView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAInterAppAudioTransportView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CAInterAppAudioTransportView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAInterAppAudioTransportView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CABTLEMIDIWindowController/title",
          "value": "CABTLEMIDIWindowController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CABTLEMIDIWindowController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CABTLEMIDIWindowController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CABTLEMIDIWindowController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CABTLEMIDIWindowController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUAudioUnitViewConfiguration/title",
          "value": "AUAudioUnitViewConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUAudioUnitViewConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUAudioUnitViewConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewController/title",
          "value": "AUGenericViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericView/title",
          "value": "AUGenericView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUCustomViewPersistentData/title",
          "value": "AUCustomViewPersistentData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUCustomViewPersistentData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUCustomViewPersistentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUCustomViewPersistentData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUCustomViewPersistentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CANetworkBrowserWindowController/title",
          "value": "CANetworkBrowserWindowController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CANetworkBrowserWindowController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CANetworkBrowserWindowController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1CANetworkBrowserWindowController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CANetworkBrowserWindowController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiokit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiokit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
