{
  "abstract": [
    {
      "text": "Add search capabilities to your app, and index your content so",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "people can find it from Spotlight and Safari.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CoreSpotlight",
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.13",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Core Spotlight"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Help people access activities and items within your app by adding",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "details about those items to a Core Spotlight index. The framework provides",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "APIs to add your content to an index, and search for items in that index. You",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "decide what content makes sense to index, but typically you index anything",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that someone might look for in your app. For example, you might index photos,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "contacts, the items someone purchased, or data they see in your interface.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You can then use Core Spotlight to search for your indexed content and display",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "those results in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your app is responsible for indexing your app’s content and maintaining",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "those indexes. You can index content when your app runs, or provide an app",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "extension to index content when the system requests it. You can index any",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "content your app manages, including files and other content that your app",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "isn’t currently displaying. The indexes you create using Core Spotlight remain",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "on device, and are private to the owner of the device. Devices don’t share",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "indexed data with Apple, or synchronize that data with the person’s other devices.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to indexing content, iOS provides additional strategies for",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "making your app’s content searchable:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the search-related properties of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to add items to the on-device index, with the option to identify the items as eligible for public indexing. Learn more about ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " in ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/Activities.html#//apple_ref/doc/uid/TP40016308-CH6-SW1",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use web markup to index content on your web server in Apple’s server-side index, which makes the data available to all iOS users in Spotlight and Safari search results. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/WebContent.html#//apple_ref/doc/uid/TP40016308-CH8-SW1",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " in ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/index.html",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CORESPOTLIGHT_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CORESPOTLIGHT_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CORESPOTLIGHT_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "CORESPOTLIGHT_EXPORT",
      "type": "topic",
      "url": "/documentation/corespotlight/corespotlight_export"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSCustomAttributeKey": {
      "abstract": [
        {
          "text": "A key associated with a custom attribute for a searchable item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSCustomAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSCustomAttributeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSCustomAttributeKey"
        }
      ],
      "role": "symbol",
      "title": "CSCustomAttributeKey",
      "type": "topic",
      "url": "/documentation/corespotlight/cscustomattributekey"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSImportExtension": {
      "abstract": [
        {
          "text": "An object that provides searchable attributes for file types that the app supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSImportExtension"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSImportExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSImportExtension"
        }
      ],
      "role": "symbol",
      "title": "CSImportExtension",
      "type": "topic",
      "url": "/documentation/corespotlight/csimportextension"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError": {
      "abstract": [
        {
          "text": "Index errors returned by Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSIndexError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexError"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexExtensionRequestHandler": {
      "abstract": [
        {
          "text": "An interface that implements an index-maintenance app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSIndexExtensionRequestHandler"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexExtensionRequestHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexExtensionRequestHandler"
        }
      ],
      "role": "symbol",
      "title": "CSIndexExtensionRequestHandler",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexextensionrequesthandler"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSLocalizedString": {
      "abstract": [
        {
          "text": "An object that displays localized text in search results related to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSLocalizedString"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSLocalizedString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSLocalizedString"
        }
      ],
      "role": "symbol",
      "title": "CSLocalizedString",
      "type": "topic",
      "url": "/documentation/corespotlight/cslocalizedstring"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSPerson": {
      "abstract": [
        {
          "text": "An object that represents a person in the context of search results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSPerson"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSPerson"
        }
      ],
      "role": "symbol",
      "title": "CSPerson",
      "type": "topic",
      "url": "/documentation/corespotlight/csperson"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery": {
      "abstract": [
        {
          "text": "A type you use to programmatically search the indexed app content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQuery"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQuery"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQuery",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext": {
      "abstract": [
        {
          "text": "The behavior configuration to use for a search query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQueryContext"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQueryContext"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQueryContext",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquerycontext"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryError": {
      "abstract": [
        {
          "text": "Search query errors returned by Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchQueryError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchQueryError"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQueryError",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchqueryerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndex": {
      "abstract": [
        {
          "text": "An on-device index for your app’s searchable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableIndex"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchableIndex"
        }
      ],
      "role": "symbol",
      "title": "CSSearchableIndex",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableindex"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndexDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines methods a delegate object or app extension uses to handle communication from the on-device index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableIndexDelegate"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndexDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchableIndexDelegate"
        }
      ],
      "role": "symbol",
      "title": "CSSearchableIndexDelegate",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableindexdelegate"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem": {
      "abstract": [
        {
          "text": "The details of your app-specific content that someone might search",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "for on their devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableItem"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchableItem"
        }
      ],
      "role": "symbol",
      "title": "CSSearchableItem",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitem"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem/UpdateListenerOptions-swift.struct": {
      "abstract": [
        {
          "text": "The set of options that contain metadata-associated summarization and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "prioritization of a searchable item.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UpdateListenerOptions"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem/UpdateListenerOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UpdateListenerOptions"
        }
      ],
      "role": "symbol",
      "title": "CSSearchableItem.UpdateListenerOptions",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitem/updatelisteneroptions-swift.struct"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet": {
      "abstract": [
        {
          "text": "The detailed metadata for a searchable item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableItemAttributeSet"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSearchableItemAttributeSet"
        }
      ],
      "role": "symbol",
      "title": "CSSearchableItemAttributeSet",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchableitemattributeset"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion": {
      "abstract": [
        {
          "text": "The kind of suggestion to use in a query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSuggestion"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSuggestion"
        }
      ],
      "role": "symbol",
      "title": "CSSuggestion",
      "type": "topic",
      "url": "/documentation/corespotlight/cssuggestion"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestionHighlightAttributeName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSuggestionHighlightAttributeName"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestionHighlightAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSuggestionHighlightAttributeName",
      "type": "topic",
      "url": "/documentation/corespotlight/cssuggestionhighlightattributename"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery": {
      "abstract": [
        {
          "text": "A type you use to initiate searches from your interface and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "offer suggested text completions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSUserQuery"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSUserQuery"
        }
      ],
      "role": "symbol",
      "title": "CSUserQuery",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquery"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext": {
      "abstract": [
        {
          "text": "The configuration details to apply to a user query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSUserQueryContext"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSUserQueryContext"
        }
      ],
      "role": "symbol",
      "title": "CSUserQueryContext",
      "type": "topic",
      "url": "/documentation/corespotlight/csuserquerycontext"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/corespotlight/cs_available"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_CLASS_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_CLASS_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_CLASS_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_CLASS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/corespotlight/cs_class_available"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_DEPRECATED",
      "type": "topic",
      "url": "/documentation/corespotlight/cs_deprecated"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_TVOS_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_TVOS_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_TVOS_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_TVOS_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/corespotlight/cs_tvos_unavailable"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CoreSpotlightAPIVersion": {
      "abstract": [
        {
          "text": "The API version number for Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CoreSpotlightAPIVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CoreSpotlightAPIVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CoreSpotlightAPIVersion"
        }
      ],
      "role": "symbol",
      "title": "CoreSpotlightAPIVersion",
      "type": "topic",
      "url": "/documentation/corespotlight/corespotlightapiversion"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CoreSpotlightVersionNumber": {
      "abstract": [
        {
          "text": "The project version number for Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CoreSpotlightVersionNumber"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CoreSpotlightVersionNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "CoreSpotlightVersionNumber",
      "type": "topic",
      "url": "/documentation/corespotlight/corespotlightversionnumber"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CoreSpotlightVersionString": {
      "abstract": [
        {
          "text": "The project version string for Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CoreSpotlightVersionString"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CoreSpotlightVersionString",
      "kind": "symbol",
      "role": "symbol",
      "title": "CoreSpotlightVersionString",
      "type": "topic",
      "url": "/documentation/corespotlight/corespotlightversionstring"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/adding-your-app-s-content-to-spotlight-indexes": {
      "abstract": [
        {
          "text": "Create a description for your app’s content and add it to a Spotlight",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "index to make it searchable.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/adding-your-app-s-content-to-spotlight-indexes",
      "kind": "article",
      "role": "article",
      "title": "Adding your app’s content to Spotlight indexes",
      "type": "topic",
      "url": "/documentation/corespotlight/adding-your-app-s-content-to-spotlight-indexes"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app": {
      "abstract": [
        {
          "text": "Add a search interface to your app to execute Spotlight queries",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and offer suggested text completions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Building a search interface for your app",
      "type": "topic",
      "url": "/documentation/corespotlight/building-a-search-interface-for-your-app"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/csindex-errors": {
      "abstract": [
        {
          "text": "Index error codes and error domain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/csindex-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CSIndex Errors",
      "type": "topic",
      "url": "/documentation/corespotlight/csindex-errors"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/cssearchquery-errors": {
      "abstract": [
        {
          "text": "Search query error codes and error domain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/cssearchquery-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CSSearchQuery Errors",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquery-errors"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/enable-apple-intelligence-summaries": {
      "abstract": [
        {
          "text": "Enable Apple Intelligence to summarize and prioritize app",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "content using Spotlight extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/enable-apple-intelligence-summaries",
      "kind": "article",
      "role": "article",
      "title": "Enabling Apple Intelligence summarization and prioritization",
      "type": "topic",
      "url": "/documentation/corespotlight/enable-apple-intelligence-summaries"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/regenerating-your-app-s-indexes-on-demand": {
      "abstract": [
        {
          "text": "Create an app extension to maintain your app’s indexes and regenerate",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "them as needed.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/regenerating-your-app-s-indexes-on-demand",
      "kind": "article",
      "role": "article",
      "title": "Regenerating your app’s indexes on demand",
      "type": "topic",
      "url": "/documentation/corespotlight/regenerating-your-app-s-indexes-on-demand"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app": {
      "abstract": [
        {
          "text": "Search for app-specific content and refine search results using",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "predicates and filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Searching for information in your app",
      "type": "topic",
      "url": "/documentation/corespotlight/searching-for-information-in-your-app"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity": {
      "abstract": [
        {
          "text": "A representation of the state of your app at a moment in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivity",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/Activities.html#//apple_ref/doc/uid/TP40016308-CH6-SW1": {
      "identifier": "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/Activities.html#//apple_ref/doc/uid/TP40016308-CH6-SW1",
      "title": "Index Activities and Navigation Points",
      "titleInlineContent": [
        {
          "text": "Index Activities and Navigation Points",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/Activities.html#//apple_ref/doc/uid/TP40016308-CH6-SW1"
    },
    "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/WebContent.html#//apple_ref/doc/uid/TP40016308-CH8-SW1": {
      "identifier": "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/WebContent.html#//apple_ref/doc/uid/TP40016308-CH8-SW1",
      "title": "Mark Up Web Content",
      "titleInlineContent": [
        {
          "text": "Mark Up Web Content",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/WebContent.html#//apple_ref/doc/uid/TP40016308-CH8-SW1"
    },
    "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/index.html": {
      "identifier": "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/index.html",
      "title": "App Search Programming Guide",
      "titleInlineContent": [
        {
          "text": "App Search Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/index.html"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/adding-your-app-s-content-to-spotlight-indexes",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/enable-apple-intelligence-summaries"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Searchable-items",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSCustomAttributeKey",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSLocalizedString",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSPerson"
      ],
      "title": "Searchable items"
    },
    {
      "anchor": "Indexes",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndex",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndexDelegate"
      ],
      "title": "Indexes"
    },
    {
      "anchor": "Spotlight-app-extensions",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/regenerating-your-app-s-indexes-on-demand",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexExtensionRequestHandler",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSImportExtension"
      ],
      "title": "Spotlight app extensions"
    },
    {
      "anchor": "Queries",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion"
      ],
      "title": "Queries"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/csindex-errors",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/cssearchquery-errors"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Version",
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CoreSpotlightAPIVersion"
      ],
      "title": "Version"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/adding-your-app-s-content-to-spotlight-indexes",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/enable-apple-intelligence-summaries"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Searchable-items",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItemAttributeSet",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSCustomAttributeKey",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSLocalizedString",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSPerson"
              ],
              "title": "Searchable items"
            },
            {
              "anchor": "Indexes",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndex",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableIndexDelegate"
              ],
              "title": "Indexes"
            },
            {
              "anchor": "Spotlight-app-extensions",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/regenerating-your-app-s-indexes-on-demand",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexExtensionRequestHandler",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSImportExtension"
              ],
              "title": "Spotlight app extensions"
            },
            {
              "anchor": "Queries",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/building-a-search-interface-for-your-app",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/searching-for-information-in-your-app",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQuery",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSUserQueryContext",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuery",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestion"
              ],
              "title": "Queries"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/csindex-errors",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/cssearchquery-errors"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Version",
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CoreSpotlightAPIVersion",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CoreSpotlightVersionNumber",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CoreSpotlightVersionString"
              ],
              "title": "Version"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSuggestionHighlightAttributeName"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CORESPOTLIGHT_EXPORT",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_AVAILABLE",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_CLASS_AVAILABLE",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_DEPRECATED",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CS_TVOS_UNAVAILABLE"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchableItem/UpdateListenerOptions-swift.struct"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/title",
          "value": "CSSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSuggestion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSPerson/title",
          "value": "CSPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSPerson/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/title",
          "value": "CSSearchQueryContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSImportExtension/title",
          "value": "CSImportExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSImportExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSImportExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSImportExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSImportExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem/title",
          "value": "CSSearchableItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableIndex/title",
          "value": "CSSearchableIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableIndex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexExtensionRequestHandler/title",
          "value": "CSIndexExtensionRequestHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexExtensionRequestHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexExtensionRequestHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexExtensionRequestHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexExtensionRequestHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/title",
          "value": "CSUserQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSLocalizedString/title",
          "value": "CSLocalizedString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSLocalizedString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSLocalizedString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSLocalizedString/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSLocalizedString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CoreSpotlightAPIVersion/title",
          "value": "CoreSpotlightAPIVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CoreSpotlightAPIVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CoreSpotlightAPIVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/title",
          "value": "CSUserQueryContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSUserQueryContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSUserQueryContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem~1UpdateListenerOptions-swift.struct/title",
          "value": "CSSearchableItemUpdateListenerOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem~1UpdateListenerOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItemUpdateListenerOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItem~1UpdateListenerOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItemUpdateListenerOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/title",
          "value": "CSSearchQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSCustomAttributeKey/title",
          "value": "CSCustomAttributeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSCustomAttributeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSCustomAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSCustomAttributeKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSCustomAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableIndexDelegate/title",
          "value": "CSSearchableIndexDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableIndexDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableIndexDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableIndexDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableIndexDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/title",
          "value": "CSSearchableItemAttributeSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItemAttributeSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchableItemAttributeSet"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corespotlight"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
