{
  "abstract": [
    {
      "text": "Use the Core Audio framework to interact with device’s audio hardware.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CoreAudio",
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Core Audio"
  },
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAggregateDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareAggregateDevice"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAggregateDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareAggregateDevice"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareAggregateDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareaggregatedevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareBox": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareBox"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareBox"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareBox",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarebox"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareClock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareClock"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareClock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareClock"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareClock",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareclock"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareControl"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareControl"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareControl",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarecontrol"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareDevice"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareDevice"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaredevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareError"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareError"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareError",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareerror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareObject": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareObject"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareObject"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareObject",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareobject"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePlugin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwarePlugin"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePlugin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwarePlugin"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwarePlugin",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareplugin"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareProcess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareProcess"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareProcess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareProcess"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareProcess",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareprocess"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareStream"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareStream"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareStream",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarestream"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSystem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareSystem"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareSystem"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareSystem",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaresystem"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareTap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareTap"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareTap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareTap"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareTap",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaretap"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATapDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATapDescription"
        }
      ],
      "role": "symbol",
      "title": "CATapDescription",
      "type": "topic",
      "url": "/documentation/coreaudio/catapdescription"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/ManagedAudioChannelLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ManagedAudioChannelLayout"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/ManagedAudioChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ManagedAudioChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "ManagedAudioChannelLayout",
      "type": "topic",
      "url": "/documentation/coreaudio/managedaudiochannellayout"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyListenerDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PropertyListenerDelegate"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyListenerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PropertyListenerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PropertyListenerDelegate",
      "type": "topic",
      "url": "/documentation/coreaudio/propertylistenerdelegate"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/building-an-audio-server-plug-in-and-driver-extension": {
      "abstract": [
        {
          "text": "Create a plug-in and driver extension to support an audio device in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/building-an-audio-server-plug-in-and-driver-extension",
      "kind": "article",
      "role": "sampleCode",
      "title": "Building an Audio Server Plug-in and Driver Extension",
      "type": "topic",
      "url": "/documentation/coreaudio/building-an-audio-server-plug-in-and-driver-extension"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/capturing-system-audio-with-core-audio-taps": {
      "abstract": [
        {
          "text": "Use a Core Audio tap to capture outgoing audio from a process or group of processes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/capturing-system-audio-with-core-audio-taps",
      "kind": "article",
      "role": "sampleCode",
      "title": "Capturing system audio with Core Audio taps",
      "type": "topic",
      "url": "/documentation/coreaudio/capturing-system-audio-with-core-audio-taps"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Constants",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-constants"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Data Types",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-data-types"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Enumerations",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-enumerations"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Functions",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-functions"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Structures",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-structures"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/creating-an-audio-server-driver-plug-in": {
      "abstract": [
        {
          "text": "Build a virtual audio device by creating a custom driver plug-in.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/creating-an-audio-server-driver-plug-in",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating an Audio Server Driver Plug-in",
      "type": "topic",
      "url": "/documentation/coreaudio/creating-an-audio-server-driver-plug-in"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Drivers",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/creating-an-audio-server-driver-plug-in",
        "doc://com.apple.coreaudio/documentation/CoreAudio/building-an-audio-server-plug-in-and-driver-extension",
        "doc://com.apple.coreaudio/documentation/CoreAudio/capturing-system-audio-with-core-audio-taps"
      ],
      "title": "Drivers"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAggregateDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareBox",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareClock",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareControl",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareObject",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePlugin",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareProcess",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareStream",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSystem",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareTap",
        "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyListenerDelegate"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareError",
        "doc://com.apple.coreaudio/documentation/CoreAudio/ManagedAudioChannelLayout"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Drivers",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/creating-an-audio-server-driver-plug-in",
                "doc://com.apple.coreaudio/documentation/CoreAudio/building-an-audio-server-plug-in-and-driver-extension",
                "doc://com.apple.coreaudio/documentation/CoreAudio/capturing-system-audio-with-core-audio-taps"
              ],
              "title": "Drivers"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1CATapDescription/title",
          "value": "CATapDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1CATapDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATapDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1CATapDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATapDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
