{
  "abstract": [
    {
      "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "CoreNFC",
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Core NFC"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app can read tags to give users more information about their physical environment and the real-world objects in it. Using Core NFC, you can read Near Field Communication (NFC) tags of types 1 through 5 that contain data in the NFC Data Exchange Format (NDEF). For example, your app might give users information about products they find in a store or exhibits they visit in a museum.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your app can also write data to tags, and interact with protocol-specific tags such as ISO 7816, ISO 15693, FeliCa™, and MIFARE® tags.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Core NFC isn’t available for use in app extensions, and it requires a device that supports Near Field Communication. To determine if support is available, check the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/readingAvailable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class property before starting a reader session.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/CardSession": {
      "abstract": [
        {
          "text": "An ISO 7816 card emulation session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CardSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/CardSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CardSession"
        }
      ],
      "role": "symbol",
      "title": "CardSession",
      "type": "topic",
      "url": "/documentation/corenfc/cardsession"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain": {
      "abstract": [
        {
          "text": "The domain for errors associated with Core NFC APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "NFCErrorDomain",
      "type": "topic",
      "url": "/documentation/corenfc/nfcerrordomain"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingResponse"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingResponse"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaPollingResponse",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicapollingresponse"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaRequestSpecificationVersionResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaRequestSpecificationVersionResponse"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaRequestSpecificationVersionResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaRequestSpecificationVersionResponse"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaRequestSpecificationVersionResponse",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicarequestspecificationversionresponse"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaRequsetServiceV2Response": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaRequsetServiceV2Response"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaRequsetServiceV2Response",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaRequsetServiceV2Response"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaRequsetServiceV2Response",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicarequsetservicev2response"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaStatusFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaStatusFlag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaStatusFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaStatusFlag"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaStatusFlag",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicastatusflag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag": {
      "abstract": [
        {
          "text": "An interface for interacting with a FeliCa™ tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaTag"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicatag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693CustomCommandConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO15693CustomCommandConfiguration"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693CustomCommandConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO15693CustomCommandConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NFCISO15693CustomCommandConfiguration",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693customcommandconfiguration"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693MultipleBlockSecurityStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO15693MultipleBlockSecurityStatus"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693MultipleBlockSecurityStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO15693MultipleBlockSecurityStatus"
        }
      ],
      "role": "symbol",
      "title": "NFCISO15693MultipleBlockSecurityStatus",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693multipleblocksecuritystatus"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ReadMultipleBlocksConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO15693ReadMultipleBlocksConfiguration"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ReadMultipleBlocksConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO15693ReadMultipleBlocksConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NFCISO15693ReadMultipleBlocksConfiguration",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693readmultipleblocksconfiguration"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ReaderSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NFCISO15693ReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ReaderSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCISO15693ReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693readersession"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693SystemInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO15693SystemInfo"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693SystemInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO15693SystemInfo"
        }
      ],
      "role": "symbol",
      "title": "NFCISO15693SystemInfo",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693systeminfo"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693Tag": {
      "abstract": [
        {
          "text": "An interface for interacting with an ISO 15693 tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO15693Tag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693Tag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO15693Tag"
        }
      ],
      "role": "symbol",
      "title": "NFCISO15693Tag",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693tag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag": {
      "abstract": [
        {
          "text": "An interface for interacting with an ISO 7816 tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO7816Tag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO7816Tag"
        }
      ],
      "role": "symbol",
      "title": "NFCISO7816Tag",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso7816tag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCMiFareTag": {
      "abstract": [
        {
          "text": "An interface for interacting with a MIFARE® tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCMiFareTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCMiFareTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCMiFareTag"
        }
      ],
      "role": "symbol",
      "title": "NFCMiFareTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfcmifaretag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage": {
      "abstract": [
        {
          "text": "An NFC NDEF message consisting of an array of payload records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFMessage"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFMessage"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFMessage",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefmessage"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload": {
      "abstract": [
        {
          "text": "A payload record in an NFC NDEF message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFPayload"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFPayload"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFPayload",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefpayload"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession": {
      "abstract": [
        {
          "text": "A reader session for detecting NFC Data Exchange Format (NDEF) tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefreadersession"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag": {
      "abstract": [
        {
          "text": "An interface for interacting with an NDEF tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFTag"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndeftag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCPresentmentIntentAssertion": {
      "abstract": [
        {
          "text": "An object that signals your app’s intention to make exclusive use of the device’s contactless features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCPresentmentIntentAssertion"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCPresentmentIntentAssertion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCPresentmentIntentAssertion"
        }
      ],
      "role": "symbol",
      "title": "NFCPresentmentIntentAssertion",
      "type": "topic",
      "url": "/documentation/corenfc/nfcpresentmentintentassertion"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct": {
      "abstract": [
        {
          "text": "An error type that indicates problems with reader sessions or tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderError"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Reader session and tag error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderError.Code",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadererror-swift.struct/code"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class": {
      "abstract": [
        {
          "text": "The abstract base class that represents a reader session for detecting NFC tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersession-swift.class"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/readingAvailable": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the device supports NFC tag reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readingAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class/readingAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readingAvailable"
        }
      ],
      "role": "symbol",
      "title": "readingAvailable",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersession-swift.class/readingavailable"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate": {
      "abstract": [
        {
          "text": "A collection of callbacks that provide information about the status of an NFC reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCReaderSessionDelegate",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersessiondelegate"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol": {
      "abstract": [
        {
          "text": "A general interface for interacting with a reader session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCReaderSessionProtocol"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCReaderSessionProtocol"
        }
      ],
      "role": "symbol",
      "title": "NFCReaderSessionProtocol",
      "type": "topic",
      "url": "/documentation/corenfc/nfcreadersessionprotocol"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-c.protocol": {
      "abstract": [
        {
          "text": "An interface for interacting with an NFC or RFID tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NFCTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfctag-c.protocol"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum": {
      "abstract": [
        {
          "text": "An object that represents an NFC tag object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTag"
        }
      ],
      "role": "symbol",
      "title": "NFCTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfctag-swift.enum"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagCommandConfiguration": {
      "abstract": [
        {
          "text": "A set of parameters you use to define the configuration of an NFC tag command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTagCommandConfiguration"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagCommandConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTagCommandConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NFCTagCommandConfiguration",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagcommandconfiguration"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession": {
      "abstract": [
        {
          "text": "A reader session for detecting ISO7816, ISO15693, FeliCa, and MIFARE tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTagReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTagReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCTagReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagreadersession"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagResponseUnexpectedLengthErrorKey": {
      "abstract": [
        {
          "text": "A user-information dictionary key that indicates an invalid received response packet length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTagResponseUnexpectedLengthErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagResponseUnexpectedLengthErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTagResponseUnexpectedLengthErrorKey"
        }
      ],
      "role": "symbol",
      "title": "NFCTagResponseUnexpectedLengthErrorKey",
      "type": "topic",
      "url": "/documentation/corenfc/nfctagresponseunexpectedlengtherrorkey"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession": {
      "abstract": [
        {
          "text": "A reader session for processing Value Added Service (VAS) tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCVASReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCVASReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasreadersession"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCWindowSceneDelegate": {
      "abstract": [
        {
          "text": "A protocol to notify your app’s user interface about NFC-related events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCWindowSceneDelegate"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCWindowSceneDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCWindowSceneDelegate"
        }
      ],
      "role": "symbol",
      "title": "NFCWindowSceneDelegate",
      "type": "topic",
      "url": "/documentation/corenfc/nfcwindowscenedelegate"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCWindowSceneEvent": {
      "abstract": [
        {
          "text": "An NFC-related event that your app uses to update its user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCWindowSceneEvent"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCWindowSceneEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCWindowSceneEvent"
        }
      ],
      "role": "symbol",
      "title": "NFCWindowSceneEvent",
      "type": "topic",
      "url": "/documentation/corenfc/nfcwindowsceneevent"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/adding-support-for-background-tag-reading": {
      "abstract": [
        {
          "text": "Allow users to scan NFC tags without an app using background tag reading.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/adding-support-for-background-tag-reading",
      "kind": "article",
      "role": "article",
      "title": "Adding Support for Background Tag Reading",
      "type": "topic",
      "url": "/documentation/corenfc/adding-support-for-background-tag-reading"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/building-an-nfc-tag-reader-app": {
      "abstract": [
        {
          "text": "Read NFC tags with NDEF messages in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/building-an-nfc-tag-reader-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Building an NFC Tag-Reader App",
      "type": "topic",
      "url": "/documentation/corenfc/building-an-nfc-tag-reader-app"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/corenfc-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/corenfc-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CoreNFC Enumerations",
      "type": "topic",
      "url": "/documentation/corenfc/corenfc-enumerations"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/creating-nfc-tags-from-your-iphone": {
      "abstract": [
        {
          "text": "Save data to tags, and interact with them using native tag protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/creating-nfc-tags-from-your-iphone",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating NFC Tags from Your iPhone",
      "type": "topic",
      "url": "/documentation/corenfc/creating-nfc-tags-from-your-iphone"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats": {
      "abstract": [
        {
          "text": "The Near Field Communication data formats an app can read.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats",
      "kind": "symbol",
      "role": "symbol",
      "title": "Near Field Communication Tag Reader Session Formats Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NFCReaderUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the device’s NFC hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NFCReaderUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCReaderUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NFCReaderUsageDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/building-an-nfc-tag-reader-app",
        "doc://com.apple.corenfc/documentation/CoreNFC/adding-support-for-background-tag-reading",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NFCReaderUsageDescription"
      ],
      "title": "Essentials"
    },
    {
      "abstract": [
        {
          "text": "Create a reader session to scan and detect NFC tags.",
          "type": "text"
        }
      ],
      "anchor": "Reader-sessions",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats"
      ],
      "title": "Reader sessions"
    },
    {
      "abstract": [
        {
          "text": "Read tag data, and save data to writable tags, by using the appropriate tag type interface.",
          "type": "text"
        }
      ],
      "anchor": "Tag-types",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/creating-nfc-tags-from-your-iphone",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693Tag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCMiFareTag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagCommandConfiguration"
      ],
      "title": "Tag types"
    },
    {
      "anchor": "NDEF-messages-and-payloads",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload"
      ],
      "title": "NDEF messages and payloads"
    },
    {
      "anchor": "Card-sessions",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/CardSession",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCPresentmentIntentAssertion"
      ],
      "title": "Card sessions"
    },
    {
      "anchor": "NFC-window-scenes",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCWindowSceneDelegate",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCWindowSceneEvent"
      ],
      "title": "NFC window scenes"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagResponseUnexpectedLengthErrorKey"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/corenfc-enumerations"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693CustomCommandConfiguration",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ReadMultipleBlocksConfiguration"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingResponse",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaRequestSpecificationVersionResponse",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaRequsetServiceV2Response",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaStatusFlag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693MultipleBlockSecurityStatus",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693SystemInfo"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/building-an-nfc-tag-reader-app",
                "doc://com.apple.corenfc/documentation/CoreNFC/adding-support-for-background-tag-reading",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NFCReaderUsageDescription"
              ],
              "title": "Essentials"
            },
            {
              "abstract": [
                {
                  "text": "Create a reader session to scan and detect NFC tags.",
                  "type": "text"
                }
              ],
              "anchor": "Reader-sessions",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagReaderSession",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASReaderSession",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionProtocol",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSession-swift.class",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderSessionDelegate",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats"
              ],
              "title": "Reader sessions"
            },
            {
              "abstract": [
                {
                  "text": "Read tag data, and save data to writable tags, by using the appropriate tag type interface.",
                  "type": "text"
                }
              ],
              "anchor": "Tag-types",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/creating-nfc-tags-from-your-iphone",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO7816Tag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693Tag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaTag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCMiFareTag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-c.protocol",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagCommandConfiguration"
              ],
              "title": "Tag types"
            },
            {
              "anchor": "NDEF-messages-and-payloads",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFPayload"
              ],
              "title": "NDEF messages and payloads"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCReaderError-swift.struct/Code",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCErrorDomain",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCTagResponseUnexpectedLengthErrorKey"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/corenfc-enumerations"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693CustomCommandConfiguration",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ReadMultipleBlocksConfiguration",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ReaderSession"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO7816Tag/title",
          "value": "NFCISO7816Tag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO7816Tag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO7816Tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO7816Tag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO7816Tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693Tag/title",
          "value": "NFCISO15693Tag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693Tag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693Tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693Tag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693Tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693CustomCommandConfiguration/title",
          "value": "NFCISO15693CustomCommandConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693CustomCommandConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693CustomCommandConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693CustomCommandConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693CustomCommandConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class/title",
          "value": "NFCReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag/title",
          "value": "NFCFeliCaTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class~1readingAvailable/title",
          "value": "readingAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSession-swift.class~1readingAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "readingAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFMessage/title",
          "value": "NFCNDEFMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagCommandConfiguration/title",
          "value": "NFCTagCommandConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagCommandConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagCommandConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagCommandConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagCommandConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCMiFareTag/title",
          "value": "NFCMiFareTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCMiFareTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCMiFareTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCMiFareTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCMiFareTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagResponseUnexpectedLengthErrorKey/title",
          "value": "NFCTagResponseUnexpectedLengthErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagResponseUnexpectedLengthErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagResponseUnexpectedLengthErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload/title",
          "value": "NFCNDEFPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693ReadMultipleBlocksConfiguration/title",
          "value": "NFCISO15693ReadMultipleBlocksConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693ReadMultipleBlocksConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693ReadMultipleBlocksConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693ReadMultipleBlocksConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693ReadMultipleBlocksConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/title",
          "value": "NFCReaderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSessionProtocol/title",
          "value": "NFCReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSessionProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCReaderSessionProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASReaderSession/title",
          "value": "NFCVASReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASReaderSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASReaderSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession/title",
          "value": "NFCTagReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCTagReaderSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCTagReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag/title",
          "value": "NFCNDEFTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCErrorDomain/title",
          "value": "NFCErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/title",
          "value": "NFCNDEFReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFReaderSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
