{
  "abstract": [
    {
      "text": "Provides mechanisms to register and block disk mount or unmount events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "DiskArbitration",
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.4",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Disk Arbitration"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For related documentation, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/About/About.html#//apple_ref/doc/uid/TP40001067",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADisk.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadisk-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADissenter.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadissenter-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DASession.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dasession-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Constants",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-constants"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Data Types",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-data-types"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Enumerations",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-enumerations"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Functions",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-functions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h": {
      "abstract": [
        {
          "text": "Register for mount/unmount notifications, and block mount/unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/enum_(unnamed)-3ky11": {
      "abstract": [
        {
          "text": "A return code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/enum_(unnamed)-3ky11",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DAReturn",
      "type": "topic",
      "url": "/documentation/diskarbitration/enum_(unnamed)-3ky11"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionFSKitPrefix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionFSKitPrefix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionFSKitPrefix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionFSKitPrefix"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionFSKitPrefix",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionfskitprefix"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskMountOptionNoFollow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskMountOptionNoFollow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskMountOptionNoFollow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskMountOptionNoFollow"
        }
      ],
      "role": "symbol",
      "title": "kDADiskMountOptionNoFollow",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskmountoptionnofollow"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBadArgument": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnBadArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBadArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnBadArgument"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnBadArgument",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnbadargument"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBusy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnBusy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBusy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnBusy"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnBusy",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnbusy"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnError"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnError",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnerror"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnExclusiveAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnExclusiveAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnExclusiveAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnExclusiveAccess"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnExclusiveAccess",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnexclusiveaccess"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNoResources": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNoResources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNoResources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNoResources"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNoResources",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnoresources"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotFound"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotFound",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotfound"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotMounted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotMounted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotMounted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotMounted"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotMounted",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotmounted"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPermitted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotPermitted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPermitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotPermitted"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotPermitted",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotpermitted"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPrivileged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotPrivileged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPrivileged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotPrivileged"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotPrivileged",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotprivileged"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotReady": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotReady"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotReady",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotReady"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotReady",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotready"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotWritable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotWritable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotWritable"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotWritable",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotwritable"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnSuccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnSuccess"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnSuccess",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnsuccess"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnUnsupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnUnsupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnUnsupported"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnUnsupported",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnunsupported"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionejectuponlogout": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionejectuponlogout",
      "kind": "article",
      "role": "article",
      "title": "kDADiskOptionEjectUponLogout",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskoptionejectuponlogout"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionmountautomatic": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionmountautomatic",
      "kind": "article",
      "role": "article",
      "title": "kDADiskOptionMountAutomatic",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskoptionmountautomatic"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionmountautomaticnodefer": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionmountautomaticnodefer",
      "kind": "article",
      "role": "article",
      "title": "kDADiskOptionMountAutomaticNoDefer",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskoptionmountautomaticnodefer"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionprivate": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionprivate",
      "kind": "article",
      "role": "article",
      "title": "kDADiskOptionPrivate",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskoptionprivate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/About/About.html#//apple_ref/doc/uid/TP40001067": {
      "identifier": "https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/About/About.html#//apple_ref/doc/uid/TP40001067",
      "title": "Mac Technology Overview",
      "titleInlineContent": [
        {
          "text": "Mac Technology Overview",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/About/About.html#//apple_ref/doc/uid/TP40001067"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionejectuponlogout",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionmountautomatic",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionmountautomaticnodefer",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionprivate",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/enum_(unnamed)-3ky11"
      ],
      "title": "Articles"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionFSKitPrefix",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskMountOptionNoFollow",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBadArgument",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBusy",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnError",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnExclusiveAccess",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNoResources",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotFound",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotMounted",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPermitted",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPrivileged",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotReady",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotWritable",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnSuccess",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnUnsupported"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Articles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionejectuponlogout",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionmountautomatic",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionmountautomaticnodefer",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kdadiskoptionprivate",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/enum_(unnamed)-3ky11"
              ],
              "title": "Articles"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionFSKitPrefix"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskMountOptionNoFollow",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBadArgument",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBusy",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnError",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnExclusiveAccess",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNoResources",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotFound",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotMounted",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPermitted",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPrivileged",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotReady",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotWritable",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnSuccess",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnUnsupported"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNoResources/title",
          "value": "kDAReturnNoResources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNoResources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNoResources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotMounted/title",
          "value": "kDAReturnNotMounted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotMounted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotMounted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionFSKitPrefix/title",
          "value": "kDADiskDescriptionFSKitPrefix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionFSKitPrefix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionFSKitPrefix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotFound/title",
          "value": "kDAReturnNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnSuccess/title",
          "value": "kDAReturnSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnBadArgument/title",
          "value": "kDAReturnBadArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnBadArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnBadArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnBusy/title",
          "value": "kDAReturnBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnBusy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnError/title",
          "value": "kDAReturnError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotPrivileged/title",
          "value": "kDAReturnNotPrivileged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotPrivileged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotPrivileged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotPermitted/title",
          "value": "kDAReturnNotPermitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotPermitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotPermitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnExclusiveAccess/title",
          "value": "kDAReturnExclusiveAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnExclusiveAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnExclusiveAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnUnsupported/title",
          "value": "kDAReturnUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotWritable/title",
          "value": "kDAReturnNotWritable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotWritable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotWritable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotReady/title",
          "value": "kDAReturnNotReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotReady/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskMountOptionNoFollow/title",
          "value": "kDADiskMountOptionNoFollow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskMountOptionNoFollow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskMountOptionNoFollow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
