{
  "abstract": [
    {
      "text": "Develop system extensions that enhance user security.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "EndpointSecurity",
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Library",
    "symbolKind": "module",
    "title": "Endpoint Security"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Endpoint Security is a C API for monitoring system events for potentially malicious activity. You can write your client in any language that supports native calls. Your client registers with Endpoint Security to authorize pending events, or receive notifications of events that already occurred. These events include process executions, mounting file systems, forking processes, and raising signals.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Develop your system extension with Endpoint Security and package it in an app that uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SystemExtensions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework to install and upgrade the extension on the user’s Mac.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.endpoint-security.client": {
      "abstract": [
        {
          "text": "The entitlement required to monitor system events for potentially malicious activity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.endpoint-security.client",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.endpoint-security.client",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.endpoint-security.client"
    },
    "doc://com.apple.documentation/documentation/SystemExtensions": {
      "abstract": [
        {
          "text": "Install and manage user space code that extends the capabilities of macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SystemExtensions",
      "kind": "symbol",
      "role": "collection",
      "title": "System Extensions",
      "type": "topic",
      "url": "/documentation/SystemExtensions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_TCC_MODIFY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_TCC_MODIFY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_event_type_t",
          "text": "es_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_TCC_MODIFY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_EVENT_TYPE_NOTIFY_TCC_MODIFY"
        }
      ],
      "role": "symbol",
      "title": "ES_EVENT_TYPE_NOTIFY_TCC_MODIFY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_type_notify_tcc_modify"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_app_type_policy"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ENTITLED": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_ENTITLED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ENTITLED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_ENTITLED"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_ENTITLED",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_entitled"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ERROR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_ERROR"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_ERROR",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_error"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MDM_POLICY": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_MDM_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MDM_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_MDM_POLICY"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_MDM_POLICY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_mdm_policy"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_missing_usage_string"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_NONE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_NONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_NONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_NONE"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_NONE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_none"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_preflight_unknown"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_prompt_cancel"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_prompt_timeout"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_service_override_policy"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY": {
      "abstract": [
        {
          "text": "A system process changed the authorization right",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_service_policy"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET": {
      "abstract": [
        {
          "text": "User changed the authorization right via Preferences",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_system_set"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_CONSENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_USER_CONSENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_CONSENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_USER_CONSENT"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_USER_CONSENT",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_user_consent"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_SET": {
      "abstract": [
        {
          "text": "User answered a prompt",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_USER_SET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_SET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_REASON_USER_SET"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_REASON_USER_SET",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_user_set"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_ADD_MODIFY_ADDED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_ADD_MODIFY_ADDED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_ADD_MODIFY_ADDED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_ADD_MODIFY_ADDED"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_RIGHT_ADD_MODIFY_ADDED",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_right_add_modify_added"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_ALLOWED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_ALLOWED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_ALLOWED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_ALLOWED"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_RIGHT_ALLOWED",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_right_allowed"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_DENIED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_DENIED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_DENIED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_DENIED"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_RIGHT_DENIED",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_right_denied"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_right_learn_more"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_LIMITED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_LIMITED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_LIMITED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_LIMITED"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_RIGHT_LIMITED",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_right_limited"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_SESSION_PID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_SESSION_PID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_SESSION_PID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_SESSION_PID"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_RIGHT_SESSION_PID",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_right_session_pid"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_UNKNOWN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_UNKNOWN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_UNKNOWN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_AUTHORIZATION_RIGHT_UNKNOWN"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_AUTHORIZATION_RIGHT_UNKNOWN",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_right_unknown"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_CREATE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_EVENT_TYPE_CREATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_event_type_t",
          "text": "es_tcc_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_CREATE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_EVENT_TYPE_CREATE"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_EVENT_TYPE_CREATE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_event_type_create"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_DELETE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_EVENT_TYPE_DELETE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_event_type_t",
          "text": "es_tcc_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_DELETE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_EVENT_TYPE_DELETE"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_EVENT_TYPE_DELETE",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_event_type_delete"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_MODIFY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_EVENT_TYPE_MODIFY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_event_type_t",
          "text": "es_tcc_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_MODIFY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_EVENT_TYPE_MODIFY"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_EVENT_TYPE_MODIFY",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_event_type_modify"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_UNKNOWN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_EVENT_TYPE_UNKNOWN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_event_type_t",
          "text": "es_tcc_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_UNKNOWN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_EVENT_TYPE_UNKNOWN"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_EVENT_TYPE_UNKNOWN",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_event_type_unknown"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_BUNDLE_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_IDENTITY_TYPE_BUNDLE_ID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_identity_type_t",
          "text": "es_tcc_identity_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_BUNDLE_ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_IDENTITY_TYPE_BUNDLE_ID"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_IDENTITY_TYPE_BUNDLE_ID",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_identity_type_bundle_id"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_EXECUTABLE_PATH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_IDENTITY_TYPE_EXECUTABLE_PATH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_identity_type_t",
          "text": "es_tcc_identity_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_EXECUTABLE_PATH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_IDENTITY_TYPE_EXECUTABLE_PATH"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_IDENTITY_TYPE_EXECUTABLE_PATH",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_identity_type_executable_path"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_FILE_PROVIDER_DOMAIN_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_IDENTITY_TYPE_FILE_PROVIDER_DOMAIN_ID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_identity_type_t",
          "text": "es_tcc_identity_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_FILE_PROVIDER_DOMAIN_ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_IDENTITY_TYPE_FILE_PROVIDER_DOMAIN_ID"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_IDENTITY_TYPE_FILE_PROVIDER_DOMAIN_ID",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_identity_type_file_provider_domain_id"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_POLICY_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ES_TCC_IDENTITY_TYPE_POLICY_ID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_identity_type_t",
          "text": "es_tcc_identity_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_POLICY_ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ES_TCC_IDENTITY_TYPE_POLICY_ID"
        }
      ],
      "role": "symbol",
      "title": "ES_TCC_IDENTITY_TYPE_POLICY_ID",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_identity_type_policy_id"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/client": {
      "abstract": [
        {
          "text": "An opaque type that maintains Endpoint Security client state, and functions related to this type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/client",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Client",
      "type": "topic",
      "url": "/documentation/endpointsecurity/client"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Constants",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-constants"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Data Types",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-data-types"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Enumerations",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-enumerations"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Functions",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-functions"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EndpointSecurity Structures",
      "type": "topic",
      "url": "/documentation/endpointsecurity/endpointsecurity-structures"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_tcc_modify_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_tcc_modify_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_tcc_modify_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_tcc_modify_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_tcc_modify_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_tcc_modify_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t": {
      "abstract": [
        {
          "text": "ess_tcc_authorization_reason_t",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "role": "symbol",
      "title": "es_tcc_authorization_reason_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_right_t": {
      "abstract": [
        {
          "text": "ess_tcc_authorization_right_t",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_right_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "role": "symbol",
      "title": "es_tcc_authorization_right_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_right_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_event_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_tcc_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_event_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_tcc_event_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_tcc_event_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_event_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_identity_type_t": {
      "abstract": [
        {
          "text": "es_tcc_identity_type_t",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_tcc_identity_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_identity_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_tcc_identity_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_tcc_identity_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_identity_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/event-types": {
      "abstract": [
        {
          "text": "Types used by messages to deliver details specific to different kinds of Endpoint Security events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/event-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Event Types",
      "type": "topic",
      "url": "/documentation/endpointsecurity/event-types"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/message": {
      "abstract": [
        {
          "text": "A type used by Endpoint Security to notify your client when a monitored action occurs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/message",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Message",
      "type": "topic",
      "url": "/documentation/endpointsecurity/message"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/monitoring-system-events-with-endpoint-security": {
      "abstract": [
        {
          "text": "Receive notifications and authorization requests for sensitive operations by creating an Endpoint Security client for your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/monitoring-system-events-with-endpoint-security",
      "kind": "article",
      "role": "sampleCode",
      "title": "Monitoring System Events with Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity/monitoring-system-events-with-endpoint-security"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Event-Monitoring",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/client",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/message",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/event-types",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/monitoring-system-events-with-endpoint-security"
      ],
      "title": "Event Monitoring"
    },
    {
      "anchor": "Entitlements",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.endpoint-security.client"
      ],
      "title": "Entitlements"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_tcc_modify_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_right_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_event_type_t",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_identity_type_t"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_EVENT_TYPE_NOTIFY_TCC_MODIFY",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ENTITLED",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_ERROR",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MDM_POLICY",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_NONE",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_CONSENT",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_REASON_USER_SET",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_ADD_MODIFY_ADDED",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_ALLOWED",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_DENIED",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_LIMITED",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_SESSION_PID",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_AUTHORIZATION_RIGHT_UNKNOWN",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_CREATE",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_DELETE",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_MODIFY",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_EVENT_TYPE_UNKNOWN",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_BUNDLE_ID",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_EXECUTABLE_PATH",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_FILE_PROVIDER_DOMAIN_ID",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/ES_TCC_IDENTITY_TYPE_POLICY_ID"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Event-Monitoring",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/client",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/message",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/event-types",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/monitoring-system-events-with-endpoint-security"
              ],
              "title": "Event Monitoring"
            },
            {
              "anchor": "Entitlements",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.endpoint-security.client"
              ],
              "title": "Entitlements"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-constants",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-data-types",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-functions",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-structures",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/endpointsecurity-enumerations"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_tcc_modify_t"
              ],
              "title": "Structures"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_right_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_event_type_t",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_identity_type_t"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_right_t/title",
          "value": "es_tcc_authorization_right_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_right_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_right_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_right_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_right_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_SESSION_PID/title",
          "value": "ES_TCC_AUTHORIZATION_RIGHT_SESSION_PID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_SESSION_PID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_RIGHT_SESSION_PID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_reason_t/title",
          "value": "es_tcc_authorization_reason_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_reason_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_reason_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_TIMEOUT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_NONE/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_NONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_NONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_NONE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_OVERRIDE_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_DENIED/title",
          "value": "ES_TCC_AUTHORIZATION_RIGHT_DENIED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_DENIED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_RIGHT_DENIED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_MDM_POLICY/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_MDM_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_MDM_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_MDM_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_PROMPT_CANCEL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_EVENT_TYPE_MODIFY/title",
          "value": "ES_TCC_EVENT_TYPE_MODIFY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_EVENT_TYPE_MODIFY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_EVENT_TYPE_MODIFY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_ERROR/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_PREFLIGHT_UNKNOWN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_IDENTITY_TYPE_BUNDLE_ID/title",
          "value": "ES_TCC_IDENTITY_TYPE_BUNDLE_ID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_IDENTITY_TYPE_BUNDLE_ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_IDENTITY_TYPE_BUNDLE_ID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_IDENTITY_TYPE_POLICY_ID/title",
          "value": "ES_TCC_IDENTITY_TYPE_POLICY_ID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_IDENTITY_TYPE_POLICY_ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_IDENTITY_TYPE_POLICY_ID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_event_type_t/title",
          "value": "es_tcc_event_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_event_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_event_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_event_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_event_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_EVENT_TYPE_UNKNOWN/title",
          "value": "ES_TCC_EVENT_TYPE_UNKNOWN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_EVENT_TYPE_UNKNOWN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_EVENT_TYPE_UNKNOWN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_ENTITLED/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_ENTITLED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_ENTITLED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_ENTITLED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_ALLOWED/title",
          "value": "ES_TCC_AUTHORIZATION_RIGHT_ALLOWED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_ALLOWED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_RIGHT_ALLOWED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_TCC_MODIFY/title",
          "value": "ES_EVENT_TYPE_NOTIFY_TCC_MODIFY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_EVENT_TYPE_NOTIFY_TCC_MODIFY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_EVENT_TYPE_NOTIFY_TCC_MODIFY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_SYSTEM_SET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_tcc_modify_t/title",
          "value": "es_event_tcc_modify_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_tcc_modify_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_tcc_modify_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_tcc_modify_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_tcc_modify_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_LIMITED/title",
          "value": "ES_TCC_AUTHORIZATION_RIGHT_LIMITED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_LIMITED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_RIGHT_LIMITED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE/title",
          "value": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_RIGHT_LEARN_MORE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_IDENTITY_TYPE_EXECUTABLE_PATH/title",
          "value": "ES_TCC_IDENTITY_TYPE_EXECUTABLE_PATH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_IDENTITY_TYPE_EXECUTABLE_PATH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_IDENTITY_TYPE_EXECUTABLE_PATH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_EVENT_TYPE_CREATE/title",
          "value": "ES_TCC_EVENT_TYPE_CREATE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_EVENT_TYPE_CREATE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_EVENT_TYPE_CREATE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_SERVICE_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_APP_TYPE_POLICY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_identity_type_t/title",
          "value": "es_tcc_identity_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_identity_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_identity_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_identity_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_identity_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_USER_SET/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_USER_SET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_USER_SET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_USER_SET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_ADD_MODIFY_ADDED/title",
          "value": "ES_TCC_AUTHORIZATION_RIGHT_ADD_MODIFY_ADDED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_ADD_MODIFY_ADDED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_RIGHT_ADD_MODIFY_ADDED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_IDENTITY_TYPE_FILE_PROVIDER_DOMAIN_ID/title",
          "value": "ES_TCC_IDENTITY_TYPE_FILE_PROVIDER_DOMAIN_ID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_IDENTITY_TYPE_FILE_PROVIDER_DOMAIN_ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_IDENTITY_TYPE_FILE_PROVIDER_DOMAIN_ID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_MISSING_USAGE_STRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_EVENT_TYPE_DELETE/title",
          "value": "ES_TCC_EVENT_TYPE_DELETE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_EVENT_TYPE_DELETE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_EVENT_TYPE_DELETE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_USER_CONSENT/title",
          "value": "ES_TCC_AUTHORIZATION_REASON_USER_CONSENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_REASON_USER_CONSENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_REASON_USER_CONSENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_UNKNOWN/title",
          "value": "ES_TCC_AUTHORIZATION_RIGHT_UNKNOWN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1ES_TCC_AUTHORIZATION_RIGHT_UNKNOWN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ES_TCC_AUTHORIZATION_RIGHT_UNKNOWN"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
