{
  "abstract": [
    {
      "text": "Create, view, and edit calendar and reminder events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "EventKit",
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.8",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "EventKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The EventKit framework provides access to calendar and reminders data so people can create, retrieve, and edit calendar items in your app. In iOS, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/EventKitUI",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides user interfaces you can implement in your app so people can create and edit calendar items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use EventKit to set up alarms and create recurring events. And if a change to the Calendar database occurs from outside your app, EventKit detects the change and sends a notification, allowing your app to stay up to date.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/EventKitUI": {
      "abstract": [
        {
          "text": "Display an interface for viewing, selecting, and editing calendar events and reminders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/EventKitUI",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit UI",
      "type": "topic",
      "url": "/documentation/EventKitUI"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/DATETIME_COMPONENTS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DATETIME_COMPONENTS"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/DATETIME_COMPONENTS",
      "kind": "symbol",
      "role": "symbol",
      "title": "DATETIME_COMPONENTS",
      "type": "topic",
      "url": "/documentation/eventkit/datetime_components"
    },
    "doc://com.apple.eventkit/documentation/EventKit/DATE_COMPONENTS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DATE_COMPONENTS"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/DATE_COMPONENTS",
      "kind": "symbol",
      "role": "symbol",
      "title": "DATE_COMPONENTS",
      "type": "topic",
      "url": "/documentation/eventkit/date_components"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKAlarm": {
      "abstract": [
        {
          "text": "A class that represents an alarm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKAlarm"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKAlarm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKAlarm"
        }
      ],
      "role": "symbol",
      "title": "EKAlarm",
      "type": "topic",
      "url": "/documentation/eventkit/ekalarm"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar": {
      "abstract": [
        {
          "text": "A class that represents a calendar in EventKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendar"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendar"
        }
      ],
      "role": "symbol",
      "title": "EKCalendar",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem": {
      "abstract": [
        {
          "text": "An abstract superclass for calendar events and reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarItem"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarItem"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarItem",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendaritem"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError": {
      "abstract": [
        {
          "text": "An EventKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKError"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKError"
        }
      ],
      "role": "symbol",
      "title": "EKError",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code": {
      "abstract": [
        {
          "text": "Error codes for EventKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the EventKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "EKErrorDomain",
      "type": "topic",
      "url": "/documentation/eventkit/ekerrordomain"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent": {
      "abstract": [
        {
          "text": "A class that represents an event in a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEvent"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEvent"
        }
      ],
      "role": "symbol",
      "title": "EKEvent",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventStore": {
      "abstract": [
        {
          "text": "An object that accesses a person’s calendar events and reminders and supports the scheduling of new events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventStore"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventStore"
        }
      ],
      "role": "symbol",
      "title": "EKEventStore",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventstore"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKObject": {
      "abstract": [
        {
          "text": "An abstract superclass for all EventKit classes that have persistent instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKObject"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKObject"
        }
      ],
      "role": "symbol",
      "title": "EKObject",
      "type": "topic",
      "url": "/documentation/eventkit/ekobject"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipant": {
      "abstract": [
        {
          "text": "A class that represents person, group, or room invited to a calendar event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKParticipant"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipant"
        }
      ],
      "role": "symbol",
      "title": "EKParticipant",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipant"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceDayOfWeek": {
      "abstract": [
        {
          "text": "A class that represents the day of the week.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKRecurrenceDayOfWeek"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceDayOfWeek",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKRecurrenceDayOfWeek"
        }
      ],
      "role": "symbol",
      "title": "EKRecurrenceDayOfWeek",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencedayofweek"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceEnd": {
      "abstract": [
        {
          "text": "A class that defines the end of a recurrence rule.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKRecurrenceEnd"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKRecurrenceEnd"
        }
      ],
      "role": "symbol",
      "title": "EKRecurrenceEnd",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrenceend"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule": {
      "abstract": [
        {
          "text": "A class that describes the pattern for a recurring event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKRecurrenceRule"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKRecurrenceRule"
        }
      ],
      "role": "symbol",
      "title": "EKRecurrenceRule",
      "type": "topic",
      "url": "/documentation/eventkit/ekrecurrencerule"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKReminder": {
      "abstract": [
        {
          "text": "A class that represents a reminder in a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKReminder"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKReminder"
        }
      ],
      "role": "symbol",
      "title": "EKReminder",
      "type": "topic",
      "url": "/documentation/eventkit/ekreminder"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKSource": {
      "abstract": [
        {
          "text": "An abstract superclass that represents the account a calendar belongs to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKSource"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKSource"
        }
      ],
      "role": "symbol",
      "title": "EKSource",
      "type": "topic",
      "url": "/documentation/eventkit/eksource"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKStructuredLocation": {
      "abstract": [
        {
          "code": "A",
          "type": "codeVoice"
        },
        {
          "text": " class that specifies a geofence to activate the alarm of a calendar item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKStructuredLocation"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKStructuredLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKStructuredLocation"
        }
      ],
      "role": "symbol",
      "title": "EKStructuredLocation",
      "type": "topic",
      "url": "/documentation/eventkit/ekstructuredlocation"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceDescriptor": {
      "abstract": [
        {
          "text": "Details about a virtual conference that uses a custom room type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKVirtualConferenceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKVirtualConferenceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "EKVirtualConferenceDescriptor",
      "type": "topic",
      "url": "/documentation/eventkit/ekvirtualconferencedescriptor"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceProvider": {
      "abstract": [
        {
          "text": "An object that associates virtual conferencing details with an event object in a user’s calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKVirtualConferenceProvider"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKVirtualConferenceProvider"
        }
      ],
      "role": "symbol",
      "title": "EKVirtualConferenceProvider",
      "type": "topic",
      "url": "/documentation/eventkit/ekvirtualconferenceprovider"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceRoomTypeDescriptor": {
      "abstract": [
        {
          "text": "Details about a room where virtual conferences take place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKVirtualConferenceRoomTypeDescriptor"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceRoomTypeDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKVirtualConferenceRoomTypeDescriptor"
        }
      ],
      "role": "symbol",
      "title": "EKVirtualConferenceRoomTypeDescriptor",
      "type": "topic",
      "url": "/documentation/eventkit/ekvirtualconferenceroomtypedescriptor"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EK_LOSE_FRACTIONAL_SECONDS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EK_LOSE_FRACTIONAL_SECONDS"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EK_LOSE_FRACTIONAL_SECONDS",
      "kind": "symbol",
      "role": "symbol",
      "title": "EK_LOSE_FRACTIONAL_SECONDS",
      "type": "topic",
      "url": "/documentation/eventkit/ek_lose_fractional_seconds"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EVENTKIT_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EVENTKIT_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EVENTKIT_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "EVENTKIT_EXTERN",
      "type": "topic",
      "url": "/documentation/eventkit/eventkit_extern"
    },
    "doc://com.apple.eventkit/documentation/EventKit/accessing-calendar-using-eventkit-and-eventkitui": {
      "abstract": [
        {
          "text": "Choose and implement the appropriate Calendar access level in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/accessing-calendar-using-eventkit-and-eventkitui",
      "kind": "article",
      "role": "sampleCode",
      "title": "Accessing Calendar using EventKit and EventKitUI",
      "type": "topic",
      "url": "/documentation/eventkit/accessing-calendar-using-eventkit-and-eventkitui"
    },
    "doc://com.apple.eventkit/documentation/EventKit/accessing-the-event-store": {
      "abstract": [
        {
          "text": "Request access to a person’s calendar data through the event store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/accessing-the-event-store",
      "kind": "article",
      "role": "article",
      "title": "Accessing the event store",
      "type": "topic",
      "url": "/documentation/eventkit/accessing-the-event-store"
    },
    "doc://com.apple.eventkit/documentation/EventKit/creating-a-recurring-event": {
      "abstract": [
        {
          "text": "Set up an event or reminder that repeats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/creating-a-recurring-event",
      "kind": "article",
      "role": "article",
      "title": "Creating a recurring event",
      "type": "topic",
      "url": "/documentation/eventkit/creating-a-recurring-event"
    },
    "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders": {
      "abstract": [
        {
          "text": "Create and modify events and reminders in a person’s database.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders",
      "kind": "article",
      "role": "article",
      "title": "Creating events and reminders",
      "type": "topic",
      "url": "/documentation/eventkit/creating-events-and-reminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders": {
      "abstract": [
        {
          "text": "Add, fetch, complete, remove, and sort location-based reminders in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders",
      "kind": "article",
      "role": "sampleCode",
      "title": "Managing Location-Based Reminders",
      "type": "topic",
      "url": "/documentation/eventkit/managing-location-based-reminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders": {
      "abstract": [
        {
          "text": "Fetch events and reminders from the Calendar database.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
      "kind": "article",
      "role": "article",
      "title": "Retrieving events and reminders",
      "type": "topic",
      "url": "/documentation/eventkit/retrieving-events-and-reminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/setting-an-alarm": {
      "abstract": [
        {
          "text": "Alert users of events and reminders with an alarm.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/setting-an-alarm",
      "kind": "article",
      "role": "article",
      "title": "Setting an alarm",
      "type": "topic",
      "url": "/documentation/eventkit/setting-an-alarm"
    },
    "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications": {
      "abstract": [
        {
          "text": "Register for notifications about changes and keep your app up to date.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Updating with notifications",
      "type": "topic",
      "url": "/documentation/eventkit/updating-with-notifications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/accessing-the-event-store",
        "doc://com.apple.eventkit/documentation/EventKit/EKEventStore",
        "doc://com.apple.eventkit/documentation/EventKit/accessing-calendar-using-eventkit-and-eventkitui"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Events-and-reminders",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders",
        "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
        "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
        "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent",
        "doc://com.apple.eventkit/documentation/EventKit/EKReminder"
      ],
      "title": "Events and reminders"
    },
    {
      "anchor": "Calendars",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipant"
      ],
      "title": "Calendars"
    },
    {
      "anchor": "Recurrence",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/creating-a-recurring-event",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceDayOfWeek",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceEnd",
        "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule"
      ],
      "title": "Recurrence"
    },
    {
      "anchor": "Alarms",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/setting-an-alarm",
        "doc://com.apple.eventkit/documentation/EventKit/EKAlarm",
        "doc://com.apple.eventkit/documentation/EventKit/EKStructuredLocation"
      ],
      "title": "Alarms"
    },
    {
      "anchor": "Common-objects",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem",
        "doc://com.apple.eventkit/documentation/EventKit/EKObject",
        "doc://com.apple.eventkit/documentation/EventKit/EKSource"
      ],
      "title": "Common objects"
    },
    {
      "anchor": "Virtual-conferences",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceProvider",
        "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceDescriptor",
        "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceRoomTypeDescriptor"
      ],
      "title": "Virtual conferences"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKError",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code",
        "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/accessing-the-event-store",
                "doc://com.apple.eventkit/documentation/EventKit/EKEventStore",
                "doc://com.apple.eventkit/documentation/EventKit/accessing-calendar-using-eventkit-and-eventkitui"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Events-and-reminders",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders",
                "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
                "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
                "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent",
                "doc://com.apple.eventkit/documentation/EventKit/EKReminder"
              ],
              "title": "Events and reminders"
            },
            {
              "anchor": "Calendars",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipant"
              ],
              "title": "Calendars"
            },
            {
              "anchor": "Recurrence",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/creating-a-recurring-event",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceDayOfWeek",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceEnd",
                "doc://com.apple.eventkit/documentation/EventKit/EKRecurrenceRule"
              ],
              "title": "Recurrence"
            },
            {
              "anchor": "Alarms",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/setting-an-alarm",
                "doc://com.apple.eventkit/documentation/EventKit/EKAlarm",
                "doc://com.apple.eventkit/documentation/EventKit/EKStructuredLocation"
              ],
              "title": "Alarms"
            },
            {
              "anchor": "Common-objects",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem",
                "doc://com.apple.eventkit/documentation/EventKit/EKObject",
                "doc://com.apple.eventkit/documentation/EventKit/EKSource"
              ],
              "title": "Common objects"
            },
            {
              "anchor": "Virtual-conferences",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceProvider",
                "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceDescriptor",
                "doc://com.apple.eventkit/documentation/EventKit/EKVirtualConferenceRoomTypeDescriptor"
              ],
              "title": "Virtual conferences"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKError/Code",
                "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/DATETIME_COMPONENTS",
                "doc://com.apple.eventkit/documentation/EventKit/DATE_COMPONENTS",
                "doc://com.apple.eventkit/documentation/EventKit/EK_LOSE_FRACTIONAL_SECONDS",
                "doc://com.apple.eventkit/documentation/EventKit/EVENTKIT_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKVirtualConferenceRoomTypeDescriptor/title",
          "value": "EKVirtualConferenceRoomTypeDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKVirtualConferenceRoomTypeDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKVirtualConferenceRoomTypeDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKVirtualConferenceRoomTypeDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKVirtualConferenceRoomTypeDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKObject/title",
          "value": "EKObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/title",
          "value": "EKReminder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKReminder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKReminder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKStructuredLocation/title",
          "value": "EKStructuredLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKStructuredLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKStructuredLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKStructuredLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKStructuredLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceEnd/title",
          "value": "EKRecurrenceEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceEnd/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar/title",
          "value": "EKCalendar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKErrorDomain/title",
          "value": "EKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/title",
          "value": "EKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKAlarm/title",
          "value": "EKAlarm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKAlarm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKAlarm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKAlarm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKAlarm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipant/title",
          "value": "EKParticipant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipant/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSource/title",
          "value": "EKSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore/title",
          "value": "EKEventStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKVirtualConferenceProvider/title",
          "value": "EKVirtualConferenceProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKVirtualConferenceProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKVirtualConferenceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKVirtualConferenceProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKVirtualConferenceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem/title",
          "value": "EKCalendarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/title",
          "value": "EKEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule/title",
          "value": "EKRecurrenceRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKVirtualConferenceDescriptor/title",
          "value": "EKVirtualConferenceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKVirtualConferenceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKVirtualConferenceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKVirtualConferenceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKVirtualConferenceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceDayOfWeek/title",
          "value": "EKRecurrenceDayOfWeek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceDayOfWeek/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceDayOfWeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKRecurrenceDayOfWeek/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKRecurrenceDayOfWeek"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
