{
  "abstract": [
    {
      "text": "Display an interface for viewing, selecting, and editing calendar events and reminders.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkitui/documentation/EventKitUI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "EventKitUI",
    "modules": [
      {
        "name": "EventKit UI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "EventKit UI"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On iOS, use the EventKitUI framework to show calendar and reminder information to the user modally. EventKitUI provides view controllers for viewing and editing calendar and reminder information, choosing which calendar to view, and for determining whether to present calendars as read-only or readable and writeable.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The view controllers you’ll use on iOS are:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventViewController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", for displaying existing events.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", for creating, editing, or deleting events.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", for selecting one or more calendars, and to determine whether a calendar has read-only or read-write access.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You present these interfaces from within your app. Upon presentation, the system manages all interactions with the user, notifying you when the interfaces are dismissed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "EventKitUI also provides several configurable classes for selecting a default calendar, displaying buttons, or to enabling the user to select one or more calendars.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "To access the event store, which contains calendar and reminder data, use EventKit. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/EventKit/accessing-the-event-store",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/EventKit/accessing-the-event-store": {
      "abstract": [
        {
          "text": "Request access to a person’s calendar data through the event store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/EventKit/accessing-the-event-store",
      "kind": "article",
      "role": "article",
      "title": "Accessing the event store",
      "type": "topic",
      "url": "/documentation/EventKit/accessing-the-event-store"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI": {
      "abstract": [
        {
          "text": "Display an interface for viewing, selecting, and editing calendar events and reminders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit UI",
      "type": "topic",
      "url": "/documentation/eventkitui"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser": {
      "abstract": [
        {
          "text": "A view controller for determining whether a user may select one or more calendars.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarChooser"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarChooser"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarChooser",
      "type": "topic",
      "url": "/documentation/eventkitui/ekcalendarchooser"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController": {
      "abstract": [
        {
          "text": "A view controller for creating, editing, and deleting calendar events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventEditViewController"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventEditViewController"
        }
      ],
      "role": "symbol",
      "title": "EKEventEditViewController",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewcontroller"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventViewController": {
      "abstract": [
        {
          "text": "A view controller for displaying existing calendar and reminder events, and for optionally editing those events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventViewController"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventViewController"
        }
      ],
      "role": "symbol",
      "title": "EKEventViewController",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventviewcontroller"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EventKitUI-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EventKitUI-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EventKitUI Constants",
      "type": "topic",
      "url": "/documentation/eventkitui/eventkitui-constants"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EventKitUIBundle()": {
      "abstract": [
        {
          "text": "Use to access resources within the app bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventKitUIBundle"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EventKitUIBundle()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventKitUIBundle"
        }
      ],
      "role": "symbol",
      "title": "EventKitUIBundle()",
      "type": "topic",
      "url": "/documentation/eventkitui/eventkituibundle()"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Calendar-Views",
      "identifiers": [
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventViewController"
      ],
      "title": "Calendar Views"
    },
    {
      "anchor": "Calendar-Edits",
      "identifiers": [
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController"
      ],
      "title": "Calendar Edits"
    },
    {
      "anchor": "Calendar-Selection",
      "identifiers": [
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser"
      ],
      "title": "Calendar Selection"
    },
    {
      "anchor": "EventKit-Bundle-Access",
      "identifiers": [
        "doc://com.apple.eventkitui/documentation/EventKitUI/EventKitUIBundle()"
      ],
      "title": "EventKit Bundle Access"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.eventkitui/documentation/EventKitUI/EventKitUI-constants"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Calendar-Views",
              "identifiers": [
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventViewController"
              ],
              "title": "Calendar Views"
            },
            {
              "anchor": "Calendar-Edits",
              "identifiers": [
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController"
              ],
              "title": "Calendar Edits"
            },
            {
              "anchor": "Calendar-Selection",
              "identifiers": [
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser"
              ],
              "title": "Calendar Selection"
            },
            {
              "anchor": "EventKit-Bundle-Access",
              "identifiers": [
                "doc://com.apple.eventkitui/documentation/EventKitUI/EventKitUIBundle()"
              ],
              "title": "EventKit Bundle Access"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.eventkitui/documentation/EventKitUI/EventKitUI-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser/title",
          "value": "EKCalendarChooser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarChooser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarChooser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventViewController/title",
          "value": "EKEventViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewController/title",
          "value": "EKEventEditViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EventKitUIBundle()/title",
          "value": "EventKitUIBundle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EventKitUIBundle()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EventKitUIBundle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkitui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkitui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
