{
  "abstract": [
    {
      "text": "Monitor and debug exceptional conditions in code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ExceptionHandling",
    "modules": [
      {
        "name": "Exception Handling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Exception Handling"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This collection of documents provides the API reference for the Exception Handling",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "framework. This framework provides facilities for monitoring and debugging exceptional",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "conditions in Objective-C code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Currently only one class reference is part of this collection: the reference for",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class, which is defined in ",
              "type": "text"
            },
            {
              "code": "NSExceptionHandler.h",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling": {
      "abstract": [
        {
          "text": "Monitor and debug exceptional conditions in code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling",
      "kind": "symbol",
      "role": "collection",
      "title": "Exception Handling",
      "type": "topic",
      "url": "/documentation/exceptionhandling"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSExceptionHandler",
          "type": "codeVoice"
        },
        {
          "text": " class provides facilities for monitoring and debugging exceptional",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "conditions in Objective-C programs. It works by installing a special uncaught exception",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "handler via the  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "function. Consequently, to use the services of ",
          "type": "text"
        },
        {
          "code": "NSExceptionHandler",
          "type": "codeVoice"
        },
        {
          "text": ", you must not",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "install your own custom uncaught exception handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExceptionHandler"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExceptionHandler"
        }
      ],
      "role": "symbol",
      "title": "NSExceptionHandler",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsexceptionhandler"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExceptionHandling Constants",
      "type": "topic",
      "url": "/documentation/exceptionhandling/exceptionhandling-constants"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExceptionHandling Enumerations",
      "type": "topic",
      "url": "/documentation/exceptionhandling/exceptionhandling-enumerations"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExceptionHandling Functions",
      "type": "topic",
      "url": "/documentation/exceptionhandling/exceptionhandling-functions"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/nsexceptionhandlerdelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSExceptionHandlerDelegate",
          "type": "codeVoice"
        },
        {
          "text": " informal protocol describes methods that ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "objects call on their delegates when exceptions occur. An ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "object does not need to have a delegate. When one does, these delegate methods are",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "asked to approve exception handling and logging for each monitored ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/nsexceptionhandlerdelegate",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSExceptionHandlerDelegate",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsexceptionhandlerdelegate"
    },
    "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler": {
      "abstract": [
        {
          "text": "Changes the top-level error handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "NSSetUncaughtExceptionHandler"
        },
        {
          "kind": "text",
          "text": "(((NSException) -> Void)?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSetUncaughtExceptionHandler(_:)",
      "type": "topic",
      "url": "/documentation/foundation/1409609-nssetuncaughtexceptionhandler"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/nsexceptionhandlerdelegate"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-constants",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-functions"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Protocols",
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/nsexceptionhandlerdelegate"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-constants",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/title",
          "value": "NSExceptionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExceptionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExceptionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~11409609-nssetuncaughtexceptionhandler/title",
          "value": "NSSetUncaughtExceptionHandler"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exceptionhandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exceptionhandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
