{
  "abstract": [
    {
      "text": "Provide functionality so developer tools can manage execution policy exceptions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ExecutionPolicy",
    "modules": [
      {
        "name": "Execution Policy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Execution Policy"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This framework provides the ability for developer tools to manage execution policy exceptions for software that’s built locally.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy": {
      "abstract": [
        {
          "text": "Provide functionality so developer tools can manage execution policy exceptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy",
      "kind": "symbol",
      "role": "collection",
      "title": "Execution Policy",
      "type": "topic",
      "url": "/documentation/executionpolicy"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperTool": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EPDeveloperTool"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperTool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EPDeveloperTool"
        }
      ],
      "role": "symbol",
      "title": "EPDeveloperTool",
      "type": "topic",
      "url": "/documentation/executionpolicy/epdevelopertool"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EPError"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EPError"
        }
      ],
      "role": "symbol",
      "title": "EPError",
      "type": "topic",
      "url": "/documentation/executionpolicy/eperror-swift.struct"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPExecutionPolicy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EPExecutionPolicy"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPExecutionPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EPExecutionPolicy"
        }
      ],
      "role": "symbol",
      "title": "EPExecutionPolicy",
      "type": "topic",
      "url": "/documentation/executionpolicy/epexecutionpolicy"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/executionpolicy-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/executionpolicy-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExecutionPolicy Constants",
      "type": "topic",
      "url": "/documentation/executionpolicy/executionpolicy-constants"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/executionpolicy-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/executionpolicy-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExecutionPolicy Enumerations",
      "type": "topic",
      "url": "/documentation/executionpolicy/executionpolicy-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperTool",
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPExecutionPolicy"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/executionpolicy-enumerations",
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/executionpolicy-constants"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperTool",
                "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPExecutionPolicy"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/executionpolicy-enumerations",
                "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/executionpolicy-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPExecutionPolicy/title",
          "value": "EPExecutionPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPExecutionPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EPExecutionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPExecutionPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EPExecutionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperTool/title",
          "value": "EPDeveloperTool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperTool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperTool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperTool/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperTool"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/executionpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/executionpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
