{
  "abstract": [
    {
      "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ExposureNotification",
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.5",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.5",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.5",
        "name": "Mac Catalyst"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Exposure Notification"
  },
  "primaryContentSections": [
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the Exposure Notification framework to inform people of potential exposure to COVID-19, the disease caused by the SARS-CoV-2 virus. You can build a notification system that employs random, rotating keys and identifiers to convey positive diagnoses in addition to data such as associated symptoms, proximity, and duration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Establish-User-Roles",
          "level": 3,
          "text": "Establish User Roles",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ExposureNotification framework defines two user roles:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "When a user has a confirmed or probable diagnosis of COVID-19 (as defined by the Health Authority), the framework identifies them as ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "affected",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " and shares their diagnosis keys to alert other users to potential exposure.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Affected user",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "To assign a user the ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "potentially exposed",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " role, use the framework to determine whether a set of temporary exposure keys indicate proximity to an affected user. If so, the app can retrieve additional information such as date and duration from the framework.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Potentially exposed user",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Before you can develop an app that uses ExposureNotification, you need the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.exposure-notification",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " entitlement. For more information on this entitlement, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/contact/request/download/Exposure_Notification_Addendum.pdf",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". To get permission to use this entitlement, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/contact/request/exposure-notification-entitlement",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Identify-Your-Apps-Region",
          "level": 3,
          "text": "Identify Your App’s Region",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "All EN apps must specify the region for which they work by adding a key called ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to the app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file. The value for ",
              "type": "text"
            },
            {
              "code": "ENDeveloperRegion",
              "type": "codeVoice"
            },
            {
              "text": " is set to a string that represents the app’s region. This value can be an ISO 3166-1 country code (for example, “CA” for Canada), or the ISO 3166-1/3166-2 country code plus subdivision code (“US-CA” for California).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Explicitly set the associated domain link to your region code. Avoid using wildcards because they can impact system operations. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Specify-Exposure-Notification-API-Version",
          "level": 3,
          "text": "Specify Exposure Notification API Version",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "iOS 13.7 introduces a new method of calculating the user’s Exposure Risk Value, described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Apps can implement this new method, or continue to use the calculation method introduced in earlier versions of iOS. To choose your app’s approach, add an entry to your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file with a key of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". To use the new approach, specify a value of ",
              "type": "text"
            },
            {
              "code": "2",
              "type": "codeVoice"
            },
            {
              "text": ". To use the original approach, specify a value of ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Support-Exposure-Notification-Express",
          "level": 3,
          "text": "Support Exposure Notification Express",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Starting with iOS 13.7, Health Authorities can inform users of potential exposure to COVID-19 without a dedicated Exposure Notification app. This feature is called Exposure Notification Express and must be enabled by a Health Authority. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains": {
      "abstract": [
        {
          "text": "The associated domains for specific services, such as shared web credentials, universal links, and App Clips.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains",
      "kind": "symbol",
      "role": "symbol",
      "title": "Associated Domains Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.exposure-notification": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may use exposure notification.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.exposure-notification",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.exposure-notification",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.exposure-notification"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion": {
      "abstract": [
        {
          "text": "A number that specifies the version of the API to use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "ENAPIVersion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/ENAPIVersion"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion": {
      "abstract": [
        {
          "text": "A string that specifies the region that the app supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion",
      "kind": "symbol",
      "role": "symbol",
      "title": "ENDeveloperRegion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/ENDeveloperRegion"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAuthorizationStatus": {
      "abstract": [
        {
          "text": "A set of cases that indicates the authorization status for the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ENAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/exposurenotification/enauthorizationstatus"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDetectExposuresHandler": {
      "abstract": [
        {
          "text": "The definition of a handler that returns exposure summaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENDetectExposuresHandler"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDetectExposuresHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDetectExposuresHandler"
        }
      ],
      "role": "symbol",
      "title": "ENDetectExposuresHandler",
      "type": "topic",
      "url": "/documentation/exposurenotification/endetectexposureshandler"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError": {
      "abstract": [
        {
          "text": "Errors that the exposure notification framework issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENError"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENError"
        }
      ],
      "role": "symbol",
      "title": "ENError",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code": {
      "abstract": [
        {
          "text": "Error codes that the exposure notification framework issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorDomain": {
      "abstract": [
        {
          "text": "The domain for an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ENErrorDomain",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerrordomain"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorHandler": {
      "abstract": [
        {
          "text": "The handler for error conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENErrorHandler"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorHandler"
        }
      ],
      "role": "symbol",
      "title": "ENErrorHandler",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerrorhandler"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorOutType": {
      "abstract": [
        {
          "text": "Type for returning NSError’s from functions. Avoids long and repetitious method signatures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENErrorOutType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorOutType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorOutType"
        }
      ],
      "role": "symbol",
      "title": "ENErrorOutType",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerrorouttype"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration": {
      "abstract": [
        {
          "text": "The object that contains parameters for configuring exposure notification risk scoring behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureConfiguration"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ENExposureConfiguration",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDaySummary": {
      "abstract": [
        {
          "text": "The summary of exposure information for a single day.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureDaySummary"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDaySummary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureDaySummary"
        }
      ],
      "role": "symbol",
      "title": "ENExposureDaySummary",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredaysummary"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary": {
      "abstract": [
        {
          "text": "A summary of exposures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureDetectionSummary"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureDetectionSummary"
        }
      ],
      "role": "symbol",
      "title": "ENExposureDetectionSummary",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredetectionsummary"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureSummaryItem": {
      "abstract": [
        {
          "text": "The summary of exposures for a specific time period or report type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureSummaryItem"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureSummaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureSummaryItem"
        }
      ],
      "role": "symbol",
      "title": "ENExposureSummaryItem",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuresummaryitem"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow": {
      "abstract": [
        {
          "text": "A set of scan events from observed beacons within a time span.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureWindow"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureWindow"
        }
      ],
      "role": "symbol",
      "title": "ENExposureWindow",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposurewindow"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetDiagnosisKeysHandler": {
      "abstract": [
        {
          "text": "The definition of a handler that returns diagnosis keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENGetDiagnosisKeysHandler"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetDiagnosisKeysHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENGetDiagnosisKeysHandler"
        }
      ],
      "role": "symbol",
      "title": "ENGetDiagnosisKeysHandler",
      "type": "topic",
      "url": "/documentation/exposurenotification/engetdiagnosiskeyshandler"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetExposureInfoHandler": {
      "abstract": [
        {
          "text": "The definition of a handler that receives exposure info.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENGetExposureInfoHandler"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetExposureInfoHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENGetExposureInfoHandler"
        }
      ],
      "role": "symbol",
      "title": "ENGetExposureInfoHandler",
      "type": "topic",
      "url": "/documentation/exposurenotification/engetexposureinfohandler"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager": {
      "abstract": [
        {
          "text": "A class that manages exposure notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENManager"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENManager"
        }
      ],
      "role": "symbol",
      "title": "ENManager",
      "type": "topic",
      "url": "/documentation/exposurenotification/enmanager"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightDefaultV2": {
      "abstract": [
        {
          "text": "This weight is not used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENRiskWeightDefaultV2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightDefaultV2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENRiskWeightDefaultV2"
        }
      ],
      "role": "symbol",
      "title": "ENRiskWeightDefaultV2",
      "type": "topic",
      "url": "/documentation/exposurenotification/enriskweightdefaultv2"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightMaxV2": {
      "abstract": [
        {
          "text": "This weight is not used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENRiskWeightMaxV2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightMaxV2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENRiskWeightMaxV2"
        }
      ],
      "role": "symbol",
      "title": "ENRiskWeightMaxV2",
      "type": "topic",
      "url": "/documentation/exposurenotification/enriskweightmaxv2"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance": {
      "abstract": [
        {
          "text": "The aggregation of attenuations of beacons received during a scan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENScanInstance"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENScanInstance"
        }
      ],
      "role": "symbol",
      "title": "ENScanInstance",
      "type": "topic",
      "url": "/documentation/exposurenotification/enscaninstance"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus": {
      "abstract": [
        {
          "text": "A set of cases that represents the overall status of exposure notification on the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENStatus"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENStatus"
        }
      ],
      "role": "symbol",
      "title": "ENStatus",
      "type": "topic",
      "url": "/documentation/exposurenotification/enstatus"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStringify": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ENStringify"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStringify",
      "kind": "symbol",
      "role": "symbol",
      "title": "ENStringify",
      "type": "topic",
      "url": "/documentation/exposurenotification/enstringify"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStringifyExpansion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ENStringifyExpansion"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStringifyExpansion",
      "kind": "symbol",
      "role": "symbol",
      "title": "ENStringifyExpansion",
      "type": "topic",
      "url": "/documentation/exposurenotification/enstringifyexpansion"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EN_API_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "EN_API_AVAILABLE",
      "type": "topic",
      "url": "/documentation/exposurenotification/en_api_available"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EN_API_AVAILABLE_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "EN_API_AVAILABLE_EXPORT",
      "type": "topic",
      "url": "/documentation/exposurenotification/en_api_available_export"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_EXPORT_V2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EN_API_AVAILABLE_EXPORT_V2"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_EXPORT_V2",
      "kind": "symbol",
      "role": "symbol",
      "title": "EN_API_AVAILABLE_EXPORT_V2",
      "type": "topic",
      "url": "/documentation/exposurenotification/en_api_available_export_v2"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_V2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EN_API_AVAILABLE_V2"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_V2",
      "kind": "symbol",
      "role": "symbol",
      "title": "EN_API_AVAILABLE_V2",
      "type": "topic",
      "url": "/documentation/exposurenotification/en_api_available_v2"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_V3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EN_API_AVAILABLE_V3"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_V3",
      "kind": "symbol",
      "role": "symbol",
      "title": "EN_API_AVAILABLE_V3",
      "type": "topic",
      "url": "/documentation/exposurenotification/en_api_available_v3"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_V5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EN_API_AVAILABLE_V5"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_V5",
      "kind": "symbol",
      "role": "symbol",
      "title": "EN_API_AVAILABLE_V5",
      "type": "topic",
      "url": "/documentation/exposurenotification/en_api_available_v5"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_FEATURE_GENERAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EN_FEATURE_GENERAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_FEATURE_GENERAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EN_FEATURE_GENERAL"
        }
      ],
      "role": "symbol",
      "title": "EN_FEATURE_GENERAL",
      "type": "topic",
      "url": "/documentation/exposurenotification/en_feature_general"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/building-an-app-to-notify-users-of-covid-19-exposure": {
      "abstract": [
        {
          "text": "Inform people when they may have been exposed to COVID-19.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/building-an-app-to-notify-users-of-covid-19-exposure",
      "kind": "article",
      "role": "sampleCode",
      "title": "Building an App to Notify Users of COVID-19 Exposure",
      "type": "topic",
      "url": "/documentation/exposurenotification/building-an-app-to-notify-users-of-covid-19-exposure"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api": {
      "abstract": [
        {
          "text": "Update Exposure Notifications configuration values from a Public Health Authority’s server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api",
      "kind": "article",
      "role": "article",
      "title": "Changing Configuration Values Using the Server‑to‑Server API",
      "type": "topic",
      "url": "/documentation/exposurenotification/changing-configuration-values-using-the-server-to-server-api"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications": {
      "abstract": [
        {
          "text": "Define how Exposure Notifications work for a region by assigning server-based key-value pairs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications",
      "kind": "article",
      "role": "article",
      "title": "Configuring Exposure Notifications",
      "type": "topic",
      "url": "/documentation/exposurenotification/configuring-exposure-notifications"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits": {
      "abstract": [
        {
          "text": "The limits for the parameters you use in exposure risk calculations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Exposure Parameter Limits",
      "type": "topic",
      "url": "/documentation/exposurenotification/exposure-parameter-limits"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server": {
      "abstract": [
        {
          "text": "Ensure that your server meets the requirements for supporting Exposure Notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server",
      "kind": "article",
      "role": "article",
      "title": "Setting Up a Key Server",
      "type": "topic",
      "url": "/documentation/exposurenotification/setting-up-a-key-server"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express": {
      "abstract": [
        {
          "text": "Configure servers to notify users of potential exposures to COVID-19 without an app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Supporting Exposure Notifications Express",
      "type": "topic",
      "url": "/documentation/exposurenotification/supporting-exposure-notifications-express"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5": {
      "abstract": [
        {
          "text": "Prepare your Exposure Notifications app to run on a previous version of iOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5",
      "kind": "article",
      "role": "article",
      "title": "Supporting Exposure Notifications in iOS 12.5",
      "type": "topic",
      "url": "/documentation/exposurenotification/supporting-exposure-notifications-in-ios-12-5"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/testing-exposure-notifications-apps-in-ios-13-7-and-later": {
      "abstract": [
        {
          "text": "Perform end-to-end validation of Exposure Notifications apps on a device by manually loading configuration files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/testing-exposure-notifications-apps-in-ios-13-7-and-later",
      "kind": "article",
      "role": "article",
      "title": "Testing Exposure Notifications Apps in iOS 13.7 and Later",
      "type": "topic",
      "url": "/documentation/exposurenotification/testing-exposure-notifications-apps-in-ios-13-7-and-later"
    },
    "https://developer.apple.com/contact/request/download/Exposure_Notification_Addendum.pdf": {
      "identifier": "https://developer.apple.com/contact/request/download/Exposure_Notification_Addendum.pdf",
      "title": "Exposure Notification APIs Addendum",
      "titleInlineContent": [
        {
          "text": "Exposure Notification APIs Addendum",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/contact/request/download/Exposure_Notification_Addendum.pdf"
    },
    "https://developer.apple.com/contact/request/exposure-notification-entitlement": {
      "identifier": "https://developer.apple.com/contact/request/exposure-notification-entitlement",
      "title": "Exposure Notification Entitlement Request",
      "titleInlineContent": [
        {
          "text": "Exposure Notification Entitlement Request",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/contact/request/exposure-notification-entitlement"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/building-an-app-to-notify-users-of-covid-19-exposure",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/testing-exposure-notifications-apps-in-ios-13-7-and-later",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Exposures",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits"
      ],
      "title": "Exposures"
    },
    {
      "anchor": "Summaries",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDaySummary",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureSummaryItem"
      ],
      "title": "Summaries"
    },
    {
      "anchor": "Status",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAuthorizationStatus",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus"
      ],
      "title": "Status"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorDomain",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorHandler"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightDefaultV2",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightMaxV2",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_FEATURE_GENERAL"
      ],
      "title": "Variables"
    },
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDetectExposuresHandler",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorOutType",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetDiagnosisKeysHandler",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetExposureInfoHandler"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/building-an-app-to-notify-users-of-covid-19-exposure",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/testing-exposure-notifications-apps-in-ios-13-7-and-later",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Exposures",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits"
              ],
              "title": "Exposures"
            },
            {
              "anchor": "Summaries",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDaySummary",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureSummaryItem"
              ],
              "title": "Summaries"
            },
            {
              "anchor": "Status",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAuthorizationStatus",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus"
              ],
              "title": "Status"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorDomain",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorHandler"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStringify",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStringifyExpansion",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_EXPORT",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_EXPORT_V2",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_V2",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_V3",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_API_AVAILABLE_V5",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/EN_FEATURE_GENERAL"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightDefaultV2",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightMaxV2"
              ],
              "title": "Enumeration Cases"
            },
            {
              "anchor": "Type-Aliases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDetectExposuresHandler",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorOutType",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetDiagnosisKeysHandler",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetExposureInfoHandler"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskWeightMaxV2/title",
          "value": "ENRiskWeightMaxV2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskWeightMaxV2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENRiskWeightMaxV2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus/title",
          "value": "ENStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetDiagnosisKeysHandler/title",
          "value": "ENGetDiagnosisKeysHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetDiagnosisKeysHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENGetDiagnosisKeysHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetDiagnosisKeysHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENGetDiagnosisKeysHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/title",
          "value": "ENExposureConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDaySummary/title",
          "value": "ENExposureDaySummary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDaySummary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureDaySummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDaySummary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureDaySummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetExposureInfoHandler/title",
          "value": "ENGetExposureInfoHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetExposureInfoHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENGetExposureInfoHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetExposureInfoHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENGetExposureInfoHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskWeightDefaultV2/title",
          "value": "ENRiskWeightDefaultV2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskWeightDefaultV2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENRiskWeightDefaultV2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1EN_FEATURE_GENERAL/title",
          "value": "EN_FEATURE_GENERAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1EN_FEATURE_GENERAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EN_FEATURE_GENERAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/title",
          "value": "ENManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/title",
          "value": "ENErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/title",
          "value": "ENExposureWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureSummaryItem/title",
          "value": "ENExposureSummaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureSummaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureSummaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary/title",
          "value": "ENExposureDetectionSummary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureDetectionSummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureDetectionSummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDetectExposuresHandler/title",
          "value": "ENDetectExposuresHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDetectExposuresHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDetectExposuresHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDetectExposuresHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDetectExposuresHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorDomain/title",
          "value": "ENErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENAuthorizationStatus/title",
          "value": "ENAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENScanInstance/title",
          "value": "ENScanInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENScanInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENScanInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENScanInstance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENScanInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorOutType/title",
          "value": "ENErrorOutType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorOutType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorOutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorOutType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorOutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorHandler/title",
          "value": "ENErrorHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
