{
  "abstract": [
    {
      "text": "Create executable bundles to extend the functionality of other apps by presenting a user interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.extensionkit/documentation/ExtensionKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ExtensionKit",
    "modules": [
      {
        "name": "ExtensionKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.1",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "16.1",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "ExtensionKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Extensions are executable code bundles, in one app that perform functions in a second, ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "host",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " app. Host apps declare ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "extension points",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " that control the kinds of functionality its extensions can implement. Extensions allow iOS and Mac apps to include code that runs inside system apps. For example, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Messages",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides extension points so apps can create ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Messages#1864841",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Messages automatically finds extension bundles that target its extension points and makes them available in its app drawer. A Mac app can also declare its own extension points so that other apps can extend the Mac app’s functionality.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Prior to macOS 13, apps use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property lists to declare and configure extensions. ExtensionKit supports this approach, but also adds the ability to configure extensions and extension points entirely in Swift code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Extensions come in two basic forms: UI and non-UI.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Vend remote views and view controllers that the host app adds to its own view hierarchy.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "UI extensions",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Present no user interface, but perform some work on behalf of the host app.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Non-UI extensions",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "An iMessage app, which can include sophisticated user interfaces — even entire games — is an example of a UI extension. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SiriKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " app intents, which gives people the ability to interact with your app using Siri, is an example of a non-UI extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use ExtensionKit, in combination with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ExtensionFoundation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", to create extensions and extension points for UI extensions. To create extensions with no user interface, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ExtensionFoundation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtension",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExtension"
    },
    "doc://com.apple.documentation/documentation/ExtensionFoundation": {
      "abstract": [
        {
          "text": "Create executable bundles to extend the functionality of other apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ExtensionFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "ExtensionFoundation",
      "type": "topic",
      "url": "/documentation/ExtensionFoundation"
    },
    "doc://com.apple.documentation/documentation/Messages": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Messages",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/Messages"
    },
    "doc://com.apple.documentation/documentation/Messages#1864841": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Messages#1864841",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/Messages"
    },
    "doc://com.apple.documentation/documentation/SiriKit": {
      "abstract": [
        {
          "text": "Empower users to interact with their devices through voice, intelligent suggestions, and personalized workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SiriKit",
      "kind": "article",
      "role": "collection",
      "title": "SiriKit",
      "type": "topic",
      "url": "/documentation/SiriKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit": {
      "abstract": [
        {
          "text": "Create executable bundles to extend the functionality of other apps by presenting a user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ExtensionKit",
      "type": "topic",
      "url": "/documentation/extensionkit"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/AppExtensionScene": {
      "abstract": [
        {
          "text": "A protocol that defines the user interface for an application extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppExtensionScene"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/AppExtensionScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AppExtensionScene"
        }
      ],
      "role": "symbol",
      "title": "AppExtensionScene",
      "type": "topic",
      "url": "/documentation/extensionkit/appextensionscene"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/AppExtensionSceneBuilder": {
      "abstract": [
        {
          "text": "A custom parameter attribute that constructs extension scenes from closures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppExtensionSceneBuilder"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/AppExtensionSceneBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AppExtensionSceneBuilder"
        }
      ],
      "role": "symbol",
      "title": "AppExtensionSceneBuilder",
      "type": "topic",
      "url": "/documentation/extensionkit/appextensionscenebuilder"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/AppExtensionSceneConfiguration": {
      "abstract": [
        {
          "text": "An object that holds configuration options for an extension scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppExtensionSceneConfiguration"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/AppExtensionSceneConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AppExtensionSceneConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AppExtensionSceneConfiguration",
      "type": "topic",
      "url": "/documentation/extensionkit/appextensionsceneconfiguration"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXAppExtensionBrowserViewController": {
      "abstract": [
        {
          "text": "A view controller that allows users to enable and disable extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EXAppExtensionBrowserViewController"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXAppExtensionBrowserViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EXAppExtensionBrowserViewController"
        }
      ],
      "role": "symbol",
      "title": "EXAppExtensionBrowserViewController",
      "type": "topic",
      "url": "/documentation/extensionkit/exappextensionbrowserviewcontroller"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController": {
      "abstract": [
        {
          "text": "A view controller that hosts remote views provided by an extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EXHostViewController"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EXHostViewController"
        }
      ],
      "role": "symbol",
      "title": "EXHostViewController",
      "type": "topic",
      "url": "/documentation/extensionkit/exhostviewcontroller"
    },
    "doc://com.apple.extensionkit/documentation/ExtensionKit/PrimitiveAppExtensionScene": {
      "abstract": [
        {
          "text": "A primitive you use to compose specialized app extension points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PrimitiveAppExtensionScene"
        }
      ],
      "identifier": "doc://com.apple.extensionkit/documentation/ExtensionKit/PrimitiveAppExtensionScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PrimitiveAppExtensionScene"
        }
      ],
      "role": "symbol",
      "title": "PrimitiveAppExtensionScene",
      "type": "topic",
      "url": "/documentation/extensionkit/primitiveappextensionscene"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "UI-App-Extensions",
      "identifiers": [
        "doc://com.apple.extensionkit/documentation/ExtensionKit/AppExtensionScene",
        "doc://com.apple.extensionkit/documentation/ExtensionKit/AppExtensionSceneConfiguration",
        "doc://com.apple.extensionkit/documentation/ExtensionKit/AppExtensionSceneBuilder",
        "doc://com.apple.extensionkit/documentation/ExtensionKit/PrimitiveAppExtensionScene"
      ],
      "title": "UI App Extensions"
    },
    {
      "anchor": "Host-Apps",
      "identifiers": [
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController",
        "doc://com.apple.extensionkit/documentation/ExtensionKit/EXAppExtensionBrowserViewController"
      ],
      "title": "Host Apps"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Host-Apps",
              "identifiers": [
                "doc://com.apple.extensionkit/documentation/ExtensionKit/EXHostViewController",
                "doc://com.apple.extensionkit/documentation/ExtensionKit/EXAppExtensionBrowserViewController"
              ],
              "title": "Host Apps"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController/title",
          "value": "EXHostViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXHostViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EXHostViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXAppExtensionBrowserViewController/title",
          "value": "EXAppExtensionBrowserViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXAppExtensionBrowserViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EXAppExtensionBrowserViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.extensionkit~1documentation~1ExtensionKit~1EXAppExtensionBrowserViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EXAppExtensionBrowserViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/extensionkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/extensionkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
