{
  "abstract": [
    {
      "text": "Add actions to the document browser’s context menu.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileproviderui/documentation/FileProviderUI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "FileProviderUI",
    "modules": [
      {
        "name": "File Provider UI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "File Provider UI"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the File Provider UI extension to add custom actions to your File Provider extension. These actions appear if the user long presses an item while browsing your file provider’s content. When the user selects your action, the system displays your custom user interface, where the user completes the action. After the user is finished, you must explicitly cancel or complete the action.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more about File Provider extensions, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/FileProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more about creating extensions, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/FileProvider"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI": {
      "abstract": [
        {
          "text": "Add actions to the document browser’s context menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider UI",
      "type": "topic",
      "url": "/documentation/fileproviderui"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController": {
      "abstract": [
        {
          "text": "The custom user interface used to perform a selected action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FPUIActionExtensionViewController"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FPUIActionExtensionViewController"
        }
      ],
      "role": "symbol",
      "title": "FPUIActionExtensionViewController",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpuiactionextensionviewcontroller"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for errors raised by the File Provider UI extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FPUIErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FPUIErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "FPUIErrorDomain",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpuierrordomain"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIExtensionErrorCode": {
      "abstract": [
        {
          "text": "The error codes for errors raised by the File Provider UI extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FPUIExtensionErrorCode"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIExtensionErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FPUIExtensionErrorCode"
        }
      ],
      "role": "symbol",
      "title": "FPUIExtensionErrorCode",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpuiextensionerrorcode"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/adding-actions-to-the-context-menu": {
      "abstract": [
        {
          "text": "Present custom actions from your File Provider extension in the system’s file browser.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/adding-actions-to-the-context-menu",
      "kind": "article",
      "role": "article",
      "title": "Adding Actions to the Context Menu",
      "type": "topic",
      "url": "/documentation/fileproviderui/adding-actions-to-the-context-menu"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/fileproviderui-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/fileproviderui-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FileProviderUI Data Types",
      "type": "topic",
      "url": "/documentation/fileproviderui/fileproviderui-data-types"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214",
      "title": "App Extension Programming Guide",
      "titleInlineContent": [
        {
          "text": "App Extension Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Document-Browser-Customization",
      "identifiers": [
        "doc://com.apple.fileproviderui/documentation/FileProviderUI/adding-actions-to-the-context-menu",
        "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController"
      ],
      "title": "Document Browser Customization"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIExtensionErrorCode",
        "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIErrorDomain"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.fileproviderui/documentation/FileProviderUI/fileproviderui-data-types"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Document-Browser-Customization",
              "identifiers": [
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/adding-actions-to-the-context-menu",
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController"
              ],
              "title": "Document Browser Customization"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIExtensionErrorCode",
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIErrorDomain"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/fileproviderui-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIExtensionErrorCode/title",
          "value": "FPUIExtensionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIExtensionErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIExtensionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIExtensionErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIExtensionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIErrorDomain/title",
          "value": "FPUIErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController/title",
          "value": "FPUIActionExtensionViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIActionExtensionViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIActionExtensionViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileproviderui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileproviderui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
