{
  "abstract": [
    {
      "text": "Modify the Finder’s user interface to express file synchronization and control.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Finder-Sync/documentation/FinderSync"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "FinderSync",
    "modules": [
      {
        "name": "Finder Sync"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.10",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Finder Sync"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use Finder Sync to cleanly and safely modify the Finder’s user interface to express file synchronization status and control. Unlike most extension points, Finder Sync doesn’t add features to a host app. Instead, it lets you modify the behavior of the Finder itself.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use this framework when you need to synchronize the contents of a local folder with a remote data source. Then provide visual feedback to the Finder by extending the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class and overriding appearance methods defined within the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To learn more about creating a Finder Sync extension, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Finder.html#//apple_ref/doc/uid/TP40014214-CH15",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Finder-Sync/documentation/FinderSync": {
      "abstract": [
        {
          "text": "Modify the Finder’s user interface to express file synchronization and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync",
      "kind": "symbol",
      "role": "collection",
      "title": "Finder Sync",
      "type": "topic",
      "url": "/documentation/findersync"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class": {
      "abstract": [
        {
          "text": "A type to subclass to add badges, custom shortcut menus, and toolbar buttons to the Finder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FIFinderSync"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIFinderSync"
        }
      ],
      "role": "symbol",
      "title": "FIFinderSync",
      "type": "topic",
      "url": "/documentation/findersync/fifindersync-swift.class"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController": {
      "abstract": [
        {
          "text": "A controller that acts as a bridge between your Finder Sync extension and the Finder itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FIFinderSyncController"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIFinderSyncController"
        }
      ],
      "role": "symbol",
      "title": "FIFinderSyncController",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol": {
      "abstract": [
        {
          "text": "The group of methods to implement for modifying the Finder user interface to express file synchronization status and control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FIFinderSyncProtocol"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIFinderSyncProtocol"
        }
      ],
      "role": "symbol",
      "title": "FIFinderSyncProtocol",
      "type": "topic",
      "url": "/documentation/findersync/fifindersyncprotocol"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FinderSyncEnumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FinderSyncEnumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FinderSync Enumerations",
      "type": "topic",
      "url": "/documentation/findersync/findersyncenumerations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Finder.html#//apple_ref/doc/uid/TP40014214-CH15": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Finder.html#//apple_ref/doc/uid/TP40014214-CH15",
      "title": "Finder Sync",
      "titleInlineContent": [
        {
          "text": "Finder Sync",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Finder.html#//apple_ref/doc/uid/TP40014214-CH15"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214",
      "title": "App Extension Programming Guide",
      "titleInlineContent": [
        {
          "text": "App Extension Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol"
      ],
      "title": "Protocols"
    },
    {
      "abstract": [
        {
          "text": " ",
          "type": "text"
        }
      ],
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FinderSyncEnumerations"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSync-swift.class",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Protocols",
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncProtocol"
              ],
              "title": "Protocols"
            },
            {
              "abstract": [
                {
                  "text": " ",
                  "type": "text"
                }
              ],
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FinderSyncEnumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSync-swift.class/title",
          "value": "FIFinderSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSync-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSync-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController/title",
          "value": "FIFinderSyncController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSyncController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSyncController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol/title",
          "value": "FIFinderSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSync"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/findersync"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/findersync"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
