{
  "abstract": [
    {
      "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ForceFeedback",
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Force Feedback"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Force Feedback framework contains the public interfaces to the Force Feedback implementation in macOS, including an API that supports the development of Force Feedback plug-ins.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Constants",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-constants"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Data Types",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-data-types"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Enumerations",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h": {
      "abstract": [
        {
          "text": "Public Interfaces to the Force Feedback implementation in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Structures",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-structures"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h": {
      "abstract": [
        {
          "text": "Constants used in the public interfaces to the Force Feedback implementation in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedbackConstants.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedbackconstants-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h": {
      "abstract": [
        {
          "text": "Public Interfaces and constants used to develop Force Feedback plugIns.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOForceFeedbackLib.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/ioforcefeedbacklib-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIMajorRev": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFFAPIMajorRev"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIMajorRev",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFFAPIMajorRev"
        }
      ],
      "role": "symbol",
      "title": "kFFAPIMajorRev",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffapimajorrev"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIMinorAndBugRev": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFFAPIMinorAndBugRev"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIMinorAndBugRev",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFFAPIMinorAndBugRev"
        }
      ],
      "role": "symbol",
      "title": "kFFAPIMinorAndBugRev",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffapiminorandbugrev"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPINonRelRev": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFFAPINonRelRev"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPINonRelRev",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFFAPINonRelRev"
        }
      ],
      "role": "symbol",
      "title": "kFFAPINonRelRev",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffapinonrelrev"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIStage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFFAPIStage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIStage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFFAPIStage"
        }
      ],
      "role": "symbol",
      "title": "kFFAPIStage",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffapistage"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPIMajorRev": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFPlugInAPIMajorRev"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPIMajorRev",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFPlugInAPIMajorRev",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffpluginapimajorrev"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPIMinorAndBugRev": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFPlugInAPIMinorAndBugRev"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPIMinorAndBugRev",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFPlugInAPIMinorAndBugRev",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffpluginapiminorandbugrev"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPINonRelRev": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFPlugInAPINonRelRev"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPINonRelRev",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFPlugInAPINonRelRev",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffpluginapinonrelrev"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPIStage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFPlugInAPIStage"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPIStage",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFPlugInAPIStage",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffpluginapistage"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIMajorRev",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIMinorAndBugRev",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPINonRelRev",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIStage"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIMajorRev",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIMinorAndBugRev",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPINonRelRev",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFAPIStage",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPIMajorRev",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPIMinorAndBugRev",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPINonRelRev",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFPlugInAPIStage"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1kFFAPIStage/title",
          "value": "kFFAPIStage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1kFFAPIStage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFFAPIStage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1kFFAPIMajorRev/title",
          "value": "kFFAPIMajorRev"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1kFFAPIMajorRev/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFFAPIMajorRev"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1kFFAPINonRelRev/title",
          "value": "kFFAPINonRelRev"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1kFFAPINonRelRev/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFFAPINonRelRev"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1kFFAPIMinorAndBugRev/title",
          "value": "kFFAPIMinorAndBugRev"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1kFFAPIMinorAndBugRev/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFFAPIMinorAndBugRev"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
