{
  "abstract": [
    {
      "text": "Conduct secure, authenticated network transactions.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "GSS",
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "5.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "5.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.14",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "GSS"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The open source Generic Security Service Application Programming Interface (GSS-API) defines a standardized interface through which the operating system vends secure data transport operations. The GSS framework provides an implementation of the interface and the underlying libraries.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Using GSS-API, you can:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a security context in which data can be passed between applications. A ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "context",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": " represents a “state of trust” between two applications. Applications that share a context recognize each other and permit data transfers as long as the context lasts.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Apply one or more types of protection, known as ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "security services",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ", to the data to be transmitted. For more on security services, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Security",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Perform data conversion, error-checking, delegation of user privileges, information display, and identity comparison.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "https://tools.ietf.org/html/rfc2743",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the definitive description of the GSS-API 2, and ",
              "type": "text"
            },
            {
              "identifier": "https://tools.ietf.org/html/rfc2744",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for a description of the related C bindings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/Security"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSSAPI_CALLCONV": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSSAPI_CALLCONV"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSAPI_CALLCONV",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSSAPI_CALLCONV",
      "type": "topic",
      "url": "/documentation/gss/gssapi_callconv"
    },
    "doc://com.apple.gss/documentation/GSS/GSSAPI_CPP_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSSAPI_CPP_END"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSAPI_CPP_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSSAPI_CPP_END",
      "type": "topic",
      "url": "/documentation/gss/gssapi_cpp_end"
    },
    "doc://com.apple.gss/documentation/GSS/GSSAPI_CPP_START": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSSAPI_CPP_START"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSAPI_CPP_START",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSSAPI_CPP_START",
      "type": "topic",
      "url": "/documentation/gss/gssapi_cpp_start"
    },
    "doc://com.apple.gss/documentation/GSS/GSSAPI_LIB_CALL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSSAPI_LIB_CALL"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSAPI_LIB_CALL",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSSAPI_LIB_CALL",
      "type": "topic",
      "url": "/documentation/gss/gssapi_lib_call"
    },
    "doc://com.apple.gss/documentation/GSS/GSSAPI_LIB_FUNCTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSSAPI_LIB_FUNCTION"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSAPI_LIB_FUNCTION",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSSAPI_LIB_FUNCTION",
      "type": "topic",
      "url": "/documentation/gss/gssapi_lib_function"
    },
    "doc://com.apple.gss/documentation/GSS/GSSAPI_LIB_VARIABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSSAPI_LIB_VARIABLE"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSAPI_LIB_VARIABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSSAPI_LIB_VARIABLE",
      "type": "topic",
      "url": "/documentation/gss/gssapi_lib_variable"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_LIB_CALL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_LIB_CALL"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_LIB_CALL",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_LIB_CALL",
      "type": "topic",
      "url": "/documentation/gss/gss_lib_call"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_LIB_FUNCTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_LIB_FUNCTION"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_LIB_FUNCTION",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_LIB_FUNCTION",
      "type": "topic",
      "url": "/documentation/gss/gss_lib_function"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_LIB_VARIABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_LIB_VARIABLE"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_LIB_VARIABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_LIB_VARIABLE",
      "type": "topic",
      "url": "/documentation/gss/gss_lib_variable"
    },
    "doc://com.apple.gss/documentation/GSS/allocating-and-releasing-objects": {
      "abstract": [
        {
          "text": "Manage memory and object lifetimes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/allocating-and-releasing-objects",
      "kind": "article",
      "role": "article",
      "title": "Allocating and Releasing Objects",
      "type": "topic",
      "url": "/documentation/gss/allocating-and-releasing-objects"
    },
    "doc://com.apple.gss/documentation/GSS/buffer-management": {
      "abstract": [
        {
          "text": "Allocate and deallocate buffers with structures that hold a variety of data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/buffer-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Management",
      "type": "topic",
      "url": "/documentation/gss/buffer-management"
    },
    "doc://com.apple.gss/documentation/GSS/context-services": {
      "abstract": [
        {
          "text": "Use context services to manage secure operations between endpoints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/context-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Context Services",
      "type": "topic",
      "url": "/documentation/gss/context-services"
    },
    "doc://com.apple.gss/documentation/GSS/credential-management": {
      "abstract": [
        {
          "text": "Securely establish connections between endpoints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/credential-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Credential Management",
      "type": "topic",
      "url": "/documentation/gss/credential-management"
    },
    "doc://com.apple.gss/documentation/GSS/function-status": {
      "abstract": [
        {
          "text": "Evaluate return values that most GSS-API functions use to indicate the outcome of an operation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/function-status",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Function Status",
      "type": "topic",
      "url": "/documentation/gss/function-status"
    },
    "doc://com.apple.gss/documentation/GSS/kerberos-implementation": {
      "abstract": [
        {
          "text": "Establish secure connections using the Kerberos implementation of GSS-API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kerberos-implementation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Kerberos Implementation",
      "type": "topic",
      "url": "/documentation/gss/kerberos-implementation"
    },
    "doc://com.apple.gss/documentation/GSS/message-protection": {
      "abstract": [
        {
          "text": "Provide cryptographic protection to secure message integrity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/message-protection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Message Protection",
      "type": "topic",
      "url": "/documentation/gss/message-protection"
    },
    "doc://com.apple.gss/documentation/GSS/name-handling": {
      "abstract": [
        {
          "text": "Manage names for GSS-API principals such as a person, a machine, or an application.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/name-handling",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Name Handling",
      "type": "topic",
      "url": "/documentation/gss/name-handling"
    },
    "doc://com.apple.gss/documentation/GSS/object-identifiers": {
      "abstract": [
        {
          "text": "Store security mechanisms, QOPs (Quality of Protection values), and name types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/object-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Object Identifiers",
      "type": "topic",
      "url": "/documentation/gss/object-identifiers"
    },
    "doc://com.apple.gss/documentation/GSS/security-mechanisms": {
      "abstract": [
        {
          "text": "Provide a security mechanism for your implementation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/security-mechanisms",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Mechanisms",
      "type": "topic",
      "url": "/documentation/gss/security-mechanisms"
    },
    "doc://com.apple.gss/documentation/GSS/structures-and-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.gss/documentation/GSS/structures-and-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Structures and macros",
      "type": "topic",
      "url": "/documentation/gss/structures-and-macros"
    },
    "doc://com.apple.gss/documentation/GSS/token-management": {
      "abstract": [
        {
          "text": "Establish secure communication with tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/token-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Token Management",
      "type": "topic",
      "url": "/documentation/gss/token-management"
    },
    "https://tools.ietf.org/html/rfc2743": {
      "identifier": "https://tools.ietf.org/html/rfc2743",
      "title": "RFC 2743",
      "titleInlineContent": [
        {
          "text": "RFC 2743",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://tools.ietf.org/html/rfc2743"
    },
    "https://tools.ietf.org/html/rfc2744": {
      "identifier": "https://tools.ietf.org/html/rfc2744",
      "title": "RFC 2744",
      "titleInlineContent": [
        {
          "text": "RFC 2744",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://tools.ietf.org/html/rfc2744"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Memory-and-Context",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/allocating-and-releasing-objects",
        "doc://com.apple.gss/documentation/GSS/function-status",
        "doc://com.apple.gss/documentation/GSS/buffer-management",
        "doc://com.apple.gss/documentation/GSS/context-services"
      ],
      "title": "Memory and Context"
    },
    {
      "anchor": "Credentials",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/credential-management",
        "doc://com.apple.gss/documentation/GSS/security-mechanisms"
      ],
      "title": "Credentials"
    },
    {
      "anchor": "Names-and-Object-Identifiers",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/name-handling",
        "doc://com.apple.gss/documentation/GSS/object-identifiers"
      ],
      "title": "Names and Object Identifiers"
    },
    {
      "anchor": "Messages",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/token-management",
        "doc://com.apple.gss/documentation/GSS/message-protection",
        "doc://com.apple.gss/documentation/GSS/kerberos-implementation"
      ],
      "title": "Messages"
    },
    {
      "anchor": "Structure-and-macros",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/structures-and-macros"
      ],
      "title": "Structure and macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Memory-and-Context",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/allocating-and-releasing-objects",
                "doc://com.apple.gss/documentation/GSS/function-status",
                "doc://com.apple.gss/documentation/GSS/buffer-management",
                "doc://com.apple.gss/documentation/GSS/context-services"
              ],
              "title": "Memory and Context"
            },
            {
              "anchor": "Credentials",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/credential-management",
                "doc://com.apple.gss/documentation/GSS/security-mechanisms"
              ],
              "title": "Credentials"
            },
            {
              "anchor": "Names-and-Object-Identifiers",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/name-handling",
                "doc://com.apple.gss/documentation/GSS/object-identifiers"
              ],
              "title": "Names and Object Identifiers"
            },
            {
              "anchor": "Messages",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/token-management",
                "doc://com.apple.gss/documentation/GSS/message-protection",
                "doc://com.apple.gss/documentation/GSS/kerberos-implementation"
              ],
              "title": "Messages"
            },
            {
              "anchor": "Structure-and-macros",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/structures-and-macros"
              ],
              "title": "Structure and macros"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSSAPI_CALLCONV",
                "doc://com.apple.gss/documentation/GSS/GSSAPI_CPP_END",
                "doc://com.apple.gss/documentation/GSS/GSSAPI_CPP_START",
                "doc://com.apple.gss/documentation/GSS/GSSAPI_LIB_CALL",
                "doc://com.apple.gss/documentation/GSS/GSSAPI_LIB_FUNCTION",
                "doc://com.apple.gss/documentation/GSS/GSSAPI_LIB_VARIABLE",
                "doc://com.apple.gss/documentation/GSS/GSS_LIB_CALL",
                "doc://com.apple.gss/documentation/GSS/GSS_LIB_FUNCTION",
                "doc://com.apple.gss/documentation/GSS/GSS_LIB_VARIABLE"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
