{
  "abstract": [
    {
      "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "HealthKit",
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "HealthKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "HealthKit provides a central repository for health and fitness data on iPhone and Apple Watch. With the user’s permission, apps communicate with the HealthKit store to access and share this data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3979193",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Creating a complete, personalized health and fitness experience includes a variety of tasks:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Collecting and storing health and fitness data",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Analyzing and visualizing the data",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enabling social interactions",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "HealthKit apps take a collaborative approach to building this experience. Your app doesn’t need to provide all of these features. Instead, you can focus just on the subset of tasks that most interests you.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, users can select their favorite weight-tracking, step-counting, and health challenge app, each calibrated to their personal needs. Because HealthKit apps freely exchange data (with user permission), the combined suite provides a more customized experience than any single app on its own. For example, when a group of friends joins a daily step-counting challenge, each person can use their preferred hardware device and app to track their steps, while everyone in the group uses the same social app for the challenge.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "HealthKit is also designed to manage and merge data from multiple sources. For example, users can view and manage all of their data in the Health App, including adding data, deleting data, and changing an app’s permissions. Therefore, your app needs to handle these changes, even when they occur outside your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Because health data may contain sensitive, personal information, apps must receive permission from the user to read data from or write data to the HealthKit store. They must also take steps to protect that data at all times. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.healthkit/documentation/HealthKit/protecting-user-privacy",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Updates/HealthKit": {
      "abstract": [
        {
          "text": "Learn about important changes to HealthKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/HealthKit",
      "kind": "article",
      "role": "article",
      "title": "HealthKit updates",
      "type": "topic",
      "url": "/documentation/Updates/HealthKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError": {
      "abstract": [
        {
          "text": "An error returned from a HealthKit method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKError"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKError"
        }
      ],
      "role": "symbol",
      "title": "HKError",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code": {
      "abstract": [
        {
          "text": "Error codes returned by HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKErrorDomain": {
      "abstract": [
        {
          "text": "The domain for all HealthKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "HKErrorDomain",
      "type": "topic",
      "url": "/documentation/healthkit/hkerrordomain"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore": {
      "abstract": [
        {
          "text": "The access point for all data managed by HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKHealthStore"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHealthStore"
        }
      ],
      "role": "symbol",
      "title": "HKHealthStore",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-macros"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/about-the-healthkit-framework": {
      "abstract": [
        {
          "text": "Learn about the architecture and design of the HealthKit framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/about-the-healthkit-framework",
      "kind": "article",
      "role": "article",
      "title": "About the HealthKit framework",
      "type": "topic",
      "url": "/documentation/healthkit/about-the-healthkit-framework"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/authorizing-access-to-health-data": {
      "abstract": [
        {
          "text": "Request permission to read and share data in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/authorizing-access-to-health-data",
      "kind": "article",
      "role": "article",
      "title": "Authorizing access to health data",
      "type": "topic",
      "url": "/documentation/healthkit/authorizing-access-to-health-data"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/creating-a-mobility-health-app": {
      "abstract": [
        {
          "text": "Create a health app that allows a clinical care team to send and receive mobility data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/creating-a-mobility-health-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a Mobility Health App",
      "type": "topic",
      "url": "/documentation/healthkit/creating-a-mobility-health-app"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/data-types": {
      "abstract": [
        {
          "text": "Specify the kind of data used in HealthKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data types",
      "type": "topic",
      "url": "/documentation/healthkit/data-types"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Classes",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-classes"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Constants",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-constants"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Data Types",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-data-types"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Enumerations",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-enumerations"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Functions",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-functions"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Variables",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-variables"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/protecting-user-privacy": {
      "abstract": [
        {
          "text": "Respect and safeguard your user’s privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/protecting-user-privacy",
      "kind": "article",
      "role": "article",
      "title": "Protecting user privacy",
      "type": "topic",
      "url": "/documentation/healthkit/protecting-user-privacy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/queries": {
      "abstract": [
        {
          "text": "Query health and fitness data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/queries",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Queries",
      "type": "topic",
      "url": "/documentation/healthkit/queries"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/reading-data-from-healthkit": {
      "abstract": [
        {
          "text": "Use queries to request sample data from HealthKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/reading-data-from-healthkit",
      "kind": "article",
      "role": "article",
      "title": "Reading data from HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit/reading-data-from-healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/samples": {
      "abstract": [
        {
          "text": "Create and save health and fitness samples.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/samples",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Samples",
      "type": "topic",
      "url": "/documentation/healthkit/samples"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/saving-data-to-healthkit": {
      "abstract": [
        {
          "text": "Create and share HealthKit samples.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/saving-data-to-healthkit",
      "kind": "article",
      "role": "article",
      "title": "Saving data to HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit/saving-data-to-healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/setting-up-healthkit": {
      "abstract": [
        {
          "text": "Set up and configure your HealthKit store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/setting-up-healthkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting up HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit/setting-up-healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/visualizing-healthkit-state-of-mind-in-visionos": {
      "abstract": [
        {
          "text": "Incorporate HealthKit State of Mind into your app and visualize the data in visionOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/visualizing-healthkit-state-of-mind-in-visionos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Visualizing HealthKit State of Mind in visionOS",
      "type": "topic",
      "url": "/documentation/healthkit/visualizing-healthkit-state-of-mind-in-visionos"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings": {
      "abstract": [
        {
          "text": "Manage workouts, workout sessions, and activity summaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workouts and activity rings",
      "type": "topic",
      "url": "/documentation/healthkit/workouts-and-activity-rings"
    },
    "doc://com.apple.healthkit/documentation/HealthKitUI": {
      "abstract": [
        {
          "text": "Display user interface that enables a person to view and interact with their health data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKitUI",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKitUI",
      "type": "topic",
      "url": "/documentation/healthkitui"
    },
    "media-3979193": {
      "alt": "An image showing Health on iPhone and Activity on Apple Watch.",
      "identifier": "media-3979193",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b81321b91287e91567ab0308257fb273/media-3979193@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/about-the-healthkit-framework",
        "doc://com.apple.healthkit/documentation/HealthKit/setting-up-healthkit",
        "doc://com.apple.healthkit/documentation/HealthKit/authorizing-access-to-health-data",
        "doc://com.apple.healthkit/documentation/HealthKit/protecting-user-privacy",
        "doc://com.apple.documentation/documentation/Updates/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKitUI"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Health-data",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/saving-data-to-healthkit",
        "doc://com.apple.healthkit/documentation/HealthKit/reading-data-from-healthkit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore",
        "doc://com.apple.healthkit/documentation/HealthKit/creating-a-mobility-health-app",
        "doc://com.apple.healthkit/documentation/HealthKit/data-types",
        "doc://com.apple.healthkit/documentation/HealthKit/samples",
        "doc://com.apple.healthkit/documentation/HealthKit/queries",
        "doc://com.apple.healthkit/documentation/HealthKit/visualizing-healthkit-state-of-mind-in-visionos"
      ],
      "title": "Health data"
    },
    {
      "anchor": "Workout-data",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings"
      ],
      "title": "Workout data"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKError",
        "doc://com.apple.healthkit/documentation/HealthKit/HKErrorDomain",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions",
        "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/about-the-healthkit-framework",
                "doc://com.apple.healthkit/documentation/HealthKit/setting-up-healthkit",
                "doc://com.apple.healthkit/documentation/HealthKit/authorizing-access-to-health-data",
                "doc://com.apple.healthkit/documentation/HealthKit/protecting-user-privacy",
                "doc://com.apple.documentation/documentation/Updates/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKitUI"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Health-data",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/saving-data-to-healthkit",
                "doc://com.apple.healthkit/documentation/HealthKit/reading-data-from-healthkit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore",
                "doc://com.apple.healthkit/documentation/HealthKit/creating-a-mobility-health-app",
                "doc://com.apple.healthkit/documentation/HealthKit/data-types",
                "doc://com.apple.healthkit/documentation/HealthKit/samples",
                "doc://com.apple.healthkit/documentation/HealthKit/queries",
                "doc://com.apple.healthkit/documentation/HealthKit/visualizing-healthkit-state-of-mind-in-visionos"
              ],
              "title": "Health data"
            },
            {
              "anchor": "Workout-data",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings"
              ],
              "title": "Workout data"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKErrorDomain",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations",
                "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes",
                "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants",
                "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types",
                "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions",
                "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros",
                "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/title",
          "value": "HKHealthStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHealthStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHealthStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code/title",
          "value": "HKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKErrorDomain/title",
          "value": "HKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
