{
  "abstract": [
    {
      "text": "Configure, control, and communicate with home automation accessories.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 1"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "HomeKit",
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "HomeKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "HomeKit enables your app to coordinate and control home automation accessories from multiple vendors to present a coherent, user-focused interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3111422",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Using HomeKit, your app can:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Discover HomeKit-compatible automation accessories and add them to a persistent, cross-device home configuration database.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Display, edit, and act upon the data in the home configuration database.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Communicate with configured accessories and services in order to perform actions like turning on the lights in the living room.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.homekit": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether users of the app may manage HomeKit-compatible accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.homekit",
      "kind": "symbol",
      "role": "symbol",
      "title": "HomeKit Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.homekit"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSHomeKitUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the user’s HomeKit configuration data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSHomeKitUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHomeKitUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSHomeKitUsageDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessory": {
      "abstract": [
        {
          "text": "A home automation accessory, like a garage door opener or a thermostat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "role": "symbol",
      "title": "HMAccessory",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessory"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupManager": {
      "abstract": [
        {
          "text": "An object that setups up new accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessorySetupManager"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessorySetupManager"
        }
      ],
      "role": "symbol",
      "title": "HMAccessorySetupManager",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetupmanager"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupPayload": {
      "abstract": [
        {
          "text": "A payload for authenticating a HomeKit accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessorySetupPayload"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessorySetupPayload"
        }
      ],
      "role": "symbol",
      "title": "HMAccessorySetupPayload",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetuppayload"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest": {
      "abstract": [
        {
          "text": "An object that describes how to add and setup up new accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessorySetupRequest"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessorySetupRequest"
        }
      ],
      "role": "symbol",
      "title": "HMAccessorySetupRequest",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetuprequest"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupResult": {
      "abstract": [
        {
          "text": "A result object describing information about a successful accessory setup request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessorySetupResult"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessorySetupResult"
        }
      ],
      "role": "symbol",
      "title": "HMAccessorySetupResult",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetupresult"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet": {
      "abstract": [
        {
          "text": "A collection of actions that you trigger as a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMActionSet"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMActionSet"
        }
      ],
      "role": "symbol",
      "title": "HMActionSet",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic": {
      "abstract": [
        {
          "text": "A specific characteristic of a service, like the brightness of a dimmable light or its color temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristic"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristic",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError": {
      "abstract": [
        {
          "text": "An error HomeKit returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "role": "symbol",
      "title": "HMError",
      "type": "topic",
      "url": "/documentation/homekit/hmerror"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code": {
      "abstract": [
        {
          "text": "Possible error values that can be returned from HomeKit APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMErrorBlock": {
      "abstract": [
        {
          "text": "A completion block that provides an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMErrorBlock"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMErrorBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorBlock"
        }
      ],
      "role": "symbol",
      "title": "HMErrorBlock",
      "type": "topic",
      "url": "/documentation/homekit/hmerrorblock"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the HomeKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "HMErrorDomain",
      "type": "topic",
      "url": "/documentation/homekit/hmerrordomain"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger": {
      "abstract": [
        {
          "text": "A trigger to activate an action set based on a set of events and optional conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMEventTrigger"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMEventTrigger"
        }
      ],
      "role": "symbol",
      "title": "HMEventTrigger",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager": {
      "abstract": [
        {
          "text": "The manager for a collection of one or more of a user’s homes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "role": "symbol",
      "title": "HMHomeManager",
      "type": "topic",
      "url": "/documentation/homekit/hmhomemanager"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile": {
      "abstract": [
        {
          "text": "An interface from which to read and, if allowed by the accessory, update the ordering of input sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMMediaSourceDisplayOrderProfile"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMMediaSourceDisplayOrderProfile"
        }
      ],
      "role": "symbol",
      "title": "HMMediaSourceDisplayOrderProfile",
      "type": "topic",
      "url": "/documentation/homekit/hmmediasourcedisplayorderprofile"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMService": {
      "abstract": [
        {
          "text": "A controllable feature of an accessory, like a light attached to a garage door opener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMService"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMService"
        }
      ],
      "role": "symbol",
      "title": "HMService",
      "type": "topic",
      "url": "/documentation/homekit/hmservice"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMTimerTrigger": {
      "abstract": [
        {
          "text": "A trigger to activate an action set based on a periodic timer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMTimerTrigger"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTimerTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMTimerTrigger"
        }
      ],
      "role": "symbol",
      "title": "HMTimerTrigger",
      "type": "topic",
      "url": "/documentation/homekit/hmtimertrigger"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HM_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HM_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HM_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "HM_EXTERN",
      "type": "topic",
      "url": "/documentation/homekit/hm_extern"
    },
    "doc://com.apple.homekit/documentation/HomeKit/configuring-a-home-automation-device": {
      "abstract": [
        {
          "text": "Give users a familiar experience when they manage HomeKit accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/configuring-a-home-automation-device",
      "kind": "article",
      "role": "sampleCode",
      "title": "Configuring a home automation device",
      "type": "topic",
      "url": "/documentation/homekit/configuring-a-home-automation-device"
    },
    "doc://com.apple.homekit/documentation/HomeKit/enabling-homekit-in-your-app": {
      "abstract": [
        {
          "text": "Declare your app’s intention to use HomeKit, and get permission from the user to access home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/enabling-homekit-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Enabling HomeKit in your app",
      "type": "topic",
      "url": "/documentation/homekit/enabling-homekit-in-your-app"
    },
    "doc://com.apple.homekit/documentation/HomeKit/interacting-with-a-home-automation-network": {
      "abstract": [
        {
          "text": "Find all the automation accessories in the primary home and control their state.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/interacting-with-a-home-automation-network",
      "kind": "article",
      "role": "sampleCode",
      "title": "Interacting with a home automation network",
      "type": "topic",
      "url": "/documentation/homekit/interacting-with-a-home-automation-network"
    },
    "doc://com.apple.homekit/documentation/HomeKit/testing-your-app-with-the-homekit-accessory-simulator": {
      "abstract": [
        {
          "text": "Install the HomeKit Accessory Simulator to help you debug your HomeKit-enabled app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/testing-your-app-with-the-homekit-accessory-simulator",
      "kind": "article",
      "role": "article",
      "title": "Testing your app with the HomeKit Accessory Simulator",
      "type": "topic",
      "url": "/documentation/homekit/testing-your-app-with-the-homekit-accessory-simulator"
    },
    "media-3111422": {
      "alt": "The diagram depicts a stylized phone emitting waves to indicate communication with a house pictured as a central icon. Four icons are arranged in a semi-circle to the right of the house icon, depicting connected accessories including a garage door, a thermometer, a sliding light switch, and a lamp.",
      "identifier": "media-3111422",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d33b070d6684f4f8ae1ed27b980f946b/media-3111422@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/0b2e40ec9875038047c423522ff71715/media-3111422~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/enabling-homekit-in-your-app",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.homekit",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSHomeKitUsageDescription"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Home-Manager",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/configuring-a-home-automation-device",
        "doc://com.apple.homekit/documentation/HomeKit/testing-your-app-with-the-homekit-accessory-simulator",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager"
      ],
      "title": "Home Manager"
    },
    {
      "anchor": "Accessories",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupManager",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupResult",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest",
        "doc://com.apple.homekit/documentation/HomeKit/interacting-with-a-home-automation-network",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
        "doc://com.apple.homekit/documentation/HomeKit/HMService",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
        "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile"
      ],
      "title": "Accessories"
    },
    {
      "anchor": "Action-Sets",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet",
        "doc://com.apple.homekit/documentation/HomeKit/HMTimerTrigger",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger"
      ],
      "title": "Action Sets"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMError",
        "doc://com.apple.homekit/documentation/HomeKit/HMErrorDomain",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code",
        "doc://com.apple.homekit/documentation/HomeKit/HMErrorBlock"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupPayload"
      ],
      "title": "Classes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/enabling-homekit-in-your-app",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.homekit",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSHomeKitUsageDescription"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Home-Manager",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/configuring-a-home-automation-device",
                "doc://com.apple.homekit/documentation/HomeKit/testing-your-app-with-the-homekit-accessory-simulator",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager"
              ],
              "title": "Home Manager"
            },
            {
              "anchor": "Accessories",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupManager",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupResult",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest",
                "doc://com.apple.homekit/documentation/HomeKit/interacting-with-a-home-automation-network",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
                "doc://com.apple.homekit/documentation/HomeKit/HMService",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic"
              ],
              "title": "Accessories"
            },
            {
              "anchor": "Action-Sets",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSet",
                "doc://com.apple.homekit/documentation/HomeKit/HMTimerTrigger",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger"
              ],
              "title": "Action Sets"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMErrorDomain",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code",
                "doc://com.apple.homekit/documentation/HomeKit/HMErrorBlock"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupPayload"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HM_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/title",
          "value": "HMCharacteristic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/title",
          "value": "HMAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/title",
          "value": "HMService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/title",
          "value": "HMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMErrorDomain/title",
          "value": "HMErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest/title",
          "value": "HMAccessorySetupRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/title",
          "value": "HMHomeManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/title",
          "value": "HMEventTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMErrorBlock/title",
          "value": "HMErrorBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMErrorBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMErrorBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet/title",
          "value": "HMActionSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupResult/title",
          "value": "HMAccessorySetupResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupPayload/title",
          "value": "HMAccessorySetupPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTimerTrigger/title",
          "value": "HMTimerTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTimerTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMTimerTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTimerTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMTimerTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupManager/title",
          "value": "HMAccessorySetupManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
