{
  "abstract": [
    {
      "text": "The Apple Search Ads iAd Attribution API is a legacy framework for attributing app data that originates from Apple Search Ads campaigns on iOS devices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iad/documentation/iAd"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "iAd",
    "modules": [
      {
        "name": "iAd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "iAd"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "After February 7, 2023, all requests made to the Apple Search Ads iAd Attribution API will return with a value of ",
                  "type": "text"
                },
                {
                  "code": "\"iad-attribution\"",
                  "type": "codeVoice"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "code": "=",
                  "type": "codeVoice"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "code": "false",
                  "type": "codeVoice"
                },
                {
                  "text": ", or errors. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.iad/documentation/iAd/ADClient/requestAttributionDetails(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AdServices",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework for current attribution integration with the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/apple_search_ads",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " Campaign Management API for devices using iOS 14.3 and later. Attribution isn’t available for downloads and redownloads from devices using iOS 14.2 or earlier.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Warning",
          "style": "warning",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Attribution data consists of campaign metadata from app ads, such as app downloads and redownloads that result from taps on ads created through the Apple Search Ads user interface or the Apple Search Ads API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "All Apple Search Ads data that Apple collects is subject to the ",
              "type": "text"
            },
            {
              "identifier": "https://www.apple.com/privacy",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AdServices": {
      "abstract": [
        {
          "text": "Attribute app-download campaigns that originate from the App Store, Apple News, or Stocks on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AdServices",
      "kind": "symbol",
      "role": "collection",
      "title": "AdServices",
      "type": "topic",
      "url": "/documentation/AdServices"
    },
    "doc://com.apple.documentation/documentation/apple_search_ads": {
      "abstract": [
        {
          "text": "Drive app discovery by creating and managing campaigns with the Apple Search Ads Campaign Management API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple_search_ads",
      "kind": "symbol",
      "role": "collection",
      "title": "Apple Search Ads",
      "type": "topic",
      "url": "/documentation/apple_search_ads"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iad/documentation/iAd": {
      "abstract": [
        {
          "text": "The Apple Search Ads iAd Attribution API is a legacy framework for attributing app data that originates from Apple Search Ads campaigns on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd",
      "kind": "symbol",
      "role": "collection",
      "title": "iAd",
      "type": "topic",
      "url": "/documentation/iad"
    },
    "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_IOS_71_145_OBSOLETED_180": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ADCLIENT_DEPRECATED_IOS_71_145_OBSOLETED_180"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_IOS_71_145_OBSOLETED_180",
      "kind": "symbol",
      "role": "symbol",
      "title": "ADCLIENT_DEPRECATED_IOS_71_145_OBSOLETED_180",
      "type": "topic",
      "url": "/documentation/iad/adclient_deprecated_ios_71_145_obsoleted_180"
    },
    "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_IOS_71_150_OBSOLETED_180": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ADCLIENT_DEPRECATED_IOS_71_150_OBSOLETED_180"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_IOS_71_150_OBSOLETED_180",
      "kind": "symbol",
      "role": "symbol",
      "title": "ADCLIENT_DEPRECATED_IOS_71_150_OBSOLETED_180",
      "type": "topic",
      "url": "/documentation/iad/adclient_deprecated_ios_71_150_obsoleted_180"
    },
    "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_IOS_90_145_OBSOLETED_180": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ADCLIENT_DEPRECATED_IOS_90_145_OBSOLETED_180"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_IOS_90_145_OBSOLETED_180",
      "kind": "symbol",
      "role": "symbol",
      "title": "ADCLIENT_DEPRECATED_IOS_90_145_OBSOLETED_180",
      "type": "topic",
      "url": "/documentation/iad/adclient_deprecated_ios_90_145_obsoleted_180"
    },
    "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_MACOS_1014_113_OBSOLETED_180": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ADCLIENT_DEPRECATED_MACOS_1014_113_OBSOLETED_180"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_MACOS_1014_113_OBSOLETED_180",
      "kind": "symbol",
      "role": "symbol",
      "title": "ADCLIENT_DEPRECATED_MACOS_1014_113_OBSOLETED_180",
      "type": "topic",
      "url": "/documentation/iad/adclient_deprecated_macos_1014_113_obsoleted_180"
    },
    "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_MACOS_1014_120_OBSOLETED_180": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ADCLIENT_DEPRECATED_MACOS_1014_120_OBSOLETED_180"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_MACOS_1014_120_OBSOLETED_180",
      "kind": "symbol",
      "role": "symbol",
      "title": "ADCLIENT_DEPRECATED_MACOS_1014_120_OBSOLETED_180",
      "type": "topic",
      "url": "/documentation/iad/adclient_deprecated_macos_1014_120_obsoleted_180"
    },
    "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_TVOS_71_145_OBSOLETED_180": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ADCLIENT_DEPRECATED_TVOS_71_145_OBSOLETED_180"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_TVOS_71_145_OBSOLETED_180",
      "kind": "symbol",
      "role": "symbol",
      "title": "ADCLIENT_DEPRECATED_TVOS_71_145_OBSOLETED_180",
      "type": "topic",
      "url": "/documentation/iad/adclient_deprecated_tvos_71_145_obsoleted_180"
    },
    "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_TVOS_71_150_OBSOLETED_180": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ADCLIENT_DEPRECATED_TVOS_71_150_OBSOLETED_180"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_TVOS_71_150_OBSOLETED_180",
      "kind": "symbol",
      "role": "symbol",
      "title": "ADCLIENT_DEPRECATED_TVOS_71_150_OBSOLETED_180",
      "type": "topic",
      "url": "/documentation/iad/adclient_deprecated_tvos_71_150_obsoleted_180"
    },
    "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_TVOS_90_145_OBSOLETED_180": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ADCLIENT_DEPRECATED_TVOS_90_145_OBSOLETED_180"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_TVOS_90_145_OBSOLETED_180",
      "kind": "symbol",
      "role": "symbol",
      "title": "ADCLIENT_DEPRECATED_TVOS_90_145_OBSOLETED_180",
      "type": "topic",
      "url": "/documentation/iad/adclient_deprecated_tvos_90_145_obsoleted_180"
    },
    "doc://com.apple.iad/documentation/iAd/ADClient": {
      "abstract": [
        {
          "text": "The parent class you use to request an attribution response.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ADClient"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClient"
        }
      ],
      "role": "symbol",
      "title": "ADClient",
      "type": "topic",
      "url": "/documentation/iad/adclient"
    },
    "doc://com.apple.iad/documentation/iAd/ADClient/requestAttributionDetails(_:)": {
      "abstract": [
        {
          "text": "Gets an attribution response.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAttributionDetails"
        },
        {
          "kind": "text",
          "text": "((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClient/requestAttributionDetails(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAttributionDetailsWithBlock:"
        }
      ],
      "role": "symbol",
      "title": "requestAttributionDetails(_:)",
      "type": "topic",
      "url": "/documentation/iad/adclient/requestattributiondetails(_:)"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct": {
      "abstract": [
        {
          "text": "The group of error codes that pass from the attribution response to the completion handler block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ADClientError"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientError"
        }
      ],
      "role": "symbol",
      "title": "ADClientError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The error codes that pass from the attribution response to the completion handler.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientErrorDomain": {
      "abstract": [
        {
          "text": "The error domain that passes to the completion handler.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ADClientErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ADClientErrorDomain",
      "type": "topic",
      "url": "/documentation/iad/adclienterrordomain"
    },
    "doc://com.apple.iad/documentation/iAd/deprecated-symbols": {
      "abstract": [
        {
          "text": "Reference symbols from the legacy iAd framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/iad/deprecated-symbols"
    },
    "doc://com.apple.iad/documentation/iAd/iad-changelog": {
      "abstract": [
        {
          "text": "Learn what’s new in the Apple Search Ads iAd Attribution API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/iad-changelog",
      "kind": "article",
      "role": "article",
      "title": "iAd Changelog",
      "type": "topic",
      "url": "/documentation/iad/iad-changelog"
    },
    "doc://com.apple.iad/documentation/iAd/setting-up-apple-search-ads-attribution": {
      "abstract": [
        {
          "text": "Retrieve the attribution dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/setting-up-apple-search-ads-attribution",
      "kind": "article",
      "role": "article",
      "title": "Setting Up Apple Search Ads Attribution",
      "type": "topic",
      "url": "/documentation/iad/setting-up-apple-search-ads-attribution"
    },
    "https://www.apple.com/privacy": {
      "identifier": "https://www.apple.com/privacy",
      "title": "Apple Privacy Policy",
      "titleInlineContent": [
        {
          "text": "Apple Privacy Policy",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.apple.com/privacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.iad/documentation/iAd/iad-changelog",
        "doc://com.apple.iad/documentation/iAd/setting-up-apple-search-ads-attribution",
        "doc://com.apple.iad/documentation/iAd/ADClient"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Attribution-Errors",
      "identifiers": [
        "doc://com.apple.iad/documentation/iAd/ADClientErrorDomain",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code"
      ],
      "title": "Attribution Errors"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.iad/documentation/iAd/deprecated-symbols"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.iad/documentation/iAd/iad-changelog",
                "doc://com.apple.iad/documentation/iAd/setting-up-apple-search-ads-attribution",
                "doc://com.apple.iad/documentation/iAd/ADClient"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Attribution-Errors",
              "identifiers": [
                "doc://com.apple.iad/documentation/iAd/ADClientErrorDomain",
                "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code"
              ],
              "title": "Attribution Errors"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.iad/documentation/iAd/deprecated-symbols"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_IOS_71_145_OBSOLETED_180",
                "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_IOS_71_150_OBSOLETED_180",
                "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_IOS_90_145_OBSOLETED_180",
                "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_MACOS_1014_113_OBSOLETED_180",
                "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_MACOS_1014_120_OBSOLETED_180",
                "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_TVOS_71_145_OBSOLETED_180",
                "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_TVOS_71_150_OBSOLETED_180",
                "doc://com.apple.iad/documentation/iAd/ADCLIENT_DEPRECATED_TVOS_90_145_OBSOLETED_180"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientErrorDomain/title",
          "value": "ADClientErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient/title",
          "value": "ADClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient~1requestAttributionDetails(_:)/title",
          "value": "requestAttributionDetailsWithBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClient~1requestAttributionDetails(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestAttributionDetailsWithBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/title",
          "value": "ADClientError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iad"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iad"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
