{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.identitylookup/documentation/IdentityLookupUI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "IdentityLookupUI",
    "modules": [
      {
        "name": "IdentityLookupUI"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "IdentityLookupUI"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookupUI": {
      "abstract": [],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookupUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IdentityLookupUI",
      "type": "topic",
      "url": "/documentation/identitylookupui"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController": {
      "abstract": [
        {
          "text": "The superclass for an Unwanted Communication Reporting extension’s principal view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILClassificationUIExtensionViewController"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILClassificationUIExtensionViewController"
        }
      ],
      "role": "symbol",
      "title": "ILClassificationUIExtensionViewController",
      "type": "topic",
      "url": "/documentation/identitylookupui/ilclassificationuiextensionviewcontroller"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController"
      ],
      "title": "Classes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionViewController/title",
          "value": "ILClassificationUIExtensionViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationUIExtensionViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationUIExtensionViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/identitylookupui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/identitylookupui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
