{
  "abstract": [
    {
      "text": "Create app extensions to manage and report unwanted SMS messages and spam calls.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.identitylookup/documentation/IdentityLookup"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "IdentityLookup",
    "modules": [
      {
        "name": "SMS and Call Reporting"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Technology",
    "symbolKind": "module",
    "title": "SMS and Call Reporting"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "SMS and Call Reporting provides app extensions to manage unwanted communication.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Identifies and filters unwanted SMS and MMS messages.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "inlineContent": [
                      {
                        "text": "Message Filter app extension",
                        "type": "text"
                      }
                    ],
                    "type": "strong"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Lets people report unwanted SMS messages and calls as spam.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "inlineContent": [
                      {
                        "text": "Unwanted Communication app extension",
                        "type": "text"
                      }
                    ],
                    "type": "strong"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Enables up-to-date calling and blocking information.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "inlineContent": [
                      {
                        "text": "Live Caller ID Lookup app extension",
                        "type": "text"
                      }
                    ],
                    "type": "strong"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup": {
      "abstract": [
        {
          "text": "Create app extensions to manage and report unwanted SMS messages and spam calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup",
      "kind": "symbol",
      "role": "collection",
      "title": "SMS and Call Reporting",
      "type": "topic",
      "url": "/documentation/identitylookup"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/CallLookupExtensionStatus": {
      "abstract": [
        {
          "text": "Returns a value with the current state of the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CallLookupExtensionStatus"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/CallLookupExtensionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CallLookupExtensionStatus"
        }
      ],
      "role": "symbol",
      "title": "CallLookupExtensionStatus",
      "type": "topic",
      "url": "/documentation/identitylookup/calllookupextensionstatus"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupExtensionConfiguration": {
      "abstract": [
        {
          "text": "An object that allows the system to query the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LiveCallerIDLookupExtensionConfiguration"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupExtensionConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LiveCallerIDLookupExtensionConfiguration"
        }
      ],
      "role": "symbol",
      "title": "LiveCallerIDLookupExtensionConfiguration",
      "type": "topic",
      "url": "/documentation/identitylookup/livecalleridlookupextensionconfiguration"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupExtensionContext": {
      "abstract": [
        {
          "text": "The information the system uses for configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LiveCallerIDLookupExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LiveCallerIDLookupExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "LiveCallerIDLookupExtensionContext",
      "type": "topic",
      "url": "/documentation/identitylookup/livecalleridlookupextensioncontext"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupManager": {
      "abstract": [
        {
          "text": "The entry point that provides access to a collection of functions that help manage the state of the Live Caller ID Lookup app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LiveCallerIDLookupManager"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LiveCallerIDLookupManager"
        }
      ],
      "role": "symbol",
      "title": "LiveCallerIDLookupManager",
      "type": "topic",
      "url": "/documentation/identitylookup/livecalleridlookupmanager"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupProtocol": {
      "abstract": [
        {
          "text": "Information the system uses to query the app extension for context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LiveCallerIDLookupProtocol"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LiveCallerIDLookupProtocol"
        }
      ],
      "role": "symbol",
      "title": "LiveCallerIDLookupProtocol",
      "type": "topic",
      "url": "/documentation/identitylookup/livecalleridlookupprotocol"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/formatting-data-for-blocking-and-identity-information": {
      "abstract": [
        {
          "text": "Set up your PIR payload for call blocking and identity information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/formatting-data-for-blocking-and-identity-information",
      "kind": "article",
      "role": "article",
      "title": "Formatting data for blocking and identity information",
      "type": "topic",
      "url": "/documentation/identitylookup/formatting-data-for-blocking-and-identity-information"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/getting-up-to-date-calling-and-blocking-information-for-your-app": {
      "abstract": [
        {
          "text": "Implement the Live Caller ID Lookup app extension to provide call-blocking and identity services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/getting-up-to-date-calling-and-blocking-information-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Getting up-to-date calling and blocking information for your app",
      "type": "topic",
      "url": "/documentation/identitylookup/getting-up-to-date-calling-and-blocking-information-for-your-app"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/macros": {
      "abstract": [],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/identitylookup/macros"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/setting-up-the-http-endpoints-for-live-caller-id-lookup": {
      "abstract": [
        {
          "text": "Connect the on-device system to your server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/setting-up-the-http-endpoints-for-live-caller-id-lookup",
      "kind": "article",
      "role": "article",
      "title": "Setting up the HTTP endpoints for Live Caller ID Lookup",
      "type": "topic",
      "url": "/documentation/identitylookup/setting-up-the-http-endpoints-for-live-caller-id-lookup"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/sms-and-call-spam-reporting": {
      "abstract": [
        {
          "text": "Create an app extension that lets users report unwanted SMS messages and calls as junk.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/sms-and-call-spam-reporting",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SMS and Call Spam Reporting",
      "type": "topic",
      "url": "/documentation/identitylookup/sms-and-call-spam-reporting"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/sms-and-mms-message-filtering": {
      "abstract": [
        {
          "text": "Create an app extension that identifies and filters unwanted SMS and MMS messages while preserving user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/sms-and-mms-message-filtering",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SMS and MMS Message Filtering",
      "type": "topic",
      "url": "/documentation/identitylookup/sms-and-mms-message-filtering"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/understanding-how-live-caller-id-lookup-preserves-privacy": {
      "abstract": [
        {
          "text": "Use Live Caller ID Lookup to protect user privacy by hiding the client’s IP address, using anonymous authentication, and hiding the incoming phone number.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/understanding-how-live-caller-id-lookup-preserves-privacy",
      "kind": "article",
      "role": "article",
      "title": "Understanding how Live Caller ID Lookup preserves privacy",
      "type": "topic",
      "url": "/documentation/identitylookup/understanding-how-live-caller-id-lookup-preserves-privacy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Message-filtering",
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookup/sms-and-mms-message-filtering"
      ],
      "title": "Message filtering"
    },
    {
      "anchor": "Spam-reporting",
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookup/sms-and-call-spam-reporting"
      ],
      "title": "Spam reporting"
    },
    {
      "anchor": "Live-Caller-ID-Lookup",
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookup/understanding-how-live-caller-id-lookup-preserves-privacy",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/formatting-data-for-blocking-and-identity-information",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/setting-up-the-http-endpoints-for-live-caller-id-lookup",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/getting-up-to-date-calling-and-blocking-information-for-your-app",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupProtocol",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupExtensionConfiguration",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupExtensionContext",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/CallLookupExtensionStatus",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/LiveCallerIDLookupManager"
      ],
      "title": "Live Caller ID Lookup"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookup/macros"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Message-filtering",
              "identifiers": [
                "doc://com.apple.identitylookup/documentation/IdentityLookup/sms-and-mms-message-filtering"
              ],
              "title": "Message filtering"
            },
            {
              "anchor": "Spam-reporting",
              "identifiers": [
                "doc://com.apple.identitylookup/documentation/IdentityLookup/sms-and-call-spam-reporting"
              ],
              "title": "Spam reporting"
            },
            {
              "anchor": "Live-Caller-ID-Lookup",
              "identifiers": [
                "doc://com.apple.identitylookup/documentation/IdentityLookup/understanding-how-live-caller-id-lookup-preserves-privacy",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/formatting-data-for-blocking-and-identity-information",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/setting-up-the-http-endpoints-for-live-caller-id-lookup",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/getting-up-to-date-calling-and-blocking-information-for-your-app"
              ],
              "title": "Live Caller ID Lookup"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.identitylookup/documentation/IdentityLookup/macros"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/identitylookup"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/identitylookup"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
