{
  "abstract": [
    {
      "text": "Read and write most image file formats, and access an image’s metadata.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ImageIO",
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.8",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Image I/O"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Image I/O framework allows applications to read and write most image file formats. This framework offers high efficiency, color management, and access to image metadata.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Adobe Photoshop image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "8BIM Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/8bim-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageAtURLWithBlock(_:_:_:)": {
      "abstract": [
        {
          "text": "Animate the sequence of images in the Graphics Interchange Format (GIF) or Animated Portable Network Graphics (APNG) file at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGAnimateImageAtURLWithBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceAnimationBlock",
          "text": "CGImageSourceAnimationBlock"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageAtURLWithBlock(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGAnimateImageAtURLWithBlock"
        }
      ],
      "role": "symbol",
      "title": "CGAnimateImageAtURLWithBlock(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cganimateimageaturlwithblock(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageDataWithBlock(_:_:_:)": {
      "abstract": [
        {
          "text": "Animate the sequence of images using data from a Graphics Interchange Format (GIF) or Animated Portable Network Graphics (APNG) file file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGAnimateImageDataWithBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceAnimationBlock",
          "text": "CGImageSourceAnimationBlock"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageDataWithBlock(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGAnimateImageDataWithBlock"
        }
      ],
      "role": "symbol",
      "title": "CGAnimateImageDataWithBlock(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cganimateimagedatawithblock(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus": {
      "abstract": [
        {
          "text": "Constants that indicate the result of animating an image sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageAnimationStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageAnimationStatus"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination": {
      "abstract": [
        {
          "text": "An opaque type that you use to write image data to a URL, data object, or data consumer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestination"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestination"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestination",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestination"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata": {
      "abstract": [
        {
          "text": "An immutable object that contains the XMP metadata associated with an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadata"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadata"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadata",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors": {
      "abstract": [
        {
          "text": "Constants for errors that occur when getting or setting metadata information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataErrors"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataErrors"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataErrors",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadataerrors"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag": {
      "abstract": [
        {
          "text": "An immutable type that contains information about a single piece of image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataTag"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataTag"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataTag",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatag"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSource": {
      "abstract": [
        {
          "text": "An opaque type that you use to read image data from a URL, data object, or data consumer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSource"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSource"
        }
      ],
      "role": "symbol",
      "title": "CGImageSource",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesource"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceAnimationBlock": {
      "abstract": [
        {
          "text": "The block to execute for each frame of an image animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceAnimationBlock"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceAnimationBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceAnimationBlock"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceAnimationBlock",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourceanimationblock"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata": {
      "abstract": [
        {
          "text": "An opaque type for adding or modifying image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGMutableImageMetadata"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGMutableImageMetadata"
        }
      ],
      "role": "symbol",
      "title": "CGMutableImageMetadata",
      "type": "topic",
      "url": "/documentation/imageio/cgmutableimagemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/Creating-spatial-photos-and-videos-with-spatial-metadata": {
      "abstract": [
        {
          "text": "Add spatial metadata to stereo photos and videos to create spatial media for viewing on Apple Vision Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/Creating-spatial-photos-and-videos-with-spatial-metadata",
      "kind": "article",
      "role": "article",
      "title": "Creating spatial photos and videos with spatial metadata",
      "type": "topic",
      "url": "/documentation/imageio/creating-spatial-photos-and-videos-with-spatial-metadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for an image from a Canon camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Canon Camera Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/canon-camera-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Camera Image File Format (CIFF) image format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/ciff-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Digital Negative (DNG) archival format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/dng-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for Exchangeable Image File Format (EXIF) data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EXIF Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/exif-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Graphics Interchange Format (GIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/gif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys for Global Positioning System (GPS) information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GPS Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/gps-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the High Efficiency Image Container (HEIC) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEIC Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/heic-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/image-i-o-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/image-i-o-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image I/O Constants",
      "type": "topic",
      "url": "/documentation/imageio/image-i-o-constants"
    },
    "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image I/O Functions",
      "type": "topic",
      "url": "/documentation/imageio/image-i-o-functions"
    },
    "doc://com.apple.imageio/documentation/ImageIO/image-i-o-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/image-i-o-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image I/O Macros",
      "type": "topic",
      "url": "/documentation/imageio/image-i-o-macros"
    },
    "doc://com.apple.imageio/documentation/ImageIO/image-properties": {
      "abstract": [
        {
          "text": "Properties that apply to the container in general, and not necessarily to an individual image in the container.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for International Press Telecommunications Council (IPTC) data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPTC Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/iptc-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the JPEG File Interchange Format (JFIF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "JFIF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/jfif-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata": {
      "abstract": [
        {
          "text": "The domain for metadata-related errors that originate in the Image I/O framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCGImageMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCGImageMetadata"
        }
      ],
      "role": "symbol",
      "title": "kCFErrorDomainCGImageMetadata",
      "type": "topic",
      "url": "/documentation/imageio/kcferrordomaincgimagemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationDelayTime": {
      "abstract": [
        {
          "text": "The number of seconds to wait before displaying the next image in an animated sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAnimationDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationDelayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationDelayTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAnimationDelayTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageanimationdelaytime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationLoopCount": {
      "abstract": [
        {
          "text": "The number of times to repeat the animated sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAnimationLoopCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationLoopCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationLoopCount"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAnimationLoopCount",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageanimationloopcount"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationStartIndex": {
      "abstract": [
        {
          "text": "A property that specifies the index of the first frame of an animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStartIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationStartIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStartIndex"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAnimationStartIndex",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageanimationstartindex"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeBaseIsSDR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeBaseIsSDR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeBaseIsSDR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeBaseIsSDR"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationEncodeBaseIsSDR",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationencodebaseissdr"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeRequest"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationEncodeRequest",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationencoderequest"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeRequestOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeRequestOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationEncodeRequestOptions",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationencoderequestoptions"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToISOGainmap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeToISOGainmap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToISOGainmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeToISOGainmap"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationEncodeToISOGainmap",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationencodetoisogainmap"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToISOHDR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeToISOHDR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToISOHDR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeToISOHDR"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationEncodeToISOHDR",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationencodetoisohdr"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToSDR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeToSDR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToSDR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeToSDR"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationEncodeToSDR",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationencodetosdr"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeTonemapMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeTonemapMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeTonemapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEncodeTonemapMode"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationEncodeTonemapMode",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationencodetonemapmode"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from an Apple camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerAppleDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerAppleDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerAppleDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerappledictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Fuji camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerFujiDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerFujiDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerFujiDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerfujidictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Minolta camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerMinoltaDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerMinoltaDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerMinoltaDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerminoltadictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Olympus camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerOlympusDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerOlympusDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerOlympusDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerolympusdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Pentax camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerPentaxDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerPentaxDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerPentaxDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerpentaxdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image that contains minimally processed, or raw, data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyRawDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyRawDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyRawDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyrawdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceGenerateImageSpecificLumaScaling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceGenerateImageSpecificLumaScaling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceGenerateImageSpecificLumaScaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceGenerateImageSpecificLumaScaling"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceGenerateImageSpecificLumaScaling",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourcegenerateimagespecificlumascaling"
    },
    "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for an image from a Nikon camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nikon Camera Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/nikon-camera-dictionary-keys"
    },
    "doc://com.apple.imageio/documentation/ImageIO/png-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Portable Network Graphics (PNG) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PNG Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/png-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Truevision Graphics Adapter (TGA) format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TGA Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tga-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties": {
      "abstract": [
        {
          "text": "Metadata keys for the Tagged Image File Format (TIFF).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TIFF Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/tiff-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/webp-data": {
      "abstract": [
        {
          "text": "Metadata keys for WebP metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/webp-data",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebP Data",
      "type": "topic",
      "url": "/documentation/imageio/webp-data"
    },
    "doc://com.apple.imageio/documentation/ImageIO/writing-spatial-photos": {
      "abstract": [
        {
          "text": "Create spatial photos for visionOS by packaging a pair of left- and right-eye images as a stereo HEIC file with related spatial metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/writing-spatial-photos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Writing spatial photos",
      "type": "topic",
      "url": "/documentation/imageio/writing-spatial-photos"
    },
    "doc://com.apple.imageio/documentation/ImageIO/xmp-namespaces-and-prefixes": {
      "abstract": [
        {
          "text": "Discover the public namespaces and prefixes that exist in XMP metadata tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/xmp-namespaces-and-prefixes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "XMP Namespaces and Prefixes",
      "type": "topic",
      "url": "/documentation/imageio/xmp-namespaces-and-prefixes"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462",
      "title": "Image I/O Programming Guide",
      "titleInlineContent": [
        {
          "text": "Image I/O Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Image-Management",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSource",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination"
      ],
      "title": "Image Management"
    },
    {
      "anchor": "XMP-Metadata",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata",
        "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag",
        "doc://com.apple.imageio/documentation/ImageIO/xmp-namespaces-and-prefixes",
        "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors"
      ],
      "title": "XMP Metadata"
    },
    {
      "anchor": "Common-Image-Properties",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/webp-data"
      ],
      "title": "Common Image Properties"
    },
    {
      "anchor": "Format-Specific-Properties",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
        "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
      ],
      "title": "Format-Specific Properties"
    },
    {
      "anchor": "Manufacturer-Specific-Properties",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary"
      ],
      "title": "Manufacturer-Specific Properties"
    },
    {
      "anchor": "Spatial-Photos",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/writing-spatial-photos",
        "doc://com.apple.imageio/documentation/ImageIO/Creating-spatial-photos-and-videos-with-spatial-metadata"
      ],
      "title": "Spatial Photos"
    },
    {
      "anchor": "Animations",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageAtURLWithBlock(_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageDataWithBlock(_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceAnimationBlock",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationStartIndex",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationDelayTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationLoopCount",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus"
      ],
      "title": "Animations"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/image-i-o-constants",
        "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions",
        "doc://com.apple.imageio/documentation/ImageIO/image-i-o-macros"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeBaseIsSDR",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeRequest",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeRequestOptions",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToISOGainmap",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToISOHDR",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToSDR",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeTonemapMode",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceGenerateImageSpecificLumaScaling"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Image-Management",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSource",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination"
              ],
              "title": "Image Management"
            },
            {
              "anchor": "XMP-Metadata",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata",
                "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag",
                "doc://com.apple.imageio/documentation/ImageIO/xmp-namespaces-and-prefixes",
                "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors"
              ],
              "title": "XMP Metadata"
            },
            {
              "anchor": "Common-Image-Properties",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/exif-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/iptc-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/gps-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/webp-data"
              ],
              "title": "Common Image Properties"
            },
            {
              "anchor": "Format-Specific-Properties",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/ciff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/dng-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/gif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/heic-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/jfif-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/png-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tga-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/tiff-image-properties",
                "doc://com.apple.imageio/documentation/ImageIO/8bim-image-properties"
              ],
              "title": "Format-Specific Properties"
            },
            {
              "anchor": "Manufacturer-Specific-Properties",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary"
              ],
              "title": "Manufacturer-Specific Properties"
            },
            {
              "anchor": "Spatial-Photos",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/writing-spatial-photos",
                "doc://com.apple.imageio/documentation/ImageIO/Creating-spatial-photos-and-videos-with-spatial-metadata"
              ],
              "title": "Spatial Photos"
            },
            {
              "anchor": "Animations",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageAtURLWithBlock(_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageDataWithBlock(_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceAnimationBlock",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationStartIndex",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationDelayTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationLoopCount",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus"
              ],
              "title": "Animations"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/image-i-o-constants",
                "doc://com.apple.imageio/documentation/ImageIO/image-i-o-functions",
                "doc://com.apple.imageio/documentation/ImageIO/image-i-o-macros"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeBaseIsSDR",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeRequest",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeRequestOptions",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToISOGainmap",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToISOHDR",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeToSDR",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEncodeTonemapMode",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceGenerateImageSpecificLumaScaling"
              ],
              "title": "Variables"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationDelayTime/title",
          "value": "kCGImageAnimationDelayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationDelayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationDelayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceAnimationBlock/title",
          "value": "CGImageSourceAnimationBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceAnimationBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceAnimationBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceAnimationBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceAnimationBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerPentaxDictionary/title",
          "value": "kCGImagePropertyMakerPentaxDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerPentaxDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerPentaxDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataTag/title",
          "value": "CGImageMetadataTagRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataTagRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataTagRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerFujiDictionary/title",
          "value": "kCGImagePropertyMakerFujiDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerFujiDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerFujiDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceGenerateImageSpecificLumaScaling/title",
          "value": "kCGImageSourceGenerateImageSpecificLumaScaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceGenerateImageSpecificLumaScaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceGenerateImageSpecificLumaScaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestination/title",
          "value": "CGImageDestinationRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGAnimateImageDataWithBlock(_:_:_:)/title",
          "value": "CGAnimateImageDataWithBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGAnimateImageDataWithBlock(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGAnimateImageDataWithBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeToISOHDR/title",
          "value": "kCGImageDestinationEncodeToISOHDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeToISOHDR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationEncodeToISOHDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadata/title",
          "value": "CGImageMetadataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeToSDR/title",
          "value": "kCGImageDestinationEncodeToSDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeToSDR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationEncodeToSDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataErrors/title",
          "value": "CGImageMetadataErrors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataErrors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataErrors/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/title",
          "value": "CGMutableImageMetadataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGMutableImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGMutableImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerMinoltaDictionary/title",
          "value": "kCGImagePropertyMakerMinoltaDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerMinoltaDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerMinoltaDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeBaseIsSDR/title",
          "value": "kCGImageDestinationEncodeBaseIsSDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeBaseIsSDR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationEncodeBaseIsSDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeRequest/title",
          "value": "kCGImageDestinationEncodeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationEncodeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationStartIndex/title",
          "value": "kCGImageAnimationStartIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationStartIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStartIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeRequestOptions/title",
          "value": "kCGImageDestinationEncodeRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationEncodeRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeTonemapMode/title",
          "value": "kCGImageDestinationEncodeTonemapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeTonemapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationEncodeTonemapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus/title",
          "value": "CGImageAnimationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageAnimationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageAnimationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCFErrorDomainCGImageMetadata/title",
          "value": "kCFErrorDomainCGImageMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCFErrorDomainCGImageMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFErrorDomainCGImageMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeToISOGainmap/title",
          "value": "kCGImageDestinationEncodeToISOGainmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEncodeToISOGainmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationEncodeToISOGainmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/title",
          "value": "CGImageSourceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerAppleDictionary/title",
          "value": "kCGImagePropertyMakerAppleDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerAppleDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerAppleDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerOlympusDictionary/title",
          "value": "kCGImagePropertyMakerOlympusDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerOlympusDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerOlympusDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGAnimateImageAtURLWithBlock(_:_:_:)/title",
          "value": "CGAnimateImageAtURLWithBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGAnimateImageAtURLWithBlock(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGAnimateImageAtURLWithBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyRawDictionary/title",
          "value": "kCGImagePropertyRawDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyRawDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyRawDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationLoopCount/title",
          "value": "kCGImageAnimationLoopCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationLoopCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationLoopCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
