{
  "abstract": [
    {
      "text": "Empower people to customize interactions for your app on their device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "Intents",
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.2",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Intents"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use intents to enable people to interact with your app across Siri, Shortcuts, and widgets. Define custom intents for specific actions that someone can trigger with Siri or Shortcuts, and donate intents to help Siri learn someone’s habits and suggest relevant shortcuts over time. You can also provide shortcut suggestions that appear in the Shortcuts app or in Siri’s recommendations to help boost discoverability.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Intents is a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.sirikit/documentation/SiriKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsAC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nacsAC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsAC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeNACSAC"
        }
      ],
      "role": "symbol",
      "title": "nacsAC",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/nacsac"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsDC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nacsDC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCar",
          "text": "INCar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INCarChargingConnectorType",
          "text": "ChargingConnectorType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsDC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarChargingConnectorTypeNACSDC"
        }
      ],
      "role": "symbol",
      "title": "nacsDC",
      "type": "topic",
      "url": "/documentation/intents/incar/chargingconnectortype/nacsdc"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDefaultCardTemplate": {
      "abstract": [
        {
          "text": "A card template for customizing the Siri watch face for a shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDefaultCardTemplate"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDefaultCardTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDefaultCardTemplate"
        }
      ],
      "role": "symbol",
      "title": "INDefaultCardTemplate",
      "type": "topic",
      "url": "/documentation/intents/indefaultcardtemplate"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntent": {
      "abstract": [
        {
          "text": "A request to fulfill in your app or Intents extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntent"
        }
      ],
      "role": "symbol",
      "title": "INIntent",
      "type": "topic",
      "url": "/documentation/intents/inintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentDonationMetadata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentDonationMetadata"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentDonationMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentDonationMetadata"
        }
      ],
      "role": "symbol",
      "title": "INIntentDonationMetadata",
      "type": "topic",
      "url": "/documentation/intents/inintentdonationmetadata"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResponse": {
      "abstract": [
        {
          "text": "Your response to an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentSetImageKeyPath"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentSetImageKeyPath"
        }
      ],
      "role": "symbol",
      "title": "INIntentSetImageKeyPath",
      "type": "topic",
      "url": "/documentation/intents/inintentsetimagekeypath"
    },
    "doc://com.apple.sirikit/documentation/Intents/INInteraction": {
      "abstract": [
        {
          "text": "An interaction between the user and your app involving an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "role": "symbol",
      "title": "INInteraction",
      "type": "topic",
      "url": "/documentation/intents/ininteraction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INParameter": {
      "abstract": [
        {
          "text": "A parameter of an interaction object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INParameter"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INParameter"
        }
      ],
      "role": "symbol",
      "title": "INParameter",
      "type": "topic",
      "url": "/documentation/intents/inparameter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum": {
      "abstract": [
        {
          "text": "An action available in your app that the system may suggest to a user or a user may add to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcut"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcut"
        }
      ],
      "role": "symbol",
      "title": "INShortcut",
      "type": "topic",
      "url": "/documentation/intents/inshortcut-swift.enum"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions": {
      "abstract": [
        {
          "text": "Defined contexts in which an intent or activity might be relevant to a user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "role": "symbol",
      "title": "INShortcutAvailabilityOptions",
      "type": "topic",
      "url": "/documentation/intents/inshortcutavailabilityoptions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutReference": {
      "abstract": [
        {
          "text": "An object representing an action available in your app that the system may suggest to a user or a user may add to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcutReference"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutReference"
        }
      ],
      "role": "symbol",
      "title": "INShortcutReference",
      "type": "topic",
      "url": "/documentation/intents/inshortcutreference"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSticker/StickerType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StickerType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSticker/StickerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StickerType"
        }
      ],
      "role": "symbol",
      "title": "INSticker.StickerType",
      "type": "topic",
      "url": "/documentation/intents/insticker/stickertype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabulary": {
      "abstract": [
        {
          "text": "An object for registering user-specific vocabulary that Siri requests might include.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVocabulary"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabulary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabulary"
        }
      ],
      "role": "symbol",
      "title": "INVocabulary",
      "type": "topic",
      "url": "/documentation/intents/invocabulary"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut": {
      "abstract": [
        {
          "text": "A shortcut the user added to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVoiceShortcut"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVoiceShortcut"
        }
      ],
      "role": "symbol",
      "title": "INVoiceShortcut",
      "type": "topic",
      "url": "/documentation/intents/invoiceshortcut"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter": {
      "abstract": [
        {
          "text": "Retrieve the user’s shortcuts and make shortcut suggestions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVoiceShortcutCenter"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVoiceShortcutCenter"
        }
      ],
      "role": "symbol",
      "title": "INVoiceShortcutCenter",
      "type": "topic",
      "url": "/documentation/intents/invoiceshortcutcenter"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI": {
      "abstract": [
        {
          "text": "Customize content in the interface for Siri and Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IntentsUI",
      "type": "topic",
      "url": "/documentation/intentsui"
    },
    "doc://com.apple.sirikit/documentation/SiriKit": {
      "abstract": [
        {
          "text": "Empower users to interact with their devices through voice, intelligent suggestions, and personalized workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit",
      "kind": "article",
      "role": "collection",
      "title": "SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/adding-shortcuts-for-wind-down": {
      "abstract": [
        {
          "text": "Reveal your app’s shortcuts inside the Health app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/adding-shortcuts-for-wind-down",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adding Shortcuts for Wind Down",
      "type": "topic",
      "url": "/documentation/sirikit/adding-shortcuts-for-wind-down"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app": {
      "abstract": [
        {
          "text": "Add custom intents and parameters to help users interact more quickly and effectively with Siri and the Shortcuts app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app",
      "kind": "article",
      "role": "article",
      "title": "Adding User Interactivity with Siri Shortcuts and the Shortcuts App",
      "type": "topic",
      "url": "/documentation/sirikit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/car-commands": {
      "abstract": [
        {
          "text": "Manage vehicle door locks and get the vehicle’s status.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/car-commands",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Car Commands",
      "type": "topic",
      "url": "/documentation/sirikit/car-commands"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/common-data-types": {
      "abstract": [
        {
          "text": "Manage common data types such as strings, dates, currencies, images, and contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/common-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Common Data Types",
      "type": "topic",
      "url": "/documentation/sirikit/common-data-types"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts": {
      "abstract": [
        {
          "text": "Remove your donations from Siri.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts",
      "kind": "article",
      "role": "article",
      "title": "Deleting Donated Shortcuts",
      "type": "topic",
      "url": "/documentation/sirikit/deleting-donated-shortcuts"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/sirikit/deprecated-symbols"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers": {
      "abstract": [
        {
          "text": "Provide SiriKit with an intent handler capable of handling a specific intent.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers",
      "kind": "article",
      "role": "article",
      "title": "Dispatching intents to handlers",
      "type": "topic",
      "url": "/documentation/sirikit/dispatching-intents-to-handlers"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/donating-shortcuts": {
      "abstract": [
        {
          "text": "Tell Siri about shortcuts to actions that the user performed in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/donating-shortcuts",
      "kind": "article",
      "role": "article",
      "title": "Donating Shortcuts",
      "type": "topic",
      "url": "/documentation/sirikit/donating-shortcuts"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/intent-class-identifiers": {
      "abstract": [
        {
          "text": "Identify intents that user notifications specify.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/intent-class-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Intent Class Identifiers",
      "type": "topic",
      "url": "/documentation/sirikit/intent-class-identifiers"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/intent-handling-infrastructure": {
      "abstract": [
        {
          "text": "Specify required permissions and provide handlers for the intents your app supports, and configure app extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/intent-handling-infrastructure",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Intent Handling Infrastructure",
      "type": "topic",
      "url": "/documentation/sirikit/intent-handling-infrastructure"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/lists-and-notes": {
      "abstract": [
        {
          "text": "Create and manage notes and to-do list items.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/lists-and-notes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Lists and Notes",
      "type": "topic",
      "url": "/documentation/sirikit/lists-and-notes"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/macros": {
      "abstract": [],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/sirikit/macros"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/media": {
      "abstract": [
        {
          "text": "Listen and control audio through Siri Intents, or listen and watch media content from your app with shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/media",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media",
      "type": "topic",
      "url": "/documentation/sirikit/media"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/messaging": {
      "abstract": [
        {
          "text": "Send messages and search the user’s received messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/messaging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Messaging",
      "type": "topic",
      "url": "/documentation/sirikit/messaging"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app": {
      "abstract": [
        {
          "text": "Suggest shortcuts users may want to add to Siri or combine with other actions in their own shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app",
      "kind": "article",
      "role": "article",
      "title": "Offering Actions in the Shortcuts App",
      "type": "topic",
      "url": "/documentation/sirikit/offering-actions-in-the-shortcuts-app"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/payments": {
      "abstract": [
        {
          "text": "Send payments between users or pay bills.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/payments",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Payments",
      "type": "topic",
      "url": "/documentation/sirikit/payments"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/providing-hands-free-app-control-with-intents": {
      "abstract": [
        {
          "text": "Resolve, confirm, and handle intents without an extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/providing-hands-free-app-control-with-intents",
      "kind": "article",
      "role": "sampleCode",
      "title": "Providing Hands-Free App Control with Intents",
      "type": "topic",
      "url": "/documentation/sirikit/providing-hands-free-app-control-with-intents"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/registering-custom-vocabulary-with-sirikit": {
      "abstract": [
        {
          "text": "Register your app’s custom terminology, and provide sample phrases for how to use your app with Siri.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/registering-custom-vocabulary-with-sirikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Registering Custom Vocabulary with SiriKit",
      "type": "topic",
      "url": "/documentation/sirikit/registering-custom-vocabulary-with-sirikit"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/resolution-results": {
      "abstract": [
        {
          "text": "Resolve common types of data like strings and dates into specific values that your app recognizes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/resolution-results",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resolution Results",
      "type": "topic",
      "url": "/documentation/sirikit/resolution-results"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/resolving-and-handling-intents": {
      "abstract": [
        {
          "text": "Resolve, confirm, and handle user requests for your app’s services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/resolving-and-handling-intents",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resolving and Handling Intents",
      "type": "topic",
      "url": "/documentation/sirikit/resolving-and-handling-intents"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/restaurant-reservations": {
      "abstract": [
        {
          "text": "Create and manage restaurant reservations with help from the Maps app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/restaurant-reservations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Restaurant Reservations",
      "type": "topic",
      "url": "/documentation/sirikit/restaurant-reservations"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/ride-booking": {
      "abstract": [
        {
          "text": "Book rides and report their status.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/ride-booking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ride Booking",
      "type": "topic",
      "url": "/documentation/sirikit/ride-booking"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/siri-event-suggestions": {
      "abstract": [
        {
          "text": "Provide users with current, actionable information connected to a reservation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/siri-event-suggestions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Siri Event Suggestions",
      "type": "topic",
      "url": "/documentation/sirikit/siri-event-suggestions"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-accelerating-app-interactions-with-shortcuts": {
      "abstract": [
        {
          "text": "Make it easy for people to use Siri with your app by providing shortcuts to your app’s actions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-accelerating-app-interactions-with-shortcuts",
      "kind": "article",
      "role": "sampleCode",
      "title": "Soup Chef: Accelerating App Interactions with Shortcuts",
      "type": "topic",
      "url": "/documentation/sirikit/soup-chef-accelerating-app-interactions-with-shortcuts"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-with-app-intents-migrating-custom-intents": {
      "abstract": [
        {
          "text": "Integrating App Intents to provide your appʼs actions to Siri and Shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-with-app-intents-migrating-custom-intents",
      "kind": "article",
      "role": "sampleCode",
      "title": "Soup Chef with App Intents: Migrating custom intents",
      "type": "topic",
      "url": "/documentation/sirikit/soup-chef-with-app-intents-migrating-custom-intents"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/voip-calling": {
      "abstract": [
        {
          "text": "Initiate calls and search the user’s call history.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/voip-calling",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VoIP Calling",
      "type": "topic",
      "url": "/documentation/sirikit/voip-calling"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/watch-and-widget-support": {
      "abstract": [
        {
          "text": "Display relevant shortcuts on the Siri watch face and suggest widgets in Smart Stacks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/watch-and-widget-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Watch and Widget Support",
      "type": "topic",
      "url": "/documentation/sirikit/watch-and-widget-support"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/workouts": {
      "abstract": [
        {
          "text": "Start, end, and manage fitness routines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/workouts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workouts",
      "type": "topic",
      "url": "/documentation/sirikit/workouts"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Frameworks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI"
      ],
      "title": "Frameworks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Intents",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers",
        "doc://com.apple.sirikit/documentation/SiriKit/resolving-and-handling-intents",
        "doc://com.apple.sirikit/documentation/Intents/INIntent",
        "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
        "doc://com.apple.sirikit/documentation/SiriKit/intent-handling-infrastructure",
        "doc://com.apple.sirikit/documentation/SiriKit/providing-hands-free-app-control-with-intents",
        "doc://com.apple.sirikit/documentation/SiriKit/resolution-results",
        "doc://com.apple.sirikit/documentation/SiriKit/common-data-types"
      ],
      "title": "Intents"
    },
    {
      "abstract": [
        {
          "text": "SiriKit groups intents into domains based on the type of app that’s likely to support them.",
          "type": "text"
        }
      ],
      "anchor": "Standard-Intents",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/car-commands",
        "doc://com.apple.sirikit/documentation/SiriKit/lists-and-notes",
        "doc://com.apple.sirikit/documentation/SiriKit/media",
        "doc://com.apple.sirikit/documentation/SiriKit/messaging",
        "doc://com.apple.sirikit/documentation/SiriKit/payments",
        "doc://com.apple.sirikit/documentation/SiriKit/restaurant-reservations",
        "doc://com.apple.sirikit/documentation/SiriKit/ride-booking",
        "doc://com.apple.sirikit/documentation/SiriKit/voip-calling",
        "doc://com.apple.sirikit/documentation/SiriKit/workouts",
        "doc://com.apple.sirikit/documentation/SiriKit/intent-class-identifiers"
      ],
      "title": "Standard Intents"
    },
    {
      "anchor": "Shortcuts-and-Donations",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app",
        "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app",
        "doc://com.apple.sirikit/documentation/SiriKit/donating-shortcuts",
        "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts",
        "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-accelerating-app-interactions-with-shortcuts",
        "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-with-app-intents-migrating-custom-intents",
        "doc://com.apple.sirikit/documentation/SiriKit/adding-shortcuts-for-wind-down",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutReference",
        "doc://com.apple.sirikit/documentation/Intents/INInteraction",
        "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum",
        "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter",
        "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutReference",
        "doc://com.apple.sirikit/documentation/Intents/INIntentDonationMetadata",
        "doc://com.apple.sirikit/documentation/SiriKit/watch-and-widget-support",
        "doc://com.apple.sirikit/documentation/SiriKit/siri-event-suggestions"
      ],
      "title": "Shortcuts and Donations"
    },
    {
      "anchor": "Vocabulary",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/registering-custom-vocabulary-with-sirikit",
        "doc://com.apple.sirikit/documentation/Intents/INVocabulary"
      ],
      "title": "Vocabulary"
    },
    {
      "anchor": "Deprecated-Symbols",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/deprecated-symbols"
      ],
      "title": "Deprecated Symbols"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/macros"
      ],
      "title": "Macros"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INDefaultCardTemplate",
        "doc://com.apple.sirikit/documentation/Intents/INParameter"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath"
      ],
      "title": "Protocols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Intents",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers",
                "doc://com.apple.sirikit/documentation/SiriKit/resolving-and-handling-intents",
                "doc://com.apple.sirikit/documentation/Intents/INIntent",
                "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
                "doc://com.apple.sirikit/documentation/SiriKit/intent-handling-infrastructure",
                "doc://com.apple.sirikit/documentation/SiriKit/providing-hands-free-app-control-with-intents",
                "doc://com.apple.sirikit/documentation/SiriKit/resolution-results",
                "doc://com.apple.sirikit/documentation/SiriKit/common-data-types"
              ],
              "title": "Intents"
            },
            {
              "abstract": [
                {
                  "text": "SiriKit groups intents into domains based on the type of app that’s likely to support them.",
                  "type": "text"
                }
              ],
              "anchor": "Standard-Intents",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/SiriKit/car-commands",
                "doc://com.apple.sirikit/documentation/SiriKit/lists-and-notes",
                "doc://com.apple.sirikit/documentation/SiriKit/media",
                "doc://com.apple.sirikit/documentation/SiriKit/messaging",
                "doc://com.apple.sirikit/documentation/SiriKit/payments",
                "doc://com.apple.sirikit/documentation/SiriKit/restaurant-reservations",
                "doc://com.apple.sirikit/documentation/SiriKit/ride-booking",
                "doc://com.apple.sirikit/documentation/SiriKit/voip-calling",
                "doc://com.apple.sirikit/documentation/SiriKit/workouts",
                "doc://com.apple.sirikit/documentation/SiriKit/intent-class-identifiers"
              ],
              "title": "Standard Intents"
            },
            {
              "anchor": "Shortcuts-and-Donations",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app",
                "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app",
                "doc://com.apple.sirikit/documentation/SiriKit/donating-shortcuts",
                "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts",
                "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-accelerating-app-interactions-with-shortcuts",
                "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-with-app-intents-migrating-custom-intents",
                "doc://com.apple.sirikit/documentation/SiriKit/adding-shortcuts-for-wind-down",
                "doc://com.apple.sirikit/documentation/Intents/INShortcutReference",
                "doc://com.apple.sirikit/documentation/Intents/INInteraction",
                "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter",
                "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut",
                "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions",
                "doc://com.apple.sirikit/documentation/Intents/INShortcutReference",
                "doc://com.apple.sirikit/documentation/Intents/INIntentDonationMetadata",
                "doc://com.apple.sirikit/documentation/SiriKit/watch-and-widget-support",
                "doc://com.apple.sirikit/documentation/SiriKit/siri-event-suggestions"
              ],
              "title": "Shortcuts and Donations"
            },
            {
              "anchor": "Vocabulary",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/SiriKit/registering-custom-vocabulary-with-sirikit",
                "doc://com.apple.sirikit/documentation/Intents/INVocabulary"
              ],
              "title": "Vocabulary"
            },
            {
              "anchor": "Deprecated-Symbols",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/SiriKit/deprecated-symbols"
              ],
              "title": "Deprecated Symbols"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/SiriKit/macros"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INDefaultCardTemplate",
                "doc://com.apple.sirikit/documentation/Intents/INParameter"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsAC",
                "doc://com.apple.sirikit/documentation/Intents/INCar/ChargingConnectorType/nacsDC"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSticker/StickerType"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Frameworks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI"
              ],
              "title": "Frameworks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/title",
          "value": "INVoiceShortcut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/title",
          "value": "INShortcutAvailabilityOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDefaultCardTemplate/title",
          "value": "INDefaultCardTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDefaultCardTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDefaultCardTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDefaultCardTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDefaultCardTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1nacsDC/title",
          "value": "INCarChargingConnectorTypeNACSDC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1nacsDC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeNACSDC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INParameter/title",
          "value": "INParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INParameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary/title",
          "value": "INVocabulary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabulary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabulary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/title",
          "value": "INInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/title",
          "value": "INShortcut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentDonationMetadata/title",
          "value": "INIntentDonationMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentDonationMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentDonationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentDonationMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentDonationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/title",
          "value": "INIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/title",
          "value": "INIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1nacsAC/title",
          "value": "INCarChargingConnectorTypeNACSAC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCar~1ChargingConnectorType~1nacsAC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarChargingConnectorTypeNACSAC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/title",
          "value": "INVoiceShortcutCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcutCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcutCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSticker~1StickerType/title",
          "value": "INStickerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSticker~1StickerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStickerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSticker~1StickerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStickerType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
