{
  "abstract": [
    {
      "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iosurface/documentation/IOSurface"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "IOSurface",
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.6",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "IOSurface"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The IOSurface framework provides a framebuffer object suitable for sharing across process boundaries. It is commonly used to allow applications to move complex image decompression and draw logic into a separate process to enhance security.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface": {
      "abstract": [
        {
          "text": "Data type representing an IOSurface opaque object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurface"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurface"
        }
      ],
      "role": "symbol",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceLockOptions"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceLockOptions"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceLockOptions",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacelockoptions"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOSurfacePropertyKey",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfacePurgeabilityState"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePurgeabilityState"
        }
      ],
      "role": "symbol",
      "title": "IOSurfacePurgeabilityState",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepurgeabilitystate"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef": {
      "abstract": [
        {
          "text": "Data type representing an IOSurface opaque object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceRef"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceRef"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceRef",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfaceref"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Constants",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-constants"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Data Types",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-data-types"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Enumerations",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-enumerations"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Functions",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-functions"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Structures",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-structures"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceContentHeadroom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceContentHeadroom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceContentHeadroom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceContentHeadroom"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceContentHeadroom",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacecontentheadroom"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCopybackCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceCopybackCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCopybackCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceCopybackCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceCopybackCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacecopybackcache"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCopybackInnerCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceCopybackInnerCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCopybackInnerCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceCopybackInnerCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceCopybackInnerCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacecopybackinnercache"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceDefaultCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceDefaultCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceDefaultCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceDefaultCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceDefaultCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacedefaultcache"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceInhibitCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceInhibitCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceInhibitCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceInhibitCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceInhibitCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceinhibitcache"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCacheShift": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapCacheShift"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCacheShift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapCacheShift"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceMapCacheShift",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacemapcacheshift"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCopybackCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapCopybackCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCopybackCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapCopybackCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceMapCopybackCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacemapcopybackcache"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCopybackInnerCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapCopybackInnerCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCopybackInnerCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapCopybackInnerCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceMapCopybackInnerCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacemapcopybackinnercache"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapDefaultCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapDefaultCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapDefaultCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapDefaultCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceMapDefaultCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacemapdefaultcache"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapInhibitCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapInhibitCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapInhibitCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapInhibitCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceMapInhibitCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacemapinhibitcache"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapWriteCombineCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapWriteCombineCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapWriteCombineCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapWriteCombineCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceMapWriteCombineCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacemapwritecombinecache"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapWriteThruCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapWriteThruCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapWriteThruCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceMapWriteThruCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceMapWriteThruCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacemapwritethrucache"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWriteCombineCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceWriteCombineCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWriteCombineCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceWriteCombineCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceWriteCombineCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacewritecombinecache"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWriteThruCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceWriteThruCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWriteThruCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceWriteThruCache"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceWriteThruCache",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacewritethrucache"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceContentHeadroom",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCopybackCache",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCopybackInnerCache",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceDefaultCache",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceInhibitCache",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCacheShift",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCopybackCache",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCopybackInnerCache",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapDefaultCache",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapInhibitCache",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapWriteCombineCache",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapWriteThruCache",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWriteCombineCache",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWriteThruCache"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState"
              ],
              "title": "Structures"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures",
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations",
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants",
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions",
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceContentHeadroom"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCopybackCache",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCopybackInnerCache",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceDefaultCache",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceInhibitCache",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCacheShift",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCopybackCache",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapCopybackInnerCache",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapDefaultCache",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapInhibitCache",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapWriteCombineCache",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceMapWriteThruCache",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWriteCombineCache",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWriteThruCache"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapWriteCombineCache/title",
          "value": "kIOSurfaceMapWriteCombineCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapWriteCombineCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceMapWriteCombineCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceLockOptions/title",
          "value": "IOSurfaceLockOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceLockOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceLockOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceLockOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceLockOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/title",
          "value": "IOSurface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceWriteCombineCache/title",
          "value": "kIOSurfaceWriteCombineCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceWriteCombineCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceWriteCombineCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapCacheShift/title",
          "value": "kIOSurfaceMapCacheShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapCacheShift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceMapCacheShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey/title",
          "value": "IOSurfacePropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapCopybackInnerCache/title",
          "value": "kIOSurfaceMapCopybackInnerCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapCopybackInnerCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceMapCopybackInnerCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapCopybackCache/title",
          "value": "kIOSurfaceMapCopybackCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapCopybackCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceMapCopybackCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceWriteThruCache/title",
          "value": "kIOSurfaceWriteThruCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceWriteThruCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceWriteThruCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceDefaultCache/title",
          "value": "kIOSurfaceDefaultCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceDefaultCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceDefaultCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceContentHeadroom/title",
          "value": "kIOSurfaceContentHeadroom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceContentHeadroom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceContentHeadroom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapDefaultCache/title",
          "value": "kIOSurfaceMapDefaultCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapDefaultCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceMapDefaultCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCopybackCache/title",
          "value": "kIOSurfaceCopybackCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCopybackCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceCopybackCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapInhibitCache/title",
          "value": "kIOSurfaceMapInhibitCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapInhibitCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceMapInhibitCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCopybackInnerCache/title",
          "value": "kIOSurfaceCopybackInnerCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCopybackInnerCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceCopybackInnerCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/title",
          "value": "IOSurfaceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapWriteThruCache/title",
          "value": "kIOSurfaceMapWriteThruCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceMapWriteThruCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceMapWriteThruCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceInhibitCache/title",
          "value": "kIOSurfaceInhibitCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceInhibitCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceInhibitCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/title",
          "value": "IOSurfacePurgeabilityState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePurgeabilityState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePurgeabilityState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iosurface"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
