{
  "abstract": [
    {
      "text": "Create host-mode user space drivers for USB devices.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "IOUSBHost",
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "IOUSBHost"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework, you can access custom and non–class-compliant USB devices from within your apps. Use this framework to connect to cameras, audio devices, scanners, printers, keyboards, mouse devices, MIDI keyboards, and USB hubs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This framework refers to the USB Implementers Forum (USB-IF) ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Universal Serial Bus 3.2 Specification",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", Revision 1.0, September 22, 2017. You can view this specification at ",
              "type": "text"
            },
            {
              "identifier": "http://www.usb.org/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateMachine": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIControllerStateMachine"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIControllerStateMachine"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIControllerStateMachine",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicontrollerstatemachine"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateMachine": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceStateMachine"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceStateMachine"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceStateMachine",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicestatemachine"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIEndpointStateMachine"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIEndpointStateMachine"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIEndpointStateMachine",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciendpointstatemachine"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusFromMessage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusFromMessage"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusFromMessage",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusFromMessage",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatusfrommessage"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageTypeFromMessage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageTypeFromMessage"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageTypeFromMessage",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBHostCIMessageTypeFromMessage",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagetypefrommessage"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStateMachine": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStateMachine"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStateMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStateMachine"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStateMachine",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatemachine"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterface"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterface"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostControllerInterface",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcontrollerinterface"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevice": {
      "abstract": [
        {
          "text": "The class that claims and configures devices, retrieves descriptors, and sends device requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostDevice"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostDevice"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostDevice",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdevice"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey": {
      "abstract": [
        {
          "text": "Properties of a USB device that describe its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostDevicePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostDevicePropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostDevicePropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdevicepropertykey"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostErrorDomain",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhosterrordomain"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSource": {
      "abstract": [
        {
          "text": "This class provides basic functionality for deriving pipe and stream classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIOSource"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIOSource"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIOSource",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostiosource"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterface": {
      "abstract": [
        {
          "text": "The class for accessing USB-related services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostInterface"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostInterface"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostInterface",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostinterface"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey": {
      "abstract": [
        {
          "text": "Properties of a USB interface that describe its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostInterfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostInterfacePropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostInterfacePropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostinterfacepropertykey"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey": {
      "abstract": [
        {
          "text": "Properties for implementing the matching service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostMatchingPropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject": {
      "abstract": [
        {
          "text": "This class provides basic functionality for sending device requests and retrieving descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostObject"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostObject"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostObject",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe": {
      "abstract": [
        {
          "text": "The class that sends control, bulk, interrupt, and isochronous input/output requests for function drivers, and manages stream capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostPipe"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostPipe"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostPipe",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey": {
      "abstract": [
        {
          "text": "Properties that the USB host device and interface classes share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostPropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostPropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpropertykey"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream": {
      "abstract": [
        {
          "text": "The class responsible for sending stream data for function drivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostStream"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostStream"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostStream",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhoststream"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostVersionNumber": {
      "abstract": [
        {
          "text": "The version number of the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOUSBHostVersionNumber"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostVersionNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBHostVersionNumber",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostversionnumber"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostVersionString": {
      "abstract": [
        {
          "text": "A string representation of the framework’s version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOUSBHostVersionString"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostVersionString",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBHostVersionString",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostversionstring"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Constants",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-constants"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Data Types",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-data-types"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Enumerations",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-enumerations"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Functions",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-functions"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Structures",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-structures"
    },
    "http://www.usb.org/": {
      "identifier": "http://www.usb.org/",
      "title": "http://www.usb.org/",
      "titleInlineContent": [
        {
          "text": "http://www.usb.org/",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.usb.org/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Function-Drivers",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterface",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream"
      ],
      "title": "Function Drivers"
    },
    {
      "anchor": "Device-Drivers",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevice"
      ],
      "title": "Device Drivers"
    },
    {
      "anchor": "Base-Classes",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSource"
      ],
      "title": "Base Classes"
    },
    {
      "abstract": [
        {
          "text": "Properties on the device and interface classes in the service plane.",
          "type": "text"
        }
      ],
      "anchor": "IOServicePlane-Properties",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey"
      ],
      "title": "IOServicePlane Properties"
    },
    {
      "anchor": "Error-Domain",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostErrorDomain"
      ],
      "title": "Error Domain"
    },
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateMachine",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateMachine",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStateMachine",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-data-types"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Function-Drivers",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterface",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream"
              ],
              "title": "Function Drivers"
            },
            {
              "anchor": "Device-Drivers",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevice"
              ],
              "title": "Device Drivers"
            },
            {
              "anchor": "Base-Classes",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSource"
              ],
              "title": "Base Classes"
            },
            {
              "abstract": [
                {
                  "text": "Properties on the device and interface classes in the service plane.",
                  "type": "text"
                }
              ],
              "anchor": "IOServicePlane-Properties",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey"
              ],
              "title": "IOServicePlane Properties"
            },
            {
              "anchor": "Version-Number",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostVersionNumber",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostVersionString"
              ],
              "title": "Version Number"
            },
            {
              "anchor": "Error-Domain",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostErrorDomain"
              ],
              "title": "Error Domain"
            },
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateMachine",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateMachine",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStateMachine",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterface"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-data-types"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusFromMessage",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageTypeFromMessage"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey/title",
          "value": "IOUSBHostDevicePropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevicePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevicePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSource/title",
          "value": "IOUSBHostIOSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIOSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIOSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe/title",
          "value": "IOUSBHostPipe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPipe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPipe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/title",
          "value": "IOUSBHostPropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterface/title",
          "value": "IOUSBHostInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStateMachine/title",
          "value": "IOUSBHostCIPortStateMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStateMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStateMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStateMachine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStateMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObject/title",
          "value": "IOUSBHostObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostErrorDomain/title",
          "value": "IOUSBHostErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevice/title",
          "value": "IOUSBHostDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/title",
          "value": "IOUSBHostMatchingPropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface/title",
          "value": "IOUSBHostControllerInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream/title",
          "value": "IOUSBHostStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine/title",
          "value": "IOUSBHostCIEndpointStateMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIEndpointStateMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIEndpointStateMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterfacePropertyKey/title",
          "value": "IOUSBHostInterfacePropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterfacePropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterfacePropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStateMachine/title",
          "value": "IOUSBHostCIControllerStateMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStateMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIControllerStateMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStateMachine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIControllerStateMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStateMachine/title",
          "value": "IOUSBHostCIDeviceStateMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStateMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceStateMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStateMachine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceStateMachine"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
