{
  "abstract": [
    {
      "text": "Retrieve the properties of the media in the user’s iTunes library.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "iTunesLibrary",
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.13",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "iTunes Library"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With this framework, you can retrieve media information, such as track and playlist metadata, directly from the user’s iTunes library, eliminating the need to query the iTunes XML file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To use this framework, create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:error:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class method. You can interrogate the instance that returns to obtain its properties and the properties of its media items. For example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You must code sign your app to retrieve information with this framework, and iTunes library access is read-only. This framework is available to users with iTunes 11 or later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ITLIB_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "ITLIB_AVAILABLE",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlib_available"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ITLIB_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "ITLIB_EXPORT",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlib_export"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ITLIB_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "ITLIB_EXTERN",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlib_extern"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_INIT_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ITLIB_INIT_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_INIT_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "ITLIB_INIT_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlib_init_unavailable"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibAlbum": {
      "abstract": [
        {
          "text": "This class provides information about an album in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibAlbum"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibAlbum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibAlbum"
        }
      ],
      "role": "symbol",
      "title": "ITLibAlbum",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibalbum"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtist": {
      "abstract": [
        {
          "text": "This class represents an artist, such as the performer of a song.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibArtist"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtist"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtist",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartist"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtwork": {
      "abstract": [
        {
          "text": "This class represents the artwork for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibArtwork"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtwork"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtwork",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartwork"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntity": {
      "abstract": [
        {
          "text": "This class describes a media entity, which can be a media item, such as an audio track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaEntity"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaEntity"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaEntity",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaentity"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem": {
      "abstract": [
        {
          "text": "This class describes a media item (a track) in the iTunes library, such as a song, a video, or a podcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItem"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItem"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItem",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo": {
      "abstract": [
        {
          "text": "This class encapsulates the video information of a video media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemVideoInfo"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemVideoInfo"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemVideoInfo",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemvideoinfo"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist": {
      "abstract": [
        {
          "text": "This class describes a playlist in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibPlaylist"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibPlaylist"
        }
      ],
      "role": "symbol",
      "title": "ITLibPlaylist",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibplaylist"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary": {
      "abstract": [
        {
          "text": "This class serves as the entry point to the iTunesLibrary framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibrary"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibrary"
        }
      ],
      "role": "symbol",
      "title": "ITLibrary",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:error:": {
      "abstract": [
        {
          "text": "Creates and initializes an instance of ",
          "type": "text"
        },
        {
          "code": "ITLibrary",
          "type": "codeVoice"
        },
        {
          "text": " that can retrieve media entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "libraryWithAPIVersion:error:"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "libraryWithAPIVersion:error:"
        }
      ],
      "role": "symbol",
      "title": "libraryWithAPIVersion:error:",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/librarywithapiversion:error:"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibraryDidChangeNotification": {
      "abstract": [
        {
          "text": "This notification is sent to NSDistributedNotificationCenter when a change has occurred in the library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ITLibraryDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibraryDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "ITLibraryDidChangeNotification",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrarydidchangenotification"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Albums-and-Playlists",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibAlbum",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist"
      ],
      "title": "Albums and Playlists"
    },
    {
      "anchor": "Media-Items",
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntity",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtist",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtwork",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo"
      ],
      "title": "Media Items"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Albums-and-Playlists",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibAlbum",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibPlaylist"
              ],
              "title": "Albums and Playlists"
            },
            {
              "anchor": "Media-Items",
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaEntity",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtist",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtwork",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo"
              ],
              "title": "Media Items"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibraryDidChangeNotification"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_AVAILABLE",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_EXPORT",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_EXTERN",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLIB_INIT_UNAVAILABLE"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo/title",
          "value": "ITLibMediaItemVideoInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemVideoInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemVideoInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist/title",
          "value": "ITLibPlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibPlaylist/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibAlbum/title",
          "value": "ITLibAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibAlbum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibAlbum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem/title",
          "value": "ITLibMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/title",
          "value": "ITLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaEntity/title",
          "value": "ITLibMediaEntity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaEntity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaEntity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaEntity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaEntity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtist/title",
          "value": "ITLibArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtist/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtwork/title",
          "value": "ITLibArtwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtwork/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtwork"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
