{
  "abstract": [
    {
      "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "JavaScriptCore",
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.5",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "JavaScriptCore"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The JavaScriptCore framework provides the ability to evaluate JavaScript programs from within Swift, Objective-C, and C-based apps. You can use also use JavaScriptCore to insert custom objects into the JavaScript environment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithDouble(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSBigIntCreateWithDouble"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithDouble(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSBigIntCreateWithDouble"
        }
      ],
      "role": "symbol",
      "title": "JSBigIntCreateWithDouble(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsbigintcreatewithdouble(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithInt64(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSBigIntCreateWithInt64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithInt64(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSBigIntCreateWithInt64"
        }
      ],
      "role": "symbol",
      "title": "JSBigIntCreateWithInt64(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsbigintcreatewithint64(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithString(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSBigIntCreateWithString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithString(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSBigIntCreateWithString"
        }
      ],
      "role": "symbol",
      "title": "JSBigIntCreateWithString(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsbigintcreatewithstring(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithUInt64(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSBigIntCreateWithUInt64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithUInt64(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSBigIntCreateWithUInt64"
        }
      ],
      "role": "symbol",
      "title": "JSBigIntCreateWithUInt64(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsbigintcreatewithuint64(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_ASSUME_NONNULL_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "JSC_ASSUME_NONNULL_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_ASSUME_NONNULL_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "JSC_ASSUME_NONNULL_BEGIN",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsc_assume_nonnull_begin"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_ASSUME_NONNULL_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "JSC_ASSUME_NONNULL_END"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_ASSUME_NONNULL_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "JSC_ASSUME_NONNULL_END",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsc_assume_nonnull_end"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_CF_ENUM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "JSC_CF_ENUM"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_CF_ENUM",
      "kind": "symbol",
      "role": "symbol",
      "title": "JSC_CF_ENUM",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsc_cf_enum"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_NONNULL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "JSC_NONNULL"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_NONNULL",
      "kind": "symbol",
      "role": "symbol",
      "title": "JSC_NONNULL",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsc_nonnull"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_NULLABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "JSC_NULLABLE"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_NULLABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "JSC_NULLABLE",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsc_nullable"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_NULL_UNSPECIFIED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "JSC_NULL_UNSPECIFIED"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_NULL_UNSPECIFIED",
      "kind": "symbol",
      "role": "symbol",
      "title": "JSC_NULL_UNSPECIFIED",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsc_null_unspecified"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContext": {
      "abstract": [
        {
          "text": "A JavaScript execution environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSContext"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSContext"
        }
      ],
      "role": "symbol",
      "title": "JSContext",
      "type": "topic",
      "url": "/documentation/javascriptcore/jscontext"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSExport": {
      "abstract": [
        {
          "text": "The protocol for exporting Objective-C objects to JavaScript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSExport"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSExport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSExport"
        }
      ],
      "role": "symbol",
      "title": "JSExport",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsexport"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSManagedValue": {
      "abstract": [
        {
          "text": "A JavaScript value with conditional retain behavior to provide automatic memory management.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSManagedValue"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSManagedValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSManagedValue"
        }
      ],
      "role": "symbol",
      "title": "JSManagedValue",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsmanagedvalue"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSRelationCondition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSRelationCondition"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSRelationCondition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSRelationCondition"
        }
      ],
      "role": "symbol",
      "title": "JSRelationCondition",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsrelationcondition"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue": {
      "abstract": [
        {
          "text": "A JavaScript value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValue"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValue"
        }
      ],
      "role": "symbol",
      "title": "JSValue",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompare(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueCompare"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@JSRelationCondition",
          "text": "JSRelationCondition"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompare(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueCompare"
        }
      ],
      "role": "symbol",
      "title": "JSValueCompare(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvaluecompare(_:_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareDouble(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueCompareDouble"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@JSRelationCondition",
          "text": "JSRelationCondition"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareDouble(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueCompareDouble"
        }
      ],
      "role": "symbol",
      "title": "JSValueCompareDouble(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvaluecomparedouble(_:_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareInt64(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueCompareInt64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@JSRelationCondition",
          "text": "JSRelationCondition"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareInt64(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueCompareInt64"
        }
      ],
      "role": "symbol",
      "title": "JSValueCompareInt64(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvaluecompareint64(_:_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareUInt64(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueCompareUInt64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@JSRelationCondition",
          "text": "JSRelationCondition"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareUInt64(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueCompareUInt64"
        }
      ],
      "role": "symbol",
      "title": "JSValueCompareUInt64(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvaluecompareuint64(_:_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsBigInt(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueIsBigInt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsBigInt(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueIsBigInt"
        }
      ],
      "role": "symbol",
      "title": "JSValueIsBigInt(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueisbigint(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToInt32(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueToInt32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToInt32(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueToInt32"
        }
      ],
      "role": "symbol",
      "title": "JSValueToInt32(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvaluetoint32(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToInt64(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueToInt64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToInt64(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueToInt64"
        }
      ],
      "role": "symbol",
      "title": "JSValueToInt64(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvaluetoint64(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToUInt32(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueToUInt32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToUInt32(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueToUInt32"
        }
      ],
      "role": "symbol",
      "title": "JSValueToUInt32(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvaluetouint32(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToUInt64(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueToUInt64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToUInt64(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueToUInt64"
        }
      ],
      "role": "symbol",
      "title": "JSValueToUInt64(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvaluetouint64(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine": {
      "abstract": [
        {
          "text": "A self-contained environment for JavaScript execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSVirtualMachine"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSVirtualMachine"
        }
      ],
      "role": "symbol",
      "title": "JSVirtualMachine",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvirtualmachine"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/c-javascriptcore-api": {
      "abstract": [
        {
          "text": "Browse the alternative C-based APIs for JavaScriptCore.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/c-javascriptcore-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "C JavaScriptCore API",
      "type": "topic",
      "url": "/documentation/javascriptcore/c-javascriptcore-api"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/javascriptcore-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/javascriptcore-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "JavaScriptCore Constants",
      "type": "topic",
      "url": "/documentation/javascriptcore/javascriptcore-constants"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeBigInt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypeBigInt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSType",
          "text": "JSType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeBigInt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypeBigInt"
        }
      ],
      "role": "symbol",
      "title": "kJSTypeBigInt",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypebigint"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Execution-Environment",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContext"
      ],
      "title": "Execution Environment"
    },
    {
      "anchor": "JavaScript-Code",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSManagedValue"
      ],
      "title": "JavaScript Code"
    },
    {
      "anchor": "Native-Code",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSExport"
      ],
      "title": "Native Code"
    },
    {
      "anchor": "C-API",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/c-javascriptcore-api"
      ],
      "title": "C API"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/javascriptcore-constants"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeBigInt"
      ],
      "title": "Variables"
    },
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithDouble(_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithInt64(_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithString(_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithUInt64(_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompare(_:_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareDouble(_:_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareInt64(_:_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareUInt64(_:_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsBigInt(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToInt32(_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToInt64(_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToUInt32(_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToUInt64(_:_:_:)"
      ],
      "title": "Functions"
    },
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSRelationCondition"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Execution-Environment",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContext"
              ],
              "title": "Execution Environment"
            },
            {
              "anchor": "JavaScript-Code",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSManagedValue"
              ],
              "title": "JavaScript Code"
            },
            {
              "anchor": "Native-Code",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSExport"
              ],
              "title": "Native Code"
            },
            {
              "anchor": "C-API",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/c-javascriptcore-api"
              ],
              "title": "C API"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/javascriptcore-constants"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithDouble(_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithInt64(_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithString(_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSBigIntCreateWithUInt64(_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompare(_:_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareDouble(_:_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareInt64(_:_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueCompareUInt64(_:_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsBigInt(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToInt32(_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToInt64(_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToUInt32(_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueToUInt64(_:_:_:)"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_ASSUME_NONNULL_BEGIN",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_ASSUME_NONNULL_END",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_CF_ENUM",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_NONNULL",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_NULLABLE",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSC_NULL_UNSPECIFIED"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSRelationCondition"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSRelationCondition/title",
          "value": "JSRelationCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSRelationCondition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSRelationCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSRelationCondition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSRelationCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSExport/title",
          "value": "JSExport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSExport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSExport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSExport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSExport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueCompareUInt64(_:_:_:_:)/title",
          "value": "JSValueCompareUInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueCompareUInt64(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueCompareUInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueToUInt32(_:_:_:)/title",
          "value": "JSValueToUInt32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueToUInt32(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueToUInt32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSBigIntCreateWithInt64(_:_:_:)/title",
          "value": "JSBigIntCreateWithInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSBigIntCreateWithInt64(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSBigIntCreateWithInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContext/title",
          "value": "JSContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsBigInt(_:_:)/title",
          "value": "JSValueIsBigInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsBigInt(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsBigInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue/title",
          "value": "JSValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSBigIntCreateWithString(_:_:_:)/title",
          "value": "JSBigIntCreateWithString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSBigIntCreateWithString(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSBigIntCreateWithString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueCompareDouble(_:_:_:_:)/title",
          "value": "JSValueCompareDouble"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueCompareDouble(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueCompareDouble"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSBigIntCreateWithUInt64(_:_:_:)/title",
          "value": "JSBigIntCreateWithUInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSBigIntCreateWithUInt64(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSBigIntCreateWithUInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSManagedValue/title",
          "value": "JSManagedValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSManagedValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSManagedValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSManagedValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSManagedValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSBigIntCreateWithDouble(_:_:_:)/title",
          "value": "JSBigIntCreateWithDouble"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSBigIntCreateWithDouble(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSBigIntCreateWithDouble"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeBigInt/title",
          "value": "kJSTypeBigInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeBigInt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypeBigInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueCompare(_:_:_:_:)/title",
          "value": "JSValueCompare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueCompare(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueCompare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueToInt64(_:_:_:)/title",
          "value": "JSValueToInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueToInt64(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueToInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSVirtualMachine/title",
          "value": "JSVirtualMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSVirtualMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSVirtualMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSVirtualMachine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSVirtualMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueToInt32(_:_:_:)/title",
          "value": "JSValueToInt32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueToInt32(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueToInt32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueCompareInt64(_:_:_:_:)/title",
          "value": "JSValueCompareInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueCompareInt64(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueCompareInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueToUInt64(_:_:_:)/title",
          "value": "JSValueToUInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueToUInt64(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueToUInt64"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
