{
  "abstract": [
    {
      "text": "Classify text and other token-based content into developer-defined categories.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "LatentSemanticMapping",
    "modules": [
      {
        "name": "Latent Semantic Mapping"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.5",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Latent Semantic Mapping"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Latent Semantic Mapping framework classifies texts based on latent semantic information. The C-based functions of this API are designed to be language-independent and are Unicode-based.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For other natural language processing functionality, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/NaturalLanguage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping": {
      "abstract": [
        {
          "text": "Classify text and other token-based content into developer-defined categories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping",
      "kind": "symbol",
      "role": "collection",
      "title": "Latent Semantic Mapping",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap": {
      "abstract": [
        {
          "text": "A map between a set of categories and related text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMMap"
        }
      ],
      "role": "symbol",
      "title": "LSMMap",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmmap"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResult": {
      "abstract": [
        {
          "text": "A result of a lookup in a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMResult"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMResult"
        }
      ],
      "role": "symbol",
      "title": "LSMResult",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmresult"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText": {
      "abstract": [
        {
          "text": "An input text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LSMText"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMText"
        }
      ],
      "role": "symbol",
      "title": "LSMText",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/lsmtext"
    },
    "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/error-codes": {
      "abstract": [
        {
          "text": "Error codes in Latent Semantic Mapping.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/latentsemanticmapping/error-codes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Text-Classification",
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText",
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResult"
      ],
      "title": "Text Classification"
    },
    {
      "anchor": "Error-Handling",
      "identifiers": [
        "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/error-codes"
      ],
      "title": "Error Handling"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Text-Classification",
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMMap",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMText",
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/LSMResult"
              ],
              "title": "Text Classification"
            },
            {
              "anchor": "Error-Handling",
              "identifiers": [
                "doc://com.apple.latentsemanticmapping/documentation/LatentSemanticMapping/error-codes"
              ],
              "title": "Error Handling"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMResult/title",
          "value": "LSMResultRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMResultRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMResultRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/title",
          "value": "LSMMapRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMMapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMText/title",
          "value": "LSMTextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.latentsemanticmapping~1documentation~1LatentSemanticMapping~1LSMText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMTextRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/latentsemanticmapping"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/latentsemanticmapping"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
