{
  "abstract": [
    {
      "text": "Present a standard local authentication view icon in a custom authentication view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "LocalAuthenticationEmbeddedUI",
    "modules": [
      {
        "name": "Local Authentication Embedded UI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Local Authentication Embedded UI"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you authenticate users with the ",
              "type": "text"
            },
            {
              "code": "Local Authentication",
              "type": "codeVoice"
            },
            {
              "text": " framework, the framework",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "handles all user interaction by default. If you want to create a custom authentication",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "user interface, build it around an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instance. The authentication view displays an icon that users associate with biometric",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "authentication, like the Touch ID icon, and then modifies that icon over time to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "reflect changes in the authentication state. You can add other text, images, or interactive",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "elements to your custom view as needed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "localauthenticationembeddedui-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For all local authentication operations, the system manages the underlying biometric",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "data, but with a local authentication view, you can customize the authentication",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interface to match the design of your app. At the same time, familiar iconography",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "helps users understand what you are asking from them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI": {
      "abstract": [
        {
          "text": "Present a standard local authentication view icon in a custom authentication view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication Embedded UI",
      "type": "topic",
      "url": "/documentation/localauthenticationembeddedui"
    },
    "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView": {
      "abstract": [
        {
          "text": "A graphical representation of the state of biometric authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAAuthenticationView"
        }
      ],
      "identifier": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAAuthenticationView"
        }
      ],
      "role": "symbol",
      "title": "LAAuthenticationView",
      "type": "topic",
      "url": "/documentation/localauthenticationembeddedui/laauthenticationview"
    },
    "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/local-authentication-embedded-ui-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/local-authentication-embedded-ui-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Local Authentication Embedded UI Data Types",
      "type": "topic",
      "url": "/documentation/localauthenticationembeddedui/local-authentication-embedded-ui-data-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "localauthenticationembeddedui-1": {
      "alt": "A screenshot of a view with the title Access My Transactions above a circular finger print icon, which is in turn above a secure text entry field. The finger print icon is highlighted.",
      "identifier": "localauthenticationembeddedui-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3f09f35196c3578fefba573ce80eb4d3/localauthenticationembeddedui-1@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/64ff9c718a1bc54deb1d0492d20dd458/localauthenticationembeddedui-1~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "The-Local-Authentication-View",
      "identifiers": [
        "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView"
      ],
      "title": "The Local Authentication View"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/local-authentication-embedded-ui-data-types"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "The-Local-Authentication-View",
              "identifiers": [
                "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView"
              ],
              "title": "The Local Authentication View"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/local-authentication-embedded-ui-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAAuthenticationView/title",
          "value": "LAAuthenticationView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAAuthenticationView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAuthenticationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAAuthenticationView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAuthenticationView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthenticationembeddedui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthenticationembeddedui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
