{
  "abstract": [
    {
      "text": "Capture content with your app’s camera experience when the device is",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "locked.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "LockedCameraCapture",
    "modules": [
      {
        "name": "LockedCameraCapture"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "18.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "18.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "LockedCameraCapture"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the LockedCameraCapture framework to create an extension that allows people",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to launch your app’s camera experience and capture content quickly when the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "device is locked. This extension makes your camera experience accessible to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "people from Control Center, the Lock Screen, or the Action button.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "locked-camera-capture-overview",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Locked-Camera-Capture-PageImage-card.png": {
      "alt": "A stylistic image of a control on the Lock Screen with a camera icon and a camera icon and arrow pointing to the Action button.",
      "identifier": "Locked-Camera-Capture-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/554cb5f26e2e6a1f759be4a76fdd33fd/Locked-Camera-Capture-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3c2a77a54fb9667d1e58e1995951eb99/Locked-Camera-Capture-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture": {
      "abstract": [
        {
          "text": "Capture content with your app’s camera experience when the device is",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "locked.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture",
      "kind": "symbol",
      "role": "collection",
      "title": "LockedCameraCapture",
      "type": "topic",
      "url": "/documentation/lockedcameracapture"
    },
    "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/Creating-a-camera-experience-for-the-Lock-Screen": {
      "abstract": [
        {
          "text": "Offer your app’s camera experience on locked devices from Control Center, the Lock Screen, and the Action button.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/Creating-a-camera-experience-for-the-Lock-Screen",
      "images": [
        {
          "identifier": "Locked-Camera-Capture-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Creating a camera experience for the Lock Screen",
      "type": "topic",
      "url": "/documentation/lockedcameracapture/creating-a-camera-experience-for-the-lock-screen"
    },
    "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureExtension": {
      "abstract": [
        {
          "text": "A protocol that creates a locked camera capture extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureExtension"
        }
      ],
      "identifier": "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureExtension"
        }
      ],
      "role": "symbol",
      "title": "LockedCameraCaptureExtension",
      "type": "topic",
      "url": "/documentation/lockedcameracapture/lockedcameracaptureextension"
    },
    "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureExtensionScene": {
      "abstract": [
        {
          "text": "A protocol that provides the UI for the locked camera capture extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureExtensionScene"
        }
      ],
      "identifier": "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureExtensionScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureExtensionScene"
        }
      ],
      "role": "symbol",
      "title": "LockedCameraCaptureExtensionScene",
      "type": "topic",
      "url": "/documentation/lockedcameracapture/lockedcameracaptureextensionscene"
    },
    "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureManager": {
      "abstract": [
        {
          "text": "An object that provides handling of captured content and transitioning to the extension’s containing app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureManager"
        }
      ],
      "identifier": "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureManager"
        }
      ],
      "role": "symbol",
      "title": "LockedCameraCaptureManager",
      "type": "topic",
      "url": "/documentation/lockedcameracapture/lockedcameracapturemanager"
    },
    "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureSession": {
      "abstract": [
        {
          "text": "An object that can request to open the extension’s containing app and receives session configuration",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureSession"
        }
      ],
      "identifier": "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureSession"
        }
      ],
      "role": "symbol",
      "title": "LockedCameraCaptureSession",
      "type": "topic",
      "url": "/documentation/lockedcameracapture/lockedcameracapturesession"
    },
    "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureUIScene": {
      "abstract": [
        {
          "text": "A structure that contains the session object and UI to display for the locked camera capture extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureUIScene"
        }
      ],
      "identifier": "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureUIScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureUIScene"
        }
      ],
      "role": "symbol",
      "title": "LockedCameraCaptureUIScene",
      "type": "topic",
      "url": "/documentation/lockedcameracapture/lockedcameracaptureuiscene"
    },
    "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureVersionNumber": {
      "abstract": [
        {
          "text": "Project version number for LockedCameraCapture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureVersionNumber"
        }
      ],
      "identifier": "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureVersionNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "LockedCameraCaptureVersionNumber",
      "type": "topic",
      "url": "/documentation/lockedcameracapture/lockedcameracaptureversionnumber"
    },
    "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureVersionString": {
      "abstract": [
        {
          "text": "Project version string for LockedCameraCapture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LockedCameraCaptureVersionString"
        }
      ],
      "identifier": "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureVersionString",
      "kind": "symbol",
      "role": "symbol",
      "title": "LockedCameraCaptureVersionString",
      "type": "topic",
      "url": "/documentation/lockedcameracapture/lockedcameracaptureversionstring"
    },
    "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/NSUserActivityTypeLockedCameraCapture": {
      "abstract": [
        {
          "text": "A type to use when opening your app from the capture extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivityTypeLockedCameraCapture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/NSUserActivityTypeLockedCameraCapture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserActivityTypeLockedCameraCapture"
        }
      ],
      "role": "symbol",
      "title": "NSUserActivityTypeLockedCameraCapture",
      "type": "topic",
      "url": "/documentation/lockedcameracapture/nsuseractivitytypelockedcameracapture"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "locked-camera-capture-overview": {
      "alt": "A conceptual image that shows a control with a camera icon on the Lock Screen on iPhone, in Control Center on iPhone, and being performed with the Action button on iPhone 15 Pro.",
      "identifier": "locked-camera-capture-overview",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/92356c4d536464fbcc88d5a37400d82a/locked-camera-capture-overview@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/Creating-a-camera-experience-for-the-Lock-Screen"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Capture-and-launch",
      "identifiers": [
        "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureUIScene",
        "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureSession"
      ],
      "title": "Capture and launch"
    },
    {
      "anchor": "App-integration",
      "identifiers": [
        "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureManager",
        "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/NSUserActivityTypeLockedCameraCapture"
      ],
      "title": "App integration"
    },
    {
      "anchor": "Extension",
      "identifiers": [
        "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureExtension",
        "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureExtensionScene"
      ],
      "title": "Extension"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/Creating-a-camera-experience-for-the-Lock-Screen"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "App-integration",
              "identifiers": [
                "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/NSUserActivityTypeLockedCameraCapture"
              ],
              "title": "App integration"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureVersionNumber",
                "doc://com.apple.LockedCameraCapture/documentation/LockedCameraCapture/LockedCameraCaptureVersionString"
              ],
              "title": "Variables"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.LockedCameraCapture~1documentation~1LockedCameraCapture~1NSUserActivityTypeLockedCameraCapture/title",
          "value": "NSUserActivityTypeLockedCameraCapture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.LockedCameraCapture~1documentation~1LockedCameraCapture~1NSUserActivityTypeLockedCameraCapture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserActivityTypeLockedCameraCapture"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/lockedcameracapture"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/lockedcameracapture"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
