{
  "abstract": [
    {
      "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "MapKit",
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.9",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.2",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "MapKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use MapKit to give your app a sense of place with maps and location information. You can use the MapKit framework to:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Embed maps directly into your app’s windows and views.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add annotations and overlays to a map to call out points of interest.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add LookAround capabilities to enable users to explore locations at street level.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Respond to user interactions with well known points of interest, geographical features, and boundaries.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Provide text completion to make it easy for users to search for a destination or point of interest.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppleMapsServerAPI": {
      "abstract": [
        {
          "text": "Reduce API calls and conserve device power by streamlining your app’s georelated searches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppleMapsServerAPI",
      "kind": "symbol",
      "role": "collection",
      "title": "Apple Maps Server API",
      "type": "topic",
      "url": "/documentation/AppleMapsServerAPI"
    },
    "doc://com.apple.documentation/documentation/MapKitJS": {
      "abstract": [
        {
          "text": "Embed interactive Apple Maps on your website, annotate points of interest, and perform georelated searches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MapKitJS",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit JS",
      "type": "topic",
      "url": "/documentation/MapKitJS"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/AnyMapContent": {
      "abstract": [
        {
          "text": "A type-erased map content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnyMapContent"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/AnyMapContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnyMapContent"
        }
      ],
      "role": "symbol",
      "title": "AnyMapContent",
      "type": "topic",
      "url": "/documentation/mapkit/anymapcontent"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCircle": {
      "abstract": [
        {
          "text": "A circular overlay with a configurable radius that you center on a geographic coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKCircle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCircle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCircle"
        }
      ],
      "role": "symbol",
      "title": "MKCircle",
      "type": "topic",
      "url": "/documentation/mapkit/mkcircle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCircleView": {
      "abstract": [
        {
          "text": "Provides the visual representation for an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCircle",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " annotation object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKCircleView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCircleView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCircleView"
        }
      ],
      "role": "symbol",
      "title": "MKCircleView",
      "type": "topic",
      "url": "/documentation/mapkit/mkcircleview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathView": {
      "abstract": [
        {
          "text": "Represents a generic overlay that draws its contents using a Core Graphics path data type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayPathView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayPathView"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayPathView",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView": {
      "abstract": [
        {
          "text": "Defines the basic behavior associated with all overlay views.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayView"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayView",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolygon": {
      "abstract": [
        {
          "text": "A closed polygon overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolygon"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolygon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolygon"
        }
      ],
      "role": "symbol",
      "title": "MKPolygon",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolygon"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolygonView": {
      "abstract": [
        {
          "text": "Provides the visual representation for an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolygon",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " annotation object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolygonView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolygonView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolygonView"
        }
      ],
      "role": "symbol",
      "title": "MKPolygonView",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolygonview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolyline": {
      "abstract": [
        {
          "text": "An open polygon overlay consisting of one or more connected line segments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolyline"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolyline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolyline"
        }
      ],
      "role": "symbol",
      "title": "MKPolyline",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolyline"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolylineView": {
      "abstract": [
        {
          "text": "Provides the visual representation for an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolyline",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " annotation object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolylineView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolylineView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolylineView"
        }
      ],
      "role": "symbol",
      "title": "MKPolylineView",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolylineview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoder": {
      "abstract": [
        {
          "text": "Provides services for converting a map coordinate (specified as a latitude/longitude pair) into information about that coordinate, such as the country or region, city, or street.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MKReverseGeocoder"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoder",
      "kind": "symbol",
      "role": "symbol",
      "title": "MKReverseGeocoder",
      "type": "topic",
      "url": "/documentation/mapkit/mkreversegeocoder"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoderDelegate": {
      "abstract": [
        {
          "text": "Defines the interface for receiving messages from an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoder",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MKReverseGeocoderDelegate"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoderDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "MKReverseGeocoderDelegate",
      "type": "topic",
      "url": "/documentation/mapkit/mkreversegeocoderdelegate"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MK_CLASS_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MK_CLASS_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MK_CLASS_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "MK_CLASS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/mapkit/mk_class_available"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MK_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MK_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MK_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "MK_EXTERN",
      "type": "topic",
      "url": "/documentation/mapkit/mk_extern"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MK_SUPPORTS_VIEW_CLASSES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MK_SUPPORTS_VIEW_CLASSES"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MK_SUPPORTS_VIEW_CLASSES",
      "kind": "symbol",
      "role": "symbol",
      "title": "MK_SUPPORTS_VIEW_CLASSES",
      "type": "topic",
      "url": "/documentation/mapkit/mk_supports_view_classes"
    },
    "doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs": {
      "abstract": [
        {
          "text": "Access Maps URLs and options for displaying Maps information across Apple platforms.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs",
      "kind": "article",
      "role": "article",
      "title": "Adopting unified Maps URLs",
      "type": "topic",
      "url": "/documentation/mapkit/unified-map-urls"
    },
    "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit": {
      "abstract": [],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MapKit for AppKit and UIKit",
      "type": "topic",
      "url": "/documentation/mapkit/mapkit-for-appkit-and-uikit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-swiftui": {
      "abstract": [
        {
          "text": "MapKit for SwiftUI allows you to build map-centric views and apps across Apple platforms. You can design expressive and highly interactive Maps with minimal code by composing views, using ViewBuilders and view modifiers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-swiftui",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MapKit for SwiftUI",
      "type": "topic",
      "url": "/documentation/mapkit/mapkit-for-swiftui"
    },
    "doc://com.apple.mapkit/documentation/MapKit/mapkit_for_appkit_and_uikit-deprecated-symbols": {
      "abstract": [
        {
          "text": "MapKit classes, protocols, and entitlements that are no longer supported.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/mapkit_for_appkit_and_uikit-deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/mapkit/mapkit_for_appkit_and_uikit-deprecated-symbols"
    },
    "doc://com.apple.mapkit/documentation/MapKit/preparing-your-app-to-be-the-default-navigation-app": {
      "abstract": [
        {
          "text": "Configure your navigation app so people can set it as the default on their devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/preparing-your-app-to-be-the-default-navigation-app",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to be the default navigation app",
      "type": "topic",
      "url": "/documentation/mapkit/preparing-your-app-to-be-the-default-navigation-app"
    },
    "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497": {
      "identifier": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497",
      "title": "Location and Maps Programming Guide",
      "titleInlineContent": [
        {
          "text": "Location and Maps Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497",
        "doc://com.apple.documentation/documentation/MapKitJS",
        "doc://com.apple.documentation/documentation/AppleMapsServerAPI"
      ],
      "title": "Related Documentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "The-MapKit-APIs",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
        "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-swiftui",
        "doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs"
      ],
      "title": "The MapKit APIs"
    },
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/preparing-your-app-to-be-the-default-navigation-app",
        "doc://com.apple.mapkit/documentation/MapKit/mapkit_for_appkit_and_uikit-deprecated-symbols"
      ],
      "title": "Articles"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKCircleView",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathView",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView",
        "doc://com.apple.mapkit/documentation/MapKit/MKPolygonView",
        "doc://com.apple.mapkit/documentation/MapKit/MKPolylineView"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/AnyMapContent"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "The-MapKit-APIs",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
                "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-swiftui",
                "doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs"
              ],
              "title": "The MapKit APIs"
            },
            {
              "anchor": "Articles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/preparing-your-app-to-be-the-default-navigation-app",
                "doc://com.apple.mapkit/documentation/MapKit/mapkit_for_appkit_and_uikit-deprecated-symbols"
              ],
              "title": "Articles"
            },
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKCircleView",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathView",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView",
                "doc://com.apple.mapkit/documentation/MapKit/MKPolygonView",
                "doc://com.apple.mapkit/documentation/MapKit/MKPolylineView",
                "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoder"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoderDelegate"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MK_CLASS_AVAILABLE",
                "doc://com.apple.mapkit/documentation/MapKit/MK_EXTERN",
                "doc://com.apple.mapkit/documentation/MapKit/MK_SUPPORTS_VIEW_CLASSES"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497",
                "doc://com.apple.documentation/documentation/MapKitJS",
                "doc://com.apple.documentation/documentation/AppleMapsServerAPI"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircleView/title",
          "value": "MKCircleView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircleView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircleView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircleView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircleView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircle/title",
          "value": "MKCircle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineView/title",
          "value": "MKPolylineView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolylineView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolylineView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/title",
          "value": "MKPolyline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/title",
          "value": "MKOverlayView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathView/title",
          "value": "MKOverlayPathView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayPathView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayPathView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygon/title",
          "value": "MKPolygon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygonView/title",
          "value": "MKPolygonView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygonView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygonView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygonView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygonView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
