{
  "abstract": [
    {
      "text": "Make your app’s media more accessible by supporting people’s systemwide preferences for video and audio content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "MediaAccessibility",
    "modules": [
      {
        "name": "Media Accessibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.9",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Media Accessibility"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "People can specify a variety of preferences about media content such as videos, songs, and images in Accessibility system settings.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, people can customize the appearance of captions that appear when they watch videos.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The Media Accessibility framework provides information about these accessibility settings for media content so you can adapt your app’s UI to people’s preferences.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility": {
      "abstract": [
        {
          "text": "Make your app’s media more accessible by supporting people’s systemwide preferences for video and audio content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Accessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceIsCustomized(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceIsCustomized"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MACaptionAppearanceDomain",
          "text": "MACaptionAppearanceDomain"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceIsCustomized(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceIsCustomized"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceIsCustomized(_:)",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearanceiscustomized(_:)"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MA_EXTERN_C_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MA_EXTERN_C_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MA_EXTERN_C_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "MA_EXTERN_C_BEGIN",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/ma_extern_c_begin"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MA_EXTERN_C_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MA_EXTERN_C_END"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MA_EXTERN_C_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "MA_EXTERN_C_END",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/ma_extern_c_end"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/captions": {
      "abstract": [
        {
          "text": "Coordinate the presentation of closed-captioned data for your app’s media files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/captions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Captions",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/captions"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/flashing-lights": {
      "abstract": [
        {
          "text": "Detect, mitigate, and inform people about flashing lights in media content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/flashing-lights",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Flashing lights",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/flashing-lights"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/music-haptics": {
      "abstract": [
        {
          "text": "Play haptic tracks along with known music tracks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/music-haptics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Music Haptics",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/music-haptics"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Features",
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/captions",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/flashing-lights",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/music-haptics"
      ],
      "title": "Features"
    },
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceIsCustomized(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Features",
              "identifiers": [
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/captions",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/flashing-lights",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/music-haptics"
              ],
              "title": "Features"
            },
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceIsCustomized(_:)"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MA_EXTERN_C_BEGIN",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MA_EXTERN_C_END"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceIsCustomized(_:)/title",
          "value": "MACaptionAppearanceIsCustomized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceIsCustomized(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceIsCustomized"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaaccessibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaaccessibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
