{
  "abstract": [
    {
      "text": "Enable support for media format readers; tap and process audio from an audio mix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediatoolbox/documentation/MediaToolbox"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "MediaToolbox",
    "modules": [
      {
        "name": "Media Toolbox"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "6.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "6.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "6.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.9",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Media Toolbox"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTRegisterProfessionalVideoWorkflowFormatReaders()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to enable the use of custom ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaExtension",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " format readers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to tap audio from an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer": {
      "abstract": [
        {
          "text": "An object that provides the interface to control the player’s transport behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayer",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayer"
    },
    "doc://com.apple.documentation/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/MediaExtension"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox": {
      "abstract": [
        {
          "text": "Enable support for media format readers; tap and process audio from an audio mix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Toolbox",
      "type": "topic",
      "url": "/documentation/mediatoolbox"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap": {
      "abstract": [
        {
          "text": "An audio processing tap object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTap"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTap"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTap",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtap"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCreate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new audio processing tap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTAudioProcessingTapCallbacks",
          "text": "MTAudioProcessingTapCallbacks"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapCreationFlags",
          "text": "MTAudioProcessingTapCreationFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapRef",
          "text": "MTAudioProcessingTap"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCreate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapCreate"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTapCreate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapcreate(_:_:_:_:)"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapFlags": {
      "abstract": [
        {
          "text": "Flags that indicate where to tap the audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapFlags"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapFlags"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTapFlags",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapflags"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetSourceAudio(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves source audio for an audio processing tap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapGetSourceAudio"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapRef",
          "text": "MTAudioProcessingTap"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMItemCount",
          "text": "CMItemCount"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioBufferList",
          "text": "AudioBufferList"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapFlags",
          "text": "MTAudioProcessingTapFlags"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMItemCount",
          "text": "CMItemCount"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetSourceAudio(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapGetSourceAudio"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTapGetSourceAudio(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapgetsourceaudio(_:_:_:_:_:_:)"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetStorage(_:)": {
      "abstract": [
        {
          "text": "Retrieves a custom storage pointer for an audio processing tap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapGetStorage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTAudioProcessingTapRef",
          "text": "MTAudioProcessingTap"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetStorage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapGetStorage"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTapGetStorage(_:)",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapgetstorage(_:)"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetTypeID()": {
      "abstract": [
        {
          "text": "Retrieves the type identifier for this audio processing tap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTAudioProcessingTapGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "MTAudioProcessingTapGetTypeID()",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtaudioprocessingtapgettypeid()"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTCopyLocalizedNameForMediaSubType(_:_:)": {
      "abstract": [
        {
          "text": "Returns a localized name for the specified media type and subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTCopyLocalizedNameForMediaSubType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FourCharCode",
          "text": "FourCharCode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTCopyLocalizedNameForMediaSubType(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTCopyLocalizedNameForMediaSubType"
        }
      ],
      "role": "symbol",
      "title": "MTCopyLocalizedNameForMediaSubType(_:_:)",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtcopylocalizednameformediasubtype(_:_:)"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTCopyLocalizedNameForMediaType(_:)": {
      "abstract": [
        {
          "text": "Returns a localized name for the specified media type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTCopyLocalizedNameForMediaType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTCopyLocalizedNameForMediaType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTCopyLocalizedNameForMediaType"
        }
      ],
      "role": "symbol",
      "title": "MTCopyLocalizedNameForMediaType(_:)",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtcopylocalizednameformediatype(_:)"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTRegisterProfessionalVideoWorkflowFormatReaders()": {
      "abstract": [
        {
          "text": "Enables the use of media format readers that support professional video workflows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRegisterProfessionalVideoWorkflowFormatReaders"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTRegisterProfessionalVideoWorkflowFormatReaders()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRegisterProfessionalVideoWorkflowFormatReaders"
        }
      ],
      "role": "symbol",
      "title": "MTRegisterProfessionalVideoWorkflowFormatReaders()",
      "type": "topic",
      "url": "/documentation/mediatoolbox/mtregisterprofessionalvideoworkflowformatreaders()"
    },
    "doc://com.apple.mediatoolbox/documentation/MediaToolbox/anonymous-enums": {
      "abstract": [],
      "identifier": "doc://com.apple.mediatoolbox/documentation/MediaToolbox/anonymous-enums",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous Enumerations",
      "type": "topic",
      "url": "/documentation/mediatoolbox/anonymous-enums"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Professional-video-workflows",
      "identifiers": [
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTRegisterProfessionalVideoWorkflowFormatReaders()"
      ],
      "title": "Professional video workflows"
    },
    {
      "anchor": "Audio-Taps",
      "identifiers": [
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCreate(_:_:_:_:)",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetSourceAudio(_:_:_:_:_:_:)",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetStorage(_:)",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetTypeID()",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapFlags",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap"
      ],
      "title": "Audio Taps"
    },
    {
      "anchor": "Utility",
      "identifiers": [
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTCopyLocalizedNameForMediaType(_:)",
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTCopyLocalizedNameForMediaSubType(_:_:)"
      ],
      "title": "Utility"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.mediatoolbox/documentation/MediaToolbox/anonymous-enums"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Professional-video-workflows",
              "identifiers": [
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTRegisterProfessionalVideoWorkflowFormatReaders()"
              ],
              "title": "Professional video workflows"
            },
            {
              "anchor": "Audio-Taps",
              "identifiers": [
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapCreate(_:_:_:_:)",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetSourceAudio(_:_:_:_:_:_:)",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetStorage(_:)",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapGetTypeID()",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTapFlags",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTAudioProcessingTap"
              ],
              "title": "Audio Taps"
            },
            {
              "anchor": "Utility",
              "identifiers": [
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTCopyLocalizedNameForMediaType(_:)",
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/MTCopyLocalizedNameForMediaSubType(_:_:)"
              ],
              "title": "Utility"
            },
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.mediatoolbox/documentation/MediaToolbox/anonymous-enums"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTap/title",
          "value": "MTAudioProcessingTapRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapFlags/title",
          "value": "MTAudioProcessingTapFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTCopyLocalizedNameForMediaSubType(_:_:)/title",
          "value": "MTCopyLocalizedNameForMediaSubType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTCopyLocalizedNameForMediaSubType(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTCopyLocalizedNameForMediaSubType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTRegisterProfessionalVideoWorkflowFormatReaders()/title",
          "value": "MTRegisterProfessionalVideoWorkflowFormatReaders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTRegisterProfessionalVideoWorkflowFormatReaders()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRegisterProfessionalVideoWorkflowFormatReaders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapGetTypeID()/title",
          "value": "MTAudioProcessingTapGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapGetSourceAudio(_:_:_:_:_:_:)/title",
          "value": "MTAudioProcessingTapGetSourceAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapGetSourceAudio(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapGetSourceAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCreate(_:_:_:_:)/title",
          "value": "MTAudioProcessingTapCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapCreate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapGetStorage(_:)/title",
          "value": "MTAudioProcessingTapGetStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTAudioProcessingTapGetStorage(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTAudioProcessingTapGetStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTCopyLocalizedNameForMediaType(_:)/title",
          "value": "MTCopyLocalizedNameForMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediatoolbox~1documentation~1MediaToolbox~1MTCopyLocalizedNameForMediaType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTCopyLocalizedNameForMediaType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediatoolbox"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediatoolbox"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
