{
  "abstract": [
    {
      "text": "Create a user interface for composing email and text messages, so users can edit and send messages without leaving your app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messageui/documentation/MessageUI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "MessageUI",
    "modules": [
      {
        "name": "Message UI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Message UI"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Message UI framework provides specialized view controllers for presenting standard composition interfaces for email and SMS (Short Messaging Service) text messages. Use these interfaces to add message delivery capabilities, without requiring the user to leave your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To display a composition interface, present the corresponding view controller modally from your app. Once presented, the user has the option to customize the contents before sending or canceling the message. Your custom delegate object then handles the dismissal of the view controller based on the user’s action. For information on how to present and dismiss view controllers, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/index.html#//apple_ref/doc/uid/TP40007457",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The view controllers in this framework provide methods for determining if you can send a given message type on the current iOS device. If you can’t send a message, don’t display the corresponding view controller.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messageui/documentation/MessageUI": {
      "abstract": [
        {
          "text": "Create a user interface for composing email and text messages, so users can edit and send messages without leaving your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Message UI",
      "type": "topic",
      "url": "/documentation/messageui"
    },
    "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeControllerDeferredAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MFMailComposeControllerDeferredAction"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeControllerDeferredAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MFMailComposeControllerDeferredAction"
        }
      ],
      "role": "symbol",
      "title": "MFMailComposeControllerDeferredAction",
      "type": "topic",
      "url": "/documentation/messageui/mfmailcomposecontrollerdeferredaction"
    },
    "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeViewController": {
      "abstract": [
        {
          "text": "A standard view controller, whose interface lets the user manage, edit, and send email messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MFMailComposeViewController"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MFMailComposeViewController"
        }
      ],
      "role": "symbol",
      "title": "MFMailComposeViewController",
      "type": "topic",
      "url": "/documentation/messageui/mfmailcomposeviewcontroller"
    },
    "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController": {
      "abstract": [
        {
          "text": "A standard view controller whose interface lets the user compose and send SMS or MMS messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MFMessageComposeViewController"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MFMessageComposeViewController"
        }
      ],
      "role": "symbol",
      "title": "MFMessageComposeViewController",
      "type": "topic",
      "url": "/documentation/messageui/mfmessagecomposeviewcontroller"
    },
    "https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/index.html#//apple_ref/doc/uid/TP40007457": {
      "identifier": "https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/index.html#//apple_ref/doc/uid/TP40007457",
      "title": "View Controller Programming Guide for iOS",
      "titleInlineContent": [
        {
          "text": "View Controller Programming Guide for iOS",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/index.html#//apple_ref/doc/uid/TP40007457"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Email-composition-interface",
      "identifiers": [
        "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeViewController"
      ],
      "title": "Email composition interface"
    },
    {
      "anchor": "Message-composition-interface",
      "identifiers": [
        "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController"
      ],
      "title": "Message composition interface"
    },
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeControllerDeferredAction"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Email-composition-interface",
              "identifiers": [
                "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeViewController"
              ],
              "title": "Email composition interface"
            },
            {
              "anchor": "Message-composition-interface",
              "identifiers": [
                "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController"
              ],
              "title": "Message composition interface"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeControllerDeferredAction"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewController/title",
          "value": "MFMessageComposeViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMessageComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMessageComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMailComposeViewController/title",
          "value": "MFMailComposeViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMailComposeViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMailComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMailComposeViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMailComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMailComposeControllerDeferredAction/title",
          "value": "MFMailComposeControllerDeferredAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMailComposeControllerDeferredAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMailComposeControllerDeferredAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMailComposeControllerDeferredAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMailComposeControllerDeferredAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messageui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messageui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
