{
  "abstract": [
    {
      "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 1"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messages/documentation/Messages"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "Messages",
    "modules": [
      {
        "name": "Messages"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Messages"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use the Messages framework to create sticker packs and iMessage apps. You can create sticker packs and iMessage apps as either standalone apps or as app extensions within a containing iOS app. For more information on creating and working with app extensions, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/app-extensions/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "iMessage apps and stickers help people interact and communicate in the context of a Messages conversation. For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/imessage-apps-and-stickers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "iMessage-apps",
          "level": 3,
          "text": "iMessage apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "iMessage apps leverage the full framework to interact with the Messages app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "To avoid a crash, an iMessage app linked on or after iOS 10 must include usage description keys for the device features it needs to access in its ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": " file. Specifically, it must include ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSCameraUsageDescription",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to access the device’s camera, and it must include ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSMicrophoneUsageDescription",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to access the device’s microphones.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Use iMessage apps to:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Present a custom user interface inside the Messages app; see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a custom or dynamic sticker browser; see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSStickerBrowserViewController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Insert text, stickers, or media files into the Messages app’s input field; see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create interactive messages that carry app-specific data; see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Update interactive messages (for example, to create games or collaborative apps); see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on submitting iMessage Apps to the App Store, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/app-store/imessage-app-submissions/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 17, Messages allows you to interactively resize iMessage apps with a vertical pan gesture. Messages handles any conflicts between resize gestures and your custom gestures. If your app uses manual touch handling such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizer/touchesBegan(_:with:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizer/touchesMoved(_:with:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizer/touchesEnded(_:with:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you can do either of the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Change your manual touch handling code to use a gesture recognizer instead.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use your ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to override ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizerDelegate/gestureRecognizerShouldBegin(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and return ",
                      "type": "text"
                    },
                    {
                      "code": "NO",
                      "type": "codeVoice"
                    },
                    {
                      "text": " when your iMessage app doesn’t own the gesture.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Become-the-default-messaging-app",
          "level": 3,
          "text": "Become the default messaging app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS and iPadOS 18.2 and later, a person may select an app other than the Messages app to send instant messages. If you wish to make your app the default messages app, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/Preparing-your-app-to-be-the-default-messaging-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSCameraUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the device’s camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSCameraUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCameraUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSCameraUsageDescription"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSMicrophoneUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the device’s microphone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSMicrophoneUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMicrophoneUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSMicrophoneUsageDescription"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizer/touchesBegan(_:with:)": {
      "abstract": [
        {
          "text": "Sent to the gesture recognizer when one or more fingers touch down in the associated view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchesBegan"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "touches"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITouch",
          "text": "UITouch"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "event"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIEvent",
          "text": "UIEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizer/touchesBegan(_:with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "touchesBegan(_:with:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIGestureRecognizer/touchesBegan(_:with:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizer/touchesEnded(_:with:)": {
      "abstract": [
        {
          "text": "Sent to the gesture recognizer when one or more fingers lift from the associated view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchesEnded"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "touches"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITouch",
          "text": "UITouch"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "event"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIEvent",
          "text": "UIEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizer/touchesEnded(_:with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "touchesEnded(_:with:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIGestureRecognizer/touchesEnded(_:with:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizer/touchesMoved(_:with:)": {
      "abstract": [
        {
          "text": "Sent to the gesture recognizer when one or more fingers move in the associated view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchesMoved"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "touches"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITouch",
          "text": "UITouch"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "event"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIEvent",
          "text": "UIEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizer/touchesMoved(_:with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "touchesMoved(_:with:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIGestureRecognizer/touchesMoved(_:with:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizerDelegate/gestureRecognizerShouldBegin(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate if a gesture recognizer should begin interpreting touches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gestureRecognizerShouldBegin"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "gestureRecognizer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGestureRecognizer",
          "text": "UIGestureRecognizer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIGestureRecognizerDelegate/gestureRecognizerShouldBegin(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "gestureRecognizerShouldBegin(_:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIGestureRecognizerDelegate/gestureRecognizerShouldBegin(_:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/UIKit/UIView"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messages/documentation/Messages": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/messages"
    },
    "doc://com.apple.messages/documentation/Messages/MESSAGES_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MESSAGES_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MESSAGES_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "MESSAGES_EXTERN",
      "type": "topic",
      "url": "/documentation/messages/messages_extern"
    },
    "doc://com.apple.messages/documentation/Messages/MSConversation": {
      "abstract": [
        {
          "text": "An object that represents a conversation in the Messages app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSConversation"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSConversation"
        }
      ],
      "role": "symbol",
      "title": "MSConversation",
      "type": "topic",
      "url": "/documentation/messages/msconversation"
    },
    "doc://com.apple.messages/documentation/Messages/MSCriticalMessage": {
      "abstract": [
        {
          "text": "MSCriticalMessage",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "A simple struct to encapsulate the message string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSCriticalMessage"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSCriticalMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSCriticalMessage"
        }
      ],
      "role": "symbol",
      "title": "MSCriticalMessage",
      "type": "topic",
      "url": "/documentation/messages/mscriticalmessage"
    },
    "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingAuthorizationStatus": {
      "abstract": [
        {
          "text": "Values that describe the authorization status for the Critical Messaging API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSCriticalMessagingAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSCriticalMessagingAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "MSCriticalMessagingAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/messages/mscriticalmessagingauthorizationstatus"
    },
    "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingError": {
      "abstract": [
        {
          "text": "Values that describe errors the Critical Messaging API returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSCriticalMessagingError"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSCriticalMessagingError"
        }
      ],
      "role": "symbol",
      "title": "MSCriticalMessagingError",
      "type": "topic",
      "url": "/documentation/messages/mscriticalmessagingerror"
    },
    "doc://com.apple.messages/documentation/Messages/MSCriticalSMSMessenger": {
      "abstract": [
        {
          "text": "The user interface for the Critical Messaging API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSCriticalSMSMessenger"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSCriticalSMSMessenger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSCriticalSMSMessenger"
        }
      ],
      "role": "symbol",
      "title": "MSCriticalSMSMessenger",
      "type": "topic",
      "url": "/documentation/messages/mscriticalsmsmessenger"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessage": {
      "abstract": [
        {
          "text": "A custom message object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessage"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessage"
        }
      ],
      "role": "symbol",
      "title": "MSMessage",
      "type": "topic",
      "url": "/documentation/messages/msmessage"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode": {
      "abstract": [
        {
          "text": "The error codes that the Messages framework generates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessageErrorCode"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCode"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageLayout": {
      "abstract": [
        {
          "text": "An abstract base class that defines the appearance of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects in the conversation transcript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessageLayout"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageLayout"
        }
      ],
      "role": "symbol",
      "title": "MSMessageLayout",
      "type": "topic",
      "url": "/documentation/messages/msmessagelayout"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageLiveLayout": {
      "abstract": [
        {
          "text": "A layout that provides a custom, interactive view inside the transcript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessageLiveLayout"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageLiveLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageLiveLayout"
        }
      ],
      "role": "symbol",
      "title": "MSMessageLiveLayout",
      "type": "topic",
      "url": "/documentation/messages/msmessagelivelayout"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout": {
      "abstract": [
        {
          "text": "A template-based layout for custom messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessageTemplateLayout"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageTemplateLayout"
        }
      ],
      "role": "symbol",
      "title": "MSMessageTemplateLayout",
      "type": "topic",
      "url": "/documentation/messages/msmessagetemplatelayout"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle": {
      "abstract": [
        {
          "text": "Presentation styles that describe your iMessage app’s appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationStyle"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppPresentationStyle",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapppresentationstyle"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation": {
      "abstract": [
        {
          "text": "A protocol that provides support for displaying live messages in the transcript of the Messages app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesAppTranscriptPresentation"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppTranscriptPresentation"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppTranscriptPresentation",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapptranscriptpresentation"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController": {
      "abstract": [
        {
          "text": "The principal view controller for iMessage apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesAppViewController"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppViewController"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppViewController",
      "type": "topic",
      "url": "/documentation/messages/msmessagesappviewcontroller"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for iMessage apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesErrorDomain",
      "type": "topic",
      "url": "/documentation/messages/msmessageserrordomain"
    },
    "doc://com.apple.messages/documentation/Messages/MSRecipient": {
      "abstract": [
        {
          "text": "A structure that describes the recipient of a critical message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSRecipient"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSRecipient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSRecipient"
        }
      ],
      "role": "symbol",
      "title": "MSRecipient",
      "type": "topic",
      "url": "/documentation/messages/msrecipient"
    },
    "doc://com.apple.messages/documentation/Messages/MSSession": {
      "abstract": [
        {
          "text": "A session object used to create and update messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSSession"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSSession"
        }
      ],
      "role": "symbol",
      "title": "MSSession",
      "type": "topic",
      "url": "/documentation/messages/mssession"
    },
    "doc://com.apple.messages/documentation/Messages/MSSticker": {
      "abstract": [
        {
          "text": "A sticker that can be sent as a new message or attached to an existing balloon in the Messages app’s  transcript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSSticker"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSSticker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSSticker"
        }
      ],
      "role": "symbol",
      "title": "MSSticker",
      "type": "topic",
      "url": "/documentation/messages/mssticker"
    },
    "doc://com.apple.messages/documentation/Messages/MSStickerBrowserView": {
      "abstract": [
        {
          "text": "A browser view that displays a dynamically generated list of stickers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSStickerBrowserView"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSStickerBrowserView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSStickerBrowserView"
        }
      ],
      "role": "symbol",
      "title": "MSStickerBrowserView",
      "type": "topic",
      "url": "/documentation/messages/msstickerbrowserview"
    },
    "doc://com.apple.messages/documentation/Messages/MSStickerBrowserViewController": {
      "abstract": [
        {
          "text": "A view controller that provides dynamic content to the standard sticker browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSStickerBrowserViewController"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSStickerBrowserViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSStickerBrowserViewController"
        }
      ],
      "role": "symbol",
      "title": "MSStickerBrowserViewController",
      "type": "topic",
      "url": "/documentation/messages/msstickerbrowserviewcontroller"
    },
    "doc://com.apple.messages/documentation/Messages/MSStickerSize": {
      "abstract": [
        {
          "text": "The size of the stickers in the browser view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSStickerSize"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSStickerSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSStickerSize"
        }
      ],
      "role": "symbol",
      "title": "MSStickerSize",
      "type": "topic",
      "url": "/documentation/messages/msstickersize"
    },
    "doc://com.apple.messages/documentation/Messages/MSStickerView": {
      "abstract": [
        {
          "text": "A view for displaying a sticker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSStickerView"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSStickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSStickerView"
        }
      ],
      "role": "symbol",
      "title": "MSStickerView",
      "type": "topic",
      "url": "/documentation/messages/msstickerview"
    },
    "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for stickers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSStickersErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSStickersErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MSStickersErrorDomain",
      "type": "topic",
      "url": "/documentation/messages/msstickerserrordomain"
    },
    "doc://com.apple.messages/documentation/Messages/Preparing-your-app-to-be-the-default-messaging-app": {
      "abstract": [
        {
          "text": "Configure your messaging app so people can set it as the default on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/Preparing-your-app-to-be-the-default-messaging-app",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to be the default messaging app",
      "type": "topic",
      "url": "/documentation/messages/preparing-your-app-to-be-the-default-messaging-app"
    },
    "doc://com.apple.messages/documentation/Messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime": {
      "abstract": [
        {
          "text": "Enable your Sticker pack or iMessage app in the media context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime",
      "kind": "article",
      "role": "article",
      "title": "Adding Sticker packs and iMessage apps to the system Stickers app, Messages camera, and FaceTime",
      "type": "topic",
      "url": "/documentation/messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime"
    },
    "doc://com.apple.messages/documentation/Messages/adding-your-sticker-packs-to-messages": {
      "abstract": [
        {
          "text": "Drag and drop your sticker pack into the Stickers asset catalog to let people access your stickers from Messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/adding-your-sticker-packs-to-messages",
      "kind": "article",
      "role": "article",
      "title": "Adding your sticker packs to Messages",
      "type": "topic",
      "url": "/documentation/messages/adding-your-sticker-packs-to-messages"
    },
    "doc://com.apple.messages/documentation/Messages/creating-a-sticker-app-with-a-custom-layout": {
      "abstract": [
        {
          "text": "Expand on the Messages sticker app template to create an app with a customized user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/creating-a-sticker-app-with-a-custom-layout",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a Sticker App with a Custom Layout",
      "type": "topic",
      "url": "/documentation/messages/creating-a-sticker-app-with-a-custom-layout"
    },
    "doc://com.apple.messages/documentation/Messages/critical-messaging-api": {
      "abstract": [
        {
          "text": "Send critical messages from inside your app using the Critical Messaging API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/critical-messaging-api",
      "kind": "article",
      "role": "article",
      "title": "Sending SMS messages from an app",
      "type": "topic",
      "url": "/documentation/messages/critical-messaging-api"
    },
    "doc://com.apple.messages/documentation/Messages/icecreambuilder-building-an-imessage-extension": {
      "abstract": [
        {
          "text": "Allow users to collaborate on the design of ice cream sundae stickers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/icecreambuilder-building-an-imessage-extension",
      "kind": "article",
      "role": "sampleCode",
      "title": "IceCreamBuilder: Building an iMessage Extension",
      "type": "topic",
      "url": "/documentation/messages/icecreambuilder-building-an-imessage-extension"
    },
    "https://developer.apple.com/app-extensions/": {
      "identifier": "https://developer.apple.com/app-extensions/",
      "title": "App extensions",
      "titleInlineContent": [
        {
          "text": "App extensions",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/app-extensions/"
    },
    "https://developer.apple.com/app-store/imessage-app-submissions/": {
      "identifier": "https://developer.apple.com/app-store/imessage-app-submissions/",
      "title": "Preparing Your iMessage App for Submission",
      "titleInlineContent": [
        {
          "text": "Preparing Your iMessage App for Submission",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/app-store/imessage-app-submissions/"
    },
    "https://developer.apple.com/design/human-interface-guidelines/imessage-apps-and-stickers": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/imessage-apps-and-stickers",
      "title": "Human Interface Guidelines > iMessage apps and stickers",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > iMessage apps and stickers",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/imessage-apps-and-stickers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Default-messaging-app",
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/Preparing-your-app-to-be-the-default-messaging-app"
      ],
      "title": "Default messaging app"
    },
    {
      "anchor": "Custom-sticker-packs",
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime",
        "doc://com.apple.messages/documentation/Messages/adding-your-sticker-packs-to-messages",
        "doc://com.apple.messages/documentation/Messages/MSStickerBrowserViewController",
        "doc://com.apple.messages/documentation/Messages/MSStickerBrowserView",
        "doc://com.apple.messages/documentation/Messages/MSStickerView",
        "doc://com.apple.messages/documentation/Messages/MSStickerSize"
      ],
      "title": "Custom sticker packs"
    },
    {
      "anchor": "Custom-iMessage-app-interface",
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/icecreambuilder-building-an-imessage-extension",
        "doc://com.apple.messages/documentation/Messages/creating-a-sticker-app-with-a-custom-layout",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle"
      ],
      "title": "Custom iMessage app interface"
    },
    {
      "anchor": "Message-content",
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSConversation",
        "doc://com.apple.messages/documentation/Messages/MSSticker"
      ],
      "title": "Message content"
    },
    {
      "anchor": "Interactive-messages",
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSMessage",
        "doc://com.apple.messages/documentation/Messages/MSSession",
        "doc://com.apple.messages/documentation/Messages/MSMessageLayout",
        "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout",
        "doc://com.apple.messages/documentation/Messages/MSMessageLiveLayout"
      ],
      "title": "Interactive messages"
    },
    {
      "anchor": "Critical-messages",
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/critical-messaging-api",
        "doc://com.apple.messages/documentation/Messages/MSCriticalSMSMessenger",
        "doc://com.apple.messages/documentation/Messages/MSRecipient",
        "doc://com.apple.messages/documentation/Messages/MSCriticalMessage",
        "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingAuthorizationStatus"
      ],
      "title": "Critical messages"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain",
        "doc://com.apple.messages/documentation/Messages/MSMessagesErrorDomain",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode",
        "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingError"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Default-messaging-app",
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/Preparing-your-app-to-be-the-default-messaging-app"
              ],
              "title": "Default messaging app"
            },
            {
              "anchor": "Custom-sticker-packs",
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime",
                "doc://com.apple.messages/documentation/Messages/adding-your-sticker-packs-to-messages",
                "doc://com.apple.messages/documentation/Messages/MSStickerBrowserViewController",
                "doc://com.apple.messages/documentation/Messages/MSStickerBrowserView",
                "doc://com.apple.messages/documentation/Messages/MSStickerView",
                "doc://com.apple.messages/documentation/Messages/MSStickerSize"
              ],
              "title": "Custom sticker packs"
            },
            {
              "anchor": "Custom-iMessage-app-interface",
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/icecreambuilder-building-an-imessage-extension",
                "doc://com.apple.messages/documentation/Messages/creating-a-sticker-app-with-a-custom-layout",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle"
              ],
              "title": "Custom iMessage app interface"
            },
            {
              "anchor": "Message-content",
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSConversation",
                "doc://com.apple.messages/documentation/Messages/MSSticker"
              ],
              "title": "Message content"
            },
            {
              "anchor": "Interactive-messages",
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSMessage",
                "doc://com.apple.messages/documentation/Messages/MSSession",
                "doc://com.apple.messages/documentation/Messages/MSMessageLayout",
                "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout",
                "doc://com.apple.messages/documentation/Messages/MSMessageLiveLayout"
              ],
              "title": "Interactive messages"
            },
            {
              "anchor": "Critical-messages",
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/critical-messaging-api"
              ],
              "title": "Critical messages"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain",
                "doc://com.apple.messages/documentation/Messages/MSMessagesErrorDomain",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MESSAGES_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesErrorDomain/title",
          "value": "MSMessagesErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerBrowserView/title",
          "value": "MSStickerBrowserView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerBrowserView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickerBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerBrowserView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickerBrowserView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSession/title",
          "value": "MSSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle/title",
          "value": "MSMessagesAppPresentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGestureRecognizerDelegate~1gestureRecognizerShouldBegin(_:)/title",
          "value": "gestureRecognizerShouldBegin:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGestureRecognizerDelegate~1gestureRecognizerShouldBegin(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "gestureRecognizerShouldBegin:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIGestureRecognizer",
              "text": "UIGestureRecognizer"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "gestureRecognizer"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIResponder",
              "text": "UIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLayout/title",
          "value": "MSMessageLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLiveLayout/title",
          "value": "MSMessageLiveLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLiveLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageLiveLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLiveLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageLiveLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode/title",
          "value": "MSMessageErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerBrowserViewController/title",
          "value": "MSStickerBrowserViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerBrowserViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickerBrowserViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerBrowserViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickerBrowserViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/title",
          "value": "MSMessagesAppViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSticker/title",
          "value": "MSSticker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSticker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSticker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSticker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSticker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerView/title",
          "value": "MSStickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage/title",
          "value": "MSMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickersErrorDomain/title",
          "value": "MSStickersErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickersErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickersErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGestureRecognizer~1touchesEnded(_:with:)/title",
          "value": "touchesEnded:withEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGestureRecognizer~1touchesEnded(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "touchesEnded:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSSet",
              "text": "NSSet<UITouch *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "touches"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "withEvent:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIEvent",
              "text": "UIEvent"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "event"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerSize/title",
          "value": "MSStickerSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickerSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickerSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickerSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGestureRecognizer~1touchesBegan(_:with:)/title",
          "value": "touchesBegan:withEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGestureRecognizer~1touchesBegan(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "touchesBegan:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSSet",
              "text": "NSSet<UITouch *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "touches"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "withEvent:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIEvent",
              "text": "UIEvent"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "event"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout/title",
          "value": "MSMessageTemplateLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageTemplateLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageTemplateLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation/title",
          "value": "MSMessagesAppTranscriptPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppTranscriptPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppTranscriptPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation/title",
          "value": "MSConversation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSConversation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSConversation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGestureRecognizer~1touchesMoved(_:with:)/title",
          "value": "touchesMoved:withEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIGestureRecognizer~1touchesMoved(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "touchesMoved:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSSet",
              "text": "NSSet<UITouch *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "touches"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "withEvent:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIEvent",
              "text": "UIEvent"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "event"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messages"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messages"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
