{
  "abstract": [
    {
      "text": "Build Metal apps quicker and easier using a common set of utility classes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalkit/documentation/MetalKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "MetalKit",
    "modules": [
      {
        "name": "MetalKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.11",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "MetalKit"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalkit/documentation/MetalKit": {
      "abstract": [
        {
          "text": "Build Metal apps quicker and easier using a common set of utility classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalKit",
      "type": "topic",
      "url": "/documentation/metalkit"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh": {
      "abstract": [
        {
          "text": "A container for the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMesh"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMesh"
        }
      ],
      "role": "symbol",
      "title": "MTKMesh",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmesh"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer": {
      "abstract": [
        {
          "text": "A buffer that backs the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMeshBuffer"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMeshBuffer"
        }
      ],
      "role": "symbol",
      "title": "MTKMeshBuffer",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbuffer"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator": {
      "abstract": [
        {
          "text": "An interface for allocating a MetalKit buffer that backs the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMeshBufferAllocator"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMeshBufferAllocator"
        }
      ],
      "role": "symbol",
      "title": "MTKMeshBufferAllocator",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbufferallocator"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh": {
      "abstract": [
        {
          "text": "A container for the index data of a Model I/O submesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKSubmesh"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKSubmesh"
        }
      ],
      "role": "symbol",
      "title": "MTKSubmesh",
      "type": "topic",
      "url": "/documentation/metalkit/mtksubmesh"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader": {
      "abstract": [
        {
          "text": "An object that creates textures from existing data in common image formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKTextureLoader"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKTextureLoader"
        }
      ],
      "role": "symbol",
      "title": "MTKTextureLoader",
      "type": "topic",
      "url": "/documentation/metalkit/mtktextureloader"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKView": {
      "abstract": [
        {
          "text": "A specialized view that creates, configures, and displays Metal objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKView"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKView"
        }
      ],
      "role": "symbol",
      "title": "MTKView",
      "type": "topic",
      "url": "/documentation/metalkit/mtkview"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate": {
      "abstract": [
        {
          "text": "Methods for responding to a MetalKit view’s drawing and resizing events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "MTKViewDelegate",
      "type": "topic",
      "url": "/documentation/metalkit/mtkviewdelegate"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTK_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTK_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTK_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTK_EXPORT",
      "type": "topic",
      "url": "/documentation/metalkit/mtk_export"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTK_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTK_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTK_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTK_EXTERN",
      "type": "topic",
      "url": "/documentation/metalkit/mtk_extern"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTK_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTK_INLINE"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTK_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTK_INLINE",
      "type": "topic",
      "url": "/documentation/metalkit/mtk_inline"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/conversion-functions": {
      "abstract": [
        {
          "text": "Convert between Metal and Model I/O vertex representations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/conversion-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Conversion Functions",
      "type": "topic",
      "url": "/documentation/metalkit/conversion-functions"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/metalkit-functions": {
      "abstract": [
        {
          "text": "The MetalKit framework defines helper functions that are used to efficiently interface with the Metal and Model I/O frameworks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/metalkit-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MetalKit Functions",
      "type": "topic",
      "url": "/documentation/metalkit/metalkit-functions"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/model-errors": {
      "abstract": [
        {
          "text": "Learn about errors thrown by model handling methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/model-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model Errors",
      "type": "topic",
      "url": "/documentation/metalkit/model-errors"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Display your Metal content with a view that manages much of the setup for you.",
          "type": "text"
        }
      ],
      "anchor": "View-Management",
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKView",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate"
      ],
      "title": "View Management"
    },
    {
      "abstract": [
        {
          "text": "Load textures into your Metal app from a variety of sources.",
          "type": "text"
        }
      ],
      "anchor": "Texture-Loading",
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader"
      ],
      "title": "Texture Loading"
    },
    {
      "abstract": [
        {
          "text": "Handle Model I/O assets using a Metal-specific interface.",
          "type": "text"
        }
      ],
      "anchor": "Model-Handling",
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh",
        "doc://com.apple.metalkit/documentation/MetalKit/conversion-functions",
        "doc://com.apple.metalkit/documentation/MetalKit/model-errors"
      ],
      "title": "Model Handling"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/metalkit-functions"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Display your Metal content with a view that manages much of the setup for you.",
                  "type": "text"
                }
              ],
              "anchor": "View-Management",
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKView",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate"
              ],
              "title": "View Management"
            },
            {
              "abstract": [
                {
                  "text": "Load textures into your Metal app from a variety of sources.",
                  "type": "text"
                }
              ],
              "anchor": "Texture-Loading",
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader"
              ],
              "title": "Texture Loading"
            },
            {
              "abstract": [
                {
                  "text": "Handle Model I/O assets using a Metal-specific interface.",
                  "type": "text"
                }
              ],
              "anchor": "Model-Handling",
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh",
                "doc://com.apple.metalkit/documentation/MetalKit/conversion-functions",
                "doc://com.apple.metalkit/documentation/MetalKit/model-errors"
              ],
              "title": "Model Handling"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/metalkit-functions"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTK_EXPORT",
                "doc://com.apple.metalkit/documentation/MetalKit/MTK_EXTERN",
                "doc://com.apple.metalkit/documentation/MetalKit/MTK_INLINE"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/title",
          "value": "MTKMeshBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate/title",
          "value": "MTKViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/title",
          "value": "MTKMeshBufferAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKSubmesh/title",
          "value": "MTKSubmesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKSubmesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKSubmesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMesh/title",
          "value": "MTKMesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader/title",
          "value": "MTKTextureLoader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKTextureLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKTextureLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView/title",
          "value": "MTKView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
