{
  "abstract": [
    {
      "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "ML Compute is deprecated. Instead, use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/Accelerate/BNNS",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for CPU tasks, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/metalperformanceshaders",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for GPU work, and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/CoreML",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for tensor APIs.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "MLCompute",
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "tvOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "ML Compute"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "ML Compute uses high performance ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Accelerate/BNNS",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " primitives from the Accelerate framework for the CPU, and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/metalperformanceshaders",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the GPU.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Accelerate/BNNS": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to BNNS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNS"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/BNNS",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNS",
      "type": "topic",
      "url": "/documentation/Accelerate/BNNS"
    },
    "doc://com.apple.documentation/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/CoreML"
    },
    "doc://com.apple.documentation/documentation/metalperformanceshaders": {
      "abstract": [
        {
          "text": "Optimize graphics and compute performance with kernels that are fine-tuned for the unique characteristics of each Metal GPU family.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/metalperformanceshaders",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal Performance Shaders",
      "type": "topic",
      "url": "/documentation/metalperformanceshaders"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_AVAILABLE_STARTING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCOMPUTE_AVAILABLE_STARTING"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_AVAILABLE_STARTING",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCOMPUTE_AVAILABLE_STARTING",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcompute_available_starting"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_AVAILABLE_STARTING_BUT_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCOMPUTE_AVAILABLE_STARTING_BUT_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_AVAILABLE_STARTING_BUT_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCOMPUTE_AVAILABLE_STARTING_BUT_DEPRECATED",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcompute_available_starting_but_deprecated"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_AVAILABLE_STARTING_BUT_DEPRECATED_MACOS14": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCOMPUTE_AVAILABLE_STARTING_BUT_DEPRECATED_MACOS14"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_AVAILABLE_STARTING_BUT_DEPRECATED_MACOS14",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCOMPUTE_AVAILABLE_STARTING_BUT_DEPRECATED_MACOS14",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcompute_available_starting_but_deprecated_macos14"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_CLASS_AVAILABLE_STARTING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCOMPUTE_CLASS_AVAILABLE_STARTING"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_CLASS_AVAILABLE_STARTING",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCOMPUTE_CLASS_AVAILABLE_STARTING",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcompute_class_available_starting"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_ENUM_AVAILABLE_STARTING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCOMPUTE_ENUM_AVAILABLE_STARTING"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_ENUM_AVAILABLE_STARTING",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCOMPUTE_ENUM_AVAILABLE_STARTING",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcompute_enum_available_starting"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_ENUM_AVAILABLE_STARTING_BUT_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCOMPUTE_ENUM_AVAILABLE_STARTING_BUT_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_ENUM_AVAILABLE_STARTING_BUT_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCOMPUTE_ENUM_AVAILABLE_STARTING_BUT_DEPRECATED",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcompute_enum_available_starting_but_deprecated"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_PROTOCOL_AVAILABLE_STARTING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCOMPUTE_PROTOCOL_AVAILABLE_STARTING"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_PROTOCOL_AVAILABLE_STARTING",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCOMPUTE_PROTOCOL_AVAILABLE_STARTING",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcompute_protocol_available_starting"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCOMPUTE_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCOMPUTE_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcompute_unavailable"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-14ba7": {
      "abstract": [
        {
          "text": "A padding policy that you specify for a convolution or pooling layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCPaddingPolicy"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-14ba7",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCPaddingPolicy",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddingpolicy-14ba7"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform": {
      "abstract": [
        {
          "text": "A utility class for setting global properties in the framework.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPlatform"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPlatform"
        }
      ],
      "role": "symbol",
      "title": "MLCPlatform",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcplatform"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor": {
      "abstract": [
        {
          "text": "The data object you use throughout the framework.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTensor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTensor"
        }
      ],
      "role": "symbol",
      "title": "MLCTensor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLComputeTypes_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLComputeTypes_h"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLComputeTypes_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLComputeTypes_h",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcomputetypes_h"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/layers": {
      "abstract": [
        {
          "text": "Create and inspect layers that encapsulate operations and configuration details to receive, process, and output tensors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/layers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layers",
      "type": "topic",
      "url": "/documentation/mlcompute/layers"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation": {
      "abstract": [
        {
          "text": "Create, train, and validate a graph to produce acceptable prediction results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Training and Validation",
      "type": "topic",
      "url": "/documentation/mlcompute/training-and-validation"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Components",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform",
        "doc://com.apple.mlcompute/documentation/MLCompute/layers",
        "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation"
      ],
      "title": "Components"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Components",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform",
                "doc://com.apple.mlcompute/documentation/MLCompute/layers",
                "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation"
              ],
              "title": "Components"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_AVAILABLE_STARTING",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_AVAILABLE_STARTING_BUT_DEPRECATED",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_AVAILABLE_STARTING_BUT_DEPRECATED_MACOS14",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_CLASS_AVAILABLE_STARTING",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_ENUM_AVAILABLE_STARTING",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_ENUM_AVAILABLE_STARTING_BUT_DEPRECATED",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_PROTOCOL_AVAILABLE_STARTING",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOMPUTE_UNAVAILABLE",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLComputeTypes_h"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-14ba7"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "ML Compute is deprecated. Instead, use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Accelerate/BNNS",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for CPU tasks, ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/metalperformanceshaders",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for GPU work, and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreML",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for tensor APIs.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPlatform/title",
          "value": "MLCPlatform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPlatform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPlatform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/title",
          "value": "MLCTensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
