{
  "abstract": [
    {
      "text": "Analyze natural language text and deduce its language-specific metadata.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "NaturalLanguage",
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.14",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "5.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Natural Language"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Natural Language framework provides a variety of natural language processing (NLP) functionality with support for many different languages and scripts. Use this framework to segment natural language text into paragraphs, sentences, or words, and tag information about those segments, such as part of speech, lexical class, lemma, script, and language.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3597579",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use this framework to perform tasks like:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Language identification",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ", automatically detecting the language of a piece of text.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Tokenization",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ", breaking up a piece of text into linguistic units or tokens.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Parts-of-speech tagging",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ", marking up individual words with their part of speech.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Lemmatization",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ", deducing a word’s stem based on its morphological analysis.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Named entity recognition",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ", identifying tokens as names of people, places, or organizations.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can also use this framework with Create ML to train and deploy custom natural language models. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/creating-a-text-classifier-model",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/creating-a-word-tagger-model",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/CreateML/creating-a-text-classifier-model": {
      "abstract": [
        {
          "text": "Train a machine learning model to classify natural language text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/creating-a-text-classifier-model",
      "kind": "article",
      "role": "article",
      "title": "Creating a text classifier model",
      "type": "topic",
      "url": "/documentation/CreateML/creating-a-text-classifier-model"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbedding": {
      "abstract": [
        {
          "text": "A model that computes sequences of embedding vectors for natural language utterances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLContextualEmbedding"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbedding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLContextualEmbedding"
        }
      ],
      "role": "symbol",
      "title": "NLContextualEmbedding",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlcontextualembedding"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbeddingKey": {
      "abstract": [
        {
          "text": "Contextual embedding keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLContextualEmbeddingKey"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbeddingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLContextualEmbeddingKey"
        }
      ],
      "role": "symbol",
      "title": "NLContextualEmbeddingKey",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlcontextualembeddingkey"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding": {
      "abstract": [
        {
          "text": "A map of strings to vectors, which locates neighboring, similar strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLEmbedding"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLEmbedding"
        }
      ],
      "role": "symbol",
      "title": "NLEmbedding",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguage": {
      "abstract": [
        {
          "text": "The languages that the Natural Language framework supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLLanguage"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLLanguage"
        }
      ],
      "role": "symbol",
      "title": "NLLanguage",
      "type": "topic",
      "url": "/documentation/naturallanguage/nllanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer": {
      "abstract": [
        {
          "text": "The language of a body of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLLanguageRecognizer"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLLanguageRecognizer"
        }
      ],
      "role": "symbol",
      "title": "NLLanguageRecognizer",
      "type": "topic",
      "url": "/documentation/naturallanguage/nllanguagerecognizer"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel": {
      "abstract": [
        {
          "text": "A custom model trained to classify or tag natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLModel"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLModel"
        }
      ],
      "role": "symbol",
      "title": "NLModel",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodel"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript": {
      "abstract": [
        {
          "text": "The writing scripts that the Natural Language framework supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScript"
        }
      ],
      "role": "symbol",
      "title": "NLScript",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger": {
      "abstract": [
        {
          "text": "A tagger that analyzes natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTagger"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagger"
        }
      ],
      "role": "symbol",
      "title": "NLTagger",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagger"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer": {
      "abstract": [
        {
          "text": "A tokenizer that segments natural language text into semantic units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTokenizer"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTokenizer"
        }
      ],
      "role": "symbol",
      "title": "NLTokenizer",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltokenizer"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/creating-a-word-tagger-model": {
      "abstract": [
        {
          "text": "Train a machine learning model to tag individual words in natural language text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/creating-a-word-tagger-model",
      "kind": "article",
      "role": "article",
      "title": "Creating a word tagger model",
      "type": "topic",
      "url": "/documentation/naturallanguage/creating-a-word-tagger-model"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/finding-similarities-between-pieces-of-text": {
      "abstract": [
        {
          "text": "Calculate the semantic distance between words or sentences.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/finding-similarities-between-pieces-of-text",
      "kind": "article",
      "role": "article",
      "title": "Finding similarities between pieces of text",
      "type": "topic",
      "url": "/documentation/naturallanguage/finding-similarities-between-pieces-of-text"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-parts-of-speech": {
      "abstract": [
        {
          "text": "Classify nouns, verbs, adjectives, and other parts of speech in a string.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-parts-of-speech",
      "kind": "article",
      "role": "article",
      "title": "Identifying parts of speech",
      "type": "topic",
      "url": "/documentation/naturallanguage/identifying-parts-of-speech"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-people-places-and-organizations": {
      "abstract": [
        {
          "text": "Use a linguistic tagger to perform named entity recognition on a string.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-people-places-and-organizations",
      "kind": "article",
      "role": "article",
      "title": "Identifying people, places, and organizations",
      "type": "topic",
      "url": "/documentation/naturallanguage/identifying-people-places-and-organizations"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-the-language-in-text": {
      "abstract": [
        {
          "text": "Detect the language in a piece of text by using a language recognizer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-the-language-in-text",
      "kind": "article",
      "role": "article",
      "title": "Identifying the language in text",
      "type": "topic",
      "url": "/documentation/naturallanguage/identifying-the-language-in-text"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/tokenizing-natural-language-text": {
      "abstract": [
        {
          "text": "Enumerate the words in a string.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/tokenizing-natural-language-text",
      "kind": "article",
      "role": "article",
      "title": "Tokenizing natural language text",
      "type": "topic",
      "url": "/documentation/naturallanguage/tokenizing-natural-language-text"
    },
    "media-3597579": {
      "alt": "Diagram showing the types of analysis that the Natural Language framework can perform.",
      "identifier": "media-3597579",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/991fa70b8c44e03076c487b8b7e7178b/media-3597579@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/adcdd6867f0a6b6a26e696ba2f4789d4/media-3597579~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Tokenization",
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/tokenizing-natural-language-text",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer"
      ],
      "title": "Tokenization"
    },
    {
      "anchor": "Language-identification",
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-the-language-in-text",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguage"
      ],
      "title": "Language identification"
    },
    {
      "anchor": "Linguistic-tags",
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-parts-of-speech",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-people-places-and-organizations",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger"
      ],
      "title": "Linguistic tags"
    },
    {
      "anchor": "Text-embedding",
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/finding-similarities-between-pieces-of-text",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding"
      ],
      "title": "Text embedding"
    },
    {
      "anchor": "Contextual-embedding",
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbedding",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbeddingKey",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript"
      ],
      "title": "Contextual embedding"
    },
    {
      "anchor": "Natural-language-models",
      "identifiers": [
        "doc://com.apple.documentation/documentation/CreateML/creating-a-text-classifier-model",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/creating-a-word-tagger-model",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel"
      ],
      "title": "Natural language models"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Tokenization",
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/tokenizing-natural-language-text",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer"
              ],
              "title": "Tokenization"
            },
            {
              "anchor": "Language-identification",
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-the-language-in-text",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguage"
              ],
              "title": "Language identification"
            },
            {
              "anchor": "Linguistic-tags",
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-parts-of-speech",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-people-places-and-organizations",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger"
              ],
              "title": "Linguistic tags"
            },
            {
              "anchor": "Text-embedding",
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/finding-similarities-between-pieces-of-text",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding"
              ],
              "title": "Text embedding"
            },
            {
              "anchor": "Contextual-embedding",
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbedding",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbeddingKey",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript"
              ],
              "title": "Contextual embedding"
            },
            {
              "anchor": "Natural-language-models",
              "identifiers": [
                "doc://com.apple.documentation/documentation/CreateML/creating-a-text-classifier-model",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/creating-a-word-tagger-model",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel"
              ],
              "title": "Natural language models"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbeddingKey/title",
          "value": "NLContextualEmbeddingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbeddingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLContextualEmbeddingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbeddingKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLContextualEmbeddingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLEmbedding/title",
          "value": "NLEmbedding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLEmbedding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLEmbedding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLEmbedding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLEmbedding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbedding/title",
          "value": "NLContextualEmbedding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbedding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLContextualEmbedding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbedding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLContextualEmbedding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguage/title",
          "value": "NLLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/title",
          "value": "NLTagger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript/title",
          "value": "NLScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenizer/title",
          "value": "NLTokenizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTokenizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTokenizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer/title",
          "value": "NLLanguageRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLLanguageRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLLanguageRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel/title",
          "value": "NLModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/naturallanguage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
