{
  "abstract": [
    {
      "text": "Create and manage widgets for the Today view.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.notificationcenter/documentation/NotificationCenter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "NotificationCenter",
    "modules": [
      {
        "name": "Notification Center"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.10",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Notification Center"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Notification Center framework helps you create and manage app extensions that implement Today widgets. The framework provides an API you can use to specify whether a Today widget has content to display, and to customize aspects of its appearance and behavior. In macOS, the Notification Center framework also provides ways to customize the editing and searching experience in a widget.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3039577",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/WidgetKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter": {
      "abstract": [
        {
          "text": "Create and manage widgets for the Today view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter",
      "kind": "symbol",
      "role": "collection",
      "title": "Notification Center",
      "type": "topic",
      "url": "/documentation/notificationcenter"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetController": {
      "abstract": [
        {
          "text": "An object used to specify whether a Today widget has content to display.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NCWidgetController"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NCWidgetController"
        }
      ],
      "role": "symbol",
      "title": "NCWidgetController",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetcontroller"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewController": {
      "abstract": [
        {
          "text": "An object that provides a list view for displaying content in a macOS Today widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NCWidgetListViewController"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NCWidgetListViewController"
        }
      ],
      "role": "symbol",
      "title": "NCWidgetListViewController",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetlistviewcontroller"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding": {
      "abstract": [
        {
          "text": "The interface for customizing the appearance and behavior of a Today widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NCWidgetProviding"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NCWidgetProviding"
        }
      ],
      "role": "symbol",
      "title": "NCWidgetProviding",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetproviding"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController": {
      "abstract": [
        {
          "text": "An object that provides a default search view within a macOS Today widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NCWidgetSearchViewController"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NCWidgetSearchViewController"
        }
      ],
      "role": "symbol",
      "title": "NCWidgetSearchViewController",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetsearchviewcontroller"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewDelegate": {
      "abstract": [
        {
          "text": "The interface for enabling user searches in the search view controller of a macOS Today widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NCWidgetSearchViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NCWidgetSearchViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "NCWidgetSearchViewDelegate",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetsearchviewdelegate"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NOTIFICATION_CENTER_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NOTIFICATION_CENTER_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NOTIFICATION_CENTER_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "NOTIFICATION_CENTER_EXTERN",
      "type": "topic",
      "url": "/documentation/notificationcenter/notification_center_extern"
    },
    "media-3039577": {
      "alt": "Widgets showing weather information in the Today view on iOS and macOS.",
      "identifier": "media-3039577",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e202f58bcb54e62c748ceb590bb16819/media-3039577@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Core-Widget",
      "identifiers": [
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding",
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetController"
      ],
      "title": "Core Widget"
    },
    {
      "anchor": "Search-View",
      "identifiers": [
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController",
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewDelegate"
      ],
      "title": "Search View"
    },
    {
      "anchor": "List-View",
      "identifiers": [
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewController"
      ],
      "title": "List View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Core-Widget",
              "identifiers": [
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding",
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetController"
              ],
              "title": "Core Widget"
            },
            {
              "anchor": "Search-View",
              "identifiers": [
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController",
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewDelegate"
              ],
              "title": "Search View"
            },
            {
              "anchor": "List-View",
              "identifiers": [
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetListViewController"
              ],
              "title": "List View"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NOTIFICATION_CENTER_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewController/title",
          "value": "NCWidgetListViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetListViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetListViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetListViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewDelegate/title",
          "value": "NCWidgetSearchViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetSearchViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetSearchViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding/title",
          "value": "NCWidgetProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetController/title",
          "value": "NCWidgetController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController/title",
          "value": "NCWidgetSearchViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetSearchViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetSearchViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/notificationcenter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/notificationcenter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
