{
  "abstract": [
    {
      "text": "Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opengles/documentation/OpenGLES"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "OpenGLES",
    "modules": [
      {
        "name": "OpenGL ES"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecatedAt": "12.0",
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "deprecatedAt": "12.0",
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "deprecatedAt": "12.0",
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "OpenGL ES"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "OpenGL ES provides a C-based interface for hardware-accelerated 2D and 3D graphics rendering. The OpenGL ES framework (",
              "type": "text"
            },
            {
              "code": "OpenGLES.framework",
              "type": "codeVoice"
            },
            {
              "text": ") in iOS provides implementations of versions 1.1, 2.0, and 3.0 of the OpenGL ES specification.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This collection of documents describes the platform-specific APIs for OpenGL ES on iOS devices, also known as EAGL. EAGL provides graphics contexts that encapsulate all OpenGL ES state and the ability to configure a Core Animation layer to be the destination for OpenGL ES drawing commands. EAGL also allows OpenGL ES objects, such as textures, renderbuffers, and framebuffers, to be shared between two or more graphics contexts.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Khronos Group maintains the OpenGL ES specifications and references for the cross-platform OpenGL ES APIs:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "http://www.khronos.org/registry/gles/",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is the official repository of OpenGL ES specification and extension documents provided by the Khronos Group.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For a complete reference to the OpenGL ES APIs and OpenGL ES Shading Language, see the collection for the version of OpenGL ES you plan to use:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "http://www.khronos.org/opengles/sdk/1.1/docs/man/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "http://www.khronos.org/opengles/sdk/docs/man/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "http://www.khronos.org/opengles/sdk/docs/man3/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opengles/documentation/OpenGLES": {
      "abstract": [
        {
          "text": "Create 3D and 2D graphics effects with this compact, efficient subset of OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES",
      "kind": "symbol",
      "role": "collection",
      "title": "OpenGL ES",
      "type": "topic",
      "url": "/documentation/opengles"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/EAGLContext": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.opengles/documentation/OpenGLES/EAGLContext",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object manages an OpenGL ES ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "rendering context",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": "—the state information, commands, and resources needed to draw using OpenGL ES. To execute OpenGL ES commands, you need a current rendering context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAGLContext"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/EAGLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAGLContext"
        }
      ],
      "role": "symbol",
      "title": "EAGLContext",
      "type": "topic",
      "url": "/documentation/opengles/eaglcontext"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable": {
      "abstract": [
        {
          "text": "iOS objects that implement the ",
          "type": "text"
        },
        {
          "code": "EAGLDrawable",
          "type": "codeVoice"
        },
        {
          "text": " protocol can be used as a rendering surface and displayed to the screen by an ",
          "type": "text"
        },
        {
          "code": "EAGLContext",
          "type": "codeVoice"
        },
        {
          "text": " object. In iOS 2.0, this protocol is implemented only by the ",
          "type": "text"
        },
        {
          "code": "CAEAGLLayer",
          "type": "codeVoice"
        },
        {
          "text": " class, but in the future other classes may choose to implement the protocol. The ",
          "type": "text"
        },
        {
          "code": "EAGLDrawable",
          "type": "codeVoice"
        },
        {
          "text": " protocol is not intended to be implemented by objects outside of the iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAGLDrawable"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAGLDrawable"
        }
      ],
      "role": "symbol",
      "title": "EAGLDrawable",
      "type": "topic",
      "url": "/documentation/opengles/eagldrawable"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/EAGLSharegroup": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "EAGLSharegroup",
          "type": "codeVoice"
        },
        {
          "text": " object manages OpenGL ES resources associated with one or more ",
          "type": "text"
        },
        {
          "code": "EAGLContext",
          "type": "codeVoice"
        },
        {
          "text": " objects. It is created when an ",
          "type": "text"
        },
        {
          "code": "EAGLContext",
          "type": "codeVoice"
        },
        {
          "text": " object is initialized and disposed of when the last ",
          "type": "text"
        },
        {
          "code": "EAGLContext",
          "type": "codeVoice"
        },
        {
          "text": " object that references it is released. As an opaque object, there is no developer accessible API.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAGLSharegroup"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/EAGLSharegroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAGLSharegroup"
        }
      ],
      "role": "symbol",
      "title": "EAGLSharegroup",
      "type": "topic",
      "url": "/documentation/opengles/eaglsharegroup"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/GLES_API_DEPRICATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GLES_API_DEPRICATED"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/GLES_API_DEPRICATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLES_API_DEPRICATED",
      "type": "topic",
      "url": "/documentation/opengles/gles_api_depricated"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/GL_SAMPLER_2D_SHADOW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GL_SAMPLER_2D_SHADOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/GL_SAMPLER_2D_SHADOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GL_SAMPLER_2D_SHADOW"
        }
      ],
      "role": "symbol",
      "title": "GL_SAMPLER_2D_SHADOW",
      "type": "topic",
      "url": "/documentation/opengles/gl_sampler_2d_shadow"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/GL_TEXTURE_ENV_COLOR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GL_TEXTURE_ENV_COLOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/GL_TEXTURE_ENV_COLOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GL_TEXTURE_ENV_COLOR"
        }
      ],
      "role": "symbol",
      "title": "GL_TEXTURE_ENV_COLOR",
      "type": "topic",
      "url": "/documentation/opengles/gl_texture_env_color"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/GL_TEXTURE_ENV_MODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GL_TEXTURE_ENV_MODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/GL_TEXTURE_ENV_MODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GL_TEXTURE_ENV_MODE"
        }
      ],
      "role": "symbol",
      "title": "GL_TEXTURE_ENV_MODE",
      "type": "topic",
      "url": "/documentation/opengles/gl_texture_env_mode"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/GL_TIMEOUT_IGNORED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GL_TIMEOUT_IGNORED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/GL_TIMEOUT_IGNORED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GL_TIMEOUT_IGNORED"
        }
      ],
      "role": "symbol",
      "title": "GL_TIMEOUT_IGNORED",
      "type": "topic",
      "url": "/documentation/opengles/gl_timeout_ignored"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/OPENGLES_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OPENGLES_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/OPENGLES_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "OPENGLES_DEPRECATED",
      "type": "topic",
      "url": "/documentation/opengles/opengles_deprecated"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/eagl-functions": {
      "abstract": [
        {
          "text": "This document describes the functions in the OpenGL ES framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/eagl-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "EAGL Functions",
      "type": "topic",
      "url": "/documentation/opengles/eagl-functions"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/glFramebufferTextureLayer(_:_:_:_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "glFramebufferTextureLayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLenum",
          "text": "GLenum"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLenum",
          "text": "GLenum"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLuint",
          "text": "GLuint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/glFramebufferTextureLayer(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "glFramebufferTextureLayer"
        }
      ],
      "role": "symbol",
      "title": "glFramebufferTextureLayer(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/opengles/glframebuffertexturelayer(_:_:_:_:_:)"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenGL ES Constants",
      "type": "topic",
      "url": "/documentation/opengles/opengl-es-constants"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenGL ES Data Types",
      "type": "topic",
      "url": "/documentation/opengles/opengl-es-data-types"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenGL ES Enumerations",
      "type": "topic",
      "url": "/documentation/opengles/opengl-es-enumerations"
    },
    "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenGL ES Functions",
      "type": "topic",
      "url": "/documentation/opengles/opengl-es-functions"
    },
    "http://www.khronos.org/opengles/sdk/1.1/docs/man/": {
      "identifier": "http://www.khronos.org/opengles/sdk/1.1/docs/man/",
      "title": "OpenGL ES 1.1 Reference Pages",
      "titleInlineContent": [
        {
          "text": "OpenGL ES 1.1 Reference Pages",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.khronos.org/opengles/sdk/1.1/docs/man/"
    },
    "http://www.khronos.org/opengles/sdk/docs/man/": {
      "identifier": "http://www.khronos.org/opengles/sdk/docs/man/",
      "title": "OpenGL ES 2.0 Reference Pages",
      "titleInlineContent": [
        {
          "text": "OpenGL ES 2.0 Reference Pages",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.khronos.org/opengles/sdk/docs/man/"
    },
    "http://www.khronos.org/opengles/sdk/docs/man3/": {
      "identifier": "http://www.khronos.org/opengles/sdk/docs/man3/",
      "title": "OpenGL ES 3.0 Reference Pages",
      "titleInlineContent": [
        {
          "text": "OpenGL ES 3.0 Reference Pages",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.khronos.org/opengles/sdk/docs/man3/"
    },
    "http://www.khronos.org/registry/gles/": {
      "identifier": "http://www.khronos.org/registry/gles/",
      "title": "OpenGL ES API Registry",
      "titleInlineContent": [
        {
          "text": "OpenGL ES API Registry",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.khronos.org/registry/gles/"
    },
    "https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40008793": {
      "identifier": "https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40008793",
      "title": "OpenGL ES Programming Guide",
      "titleInlineContent": [
        {
          "text": "OpenGL ES Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40008793"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40008793"
      ],
      "title": "Related Documentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.opengles/documentation/OpenGLES/EAGLContext",
        "doc://com.apple.opengles/documentation/OpenGLES/EAGLSharegroup"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "identifiers": [
        "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.opengles/documentation/OpenGLES/eagl-functions",
        "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-enumerations",
        "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-constants",
        "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-functions",
        "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-data-types"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opengles/documentation/OpenGLES/GL_SAMPLER_2D_SHADOW",
        "doc://com.apple.opengles/documentation/OpenGLES/GL_TEXTURE_ENV_COLOR",
        "doc://com.apple.opengles/documentation/OpenGLES/GL_TEXTURE_ENV_MODE",
        "doc://com.apple.opengles/documentation/OpenGLES/GL_TIMEOUT_IGNORED"
      ],
      "title": "Variables"
    },
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opengles/documentation/OpenGLES/glFramebufferTextureLayer(_:_:_:_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.opengles/documentation/OpenGLES/EAGLContext",
                "doc://com.apple.opengles/documentation/OpenGLES/EAGLSharegroup"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Protocols",
              "identifiers": [
                "doc://com.apple.opengles/documentation/OpenGLES/EAGLDrawable"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.opengles/documentation/OpenGLES/eagl-functions",
                "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-enumerations",
                "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-constants",
                "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-functions",
                "doc://com.apple.opengles/documentation/OpenGLES/opengl-es-data-types"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opengles/documentation/OpenGLES/glFramebufferTextureLayer(_:_:_:_:_:)"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opengles/documentation/OpenGLES/GLES_API_DEPRICATED",
                "doc://com.apple.opengles/documentation/OpenGLES/GL_SAMPLER_2D_SHADOW",
                "doc://com.apple.opengles/documentation/OpenGLES/GL_TEXTURE_ENV_COLOR",
                "doc://com.apple.opengles/documentation/OpenGLES/GL_TEXTURE_ENV_MODE",
                "doc://com.apple.opengles/documentation/OpenGLES/GL_TIMEOUT_IGNORED",
                "doc://com.apple.opengles/documentation/OpenGLES/OPENGLES_DEPRECATED"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40008793"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/title",
          "value": "EAGLDrawable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLDrawable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLContext/title",
          "value": "EAGLContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_TEXTURE_ENV_COLOR/title",
          "value": "GL_TEXTURE_ENV_COLOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_TEXTURE_ENV_COLOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GL_TEXTURE_ENV_COLOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLSharegroup/title",
          "value": "EAGLSharegroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLSharegroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLSharegroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1EAGLSharegroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EAGLSharegroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_TEXTURE_ENV_MODE/title",
          "value": "GL_TEXTURE_ENV_MODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_TEXTURE_ENV_MODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GL_TEXTURE_ENV_MODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_TIMEOUT_IGNORED/title",
          "value": "GL_TIMEOUT_IGNORED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_TIMEOUT_IGNORED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GL_TIMEOUT_IGNORED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_SAMPLER_2D_SHADOW/title",
          "value": "GL_SAMPLER_2D_SHADOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1GL_SAMPLER_2D_SHADOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GL_SAMPLER_2D_SHADOW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1glFramebufferTextureLayer(_:_:_:_:_:)/title",
          "value": "glFramebufferTextureLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opengles~1documentation~1OpenGLES~1glFramebufferTextureLayer(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "glFramebufferTextureLayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opengles"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opengles"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
