{
  "abstract": [
    {
      "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 1"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 1"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "os",
    "modules": [
      {
        "name": "os"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.10",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "os"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/API_OBSOLETED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "API_OBSOLETED"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/API_OBSOLETED",
      "kind": "symbol",
      "role": "symbol",
      "title": "API_OBSOLETED",
      "type": "topic",
      "url": "/documentation/os/api_obsoleted"
    },
    "doc://com.apple.os/documentation/os/API_OBSOLETED_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "API_OBSOLETED_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/API_OBSOLETED_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "API_OBSOLETED_BEGIN",
      "type": "topic",
      "url": "/documentation/os/api_obsoleted_begin"
    },
    "doc://com.apple.os/documentation/os/API_OBSOLETED_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "API_OBSOLETED_END"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/API_OBSOLETED_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "API_OBSOLETED_END",
      "type": "topic",
      "url": "/documentation/os/api_obsoleted_end"
    },
    "doc://com.apple.os/documentation/os/API_OBSOLETED_WITH_REPLACEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "API_OBSOLETED_WITH_REPLACEMENT"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/API_OBSOLETED_WITH_REPLACEMENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "API_OBSOLETED_WITH_REPLACEMENT",
      "type": "topic",
      "url": "/documentation/os/api_obsoleted_with_replacement"
    },
    "doc://com.apple.os/documentation/os/API_OBSOLETED_WITH_REPLACEMENT_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "API_OBSOLETED_WITH_REPLACEMENT_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/API_OBSOLETED_WITH_REPLACEMENT_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "API_OBSOLETED_WITH_REPLACEMENT_BEGIN",
      "type": "topic",
      "url": "/documentation/os/api_obsoleted_with_replacement_begin"
    },
    "doc://com.apple.os/documentation/os/API_OBSOLETED_WITH_REPLACEMENT_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "API_OBSOLETED_WITH_REPLACEMENT_END"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/API_OBSOLETED_WITH_REPLACEMENT_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "API_OBSOLETED_WITH_REPLACEMENT_END",
      "type": "topic",
      "url": "/documentation/os/api_obsoleted_with_replacement_end"
    },
    "doc://com.apple.os/documentation/os/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/os/deprecated-symbols"
    },
    "doc://com.apple.os/documentation/os/logging": {
      "abstract": [
        {
          "text": "Capture telemetry from your app for debugging and performance analysis using the unified logging system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/logging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Logging",
      "type": "topic",
      "url": "/documentation/os/logging"
    },
    "doc://com.apple.os/documentation/os/os-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.os/documentation/os/os-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "os Constants",
      "type": "topic",
      "url": "/documentation/os/os-constants"
    },
    "doc://com.apple.os/documentation/os/os-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.os/documentation/os/os-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "os Data Types",
      "type": "topic",
      "url": "/documentation/os/os-data-types"
    },
    "doc://com.apple.os/documentation/os/os-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.os/documentation/os/os-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "os Macros",
      "type": "topic",
      "url": "/documentation/os/os-macros"
    },
    "doc://com.apple.os/documentation/os/os_block_t": {
      "abstract": [
        {
          "text": "A block that takes no arguments and returns no value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_block_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_block_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_block_t",
      "type": "topic",
      "url": "/documentation/os/os_block_t"
    },
    "doc://com.apple.os/documentation/os/os_function_t": {
      "abstract": [
        {
          "text": "A pointer to a function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_function_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_function_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_function_t",
      "type": "topic",
      "url": "/documentation/os/os_function_t"
    },
    "doc://com.apple.os/documentation/os/os_proc_available_memory": {
      "abstract": [
        {
          "text": "Determines the amount of memory available to the current app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_proc_available_memory"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_proc_available_memory",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_proc_available_memory",
      "type": "topic",
      "url": "/documentation/os/os_proc_available_memory"
    },
    "doc://com.apple.os/documentation/os/os_release-c.func": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_release"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_release-c.func",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_release",
      "type": "topic",
      "url": "/documentation/os/os_release-c.func"
    },
    "doc://com.apple.os/documentation/os/os_retain-c.func": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_retain"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_retain-c.func",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_retain",
      "type": "topic",
      "url": "/documentation/os/os_retain-c.func"
    },
    "doc://com.apple.os/documentation/os/reading-unix-manual-pages": {
      "abstract": [
        {
          "text": "Use the Terminal app to read the documentation for low-level UNIX tools and APIs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/reading-unix-manual-pages",
      "kind": "article",
      "role": "article",
      "title": "Reading UNIX Manual Pages",
      "type": "topic",
      "url": "/documentation/os/reading-unix-manual-pages"
    },
    "doc://com.apple.os/documentation/os/synchronization": {
      "abstract": [
        {
          "text": "Access low-level synchronization mechanisms to control state across threads.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/synchronization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Synchronization",
      "type": "topic",
      "url": "/documentation/os/synchronization"
    },
    "doc://com.apple.os/documentation/os/workgroups": {
      "abstract": [
        {
          "text": "Schedule one or more threads to run at regular intervals and before specific deadlines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/workgroups",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workgroups",
      "type": "topic",
      "url": "/documentation/os/workgroups"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.os/documentation/os/reading-unix-manual-pages"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Logs",
      "identifiers": [
        "doc://com.apple.os/documentation/os/logging"
      ],
      "title": "Logs"
    },
    {
      "anchor": "Task-Management",
      "identifiers": [
        "doc://com.apple.os/documentation/os/synchronization"
      ],
      "title": "Task Management"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.os/documentation/os/deprecated-symbols"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.os/documentation/os/os-constants"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.os/documentation/os/reading-unix-manual-pages"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Logs",
              "identifiers": [
                "doc://com.apple.os/documentation/os/logging"
              ],
              "title": "Logs"
            },
            {
              "anchor": "Task-Management",
              "identifiers": [
                "doc://com.apple.os/documentation/os/workgroups",
                "doc://com.apple.os/documentation/os/synchronization"
              ],
              "title": "Task Management"
            },
            {
              "anchor": "Memory",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_proc_available_memory",
                "doc://com.apple.os/documentation/os/os_block_t",
                "doc://com.apple.os/documentation/os/os_function_t",
                "doc://com.apple.os/documentation/os/os_release-c.func",
                "doc://com.apple.os/documentation/os/os_retain-c.func"
              ],
              "title": "Memory"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.os/documentation/os/deprecated-symbols"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os-macros",
                "doc://com.apple.os/documentation/os/os-data-types"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/API_OBSOLETED",
                "doc://com.apple.os/documentation/os/API_OBSOLETED_BEGIN",
                "doc://com.apple.os/documentation/os/API_OBSOLETED_END",
                "doc://com.apple.os/documentation/os/API_OBSOLETED_WITH_REPLACEMENT",
                "doc://com.apple.os/documentation/os/API_OBSOLETED_WITH_REPLACEMENT_BEGIN",
                "doc://com.apple.os/documentation/os/API_OBSOLETED_WITH_REPLACEMENT_END"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
