{
  "abstract": [
    {
      "text": "A unified logging system for the reading of historical data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.oslog/documentation/OSLog"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "OSLog",
    "modules": [
      {
        "name": "OSLog"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "OSLog"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The OSLog framework allows you to read logs. With the unified logging system, you can build custom debugging and analysis tools to be used alongside Apple tools like Instruments and Console. To learn more about how to create logs, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/os/logging",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/os/logging": {
      "abstract": [
        {
          "text": "Capture telemetry from your app for debugging and performance analysis using the unified logging system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/logging",
      "kind": "article",
      "role": "article",
      "title": "Logging",
      "type": "topic",
      "url": "/documentation/os/logging"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.oslog/documentation/OSLog": {
      "abstract": [
        {
          "text": "A unified logging system for the reading of historical data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog",
      "kind": "symbol",
      "role": "collection",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/oslog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry": {
      "abstract": [
        {
          "text": "A single entry from the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntry"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntry"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity": {
      "abstract": [
        {
          "text": "An entry generated by an activity event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryActivity"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryActivity"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryActivity",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryactivity"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary": {
      "abstract": [
        {
          "text": "The metadata that partitions sequences of other entries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryBoundary"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryBoundary"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryBoundary",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryboundary"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess": {
      "abstract": [
        {
          "text": "A protocol that defines subclasses containing metadata about a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryFromProcess"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryFromProcess"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryFromProcess",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryfromprocess"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog": {
      "abstract": [
        {
          "text": "A log entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryLog"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryLog"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryLog",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost": {
      "abstract": [
        {
          "text": "An entry containing a signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntrySignpost"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntrySignpost"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntrySignpost",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrysignpost"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload": {
      "abstract": [
        {
          "text": "A protocol defining subclasses that represent entries made using a handle and a format string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryWithPayload"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryWithPayload"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryWithPayload",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrywithpayload"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEnumerator": {
      "abstract": [
        {
          "text": "An enumerator that can access and list log entries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEnumerator"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEnumerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEnumerator"
        }
      ],
      "role": "symbol",
      "title": "OSLogEnumerator",
      "type": "topic",
      "url": "/documentation/oslog/oslogenumerator"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent": {
      "abstract": [
        {
          "text": "The message arguments for a particular entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogMessageComponent"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogMessageComponent"
        }
      ],
      "role": "symbol",
      "title": "OSLogMessageComponent",
      "type": "topic",
      "url": "/documentation/oslog/oslogmessagecomponent"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogPosition": {
      "abstract": [
        {
          "text": "A representation of a point in a sequence of entries in the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogPosition"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogPosition"
        }
      ],
      "role": "symbol",
      "title": "OSLogPosition",
      "type": "topic",
      "url": "/documentation/oslog/oslogposition"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogStore": {
      "abstract": [
        {
          "text": "A set of entries from the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogStore"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogStore"
        }
      ],
      "role": "symbol",
      "title": "OSLogStore",
      "type": "topic",
      "url": "/documentation/oslog/oslogstore"
    },
    "doc://com.apple.oslog/documentation/OSLog/oslog-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/oslog-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OSLog Enumerations",
      "type": "topic",
      "url": "/documentation/oslog/oslog-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Read-Log-Entries",
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogStore",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEnumerator"
      ],
      "title": "Read Log Entries"
    },
    {
      "anchor": "Log-Entries",
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload"
      ],
      "title": "Log Entries"
    },
    {
      "anchor": "Entry-Data",
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent",
        "doc://com.apple.oslog/documentation/OSLog/OSLogPosition"
      ],
      "title": "Entry Data"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/oslog-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Read-Log-Entries",
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogStore",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEnumerator"
              ],
              "title": "Read Log Entries"
            },
            {
              "anchor": "Log-Entries",
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryActivity",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryBoundary",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntrySignpost",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryWithPayload"
              ],
              "title": "Log Entries"
            },
            {
              "anchor": "Entry-Data",
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogMessageComponent",
                "doc://com.apple.oslog/documentation/OSLog/OSLogPosition"
              ],
              "title": "Entry Data"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/oslog-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/title",
          "value": "OSLogEntryFromProcess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryFromProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryFromProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryActivity/title",
          "value": "OSLogEntryActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogPosition/title",
          "value": "OSLogPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/title",
          "value": "OSLogMessageComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogMessageComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogMessageComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/title",
          "value": "OSLogEntryLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEnumerator/title",
          "value": "OSLogEnumerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEnumerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEnumerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEnumerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEnumerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogStore/title",
          "value": "OSLogStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/title",
          "value": "OSLogEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload/title",
          "value": "OSLogEntryWithPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryWithPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryWithPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryWithPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryBoundary/title",
          "value": "OSLogEntryBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryBoundary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntrySignpost/title",
          "value": "OSLogEntrySignpost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntrySignpost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntrySignpost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntrySignpost/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntrySignpost"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/oslog"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/oslog"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
