{
  "abstract": [
    {
      "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "PassKit",
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "6.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "6.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Technology",
    "symbolKind": "module",
    "title": "PassKit (Apple Pay and Wallet)"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The PassKit framework lets you:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add Apple Pay to your app",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Manage passes in the user’s Wallet app",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3975193",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Apple Pay is a secure and easy way for users to make purchases in stores, in apps, and on the web. When you use PassKit APIs to support Apple Pay in your iOS and watchOS apps, your users can purchase real-world goods and services, or donate to nonprofit organizations, without ever leaving your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "To add Apple Pay to your web applications, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/apple_pay_on_the_web",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "For digital goods and services delivered within the app, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/in-app-purchase/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3975195",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Wallet app allows users to organize their boarding passes, tickets, gift cards, and loyalty cards. It also lets users manage their payment cards for Apple Pay. Using the PassKit framework, you can add passes to Wallet and have these passes appear on the user’s lock screen based on the time and place when the pass is relevant. You can also update a pass’s content using push notifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/WalletPasses": {
      "abstract": [
        {
          "text": "Create, distribute, and update passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WalletPasses",
      "kind": "symbol",
      "role": "collection",
      "title": "Wallet Passes",
      "type": "topic",
      "url": "/documentation/WalletPasses"
    },
    "doc://com.apple.documentation/documentation/apple_pay_on_the_web": {
      "abstract": [
        {
          "text": "Support Apple Pay on your website with JavaScript-based APIs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple_pay_on_the_web",
      "kind": "symbol",
      "role": "collection",
      "title": "Apple Pay on the Web",
      "type": "topic",
      "url": "/documentation/apple_pay_on_the_web"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/apple-pay": {
      "abstract": [
        {
          "text": "Request and process Apple Pay payments in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/apple-pay",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Apple Pay",
      "type": "topic",
      "url": "/documentation/passkit/apple-pay"
    },
    "doc://com.apple.passkit/documentation/PassKit/wallet": {
      "abstract": [
        {
          "text": "Manage tickets, boarding passes, payment cards and other passes in the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/wallet",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Wallet",
      "type": "topic",
      "url": "/documentation/passkit/wallet"
    },
    "https://developer.apple.com/in-app-purchase/": {
      "identifier": "https://developer.apple.com/in-app-purchase/",
      "title": "In-App Purchase",
      "titleInlineContent": [
        {
          "text": "In-App Purchase",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/in-app-purchase/"
    },
    "media-3975193": {
      "alt": "The Apple Pay logo.",
      "identifier": "media-3975193",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/65928622a496739ca5949a1771499e5d/media-3975193@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e0adf1ae3325ac5a8f914436621fe6fc/media-3975193~dark@2x.png"
        }
      ]
    },
    "media-3975195": {
      "alt": "The icon that respresents Wallet.",
      "identifier": "media-3975195",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1f03432c3578ddd87cc12f1efefebc4e/media-3975195@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c5e6a075eae6bed38b28e6773ce984d0/media-3975195~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/WalletPasses"
      ],
      "title": "Related Documentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Apple-pay-support",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/apple-pay"
      ],
      "title": "Apple pay support"
    },
    {
      "anchor": "Wallet-support",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/wallet"
      ],
      "title": "Wallet support"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Apple-pay-support",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/apple-pay"
              ],
              "title": "Apple pay support"
            },
            {
              "anchor": "Wallet-support",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/wallet"
              ],
              "title": "Wallet support"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/WalletPasses"
              ],
              "title": "Related Documentation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
