{
  "abstract": [
    {
      "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "PencilKit",
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "PencilKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "PencilKit makes it easy to incorporate hand-drawn content into your iPadOS or macOS apps. PencilKit provides a drawing environment for your iOS app that receives input from Apple Pencil or the user’s finger, and turns it into images you display in iPadOS, iOS, or macOS. The environment comes with tools for creating, erasing, and selecting lines.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You capture content in your iPad app using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that you integrate into your existing view hierarchy. It supports the low-latency capture of touches originating from Apple Pencil or your finger. The canvas object sends final results as a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, whose contents you can save with your app’s content. You can also convert the drawn content into an image for display in iOS or macOS app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about handling user interactions on Apple Pencil in your UIKit app, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/apple-pencil-interactions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/apple-pencil-interactions": {
      "abstract": [
        {
          "text": "Handle user interactions like double tap and squeeze on Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/apple-pencil-interactions",
      "kind": "article",
      "role": "article",
      "title": "Apple Pencil interactions",
      "type": "topic",
      "url": "/documentation/UIKit/apple-pencil-interactions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView": {
      "abstract": [
        {
          "text": "A view that captures Apple Pencil input and displays the rendered results in an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "role": "symbol",
      "title": "PKCanvasView",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKContentVersion": {
      "abstract": [
        {
          "text": "Constants that represent versions of PencilKit for backward compatibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKContentVersion"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKContentVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKContentVersion"
        }
      ],
      "role": "symbol",
      "title": "PKContentVersion",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcontentversion"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct": {
      "abstract": [
        {
          "text": "A structure representing the drawing information captured by a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDrawing"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDrawing"
        }
      ],
      "role": "symbol",
      "title": "PKDrawing",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawing-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference": {
      "abstract": [
        {
          "text": "A data structure that contains the drawing information captured by a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDrawingReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDrawingReference"
        }
      ],
      "role": "symbol",
      "title": "PKDrawingReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserTool-swift.struct": {
      "abstract": [
        {
          "text": "A tool for erasing previously drawn content in a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKEraserTool"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserTool-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKEraserTool"
        }
      ],
      "role": "symbol",
      "title": "PKEraserTool",
      "type": "topic",
      "url": "/documentation/pencilkit/pkerasertool-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserToolReference": {
      "abstract": [
        {
          "text": "A tool for erasing previously drawn content in a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKEraserToolReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserToolReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKEraserToolReference"
        }
      ],
      "role": "symbol",
      "title": "PKEraserToolReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkerasertoolreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKFloatRange": {
      "abstract": [
        {
          "text": "A utility class that represents range components of a stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKFloatRange"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKFloatRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKFloatRange",
      "type": "topic",
      "url": "/documentation/pencilkit/pkfloatrange"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents an ink that specifies its type, color, and width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInk"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInk"
        }
      ],
      "role": "symbol",
      "title": "PKInk",
      "type": "topic",
      "url": "/documentation/pencilkit/pkink-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference": {
      "abstract": [
        {
          "text": "Provides a description of the creation and rendering of marks on a canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInkReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInkReference"
        }
      ],
      "role": "symbol",
      "title": "PKInkReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkinkreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct": {
      "abstract": [
        {
          "text": "A structure that defines the drawing characteristics (width, color, pen style) to use when drawing lines on a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInkingTool"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInkingTool"
        }
      ],
      "role": "symbol",
      "title": "PKInkingTool",
      "type": "topic",
      "url": "/documentation/pencilkit/pkinkingtool-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingToolReference": {
      "abstract": [
        {
          "text": "An object that defines the drawing characteristics (width, color, pen style) to use when drawing lines on a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInkingToolReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingToolReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInkingToolReference"
        }
      ],
      "role": "symbol",
      "title": "PKInkingToolReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkinkingtoolreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKLassoTool-swift.struct": {
      "abstract": [
        {
          "text": "A tool for selecting stroked lines and shapes in a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKLassoTool"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKLassoTool-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKLassoTool"
        }
      ],
      "role": "symbol",
      "title": "PKLassoTool",
      "type": "topic",
      "url": "/documentation/pencilkit/pklassotool-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKLassoToolReference": {
      "abstract": [
        {
          "text": "A tool for selecting stroked lines and shapes in a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKLassoToolReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKLassoToolReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKLassoToolReference"
        }
      ],
      "role": "symbol",
      "title": "PKLassoToolReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pklassotoolreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents the paths, boundaries, and other properties of a stroke drawn on a canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStroke"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStroke"
        }
      ],
      "role": "symbol",
      "title": "PKStroke",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstroke-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct": {
      "abstract": [
        {
          "text": "A structure that captures the components of a stroke and provides methods to find and interpolate points along the stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePath"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePath"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePath",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepath-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePathReference": {
      "abstract": [
        {
          "text": "A class that captures the components of a stroke and provides methods to find and interpolate points along the stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePathReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePathReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePathReference"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePathReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepathreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents the properties of a specific point along a stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePoint"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePoint"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePoint",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference": {
      "abstract": [
        {
          "text": "A class that represents the properties of a specific point along a stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePointReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePointReference"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePointReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokeReference": {
      "abstract": [
        {
          "text": "A class that represents the paths, boundaries and other properties of a stroke drawn on a canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokeReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokeReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokeReference"
        }
      ],
      "role": "symbol",
      "title": "PKStrokeReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokereference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKTool-c.class": {
      "abstract": [
        {
          "text": "An abstract base class for tools used by a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKTool"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKTool-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKTool",
      "type": "topic",
      "url": "/documentation/pencilkit/pktool-c.class"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKTool-swift.protocol": {
      "abstract": [
        {
          "text": "An interface adopted by drawing and writing tools used by a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKTool"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKTool-swift.protocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKTool"
        }
      ],
      "role": "symbol",
      "title": "PKTool",
      "type": "topic",
      "url": "/documentation/pencilkit/pktool-swift.protocol"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker": {
      "abstract": [
        {
          "text": "A tool palette that displays a selection of drawing tools and colors for tools that a person can choose from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPicker"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPicker"
        }
      ],
      "role": "symbol",
      "title": "PKToolPicker",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpicker"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/Delegate-swift.protocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Delegate"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/Delegate-swift.protocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Delegate"
        }
      ],
      "role": "symbol",
      "title": "PKToolPicker.Delegate",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpicker/delegate-swift.protocol"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/ControlOptions": {
      "abstract": [
        {
          "text": "Options for which controls to present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlOptions"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/ControlOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlOptions"
        }
      ],
      "role": "symbol",
      "title": "PKToolPickerCustomItem.ControlOptions",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitem/controloptions"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/configuring-the-pencilkit-tool-picker": {
      "abstract": [
        {
          "text": "Incorporate a custom PencilKit tool picker with a variety of system and custom tools into a drawing app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/configuring-the-pencilkit-tool-picker",
      "kind": "article",
      "role": "sampleCode",
      "title": "Configuring the PencilKit tool picker",
      "type": "topic",
      "url": "/documentation/pencilkit/configuring-the-pencilkit-tool-picker"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/customizing-scribble-with-interactions": {
      "abstract": [
        {
          "text": "Enable writing on a non-text-input view by adding interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/customizing-scribble-with-interactions",
      "kind": "article",
      "role": "sampleCode",
      "title": "Customizing Scribble with Interactions",
      "type": "topic",
      "url": "/documentation/pencilkit/customizing-scribble-with-interactions"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/drawing-with-pencilkit": {
      "abstract": [
        {
          "text": "Add expressive, low-latency drawing to your app using PencilKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/drawing-with-pencilkit",
      "kind": "article",
      "role": "sampleCode",
      "title": "Drawing with PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit/drawing-with-pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/inspecting-modifying-and-constructing-pencilkit-drawings": {
      "abstract": [
        {
          "text": "Score users’ ability to match PencilKit drawings generated from text, by accessing the strokes and points inside PencilKit drawings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/inspecting-modifying-and-constructing-pencilkit-drawings",
      "kind": "article",
      "role": "sampleCode",
      "title": "Inspecting, Modifying, and Constructing PencilKit Drawings",
      "type": "topic",
      "url": "/documentation/pencilkit/inspecting-modifying-and-constructing-pencilkit-drawings"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/supporting-backward-compatibility-for-ink-types": {
      "abstract": [
        {
          "text": "Leverage the latest PencilKit features while providing a good user experience in earlier versions of the OS that don’t support those features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/supporting-backward-compatibility-for-ink-types",
      "kind": "article",
      "role": "article",
      "title": "Supporting backward compatibility for ink types",
      "type": "topic",
      "url": "/documentation/pencilkit/supporting-backward-compatibility-for-ink-types"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Canvas",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/drawing-with-pencilkit",
        "doc://com.apple.pencilkit/documentation/PencilKit/customizing-scribble-with-interactions",
        "doc://com.apple.pencilkit/documentation/PencilKit/inspecting-modifying-and-constructing-pencilkit-drawings",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct"
      ],
      "title": "Canvas"
    },
    {
      "anchor": "Tools",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/configuring-the-pencilkit-tool-picker",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserTool-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKLassoTool-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKTool-swift.protocol"
      ],
      "title": "Tools"
    },
    {
      "anchor": "Backward-compatibility",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/supporting-backward-compatibility-for-ink-types",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKContentVersion"
      ],
      "title": "Backward compatibility"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Canvas",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokeReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePathReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKFloatRange"
              ],
              "title": "Canvas"
            },
            {
              "anchor": "Tools",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingToolReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserToolReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKLassoToolReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKTool-c.class"
              ],
              "title": "Tools"
            },
            {
              "anchor": "Backward-compatibility",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/supporting-backward-compatibility-for-ink-types",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKContentVersion"
              ],
              "title": "Backward compatibility"
            },
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/Delegate-swift.protocol"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/ControlOptions"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKContentVersion/title",
          "value": "PKContentVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKContentVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKContentVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKContentVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKContentVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem~1ControlOptions/title",
          "value": "PKToolPickerCustomItemControlOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem~1ControlOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerCustomItemControlOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem~1ControlOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerCustomItemControlOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkingToolReference/title",
          "value": "PKInkingTool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkingToolReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInkingTool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkingToolReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInkingTool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokeReference/title",
          "value": "PKStroke"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokeReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStroke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokeReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStroke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1Delegate-swift.protocol/title",
          "value": "PKToolPickerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1Delegate-swift.protocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1Delegate-swift.protocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKEraserToolReference/title",
          "value": "PKEraserTool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKEraserToolReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKEraserTool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKEraserToolReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKEraserTool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker/title",
          "value": "PKToolPicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/title",
          "value": "PKCanvasView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePathReference/title",
          "value": "PKStrokePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePathReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePathReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/title",
          "value": "PKInk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/title",
          "value": "PKDrawing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKLassoToolReference/title",
          "value": "PKLassoTool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKLassoToolReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKLassoTool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKLassoToolReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKLassoTool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/title",
          "value": "PKStrokePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePoint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pencilkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
