{
  "abstract": [
    {
      "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "Photos",
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.11",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Photos"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use PhotoKit to access image and video assets that the Photos app manages in iOS, macOS, tvOS, and visionOS. You might use this framework to edit or display a person’s photos, or to manage collections of assets such as albums, Moments, and Shared Albums. The framework provides access to photos on the person’s device and in iCloud.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Photos is a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.photokit/documentation/PhotoKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit",
      "kind": "article",
      "role": "collection",
      "title": "PhotoKit",
      "type": "topic",
      "url": "/documentation/photokit"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/deprecated-errors": {
      "abstract": [
        {
          "text": "Review unsupported errors and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/deprecated-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Errors",
      "type": "topic",
      "url": "/documentation/photokit/deprecated-errors"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/fetching-objects-and-requesting-changes": {
      "abstract": [
        {
          "text": "Get assets, asset collections, and collection lists matching a specified query.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/fetching-objects-and-requesting-changes",
      "kind": "article",
      "role": "article",
      "title": "Fetching Objects and Requesting Changes",
      "type": "topic",
      "url": "/documentation/photokit/fetching-objects-and-requesting-changes"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/loading-and-caching-assets-and-thumbnails": {
      "abstract": [
        {
          "text": "Request image, video, or Live Photos content, and cache for quick reuse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/loading-and-caching-assets-and-thumbnails",
      "kind": "article",
      "role": "article",
      "title": "Loading and Caching Assets and Thumbnails",
      "type": "topic",
      "url": "/documentation/photokit/loading-and-caching-assets-and-thumbnails"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset": {
      "abstract": [
        {
          "text": "A representation of an image, video, or Live Photo in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "role": "symbol",
      "title": "PHAsset",
      "type": "topic",
      "url": "/documentation/photos/phasset"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection": {
      "abstract": [
        {
          "text": "A representation of a Photos asset grouping, such as a moment, user-created album, or smart album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCollection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollection"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollection",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest": {
      "abstract": [
        {
          "text": "A request to create a new Photos asset from underlying data resources, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCreationRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCreationRequest"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCreationRequest",
      "type": "topic",
      "url": "/documentation/photos/phassetcreationrequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResource": {
      "abstract": [
        {
          "text": "An underlying data resource associated with a photo, video, or Live Photo asset in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResource"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResource"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResource",
      "type": "topic",
      "url": "/documentation/photos/phassetresource"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceCreationOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the creation of a new Photos asset from underlying resources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResourceCreationOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceCreationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceCreationOptions"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceCreationOptions",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcecreationoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager": {
      "abstract": [
        {
          "text": "A resource manager for the data storage underlying a Photos asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResourceManager"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceManager"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceManager",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcemanager"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceRequestOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the delivery of underlying asset data that you request from the asset resource manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResourceRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceRequestOptions",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcerequestoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager": {
      "abstract": [
        {
          "text": "An object that facilitates retrieving or generating preview thumbnails, optimized for batch preloading large numbers of assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCachingImageManager"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCachingImageManager"
        }
      ],
      "role": "symbol",
      "title": "PHCachingImageManager",
      "type": "topic",
      "url": "/documentation/photos/phcachingimagemanager"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollection": {
      "abstract": [
        {
          "text": "The abstract superclass for Photos asset collections and collection lists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCollection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollection"
        }
      ],
      "role": "symbol",
      "title": "PHCollection",
      "type": "topic",
      "url": "/documentation/photos/phcollection"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionList": {
      "abstract": [
        {
          "text": "A group containing Photos asset collections, such as Moments, Years, or folders of user-created albums.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCollectionList"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionList"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionList",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlist"
    },
    "doc://com.apple.photokit/documentation/Photos/PHFetchOptions": {
      "abstract": [
        {
          "text": "A set of options that affect the filtering, sorting, and management of results that Photos returns when you fetch asset or collection objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHFetchOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHFetchOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHFetchOptions"
        }
      ],
      "role": "symbol",
      "title": "PHFetchOptions",
      "type": "topic",
      "url": "/documentation/photos/phfetchoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHFetchResult": {
      "abstract": [
        {
          "text": "An ordered list of assets or collections returned from a Photos fetch method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHFetchResult"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHFetchResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHFetchResult"
        }
      ],
      "role": "symbol",
      "title": "PHFetchResult",
      "type": "topic",
      "url": "/documentation/photos/phfetchresult"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageManager": {
      "abstract": [
        {
          "text": "An object that facilitates retrieving or generating preview thumbnails and asset data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHImageManager"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageManager"
        }
      ],
      "role": "symbol",
      "title": "PHImageManager",
      "type": "topic",
      "url": "/documentation/photos/phimagemanager"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the delivery of still image representations of Photos assets you request from an image manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHImageRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "PHImageRequestOptions",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhoto": {
      "abstract": [
        {
          "text": "A displayable representation of a Live Photo—a picture that includes motion and sound from the moments just before and after its capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhoto"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhoto"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhoto",
      "type": "topic",
      "url": "/documentation/photos/phlivephoto"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the delivery of Live Photo assets you request from an image manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoRequestOptions",
      "type": "topic",
      "url": "/documentation/photos/phlivephotorequestoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHObject": {
      "abstract": [
        {
          "text": "The abstract superclass for Photos model objects (assets and collections).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHObject"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHObject"
        }
      ],
      "role": "symbol",
      "title": "PHObject",
      "type": "topic",
      "url": "/documentation/photos/phobject"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary": {
      "abstract": [
        {
          "text": "An object that manages access and changes to the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "role": "symbol",
      "title": "PHPhotoLibrary",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPhotosError"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosError"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosErrorDomain": {
      "abstract": [
        {
          "text": "A string representation of the error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPhotosErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosErrorDomain",
      "type": "topic",
      "url": "/documentation/photos/phphotoserrordomain"
    },
    "doc://com.apple.photokit/documentation/Photos/PHProject": {
      "abstract": [
        {
          "text": "A representation of a Photos app project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProject"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHProject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProject"
        }
      ],
      "role": "symbol",
      "title": "PHProject",
      "type": "topic",
      "url": "/documentation/photos/phproject"
    },
    "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest": {
      "abstract": [
        {
          "text": "A request to change asset data in a Photos project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHProjectChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phprojectchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the delivery of video asset data that you request from an image manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHVideoRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHVideoRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "PHVideoRequestOptions",
      "type": "topic",
      "url": "/documentation/photos/phvideorequestoptions"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Frameworks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI"
      ],
      "title": "Frameworks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Shared-photo-library",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary"
      ],
      "title": "Shared photo library"
    },
    {
      "anchor": "Asset-retrieval",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/fetching-objects-and-requesting-changes",
        "doc://com.apple.photokit/documentation/Photos/PHAsset",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollection",
        "doc://com.apple.photokit/documentation/Photos/PHCollection",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionList",
        "doc://com.apple.photokit/documentation/Photos/PHObject",
        "doc://com.apple.photokit/documentation/Photos/PHFetchResult",
        "doc://com.apple.photokit/documentation/Photos/PHFetchOptions"
      ],
      "title": "Asset retrieval"
    },
    {
      "anchor": "Asset-loading",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/loading-and-caching-assets-and-thumbnails",
        "doc://com.apple.photokit/documentation/Photos/PHImageManager",
        "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager",
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions",
        "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions"
      ],
      "title": "Asset loading"
    },
    {
      "anchor": "Asset-resource-management",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetResource",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceCreationOptions",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceRequestOptions"
      ],
      "title": "Asset resource management"
    },
    {
      "anchor": "Live-Photos",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHLivePhoto"
      ],
      "title": "Live Photos"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Deprecated-errors",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/deprecated-errors"
      ],
      "title": "Deprecated errors"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHProject",
        "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHPhotosErrorDomain"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Shared-photo-library",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary"
              ],
              "title": "Shared photo library"
            },
            {
              "anchor": "Asset-retrieval",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotoKit/fetching-objects-and-requesting-changes",
                "doc://com.apple.photokit/documentation/Photos/PHAsset",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollection",
                "doc://com.apple.photokit/documentation/Photos/PHCollection",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionList",
                "doc://com.apple.photokit/documentation/Photos/PHObject",
                "doc://com.apple.photokit/documentation/Photos/PHFetchResult",
                "doc://com.apple.photokit/documentation/Photos/PHFetchOptions"
              ],
              "title": "Asset retrieval"
            },
            {
              "anchor": "Asset-loading",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotoKit/loading-and-caching-assets-and-thumbnails",
                "doc://com.apple.photokit/documentation/Photos/PHImageManager",
                "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager",
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions",
                "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions",
                "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions"
              ],
              "title": "Asset loading"
            },
            {
              "anchor": "Asset-resource-management",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetResource",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceCreationOptions",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceRequestOptions"
              ],
              "title": "Asset resource management"
            },
            {
              "anchor": "Live-Photos",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHLivePhoto"
              ],
              "title": "Live Photos"
            },
            {
              "anchor": "Deprecated-errors",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotoKit/deprecated-errors"
              ],
              "title": "Deprecated errors"
            },
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHProject",
                "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHPhotosErrorDomain"
              ],
              "title": "Variables"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Frameworks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI"
              ],
              "title": "Frameworks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceRequestOptions/title",
          "value": "PHAssetResourceRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptions/title",
          "value": "PHVideoRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHVideoRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHVideoRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList/title",
          "value": "PHCollectionList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager/title",
          "value": "PHCachingImageManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCachingImageManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCachingImageManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/title",
          "value": "PHProjectChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceCreationOptions/title",
          "value": "PHAssetResourceCreationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceCreationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceCreationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceCreationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceCreationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/title",
          "value": "PHLivePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosErrorDomain/title",
          "value": "PHPhotosErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollection/title",
          "value": "PHCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions/title",
          "value": "PHImageRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCreationRequest/title",
          "value": "PHAssetCreationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCreationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCreationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCreationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCreationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObject/title",
          "value": "PHObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchOptions/title",
          "value": "PHFetchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHFetchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHFetchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/title",
          "value": "PHPhotoLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/title",
          "value": "PHAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResult/title",
          "value": "PHFetchResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHFetchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHFetchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageManager/title",
          "value": "PHImageManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/title",
          "value": "PHAssetCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestOptions/title",
          "value": "PHLivePhotoRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource/title",
          "value": "PHAssetResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProject/title",
          "value": "PHProject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager/title",
          "value": "PHAssetResourceManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
