{
  "abstract": [
    {
      "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "PhotosUI",
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.11",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "PhotosUI"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "PhotosUI offers a photo picker that enables people to view their library and choose one or more photos for your app to display or process. The picker renders in a system view and only gives your app access to the photos someone chooses, which facilitates a user experience with enhanced privacy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The framework also provides a view you can use to display live photos.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "PhotosUI is a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.photokit/documentation/PhotoKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit",
      "kind": "article",
      "role": "collection",
      "title": "PhotoKit",
      "type": "topic",
      "url": "/documentation/photokit"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/bringing-photos-picker-to-your-swiftui-app": {
      "abstract": [
        {
          "text": "Select media assets by using a Photos picker view that SwiftUI provides.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/bringing-photos-picker-to-your-swiftui-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Bringing Photos picker to your SwiftUI app",
      "type": "topic",
      "url": "/documentation/photokit/bringing-photos-picker-to-your-swiftui-app"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/creating-a-slideshow-project-extension-for-photos": {
      "abstract": [
        {
          "text": "Augment the macOS Photos app with extensions that support project creation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/creating-a-slideshow-project-extension-for-photos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a Slideshow Project Extension for Photos",
      "type": "topic",
      "url": "/documentation/photokit/creating-a-slideshow-project-extension-for-photos"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/creating-photo-editing-extensions": {
      "abstract": [
        {
          "text": "Provide custom functionality in the Photos app by bundling an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/creating-photo-editing-extensions",
      "kind": "article",
      "role": "article",
      "title": "Creating Photo Editing Extensions",
      "type": "topic",
      "url": "/documentation/photokit/creating-photo-editing-extensions"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/delivering-an-enhanced-privacy-experience-in-your-photos-app": {
      "abstract": [
        {
          "text": "Adopt the latest privacy enhancements to deliver advanced user-privacy controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/delivering-an-enhanced-privacy-experience-in-your-photos-app",
      "kind": "article",
      "role": "article",
      "title": "Delivering an Enhanced Privacy Experience in Your Photos App",
      "type": "topic",
      "url": "/documentation/photokit/delivering-an-enhanced-privacy-experience-in-your-photos-app"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/displaying-live-photos": {
      "abstract": [
        {
          "text": "Provide the same interactive playback of Live Photos as in the iOS Photos app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/displaying-live-photos",
      "kind": "article",
      "role": "article",
      "title": "Displaying Live Photos",
      "type": "topic",
      "url": "/documentation/photokit/displaying-live-photos"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/implementing-an-inline-photos-picker": {
      "abstract": [
        {
          "text": "Embed a system-provided, half-height Photos picker into your app’s view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/implementing-an-inline-photos-picker",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing an inline Photos picker",
      "type": "topic",
      "url": "/documentation/photokit/implementing-an-inline-photos-picker"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/selecting-photos-and-videos-in-ios": {
      "abstract": [
        {
          "text": "Improve the user experience of finding and selecting assets by using the Photos picker.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/selecting-photos-and-videos-in-ios",
      "kind": "article",
      "role": "sampleCode",
      "title": "Selecting Photos and Videos in iOS",
      "type": "topic",
      "url": "/documentation/photokit/selecting-photos-and-videos-in-ios"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHProject": {
      "abstract": [
        {
          "text": "A representation of a Photos app project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProject"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHProject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProject"
        }
      ],
      "role": "symbol",
      "title": "PHProject",
      "type": "topic",
      "url": "/documentation/photos/phproject"
    },
    "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest": {
      "abstract": [
        {
          "text": "A request to change asset data in a Photos project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHProjectChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phprojectchangerequest"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHContentEditingController": {
      "abstract": [
        {
          "text": "A protocol your custom view controller class implements to provide a user interface for your Photos extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHContentEditingController"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHContentEditingController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHContentEditingController"
        }
      ],
      "role": "symbol",
      "title": "PHContentEditingController",
      "type": "topic",
      "url": "/documentation/photosui/phcontenteditingcontroller"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoView": {
      "abstract": [
        {
          "text": "A view that displays a Live Photo—a picture that also includes motion and sound from the moments just before and after its capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoView"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoView"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoView",
      "type": "topic",
      "url": "/documentation/photosui/phlivephotoview"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class": {
      "abstract": [
        {
          "text": "An object that contains information about how to configure a picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerConfiguration",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "An object that contains information about how to configure a picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "role": "symbol",
      "title": "PHPickerConfiguration",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class": {
      "abstract": [
        {
          "text": "A type that defines the filter to apply to the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct": {
      "abstract": [
        {
          "text": "A type that defines the filter to apply to the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerFilter"
        }
      ],
      "role": "symbol",
      "title": "PHPickerFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-c.class": {
      "abstract": [
        {
          "text": "Types that represent a selected asset from the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerResult"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerResult",
      "type": "topic",
      "url": "/documentation/photosui/phpickerresult-c.class"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-swift.struct": {
      "abstract": [
        {
          "text": "Types that represent a selected asset from the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerResult"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerResult"
        }
      ],
      "role": "symbol",
      "title": "PHPickerResult",
      "type": "topic",
      "url": "/documentation/photosui/phpickerresult-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that provides the user interface for choosing assets from the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "PHPickerViewController",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontroller"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewControllerDelegate-5yntc": {
      "abstract": [
        {
          "text": "A set of methods that the delegate must implement to respond to ",
          "type": "text"
        },
        {
          "code": "PHPickerViewController",
          "type": "codeVoice"
        },
        {
          "text": " user events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewControllerDelegate-5yntc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PHPickerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontrollerdelegate-5yntc"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectCategory": {
      "abstract": [
        {
          "text": "A representation of Photos project extension categories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectCategory"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCategory"
        }
      ],
      "role": "symbol",
      "title": "PHProjectCategory",
      "type": "topic",
      "url": "/documentation/photosui/phprojectcategory"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement": {
      "abstract": [
        {
          "text": "The superclass for all element objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectElement"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectElement"
        }
      ],
      "role": "symbol",
      "title": "PHProjectElement",
      "type": "topic",
      "url": "/documentation/photosui/phprojectelement"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext": {
      "abstract": [
        {
          "text": "An object that provides Photos project extensions with access to the underlying project, as well as to the user’s photo library for editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "PHProjectExtensionContext",
      "type": "topic",
      "url": "/documentation/photosui/phprojectextensioncontext"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController": {
      "abstract": [
        {
          "text": "A protocol defining the life cycle and supported types of project extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectExtensionController"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectExtensionController"
        }
      ],
      "role": "symbol",
      "title": "PHProjectExtensionController",
      "type": "topic",
      "url": "/documentation/photosui/phprojectextensioncontroller"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo": {
      "abstract": [
        {
          "text": "Information about the project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectInfo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectInfo"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectRegionOfInterest": {
      "abstract": [
        {
          "text": "A representation of a region of interest in a photo asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectRegionOfInterest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectRegionOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectRegionOfInterest"
        }
      ],
      "role": "symbol",
      "title": "PHProjectRegionOfInterest",
      "type": "topic",
      "url": "/documentation/photosui/phprojectregionofinterest"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection": {
      "abstract": [
        {
          "text": "A collection of content representing curated asset and text elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectSection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectSection"
        }
      ],
      "role": "symbol",
      "title": "PHProjectSection",
      "type": "topic",
      "url": "/documentation/photosui/phprojectsection"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PhotosPicker": {
      "abstract": [
        {
          "text": "A view that displays a Photos picker for choosing assets from the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PhotosPicker"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PhotosPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PhotosPicker"
        }
      ],
      "role": "symbol",
      "title": "PhotosPicker",
      "type": "topic",
      "url": "/documentation/photosui/photospicker"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PhotosPickerItem": {
      "abstract": [
        {
          "text": "A type that represents an item you use with a Photos picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PhotosPickerItem"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PhotosPickerItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PhotosPickerItem"
        }
      ],
      "role": "symbol",
      "title": "PhotosPickerItem",
      "type": "topic",
      "url": "/documentation/photosui/photospickeritem"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PhotosPickerSelectionBehavior": {
      "abstract": [
        {
          "text": "A type that describes how the Photos picker handles user selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PhotosPickerSelectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PhotosPickerSelectionBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PhotosPickerSelectionBehavior"
        }
      ],
      "role": "symbol",
      "title": "PhotosPickerSelectionBehavior",
      "type": "topic",
      "url": "/documentation/photosui/photospickerselectionbehavior"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PhotosPickerStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PhotosPickerStyle"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PhotosPickerStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PhotosPickerStyle"
        }
      ],
      "role": "symbol",
      "title": "PhotosPickerStyle",
      "type": "topic",
      "url": "/documentation/photosui/photospickerstyle"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Frameworks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos"
      ],
      "title": "Frameworks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Shared-photo-library",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/delivering-an-enhanced-privacy-experience-in-your-photos-app",
        "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoView"
      ],
      "title": "Shared photo library"
    },
    {
      "anchor": "Photos-picker-for-UIKit-AppKit",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/selecting-photos-and-videos-in-ios",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewControllerDelegate-5yntc",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-swift.struct"
      ],
      "title": "Photos picker for UIKit, AppKit"
    },
    {
      "anchor": "Photos-picker-for-SwiftUI",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/bringing-photos-picker-to-your-swiftui-app",
        "doc://com.apple.photokit/documentation/PhotoKit/implementing-an-inline-photos-picker",
        "doc://com.apple.photokit/documentation/PhotosUI/PhotosPicker",
        "doc://com.apple.photokit/documentation/PhotosUI/PhotosPickerItem",
        "doc://com.apple.photokit/documentation/PhotosUI/PhotosPickerSelectionBehavior",
        "doc://com.apple.photokit/documentation/PhotosUI/PhotosPickerStyle"
      ],
      "title": "Photos picker for SwiftUI"
    },
    {
      "anchor": "Live-Photos",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/displaying-live-photos"
      ],
      "title": "Live Photos"
    },
    {
      "anchor": "Photo-Editing-Extensions",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/creating-photo-editing-extensions",
        "doc://com.apple.photokit/documentation/PhotosUI/PHContentEditingController"
      ],
      "title": "Photo Editing Extensions"
    },
    {
      "anchor": "macOS-Photos-Project-Extensions",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/creating-a-slideshow-project-extension-for-photos",
        "doc://com.apple.photokit/documentation/Photos/PHProject",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectRegionOfInterest",
        "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectCategory"
      ],
      "title": "macOS Photos Project Extensions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Shared-photo-library",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotoKit/delivering-an-enhanced-privacy-experience-in-your-photos-app",
                "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoView"
              ],
              "title": "Shared photo library"
            },
            {
              "anchor": "Photos-picker-for-UIKit-AppKit",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotoKit/selecting-photos-and-videos-in-ios",
                "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
                "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class",
                "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class",
                "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-c.class"
              ],
              "title": "Photos picker for UIKit, AppKit"
            },
            {
              "anchor": "Photos-picker-for-SwiftUI",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotoKit/bringing-photos-picker-to-your-swiftui-app",
                "doc://com.apple.photokit/documentation/PhotoKit/implementing-an-inline-photos-picker"
              ],
              "title": "Photos picker for SwiftUI"
            },
            {
              "anchor": "Live-Photos",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotoKit/displaying-live-photos"
              ],
              "title": "Live Photos"
            },
            {
              "anchor": "Photo-Editing-Extensions",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotoKit/creating-photo-editing-extensions",
                "doc://com.apple.photokit/documentation/PhotosUI/PHContentEditingController"
              ],
              "title": "Photo Editing Extensions"
            },
            {
              "anchor": "macOS-Photos-Project-Extensions",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotoKit/creating-a-slideshow-project-extension-for-photos",
                "doc://com.apple.photokit/documentation/Photos/PHProject",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectRegionOfInterest",
                "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectCategory"
              ],
              "title": "macOS Photos Project Extensions"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Frameworks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos"
              ],
              "title": "Frameworks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHContentEditingController/title",
          "value": "PHContentEditingController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHContentEditingController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHContentEditingController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext/title",
          "value": "PHProjectExtensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoView/title",
          "value": "PHLivePhotoView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectElement/title",
          "value": "PHProjectElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectRegionOfInterest/title",
          "value": "PHProjectRegionOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectRegionOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectRegionOfInterest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/title",
          "value": "PHProjectChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectCategory/title",
          "value": "PHProjectCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection/title",
          "value": "PHProjectSection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProject/title",
          "value": "PHProject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/title",
          "value": "PHProjectInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController/title",
          "value": "PHProjectExtensionController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/title",
          "value": "PHPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photosui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
