{
  "abstract": [
    {
      "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "professional_video_applications",
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "collection",
    "roleHeading": "Technology",
    "symbolKind": "module",
    "title": "Professional Video Applications"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Final Cut Pro XML (FCPXML) offers a way for video producers to streamline the exchange of media and metadata between apps and Final Cut Pro. Use FCPXML to send media and metadata from your app to Final Cut Pro for editing, and receive rendered projects—along with their edit descriptions and metadata—from Final Cut Pro into your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can choose to build a workflow extension for your app and integrate the app’s workflow within the Final Cut Pro interface. Workflow extensions provide a seamless experience by allowing users to access your app’s workflow without leaving the Final Cut Pro interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The FxPlug SDK provides a complete API for creating custom effects plug-ins. Your plug-ins are fully integrated with Final Cut Pro and Motion so video editors can easily add them in post-production.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Compressor Extension SDK comes with APIs that allow you to add output file formats that the Compressor app does not provide by default. Use the SDK to integrate your custom output formats into the Compressor app settings and allow users to export their Final Cut Pro projects to your custom file formats.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about Final Cut Pro concepts, see ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/guide/final-cut-pro/what-are-libraries-verfdd5c590e/mac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/guide/final-cut-pro/intro-to-metadata-verc392f8885/mac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro": {
      "abstract": [
        {
          "text": "Send media assets and timeline sequences to Final Cut Pro for editing, and receive rendered media and editing decisions in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Content and Metadata Exchanges with Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/content-and-metadata-exchanges-with-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/create-an-effect-template-for-use-in-final-cut-pro": {
      "abstract": [
        {
          "text": "Use Motion to create custom filters, generators, and transitions for Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/create-an-effect-template-for-use-in-final-cut-pro",
      "kind": "article",
      "role": "article",
      "title": "Create an effect template for use in Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/create-an-effect-template-for-use-in-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/encoder-extensions": {
      "abstract": [
        {
          "text": "Add custom output file formats to the Final Cut Pro workflow.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/encoder-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Encoder Extensions",
      "type": "topic",
      "url": "/documentation/professional-video-applications/encoder-extensions"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug": {
      "abstract": [
        {
          "text": "Create custom effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FxPlug",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fxplug"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Professional Video Applications Constants",
      "type": "topic",
      "url": "/documentation/professional-video-applications/professional-video-applications-constants"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Professional Video Applications Data Types",
      "type": "topic",
      "url": "/documentation/professional-video-applications/professional-video-applications-data-types"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Professional Video Applications Enumerations",
      "type": "topic",
      "url": "/documentation/professional-video-applications/professional-video-applications-enumerations"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-protocols": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-protocols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Professional Video Applications Protocols",
      "type": "topic",
      "url": "/documentation/professional-video-applications/professional-video-applications-protocols"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/workflow-extensions": {
      "abstract": [
        {
          "text": "Integrate your app’s workflow within the Final Cut Pro interface to streamline data exchange.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/workflow-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workflow Extensions",
      "type": "topic",
      "url": "/documentation/professional-video-applications/workflow-extensions"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_ChangesOutputSize": {
      "abstract": [
        {
          "text": "A key that determines whether your filter has the ability to change the size of its output to be different than the size of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_ChangesOutputSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_ChangesOutputSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_ChangesOutputSize"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_ChangesOutputSize",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_changesoutputsize"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DesiredProcessingColorInfo": {
      "abstract": [
        {
          "text": "A key that determines whether your plug-in renders in linear or gamma-corrected color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_DesiredProcessingColorInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DesiredProcessingColorInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_DesiredProcessingColorInfo"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_DesiredProcessingColorInfo",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_desiredprocessingcolorinfo"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_NeedsFullBuffer": {
      "abstract": [
        {
          "text": "A key that determines whether the plug-in needs the entire image to do its processing, and can’t tile its rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_NeedsFullBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_NeedsFullBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_NeedsFullBuffer"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_NeedsFullBuffer",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_needsfullbuffer"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_VariesWhenParamsAreStatic": {
      "abstract": [
        {
          "text": "A key that determines whether your rendering varies even when the parameters remain the same.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_VariesWhenParamsAreStatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_VariesWhenParamsAreStatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_VariesWhenParamsAreStatic"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_VariesWhenParamsAreStatic",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_varieswhenparamsarestatic"
    },
    "https://support.apple.com/guide/final-cut-pro/intro-to-metadata-verc392f8885/mac": {
      "identifier": "https://support.apple.com/guide/final-cut-pro/intro-to-metadata-verc392f8885/mac",
      "title": "Intro to metadata in Final Cut Pro",
      "titleInlineContent": [
        {
          "text": "Intro to metadata in Final Cut Pro",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/final-cut-pro/intro-to-metadata-verc392f8885/mac"
    },
    "https://support.apple.com/guide/final-cut-pro/what-are-libraries-verfdd5c590e/mac": {
      "identifier": "https://support.apple.com/guide/final-cut-pro/what-are-libraries-verfdd5c590e/mac",
      "title": "What are libraries",
      "titleInlineContent": [
        {
          "text": "What are libraries",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/final-cut-pro/what-are-libraries-verfdd5c590e/mac"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Effects",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/create-an-effect-template-for-use-in-final-cut-pro"
      ],
      "title": "Effects"
    },
    {
      "anchor": "XML-Data-Exchange",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/workflow-extensions",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference"
      ],
      "title": "XML Data Exchange"
    },
    {
      "anchor": "Compressor-Encoder-Extensions",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/encoder-extensions"
      ],
      "title": "Compressor Encoder Extensions"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-data-types",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-protocols"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_ChangesOutputSize",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DesiredProcessingColorInfo",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_NeedsFullBuffer",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_VariesWhenParamsAreStatic"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Effects",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/create-an-effect-template-for-use-in-final-cut-pro"
              ],
              "title": "Effects"
            },
            {
              "anchor": "XML-Data-Exchange",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/workflow-extensions",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference"
              ],
              "title": "XML Data Exchange"
            },
            {
              "anchor": "Compressor-Encoder-Extensions",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/encoder-extensions"
              ],
              "title": "Compressor Encoder Extensions"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-data-types",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-protocols"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_ChangesOutputSize",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DesiredProcessingColorInfo",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_NeedsFullBuffer",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_VariesWhenParamsAreStatic"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_VariesWhenParamsAreStatic/title",
          "value": "kFxPropertyKey_VariesWhenParamsAreStatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_VariesWhenParamsAreStatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_VariesWhenParamsAreStatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_ChangesOutputSize/title",
          "value": "kFxPropertyKey_ChangesOutputSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_ChangesOutputSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_ChangesOutputSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_DesiredProcessingColorInfo/title",
          "value": "kFxPropertyKey_DesiredProcessingColorInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_DesiredProcessingColorInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_DesiredProcessingColorInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_NeedsFullBuffer/title",
          "value": "kFxPropertyKey_NeedsFullBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_NeedsFullBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_NeedsFullBuffer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
