{
  "abstract": [
    {
      "text": "Display the system user interface for your app’s Push to Talk services.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pushtotalk/documentation/PushToTalk"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "PushToTalk",
    "modules": [
      {
        "name": "Push to Talk"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Push to Talk"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Push to Talk framework is a power-efficient, user-friendly, and privacy-focused API. It gives your apps the ability to provide user interface controls that allow your users to transmit audio from anywhere. It supplies an ephemeral Apple Push Notification service token so the system can wake your app in the background to handle incoming audio while a session is ongoing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Push to Talk services aren’t available to compatible iPad and iPhone apps running in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk": {
      "abstract": [
        {
          "text": "Display the system user interface for your app’s Push to Talk services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk",
      "kind": "symbol",
      "role": "collection",
      "title": "Push to Talk",
      "type": "topic",
      "url": "/documentation/pushtotalk"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelDescriptor": {
      "abstract": [
        {
          "text": "An object that describes a channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelDescriptor"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelDescriptor"
        }
      ],
      "role": "symbol",
      "title": "PTChannelDescriptor",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneldescriptor"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a channel error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelError"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelError"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for channel operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelErrorDomain": {
      "abstract": [
        {
          "text": "A string representation of the channel error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PTChannelErrorDomain",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerrordomain"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason": {
      "abstract": [
        {
          "text": "Identifies the type that indicates the join reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelJoinReason"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelJoinReason"
        }
      ],
      "role": "symbol",
      "title": "PTChannelJoinReason",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneljoinreason"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelLeaveReason": {
      "abstract": [
        {
          "text": "Identifies the type that indicates the leave reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelLeaveReason"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelLeaveReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelLeaveReason"
        }
      ],
      "role": "symbol",
      "title": "PTChannelLeaveReason",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelleavereason"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManager": {
      "abstract": [
        {
          "text": "An object that represents a push-to-talk channel manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelManager"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelManager"
        }
      ],
      "role": "symbol",
      "title": "PTChannelManager",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelmanager"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManagerDelegate": {
      "abstract": [
        {
          "text": "A type that represents your life cycle of a channel manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelManagerDelegate"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManagerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelManagerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PTChannelManagerDelegate",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelmanagerdelegate"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelRestorationDelegate": {
      "abstract": [
        {
          "text": "A type that represents the channel restoration behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelRestorationDelegate"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelRestorationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelRestorationDelegate"
        }
      ],
      "role": "symbol",
      "title": "PTChannelRestorationDelegate",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelrestorationdelegate"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource": {
      "abstract": [
        {
          "text": "Identifies the type that indicates the transmission request source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelTransmitRequestSource"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelTransmitRequestSource"
        }
      ],
      "role": "symbol",
      "title": "PTChannelTransmitRequestSource",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneltransmitrequestsource"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents an instantiation error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTInstantiationError"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationError"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for instantiation operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationErrorDomain": {
      "abstract": [
        {
          "text": "A string representation of the instantiation error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationErrorDomain",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerrordomain"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTParticipant": {
      "abstract": [
        {
          "text": "An object that represents a participant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTParticipant"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTParticipant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTParticipant"
        }
      ],
      "role": "symbol",
      "title": "PTParticipant",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptparticipant"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTPushResult": {
      "abstract": [
        {
          "text": "An object that represents a push result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTPushResult"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTPushResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTPushResult"
        }
      ],
      "role": "symbol",
      "title": "PTPushResult",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptpushresult"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTServiceStatus": {
      "abstract": [
        {
          "text": "Identifies the type that indicates the status of the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTServiceStatus"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTServiceStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTServiceStatus"
        }
      ],
      "role": "symbol",
      "title": "PTServiceStatus",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptservicestatus"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode": {
      "abstract": [
        {
          "text": "Identifies the type of audio transmission modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTTransmissionMode"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTTransmissionMode"
        }
      ],
      "role": "symbol",
      "title": "PTTransmissionMode",
      "type": "topic",
      "url": "/documentation/pushtotalk/pttransmissionmode"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PT_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PT_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PT_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "PT_EXTERN",
      "type": "topic",
      "url": "/documentation/pushtotalk/pt_extern"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/creating-a-push-to-talk-app": {
      "abstract": [
        {
          "text": "Build a walkie-talkie style app with system user interface controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/creating-a-push-to-talk-app",
      "kind": "article",
      "role": "article",
      "title": "Creating a Push to Talk app",
      "type": "topic",
      "url": "/documentation/pushtotalk/creating-a-push-to-talk-app"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/creating-a-push-to-talk-app",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManager"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Channel-management",
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManagerDelegate",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTServiceStatus",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelLeaveReason",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource"
      ],
      "title": "Channel management"
    },
    {
      "anchor": "Channel-restoration",
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelDescriptor",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelRestorationDelegate"
      ],
      "title": "Channel restoration"
    },
    {
      "anchor": "Channel-participants",
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTParticipant"
      ],
      "title": "Channel participants"
    },
    {
      "anchor": "Push-notification-results",
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTPushResult"
      ],
      "title": "Push notification results"
    },
    {
      "anchor": "Push-to-Talk-errors",
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelErrorDomain",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationErrorDomain"
      ],
      "title": "Push to Talk errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/creating-a-push-to-talk-app",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManager"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Channel-management",
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelManagerDelegate",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTServiceStatus",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelJoinReason",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelLeaveReason",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource"
              ],
              "title": "Channel management"
            },
            {
              "anchor": "Channel-restoration",
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelDescriptor",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelRestorationDelegate"
              ],
              "title": "Channel restoration"
            },
            {
              "anchor": "Channel-participants",
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTParticipant"
              ],
              "title": "Channel participants"
            },
            {
              "anchor": "Push-notification-results",
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTPushResult"
              ],
              "title": "Push notification results"
            },
            {
              "anchor": "Push-to-Talk-errors",
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelErrorDomain",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationErrorDomain"
              ],
              "title": "Push to Talk errors"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PT_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode/title",
          "value": "PTTransmissionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTTransmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTTransmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/title",
          "value": "PTChannelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTParticipant/title",
          "value": "PTParticipant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTParticipant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTParticipant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTParticipant/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTParticipant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelErrorDomain/title",
          "value": "PTChannelErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelManagerDelegate/title",
          "value": "PTChannelManagerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelManagerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelManagerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/title",
          "value": "PTInstantiationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelRestorationDelegate/title",
          "value": "PTChannelRestorationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelRestorationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelRestorationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelRestorationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelRestorationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTServiceStatus/title",
          "value": "PTServiceStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTServiceStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTServiceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTServiceStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTServiceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelLeaveReason/title",
          "value": "PTChannelLeaveReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelLeaveReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelLeaveReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelLeaveReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelLeaveReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelDescriptor/title",
          "value": "PTChannelDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource/title",
          "value": "PTChannelTransmitRequestSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelTransmitRequestSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelTransmitRequestSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelManager/title",
          "value": "PTChannelManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelJoinReason/title",
          "value": "PTChannelJoinReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelJoinReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelJoinReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelJoinReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelJoinReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTPushResult/title",
          "value": "PTPushResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTPushResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTPushResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTPushResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTPushResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationErrorDomain/title",
          "value": "PTInstantiationErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pushtotalk"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pushtotalk"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
