{
  "abstract": [
    {
      "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "Quartz",
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.4",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Quartz"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This collection of documents provides the API reference for the Quartz framework; in particular, for Quartz Composer, ImageKit, and PDFKit. The Quartz Composer API supports  processing and rendering graphical data and allows developers to create custom patches for the Quartz Composer developer tool. ImageKit provides user interface support for browsing, editing, and saving images, showing slideshows, and browsing and previewing Core Image filters. PDFKit is a technology that allows applications to display and manipulate PDF documents.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/Quartz-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/Quartz-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/quartz/quartz-macros"
    },
    "doc://com.apple.quartz/documentation/Quartz/imagekit": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/imagekit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageKit",
      "type": "topic",
      "url": "/documentation/quartz/imagekit"
    },
    "doc://com.apple.quartz/documentation/Quartz/pdfkit": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/pdfkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/quartz/pdfkit"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-composer": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-composer",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Composer",
      "type": "topic",
      "url": "/documentation/quartz/quartz-composer"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Constants",
      "type": "topic",
      "url": "/documentation/quartz/quartz-constants"
    },
    "doc://com.apple.quartz/documentation/Quartz/quartz-filter": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quartz-filter",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quartz Filter",
      "type": "topic",
      "url": "/documentation/quartz/quartz-filter"
    },
    "doc://com.apple.quartz/documentation/Quartz/quick-look": {
      "abstract": [],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/quick-look",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quick Look",
      "type": "topic",
      "url": "/documentation/quartz/quick-look"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageKitProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004907": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageKitProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004907",
      "title": "Image Kit Programming Guide",
      "titleInlineContent": [
        {
          "text": "Image Kit Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageKitProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004907"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/PDFKitGuide/PDFKit_Prog_Intro/PDFKit_Prog_Intro.html#//apple_ref/doc/uid/TP40001863": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/PDFKitGuide/PDFKit_Prog_Intro/PDFKit_Prog_Intro.html#//apple_ref/doc/uid/TP40001863",
      "title": "PDF Kit Programming Guide",
      "titleInlineContent": [
        {
          "text": "PDF Kit Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/PDFKitGuide/PDFKit_Prog_Intro/PDFKit_Prog_Intro.html#//apple_ref/doc/uid/TP40001863"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/QuartzComposer_Patch_PlugIn_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004787": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/QuartzComposer_Patch_PlugIn_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004787",
      "title": "Quartz Composer Custom Patch Programming Guide",
      "titleInlineContent": [
        {
          "text": "Quartz Composer Custom Patch Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/QuartzComposer_Patch_PlugIn_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004787"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/QuartzComposer_Patch_PlugIn_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004787",
        "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/PDFKitGuide/PDFKit_Prog_Intro/PDFKit_Prog_Intro.html#//apple_ref/doc/uid/TP40001863",
        "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageKitProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004907"
      ],
      "title": "Related Documentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Viewing-and-Transforming-Images",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/imagekit"
      ],
      "title": "Viewing and Transforming Images"
    },
    {
      "anchor": "Displaying-PDFs",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/pdfkit"
      ],
      "title": "Displaying PDFs"
    },
    {
      "anchor": "Quartz-Composer",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/quartz-composer"
      ],
      "title": "Quartz Composer"
    },
    {
      "anchor": "Using-Quick-Look",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/quick-look"
      ],
      "title": "Using Quick Look"
    },
    {
      "anchor": "Conversion-Filters",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/quartz-filter"
      ],
      "title": "Conversion Filters"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/quartz-constants"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/Quartz-macros"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Viewing-and-Transforming-Images",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/imagekit"
              ],
              "title": "Viewing and Transforming Images"
            },
            {
              "anchor": "Displaying-PDFs",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/pdfkit"
              ],
              "title": "Displaying PDFs"
            },
            {
              "anchor": "Quartz-Composer",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/quartz-composer"
              ],
              "title": "Quartz Composer"
            },
            {
              "anchor": "Using-Quick-Look",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/quick-look"
              ],
              "title": "Using Quick Look"
            },
            {
              "anchor": "Conversion-Filters",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/quartz-filter"
              ],
              "title": "Conversion Filters"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/quartz-constants"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/Quartz-macros"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/QuartzComposer_Patch_PlugIn_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004787",
                "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/PDFKitGuide/PDFKit_Prog_Intro/PDFKit_Prog_Intro.html#//apple_ref/doc/uid/TP40001863",
                "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageKitProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004907"
              ],
              "title": "Related Documentation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
