{
  "abstract": [
    {
      "text": "Render, compose, and animate visual elements.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "QuartzCore",
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.3",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Core Animation"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Animation provides high frame rates and smooth animations without burdening the CPU or slowing down your app. Core Animation does most of the work of drawing each frame of an animation for you. You’re responsible for configuring the animation parameters, such as the start and end points, and Core Animation does the rest. It accelerates the rendering by handing over most of the work to dedicated graphics hardware. For more details, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Quartz/QCCompositionLayer": {
      "abstract": [
        {
          "text": "A layer that loads, plays, and controls Quartz Composer compositions in a Core Animation layer hierarchy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QCCompositionLayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Quartz/QCCompositionLayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "QCCompositionLayer",
      "type": "topic",
      "url": "/documentation/Quartz/QCCompositionLayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAction": {
      "abstract": [
        {
          "text": "An interface that allows instances to respond to actions triggered by a Core Animation layer change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAction"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAction"
        }
      ],
      "role": "symbol",
      "title": "CAAction",
      "type": "topic",
      "url": "/documentation/quartzcore/caaction"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation": {
      "abstract": [
        {
          "text": "The abstract superclass for animations in Core Animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimation"
        }
      ],
      "role": "symbol",
      "title": "CAAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate": {
      "abstract": [
        {
          "text": "Methods your app can implement to respond when animations start and stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimationDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimationDelegate"
        }
      ],
      "role": "symbol",
      "title": "CAAnimationDelegate",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationdelegate"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationGroup": {
      "abstract": [
        {
          "text": "An object that allows multiple animations to be grouped and run concurrently.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimationGroup"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimationGroup"
        }
      ],
      "role": "symbol",
      "title": "CAAnimationGroup",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationgroup"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation": {
      "abstract": [
        {
          "text": "An object that provides basic, single-keyframe animation capabilities for a layer property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CABasicAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CABasicAnimation"
        }
      ],
      "role": "symbol",
      "title": "CABasicAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/cabasicanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint": {
      "abstract": [
        {
          "text": "A representation of a single layout constraint between two layers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAConstraint"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAConstraint"
        }
      ],
      "role": "symbol",
      "title": "CAConstraint",
      "type": "topic",
      "url": "/documentation/quartzcore/caconstraint"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraintLayoutManager": {
      "abstract": [
        {
          "text": "An object that provides a constraint-based layout manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAConstraintLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraintLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAConstraintLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "CAConstraintLayoutManager",
      "type": "topic",
      "url": "/documentation/quartzcore/caconstraintlayoutmanager"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CACurrentMediaTime()": {
      "abstract": [
        {
          "text": "Returns the current absolute time, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CACurrentMediaTime"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTimeInterval",
          "text": "CFTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CACurrentMediaTime()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CACurrentMediaTime"
        }
      ],
      "role": "symbol",
      "title": "CACurrentMediaTime()",
      "type": "topic",
      "url": "/documentation/quartzcore/cacurrentmediatime()"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CADisplayLink": {
      "abstract": [
        {
          "text": "A timer object that allows your app to synchronize its drawing to the refresh rate of the display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CADisplayLink"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CADisplayLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CADisplayLink"
        }
      ],
      "role": "symbol",
      "title": "CADisplayLink",
      "type": "topic",
      "url": "/documentation/quartzcore/cadisplaylink"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEAGLLayer": {
      "abstract": [
        {
          "text": "A layer that supports drawing OpenGL content in iOS and tvOS applications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEAGLLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEAGLLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEAGLLayer"
        }
      ],
      "role": "symbol",
      "title": "CAEAGLLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/caeagllayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEDRMetadata": {
      "abstract": [
        {
          "text": "Metadata describing how extended dynamic range (EDR) values should be tone mapped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEDRMetadata"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEDRMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEDRMetadata"
        }
      ],
      "role": "symbol",
      "title": "CAEDRMetadata",
      "type": "topic",
      "url": "/documentation/quartzcore/caedrmetadata"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell": {
      "abstract": [
        {
          "text": "The definition of a particle emitted by a particle layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterCell"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterCell"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterCell",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer": {
      "abstract": [
        {
          "text": "A layer that emits, animates, and renders a particle system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayer"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayer": {
      "abstract": [
        {
          "text": "A layer that draws a color gradient over its background color, filling the shape of the layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAGradientLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAGradientLayer"
        }
      ],
      "role": "symbol",
      "title": "CAGradientLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/cagradientlayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation": {
      "abstract": [
        {
          "text": "An object that provides keyframe animation capabilities for a layer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAKeyframeAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAKeyframeAnimation"
        }
      ],
      "role": "symbol",
      "title": "CAKeyframeAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer": {
      "abstract": [
        {
          "text": "An object that manages image-based content and allows you to perform animations on that content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayer"
        }
      ],
      "role": "symbol",
      "title": "CALayer",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerDelegate": {
      "abstract": [
        {
          "text": "Methods your app can implement to respond to layer-related events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerDelegate"
        }
      ],
      "role": "symbol",
      "title": "CALayerDelegate",
      "type": "topic",
      "url": "/documentation/quartzcore/calayerdelegate"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayoutManager": {
      "abstract": [
        {
          "text": "Methods that allow an object to manage the layout of a layer and its sublayers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayoutManager"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayoutManager"
        }
      ],
      "role": "symbol",
      "title": "CALayoutManager",
      "type": "topic",
      "url": "/documentation/quartzcore/calayoutmanager"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming": {
      "abstract": [
        {
          "text": "Methods that model a hierarchical timing system, allowing objects to map time between their parent and local time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTiming",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatiming"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunction": {
      "abstract": [
        {
          "text": "A function that defines the pacing of an animation as a timing curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTimingFunction"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTimingFunction"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTimingFunction",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatimingfunction"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLink": {
      "abstract": [
        {
          "text": "A class your Metal app uses to register for callbacks to synchronize its animations for a display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMetalDisplayLink"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMetalDisplayLink"
        }
      ],
      "role": "symbol",
      "title": "CAMetalDisplayLink",
      "type": "topic",
      "url": "/documentation/quartzcore/cametaldisplaylink"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLink/Update": {
      "abstract": [
        {
          "text": "Stores information about a single update from a Metal display link instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Update"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLink/Update",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Update"
        }
      ],
      "role": "symbol",
      "title": "CAMetalDisplayLink.Update",
      "type": "topic",
      "url": "/documentation/quartzcore/cametaldisplaylink/update"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLinkDelegate": {
      "abstract": [
        {
          "text": "A protocol your app implements to respond to callbacks from Core Animation for a Metal display link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMetalDisplayLinkDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLinkDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMetalDisplayLinkDelegate"
        }
      ],
      "role": "symbol",
      "title": "CAMetalDisplayLinkDelegate",
      "type": "topic",
      "url": "/documentation/quartzcore/cametaldisplaylinkdelegate"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable": {
      "abstract": [
        {
          "text": "A Metal drawable associated with a Core Animation layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMetalDrawable"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMetalDrawable"
        }
      ],
      "role": "symbol",
      "title": "CAMetalDrawable",
      "type": "topic",
      "url": "/documentation/quartzcore/cametaldrawable"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalLayer": {
      "abstract": [
        {
          "text": "A Core Animation layer that Metal can render into, typically displayed onscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMetalLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMetalLayer"
        }
      ],
      "role": "symbol",
      "title": "CAMetalLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/cametallayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAOpenGLLayer": {
      "abstract": [
        {
          "text": "A layer that provides a layer suitable for rendering OpenGL content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAOpenGLLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAOpenGLLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAOpenGLLayer"
        }
      ],
      "role": "symbol",
      "title": "CAOpenGLLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/caopengllayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation": {
      "abstract": [
        {
          "text": "An abstract subclass for creating animations that manipulate the value of layer properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAPropertyAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAPropertyAnimation"
        }
      ],
      "role": "symbol",
      "title": "CAPropertyAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/capropertyanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CARemoteLayerClient": {
      "abstract": [
        {
          "text": "A legacy class for cross-process rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CARemoteLayerClient"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CARemoteLayerClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CARemoteLayerClient"
        }
      ],
      "role": "symbol",
      "title": "CARemoteLayerClient",
      "type": "topic",
      "url": "/documentation/quartzcore/caremotelayerclient"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CARemoteLayerServer": {
      "abstract": [
        {
          "text": "A legacy class for cross-process rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CARemoteLayerServer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CARemoteLayerServer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CARemoteLayerServer"
        }
      ],
      "role": "symbol",
      "title": "CARemoteLayerServer",
      "type": "topic",
      "url": "/documentation/quartzcore/caremotelayerserver"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CARenderer": {
      "abstract": [
        {
          "text": "A layer that allows an application to render a layer tree into a Core OpenGL context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CARenderer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CARenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CARenderer"
        }
      ],
      "role": "symbol",
      "title": "CARenderer",
      "type": "topic",
      "url": "/documentation/quartzcore/carenderer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAReplicatorLayer": {
      "abstract": [
        {
          "text": "A layer that creates a specified number of sublayer copies with varying geometric, temporal, and color transformations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAReplicatorLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAReplicatorLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAReplicatorLayer"
        }
      ],
      "role": "symbol",
      "title": "CAReplicatorLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/careplicatorlayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayer": {
      "abstract": [
        {
          "text": "A layer that displays scrollable content larger than its own bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAScrollLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAScrollLayer"
        }
      ],
      "role": "symbol",
      "title": "CAScrollLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/cascrolllayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer": {
      "abstract": [
        {
          "text": "A layer that draws a cubic Bezier spline in its coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAShapeLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAShapeLayer"
        }
      ],
      "role": "symbol",
      "title": "CAShapeLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation": {
      "abstract": [
        {
          "text": "An animation that applies a spring-like force to a layer’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CASpringAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CASpringAnimation"
        }
      ],
      "role": "symbol",
      "title": "CASpringAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayer": {
      "abstract": [
        {
          "text": "A layer that provides simple text layout and rendering of plain or attributed strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATextLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATextLayer"
        }
      ],
      "role": "symbol",
      "title": "CATextLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/catextlayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATiledLayer": {
      "abstract": [
        {
          "text": "A layer that provides a way to asynchronously provide tiles of the layer’s content, potentially cached at multiple levels of detail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATiledLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATiledLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATiledLayer"
        }
      ],
      "role": "symbol",
      "title": "CATiledLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/catiledlayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransaction": {
      "abstract": [
        {
          "text": "A mechanism for grouping multiple layer-tree operations into atomic updates to the render tree.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransaction"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransaction"
        }
      ],
      "role": "symbol",
      "title": "CATransaction",
      "type": "topic",
      "url": "/documentation/quartzcore/catransaction"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransformLayer": {
      "abstract": [
        {
          "text": "Objects used to create true 3D layer hierarchies, rather than the flattened hierarchy rendering model used by other layer types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransformLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransformLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransformLayer"
        }
      ],
      "role": "symbol",
      "title": "CATransformLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/catransformlayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition": {
      "abstract": [
        {
          "text": "An object that provides an animated transition between a layer’s states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransition"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransition"
        }
      ],
      "role": "symbol",
      "title": "CATransition",
      "type": "topic",
      "url": "/documentation/quartzcore/catransition"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction": {
      "abstract": [
        {
          "text": "An object that provides a flexible method of defining animated transformations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAValueFunction"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAValueFunction"
        }
      ],
      "role": "symbol",
      "title": "CAValueFunction",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunction"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Constants",
      "type": "topic",
      "url": "/documentation/quartzcore/core-animation-constants"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Data Types",
      "type": "topic",
      "url": "/documentation/quartzcore/core-animation-data-types"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Structures",
      "type": "topic",
      "url": "/documentation/quartzcore/core-animation-structures"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro": {
      "abstract": [
        {
          "text": "Provide custom animated content for ProMotion displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro",
      "kind": "article",
      "role": "article",
      "title": "Optimizing ProMotion refresh rates for iPhone 13 Pro and iPad Pro",
      "type": "topic",
      "url": "/documentation/quartzcore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QuartzCore Functions",
      "type": "topic",
      "url": "/documentation/quartzcore/quartzcore-functions"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/transforms": {
      "abstract": [
        {
          "text": "Define transform matrices to apply affine transformations to layers in Core Animation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/transforms",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transforms",
      "type": "topic",
      "url": "/documentation/quartzcore/transforms"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514",
      "title": "Core Animation Programming Guide",
      "titleInlineContent": [
        {
          "text": "Core Animation Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514"
      ],
      "title": "Related Documentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Layer-Basics",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerDelegate",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayoutManager",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraintLayoutManager",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAction"
      ],
      "title": "Layer Basics"
    },
    {
      "anchor": "Text-Shapes-and-Gradients",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayer"
      ],
      "title": "Text, Shapes, and Gradients"
    },
    {
      "anchor": "Animation",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction"
      ],
      "title": "Animation"
    },
    {
      "anchor": "Animation-Groups",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationGroup",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransaction"
      ],
      "title": "Animation Groups"
    },
    {
      "anchor": "Animation-Timing",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CACurrentMediaTime()",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunction",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CADisplayLink",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLink",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLink/Update",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLinkDelegate"
      ],
      "title": "Animation Timing"
    },
    {
      "anchor": "Particle-Systems",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell"
      ],
      "title": "Particle Systems"
    },
    {
      "anchor": "Advanced-Layer-Options",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATiledLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransformLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAReplicatorLayer"
      ],
      "title": "Advanced Layer Options"
    },
    {
      "anchor": "Metal-and-OpenGL",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEAGLLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEDRMetadata",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAOpenGLLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CARenderer"
      ],
      "title": "Metal and OpenGL"
    },
    {
      "anchor": "ProMotion",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
      ],
      "title": "ProMotion"
    },
    {
      "anchor": "Remote-Display-of-Layer-Content",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CARemoteLayerClient",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CARemoteLayerServer"
      ],
      "title": "Remote Display of Layer Content"
    },
    {
      "anchor": "Transforms",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/transforms"
      ],
      "title": "Transforms"
    },
    {
      "anchor": "Quartz-Composer",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Quartz/QCCompositionLayer"
      ],
      "title": "Quartz Composer"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
        "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants",
        "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions",
        "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Layer-Basics",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerDelegate",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayoutManager",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraintLayoutManager",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAction"
              ],
              "title": "Layer Basics"
            },
            {
              "anchor": "Text-Shapes-and-Gradients",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayer"
              ],
              "title": "Text, Shapes, and Gradients"
            },
            {
              "anchor": "Animation",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction"
              ],
              "title": "Animation"
            },
            {
              "anchor": "Animation-Groups",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationGroup",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransaction"
              ],
              "title": "Animation Groups"
            },
            {
              "anchor": "Animation-Timing",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CACurrentMediaTime()",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunction",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CADisplayLink",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLink",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLink/Update",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDisplayLinkDelegate"
              ],
              "title": "Animation Timing"
            },
            {
              "anchor": "Particle-Systems",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell"
              ],
              "title": "Particle Systems"
            },
            {
              "anchor": "Advanced-Layer-Options",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATiledLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransformLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAReplicatorLayer"
              ],
              "title": "Advanced Layer Options"
            },
            {
              "anchor": "Metal-and-OpenGL",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEAGLLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEDRMetadata",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAOpenGLLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CARenderer"
              ],
              "title": "Metal and OpenGL"
            },
            {
              "anchor": "ProMotion",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
              ],
              "title": "ProMotion"
            },
            {
              "anchor": "Remote-Display-of-Layer-Content",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CARemoteLayerClient",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CARemoteLayerServer"
              ],
              "title": "Remote Display of Layer Content"
            },
            {
              "anchor": "Transforms",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/transforms"
              ],
              "title": "Transforms"
            },
            {
              "anchor": "Quartz-Composer",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Quartz/QCCompositionLayer"
              ],
              "title": "Quartz Composer"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
                "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants",
                "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions",
                "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/title",
          "value": "CAMediaTiming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CABasicAnimation/title",
          "value": "CABasicAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CABasicAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CABasicAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CABasicAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CABasicAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation/title",
          "value": "CASpringAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CASpringAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CASpringAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayoutManager/title",
          "value": "CALayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAReplicatorLayer/title",
          "value": "CAReplicatorLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAReplicatorLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAReplicatorLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAReplicatorLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAReplicatorLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATiledLayer/title",
          "value": "CATiledLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATiledLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATiledLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATiledLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATiledLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerDelegate/title",
          "value": "CALayerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimation/title",
          "value": "CAAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEDRMetadata/title",
          "value": "CAEDRMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEDRMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEDRMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEDRMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEDRMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAOpenGLLayer/title",
          "value": "CAOpenGLLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAOpenGLLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAOpenGLLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayer/title",
          "value": "CAGradientLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAGradientLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAGradientLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARemoteLayerServer/title",
          "value": "CARemoteLayerServer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARemoteLayerServer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CARemoteLayerServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARemoteLayerServer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CARemoteLayerServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CADisplayLink/title",
          "value": "CADisplayLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CADisplayLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CADisplayLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CADisplayLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CADisplayLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDisplayLinkDelegate/title",
          "value": "CAMetalDisplayLinkDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDisplayLinkDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDisplayLinkDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDisplayLinkDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDisplayLinkDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEAGLLayer/title",
          "value": "CAEAGLLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEAGLLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEAGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEAGLLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEAGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer/title",
          "value": "CAEmitterLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Quartz~1QCCompositionLayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QCCompositionLayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CAOpenGLLayer",
              "text": "CAOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer/title",
          "value": "CAShapeLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/title",
          "value": "CATransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACurrentMediaTime()/title",
          "value": "CACurrentMediaTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACurrentMediaTime()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CACurrentMediaTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell/title",
          "value": "CAEmitterCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint/title",
          "value": "CAConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARemoteLayerClient/title",
          "value": "CARemoteLayerClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARemoteLayerClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CARemoteLayerClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARemoteLayerClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CARemoteLayerClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/title",
          "value": "CALayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayer/title",
          "value": "CAScrollLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAScrollLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAScrollLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalLayer/title",
          "value": "CAMetalLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransformLayer/title",
          "value": "CATransformLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransformLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransformLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransformLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransformLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/title",
          "value": "CAValueFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunction/title",
          "value": "CAMediaTimingFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationDelegate/title",
          "value": "CAAnimationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation/title",
          "value": "CAKeyframeAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAKeyframeAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAKeyframeAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDisplayLink~1Update/title",
          "value": "CAMetalDisplayLinkUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDisplayLink~1Update/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDisplayLinkUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDisplayLink~1Update/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDisplayLinkUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARenderer/title",
          "value": "CARenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CARenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CARenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAction/title",
          "value": "CAAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationGroup/title",
          "value": "CAAnimationGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayer/title",
          "value": "CATextLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATextLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATextLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/title",
          "value": "CAPropertyAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAPropertyAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAPropertyAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransaction/title",
          "value": "CATransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransaction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraintLayoutManager/title",
          "value": "CAConstraintLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraintLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAConstraintLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraintLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAConstraintLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDrawable/title",
          "value": "CAMetalDrawable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDrawable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDrawable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDisplayLink/title",
          "value": "CAMetalDisplayLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDisplayLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDisplayLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDisplayLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDisplayLink"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
