{
  "abstract": [
    {
      "text": "Generate thumbnails for common file types and add a Thumbnail Extension to your app to enable others to create thumbnails of your custom files.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "QuickLookThumbnailing",
    "modules": [
      {
        "name": "Quick Look Thumbnailing"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Quick Look Thumbnailing"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You may want to create a miniature representation, or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "thumbnail",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", of a file and its contents to display within your app. The QuickLookThumbnailing framework provides an API to generate thumbnails using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. It can generate thumbnails for common file types, including:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Images",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Live Photos",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Text files",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "PDFs",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Audio and video files",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Augmented reality objects using the usdz file format (iOS and iPadOS only)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Many apps use custom file types to persist their data. Finder and Spotlight on macOS, other features of the operating system, as well as other apps, often display a generic file icon instead of a thumbnail for these files. However, if an installed app implements a Thumbnail Extension that supports the custom file types, the operating system and other apps can leverage the extension to display rich thumbnails of the custom file types through the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Add a Thumbnail Extension to your app to provide rich thumbnails of your custom file types to your users throughout the operating system and third party apps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing": {
      "abstract": [
        {
          "text": "Generate thumbnails for common file types and add a Thumbnail Extension to your app to enable others to create thumbnails of your custom files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look Thumbnailing",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLFileThumbnailRequest": {
      "abstract": [
        {
          "text": "A request to generate a thumbnail for a custom file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLFileThumbnailRequest"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLFileThumbnailRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLFileThumbnailRequest"
        }
      ],
      "role": "symbol",
      "title": "QLFileThumbnailRequest",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlfilethumbnailrequest"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QLT_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLT_DEPRECATED",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlt_deprecated"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QLT_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLT_EXPORT",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlt_export"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_EXTERN_C_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QLT_EXTERN_C_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_EXTERN_C_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLT_EXTERN_C_BEGIN",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlt_extern_c_begin"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_EXTERN_C_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QLT_EXTERN_C_END"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_EXTERN_C_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLT_EXTERN_C_END",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlt_extern_c_end"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_FORMAT_ARG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QLT_FORMAT_ARG"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_FORMAT_ARG",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLT_FORMAT_ARG",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlt_format_arg"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QLT_INLINE"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLT_INLINE",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlt_inline"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_LIKELY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QLT_LIKELY"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_LIKELY",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLT_LIKELY",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlt_likely"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_NOINLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QLT_NOINLINE"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_NOINLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLT_NOINLINE",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlt_noinline"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_PRIVATE_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QLT_PRIVATE_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_PRIVATE_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLT_PRIVATE_EXPORT",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlt_private_export"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_UNLIKELY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QLT_UNLIKELY"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_UNLIKELY",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLT_UNLIKELY",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlt_unlikely"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_WEAK_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QLT_WEAK_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_WEAK_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLT_WEAK_EXPORT",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlt_weak_export"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailError-swift.struct": {
      "abstract": [
        {
          "text": "Error information that might return when you generate a thumbnail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailError"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailError"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailError",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailerror-swift.struct"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes that may be returned when generating a thumbnail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailError.Code",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailerror-swift.struct/code"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailErrorDomain": {
      "abstract": [
        {
          "text": "The error domain of the QuickLookThumbnailing framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailErrorDomain",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailerrordomain"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator": {
      "abstract": [
        {
          "text": "An object that generates thumbnail images based on provided requirements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailGenerator"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailGenerator"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailGenerator",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailProvider": {
      "abstract": [
        {
          "text": "An abstract base class for creating thumbnails of custom file types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailProvider"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailProvider"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailProvider",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailprovider"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailReply": {
      "abstract": [
        {
          "text": "The object that provides a thumbnail for a custom file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailReply"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailReply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailReply"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailReply",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailreply"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation": {
      "abstract": [
        {
          "text": "Information about the thumbnail that the thumbnail generator returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailRepresentation"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailRepresentation"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailRepresentation",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/creating-quick-look-thumbnails-to-preview-files-in-your-app": {
      "abstract": [
        {
          "text": "Generate thumbnails of images, text files, PDFs, audio files, videos, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/creating-quick-look-thumbnails-to-preview-files-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Creating Quick Look Thumbnails to Preview Files in Your App",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/creating-quick-look-thumbnails-to-preview-files-in-your-app"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/providing-thumbnails-of-your-custom-file-types": {
      "abstract": [
        {
          "text": "Implement a Thumbnail Extension to allow the operating system and other apps to display thumbnails of your custom files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/providing-thumbnails-of-your-custom-file-types",
      "kind": "article",
      "role": "article",
      "title": "Providing Thumbnails of Your Custom File Types",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/providing-thumbnails-of-your-custom-file-types"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Thumbnail-Generation",
      "identifiers": [
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/creating-quick-look-thumbnails-to-preview-files-in-your-app",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation"
      ],
      "title": "Thumbnail Generation"
    },
    {
      "anchor": "Thumbnails-for-Custom-File-Types",
      "identifiers": [
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/providing-thumbnails-of-your-custom-file-types",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailProvider",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLFileThumbnailRequest",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailReply"
      ],
      "title": "Thumbnails for Custom File Types"
    },
    {
      "anchor": "Error-Information",
      "identifiers": [
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailErrorDomain",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailError-swift.struct",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailError-swift.struct/Code"
      ],
      "title": "Error Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Thumbnail-Generation",
              "identifiers": [
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/creating-quick-look-thumbnails-to-preview-files-in-your-app",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation"
              ],
              "title": "Thumbnail Generation"
            },
            {
              "anchor": "Thumbnails-for-Custom-File-Types",
              "identifiers": [
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/providing-thumbnails-of-your-custom-file-types",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailProvider",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLFileThumbnailRequest",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailReply"
              ],
              "title": "Thumbnails for Custom File Types"
            },
            {
              "anchor": "Error-Information",
              "identifiers": [
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailErrorDomain",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailError-swift.struct/Code"
              ],
              "title": "Error Information"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_DEPRECATED",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_EXPORT",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_EXTERN_C_BEGIN",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_EXTERN_C_END",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_FORMAT_ARG",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_INLINE",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_LIKELY",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_NOINLINE",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_PRIVATE_EXPORT",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_UNLIKELY",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLT_WEAK_EXPORT"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailErrorDomain/title",
          "value": "QLThumbnailErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailError-swift.struct~1Code/title",
          "value": "QLThumbnailError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailProvider/title",
          "value": "QLThumbnailProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLFileThumbnailRequest/title",
          "value": "QLFileThumbnailRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLFileThumbnailRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLFileThumbnailRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLFileThumbnailRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLFileThumbnailRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailReply/title",
          "value": "QLThumbnailReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailReply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailReply/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation/title",
          "value": "QLThumbnailRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator/title",
          "value": "QLThumbnailGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklookthumbnailing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklookthumbnailing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
