{
  "abstract": [
    {
      "text": "Record or stream video from the screen, and audio from the app and microphone.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.replaykit/documentation/ReplayKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ReplayKit",
    "modules": [
      {
        "name": "ReplayKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "ReplayKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Using the ReplayKit framework, users can record video from the screen, and audio from the app and microphone. They can then share their recordings with other users through email, messages, and social media. You can build app extensions for live broadcasting your content to sharing services. ReplayKit is incompatible with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer": {
      "abstract": [
        {
          "text": "An object that provides the interface to control the player’s transport behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayer",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit": {
      "abstract": [
        {
          "text": "Record or stream video from the screen, and audio from the app and microphone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ReplayKit",
      "type": "topic",
      "url": "/documentation/replaykit"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityController": {
      "abstract": [
        {
          "text": "A controller object that presents the macOS broadcast picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastActivityController"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastActivityController"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastActivityController",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastactivitycontroller"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityControllerDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to implement to respond to selection events from a broadcast activity controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastActivityControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastActivityControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastActivityControllerDelegate",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastactivitycontrollerdelegate"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewController": {
      "abstract": [
        {
          "text": "A view controller that displays a user interface where users choose a broadcast service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastActivityViewController"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastActivityViewController"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastActivityViewController",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastactivityviewcontroller"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastConfiguration": {
      "abstract": [
        {
          "text": "An object used to configure the movie clips produced during a live broadcast.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastConfiguration"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastConfiguration"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastConfiguration",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastconfiguration"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController": {
      "abstract": [
        {
          "text": "An object containing methods for starting and controlling a broadcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastController"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastController"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastController",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastcontroller"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastHandler": {
      "abstract": [
        {
          "text": "An object that sends messages to the broadcasting app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastHandler"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastHandler"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastHandler",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcasthandler"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastMP4ClipHandler": {
      "abstract": [
        {
          "text": "An object that processes MP4 movie clips from ReplayKit.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastMP4ClipHandler"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastMP4ClipHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastMP4ClipHandler"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastMP4ClipHandler",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastmp4cliphandler"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler": {
      "abstract": [
        {
          "text": "An object that processes buffer objects as received from ReplayKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastSampleHandler"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastSampleHandler"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastSampleHandler",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastsamplehandler"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController": {
      "abstract": [
        {
          "text": "An object that displays a user interface where users preview and edit a screen recording that you create with ReplayKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPPreviewViewController"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPPreviewViewController"
        }
      ],
      "role": "symbol",
      "title": "RPPreviewViewController",
      "type": "topic",
      "url": "/documentation/replaykit/rppreviewviewcontroller"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode": {
      "abstract": [
        {
          "text": "The ReplayKit error domain codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPRecordingErrorCode"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorCode"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder": {
      "abstract": [
        {
          "text": "The shared recorder object that provides the ability to record audio and video of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPScreenRecorder"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPScreenRecorder"
        }
      ],
      "role": "symbol",
      "title": "RPScreenRecorder",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPSystemBroadcastPickerView": {
      "abstract": [
        {
          "text": "A view displaying a broadcast button that, when tapped, shows a broadcast picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPSystemBroadcastPickerView"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPSystemBroadcastPickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPSystemBroadcastPickerView"
        }
      ],
      "role": "symbol",
      "title": "RPSystemBroadcastPickerView",
      "type": "topic",
      "url": "/documentation/replaykit/rpsystembroadcastpickerview"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/recording-and-streaming-your-macos-app": {
      "abstract": [
        {
          "text": "Share screen recordings, or broadcast live audio and video of your app, by adding ReplayKit to your macOS apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/recording-and-streaming-your-macos-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Recording and Streaming Your macOS App",
      "type": "topic",
      "url": "/documentation/replaykit/recording-and-streaming-your-macos-app"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/replaykit-constants": {
      "abstract": [
        {
          "text": "ReplayKit constants affecting multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/replaykit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ReplayKit Constants",
      "type": "topic",
      "url": "/documentation/replaykit/replaykit-constants"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/rprecordingerrordomain-5gi": {
      "abstract": [
        {
          "text": "The ReplayKit framework error domain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/rprecordingerrordomain-5gi",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RPRecordingErrorDomain",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrordomain-5gi"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Replay-Sharing",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/recording-and-streaming-your-macos-app",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController"
      ],
      "title": "Replay Sharing"
    },
    {
      "anchor": "Media-Clip-Processing",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastHandler",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastMP4ClipHandler"
      ],
      "title": "Media Clip Processing"
    },
    {
      "anchor": "Live-Broadcast-Implementation",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewController",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPSystemBroadcastPickerView",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityController",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityControllerDelegate",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastConfiguration"
      ],
      "title": "Live Broadcast Implementation"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode",
        "doc://com.apple.replaykit/documentation/ReplayKit/rprecordingerrordomain-5gi"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/replaykit-constants"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Replay-Sharing",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/recording-and-streaming-your-macos-app",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController"
              ],
              "title": "Replay Sharing"
            },
            {
              "anchor": "Media-Clip-Processing",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastHandler",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastMP4ClipHandler"
              ],
              "title": "Media Clip Processing"
            },
            {
              "anchor": "Live-Broadcast-Implementation",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityViewController",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPSystemBroadcastPickerView",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityController",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastActivityControllerDelegate",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastConfiguration"
              ],
              "title": "Live Broadcast Implementation"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode",
                "doc://com.apple.replaykit/documentation/ReplayKit/rprecordingerrordomain-5gi"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/replaykit-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastMP4ClipHandler/title",
          "value": "RPBroadcastMP4ClipHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastMP4ClipHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastMP4ClipHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastMP4ClipHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastMP4ClipHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPPreviewViewController/title",
          "value": "RPPreviewViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPPreviewViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPPreviewViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPPreviewViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPPreviewViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/title",
          "value": "RPScreenRecorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewController/title",
          "value": "RPBroadcastActivityViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode/title",
          "value": "RPRecordingErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityControllerDelegate/title",
          "value": "RPBroadcastActivityControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastConfiguration/title",
          "value": "RPBroadcastConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastHandler/title",
          "value": "RPBroadcastHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPSystemBroadcastPickerView/title",
          "value": "RPSystemBroadcastPickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPSystemBroadcastPickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPSystemBroadcastPickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPSystemBroadcastPickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPSystemBroadcastPickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityController/title",
          "value": "RPBroadcastActivityController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastActivityController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastActivityController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController/title",
          "value": "RPBroadcastController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler/title",
          "value": "RPBroadcastSampleHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastSampleHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastSampleHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/replaykit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/replaykit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
