{
  "abstract": [
    {
      "text": "Enable web views and services in your app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "SafariServices",
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "7.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "7.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.12",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Safari Services"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the Safari Services framework to integrate Safari behaviors into your iOS or macOS app, or to extend the behavior of Safari.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Provide a user interface that is almost identical to the user interface that the Safari app provides. Users can browse the web in this view and then return to your app’s content. This view is more consistent with the Safari user interface than implementing your own custom browsing solution and can be done using fewer lines of code. (iOS)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add items to the user’s Safari Reading List. (iOS)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Convert your existing Chrome, Firefox, or Edge extensions into a Safari web extension, or create a new Safari web extension that can work in other browsers. (iOS and macOS)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Determine from your app whether your content blocker extension is loaded, and if it is, tell it to refresh its contents. (iOS and macOS)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Implement Safari app extensions. Determine from your app whether a Safari app extension is loaded. (macOS)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Allow the user to share cookies and website data between an app and Safari for a single sign-on (SSO) experience with  ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSession": {
      "abstract": [
        {
          "text": "A session that an app uses to authenticate a user through a web service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASWebAuthenticationSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASWebAuthenticationSession",
      "type": "topic",
      "url": "/documentation/AuthenticationServices/ASWebAuthenticationSession"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains": {
      "abstract": [
        {
          "text": "The associated domains for specific services, such as shared web credentials, universal links, and App Clips.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains",
      "kind": "symbol",
      "role": "symbol",
      "title": "Associated Domains Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains"
    },
    "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains": {
      "abstract": [
        {
          "text": "Connect your app and a website to provide both a native app and a browser experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
      "kind": "article",
      "role": "article",
      "title": "Supporting associated domains",
      "type": "topic",
      "url": "/documentation/Xcode/supporting-associated-domains"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFAddToHomeScreenActivityItem": {
      "abstract": [
        {
          "text": "A protocol that describes a bookmark someone can add to their Home Screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAddToHomeScreenActivityItem"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFAddToHomeScreenActivityItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAddToHomeScreenActivityItem"
        }
      ],
      "role": "symbol",
      "title": "SFAddToHomeScreenActivityItem",
      "type": "topic",
      "url": "/documentation/safariservices/sfaddtohomescreenactivityitem"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationSession/CompletionHandler": {
      "abstract": [
        {
          "text": "The completion handler for an authentication session when the user cancels or finishes the login.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationSession/CompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "SFAuthenticationSession.CompletionHandler",
      "type": "topic",
      "url": "/documentation/safariservices/sfauthenticationsession/completionhandler"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFContentBlockerManager": {
      "abstract": [
        {
          "text": "A class that your app uses to interact with a content blocker extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFContentBlockerManager"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFContentBlockerManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFContentBlockerManager"
        }
      ],
      "role": "symbol",
      "title": "SFContentBlockerManager",
      "type": "topic",
      "url": "/documentation/safariservices/sfcontentblockermanager"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFContentBlockerState": {
      "abstract": [
        {
          "text": "The state of a content blocker extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFContentBlockerState"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFContentBlockerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFContentBlockerState"
        }
      ],
      "role": "symbol",
      "title": "SFContentBlockerState",
      "type": "topic",
      "url": "/documentation/safariservices/sfcontentblockerstate"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFError": {
      "abstract": [
        {
          "text": "A content blocker or Safari app extension error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFError"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFError"
        }
      ],
      "role": "symbol",
      "title": "SFError",
      "type": "topic",
      "url": "/documentation/safariservices/sferror"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFError/Code": {
      "abstract": [
        {
          "text": "Messages that describe a content blocker or Safari app extension error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SFError.Code",
      "type": "topic",
      "url": "/documentation/safariservices/sferror/code"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFErrorDomain": {
      "abstract": [
        {
          "text": "The domain for content blocker or Safari app extension errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SFErrorDomain",
      "type": "topic",
      "url": "/documentation/safariservices/sferrordomain"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariApplication": {
      "abstract": [
        {
          "text": "A proxy for the Safari app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariApplication"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariApplication"
        }
      ],
      "role": "symbol",
      "title": "SFSafariApplication",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariapplication"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtension": {
      "abstract": [
        {
          "text": "A proxy for the Safari extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariExtension"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariExtension"
        }
      ],
      "role": "symbol",
      "title": "SFSafariExtension",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextension"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPage": {
      "abstract": [
        {
          "text": "A proxy for a Safari webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariPage"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariPage"
        }
      ],
      "role": "symbol",
      "title": "SFSafariPage",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafaripage"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesAvailable(_:)": {
      "abstract": [
        {
          "text": "Indicates whether a given version of Safari services is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariServicesAvailable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SFSafariServicesVersion",
          "text": "SFSafariServicesVersion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesAvailable(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "SFSafariServicesAvailable(_:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariservicesavailable(_:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion": {
      "abstract": [
        {
          "text": "The version of Safari services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariServicesVersion"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariServicesVersion"
        }
      ],
      "role": "symbol",
      "title": "SFSafariServicesVersion",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariservicesversion"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariTab": {
      "abstract": [
        {
          "text": "A proxy for a tab in a Safari window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariTab"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariTab"
        }
      ],
      "role": "symbol",
      "title": "SFSafariTab",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafaritab"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariViewController": {
      "abstract": [
        {
          "text": "An object that provides a visible standard interface for browsing the web.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariViewController"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariViewController"
        }
      ],
      "role": "symbol",
      "title": "SFSafariViewController",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariviewcontroller"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow": {
      "abstract": [
        {
          "text": "A proxy for a Safari window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariWindow"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariWindow"
        }
      ],
      "role": "symbol",
      "title": "SFSafariWindow",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariwindow"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFUniversalLink": {
      "abstract": [
        {
          "text": "An object that provides browsers with the ability to discover associations between an app and a website.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFUniversalLink"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFUniversalLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFUniversalLink"
        }
      ],
      "role": "symbol",
      "title": "SFUniversalLink",
      "type": "topic",
      "url": "/documentation/safariservices/sfuniversallink"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_AVAILABLE_MAC_SAFARI"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_AVAILABLE_MAC_SAFARI",
      "type": "topic",
      "url": "/documentation/safariservices/sf_available_mac_safari"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_10_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_AVAILABLE_MAC_SAFARI_10_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_10_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_AVAILABLE_MAC_SAFARI_10_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_available_mac_safari_10_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_10_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_AVAILABLE_MAC_SAFARI_10_1"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_10_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_AVAILABLE_MAC_SAFARI_10_1",
      "type": "topic",
      "url": "/documentation/safariservices/sf_available_mac_safari_10_1"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_11_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_AVAILABLE_MAC_SAFARI_11_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_11_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_AVAILABLE_MAC_SAFARI_11_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_available_mac_safari_11_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_11_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_AVAILABLE_MAC_SAFARI_11_1"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_11_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_AVAILABLE_MAC_SAFARI_11_1",
      "type": "topic",
      "url": "/documentation/safariservices/sf_available_mac_safari_11_1"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_12_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_AVAILABLE_MAC_SAFARI_12_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_12_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_AVAILABLE_MAC_SAFARI_12_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_available_mac_safari_12_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_12_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_AVAILABLE_MAC_SAFARI_12_1"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_12_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_AVAILABLE_MAC_SAFARI_12_1",
      "type": "topic",
      "url": "/documentation/safariservices/sf_available_mac_safari_12_1"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_13_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_AVAILABLE_MAC_SAFARI_13_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_13_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_AVAILABLE_MAC_SAFARI_13_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_available_mac_safari_13_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_14_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_AVAILABLE_MAC_SAFARI_14_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_14_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_AVAILABLE_MAC_SAFARI_14_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_available_mac_safari_14_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_17_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_AVAILABLE_MAC_SAFARI_17_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_17_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_AVAILABLE_MAC_SAFARI_17_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_available_mac_safari_17_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_18_4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_AVAILABLE_MAC_SAFARI_18_4"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_18_4",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_AVAILABLE_MAC_SAFARI_18_4",
      "type": "topic",
      "url": "/documentation/safariservices/sf_available_mac_safari_18_4"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_CLASS_AVAILABLE_MAC_SAFARI"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_CLASS_AVAILABLE_MAC_SAFARI",
      "type": "topic",
      "url": "/documentation/safariservices/sf_class_available_mac_safari"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_10_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_CLASS_AVAILABLE_MAC_SAFARI_10_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_10_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_CLASS_AVAILABLE_MAC_SAFARI_10_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_class_available_mac_safari_10_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_10_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_CLASS_AVAILABLE_MAC_SAFARI_10_1"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_10_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_CLASS_AVAILABLE_MAC_SAFARI_10_1",
      "type": "topic",
      "url": "/documentation/safariservices/sf_class_available_mac_safari_10_1"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_11_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_CLASS_AVAILABLE_MAC_SAFARI_11_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_11_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_CLASS_AVAILABLE_MAC_SAFARI_11_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_class_available_mac_safari_11_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_11_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_CLASS_AVAILABLE_MAC_SAFARI_11_1"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_11_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_CLASS_AVAILABLE_MAC_SAFARI_11_1",
      "type": "topic",
      "url": "/documentation/safariservices/sf_class_available_mac_safari_11_1"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_12_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_CLASS_AVAILABLE_MAC_SAFARI_12_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_12_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_CLASS_AVAILABLE_MAC_SAFARI_12_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_class_available_mac_safari_12_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_12_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_CLASS_AVAILABLE_MAC_SAFARI_12_1"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_12_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_CLASS_AVAILABLE_MAC_SAFARI_12_1",
      "type": "topic",
      "url": "/documentation/safariservices/sf_class_available_mac_safari_12_1"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_13_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_CLASS_AVAILABLE_MAC_SAFARI_13_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_13_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_CLASS_AVAILABLE_MAC_SAFARI_13_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_class_available_mac_safari_13_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_14_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_CLASS_AVAILABLE_MAC_SAFARI_14_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_14_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_CLASS_AVAILABLE_MAC_SAFARI_14_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_class_available_mac_safari_14_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_17_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_CLASS_AVAILABLE_MAC_SAFARI_17_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_17_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_CLASS_AVAILABLE_MAC_SAFARI_17_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_class_available_mac_safari_17_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_18_4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_CLASS_AVAILABLE_MAC_SAFARI_18_4"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_18_4",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_CLASS_AVAILABLE_MAC_SAFARI_18_4",
      "type": "topic",
      "url": "/documentation/safariservices/sf_class_available_mac_safari_18_4"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_DEPRECATED_MAC_SAFARI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_DEPRECATED_MAC_SAFARI"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_DEPRECATED_MAC_SAFARI",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_DEPRECATED_MAC_SAFARI",
      "type": "topic",
      "url": "/documentation/safariservices/sf_deprecated_mac_safari"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_DEPRECATED_MAC_SAFARI_10_0_11_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_DEPRECATED_MAC_SAFARI_10_0_11_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_DEPRECATED_MAC_SAFARI_10_0_11_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_DEPRECATED_MAC_SAFARI_10_0_11_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_deprecated_mac_safari_10_0_11_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_ENUM_AVAILABLE_MAC_SAFARI"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_ENUM_AVAILABLE_MAC_SAFARI",
      "type": "topic",
      "url": "/documentation/safariservices/sf_enum_available_mac_safari"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_10_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_ENUM_AVAILABLE_MAC_SAFARI_10_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_10_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_ENUM_AVAILABLE_MAC_SAFARI_10_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_enum_available_mac_safari_10_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_10_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_ENUM_AVAILABLE_MAC_SAFARI_10_1"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_10_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_ENUM_AVAILABLE_MAC_SAFARI_10_1",
      "type": "topic",
      "url": "/documentation/safariservices/sf_enum_available_mac_safari_10_1"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_11_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_ENUM_AVAILABLE_MAC_SAFARI_11_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_11_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_ENUM_AVAILABLE_MAC_SAFARI_11_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_enum_available_mac_safari_11_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_11_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_ENUM_AVAILABLE_MAC_SAFARI_11_1"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_11_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_ENUM_AVAILABLE_MAC_SAFARI_11_1",
      "type": "topic",
      "url": "/documentation/safariservices/sf_enum_available_mac_safari_11_1"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_12_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_ENUM_AVAILABLE_MAC_SAFARI_12_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_12_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_ENUM_AVAILABLE_MAC_SAFARI_12_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_enum_available_mac_safari_12_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_12_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_ENUM_AVAILABLE_MAC_SAFARI_12_1"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_12_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_ENUM_AVAILABLE_MAC_SAFARI_12_1",
      "type": "topic",
      "url": "/documentation/safariservices/sf_enum_available_mac_safari_12_1"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_13_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_ENUM_AVAILABLE_MAC_SAFARI_13_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_13_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_ENUM_AVAILABLE_MAC_SAFARI_13_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_enum_available_mac_safari_13_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_14_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_ENUM_AVAILABLE_MAC_SAFARI_14_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_14_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_ENUM_AVAILABLE_MAC_SAFARI_14_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_enum_available_mac_safari_14_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_17_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_ENUM_AVAILABLE_MAC_SAFARI_17_0"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_17_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_ENUM_AVAILABLE_MAC_SAFARI_17_0",
      "type": "topic",
      "url": "/documentation/safariservices/sf_enum_available_mac_safari_17_0"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_18_4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_ENUM_AVAILABLE_MAC_SAFARI_18_4"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_18_4",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_ENUM_AVAILABLE_MAC_SAFARI_18_4",
      "type": "topic",
      "url": "/documentation/safariservices/sf_enum_available_mac_safari_18_4"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SF_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SF_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_EXTERN",
      "type": "topic",
      "url": "/documentation/safariservices/sf_extern"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SSReadingList": {
      "abstract": [
        {
          "text": "An object for adding items to a user’s Safari Reading List.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSReadingList"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SSReadingList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSReadingList"
        }
      ],
      "role": "symbol",
      "title": "SSReadingList",
      "type": "topic",
      "url": "/documentation/safariservices/ssreadinglist"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListError": {
      "abstract": [
        {
          "text": "A Safari Reading List error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSReadingListError"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSReadingListError"
        }
      ],
      "role": "symbol",
      "title": "SSReadingListError",
      "type": "topic",
      "url": "/documentation/safariservices/ssreadinglisterror"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListError/Code": {
      "abstract": [
        {
          "text": "Messages that describe a Safari Reading List error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SSReadingListError.Code",
      "type": "topic",
      "url": "/documentation/safariservices/ssreadinglisterror/code"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Safari Reading List errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSReadingListErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSReadingListErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SSReadingListErrorDomain",
      "type": "topic",
      "url": "/documentation/safariservices/ssreadinglisterrordomain"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/creating-a-content-blocker": {
      "abstract": [
        {
          "text": "Create a content blocker for Safari in Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/creating-a-content-blocker",
      "kind": "article",
      "role": "article",
      "title": "Creating a content blocker",
      "type": "topic",
      "url": "/documentation/safariservices/creating-a-content-blocker"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated symbols",
      "type": "topic",
      "url": "/documentation/safariservices/deprecated-symbols"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/importing-data-exported-from-safari": {
      "abstract": [
        {
          "text": "Transfer bookmarks, saved passwords, and other information between browsers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/importing-data-exported-from-safari",
      "kind": "article",
      "role": "article",
      "title": "Importing data exported from Safari",
      "type": "topic",
      "url": "/documentation/safariservices/importing-data-exported-from-safari"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extensions": {
      "abstract": [
        {
          "text": "Learn how Safari app extensions extend the web-browsing experience in Safari by leveraging web technologies and native code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Safari app extensions",
      "type": "topic",
      "url": "/documentation/safariservices/safari-app-extensions"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions": {
      "abstract": [
        {
          "text": "Create web extensions that work in Safari and other browsers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Safari web extensions",
      "type": "topic",
      "url": "/documentation/safariservices/safari-web-extensions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Safari-web-extensions",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions"
      ],
      "title": "Safari web extensions"
    },
    {
      "anchor": "Content-blockers",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/creating-a-content-blocker",
        "doc://com.apple.safariservices/documentation/SafariServices/SFContentBlockerManager",
        "doc://com.apple.safariservices/documentation/SafariServices/SFContentBlockerState"
      ],
      "title": "Content blockers"
    },
    {
      "anchor": "Safari-app-extensions",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extensions",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtension",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariApplication",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPage",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariTab"
      ],
      "title": "Safari app extensions"
    },
    {
      "anchor": "Safari-content-in-your-app",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariViewController",
        "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationSession/CompletionHandler",
        "doc://com.apple.safariservices/documentation/SafariServices/importing-data-exported-from-safari"
      ],
      "title": "Safari content in your app"
    },
    {
      "anchor": "Associated-domains",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
        "doc://com.apple.safariservices/documentation/SafariServices/SFUniversalLink",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains"
      ],
      "title": "Associated domains"
    },
    {
      "anchor": "Availability",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesAvailable(_:)",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion"
      ],
      "title": "Availability"
    },
    {
      "anchor": "Safari-Reading-List",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SSReadingList",
        "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListErrorDomain",
        "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListError/Code",
        "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListError"
      ],
      "title": "Safari Reading List"
    },
    {
      "anchor": "Home-Screen-bookmarks",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFAddToHomeScreenActivityItem"
      ],
      "title": "Home Screen bookmarks"
    },
    {
      "anchor": "Miscellaneous-errors",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFError",
        "doc://com.apple.safariservices/documentation/SafariServices/SFError/Code",
        "doc://com.apple.safariservices/documentation/SafariServices/SFErrorDomain"
      ],
      "title": "Miscellaneous errors"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/deprecated-symbols"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Safari-web-extensions",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions"
              ],
              "title": "Safari web extensions"
            },
            {
              "anchor": "Content-blockers",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/creating-a-content-blocker",
                "doc://com.apple.safariservices/documentation/SafariServices/SFContentBlockerManager",
                "doc://com.apple.safariservices/documentation/SafariServices/SFContentBlockerState"
              ],
              "title": "Content blockers"
            },
            {
              "anchor": "Safari-app-extensions",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extensions",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtension",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariApplication",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPage",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariTab"
              ],
              "title": "Safari app extensions"
            },
            {
              "anchor": "Safari-content-in-your-app",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariViewController",
                "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationSession/CompletionHandler",
                "doc://com.apple.safariservices/documentation/SafariServices/importing-data-exported-from-safari"
              ],
              "title": "Safari content in your app"
            },
            {
              "anchor": "Associated-domains",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
                "doc://com.apple.safariservices/documentation/SafariServices/SFUniversalLink",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains"
              ],
              "title": "Associated domains"
            },
            {
              "anchor": "Availability",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariServicesVersion"
              ],
              "title": "Availability"
            },
            {
              "anchor": "Safari-Reading-List",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SSReadingList",
                "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListErrorDomain",
                "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListError/Code"
              ],
              "title": "Safari Reading List"
            },
            {
              "anchor": "Home-Screen-bookmarks",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFAddToHomeScreenActivityItem"
              ],
              "title": "Home Screen bookmarks"
            },
            {
              "anchor": "Miscellaneous-errors",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFError/Code",
                "doc://com.apple.safariservices/documentation/SafariServices/SFErrorDomain"
              ],
              "title": "Miscellaneous errors"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/deprecated-symbols"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_10_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_10_1",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_11_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_11_1",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_12_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_12_1",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_13_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_14_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_17_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_AVAILABLE_MAC_SAFARI_18_4",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_10_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_10_1",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_11_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_11_1",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_12_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_12_1",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_13_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_14_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_17_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_CLASS_AVAILABLE_MAC_SAFARI_18_4",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_DEPRECATED_MAC_SAFARI",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_DEPRECATED_MAC_SAFARI_10_0_11_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_10_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_10_1",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_11_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_11_1",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_12_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_12_1",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_13_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_14_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_17_0",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_ENUM_AVAILABLE_MAC_SAFARI_18_4",
                "doc://com.apple.safariservices/documentation/SafariServices/SF_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingListErrorDomain/title",
          "value": "SSReadingListErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingListErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSReadingListErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion/title",
          "value": "SFSafariServicesVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariServicesVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariServicesVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariServicesVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAuthenticationSession~1CompletionHandler/title",
          "value": "SFAuthenticationCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAuthenticationSession~1CompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthenticationCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAuthenticationSession~1CompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthenticationCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtension/title",
          "value": "SFSafariExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariPage/title",
          "value": "SFSafariPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariPage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingListError~1Code/title",
          "value": "SSReadingListErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingListError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSReadingListErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingListError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSReadingListErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariApplication/title",
          "value": "SFSafariApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFContentBlockerManager/title",
          "value": "SFContentBlockerManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFContentBlockerManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFContentBlockerManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFContentBlockerManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFContentBlockerManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFContentBlockerState/title",
          "value": "SFContentBlockerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFContentBlockerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFContentBlockerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFContentBlockerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFContentBlockerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariTab/title",
          "value": "SFSafariTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariTab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariWindow/title",
          "value": "SFSafariWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFUniversalLink/title",
          "value": "SFUniversalLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFUniversalLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFUniversalLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFUniversalLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFUniversalLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASWebAuthenticationSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASWebAuthenticationSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingList/title",
          "value": "SSReadingList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSReadingList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSReadingList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFError~1Code/title",
          "value": "SFErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAddToHomeScreenActivityItem/title",
          "value": "SFAddToHomeScreenActivityItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAddToHomeScreenActivityItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAddToHomeScreenActivityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAddToHomeScreenActivityItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAddToHomeScreenActivityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFErrorDomain/title",
          "value": "SFErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariViewController/title",
          "value": "SFSafariViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
