{
  "abstract": [
    {
      "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 1"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "SceneKit",
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "8.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.8",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "SceneKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "SceneKit combines a high-performance rendering engine with a descriptive API for import, manipulation, and rendering of 3D assets. Unlike lower-level APIs such as Metal and OpenGL that require you to implement in precise detail the rendering algorithms that display a scene, SceneKit requires only descriptions of your scene’s contents and the actions or animations you want it to perform.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In visionOS, you can display SceneKit content only in 2D views and textures. For information about how to create immersive 3D content, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/visionOS/creating-fully-immersive-experiences",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/visionOS/creating-fully-immersive-experiences": {
      "abstract": [
        {
          "text": "Build fully immersive experiences by combining spaces with content you create using RealityKit or Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/creating-fully-immersive-experiences",
      "kind": "article",
      "role": "article",
      "title": "Creating fully immersive experiences in your app",
      "type": "topic",
      "url": "/documentation/visionOS/creating-fully-immersive-experiences"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNAudioPlayer": {
      "abstract": [
        {
          "text": "A controller for playback of a positional audio source in a SceneKit scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNAudioPlayer"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNAudioPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNAudioPlayer"
        }
      ],
      "role": "symbol",
      "title": "SCNAudioPlayer",
      "type": "topic",
      "url": "/documentation/scenekit/scnaudioplayer"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNAudioSource": {
      "abstract": [
        {
          "text": "A simple, reusable audio source—music or sound effects loaded from a file—for use in positional audio playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNAudioSource"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNAudioSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNAudioSource"
        }
      ],
      "role": "symbol",
      "title": "SCNAudioSource",
      "type": "topic",
      "url": "/documentation/scenekit/scnaudiosource"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNBufferStream": {
      "abstract": [
        {
          "text": "An object that manages a Metal buffer used by a custom shader program.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNBufferStream"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBufferStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNBufferStream"
        }
      ],
      "role": "symbol",
      "title": "SCNBufferStream",
      "type": "topic",
      "url": "/documentation/scenekit/scnbufferstream"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCamera": {
      "abstract": [
        {
          "text": "A set of camera attributes that can be attached to a node to provide a point of view for displaying the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCamera"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCamera"
        }
      ],
      "role": "symbol",
      "title": "SCNCamera",
      "type": "topic",
      "url": "/documentation/scenekit/scncamera"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCullBack": {
      "abstract": [
        {
          "text": "The mode for culling back-facing polygons (and rendering only front-facing polygons).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNCullBack"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCullBack",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNCullBack",
      "type": "topic",
      "url": "/documentation/scenekit/scncullback"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCullFront": {
      "abstract": [
        {
          "text": "The mode for culling front-facing polygons (and rendering only back-facing polygons).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNCullFront"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCullFront",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNCullFront",
      "type": "topic",
      "url": "/documentation/scenekit/scncullfront"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNExportJavaScriptModule(_:)": {
      "abstract": [
        {
          "text": "Makes SceneKit classes and global constants available to the specified JavaScript context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNExportJavaScriptModule"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNExportJavaScriptModule(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNExportJavaScriptModule"
        }
      ],
      "role": "symbol",
      "title": "SCNExportJavaScriptModule(_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnexportjavascriptmodule(_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry": {
      "abstract": [
        {
          "text": "A three-dimensional shape (also called a model or mesh) that can be displayed in a scene, with attached materials that define its appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNGeometry"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNGeometry"
        }
      ],
      "role": "symbol",
      "title": "SCNGeometry",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometry"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometryElement": {
      "abstract": [
        {
          "text": "A container for index data describing how vertices connect to define a three-dimensional object, or geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNGeometryElement"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometryElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNGeometryElement"
        }
      ],
      "role": "symbol",
      "title": "SCNGeometryElement",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometryelement"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource": {
      "abstract": [
        {
          "text": "A container for vertex data forming part of the definition for a three-dimensional object, or geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNGeometrySource"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNGeometrySource"
        }
      ],
      "role": "symbol",
      "title": "SCNGeometrySource",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometrysource"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOption/ignoreLightArea": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignoreLightArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNHitTestOption",
          "text": "SCNHitTestOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOption/ignoreLightArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionIgnoreLightArea"
        }
      ],
      "role": "symbol",
      "title": "ignoreLightArea",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoption/ignorelightarea"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestResult": {
      "abstract": [
        {
          "text": "Information about the result of a scene-space or view-space search for scene elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNHitTestResult"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNHitTestResult"
        }
      ],
      "role": "symbol",
      "title": "SCNHitTestResult",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestresult"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNLayer": {
      "abstract": [
        {
          "text": "A Core Animation layer that renders a SceneKit scene as its content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNLayer"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNLayer"
        }
      ],
      "role": "symbol",
      "title": "SCNLayer",
      "type": "topic",
      "url": "/documentation/scenekit/scnlayer"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNLight": {
      "abstract": [
        {
          "text": "A light source that can be attached to a node to illuminate the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNLight"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNLight"
        }
      ],
      "role": "symbol",
      "title": "SCNLight",
      "type": "topic",
      "url": "/documentation/scenekit/scnlight"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial": {
      "abstract": [
        {
          "text": "A set of shading attributes that define the appearance of a geometry’s surface when rendered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMaterial"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMaterial"
        }
      ],
      "role": "symbol",
      "title": "SCNMaterial",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty": {
      "abstract": [
        {
          "text": "A container for the color or texture of one of a material’s visual properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMaterialProperty"
        }
      ],
      "role": "symbol",
      "title": "SCNMaterialProperty",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterialproperty"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher": {
      "abstract": [
        {
          "text": "An object that manages smooth transitions between a node’s base geometry and one or more target geometries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMorpher"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMorpher"
        }
      ],
      "role": "symbol",
      "title": "SCNMorpher",
      "type": "topic",
      "url": "/documentation/scenekit/scnmorpher"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNNode": {
      "abstract": [
        {
          "text": "A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNNode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNNode"
        }
      ],
      "role": "symbol",
      "title": "SCNNode",
      "type": "topic",
      "url": "/documentation/scenekit/scnnode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNNodeRendererDelegate": {
      "abstract": [
        {
          "text": "Methods you can implement to use your own custom Metal or OpenGL drawing code to render content for a node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNNodeRendererDelegate"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNodeRendererDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNNodeRendererDelegate"
        }
      ],
      "role": "symbol",
      "title": "SCNNodeRendererDelegate",
      "type": "topic",
      "url": "/documentation/scenekit/scnnoderendererdelegate"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController": {
      "abstract": [
        {
          "text": "An animation for a single property of the individual particles rendered by a particle system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNParticlePropertyController"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticlePropertyController"
        }
      ],
      "role": "symbol",
      "title": "SCNParticlePropertyController",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlepropertycontroller"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem": {
      "abstract": [
        {
          "text": "An object that animates and renders a system of small image sprites using a high-level simulation whose general behavior you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNParticleSystem"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleSystem"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleSystem",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNProgram": {
      "abstract": [
        {
          "text": "A complete Metal or OpenGL shader program that replaces SceneKit’s rendering of a geometry or material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNProgram"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNProgram",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNProgram"
        }
      ],
      "role": "symbol",
      "title": "SCNProgram",
      "type": "topic",
      "url": "/documentation/scenekit/scnprogram"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNReferenceNode": {
      "abstract": [
        {
          "text": "A scene graph node that serves as a placeholder for content to be loaded from a separate scene file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNReferenceNode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNReferenceNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNReferenceNode"
        }
      ],
      "role": "symbol",
      "title": "SCNReferenceNode",
      "type": "topic",
      "url": "/documentation/scenekit/scnreferencenode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderer": {
      "abstract": [
        {
          "text": "A renderer for displaying a SceneKit scene in an existing Metal workflow or OpenGL context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNRenderer"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNRenderer"
        }
      ],
      "role": "symbol",
      "title": "SCNRenderer",
      "type": "topic",
      "url": "/documentation/scenekit/scnrenderer"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNScene": {
      "abstract": [
        {
          "text": "A container for the node hierarchy and global properties that together form a displayable 3D scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNScene"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNScene"
        }
      ],
      "role": "symbol",
      "title": "SCNScene",
      "type": "topic",
      "url": "/documentation/scenekit/scnscene"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer": {
      "abstract": [
        {
          "text": "Methods and properties common to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLayer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneRenderer"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneRenderer"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneRenderer",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRendererDelegate": {
      "abstract": [
        {
          "text": "Methods your app can implement to participate in SceneKit’s animation loop or perform additional rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneRendererDelegate"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRendererDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneRendererDelegate"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneRendererDelegate",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerendererdelegate"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource": {
      "abstract": [
        {
          "text": "An object that manages the data-reading tasks associated with loading scene contents from a file or data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneSource"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSource"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSource",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNShadable": {
      "abstract": [
        {
          "text": "Methods for customizing SceneKit’s rendering of geometry and materials using Metal or OpenGL shader programs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNShadable"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNShadable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNShadable"
        }
      ],
      "role": "symbol",
      "title": "SCNShadable",
      "type": "topic",
      "url": "/documentation/scenekit/scnshadable"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner": {
      "abstract": [
        {
          "text": "An object that manages the relationship between skeletal animations and the nodes and geometries they animate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSkinner"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSkinner"
        }
      ],
      "role": "symbol",
      "title": "SCNSkinner",
      "type": "topic",
      "url": "/documentation/scenekit/scnskinner"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique": {
      "abstract": [
        {
          "text": "A specification for augmenting or postprocessing SceneKit’s rendering of a scene using additional drawing passes with custom Metal or OpenGL shaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNTechnique"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNTechnique"
        }
      ],
      "role": "symbol",
      "title": "SCNTechnique",
      "type": "topic",
      "url": "/documentation/scenekit/scntechnique"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTechniqueSupport": {
      "abstract": [
        {
          "text": "The common interface for SceneKit objects that support multipass rendering using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNTechniqueSupport"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTechniqueSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNTechniqueSupport"
        }
      ],
      "role": "symbol",
      "title": "SCNTechniqueSupport",
      "type": "topic",
      "url": "/documentation/scenekit/scntechniquesupport"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNView": {
      "abstract": [
        {
          "text": "A view for displaying 3D SceneKit content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNView"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNView"
        }
      ],
      "role": "symbol",
      "title": "SCNView",
      "type": "topic",
      "url": "/documentation/scenekit/scnview"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SceneKit-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SceneKit-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/scenekit/scenekit-macros"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SceneView": {
      "abstract": [
        {
          "text": "A SwiftUI view for displaying 3D SceneKit content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneView"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SceneView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SceneView"
        }
      ],
      "role": "symbol",
      "title": "SceneView",
      "type": "topic",
      "url": "/documentation/scenekit/sceneview"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/animation": {
      "abstract": [
        {
          "text": "Create declarative animations that move elements of a scene in predetermined ways, or manage animations imported with external authoring tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/animation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation",
      "type": "topic",
      "url": "/documentation/scenekit/animation"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/built-in-geometry-types": {
      "abstract": [
        {
          "text": "Basic shapes—such as spheres, boxes, and planes—and features for generating 3D objects from 2D text and Bézier curves.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/built-in-geometry-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Built-in Geometry Types",
      "type": "topic",
      "url": "/documentation/scenekit/built-in-geometry-types"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/constraints": {
      "abstract": [
        {
          "text": "Automatically adjust the position or orientation of a node based on specified rules.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/constraints",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Constraints",
      "type": "topic",
      "url": "/documentation/scenekit/constraints"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/organizing-a-scene-with-nodes": {
      "abstract": [
        {
          "text": "Use nodes to define the structure of a scene.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/organizing-a-scene-with-nodes",
      "kind": "article",
      "role": "article",
      "title": "Organizing a Scene with Nodes",
      "type": "topic",
      "url": "/documentation/scenekit/organizing-a-scene-with-nodes"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/physics-simulation": {
      "abstract": [
        {
          "text": "Add dynamic behaviors to scene elements; detect contacts and collisions; simulate realistic effects like gravity, springs, and vehicles.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/physics-simulation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Physics Simulation",
      "type": "topic",
      "url": "/documentation/scenekit/physics-simulation"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/postprocessing-a-scene-with-custom-symbols": {
      "abstract": [
        {
          "text": "Create visual effects in a scene by defining a rendering technique with custom symbols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/postprocessing-a-scene-with-custom-symbols",
      "kind": "article",
      "role": "sampleCode",
      "title": "Postprocessing a Scene With Custom Symbols",
      "type": "topic",
      "url": "/documentation/scenekit/postprocessing-a-scene-with-custom-symbols"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/scenekit-3d-data-types": {
      "abstract": [
        {
          "text": "SceneKit-specific vectors, matrices, and related functions and operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/scenekit-3d-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SceneKit 3D Data Types",
      "type": "topic",
      "url": "/documentation/scenekit/scenekit-3d-data-types"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/scenekit-constants": {
      "abstract": [
        {
          "text": "Constants used throughout the SceneKit framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/scenekit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SceneKit Constants",
      "type": "topic",
      "url": "/documentation/scenekit/scenekit-constants"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/scenekit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/scenekit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SceneKit Enumerations",
      "type": "topic",
      "url": "/documentation/scenekit/scenekit-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNScene",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNView"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Scene-Structure",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/organizing-a-scene-with-nodes",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNReferenceNode"
      ],
      "title": "Scene Structure"
    },
    {
      "anchor": "Display-and-Interactivity",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRendererDelegate",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNLayer",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderer",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestResult"
      ],
      "title": "Display and Interactivity"
    },
    {
      "anchor": "Lighting-Cameras-and-Shading",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNLight",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCamera",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty"
      ],
      "title": "Lighting, Cameras, and Shading"
    },
    {
      "anchor": "Geometry",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometryElement",
        "doc://com.apple.scenekit/documentation/SceneKit/built-in-geometry-types"
      ],
      "title": "Geometry"
    },
    {
      "anchor": "Animation-and-Constraints",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/animation",
        "doc://com.apple.scenekit/documentation/SceneKit/constraints",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher"
      ],
      "title": "Animation and Constraints"
    },
    {
      "anchor": "Physics",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/physics-simulation"
      ],
      "title": "Physics"
    },
    {
      "anchor": "Particle-Systems",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController"
      ],
      "title": "Particle Systems"
    },
    {
      "anchor": "Audio",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNAudioSource",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNAudioPlayer"
      ],
      "title": "Audio"
    },
    {
      "anchor": "Renderer-Customization",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNShadable",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNProgram",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNBufferStream",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTechniqueSupport",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNNodeRendererDelegate",
        "doc://com.apple.scenekit/documentation/SceneKit/postprocessing-a-scene-with-custom-symbols"
      ],
      "title": "Renderer Customization"
    },
    {
      "anchor": "Scene-Asset-Import",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource"
      ],
      "title": "Scene Asset Import"
    },
    {
      "anchor": "JavaScript",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNExportJavaScriptModule(_:)"
      ],
      "title": "JavaScript"
    },
    {
      "anchor": "SceneKit-Data-Types",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/scenekit-3d-data-types"
      ],
      "title": "SceneKit Data Types"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SceneKit-macros"
      ],
      "title": "Macros"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/scenekit-enumerations",
        "doc://com.apple.scenekit/documentation/SceneKit/scenekit-constants"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SceneView"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNScene",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNView"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Scene-Structure",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/organizing-a-scene-with-nodes",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNReferenceNode"
              ],
              "title": "Scene Structure"
            },
            {
              "anchor": "Display-and-Interactivity",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRendererDelegate",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNLayer",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderer",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestResult"
              ],
              "title": "Display and Interactivity"
            },
            {
              "anchor": "Lighting-Cameras-and-Shading",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNLight",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCamera",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty"
              ],
              "title": "Lighting, Cameras, and Shading"
            },
            {
              "anchor": "Geometry",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometryElement",
                "doc://com.apple.scenekit/documentation/SceneKit/built-in-geometry-types"
              ],
              "title": "Geometry"
            },
            {
              "anchor": "Animation-and-Constraints",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/animation",
                "doc://com.apple.scenekit/documentation/SceneKit/constraints",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher"
              ],
              "title": "Animation and Constraints"
            },
            {
              "anchor": "Physics",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/physics-simulation"
              ],
              "title": "Physics"
            },
            {
              "anchor": "Particle-Systems",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController"
              ],
              "title": "Particle Systems"
            },
            {
              "anchor": "Audio",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNAudioSource",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNAudioPlayer"
              ],
              "title": "Audio"
            },
            {
              "anchor": "Renderer-Customization",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNShadable",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNProgram",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNBufferStream",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTechniqueSupport",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNNodeRendererDelegate",
                "doc://com.apple.scenekit/documentation/SceneKit/postprocessing-a-scene-with-custom-symbols"
              ],
              "title": "Renderer Customization"
            },
            {
              "anchor": "Scene-Asset-Import",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource"
              ],
              "title": "Scene Asset Import"
            },
            {
              "anchor": "JavaScript",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNExportJavaScriptModule(_:)"
              ],
              "title": "JavaScript"
            },
            {
              "anchor": "SceneKit-Data-Types",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/scenekit-3d-data-types"
              ],
              "title": "SceneKit Data Types"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SceneKit-macros",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCullBack",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCullFront"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/scenekit-enumerations",
                "doc://com.apple.scenekit/documentation/SceneKit/scenekit-constants"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOption/ignoreLightArea"
              ],
              "title": "Variables"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNReferenceNode/title",
          "value": "SCNReferenceNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNReferenceNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNReferenceNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNReferenceNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNReferenceNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene/title",
          "value": "SCNScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechniqueSupport/title",
          "value": "SCNTechniqueSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechniqueSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTechniqueSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechniqueSupport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTechniqueSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticlePropertyController/title",
          "value": "SCNParticlePropertyController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticlePropertyController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticlePropertyController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticlePropertyController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticlePropertyController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem/title",
          "value": "SCNParticleSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometryElement/title",
          "value": "SCNGeometryElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometryElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometryElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometryElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometryElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial/title",
          "value": "SCNMaterial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRendererDelegate/title",
          "value": "SCNSceneRendererDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRendererDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneRendererDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRendererDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneRendererDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title",
          "value": "SCNNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/title",
          "value": "SCNSkinner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSkinner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSkinner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/title",
          "value": "SCNView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/title",
          "value": "SCNSceneSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLight/title",
          "value": "SCNLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAudioPlayer/title",
          "value": "SCNAudioPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAudioPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAudioPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAudioPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAudioPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCamera/title",
          "value": "SCNCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCamera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource/title",
          "value": "SCNGeometrySource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometrySource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometrySource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAudioSource/title",
          "value": "SCNAudioSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAudioSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAudioSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAudioSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAudioSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNProgram/title",
          "value": "SCNProgram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNProgram/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNProgram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNProgram/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNProgram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNExportJavaScriptModule(_:)/title",
          "value": "SCNExportJavaScriptModule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNExportJavaScriptModule(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNExportJavaScriptModule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/title",
          "value": "SCNGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNHitTestResult/title",
          "value": "SCNHitTestResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNHitTestResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNHitTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNHitTestResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNHitTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShadable/title",
          "value": "SCNShadable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShadable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNShadable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShadable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNShadable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMorpher/title",
          "value": "SCNMorpher"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMorpher/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMorpher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMorpher/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMorpher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNodeRendererDelegate/title",
          "value": "SCNNodeRendererDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNodeRendererDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNNodeRendererDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNodeRendererDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNNodeRendererDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer/title",
          "value": "SCNSceneRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBufferStream/title",
          "value": "SCNBufferStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBufferStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBufferStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBufferStream/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBufferStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty/title",
          "value": "SCNMaterialProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMaterialProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMaterialProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderer/title",
          "value": "SCNRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLayer/title",
          "value": "SCNLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique/title",
          "value": "SCNTechnique"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTechnique"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTechnique"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNHitTestOption~1ignoreLightArea/title",
          "value": "SCNHitTestOptionIgnoreLightArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNHitTestOption~1ignoreLightArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNHitTestOptionIgnoreLightArea"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
