{
  "abstract": [
    {
      "text": "Filter and select screen content and stream it to your app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ScreenCaptureKit",
    "modules": [
      {
        "name": "ScreenCaptureKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "12.3",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "ScreenCaptureKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ScreenCaptureKit framework to add support for high-performance frame capture of screen and audio content to your Mac app. The framework gives you fine-grained control to select and stream only the content that you want to capture. As a stream captures new video frames and audio samples, it passes them to your app as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMSampleBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects that contain the media data and its related metadata. ScreenCaptureKit also provides a macOS-integrated picker for streaming selection and management, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPicker",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Session 10156: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc22/10156",
                  "isActive": true,
                  "type": "reference"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Session 10155: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc22/10155",
                  "isActive": true,
                  "type": "reference"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Session 10136: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc2023/10136/",
                  "isActive": true,
                  "type": "reference"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Related Sessions from WWDC22 and WWDC23",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.persistent-content-capture": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a Virtual Network Computing (VNC) app needs persistent access to screen capture.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.persistent-content-capture",
      "kind": "symbol",
      "role": "symbol",
      "title": "Persistent Content Capture",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.persistent-content-capture"
    },
    "doc://com.apple.documentation/documentation/CoreMedia/CMSampleBuffer": {
      "abstract": [
        {
          "text": "A reference to a buffer of media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMSampleBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMSampleBuffer",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMSampleBuffer"
    },
    "doc://com.apple.documentation/documentation/Updates/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Learn about important changes to ScreenCaptureKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/ScreenCaptureKit",
      "kind": "article",
      "role": "article",
      "title": "ScreenCaptureKit updates",
      "type": "topic",
      "url": "/documentation/Updates/ScreenCaptureKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Filter and select screen content and stream it to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ScreenCaptureKit",
      "type": "topic",
      "url": "/documentation/screencapturekit"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter": {
      "abstract": [
        {
          "text": "An instance that filters the content a stream captures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCContentFilter"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentFilter"
        }
      ],
      "role": "symbol",
      "title": "SCContentFilter",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentfilter"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPicker": {
      "abstract": [
        {
          "text": "An instance of a picker presented by the operating system for managing frame-capture streams.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCContentSharingPicker"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentSharingPicker"
        }
      ],
      "role": "symbol",
      "title": "SCContentSharingPicker",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentsharingpicker"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerConfiguration-c.class": {
      "abstract": [
        {
          "text": "An instance for configuring the system content-sharing picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCContentSharingPickerConfiguration",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentsharingpickerconfiguration-c.class"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "An instance for configuring the system content-sharing picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerConfiguration"
        }
      ],
      "role": "symbol",
      "title": "SCContentSharingPickerConfiguration",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentsharingpickerconfiguration-swift.struct"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode": {
      "abstract": [
        {
          "text": "Available modes for selecting streaming content from a picker presented by the operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerMode"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerMode"
        }
      ],
      "role": "symbol",
      "title": "SCContentSharingPickerMode",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentsharingpickermode"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerObserver": {
      "abstract": [
        {
          "text": "An observer protocol your app implements to receive messages from the operating system’s content picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerObserver"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerObserver"
        }
      ],
      "role": "symbol",
      "title": "SCContentSharingPickerObserver",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentsharingpickerobserver"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCDisplay": {
      "abstract": [
        {
          "text": "An instance that represents a display device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCDisplay"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCDisplay"
        }
      ],
      "role": "symbol",
      "title": "SCDisplay",
      "type": "topic",
      "url": "/documentation/screencapturekit/scdisplay"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus": {
      "abstract": [
        {
          "text": "Status values for a frame from a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCFrameStatus"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCFrameStatus"
        }
      ],
      "role": "symbol",
      "title": "SCFrameStatus",
      "type": "topic",
      "url": "/documentation/screencapturekit/scframestatus"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRunningApplication": {
      "abstract": [
        {
          "text": "An instance that represents an app running on a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCRunningApplication"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRunningApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCRunningApplication"
        }
      ],
      "role": "symbol",
      "title": "SCRunningApplication",
      "type": "topic",
      "url": "/documentation/screencapturekit/scrunningapplication"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCScreenshotManager": {
      "abstract": [
        {
          "text": "An instance for the capture of single frames from a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCScreenshotManager"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCScreenshotManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCScreenshotManager"
        }
      ],
      "role": "symbol",
      "title": "SCScreenshotManager",
      "type": "topic",
      "url": "/documentation/screencapturekit/scscreenshotmanager"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContent": {
      "abstract": [
        {
          "text": "An instance that represents a set of displays, apps, and windows that your app can capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCShareableContent"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCShareableContent"
        }
      ],
      "role": "symbol",
      "title": "SCShareableContent",
      "type": "topic",
      "url": "/documentation/screencapturekit/scshareablecontent"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContentInfo": {
      "abstract": [
        {
          "text": "An instance that provides information for the content in a given stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCShareableContentInfo"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContentInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCShareableContentInfo"
        }
      ],
      "role": "symbol",
      "title": "SCShareableContentInfo",
      "type": "topic",
      "url": "/documentation/screencapturekit/scshareablecontentinfo"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContentStyle": {
      "abstract": [
        {
          "text": "The style of content presented in a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCShareableContentStyle"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContentStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCShareableContentStyle"
        }
      ],
      "role": "symbol",
      "title": "SCShareableContentStyle",
      "type": "topic",
      "url": "/documentation/screencapturekit/scshareablecontentstyle"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream": {
      "abstract": [
        {
          "text": "An instance that represents a stream of shareable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStream"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStream"
        }
      ],
      "role": "symbol",
      "title": "SCStream",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamConfiguration": {
      "abstract": [
        {
          "text": "An instance that provides the output configuration for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamConfiguration"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "SCStreamConfiguration",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamconfiguration"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamDelegate": {
      "abstract": [
        {
          "text": "A delegate protocol your app implements to respond to stream events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamDelegate"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamDelegate"
        }
      ],
      "role": "symbol",
      "title": "SCStreamDelegate",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamdelegate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError": {
      "abstract": [
        {
          "text": "An instance representing a ScreenCaptureKit framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamError"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamError"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code": {
      "abstract": [
        {
          "text": "Codes for user cancellation events and errors that can occur in ScreenCaptureKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamErrorDomain": {
      "abstract": [
        {
          "text": "A string representation of the error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SCStreamErrorDomain",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerrordomain"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamFrameInfo": {
      "abstract": [
        {
          "text": "An instance that defines metadata keys for a stream frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamFrameInfo"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamFrameInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamFrameInfo"
        }
      ],
      "role": "symbol",
      "title": "SCStreamFrameInfo",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamframeinfo"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamOutput": {
      "abstract": [
        {
          "text": "A delegate protocol your app implements to receive capture stream output events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamOutput"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamOutput"
        }
      ],
      "role": "symbol",
      "title": "SCStreamOutput",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamoutput"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamOutputType": {
      "abstract": [
        {
          "text": "Constants that represent output types for a stream frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamOutputType"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamOutputType"
        }
      ],
      "role": "symbol",
      "title": "SCStreamOutputType",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamoutputtype"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCWindow": {
      "abstract": [
        {
          "text": "An instance that represents an onscreen window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCWindow"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCWindow"
        }
      ],
      "role": "symbol",
      "title": "SCWindow",
      "type": "topic",
      "url": "/documentation/screencapturekit/scwindow"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/capturing-screen-content-in-macos": {
      "abstract": [
        {
          "text": "Stream desktop content like displays, apps, and windows by adopting screen capture in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/capturing-screen-content-in-macos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Capturing screen content in macOS",
      "type": "topic",
      "url": "/documentation/screencapturekit/capturing-screen-content-in-macos"
    },
    "https://developer.apple.com/videos/play/wwdc2023/10136/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2023/10136/",
      "title": "What’s new in ScreenCaptureKit",
      "titleInlineContent": [
        {
          "text": "What’s new in ScreenCaptureKit",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10136/"
    },
    "https://developer.apple.com/wwdc22/10155": {
      "identifier": "https://developer.apple.com/wwdc22/10155",
      "title": "Take ScreenCaptureKit to the next level",
      "titleInlineContent": [
        {
          "text": "Take ScreenCaptureKit to the next level",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc22/10155"
    },
    "https://developer.apple.com/wwdc22/10156": {
      "identifier": "https://developer.apple.com/wwdc22/10156",
      "title": "Meet ScreenCaptureKit",
      "titleInlineContent": [
        {
          "text": "Meet ScreenCaptureKit",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc22/10156"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Updates/ScreenCaptureKit",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.persistent-content-capture",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/capturing-screen-content-in-macos"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Shareable-content",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContent",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContentInfo",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContentStyle",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCDisplay",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRunningApplication",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCWindow"
      ],
      "title": "Shareable content"
    },
    {
      "anchor": "Content-capture",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamConfiguration",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamDelegate",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCScreenshotManager"
      ],
      "title": "Content capture"
    },
    {
      "anchor": "Output-processing",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamOutput",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamOutputType",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamFrameInfo",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus"
      ],
      "title": "Output processing"
    },
    {
      "anchor": "System-content-sharing-picker",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPicker",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerConfiguration-swift.struct",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerObserver"
      ],
      "title": "System content-sharing picker"
    },
    {
      "anchor": "Stream-errors",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamErrorDomain",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError"
      ],
      "title": "Stream errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Updates/ScreenCaptureKit",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.persistent-content-capture",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/capturing-screen-content-in-macos"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Shareable-content",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContent",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContentInfo",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCShareableContentStyle",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCDisplay",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRunningApplication",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCWindow"
              ],
              "title": "Shareable content"
            },
            {
              "anchor": "Content-capture",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamConfiguration",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamDelegate",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCScreenshotManager"
              ],
              "title": "Content capture"
            },
            {
              "anchor": "Output-processing",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamOutput",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamOutputType",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamFrameInfo",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus"
              ],
              "title": "Output processing"
            },
            {
              "anchor": "System-content-sharing-picker",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPicker",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerConfiguration-c.class",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerObserver"
              ],
              "title": "System content-sharing picker"
            },
            {
              "anchor": "Stream-errors",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamErrorDomain",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code"
              ],
              "title": "Stream errors"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCWindow/title",
          "value": "SCWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode/title",
          "value": "SCContentSharingPickerMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamOutputType/title",
          "value": "SCStreamOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamOutputType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCDisplay/title",
          "value": "SCDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCDisplay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentFilter/title",
          "value": "SCContentFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerObserver/title",
          "value": "SCContentSharingPickerObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/title",
          "value": "SCStreamErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamDelegate/title",
          "value": "SCStreamDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCScreenshotManager/title",
          "value": "SCScreenshotManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCScreenshotManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCScreenshotManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCScreenshotManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCScreenshotManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMSampleBuffer/title",
          "value": "CMSampleBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMSampleBuffer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@opaqueCMSampleBuffer",
              "text": "opaqueCMSampleBuffer"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamConfiguration/title",
          "value": "SCStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream/title",
          "value": "SCStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamErrorDomain/title",
          "value": "SCStreamErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCShareableContentStyle/title",
          "value": "SCShareableContentStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCShareableContentStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCShareableContentStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCShareableContentStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCShareableContentStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCShareableContent/title",
          "value": "SCShareableContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCShareableContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCShareableContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCShareableContent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCShareableContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamOutput/title",
          "value": "SCStreamOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPicker/title",
          "value": "SCContentSharingPicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus/title",
          "value": "SCFrameStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCFrameStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCFrameStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRunningApplication/title",
          "value": "SCRunningApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRunningApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRunningApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRunningApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRunningApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCShareableContentInfo/title",
          "value": "SCShareableContentInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCShareableContentInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCShareableContentInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCShareableContentInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCShareableContentInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamFrameInfo/title",
          "value": "SCStreamFrameInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamFrameInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamFrameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamFrameInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamFrameInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screencapturekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screencapturekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
