{
  "abstract": [
    {
      "text": "Share and manage web-usage data, and observe changes made by a parent or guardian.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Screen-Time/documentation/ScreenTime"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ScreenTime",
    "modules": [
      {
        "name": "Screen Time"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Screen Time"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Screen Time framework gives you the tools you need to help parents and guardians",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "supervise their children’s web usage. Use this framework to:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Report web-usage data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Delete history.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Take action when a parent or guardian blocks a URL or begins enforcing child restrictions.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "In a compatible iPad or iPhone app running in visionOS, the APIs of this framework do nothing.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Screen-Time/documentation/ScreenTime": {
      "abstract": [
        {
          "text": "Share and manage web-usage data, and observe changes made by a parent or guardian.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime",
      "kind": "symbol",
      "role": "collection",
      "title": "Screen Time",
      "type": "topic",
      "url": "/documentation/screentime"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfiguration": {
      "abstract": [
        {
          "text": "The configuration for this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "STScreenTimeConfiguration"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "STScreenTimeConfiguration"
        }
      ],
      "role": "symbol",
      "title": "STScreenTimeConfiguration",
      "type": "topic",
      "url": "/documentation/screentime/stscreentimeconfiguration"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfigurationObserver": {
      "abstract": [
        {
          "text": "The object you use to observe changes to the current configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "STScreenTimeConfigurationObserver"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfigurationObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "STScreenTimeConfigurationObserver"
        }
      ],
      "role": "symbol",
      "title": "STScreenTimeConfigurationObserver",
      "type": "topic",
      "url": "/documentation/screentime/stscreentimeconfigurationobserver"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory": {
      "abstract": [
        {
          "text": "The object you use to delete web-usage data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "STWebHistory"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "STWebHistory"
        }
      ],
      "role": "symbol",
      "title": "STWebHistory",
      "type": "topic",
      "url": "/documentation/screentime/stwebhistory"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier": {
      "abstract": [
        {
          "text": "An identifier representing a web history profile.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProfileIdentifier"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProfileIdentifier"
        }
      ],
      "role": "symbol",
      "title": "STWebHistory.ProfileIdentifier",
      "type": "topic",
      "url": "/documentation/screentime/stwebhistory/profileidentifier"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebpageController": {
      "abstract": [
        {
          "text": "The controller you use to report web usage and block restricted webpages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "STWebpageController"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebpageController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "STWebpageController"
        }
      ],
      "role": "symbol",
      "title": "STWebpageController",
      "type": "topic",
      "url": "/documentation/screentime/stwebpagecontroller"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebpageController"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Configuration-queries",
      "identifiers": [
        "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfigurationObserver",
        "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfiguration"
      ],
      "title": "Configuration queries"
    },
    {
      "anchor": "Web-Usage-data-deletion",
      "identifiers": [
        "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory"
      ],
      "title": "Web-Usage data deletion"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebpageController"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Configuration-queries",
              "identifiers": [
                "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfigurationObserver",
                "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfiguration"
              ],
              "title": "Configuration queries"
            },
            {
              "anchor": "Web-Usage-data-deletion",
              "identifiers": [
                "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory"
              ],
              "title": "Web-Usage data deletion"
            },
            {
              "anchor": "Type-Aliases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebpageController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebpageController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebpageController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebpageController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory~1ProfileIdentifier/title",
          "value": "STWebHistoryProfileIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory~1ProfileIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistoryProfileIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory~1ProfileIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistoryProfileIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfiguration/title",
          "value": "STScreenTimeConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "STScreenTimeConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "STScreenTimeConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfigurationObserver/title",
          "value": "STScreenTimeConfigurationObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfigurationObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "STScreenTimeConfigurationObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfigurationObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "STScreenTimeConfigurationObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory/title",
          "value": "STWebHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screentime"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screentime"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
