{
  "abstract": [
    {
      "text": "Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.securityinterface/documentation/SecurityInterface"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "SecurityInterface",
    "modules": [
      {
        "name": "Security Interface"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.3",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Security Interface"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This document was previously titled ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "Security Objective-C API",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ". The documentation for the SFAuthorization class is now in a separate document, ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/SecurityFoundation",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The Security Interface framework is a set of Objective-C classes that provide user interface elements for programs that implement security features such as authorization, access to digital certificates, and access to items in keychains.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/SecurityFoundation": {
      "abstract": [
        {
          "text": "Restrict a user’s access to particular features in your Mac app or daemon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SecurityFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Foundation",
      "type": "topic",
      "url": "/documentation/SecurityFoundation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface": {
      "abstract": [
        {
          "text": "Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Interface",
      "type": "topic",
      "url": "/documentation/securityinterface"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView": {
      "abstract": [
        {
          "text": "Allows authorization plug-in developers to create a custom view their plug-in can display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthorizationPluginView"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthorizationPluginView"
        }
      ],
      "role": "symbol",
      "title": "SFAuthorizationPluginView",
      "type": "topic",
      "url": "/documentation/securityinterface/sfauthorizationpluginview"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView": {
      "abstract": [
        {
          "text": "The class responsible for displaying a lock icon that can be used to indicate that a user interface has restricted access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthorizationView"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthorizationView"
        }
      ],
      "role": "symbol",
      "title": "SFAuthorizationView",
      "type": "topic",
      "url": "/documentation/securityinterface/sfauthorizationview"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationViewState": {
      "abstract": [
        {
          "text": "Defines the current state of the authorization view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthorizationViewState"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationViewState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthorizationViewState"
        }
      ],
      "role": "symbol",
      "title": "SFAuthorizationViewState",
      "type": "topic",
      "url": "/documentation/securityinterface/sfauthorizationviewstate"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType": {
      "abstract": [
        {
          "text": "These constants define the button types used by authorization plug-ins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFButtonType"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFButtonType"
        }
      ],
      "role": "symbol",
      "title": "SFButtonType",
      "type": "topic",
      "url": "/documentation/securityinterface/sfbuttontype"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificatePanel": {
      "abstract": [
        {
          "text": "A panel or sheet that displays one or more certificates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFCertificatePanel"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificatePanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFCertificatePanel"
        }
      ],
      "role": "symbol",
      "title": "SFCertificatePanel",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificatepanel"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel": {
      "abstract": [
        {
          "text": "A panel or sheet that lets the user edit the trust settings in any of the certificates in a certificate chain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFCertificateTrustPanel"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFCertificateTrustPanel"
        }
      ],
      "role": "symbol",
      "title": "SFCertificateTrustPanel",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificatetrustpanel"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView": {
      "abstract": [
        {
          "text": "A view that displays the contents of a certificate, with options to display certificate details, display trust settings, and allow users to edit a certificate’s trust settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFCertificateView"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFCertificateView"
        }
      ],
      "role": "symbol",
      "title": "SFCertificateView",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificateview"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFChooseIdentityPanel": {
      "abstract": [
        {
          "text": "A panel or sheet containing a list of identities that a user can choose from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFChooseIdentityPanel"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFChooseIdentityPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFChooseIdentityPanel"
        }
      ],
      "role": "symbol",
      "title": "SFChooseIdentityPanel",
      "type": "topic",
      "url": "/documentation/securityinterface/sfchooseidentitypanel"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFChooseIdentityTableCellView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFChooseIdentityTableCellView"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFChooseIdentityTableCellView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFChooseIdentityTableCellView"
        }
      ],
      "role": "symbol",
      "title": "SFChooseIdentityTableCellView",
      "type": "topic",
      "url": "/documentation/securityinterface/sfchooseidentitytablecellview"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSavePanel": {
      "abstract": [
        {
          "text": "A panel or sheet that allows the user to create a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFKeychainSavePanel"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSavePanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFKeychainSavePanel"
        }
      ],
      "role": "symbol",
      "title": "SFKeychainSavePanel",
      "type": "topic",
      "url": "/documentation/securityinterface/sfkeychainsavepanel"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel": {
      "abstract": [
        {
          "text": "A panel or sheet that allows users to change their keychain settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFKeychainSettingsPanel"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFKeychainSettingsPanel"
        }
      ],
      "role": "symbol",
      "title": "SFKeychainSettingsPanel",
      "type": "topic",
      "url": "/documentation/securityinterface/sfkeychainsettingspanel"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType": {
      "abstract": [
        {
          "text": "These constants define the view type requested by the authorization plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFViewType"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFViewType"
        }
      ],
      "role": "symbol",
      "title": "SFViewType",
      "type": "topic",
      "url": "/documentation/securityinterface/sfviewtype"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-constants": {
      "abstract": [
        {
          "text": "Constants in the SecurityInterface framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SecurityInterface Constants",
      "type": "topic",
      "url": "/documentation/securityinterface/securityinterface-constants"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-data-types": {
      "abstract": [
        {
          "text": "Data types found in the Security Interface framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SecurityInterface Data Types",
      "type": "topic",
      "url": "/documentation/securityinterface/securityinterface-data-types"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SecurityInterface Enumerations",
      "type": "topic",
      "url": "/documentation/securityinterface/securityinterface-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificatePanel",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFChooseIdentityPanel",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFChooseIdentityTableCellView",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSavePanel",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationViewState",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-constants",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-data-types",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificatePanel",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFChooseIdentityPanel",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFChooseIdentityTableCellView",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSavePanel",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFKeychainSettingsPanel"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationViewState",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-constants",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-data-types",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView/title",
          "value": "SFAuthorizationPluginView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationPluginView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationPluginView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFKeychainSavePanel/title",
          "value": "SFKeychainSavePanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFKeychainSavePanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFKeychainSavePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFKeychainSavePanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFKeychainSavePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFKeychainSettingsPanel/title",
          "value": "SFKeychainSettingsPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFKeychainSettingsPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFKeychainSettingsPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFKeychainSettingsPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFKeychainSettingsPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFChooseIdentityPanel/title",
          "value": "SFChooseIdentityPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFChooseIdentityPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFChooseIdentityPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFChooseIdentityPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFChooseIdentityPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFViewType/title",
          "value": "SFViewType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFViewType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFViewType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFViewType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFViewType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificatePanel/title",
          "value": "SFCertificatePanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificatePanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFCertificatePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificatePanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFCertificatePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFChooseIdentityTableCellView/title",
          "value": "SFChooseIdentityTableCellView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFChooseIdentityTableCellView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFChooseIdentityTableCellView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFChooseIdentityTableCellView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFChooseIdentityTableCellView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView/title",
          "value": "SFAuthorizationView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationViewState/title",
          "value": "SFAuthorizationViewState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationViewState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationViewState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationViewState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationViewState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/title",
          "value": "SFButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateTrustPanel/title",
          "value": "SFCertificateTrustPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateTrustPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFCertificateTrustPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateTrustPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFCertificateTrustPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView/title",
          "value": "SFCertificateView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFCertificateView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFCertificateView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityinterface"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/securityinterface"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
