{
  "abstract": [
    {
      "text": "Restrict a user’s access to particular features in your Mac app or daemon.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.securityfoundation/documentation/SecurityFoundation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "SecurityFoundation",
    "modules": [
      {
        "name": "Security Foundation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.3",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Security Foundation"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This document was previously titled ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Authorization Services Objective-C Reference,",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " and it replaced the ",
              "type": "text"
            },
            {
              "code": "SFAuthorization",
              "type": "codeVoice"
            },
            {
              "text": " chapter of the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Security Objective-C API",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " document. The other chapters of that document have been replaced by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SecurityInterface",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Security Foundation framework contains a single class, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which allows you to restrict a user’s access to particular features in your Mac app or daemon.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/SecurityInterface": {
      "abstract": [
        {
          "text": "Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SecurityInterface",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Interface",
      "type": "topic",
      "url": "/documentation/SecurityInterface"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation": {
      "abstract": [
        {
          "text": "Restrict a user’s access to particular features in your Mac app or daemon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Foundation",
      "type": "topic",
      "url": "/documentation/securityfoundation"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization": {
      "abstract": [
        {
          "text": "A class that allows you to restrict a user’s access to particular features in your Mac app or daemon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthorization"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthorization"
        }
      ],
      "role": "symbol",
      "title": "SFAuthorization",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SF_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SF_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SF_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "SF_EXTERN",
      "type": "topic",
      "url": "/documentation/securityfoundation/sf_extern"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization"
      ],
      "title": "Classes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SF_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/title",
          "value": "SFAuthorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorization"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityfoundation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/securityfoundation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
