{
  "abstract": [
    {
      "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "SensorKit",
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iPadOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "SensorKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "As the system gathers information using various sensors on a device, SensorKit enables an app to access select raw data, or metrics that the system processes from a sensor, such as:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Steps information",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Accelerometer or rotation-rate data",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The configuration of a watch on the user’s wrist",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Ambient light in the physical environment",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Details about a user’s routine commute or travel",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the complete list.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This framework ignores calls from Mac apps that you build with Mac Catalyst, and from compatible iPad and iPhone apps running in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.sensorkit.reader.allow": {
      "abstract": [
        {
          "text": "The necessary entitlement to access sensor data that’s required by your app’s preapproved research study.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.sensorkit.reader.allow",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.sensorkit.reader.allow",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.sensorkit.reader.allow"
    },
    "doc://com.apple.documentation/documentation/Updates/SensorKit": {
      "abstract": [
        {
          "text": "Learn about important changes to SensorKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/SensorKit",
      "kind": "article",
      "role": "article",
      "title": "SensorKit updates",
      "type": "topic",
      "url": "/documentation/Updates/SensorKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample": {
      "abstract": [
        {
          "text": "The amount of ambient light in the user’s environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRAmbientLightSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSample"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeletionRecord": {
      "abstract": [
        {
          "text": "An object that describes the reason the framework deletes samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRDeletionRecord"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeletionRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeletionRecord"
        }
      ],
      "role": "symbol",
      "title": "SRDeletionRecord",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeletionrecord"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport": {
      "abstract": [
        {
          "text": "The frequency and relative duration that the user uses their device, particular Apple apps, or websites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSample": {
      "abstract": [
        {
          "text": "The sample electrocardiogram sensor data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRElectrocardiogramSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRElectrocardiogramSample"
        }
      ],
      "role": "symbol",
      "title": "SRElectrocardiogramSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srelectrocardiogramsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics": {
      "abstract": [
        {
          "text": "An object that represents metrics about the user’s face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRFaceMetrics"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRFaceMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRFaceMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srfacemetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest": {
      "abstract": [
        {
          "text": "An object that defines the criteria for a sample query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRFetchRequest"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRFetchRequest"
        }
      ],
      "role": "symbol",
      "title": "SRFetchRequest",
      "type": "topic",
      "url": "/documentation/sensorkit/srfetchrequest"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult": {
      "abstract": [
        {
          "text": "Recorded data that a sensor reader fetches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRFetchResult"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRFetchResult"
        }
      ],
      "role": "symbol",
      "title": "SRFetchResult",
      "type": "topic",
      "url": "/documentation/sensorkit/srfetchresult"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics": {
      "abstract": [
        {
          "text": "The configuration of a device’s keyboard and its usage patterns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRKeyboardMetrics"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRKeyboardMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRKeyboardMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEvent": {
      "abstract": [
        {
          "text": "A user interaction with a media object, such as an image or a video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRMediaEvent"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRMediaEvent"
        }
      ],
      "role": "symbol",
      "title": "SRMediaEvent",
      "type": "topic",
      "url": "/documentation/sensorkit/srmediaevent"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRMessagesUsageReport": {
      "abstract": [
        {
          "text": "An object that describes the user’s Messages app activity over a period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRMessagesUsageReport"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRMessagesUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRMessagesUsageReport"
        }
      ],
      "role": "symbol",
      "title": "SRMessagesUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srmessagesusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhoneUsageReport": {
      "abstract": [
        {
          "text": "An object that describes the user’s phone activity over a period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRPhoneUsageReport"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhoneUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhoneUsageReport"
        }
      ],
      "role": "symbol",
      "title": "SRPhoneUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srphoneusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample": {
      "abstract": [
        {
          "text": "The sample photoplethysmogram (PPG) sensor data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramSample"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor": {
      "abstract": [
        {
          "text": "The sensors an app can read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensor"
        }
      ],
      "role": "symbol",
      "title": "SRSensor",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader": {
      "abstract": [
        {
          "text": "An object that establishes user authorization and records data for a particular sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRSensorReader"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorReader"
        }
      ],
      "role": "symbol",
      "title": "SRSensorReader",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreader"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechExpression": {
      "abstract": [
        {
          "text": "An object that represents the metrics and voice analytics for a range of speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRSpeechExpression"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechExpression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSpeechExpression"
        }
      ],
      "role": "symbol",
      "title": "SRSpeechExpression",
      "type": "topic",
      "url": "/documentation/sensorkit/srspeechexpression"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechMetrics": {
      "abstract": [
        {
          "text": "An object that represents metrics about a range of speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRSpeechMetrics"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSpeechMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRSpeechMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srspeechmetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit": {
      "abstract": [
        {
          "text": "The user’s progress in their daily travel routine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRVisit"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRVisit"
        }
      ],
      "role": "symbol",
      "title": "SRVisit",
      "type": "topic",
      "url": "/documentation/sensorkit/srvisit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection": {
      "abstract": [
        {
          "text": "The configuration of a watch on the wearer’s wrist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRWristDetection"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristDetection"
        }
      ],
      "role": "symbol",
      "title": "SRWristDetection",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristdetection"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature": {
      "abstract": [
        {
          "text": "The temperature of the user’s wrist while the user sleeps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRWristTemperature"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristTemperature"
        }
      ],
      "role": "symbol",
      "title": "SRWristTemperature",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperatureSession": {
      "abstract": [
        {
          "text": "An object that represents wrist temperatures that a device records during a period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRWristTemperatureSession"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperatureSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristTemperatureSession"
        }
      ],
      "role": "symbol",
      "title": "SRWristTemperatureSession",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperaturesession"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SR_ARKIT_SUPPORTED": {
      "abstract": [
        {
          "text": "A flag that indicates whether the ARKit framework is available in the SDK for the SensorKit framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SR_ARKIT_SUPPORTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SR_ARKIT_SUPPORTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SR_ARKIT_SUPPORTED"
        }
      ],
      "role": "symbol",
      "title": "SR_ARKIT_SUPPORTED",
      "type": "topic",
      "url": "/documentation/sensorkit/sr_arkit_supported"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SR_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SR_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SR_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "SR_EXTERN",
      "type": "topic",
      "url": "/documentation/sensorkit/sr_extern"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SR_EXTERN_HIDDEN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SR_EXTERN_HIDDEN"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SR_EXTERN_HIDDEN",
      "kind": "symbol",
      "role": "symbol",
      "title": "SR_EXTERN_HIDDEN",
      "type": "topic",
      "url": "/documentation/sensorkit/sr_extern_hidden"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/configuring-your-project-for-sensor-reading": {
      "abstract": [
        {
          "text": "Add metadata to your app to attain system and user permission to access sensor data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/configuring-your-project-for-sensor-reading",
      "kind": "article",
      "role": "article",
      "title": "Configuring your project for sensor reading",
      "type": "topic",
      "url": "/documentation/sensorkit/configuring-your-project-for-sensor-reading"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Updates/SensorKit"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Setup",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/configuring-your-project-for-sensor-reading",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader"
      ],
      "title": "Setup"
    },
    {
      "anchor": "Authorization",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.sensorkit.reader.allow"
      ],
      "title": "Authorization"
    },
    {
      "anchor": "Querying-data",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult"
      ],
      "title": "Querying data"
    },
    {
      "anchor": "Interpreting-data",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEvent",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRMessagesUsageReport",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhoneUsageReport",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection"
      ],
      "title": "Interpreting data"
    },
    {
      "anchor": "Deleting-samples",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeletionRecord"
      ],
      "title": "Deleting samples"
    },
    {
      "anchor": "Analyzing-speech",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechMetrics",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechExpression"
      ],
      "title": "Analyzing speech"
    },
    {
      "anchor": "Analyzing-faces",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics",
        "doc://com.apple.sensorkit/documentation/SensorKit/SR_ARKIT_SUPPORTED"
      ],
      "title": "Analyzing faces"
    },
    {
      "anchor": "Recording-wrist-temperatures",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperatureSession",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature"
      ],
      "title": "Recording wrist temperatures"
    },
    {
      "anchor": "Recording-ectrocardiogram-data",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSample"
      ],
      "title": "Recording ectrocardiogram data"
    },
    {
      "anchor": "Recording-photoplethysmogram-data",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample"
      ],
      "title": "Recording photoplethysmogram data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Updates/SensorKit"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Setup",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/configuring-your-project-for-sensor-reading",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader"
              ],
              "title": "Setup"
            },
            {
              "anchor": "Authorization",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.sensorkit.reader.allow"
              ],
              "title": "Authorization"
            },
            {
              "anchor": "Querying-data",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult"
              ],
              "title": "Querying data"
            },
            {
              "anchor": "Interpreting-data",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEvent",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRMessagesUsageReport",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhoneUsageReport",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection"
              ],
              "title": "Interpreting data"
            },
            {
              "anchor": "Deleting-samples",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeletionRecord"
              ],
              "title": "Deleting samples"
            },
            {
              "anchor": "Analyzing-speech",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechMetrics",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechExpression"
              ],
              "title": "Analyzing speech"
            },
            {
              "anchor": "Analyzing-faces",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics",
                "doc://com.apple.sensorkit/documentation/SensorKit/SR_ARKIT_SUPPORTED"
              ],
              "title": "Analyzing faces"
            },
            {
              "anchor": "Recording-wrist-temperatures",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperatureSession",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature"
              ],
              "title": "Recording wrist temperatures"
            },
            {
              "anchor": "Recording-ectrocardiogram-data",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRElectrocardiogramSample"
              ],
              "title": "Recording ectrocardiogram data"
            },
            {
              "anchor": "Recording-photoplethysmogram-data",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample"
              ],
              "title": "Recording photoplethysmogram data"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SR_EXTERN",
                "doc://com.apple.sensorkit/documentation/SensorKit/SR_EXTERN_HIDDEN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/title",
          "value": "SRVisit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor/title",
          "value": "SRSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/title",
          "value": "SRKeyboardMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMessagesUsageReport/title",
          "value": "SRMessagesUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMessagesUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMessagesUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMessagesUsageReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMessagesUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/title",
          "value": "SRSensorReader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhoneUsageReport/title",
          "value": "SRPhoneUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhoneUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhoneUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhoneUsageReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhoneUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSpeechExpression/title",
          "value": "SRSpeechExpression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSpeechExpression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSpeechExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSpeechExpression/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSpeechExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperatureSession/title",
          "value": "SRWristTemperatureSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperatureSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperatureSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/title",
          "value": "SRAmbientLightSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample/title",
          "value": "SRPhotoplethysmogramSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEvent/title",
          "value": "SRMediaEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMediaEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMediaEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeletionRecord/title",
          "value": "SRDeletionRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeletionRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeletionRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeletionRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeletionRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/title",
          "value": "SRDeviceUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/title",
          "value": "SRWristDetection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristDetection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristDetection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult/title",
          "value": "SRFetchResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFetchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFetchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/title",
          "value": "SRFetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSample/title",
          "value": "SRElectrocardiogramSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRElectrocardiogramSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRElectrocardiogramSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRElectrocardiogramSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SR_ARKIT_SUPPORTED/title",
          "value": "SR_ARKIT_SUPPORTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SR_ARKIT_SUPPORTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SR_ARKIT_SUPPORTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSpeechMetrics/title",
          "value": "SRSpeechMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSpeechMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSpeechMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSpeechMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSpeechMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics/title",
          "value": "SRFaceMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFaceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRFaceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/title",
          "value": "SRWristTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperature"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
