{
  "abstract": [
    {
      "text": "Post content to supported social networking services, using standard system interfaces.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.social/documentation/Social"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "Social",
    "modules": [
      {
        "name": "Social"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "6.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "6.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.8",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Social"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On iOS and macOS, this framework provides a template for creating HTTP requests. On iOS only, the Social framework provides a generalized interface for posting requests on behalf of the user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A common way to use this framework is:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a network session.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Get the activity feed for a user.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Make a new post.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set properties on a post, add attachments, etc.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Publish a post to an activity feed.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.social/documentation/Social": {
      "abstract": [
        {
          "text": "Post content to supported social networking services, using standard system interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social",
      "kind": "symbol",
      "role": "collection",
      "title": "Social",
      "type": "topic",
      "url": "/documentation/social"
    },
    "doc://com.apple.social/documentation/Social/SLComposeServiceViewController": {
      "abstract": [
        {
          "text": "A view controller that you present from your share app extension, allowing the user to compose social media posts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLComposeServiceViewController"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeServiceViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeServiceViewController"
        }
      ],
      "role": "symbol",
      "title": "SLComposeServiceViewController",
      "type": "topic",
      "url": "/documentation/social/slcomposeserviceviewcontroller"
    },
    "doc://com.apple.social/documentation/Social/SLComposeViewController": {
      "abstract": [
        {
          "text": "A view controller that allows the user to compose social media posts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLComposeViewController"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeViewController"
        }
      ],
      "role": "symbol",
      "title": "SLComposeViewController",
      "type": "topic",
      "url": "/documentation/social/slcomposeviewcontroller"
    },
    "doc://com.apple.social/documentation/Social/SLRequest": {
      "abstract": [
        {
          "text": "An object that you use to assemble an HTTP request for communicating with a social media service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLRequest"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLRequest"
        }
      ],
      "role": "symbol",
      "title": "SLRequest",
      "type": "topic",
      "url": "/documentation/social/slrequest"
    },
    "doc://com.apple.social/documentation/Social/SOCIAL_CLASS_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SOCIAL_CLASS_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SOCIAL_CLASS_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "SOCIAL_CLASS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/social/social_class_available"
    },
    "doc://com.apple.social/documentation/Social/SOCIAL_CLASS_AVAILABLE_IOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SOCIAL_CLASS_AVAILABLE_IOS"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SOCIAL_CLASS_AVAILABLE_IOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "SOCIAL_CLASS_AVAILABLE_IOS",
      "type": "topic",
      "url": "/documentation/social/social_class_available_ios"
    },
    "doc://com.apple.social/documentation/Social/SOCIAL_CLASS_AVAILABLE_MAC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SOCIAL_CLASS_AVAILABLE_MAC"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SOCIAL_CLASS_AVAILABLE_MAC",
      "kind": "symbol",
      "role": "symbol",
      "title": "SOCIAL_CLASS_AVAILABLE_MAC",
      "type": "topic",
      "url": "/documentation/social/social_class_available_mac"
    },
    "doc://com.apple.social/documentation/Social/SOCIAL_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SOCIAL_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SOCIAL_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "SOCIAL_EXTERN",
      "type": "topic",
      "url": "/documentation/social/social_extern"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Composition-Interfaces",
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLComposeServiceViewController",
        "doc://com.apple.social/documentation/Social/SLComposeViewController"
      ],
      "title": "Composition Interfaces"
    },
    {
      "anchor": "Server-Communication",
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLRequest"
      ],
      "title": "Server Communication"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Composition-Interfaces",
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLComposeServiceViewController",
                "doc://com.apple.social/documentation/Social/SLComposeViewController"
              ],
              "title": "Composition Interfaces"
            },
            {
              "anchor": "Server-Communication",
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLRequest"
              ],
              "title": "Server Communication"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SOCIAL_CLASS_AVAILABLE",
                "doc://com.apple.social/documentation/Social/SOCIAL_CLASS_AVAILABLE_IOS",
                "doc://com.apple.social/documentation/Social/SOCIAL_CLASS_AVAILABLE_MAC",
                "doc://com.apple.social/documentation/Social/SOCIAL_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeServiceViewController/title",
          "value": "SLComposeServiceViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeServiceViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeServiceViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeServiceViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeServiceViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewController/title",
          "value": "SLComposeViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest/title",
          "value": "SLRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/social"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/social"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
