{
  "abstract": [
    {
      "text": "Classify various sounds by analyzing audio files or streams.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.soundanalysis/documentation/SoundAnalysis"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "SoundAnalysis",
    "modules": [
      {
        "name": "Sound Analysis"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Sound Analysis"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Identify specific sounds in your app, such as laughter or applause, by creating an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to analyze an audio file or stream. Sound requests can identify over 300 sounds. Alternatively, you identify a custom set of sounds by providing the sound request with a custom Core ML model. You train a custom sound classification model by creating an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLSoundClassifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with audio data in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/CreateML": {
      "abstract": [
        {
          "text": "Create machine learning models for use in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML",
      "kind": "symbol",
      "role": "collection",
      "title": "Create ML",
      "type": "topic",
      "url": "/documentation/CreateML"
    },
    "doc://com.apple.documentation/documentation/CreateML/MLSoundClassifier": {
      "abstract": [
        {
          "text": "A machine learning model you train with audio files to recognize and identify sounds on a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLSoundClassifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLSoundClassifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLSoundClassifier",
      "type": "topic",
      "url": "/documentation/CreateML/MLSoundClassifier"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis": {
      "abstract": [
        {
          "text": "Classify various sounds by analyzing audio files or streams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
      "kind": "symbol",
      "role": "collection",
      "title": "Sound Analysis",
      "type": "topic",
      "url": "/documentation/soundanalysis"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNAudioFileAnalyzer": {
      "abstract": [
        {
          "text": "An analyzer that runs sound classification requests on an audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNAudioFileAnalyzer"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNAudioFileAnalyzer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNAudioFileAnalyzer"
        }
      ],
      "role": "symbol",
      "title": "SNAudioFileAnalyzer",
      "type": "topic",
      "url": "/documentation/soundanalysis/snaudiofileanalyzer"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNAudioStreamAnalyzer": {
      "abstract": [
        {
          "text": "An object you create to analyze a stream of audio data and provide the results to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNAudioStreamAnalyzer"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNAudioStreamAnalyzer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNAudioStreamAnalyzer"
        }
      ],
      "role": "symbol",
      "title": "SNAudioStreamAnalyzer",
      "type": "topic",
      "url": "/documentation/soundanalysis/snaudiostreamanalyzer"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult": {
      "abstract": [
        {
          "text": "A result that contains the highest-ranking classifications in a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNClassificationResult"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNClassificationResult"
        }
      ],
      "role": "symbol",
      "title": "SNClassificationResult",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassificationresult"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest": {
      "abstract": [
        {
          "text": "A request that classifies sound using a Core ML model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNClassifySoundRequest"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNClassifySoundRequest"
        }
      ],
      "role": "symbol",
      "title": "SNClassifySoundRequest",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassifysoundrequest"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError": {
      "abstract": [
        {
          "text": "An error from the Sound Analysis framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNError"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNError"
        }
      ],
      "role": "symbol",
      "title": "SNError",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerror"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code": {
      "abstract": [
        {
          "text": "The enumerated error codes that the Sound Analysis framework produces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SNError.Code",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerror/code"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the Sound Analysis error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SNErrorDomain",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerrordomain"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SN_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SN_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SN_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "SN_EXPORT",
      "type": "topic",
      "url": "/documentation/soundanalysis/sn_export"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-live-audio-input-with-a-built-in-sound-classifier": {
      "abstract": [
        {
          "text": "Detect and identify hundreds of sounds by using a trained classifier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-live-audio-input-with-a-built-in-sound-classifier",
      "kind": "article",
      "role": "sampleCode",
      "title": "Classifying Live Audio Input with a Built-in Sound Classifier",
      "type": "topic",
      "url": "/documentation/soundanalysis/classifying-live-audio-input-with-a-built-in-sound-classifier"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-sounds-in-an-audio-file": {
      "abstract": [
        {
          "text": "Identify individual sounds in a file, such as a recording, with an audio file analyzer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-sounds-in-an-audio-file",
      "kind": "article",
      "role": "article",
      "title": "Classifying Sounds in an Audio File",
      "type": "topic",
      "url": "/documentation/soundanalysis/classifying-sounds-in-an-audio-file"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-sounds-in-an-audio-stream": {
      "abstract": [
        {
          "text": "Identify individual sounds in an audio data stream, such as from a microphone, with an audio stream analyzer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-sounds-in-an-audio-stream",
      "kind": "article",
      "role": "article",
      "title": "Classifying Sounds in an Audio Stream",
      "type": "topic",
      "url": "/documentation/soundanalysis/classifying-sounds-in-an-audio-stream"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Audio-analyzers",
      "identifiers": [
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-sounds-in-an-audio-file",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNAudioFileAnalyzer",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-sounds-in-an-audio-stream",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNAudioStreamAnalyzer"
      ],
      "title": "Audio analyzers"
    },
    {
      "anchor": "Sound-classification-requests",
      "identifiers": [
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-live-audio-input-with-a-built-in-sound-classifier",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult"
      ],
      "title": "Sound classification requests"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Audio-analyzers",
              "identifiers": [
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-sounds-in-an-audio-file",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNAudioFileAnalyzer",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-sounds-in-an-audio-stream",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNAudioStreamAnalyzer"
              ],
              "title": "Audio analyzers"
            },
            {
              "anchor": "Sound-classification-requests",
              "identifiers": [
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-live-audio-input-with-a-built-in-sound-classifier",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult"
              ],
              "title": "Sound classification requests"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNErrorDomain"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SN_EXPORT"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNErrorDomain/title",
          "value": "SNErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult/title",
          "value": "SNClassificationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassificationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassificationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNAudioStreamAnalyzer/title",
          "value": "SNAudioStreamAnalyzer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNAudioStreamAnalyzer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNAudioStreamAnalyzer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNAudioStreamAnalyzer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNAudioStreamAnalyzer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest/title",
          "value": "SNClassifySoundRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassifySoundRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassifySoundRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code/title",
          "value": "SNErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNAudioFileAnalyzer/title",
          "value": "SNAudioFileAnalyzer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNAudioFileAnalyzer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNAudioFileAnalyzer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNAudioFileAnalyzer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNAudioFileAnalyzer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/soundanalysis"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/soundanalysis"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
