{
  "abstract": [
    {
      "text": "Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.speech/documentation/Speech"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "Speech",
    "modules": [
      {
        "name": "Speech"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Speech"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the Speech framework to recognize spoken words in recorded or live audio. The keyboard’s dictation support uses speech recognition to translate audio content into text. This framework provides a similar behavior, except that you can use it without the presence of the keyboard. For example, you might use speech recognition to recognize verbal commands or to handle text dictation in other parts of your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can perform speech recognition in many languages, but each ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object operates on a single language. On-device speech recognition is available for some languages, but the framework also relies on Apple’s servers for speech recognition. Always assume that performing speech recognition requires a network connection.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.speech/documentation/Speech": {
      "abstract": [
        {
          "text": "Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech",
      "kind": "symbol",
      "role": "collection",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/speech"
    },
    "doc://com.apple.speech/documentation/Speech/DataInsertable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataInsertable"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/DataInsertable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataInsertable"
        }
      ],
      "role": "symbol",
      "title": "DataInsertable",
      "type": "topic",
      "url": "/documentation/speech/datainsertable"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFCustomLanguageModelData"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFCustomLanguageModelData"
        }
      ],
      "role": "symbol",
      "title": "SFCustomLanguageModelData",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest": {
      "abstract": [
        {
          "text": "A request to recognize speech from captured audio content, such as audio from the device’s microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechAudioBufferRecognitionRequest"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechAudioBufferRecognitionRequest"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechAudioBufferRecognitionRequest",
      "type": "topic",
      "url": "/documentation/speech/sfspeechaudiobufferrecognitionrequest"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechError"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechError"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechError",
      "type": "topic",
      "url": "/documentation/speech/sfspeecherror"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechLanguageModel"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechLanguageModel"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechLanguageModel",
      "type": "topic",
      "url": "/documentation/speech/sfspeechlanguagemodel"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel/Configuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel/Configuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechLanguageModel.Configuration",
      "type": "topic",
      "url": "/documentation/speech/sfspeechlanguagemodel/configuration"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionMetadata": {
      "abstract": [
        {
          "text": "The metadata of speech in the audio of a speech recognition request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionMetadata"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionMetadata"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionMetadata",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitionmetadata"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest": {
      "abstract": [
        {
          "text": "An abstract class that represents a request to recognize speech from an audio source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionRequest"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionRequest"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionRequest",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitionrequest"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionResult": {
      "abstract": [
        {
          "text": "An object that contains the partial or final results of a speech recognition request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionResult"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionResult"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionResult",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitionresult"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask": {
      "abstract": [
        {
          "text": "A task object for monitoring the speech recognition progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTask"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTask"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTask",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontask"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer": {
      "abstract": [
        {
          "text": "An object you use to check for the availability of the speech recognition service, and to initiate the speech recognition process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizer"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizer"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognizer",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognizer"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest": {
      "abstract": [
        {
          "text": "A request to recognize speech in a recorded audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechURLRecognitionRequest"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechURLRecognitionRequest"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechURLRecognitionRequest",
      "type": "topic",
      "url": "/documentation/speech/sfspeechurlrecognitionrequest"
    },
    "doc://com.apple.speech/documentation/Speech/SFTranscription": {
      "abstract": [
        {
          "text": "A textual representation of the specified speech in its entirety, as recognized by the speech recognizer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFTranscription"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFTranscription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFTranscription"
        }
      ],
      "role": "symbol",
      "title": "SFTranscription",
      "type": "topic",
      "url": "/documentation/speech/sftranscription"
    },
    "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment": {
      "abstract": [
        {
          "text": "A discrete part of an entire transcription, as identified by the speech recognizer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFTranscriptionSegment"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFTranscriptionSegment"
        }
      ],
      "role": "symbol",
      "title": "SFTranscriptionSegment",
      "type": "topic",
      "url": "/documentation/speech/sftranscriptionsegment"
    },
    "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics": {
      "abstract": [
        {
          "text": "A collection of vocal analysis metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFVoiceAnalytics"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFVoiceAnalytics"
        }
      ],
      "role": "symbol",
      "title": "SFVoiceAnalytics",
      "type": "topic",
      "url": "/documentation/speech/sfvoiceanalytics"
    },
    "doc://com.apple.speech/documentation/Speech/TemplateInsertable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TemplateInsertable"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/TemplateInsertable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TemplateInsertable"
        }
      ],
      "role": "symbol",
      "title": "TemplateInsertable",
      "type": "topic",
      "url": "/documentation/speech/templateinsertable"
    },
    "doc://com.apple.speech/documentation/Speech/asking-permission-to-use-speech-recognition": {
      "abstract": [
        {
          "text": "Ask the user’s permission to perform speech recognition using Apple’s servers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/asking-permission-to-use-speech-recognition",
      "kind": "article",
      "role": "article",
      "title": "Asking Permission to Use Speech Recognition",
      "type": "topic",
      "url": "/documentation/speech/asking-permission-to-use-speech-recognition"
    },
    "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio": {
      "abstract": [
        {
          "text": "Perform speech recognition on audio coming from the microphone of an iOS device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio",
      "kind": "article",
      "role": "sampleCode",
      "title": "Recognizing speech in live audio",
      "type": "topic",
      "url": "/documentation/speech/recognizing-speech-in-live-audio"
    },
    "doc://com.apple.speech/documentation/Speech/speech-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.speech/documentation/Speech/speech-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Speech Constants",
      "type": "topic",
      "url": "/documentation/speech/speech-constants"
    },
    "doc://com.apple.speech/documentation/Speech/speech-enumerations": {
      "abstract": [
        {
          "text": "Constants that specify types of speech recognition, the state of a recognition task, and the status of the authorization request.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/speech-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Speech Enumerations",
      "type": "topic",
      "url": "/documentation/speech/speech-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/asking-permission-to-use-speech-recognition",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Audio-sources",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio",
        "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest",
        "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest"
      ],
      "title": "Audio sources"
    },
    {
      "anchor": "In-progress-requests",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask"
      ],
      "title": "In-progress requests"
    },
    {
      "anchor": "Transcription-results",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionResult",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionMetadata",
        "doc://com.apple.speech/documentation/Speech/SFTranscription",
        "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment"
      ],
      "title": "Transcription results"
    },
    {
      "anchor": "Voice-analytics",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics"
      ],
      "title": "Voice analytics"
    },
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechError"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData",
        "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel",
        "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel/Configuration"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/DataInsertable",
        "doc://com.apple.speech/documentation/Speech/TemplateInsertable"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/speech-enumerations",
        "doc://com.apple.speech/documentation/Speech/speech-constants"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/asking-permission-to-use-speech-recognition",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizer"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Audio-sources",
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio",
                "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest",
                "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest"
              ],
              "title": "Audio sources"
            },
            {
              "anchor": "In-progress-requests",
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask"
              ],
              "title": "In-progress requests"
            },
            {
              "anchor": "Transcription-results",
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionResult",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionMetadata",
                "doc://com.apple.speech/documentation/Speech/SFTranscription",
                "doc://com.apple.speech/documentation/Speech/SFTranscriptionSegment"
              ],
              "title": "Transcription results"
            },
            {
              "anchor": "Voice-analytics",
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics"
              ],
              "title": "Voice analytics"
            },
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel",
                "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel/Configuration"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/speech-enumerations",
                "doc://com.apple.speech/documentation/Speech/speech-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscription/title",
          "value": "SFTranscription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFTranscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFTranscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTask/title",
          "value": "SFSpeechRecognitionTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionResult/title",
          "value": "SFSpeechRecognitionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel/title",
          "value": "SFSpeechLanguageModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechLanguageModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechLanguageModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscriptionSegment/title",
          "value": "SFTranscriptionSegment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscriptionSegment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFTranscriptionSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscriptionSegment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFTranscriptionSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel~1Configuration/title",
          "value": "SFSpeechLanguageModelConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel~1Configuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechLanguageModelConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel~1Configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechLanguageModelConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest/title",
          "value": "SFSpeechURLRecognitionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechURLRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechURLRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics/title",
          "value": "SFVoiceAnalytics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFVoiceAnalytics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFVoiceAnalytics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionRequest/title",
          "value": "SFSpeechRecognitionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizer/title",
          "value": "SFSpeechRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionMetadata/title",
          "value": "SFSpeechRecognitionMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest/title",
          "value": "SFSpeechAudioBufferRecognitionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechAudioBufferRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechAudioBufferRecognitionRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/speech"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/speech"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
