{
  "abstract": [
    {
      "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "SpriteKit",
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "7.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "7.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.9",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "SpriteKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "SpriteKit is a general-purpose framework for drawing shapes, particles, text, images, and video in two dimensions. It leverages Metal to achieve high-performance rendering, while offering a simple programming interface to make it easy to create games and other graphics-intensive apps. Using a rich set of animations and physics behaviors, you can quickly add life to your visual elements and gracefully transition between screens.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "SpriteKit is supported in iOS, macOS, tvOS, and watchOS, and it integrates well with frameworks such as GameplayKit and SceneKit. You can use SpriteKit in a compatible iPhone or iPad app running in visionOS, but don’t use it in apps you create specifically for visionOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceSKScene": {
      "abstract": [
        {
          "text": "A visual WatchKit element that displays a SpriteKit scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceSKScene"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceSKScene",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKInterfaceSKScene",
      "type": "topic",
      "url": "/documentation/WatchKit/WKInterfaceSKScene"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAction": {
      "abstract": [
        {
          "text": "An object that is run by a node to change its structure or content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAction"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAction"
        }
      ],
      "role": "symbol",
      "title": "SKAction",
      "type": "topic",
      "url": "/documentation/spritekit/skaction"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttribute": {
      "abstract": [
        {
          "text": "A specification for dynamic per-node data used with a custom shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAttribute"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttribute"
        }
      ],
      "role": "symbol",
      "title": "SKAttribute",
      "type": "topic",
      "url": "/documentation/spritekit/skattribute"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeValue": {
      "abstract": [
        {
          "text": "A container for dynamic shader data associated with a node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAttributeValue"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAttributeValue"
        }
      ],
      "role": "symbol",
      "title": "SKAttributeValue",
      "type": "topic",
      "url": "/documentation/spritekit/skattributevalue"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKConstraint": {
      "abstract": [
        {
          "text": "A specification for constraining a node’s position or rotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKConstraint"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKConstraint"
        }
      ],
      "role": "symbol",
      "title": "SKConstraint",
      "type": "topic",
      "url": "/documentation/spritekit/skconstraint"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldNode": {
      "abstract": [
        {
          "text": "A node that applies physics effects to nearby nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKFieldNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKFieldNode"
        }
      ],
      "role": "symbol",
      "title": "SKFieldNode",
      "type": "topic",
      "url": "/documentation/spritekit/skfieldnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence": {
      "abstract": [
        {
          "text": "An object that performs interpolation between values specified at different times (keyframes).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKKeyframeSequence"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKKeyframeSequence"
        }
      ],
      "role": "symbol",
      "title": "SKKeyframeSequence",
      "type": "topic",
      "url": "/documentation/spritekit/skkeyframesequence"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKMutableTexture": {
      "abstract": [
        {
          "text": "A texture whose contents can be dynamically updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKMutableTexture"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKMutableTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKMutableTexture"
        }
      ],
      "role": "symbol",
      "title": "SKMutableTexture",
      "type": "topic",
      "url": "/documentation/spritekit/skmutabletexture"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody": {
      "abstract": [
        {
          "text": "An object that adds physics simulation to a node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsBody"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsBody"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsBody",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicsbody"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsContact": {
      "abstract": [
        {
          "text": "A description of the contact between two physics bodies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsContact"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsContact"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsContact",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicscontact"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsContactDelegate": {
      "abstract": [
        {
          "text": "Methods your app can implement to respond when physics bodies come into contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsContactDelegate"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsContactDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsContactDelegate"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsContactDelegate",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicscontactdelegate"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJoint": {
      "abstract": [
        {
          "text": "The abstract superclass for objects that connect physics bodies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsJoint"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsJoint"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsJoint",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicsjoint"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointFixed": {
      "abstract": [
        {
          "text": "A joint that fuses two physics bodies together at a reference point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsJointFixed"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointFixed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsJointFixed"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsJointFixed",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicsjointfixed"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointLimit": {
      "abstract": [
        {
          "text": "A joint that imposes a maximum distance between two physics bodies, as if they were connected by a rope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsJointLimit"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsJointLimit"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsJointLimit",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicsjointlimit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointPin": {
      "abstract": [
        {
          "text": "A joint that pins together two physics bodies, allowing independent rotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsJointPin"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointPin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsJointPin"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsJointPin",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicsjointpin"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointSliding": {
      "abstract": [
        {
          "text": "A joint that allows two physics bodies to slide along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsJointSliding"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointSliding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsJointSliding"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsJointSliding",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicsjointsliding"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointSpring": {
      "abstract": [
        {
          "text": "A joint that simulates a spring connecting two physics bodies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsJointSpring"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointSpring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsJointSpring"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsJointSpring",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicsjointspring"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsWorld": {
      "abstract": [
        {
          "text": "The driver of the physics engine in a scene; it exposes the ability for you to configure and query the physics system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPhysicsWorld"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsWorld",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPhysicsWorld"
        }
      ],
      "role": "symbol",
      "title": "SKPhysicsWorld",
      "type": "topic",
      "url": "/documentation/spritekit/skphysicsworld"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKRange": {
      "abstract": [
        {
          "text": "A definition of a range of floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKRange"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKRange"
        }
      ],
      "role": "symbol",
      "title": "SKRange",
      "type": "topic",
      "url": "/documentation/spritekit/skrange"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKReachConstraints": {
      "abstract": [
        {
          "text": "A specification of the degree of freedom when solving inverse kinematics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKReachConstraints"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKReachConstraints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKReachConstraints"
        }
      ],
      "role": "symbol",
      "title": "SKReachConstraints",
      "type": "topic",
      "url": "/documentation/spritekit/skreachconstraints"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKRegion": {
      "abstract": [
        {
          "text": "The definition of an arbitrary area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKRegion"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKRegion"
        }
      ],
      "role": "symbol",
      "title": "SKRegion",
      "type": "topic",
      "url": "/documentation/spritekit/skregion"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKRenderer": {
      "abstract": [
        {
          "text": "An object that renders a scene into a custom Metal rendering pipeline and drives the scene update cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKRenderer"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKRenderer"
        }
      ],
      "role": "symbol",
      "title": "SKRenderer",
      "type": "topic",
      "url": "/documentation/spritekit/skrenderer"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKScene": {
      "abstract": [
        {
          "text": "An object that organizes all of the active SpriteKit content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKScene"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKScene"
        }
      ],
      "role": "symbol",
      "title": "SKScene",
      "type": "topic",
      "url": "/documentation/spritekit/skscene"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKShader": {
      "abstract": [
        {
          "text": "An object that allows you to apply a custom fragment shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKShader"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKShader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKShader"
        }
      ],
      "role": "symbol",
      "title": "SKShader",
      "type": "topic",
      "url": "/documentation/spritekit/skshader"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTexture": {
      "abstract": [
        {
          "text": "An image, decoded on the GPU, that can be used to render various SpriteKit objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTexture"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTexture"
        }
      ],
      "role": "symbol",
      "title": "SKTexture",
      "type": "topic",
      "url": "/documentation/spritekit/sktexture"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTextureAtlas": {
      "abstract": [
        {
          "text": "A collection of textures optimized for storage and drawing performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTextureAtlas"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTextureAtlas",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTextureAtlas"
        }
      ],
      "role": "symbol",
      "title": "SKTextureAtlas",
      "type": "topic",
      "url": "/documentation/spritekit/sktextureatlas"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileDefinition": {
      "abstract": [
        {
          "text": "A single tile that can be repeated in a tile map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileDefinition"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileDefinition"
        }
      ],
      "role": "symbol",
      "title": "SKTileDefinition",
      "type": "topic",
      "url": "/documentation/spritekit/sktiledefinition"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroup": {
      "abstract": [
        {
          "text": "A set of tiles that collectively define one type of terrain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileGroup"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileGroup"
        }
      ],
      "role": "symbol",
      "title": "SKTileGroup",
      "type": "topic",
      "url": "/documentation/spritekit/sktilegroup"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule": {
      "abstract": [
        {
          "text": "Rules that describe how various tiles should be placed in a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileGroupRule"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileGroupRule"
        }
      ],
      "role": "symbol",
      "title": "SKTileGroupRule",
      "type": "topic",
      "url": "/documentation/spritekit/sktilegrouprule"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode": {
      "abstract": [
        {
          "text": "A two-dimensional array of images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileMapNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileMapNode"
        }
      ],
      "role": "symbol",
      "title": "SKTileMapNode",
      "type": "topic",
      "url": "/documentation/spritekit/sktilemapnode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileSet": {
      "abstract": [
        {
          "text": "A container for related tile groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileSet"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileSet"
        }
      ],
      "role": "symbol",
      "title": "SKTileSet",
      "type": "topic",
      "url": "/documentation/spritekit/sktileset"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform": {
      "abstract": [
        {
          "text": "A container for uniform shader data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKUniform"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniform"
        }
      ],
      "role": "symbol",
      "title": "SKUniform",
      "type": "topic",
      "url": "/documentation/spritekit/skuniform"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKView": {
      "abstract": [
        {
          "text": "A view subclass that renders a SpriteKit scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKView"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKView"
        }
      ],
      "role": "symbol",
      "title": "SKView",
      "type": "topic",
      "url": "/documentation/spritekit/skview"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpGeometry": {
      "abstract": [
        {
          "text": "A definition for a deformation of nodes that conform to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpable",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKWarpGeometry"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKWarpGeometry"
        }
      ],
      "role": "symbol",
      "title": "SKWarpGeometry",
      "type": "topic",
      "url": "/documentation/spritekit/skwarpgeometry"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpGeometryGrid": {
      "abstract": [
        {
          "text": "A definition for a grid-based deformation of nodes that conform to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpable",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKWarpGeometryGrid"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpGeometryGrid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKWarpGeometryGrid"
        }
      ],
      "role": "symbol",
      "title": "SKWarpGeometryGrid",
      "type": "topic",
      "url": "/documentation/spritekit/skwarpgeometrygrid"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpable": {
      "abstract": [
        {
          "text": "A protocol for objects that can be warped and animated by an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpGeometry",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKWarpable"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKWarpable"
        }
      ],
      "role": "symbol",
      "title": "SKWarpable",
      "type": "topic",
      "url": "/documentation/spritekit/skwarpable"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SpriteView": {
      "abstract": [
        {
          "text": "A SwiftUI view that renders a SpriteKit scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SpriteView"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SpriteView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SpriteView"
        }
      ],
      "role": "symbol",
      "title": "SpriteView",
      "type": "topic",
      "url": "/documentation/spritekit/spriteview"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/choosing-a-spritekit-scene-renderer": {
      "abstract": [
        {
          "text": "Compare the different ways to display a SpriteKit scene.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/choosing-a-spritekit-scene-renderer",
      "kind": "article",
      "role": "article",
      "title": "Choosing a SpriteKit Scene Renderer",
      "type": "topic",
      "url": "/documentation/spritekit/choosing-a-spritekit-scene-renderer"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/drawing-spritekit-content-in-a-view": {
      "abstract": [
        {
          "text": "Display visual content using SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/drawing-spritekit-content-in-a-view",
      "kind": "article",
      "role": "article",
      "title": "Drawing SpriteKit Content in a View",
      "type": "topic",
      "url": "/documentation/spritekit/drawing-spritekit-content-in-a-view"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/getting-started-with-actions": {
      "abstract": [
        {
          "text": "Create, configure, and run actions in SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/getting-started-with-actions",
      "kind": "article",
      "role": "article",
      "title": "Getting Started with Actions",
      "type": "topic",
      "url": "/documentation/spritekit/getting-started-with-actions"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/getting-started-with-physics": {
      "abstract": [
        {
          "text": "Simulate gravity, acceleration, collision detection, or joints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/getting-started-with-physics",
      "kind": "article",
      "role": "article",
      "title": "Getting Started with Physics",
      "type": "topic",
      "url": "/documentation/spritekit/getting-started-with-physics"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/maximizing-texture-performance": {
      "abstract": [
        {
          "text": "Speed up image display and enable more images to be displayed at one time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/maximizing-texture-performance",
      "kind": "article",
      "role": "article",
      "title": "Maximizing Texture Performance",
      "type": "topic",
      "url": "/documentation/spritekit/maximizing-texture-performance"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building": {
      "abstract": [
        {
          "text": "Define the appearance or layout of scene content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nodes for Scene Building",
      "type": "topic",
      "url": "/documentation/spritekit/nodes-for-scene-building"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants": {
      "abstract": [
        {
          "text": "Constants used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Constants",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-constants"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types": {
      "abstract": [
        {
          "text": "Data types used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Data Types",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-data-types"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations": {
      "abstract": [
        {
          "text": "Enumerations used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Enumerations",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-enumerations"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases": {
      "abstract": [
        {
          "text": "Type aliases used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Type Aliases",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-type-aliases"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables": {
      "abstract": [
        {
          "text": "Global variables and macros used across SpriteKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SpriteKit Variables",
      "type": "topic",
      "url": "/documentation/spritekit/spritekit-variables"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/working-with-inverse-kinematics": {
      "abstract": [
        {
          "text": "Gain fine-tuned control of objects that are connected by joints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/working-with-inverse-kinematics",
      "kind": "article",
      "role": "article",
      "title": "Working with Inverse Kinematics",
      "type": "topic",
      "url": "/documentation/spritekit/working-with-inverse-kinematics"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/drawing-spritekit-content-in-a-view",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKScene",
        "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building"
      ],
      "title": "Essentials"
    },
    {
      "abstract": [
        {
          "text": "Draw a SpriteKit scene using a rendering object.",
          "type": "text"
        }
      ],
      "anchor": "Scene-Renderers",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/choosing-a-spritekit-scene-renderer",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKView",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKRenderer",
        "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceSKScene"
      ],
      "title": "Scene Renderers"
    },
    {
      "abstract": [
        {
          "text": "Load graphics from various sources, or use an atlas to maximize rendering performance.",
          "type": "text"
        }
      ],
      "anchor": "Textures",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/maximizing-texture-performance",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTexture",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTextureAtlas",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKMutableTexture"
      ],
      "title": "Textures"
    },
    {
      "abstract": [
        {
          "text": "Animate nodes by using a suite of provided actions, or create custom actions.",
          "type": "text"
        }
      ],
      "anchor": "Animation",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/getting-started-with-actions",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAction"
      ],
      "title": "Animation"
    },
    {
      "abstract": [
        {
          "text": "Constrain the position or orientation of nodes.",
          "type": "text"
        }
      ],
      "anchor": "Constraints",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKConstraint",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKReachConstraints"
      ],
      "title": "Constraints"
    },
    {
      "abstract": [
        {
          "text": "Multipurpose mathematical objects you use to facilitate other graphical work.",
          "type": "text"
        }
      ],
      "anchor": "Mathematical-Tools",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKRange",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKRegion"
      ],
      "title": "Mathematical Tools"
    },
    {
      "abstract": [
        {
          "text": "Add physics behaviors to nodes in your scene.",
          "type": "text"
        }
      ],
      "anchor": "Physics-Simulation",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/getting-started-with-physics",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsWorld",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsContact",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsContactDelegate",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldNode"
      ],
      "title": "Physics Simulation"
    },
    {
      "abstract": [
        {
          "text": "Connect physics bodies by using conceptual tools like pins, sliding joints, and spring joints.",
          "type": "text"
        }
      ],
      "anchor": "Physics-Joints",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/working-with-inverse-kinematics",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJoint",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointFixed",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointLimit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointPin",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointSliding",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointSpring"
      ],
      "title": "Physics Joints"
    },
    {
      "abstract": [
        {
          "text": "Configure the images or autotiling behavior of a tile map node.",
          "type": "text"
        }
      ],
      "anchor": "Tiling",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileDefinition",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroup",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileSet"
      ],
      "title": "Tiling"
    },
    {
      "abstract": [
        {
          "text": "Customize node drawing by augmenting the node’s color or shape.",
          "type": "text"
        }
      ],
      "anchor": "Shaders",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKShader",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttribute",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeValue",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform"
      ],
      "title": "Shaders"
    },
    {
      "abstract": [
        {
          "text": "Distort a node by supplying vertices and their transformations.",
          "type": "text"
        }
      ],
      "anchor": "Warping",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpGeometry",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpGeometryGrid",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpable"
      ],
      "title": "Warping"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
        "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SpriteView"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/drawing-spritekit-content-in-a-view",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKScene",
                "doc://com.apple.spritekit/documentation/SpriteKit/nodes-for-scene-building"
              ],
              "title": "Essentials"
            },
            {
              "abstract": [
                {
                  "text": "Draw a SpriteKit scene using a rendering object.",
                  "type": "text"
                }
              ],
              "anchor": "Scene-Renderers",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/choosing-a-spritekit-scene-renderer",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKView",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKRenderer",
                "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceSKScene"
              ],
              "title": "Scene Renderers"
            },
            {
              "abstract": [
                {
                  "text": "Load graphics from various sources, or use an atlas to maximize rendering performance.",
                  "type": "text"
                }
              ],
              "anchor": "Textures",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/maximizing-texture-performance",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTexture",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTextureAtlas",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKMutableTexture"
              ],
              "title": "Textures"
            },
            {
              "abstract": [
                {
                  "text": "Animate nodes by using a suite of provided actions, or create custom actions.",
                  "type": "text"
                }
              ],
              "anchor": "Animation",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/getting-started-with-actions",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAction"
              ],
              "title": "Animation"
            },
            {
              "abstract": [
                {
                  "text": "Constrain the position or orientation of nodes.",
                  "type": "text"
                }
              ],
              "anchor": "Constraints",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKConstraint",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKReachConstraints"
              ],
              "title": "Constraints"
            },
            {
              "abstract": [
                {
                  "text": "Multipurpose mathematical objects you use to facilitate other graphical work.",
                  "type": "text"
                }
              ],
              "anchor": "Mathematical-Tools",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKKeyframeSequence",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKRange",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKRegion"
              ],
              "title": "Mathematical Tools"
            },
            {
              "abstract": [
                {
                  "text": "Add physics behaviors to nodes in your scene.",
                  "type": "text"
                }
              ],
              "anchor": "Physics-Simulation",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/getting-started-with-physics",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsWorld",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsBody",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsContact",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsContactDelegate",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKFieldNode"
              ],
              "title": "Physics Simulation"
            },
            {
              "abstract": [
                {
                  "text": "Connect physics bodies by using conceptual tools like pins, sliding joints, and spring joints.",
                  "type": "text"
                }
              ],
              "anchor": "Physics-Joints",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/working-with-inverse-kinematics",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJoint",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointFixed",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointLimit",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointPin",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointSliding",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKPhysicsJointSpring"
              ],
              "title": "Physics Joints"
            },
            {
              "abstract": [
                {
                  "text": "Configure the images or autotiling behavior of a tile map node.",
                  "type": "text"
                }
              ],
              "anchor": "Tiling",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileMapNode",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileDefinition",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroup",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileGroupRule",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileSet"
              ],
              "title": "Tiling"
            },
            {
              "abstract": [
                {
                  "text": "Customize node drawing by augmenting the node’s color or shape.",
                  "type": "text"
                }
              ],
              "anchor": "Shaders",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKShader",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttribute",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKAttributeValue",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform"
              ],
              "title": "Shaders"
            },
            {
              "abstract": [
                {
                  "text": "Distort a node by supplying vertices and their transformations.",
                  "type": "text"
                }
              ],
              "anchor": "Warping",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpGeometry",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpGeometryGrid",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKWarpable"
              ],
              "title": "Warping"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-enumerations",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-data-types",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-constants",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-type-aliases",
                "doc://com.apple.spritekit/documentation/SpriteKit/spritekit-variables"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence/title",
          "value": "SKKeyframeSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKKeyframeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKKeyframeSequence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKKeyframeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRegion/title",
          "value": "SKRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKInterfaceSKScene/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKInterfaceSKScene"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKInterfaceObject",
              "text": "WKInterfaceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/title",
          "value": "SKScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointLimit/title",
          "value": "SKPhysicsJointLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJointLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointLimit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJointLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAction/title",
          "value": "SKAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileDefinition/title",
          "value": "SKTileDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKMutableTexture/title",
          "value": "SKMutableTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKMutableTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKMutableTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKMutableTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKMutableTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTexture/title",
          "value": "SKTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView/title",
          "value": "SKView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTextureAtlas/title",
          "value": "SKTextureAtlas"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTextureAtlas/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTextureAtlas"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTextureAtlas/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTextureAtlas"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJoint/title",
          "value": "SKPhysicsJoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKWarpGeometry/title",
          "value": "SKWarpGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKWarpGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWarpGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKWarpGeometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWarpGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointSliding/title",
          "value": "SKPhysicsJointSliding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointSliding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJointSliding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointSliding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJointSliding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroup/title",
          "value": "SKTileGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKWarpGeometryGrid/title",
          "value": "SKWarpGeometryGrid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKWarpGeometryGrid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWarpGeometryGrid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKWarpGeometryGrid/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWarpGeometryGrid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeValue/title",
          "value": "SKAttributeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttributeValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttributeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsBody/title",
          "value": "SKPhysicsBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsBody/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRenderer/title",
          "value": "SKRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniform/title",
          "value": "SKUniform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKConstraint/title",
          "value": "SKConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsContact/title",
          "value": "SKPhysicsContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsContact/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKReachConstraints/title",
          "value": "SKReachConstraints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKReachConstraints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKReachConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKReachConstraints/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKReachConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointSpring/title",
          "value": "SKPhysicsJointSpring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointSpring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJointSpring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointSpring/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJointSpring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode/title",
          "value": "SKTileMapNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileMapNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileMapNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileMapNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKShader/title",
          "value": "SKShader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKShader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKShader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKShader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKShader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsWorld/title",
          "value": "SKPhysicsWorld"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsWorld/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsWorld"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsWorld/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsWorld"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKWarpable/title",
          "value": "SKWarpable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKWarpable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWarpable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKWarpable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWarpable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRange/title",
          "value": "SKRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileSet/title",
          "value": "SKTileSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttribute/title",
          "value": "SKAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointFixed/title",
          "value": "SKPhysicsJointFixed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointFixed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJointFixed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointFixed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJointFixed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroupRule/title",
          "value": "SKTileGroupRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroupRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileGroupRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileGroupRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileGroupRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsContactDelegate/title",
          "value": "SKPhysicsContactDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsContactDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsContactDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsContactDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsContactDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKFieldNode/title",
          "value": "SKFieldNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKFieldNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKFieldNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKFieldNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKFieldNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointPin/title",
          "value": "SKPhysicsJointPin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointPin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJointPin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKPhysicsJointPin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPhysicsJointPin"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
