{
  "abstract": [
    {
      "text": "Support In-App Purchases and interactions with the App Store.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "StoreKit",
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.7",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "6.2",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "StoreKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the StoreKit framework to provide the following features and services for your apps and In-App Purchases:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Offer and promote In-App Purchases for content and services.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "In-App Purchase",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Verify a customer’s app purchase with an App Store-signed transaction.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "App transaction",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Control the display of App Store messages in your app.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Messages",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Request App Store reviews and ratings from your customers.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Reviews",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Provide recommendations for third-party content that customers can purchase from the App Store.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Recommendations",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Validate advertisement-driven app installations. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/AdAttributionKit",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for app ad campaigns on the App Store and alternative marketplaces.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Ad network attribution",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "The StoreKit framework also provides functionality for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/external-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/external-link-account",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/PaymentMethodBinding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AdAttributionKit": {
      "abstract": [
        {
          "text": "Present, process, and register postbacks for in-app ads in the App Store and alternative app marketplaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AdAttributionKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AdAttributionKit",
      "type": "topic",
      "url": "/documentation/AdAttributionKit"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI": {
      "abstract": [
        {
          "text": "Automate the tasks you perform on the Apple Developer website and in App Store Connect.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI",
      "kind": "symbol",
      "role": "collection",
      "title": "App Store Connect API",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI"
    },
    "doc://com.apple.documentation/documentation/AppStoreServerAPI": {
      "abstract": [
        {
          "text": "Manage your customers’ App Store transactions from your server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerAPI",
      "kind": "symbol",
      "role": "collection",
      "title": "App Store Server API",
      "type": "topic",
      "url": "/documentation/AppStoreServerAPI"
    },
    "doc://com.apple.documentation/documentation/AppStoreServerNotifications": {
      "abstract": [
        {
          "text": "Monitor In-App Purchase events in real time and learn of unreported external purchase tokens, with server notifications from the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreServerNotifications",
      "kind": "symbol",
      "role": "collection",
      "title": "App Store Server Notifications",
      "type": "topic",
      "url": "/documentation/AppStoreServerNotifications"
    },
    "doc://com.apple.documentation/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/StoreKitTest"
    },
    "doc://com.apple.documentation/documentation/appstorereceipts": {
      "abstract": [
        {
          "text": "Validate app and In-App Purchase receipts with the App Store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts",
      "kind": "symbol",
      "role": "collection",
      "title": "App Store Receipts",
      "type": "topic",
      "url": "/documentation/appstorereceipts"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/AppTransaction": {
      "abstract": [
        {
          "text": "Information that represents the customer’s purchase of the app, cryptographically signed by the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppTransaction"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/AppTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AppTransaction"
        }
      ],
      "role": "symbol",
      "title": "AppTransaction",
      "type": "topic",
      "url": "/documentation/storekit/apptransaction"
    },
    "doc://com.apple.storekit/documentation/StoreKit/DisplayMessageAction": {
      "abstract": [
        {
          "text": "An instance that asks StoreKit to display an App Store message, if appropriate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayMessageAction"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/DisplayMessageAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayMessageAction"
        }
      ],
      "role": "symbol",
      "title": "DisplayMessageAction",
      "type": "topic",
      "url": "/documentation/storekit/displaymessageaction"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Message": {
      "abstract": [
        {
          "text": "An instance for receiving and displaying App Store messages in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Message"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Message",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Message"
        }
      ],
      "role": "symbol",
      "title": "Message",
      "type": "topic",
      "url": "/documentation/storekit/message"
    },
    "doc://com.apple.storekit/documentation/StoreKit/Message/Reason-swift.struct": {
      "abstract": [
        {
          "text": "Reasons for the App Store messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/Message/Reason-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "role": "symbol",
      "title": "Message.Reason",
      "type": "topic",
      "url": "/documentation/storekit/message/reason-swift.struct"
    },
    "doc://com.apple.storekit/documentation/StoreKit/PaymentMethodBinding": {
      "abstract": [
        {
          "text": "A binding that makes payment methods available in apps for an Apple ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PaymentMethodBinding"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/PaymentMethodBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PaymentMethodBinding"
        }
      ],
      "role": "symbol",
      "title": "PaymentMethodBinding",
      "type": "topic",
      "url": "/documentation/storekit/paymentmethodbinding"
    },
    "doc://com.apple.storekit/documentation/StoreKit/RequestReviewAction": {
      "abstract": [
        {
          "text": "An instance that tells StoreKit to request an App Store rating or review, if appropriate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RequestReviewAction"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/RequestReviewAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RequestReviewAction"
        }
      ],
      "role": "symbol",
      "title": "RequestReviewAction",
      "type": "topic",
      "url": "/documentation/storekit/requestreviewaction"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController": {
      "abstract": [
        {
          "text": "An object that determines the current capabilities of a person’s Music library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCloudServiceController"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceController"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceController",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecontroller"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupViewController": {
      "abstract": [
        {
          "text": "A view controller that helps people perform setup for a cloud service, like an Apple Music subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCloudServiceSetupViewController"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceSetupViewController"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceSetupViewController",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicesetupviewcontroller"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKLocalizedString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SKLocalizedString"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKLocalizedString",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKLocalizedString",
      "type": "topic",
      "url": "/documentation/storekit/sklocalizedstring"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay": {
      "abstract": [
        {
          "text": "A class that displays an overlay you can use to recommend another app or an App Clip’s corresponding full app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKOverlay"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKOverlay"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController": {
      "abstract": [
        {
          "text": "A view controller that provides a page where customers can purchase media from the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKStoreProductViewController"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKStoreProductViewController"
        }
      ],
      "role": "symbol",
      "title": "SKStoreProductViewController",
      "type": "topic",
      "url": "/documentation/storekit/skstoreproductviewcontroller"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKStoreReviewController": {
      "abstract": [
        {
          "text": "An object that controls the process of requesting App Store ratings and reviews from customers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKStoreReviewController"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKStoreReviewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKStoreReviewController"
        }
      ],
      "role": "symbol",
      "title": "SKStoreReviewController",
      "type": "topic",
      "url": "/documentation/storekit/skstorereviewcontroller"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SK_CLASS_FINAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SK_CLASS_FINAL"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SK_CLASS_FINAL",
      "kind": "symbol",
      "role": "symbol",
      "title": "SK_CLASS_FINAL",
      "type": "topic",
      "url": "/documentation/storekit/sk_class_final"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SK_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "SK_EXTERN",
      "type": "topic",
      "url": "/documentation/storekit/sk_extern"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SK_EXTERN_CLASS"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS",
      "kind": "symbol",
      "role": "symbol",
      "title": "SK_EXTERN_CLASS",
      "type": "topic",
      "url": "/documentation/storekit/sk_extern_class"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SK_EXTERN_CLASS_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "SK_EXTERN_CLASS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/storekit/sk_extern_class_available"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS_AVAILABLE_IOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SK_EXTERN_CLASS_AVAILABLE_IOS"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS_AVAILABLE_IOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "SK_EXTERN_CLASS_AVAILABLE_IOS",
      "type": "topic",
      "url": "/documentation/storekit/sk_extern_class_available_ios"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS_AVAILABLE_MAC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SK_EXTERN_CLASS_AVAILABLE_MAC"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS_AVAILABLE_MAC",
      "kind": "symbol",
      "role": "symbol",
      "title": "SK_EXTERN_CLASS_AVAILABLE_MAC",
      "type": "topic",
      "url": "/documentation/storekit/sk_extern_class_available_mac"
    },
    "doc://com.apple.storekit/documentation/StoreKit/StoreKitBundle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "StoreKitBundle"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/StoreKitBundle",
      "kind": "symbol",
      "role": "symbol",
      "title": "StoreKitBundle",
      "type": "topic",
      "url": "/documentation/storekit/storekitbundle"
    },
    "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution": {
      "abstract": [
        {
          "text": "Validate advertisement-driven app installations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ad network attribution",
      "type": "topic",
      "url": "/documentation/storekit/ad-network-attribution"
    },
    "doc://com.apple.storekit/documentation/StoreKit/external-link-account": {
      "abstract": [
        {
          "text": "Enable qualifying apps to link to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/external-link-account",
      "kind": "article",
      "role": "collectionGroup",
      "title": "External link account",
      "type": "topic",
      "url": "/documentation/storekit/external-link-account"
    },
    "doc://com.apple.storekit/documentation/StoreKit/external-purchase": {
      "abstract": [
        {
          "text": "Enable qualifying apps to offer external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/external-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "External Purchase",
      "type": "topic",
      "url": "/documentation/storekit/external-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase": {
      "abstract": [
        {
          "text": "Offer content and services in your app across Apple platforms using a Swift-based interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase",
      "kind": "article",
      "role": "collectionGroup",
      "title": "In-App Purchase",
      "type": "topic",
      "url": "/documentation/storekit/in-app-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/offering-media-for-sale-in-your-app": {
      "abstract": [
        {
          "text": "Allow users to purchase media in the App Store from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/offering-media-for-sale-in-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Offering media for sale in your app",
      "type": "topic",
      "url": "/documentation/storekit/offering-media-for-sale-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/requesting-app-store-reviews": {
      "abstract": [
        {
          "text": "Implement best practices for prompting users to review your app in the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/requesting-app-store-reviews",
      "kind": "article",
      "role": "sampleCode",
      "title": "Requesting App Store reviews",
      "type": "topic",
      "url": "/documentation/storekit/requesting-app-store-reviews"
    },
    "doc://com.apple.storekit/documentation/StoreKit/supporting-business-model-changes-by-using-the-app-transaction": {
      "abstract": [
        {
          "text": "Access the app transaction to learn when a customer first purchased an app, to determine the app features they’re entitled to.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/supporting-business-model-changes-by-using-the-app-transaction",
      "kind": "article",
      "role": "article",
      "title": "Supporting business model changes by using the app transaction",
      "type": "topic",
      "url": "/documentation/storekit/supporting-business-model-changes-by-using-the-app-transaction"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AppStoreServerAPI",
        "doc://com.apple.documentation/documentation/StoreKitTest",
        "doc://com.apple.documentation/documentation/AppStoreServerNotifications",
        "doc://com.apple.documentation/documentation/appstorereceipts",
        "doc://com.apple.documentation/documentation/AppStoreConnectAPI"
      ],
      "title": "Related Documentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "In-App-Purchase",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase"
      ],
      "title": "In-App Purchase"
    },
    {
      "anchor": "App-transaction",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/supporting-business-model-changes-by-using-the-app-transaction",
        "doc://com.apple.storekit/documentation/StoreKit/AppTransaction"
      ],
      "title": "App transaction"
    },
    {
      "anchor": "Messages",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/Message",
        "doc://com.apple.storekit/documentation/StoreKit/Message/Reason-swift.struct",
        "doc://com.apple.storekit/documentation/StoreKit/DisplayMessageAction"
      ],
      "title": "Messages"
    },
    {
      "anchor": "Reviews",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/requesting-app-store-reviews",
        "doc://com.apple.storekit/documentation/StoreKit/RequestReviewAction",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreReviewController"
      ],
      "title": "Reviews"
    },
    {
      "anchor": "Recommendations",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/offering-media-for-sale-in-your-app",
        "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay"
      ],
      "title": "Recommendations"
    },
    {
      "anchor": "Ad-network-attribution",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution"
      ],
      "title": "Ad network attribution"
    },
    {
      "anchor": "External-Purchase",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/external-purchase"
      ],
      "title": "External Purchase"
    },
    {
      "anchor": "External-link-account",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/external-link-account"
      ],
      "title": "External link account"
    },
    {
      "anchor": "Payment-method-binding",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/PaymentMethodBinding"
      ],
      "title": "Payment method binding"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupViewController",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "In-App-Purchase",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/in-app-purchase"
              ],
              "title": "In-App Purchase"
            },
            {
              "anchor": "App-transaction",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/supporting-business-model-changes-by-using-the-app-transaction"
              ],
              "title": "App transaction"
            },
            {
              "anchor": "Reviews",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/requesting-app-store-reviews",
                "doc://com.apple.storekit/documentation/StoreKit/SKStoreReviewController"
              ],
              "title": "Reviews"
            },
            {
              "anchor": "Recommendations",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/offering-media-for-sale-in-your-app",
                "doc://com.apple.storekit/documentation/StoreKit/SKStoreProductViewController",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay"
              ],
              "title": "Recommendations"
            },
            {
              "anchor": "Ad-network-attribution",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/ad-network-attribution"
              ],
              "title": "Ad network attribution"
            },
            {
              "anchor": "External-Purchase",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/external-purchase"
              ],
              "title": "External Purchase"
            },
            {
              "anchor": "External-link-account",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/external-link-account"
              ],
              "title": "External link account"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceSetupViewController",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceController"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKLocalizedString",
                "doc://com.apple.storekit/documentation/StoreKit/SK_CLASS_FINAL",
                "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN",
                "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS",
                "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS_AVAILABLE",
                "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS_AVAILABLE_IOS",
                "doc://com.apple.storekit/documentation/StoreKit/SK_EXTERN_CLASS_AVAILABLE_MAC",
                "doc://com.apple.storekit/documentation/StoreKit/StoreKitBundle"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/AppStoreServerAPI",
                "doc://com.apple.documentation/documentation/StoreKitTest",
                "doc://com.apple.documentation/documentation/AppStoreServerNotifications",
                "doc://com.apple.documentation/documentation/appstorereceipts",
                "doc://com.apple.documentation/documentation/AppStoreConnectAPI"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/title",
          "value": "SKOverlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController/title",
          "value": "SKCloudServiceController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreReviewController/title",
          "value": "SKStoreReviewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreReviewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreReviewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreReviewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreReviewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupViewController/title",
          "value": "SKCloudServiceSetupViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceSetupViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceSetupViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceSetupViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductViewController/title",
          "value": "SKStoreProductViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreProductViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKStoreProductViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKStoreProductViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
