{
  "abstract": [
    {
      "text": "Install and manage user space code that extends the capabilities of macOS.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemextensions/documentation/SystemExtensions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "SystemExtensions",
    "modules": [
      {
        "name": "System Extensions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "System Extensions"
  },
  "primaryContentSections": [
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/implementing-drivers-system-extensions-and-kexts"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Extend the capabilities of macOS by installing and managing system extensions—drivers and other low-level code—in user space rather than in the kernel. By running in user space, system extensions can’t compromise the security or stability of macOS. The system grants these extensions a high level of privilege, so they can perform the kinds of tasks previously reserved for kernel extensions (KEXTs).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You use frameworks like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/driverkit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/EndpointSecurity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NetworkExtension",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to write your system extension, and you package the extension in your app bundle. At runtime, use the SystemExtensions framework to install or update the extension on the user’s system. Once installed, an extension remains available for all users on the system. Users can disable the extension by deleting the app, which deletes the extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-system-extension-and-the-host-app",
          "level": 3,
          "text": "Configure the system extension and the host app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To successfully activate your extension, you must adhere to the following rules:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The extension must match your bundle identifier, excluding file extension. For example, a DriverKit extension with bundle identifier ",
                      "type": "text"
                    },
                    {
                      "code": "com.example.usbdriver",
                      "type": "codeVoice"
                    },
                    {
                      "text": " must use the filename ",
                      "type": "text"
                    },
                    {
                      "code": "com.example.usbdriver.dext",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". Similarly, a NetworkExtension extension with bundle identifier ",
                      "type": "text"
                    },
                    {
                      "code": "com.example.networkextension",
                      "type": "codeVoice"
                    },
                    {
                      "text": " must use the filename ",
                      "type": "text"
                    },
                    {
                      "code": "com.example.networkextension.systemextension",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You must use the same Team ID when signing the extension that you use for signing your app, unless the extension has the ",
                      "type": "text"
                    },
                    {
                      "code": "com.apple.developer.system-extension.redistributable",
                      "type": "codeVoice"
                    },
                    {
                      "text": " entitlement.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You must either distribute your app and extension through the Mac App Store, or notarize them. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Security/notarizing-macos-software-before-distribution",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to learn more about notarization.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.install": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app has permission to activate or deactivate system extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.install",
      "kind": "symbol",
      "role": "symbol",
      "title": "System Extension Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.install"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.redistributable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether other development teams may distribute a system extension you create.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.redistributable",
      "kind": "symbol",
      "role": "symbol",
      "title": "System Extension Redistributable Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.redistributable"
    },
    "doc://com.apple.documentation/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/EndpointSecurity"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/NetworkExtension"
    },
    "doc://com.apple.documentation/documentation/Security/notarizing-macos-software-before-distribution": {
      "abstract": [
        {
          "text": "Give users even more confidence in your macOS software by submitting it to Apple for notarization.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/notarizing-macos-software-before-distribution",
      "kind": "article",
      "role": "article",
      "title": "Notarizing macOS software before distribution",
      "type": "topic",
      "url": "/documentation/Security/notarizing-macos-software-before-distribution"
    },
    "doc://com.apple.documentation/documentation/driverkit": {
      "abstract": [
        {
          "text": "Develop device drivers that run in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/driverkit",
      "kind": "symbol",
      "role": "collection",
      "title": "DriverKit",
      "type": "topic",
      "url": "/documentation/driverkit"
    },
    "doc://com.apple.documentation/documentation/driverkit/debugging_and_testing_system_extensions": {
      "abstract": [
        {
          "text": "Debug your system extensions by temporarily disabling the security checks that macOS performs during the installation process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/driverkit/debugging_and_testing_system_extensions",
      "kind": "article",
      "role": "article",
      "title": "Debugging and testing system extensions",
      "type": "topic",
      "url": "/documentation/driverkit/debugging_and_testing_system_extensions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions": {
      "abstract": [
        {
          "text": "Install and manage user space code that extends the capabilities of macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions",
      "kind": "symbol",
      "role": "collection",
      "title": "System Extensions",
      "type": "topic",
      "url": "/documentation/systemextensions"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/NSSystemExtensionUsageDescriptionKey": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is trying to install a system extension bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSystemExtensionUsageDescriptionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/NSSystemExtensionUsageDescriptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSystemExtensionUsageDescriptionKey"
        }
      ],
      "role": "symbol",
      "title": "NSSystemExtensionUsageDescriptionKey",
      "type": "topic",
      "url": "/documentation/systemextensions/nssystemextensionusagedescriptionkey"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSBundleUsageDescriptionKey": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is trying to install a driver extension bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSBundleUsageDescriptionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSBundleUsageDescriptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSBundleUsageDescriptionKey"
        }
      ],
      "role": "symbol",
      "title": "OSBundleUsageDescriptionKey",
      "type": "topic",
      "url": "/documentation/systemextensions/osbundleusagedescriptionkey"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError": {
      "abstract": [
        {
          "text": "An error that describes a failed extension manager request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionError"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionError"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code": {
      "abstract": [
        {
          "text": "Error codes for system extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionErrorDomain": {
      "abstract": [
        {
          "text": "The error domain identifying system extension errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionErrorDomain",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerrordomain"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionInfo"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionInfo"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionInfo",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensioninfo"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionManager": {
      "abstract": [
        {
          "text": "A type that facilitates activation and deactivation of system extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionManager"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionManager"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionManager",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionmanager"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest": {
      "abstract": [
        {
          "text": "A request to activate or deactivate a system extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionRequest"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionRequest"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionRequest",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionrequest"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionsWorkspace": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionsWorkspace"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionsWorkspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionsWorkspace"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionsWorkspace",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionsworkspace"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionsWorkspaceObserver": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionsWorkspaceObserver"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionsWorkspaceObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionsWorkspaceObserver"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionsWorkspaceObserver",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionsworkspaceobserver"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/implementing-drivers-system-extensions-and-kexts": {
      "abstract": [
        {
          "text": "Create drivers and system extensions to communicate with hardware and provide low-level services, and only use kernel extensions for a few tasks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/implementing-drivers-system-extensions-and-kexts",
      "kind": "article",
      "role": "article",
      "title": "Implementing drivers, system extensions, and kexts",
      "type": "topic",
      "url": "/documentation/systemextensions/implementing-drivers-system-extensions-and-kexts"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/installing-system-extensions-and-drivers": {
      "abstract": [
        {
          "text": "Activate system extensions and drivers to make them available to the system, and update or deactivate them as needed.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/installing-system-extensions-and-drivers",
      "kind": "article",
      "role": "article",
      "title": "Installing System Extensions and Drivers",
      "type": "topic",
      "url": "/documentation/systemextensions/installing-system-extensions-and-drivers"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/systemextensions-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/systemextensions-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemExtensions Constants",
      "type": "topic",
      "url": "/documentation/systemextensions/systemextensions-constants"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/implementing-drivers-system-extensions-and-kexts",
        "doc://com.apple.documentation/documentation/driverkit/debugging_and_testing_system_extensions",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.install"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Usage-descriptions",
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/NSSystemExtensionUsageDescriptionKey",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSBundleUsageDescriptionKey"
      ],
      "title": "Usage descriptions"
    },
    {
      "anchor": "Extension-activation-and-deactivation",
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/installing-system-extensions-and-drivers",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionManager",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.redistributable"
      ],
      "title": "Extension activation and deactivation"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionErrorDomain"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/systemextensions-constants"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionInfo",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionsWorkspace"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionsWorkspaceObserver"
      ],
      "title": "Protocols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.systemextensions/documentation/SystemExtensions/implementing-drivers-system-extensions-and-kexts",
                "doc://com.apple.documentation/documentation/driverkit/debugging_and_testing_system_extensions",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.install"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Usage-descriptions",
              "identifiers": [
                "doc://com.apple.systemextensions/documentation/SystemExtensions/NSSystemExtensionUsageDescriptionKey",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSBundleUsageDescriptionKey"
              ],
              "title": "Usage descriptions"
            },
            {
              "anchor": "Extension-activation-and-deactivation",
              "identifiers": [
                "doc://com.apple.systemextensions/documentation/SystemExtensions/installing-system-extensions-and-drivers",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionManager",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionRequest",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.system-extension.redistributable"
              ],
              "title": "Extension activation and deactivation"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionErrorDomain"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.systemextensions/documentation/SystemExtensions/systemextensions-constants"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionInfo",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionsWorkspace"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionsWorkspaceObserver"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionsWorkspaceObserver/title",
          "value": "OSSystemExtensionsWorkspaceObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionsWorkspaceObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionsWorkspaceObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionsWorkspaceObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionsWorkspaceObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequest/title",
          "value": "OSSystemExtensionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1NSSystemExtensionUsageDescriptionKey/title",
          "value": "NSSystemExtensionUsageDescriptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1NSSystemExtensionUsageDescriptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSystemExtensionUsageDescriptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/title",
          "value": "OSSystemExtensionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSBundleUsageDescriptionKey/title",
          "value": "OSBundleUsageDescriptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSBundleUsageDescriptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSBundleUsageDescriptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionManager/title",
          "value": "OSSystemExtensionManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionsWorkspace/title",
          "value": "OSSystemExtensionsWorkspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionsWorkspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionsWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionsWorkspace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionsWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionInfo/title",
          "value": "OSSystemExtensionInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionErrorDomain/title",
          "value": "OSSystemExtensionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemextensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemextensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
