{
  "abstract": [
    {
      "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "TVMLKit is deprecated in tvOS 18 and later. Instead, develop apps for tvOS with ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/documentation/swiftui",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/documentation/uikit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/documentation/swiftui/creating-a-tvos-media-catalog-app-in-swiftui",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "TVMLKit",
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "TVMLKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The TVMLKit framework enables you to evaluate TVMLKit JS and TVML files from within your tvOS app. You can create TVML elements, styles, views, and view controllers through the JavaScript environment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController": {
      "abstract": [
        {
          "text": "An object that bridges the UI, navigation stack, storage, and event handling from JavaScript.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVApplicationController"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVApplicationController"
        }
      ],
      "role": "symbol",
      "title": "TVApplicationController",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext": {
      "abstract": [
        {
          "text": "Launch information provided to the TV application controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVApplicationControllerContext"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVApplicationControllerContext"
        }
      ],
      "role": "symbol",
      "title": "TVApplicationControllerContext",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontrollercontext"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVBrowserViewController": {
      "abstract": [
        {
          "text": "A view controller that presents content in a browsable, full-screen format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVBrowserViewController"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVBrowserViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVBrowserViewController"
        }
      ],
      "role": "symbol",
      "title": "TVBrowserViewController",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvbrowserviewcontroller"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor": {
      "abstract": [
        {
          "text": "The color data used by styles.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVColor"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVColor"
        }
      ],
      "role": "symbol",
      "title": "TVColor",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvcolor"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentError-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVDocumentError"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVDocumentError"
        }
      ],
      "role": "symbol",
      "title": "TVDocumentError",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumenterror-swift.struct"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController": {
      "abstract": [
        {
          "text": "A view controller that represents a TVMLKit document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVDocumentViewController"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVDocumentViewController"
        }
      ],
      "role": "symbol",
      "title": "TVDocumentViewController",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontroller"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementFactory": {
      "abstract": [
        {
          "text": "An object used to register new elements to extend the Apple TV Markup Language (TVML).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVElementFactory"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementFactory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementFactory"
        }
      ],
      "role": "symbol",
      "title": "TVElementFactory",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementfactory"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVImageElement": {
      "abstract": [
        {
          "text": "A representation of a read-only DOM node containing the attributes that describe an image element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVImageElement"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVImageElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVImageElement"
        }
      ],
      "role": "symbol",
      "title": "TVImageElement",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvimageelement"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating": {
      "abstract": [
        {
          "text": "A protocol that defines methods used to create views and view controllers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVInterfaceCreating"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVInterfaceCreating"
        }
      ],
      "role": "symbol",
      "title": "TVInterfaceCreating",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvinterfacecreating"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceFactory": {
      "abstract": [
        {
          "text": "A factory for the creation of views and view controllers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVInterfaceFactory"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceFactory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVInterfaceFactory"
        }
      ],
      "role": "symbol",
      "title": "TVInterfaceFactory",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvinterfacefactory"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMLKitError": {
      "abstract": [
        {
          "text": "Error codes for the TVMLKit error domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMLKitError"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMLKitError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMLKitError"
        }
      ],
      "role": "symbol",
      "title": "TVMLKitError",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmlkiterror"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMLKitErrorDomain": {
      "abstract": [
        {
          "text": "An error occurred in TVMLKit.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMLKitErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMLKitErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMLKitErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "TVMLKitErrorDomain",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmlkiterrordomain"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "TVML_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "TVML_DEPRECATED",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvml_deprecated"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "TVML_DEPRECATED_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "TVML_DEPRECATED_BEGIN",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvml_deprecated_begin"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "TVML_DEPRECATED_END"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "TVML_DEPRECATED_END",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvml_deprecated_end"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED_IOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "TVML_DEPRECATED_IOS"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED_IOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "TVML_DEPRECATED_IOS",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvml_deprecated_ios"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem": {
      "abstract": [
        {
          "text": "A single audio or video item associated with the Apple TV JavaScript player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMediaItem"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMediaItem"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer": {
      "abstract": [
        {
          "text": "A customizable native media player used to control playback from the JavaScript player used in an Apple TV client-server app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlayer"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlayer"
        }
      ],
      "role": "symbol",
      "title": "TVPlayer",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist": {
      "abstract": [
        {
          "text": "A collection of media items associated with the Apple TV JavaScript player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaylist"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaylist"
        }
      ],
      "role": "symbol",
      "title": "TVPlaylist",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaylist"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVStyleFactory": {
      "abstract": [
        {
          "text": "An object used to register custom style properties.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVStyleFactory"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVStyleFactory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVStyleFactory"
        }
      ],
      "role": "symbol",
      "title": "TVStyleFactory",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvstylefactory"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextElement": {
      "abstract": [
        {
          "text": "The textual content for the DOM element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVTextElement"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTextElement"
        }
      ],
      "role": "symbol",
      "title": "TVTextElement",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextelement"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement": {
      "abstract": [
        {
          "text": "A representation of a read-only DOM node.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVViewElement"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVViewElement"
        }
      ],
      "role": "symbol",
      "title": "TVViewElement",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelement"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle": {
      "abstract": [
        {
          "text": "A style applied to a view element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVViewElementStyle"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVViewElementStyle"
        }
      ],
      "role": "symbol",
      "title": "TVViewElementStyle",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelementstyle"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TV_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "TV_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TV_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "TV_EXTERN",
      "type": "topic",
      "url": "/documentation/tvmlkit/tv_extern"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TV_EXTERN_CLASS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "TV_EXTERN_CLASS"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TV_EXTERN_CLASS",
      "kind": "symbol",
      "role": "symbol",
      "title": "TV_EXTERN_CLASS",
      "type": "topic",
      "url": "/documentation/tvmlkit/tv_extern_class"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TV_EXTERN_CLASS_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "TV_EXTERN_CLASS_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TV_EXTERN_CLASS_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "TV_EXTERN_CLASS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/tvmlkit/tv_extern_class_available"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/creating-tvml-elements": {
      "abstract": [
        {
          "text": "Avoid rewriting complex and often used elements by creating a simplified custom element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/creating-tvml-elements",
      "kind": "article",
      "role": "article",
      "title": "Creating TVML Elements",
      "type": "topic",
      "url": "/documentation/tvmlkit/creating-tvml-elements"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/implementing-a-hybrid-tv-app-with-tvmlkit": {
      "abstract": [
        {
          "text": "Display content options with document view controllers and fetch and populate content with TVMLKit JS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/implementing-a-hybrid-tv-app-with-tvmlkit",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing a Hybrid TV App with TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit/implementing-a-hybrid-tv-app-with-tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/tvmlkit-constants": {
      "abstract": [
        {
          "text": "This document defines constants in the TVMLKit framework that are not associated with a particular class.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/tvmlkit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TVMLKit Constants",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmlkit-constants"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/tvmlkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/tvmlkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TVMLKit Enumerations",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmlkit-enumerations"
    },
    "https://developer.apple.com/documentation/swiftui": {
      "identifier": "https://developer.apple.com/documentation/swiftui",
      "title": "SwiftUI",
      "titleInlineContent": [
        {
          "text": "SwiftUI",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/swiftui"
    },
    "https://developer.apple.com/documentation/swiftui/creating-a-tvos-media-catalog-app-in-swiftui": {
      "identifier": "https://developer.apple.com/documentation/swiftui/creating-a-tvos-media-catalog-app-in-swiftui",
      "title": "Creating a tvOS media catalog app in SwiftUI",
      "titleInlineContent": [
        {
          "text": "Creating a tvOS media catalog app in SwiftUI",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/swiftui/creating-a-tvos-media-catalog-app-in-swiftui"
    },
    "https://developer.apple.com/documentation/uikit": {
      "identifier": "https://developer.apple.com/documentation/uikit",
      "title": "UIKit",
      "titleInlineContent": [
        {
          "text": "UIKit",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/uikit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "JavaScript-Environment",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/implementing-a-hybrid-tv-app-with-tvmlkit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext"
      ],
      "title": "JavaScript Environment"
    },
    {
      "anchor": "Views-and-View-Controllers",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceFactory",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVBrowserViewController",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController"
      ],
      "title": "Views and View Controllers"
    },
    {
      "anchor": "Custom-Elements",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementFactory",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVImageElement",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextElement",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/creating-tvml-elements"
      ],
      "title": "Custom Elements"
    },
    {
      "anchor": "Custom-Styles",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVStyleFactory",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor"
      ],
      "title": "Custom Styles"
    },
    {
      "anchor": "Custom-Player",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer"
      ],
      "title": "Custom Player"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMLKitErrorDomain",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMLKitError",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentError-swift.struct"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/tvmlkit-enumerations",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/tvmlkit-constants"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "JavaScript-Environment",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/implementing-a-hybrid-tv-app-with-tvmlkit",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext"
              ],
              "title": "JavaScript Environment"
            },
            {
              "anchor": "Views-and-View-Controllers",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceFactory",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVBrowserViewController",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController"
              ],
              "title": "Views and View Controllers"
            },
            {
              "anchor": "Custom-Elements",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementFactory",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVImageElement",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextElement",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/creating-tvml-elements"
              ],
              "title": "Custom Elements"
            },
            {
              "anchor": "Custom-Styles",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVStyleFactory",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVColor"
              ],
              "title": "Custom Styles"
            },
            {
              "anchor": "Custom-Player",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer"
              ],
              "title": "Custom Player"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMLKitErrorDomain",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMLKitError"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/tvmlkit-enumerations",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/tvmlkit-constants"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED_BEGIN",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED_END",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVML_DEPRECATED_IOS",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TV_EXTERN",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TV_EXTERN_CLASS",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TV_EXTERN_CLASS_AVAILABLE"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "TVMLKit is deprecated in tvOS 18 and later. Instead, develop apps for tvOS with ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/documentation/swiftui",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/documentation/uikit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/documentation/swiftui/creating-a-tvos-media-catalog-app-in-swiftui",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating/title",
          "value": "TVInterfaceCreating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVInterfaceCreating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVInterfaceCreating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVStyleFactory/title",
          "value": "TVStyleFactory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVStyleFactory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVStyleFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVStyleFactory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVStyleFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor/title",
          "value": "TVColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/title",
          "value": "TVViewElementStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElementStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElementStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVTextElement/title",
          "value": "TVTextElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVTextElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTextElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVTextElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTextElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementFactory/title",
          "value": "TVElementFactory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementFactory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementFactory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/title",
          "value": "TVApplicationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVBrowserViewController/title",
          "value": "TVBrowserViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVBrowserViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVBrowserViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVBrowserViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVBrowserViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/title",
          "value": "TVMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceFactory/title",
          "value": "TVInterfaceFactory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceFactory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVInterfaceFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceFactory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVInterfaceFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement/title",
          "value": "TVViewElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVImageElement/title",
          "value": "TVImageElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVImageElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVImageElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVImageElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVImageElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerContext/title",
          "value": "TVApplicationControllerContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaylist/title",
          "value": "TVPlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaylist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaylist/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer/title",
          "value": "TVPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMLKitError/title",
          "value": "TVMLKitError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMLKitError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMLKitError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMLKitError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMLKitError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController/title",
          "value": "TVDocumentViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMLKitErrorDomain/title",
          "value": "TVMLKitErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMLKitErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMLKitErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
