{
  "abstract": [
    {
      "text": "Show common user interface elements from Apple TV in your native app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvuikit/documentation/TVUIKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "TVUIKit",
    "modules": [
      {
        "name": "TVUIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "tvOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "TVUIKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you build an app for tvOS with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you can use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to refine the display of your content for a TV environment. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/TVServices",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework to provide deeper integration between your app and Apple TV.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about combining Apple technologies to build a great Apple TV experience, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/tvos/planning/#build-the-data-structures-youll-use-in-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4133629",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/TVServices"
    },
    "doc://com.apple.documentation/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/UIKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit": {
      "abstract": [
        {
          "text": "Show common user interface elements from Apple TV in your native app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVUIKit",
      "type": "topic",
      "url": "/documentation/tvuikit"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView": {
      "abstract": [
        {
          "text": "A button-like view that responds to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCaptionButtonView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonView"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCardView": {
      "abstract": [
        {
          "text": "A view that responds to focus interaction with a motion effect it applies to all of its subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCardView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCardView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCardView"
        }
      ],
      "role": "symbol",
      "title": "TVCardView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcardview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout": {
      "abstract": [
        {
          "text": "Methods that send notifications of events during cell transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewDelegateFullScreenLayout"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewDelegateFullScreenLayout"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewDelegateFullScreenLayout",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewdelegatefullscreenlayout"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell": {
      "abstract": [
        {
          "text": "A full-screen cell to use in full-screen display format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenCell"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenCell"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenCell",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreencell"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout": {
      "abstract": [
        {
          "text": "A collection view layout that organizes items into a browsable, full-screen display format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayout"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayout"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenLayout",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayout"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes": {
      "abstract": [
        {
          "text": "Attributes to manage the appearance of the collection view’s layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenLayoutAttributes",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayoutattributes"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVDigitEntryViewController": {
      "abstract": [
        {
          "text": "A view controller that enables the user to enter digits, like a passcode, in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVDigitEntryViewController"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVDigitEntryViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVDigitEntryViewController"
        }
      ],
      "role": "symbol",
      "title": "TVDigitEntryViewController",
      "type": "topic",
      "url": "/documentation/tvuikit/tvdigitentryviewcontroller"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupHeaderFooterView": {
      "abstract": [
        {
          "text": "A view that contains header and footer information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVLockupHeaderFooterView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupHeaderFooterView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVLockupHeaderFooterView"
        }
      ],
      "role": "symbol",
      "title": "TVLockupHeaderFooterView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvlockupheaderfooterview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView": {
      "abstract": [
        {
          "text": "A focusable view that presents main content, like a movie poster, and an optional header and footer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVLockupView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVLockupView"
        }
      ],
      "role": "symbol",
      "title": "TVLockupView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvlockupview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupViewComponent": {
      "abstract": [
        {
          "text": "The protocol for responding to lockup view state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVLockupViewComponent"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupViewComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVLockupViewComponent"
        }
      ],
      "role": "symbol",
      "title": "TVLockupViewComponent",
      "type": "topic",
      "url": "/documentation/tvuikit/tvlockupviewcomponent"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVMediaItemContentView": {
      "abstract": [
        {
          "text": "A view that represents media content, such as movies and TV shows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMediaItemContentView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMediaItemContentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMediaItemContentView"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItemContentView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvmediaitemcontentview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentView": {
      "abstract": [
        {
          "text": "A view that contains a circular image of a person or the person’s initials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMonogramContentView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMonogramContentView"
        }
      ],
      "role": "symbol",
      "title": "TVMonogramContentView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvmonogramcontentview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramView": {
      "abstract": [
        {
          "text": "A specialized lockup view that contains a circular image of a person or the person’s initials, along with a footer view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMonogramView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMonogramView"
        }
      ],
      "role": "symbol",
      "title": "TVMonogramView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvmonogramview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVPosterView": {
      "abstract": [
        {
          "text": "An optimized view for displaying an image, a header, and a footer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPosterView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVPosterView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPosterView"
        }
      ],
      "role": "symbol",
      "title": "TVPosterView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvposterview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/creating-immersive-experiences-using-a-full-screen-layout": {
      "abstract": [
        {
          "text": "Display content with a collection view that maximizes the tvOS experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/creating-immersive-experiences-using-a-full-screen-layout",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating immersive experiences using a full-screen layout",
      "type": "topic",
      "url": "/documentation/tvuikit/creating-immersive-experiences-using-a-full-screen-layout"
    },
    "https://developer.apple.com/tvos/planning/#build-the-data-structures-youll-use-in-your-app": {
      "identifier": "https://developer.apple.com/tvos/planning/#build-the-data-structures-youll-use-in-your-app",
      "title": "Planning your tvOS app",
      "titleInlineContent": [
        {
          "text": "Planning your tvOS app",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/tvos/planning/#build-the-data-structures-youll-use-in-your-app"
    },
    "media-4133629": {
      "alt": "A figure containing a hexagonal UIKit framework icon, an arrow pointing to the right, a hexagon with the label TVUIKit, an arrow pointing to the right, and a TV screen. The TV screen shows a centered image of a palm tree, with other images partially visible on either side of the palm tree.",
      "identifier": "media-4133629",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/0ac9f4c161a4bb424a89960bc2d42e7a/media-4133629@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6587b8ca1b47beb93f6f3022dc46425d/media-4133629~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Collections-of-content",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/creating-immersive-experiences-using-a-full-screen-layout",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes"
      ],
      "title": "Collections of content"
    },
    {
      "anchor": "Content-views",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVMediaItemContentView",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentView"
      ],
      "title": "Content views"
    },
    {
      "anchor": "Numeric-input",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVDigitEntryViewController"
      ],
      "title": "Numeric input"
    },
    {
      "anchor": "Lockup-views",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupViewComponent",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupHeaderFooterView",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCardView",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVPosterView",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramView"
      ],
      "title": "Lockup views"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Collections-of-content",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/creating-immersive-experiences-using-a-full-screen-layout",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes"
              ],
              "title": "Collections of content"
            },
            {
              "anchor": "Content-views",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVMediaItemContentView",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentView"
              ],
              "title": "Content views"
            },
            {
              "anchor": "Numeric-input",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVDigitEntryViewController"
              ],
              "title": "Numeric input"
            },
            {
              "anchor": "Lockup-views",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupViewComponent",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupHeaderFooterView",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCardView",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVPosterView",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramView"
              ],
              "title": "Lockup views"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/title",
          "value": "TVCollectionViewDelegateFullScreenLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewDelegateFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewDelegateFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/title",
          "value": "TVCollectionViewFullScreenLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView/title",
          "value": "TVLockupView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVPosterView/title",
          "value": "TVPosterView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVPosterView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPosterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVPosterView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPosterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupHeaderFooterView/title",
          "value": "TVLockupHeaderFooterView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupHeaderFooterView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupHeaderFooterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupHeaderFooterView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupHeaderFooterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/title",
          "value": "TVCollectionViewFullScreenLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/title",
          "value": "TVCollectionViewFullScreenCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCardView/title",
          "value": "TVCardView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCardView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCardView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCardView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCardView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMediaItemContentView/title",
          "value": "TVMediaItemContentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMediaItemContentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItemContentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMediaItemContentView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItemContentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonView/title",
          "value": "TVCaptionButtonView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramView/title",
          "value": "TVMonogramView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMonogramView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMonogramView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVDigitEntryViewController/title",
          "value": "TVDigitEntryViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVDigitEntryViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDigitEntryViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVDigitEntryViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDigitEntryViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramContentView/title",
          "value": "TVMonogramContentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramContentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMonogramContentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramContentView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMonogramContentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupViewComponent/title",
          "value": "TVLockupViewComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupViewComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupViewComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupViewComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupViewComponent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvuikit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvuikit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
