{
  "abstract": [
    {
      "text": "Customize the interface that displays local and remote notifications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "UserNotificationsUI",
    "modules": [
      {
        "name": "User Notifications UI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "User Notifications UI"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Customize how local and remote notifications appear on the user’s device by adding",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a notification content app extension to the bundle of your iOS app. Your extension",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "manages a custom view controller, which you use to present the content from incoming",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "notifications. When a notification arrives, the system displays your view controller",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in addition to, or in place of, the default system interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI": {
      "abstract": [
        {
          "text": "Customize the interface that displays local and remote notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications UI",
      "type": "topic",
      "url": "/documentation/usernotificationsui"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension": {
      "abstract": [
        {
          "text": "An object that presents a custom interface for a delivered local or remote",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtension"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtension"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentExtension",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextension"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/customizing-the-appearance-of-notifications": {
      "abstract": [
        {
          "text": "Customize the appearance of your iOS app’s notification alerts with a notification",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "content app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/customizing-the-appearance-of-notifications",
      "kind": "article",
      "role": "article",
      "title": "Customizing the Appearance of Notifications",
      "type": "topic",
      "url": "/documentation/usernotificationsui/customizing-the-appearance-of-notifications"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Notification-Content-App-Extension",
      "identifiers": [
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/customizing-the-appearance-of-notifications",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension"
      ],
      "title": "Notification Content App Extension"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Notification-Content-App-Extension",
              "identifiers": [
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/customizing-the-appearance-of-notifications",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtension"
              ],
              "title": "Notification Content App Extension"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension/title",
          "value": "UNNotificationContentExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtension"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotificationsui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotificationsui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
