{
  "abstract": [
    {
      "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "VideoToolbox",
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "6.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "6.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.8",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Video Toolbox"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "VideoToolbox is a low-level framework that provides direct access to hardware encoders and decoders. It provides services for video compression and decompression, and for conversion between raster image formats stored in CoreVideo pixel buffers. These services are provided in the form of session objects (compression, decompression, and pixel transfer), which are vended as Core Foundation (CF) types. Apps that don’t need direct access to hardware encoders and decoders shouldn’t need to use VideoToolbox directly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/1490398-error-code-constants": {
      "abstract": [
        {
          "text": "Constants for Video Toolbox operation error codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/1490398-error-code-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Code Constants",
      "type": "topic",
      "url": "/documentation/videotoolbox/1490398-error-code-constants"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCompressionSession-api-collection": {
      "abstract": [
        {
          "text": "An object that compresses video data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCompressionSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTCompressionSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcompressionsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)": {
      "abstract": [
        {
          "text": "Builds a list of supported properties and encoder ID for an encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTCopySupportedPropertyDictionaryForEncoder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "codecType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "encoderSpecification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "encoderIDOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "externalParam",
          "text": "supportedPropertiesOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTCopySupportedPropertyDictionaryForEncoder"
        }
      ],
      "role": "symbol",
      "title": "VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcopysupportedpropertydictionaryforencoder(width:height:codectype:encoderspecification:encoderidout:supportedpropertiesout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoDecoderExtensionProperties": {
      "abstract": [
        {
          "text": "Returns information about the Media Extension video decoder required to decode the specified format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTCopyVideoDecoderExtensionProperties"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoDecoderExtensionProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTCopyVideoDecoderExtensionProperties",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcopyvideodecoderextensionproperties"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoEncoderList(_:_:)": {
      "abstract": [
        {
          "text": "Builds a list of available video encoders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTCopyVideoEncoderList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoEncoderList(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTCopyVideoEncoderList"
        }
      ],
      "role": "symbol",
      "title": "VTCopyVideoEncoderList(_:_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcopyvideoencoderlist(_:_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCreateCGImageFromCVPixelBuffer(_:options:imageOut:)": {
      "abstract": [
        {
          "text": "Creates a Core Graphics bitmap image or image mask using the provided pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTCreateCGImageFromCVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "imageOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCreateCGImageFromCVPixelBuffer(_:options:imageOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTCreateCGImageFromCVPixelBuffer"
        }
      ],
      "role": "symbol",
      "title": "VTCreateCGImageFromCVPixelBuffer(_:options:imageOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcreatecgimagefromcvpixelbuffer(_:options:imageout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession-api-collection": {
      "abstract": [
        {
          "text": "An object that decompresses video data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTDecompressionSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey": {
      "abstract": [
        {
          "text": "A key in a Media Extension extension properties dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "role": "symbol",
      "title": "VTExtensionPropertiesKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessor": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessor"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessor"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessor",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessor"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorConfiguration"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorConfiguration",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorconfiguration"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorError"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorError"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorErrorDomain": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorErrorDomain",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerrordomain"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorFrame": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorFrame"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorFrame"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorFrame",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorframe"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorOpticalFlow": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorOpticalFlow"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorOpticalFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorOpticalFlow"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorOpticalFlow",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessoropticalflow"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorParameters": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorParameters"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameRateConversionConfiguration"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameRateConversionConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VTFrameRateConversionConfiguration",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframerateconversionconfiguration"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration/QualityPrioritization-swift.enum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QualityPrioritization"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration/QualityPrioritization-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QualityPrioritization"
        }
      ],
      "role": "symbol",
      "title": "VTFrameRateConversionConfiguration.QualityPrioritization",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframerateconversionconfiguration/qualityprioritization-swift.enum"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration/Revision-swift.enum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Revision"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration/Revision-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Revision"
        }
      ],
      "role": "symbol",
      "title": "VTFrameRateConversionConfiguration.Revision",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframerateconversionconfiguration/revision-swift.enum"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionParameters": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameRateConversionParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameRateConversionParameters"
        }
      ],
      "role": "symbol",
      "title": "VTFrameRateConversionParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframerateconversionparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionParameters/SubmissionMode-swift.enum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SubmissionMode"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionParameters/SubmissionMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SubmissionMode"
        }
      ],
      "role": "symbol",
      "title": "VTFrameRateConversionParameters.SubmissionMode",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframerateconversionparameters/submissionmode-swift.enum"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSilo-api-collection": {
      "abstract": [
        {
          "text": "An object that stores sample buffers from a multipass encoding session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSilo-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTFrameSilo",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframesilo-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSession": {
      "abstract": [
        {
          "text": "An object that generates per-frame HDR metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationSession"
        }
      ],
      "role": "symbol",
      "title": "VTHDRPerFrameMetadataGenerationSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationsession"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSession-api-collection": {
      "abstract": [
        {
          "text": "An object that generates per-frame HDR metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTHDRPerFrameMetadataGenerationSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Point": {
      "abstract": [
        {
          "text": "A structure that represents a 32-bit integer point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTInt32Point"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Point",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTInt32Point"
        }
      ],
      "role": "symbol",
      "title": "VTInt32Point",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtint32point"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Size": {
      "abstract": [
        {
          "text": "A structure that represents a 32-bit integer size value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTInt32Size"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTInt32Size"
        }
      ],
      "role": "symbol",
      "title": "VTInt32Size",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtint32size"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTIsHardwareDecodeSupported(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the current system supports hardware decode for the specified codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTIsHardwareDecodeSupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTIsHardwareDecodeSupported(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTIsHardwareDecodeSupported"
        }
      ],
      "role": "symbol",
      "title": "VTIsHardwareDecodeSupported(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtishardwaredecodesupported(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTMotionBlurConfiguration"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTMotionBlurConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VTMotionBlurConfiguration",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtmotionblurconfiguration"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration/QualityPrioritization-swift.enum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QualityPrioritization"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration/QualityPrioritization-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QualityPrioritization"
        }
      ],
      "role": "symbol",
      "title": "VTMotionBlurConfiguration.QualityPrioritization",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtmotionblurconfiguration/qualityprioritization-swift.enum"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration/Revision-swift.enum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Revision"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration/Revision-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Revision"
        }
      ],
      "role": "symbol",
      "title": "VTMotionBlurConfiguration.Revision",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtmotionblurconfiguration/revision-swift.enum"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurParameters": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTMotionBlurParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTMotionBlurParameters"
        }
      ],
      "role": "symbol",
      "title": "VTMotionBlurParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtmotionblurparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurParameters/SubmissionMode-swift.enum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SubmissionMode"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurParameters/SubmissionMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SubmissionMode"
        }
      ],
      "role": "symbol",
      "title": "VTMotionBlurParameters.SubmissionMode",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtmotionblurparameters/submissionmode-swift.enum"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMultiPassStorage-api-collection": {
      "abstract": [
        {
          "text": "An object that stores video encoding metadata from a multipass encoding session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMultiPassStorage-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTMultiPassStorage",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtmultipassstorage-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTOpticalFlowConfiguration"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTOpticalFlowConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VTOpticalFlowConfiguration",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtopticalflowconfiguration"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration/QualityPrioritization-swift.enum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QualityPrioritization"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration/QualityPrioritization-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QualityPrioritization"
        }
      ],
      "role": "symbol",
      "title": "VTOpticalFlowConfiguration.QualityPrioritization",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtopticalflowconfiguration/qualityprioritization-swift.enum"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration/Revision-swift.enum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Revision"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration/Revision-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Revision"
        }
      ],
      "role": "symbol",
      "title": "VTOpticalFlowConfiguration.Revision",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtopticalflowconfiguration/revision-swift.enum"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTOpticalFlowParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTOpticalFlowParameters"
        }
      ],
      "role": "symbol",
      "title": "VTOpticalFlowParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtopticalflowparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters/SubmissionMode-swift.enum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SubmissionMode"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters/SubmissionMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SubmissionMode"
        }
      ],
      "role": "symbol",
      "title": "VTOpticalFlowParameters.SubmissionMode",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtopticalflowparameters/submissionmode-swift.enum"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession-api-collection": {
      "abstract": [
        {
          "text": "An object that rotates source pixel buffers to destination pixel buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTPixelRotationSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtpixelrotationsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelTransferSession-api-collection": {
      "abstract": [
        {
          "text": "An object converts video data from source pixel buffers to destination pixel buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelTransferSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTPixelTransferSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtpixeltransfersession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession": {
      "abstract": [
        {
          "text": "An object that processes frames in camera native formats such as RAW or Bayer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSession"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession-api-collection": {
      "abstract": [
        {
          "text": "An object that processes frames in camera native formats such as RAW or Bayer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTRAWProcessingSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoDecoders()": {
      "abstract": [
        {
          "text": "Loads decoders appropriate for the client’s professional video workflows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRegisterProfessionalVideoWorkflowVideoDecoders"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoDecoders()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTRegisterProfessionalVideoWorkflowVideoDecoders"
        }
      ],
      "role": "symbol",
      "title": "VTRegisterProfessionalVideoWorkflowVideoDecoders()",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtregisterprofessionalvideoworkflowvideodecoders()"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoEncoders()": {
      "abstract": [
        {
          "text": "Loads encoders appropriate for the client’s professional video workflows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRegisterProfessionalVideoWorkflowVideoEncoders"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoEncoders()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTRegisterProfessionalVideoWorkflowVideoEncoders"
        }
      ],
      "role": "symbol",
      "title": "VTRegisterProfessionalVideoWorkflowVideoEncoders()",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtregisterprofessionalvideoworkflowvideoencoders()"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterSupplementalVideoDecoderIfAvailable(_:)": {
      "abstract": [
        {
          "text": "Registers a video decoder for the specified codec type, if one exists on the current system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRegisterSupplementalVideoDecoderIfAvailable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterSupplementalVideoDecoderIfAvailable(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTRegisterSupplementalVideoDecoderIfAvailable"
        }
      ],
      "role": "symbol",
      "title": "VTRegisterSupplementalVideoDecoderIfAvailable(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtregistersupplementalvideodecoderifavailable(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection": {
      "abstract": [
        {
          "text": "An abstract object that provides the common interface to configure VideoToolbox session objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
        }
      ],
      "role": "symbol",
      "title": "VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER",
      "type": "topic",
      "url": "/documentation/videotoolbox/vt_support_colorsync_pixel_transfer"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VideoToolbox-reference": {
      "abstract": [],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VideoToolbox-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VideoToolbox Reference",
      "type": "topic",
      "url": "/documentation/videotoolbox/videotoolbox-reference"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-live-streaming": {
      "abstract": [
        {
          "text": "Configure a compression session to encode video for live streaming.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-live-streaming",
      "kind": "article",
      "role": "sampleCode",
      "title": "Encoding video for live streaming",
      "type": "topic",
      "url": "/documentation/videotoolbox/encoding-video-for-live-streaming"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-low-latency-conferencing": {
      "abstract": [
        {
          "text": "Configure a compression session to optimize encoding for video-conferencing apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-low-latency-conferencing",
      "kind": "article",
      "role": "sampleCode",
      "title": "Encoding video for low-latency conferencing",
      "type": "topic",
      "url": "/documentation/videotoolbox/encoding-video-for-low-latency-conferencing"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-offline-transcoding": {
      "abstract": [
        {
          "text": "Configure a compression session to transcode video in offline workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-offline-transcoding",
      "kind": "article",
      "role": "sampleCode",
      "title": "Encoding video for offline transcoding",
      "type": "topic",
      "url": "/documentation/videotoolbox/encoding-video-for-offline-transcoding"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/video-encoder-list-keys": {
      "abstract": [
        {
          "text": "Dictionary key constants to use to retrieve video encoder information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/video-encoder-list-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Video Encoder List Keys",
      "type": "topic",
      "url": "/documentation/videotoolbox/video-encoder-list-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Compression",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-low-latency-conferencing",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-live-streaming",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-offline-transcoding",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCompressionSession-api-collection",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession-api-collection",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSilo-api-collection",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMultiPassStorage-api-collection"
      ],
      "title": "Compression"
    },
    {
      "anchor": "Transformation",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelTransferSession-api-collection",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession-api-collection"
      ],
      "title": "Transformation"
    },
    {
      "anchor": "RAW-Processing",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession"
      ],
      "title": "RAW Processing"
    },
    {
      "anchor": "Media-Extension",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey"
      ],
      "title": "Media Extension"
    },
    {
      "anchor": "HDR-Metadata",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSession"
      ],
      "title": "HDR Metadata"
    },
    {
      "anchor": "Codec-Support",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTIsHardwareDecodeSupported(_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoEncoders()",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoDecoders()",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterSupplementalVideoDecoderIfAvailable(_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoEncoderList(_:_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/video-encoder-list-keys"
      ],
      "title": "Codec Support"
    },
    {
      "anchor": "Utilities",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCreateCGImageFromCVPixelBuffer(_:options:imageOut:)"
      ],
      "title": "Utilities"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Point",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Size",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/1490398-error-code-constants"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Reference",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VideoToolbox-reference"
      ],
      "title": "Reference"
    },
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessor",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorFrame",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorOpticalFlow",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionParameters",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurParameters",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorParameters"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorErrorDomain"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Compression",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-low-latency-conferencing",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-live-streaming",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/encoding-video-for-offline-transcoding",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCompressionSession-api-collection",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession-api-collection",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSilo-api-collection",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMultiPassStorage-api-collection"
              ],
              "title": "Compression"
            },
            {
              "anchor": "Transformation",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelTransferSession-api-collection",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession-api-collection"
              ],
              "title": "Transformation"
            },
            {
              "anchor": "RAW-Processing",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession-api-collection"
              ],
              "title": "RAW Processing"
            },
            {
              "anchor": "Media-Extension",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoDecoderExtensionProperties"
              ],
              "title": "Media Extension"
            },
            {
              "anchor": "HDR-Metadata",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSession-api-collection"
              ],
              "title": "HDR Metadata"
            },
            {
              "anchor": "Codec-Support",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTIsHardwareDecodeSupported(_:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoEncoders()",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoDecoders()",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterSupplementalVideoDecoderIfAvailable(_:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoEncoderList(_:_:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/video-encoder-list-keys"
              ],
              "title": "Codec Support"
            },
            {
              "anchor": "Utilities",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCreateCGImageFromCVPixelBuffer(_:options:imageOut:)"
              ],
              "title": "Utilities"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Point",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Size",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/1490398-error-code-constants"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VideoToolbox-reference"
              ],
              "title": "Reference"
            },
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessor",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorFrame",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorOpticalFlow",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionParameters",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurParameters",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorParameters"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorErrorDomain"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration/QualityPrioritization-swift.enum",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration/Revision-swift.enum",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionParameters/SubmissionMode-swift.enum",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration/QualityPrioritization-swift.enum",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration/Revision-swift.enum",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurParameters/SubmissionMode-swift.enum",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration/QualityPrioritization-swift.enum",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration/Revision-swift.enum",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters/SubmissionMode-swift.enum"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurParameters~1SubmissionMode-swift.enum/title",
          "value": "VTMotionBlurParametersSubmissionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurParameters~1SubmissionMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurParametersSubmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurParameters~1SubmissionMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurParametersSubmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorOpticalFlow/title",
          "value": "VTFrameProcessorOpticalFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorOpticalFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorOpticalFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorOpticalFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorOpticalFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration~1QualityPrioritization-swift.enum/title",
          "value": "VTOpticalFlowConfigurationQualityPrioritization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration~1QualityPrioritization-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowConfigurationQualityPrioritization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration~1QualityPrioritization-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowConfigurationQualityPrioritization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterProfessionalVideoWorkflowVideoDecoders()/title",
          "value": "VTRegisterProfessionalVideoWorkflowVideoDecoders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterProfessionalVideoWorkflowVideoDecoders()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRegisterProfessionalVideoWorkflowVideoDecoders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters/title",
          "value": "VTOpticalFlowParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters~1SubmissionMode-swift.enum/title",
          "value": "VTOpticalFlowParametersSubmissionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters~1SubmissionMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowParametersSubmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters~1SubmissionMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowParametersSubmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorErrorDomain/title",
          "value": "VTFrameProcessorErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code/title",
          "value": "VTFrameProcessorError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCopyVideoEncoderList(_:_:)/title",
          "value": "VTCopyVideoEncoderList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCopyVideoEncoderList(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTCopyVideoEncoderList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTIsHardwareDecodeSupported(_:)/title",
          "value": "VTIsHardwareDecodeSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTIsHardwareDecodeSupported(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTIsHardwareDecodeSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionParameters/title",
          "value": "VTFrameRateConversionParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration~1Revision-swift.enum/title",
          "value": "VTFrameRateConversionConfigurationRevision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration~1Revision-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionConfigurationRevision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration~1Revision-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionConfigurationRevision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Point/title",
          "value": "VTInt32Point"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Point/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTInt32Point"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Point/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTInt32Point"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorFrame/title",
          "value": "VTFrameProcessorFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration/title",
          "value": "VTOpticalFlowConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterSupplementalVideoDecoderIfAvailable(_:)/title",
          "value": "VTRegisterSupplementalVideoDecoderIfAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterSupplementalVideoDecoderIfAvailable(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRegisterSupplementalVideoDecoderIfAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)/title",
          "value": "VTCopySupportedPropertyDictionaryForEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTCopySupportedPropertyDictionaryForEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration~1QualityPrioritization-swift.enum/title",
          "value": "VTFrameRateConversionConfigurationQualityPrioritization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration~1QualityPrioritization-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionConfigurationQualityPrioritization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration~1QualityPrioritization-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionConfigurationQualityPrioritization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration~1Revision-swift.enum/title",
          "value": "VTMotionBlurConfigurationRevision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration~1Revision-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurConfigurationRevision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration~1Revision-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurConfigurationRevision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorParameters/title",
          "value": "VTFrameProcessorParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurParameters/title",
          "value": "VTMotionBlurParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCreateCGImageFromCVPixelBuffer(_:options:imageOut:)/title",
          "value": "VTCreateCGImageFromCVPixelBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCreateCGImageFromCVPixelBuffer(_:options:imageOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTCreateCGImageFromCVPixelBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/title",
          "value": "VTRAWProcessingSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration~1Revision-swift.enum/title",
          "value": "VTOpticalFlowConfigurationRevision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration~1Revision-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowConfigurationRevision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration~1Revision-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowConfigurationRevision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Size/title",
          "value": "VTInt32Size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTInt32Size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Size/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTInt32Size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER/title",
          "value": "VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterProfessionalVideoWorkflowVideoEncoders()/title",
          "value": "VTRegisterProfessionalVideoWorkflowVideoEncoders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterProfessionalVideoWorkflowVideoEncoders()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRegisterProfessionalVideoWorkflowVideoEncoders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/title",
          "value": "VTExtensionPropertiesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTExtensionPropertiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTExtensionPropertiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration/title",
          "value": "VTFrameRateConversionConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration/title",
          "value": "VTMotionBlurConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration~1QualityPrioritization-swift.enum/title",
          "value": "VTMotionBlurConfigurationQualityPrioritization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration~1QualityPrioritization-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurConfigurationQualityPrioritization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration~1QualityPrioritization-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurConfigurationQualityPrioritization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionParameters~1SubmissionMode-swift.enum/title",
          "value": "VTFrameRateConversionParametersSubmissionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionParameters~1SubmissionMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionParametersSubmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionParameters~1SubmissionMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionParametersSubmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessor/title",
          "value": "VTFrameProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration/title",
          "value": "VTFrameProcessorConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
