{
  "abstract": [
    {
      "text": "Support TV provider and Apple TV app functionality.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "VideoSubscriberAccount",
    "modules": [
      {
        "name": "Video Subscriber Account"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.14",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "Video Subscriber Account"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "VideoSubscriberAccount",
              "type": "codeVoice"
            },
            {
              "text": " provides APIs to help you create apps that require secure communication with a TV provider’s authentication service. The framework also informs the Apple TV app about whether your user has a subscription and the details of that subscription.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount": {
      "abstract": [
        {
          "text": "Support TV provider and Apple TV app functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Subscriber Account",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountApplicationProvider": {
      "abstract": [
        {
          "text": "An object to display app-specific providers in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSAccountApplicationProvider"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountApplicationProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSAccountApplicationProvider"
        }
      ],
      "role": "symbol",
      "title": "VSAccountApplicationProvider",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountapplicationprovider"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManager": {
      "abstract": [
        {
          "text": "The object that coordinates your app’s authentication requests with a TV provider’s authentication service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSAccountManager"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSAccountManager"
        }
      ],
      "role": "symbol",
      "title": "VSAccountManager",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmanager"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAppleSubscription-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VSAppleSubscription"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAppleSubscription-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "VSAppleSubscription",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsapplesubscription-c.class"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAppleSubscription-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSAppleSubscription"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAppleSubscription-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSAppleSubscription"
        }
      ],
      "role": "symbol",
      "title": "VSAppleSubscription",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsapplesubscription-swift.struct"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError": {
      "abstract": [
        {
          "text": "Error information in the framework error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSError"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSError"
        }
      ],
      "role": "symbol",
      "title": "VSError",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code": {
      "abstract": [
        {
          "text": "Error codes in the framework error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorDomain": {
      "abstract": [
        {
          "text": "The domain for all errors in the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "VSErrorDomain",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrordomain"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyAccountProviderResponse": {
      "abstract": [
        {
          "text": "The account provider’s error-response object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyAccountProviderResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyAccountProviderResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyAccountProviderResponse"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeyAccountProviderResponse",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeyaccountproviderresponse"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponse": {
      "abstract": [
        {
          "text": "The subscription provider’s SAML error response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponse"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeySAMLResponse",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeysamlresponse"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponseStatus": {
      "abstract": [
        {
          "text": "The subscription provider’s SAML error-response status code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponseStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeySAMLResponseStatus",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeysamlresponsestatus"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyUnsupportedProviderIdentifier": {
      "abstract": [
        {
          "text": "The identifier of the unsupported subscription provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyUnsupportedProviderIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyUnsupportedProviderIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyUnsupportedProviderIdentifier"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeyUnsupportedProviderIdentifier",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeyunsupportedprovideridentifier"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSSubscription": {
      "abstract": [
        {
          "text": "An object that describes a subscriber’s access to content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSSubscription"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSSubscription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSSubscription"
        }
      ],
      "role": "symbol",
      "title": "VSSubscription",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vssubscription"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSSubscriptionRegistrationCenter": {
      "abstract": [
        {
          "text": "An object that stores subscription information that the system provides to the Apple TV app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSSubscriptionRegistrationCenter"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSSubscriptionRegistrationCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSSubscriptionRegistrationCenter"
        }
      ],
      "role": "symbol",
      "title": "VSSubscriptionRegistrationCenter",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vssubscriptionregistrationcenter"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-c.class": {
      "abstract": [
        {
          "text": "An object that represents a user’s account with a TV provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VSUserAccount"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "VSUserAccount",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-c.class"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct": {
      "abstract": [
        {
          "text": "An object that represents a user’s account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSUserAccount"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSUserAccount"
        }
      ],
      "role": "symbol",
      "title": "VSUserAccount",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager": {
      "abstract": [
        {
          "text": "The object that coordinates your app’s user account actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSUserAccountManager"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSUserAccountManager"
        }
      ],
      "role": "symbol",
      "title": "VSUserAccountManager",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccountmanager"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VS_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "VS_EXPORT",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vs_export"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VS_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "VS_EXTERN",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vs_extern"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_INIT_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VS_INIT_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_INIT_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "VS_INIT_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vs_init_unavailable"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_INTERNAL_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VS_INTERNAL_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_INTERNAL_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "VS_INTERNAL_EXPORT",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vs_internal_export"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_INTERNAL_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VS_INTERNAL_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_INTERNAL_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "VS_INTERNAL_EXTERN",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vs_internal_extern"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "TV-provider-authentication",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManager"
      ],
      "title": "TV provider authentication"
    },
    {
      "anchor": "TV-app-integration",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSSubscription",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSSubscriptionRegistrationCenter",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountApplicationProvider"
      ],
      "title": "TV app integration"
    },
    {
      "anchor": "User-account-management",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct"
      ],
      "title": "User account management"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorDomain",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponse",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponseStatus",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyAccountProviderResponse",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyUnsupportedProviderIdentifier",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAppleSubscription-swift.struct"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "TV-provider-authentication",
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManager"
              ],
              "title": "TV provider authentication"
            },
            {
              "anchor": "TV-app-integration",
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSSubscription",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSSubscriptionRegistrationCenter",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountApplicationProvider"
              ],
              "title": "TV app integration"
            },
            {
              "anchor": "User-account-management",
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-c.class"
              ],
              "title": "User account management"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorDomain",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponse",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponseStatus",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyAccountProviderResponse",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyUnsupportedProviderIdentifier",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAppleSubscription-c.class"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_EXPORT",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_EXTERN",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_INIT_UNAVAILABLE",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_INTERNAL_EXPORT",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VS_INTERNAL_EXTERN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyUnsupportedProviderIdentifier/title",
          "value": "VSErrorInfoKeyUnsupportedProviderIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyUnsupportedProviderIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeyUnsupportedProviderIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager/title",
          "value": "VSUserAccountManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSUserAccountManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSUserAccountManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponse/title",
          "value": "VSErrorInfoKeySAMLResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeySAMLResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSSubscriptionRegistrationCenter/title",
          "value": "VSSubscriptionRegistrationCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSSubscriptionRegistrationCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSSubscriptionRegistrationCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSSubscriptionRegistrationCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSSubscriptionRegistrationCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountManager/title",
          "value": "VSAccountManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountApplicationProvider/title",
          "value": "VSAccountApplicationProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountApplicationProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountApplicationProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountApplicationProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountApplicationProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/title",
          "value": "VSErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponseStatus/title",
          "value": "VSErrorInfoKeySAMLResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeySAMLResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSSubscription/title",
          "value": "VSSubscription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSSubscription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSSubscription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorDomain/title",
          "value": "VSErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyAccountProviderResponse/title",
          "value": "VSErrorInfoKeyAccountProviderResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyAccountProviderResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeyAccountProviderResponse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videosubscriberaccount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videosubscriberaccount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
