{
  "abstract": [
    {
      "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "WatchKit",
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "WatchKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The WatchKit framework provides infrastructure for creating watchOS apps, including an extension delegate that manages background tasks, extended runtime sessions, and Siri intents. The framework also performs other support tasks, such as accessing information about the user’s Apple Watch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3987848",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can also use WatchKit to design your app’s user interface in a storyboard, connecting UI elements to an interface controller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Building your app with SwiftUI gives you more control over the user interface than designing it in a storyboard. When creating a new watchOS app, strongly consider using ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/SwiftUI",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/watchOS-Apps/building_a_watchos_app",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on building watchOS apps, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/watchOS-Apps",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "SwiftUI-PageImage-card.png": {
      "alt": "A black Swift logo on a swirly blue and purple background.",
      "identifier": "SwiftUI-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1450d0b30a6b024e10c148e3f31dafe9/SwiftUI-PageImage-card~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b1de0de086f81a5d0eac3839a0af6e6f/SwiftUI-PageImage-card@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app requires network access on launch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKPrefersNetworkUponForeground",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground"
    },
    "doc://com.apple.documentation/documentation/SwiftUI": {
      "abstract": [
        {
          "text": "Declare the user interface and behavior for your app on every platform.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI",
      "images": [
        {
          "identifier": "SwiftUI-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "SwiftUI",
      "type": "topic",
      "url": "/documentation/SwiftUI"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/watchOS-Apps": {
      "abstract": [
        {
          "text": "Build watchOS apps that combine complications, notifications, and Siri to create a personal experience on Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/watchOS-Apps",
      "images": [
        {
          "identifier": "watchOSApps-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "watchOS apps",
      "type": "topic",
      "url": "/documentation/watchOS-Apps"
    },
    "doc://com.apple.documentation/documentation/watchOS-Apps/building_a_watchos_app": {
      "abstract": [
        {
          "text": "Set up your app’s life cycle and create its user interface with SwiftUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/watchOS-Apps/building_a_watchos_app",
      "kind": "article",
      "role": "article",
      "title": "Building a watchOS app",
      "type": "topic",
      "url": "/documentation/watchOS-Apps/building_a_watchos_app"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/NowPlayingView": {
      "abstract": [
        {
          "text": "A view that displays the system’s Now Playing interface so that the user can control audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NowPlayingView"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/NowPlayingView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NowPlayingView"
        }
      ],
      "role": "symbol",
      "title": "NowPlayingView",
      "type": "topic",
      "url": "/documentation/watchkit/nowplayingview"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplication": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for apps with a single watchOS app target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplication"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplication"
        }
      ],
      "role": "symbol",
      "title": "WKApplication",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplication"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate": {
      "abstract": [
        {
          "text": "A collection of methods that manages the app-level behavior for a single-target watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplicationDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationDelegate"
        }
      ],
      "role": "symbol",
      "title": "WKApplicationDelegate",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates the application object and the application delegate, and sets up the app’s event cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplicationMain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationMain"
        }
      ],
      "role": "symbol",
      "title": "WKApplicationMain(_:_:_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationmain(_:_:_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession": {
      "abstract": [
        {
          "text": "A session that continues to run your app after the user has stopped interacting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSession"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSession"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSession",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesession"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtension": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for extension-based apps running in watchOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtension"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtension"
        }
      ],
      "role": "symbol",
      "title": "WKExtension",
      "type": "topic",
      "url": "/documentation/watchkit/wkextension"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate": {
      "abstract": [
        {
          "text": "A collection of methods that manages the app-level behavior of a WatchKit extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtensionDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtensionDelegate"
        }
      ],
      "role": "symbol",
      "title": "WKExtensionDelegate",
      "type": "topic",
      "url": "/documentation/watchkit/wkextensiondelegate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice": {
      "abstract": [
        {
          "text": "An object that provides information about the user’s Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceDevice"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceDevice"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceDevice",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacedevice"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKit-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKit-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/watchkit/watchkit-macros"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError": {
      "abstract": [
        {
          "text": "An error reported by WatchKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WatchKitError"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitError"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code": {
      "abstract": [
        {
          "text": "Error codes reported by WatchKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError.Code",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/code"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitErrorDomain": {
      "abstract": [
        {
          "text": "The domain for WatchKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WatchKitErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "WatchKitErrorDomain",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterrordomain"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/background-execution": {
      "abstract": [
        {
          "text": "Manage background sessions and tasks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/background-execution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Background execution",
      "type": "topic",
      "url": "/documentation/watchkit/background-execution"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/interacting-with-bluetooth-peripherals-during-background-app-refresh": {
      "abstract": [
        {
          "text": "Keep your complications up-to-date by reading values from a Bluetooth peripheral while your app is running in the background.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/interacting-with-bluetooth-peripherals-during-background-app-refresh",
      "kind": "article",
      "role": "sampleCode",
      "title": "Interacting with Bluetooth peripherals during background app refresh",
      "type": "topic",
      "url": "/documentation/watchkit/interacting-with-bluetooth-peripherals-during-background-app-refresh"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/life-cycles": {
      "abstract": [
        {
          "text": "Receive and respond to life-cycle notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/life-cycles",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Life cycles",
      "type": "topic",
      "url": "/documentation/watchkit/life-cycles"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project": {
      "abstract": [
        {
          "text": "Create a new watchOS project or add a watch target to an existing iOS project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting up a watchOS project",
      "type": "topic",
      "url": "/documentation/watchkit/setting-up-a-watchos-project"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/storyboard-support": {
      "abstract": [
        {
          "text": "Connect your code to storyboard elements using interface controllers, interface objects, and event handlers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/storyboard-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Storyboard support",
      "type": "topic",
      "url": "/documentation/watchkit/storyboard-support"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/using-extended-runtime-sessions": {
      "abstract": [
        {
          "text": "Create an extended runtime session that continues running your app after the user stops interacting with it.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/using-extended-runtime-sessions",
      "kind": "article",
      "role": "article",
      "title": "Using extended runtime sessions",
      "type": "topic",
      "url": "/documentation/watchkit/using-extended-runtime-sessions"
    },
    "media-3987848": {
      "alt": "An illustration showing a blueprint. The central image displays a drawing of an Apple Watch with gears inside it. There are sketches of icons on either side of the watch.",
      "identifier": "media-3987848",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/66915464f240eff7cbd25784f1bb497e/media-3987848@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/66915464f240eff7cbd25784f1bb497e/media-3987848~dark@2x.png"
        }
      ]
    },
    "watchOSApps-PageImage-card.png": {
      "alt": null,
      "identifier": "watchOSApps-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2e82e5f258fb084d7b684889cabbe515/watchOSApps-PageImage-card~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5e043ca96ec9c9e5579649124c448c35/watchOSApps-PageImage-card@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "App-structure",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplication",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtension",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground"
      ],
      "title": "App structure"
    },
    {
      "anchor": "Runtime-management",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/background-execution",
        "doc://com.apple.watchkit/documentation/WatchKit/life-cycles",
        "doc://com.apple.watchkit/documentation/WatchKit/using-extended-runtime-sessions",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession",
        "doc://com.apple.watchkit/documentation/WatchKit/interacting-with-bluetooth-peripherals-during-background-app-refresh"
      ],
      "title": "Runtime management"
    },
    {
      "anchor": "User-interface",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/storyboard-support",
        "doc://com.apple.watchkit/documentation/WatchKit/NowPlayingView"
      ],
      "title": "User interface"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "App-structure",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/setting-up-a-watchos-project",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplication",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtension",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtensionDelegate",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationMain(_:_:_:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDevice",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/WKPrefersNetworkUponForeground"
              ],
              "title": "App structure"
            },
            {
              "anchor": "Runtime-management",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/background-execution",
                "doc://com.apple.watchkit/documentation/WatchKit/life-cycles",
                "doc://com.apple.watchkit/documentation/WatchKit/using-extended-runtime-sessions",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession",
                "doc://com.apple.watchkit/documentation/WatchKit/interacting-with-bluetooth-peripherals-during-background-app-refresh"
              ],
              "title": "Runtime management"
            },
            {
              "anchor": "User-interface",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/storyboard-support"
              ],
              "title": "User interface"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code",
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitErrorDomain"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKit-macros"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/title",
          "value": "WKApplicationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtensionDelegate/title",
          "value": "WKExtensionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtensionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtensionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtensionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtensionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension/title",
          "value": "WKExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/title",
          "value": "WatchKitErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSession/title",
          "value": "WKExtendedRuntimeSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/title",
          "value": "WKApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDevice/title",
          "value": "WKInterfaceDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitErrorDomain/title",
          "value": "WatchKitErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationMain(_:_:_:)/title",
          "value": "WKApplicationMain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationMain(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationMain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
