{
  "abstract": [
    {
      "text": "Create extensions to add commands to the Xcode source editor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcodekit/documentation/XcodeKit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "XcodeKit",
    "modules": [
      {
        "name": "XcodeKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.12",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "XcodeKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Using the XcodeKit framework, you can customize Xcode with source editor extensions to add functionality and specialized behavior to the source editor. Source editor extensions provide a group of editor commands alongside the built-in commands in the Editor menu in Xcode.  Source editor extensions can read and modify the contents of a source file, as well as read and modify the current text selection within the editor. Include source editor extensions in developer apps distributed on the Mac App Store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit": {
      "abstract": [
        {
          "text": "Create extensions to add commands to the Xcode source editor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "XcodeKit",
      "type": "topic",
      "url": "/documentation/xcodekit"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommand": {
      "abstract": [
        {
          "text": "The protocol you implement to handle command invocations in a source editor extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommand"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommand"
        }
      ],
      "role": "symbol",
      "title": "XCSourceEditorCommand",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourceeditorcommand"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation": {
      "abstract": [
        {
          "text": "An object that identifies the command issued to your extension and provides the contents of the active source editor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommandInvocation"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommandInvocation"
        }
      ],
      "role": "symbol",
      "title": "XCSourceEditorCommandInvocation",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourceeditorcommandinvocation"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorExtension": {
      "abstract": [
        {
          "text": "The protocol you implement to create Xcode source editor extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceEditorExtension"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceEditorExtension"
        }
      ],
      "role": "symbol",
      "title": "XCSourceEditorExtension",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourceeditorextension"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextBuffer": {
      "abstract": [
        {
          "text": "A buffer you use to access and modify the text contents and text selections in a source editor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceTextBuffer"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceTextBuffer"
        }
      ],
      "role": "symbol",
      "title": "XCSourceTextBuffer",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourcetextbuffer"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextPosition": {
      "abstract": [
        {
          "text": "A zero-based position in a source editor, defined by a line number and column number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceTextPosition"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceTextPosition"
        }
      ],
      "role": "symbol",
      "title": "XCSourceTextPosition",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourcetextposition"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange": {
      "abstract": [
        {
          "text": "A half-open range of text in a buffer you use to select text or specify the insertion point for new text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceTextRange"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceTextRange"
        }
      ],
      "role": "symbol",
      "title": "XCSourceTextRange",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourcetextrange"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/creating-a-source-editor-extension": {
      "abstract": [
        {
          "text": "Add and configure a source editor extension in your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/creating-a-source-editor-extension",
      "kind": "article",
      "role": "article",
      "title": "Creating a Source Editor Extension",
      "type": "topic",
      "url": "/documentation/xcodekit/creating-a-source-editor-extension"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/testing-your-source-editor-extension": {
      "abstract": [
        {
          "text": "Launch a special instance of Xcode to test your source editor extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/testing-your-source-editor-extension",
      "kind": "article",
      "role": "article",
      "title": "Testing Your Source Editor Extension",
      "type": "topic",
      "url": "/documentation/xcodekit/testing-your-source-editor-extension"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/xcodekit-version-constants": {
      "abstract": [
        {
          "text": "Determine the version of XcodeKit available in an instance of Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/xcodekit-version-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "XcodeKit Version Constants",
      "type": "topic",
      "url": "/documentation/xcodekit/xcodekit-version-constants"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Add a source editor extension target to an Xcode project and activate its scheme.",
          "type": "text"
        }
      ],
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/creating-a-source-editor-extension",
        "doc://com.apple.xcodekit/documentation/XcodeKit/testing-your-source-editor-extension",
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorExtension"
      ],
      "title": "Essentials"
    },
    {
      "abstract": [
        {
          "text": "Respond to commands by changing the text contents and text selections in a source editor.",
          "type": "text"
        }
      ],
      "anchor": "Editor-Commands",
      "identifiers": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommand",
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation"
      ],
      "title": "Editor Commands"
    },
    {
      "anchor": "Source-Text",
      "identifiers": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextBuffer",
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextPosition",
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange"
      ],
      "title": "Source Text"
    },
    {
      "anchor": "XcodeKit-Constants",
      "identifiers": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/xcodekit-version-constants"
      ],
      "title": "XcodeKit Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Add a source editor extension target to an Xcode project and activate its scheme.",
                  "type": "text"
                }
              ],
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/creating-a-source-editor-extension",
                "doc://com.apple.xcodekit/documentation/XcodeKit/testing-your-source-editor-extension",
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorExtension"
              ],
              "title": "Essentials"
            },
            {
              "abstract": [
                {
                  "text": "Respond to commands by changing the text contents and text selections in a source editor.",
                  "type": "text"
                }
              ],
              "anchor": "Editor-Commands",
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommand",
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation"
              ],
              "title": "Editor Commands"
            },
            {
              "anchor": "Source-Text",
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextBuffer",
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextPosition",
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange"
              ],
              "title": "Source Text"
            },
            {
              "anchor": "XcodeKit-Constants",
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/xcodekit-version-constants"
              ],
              "title": "XcodeKit Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommand/title",
          "value": "XCSourceEditorCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextPosition/title",
          "value": "XCSourceTextPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceTextPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceTextPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorExtension/title",
          "value": "XCSourceEditorExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation/title",
          "value": "XCSourceEditorCommandInvocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommandInvocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommandInvocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextBuffer/title",
          "value": "XCSourceTextBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceTextBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceTextBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextRange/title",
          "value": "XCSourceTextRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceTextRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceTextRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcodekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcodekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
