{
  "abstract": [
    {
      "text": "Access the path of the macOS SDK available on the host system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcselect/documentation/xcselect"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "xcselect",
    "modules": [
      {
        "name": "xcselect"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.15",
        "name": "macOS"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "xcselect"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system provides ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xcselect/documentation/xcselect/xcselect_host_sdk_path",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", a function to locate the path to a macOS SDK version for building executables, libraries, and other content that runs on the local Mac. If you don’t use Xcode build tools, you can use this function to get the macOS SDK version you need.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "code": "xcselect",
                  "type": "codeVoice"
                },
                {
                  "text": " framework is not available in Swift.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcselect/documentation/xcselect": {
      "abstract": [
        {
          "text": "Access the path of the macOS SDK available on the host system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect",
      "kind": "symbol",
      "role": "collection",
      "title": "xcselect",
      "type": "topic",
      "url": "/documentation/xcselect"
    },
    "doc://com.apple.xcselect/documentation/xcselect/enumerations": {
      "abstract": [
        {
          "text": "Enumerations in the xcselect framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Enumerations",
      "type": "topic",
      "url": "/documentation/xcselect/enumerations"
    },
    "doc://com.apple.xcselect/documentation/xcselect/macros": {
      "abstract": [
        {
          "text": "Macros in the xcselect framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/xcselect/macros"
    },
    "doc://com.apple.xcselect/documentation/xcselect/xcselect_host_sdk_path": {
      "abstract": [
        {
          "text": "Returns the path to a version of the macOS SDK for building executables, libraries, and other content that run on the local Mac.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "xcselect_host_sdk_path"
        }
      ],
      "identifier": "doc://com.apple.xcselect/documentation/xcselect/xcselect_host_sdk_path",
      "kind": "symbol",
      "role": "symbol",
      "title": "xcselect_host_sdk_path",
      "type": "topic",
      "url": "/documentation/xcselect/xcselect_host_sdk_path"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "macOS-SDK-Paths",
              "identifiers": [
                "doc://com.apple.xcselect/documentation/xcselect/xcselect_host_sdk_path"
              ],
              "title": "macOS SDK Paths"
            },
            {
              "anchor": "Reference",
              "identifiers": [
                "doc://com.apple.xcselect/documentation/xcselect/macros",
                "doc://com.apple.xcselect/documentation/xcselect/enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcselect"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcselect"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
