{
  "abstract": [
    {
      "text": "Replicate sequences of interactions and make sure that your app’s user interface behaves as intended.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 1"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 1"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "XCUIAutomation",
    "modules": [
      {
        "name": "XCUIAutomation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.3",
        "name": "Xcode"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "XCUIAutomation"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "UI testing lets you verify that when you change parts of your app’s data model, your app’s view controllers, views, and controls respond appropriately. You can also create test cases to manipulate your app’s views and controls, as if a person is interacting with your interface.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Use the XCUIAutomation framework to control your app’s user interface and inspect its state.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCTest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to write tests that control your app using XCUIAutomation, and check if your app’s state matches your expectations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "UI testing isn’t available to apps you build using the visionOS SDK. You can still use it to test compatible iPad and iPhone apps that you build using the iOS SDK but run in visionOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/XCTest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation": {
      "abstract": [
        {
          "text": "Replicate sequences of interactions and make sure that your app’s user interface behaves as intended.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
      "kind": "symbol",
      "role": "collection",
      "title": "XCUIAutomation",
      "type": "topic",
      "url": "/documentation/xcuiautomation"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIApplication": {
      "abstract": [
        {
          "text": "A proxy that can launch, monitor, and terminate a test application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIApplication"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIApplication"
        }
      ],
      "role": "symbol",
      "title": "XCUIApplication",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiapplication"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUICoordinate": {
      "abstract": [
        {
          "text": "A location on screen relative to a UI element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUICoordinate"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUICoordinate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUICoordinate"
        }
      ],
      "role": "symbol",
      "title": "XCUICoordinate",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuicoordinate"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIDevice": {
      "abstract": [
        {
          "text": "A proxy that can simulate physical buttons, device orientation, and Siri interaction for an iOS, watchOS, or tvOS device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIDevice"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIDevice"
        }
      ],
      "role": "symbol",
      "title": "XCUIDevice",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuidevice"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementAttributes": {
      "abstract": [
        {
          "text": "Attributes exposed by UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementAttributes"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributes"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementAttributes",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielementattributes"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementQuery": {
      "abstract": [
        {
          "text": "An object that defines the search criteria a test uses to identify UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementQuery"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementQuery",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielementquery"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementSnapshot": {
      "abstract": [
        {
          "text": "A set of attributes to express a snapshot of an element’s attributes and descendant user interface hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshot"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementSnapshot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshot"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementSnapshot",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielementsnapshot"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementSnapshotProviding": {
      "abstract": [
        {
          "text": "A method to capture a snapshot of an element’s attributes and descendant user interface hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshotProviding"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementSnapshotProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshotProviding"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementSnapshotProviding",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielementsnapshotproviding"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementTypeQueryProvider": {
      "abstract": [
        {
          "text": "A type that provides ready-made queries for locating descendant UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementTypeQueryProvider"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementTypeQueryProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeQueryProvider"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementTypeQueryProvider",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielementtypequeryprovider"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote": {
      "abstract": [
        {
          "text": "A class that simulates interaction with a physical remote control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIRemote"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemote"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemote",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremote"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreen": {
      "abstract": [
        {
          "text": "A physical screen attached to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIScreen"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIScreen"
        }
      ],
      "role": "symbol",
      "title": "XCUIScreen",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiscreen"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreenshot": {
      "abstract": [
        {
          "text": "A captured image of a screen, app, or UI element state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIScreenshot"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreenshot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIScreenshot"
        }
      ],
      "role": "symbol",
      "title": "XCUIScreenshot",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiscreenshot"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreenshotProviding": {
      "abstract": [
        {
          "text": "A type that can provide a screenshot of its current UI state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIScreenshotProviding"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreenshotProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIScreenshotProviding"
        }
      ],
      "role": "symbol",
      "title": "XCUIScreenshotProviding",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiscreenshotproviding"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUISiriService": {
      "abstract": [
        {
          "text": "A proxy that simulates a device’s Siri interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUISiriService"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUISiriService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUISiriService"
        }
      ],
      "role": "symbol",
      "title": "XCUISiriService",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuisiriservice"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUISystem": {
      "abstract": [
        {
          "text": "A proxy that provides an interface to OS-specific properties and actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUISystem"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUISystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUISystem"
        }
      ],
      "role": "symbol",
      "title": "XCUISystem",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuisystem"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_DEPRECATED_WITH_DIRECT_REPLACEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUI_DEPRECATED_WITH_DIRECT_REPLACEMENT"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_DEPRECATED_WITH_DIRECT_REPLACEMENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUI_DEPRECATED_WITH_DIRECT_REPLACEMENT",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcui_deprecated_with_direct_replacement"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_DEPRECATED_WITH_REPLACEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUI_DEPRECATED_WITH_REPLACEMENT"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_DEPRECATED_WITH_REPLACEMENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUI_DEPRECATED_WITH_REPLACEMENT",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcui_deprecated_with_replacement"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_DEPRECATED_WITH_SWIFT_REPLACEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUI_DEPRECATED_WITH_SWIFT_REPLACEMENT"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_DEPRECATED_WITH_SWIFT_REPLACEMENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUI_DEPRECATED_WITH_SWIFT_REPLACEMENT",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcui_deprecated_with_swift_replacement"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUI_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUI_EXPORT",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcui_export"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_NOESCAPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUI_NOESCAPE"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_NOESCAPE",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUI_NOESCAPE",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcui_noescape"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_PROTECTED_RESOURCES_RESET_API_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUI_PROTECTED_RESOURCES_RESET_API_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_PROTECTED_RESOURCES_RESET_API_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUI_PROTECTED_RESOURCES_RESET_API_AVAILABLE",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcui_protected_resources_reset_api_available"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_SIMULATOR_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUI_SIMULATOR_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_SIMULATOR_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUI_SIMULATOR_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcui_simulator_unavailable"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_SWIFT_MAIN_ACTOR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUI_SWIFT_MAIN_ACTOR"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_SWIFT_MAIN_ACTOR",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUI_SWIFT_MAIN_ACTOR",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcui_swift_main_actor"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_UI_TESTING_AVAILABLE": {
      "abstract": [
        {
          "text": "Indicates whether the current environment supports UI testing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUI_UI_TESTING_AVAILABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_UI_TESTING_AVAILABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUI_UI_TESTING_AVAILABLE"
        }
      ],
      "role": "symbol",
      "title": "XCUI_UI_TESTING_AVAILABLE",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcui_ui_testing_available"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUI_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUI_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcui_unavailable"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_WARN_UNUSED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCUI_WARN_UNUSED"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_WARN_UNUSED",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUI_WARN_UNUSED",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcui_warn_unused"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/recording-ui-automation-for-testing": {
      "abstract": [
        {
          "text": "Capture and replay interaction sequences to verify your app’s behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/recording-ui-automation-for-testing",
      "kind": "article",
      "role": "article",
      "title": "Recording UI automation for testing",
      "type": "topic",
      "url": "/documentation/xcuiautomation/recording-ui-automation-for-testing"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/recording-ui-automation-for-testing"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "UI-element-queries",
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementQuery",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementTypeQueryProvider"
      ],
      "title": "UI element queries"
    },
    {
      "anchor": "UI-elements",
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementAttributes",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementSnapshot",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementSnapshotProviding",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUICoordinate"
      ],
      "title": "UI elements"
    },
    {
      "anchor": "Application-lifecycle",
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIApplication"
      ],
      "title": "Application lifecycle"
    },
    {
      "anchor": "Screenshots",
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreen",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreenshot",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreenshotProviding"
      ],
      "title": "Screenshots"
    },
    {
      "anchor": "Device-simulation",
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIDevice",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUISystem",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUISiriService"
      ],
      "title": "Device simulation"
    },
    {
      "anchor": "Remote-control-simulation",
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote"
      ],
      "title": "Remote control simulation"
    },
    {
      "anchor": "UI-testing-availability",
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_UI_TESTING_AVAILABLE"
      ],
      "title": "UI testing availability"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/recording-ui-automation-for-testing"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "UI-element-queries",
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementQuery",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementTypeQueryProvider"
              ],
              "title": "UI element queries"
            },
            {
              "anchor": "UI-elements",
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementAttributes",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementSnapshot",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElementSnapshotProviding",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUICoordinate"
              ],
              "title": "UI elements"
            },
            {
              "anchor": "Application-lifecycle",
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIApplication"
              ],
              "title": "Application lifecycle"
            },
            {
              "anchor": "Screenshots",
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreen",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreenshot",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIScreenshotProviding"
              ],
              "title": "Screenshots"
            },
            {
              "anchor": "Device-simulation",
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIDevice",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUISystem",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUISiriService"
              ],
              "title": "Device simulation"
            },
            {
              "anchor": "Remote-control-simulation",
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote"
              ],
              "title": "Remote control simulation"
            },
            {
              "anchor": "UI-testing-availability",
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_UI_TESTING_AVAILABLE"
              ],
              "title": "UI testing availability"
            },
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_DEPRECATED_WITH_DIRECT_REPLACEMENT",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_DEPRECATED_WITH_REPLACEMENT",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_DEPRECATED_WITH_SWIFT_REPLACEMENT",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_EXPORT",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_NOESCAPE",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_PROTECTED_RESOURCES_RESET_API_AVAILABLE",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_SIMULATOR_UNAVAILABLE",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_SWIFT_MAIN_ACTOR",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_UNAVAILABLE",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUI_WARN_UNUSED"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUISiriService/title",
          "value": "XCUISiriService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUISiriService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUISiriService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUISiriService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUISiriService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIApplication/title",
          "value": "XCUIApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementSnapshot/title",
          "value": "XCUIElementSnapshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementSnapshot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementSnapshot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/title",
          "value": "XCUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementAttributes/title",
          "value": "XCUIElementAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemote/title",
          "value": "XCUIRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemote/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIScreenshotProviding/title",
          "value": "XCUIScreenshotProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIScreenshotProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIScreenshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIScreenshotProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIScreenshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIDevice/title",
          "value": "XCUIDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIScreen/title",
          "value": "XCUIScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIScreenshot/title",
          "value": "XCUIScreenshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIScreenshot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIScreenshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIScreenshot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIScreenshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUICoordinate/title",
          "value": "XCUICoordinate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUICoordinate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUICoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUICoordinate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUICoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementSnapshotProviding/title",
          "value": "XCUIElementSnapshotProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementSnapshotProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementSnapshotProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementTypeQueryProvider/title",
          "value": "XCUIElementTypeQueryProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementTypeQueryProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeQueryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementTypeQueryProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeQueryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUISystem/title",
          "value": "XCUISystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUISystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUISystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUISystem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUISystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementQuery/title",
          "value": "XCUIElementQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElementQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUI_UI_TESTING_AVAILABLE/title",
          "value": "XCUI_UI_TESTING_AVAILABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUI_UI_TESTING_AVAILABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUI_UI_TESTING_AVAILABLE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcuiautomation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcuiautomation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
