{
  "abstract": [
    {
      "text": "An unknown repetition frequency.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/unknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INRecurrenceFrequency@INRecurrenceFrequencyUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknown"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INRecurrenceFrequencyUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INRecurrenceFrequency.unknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency": {
      "abstract": [
        {
          "text": "The time frame for which the rule applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRecurrenceFrequency"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRecurrenceFrequency"
        }
      ],
      "role": "symbol",
      "title": "INRecurrenceFrequency",
      "type": "topic",
      "url": "/documentation/intents/inrecurrencefrequency"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/daily": {
      "abstract": [
        {
          "text": "A time range that repeats on a daily basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daily"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/daily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRecurrenceFrequencyDaily"
        }
      ],
      "role": "symbol",
      "title": "INRecurrenceFrequency.daily",
      "type": "topic",
      "url": "/documentation/intents/inrecurrencefrequency/daily"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/hourly": {
      "abstract": [
        {
          "text": "A time range that repeats on an hourly basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hourly"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/hourly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRecurrenceFrequencyHourly"
        }
      ],
      "role": "symbol",
      "title": "INRecurrenceFrequency.hourly",
      "type": "topic",
      "url": "/documentation/intents/inrecurrencefrequency/hourly"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/minute": {
      "abstract": [
        {
          "text": "A time range that repeats every minute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minute"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/minute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRecurrenceFrequencyMinute"
        }
      ],
      "role": "symbol",
      "title": "INRecurrenceFrequency.minute",
      "type": "topic",
      "url": "/documentation/intents/inrecurrencefrequency/minute"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/monthly": {
      "abstract": [
        {
          "text": "A date range that repeats on a monthly basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monthly"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/monthly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRecurrenceFrequencyMonthly"
        }
      ],
      "role": "symbol",
      "title": "INRecurrenceFrequency.monthly",
      "type": "topic",
      "url": "/documentation/intents/inrecurrencefrequency/monthly"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/unknown": {
      "abstract": [
        {
          "text": "An unknown repetition frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRecurrenceFrequencyUnknown"
        }
      ],
      "role": "symbol",
      "title": "INRecurrenceFrequency.unknown",
      "type": "topic",
      "url": "/documentation/intents/inrecurrencefrequency/unknown"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/weekly": {
      "abstract": [
        {
          "text": "A date range that repeats on a weekly basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weekly"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/weekly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRecurrenceFrequencyWeekly"
        }
      ],
      "role": "symbol",
      "title": "INRecurrenceFrequency.weekly",
      "type": "topic",
      "url": "/documentation/intents/inrecurrencefrequency/weekly"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/yearly": {
      "abstract": [
        {
          "text": "A date range that repeats on a yearly basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yearly"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/yearly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRecurrenceFrequencyYearly"
        }
      ],
      "role": "symbol",
      "title": "INRecurrenceFrequency.yearly",
      "type": "topic",
      "url": "/documentation/intents/inrecurrencefrequency/yearly"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/minute",
        "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/hourly",
        "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/daily",
        "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/weekly",
        "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/monthly",
        "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/yearly"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INRecurrenceFrequencyUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRecurrenceFrequencyUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/minute",
                "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/hourly",
                "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/daily",
                "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/weekly",
                "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/monthly",
                "doc://com.apple.sirikit/documentation/Intents/INRecurrenceFrequency/yearly"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INRecurrenceFrequencyUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1yearly/title",
          "value": "INRecurrenceFrequencyYearly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1yearly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRecurrenceFrequencyYearly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1unknown/title",
          "value": "INRecurrenceFrequencyUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRecurrenceFrequencyUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1monthly/title",
          "value": "INRecurrenceFrequencyMonthly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1monthly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRecurrenceFrequencyMonthly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1minute/title",
          "value": "INRecurrenceFrequencyMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1minute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRecurrenceFrequencyMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1daily/title",
          "value": "INRecurrenceFrequencyDaily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1daily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRecurrenceFrequencyDaily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency/title",
          "value": "INRecurrenceFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRecurrenceFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRecurrenceFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1hourly/title",
          "value": "INRecurrenceFrequencyHourly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1hourly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRecurrenceFrequencyHourly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1weekly/title",
          "value": "INRecurrenceFrequencyWeekly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRecurrenceFrequency~1weekly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRecurrenceFrequencyWeekly"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inrecurrencefrequency/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inrecurrencefrequency/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
