{
  "abstract": [
    {
      "text": "A constant that indicates the postback version.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@SKAdTestPostbackVersion",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKAdTestPostbackVersion"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKAdTestPostbackVersion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SKAdTestPostbackVersion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This postback version number corresponds to a version of SKAdNetwork. All versions of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKAdNetwork",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " have specific instructions for signing ads and validating postbacks. The testing environment supports testing the versions indicated by the constants listed in the Getting SKAdNetwork Versions section below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about versions, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/StoreKit/SKAdNetwork": {
      "abstract": [
        {
          "text": "A class that validates advertisement-driven app installations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdNetwork"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKAdNetwork",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKAdNetwork",
      "type": "topic",
      "url": "/documentation/StoreKit/SKAdNetwork"
    },
    "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes": {
      "abstract": [
        {
          "text": "Learn about the features in each SKAdNetwork version.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes",
      "kind": "article",
      "role": "article",
      "title": "SKAdNetwork release notes",
      "type": "topic",
      "url": "/documentation/StoreKit/skadnetwork-release-notes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback": {
      "abstract": [
        {
          "text": "A test postback that contains ad conversion information in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestPostback"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostback"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackResponse": {
      "abstract": [
        {
          "text": "The status and error information for a postback that the system sends in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackResponse"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackResponse"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestPostbackResponse",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostbackresponse"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion": {
      "abstract": [
        {
          "text": "A constant that indicates the postback version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackVersion"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackVersion"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestPostbackVersion",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostbackversion"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initialize a version object with the supplied raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostbackversion/init(rawvalue:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version2_1": {
      "abstract": [
        {
          "text": "A constant that represents SKAdNetwork version 2.1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version2_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version2_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackVersion2_1"
        }
      ],
      "role": "symbol",
      "title": "version2_1",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostbackversion/version2_1"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version2_2": {
      "abstract": [
        {
          "text": "A constant that represents SKAdNetwork version 2.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version2_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version2_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackVersion2_2"
        }
      ],
      "role": "symbol",
      "title": "version2_2",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostbackversion/version2_2"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version3_0": {
      "abstract": [
        {
          "text": "A constant that represents SKAdNetwork version 3.0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version3_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version3_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackVersion3_0"
        }
      ],
      "role": "symbol",
      "title": "version3_0",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostbackversion/version3_0"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version4_0": {
      "abstract": [
        {
          "text": "A constant that represents SKAdNetwork version 4.0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version4_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version4_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackVersion4_0"
        }
      ],
      "role": "symbol",
      "title": "version4_0",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostbackversion/version4_0"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession": {
      "abstract": [
        {
          "text": "The class you use to test ad impressions and postbacks in Xcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestSession"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestSession"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestSession",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestsession"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork": {
      "abstract": [
        {
          "text": "Validate your ad impressions and test your postbacks by creating unit tests using the StoreKit Test framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork",
      "kind": "article",
      "role": "sampleCode",
      "title": "Testing and validating ad impression signatures and postbacks for SKAdNetwork",
      "type": "topic",
      "url": "/documentation/storekittest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Ad-impression-and-postback-testing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackResponse"
      ],
      "title": "Ad impression and postback testing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-SKAdNetwork-Versions",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version4_0",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version3_0",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version2_2",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version2_1"
      ],
      "title": "Getting SKAdNetwork Versions"
    },
    {
      "anchor": "Initializing-the-Postback-Version",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/init(rawValue:)"
      ],
      "title": "Initializing the Postback Version"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKAdTestPostbackVersion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-SKAdNetwork-Versions",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version4_0",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version3_0",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version2_2",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version2_1"
              ],
              "title": "Getting SKAdNetwork Versions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Ad-impression-and-postback-testing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackResponse"
              ],
              "title": "Ad impression and postback testing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKAdTestPostbackVersion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion/title",
          "value": "SKAdTestPostbackVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKAdNetwork/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKAdNetwork"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version4_0/title",
          "value": "SKAdTestPostbackVersion4_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version4_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion4_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession/title",
          "value": "SKAdTestSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/title",
          "value": "SKAdTestPostback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version3_0/title",
          "value": "SKAdTestPostbackVersion3_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version3_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion3_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackResponse/title",
          "value": "SKAdTestPostbackResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version2_1/title",
          "value": "SKAdTestPostbackVersion2_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version2_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion2_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version2_2/title",
          "value": "SKAdTestPostbackVersion2_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version2_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion2_2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/skadtestpostbackversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/skadtestpostbackversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
