{
  "abstract": [
    {
      "text": "An error the testing environment returns for SKAdNetwork testing errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC17SKAdTestErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKAdTestError"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKAdTestError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SKAdTestError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKAdTestError"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Unit tests that call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/setPostbacks(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/flushPostbacks(responses:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validateImpression(parameters:publicKey:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validate(_:publicKey:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", can throw ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " errors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you call the unit test methods ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validateImpression(parameters:publicKey:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validate(_:publicKey:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validateWebAdImpressionPayload(_:publicKey:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to validate your ad impression, the system may return signature-related errors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/setPostbacks(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/flushPostbacks(responses:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you may get postback-related errors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError": {
      "abstract": [
        {
          "text": "An error the testing environment returns for SKAdNetwork testing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code": {
      "abstract": [
        {
          "text": "Enumerated error codes related to ad network testing in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/conflictingSource": {
      "abstract": [
        {
          "text": "This error code is unused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conflictingSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/conflictingSource",
      "kind": "symbol",
      "role": "symbol",
      "title": "conflictingSource",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/conflictingsource"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/errorDomain": {
      "abstract": [
        {
          "text": "The domain of the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/errordomain"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/excessivePostbacks": {
      "abstract": [
        {
          "text": "Too many postbacks submitted to the test session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excessivePostbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/excessivePostbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "excessivePostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/excessivepostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidCampaignId": {
      "abstract": [
        {
          "text": "The campaign ID isn’t an integer between one and one hundred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCampaignId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidCampaignId",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidCampaignId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidcampaignid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidConversionValue": {
      "abstract": [
        {
          "text": "The conversion value isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConversionValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidConversionValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidConversionValue",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidconversionvalue"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidImpressionId": {
      "abstract": [
        {
          "text": "The impression ID isn’t a valid UUID string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidImpressionId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidImpressionId",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidImpressionId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidimpressionid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidPostbackURL": {
      "abstract": [
        {
          "text": "The URL for the postback isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPostbackURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidPostbackURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidPostbackURL",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidpostbackurl"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidRunnerUpPostback": {
      "abstract": [
        {
          "text": "A non-winning postback is defined with a version prior to version 3, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRunnerUpPostback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidRunnerUpPostback",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidRunnerUpPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidrunneruppostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidSourceAppAdamId": {
      "abstract": [
        {
          "text": "The app ID is less than zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSourceAppAdamId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidSourceAppAdamId",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidSourceAppAdamId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidsourceappadamid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidSourceDomain": {
      "abstract": [
        {
          "text": "The source domain isn’t in the correct format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSourceDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidSourceDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidSourceDomain",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidsourcedomain"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidSourceIdentifier": {
      "abstract": [
        {
          "text": "The postback’s identifier isn’t two, three, or four digits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSourceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidSourceIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidSourceIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidsourceidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidVersion": {
      "abstract": [
        {
          "text": "A postback contains an incorrect version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidVersion",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidversion"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidWinningPostbackCount": {
      "abstract": [
        {
          "text": "The number of winning postbacks isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidWinningPostbackCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidWinningPostbackCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidWinningPostbackCount",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidwinningpostbackcount"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/malformedPostbacks": {
      "abstract": [
        {
          "text": "The postback in the testing environment is malformed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "malformedPostbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/malformedPostbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "malformedPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/malformedpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/misplacedWinnerPostback": {
      "abstract": [
        {
          "text": "A winning postback wasn’t found in the first position, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "misplacedWinnerPostback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/misplacedWinnerPostback",
      "kind": "symbol",
      "role": "symbol",
      "title": "misplacedWinnerPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/misplacedwinnerpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingPostbacks": {
      "abstract": [
        {
          "text": "The testing environment doesn’t have any postbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingPostbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingPostbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/missingpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingSignature": {
      "abstract": [
        {
          "text": "The signature for the ad is missing, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingSignature",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingSignature",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/missingsignature"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingWinningPostback": {
      "abstract": [
        {
          "text": "The testing environment is missing a winning postback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingWinningPostback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingWinningPostback",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingWinningPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/missingwinningpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/noPendingPostbacks": {
      "abstract": [
        {
          "text": "The test session doesn’t have any pending postbacks to send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noPendingPostbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/noPendingPostbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "noPendingPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/nopendingpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidKey": {
      "abstract": [
        {
          "text": "The public key isn’t a valid cryptographic key, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureInvalidKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureInvalidKey",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signatureinvalidkey"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidOrder": {
      "abstract": [
        {
          "text": "The order of the parameters in the signature is invalid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureInvalidOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidOrder",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureInvalidOrder",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signatureinvalidorder"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAdNetworkId": {
      "abstract": [
        {
          "text": "The signature is missing an ad network identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingAdNetworkId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAdNetworkId",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingAdNetworkId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingadnetworkid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAppAdamId": {
      "abstract": [
        {
          "text": "The signature is missing the app item identifier for the advertised app, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingAppAdamId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAppAdamId",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingAppAdamId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingappadamid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingCampaignId": {
      "abstract": [
        {
          "text": "The signature is missing the campaign identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingCampaignId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingCampaignId",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingCampaignId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingcampaignid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingFidelityType": {
      "abstract": [
        {
          "text": "The signature is missing the fidelity type, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingFidelityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingFidelityType",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingFidelityType",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingfidelitytype"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingNonce": {
      "abstract": [
        {
          "text": "The signature is missing the nonce, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingNonce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingNonce",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingNonce",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingnonce"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceAppAdamId": {
      "abstract": [
        {
          "text": "The signature is missing the source app item identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceAppAdamId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceAppAdamId",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingSourceAppAdamId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingsourceappadamid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceDomain": {
      "abstract": [
        {
          "text": "The signature is missing the source domain, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingSourceDomain",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingsourcedomain"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceIdentifier": {
      "abstract": [
        {
          "text": "The signature is missing the source identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingSourceIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingsourceidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingTimestamp": {
      "abstract": [
        {
          "text": "The signature is missing a timestamp, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingTimestamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingTimestamp",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingtimestamp"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureUnknownError": {
      "abstract": [
        {
          "text": "An unknown error occurred with the signature in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureUnknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureUnknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureUnknownError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signatureunknownerror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureVerificationFailed": {
      "abstract": [
        {
          "text": "The signature verification failed in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureVerificationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureVerificationFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureVerificationFailed",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signatureverificationfailed"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/unknownError": {
      "abstract": [
        {
          "text": "An unknown error occurred in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/unknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/unknownerror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/unlinkedWinningPostbacks": {
      "abstract": [
        {
          "text": "The postbacks aren’t correctly related to one another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlinkedWinningPostbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/unlinkedWinningPostbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "unlinkedWinningPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/unlinkedwinningpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the error domain for SKAdNetwork testing in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestErrorDomain",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterrordomain"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/flushPostbacks(responses:)": {
      "abstract": [
        {
          "text": "Sends the test postbacks and handles the responses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flushPostbacks"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "responses"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKANTestPostbackResponseHandler",
          "text": "SKANTestPostbackResponseHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/flushPostbacks(responses:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flushPostbacksWithResponses:"
        }
      ],
      "role": "symbol",
      "title": "flushPostbacks(responses:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestsession/flushpostbacks(responses:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/setPostbacks(_:)": {
      "abstract": [
        {
          "text": "Add test postbacks to the test session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPostbacks"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKAdTestPostback",
          "text": "SKAdTestPostback"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/setPostbacks(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPostbacks:error:"
        }
      ],
      "role": "symbol",
      "title": "setPostbacks(_:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestsession/setpostbacks(_:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validate(_:publicKey:)": {
      "abstract": [
        {
          "text": "Validates an impression for a view-through ad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKAdImpression",
          "text": "SKAdImpression"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "publicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validate(_:publicKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validateImpression:publicKey:error:"
        }
      ],
      "role": "symbol",
      "title": "validate(_:publicKey:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestsession/validate(_:publickey:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validateImpression(parameters:publicKey:)": {
      "abstract": [
        {
          "text": "Validates an impression for a StoreKit-rendered ad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validateImpression"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "publicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validateImpression(parameters:publicKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validateImpressionWithParameters:publicKey:error:"
        }
      ],
      "role": "symbol",
      "title": "validateImpression(parameters:publicKey:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestsession/validateimpression(parameters:publickey:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validateWebAdImpressionPayload(_:publicKey:)": {
      "abstract": [
        {
          "text": "Validates an impression for a web ad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validateWebAdImpressionPayload"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "publicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validateWebAdImpressionPayload(_:publicKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validateWebAdImpressionPayload:publicKey:error:"
        }
      ],
      "role": "symbol",
      "title": "validateWebAdImpressionPayload(_:publicKey:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestsession/validatewebadimpressionpayload(_:publickey:)"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Ad-impression-and-postback-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestErrorDomain"
      ],
      "title": "Ad impression and postback errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Signature-Errors",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingSignature",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidKey",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidOrder",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAdNetworkId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingFidelityType",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingNonce",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceDomain",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingTimestamp",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureUnknownError",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureVerificationFailed"
      ],
      "title": "Getting Signature Errors"
    },
    {
      "anchor": "Getting-Postback-Errors",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/excessivePostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidConversionValue",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidPostbackURL",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidRunnerUpPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidWinningPostbackCount",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/malformedPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/misplacedWinnerPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingWinningPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/noPendingPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/unlinkedWinningPostbacks"
      ],
      "title": "Getting Postback Errors"
    },
    {
      "anchor": "Getting-Other-Errors",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidVersion",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidImpressionId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidSourceAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidSourceDomain",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidSourceIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/unknownError"
      ],
      "title": "Getting Other Errors"
    },
    {
      "abstract": [
        {
          "text": "These errors can occur in version 3 and earlier.",
          "type": "text"
        }
      ],
      "anchor": "Getting-Older-Errors",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidCampaignId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingCampaignId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/conflictingSource"
      ],
      "title": "Getting Older Errors"
    },
    {
      "anchor": "Initializing-the-Error-Objects",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code"
      ],
      "title": "Initializing the Error Objects"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1flushPostbacks(responses:)/title",
          "value": "flushPostbacksWithResponses:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1flushPostbacks(responses:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "flushPostbacksWithResponses:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1validateImpression(parameters:publicKey:)/title",
          "value": "validateImpressionWithParameters:publicKey:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1validateImpression(parameters:publicKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validateImpressionWithParameters:publicKey:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1validateWebAdImpressionPayload(_:publicKey:)/title",
          "value": "validateWebAdImpressionPayload:publicKey:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1validateWebAdImpressionPayload(_:publicKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validateWebAdImpressionPayload:publicKey:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestErrorDomain/title",
          "value": "SKAdTestErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/title",
          "value": "SKAdTestErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1validate(_:publicKey:)/title",
          "value": "validateImpression:publicKey:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1validate(_:publicKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validateImpression:publicKey:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1setPostbacks(_:)/title",
          "value": "setPostbacks:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1setPostbacks(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPostbacks:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/skadtesterror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
