{
  "abstract": [
    {
      "text": "A test postback that contains ad conversion information in the testing environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKAdTestPostback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKAdTestPostback"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKAdTestPostback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SKAdTestPostback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKAdTestPostback"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this class to create test postbacks to use for unit testing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the production environment, the system creates a postback after a user installs an advertised app. The advertised app is responsible for registering the installation and may update the conversion value. The system sends the postback after a timer expires.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the testing environment, you can mimic a postback by creating it directly. You control the property values within the postback. Use it to test your app’s ability to register the app installation and update conversion values, and to test your server’s ability to receive postbacks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback": {
      "abstract": [
        {
          "text": "A test postback that contains ad conversion information in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestPostback"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostback"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/adCampaignIdentifier": {
      "abstract": [
        {
          "text": "A number that represents the advertising network’s campaign.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adCampaignIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/adCampaignIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adCampaignIdentifier"
        }
      ],
      "role": "symbol",
      "title": "adCampaignIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/adcampaignidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/adNetworkIdentifier": {
      "abstract": [
        {
          "text": "A string that represents the advertising network’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adNetworkIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/adNetworkIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adNetworkIdentifier"
        }
      ],
      "role": "symbol",
      "title": "adNetworkIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/adnetworkidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/appStoreItemIdentifier": {
      "abstract": [
        {
          "text": "The item identifier of the app that this ad impression advertises.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/appStoreItemIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appStoreItemIdentifier"
        }
      ],
      "role": "symbol",
      "title": "appStoreItemIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/appstoreitemidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/coarseConversionValue": {
      "abstract": [
        {
          "text": "A value that indicates a high, medium, or low conversion value for an ad postback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coarseConversionValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKAdNetwork",
          "text": "SKAdNetwork"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdNetworkCoarseConversionValue",
          "text": "CoarseConversionValue"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/coarseConversionValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "coarseConversionValue"
        }
      ],
      "role": "symbol",
      "title": "coarseConversionValue",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/coarseconversionvalue"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/conversionValue": {
      "abstract": [
        {
          "text": "An unsigned 6-bit value that the app or ad network controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conversionValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/conversionValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "conversionValue"
        }
      ],
      "role": "symbol",
      "title": "conversionValue",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/conversionvalue"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/didWin": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the postback won the attribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didWin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/didWin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didWin"
        }
      ],
      "role": "symbol",
      "title": "didWin",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/didwin"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/fidelityType": {
      "abstract": [
        {
          "text": "An integer that indicates the type of ad impression, StoreKit-rendered or view-through.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fidelityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/fidelityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fidelityType"
        }
      ],
      "role": "symbol",
      "title": "fidelityType",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/fidelitytype"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/fineConversionValue": {
      "abstract": [
        {
          "text": "The specific conversion value of an ad postback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fineConversionValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/fineConversionValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fineConversionValue"
        }
      ],
      "role": "symbol",
      "title": "fineConversionValue",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/fineconversionvalue"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)": {
      "abstract": [
        {
          "text": "Creates a test postback for an in-app ad.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "adNetworkIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "adCampaignIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "appStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceAppStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "conversionValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fidelityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isRedownload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didWin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "postbackURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithVersion:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:"
        }
      ],
      "role": "symbol",
      "title": "init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/init(version:adnetworkidentifier:adcampaignidentifier:appstoreitemidentifier:sourceappstoreitemidentifier:conversionvalue:fidelitytype:isredownload:didwin:postbackurl:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:didWin:postbackURL:)": {
      "abstract": [
        {
          "text": "Creates a test postback for a web ad or an in-app ad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "adNetworkIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "appStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceAppStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "fidelityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isRedownload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didWin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "postbackURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:didWin:postbackURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:didWin:postbackURL:"
        }
      ],
      "role": "symbol",
      "title": "init(version:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:didWin:postbackURL:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/init(version:adnetworkidentifier:sourceidentifier:appstoreitemidentifier:sourceappstoreitemidentifier:sourcedomain:fidelitytype:isredownload:didwin:postbackurl:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/isRedownload": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the user redownloaded and reinstalled the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRedownload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/isRedownload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isRedownload"
        }
      ],
      "role": "symbol",
      "title": "isRedownload",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/isredownload"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/isRegistered": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the postback is registered in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRegistered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/isRegistered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isRegistered"
        }
      ],
      "role": "symbol",
      "title": "isRegistered",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/isregistered"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/postbackSequenceIndex": {
      "abstract": [
        {
          "text": "The position of this postback among all postbacks for an ad impression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postbackSequenceIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/postbackSequenceIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postbackSequenceIndex"
        }
      ],
      "role": "symbol",
      "title": "postbackSequenceIndex",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/postbacksequenceindex"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/postbackURL": {
      "abstract": [
        {
          "text": "A URL on your server where the testing environment sends test postbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postbackURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/postbackURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postbackURL"
        }
      ],
      "role": "symbol",
      "title": "postbackURL",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/postbackurl"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceAppStoreItemIdentifier": {
      "abstract": [
        {
          "text": "The item identifier of the app that displays the ad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAppStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceAppStoreItemIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceAppStoreItemIdentifier"
        }
      ],
      "role": "symbol",
      "title": "sourceAppStoreItemIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/sourceappstoreitemidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceDomain": {
      "abstract": [
        {
          "text": "The source of a web ad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceDomain"
        }
      ],
      "role": "symbol",
      "title": "sourceDomain",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/sourcedomain"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceIdentifier": {
      "abstract": [
        {
          "text": "A string that identifies an ad campaign.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "sourceIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/sourceidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/transactionIdentifier": {
      "abstract": [
        {
          "text": "A unique transaction identifier that the system generates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/transactionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transactionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "transactionIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/transactionidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/version": {
      "abstract": [
        {
          "text": "The SKAdNetwork version that the postback uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/version"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/winningPostbacks(withVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:postbackURL:)": {
      "abstract": [
        {
          "text": "Creates a sequence of test postbacks for an in-app or web ad impression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "winningPostbacks"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "adNetworkIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "appStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceAppStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "fidelityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isRedownload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "postbackURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKAdTestPostback",
          "text": "SKAdTestPostback"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/winningPostbacks(withVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:postbackURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "winningPostbacksWithVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:postbackURL:"
        }
      ],
      "role": "symbol",
      "title": "winningPostbacks(withVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:postbackURL:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/winningpostbacks(withversion:adnetworkidentifier:sourceidentifier:appstoreitemidentifier:sourceappstoreitemidentifier:sourcedomain:fidelitytype:isredownload:postbackurl:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackResponse": {
      "abstract": [
        {
          "text": "The status and error information for a postback that the system sends in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackResponse"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackResponse"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestPostbackResponse",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostbackresponse"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion": {
      "abstract": [
        {
          "text": "A constant that indicates the postback version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackVersion"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackVersion"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestPostbackVersion",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostbackversion"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession": {
      "abstract": [
        {
          "text": "The class you use to test ad impressions and postbacks in Xcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestSession"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestSession"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestSession",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestsession"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork": {
      "abstract": [
        {
          "text": "Validate your ad impressions and test your postbacks by creating unit tests using the StoreKit Test framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork",
      "kind": "article",
      "role": "sampleCode",
      "title": "Testing and validating ad impression signatures and postbacks for SKAdNetwork",
      "type": "topic",
      "url": "/documentation/storekittest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Ad-impression-and-postback-testing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/testing-and-validating-ad-impression-signatures-and-postbacks-for-skadnetwork",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackResponse",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion"
      ],
      "title": "Ad impression and postback testing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-test-postbacks",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:didWin:postbackURL:)",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/winningPostbacks(withVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:postbackURL:)",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)"
      ],
      "title": "Creating test postbacks"
    },
    {
      "anchor": "Getting-the-Postback-Destination",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/postbackURL"
      ],
      "title": "Getting the Postback Destination"
    },
    {
      "anchor": "Getting-general-information",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/version",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/transactionIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/postbackSequenceIndex",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/isRegistered",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/isRedownload"
      ],
      "title": "Getting general information"
    },
    {
      "anchor": "Getting-advertisement-information",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/adNetworkIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/appStoreItemIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceAppStoreItemIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceDomain",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceIdentifier"
      ],
      "title": "Getting advertisement information"
    },
    {
      "anchor": "Getting-conversion-information",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/fidelityType",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/fineConversionValue",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/coarseConversionValue",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/didWin"
      ],
      "title": "Getting conversion information"
    },
    {
      "anchor": "Getting-information-in-earlier-versions",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/adCampaignIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/conversionValue"
      ],
      "title": "Getting information in earlier versions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKAdTestPostback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-test-postbacks",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:didWin:postbackURL:)",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/winningPostbacks(withVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:postbackURL:)",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)"
              ],
              "title": "Creating test postbacks"
            },
            {
              "anchor": "Getting-the-Postback-Destination",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/postbackURL"
              ],
              "title": "Getting the Postback Destination"
            },
            {
              "anchor": "Getting-general-information",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/version",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/transactionIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/postbackSequenceIndex",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/isRegistered",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/isRedownload"
              ],
              "title": "Getting general information"
            },
            {
              "anchor": "Getting-advertisement-information",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/adNetworkIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/appStoreItemIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceAppStoreItemIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceDomain",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/sourceIdentifier"
              ],
              "title": "Getting advertisement information"
            },
            {
              "anchor": "Getting-conversion-information",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/fidelityType",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/fineConversionValue",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/coarseConversionValue",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/didWin"
              ],
              "title": "Getting conversion information"
            },
            {
              "anchor": "Getting-information-in-earlier-versions",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/adCampaignIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/conversionValue"
              ],
              "title": "Getting information in earlier versions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Ad-impression-and-postback-testing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackResponse",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion"
              ],
              "title": "Ad impression and postback testing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKAdTestPostback"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession/title",
          "value": "SKAdTestSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1postbackSequenceIndex/title",
          "value": "postbackSequenceIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1postbackSequenceIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postbackSequenceIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1isRedownload/title",
          "value": "isRedownload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1isRedownload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isRedownload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1isRegistered/title",
          "value": "isRegistered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1isRegistered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isRegistered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1transactionIdentifier/title",
          "value": "transactionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1transactionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transactionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1coarseConversionValue/title",
          "value": "coarseConversionValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1coarseConversionValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "coarseConversionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1winningPostbacks(withVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:postbackURL:)/title",
          "value": "winningPostbacksWithVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:postbackURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1winningPostbacks(withVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:postbackURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "winningPostbacksWithVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:postbackURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)/title",
          "value": "initWithVersion:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithVersion:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1postbackURL/title",
          "value": "postbackURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1postbackURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postbackURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1sourceIdentifier/title",
          "value": "sourceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1sourceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1didWin/title",
          "value": "didWin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1didWin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "didWin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1appStoreItemIdentifier/title",
          "value": "appStoreItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1appStoreItemIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appStoreItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1fineConversionValue/title",
          "value": "fineConversionValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1fineConversionValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fineConversionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1fidelityType/title",
          "value": "fidelityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1fidelityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fidelityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1sourceAppStoreItemIdentifier/title",
          "value": "sourceAppStoreItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1sourceAppStoreItemIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceAppStoreItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1init(version:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:didWin:postbackURL:)/title",
          "value": "initWithVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:didWin:postbackURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1init(version:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:didWin:postbackURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithVersion:adNetworkIdentifier:sourceIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:sourceDomain:fidelityType:isRedownload:didWin:postbackURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackResponse/title",
          "value": "SKAdTestPostbackResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1conversionValue/title",
          "value": "conversionValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1conversionValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "conversionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1adCampaignIdentifier/title",
          "value": "adCampaignIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1adCampaignIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "adCampaignIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/title",
          "value": "SKAdTestPostback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion/title",
          "value": "SKAdTestPostbackVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1sourceDomain/title",
          "value": "sourceDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1sourceDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1adNetworkIdentifier/title",
          "value": "adNetworkIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1adNetworkIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "adNetworkIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/skadtestpostback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/skadtestpostback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
