{
  "abstract": [
    {
      "text": "Detect and identify hundreds of sounds by using a trained classifier.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/classifying-live-audio-input-with-a-built-in-sound-classifier"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Sound Analysis"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Classifying Live Audio Input with a Built-in Sound Classifier"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC21 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc21/10036/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis": {
      "abstract": [
        {
          "text": "Classify various sounds by analyzing audio files or streams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
      "kind": "symbol",
      "role": "collection",
      "title": "Sound Analysis",
      "type": "topic",
      "url": "/documentation/soundanalysis"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult": {
      "abstract": [
        {
          "text": "A result that contains the highest-ranking classifications in a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNClassificationResult"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNClassificationResult"
        }
      ],
      "role": "symbol",
      "title": "SNClassificationResult",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassificationresult"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest": {
      "abstract": [
        {
          "text": "A request that classifies sound using a Core ML model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNClassifySoundRequest"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNClassifySoundRequest"
        }
      ],
      "role": "symbol",
      "title": "SNClassifySoundRequest",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassifysoundrequest"
    },
    "ee91a9289839/ClassifyingLiveAudioInputWithABuiltInSoundClassifier.zip": {
      "checksum": "ee91a9289839a118de01a998299d99e182348d223422867097073d44cde7f73d06e58d3ad8f10ea41a8cc1d130e9c8a6b2f10ecd052bc98fc0072f58ac7a0ba0",
      "identifier": "ee91a9289839/ClassifyingLiveAudioInputWithABuiltInSoundClassifier.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/ee91a9289839/ClassifyingLiveAudioInputWithABuiltInSoundClassifier.zip"
    },
    "https://developer.apple.com/wwdc21/10036/": {
      "identifier": "https://developer.apple.com/wwdc21/10036/",
      "title": "10036: Discover Built-in Sound Classification in Sound Analysis",
      "titleInlineContent": [
        {
          "text": "10036: Discover Built-in Sound Classification in Sound Analysis",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10036/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "ee91a9289839/ClassifyingLiveAudioInputWithABuiltInSoundClassifier.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sound-classification-requests",
      "generated": true,
      "identifiers": [
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult"
      ],
      "title": "Sound classification requests"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sound-classification-requests",
              "generated": true,
              "identifiers": [
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassificationResult"
              ],
              "title": "Sound classification requests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest/title",
          "value": "SNClassifySoundRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassifySoundRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassifySoundRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult/title",
          "value": "SNClassificationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassificationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassificationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassificationResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/soundanalysis/classifying-live-audio-input-with-a-built-in-sound-classifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/soundanalysis/classifying-live-audio-input-with-a-built-in-sound-classifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
