{"seeAlsoSections":[{"title":"Creating a Request","anchor":"Creating-a-Request","generated":true,"identifiers":["doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/init(mlModel:)","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/init(classifierIdentifier:)"]}],"identifier":{"url":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier","interfaceLanguage":"swift"},"metadata":{"title":"SNClassifierIdentifier","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SNClassifierIdentifier"}],"modules":[{"name":"Sound Analysis"}],"symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"SNClassifierIdentifier"}],"platforms":[{"introducedAt":"15.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"introducedAt":"15.0","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"15.0","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"12.0","unavailable":false,"beta":false,"deprecated":false,"name":"macOS"},{"introducedAt":"15.0","unavailable":false,"beta":false,"deprecated":false,"name":"tvOS"},{"introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"},{"introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false,"name":"watchOS"}],"role":"symbol","roleHeading":"Structure","externalID":"c:@T@SNClassifierIdentifier"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.soundanalysis/documentation/SoundAnalysis"]]},"abstract":[{"type":"text","text":"An identifier that represents the versions of the framework’s sound classifier."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/soundanalysis/snclassifieridentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/soundanalysis/snclassifieridentifier"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SNClassifierIdentifier","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Selecting a Sound Classifier","anchor":"Selecting-a-Sound-Classifier","identifiers":["doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier/version1"]},{"title":"Creating an Identifier","anchor":"Creating-an-Identifier","identifiers":["doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier/init(rawValue:)"]}],"references":{"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/init(mlModel:)":{"identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/init(mlModel:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithMLModel:error:"}],"title":"init(mlModel:)","abstract":[{"type":"text","text":"Creates a request that uses a custom sound classification model."}],"type":"topic","url":"/documentation/soundanalysis/snclassifysoundrequest/init(mlmodel:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mlModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLModel","text":"MLModel"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier/version1":{"navigatorTitle":[{"text":"SNClassifierIdentifierVersion1","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier/version1","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"version1","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SNClassifierIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@T@SNClassifierIdentifier"}],"type":"topic","url":"/documentation/soundanalysis/snclassifieridentifier/version1","role":"symbol","title":"version1","abstract":[{"text":"Version 1 of the sound classifier.","type":"text"}]},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/init(classifierIdentifier:)":{"identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/init(classifierIdentifier:)","kind":"symbol","navigatorTitle":[{"text":"initWithClassifierIdentifier:error:","kind":"identifier"}],"title":"init(classifierIdentifier:)","abstract":[{"type":"text","text":"Creates a request that uses the framework’s built-in sound classification model."}],"type":"topic","url":"/documentation/soundanalysis/snclassifysoundrequest/init(classifieridentifier:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"classifierIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SNClassifierIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@T@SNClassifierIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","title":"Technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic"},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier/init(rawValue:)":{"identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier/init(rawValue:)","title":"init(rawValue:)","abstract":[{"type":"text","text":"Creates an identifier for a sound classifier."}],"role":"symbol","kind":"symbol","type":"topic","url":"/documentation/soundanalysis/snclassifieridentifier/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"title":"Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","url":"/documentation/Swift/Sendable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SH":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"title":"Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","url":"/documentation/Swift/Hashable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Equatable","preciseIdentifier":"s:SQ","kind":"typeIdentifier"}]},"doc://com.apple.soundanalysis/documentation/SoundAnalysis":{"role":"collection","abstract":[{"text":"Classify various sounds by analyzing audio files or streams.","type":"text"}],"kind":"symbol","title":"Sound Analysis","url":"/documentation/soundanalysis","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis","type":"topic"},"doc://com.externally.resolved.symbol/s:SQ":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"title":"Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","url":"/documentation/Swift/Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}]},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SNClassifierIdentifier"}],"identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An identifier that represents the versions of the framework’s sound classifier."}],"url":"/documentation/soundanalysis/snclassifieridentifier","title":"SNClassifierIdentifier","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SNClassifierIdentifier"}]},"doc://com.externally.resolved.symbol/s:SY":{"abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SY8RawValueQa","text":"RawValue"},{"kind":"text","text":">"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY","title":"RawRepresentable","url":"/documentation/Swift/RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"introducedAt":"15.0","name":"iOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"15.0","name":"iPadOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"15.0","name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"12.0","name":"macOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"15.0","name":"tvOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"},{"introducedAt":"8.0","beta":false,"unavailable":false,"deprecated":false,"name":"watchOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Type Alias","op":"replace"},{"path":"/metadata/title","value":"SNClassifierIdentifier","op":"replace"},{"path":"/metadata/symbolKind","value":"typealias","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"SNClassifierIdentifier","kind":"identifier"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"SNClassifierIdentifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.soundanalysis/documentation/SoundAnalysis"]]},"op":"replace"},{"path":"/topicSections","value":[{"anchor":"Selecting-a-Sound-Classifier","identifiers":["doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifierIdentifier/version1"],"title":"Selecting a Sound Classifier"}],"op":"replace"},{"op":"replace","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Creating a Request","identifiers":["doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/init(mlModel:)","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/init(classifierIdentifier:)"],"anchor":"Creating-a-Request","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SNClassifierIdentifier"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest~1init(mlModel:)/title","op":"replace","value":"initWithMLModel:error:"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest~1init(mlModel:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMLModel:error:"}]},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifierIdentifier~1version1/title","op":"replace","value":"SNClassifierIdentifierVersion1"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifierIdentifier~1version1/fragments","op":"replace","value":[{"text":"SNClassifierIdentifierVersion1","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest~1init(classifierIdentifier:)/title","op":"replace","value":"initWithClassifierIdentifier:error:"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest~1init(classifierIdentifier:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithClassifierIdentifier:error:"}]},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifierIdentifier/title","op":"replace","value":"SNClassifierIdentifier"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifierIdentifier/fragments","op":"replace","value":[{"text":"SNClassifierIdentifier","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifierIdentifier/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SNClassifierIdentifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}