{
  "abstract": [
    {
      "text": "Tells the delegate that the user deleted a contact.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-ci4z"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CNChangeHistoryEventVisitor(im)visitDeleteContactEvent:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "visit"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CNChangeHistoryDeleteContactEvent",
        "text": "CNChangeHistoryDeleteContactEvent"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "visitDeleteContactEvent:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "visit(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "visit"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "event"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CNChangeHistoryDeleteContactEvent",
              "text": "CNChangeHistoryDeleteContactEvent"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The event object that represents a user deleting a contact.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "event"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Inspect the contact identifier in the event that the system provides and update your app’s cached data accordingly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent": {
      "abstract": [
        {
          "text": "An object that represents a user deleting a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDeleteContactEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDeleteContactEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryDeleteContactEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistorydeletecontactevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor": {
      "abstract": [
        {
          "text": "An interface for receiving notice of changes to contacts and groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryEventVisitor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryEventVisitor"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryEventVisitor",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-1pf2a": {
      "abstract": [
        {
          "text": "Tells the delegate that the user updated a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryUpdateContactEvent",
          "text": "CNChangeHistoryUpdateContactEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-1pf2a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitUpdateContactEvent:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "visit(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-1pf2a"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-9w73y": {
      "abstract": [
        {
          "text": "Tells the delegate that the user added a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryAddContactEvent",
          "text": "CNChangeHistoryAddContactEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-9w73y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitAddContactEvent:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "visit(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-9w73y"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-ci4z": {
      "abstract": [
        {
          "text": "Tells the delegate that the user deleted a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryDeleteContactEvent",
          "text": "CNChangeHistoryDeleteContactEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-ci4z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitDeleteContactEvent:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "visit(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-ci4z"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Updating-contacts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-9w73y",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-1pf2a"
      ],
      "title": "Updating contacts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "visitDeleteContactEvent:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitDeleteContactEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Updating-contacts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-9w73y",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-1pf2a"
              ],
              "title": "Updating contacts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "visitDeleteContactEvent:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CNChangeHistoryDeleteContactEvent",
                    "text": "CNChangeHistoryDeleteContactEvent"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "event"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The event object that represents a user deleting a contact.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "event"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-ci4z/title",
          "value": "visitDeleteContactEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-ci4z/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitDeleteContactEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteContactEvent/title",
          "value": "CNChangeHistoryDeleteContactEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteContactEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDeleteContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteContactEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDeleteContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-1pf2a/title",
          "value": "visitUpdateContactEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-1pf2a/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitUpdateContactEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor/title",
          "value": "CNChangeHistoryEventVisitor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEventVisitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEventVisitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-9w73y/title",
          "value": "visitAddContactEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-9w73y/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitAddContactEvent:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-ci4z"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-ci4z"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
