{
  "abstract": [
    {
      "text": "The macOS 10.2 typesetting behavior that is still compatible with the original typesetter behavior.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_2_WithCompatibility"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTypesetterBehavior@NSTypesetterBehavior_10_2_WithCompatibility",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "behavior_10_2_WithCompatibility"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTypesetterBehavior_10_2_WithCompatibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSLayoutManager.TypesetterBehavior.behavior_10_2_WithCompatibility"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "behavior_10_2_WithCompatibility"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The typesetting behavior is the same as ",
              "type": "text"
            },
            {
              "code": "NSTypesetterBehavior_10_2",
              "type": "codeVoice"
            },
            {
              "text": ", but using line widths and height metric calculations that are the same as with ",
              "type": "text"
            },
            {
              "code": "NSTypesetterOriginalBehavior",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager": {
      "abstract": [
        {
          "text": "An object that coordinates the layout and display of text characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum": {
      "abstract": [
        {
          "text": "Constants that determine the layout manager’s behavior during layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TypesetterBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TypesetterBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TypesetterBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/typesetterbehavior-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_2": {
      "abstract": [
        {
          "text": "The typesetter behavior introduced in macOS 10.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "behavior_10_2"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTypesetterBehavior_10_2"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TypesetterBehavior.behavior_10_2",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/typesetterbehavior-swift.enum/behavior_10_2"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_2_WithCompatibility": {
      "abstract": [
        {
          "text": "The macOS 10.2 typesetting behavior that is still compatible with the original typesetter behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "behavior_10_2_WithCompatibility"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_2_WithCompatibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTypesetterBehavior_10_2_WithCompatibility"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TypesetterBehavior.behavior_10_2_WithCompatibility",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/typesetterbehavior-swift.enum/behavior_10_2_withcompatibility"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_3": {
      "abstract": [
        {
          "text": "The typesetter behavior introduced in macOS 10.3.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "behavior_10_3"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTypesetterBehavior_10_3"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TypesetterBehavior.behavior_10_3",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/typesetterbehavior-swift.enum/behavior_10_3"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_4": {
      "abstract": [
        {
          "text": "The typesetter behavior introduced in macOS 10.4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "behavior_10_4"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTypesetterBehavior_10_4"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TypesetterBehavior.behavior_10_4",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/typesetterbehavior-swift.enum/behavior_10_4"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/latestBehavior": {
      "abstract": [
        {
          "text": "The current typesetter behavior in the current operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latestBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/latestBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTypesetterLatestBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TypesetterBehavior.latestBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/typesetterbehavior-swift.enum/latestbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/originalBehavior": {
      "abstract": [
        {
          "text": "The original typesetter behavior, as shipped with macOS 10.1 and earlier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "originalBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/originalBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTypesetterOriginalBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TypesetterBehavior.originalBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/typesetterbehavior-swift.enum/originalbehavior"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Behaviors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/latestBehavior",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/originalBehavior",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_2",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_3",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_4"
      ],
      "title": "Behaviors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTypesetterBehavior_10_2_WithCompatibility"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypesetterBehavior_10_2_WithCompatibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Behaviors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/latestBehavior",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/originalBehavior",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_2",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_3",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TypesetterBehavior-swift.enum/behavior_10_4"
              ],
              "title": "Behaviors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTypesetterBehavior_10_2_WithCompatibility"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1behavior_10_2_WithCompatibility/title",
          "value": "NSTypesetterBehavior_10_2_WithCompatibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1behavior_10_2_WithCompatibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypesetterBehavior_10_2_WithCompatibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1originalBehavior/title",
          "value": "NSTypesetterOriginalBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1originalBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypesetterOriginalBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/title",
          "value": "NSLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1behavior_10_4/title",
          "value": "NSTypesetterBehavior_10_4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1behavior_10_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypesetterBehavior_10_4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum/title",
          "value": "NSTypesetterBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypesetterBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypesetterBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1behavior_10_2/title",
          "value": "NSTypesetterBehavior_10_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1behavior_10_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypesetterBehavior_10_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1latestBehavior/title",
          "value": "NSTypesetterLatestBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1latestBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypesetterLatestBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1behavior_10_3/title",
          "value": "NSTypesetterBehavior_10_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TypesetterBehavior-swift.enum~1behavior_10_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypesetterBehavior_10_3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nslayoutmanager/typesetterbehavior-swift.enum/behavior_10_2_withcompatibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nslayoutmanager/typesetterbehavior-swift.enum/behavior_10_2_withcompatibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
