{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uipresentationcontroller/containerviewdidlayoutsubviews()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uipresentationcontroller/containerviewdidlayoutsubviews()"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIPresentationController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"anchor":"Presentation-controllers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewWillLayoutSubviews()"],"title":"Presentation controllers"}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"8.0"},{"introducedAt":"8.0","deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false,"beta":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerViewDidLayoutSubviews"},{"kind":"text","text":"()"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"containerViewDidLayoutSubviews"}],"modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UIPresentationController(im)containerViewDidLayoutSubviews","title":"containerViewDidLayoutSubviews()"},"abstract":[{"type":"text","text":"Notifies the presentation controller when layout ends on the views of the container view."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containerViewDidLayoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"UIKit calls this method after adjusting the layout of the views in the container view. Use this method to make any additional changes to the view hierarchy.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In iOS 18 and later, UIKit supports automatic trait tracking inside this method for traits from this presentation controller’s "},{"code":"traitCollection","type":"codeVoice"},{"type":"text","text":" and the "},{"code":"traitCollection","type":"codeVoice"},{"type":"text","text":" of its "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerView","isActive":true,"type":"reference"},{"type":"text","text":". For more information, see "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","isActive":true,"type":"reference"},{"type":"text","text":"."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewDidLayoutSubviews()"},"sections":[],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewWillLayoutSubviews()":{"title":"containerViewWillLayoutSubviews()","url":"/documentation/uikit/uipresentationcontroller/containerviewwilllayoutsubviews()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerViewWillLayoutSubviews"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"containerViewWillLayoutSubviews"}],"role":"symbol","abstract":[{"text":"Notifies the presentation controller that layout is about to begin on the views of the container view.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewWillLayoutSubviews()"},"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking":{"kind":"article","abstract":[{"text":"Reduce the need to manually register for trait changes when you use traits within a method or closure that supports automatic trait tracking.","type":"text"}],"url":"/documentation/uikit/automatic-trait-tracking","identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","title":"Automatic trait tracking","role":"collectionGroup","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerView":{"title":"containerView","type":"topic","kind":"symbol","abstract":[{"text":"The view in which the presentation occurs.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerView","navigatorTitle":[{"text":"containerView","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uipresentationcontroller/containerview"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewDidLayoutSubviews()":{"title":"containerViewDidLayoutSubviews()","url":"/documentation/uikit/uipresentationcontroller/containerviewdidlayoutsubviews()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerViewDidLayoutSubviews"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"containerViewDidLayoutSubviews"}],"role":"symbol","abstract":[{"text":"Notifies the presentation controller when layout ends on the views of the container view.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewDidLayoutSubviews()"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController","role":"symbol","abstract":[{"type":"text","text":"An object that manages the transition animations and the presentation of view controllers onscreen."}],"kind":"symbol","url":"/documentation/uikit/uipresentationcontroller","navigatorTitle":[{"text":"UIPresentationController","kind":"identifier"}],"title":"UIPresentationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UIPresentationController","kind":"identifier"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"iOS","beta":false,"introducedAt":"8.0","unavailable":false},{"introducedAt":"8.0","deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"path":"/metadata/title","value":"containerViewDidLayoutSubviews","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containerViewDidLayoutSubviews"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIPresentationController"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewWillLayoutSubviews()"],"generated":true,"anchor":"Presentation-controllers","title":"Presentation controllers"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"containerViewDidLayoutSubviews","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"containerViewWillLayoutSubviews","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1containerViewWillLayoutSubviews()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"containerViewWillLayoutSubviews","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1containerViewWillLayoutSubviews()/fragments"},{"op":"replace","value":"containerView","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1containerView/title"},{"op":"replace","value":[{"kind":"identifier","text":"containerView"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1containerView/fragments"},{"op":"replace","value":"containerViewDidLayoutSubviews","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1containerViewDidLayoutSubviews()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"containerViewDidLayoutSubviews","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1containerViewDidLayoutSubviews()/fragments"},{"op":"replace","value":"UIPresentationController","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/title"},{"op":"replace","value":[{"text":"UIPresentationController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIPresentationController"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}