{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uipresentationcontroller/overridetraitcollection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uipresentationcontroller/overridetraitcollection"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/overrideTraitCollection","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIPresentationController"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"overrideTraitCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection"},{"kind":"text","text":"?"}],"modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UIPresentationController(py)overrideTraitCollection","role":"symbol","title":"overrideTraitCollection","roleHeading":"Instance Property","platforms":[{"beta":false,"deprecated":false,"introducedAt":"8.0","unavailable":false,"message":"Use the traitOverrides property instead","name":"iOS","deprecatedAt":"17.0"},{"beta":false,"deprecated":false,"introducedAt":"8.0","unavailable":false,"message":"Use the traitOverrides property instead","name":"iPadOS","deprecatedAt":"17.0"},{"beta":false,"deprecated":false,"introducedAt":"13.1","unavailable":false,"message":"Use the traitOverrides property instead","name":"Mac Catalyst","deprecatedAt":"17.0"},{"beta":false,"deprecated":false,"unavailable":false,"message":"Use the traitOverrides property instead","name":"tvOS","deprecatedAt":"17.0"},{"beta":false,"deprecated":false,"introducedAt":"1.0","unavailable":false,"message":"Use the traitOverrides property instead","name":"visionOS","deprecatedAt":"1.0"}],"navigatorTitle":[{"kind":"identifier","text":"overrideTraitCollection"}],"symbolKind":"property"},"kind":"symbol","abstract":[{"type":"text","text":"Interface traits for the presented view controller, to use in place of traits from the iOS environment."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@NSCopying","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overrideTraitCollection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITraitCollection","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitCollection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/choosing-a-specific-interface-style-for-your-ios-app"]},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Use this property to provide an interface trait collection for the presented view controller, overriding one or more values in the iOS trait environment."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Each value you place in the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/overrideTraitCollection"},{"type":"text","text":" property overrides the corresponding value in the iOS trait environment. For example, the following code snippet shows how to override the display scale for the presented view controller, leaving other traits as they are provided by the system. Place such code, typically, in the implementation file for the presenting view controller:"}],"type":"paragraph"},{"code":["presentedVC.presentationController.overrideTraitCollection = [UITraitCollection traitCollectionWithDisplayScale: 1.5];","[self presentViewController: presentedVC animated: NO completion: nil];"],"syntax":"objc","type":"codeListing"},{"inlineContent":[{"text":"The ","type":"text"},{"inlineContent":[{"text":"presenting","type":"text"}],"type":"emphasis"},{"text":" view controller is not affected by use of this property.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"The default value of the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/overrideTraitCollection"},{"text":" property is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":", which results in the full iOS trait environment being used by the presented view controller.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIPresentationController":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController","role":"symbol","abstract":[{"type":"text","text":"An object that manages the transition animations and the presentation of view controllers onscreen."}],"kind":"symbol","url":"/documentation/uikit/uipresentationcontroller","navigatorTitle":[{"text":"UIPresentationController","kind":"identifier"}],"title":"UIPresentationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UIPresentationController","kind":"identifier"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITraitCollection":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UITraitCollection","kind":"identifier"}],"title":"UITraitCollection","url":"/documentation/uikit/uitraitcollection","abstract":[{"text":"A collection of data that represents the environment for an individual element in your app’s user interface.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitCollection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITraitCollection","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/choosing-a-specific-interface-style-for-your-ios-app":{"kind":"article","title":"Choosing a Specific Interface Style for Your iOS App","identifier":"doc://com.apple.uikit/documentation/UIKit/choosing-a-specific-interface-style-for-your-ios-app","abstract":[{"text":"Adopt a specific interface style for your views, view controllers, or app when it is inappropriate to support both light and dark variants.","type":"text"}],"url":"/documentation/uikit/choosing-a-specific-interface-style-for-your-ios-app","role":"article","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/overrideTraitCollection":{"type":"topic","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"overrideTraitCollection"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/overrideTraitCollection","role":"symbol","url":"/documentation/uikit/uipresentationcontroller/overridetraitcollection","title":"overrideTraitCollection","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"overrideTraitCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection"},{"kind":"text","text":"?"}],"abstract":[{"text":"Interface traits for the presented view controller, to use in place of traits from the iOS environment.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"deprecatedAt":"17.0","name":"iOS","introducedAt":"8.0","unavailable":false,"deprecated":false},{"beta":false,"deprecatedAt":"17.0","name":"iPadOS","introducedAt":"8.0","unavailable":false,"deprecated":false},{"beta":false,"deprecatedAt":"17.0","name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"deprecated":false},{"beta":false,"deprecatedAt":"17.0","name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"deprecatedAt":"1.0","name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"overrideTraitCollection","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"overrideTraitCollection","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIPresentationController"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UITraitCollection","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitCollection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"text":" * ","kind":"text"},{"text":"overrideTraitCollection","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"add","path":"/deprecationSummary","value":[]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/title","value":"UIPresentationController"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/fragments","value":[{"text":"UIPresentationController","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/navigatorTitle","value":[{"text":"UIPresentationController","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/title","value":"UITraitCollection"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/fragments","value":[{"kind":"identifier","text":"UITraitCollection"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/navigatorTitle","value":[{"kind":"identifier","text":"UITraitCollection"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1overrideTraitCollection/title","value":"overrideTraitCollection"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1overrideTraitCollection/fragments","value":[{"kind":"identifier","text":"overrideTraitCollection"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}