{"kind":"symbol","abstract":[{"text":"The presentation style of the presented view controller.","type":"text"}],"metadata":{"roleHeading":"Instance Property","platforms":[{"unavailable":false,"introducedAt":"8.0","name":"iOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"8.0","name":"iPadOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst","beta":false,"deprecated":false},{"unavailable":false,"name":"tvOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false}],"navigatorTitle":[{"kind":"identifier","text":"presentationStyle"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIModalPresentationStyle","kind":"typeIdentifier","text":"UIModalPresentationStyle"}],"modules":[{"name":"UIKit"}],"title":"presentationStyle","externalID":"c:objc(cs)UIPresentationController(py)presentationStyle","symbolKind":"property","role":"symbol"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIPresentationController"]]},"seeAlsoSections":[{"title":"Getting the presentation attributes","anchor":"Getting-the-presentation-attributes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIPresentationController/adaptivePresentationStyle(for:)","doc://com.apple.uikit/documentation/UIKit/UIPresentationController/adaptivePresentationStyle","doc://com.apple.uikit/documentation/UIKit/UIPresentationController/shouldPresentInFullscreen","doc://com.apple.uikit/documentation/UIKit/UIPresentationController/shouldRemovePresentersView"],"generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIModalPresentationStyle","text":"UIModalPresentationStyle","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property is set to the presentation style of the presented view controller. The presentation controller uses this style to determine the initial appearance of the presented content."}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/presentationStyle"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uipresentationcontroller/presentationstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uipresentationcontroller/presentationstyle"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit/UIPresentationController":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController","role":"symbol","abstract":[{"type":"text","text":"An object that manages the transition animations and the presentation of view controllers onscreen."}],"kind":"symbol","url":"/documentation/uikit/uipresentationcontroller","navigatorTitle":[{"text":"UIPresentationController","kind":"identifier"}],"title":"UIPresentationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UIPresentationController","kind":"identifier"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle":{"role":"symbol","title":"UIModalPresentationStyle","abstract":[{"type":"text","text":"Modal presentation styles available when presenting view controllers."}],"navigatorTitle":[{"text":"UIModalPresentationStyle","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIModalPresentationStyle","kind":"identifier"}],"url":"/documentation/uikit/uimodalpresentationstyle","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/adaptivePresentationStyle(for:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/adaptivePresentationStyle(for:)","url":"/documentation/uikit/uipresentationcontroller/adaptivepresentationstyle(for:)","navigatorTitle":[{"kind":"identifier","text":"adaptivePresentationStyleForTraitCollection:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adaptivePresentationStyle","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"UITraitCollection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIModalPresentationStyle","text":"UIModalPresentationStyle"}],"abstract":[{"type":"text","text":"Returns the presentation style to use for the specified set of traits."}],"kind":"symbol","title":"adaptivePresentationStyle(for:)","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/adaptivePresentationStyle":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"adaptivePresentationStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIModalPresentationStyle","text":"UIModalPresentationStyle","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"adaptivePresentationStyle","kind":"identifier"}],"title":"adaptivePresentationStyle","identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/adaptivePresentationStyle","type":"topic","url":"/documentation/uikit/uipresentationcontroller/adaptivepresentationstyle","kind":"symbol","abstract":[{"text":"Returns the presentation style to use when the presented view controller becomes horizontally compact.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/shouldRemovePresentersView":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldRemovePresentersView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A Boolean value indicating whether the presenting view controller’s view should be removed when the presentation animations finish."}],"url":"/documentation/uikit/uipresentationcontroller/shouldremovepresentersview","navigatorTitle":[{"text":"shouldRemovePresentersView","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/shouldRemovePresentersView","title":"shouldRemovePresentersView"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/shouldPresentInFullscreen":{"type":"topic","abstract":[{"text":"A Boolean value indicating whether the presentation covers the entire screen.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldPresentInFullscreen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/uikit/uipresentationcontroller/shouldpresentinfullscreen","role":"symbol","navigatorTitle":[{"text":"shouldPresentInFullscreen","kind":"identifier"}],"title":"shouldPresentInFullscreen","identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/shouldPresentInFullscreen","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/presentationStyle":{"url":"/documentation/uikit/uipresentationcontroller/presentationstyle","title":"presentationStyle","abstract":[{"text":"The presentation style of the presented view controller.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIModalPresentationStyle","text":"UIModalPresentationStyle","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/presentationStyle","navigatorTitle":[{"text":"presentationStyle","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"8.0","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"8.0","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"presentationStyle"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"presentationStyle"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIPresentationController"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Getting the presentation attributes","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIPresentationController/adaptivePresentationStyle(for:)","doc://com.apple.uikit/documentation/UIKit/UIPresentationController/adaptivePresentationStyle","doc://com.apple.uikit/documentation/UIKit/UIPresentationController/shouldPresentInFullscreen","doc://com.apple.uikit/documentation/UIKit/UIPresentationController/shouldRemovePresentersView"],"anchor":"Getting-the-presentation-attributes"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIModalPresentationStyle","text":"UIModalPresentationStyle","identifier":"doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationStyle"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/title","value":"UIPresentationController"},{"value":[{"kind":"identifier","text":"UIPresentationController"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/fragments"},{"value":[{"text":"UIPresentationController","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/navigatorTitle"},{"value":"UIModalPresentationStyle","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/title"},{"value":[{"kind":"identifier","text":"UIModalPresentationStyle"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/fragments"},{"value":[{"text":"UIModalPresentationStyle","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle/navigatorTitle"},{"value":"adaptivePresentationStyleForTraitCollection:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1adaptivePresentationStyle(for:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adaptivePresentationStyleForTraitCollection:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1adaptivePresentationStyle(for:)/fragments"},{"value":"adaptivePresentationStyle","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1adaptivePresentationStyle/title"},{"value":[{"text":"adaptivePresentationStyle","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1adaptivePresentationStyle/fragments"},{"value":"shouldRemovePresentersView","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1shouldRemovePresentersView/title"},{"value":[{"text":"shouldRemovePresentersView","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1shouldRemovePresentersView/fragments"},{"value":"shouldPresentInFullscreen","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1shouldPresentInFullscreen/title"},{"value":[{"kind":"identifier","text":"shouldPresentInFullscreen"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1shouldPresentInFullscreen/fragments"},{"value":"presentationStyle","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1presentationStyle/title"},{"value":[{"text":"presentationStyle","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1presentationStyle/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}