{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIPresentationController"]]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/traitOverrides-9o0j4"},"seeAlsoSections":[{"generated":true,"title":"Overriding trait values","anchor":"Overriding-trait-values","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITraitOverrides-c.protocol"]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uipresentationcontroller/traitoverrides-9o0j4"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"introducedAt":"17.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"introducedAt":"17.0","deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"introducedAt":"17.0","deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"introducedAt":"17.0","deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false,"unavailable":false}],"fragments":[{"text":"traitOverrides","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)UIPresentationController(py)traitOverrides","roleHeading":"Instance Property","modules":[{"name":"UIKit"}],"symbolKind":"property","title":"traitOverrides","navigatorTitle":[{"text":"traitOverrides","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UITraitOverrides","text":"id<UITraitOverrides>"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitOverrides"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController","role":"symbol","abstract":[{"type":"text","text":"An object that manages the transition animations and the presentation of view controllers onscreen."}],"kind":"symbol","url":"/documentation/uikit/uipresentationcontroller","navigatorTitle":[{"text":"UIPresentationController","kind":"identifier"}],"title":"UIPresentationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UIPresentationController","kind":"identifier"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/traitOverrides-9o0j4":{"fragments":[{"kind":"identifier","text":"traitOverrides"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIPresentationController/traitOverrides-9o0j4","abstract":[],"url":"/documentation/uikit/uipresentationcontroller/traitoverrides-9o0j4","title":"traitOverrides","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITraitOverrides-c.protocol":{"url":"/documentation/uikit/uitraitoverrides-c.protocol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitOverrides-c.protocol","role":"symbol","fragments":[{"text":"UITraitOverrides","kind":"identifier"}],"type":"topic","title":"UITraitOverrides","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"UIPresentationController","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/title"},{"value":[{"kind":"identifier","text":"UIPresentationController"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/fragments"},{"value":[{"kind":"identifier","text":"UIPresentationController"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}