{"variants":[{"paths":["/documentation/uikit/uifocussoundidentifier/default"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uifocussoundidentifier/default"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier"]]},"metadata":{"externalID":"c:@UIFocusSoundIdentifierDefault","modules":[{"name":"UIKit"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UIFocusSoundIdentifier","text":"UIFocusSoundIdentifier","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIFocusSoundIdentifierDefault","kind":"identifier"}],"extendedModule":"UIKit","role":"symbol","platforms":[{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false,"introducedAt":"11.0"}],"title":"default","roleHeading":"Type Property"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["tvOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UIFocusSoundIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier","kind":"typeIdentifier","text":"UIFocusSoundIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","seeAlsoSections":[{"anchor":"Constants","title":"Constants","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/none"]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/default","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The identifier for the default system sound to play during focus updates."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier","type":"topic","url":"/documentation/uikit/uifocussoundidentifier","navigatorTitle":[{"text":"UIFocusSoundIdentifier","kind":"identifier"}],"role":"symbol","abstract":[{"text":"An identifier for a focus-related sound.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusSoundIdentifier","kind":"identifier"}],"title":"UIFocusSoundIdentifier","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/default":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/default","title":"default","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIFocusSoundIdentifierDefault"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UIFocusSoundIdentifier","kind":"typeIdentifier","text":"UIFocusSoundIdentifier"}],"url":"/documentation/uikit/uifocussoundidentifier/default","abstract":[{"type":"text","text":"The identifier for the default system sound to play during focus updates."}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/none":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/none","title":"none","type":"topic","navigatorTitle":[{"text":"UIFocusSoundIdentifierNone","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UIFocusSoundIdentifier","text":"UIFocusSoundIdentifier","kind":"typeIdentifier"}],"url":"/documentation/uikit/uifocussoundidentifier/none","abstract":[{"text":"The identifier for disabling sound during a focus update.","type":"text"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"11.0","deprecated":false,"unavailable":false,"name":"tvOS","beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","path":"/metadata/title","value":"UIFocusSoundIdentifierDefault"},{"op":"replace","path":"/metadata/symbolKind","value":"var"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"UIFocusSoundIdentifierDefault","kind":"identifier"}]},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier/none"],"generated":true,"anchor":"Constants"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusSoundIdentifier","preciseIdentifier":"c:@T@UIFocusSoundIdentifier","text":"UIFocusSoundIdentifier"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIFocusSoundIdentifierDefault"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"UIFocusSoundIdentifier","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier/title"},{"op":"replace","value":[{"text":"UIFocusSoundIdentifier","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier/fragments"},{"op":"replace","value":[{"text":"UIFocusSoundIdentifier","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier/navigatorTitle"},{"op":"replace","value":"UIFocusSoundIdentifierDefault","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier~1default/title"},{"op":"replace","value":[{"text":"UIFocusSoundIdentifierDefault","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier~1default/fragments"},{"op":"replace","value":"UIFocusSoundIdentifierNone","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier~1none/title"},{"op":"replace","value":[{"text":"UIFocusSoundIdentifierNone","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusSoundIdentifier~1none/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}