{
  "abstract": [
    {
      "text": "Tells the delegate that the location manager detected at least one beacon that satisfies the provided constraint.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:didRange:satisfying:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CLLocationManagerDelegate(im)locationManager:didRangeBeacons:satisfyingConstraint:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "locationManager"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CLLocationManager",
        "text": "CLLocationManager"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didRange"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CLBeacon",
        "text": "CLBeacon"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "satisfying"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CLBeaconIdentityConstraint",
        "text": "CLBeaconIdentityConstraint"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "locationManager:didRangeBeacons:satisfyingConstraint:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "locationManager(_:didRange:satisfying:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "locationManager"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "manager"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLLocationManager",
              "text": "CLLocationManager"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didRange"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "beacons"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeacon",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLBeacon",
              "text": "CLBeacon"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "satisfying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "beaconConstraint"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityConstraint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLBeaconIdentityConstraint",
              "text": "CLBeaconIdentityConstraint"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that corresponds to this delegate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "manager"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeacon",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "beacons"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityConstraint",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that describes the characteristics of the beacons the location manager is looking for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "beaconConstraint"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBeacon": {
      "abstract": [
        {
          "text": "Information about an observed iBeacon device and its relative distance to a person’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLBeacon"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeacon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLBeacon"
        }
      ],
      "role": "symbol",
      "title": "CLBeacon",
      "type": "topic",
      "url": "/documentation/corelocation/clbeacon"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityConstraint": {
      "abstract": [
        {
          "text": "Identity characteristics that can match one or more beacons.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLBeaconIdentityConstraint"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLBeaconIdentityConstraint"
        }
      ],
      "role": "symbol",
      "title": "CLBeaconIdentityConstraint",
      "type": "topic",
      "url": "/documentation/corelocation/clbeaconidentityconstraint"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager": {
      "abstract": [
        {
          "text": "The object you use to start and stop the delivery of location-related events to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationManager"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationManager"
        }
      ],
      "role": "symbol",
      "title": "CLLocationManager",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate": {
      "abstract": [
        {
          "text": "The methods you use to receive events from an associated location-manager object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationManagerDelegate"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationManagerDelegate"
        }
      ],
      "role": "symbol",
      "title": "CLLocationManagerDelegate",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanagerdelegate"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:didFailRangingFor:error:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the location manager couldn’t detect any beacons that satisfy the provided constraint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLLocationManager",
          "text": "CLLocationManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailRangingFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLBeaconIdentityConstraint",
          "text": "CLBeaconIdentityConstraint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:didFailRangingFor:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationManager:didFailRangingBeaconsForConstraint:error:"
        }
      ],
      "role": "symbol",
      "title": "locationManager(_:didFailRangingFor:error:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanagerdelegate/locationmanager(_:didfailrangingfor:error:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:didRange:satisfying:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the location manager detected at least one beacon that satisfies the provided constraint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLLocationManager",
          "text": "CLLocationManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRange"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLBeacon",
          "text": "CLBeacon"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "satisfying"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLBeaconIdentityConstraint",
          "text": "CLBeaconIdentityConstraint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:didRange:satisfying:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationManager:didRangeBeacons:satisfyingConstraint:"
        }
      ],
      "role": "symbol",
      "title": "locationManager(_:didRange:satisfying:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanagerdelegate/locationmanager(_:didrange:satisfying:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:didRangeBeacons:in:)": {
      "abstract": [
        {
          "text": "Tells the delegate that one or more beacons are in range.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLLocationManager",
          "text": "CLLocationManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRangeBeacons"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLBeacon",
          "text": "CLBeacon"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLBeaconRegion",
          "text": "CLBeaconRegion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:didRangeBeacons:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationManager:didRangeBeacons:inRegion:"
        }
      ],
      "role": "symbol",
      "title": "locationManager(_:didRangeBeacons:in:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanagerdelegate/locationmanager(_:didrangebeacons:in:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:rangingBeaconsDidFailFor:withError:)": {
      "abstract": [
        {
          "text": "Tells the delegate that an error occurred while gathering ranging information for a set of beacons.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLLocationManager",
          "text": "CLLocationManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rangingBeaconsDidFailFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLBeaconRegion",
          "text": "CLBeaconRegion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:rangingBeaconsDidFailFor:withError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationManager:rangingBeaconsDidFailForRegion:withError:"
        }
      ],
      "role": "symbol",
      "title": "locationManager(_:rangingBeaconsDidFailFor:withError:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanagerdelegate/locationmanager(_:rangingbeaconsdidfailfor:witherror:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Receiving-beacon-related-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:didFailRangingFor:error:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:didRangeBeacons:in:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:rangingBeaconsDidFailFor:withError:)"
      ],
      "title": "Receiving beacon-related updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "locationManager:didRangeBeacons:satisfyingConstraint:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationManager:didRangeBeacons:satisfyingConstraint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corelocation/documentation/CoreLocation",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Receiving-beacon-related-updates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:didFailRangingFor:error:)",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:didRangeBeacons:in:)",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManagerDelegate/locationManager(_:rangingBeaconsDidFailFor:withError:)"
              ],
              "title": "Receiving beacon-related updates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "locationManager:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CLLocationManager",
                    "text": "CLLocationManager"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "manager"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didRangeBeacons:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<CLBeacon *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "beacons"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "satisfyingConstraint:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityConstraint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CLBeaconIdentityConstraint",
                    "text": "CLBeaconIdentityConstraint"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "beaconConstraint"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " that corresponds to this delegate.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "manager"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeacon",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " objects.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "beacons"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityConstraint",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " that describes the characteristics of the beacons the location manager is looking for.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "beaconConstraint"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeacon/title",
          "value": "CLBeacon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeacon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLBeacon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeacon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLBeacon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManagerDelegate~1locationManager(_:didRange:satisfying:)/title",
          "value": "locationManager:didRangeBeacons:satisfyingConstraint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManagerDelegate~1locationManager(_:didRange:satisfying:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationManager:didRangeBeacons:satisfyingConstraint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManagerDelegate/title",
          "value": "CLLocationManagerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManagerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManagerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManagerDelegate~1locationManager(_:didFailRangingFor:error:)/title",
          "value": "locationManager:didFailRangingBeaconsForConstraint:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManagerDelegate~1locationManager(_:didFailRangingFor:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationManager:didFailRangingBeaconsForConstraint:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManagerDelegate~1locationManager(_:rangingBeaconsDidFailFor:withError:)/title",
          "value": "locationManager:rangingBeaconsDidFailForRegion:withError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManagerDelegate~1locationManager(_:rangingBeaconsDidFailFor:withError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationManager:rangingBeaconsDidFailForRegion:withError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManagerDelegate~1locationManager(_:didRangeBeacons:in:)/title",
          "value": "locationManager:didRangeBeacons:inRegion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManagerDelegate~1locationManager(_:didRangeBeacons:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationManager:didRangeBeacons:inRegion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/title",
          "value": "CLLocationManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeaconIdentityConstraint/title",
          "value": "CLBeaconIdentityConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeaconIdentityConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLBeaconIdentityConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeaconIdentityConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLBeaconIdentityConstraint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/cllocationmanagerdelegate/locationmanager(_:didrange:satisfying:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/cllocationmanagerdelegate/locationmanager(_:didrange:satisfying:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
