{
  "abstract": [
    {
      "text": "The strength of the vertical correction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/verticalAmount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKVisionPrism(py)verticalAmount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "verticalAmount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HKQuantity",
        "text": "HKQuantity"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "verticalAmount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "verticalAmount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "verticalAmount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKQuantity",
              "text": "HKQuantity"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This parameter holds the vertical component of the prescriptions correction, measured in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUnit/prismDiopter()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " units.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPrismBase": {
      "abstract": [
        {
          "text": "The orientation of the prism correction, represented by the location of the prism’s base (the thickest part of the prism).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPrismBase"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPrismBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPrismBase"
        }
      ],
      "role": "symbol",
      "title": "HKPrismBase",
      "type": "topic",
      "url": "/documentation/healthkit/hkprismbase"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity": {
      "abstract": [
        {
          "text": "An object that stores a value for a given unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKUnit/prismDiopter()": {
      "abstract": [
        {
          "text": "Returns a HealthKit unit for measuring the prismatic deviation of a lens using prism diopter units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prismDiopter"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUnit/prismDiopter()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prismDiopterUnit"
        }
      ],
      "role": "symbol",
      "title": "prismDiopter()",
      "type": "topic",
      "url": "/documentation/healthkit/hkunit/prismdiopter()"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionEye": {
      "abstract": [
        {
          "text": "A value that specifies the eye for a vision prescription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKVisionEye"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionEye",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVisionEye"
        }
      ],
      "role": "symbol",
      "title": "HKVisionEye",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisioneye"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism": {
      "abstract": [
        {
          "text": "Prescription data for eye alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKVisionPrism"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVisionPrism"
        }
      ],
      "role": "symbol",
      "title": "HKVisionPrism",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprism"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/amount": {
      "abstract": [
        {
          "text": "The strength of the correction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/amount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "amount"
        }
      ],
      "role": "symbol",
      "title": "amount",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprism/amount"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/angle": {
      "abstract": [
        {
          "text": "The orientation of the adjustment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "angle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/angle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "angle"
        }
      ],
      "role": "symbol",
      "title": "angle",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprism/angle"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/eye": {
      "abstract": [
        {
          "text": "A value indicating which eye the correction applies to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eye"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKVisionEye",
          "text": "HKVisionEye"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/eye",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eye"
        }
      ],
      "role": "symbol",
      "title": "eye",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprism/eye"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/horizontalAmount": {
      "abstract": [
        {
          "text": "The strength of the horizontal correction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/horizontalAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "horizontalAmount"
        }
      ],
      "role": "symbol",
      "title": "horizontalAmount",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprism/horizontalamount"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/horizontalBase": {
      "abstract": [
        {
          "text": "The orientation of the horizontal portion of the correction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalBase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKPrismBase",
          "text": "HKPrismBase"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/horizontalBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "horizontalBase"
        }
      ],
      "role": "symbol",
      "title": "horizontalBase",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprism/horizontalbase"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/verticalAmount": {
      "abstract": [
        {
          "text": "The strength of the vertical correction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/verticalAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "verticalAmount"
        }
      ],
      "role": "symbol",
      "title": "verticalAmount",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprism/verticalamount"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/verticalBase": {
      "abstract": [
        {
          "text": "The orientation of the vertical portion of the correction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalBase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKPrismBase",
          "text": "HKPrismBase"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/verticalBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "verticalBase"
        }
      ],
      "role": "symbol",
      "title": "verticalBase",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprism/verticalbase"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-lens-specification-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/eye",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionEye",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/amount",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/angle",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/horizontalAmount",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/horizontalBase",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/verticalBase",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPrismBase"
      ],
      "title": "Accessing lens specification data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "verticalAmount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticalAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-lens-specification-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/eye",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionEye",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/amount",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/angle",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/horizontalAmount",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/horizontalBase",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism/verticalBase",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPrismBase"
              ],
              "title": "Accessing lens specification data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HKQuantity",
                    "text": "HKQuantity"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "verticalAmount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1verticalAmount/title",
          "value": "verticalAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1verticalAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticalAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1verticalBase/title",
          "value": "verticalBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1verticalBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticalBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism/title",
          "value": "HKVisionPrism"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionPrism"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionPrism"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/title",
          "value": "HKQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionEye/title",
          "value": "HKVisionEye"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionEye/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionEye"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionEye/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionEye"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1horizontalAmount/title",
          "value": "horizontalAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1horizontalAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "horizontalAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1eye/title",
          "value": "eye"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1eye/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eye"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUnit~1prismDiopter()/title",
          "value": "prismDiopterUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUnit~1prismDiopter()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "prismDiopterUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPrismBase/title",
          "value": "HKPrismBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPrismBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPrismBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPrismBase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPrismBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1horizontalBase/title",
          "value": "horizontalBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1horizontalBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "horizontalBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1angle/title",
          "value": "angle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1angle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "angle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1amount/title",
          "value": "amount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism~1amount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "amount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkvisionprism/verticalamount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkvisionprism/verticalamount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
