{
  "abstract": [
    {
      "text": "An enumeration of flags that control behaviors and features of block buffer APIs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/block-buffer-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Block Buffer Flags"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer": {
      "abstract": [
        {
          "text": "A reference to a block buffer instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBlockBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBlockBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMBlockBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateContiguous(allocator:sourceBuffer:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)": {
      "abstract": [
        {
          "text": "Creates a block buffer that contains a contiguous copy of, or reference to, the data specified by the parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBlockBufferCreateContiguous"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "sourceBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blockAllocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "customBlockSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMBlockBufferCustomBlockSource",
          "text": "CMBlockBufferCustomBlockSource"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "offsetToData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dataLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferFlags",
          "text": "CMBlockBufferFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blockBufferOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateContiguous(allocator:sourceBuffer:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBlockBufferCreateContiguous"
        }
      ],
      "role": "symbol",
      "title": "CMBlockBufferCreateContiguous(allocator:sourceBuffer:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffercreatecontiguous(allocator:sourcebuffer:blockallocator:customblocksource:offsettodata:datalength:flags:blockbufferout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateEmpty(allocator:capacity:flags:blockBufferOut:)": {
      "abstract": [
        {
          "text": "Creates an empty block buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBlockBufferCreateEmpty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "capacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferFlags",
          "text": "CMBlockBufferFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blockBufferOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateEmpty(allocator:capacity:flags:blockBufferOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBlockBufferCreateEmpty"
        }
      ],
      "role": "symbol",
      "title": "CMBlockBufferCreateEmpty(allocator:capacity:flags:blockBufferOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffercreateempty(allocator:capacity:flags:blockbufferout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateWithBufferReference(allocator:referenceBuffer:offsetToData:dataLength:flags:blockBufferOut:)": {
      "abstract": [
        {
          "text": "Creates a block buffer that refers to another block buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBlockBufferCreateWithBufferReference"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "referenceBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offsetToData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dataLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferFlags",
          "text": "CMBlockBufferFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blockBufferOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateWithBufferReference(allocator:referenceBuffer:offsetToData:dataLength:flags:blockBufferOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBlockBufferCreateWithBufferReference"
        }
      ],
      "role": "symbol",
      "title": "CMBlockBufferCreateWithBufferReference(allocator:referenceBuffer:offsetToData:dataLength:flags:blockBufferOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffercreatewithbufferreference(allocator:referencebuffer:offsettodata:datalength:flags:blockbufferout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)": {
      "abstract": [
        {
          "text": "Creates a block buffer that’s backed by a memory block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBlockBufferCreateWithMemoryBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "memoryBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "blockLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blockAllocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "customBlockSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMBlockBufferCustomBlockSource",
          "text": "CMBlockBufferCustomBlockSource"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "offsetToData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dataLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferFlags",
          "text": "CMBlockBufferFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blockBufferOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBlockBufferCreateWithMemoryBlock"
        }
      ],
      "role": "symbol",
      "title": "CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffercreatewithmemoryblock(allocator:memoryblock:blocklength:blockallocator:customblocksource:offsettodata:datalength:flags:blockbufferout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCustomBlockSource": {
      "abstract": [
        {
          "text": "A structure to support custom memory allocation and deallocation for a block used in a block buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBlockBufferCustomBlockSource"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCustomBlockSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBlockBufferCustomBlockSource"
        }
      ],
      "role": "symbol",
      "title": "CMBlockBufferCustomBlockSource",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffercustomblocksource"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferFlags": {
      "abstract": [
        {
          "text": "A type for flags that control behaviors and features of block buffer APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBlockBufferFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBlockBufferFlags"
        }
      ],
      "role": "symbol",
      "title": "CMBlockBufferFlags",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api": {
      "abstract": [
        {
          "text": "An object the system uses to move blocks of memory through a processing system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMBlockBuffer APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffer-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/custom-block-source-version": {
      "abstract": [
        {
          "text": "A custom block source version identifier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/custom-block-source-version",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Custom Block Source Version",
      "type": "topic",
      "url": "/documentation/coremedia/custom-block-source-version"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferAlwaysCopyDataFlag": {
      "abstract": [
        {
          "text": "Used with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to cause it to always produce an allocated copy of the desired data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferAlwaysCopyDataFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferFlags",
          "text": "CMBlockBufferFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferAlwaysCopyDataFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferAlwaysCopyDataFlag"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferAlwaysCopyDataFlag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferalwayscopydataflag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferAssureMemoryNowFlag": {
      "abstract": [
        {
          "text": "When passed to routines that accept block allocators, causes the memory block to be allocated immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferAssureMemoryNowFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferFlags",
          "text": "CMBlockBufferFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferAssureMemoryNowFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferAssureMemoryNowFlag"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferAssureMemoryNowFlag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferassurememorynowflag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferDontOptimizeDepthFlag": {
      "abstract": [
        {
          "text": "Passed to block buffers to suppress reference depth optimization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferDontOptimizeDepthFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferFlags",
          "text": "CMBlockBufferFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferDontOptimizeDepthFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferDontOptimizeDepthFlag"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferDontOptimizeDepthFlag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferdontoptimizedepthflag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferPermitEmptyReferenceFlag": {
      "abstract": [
        {
          "text": "Passed to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to allow references into a ",
          "type": "text"
        },
        {
          "code": "CMBlockBuffer",
          "type": "codeVoice"
        },
        {
          "text": " that may not yet be populated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferPermitEmptyReferenceFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferFlags",
          "text": "CMBlockBufferFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferPermitEmptyReferenceFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferPermitEmptyReferenceFlag"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferPermitEmptyReferenceFlag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferpermitemptyreferenceflag"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Block-Buffer",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateEmpty(allocator:capacity:flags:blockBufferOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateWithBufferReference(allocator:referenceBuffer:offsetToData:dataLength:flags:blockBufferOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateContiguous(allocator:sourceBuffer:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferFlags",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCustomBlockSource",
        "doc://com.apple.coremedia/documentation/CoreMedia/custom-block-source-version"
      ],
      "title": "Creating a Block Buffer"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferAssureMemoryNowFlag",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferAlwaysCopyDataFlag",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferDontOptimizeDepthFlag",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferPermitEmptyReferenceFlag"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferAssureMemoryNowFlag",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferAlwaysCopyDataFlag",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferDontOptimizeDepthFlag",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferPermitEmptyReferenceFlag"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Block-Buffer",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateEmpty(allocator:capacity:flags:blockBufferOut:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateWithBufferReference(allocator:referenceBuffer:offsetToData:dataLength:flags:blockBufferOut:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateContiguous(allocator:sourceBuffer:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferFlags",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCustomBlockSource",
                "doc://com.apple.coremedia/documentation/CoreMedia/custom-block-source-version"
              ],
              "title": "Creating a Block Buffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferAssureMemoryNowFlag/title",
          "value": "kCMBlockBufferAssureMemoryNowFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferAssureMemoryNowFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferAssureMemoryNowFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferAlwaysCopyDataFlag/title",
          "value": "kCMBlockBufferAlwaysCopyDataFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferAlwaysCopyDataFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferAlwaysCopyDataFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCreateWithBufferReference(allocator:referenceBuffer:offsetToData:dataLength:flags:blockBufferOut:)/title",
          "value": "CMBlockBufferCreateWithBufferReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCreateWithBufferReference(allocator:referenceBuffer:offsetToData:dataLength:flags:blockBufferOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferCreateWithBufferReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCreateContiguous(allocator:sourceBuffer:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)/title",
          "value": "CMBlockBufferCreateContiguous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCreateContiguous(allocator:sourceBuffer:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferCreateContiguous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCreateEmpty(allocator:capacity:flags:blockBufferOut:)/title",
          "value": "CMBlockBufferCreateEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCreateEmpty(allocator:capacity:flags:blockBufferOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferCreateEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferPermitEmptyReferenceFlag/title",
          "value": "kCMBlockBufferPermitEmptyReferenceFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferPermitEmptyReferenceFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferPermitEmptyReferenceFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferFlags/title",
          "value": "CMBlockBufferFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBuffer/title",
          "value": "CMBlockBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCustomBlockSource/title",
          "value": "CMBlockBufferCustomBlockSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCustomBlockSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferCustomBlockSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCustomBlockSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferCustomBlockSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferDontOptimizeDepthFlag/title",
          "value": "kCMBlockBufferDontOptimizeDepthFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferDontOptimizeDepthFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferDontOptimizeDepthFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)/title",
          "value": "CMBlockBufferCreateWithMemoryBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferCreateWithMemoryBlock"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/block-buffer-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/block-buffer-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
