{
  "abstract": [
    {
      "text": "Constants that identify chroma location extensions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Chroma Location Extension Constants"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes": {
      "abstract": [
        {
          "text": "Mask codes that identify audio formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Description Mask Codes",
      "type": "topic",
      "url": "/documentation/coremedia/audio-format-desc-codes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify clean aperture extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clean Aperture Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/clean-aperture-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify color primary extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Primary Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/color-primary-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify field detail extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Field Detail Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/field-detail-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors": {
      "abstract": [
        {
          "text": "Bridge errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Bridge Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-bridge-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors": {
      "abstract": [
        {
          "text": "Errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants": {
      "abstract": [
        {
          "text": "Constants that identify HEVC temporal level information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEVC Temporal Level Info Constants",
      "type": "topic",
      "url": "/documentation/coremedia/hevc-temporal-level-info-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Bottom-swift.var": {
      "abstract": [
        {
          "text": "The chroma sample is horizontally centered, but co-sited with the bottom row of the luma samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Bottom-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Bottom"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_Bottom",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_bottom-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_BottomLeft-swift.var": {
      "abstract": [
        {
          "text": "The chroma sample is co-sited with the bottom-left luma sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_BottomLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_BottomLeft-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_BottomLeft"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_BottomLeft",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_bottomleft-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Center-swift.var": {
      "abstract": [
        {
          "text": "The chroma sample is fully centered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Center"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Center-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Center"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_Center",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_center-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_DV420-swift.var": {
      "abstract": [
        {
          "text": "The Cr and Cb samples are alternately co-sited with the left luma samples of the same field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_DV420"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_DV420-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_DV420"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_DV420",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_dv420-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Left-swift.var": {
      "abstract": [
        {
          "text": "The chroma sample is horizontally co-sited with the left column of the luma samples, but centered vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Left-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Left"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_Left",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_left-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Top-swift.var": {
      "abstract": [
        {
          "text": "The chroma sample is horizontally centered, but co-sited with the top row of the luma samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Top-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Top"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_Top",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_top-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_TopLeft-swift.var": {
      "abstract": [
        {
          "text": "The chroma sample is co-sited with the top-left luma sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_TopLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_TopLeft-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_TopLeft"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_TopLeft",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_topleft-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify metadata format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats": {
      "abstract": [
        {
          "text": "Constants that identify MPEG-2 formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MPEG-2-conformant Formats",
      "type": "topic",
      "url": "/documentation/coremedia/mpeg-2-conformant-formats"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify pixel aspect ratio extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Aspect Ratio Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/pixel-aspect-ratio-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify text format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/text-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify time code format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify transfer function extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transfer Function Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/transfer-function-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify YCbCrMatrix extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "YCbCrMatrix Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/ycbcrmatrix-extension-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
        "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Bottom-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_BottomLeft-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Center-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_DV420-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Left-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Top-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_TopLeft-swift.var"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Bottom-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_BottomLeft-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Center-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_DV420-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Left-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Top-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_TopLeft-swift.var"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
                "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_DV420-swift.var/title",
          "value": "kCMFormatDescriptionChromaLocation_DV420"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_DV420-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionChromaLocation_DV420"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_BottomLeft-swift.var/title",
          "value": "kCMFormatDescriptionChromaLocation_BottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_BottomLeft-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionChromaLocation_BottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_Bottom-swift.var/title",
          "value": "kCMFormatDescriptionChromaLocation_Bottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_Bottom-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionChromaLocation_Bottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_Center-swift.var/title",
          "value": "kCMFormatDescriptionChromaLocation_Center"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_Center-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionChromaLocation_Center"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_TopLeft-swift.var/title",
          "value": "kCMFormatDescriptionChromaLocation_TopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_TopLeft-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionChromaLocation_TopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_Left-swift.var/title",
          "value": "kCMFormatDescriptionChromaLocation_Left"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_Left-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionChromaLocation_Left"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_Top-swift.var/title",
          "value": "kCMFormatDescriptionChromaLocation_Top"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionChromaLocation_Top-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionChromaLocation_Top"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/chroma-location-extension-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/chroma-location-extension-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
