{
  "abstract": [
    {
      "text": "Add supporting metadata to sample buffers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmattachment-api"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMAttachment APIs"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An attachment bearer is a Core Foundation type object that supports the suite of key, value, and mode attachment APIs. You can attach any Core Foundation object to an attachment bearer to store additional information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearer": {
      "abstract": [
        {
          "text": "An object that can carry attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAttachmentBearer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAttachmentBearer"
        }
      ],
      "role": "symbol",
      "title": "CMAttachmentBearer",
      "type": "topic",
      "url": "/documentation/coremedia/cmattachmentbearer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearerProtocol": {
      "abstract": [
        {
          "text": "A protocol for objects that can carry attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAttachmentBearerProtocol"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearerProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAttachmentBearerProtocol"
        }
      ],
      "role": "symbol",
      "title": "CMAttachmentBearerProtocol",
      "type": "topic",
      "url": "/documentation/coremedia/cmattachmentbearerprotocol"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentMode": {
      "abstract": [
        {
          "text": "The mode to use when propagating attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAttachmentMode"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAttachmentMode"
        }
      ],
      "role": "symbol",
      "title": "CMAttachmentMode",
      "type": "topic",
      "url": "/documentation/coremedia/cmattachmentmode"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)": {
      "abstract": [
        {
          "text": "Returns a dictionary of all attachments for an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMCopyDictionaryOfAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attachmentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMCopyDictionaryOfAttachments"
        }
      ],
      "role": "symbol",
      "title": "CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmcopydictionaryofattachments(allocator:target:attachmentmode:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMGetAttachment(_:key:attachmentModeOut:)": {
      "abstract": [
        {
          "text": "Returns an attachment from an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMGetAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attachmentModeOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMGetAttachment(_:key:attachmentModeOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMGetAttachment"
        }
      ],
      "role": "symbol",
      "title": "CMGetAttachment(_:key:attachmentModeOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmgetattachment(_:key:attachmentmodeout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPropagateAttachments(_:destination:)": {
      "abstract": [
        {
          "text": "Copies all propagable attachments from one attachment bearer object to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPropagateAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPropagateAttachments(_:destination:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPropagateAttachments"
        }
      ],
      "role": "symbol",
      "title": "CMPropagateAttachments(_:destination:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmpropagateattachments(_:destination:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAllAttachments(_:)": {
      "abstract": [
        {
          "text": "Removes all attachments from an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMRemoveAllAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAllAttachments(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMRemoveAllAttachments"
        }
      ],
      "role": "symbol",
      "title": "CMRemoveAllAttachments(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmremoveallattachments(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAttachment(_:key:)": {
      "abstract": [
        {
          "text": "Removes a specific attachment from an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMRemoveAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAttachment(_:key:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMRemoveAttachment"
        }
      ],
      "role": "symbol",
      "title": "CMRemoveAttachment(_:key:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmremoveattachment(_:key:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachment(_:key:value:attachmentMode:)": {
      "abstract": [
        {
          "text": "Sets or adds an attachment to an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSetAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "attachmentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachment(_:key:value:attachmentMode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSetAttachment"
        }
      ],
      "role": "symbol",
      "title": "CMSetAttachment(_:key:value:attachmentMode:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsetattachment(_:key:value:attachmentmode:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachments(_:attachments:attachmentMode:)": {
      "abstract": [
        {
          "text": "Sets a dictionary of attachments on an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSetAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attachments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attachmentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachments(_:attachments:attachmentMode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSetAttachments"
        }
      ],
      "role": "symbol",
      "title": "CMSetAttachments(_:attachments:attachmentMode:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsetattachments(_:attachments:attachmentmode:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer": {
      "abstract": [
        {
          "text": "An instance of a media buffer containing metadata tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTaggedBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTaggedBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMTaggedBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api": {
      "abstract": [
        {
          "text": "An object the system uses to move blocks of memory through a processing system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMBlockBuffer APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffer-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api": {
      "abstract": [
        {
          "text": "An object that contains zero or more media samples of a uniform media type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSampleBuffer APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtaggedbuffergroup": {
      "abstract": [
        {
          "text": "Objective-C types and interfaces for working with Core Media tagged buffer groups.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtaggedbuffergroup",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTaggedBufferGroup APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroup"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldNotPropagate": {
      "abstract": [
        {
          "text": "A mode that doesn’t propagate attachments to another object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMAttachmentMode_ShouldNotPropagate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldNotPropagate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMAttachmentMode_ShouldNotPropagate"
        }
      ],
      "role": "symbol",
      "title": "kCMAttachmentMode_ShouldNotPropagate",
      "type": "topic",
      "url": "/documentation/coremedia/kcmattachmentmode_shouldnotpropagate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldPropagate": {
      "abstract": [
        {
          "text": "A mode that propagates attachments to another object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMAttachmentMode_ShouldPropagate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldPropagate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMAttachmentMode_ShouldPropagate"
        }
      ],
      "role": "symbol",
      "title": "kCMAttachmentMode_ShouldPropagate",
      "type": "topic",
      "url": "/documentation/coremedia/kcmattachmentmode_shouldpropagate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount": {
      "abstract": [
        {
          "text": "An attachment that’s only present if the audio sample is an independent frame or immediate playout frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_audioindependentsampledecoderrefreshcount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData": {
      "abstract": [
        {
          "text": "An attachment that describes the ranges of protected and unprotected data within a protected sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_cryptorsubsampleauxiliarydata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess": {
      "abstract": [
        {
          "text": "An attachment that indicates a step-wise temporal sublayer access (STSA) sample grouping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_hevcstepwisetemporalsublayeraccess"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType": {
      "abstract": [
        {
          "text": "An attachment that indicates a sync sample NAL unit type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_hevcsyncsamplenalunittype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalLevelInfo": {
      "abstract": [
        {
          "text": "An attachment that indicates a video frame’s level within a hierarchical frame dependency structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCTemporalLevelInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalLevelInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCTemporalLevelInfo"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HEVCTemporalLevelInfo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_hevctemporallevelinfo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess": {
      "abstract": [
        {
          "text": "An attachment that indicates a temporal sublayer access grouping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_hevctemporalsublayeraccess"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix": {
      "abstract": [
        {
          "text": "An attachment that indicates a 3x3 camera intrinsic matrix to apply to the current sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_cameraintrinsicmatrix"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sample-Processing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtaggedbuffergroup",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ],
      "title": "Sample Processing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Processing-Attachments",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMGetAttachment(_:key:attachmentModeOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachment(_:key:value:attachmentMode:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachments(_:attachments:attachmentMode:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAttachment(_:key:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAllAttachments(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPropagateAttachments(_:destination:)"
      ],
      "title": "Processing Attachments"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearerProtocol",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearer",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentMode"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldNotPropagate",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldPropagate",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalLevelInfo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Processing-Attachments",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMGetAttachment(_:key:attachmentModeOut:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachment(_:key:value:attachmentMode:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachments(_:attachments:attachmentMode:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAttachment(_:key:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAllAttachments(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPropagateAttachments(_:destination:)"
              ],
              "title": "Processing Attachments"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearer",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentMode"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldNotPropagate",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldPropagate",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalLevelInfo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sample-Processing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtaggedbuffergroup",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
              ],
              "title": "Sample Processing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix/title",
          "value": "kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentBearer/title",
          "value": "CMAttachmentBearerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentBearer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAttachmentBearerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentBearer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAttachmentBearerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAttachmentMode_ShouldNotPropagate/title",
          "value": "kCMAttachmentMode_ShouldNotPropagate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAttachmentMode_ShouldNotPropagate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMAttachmentMode_ShouldNotPropagate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess/title",
          "value": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType/title",
          "value": "kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAttachmentMode_ShouldPropagate/title",
          "value": "kCMAttachmentMode_ShouldPropagate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAttachmentMode_ShouldPropagate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMAttachmentMode_ShouldPropagate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentMode/title",
          "value": "CMAttachmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAttachmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAttachmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSetAttachments(_:attachments:attachmentMode:)/title",
          "value": "CMSetAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSetAttachments(_:attachments:attachmentMode:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSetAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount/title",
          "value": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPropagateAttachments(_:destination:)/title",
          "value": "CMPropagateAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPropagateAttachments(_:destination:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPropagateAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCTemporalLevelInfo/title",
          "value": "kCMSampleAttachmentKey_HEVCTemporalLevelInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCTemporalLevelInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HEVCTemporalLevelInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSetAttachment(_:key:value:attachmentMode:)/title",
          "value": "CMSetAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSetAttachment(_:key:value:attachmentMode:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData/title",
          "value": "kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMGetAttachment(_:key:attachmentModeOut:)/title",
          "value": "CMGetAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMGetAttachment(_:key:attachmentModeOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMGetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess/title",
          "value": "kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)/title",
          "value": "CMCopyDictionaryOfAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMCopyDictionaryOfAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMRemoveAllAttachments(_:)/title",
          "value": "CMRemoveAllAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMRemoveAllAttachments(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMRemoveAllAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMRemoveAttachment(_:key:)/title",
          "value": "CMRemoveAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMRemoveAttachment(_:key:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMRemoveAttachment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmattachment-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmattachment-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
