{
  "abstract": [
    {
      "text": "A protocol for objects that operate on a range of a block buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9CoreMedia21CMBlockBufferProtocolP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMBlockBufferProtocol"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMBlockBufferProtocol"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CMBlockBufferProtocol"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMBlockBufferProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer": {
      "abstract": [
        {
          "text": "A reference to a block buffer instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBlockBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBlockBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMBlockBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer/Slice": {
      "abstract": [
        {
          "text": "A structure that defines a slice of a block buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Slice"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer/Slice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Slice"
        }
      ],
      "role": "symbol",
      "title": "CMBlockBuffer.Slice",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffer/slice"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol": {
      "abstract": [
        {
          "text": "A protocol for objects that operate on a range of a block buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBlockBufferProtocol"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBlockBufferProtocol"
        }
      ],
      "role": "symbol",
      "title": "CMBlockBufferProtocol",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/copyDataBytes(to:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyDataBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sw",
          "text": "UnsafeMutableRawBufferPointer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/copyDataBytes(to:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "copyDataBytes(to:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/copydatabytes(to:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/dataBytes()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataBytes"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/dataBytes()",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataBytes()",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/databytes()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/dataLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/dataLength",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataLength",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/datalength"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/endIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/endIndex",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "endIndex",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/endindex"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/fillDataBytes(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fillDataBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/fillDataBytes(with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "fillDataBytes(with:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/filldatabytes(with:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/isContiguous": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isContiguous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/isContiguous",
      "kind": "symbol",
      "role": "symbol",
      "title": "isContiguous",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/iscontiguous"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/makeContiguous(allocator:deallocator:flags:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeContiguous"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBlockBufferRefa9CoreMediaE20CustomBlockAllocatora",
          "text": "CustomBlockAllocator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deallocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBlockBufferRefa9CoreMediaE22CustomBlockDeallocatora",
          "text": "CustomBlockDeallocator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBlockBufferRefa9CoreMediaE5FlagsV",
          "text": "Flags"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/makeContiguous(allocator:deallocator:flags:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "makeContiguous(allocator:deallocator:flags:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/makecontiguous(allocator:deallocator:flags:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/makeContiguous(allocator:flags:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeContiguous"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBlockBufferRefa9CoreMediaE5FlagsV",
          "text": "Flags"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/makeContiguous(allocator:flags:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "makeContiguous(allocator:flags:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/makecontiguous(allocator:flags:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/owner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "owner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/owner",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "owner",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/owner"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/replaceDataBytes(with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceDataBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SW",
          "text": "UnsafeRawBufferPointer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/replaceDataBytes(with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "replaceDataBytes(with:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/replacedatabytes(with:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/startIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/startIndex",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "startIndex",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/startindex"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-1go3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBlockBufferRefa9CoreMediaE5SliceV",
          "text": "Slice"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-1go3",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/subscript(_:)-1go3"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-532k5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s19PartialRangeThroughV",
          "text": "PartialRangeThrough"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBlockBufferRefa9CoreMediaE5SliceV",
          "text": "Slice"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-532k5",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/subscript(_:)-532k5"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-6ghj4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s16PartialRangeUpToV",
          "text": "PartialRangeUpTo"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBlockBufferRefa9CoreMediaE5SliceV",
          "text": "Slice"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-6ghj4",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/subscript(_:)-6ghj4"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-7a30d": {
      "abstract": [
        {
          "text": "Creates a slice from a ",
          "type": "text"
        },
        {
          "code": "ClosedRange",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SN",
          "text": "ClosedRange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBlockBufferRefa9CoreMediaE5SliceV",
          "text": "Slice"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-7a30d",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/subscript(_:)-7a30d"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-8jilq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s15UnboundedRange_O",
          "text": "UnboundedRange_"
        },
        {
          "kind": "text",
          "text": ") -> ()) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBlockBufferRefa9CoreMediaE5SliceV",
          "text": "Slice"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-8jilq",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/subscript(_:)-8jilq"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-9ntfs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s16PartialRangeFromV",
          "text": "PartialRangeFrom"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBlockBufferRefa9CoreMediaE5SliceV",
          "text": "Slice"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-9ntfs",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/subscript(_:)-9ntfs"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/withContiguousStorage(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withContiguousStorage"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SW",
          "text": "UnsafeRawBufferPointer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/withContiguousStorage(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "withContiguousStorage(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbufferprotocol/withcontiguousstorage(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer/Slice"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBuffer"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Modifying-a-Block-Buffer",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/copyDataBytes(to:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/dataBytes()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/fillDataBytes(with:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/replaceDataBytes(with:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/isContiguous",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/makeContiguous(allocator:deallocator:flags:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/makeContiguous(allocator:flags:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/withContiguousStorage(_:)"
      ],
      "title": "Modifying a Block Buffer"
    },
    {
      "anchor": "Inspecting-a-Block-Buffer",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/dataLength",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/startIndex",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/endIndex",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/owner"
      ],
      "title": "Inspecting a Block Buffer"
    },
    {
      "anchor": "Subscripts",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-7a30d",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-1go3",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-9ntfs",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-6ghj4",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-532k5",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferProtocol/subscript(_:)-8jilq"
      ],
      "title": "Subscripts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBuffer/title",
          "value": "CMBlockBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmblockbufferprotocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
