{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMBufferCompareHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMBufferCompareHandler"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMBufferCompareHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CMBufferCompareHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMBufferCompareHandler"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMBufferRef",
              "text": "CMBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMBufferRef",
              "text": "CMBuffer"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@CFComparisonResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CFComparisonResult",
              "text": "CFComparisonResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer": {
      "abstract": [
        {
          "text": "A reference to a buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferCompareHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferCompareHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferCompareHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercomparehandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetBooleanHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetBooleanHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetBooleanHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergetbooleanhandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetSizeHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetSizeHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetSizeHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergetsizehandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetTimeHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetTimeHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetTimeHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergettimehandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription": {
      "abstract": [
        {
          "text": "A type for tagged buffer format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMTaggedBufferGroupFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType": {
      "abstract": [
        {
          "text": "A type for tagged buffer format information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMTaggedBufferGroupFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupformattype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@CFComparisonResult": {
      "abstract": [
        {
          "text": "Constants returned by comparison functions, indicating whether a value is equal to, less than, or greater than another value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "enum "
        },
        {
          "kind": "identifier",
          "text": "CFComparisonResult"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@CFComparisonResult",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFComparisonResult",
      "type": "topic",
      "url": "/documentation/corefoundation/cfcomparisonresult"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMBufferCompareHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCompareHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCompareHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Aliases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanHandler",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeHandler",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeHandler",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BF$@E@CFComparisonResult(#*1v#S3_)",
                    "text": "enum CFComparisonResult (^)(const void *, const void *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMBufferCompareHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeHandler/title",
          "value": "CMBufferGetSizeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetSizeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetSizeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeHandler/title",
          "value": "CMBufferGetTimeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetTimeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetTimeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatDescription/title",
          "value": "CMTaggedBufferGroupFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/title",
          "value": "CMBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareHandler/title",
          "value": "CMBufferCompareHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCompareHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCompareHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanHandler/title",
          "value": "CMBufferGetBooleanHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetBooleanHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetBooleanHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatType/title",
          "value": "CMTaggedBufferGroupFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmbuffercomparehandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmbuffercomparehandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
