{
  "abstract": [
    {
      "text": "A reference to a buffer queue instance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMBufferQueueRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMBufferQueue"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMBufferQueue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CMBufferQueue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMBufferQueue"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "CMBufferQueue",
              "type": "codeVoice"
            },
            {
              "text": " is a queue of timed buffers backed by a Core Foundation object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue": {
      "abstract": [
        {
          "text": "A reference to a buffer queue instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/Buffers-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Buffers"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/Buffers-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Buffers"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue.Buffers",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/buffers-swift.struct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/Error": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue.Error",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/error"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/Handlers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Handlers"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/Handlers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Handlers"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue.Handlers",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/handlers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition": {
      "abstract": [
        {
          "text": "An enumeration of trigger conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TriggerCondition"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerToken": {
      "abstract": [
        {
          "text": "A type alias for a trigger token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TriggerToken"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TriggerToken"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue.TriggerToken",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggertoken"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/bufferCount": {
      "abstract": [
        {
          "text": "The count of buffers in the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bufferCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMItemCount",
          "text": "CMItemCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/bufferCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "bufferCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/buffercount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/buffers-swift.property": {
      "abstract": [
        {
          "text": "The buffers that the queue contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buffers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBufferQueueRefa9CoreMediaE7BuffersV",
          "text": "Buffers"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/buffers-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "buffers",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/buffers-swift.property"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/containsEndOfData": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the buffer has its end-of-data state set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsEndOfData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/containsEndOfData",
      "kind": "symbol",
      "role": "symbol",
      "title": "containsEndOfData",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/containsendofdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeue()": {
      "abstract": [
        {
          "text": "Dequeues a buffer from the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dequeue"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeue()",
      "kind": "symbol",
      "role": "symbol",
      "title": "dequeue()",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/dequeue()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeueIfDataReady()": {
      "abstract": [
        {
          "text": "Dequeues a buffer from the queue, if it’s ready.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dequeueIfDataReady"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeueIfDataReady()",
      "kind": "symbol",
      "role": "symbol",
      "title": "dequeueIfDataReady()",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/dequeueifdataready()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/duration": {
      "abstract": [
        {
          "text": "The sum of all durations of buffers in the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/duration",
      "kind": "symbol",
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/duration"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/endPresentationTimeStamp": {
      "abstract": [
        {
          "text": "The greatest end presentation timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endPresentationTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/endPresentationTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "endPresentationTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/endpresentationtimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/enqueue(_:)": {
      "abstract": [
        {
          "text": "Enqueues a buffer to the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enqueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/enqueue(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "enqueue(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/enqueue(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/firstDecodeTimeStamp": {
      "abstract": [
        {
          "text": "The decode timestamp of the first buffer in the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstDecodeTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/firstDecodeTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "firstDecodeTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/firstdecodetimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/firstPresentationTimeStamp": {
      "abstract": [
        {
          "text": "The presentation timestamp of the first buffer in the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstPresentationTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/firstPresentationTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "firstPresentationTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/firstpresentationtimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/head": {
      "abstract": [
        {
          "text": "The element at the head of the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "head"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/head",
      "kind": "symbol",
      "role": "symbol",
      "title": "head",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/head"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/installTrigger(condition:_:)": {
      "abstract": [
        {
          "text": "Installs a trigger on the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "installTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "condition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBufferQueueRefa9CoreMediaE16TriggerConditionO",
          "text": "TriggerCondition"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerHandler",
          "text": "CMBufferQueueTriggerHandler"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBufferQueueRefa9CoreMediaE12TriggerTokena",
          "text": "TriggerToken"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/installTrigger(condition:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "installTrigger(condition:_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/installtrigger(condition:_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/isAtEndOfData": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether that queue is at the end of its data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAtEndOfData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/isAtEndOfData",
      "kind": "symbol",
      "role": "symbol",
      "title": "isAtEndOfData",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/isatendofdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/isEmpty": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the queue contains buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEmpty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/isEmpty",
      "kind": "symbol",
      "role": "symbol",
      "title": "isEmpty",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/isempty"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/markEndOfData()": {
      "abstract": [
        {
          "text": "Marks a buffer as being at the end of its data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markEndOfData"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/markEndOfData()",
      "kind": "symbol",
      "role": "symbol",
      "title": "markEndOfData()",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/markendofdata()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/maxPresentationTimeStamp": {
      "abstract": [
        {
          "text": "The greatest presentation timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxPresentationTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/maxPresentationTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "maxPresentationTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/maxpresentationtimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/minDecodeTimeStamp": {
      "abstract": [
        {
          "text": "The earliest decode timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minDecodeTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/minDecodeTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "minDecodeTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/mindecodetimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/minPresentationTimeStamp": {
      "abstract": [
        {
          "text": "The earliest presentation timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minPresentationTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/minPresentationTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "minPresentationTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/minpresentationtimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/removeTrigger(_:)": {
      "abstract": [
        {
          "text": "Removes a trigger from the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBufferQueueRefa9CoreMediaE12TriggerTokena",
          "text": "TriggerToken"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/removeTrigger(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeTrigger(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/removetrigger(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset()": {
      "abstract": [
        {
          "text": "Empties the queue and resets its end-of-data state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reset"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset()",
      "kind": "symbol",
      "role": "symbol",
      "title": "reset()",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/reset()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset(_:)": {
      "abstract": [
        {
          "text": "Resets a buffer with a callback block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reset"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ()) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "reset(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/reset(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/setValidationHandler(_:)": {
      "abstract": [
        {
          "text": "Sets validation handler for the queue to call before enqueuing buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setValidationHandler"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/setValidationHandler(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setValidationHandler(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/setvalidationhandler(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/testTrigger(_:)": {
      "abstract": [
        {
          "text": "Tests a trigger condition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So16CMBufferQueueRefa9CoreMediaE12TriggerTokena",
          "text": "TriggerToken"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/testTrigger(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "testTrigger(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/testtrigger(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/totalSize": {
      "abstract": [
        {
          "text": "The total size of all buffers in the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/totalSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "totalSize",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/totalsize"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/typeID": {
      "abstract": [
        {
          "text": "The type identifier for this object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/typeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "typeID",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/typeid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Managing-a-Queue",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/enqueue(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeue()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeueIfDataReady()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/markEndOfData()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset(_:)"
      ],
      "title": "Managing a Queue"
    },
    {
      "anchor": "Managing-Triggers",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/installTrigger(condition:_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/removeTrigger(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/testTrigger(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerToken",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition"
      ],
      "title": "Managing Triggers"
    },
    {
      "anchor": "Inspecting-Duration-and-Timing",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/duration",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/totalSize",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/firstDecodeTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/firstPresentationTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/endPresentationTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/minDecodeTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/minPresentationTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/maxPresentationTimeStamp"
      ],
      "title": "Inspecting Duration and Timing"
    },
    {
      "anchor": "Inspecting-a-Queue",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/isEmpty",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/bufferCount",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/head",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/containsEndOfData",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/isAtEndOfData"
      ],
      "title": "Inspecting a Queue"
    },
    {
      "anchor": "Validating-a-Queue",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/setValidationHandler(_:)"
      ],
      "title": "Validating a Queue"
    },
    {
      "anchor": "Accessing-Buffers",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/buffers-swift.property"
      ],
      "title": "Accessing Buffers"
    },
    {
      "anchor": "Accessing-the-Type-Identifier",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/typeID"
      ],
      "title": "Accessing the Type Identifier"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/Buffers-swift.struct",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/Handlers",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/Error"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMBufferQueueRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@opaqueCMBufferQueue",
                    "text": "opaqueCMBufferQueue"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMBufferQueueRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/title",
          "value": "CMBufferQueueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmbufferqueue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmbufferqueue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
