{
  "abstract": [
    {
      "text": "Gets the number of buffers in the queue.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueGetBufferCount(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMBufferQueueGetBufferCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMBufferQueueGetBufferCount"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMBufferQueueRef",
        "text": "CMBufferQueue"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMItemCount",
        "text": "CMItemCount"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMBufferQueueGetBufferCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMBufferQueueGetBufferCount(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMBufferQueueGetBufferCount"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMBufferQueueRef",
              "text": "CMBufferQueue"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMItemCount",
              "text": "CMItemCount"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "code": "CMBufferQueue",
                  "type": "codeVoice"
                },
                {
                  "text": " being interrogated.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "queue"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns the number of buffers in the ",
              "type": "text"
            },
            {
              "code": "CMBufferQueue",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue": {
      "abstract": [
        {
          "text": "A reference to a buffer queue instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueContainsEndOfData(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a buffer queue has its end-of-data marker set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueContainsEndOfData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueContainsEndOfData(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueContainsEndOfData"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueContainsEndOfData(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuecontainsendofdata(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueGetBufferCount(_:)": {
      "abstract": [
        {
          "text": "Gets the number of buffers in the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueGetBufferCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMItemCount",
          "text": "CMItemCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueGetBufferCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueGetBufferCount"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueGetBufferCount(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuegetbuffercount(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueGetHead(_:)": {
      "abstract": [
        {
          "text": "Retrieves the next buffer from a queue, but doesn’t remove it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueGetHead"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueGetHead(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueGetHead"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueGetHead(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuegethead(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueGetTotalSize(_:)": {
      "abstract": [
        {
          "text": "Gets the total size of all sample buffers of a buffer queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueGetTotalSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueGetTotalSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueGetTotalSize"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueGetTotalSize(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuegettotalsize(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueIsAtEndOfData(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a buffer queue has its end-of-data marker set, and is now empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueIsAtEndOfData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueIsAtEndOfData(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueIsAtEndOfData"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueIsAtEndOfData(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueueisatendofdata(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueIsEmpty(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a buffer queue is empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueIsEmpty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueIsEmpty(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueIsEmpty"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueIsEmpty(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueueisempty(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount": {
      "abstract": [
        {
          "text": "A datatype that represents an item count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "role": "symbol",
      "title": "CMItemCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmitemcount"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-Queue",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueIsEmpty(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueGetTotalSize(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueGetHead(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueContainsEndOfData(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueIsAtEndOfData(_:)"
      ],
      "title": "Inspecting a Queue"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMBufferQueueGetBufferCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueGetBufferCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-Queue",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueIsEmpty(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueGetTotalSize(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueGetHead(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueContainsEndOfData(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueIsAtEndOfData(_:)"
              ],
              "title": "Inspecting a Queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMItemCount",
                    "text": "CMItemCount"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMBufferQueueGetBufferCount"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMBufferQueueRef",
                    "text": "CMBufferQueueRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "queue"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "",
                        "type": "text"
                      },
                      {
                        "code": "CMBufferQueue",
                        "type": "codeVoice"
                      },
                      {
                        "text": " being interrogated.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "queue"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Returns the number of buffers in the ",
                    "type": "text"
                  },
                  {
                    "code": "CMBufferQueue",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueGetBufferCount(_:)/title",
          "value": "CMBufferQueueGetBufferCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueGetBufferCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueGetBufferCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueGetHead(_:)/title",
          "value": "CMBufferQueueGetHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueGetHead(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueGetHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueIsAtEndOfData(_:)/title",
          "value": "CMBufferQueueIsAtEndOfData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueIsAtEndOfData(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueIsAtEndOfData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/title",
          "value": "CMBufferQueueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/title",
          "value": "CMItemCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueIsEmpty(_:)/title",
          "value": "CMBufferQueueIsEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueIsEmpty(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueIsEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueContainsEndOfData(_:)/title",
          "value": "CMBufferQueueContainsEndOfData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueContainsEndOfData(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueContainsEndOfData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueGetTotalSize(_:)/title",
          "value": "CMBufferQueueGetTotalSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueGetTotalSize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueGetTotalSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmbufferqueuegetbuffercount(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmbufferqueuegetbuffercount(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
