{
  "abstract": [
    {
      "text": "Callback that returns a Boolean value from a ",
      "type": "text"
    },
    {
      "code": "CMBuffer",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanCallback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMBufferGetBooleanCallback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMBufferGetBooleanCallback"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMBufferGetBooleanCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CMBufferGetBooleanCallback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMBufferGetBooleanCallback"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMBufferRef",
              "text": "CMBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:6Darwin0A7BooleanV",
              "text": "DarwinBoolean"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "There is one callback of this type that can be provided to ",
              "type": "text"
            },
            {
              "code": "Creating Buffer Queues",
              "type": "codeVoice"
            },
            {
              "text": ": ",
              "type": "text"
            },
            {
              "code": "isDataReady",
              "type": "codeVoice"
            },
            {
              "text": " (optional).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Callback-Parameters",
          "level": 3,
          "text": "Callback Parameters",
          "type": "heading"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The buffer being interrogated.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "buf",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The contextual data from the client (which may be ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ").",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "refcon",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer": {
      "abstract": [
        {
          "text": "A reference to a buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/compare": {
      "abstract": [
        {
          "text": "This callback is called multiple times from ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueEnqueue(_:buffer:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", to perform an insertion sort.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferCompareCallback",
          "text": "CMBufferCompareCallback"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/compare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compare"
        }
      ],
      "role": "symbol",
      "title": "compare",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercallbacks/compare"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/dataBecameReadyNotification": {
      "abstract": [
        {
          "text": "If triggers of type ",
          "type": "text"
        },
        {
          "code": "kCMBufferQueueTrigger_WhenDataBecomesReady",
          "type": "codeVoice"
        },
        {
          "text": " are installed, the queue will listen for this notification on the head buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataBecameReadyNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/dataBecameReadyNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataBecameReadyNotification"
        }
      ],
      "role": "symbol",
      "title": "dataBecameReadyNotification",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercallbacks/databecamereadynotification"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getDecodeTimeStamp": {
      "abstract": [
        {
          "text": "Client callback that returns a ",
          "type": "text"
        },
        {
          "code": "CMTime",
          "type": "codeVoice"
        },
        {
          "text": " from a ",
          "type": "text"
        },
        {
          "code": "CMBuffer",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getDecodeTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferGetTimeCallback",
          "text": "CMBufferGetTimeCallback"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getDecodeTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getDecodeTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "getDecodeTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercallbacks/getdecodetimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getDuration": {
      "abstract": [
        {
          "text": "This callback is called (once) during enqueue and dequeue operations to update the total duration of the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferGetTimeCallback",
          "text": "CMBufferGetTimeCallback"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getDuration"
        }
      ],
      "role": "symbol",
      "title": "getDuration",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercallbacks/getduration"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getPresentationTimeStamp": {
      "abstract": [
        {
          "text": "Client callback that returns a ",
          "type": "text"
        },
        {
          "code": "CMTime",
          "type": "codeVoice"
        },
        {
          "text": " from a ",
          "type": "text"
        },
        {
          "code": "CMBuffer",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getPresentationTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferGetTimeCallback",
          "text": "CMBufferGetTimeCallback"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getPresentationTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getPresentationTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "getPresentationTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercallbacks/getpresentationtimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferGetSizeCallback",
          "text": "CMBufferGetSizeCallback"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getSize"
        }
      ],
      "role": "symbol",
      "title": "getSize",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercallbacks/getsize"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/isDataReady": {
      "abstract": [
        {
          "text": "This callback is called from ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeueIfDataReady(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", to ask if the buffer that is about to be dequeued is ready.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDataReady"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferGetBooleanCallback",
          "text": "CMBufferGetBooleanCallback"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/isDataReady",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isDataReady"
        }
      ],
      "role": "symbol",
      "title": "isDataReady",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercallbacks/isdataready"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/refcon": {
      "abstract": [
        {
          "text": "Contextual data to be passed to all callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/refcon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "refcon"
        }
      ],
      "role": "symbol",
      "title": "refcon",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercallbacks/refcon"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/version": {
      "abstract": [
        {
          "text": "The callback version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercallbacks/version"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareCallback": {
      "abstract": [
        {
          "text": "Callback that compares one ",
          "type": "text"
        },
        {
          "code": "CMBuffer",
          "type": "codeVoice"
        },
        {
          "text": " with another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferCompareCallback"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferCompareCallback"
        }
      ],
      "role": "symbol",
      "title": "CMBufferCompareCallback",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercomparecallback"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanCallback": {
      "abstract": [
        {
          "text": "Callback that returns a Boolean value from a ",
          "type": "text"
        },
        {
          "code": "CMBuffer",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetBooleanCallback"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetBooleanCallback"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetBooleanCallback",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergetbooleancallback"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeCallback": {
      "abstract": [
        {
          "text": "Callback that returns a ",
          "type": "text"
        },
        {
          "code": "CMTime",
          "type": "codeVoice"
        },
        {
          "text": " from a ",
          "type": "text"
        },
        {
          "code": "CMBuffer",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetTimeCallback"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetTimeCallback"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetTimeCallback",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergettimecallback"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeueIfDataReady(_:)": {
      "abstract": [
        {
          "text": "Dequeues a buffer from a queue, if it’s ready.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueDequeueIfDataReady"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeueIfDataReady(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueDequeueIfDataReadyAndRetain"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueDequeueIfDataReady(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuedequeueifdataready(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueEnqueue(_:buffer:)": {
      "abstract": [
        {
          "text": "Enqueues a buffer onto a queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueEnqueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "buffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueEnqueue(_:buffer:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueEnqueue"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueEnqueue(_:buffer:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueueenqueue(_:buffer:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/compare",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareCallback",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeCallback",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/dataBecameReadyNotification",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getDecodeTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getDuration",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getPresentationTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getSize",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/isDataReady",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/refcon",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/version"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMBufferGetBooleanCallback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetBooleanCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetBooleanCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/compare",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareCallback",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeCallback",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/dataBecameReadyNotification",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getDecodeTimeStamp",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getDuration",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getPresentationTimeStamp",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/getSize",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/isDataReady",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/refcon",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks/version"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*Fc(#*1v#*v)",
                    "text": "unsigned char (*)(const void *, void *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMBufferGetBooleanCallback"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1refcon/title",
          "value": "refcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1refcon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "refcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/title",
          "value": "CMBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1isDataReady/title",
          "value": "isDataReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1isDataReady/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isDataReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanCallback/title",
          "value": "CMBufferGetBooleanCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetBooleanCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetBooleanCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareCallback/title",
          "value": "CMBufferCompareCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCompareCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCompareCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeCallback/title",
          "value": "CMBufferGetTimeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetTimeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetTimeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1getSize/title",
          "value": "getSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1getSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1dataBecameReadyNotification/title",
          "value": "dataBecameReadyNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1dataBecameReadyNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataBecameReadyNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueDequeueIfDataReady(_:)/title",
          "value": "CMBufferQueueDequeueIfDataReadyAndRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueDequeueIfDataReady(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueDequeueIfDataReadyAndRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueEnqueue(_:buffer:)/title",
          "value": "CMBufferQueueEnqueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueEnqueue(_:buffer:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueEnqueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1compare/title",
          "value": "compare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1compare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1getPresentationTimeStamp/title",
          "value": "getPresentationTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1getPresentationTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getPresentationTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1getDuration/title",
          "value": "getDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1getDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1getDecodeTimeStamp/title",
          "value": "getDecodeTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1getDecodeTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getDecodeTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmbuffergetbooleancallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmbuffergetbooleancallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
