{
  "abstract": [
    {
      "text": "A callback that invokes a function for every buffer in a queue and then resets the queue.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueResetWithCallback(_:callback:refcon:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMBufferQueueResetWithCallback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMBufferQueueResetWithCallback"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMBufferQueueRef",
        "text": "CMBufferQueue"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "callback"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMBufferRef",
        "text": "CMBuffer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "refcon"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMBufferQueueResetWithCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMBufferQueueResetWithCallback(_:callback:refcon:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMBufferQueueResetWithCallback"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMBufferQueueRef",
              "text": "CMBufferQueue"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "callback"
            },
            {
              "kind": "text",
              "text": ": ("
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMBufferRef",
              "text": "CMBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "refcon"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "code": "CMBufferQueue",
                  "type": "codeVoice"
                },
                {
                  "text": " being reset, that may contain multiple buffers.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "queue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Function to be called for each buffer.  The callback should not make other calls to the buffer queue.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "callback"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Reference constant to be passed to the callback function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "refcon"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. See ",
              "type": "text"
            },
            {
              "code": "Result Codes",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer": {
      "abstract": [
        {
          "text": "A reference to a buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue": {
      "abstract": [
        {
          "text": "A reference to a buffer queue instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCallForEachBuffer(_:callback:refcon:)": {
      "abstract": [
        {
          "text": "Calls a function for every buffer in a queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueCallForEachBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "callback"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "refcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCallForEachBuffer(_:callback:refcon:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueCallForEachBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueCallForEachBuffer(_:callback:refcon:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuecallforeachbuffer(_:callback:refcon:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeue(_:)": {
      "abstract": [
        {
          "text": "Dequeues a buffer from a queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueDequeue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeue(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueDequeueAndRetain"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueDequeue(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuedequeue(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeueIfDataReady(_:)": {
      "abstract": [
        {
          "text": "Dequeues a buffer from a queue, if it’s ready.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueDequeueIfDataReady"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeueIfDataReady(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueDequeueIfDataReadyAndRetain"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueDequeueIfDataReady(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuedequeueifdataready(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueEnqueue(_:buffer:)": {
      "abstract": [
        {
          "text": "Enqueues a buffer onto a queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueEnqueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "buffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueEnqueue(_:buffer:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueEnqueue"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueEnqueue(_:buffer:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueueenqueue(_:buffer:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueMarkEndOfData(_:)": {
      "abstract": [
        {
          "text": "Sets a marker to indicate this queue doesn’t allow enqueuing new buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueMarkEndOfData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueMarkEndOfData(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueMarkEndOfData"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueMarkEndOfData(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuemarkendofdata(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueRemoveTrigger(_:triggerToken:)": {
      "abstract": [
        {
          "text": "Removes a previously installed trigger from a buffer queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueRemoveTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "triggerToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerToken",
          "text": "CMBufferQueueTriggerToken"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueRemoveTrigger(_:triggerToken:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueRemoveTrigger"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueRemoveTrigger(_:triggerToken:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueueremovetrigger(_:triggertoken:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueReset(_:)": {
      "abstract": [
        {
          "text": "Resets a buffer queue, which allows it to enqueue new buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueReset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueReset(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueReset"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueReset(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuereset(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueResetWithCallback(_:callback:refcon:)": {
      "abstract": [
        {
          "text": "A callback that invokes a function for every buffer in a queue and then resets the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueResetWithCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "callback"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "refcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueResetWithCallback(_:callback:refcon:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueResetWithCallback"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueResetWithCallback(_:callback:refcon:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueueresetwithcallback(_:callback:refcon:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-a-Queue",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueEnqueue(_:buffer:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCallForEachBuffer(_:callback:refcon:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeue(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeueIfDataReady(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueMarkEndOfData(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueReset(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueRemoveTrigger(_:triggerToken:)"
      ],
      "title": "Managing a Queue"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMBufferQueueResetWithCallback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueResetWithCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-a-Queue",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueEnqueue(_:buffer:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCallForEachBuffer(_:callback:refcon:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeue(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeueIfDataReady(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueMarkEndOfData(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueReset(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueRemoveTrigger(_:triggerToken:)"
              ],
              "title": "Managing a Queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMBufferQueueResetWithCallback"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMBufferQueueRef",
                    "text": "CMBufferQueueRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "queue"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*Fv(#*1v#*v)",
                    "text": "void (*)(const void *, void *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "callback"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "refcon"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "",
                        "type": "text"
                      },
                      {
                        "code": "CMBufferQueue",
                        "type": "codeVoice"
                      },
                      {
                        "text": " being reset, that may contain multiple buffers.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "queue"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Function to be called for each buffer.  The callback should not make other calls to the buffer queue.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "callback"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Reference constant to be passed to the callback function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "refcon"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A result code. See ",
                    "type": "text"
                  },
                  {
                    "code": "Result Codes",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/title",
          "value": "CMBufferQueueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueDequeueIfDataReady(_:)/title",
          "value": "CMBufferQueueDequeueIfDataReadyAndRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueDequeueIfDataReady(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueDequeueIfDataReadyAndRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueReset(_:)/title",
          "value": "CMBufferQueueReset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueReset(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueReset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueResetWithCallback(_:callback:refcon:)/title",
          "value": "CMBufferQueueResetWithCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueResetWithCallback(_:callback:refcon:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueResetWithCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueEnqueue(_:buffer:)/title",
          "value": "CMBufferQueueEnqueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueEnqueue(_:buffer:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueEnqueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueDequeue(_:)/title",
          "value": "CMBufferQueueDequeueAndRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueDequeue(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueDequeueAndRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueCallForEachBuffer(_:callback:refcon:)/title",
          "value": "CMBufferQueueCallForEachBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueCallForEachBuffer(_:callback:refcon:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueCallForEachBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueMarkEndOfData(_:)/title",
          "value": "CMBufferQueueMarkEndOfData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueMarkEndOfData(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueMarkEndOfData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/title",
          "value": "CMBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueRemoveTrigger(_:triggerToken:)/title",
          "value": "CMBufferQueueRemoveTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueRemoveTrigger(_:triggerToken:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRemoveTrigger"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmbufferqueueresetwithcallback(_:callback:refcon:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmbufferqueueresetwithcallback(_:callback:refcon:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
