{
  "abstract": [
    {
      "text": "A validation handler for the queue to call before enqueuing buffers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueSetValidationHandler(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMBufferQueueSetValidationHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMBufferQueueSetValidationHandler"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMBufferQueueRef",
        "text": "CMBufferQueue"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMBufferValidationHandler",
        "text": "CMBufferValidationHandler"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMBufferQueueSetValidationHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMBufferQueueSetValidationHandler(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMBufferQueueSetValidationHandler"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMBufferQueueRef",
              "text": "CMBufferQueue"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferValidationHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMBufferValidationHandler",
              "text": "CMBufferValidationHandler"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue": {
      "abstract": [
        {
          "text": "A reference to a buffer queue instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueSetValidationCallback(_:callback:refcon:)": {
      "abstract": [
        {
          "text": "A validation callback for the queue to call before enqueuing buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueSetValidationCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "callback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferValidationCallback",
          "text": "CMBufferValidationCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "refcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueSetValidationCallback(_:callback:refcon:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueSetValidationCallback"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueSetValidationCallback(_:callback:refcon:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuesetvalidationcallback(_:callback:refcon:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueSetValidationHandler(_:_:)": {
      "abstract": [
        {
          "text": "A validation handler for the queue to call before enqueuing buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueSetValidationHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferValidationHandler",
          "text": "CMBufferValidationHandler"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueSetValidationHandler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueSetValidationHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueSetValidationHandler(_:_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuesetvalidationhandler(_:_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferValidationCallback": {
      "abstract": [
        {
          "text": "A type alias for a callback that tests whether a buffer is in a valid state to add to a queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferValidationCallback"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferValidationCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferValidationCallback"
        }
      ],
      "role": "symbol",
      "title": "CMBufferValidationCallback",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffervalidationcallback"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferValidationHandler": {
      "abstract": [
        {
          "text": "A type alias for a handler that tests whether a buffer is in a valid state to add to a queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferValidationHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferValidationHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferValidationHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferValidationHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffervalidationhandler"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Validating-a-Queue",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferValidationHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueSetValidationCallback(_:callback:refcon:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferValidationCallback"
      ],
      "title": "Validating a Queue"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMBufferQueueSetValidationHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueSetValidationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Validating-a-Queue",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferValidationHandler",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueSetValidationCallback(_:callback:refcon:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferValidationCallback"
              ],
              "title": "Validating a Queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMBufferQueueSetValidationHandler"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMBufferQueueRef",
                    "text": "CMBufferQueueRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "queue"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferValidationHandler",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMBufferValidationHandler",
                    "text": "CMBufferValidationHandler"
                  },
                  {
                    "kind": "internalParam",
                    "text": "handler"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueSetValidationHandler(_:_:)/title",
          "value": "CMBufferQueueSetValidationHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueSetValidationHandler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueSetValidationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/title",
          "value": "CMBufferQueueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferValidationHandler/title",
          "value": "CMBufferValidationHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferValidationHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferValidationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferValidationHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferValidationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueSetValidationCallback(_:callback:refcon:)/title",
          "value": "CMBufferQueueSetValidationCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueSetValidationCallback(_:callback:refcon:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueSetValidationCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferValidationCallback/title",
          "value": "CMBufferValidationCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferValidationCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferValidationCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferValidationCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferValidationCallback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmbufferqueuesetvalidationhandler(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmbufferqueuesetvalidationhandler(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
