{
  "abstract": [
    {
      "text": "A structure that stores the handlers that perform buffer operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@CMBufferHandlers",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMBufferHandlers"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMBufferHandlers"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CMBufferHandlers"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "CMBufferHandlers"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks": {
      "abstract": [
        {
          "text": "A structure that stores the callbacks that perform buffer operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferCallbacks"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferCallbacks"
        }
      ],
      "role": "symbol",
      "title": "CMBufferCallbacks",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercallbacks"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferCompareHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferCompareHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferCompareHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercomparehandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetBooleanHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetBooleanHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetBooleanHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergetbooleanhandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetSizeHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetSizeHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetSizeHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergetsizehandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetTimeHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetTimeHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetTimeHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergettimehandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers": {
      "abstract": [
        {
          "text": "A structure that stores the handlers that perform buffer operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMBufferHandlers"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferHandlers",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferhandlers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/compare": {
      "abstract": [
        {
          "text": "A handler callback the queue uses to perform an insertion sort of the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "compare"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/compare",
      "kind": "symbol",
      "role": "symbol",
      "title": "compare",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferhandlers/compare"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/dataBecameReadyNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dataBecameReadyNotification"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/dataBecameReadyNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataBecameReadyNotification",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferhandlers/databecamereadynotification"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getDecodeTimeStamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "getDecodeTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getDecodeTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "getDecodeTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferhandlers/getdecodetimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getDuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "getDuration"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getDuration",
      "kind": "symbol",
      "role": "symbol",
      "title": "getDuration",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferhandlers/getduration"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getPresentationTimeStamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "getPresentationTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getPresentationTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "getPresentationTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferhandlers/getpresentationtimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "getSize"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "getSize",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferhandlers/getsize"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/isDataReady": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "isDataReady"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/isDataReady",
      "kind": "symbol",
      "role": "symbol",
      "title": "isDataReady",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferhandlers/isdataready"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/version": {
      "abstract": [
        {
          "text": "The version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/version",
      "kind": "symbol",
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferhandlers/version"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCreate(allocator:capacity:callbacks:queueOut:)": {
      "abstract": [
        {
          "text": "Creates a buffer queue with callbacks to inspect buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "capacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMItemCount",
          "text": "CMItemCount"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "callbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMBufferCallbacks",
          "text": "CMBufferCallbacks"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "queueOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCreate(allocator:capacity:callbacks:queueOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueCreate"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueCreate(allocator:capacity:callbacks:queueOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuecreate(allocator:capacity:callbacks:queueout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCreateWithHandlers(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a buffer queue with handlers to inspect buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueCreateWithHandlers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMItemCount",
          "text": "CMItemCount"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCreateWithHandlers(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueCreateWithHandlers"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueCreateWithHandlers(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuecreatewithhandlers(_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Queue",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCreateWithHandlers(_:_:_:_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCreate(allocator:capacity:callbacks:queueOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCallbacks"
      ],
      "title": "Creating a Queue"
    }
  ],
  "topicSections": [
    {
      "anchor": "Buffer-Handlers",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/compare",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getDuration",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getDecodeTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getPresentationTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/getSize",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/isDataReady",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/dataBecameReadyNotification",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferHandlers/version"
      ],
      "title": "Buffer Handlers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanHandler/title",
          "value": "CMBufferGetBooleanHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetBooleanHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetBooleanHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeHandler/title",
          "value": "CMBufferGetTimeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetTimeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetTimeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueCreateWithHandlers(_:_:_:_:)/title",
          "value": "CMBufferQueueCreateWithHandlers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueCreateWithHandlers(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueCreateWithHandlers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueCreate(allocator:capacity:callbacks:queueOut:)/title",
          "value": "CMBufferQueueCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueCreate(allocator:capacity:callbacks:queueOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks/title",
          "value": "CMBufferCallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeHandler/title",
          "value": "CMBufferGetSizeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetSizeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetSizeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareHandler/title",
          "value": "CMBufferCompareHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCompareHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCompareHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmbufferhandlers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
