{
  "abstract": [
    {
      "text": "A reference clock you use to synchronize applications and devices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-api"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMClock APIs"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "The CMSync",
              "type": "codeVoice"
            },
            {
              "text": " API provides a reference clock that you use to synchronize applications and devices. This API also provides functions to monitor relative drift between ",
              "type": "text"
            },
            {
              "code": "CMClocks",
              "type": "codeVoice"
            },
            {
              "text": " and functions that are associated with timer services.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClock": {
      "abstract": [
        {
          "text": "An object that represents a source of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClock"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClock"
        }
      ],
      "role": "symbol",
      "title": "CMClock",
      "type": "topic",
      "url": "/documentation/coremedia/cmclock"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClockConvertHostTimeToSystemUnits(_:)": {
      "abstract": [
        {
          "text": "Converts a host time from a core media time structure to the host time’s native units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClockConvertHostTimeToSystemUnits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClockConvertHostTimeToSystemUnits(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClockConvertHostTimeToSystemUnits"
        }
      ],
      "role": "symbol",
      "title": "CMClockConvertHostTimeToSystemUnits(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmclockconverthosttimetosystemunits(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetAnchorTime(_:clockTimeOut:referenceClockTimeOut:)": {
      "abstract": [
        {
          "text": "Returns the current time from a clock and the matching time from the clock’s reference clock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClockGetAnchorTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clockTimeOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "referenceClockTimeOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetAnchorTime(_:clockTimeOut:referenceClockTimeOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClockGetAnchorTime"
        }
      ],
      "role": "symbol",
      "title": "CMClockGetAnchorTime(_:clockTimeOut:referenceClockTimeOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmclockgetanchortime(_:clocktimeout:referenceclocktimeout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetHostTimeClock()": {
      "abstract": [
        {
          "text": "Returns a reference to the singleton clock that reflects the host time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClockGetHostTimeClock"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetHostTimeClock()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClockGetHostTimeClock"
        }
      ],
      "role": "symbol",
      "title": "CMClockGetHostTimeClock()",
      "type": "topic",
      "url": "/documentation/coremedia/cmclockgethosttimeclock()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetTime(_:)": {
      "abstract": [
        {
          "text": "Returns the current time from a clock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClockGetTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetTime(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClockGetTime"
        }
      ],
      "role": "symbol",
      "title": "CMClockGetTime(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmclockgettime(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the core foundation type identifier of a clock type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClockGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClockGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CMClockGetTypeID()",
      "type": "topic",
      "url": "/documentation/coremedia/cmclockgettypeid()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClockInvalidate(_:)": {
      "abstract": [
        {
          "text": "Stops the clock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClockInvalidate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClockInvalidate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClockInvalidate"
        }
      ],
      "role": "symbol",
      "title": "CMClockInvalidate(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmclockinvalidate(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClockMakeHostTimeFromSystemUnits(_:)": {
      "abstract": [
        {
          "text": "Converts a host time from native units to a core media time structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClockMakeHostTimeFromSystemUnits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClockMakeHostTimeFromSystemUnits(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClockMakeHostTimeFromSystemUnits"
        }
      ],
      "role": "symbol",
      "title": "CMClockMakeHostTimeFromSystemUnits(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmclockmakehosttimefromsystemunits(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClockMightDrift(_:otherClock:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether it’s possible for two clocks to drift relative to each other.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClockMightDrift"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "otherClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClockMightDrift(_:otherClock:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClockMightDrift"
        }
      ],
      "role": "symbol",
      "title": "CMClockMightDrift(_:otherClock:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmclockmightdrift(_:otherclock:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClockOrTimebase": {
      "abstract": [
        {
          "text": "A type you use in argument lists and function results to indicate that you can pass either a clock or timebase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClockOrTimebase"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClockOrTimebase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClockOrTimebase"
        }
      ],
      "role": "symbol",
      "title": "CMClockOrTimebase",
      "type": "topic",
      "url": "/documentation/coremedia/cmclockortimebase"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncConvertTime(_:from:to:)": {
      "abstract": [
        {
          "text": "Converts a time from one timebase or clock to another timebase or clock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSyncConvertTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncConvertTime(_:from:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSyncConvertTime"
        }
      ],
      "role": "symbol",
      "title": "CMSyncConvertTime(_:from:to:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncconverttime(_:from:to:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetRelativeRate(_:relativeTo:)": {
      "abstract": [
        {
          "text": "Returns the relative rate of one timebase or clock relative to another timebase or clock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSyncGetRelativeRate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetRelativeRate(_:relativeTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSyncGetRelativeRate"
        }
      ],
      "role": "symbol",
      "title": "CMSyncGetRelativeRate(_:relativeTo:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncgetrelativerate(_:relativeto:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetRelativeRateAndAnchorTime(_:relativeTo:relativeRateOut:anchorTimeOut:relativeToAnchorTimeOut:)": {
      "abstract": [
        {
          "text": "Returns the relative rate of one timebase or clock relative to another timebase or clock and the times of each timebase or clock at which the relative rate went into effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSyncGetRelativeRateAndAnchorTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relativeRateOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "anchorTimeOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "relativeToAnchorTimeOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetRelativeRateAndAnchorTime(_:relativeTo:relativeRateOut:anchorTimeOut:relativeToAnchorTimeOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSyncGetRelativeRateAndAnchorTime"
        }
      ],
      "role": "symbol",
      "title": "CMSyncGetRelativeRateAndAnchorTime(_:relativeTo:relativeRateOut:anchorTimeOut:relativeToAnchorTimeOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncgetrelativerateandanchortime(_:relativeto:relativerateout:anchortimeout:relativetoanchortimeout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetTime(_:)": {
      "abstract": [
        {
          "text": "Returns the time from a clock or timebase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSyncGetTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetTime(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSyncGetTime"
        }
      ],
      "role": "symbol",
      "title": "CMSyncGetTime(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncgettime(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncMightDrift(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether it’s possible for one timebase or clock to drift relative to the other.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSyncMightDrift"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockOrTimebaseRef",
          "text": "CMClockOrTimebase"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncMightDrift(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSyncMightDrift"
        }
      ],
      "role": "symbol",
      "title": "CMSyncMightDrift(_:_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncmightdrift(_:_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmaudioclock-api": {
      "abstract": [
        {
          "text": "A specialized reference clock that synchronizes with audio sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmaudioclock-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMAudioClock APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudioclock-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes": {
      "abstract": [
        {
          "text": "Constants that represent the errors in Core Media clock operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMClock Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/cmclock-error-codes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes": {
      "abstract": [
        {
          "text": "Constants that represent error codes Core Media sync operations return.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSync error codes",
      "type": "topic",
      "url": "/documentation/coremedia/cmsync-error-codes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-api": {
      "abstract": [
        {
          "text": "A model of a timeline under application control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTimebase APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-errors": {
      "abstract": [
        {
          "text": "Constants that represent errors in Core Media timebase operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTimebase Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/timebase-notifications": {
      "abstract": [
        {
          "text": "Keys that represent timebase notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/timebase-notifications",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Timebase Notifications",
      "type": "topic",
      "url": "/documentation/coremedia/timebase-notifications"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-Synchronization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmaudioclock-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-api"
      ],
      "title": "Media Synchronization"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-Host-Clock",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetHostTimeClock()"
      ],
      "title": "Accessing the Host Clock"
    },
    {
      "anchor": "Stopping-the-Clock",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClockInvalidate(_:)"
      ],
      "title": "Stopping the Clock"
    },
    {
      "anchor": "Accessing-and-Converting-Time",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetTime(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetAnchorTime(_:clockTimeOut:referenceClockTimeOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClockConvertHostTimeToSystemUnits(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClockMakeHostTimeFromSystemUnits(_:)"
      ],
      "title": "Accessing and Converting Time"
    },
    {
      "anchor": "Getting-and-Syncing-Time",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetTime(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetRelativeRate(_:relativeTo:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetRelativeRateAndAnchorTime(_:relativeTo:relativeRateOut:anchorTimeOut:relativeToAnchorTimeOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncConvertTime(_:from:to:)"
      ],
      "title": "Getting and Syncing Time"
    },
    {
      "anchor": "Determining-Clock-Drift",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClockMightDrift(_:otherClock:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncMightDrift(_:_:)"
      ],
      "title": "Determining Clock Drift"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClock",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClockOrTimebase",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetTypeID()"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes",
        "doc://com.apple.coremedia/documentation/CoreMedia/timebase-notifications"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-Host-Clock",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetHostTimeClock()"
              ],
              "title": "Accessing the Host Clock"
            },
            {
              "anchor": "Stopping-the-Clock",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClockInvalidate(_:)"
              ],
              "title": "Stopping the Clock"
            },
            {
              "anchor": "Accessing-and-Converting-Time",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetTime(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetAnchorTime(_:clockTimeOut:referenceClockTimeOut:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClockConvertHostTimeToSystemUnits(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClockMakeHostTimeFromSystemUnits(_:)"
              ],
              "title": "Accessing and Converting Time"
            },
            {
              "anchor": "Getting-and-Syncing-Time",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetTime(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetRelativeRate(_:relativeTo:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncGetRelativeRateAndAnchorTime(_:relativeTo:relativeRateOut:anchorTimeOut:relativeToAnchorTimeOut:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncConvertTime(_:from:to:)"
              ],
              "title": "Getting and Syncing Time"
            },
            {
              "anchor": "Determining-Clock-Drift",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClockMightDrift(_:otherClock:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncMightDrift(_:_:)"
              ],
              "title": "Determining Clock Drift"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClock",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClockOrTimebase",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClockGetTypeID()"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes",
                "doc://com.apple.coremedia/documentation/CoreMedia/timebase-notifications"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-Synchronization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmaudioclock-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-api"
              ],
              "title": "Media Synchronization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSyncConvertTime(_:from:to:)/title",
          "value": "CMSyncConvertTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSyncConvertTime(_:from:to:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSyncConvertTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockGetTime(_:)/title",
          "value": "CMClockGetTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockGetTime(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockGetTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSyncGetTime(_:)/title",
          "value": "CMSyncGetTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSyncGetTime(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSyncGetTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockGetHostTimeClock()/title",
          "value": "CMClockGetHostTimeClock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockGetHostTimeClock()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockGetHostTimeClock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClock/title",
          "value": "CMClockRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSyncGetRelativeRate(_:relativeTo:)/title",
          "value": "CMSyncGetRelativeRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSyncGetRelativeRate(_:relativeTo:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSyncGetRelativeRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockGetTypeID()/title",
          "value": "CMClockGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockGetAnchorTime(_:clockTimeOut:referenceClockTimeOut:)/title",
          "value": "CMClockGetAnchorTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockGetAnchorTime(_:clockTimeOut:referenceClockTimeOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockGetAnchorTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockMightDrift(_:otherClock:)/title",
          "value": "CMClockMightDrift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockMightDrift(_:otherClock:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockMightDrift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockConvertHostTimeToSystemUnits(_:)/title",
          "value": "CMClockConvertHostTimeToSystemUnits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockConvertHostTimeToSystemUnits(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockConvertHostTimeToSystemUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockMakeHostTimeFromSystemUnits(_:)/title",
          "value": "CMClockMakeHostTimeFromSystemUnits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockMakeHostTimeFromSystemUnits(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockMakeHostTimeFromSystemUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockOrTimebase/title",
          "value": "CMClockOrTimebaseRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockOrTimebase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockOrTimebaseRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockOrTimebase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockOrTimebaseRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSyncGetRelativeRateAndAnchorTime(_:relativeTo:relativeRateOut:anchorTimeOut:relativeToAnchorTimeOut:)/title",
          "value": "CMSyncGetRelativeRateAndAnchorTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSyncGetRelativeRateAndAnchorTime(_:relativeTo:relativeRateOut:anchorTimeOut:relativeToAnchorTimeOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSyncGetRelativeRateAndAnchorTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSyncMightDrift(_:_:)/title",
          "value": "CMSyncMightDrift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSyncMightDrift(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSyncMightDrift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockInvalidate(_:)/title",
          "value": "CMClockInvalidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClockInvalidate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockInvalidate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmclock-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmclock-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
