{
  "abstract": [
    {
      "text": "An object that describes a media format descriptor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMFormatDescriptionRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMFormatDescription"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMFormatDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CMFormatDescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMFormatDescription"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "CMFormatDescription",
              "type": "codeVoice"
            },
            {
              "text": " object is an object that describes media types (audio, video, muxed, and so on).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with audio format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMAudioFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudioformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with closed caption format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClosedCaptionFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClosedCaptionFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMClosedCaptionFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmclosedcaptionformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription": {
      "abstract": [
        {
          "text": "An object that describes a media format descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/==(_:_:)": {
      "abstract": [
        {
          "text": "Equality is derived from",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "=="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/==(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "==(_:_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/==(_:_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask": {
      "abstract": [
        {
          "text": "A type that describes format description equality masks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EqualityMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EqualityMask"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription.EqualityMask",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/equalitymask"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Error": {
      "abstract": [
        {
          "text": "A type that describes format description errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription.Error",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/error"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct": {
      "abstract": [
        {
          "text": "A type that describes format description extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Extensions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Extensions"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription.Extensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/extensions-swift.struct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/MediaSubType-swift.struct": {
      "abstract": [
        {
          "text": "A type that describes format description media subtypes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MediaSubType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/MediaSubType-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MediaSubType"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription.MediaSubType",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/mediasubtype-swift.struct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/MediaType-swift.struct": {
      "abstract": [
        {
          "text": "A type that describes format description media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/MediaType-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MediaType"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription.MediaType",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/mediatype-swift.struct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/ParameterSetCollection": {
      "abstract": [
        {
          "text": "A type that describes format description parameter sets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ParameterSetCollection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/ParameterSetCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ParameterSetCollection"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription.ParameterSetCollection",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/parametersetcollection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/TimeCode": {
      "abstract": [
        {
          "text": "A type that describes format description time codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TimeCode"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/TimeCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TimeCode"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription.TimeCode",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/timecode"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioChannelLayout": {
      "abstract": [
        {
          "text": "The audio channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreAudio07ManagedB13ChannelLayoutV",
          "text": "ManagedAudioChannelLayout"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioChannelLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "audioChannelLayout",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/audiochannellayout"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioFormatList": {
      "abstract": [
        {
          "text": "The audio format list items that describe the audio formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioFormatList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioFormatListItem",
          "text": "AudioFormatListItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioFormatList",
      "kind": "symbol",
      "role": "symbol",
      "title": "audioFormatList",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/audioformatlist"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioStreamBasicDescription": {
      "abstract": [
        {
          "text": "The audio stream description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioStreamBasicDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
          "text": "AudioStreamBasicDescription"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioStreamBasicDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "audioStreamBasicDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/audiostreambasicdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/cleanAperture(originIsAtTopLeft:)": {
      "abstract": [
        {
          "text": "Returns the clean aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cleanAperture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "originIsAtTopLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/cleanAperture(originIsAtTopLeft:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "cleanAperture(originIsAtTopLeft:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/cleanaperture(originisattopleft:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/defaultStyle()": {
      "abstract": [
        {
          "text": "Returns the default text style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultStyle"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> (localFontID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", bold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", italic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", underline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", fontSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", colorComponents"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/defaultStyle()",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultStyle()",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/defaultstyle()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/defaultTextBox(originIsAtTopLeft:heightOfTextTrack:)": {
      "abstract": [
        {
          "text": "Returns the default text box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultTextBox"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "originIsAtTopLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "heightOfTextTrack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/defaultTextBox(originIsAtTopLeft:heightOfTextTrack:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultTextBox(originIsAtTopLeft:heightOfTextTrack:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/defaulttextbox(originisattopleft:heightoftexttrack:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/dimensions": {
      "abstract": [
        {
          "text": "The encoded pixels not including the pixel aspect ratio or clean aperture tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/dimensions",
      "kind": "symbol",
      "role": "symbol",
      "title": "dimensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/dimensions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/displayFlags()": {
      "abstract": [
        {
          "text": "Returns the display mode flags for the text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayFlags"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
          "text": "Extensions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV16TextDisplayFlagsV",
          "text": "TextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/displayFlags()",
      "kind": "symbol",
      "role": "symbol",
      "title": "displayFlags()",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/displayflags()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/equalTo(_:equalityMask:)": {
      "abstract": [
        {
          "text": "Evaluates equality for the parts of two audio format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "equalTo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAudioFormatDescriptionRef",
          "text": "CMAudioFormatDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "equalityMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE12EqualityMaskV",
          "text": "EqualityMask"
        },
        {
          "kind": "text",
          "text": ") -> ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", equalityMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE12EqualityMaskV",
          "text": "EqualityMask"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/equalTo(_:equalityMask:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "equalTo(_:equalityMask:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/equalto(_:equalitymask:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/equalTo(_:extensionKeysToIgnore:sampleDescriptionExtensionAtomKeysToIgnore:)": {
      "abstract": [
        {
          "text": "Evaluates equality for the parts of two audio format descriptions, ignoring the extensions you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "equalTo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "extensionKeysToIgnore"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
          "text": "Extensions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV3KeyV",
          "text": "Key"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "sampleDescriptionExtensionAtomKeysToIgnore"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/equalTo(_:extensionKeysToIgnore:sampleDescriptionExtensionAtomKeysToIgnore:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "equalTo(_:extensionKeysToIgnore:sampleDescriptionExtensionAtomKeysToIgnore:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/equalto(_:extensionkeystoignore:sampledescriptionextensionatomkeystoignore:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/extensionKeysCommonWithImageBuffers": {
      "abstract": [
        {
          "text": "A constant that represents keys you use with video format description extensions and image buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionKeysCommonWithImageBuffers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
          "text": "Extensions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV3KeyV",
          "text": "Key"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/extensionKeysCommonWithImageBuffers",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensionKeysCommonWithImageBuffers",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/extensionkeyscommonwithimagebuffers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/extensions-swift.property": {
      "abstract": [
        {
          "text": "A dictionary that contains all of the extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
          "text": "Extensions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/extensions-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/extensions-swift.property"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/fontName(localFontID:)": {
      "abstract": [
        {
          "text": "Returns the font name for the local font identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localFontID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/fontName(localFontID:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "fontName(localFontID:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/fontname(localfontid:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameDuration": {
      "abstract": [
        {
          "text": "The duration of each frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameDuration",
      "kind": "symbol",
      "role": "symbol",
      "title": "frameDuration",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/frameduration"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameQuanta": {
      "abstract": [
        {
          "text": "The frames per second for the time code, or the frame per tick for counter mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameQuanta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameQuanta",
      "kind": "symbol",
      "role": "symbol",
      "title": "frameQuanta",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/framequanta"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/identifiers": {
      "abstract": [
        {
          "text": "An array of metadata identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/identifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "identifiers",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/identifiers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/justification()": {
      "abstract": [
        {
          "text": "Returns the horizontal and vertical justification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "justification"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> (horizontal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
          "text": "Extensions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV17TextJustificationV",
          "text": "TextJustification"
        },
        {
          "kind": "text",
          "text": ", vertical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
          "text": "Extensions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV17TextJustificationV",
          "text": "TextJustification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/justification()",
      "kind": "symbol",
      "role": "symbol",
      "title": "justification()",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/justification()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/keyWithLocalID(_:)": {
      "abstract": [
        {
          "text": "Returns the metadata for the local identifier you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyWithLocalID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFPropertyListRef",
          "text": "CFPropertyList"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/keyWithLocalID(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "keyWithLocalID(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/keywithlocalid(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/magicCookie": {
      "abstract": [
        {
          "text": "A copy of the magic cookie, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/magicCookie",
      "kind": "symbol",
      "role": "symbol",
      "title": "magicCookie",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/magiccookie"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/matchesImageBuffer(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the format description matches an image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchesImageBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/matchesImageBuffer(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "matchesImageBuffer(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/matchesimagebuffer(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/matchesTaggedBufferGroup(_:)": {
      "abstract": [
        {
          "text": "Whether the format description matches a set of tagged buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchesTaggedBufferGroup"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia14CMTaggedBufferV",
          "text": "CMTaggedBuffer"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/matchesTaggedBufferGroup(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "matchesTaggedBufferGroup(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/matchestaggedbuffergroup(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaSubType-swift.property": {
      "abstract": [
        {
          "text": "The media subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaSubType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE0E7SubTypeV",
          "text": "MediaSubType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaSubType-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "mediaSubType",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/mediasubtype-swift.property"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaType-swift.property": {
      "abstract": [
        {
          "text": "The media type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE0E4TypeV",
          "text": "MediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaType-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "mediaType",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/mediatype-swift.property"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mostCompatibleFormat": {
      "abstract": [
        {
          "text": "The most compatible audio format list item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mostCompatibleFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioFormatListItem",
          "text": "AudioFormatListItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mostCompatibleFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "mostCompatibleFormat",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/mostcompatibleformat"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/nalUnitHeaderLength": {
      "abstract": [
        {
          "text": "The size, in bytes, of the unit length field in an AVC or HEVC video sample or parameter set sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nalUnitHeaderLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/nalUnitHeaderLength",
      "kind": "symbol",
      "role": "symbol",
      "title": "nalUnitHeaderLength",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/nalunitheaderlength"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/parameterSets": {
      "abstract": [
        {
          "text": "The parameter sets that an H.264 or HEVC format contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameterSets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE22ParameterSetCollectionV",
          "text": "ParameterSetCollection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/parameterSets",
      "kind": "symbol",
      "role": "symbol",
      "title": "parameterSets",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/parametersets"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/presentationDimensions(usePixelAspectRatio:useCleanAperture:)": {
      "abstract": [
        {
          "text": "Returns the dimensions to take the pixel aspect ratio or clean aperture into account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationDimensions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "usePixelAspectRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "useCleanAperture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/presentationDimensions(usePixelAspectRatio:useCleanAperture:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "presentationDimensions(usePixelAspectRatio:useCleanAperture:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/presentationdimensions(usepixelaspectratio:usecleanaperture:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/richestDecodableFormat": {
      "abstract": [
        {
          "text": "The audio format list item the system validates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "richestDecodableFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioFormatListItem",
          "text": "AudioFormatListItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/richestDecodableFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "richestDecodableFormat",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/richestdecodableformat"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/tagCollections": {
      "abstract": [
        {
          "text": "The tag collections associated with this media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tagCollections"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC",
          "text": "CMTag"
        },
        {
          "kind": "text",
          "text": "]]?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/tagCollections",
      "kind": "symbol",
      "role": "symbol",
      "title": "tagCollections",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/tagcollections"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/timeCodeFlags": {
      "abstract": [
        {
          "text": "The flags for the available time codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeCodeFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE8TimeCodeV",
          "text": "TimeCode"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE8TimeCodeV4FlagV",
          "text": "Flag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/timeCodeFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeCodeFlags",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/timecodeflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/typeID": {
      "abstract": [
        {
          "text": "A type identifier that corresponds to a description object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/typeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "typeID",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/typeid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/withMagicCookie(_:)": {
      "abstract": [
        {
          "text": "Returns the magic cookie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withMagicCookie"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SW",
          "text": "UnsafeRawBufferPointer"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/withMagicCookie(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "withMagicCookie(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/withmagiccookie(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with metadata format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadataformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with muxed format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMuxedFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMuxedFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMMuxedFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmmuxedformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with text format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMTextFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with time code format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeCodeFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeCodeFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMTimeCodeFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimecodeformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with video format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMVideoFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideoformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionError_AllocationFailed": {
      "abstract": [
        {
          "text": "An error that indicates when an allocation fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionError_AllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionError_AllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionError_AllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionError_AllocationFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionerror_allocationfailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionError_InvalidParameter": {
      "abstract": [
        {
          "text": "An error that indicates that the function recieves an empty value for a parameter it requires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionError_InvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionError_InvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionError_InvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionError_InvalidParameter",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionerror_invalidparameter"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionError_ValueNotAvailable": {
      "abstract": [
        {
          "text": "An error that indicates the format description doesnt contain the value you request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionError_ValueNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionError_ValueNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionError_ValueNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionError_ValueNotAvailable",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionerror_valuenotavailable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-Description-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoFormatDescription"
      ],
      "title": "Format Description Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-Format-Descriptions",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioFormatList",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioStreamBasicDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioChannelLayout",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/dimensions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/extensions-swift.property",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameDuration",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameQuanta",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/identifiers",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/magicCookie",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaSubType-swift.property",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaType-swift.property",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mostCompatibleFormat",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/nalUnitHeaderLength",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/parameterSets",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/richestDecodableFormat",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/timeCodeFlags",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/tagCollections",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/matchesTaggedBufferGroup(_:)"
      ],
      "title": "Inspecting Format Descriptions"
    },
    {
      "anchor": "Working-with-Audio-Descriptions",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/withMagicCookie(_:)"
      ],
      "title": "Working with Audio Descriptions"
    },
    {
      "anchor": "Working-with-Video-Descriptions",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/cleanAperture(originIsAtTopLeft:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/matchesImageBuffer(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/presentationDimensions(usePixelAspectRatio:useCleanAperture:)"
      ],
      "title": "Working with Video Descriptions"
    },
    {
      "anchor": "Working-with-Metadata-Descriptions",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/keyWithLocalID(_:)"
      ],
      "title": "Working with Metadata Descriptions"
    },
    {
      "anchor": "Working-with-Text-Descriptions",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/defaultStyle()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/defaultTextBox(originIsAtTopLeft:heightOfTextTrack:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/displayFlags()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/fontName(localFontID:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/justification()"
      ],
      "title": "Working with Text Descriptions"
    },
    {
      "anchor": "Comparing-Format-Descriptions",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/==(_:_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/equalTo(_:equalityMask:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/equalTo(_:extensionKeysToIgnore:sampleDescriptionExtensionAtomKeysToIgnore:)"
      ],
      "title": "Comparing Format Descriptions"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Error"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/extensionKeysCommonWithImageBuffers",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/typeID",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/MediaType-swift.struct",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/MediaSubType-swift.struct",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/TimeCode",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/EqualityMask",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/Extensions-swift.struct",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/ParameterSetCollection"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionError_InvalidParameter",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionError_AllocationFailed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionError_ValueNotAvailable"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-Description-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoFormatDescription"
              ],
              "title": "Format Description Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@opaqueCMFormatDescription",
                    "text": "opaqueCMFormatDescription"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMFormatDescriptionRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedFormatDescription/title",
          "value": "CMMuxedFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMuxedFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMuxedFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatDescription/title",
          "value": "CMMetadataFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatDescription/title",
          "value": "CMClosedCaptionFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClosedCaptionFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClosedCaptionFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatDescription/title",
          "value": "CMTimeCodeFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionError_ValueNotAvailable/title",
          "value": "kCMFormatDescriptionError_ValueNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionError_ValueNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionError_ValueNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoFormatDescription/title",
          "value": "CMVideoFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatDescription/title",
          "value": "CMTextFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionError_InvalidParameter/title",
          "value": "kCMFormatDescriptionError_InvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionError_InvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionError_InvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescription/title",
          "value": "CMAudioFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionError_AllocationFailed/title",
          "value": "kCMFormatDescriptionError_AllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionError_AllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionError_AllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/title",
          "value": "CMFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmformatdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmformatdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
