{
  "abstract": [
    {
      "text": "An object that optimizes memory allocation when working with large blocks of memory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmmemorypool-api"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMMemoryPool APIs"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An instance of ",
              "type": "text"
            },
            {
              "code": "CMMemoryPool",
              "type": "codeVoice"
            },
            {
              "text": " is a memory allocation service that holds a pool of recently deallocated memory. Its purpose is to speed up subsequent allocations of the same size. Use this API in cases where you need to repeatedly allocate large blocks of memory, such as a video encoding app that outputs compressed data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This object allocates memory by page. It doesn’t suballocate memory within pages, so don’t use it to allocate small blocks. For example, when calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function, you can use it as the ",
              "type": "text"
            },
            {
              "code": "blockAllocator",
              "type": "codeVoice"
            },
            {
              "text": " argument, but not as the ",
              "type": "text"
            },
            {
              "code": "structureAllocator",
              "type": "codeVoice"
            },
            {
              "text": " argument (use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfallocatordefault",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you no longer need to allocate memory from the pool, invalidate it by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolInvalidate(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function, which tells the pool to stop holding memory for reuse.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "A pool’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfallocator",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " can outlive the pool itself. After you invalidate a memory pool, its ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfallocator",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instance allocates and deallocates with no pooling behavior.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "A memory pool deallocates memory if it isn’t reused in ",
              "type": "text"
            },
            {
              "code": "0.5",
              "type": "codeVoice"
            },
            {
              "text": " seconds, so that short-term peak usage doesn’t cause persistent bloat. You can override this period by specifying a value for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMemoryPoolOption_AgeOutPeriod",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The system does this “aging out” during the pool’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521250-cfallocatorallocate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521299-cfallocatordeallocate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " calls.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)": {
      "abstract": [
        {
          "text": "Creates a block buffer that’s backed by a memory block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBlockBufferCreateWithMemoryBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "memoryBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "blockLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blockAllocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "customBlockSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMBlockBufferCustomBlockSource",
          "text": "CMBlockBufferCustomBlockSource"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "offsetToData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dataLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferFlags",
          "text": "CMBlockBufferFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blockBufferOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBlockBufferCreateWithMemoryBlock"
        }
      ],
      "role": "symbol",
      "title": "CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffercreatewithmemoryblock(allocator:memoryblock:blocklength:blockallocator:customblocksource:offsettodata:datalength:flags:blockbufferout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPool": {
      "abstract": [
        {
          "text": "An instance that optimizes memory allocation when working with large blocks of memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMemoryPool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMemoryPool"
        }
      ],
      "role": "symbol",
      "title": "CMMemoryPool",
      "type": "topic",
      "url": "/documentation/coremedia/cmmemorypool"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolCreate(options:)": {
      "abstract": [
        {
          "text": "Creates a memory pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMemoryPoolCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMemoryPoolRef",
          "text": "CMMemoryPool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolCreate(options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMemoryPoolCreate"
        }
      ],
      "role": "symbol",
      "title": "CMMemoryPoolCreate(options:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmemorypoolcreate(options:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolFlush(_:)": {
      "abstract": [
        {
          "text": "Deallocates all memory the pool holds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMemoryPoolFlush"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMemoryPoolRef",
          "text": "CMMemoryPool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolFlush(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMemoryPoolFlush"
        }
      ],
      "role": "symbol",
      "title": "CMMemoryPoolFlush(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmemorypoolflush(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolGetAllocator(_:)": {
      "abstract": [
        {
          "text": "Returns the allocator for the memory pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMemoryPoolGetAllocator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMemoryPoolRef",
          "text": "CMMemoryPool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolGetAllocator(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMemoryPoolGetAllocator"
        }
      ],
      "role": "symbol",
      "title": "CMMemoryPoolGetAllocator(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmemorypoolgetallocator(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the type identifier of memory pool objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMemoryPoolGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMemoryPoolGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CMMemoryPoolGetTypeID()",
      "type": "topic",
      "url": "/documentation/coremedia/cmmemorypoolgettypeid()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolInvalidate(_:)": {
      "abstract": [
        {
          "text": "Invalidates the memory pool, which causes its allocator to stop recycling memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMemoryPoolInvalidate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMemoryPoolRef",
          "text": "CMMemoryPool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolInvalidate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMemoryPoolInvalidate"
        }
      ],
      "role": "symbol",
      "title": "CMMemoryPoolInvalidate(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmemorypoolinvalidate(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmbufferqueue-api": {
      "abstract": [
        {
          "text": "A queue of timed buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmbufferqueue-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMBufferQueue APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsimplequeue-api": {
      "abstract": [
        {
          "text": "A simple, lockless FIFO queue of elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsimplequeue-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSimpleQueue APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmsimplequeue-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMemoryPoolError_AllocationFailed": {
      "abstract": [
        {
          "text": "An error that indicates the system failed to allocate an internal data structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMemoryPoolError_AllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMemoryPoolError_AllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMemoryPoolError_AllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMMemoryPoolError_AllocationFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmemorypoolerror_allocationfailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMemoryPoolError_InvalidParameter": {
      "abstract": [
        {
          "text": "An error that indicates you called an API with an invalid parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMemoryPoolError_InvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMemoryPoolError_InvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMemoryPoolError_InvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "kCMMemoryPoolError_InvalidParameter",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmemorypoolerror_invalidparameter"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMemoryPoolOption_AgeOutPeriod": {
      "abstract": [
        {
          "text": "The period of time before the pool recycles its memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMemoryPoolOption_AgeOutPeriod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMemoryPoolOption_AgeOutPeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMemoryPoolOption_AgeOutPeriod"
        }
      ],
      "role": "symbol",
      "title": "kCMMemoryPoolOption_AgeOutPeriod",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmemorypooloption_ageoutperiod"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1521250-cfallocatorallocate": {
      "abstract": [
        {
          "text": "Allocates memory using the specified allocator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFAllocatorAllocate"
        },
        {
          "kind": "text",
          "text": "(CFAllocator!, CFIndex, CFOptionFlags) -> UnsafeMutableRawPointer!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521250-cfallocatorallocate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocatorAllocate(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1521250-cfallocatorallocate"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1521299-cfallocatordeallocate": {
      "abstract": [
        {
          "text": "Deallocates a block of memory with a given allocator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFAllocatorDeallocate"
        },
        {
          "kind": "text",
          "text": "(CFAllocator!, UnsafeMutableRawPointer!)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521299-cfallocatordeallocate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocatorDeallocate(_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1521299-cfallocatordeallocate"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfallocator": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfallocator",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfallocatordefault": {
      "abstract": [
        {
          "text": "This is a synonym for `NULL`. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFAllocatorDefault"
        },
        {
          "kind": "text",
          "text": ": CFAllocator!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfallocatordefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFAllocatorDefault",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfallocatordefault"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Queues",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsimplequeue-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmbufferqueue-api"
      ],
      "title": "Queues"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Memory-Pool",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolCreate(options:)"
      ],
      "title": "Creating a Memory Pool"
    },
    {
      "anchor": "Managing-a-Memory-Pool",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolGetAllocator(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolFlush(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolInvalidate(_:)"
      ],
      "title": "Managing a Memory Pool"
    },
    {
      "anchor": "Accessing-the-Type-Identifier",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolGetTypeID()"
      ],
      "title": "Accessing the Type Identifier"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPool"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMemoryPoolError_AllocationFailed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMemoryPoolError_InvalidParameter"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Memory-Pool",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolCreate(options:)"
              ],
              "title": "Creating a Memory Pool"
            },
            {
              "anchor": "Managing-a-Memory-Pool",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolGetAllocator(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolFlush(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolInvalidate(_:)"
              ],
              "title": "Managing a Memory Pool"
            },
            {
              "anchor": "Accessing-the-Type-Identifier",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPoolGetTypeID()"
              ],
              "title": "Accessing the Type Identifier"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMemoryPool"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMemoryPoolError_AllocationFailed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMemoryPoolError_InvalidParameter"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Queues",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmsimplequeue-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmbufferqueue-api"
              ],
              "title": "Queues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11521250-cfallocatorallocate/title",
          "value": "CFAllocatorAllocate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMemoryPoolError_InvalidParameter/title",
          "value": "kCMMemoryPoolError_InvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMemoryPoolError_InvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMemoryPoolError_InvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPool/title",
          "value": "CMMemoryPoolRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMemoryPoolRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPool/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMemoryPoolRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPoolInvalidate(_:)/title",
          "value": "CMMemoryPoolInvalidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPoolInvalidate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMemoryPoolInvalidate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11521299-cfallocatordeallocate/title",
          "value": "CFAllocatorDeallocate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPoolFlush(_:)/title",
          "value": "CMMemoryPoolFlush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPoolFlush(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMemoryPoolFlush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPoolGetTypeID()/title",
          "value": "CMMemoryPoolGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPoolGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMemoryPoolGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMemoryPoolError_AllocationFailed/title",
          "value": "kCMMemoryPoolError_AllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMemoryPoolError_AllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMemoryPoolError_AllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMemoryPoolOption_AgeOutPeriod/title",
          "value": "kCMMemoryPoolOption_AgeOutPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMemoryPoolOption_AgeOutPeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMemoryPoolOption_AgeOutPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)/title",
          "value": "CMBlockBufferCreateWithMemoryBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBlockBufferCreateWithMemoryBlock(allocator:memoryBlock:blockLength:blockAllocator:customBlockSource:offsetToData:dataLength:flags:blockBufferOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBlockBufferCreateWithMemoryBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPoolGetAllocator(_:)/title",
          "value": "CMMemoryPoolGetAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPoolGetAllocator(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMemoryPoolGetAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPoolCreate(options:)/title",
          "value": "CMMemoryPoolCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMemoryPoolCreate(options:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMemoryPoolCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfallocator/title",
          "value": "CFAllocatorRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmmemorypool-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmmemorypool-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
